#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: tMSSelection.run
#-----------------------------------------------------------------------------
# This script executes the program tMSSelection to test if new the
# measurement set selection is working.

# The script supplies the names of all test tables found in the system.
# It is meant to be run from assay, but can also be used standalone.
#
# $Id$
#-----------------------------------------------------------------------------

  if [ ${#AIPSPATH} = 0 ]
  then
     echo "UNTESTED: tMSSelection.run (AIPSPATH not defined)"
     exit 3
  fi
  IN='3C273XC1.fits'
  AIPSDEMO=`echo $AIPSPATH | awk '{printf("%s/data/demo",$1)}'`
  FITS=`echo $AIPSDEMO $IN | awk '{printf("%s/%s", $1,$2)}'`
  MS=`echo $IN | sed 's/.fits/_tmp.ms/'`
  echo $AIPSDEMO
  echo $FITS
  echo $MS

  if [ ! -e $FITS ]
  then
     echo "UNTESTED: tMSSelection.run ($FITS not found)"
     exit 3
  fi

  $casa_checktool ./tMSSelection fits=$FITS ms=$MS
