#!/bin/sh

# Update for all changes in Casacore release 2.0.

# Find the path used to start the script.
pgmpath=`dirname $0`
pgmpath=`cd $pgmpath > /dev/null 2>&1  &&  pwd`

$pgmpath/updateinclude $*
$pgmpath/updatenamespace $*
$pgmpath/updatepath $*
