#!/bin/sh

# Create a table with 5 columns containing earthmagnetics, directions, epochs
# and positions.
# The same positions are defined as WGS84 (llh) and ITRF (xyz).
# Define the measure keywords for them.
../../../tables/apps/taql "create table tEarthMagneticEngine_tmp.tab EM R8 [shape=[3], unit=['nT','nT','nT']], DIR R8 [shape=[2,2], unit=['deg','deg']], TIME R8 [unit='s'], POS1 R8 [shape=[3], unit=['deg','deg','m']], POS2 R8 [shape=[3], unit=['m','m','m']]"
../../../tables/apps/taql "alter table tEarthMagneticEngine_tmp.tab set keyword EM::MEASINFO=[type='earthmagnetic', Ref='ITRF'], DIR::MEASINFO=[type='direction', Ref='J2000'], TIME::MEASINFO=[type='epoch',Ref='UTC'], POS1::MEASINFO=[type='position',Ref='WGS84'], POS2::MEASINFO=[type='position',Ref='ITRF']"
../../../tables/apps/taql 'insert into tEarthMagneticEngine_tmp.tab (EM,DIR,TIME,POS1,POS2) values
 ([-4.22979e-09, -3.98632e-10, 2.63628e-09],
  [[185.425833deg, 31.799167deg], [0,0]],
  50217.625d,
  [6.60417, 52.8, 10],
  [3.83879e+06, 444447, 5.05713e+06]),
 ([-7.42905e-09, 6.00219e-10, 6.66701e-09],
  [[175.425833deg, 41.799167deg], [0,0]],
  50417.625d,
  [-60.60417, -32.8, 1000],
  [2.63452e+06, -4.67631e+06, -3.43588e+06]),
 ([-1.28774e-08, 5.90596e-09, 2.64441e-08],
  [[165.425833deg, 51.799167deg], [0,0]],
  50617.625d,
  [-6.60417, 32.8, 2000],
  [5.33258e+06, -617394, 3.43642e+06])'

$casa_checktool ./tEarthMagneticEngine
