#!/bin/sh

# Create a table with 3 columns containing epochs and positions.
# The same positions are defined as WGS84 (llh) and ITRF (xyz).
# Define the measure keywords for them.
../../../tables/apps/taql "create table tEpochEngine_tmp.tab TIME R8 [unit='s'], POS1 R8 [shape=[3], unit=['deg','deg','m']], POS2 R8 [shape=[3], unit=['m','m','m']]"
../../../tables/apps/taql "alter table tEpochEngine_tmp.tab set keyword TIME::MEASINFO=[type='epoch',Ref='UTC'], POS1::MEASINFO=[type='position',Ref='WGS84'], POS2::MEASINFO=[type='position',Ref='ITRF']"
../../../tables/apps/taql 'insert into tEpochEngine_tmp.tab (TIME,POS1,POS2) values
 (50217.625d,
  [6.60417, 52.8, 10],
  [3.83879e+06, 444447, 5.05713e+06]),
 (50417.625d,
  [-60.60417, -32.8, 1000],
  [2.63452e+06, -4.67631e+06, -3.43588e+06]),
 (50617.625d,
  [-6.60417, 32.8, 2000],
  [5.33258e+06, -617394, 3.43642e+06])'

$casa_checktool ./tEpochEngine
