#!/bin/sh

# Create a table with 7 columns containing freq, radvel, doppler,
# restfreq, directions, epochs and positions.
# Define the measure keywords for them.
../../../tables/apps/taql "create table tFrequencyEngine_tmp.tab DOPPCOL R8, RVCOL R8 [shape=[2], unit='m/s'], FREQ R8 [unit='GHz'], RESTFREQ R8 [unit='MHz'], DIR R8 [shape=[2,2], unit=['deg','deg']], TIME R8 [unit='s'], POS1 R8 [shape=[3], unit=['deg','deg','m']]"
../../../tables/apps/taql "alter table tFrequencyEngine_tmp.tab set keyword DOPPCOL::MEASINFO=[type='doppler',Ref='RADIO'], RVCOL::MEASINFO=[type='radialvelocity',Ref='BARY'], FREQ::MEASINFO=[type='frequency',Ref='LSRK'], DIR::MEASINFO=[type='direction', Ref='J2000'], TIME::MEASINFO=[type='epoch',Ref='UTC'], POS1::MEASINFO=[type='position',Ref='WGS84']"
../../../tables/apps/taql 'insert into tFrequencyEngine_tmp.tab (DOPPCOL,RVCOL,FREQ,RESTFREQ,DIR,TIME,POS1) values
 (0.5, [2e5, 3e5], 0.2, 1425.445,
  [[185.425833deg, 31.799167deg], [0,0]],
  50217.625d,
  [6.60417, 52.8, 10]),
 (0.6, [3e5, 2e5], 0.3, 4874.157,
  [[175.425833deg, 41.799167deg], [0,0]],
  50417.625d,
  [-60.60417, -32.8, 1000])'

$casa_checktool ./tFrequencyEngine
