#!/bin/sh

export LD_LIBRARY_PATH=../..:${LD_LIBRARY_PATH}
export DYLD_LIBRARY_PATH=../..:${DYLD_LIBRARY_PATH}

$casa_checktool ./tmeas
echo

# Test various commands
$casa_checktool ../../../tables/apps/taql 'meas.wgs("WSRT")'
$casa_checktool ../../../tables/apps/taql 'str(meas.dir("ITRF", "SUN", 10Aug2010/13:12:11, "WSRT"))'
$casa_checktool ../../../tables/apps/taql 'str(meas.dircos("ITRF", "SUN", 10Aug2010/13:12:11, "WSRT"))'
$casa_checktool ../../../tables/apps/taql 'str(meas.riseset("SUN", 10Aug2010/13:12:11, "WSRT"))'

# Check if all dates are correct.
$casa_checktool ../../../tables/apps/taql "any(date(meas.riseset(['SUN'],1jan10+[0:366],[5d0m, 52d0m])) != transpose(array(date(1jan2010+[0:366]),2,366)))"
# Show the rise/set times for the year.
$casa_checktool ../../../tables/apps/taql "transpose(time(meas.riseset(['SUN'],1jan10+[0:366],[4d53m22, 52d22m26])))"
