#!/bin/sh

# Create a table with 2 columns containing positions.
# The same positions are defined as WGS84 (llh) and ITRF (xyz).
# Define the measure keywords for them.
../../../tables/apps/taql "create table tPositionEngine_tmp.tab POS1 R8 [shape=[3], unit=['deg','deg','m']], POS2 R8 [shape=[3], unit=['m','m','m']]"
../../../tables/apps/taql "alter table tPositionEngine_tmp.tab set keyword POS1::MEASINFO=[type='position',Ref='WGS84'], POS2::MEASINFO=[type='position',Ref='WGS84']"
../../../tables/apps/taql 'insert into tPositionEngine_tmp.tab (POS1,POS2) values
 ([6.60417, 52.8, 10],
  [6.005872356561, 0.6953461051394, 7.9652991802420]),
 ([-60.60417, -32.8, 1000],
  [412.5840018012746, -732.3432640298653, -541.7082102827397]),
 ([-6.60417, 32.8, 2000],
  [1669.9778758135608, -193.3462022960651, 1083.4164205654795])'

$casa_checktool ./tPositionEngine
