#!/bin/sh

# Create a table with 5 columns containing radvel, doppler, directions, epochs and positions.
# Define the measure keywords for them.
../../../tables/apps/taql "create table tRadialVelocityEngine_tmp.tab DOPPCOL R8, RVCOL R8 [shape=[2], unit='m/s'], DIR R8 [shape=[2,2], unit=['deg','deg']], TIME R8 [unit='s'], POS1 R8 [shape=[3], unit=['deg','deg','m']]"
../../../tables/apps/taql "alter table tRadialVelocityEngine_tmp.tab set keyword DOPPCOL::MEASINFO=[type='doppler',Ref='RADIO'], RVCOL::MEASINFO=[type='radialvelocity',Ref='BARY'], DIR::MEASINFO=[type='direction', Ref='J2000'], TIME::MEASINFO=[type='epoch',Ref='UTC'], POS1::MEASINFO=[type='position',Ref='WGS84']"
../../../tables/apps/taql 'insert into tRadialVelocityEngine_tmp.tab (DOPPCOL,RVCOL,DIR,TIME,POS1) values
 (0.2, [2e5, 3e5],
  [[185.425833deg, 31.799167deg], [0,0]],
  50217.625d,
  [6.60417, 52.8, 10]),
 (0.3, [3e5, 2e5],
  [[175.425833deg, 41.799167deg], [0,0]],
  50417.625d,
  [-60.60417, -32.8, 1000])'

$casa_checktool ./tRadialVelocityEngine
