#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: tAutoflag.run
#-----------------------------------------------------------------------------
# This script executes the tAutoflag.g test script to check if all the
# flagging modules are working
#
# $Id$
#-----------------------------------------------------------------------------

  # This script has problems, because it uses glish. So exit immediately.
  echo "UNTESTED: tAutoflag.run (AIPSPATH not defined)"
  exit 3

  if [ "$AIPSPATH" = "" ]
  then
     echo "UNTESTED: tAutoflag.run (AIPSPATH not defined)"
     exit 3
  fi

  # establish location of test MS
  MS='WSRT-test.MS2'
  AIPSDEMO=`echo $AIPSPATH | awk '{printf("%s/data/demo/autoflag",$1)}'`
  MSPATH="$AIPSDEMO/$MS"
  if [ ! -d "$MSPATH" -o ! -w "$MSPATH" ]; then
    MSPATH="$HOME/aips++/data/demo/autoflag/$MS"
    if [ ! -d "$MSPATH" -o ! -w "$MSPATH" ]; then
      echo "UNTESTED: tAutoflag.run (found neither $AIPSDEMO/$MS nor $MSPATH)"
      exit 3
    fi
  fi
  # set symlink
  LINK='tAutoflag_tmp.MS2'
  rm -f $LINK 2>/dev/null
  ln -s $MSPATH $LINK
  if [ ! $? ]; then
    echo "UNTESTED: tAutoflag.run (failed to set $LINK symlink)"
    exit 3
  fi
  
  # run the glish script
  echo ">>>"
  glish -l tAutoflag.g
