#!/bin/sh
#-----------------------------------------------------------------------------
# prd: Report the default printer
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1992,1993,1994
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: prd
#-----------------------------------------------------------------------------
# prd reports the default printer for the current host.
#
# Original: 1992/03/04 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Use the PRINTER environment variable if defined.
  if [ "$PRINTER" != "" ]
  then
     echo $PRINTER
  else
#    Query the AIPS++ resource database.
     getrc printer.default 2> /dev/null
  fi


  exit 0
