casacore: casacore::ROMSMainColumns Class Reference
casacore::ROMSMainColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class for easy read-only access to MeasurementSet main table columns.
#include <MSMainColumns.h>
Public Member Functions
ROMSMainColumns (const MeasurementSet &ms)
Create a columns object that accesses the data in the specified Table.
~ROMSMainColumns ()
The desctructor does nothing special.
const ROScalarColumn< Int > & antenna1 () const
Access to required columns.
const ROScalarColumn< Int > & antenna2 () const
const ROScalarColumn< Int > & arrayId () const
const ROScalarColumn< Int > & dataDescId () const
const ROScalarColumn< Double > & exposure () const
const ROScalarQuantColumn< Double > & exposureQuant () const
const ROScalarColumn< Int > & feed1 () const
const ROScalarColumn< Int > & feed2 () const
const ROScalarColumn< Int > & fieldId () const
const ROArrayColumn< Bool > & flag () const
const ROArrayColumn< Bool > & flagCategory () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & observationId () const
const ROScalarColumn< Int > & processorId () const
const ROScalarColumn< Int > & scanNumber () const
const ROArrayColumn< Float > & sigma () const
const ROScalarColumn< Int > & stateId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & timeCentroid () const
const ROScalarQuantColumn< Double > & timeCentroidQuant () const
const ROScalarMeasColumn< MEpoch > & timeCentroidMeas () const
const ROArrayColumn< Double > & uvw () const
const ROArrayQuantColumn< Double > & uvwQuant () const
const ROScalarMeasColumn< Muvw > & uvwMeas () const
const ROArrayColumn< Float > & weight () const
const ROScalarColumn< Int > & antenna3 () const
Access to optional columns.
const ROScalarColumn< Bool > & baselineRef () const
const ROArrayColumn< Complex > & correctedData () const
const ROArrayColumn< Complex > & data () const
const ROScalarColumn< Int > & feed3 () const
const ROArrayColumn< Float > & floatData () const
const ROArrayColumn< Float > & imagingWeight () const
const ROArrayColumn< Complex > & lagData () const
const ROArrayColumn< Complex > & modelData () const
const ROScalarColumn< Int > & phaseId () const
const ROScalarColumn< Int > & pulsarBin () const
const ROScalarColumn< Int > & pulsarGateId () const
const ROArrayColumn< Float > & sigmaSpectrum () const
const ROScalarColumn< Double > & timeExtraPrec () const
const ROScalarQuantColumn< Double > & timeExtraPrecQuant () const
const ROArrayColumn< Double > & uvw2 () const
const ROScalarMeasColumn< Muvw > & uvw2Meas () const
const ROArrayQuantColumn< Double > & uvw2Quant () const
const ROArrayColumn< Complex > & videoPoint () const
const ROArrayColumn< Float > & weightSpectrum () const
const ROArrayColumn< Float > & weightSpectrumCorrected () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Vector< String > flagCategories () const
Returns the category labels for the FLAG_CATEGORY column.
Protected Member Functions
ROMSMainColumns ()
void attach (const MeasurementSet &ms)
Private Member Functions
ROMSMainColumns (const ROMSMainColumns &)
ROMSMainColumns & operator= (const ROMSMainColumns &)
void attachOptionalCols (const MeasurementSet &ms)
Private Attributes
ROScalarColumn< Int > antenna1_p
ROScalarColumn< Int > antenna2_p
ROScalarColumn< Int > arrayId_p
ROScalarColumn< Int > dataDescId_p
ROScalarColumn< Double > exposure_p
ROScalarColumn< Int > feed1_p
ROScalarColumn< Int > feed2_p
ROScalarColumn< Int > fieldId_p
ROArrayColumn< Bool > flag_p
ROArrayColumn< Bool > flagCategory_p
ROScalarColumn< Bool > flagRow_p
ROScalarColumn< Double > interval_p
ROScalarColumn< Int > observationId_p
ROScalarColumn< Int > processorId_p
ROScalarColumn< Int > scanNumber_p
ROArrayColumn< Float > sigma_p
ROScalarColumn< Int > stateId_p
ROScalarColumn< Double > time_p
ROScalarColumn< Double > timeCentroid_p
ROArrayColumn< Double > uvw_p
ROArrayColumn< Float > weight_p
ROScalarColumn< Int > antenna3_p
ROScalarColumn< Bool > baselineRef_p
ROArrayColumn< Complex > data_p
ROScalarColumn< Int > feed3_p
ROArrayColumn< Float > floatData_p
ROArrayColumn< Complex > lagData_p
ROScalarColumn< Int > phaseId_p
ROScalarColumn< Int > pulsarBin_p
ROScalarColumn< Int > pulsarGateId_p
ROArrayColumn< Float > sigmaSpectrum_p
ROScalarColumn< Double > timeExtraPrec_p
ROArrayColumn< Double > uvw2_p
ROArrayColumn< Complex > videoPoint_p
ROArrayColumn< Float > weightSpectrum_p
ROArrayColumn< Float > weightSpectrumCorrected_p
ROArrayColumn< Complex > correctedData_p
ROArrayColumn< Float > imagingWeight_p
ROArrayColumn< Complex > modelData_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarMeasColumn< MEpoch > timeCentroidMeas_p
ROScalarMeasColumn< Muvw > uvwMeas_p
ROScalarMeasColumn< Muvw > uvw2Meas_p
ROScalarQuantColumn< Double > exposureQuant_p
ROScalarQuantColumn< Double > intervalQuant_p
ROScalarQuantColumn< Double > timeQuant_p
ROScalarQuantColumn< Double > timeCentroidQuant_p
ROArrayQuantColumn< Double > uvwQuant_p
ROScalarQuantColumn< Double > timeExtraPrecQuant_p
ROArrayQuantColumn< Double > uvw2Quant_p
Detailed Description
A class for easy read-only access to MeasurementSet main table columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MeasurementSet
ArrayColumn
ScalarColumn
Etymology
ROMSColumns stands for Read-Only MeasurementSet Table columns.
Synopsis
This class provides read-only access to the columns in the MeasurementSet. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations.
Warning: The Table that is used to construct this class must not be destroyed (or go out of scope) before this class does; Otherwise the scalar and array columns use by this class will be left dangling;
Example
// use as follows
MeasurementSet ms("myMS");
ROMSColumns msc(ms);
// show data from row 5
cout << msc.data()(5);
// show name of antenna on row 3 in antenna table
cout << msc.antenna().name();
Motivation
See MSColumns for the motivation.
To Do
We might decide to merge all the MSColumn classes with the corresponding MeasurementSet classes.
Definition at line 101 of file MSMainColumns.h.
Constructor & Destructor Documentation
ROMSMainColumns() [1/3]
casacore::ROMSMainColumns::ROMSMainColumns (const MeasurementSet & ms)
Create a columns object that accesses the data in the specified Table.
~ROMSMainColumns()
casacore::ROMSMainColumns::~ROMSMainColumns ()
The desctructor does nothing special.
ROMSMainColumns() [2/3]
casacore::ROMSMainColumns::ROMSMainColumns () protected
ROMSMainColumns() [3/3]
casacore::ROMSMainColumns::ROMSMainColumns (const ROMSMainColumns &) private
Member Function Documentation
antenna1()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::antenna1 () const inline
Access to required columns.
Definition at line 112 of file MSMainColumns.h.
References antenna1_p.
Referenced by casacore::MSMainColumns::antenna1().
antenna2()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::antenna2 () const inline
Definition at line 113 of file MSMainColumns.h.
References antenna2_p.
Referenced by casacore::MSMainColumns::antenna2().
antenna3()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::antenna3 () const inline
Access to optional columns.
Definition at line 153 of file MSMainColumns.h.
References antenna3_p.
Referenced by casacore::MSMainColumns::antenna3().
arrayId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::arrayId () const inline
Definition at line 114 of file MSMainColumns.h.
References arrayId_p.
Referenced by casacore::MSMainColumns::arrayId().
attach()
void casacore::ROMSMainColumns::attach (const MeasurementSet & ms) protected
attachOptionalCols()
void casacore::ROMSMainColumns::attachOptionalCols (const MeasurementSet & ms) private
baselineRef()
const ROScalarColumn<Bool>& casacore::ROMSMainColumns::baselineRef () const inline
Definition at line 154 of file MSMainColumns.h.
References baselineRef_p.
Referenced by casacore::MSMainColumns::baselineRef().
correctedData()
const ROArrayColumn<Complex>& casacore::ROMSMainColumns::correctedData () const inline
Definition at line 155 of file MSMainColumns.h.
References correctedData_p.
Referenced by casacore::MSMainColumns::correctedData().
data()
const ROArrayColumn<Complex>& casacore::ROMSMainColumns::data () const inline
Definition at line 156 of file MSMainColumns.h.
References data_p.
Referenced by casacore::MSMainColumns::data().
dataDescId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::dataDescId () const inline
Definition at line 115 of file MSMainColumns.h.
References dataDescId_p.
Referenced by casacore::MSMainColumns::dataDescId().
exposure()
const ROScalarColumn<Double>& casacore::ROMSMainColumns::exposure () const inline
Definition at line 116 of file MSMainColumns.h.
References exposure_p.
Referenced by casacore::MSMainColumns::exposure().
exposureQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSMainColumns::exposureQuant () const inline
Definition at line 117 of file MSMainColumns.h.
References exposureQuant_p.
Referenced by casacore::MSMainColInterface::exposureQuant(), and casacore::MSMainColumns::exposureQuant().
feed1()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::feed1 () const inline
Definition at line 119 of file MSMainColumns.h.
References feed1_p.
Referenced by casacore::MSMainColumns::feed1().
feed2()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::feed2 () const inline
Definition at line 120 of file MSMainColumns.h.
References feed2_p.
Referenced by casacore::MSMainColumns::feed2().
feed3()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::feed3 () const inline
Definition at line 157 of file MSMainColumns.h.
References feed3_p.
Referenced by casacore::MSMainColumns::feed3().
fieldId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::fieldId () const inline
Definition at line 121 of file MSMainColumns.h.
References fieldId_p.
Referenced by casacore::MSMainColumns::fieldId().
flag()
const ROArrayColumn<Bool>& casacore::ROMSMainColumns::flag () const inline
Definition at line 122 of file MSMainColumns.h.
References flag_p.
Referenced by casacore::MSMainColInterface::flag(), and casacore::MSMainColumns::flag().
flagCategories()
Vector<String> casacore::ROMSMainColumns::flagCategories () const
Returns the category labels for the FLAG_CATEGORY column.
flagCategory()
const ROArrayColumn<Bool>& casacore::ROMSMainColumns::flagCategory () const inline
Definition at line 123 of file MSMainColumns.h.
References flagCategory_p.
Referenced by casacore::MSMainColumns::flagCategory().
flagRow()
const ROScalarColumn<Bool>& casacore::ROMSMainColumns::flagRow () const inline
Definition at line 124 of file MSMainColumns.h.
References flagRow_p.
Referenced by casacore::MSMainColInterface::flagRow(), and casacore::MSMainColumns::flagRow().
floatData()
const ROArrayColumn<Float>& casacore::ROMSMainColumns::floatData () const inline
Definition at line 158 of file MSMainColumns.h.
References floatData_p.
Referenced by casacore::MSMainColumns::floatData().
imagingWeight()
const ROArrayColumn<Float>& casacore::ROMSMainColumns::imagingWeight () const inline
Definition at line 159 of file MSMainColumns.h.
References imagingWeight_p.
Referenced by casacore::MSMainColumns::imagingWeight().
interval()
const ROScalarColumn<Double>& casacore::ROMSMainColumns::interval () const inline
Definition at line 125 of file MSMainColumns.h.
References interval_p.
Referenced by casacore::MSMainColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSMainColumns::intervalQuant () const inline
Definition at line 126 of file MSMainColumns.h.
References intervalQuant_p.
Referenced by casacore::MSMainColumns::intervalQuant().
lagData()
const ROArrayColumn<Complex>& casacore::ROMSMainColumns::lagData () const inline
Definition at line 160 of file MSMainColumns.h.
References lagData_p.
Referenced by casacore::MSMainColumns::lagData().
modelData()
const ROArrayColumn<Complex>& casacore::ROMSMainColumns::modelData () const inline
Definition at line 161 of file MSMainColumns.h.
References modelData_p.
Referenced by casacore::MSMainColumns::modelData().
nrow()
uInt casacore::ROMSMainColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 180 of file MSMainColumns.h.
References antenna1_p.
observationId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::observationId () const inline
Definition at line 128 of file MSMainColumns.h.
References observationId_p.
Referenced by casacore::MSMainColumns::observationId().
operator=()
ROMSMainColumns& casacore::ROMSMainColumns::operator= (const ROMSMainColumns &) private
phaseId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::phaseId () const inline
Definition at line 162 of file MSMainColumns.h.
References phaseId_p.
Referenced by casacore::MSMainColumns::phaseId().
processorId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::processorId () const inline
Definition at line 129 of file MSMainColumns.h.
References processorId_p.
Referenced by casacore::MSMainColumns::processorId().
pulsarBin()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::pulsarBin () const inline
Definition at line 163 of file MSMainColumns.h.
References pulsarBin_p.
Referenced by casacore::MSMainColumns::pulsarBin().
pulsarGateId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::pulsarGateId () const inline
Definition at line 164 of file MSMainColumns.h.
References pulsarGateId_p.
Referenced by casacore::MSMainColumns::pulsarGateId().
scanNumber()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::scanNumber () const inline
Definition at line 130 of file MSMainColumns.h.
References scanNumber_p.
Referenced by casacore::MSMainColumns::scanNumber().
sigma()
const ROArrayColumn<Float>& casacore::ROMSMainColumns::sigma () const inline
Definition at line 131 of file MSMainColumns.h.
References sigma_p.
Referenced by casacore::MSMainColumns::sigma().
sigmaSpectrum()
const ROArrayColumn<Float>& casacore::ROMSMainColumns::sigmaSpectrum () const inline
Definition at line 165 of file MSMainColumns.h.
References sigmaSpectrum_p.
Referenced by casacore::MSMainColumns::sigmaSpectrum().
stateId()
const ROScalarColumn<Int>& casacore::ROMSMainColumns::stateId () const inline
Definition at line 132 of file MSMainColumns.h.
References stateId_p.
Referenced by casacore::MSMainColumns::stateId().
time()
const ROScalarColumn<Double>& casacore::ROMSMainColumns::time () const inline
Definition at line 133 of file MSMainColumns.h.
References time_p.
Referenced by casacore::MSMainColumns::time().
timeCentroid()
const ROScalarColumn<Double>& casacore::ROMSMainColumns::timeCentroid () const inline
Definition at line 138 of file MSMainColumns.h.
References timeCentroid_p.
Referenced by casacore::MSMainColumns::timeCentroid().
timeCentroidMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSMainColumns::timeCentroidMeas () const inline
Definition at line 141 of file MSMainColumns.h.
References timeCentroidMeas_p.
Referenced by casacore::MSMainColumns::timeCentroidMeas().
timeCentroidQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSMainColumns::timeCentroidQuant () const inline
Definition at line 139 of file MSMainColumns.h.
References timeCentroidQuant_p.
Referenced by casacore::MSMainColumns::timeCentroidQuant().
timeExtraPrec()
const ROScalarColumn<Double>& casacore::ROMSMainColumns::timeExtraPrec () const inline
Definition at line 166 of file MSMainColumns.h.
References timeExtraPrec_p.
Referenced by casacore::MSMainColumns::timeExtraPrec().
timeExtraPrecQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSMainColumns::timeExtraPrecQuant () const inline
Definition at line 167 of file MSMainColumns.h.
References timeExtraPrecQuant_p.
Referenced by casacore::MSMainColumns::timeExtraPrecQuant().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSMainColumns::timeMeas () const inline
Definition at line 136 of file MSMainColumns.h.
References timeMeas_p.
Referenced by casacore::MSMainColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSMainColumns::timeQuant () const inline
Definition at line 134 of file MSMainColumns.h.
References timeQuant_p.
Referenced by casacore::MSMainColInterface::timeQuant(), and casacore::MSMainColumns::timeQuant().
uvw()
const ROArrayColumn<Double>& casacore::ROMSMainColumns::uvw () const inline
Definition at line 143 of file MSMainColumns.h.
References uvw_p.
Referenced by casacore::MSMainColumns::uvw().
uvw2()
const ROArrayColumn<Double>& casacore::ROMSMainColumns::uvw2 () const inline
Definition at line 169 of file MSMainColumns.h.
References uvw2_p.
Referenced by casacore::MSMainColumns::uvw2().
uvw2Meas()
const ROScalarMeasColumn<Muvw>& casacore::ROMSMainColumns::uvw2Meas () const inline
Definition at line 170 of file MSMainColumns.h.
References uvw2Meas_p.
Referenced by casacore::MSMainColumns::uvw2Meas().
uvw2Quant()
const ROArrayQuantColumn<Double>& casacore::ROMSMainColumns::uvw2Quant () const inline
Definition at line 172 of file MSMainColumns.h.
References uvw2Quant_p.
Referenced by casacore::MSMainColumns::uvw2Quant().
uvwMeas()
const ROScalarMeasColumn<Muvw>& casacore::ROMSMainColumns::uvwMeas () const inline
Definition at line 146 of file MSMainColumns.h.
References uvwMeas_p.
Referenced by casacore::MSMainColumns::uvwMeas().
uvwQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSMainColumns::uvwQuant () const inline
Definition at line 144 of file MSMainColumns.h.
References uvwQuant_p.
Referenced by casacore::MSMainColumns::uvwQuant().
videoPoint()
const ROArrayColumn<Complex>& casacore::ROMSMainColumns::videoPoint () const inline
Definition at line 174 of file MSMainColumns.h.
References videoPoint_p.
Referenced by casacore::MSMainColumns::videoPoint().
weight()
const ROArrayColumn<Float>& casacore::ROMSMainColumns::weight () const inline
Definition at line 148 of file MSMainColumns.h.
References weight_p.
Referenced by casacore::MSMainColumns::weight().
weightSpectrum()
const ROArrayColumn<Float>& casacore::ROMSMainColumns::weightSpectrum () const inline
Definition at line 175 of file MSMainColumns.h.
References weightSpectrum_p.
Referenced by casacore::MSMainColumns::weightSpectrum().
weightSpectrumCorrected()
const ROArrayColumn<Float>& casacore::ROMSMainColumns::weightSpectrumCorrected () const inline
Definition at line 176 of file MSMainColumns.h.
References weightSpectrumCorrected_p.
Referenced by casacore::MSMainColumns::weightSpectrumCorrected().
Member Data Documentation
antenna1_p
ROScalarColumn<Int> casacore::ROMSMainColumns::antenna1_p private
Definition at line 203 of file MSMainColumns.h.
Referenced by antenna1(), and nrow().
antenna2_p
ROScalarColumn<Int> casacore::ROMSMainColumns::antenna2_p private
Definition at line 204 of file MSMainColumns.h.
Referenced by antenna2().
antenna3_p
ROScalarColumn<Int> casacore::ROMSMainColumns::antenna3_p private
Definition at line 225 of file MSMainColumns.h.
Referenced by antenna3().
arrayId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::arrayId_p private
Definition at line 205 of file MSMainColumns.h.
Referenced by arrayId().
baselineRef_p
ROScalarColumn<Bool> casacore::ROMSMainColumns::baselineRef_p private
Definition at line 226 of file MSMainColumns.h.
Referenced by baselineRef().
correctedData_p
ROArrayColumn<Complex> casacore::ROMSMainColumns::correctedData_p private
Definition at line 242 of file MSMainColumns.h.
Referenced by correctedData().
data_p
ROArrayColumn<Complex> casacore::ROMSMainColumns::data_p private
Definition at line 227 of file MSMainColumns.h.
Referenced by data().
dataDescId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::dataDescId_p private
Definition at line 206 of file MSMainColumns.h.
Referenced by dataDescId().
exposure_p
ROScalarColumn<Double> casacore::ROMSMainColumns::exposure_p private
Definition at line 207 of file MSMainColumns.h.
Referenced by exposure().
exposureQuant_p
ROScalarQuantColumn<Double> casacore::ROMSMainColumns::exposureQuant_p private
Definition at line 254 of file MSMainColumns.h.
Referenced by exposureQuant().
feed1_p
ROScalarColumn<Int> casacore::ROMSMainColumns::feed1_p private
Definition at line 208 of file MSMainColumns.h.
Referenced by feed1().
feed2_p
ROScalarColumn<Int> casacore::ROMSMainColumns::feed2_p private
Definition at line 209 of file MSMainColumns.h.
Referenced by feed2().
feed3_p
ROScalarColumn<Int> casacore::ROMSMainColumns::feed3_p private
Definition at line 228 of file MSMainColumns.h.
Referenced by feed3().
fieldId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::fieldId_p private
Definition at line 210 of file MSMainColumns.h.
Referenced by fieldId().
flag_p
ROArrayColumn<Bool> casacore::ROMSMainColumns::flag_p private
Definition at line 211 of file MSMainColumns.h.
Referenced by flag().
flagCategory_p
ROArrayColumn<Bool> casacore::ROMSMainColumns::flagCategory_p private
Definition at line 212 of file MSMainColumns.h.
Referenced by flagCategory().
flagRow_p
ROScalarColumn<Bool> casacore::ROMSMainColumns::flagRow_p private
Definition at line 213 of file MSMainColumns.h.
Referenced by flagRow().
floatData_p
ROArrayColumn<Float> casacore::ROMSMainColumns::floatData_p private
Definition at line 229 of file MSMainColumns.h.
Referenced by floatData().
imagingWeight_p
ROArrayColumn<Float> casacore::ROMSMainColumns::imagingWeight_p private
Definition at line 243 of file MSMainColumns.h.
Referenced by imagingWeight().
interval_p
ROScalarColumn<Double> casacore::ROMSMainColumns::interval_p private
Definition at line 214 of file MSMainColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSMainColumns::intervalQuant_p private
Definition at line 255 of file MSMainColumns.h.
Referenced by intervalQuant().
lagData_p
ROArrayColumn<Complex> casacore::ROMSMainColumns::lagData_p private
Definition at line 230 of file MSMainColumns.h.
Referenced by lagData().
modelData_p
ROArrayColumn<Complex> casacore::ROMSMainColumns::modelData_p private
Definition at line 244 of file MSMainColumns.h.
Referenced by modelData().
observationId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::observationId_p private
Definition at line 215 of file MSMainColumns.h.
Referenced by observationId().
phaseId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::phaseId_p private
Definition at line 231 of file MSMainColumns.h.
Referenced by phaseId().
processorId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::processorId_p private
Definition at line 216 of file MSMainColumns.h.
Referenced by processorId().
pulsarBin_p
ROScalarColumn<Int> casacore::ROMSMainColumns::pulsarBin_p private
Definition at line 232 of file MSMainColumns.h.
Referenced by pulsarBin().
pulsarGateId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::pulsarGateId_p private
Definition at line 233 of file MSMainColumns.h.
Referenced by pulsarGateId().
scanNumber_p
ROScalarColumn<Int> casacore::ROMSMainColumns::scanNumber_p private
Definition at line 217 of file MSMainColumns.h.
Referenced by scanNumber().
sigma_p
ROArrayColumn<Float> casacore::ROMSMainColumns::sigma_p private
Definition at line 218 of file MSMainColumns.h.
Referenced by sigma().
sigmaSpectrum_p
ROArrayColumn<Float> casacore::ROMSMainColumns::sigmaSpectrum_p private
Definition at line 234 of file MSMainColumns.h.
Referenced by sigmaSpectrum().
stateId_p
ROScalarColumn<Int> casacore::ROMSMainColumns::stateId_p private
Definition at line 219 of file MSMainColumns.h.
Referenced by stateId().
time_p
ROScalarColumn<Double> casacore::ROMSMainColumns::time_p private
Definition at line 220 of file MSMainColumns.h.
Referenced by time().
timeCentroid_p
ROScalarColumn<Double> casacore::ROMSMainColumns::timeCentroid_p private
Definition at line 221 of file MSMainColumns.h.
Referenced by timeCentroid().
timeCentroidMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSMainColumns::timeCentroidMeas_p private
Definition at line 248 of file MSMainColumns.h.
Referenced by timeCentroidMeas().
timeCentroidQuant_p
ROScalarQuantColumn<Double> casacore::ROMSMainColumns::timeCentroidQuant_p private
Definition at line 257 of file MSMainColumns.h.
Referenced by timeCentroidQuant().
timeExtraPrec_p
ROScalarColumn<Double> casacore::ROMSMainColumns::timeExtraPrec_p private
Definition at line 235 of file MSMainColumns.h.
Referenced by timeExtraPrec().
timeExtraPrecQuant_p
ROScalarQuantColumn<Double> casacore::ROMSMainColumns::timeExtraPrecQuant_p private
Definition at line 260 of file MSMainColumns.h.
Referenced by timeExtraPrecQuant().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSMainColumns::timeMeas_p private
Definition at line 247 of file MSMainColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSMainColumns::timeQuant_p private
Definition at line 256 of file MSMainColumns.h.
Referenced by timeQuant().
uvw2_p
ROArrayColumn<Double> casacore::ROMSMainColumns::uvw2_p private
Definition at line 236 of file MSMainColumns.h.
Referenced by uvw2().
uvw2Meas_p
ROScalarMeasColumn<Muvw> casacore::ROMSMainColumns::uvw2Meas_p private
Definition at line 251 of file MSMainColumns.h.
Referenced by uvw2Meas().
uvw2Quant_p
ROArrayQuantColumn<Double> casacore::ROMSMainColumns::uvw2Quant_p private
Definition at line 261 of file MSMainColumns.h.
Referenced by uvw2Quant().
uvw_p
ROArrayColumn<Double> casacore::ROMSMainColumns::uvw_p private
Definition at line 222 of file MSMainColumns.h.
Referenced by uvw().
uvwMeas_p
ROScalarMeasColumn<Muvw> casacore::ROMSMainColumns::uvwMeas_p private
Definition at line 249 of file MSMainColumns.h.
Referenced by uvwMeas().
uvwQuant_p
ROArrayQuantColumn<Double> casacore::ROMSMainColumns::uvwQuant_p private
Definition at line 258 of file MSMainColumns.h.
Referenced by uvwQuant().
videoPoint_p
ROArrayColumn<Complex> casacore::ROMSMainColumns::videoPoint_p private
Definition at line 237 of file MSMainColumns.h.
Referenced by videoPoint().
weight_p
ROArrayColumn<Float> casacore::ROMSMainColumns::weight_p private
Definition at line 223 of file MSMainColumns.h.
Referenced by weight().
weightSpectrum_p
ROArrayColumn<Float> casacore::ROMSMainColumns::weightSpectrum_p private
Definition at line 238 of file MSMainColumns.h.
Referenced by weightSpectrum().
weightSpectrumCorrected_p
ROArrayColumn<Float> casacore::ROMSMainColumns::weightSpectrumCorrected_p private
Definition at line 239 of file MSMainColumns.h.
Referenced by weightSpectrumCorrected().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSMainColumns.h