casacore: casacore::VAXConversion Class Reference
casacore::VAXConversion Class Reference
OS_module
A class with static functions to convert VAX format.
#include <VAXConversion.h>
Static Public Member Functions
static void toLocal (char &to, const void *from)
Convert one value from VAX format to local format.
static void toLocal (unsigned char &to, const void *from)
static void toLocal (short &to, const void *from)
static void toLocal (unsigned short &to, const void *from)
static void toLocal (int &to, const void *from)
static void toLocal (unsigned int &to, const void *from)
static void toLocal (Int64 &to, const void *from)
static void toLocal (uInt64 &to, const void *from)
static void toLocal (float &to, const void *from)
static void toLocal (double &to, const void *from)
static void toLocal (char *to, const void *from, size_t nr)
Convert nr values from VAX format to local format.
static void toLocal (unsigned char *to, const void *from, size_t nr)
static void toLocal (short *to, const void *from, size_t nr)
static void toLocal (unsigned short *to, const void *from, size_t nr)
static void toLocal (int *to, const void *from, size_t nr)
static void toLocal (unsigned int *to, const void *from, size_t nr)
static void toLocal (Int64 *to, const void *from, size_t nr)
static void toLocal (uInt64 *to, const void *from, size_t nr)
static void toLocal (float *to, const void *from, size_t nr)
static void toLocal (double *to, const void *from, size_t nr)
static void fromLocal (void *to, char from)
Convert one value from local format to VAX format.
static void fromLocal (void *to, unsigned char from)
static void fromLocal (void *to, short from)
static void fromLocal (void *to, unsigned short from)
static void fromLocal (void *to, int from)
static void fromLocal (void *to, unsigned int from)
static void fromLocal (void *to, Int64 from)
static void fromLocal (void *to, uInt64 from)
static void fromLocal (void *to, float from)
static void fromLocal (void *to, double from)
static void fromLocal (void *to, const char *from, size_t nr)
Convert nr values from local format to VAX format.
static void fromLocal (void *to, const unsigned char *from, size_t nr)
static void fromLocal (void *to, const short *from, size_t nr)
static void fromLocal (void *to, const unsigned short *from, size_t nr)
static void fromLocal (void *to, const int *from, size_t nr)
static void fromLocal (void *to, const unsigned int *from, size_t nr)
static void fromLocal (void *to, const Int64 *from, size_t nr)
static void fromLocal (void *to, const uInt64 *from, size_t nr)
static void fromLocal (void *to, const float *from, size_t nr)
static void fromLocal (void *to, const double *from, size_t nr)
static void moveFloat (void *to, const void *from)
Move a float value (by swapping bytes correctly).
Private Member Functions
VAXConversion ()
This class should not be constructed (so declare the constructor private).
Detailed Description
A class with static functions to convert VAX format.
Intended use:
Public interface
Review Status
Reviewed By:
Friso Olnon
Date Reviewed:
1996/11/06
Test programs:
tVAXConversion
Synopsis
This class contains static toLocal functions to convert data from VAX format to local format and vice-versa. It only handles VAX D-float format. Another class should be implemented to handle VAX G-float format.
The functions work well on big-endian as well as little-endian machines.
Motivation
Archived WSRT data can be stored in the old VAX format (little-endian and VAX D-float floating point format). Conversion functions are needed to read these data.
To Do
Support data type long double.
Definition at line 82 of file VAXConversion.h.
Constructor & Destructor Documentation
casacore::VAXConversion::VAXConversion () private
This class should not be constructed (so declare the constructor private).
Member Function Documentation
void casacore::VAXConversion::fromLocal (void * to, char from) inline static
Convert one value from local format to VAX format.
The from and to buffer should not overlap.
Definition at line 275 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
Referenced by fromLocal().
void casacore::VAXConversion::fromLocal (void * to, unsigned char from) inline static
Definition at line 280 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, short from) inline static
Definition at line 285 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, unsigned short from) inline static
Definition at line 290 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, int from) inline static
Definition at line 295 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, unsigned int from) inline static
Definition at line 300 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, Int64 from) inline static
Definition at line 305 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, uInt64 from) inline static
Definition at line 310 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, float from) inline static
Definition at line 315 of file VAXConversion.h.
References fromLocal().
void casacore::VAXConversion::fromLocal (void * to, double from) inline static
Definition at line 320 of file VAXConversion.h.
References fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const char * from, size_t nr) inline static
Convert nr values from local format to VAX format.
The from and to buffer should not overlap.
Definition at line 325 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const unsigned char * from, size_t nr) inline static
Definition at line 331 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const short * from, size_t nr) inline static
Definition at line 337 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const unsigned short * from, size_t nr) inline static
Definition at line 343 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const int * from, size_t nr) inline static
Definition at line 349 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const unsigned int * from, size_t nr) inline static
Definition at line 355 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const Int64 * from, size_t nr) inline static
Definition at line 361 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
void casacore::VAXConversion::fromLocal (void * to, const uInt64 * from, size_t nr) inline static
Definition at line 367 of file VAXConversion.h.
References casacore::LittleEndianConversion::fromLocal().
static void casacore::VAXConversion::fromLocal (void * to, const float * from, size_t nr) static
static void casacore::VAXConversion::fromLocal (void * to, const double * from, size_t nr) static
void casacore::VAXConversion::moveFloat (void * to, const void * from) inline static
Move a float value (by swapping bytes correctly).
Definition at line 375 of file VAXConversion.h.
void casacore::VAXConversion::toLocal (char & to, const void * from) inline static
Convert one value from VAX format to local format.
The from and to buffer should not overlap.
Definition at line 176 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
Referenced by toLocal().
void casacore::VAXConversion::toLocal (unsigned char & to, const void * from) inline static
Definition at line 181 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (short & to, const void * from) inline static
Definition at line 186 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (unsigned short & to, const void * from) inline static
Definition at line 191 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (int & to, const void * from) inline static
Definition at line 196 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (unsigned int & to, const void * from) inline static
Definition at line 201 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (Int64 & to, const void * from) inline static
Definition at line 206 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (uInt64 & to, const void * from) inline static
Definition at line 211 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (float & to, const void * from) inline static
Definition at line 216 of file VAXConversion.h.
References toLocal().
void casacore::VAXConversion::toLocal (double & to, const void * from) inline static
Definition at line 221 of file VAXConversion.h.
References toLocal().
void casacore::VAXConversion::toLocal (char * to, const void * from, size_t nr) inline static
Convert nr values from VAX format to local format.
The from and to buffer should not overlap.
Definition at line 226 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (unsigned char * to, const void * from, size_t nr) inline static
Definition at line 232 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (short * to, const void * from, size_t nr) inline static
Definition at line 238 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (unsigned short * to, const void * from, size_t nr) inline static
Definition at line 244 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (int * to, const void * from, size_t nr) inline static
Definition at line 250 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (unsigned int * to, const void * from, size_t nr) inline static
Definition at line 256 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (Int64 * to, const void * from, size_t nr) inline static
Definition at line 262 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
void casacore::VAXConversion::toLocal (uInt64 * to, const void * from, size_t nr) inline static
Definition at line 268 of file VAXConversion.h.
References casacore::LittleEndianConversion::toLocal().
static void casacore::VAXConversion::toLocal (float * to, const void * from, size_t nr) static
static void casacore::VAXConversion::toLocal (double * to, const void * from, size_t nr) static
The documentation for this class was generated from the following file:
casa/OS/VAXConversion.h