casacore: casacore::SymLink Class Reference
casacore::SymLink Class Reference
casa package (libcasa_casa) » OS_module
Get information about, and manipulate symbolic links.
#include <SymLink.h>
Public Member Functions
SymLink ()
The default constructor creates a SymLink with path ".".
SymLink (const Path &name)
Create a SymLink with the given path.
SymLink (const String &name)
SymLink (const File &name)
SymLink (const SymLink &that)
Copy constructor (copy semantics).
~SymLink ()
SymLink & operator= (const SymLink &that)
Assignment (copy semantics).
void create (const Path &target, Bool overwrite=True)
Make a symbolic link to a file given by target.
void create (const String &target, Bool overwrite=True)
void copy (const Path &target, Bool overwrite=True) const
Copy the symlink to the target path using the system command cp.
void copy (const String &target, Bool overwrite=True) const
void move (const Path &target, Bool overwrite=True)
Move the symlink to the target path using the system command mv.
void move (const String &target, Bool overwrite=True)
void remove ()
Remove a symbolic link.
Path readSymLink () const
Read value of a symbolic link and return it as a Path.
Path followSymLink () const
As readSymLink, but the entire symlink chain is followed when the symlinks points to other symlinks.
Public Member Functions inherited from casacore::File
File ()
Construct a File object whose Path is set to the current working directory.
File (const Path &path)
Construct a File object whose Path is set to the given Path.
File (const String &path)
File (const File &that)
Copy constructor (copy semantics).
virtual ~File ()
File & operator= (const File &that)
Assignment (copy semantics).
const Path & path () const
Returns the pathname of the file.
Bool isRegular (Bool followSymLink=True) const
Check if the file is a regular file.
Bool isDirectory (Bool followSymLink=True) const
Check if the file is a directory.
Bool isSymLink () const
Check if the file is a symbolic link.
Bool isPipe () const
Check if the file is a pipe.
Bool isCharacterSpecial () const
Check if the file is a character special file.
Bool isBlockSpecial () const
Check if the file is a block special file.
Bool isSocket () const
Check if the file is a socket.
Bool exists () const
Check if the file exists.
Bool isReadable () const
Check if the file is readable.
Bool isWritable () const
Check if the file is writable.
Bool isExecutable () const
Check if the file is executable.
Bool canCreate () const
Check if a file can be created.
long userID () const
Return the userID of the file.
long groupID () const
Return the groupID of the file.
virtual Int64 size () const
Return the size of the file.
uInt readPermissions () const
Return the permissions as a decimal value.
void setPermissions (uInt permissions)
Set permission with perm.
void touch (uInt time)
Update access time and modification time of a file.
void touch ()
Update access time and modification time of a file.
uInt accessTime () const
Time related fucnctions: Return the time when the file was last accessed in seconds since 00:00:00 GMT Jan 1, 1970.
String accessTimeString () const
Return the time when the file was last accessed as a 26-characters String of the form: Thu Feb 3 13:40:11 1994.
uInt modifyTime () const
Return the time when the file was last modified in seconds since 00:00:00 GMT Jan 1, 1970.
String modifyTimeString () const
Return the time when the file was last modified as a 26-characters String of the form: Thu Feb 3 13:40:11 1994.
uInt statusChangeTime () const
Return the time when the file status was last changed in seconds since 00:00:00 GMT Jan 1, 1970.
String statusChangeTimeString () const
return the time when the file status was last changed as a 26-characters String of the form: Thu Feb 3 13:40:11 1994
FileWriteStatus getWriteStatus () const
get write status of the file.
String getFSType () const
Return the filesystem type.
Private Member Functions
void checkPath () const
Check if the path of the file is valid.
String getSymLink () const
Get the value of the symlink.
Additional Inherited Members
Public Types inherited from casacore::File
enum FileWriteStatus {
OVERWRITABLE,
NOT_OVERWRITABLE,
CREATABLE,
NOT_CREATABLE
}
Static Public Member Functions inherited from casacore::File
static Path newUniqueName (const String &directory, const String &prefix)
Create a new unique path name in the specified directory, with the specified prefix and random trailing characters:
static Path newUniqueName (const String &directory)
Create a new unique filename without a prefix.
Protected Member Functions inherited from casacore::File
void removeSymLinks ()
This function is used by RegularFile.
void checkTarget (Path &targetName, Bool overwrite, Bool forDirectory=False) const
Check if the new path for a copy or move is valid.
Detailed Description
Get information about, and manipulate symbolic links.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Intended use:
Public interface
Prerequisite
Basic knowledge of the UNIX file system
File
Etymology
The class SymLink handles SYMbolic LINKs in the file system.
Synopsis
SymLink provides functions to manipulate and to get information about symbolic links. The functions for getting information (like ownership, dates) about symbolic links are inherited from the File class.
The class SymLink itself provides functions to create, remove, copy, and move symbolic links. There is a function readSymLink which reads a link and then returns a path and there is a function followSymLink which reads a link recursively. If the link eventually refers to itself (a loop), an exception will be thrown.
Example
SymLink symLink1("isLink");
SymLink symLink2("isLink2");
SymLink symLinkA("A");
SymLink symLinkB("B");
symLink1.create("~", True);    // Create a symbolic link to the home
// directory. When it exists it will be
// overwritten.
symLink2.create("isLink", False); // Create a symbolic link to
// isLink. When it exists it will not
// be overwritten.
symLinkA.create(Path("B"));    // Create a recursive link
symLinkB.create(Path("A"));    // Create a recursive link
cout << symLink1.readSymLink() << endl;  // The homedirectory is printed
cout << symLink2.readSymLink() << endl;  // isLink is printed
cout << symLink2.followSymLink() << endl;// The homedirectory is printed
cout << symLinkA.readSymLink() << endl;  // B is printed
cout << symLinkA.followSymLink() << endl;// An exception is thrown (loop)
Motivation
Provide functions for manipulating and getting information about symbolic links.
Definition at line 100 of file SymLink.h.
Constructor & Destructor Documentation
SymLink() [1/5]
casacore::SymLink::SymLink ()
The default constructor creates a SymLink with path ".".
SymLink() [2/5]
casacore::SymLink::SymLink (const Path & name)
Create a SymLink with the given path.
An exception is thrown if the path exist and is no symbolic link or if it does not exist, but cannot be created.
SymLink() [3/5]
casacore::SymLink::SymLink (const String & name)
SymLink() [4/5]
casacore::SymLink::SymLink (const File & name)
SymLink() [5/5]
casacore::SymLink::SymLink (const SymLink & that)
Copy constructor (copy semantics).
~SymLink()
casacore::SymLink::~SymLink ()
Member Function Documentation
checkPath()
void casacore::SymLink::checkPath () const private
Check if the path of the file is valid.
Also resolve possible symlinks.
copy() [1/2]
void casacore::SymLink::copy (const Path & target, Bool overwrite = True) const
Copy the symlink to the target path using the system command cp.
The target path can be a directory or a file (as in cp). An exception is thrown if:
- the target directory is not writable
- or the target file already exists and overwrite==False
- or the target file already exists and is not writable
Referenced by copy().
copy() [2/2]
void casacore::SymLink::copy (const String & target, Bool overwrite = True) const inline
Definition at line 192 of file SymLink.h.
References copy().
create() [1/2]
void casacore::SymLink::create (const Path & target, Bool overwrite = True)
Make a symbolic link to a file given by target.
An exception will be thrown if:
-target already exists and is no symlink
-or target already exists and overwrite==False
Referenced by create().
create() [2/2]
void casacore::SymLink::create (const String & target, Bool overwrite = True) inline
Definition at line 188 of file SymLink.h.
References create().
followSymLink()
Path casacore::SymLink::followSymLink () const
As readSymLink, but the entire symlink chain is followed when the symlinks points to other symlinks.
An exception is thrown if this results in a loop (that is, if more than 25 links are encountered).
getSymLink()
String casacore::SymLink::getSymLink () const private
Get the value of the symlink.
move() [1/2]
void casacore::SymLink::move (const Path & target, Bool overwrite = True)
Move the symlink to the target path using the system command mv.
The target path can be a directory or a file (as in mv). An exception is thrown if:
- the target directory is not writable
- or the target file already exists and overwrite==False
- or the target file already exists and is not writable
Referenced by move().
move() [2/2]
void casacore::SymLink::move (const String & target, Bool overwrite = True) inline
Definition at line 196 of file SymLink.h.
References move().
operator=()
SymLink& casacore::SymLink::operator= (const SymLink & that)
Assignment (copy semantics).
readSymLink()
Path casacore::SymLink::readSymLink () const
Read value of a symbolic link and return it as a Path.
If the symlink does not exist, an exception will be thrown. When the symlink points to a file with a relative name, the resulting file name gets prepended by the dirname of the symlink, which is similar to the way a shell handles symlinks. E.g.
ls > subdir/a
ln -s a subdir/b
more subdir/b
The more command shows the results of subdir/a.
remove()
void casacore::SymLink::remove ()
Remove a symbolic link.
The documentation for this class was generated from the following file:
casa/OS/SymLink.h