casacore: casacore::ROMSSpWindowColumns Class Reference
casacore::ROMSSpWindowColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSASpectralWindow columns.
#include <MSSpWindowColumns.h>
Public Member Functions
ROMSSpWindowColumns (const MSSpectralWindow &msSpWindow)
Create a columns object that accesses the data in the specified Table.
~ROMSSpWindowColumns ()
The destructor does nothing special.
const ROArrayColumn< Double > & chanFreq () const
Access to columns.
const ROArrayQuantColumn< Double > & chanFreqQuant () const
const ROArrayMeasColumn< MFrequency > & chanFreqMeas () const
const ROArrayColumn< Double > & chanWidth () const
const ROArrayQuantColumn< Double > & chanWidthQuant () const
const ROArrayColumn< Double > & effectiveBW () const
const ROArrayQuantColumn< Double > & effectiveBWQuant () const
const ROScalarColumn< Int > & freqGroup () const
const ROScalarColumn< String > & freqGroupName () const
const ROScalarColumn< Int > & ifConvChain () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Int > & measFreqRef () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & netSideband () const
const ROScalarColumn< Int > & numChan () const
const ROScalarColumn< Double > & refFrequency () const
const ROScalarQuantColumn< Double > & refFrequencyQuant () const
const ROScalarMeasColumn< MFrequency > & refFrequencyMeas () const
const ROArrayColumn< Double > & resolution () const
const ROArrayQuantColumn< Double > & resolutionQuant () const
const ROScalarColumn< Double > & totalBandwidth () const
const ROScalarQuantColumn< Double > & totalBandwidthQuant () const
const ROArrayColumn< String > & assocNature () const
Access to optional columns.
const ROArrayColumn< Int > & assocSpwId () const
const ROScalarColumn< Int > & bbcNo () const
const ROScalarColumn< Int > & bbcSideband () const
const ROScalarColumn< Int > & dopplerId () const
const ROScalarColumn< Int > & receiverId () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int matchSpw (const MFrequency &refFreq, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance, Int tryRow=-1) const
returns the last row that contains a spectral window that has the specified reference frequency, number of channels, total-bandwidth and IF conversion chain.
Int matchSpw (const MFrequency &refFreq, const MFrequency &chanFreq1, const MeasFrame &measFrm, const MSDopplerColumns &msdopc, const MSSourceColumns &mssrcc, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance, Int tryRow=-1) const
Similar to above, but also pass in the frame info.
Vector< Int > allMatchedSpw (const MFrequency &refFreq, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance) const
This is to check that the channels are matched individually and also if the spw is matched in reverse;.
Int matchSpw (const MFrequency &refFreq, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance, Vector< Double > &otherFreqs, Bool &reversed) const
This version does a channel to channel match too and also return the reversed if it matches but the channels are in inverse order like an upper or lower side band having same characteristics.
Protected Member Functions
ROMSSpWindowColumns ()
void attach (const MSSpectralWindow &msSpWindow)
Private Member Functions
ROMSSpWindowColumns (const ROMSSpWindowColumns &)
ROMSSpWindowColumns & operator= (const ROMSSpWindowColumns &)
void attachOptionalCols (const MSSpectralWindow &msSpWindow)
Bool matchRefFrequency (uInt row, MFrequency::Types refType, Double refFreqInHz, Double tolInHz) const
Bool matchRefFreqCnvtrd (uInt row, MFrequency refOrChanFreq, const Bool isRefFreq, const MeasFrame &measFrm, const MSDopplerColumns &msdopc, const MSSourceColumns &mssrcc, Double tolInHz) const
Bool matchChanFreq (uInt row, const Vector< Double > &chanFreqInHz, Double tolInHz) const
Bool matchIfConvChain (uInt row, Int ifChain) const
Bool matchTotalBandwidth (uInt row, Double bandwidthInHz, Double tolInHz) const
Bool matchNumChan (uInt row, Int nChan) const
Private Attributes
ROArrayColumn< Double > chanFreq_p
ROArrayColumn< Double > chanWidth_p
ROArrayColumn< Double > effectiveBW_p
ROScalarColumn< Bool > flagRow_p
ROScalarColumn< Int > freqGroup_p
ROScalarColumn< String > freqGroupName_p
ROScalarColumn< Int > ifConvChain_p
ROScalarColumn< Int > measFreqRef_p
ROScalarColumn< String > name_p
ROScalarColumn< Int > netSideband_p
ROScalarColumn< Int > numChan_p
ROScalarColumn< Double > refFrequency_p
ROArrayColumn< Double > resolution_p
ROScalarColumn< Double > totalBandwidth_p
ROArrayColumn< String > assocNature_p
ROArrayColumn< Int > assocSpwId_p
ROScalarColumn< Int > bbcNo_p
ROScalarColumn< Int > bbcSideband_p
ROScalarColumn< Int > dopplerId_p
ROScalarColumn< Int > receiverId_p
ROArrayMeasColumn< MFrequency > chanFreqMeas_p
ROScalarMeasColumn< MFrequency > refFrequencyMeas_p
ROArrayQuantColumn< Double > chanFreqQuant_p
ROArrayQuantColumn< Double > chanWidthQuant_p
ROArrayQuantColumn< Double > effectiveBWQuant_p
ROScalarQuantColumn< Double > refFrequencyQuant_p
ROArrayQuantColumn< Double > resolutionQuant_p
ROScalarQuantColumn< Double > totalBandwidthQuant_p
Detailed Description
A class to provide easy read-only access to MSASpectralWindow columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSSpectralWindow
ArrayColumn
ScalarColumn
Etymology
ROMSSpectralWindowColumns stands for Read-Only MeasurementSet SpectralWindow Table columns.
Synopsis
This class provides read-only access to the columns in the MSSpectralWindow Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 82 of file MSSpWindowColumns.h.
Constructor & Destructor Documentation
ROMSSpWindowColumns() [1/3]
casacore::ROMSSpWindowColumns::ROMSSpWindowColumns (const MSSpectralWindow & msSpWindow)
Create a columns object that accesses the data in the specified Table.
~ROMSSpWindowColumns()
casacore::ROMSSpWindowColumns::~ROMSSpWindowColumns ()
The destructor does nothing special.
ROMSSpWindowColumns() [2/3]
casacore::ROMSSpWindowColumns::ROMSSpWindowColumns () protected
ROMSSpWindowColumns() [3/3]
casacore::ROMSSpWindowColumns::ROMSSpWindowColumns (const ROMSSpWindowColumns &) private
Member Function Documentation
allMatchedSpw()
Vector<Int> casacore::ROMSSpWindowColumns::allMatchedSpw (const MFrequency & refFreq, uInt nChan, const Quantum< Double > & bandwidth, Int ifChain, const Quantum< Double > & tolerance) const
This is to check that the channels are matched individually and also if the spw is matched in reverse;.
Same as the above but returns all the possible match that it could find in the spectral window table.
assocNature()
const ROArrayColumn<String>& casacore::ROMSSpWindowColumns::assocNature () const inline
Access to optional columns.
Definition at line 128 of file MSSpWindowColumns.h.
References assocNature_p.
Referenced by casacore::MSSpWindowColumns::assocNature().
assocSpwId()
const ROArrayColumn<Int>& casacore::ROMSSpWindowColumns::assocSpwId () const inline
Definition at line 129 of file MSSpWindowColumns.h.
References assocSpwId_p.
Referenced by casacore::MSSpWindowColumns::assocSpwId().
attach()
void casacore::ROMSSpWindowColumns::attach (const MSSpectralWindow & msSpWindow) protected
attachOptionalCols()
void casacore::ROMSSpWindowColumns::attachOptionalCols (const MSSpectralWindow & msSpWindow) private
bbcNo()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::bbcNo () const inline
Definition at line 130 of file MSSpWindowColumns.h.
References bbcNo_p.
Referenced by casacore::MSSpWindowColumns::bbcNo().
bbcSideband()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::bbcSideband () const inline
Definition at line 131 of file MSSpWindowColumns.h.
References bbcSideband_p.
Referenced by casacore::MSSpWindowColumns::bbcSideband().
chanFreq()
const ROArrayColumn<Double>& casacore::ROMSSpWindowColumns::chanFreq () const inline
Access to columns.
Definition at line 93 of file MSSpWindowColumns.h.
References chanFreq_p.
Referenced by casacore::MSSpWindowColumns::chanFreq().
chanFreqMeas()
const ROArrayMeasColumn<MFrequency>& casacore::ROMSSpWindowColumns::chanFreqMeas () const inline
Definition at line 96 of file MSSpWindowColumns.h.
References chanFreqMeas_p.
Referenced by casacore::MSSpWindowColumns::chanFreqMeas().
chanFreqQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSpWindowColumns::chanFreqQuant () const inline
Definition at line 94 of file MSSpWindowColumns.h.
References chanFreqQuant_p.
Referenced by casacore::MSSpWindowColumns::chanFreqQuant().
chanWidth()
const ROArrayColumn<Double>& casacore::ROMSSpWindowColumns::chanWidth () const inline
Definition at line 98 of file MSSpWindowColumns.h.
References chanWidth_p.
Referenced by casacore::MSSpWindowColumns::chanWidth().
chanWidthQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSpWindowColumns::chanWidthQuant () const inline
Definition at line 99 of file MSSpWindowColumns.h.
References chanWidthQuant_p.
Referenced by casacore::MSSpWindowColumns::chanWidthQuant().
dopplerId()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::dopplerId () const inline
Definition at line 132 of file MSSpWindowColumns.h.
References dopplerId_p.
Referenced by casacore::MSSpWindowColumns::dopplerId().
effectiveBW()
const ROArrayColumn<Double>& casacore::ROMSSpWindowColumns::effectiveBW () const inline
Definition at line 101 of file MSSpWindowColumns.h.
References effectiveBW_p.
Referenced by casacore::MSSpWindowColumns::effectiveBW().
effectiveBWQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSpWindowColumns::effectiveBWQuant () const inline
Definition at line 102 of file MSSpWindowColumns.h.
References effectiveBWQuant_p.
Referenced by casacore::MSSpWindowColumns::effectiveBWQuant().
flagRow()
const ROScalarColumn<Bool>& casacore::ROMSSpWindowColumns::flagRow () const inline
Definition at line 107 of file MSSpWindowColumns.h.
References flagRow_p.
Referenced by casacore::MSSpWindowColumns::flagRow().
freqGroup()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::freqGroup () const inline
Definition at line 104 of file MSSpWindowColumns.h.
References freqGroup_p.
Referenced by casacore::MSSpWindowColumns::freqGroup().
freqGroupName()
const ROScalarColumn<String>& casacore::ROMSSpWindowColumns::freqGroupName () const inline
Definition at line 105 of file MSSpWindowColumns.h.
References freqGroupName_p.
Referenced by casacore::MSSpWindowColumns::freqGroupName().
ifConvChain()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::ifConvChain () const inline
Definition at line 106 of file MSSpWindowColumns.h.
References ifConvChain_p.
Referenced by casacore::MSSpWindowColumns::ifConvChain().
matchChanFreq()
Bool casacore::ROMSSpWindowColumns::matchChanFreq (uInt row, const Vector< Double > & chanFreqInHz, Double tolInHz) const private
matchIfConvChain()
Bool casacore::ROMSSpWindowColumns::matchIfConvChain (uInt row, Int ifChain) const private
matchNumChan()
Bool casacore::ROMSSpWindowColumns::matchNumChan (uInt row, Int nChan) const private
matchRefFreqCnvtrd()
Bool casacore::ROMSSpWindowColumns::matchRefFreqCnvtrd (uInt row, MFrequency refOrChanFreq, const Bool isRefFreq, const MeasFrame & measFrm, const MSDopplerColumns & msdopc, const MSSourceColumns & mssrcc, Double tolInHz) const private
matchRefFrequency()
Bool casacore::ROMSSpWindowColumns::matchRefFrequency (uInt row, MFrequency::Types refType, Double refFreqInHz, Double tolInHz) const private
matchSpw() [1/3]
Int casacore::ROMSSpWindowColumns::matchSpw (const MFrequency & refFreq, uInt nChan, const Quantum< Double > & bandwidth, Int ifChain, const Quantum< Double > & tolerance, Int tryRow = -1) const
returns the last row that contains a spectral window that has the specified reference frequency, number of channels, total-bandwidth and IF conversion chain.
All frequencies need to match within the specified tolerance. Both the totalBandwidth & the tolerance arguments must have the same dimensions as the Hz and an AipsError exception is thrown, in debug mode, if the dimensions are wrong. In addition to the numerical values the frequency reference frame is checked and needs to match the value in the MEAS_FREQ_REF column. No conversions to other reference frames are done. Will only try to match on rows where FLAG_ROW is false. If tryRow is set to a non-negative value then that row is checked first to see if it matches. An AIpsError exception is thrown if tryRow is bigger than the number of rows in the Table. Returns -1 if no match could be found.
matchSpw() [2/3]
Int casacore::ROMSSpWindowColumns::matchSpw (const MFrequency & refFreq, const MFrequency & chanFreq1, const MeasFrame & measFrm, const MSDopplerColumns & msdopc, const MSSourceColumns & mssrcc, uInt nChan, const Quantum< Double > & bandwidth, Int ifChain, const Quantum< Double > & tolerance, Int tryRow = -1) const
Similar to above, but also pass in the frame info.
matchSpw() [3/3]
Int casacore::ROMSSpWindowColumns::matchSpw (const MFrequency & refFreq, uInt nChan, const Quantum< Double > & bandwidth, Int ifChain, const Quantum< Double > & tolerance, Vector< Double > & otherFreqs, Bool & reversed) const
This version does a channel to channel match too and also return the reversed if it matches but the channels are in inverse order like an upper or lower side band having same characteristics.
matchTotalBandwidth()
Bool casacore::ROMSSpWindowColumns::matchTotalBandwidth (uInt row, Double bandwidthInHz, Double tolInHz) const private
measFreqRef()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::measFreqRef () const inline
Definition at line 108 of file MSSpWindowColumns.h.
References measFreqRef_p.
Referenced by casacore::MSSpWindowColumns::measFreqRef().
name()
const ROScalarColumn<String>& casacore::ROMSSpWindowColumns::name () const inline
Definition at line 109 of file MSSpWindowColumns.h.
References name_p.
Referenced by casacore::MSSpWindowColumns::name().
netSideband()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::netSideband () const inline
Definition at line 110 of file MSSpWindowColumns.h.
References netSideband_p.
Referenced by casacore::MSSpWindowColumns::netSideband().
nrow()
uInt casacore::ROMSSpWindowColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 137 of file MSSpWindowColumns.h.
References chanFreq_p.
numChan()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::numChan () const inline
Definition at line 111 of file MSSpWindowColumns.h.
References numChan_p.
Referenced by casacore::MSSpWindowColumns::numChan().
operator=()
ROMSSpWindowColumns& casacore::ROMSSpWindowColumns::operator= (const ROMSSpWindowColumns &) private
receiverId()
const ROScalarColumn<Int>& casacore::ROMSSpWindowColumns::receiverId () const inline
Definition at line 133 of file MSSpWindowColumns.h.
References receiverId_p.
Referenced by casacore::MSSpWindowColumns::receiverId().
refFrequency()
const ROScalarColumn<Double>& casacore::ROMSSpWindowColumns::refFrequency () const inline
Definition at line 112 of file MSSpWindowColumns.h.
References refFrequency_p.
Referenced by casacore::MSSpWindowColumns::refFrequency().
refFrequencyMeas()
const ROScalarMeasColumn<MFrequency>& casacore::ROMSSpWindowColumns::refFrequencyMeas () const inline
Definition at line 115 of file MSSpWindowColumns.h.
References refFrequencyMeas_p.
Referenced by casacore::MSSpWindowColumns::refFrequencyMeas().
refFrequencyQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSSpWindowColumns::refFrequencyQuant () const inline
Definition at line 113 of file MSSpWindowColumns.h.
References refFrequencyQuant_p.
Referenced by casacore::MSSpWindowColumns::refFrequencyQuant().
resolution()
const ROArrayColumn<Double>& casacore::ROMSSpWindowColumns::resolution () const inline
Definition at line 117 of file MSSpWindowColumns.h.
References resolution_p.
Referenced by casacore::MSSpWindowColumns::resolution().
resolutionQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSpWindowColumns::resolutionQuant () const inline
Definition at line 118 of file MSSpWindowColumns.h.
References resolutionQuant_p.
Referenced by casacore::MSSpWindowColumns::resolutionQuant().
totalBandwidth()
const ROScalarColumn<Double>& casacore::ROMSSpWindowColumns::totalBandwidth () const inline
Definition at line 120 of file MSSpWindowColumns.h.
References totalBandwidth_p.
Referenced by casacore::MSSpWindowColumns::totalBandwidth().
totalBandwidthQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSSpWindowColumns::totalBandwidthQuant () const inline
Definition at line 122 of file MSSpWindowColumns.h.
References totalBandwidthQuant_p.
Referenced by casacore::MSSpWindowColumns::totalBandwidthQuant().
Member Data Documentation
assocNature_p
ROArrayColumn<String> casacore::ROMSSpWindowColumns::assocNature_p private
Definition at line 225 of file MSSpWindowColumns.h.
Referenced by assocNature().
assocSpwId_p
ROArrayColumn<Int> casacore::ROMSSpWindowColumns::assocSpwId_p private
Definition at line 226 of file MSSpWindowColumns.h.
Referenced by assocSpwId().
bbcNo_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::bbcNo_p private
Definition at line 227 of file MSSpWindowColumns.h.
Referenced by bbcNo().
bbcSideband_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::bbcSideband_p private
Definition at line 228 of file MSSpWindowColumns.h.
Referenced by bbcSideband().
chanFreq_p
ROArrayColumn<Double> casacore::ROMSSpWindowColumns::chanFreq_p private
Definition at line 210 of file MSSpWindowColumns.h.
Referenced by chanFreq(), and nrow().
chanFreqMeas_p
ROArrayMeasColumn<MFrequency> casacore::ROMSSpWindowColumns::chanFreqMeas_p private
Definition at line 233 of file MSSpWindowColumns.h.
Referenced by chanFreqMeas().
chanFreqQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSpWindowColumns::chanFreqQuant_p private
Definition at line 237 of file MSSpWindowColumns.h.
Referenced by chanFreqQuant().
chanWidth_p
ROArrayColumn<Double> casacore::ROMSSpWindowColumns::chanWidth_p private
Definition at line 211 of file MSSpWindowColumns.h.
Referenced by chanWidth().
chanWidthQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSpWindowColumns::chanWidthQuant_p private
Definition at line 238 of file MSSpWindowColumns.h.
Referenced by chanWidthQuant().
dopplerId_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::dopplerId_p private
Definition at line 229 of file MSSpWindowColumns.h.
Referenced by dopplerId().
effectiveBW_p
ROArrayColumn<Double> casacore::ROMSSpWindowColumns::effectiveBW_p private
Definition at line 212 of file MSSpWindowColumns.h.
Referenced by effectiveBW().
effectiveBWQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSpWindowColumns::effectiveBWQuant_p private
Definition at line 239 of file MSSpWindowColumns.h.
Referenced by effectiveBWQuant().
flagRow_p
ROScalarColumn<Bool> casacore::ROMSSpWindowColumns::flagRow_p private
Definition at line 213 of file MSSpWindowColumns.h.
Referenced by flagRow().
freqGroup_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::freqGroup_p private
Definition at line 214 of file MSSpWindowColumns.h.
Referenced by freqGroup().
freqGroupName_p
ROScalarColumn<String> casacore::ROMSSpWindowColumns::freqGroupName_p private
Definition at line 215 of file MSSpWindowColumns.h.
Referenced by freqGroupName().
ifConvChain_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::ifConvChain_p private
Definition at line 216 of file MSSpWindowColumns.h.
Referenced by ifConvChain().
measFreqRef_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::measFreqRef_p private
Definition at line 217 of file MSSpWindowColumns.h.
Referenced by measFreqRef().
name_p
ROScalarColumn<String> casacore::ROMSSpWindowColumns::name_p private
Definition at line 218 of file MSSpWindowColumns.h.
Referenced by name().
netSideband_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::netSideband_p private
Definition at line 219 of file MSSpWindowColumns.h.
Referenced by netSideband().
numChan_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::numChan_p private
Definition at line 220 of file MSSpWindowColumns.h.
Referenced by numChan().
receiverId_p
ROScalarColumn<Int> casacore::ROMSSpWindowColumns::receiverId_p private
Definition at line 230 of file MSSpWindowColumns.h.
Referenced by receiverId().
refFrequency_p
ROScalarColumn<Double> casacore::ROMSSpWindowColumns::refFrequency_p private
Definition at line 221 of file MSSpWindowColumns.h.
Referenced by refFrequency().
refFrequencyMeas_p
ROScalarMeasColumn<MFrequency> casacore::ROMSSpWindowColumns::refFrequencyMeas_p private
Definition at line 234 of file MSSpWindowColumns.h.
Referenced by refFrequencyMeas().
refFrequencyQuant_p
ROScalarQuantColumn<Double> casacore::ROMSSpWindowColumns::refFrequencyQuant_p private
Definition at line 240 of file MSSpWindowColumns.h.
Referenced by refFrequencyQuant().
resolution_p
ROArrayColumn<Double> casacore::ROMSSpWindowColumns::resolution_p private
Definition at line 222 of file MSSpWindowColumns.h.
Referenced by resolution().
resolutionQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSpWindowColumns::resolutionQuant_p private
Definition at line 241 of file MSSpWindowColumns.h.
Referenced by resolutionQuant().
totalBandwidth_p
ROScalarColumn<Double> casacore::ROMSSpWindowColumns::totalBandwidth_p private
Definition at line 223 of file MSSpWindowColumns.h.
Referenced by totalBandwidth().
totalBandwidthQuant_p
ROScalarQuantColumn<Double> casacore::ROMSSpWindowColumns::totalBandwidthQuant_p private
Definition at line 242 of file MSSpWindowColumns.h.
Referenced by totalBandwidthQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSSpWindowColumns.h