casacore: casacore::TaQLNodeResult Class Reference
casacore::TaQLNodeResult Class Reference
tables package (libcasa_tables) » TaQL_module » TaQL_module_internal_classes
Envelope class to hold the result of a visit to the node tree.
#include <TaQLNodeResult.h>
Public Member Functions
TaQLNodeResult ()
Default constructor has no letter.
TaQLNodeResult (TaQLNodeResultRep *rep)
Take the given letter and increment its reference count.
TaQLNodeResult (const TaQLNodeResult &that)
Copy constructor (reference semantics).
TaQLNodeResult & operator= (const TaQLNodeResult &that)
Assignment (reference semantics).
~TaQLNodeResult ()
Destructor decrements the reference count.
Bool isValid () const
Does the envelope hold a letter?
const TaQLNodeResultRep * getRep () const
Get the actual underlying object.
Private Attributes
TaQLNodeResultRep * itsRep
Detailed Description
Envelope class to hold the result of a visit to the node tree.
Intended use:
Internal
Review Status
Test programs:
tTableGram
Prerequisite
TaQLNodeVisitor
Note 199 describing TaQL
Synopsis
TaQLNodeResult is the envelope class for classes holding values filled by visitors to the raw TaQL parse tree. Visitors are classes derived from TaQLNodeVisitor which traverse the parse tree. The counted referenced letter base class for the envelope is class TaQLNodeResultRep.
Definition at line 123 of file TaQLNodeResult.h.
Constructor & Destructor Documentation
TaQLNodeResult() [1/3]
casacore::TaQLNodeResult::TaQLNodeResult () inline
Default constructor has no letter.
Definition at line 127 of file TaQLNodeResult.h.
TaQLNodeResult() [2/3]
casacore::TaQLNodeResult::TaQLNodeResult (TaQLNodeResultRep * rep) inline
Take the given letter and increment its reference count.
Definition at line 131 of file TaQLNodeResult.h.
References itsRep, and casacore::TaQLNodeResultRep::link().
TaQLNodeResult() [3/3]
casacore::TaQLNodeResult::TaQLNodeResult (const TaQLNodeResult & that) inline
Copy constructor (reference semantics).
Definition at line 135 of file TaQLNodeResult.h.
References itsRep, and casacore::TaQLNodeResultRep::link().
~TaQLNodeResult()
casacore::TaQLNodeResult::~TaQLNodeResult () inline
Destructor decrements the reference count.
The letter is deleted if no more references.
Definition at line 149 of file TaQLNodeResult.h.
References itsRep, and casacore::TaQLNodeResultRep::unlink().
Member Function Documentation
getRep()
const TaQLNodeResultRep* casacore::TaQLNodeResult::getRep () const inline
Get the actual underlying object.
Definition at line 161 of file TaQLNodeResult.h.
References itsRep.
Referenced by casacore::TaQLNodeHandler::getHR().
isValid()
Bool casacore::TaQLNodeResult::isValid () const inline
Does the envelope hold a letter?
Definition at line 153 of file TaQLNodeResult.h.
References itsRep.
operator=()
TaQLNodeResult& casacore::TaQLNodeResult::operator= (const TaQLNodeResult & that) inline
Assignment (reference semantics).
Definition at line 139 of file TaQLNodeResult.h.
References itsRep, casacore::TaQLNodeResultRep::link(), and casacore::TaQLNodeResultRep::unlink().
Member Data Documentation
itsRep
TaQLNodeResultRep* casacore::TaQLNodeResult::itsRep private
Definition at line 157 of file TaQLNodeResult.h.
Referenced by getRep(), isValid(), operator=(), TaQLNodeResult(), and ~TaQLNodeResult().
The documentation for this class was generated from the following file:
tables/TaQL/TaQLNodeResult.h