casacore: casacore::MSSpWindowColumns Class Reference
casacore::MSSpWindowColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSSpectralWindow columns.
#include <MSSpWindowColumns.h>
Public Member Functions
MSSpWindowColumns (MSSpectralWindow &msSpWindow)
Create a columns object that accesses the data in the specified Table.
~MSSpWindowColumns ()
The destructor does nothing special.
ArrayColumn< Double > & chanFreq ()
Read-write access to required columns.
ArrayMeasColumn< MFrequency > & chanFreqMeas ()
ArrayQuantColumn< Double > & chanFreqQuant ()
ArrayColumn< Double > & chanWidth ()
ArrayQuantColumn< Double > & chanWidthQuant ()
ArrayColumn< Double > & effectiveBW ()
ArrayQuantColumn< Double > & effectiveBWQuant ()
ScalarColumn< Bool > & flagRow ()
ScalarColumn< Int > & freqGroup ()
ScalarColumn< String > & freqGroupName ()
ScalarColumn< Int > & ifConvChain ()
ScalarColumn< Int > & measFreqRef ()
ScalarColumn< String > & name ()
ScalarColumn< Int > & netSideband ()
ScalarColumn< Int > & numChan ()
ScalarColumn< Double > & refFrequency ()
ScalarQuantColumn< Double > & refFrequencyQuant ()
ScalarMeasColumn< MFrequency > & refFrequencyMeas ()
ArrayColumn< Double > & resolution ()
ArrayQuantColumn< Double > & resolutionQuant ()
ScalarColumn< Double > & totalBandwidth ()
ScalarQuantColumn< Double > & totalBandwidthQuant ()
ArrayColumn< String > & assocNature ()
Read-write access to optional columns.
ArrayColumn< Int > & assocSpwId ()
ScalarColumn< Int > & bbcNo ()
ScalarColumn< Int > & bbcSideband ()
ScalarColumn< Int > & dopplerId ()
ScalarColumn< Int > & receiverId ()
const ROArrayColumn< Double > & chanFreq () const
Read-only access to required columns.
const ROArrayQuantColumn< Double > & chanFreqQuant () const
const ROArrayMeasColumn< MFrequency > & chanFreqMeas () const
const ROArrayColumn< Double > & chanWidth () const
const ROArrayQuantColumn< Double > & chanWidthQuant () const
const ROArrayColumn< Double > & effectiveBW () const
const ROArrayQuantColumn< Double > & effectiveBWQuant () const
const ROScalarColumn< Int > & freqGroup () const
const ROScalarColumn< String > & freqGroupName () const
const ROScalarColumn< Int > & ifConvChain () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Int > & measFreqRef () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & netSideband () const
const ROScalarColumn< Int > & numChan () const
const ROScalarColumn< Double > & refFrequency () const
const ROScalarQuantColumn< Double > & refFrequencyQuant () const
const ROScalarMeasColumn< MFrequency > & refFrequencyMeas () const
const ROArrayColumn< Double > & resolution () const
const ROArrayQuantColumn< Double > & resolutionQuant () const
const ROScalarColumn< Double > & totalBandwidth () const
const ROScalarQuantColumn< Double > & totalBandwidthQuant () const
const ROArrayColumn< String > & assocNature () const
Read-only access to optional columns.
const ROArrayColumn< Int > & assocSpwId () const
const ROScalarColumn< Int > & bbcNo () const
const ROScalarColumn< Int > & bbcSideband () const
const ROScalarColumn< Int > & dopplerId () const
const ROScalarColumn< Int > & receiverId () const
Public Member Functions inherited from casacore::ROMSSpWindowColumns
ROMSSpWindowColumns (const MSSpectralWindow &msSpWindow)
Create a columns object that accesses the data in the specified Table.
~ROMSSpWindowColumns ()
The destructor does nothing special.
const ROArrayColumn< Double > & chanFreq () const
Access to columns.
const ROArrayQuantColumn< Double > & chanFreqQuant () const
const ROArrayMeasColumn< MFrequency > & chanFreqMeas () const
const ROArrayColumn< Double > & chanWidth () const
const ROArrayQuantColumn< Double > & chanWidthQuant () const
const ROArrayColumn< Double > & effectiveBW () const
const ROArrayQuantColumn< Double > & effectiveBWQuant () const
const ROScalarColumn< Int > & freqGroup () const
const ROScalarColumn< String > & freqGroupName () const
const ROScalarColumn< Int > & ifConvChain () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Int > & measFreqRef () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & netSideband () const
const ROScalarColumn< Int > & numChan () const
const ROScalarColumn< Double > & refFrequency () const
const ROScalarQuantColumn< Double > & refFrequencyQuant () const
const ROScalarMeasColumn< MFrequency > & refFrequencyMeas () const
const ROArrayColumn< Double > & resolution () const
const ROArrayQuantColumn< Double > & resolutionQuant () const
const ROScalarColumn< Double > & totalBandwidth () const
const ROScalarQuantColumn< Double > & totalBandwidthQuant () const
const ROArrayColumn< String > & assocNature () const
Access to optional columns.
const ROArrayColumn< Int > & assocSpwId () const
const ROScalarColumn< Int > & bbcNo () const
const ROScalarColumn< Int > & bbcSideband () const
const ROScalarColumn< Int > & dopplerId () const
const ROScalarColumn< Int > & receiverId () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int matchSpw (const MFrequency &refFreq, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance, Int tryRow=-1) const
returns the last row that contains a spectral window that has the specified reference frequency, number of channels, total-bandwidth and IF conversion chain.
Int matchSpw (const MFrequency &refFreq, const MFrequency &chanFreq1, const MeasFrame &measFrm, const MSDopplerColumns &msdopc, const MSSourceColumns &mssrcc, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance, Int tryRow=-1) const
Similar to above, but also pass in the frame info.
Vector< Int > allMatchedSpw (const MFrequency &refFreq, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance) const
This is to check that the channels are matched individually and also if the spw is matched in reverse;.
Int matchSpw (const MFrequency &refFreq, uInt nChan, const Quantum< Double > &bandwidth, Int ifChain, const Quantum< Double > &tolerance, Vector< Double > &otherFreqs, Bool &reversed) const
This version does a channel to channel match too and also return the reversed if it matches but the channels are in inverse order like an upper or lower side band having same characteristics.
Protected Member Functions
MSSpWindowColumns ()
void attach (MSSpectralWindow &msSpWindow)
Protected Member Functions inherited from casacore::ROMSSpWindowColumns
ROMSSpWindowColumns ()
void attach (const MSSpectralWindow &msSpWindow)
Private Member Functions
MSSpWindowColumns (const MSSpWindowColumns &)
MSSpWindowColumns & operator= (const MSSpWindowColumns &)
void attachOptionalCols (MSSpectralWindow &msSpWindow)
Private Attributes
ArrayColumn< Double > chanFreq_p
ArrayColumn< Double > chanWidth_p
ArrayColumn< Double > effectiveBW_p
ScalarColumn< Bool > flagRow_p
ScalarColumn< Int > freqGroup_p
ScalarColumn< String > freqGroupName_p
ScalarColumn< Int > ifConvChain_p
ScalarColumn< Int > measFreqRef_p
ScalarColumn< String > name_p
ScalarColumn< Int > netSideband_p
ScalarColumn< Int > numChan_p
ScalarColumn< Double > refFrequency_p
ArrayColumn< Double > resolution_p
ScalarColumn< Double > totalBandwidth_p
ArrayColumn< String > assocNature_p
ArrayColumn< Int > assocSpwId_p
ScalarColumn< Int > bbcNo_p
ScalarColumn< Int > bbcSideband_p
ScalarColumn< Int > dopplerId_p
ScalarColumn< Int > receiverId_p
ArrayMeasColumn< MFrequency > chanFreqMeas_p
ScalarMeasColumn< MFrequency > refFrequencyMeas_p
ArrayQuantColumn< Double > chanFreqQuant_p
ArrayQuantColumn< Double > chanWidthQuant_p
ArrayQuantColumn< Double > effectiveBWQuant_p
ScalarQuantColumn< Double > refFrequencyQuant_p
ArrayQuantColumn< Double > resolutionQuant_p
ScalarQuantColumn< Double > totalBandwidthQuant_p
Detailed Description
A class to provide easy read-write access to MSSpectralWindow columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSSpectralWindow
ArrayColumn
ScalarColumn
Etymology
MSSpectralWindowColumns stands for MeasurementSet SpectralWindow Table columns.
Synopsis
This class provides access to the columns in the MSSpectralWindow Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 283 of file MSSpWindowColumns.h.
Constructor & Destructor Documentation
MSSpWindowColumns() [1/3]
casacore::MSSpWindowColumns::MSSpWindowColumns (MSSpectralWindow & msSpWindow)
Create a columns object that accesses the data in the specified Table.
~MSSpWindowColumns()
casacore::MSSpWindowColumns::~MSSpWindowColumns ()
The destructor does nothing special.
MSSpWindowColumns() [2/3]
casacore::MSSpWindowColumns::MSSpWindowColumns () protected
MSSpWindowColumns() [3/3]
casacore::MSSpWindowColumns::MSSpWindowColumns (const MSSpWindowColumns &) private
Member Function Documentation
assocNature() [1/2]
ArrayColumn<String>& casacore::MSSpWindowColumns::assocNature () inline
Read-write access to optional columns.
Definition at line 321 of file MSSpWindowColumns.h.
References assocNature_p.
assocNature() [2/2]
const ROArrayColumn<String>& casacore::MSSpWindowColumns::assocNature () const inline
Read-only access to optional columns.
Definition at line 379 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::assocNature().
assocSpwId() [1/2]
ArrayColumn<Int>& casacore::MSSpWindowColumns::assocSpwId () inline
Definition at line 322 of file MSSpWindowColumns.h.
References assocSpwId_p.
assocSpwId() [2/2]
const ROArrayColumn<Int>& casacore::MSSpWindowColumns::assocSpwId () const inline
Definition at line 381 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::assocSpwId().
attach()
void casacore::MSSpWindowColumns::attach (MSSpectralWindow & msSpWindow) protected
attachOptionalCols()
void casacore::MSSpWindowColumns::attachOptionalCols (MSSpectralWindow & msSpWindow) private
bbcNo() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::bbcNo () inline
Definition at line 323 of file MSSpWindowColumns.h.
References bbcNo_p.
bbcNo() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::bbcNo () const inline
Definition at line 383 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::bbcNo().
bbcSideband() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::bbcSideband () inline
Definition at line 324 of file MSSpWindowColumns.h.
References bbcSideband_p.
bbcSideband() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::bbcSideband () const inline
Definition at line 385 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::bbcSideband().
chanFreq() [1/2]
ArrayColumn<Double>& casacore::MSSpWindowColumns::chanFreq () inline
Read-write access to required columns.
Definition at line 294 of file MSSpWindowColumns.h.
References chanFreq_p.
chanFreq() [2/2]
const ROArrayColumn<Double>& casacore::MSSpWindowColumns::chanFreq () const inline
Read-only access to required columns.
Definition at line 331 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::chanFreq().
chanFreqMeas() [1/2]
ArrayMeasColumn<MFrequency>& casacore::MSSpWindowColumns::chanFreqMeas () inline
Definition at line 295 of file MSSpWindowColumns.h.
References chanFreqMeas_p.
chanFreqMeas() [2/2]
const ROArrayMeasColumn<MFrequency>& casacore::MSSpWindowColumns::chanFreqMeas () const inline
Definition at line 335 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::chanFreqMeas().
chanFreqQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSpWindowColumns::chanFreqQuant () inline
Definition at line 296 of file MSSpWindowColumns.h.
References chanFreqQuant_p.
chanFreqQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSpWindowColumns::chanFreqQuant () const inline
Definition at line 333 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::chanFreqQuant().
chanWidth() [1/2]
ArrayColumn<Double>& casacore::MSSpWindowColumns::chanWidth () inline
Definition at line 297 of file MSSpWindowColumns.h.
References chanWidth_p.
chanWidth() [2/2]
const ROArrayColumn<Double>& casacore::MSSpWindowColumns::chanWidth () const inline
Definition at line 337 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::chanWidth().
chanWidthQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSpWindowColumns::chanWidthQuant () inline
Definition at line 298 of file MSSpWindowColumns.h.
References chanWidthQuant_p.
chanWidthQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSpWindowColumns::chanWidthQuant () const inline
Definition at line 339 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::chanWidthQuant().
dopplerId() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::dopplerId () inline
Definition at line 325 of file MSSpWindowColumns.h.
References dopplerId_p.
dopplerId() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::dopplerId () const inline
Definition at line 387 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::dopplerId().
effectiveBW() [1/2]
ArrayColumn<Double>& casacore::MSSpWindowColumns::effectiveBW () inline
Definition at line 299 of file MSSpWindowColumns.h.
References effectiveBW_p.
effectiveBW() [2/2]
const ROArrayColumn<Double>& casacore::MSSpWindowColumns::effectiveBW () const inline
Definition at line 341 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::effectiveBW().
effectiveBWQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSpWindowColumns::effectiveBWQuant () inline
Definition at line 300 of file MSSpWindowColumns.h.
References effectiveBWQuant_p.
effectiveBWQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSpWindowColumns::effectiveBWQuant () const inline
Definition at line 343 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::effectiveBWQuant().
flagRow() [1/2]
ScalarColumn<Bool>& casacore::MSSpWindowColumns::flagRow () inline
Definition at line 301 of file MSSpWindowColumns.h.
References flagRow_p.
flagRow() [2/2]
const ROScalarColumn<Bool>& casacore::MSSpWindowColumns::flagRow () const inline
Definition at line 351 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::flagRow().
freqGroup() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::freqGroup () inline
Definition at line 302 of file MSSpWindowColumns.h.
References freqGroup_p.
freqGroup() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::freqGroup () const inline
Definition at line 345 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::freqGroup().
freqGroupName() [1/2]
ScalarColumn<String>& casacore::MSSpWindowColumns::freqGroupName () inline
Definition at line 303 of file MSSpWindowColumns.h.
References freqGroupName_p.
freqGroupName() [2/2]
const ROScalarColumn<String>& casacore::MSSpWindowColumns::freqGroupName () const inline
Definition at line 347 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::freqGroupName().
ifConvChain() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::ifConvChain () inline
Definition at line 304 of file MSSpWindowColumns.h.
References ifConvChain_p.
ifConvChain() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::ifConvChain () const inline
Definition at line 349 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::ifConvChain().
measFreqRef() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::measFreqRef () inline
Definition at line 305 of file MSSpWindowColumns.h.
References measFreqRef_p.
measFreqRef() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::measFreqRef () const inline
Definition at line 353 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::measFreqRef().
name() [1/2]
ScalarColumn<String>& casacore::MSSpWindowColumns::name () inline
Definition at line 306 of file MSSpWindowColumns.h.
References name_p.
name() [2/2]
const ROScalarColumn<String>& casacore::MSSpWindowColumns::name () const inline
Definition at line 355 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::name().
netSideband() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::netSideband () inline
Definition at line 307 of file MSSpWindowColumns.h.
References netSideband_p.
netSideband() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::netSideband () const inline
Definition at line 357 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::netSideband().
numChan() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::numChan () inline
Definition at line 308 of file MSSpWindowColumns.h.
References numChan_p.
numChan() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::numChan () const inline
Definition at line 359 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::numChan().
operator=()
MSSpWindowColumns& casacore::MSSpWindowColumns::operator= (const MSSpWindowColumns &) private
receiverId() [1/2]
ScalarColumn<Int>& casacore::MSSpWindowColumns::receiverId () inline
Definition at line 326 of file MSSpWindowColumns.h.
References receiverId_p.
receiverId() [2/2]
const ROScalarColumn<Int>& casacore::MSSpWindowColumns::receiverId () const inline
Definition at line 389 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::receiverId().
refFrequency() [1/2]
ScalarColumn<Double>& casacore::MSSpWindowColumns::refFrequency () inline
Definition at line 309 of file MSSpWindowColumns.h.
References refFrequency_p.
refFrequency() [2/2]
const ROScalarColumn<Double>& casacore::MSSpWindowColumns::refFrequency () const inline
Definition at line 361 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::refFrequency().
refFrequencyMeas() [1/2]
ScalarMeasColumn<MFrequency>& casacore::MSSpWindowColumns::refFrequencyMeas () inline
Definition at line 311 of file MSSpWindowColumns.h.
References refFrequencyMeas_p.
refFrequencyMeas() [2/2]
const ROScalarMeasColumn<MFrequency>& casacore::MSSpWindowColumns::refFrequencyMeas () const inline
Definition at line 365 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::refFrequencyMeas().
refFrequencyQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSSpWindowColumns::refFrequencyQuant () inline
Definition at line 310 of file MSSpWindowColumns.h.
References refFrequencyQuant_p.
refFrequencyQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSSpWindowColumns::refFrequencyQuant () const inline
Definition at line 363 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::refFrequencyQuant().
resolution() [1/2]
ArrayColumn<Double>& casacore::MSSpWindowColumns::resolution () inline
Definition at line 312 of file MSSpWindowColumns.h.
References resolution_p.
resolution() [2/2]
const ROArrayColumn<Double>& casacore::MSSpWindowColumns::resolution () const inline
Definition at line 367 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::resolution().
resolutionQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSpWindowColumns::resolutionQuant () inline
Definition at line 313 of file MSSpWindowColumns.h.
References resolutionQuant_p.
resolutionQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSpWindowColumns::resolutionQuant () const inline
Definition at line 369 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::resolutionQuant().
totalBandwidth() [1/2]
ScalarColumn<Double>& casacore::MSSpWindowColumns::totalBandwidth () inline
Definition at line 314 of file MSSpWindowColumns.h.
References totalBandwidth_p.
totalBandwidth() [2/2]
const ROScalarColumn<Double>& casacore::MSSpWindowColumns::totalBandwidth () const inline
Definition at line 371 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::totalBandwidth().
totalBandwidthQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSSpWindowColumns::totalBandwidthQuant () inline
Definition at line 315 of file MSSpWindowColumns.h.
References totalBandwidthQuant_p.
totalBandwidthQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSSpWindowColumns::totalBandwidthQuant () const inline
Definition at line 373 of file MSSpWindowColumns.h.
References casacore::ROMSSpWindowColumns::totalBandwidthQuant().
Member Data Documentation
assocNature_p
ArrayColumn<String> casacore::MSSpWindowColumns::assocNature_p private
Definition at line 426 of file MSSpWindowColumns.h.
Referenced by assocNature().
assocSpwId_p
ArrayColumn<Int> casacore::MSSpWindowColumns::assocSpwId_p private
Definition at line 427 of file MSSpWindowColumns.h.
Referenced by assocSpwId().
bbcNo_p
ScalarColumn<Int> casacore::MSSpWindowColumns::bbcNo_p private
Definition at line 428 of file MSSpWindowColumns.h.
Referenced by bbcNo().
bbcSideband_p
ScalarColumn<Int> casacore::MSSpWindowColumns::bbcSideband_p private
Definition at line 429 of file MSSpWindowColumns.h.
Referenced by bbcSideband().
chanFreq_p
ArrayColumn<Double> casacore::MSSpWindowColumns::chanFreq_p private
Definition at line 411 of file MSSpWindowColumns.h.
Referenced by chanFreq().
chanFreqMeas_p
ArrayMeasColumn<MFrequency> casacore::MSSpWindowColumns::chanFreqMeas_p private
Definition at line 434 of file MSSpWindowColumns.h.
Referenced by chanFreqMeas().
chanFreqQuant_p
ArrayQuantColumn<Double> casacore::MSSpWindowColumns::chanFreqQuant_p private
Definition at line 438 of file MSSpWindowColumns.h.
Referenced by chanFreqQuant().
chanWidth_p
ArrayColumn<Double> casacore::MSSpWindowColumns::chanWidth_p private
Definition at line 412 of file MSSpWindowColumns.h.
Referenced by chanWidth().
chanWidthQuant_p
ArrayQuantColumn<Double> casacore::MSSpWindowColumns::chanWidthQuant_p private
Definition at line 439 of file MSSpWindowColumns.h.
Referenced by chanWidthQuant().
dopplerId_p
ScalarColumn<Int> casacore::MSSpWindowColumns::dopplerId_p private
Definition at line 430 of file MSSpWindowColumns.h.
Referenced by dopplerId().
effectiveBW_p
ArrayColumn<Double> casacore::MSSpWindowColumns::effectiveBW_p private
Definition at line 413 of file MSSpWindowColumns.h.
Referenced by effectiveBW().
effectiveBWQuant_p
ArrayQuantColumn<Double> casacore::MSSpWindowColumns::effectiveBWQuant_p private
Definition at line 440 of file MSSpWindowColumns.h.
Referenced by effectiveBWQuant().
flagRow_p
ScalarColumn<Bool> casacore::MSSpWindowColumns::flagRow_p private
Definition at line 414 of file MSSpWindowColumns.h.
Referenced by flagRow().
freqGroup_p
ScalarColumn<Int> casacore::MSSpWindowColumns::freqGroup_p private
Definition at line 415 of file MSSpWindowColumns.h.
Referenced by freqGroup().
freqGroupName_p
ScalarColumn<String> casacore::MSSpWindowColumns::freqGroupName_p private
Definition at line 416 of file MSSpWindowColumns.h.
Referenced by freqGroupName().
ifConvChain_p
ScalarColumn<Int> casacore::MSSpWindowColumns::ifConvChain_p private
Definition at line 417 of file MSSpWindowColumns.h.
Referenced by ifConvChain().
measFreqRef_p
ScalarColumn<Int> casacore::MSSpWindowColumns::measFreqRef_p private
Definition at line 418 of file MSSpWindowColumns.h.
Referenced by measFreqRef().
name_p
ScalarColumn<String> casacore::MSSpWindowColumns::name_p private
Definition at line 419 of file MSSpWindowColumns.h.
Referenced by name().
netSideband_p
ScalarColumn<Int> casacore::MSSpWindowColumns::netSideband_p private
Definition at line 420 of file MSSpWindowColumns.h.
Referenced by netSideband().
numChan_p
ScalarColumn<Int> casacore::MSSpWindowColumns::numChan_p private
Definition at line 421 of file MSSpWindowColumns.h.
Referenced by numChan().
receiverId_p
ScalarColumn<Int> casacore::MSSpWindowColumns::receiverId_p private
Definition at line 431 of file MSSpWindowColumns.h.
Referenced by receiverId().
refFrequency_p
ScalarColumn<Double> casacore::MSSpWindowColumns::refFrequency_p private
Definition at line 422 of file MSSpWindowColumns.h.
Referenced by refFrequency().
refFrequencyMeas_p
ScalarMeasColumn<MFrequency> casacore::MSSpWindowColumns::refFrequencyMeas_p private
Definition at line 435 of file MSSpWindowColumns.h.
Referenced by refFrequencyMeas().
refFrequencyQuant_p
ScalarQuantColumn<Double> casacore::MSSpWindowColumns::refFrequencyQuant_p private
Definition at line 441 of file MSSpWindowColumns.h.
Referenced by refFrequencyQuant().
resolution_p
ArrayColumn<Double> casacore::MSSpWindowColumns::resolution_p private
Definition at line 423 of file MSSpWindowColumns.h.
Referenced by resolution().
resolutionQuant_p
ArrayQuantColumn<Double> casacore::MSSpWindowColumns::resolutionQuant_p private
Definition at line 442 of file MSSpWindowColumns.h.
Referenced by resolutionQuant().
totalBandwidth_p
ScalarColumn<Double> casacore::MSSpWindowColumns::totalBandwidth_p private
Definition at line 424 of file MSSpWindowColumns.h.
Referenced by totalBandwidth().
totalBandwidthQuant_p
ScalarQuantColumn<Double> casacore::MSSpWindowColumns::totalBandwidthQuant_p private
Definition at line 443 of file MSSpWindowColumns.h.
Referenced by totalBandwidthQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSSpWindowColumns.h