casacore: casacore::HDF5Object Class Reference
casacore::HDF5Object Class Reference
HDF5_module
An abstract base class representing an HDF5 object.
#include <HDF5Object.h>
Public Member Functions
HDF5Object ()
Default constructor sets to invalid hid.
virtual ~HDF5Object ()
The destructor in a derived class should close the hid appropriately.
virtual void close ()=0
Close the hid if valid.
bool isValid () const
Is it a valid hid?
hid_t getHid () const
Get the hid.
operator hid_t () const
Convert automatically to hid_t.
void setName (const String &name)
Get or set the name.
const String & getName () const
Static Public Member Functions
static Bool hasHDF5Support ()
Check if there is HDF5 support compiled in.
static void throwNoHDF5 ()
If no HDF5, throw an exception that HDF5 is not supported.
Protected Member Functions
void setHid (hid_t hid)
Set the hid.
void clearHid ()
Clear the hid (set to invalid).
Private Member Functions
HDF5Object (const HDF5Object &that)
Copy constructor cannot be used.
HDF5Object & operator= (const HDF5Object &that)
Assignment cannot be used.
Private Attributes
hid_t itsHid
String itsName
Detailed Description
An abstract base class representing an HDF5 object.
Intended use:
Public interface
Review Status
Test programs:
tHDF5Dataset
Synopsis
This class wraps a basic HDF5 object. It offers several benefits:
The most important is resource management. In case of an exception, the object's hid will automatically be closed by the destructor.
It acts as the base class for the basic objects file, group, and dataset.
An HDF5 hid is a kind of pointer and should not be copied. These classes forbid making a copy, but make it possible to use them in a shared pointer context.
Definition at line 82 of file HDF5Object.h.
Constructor & Destructor Documentation
casacore::HDF5Object::HDF5Object () inline
Default constructor sets to invalid hid.
Definition at line 86 of file HDF5Object.h.
References casacore::check_hid_t(), and casacore::check_hsize_t().
virtual casacore::HDF5Object::~HDF5Object () virtual
The destructor in a derived class should close the hid appropriately.
casacore::HDF5Object::HDF5Object (const HDF5Object & that) private
Copy constructor cannot be used.
Member Function Documentation
void casacore::HDF5Object::clearHid () inline protected
Clear the hid (set to invalid).
Definition at line 131 of file HDF5Object.h.
References itsHid.
virtual void casacore::HDF5Object::close () pure virtual
Close the hid if valid.
Implemented in casacore::HDF5DataSet, casacore::HDF5File, and casacore::HDF5Group.
hid_t casacore::HDF5Object::getHid () const inline
Get the hid.
Definition at line 107 of file HDF5Object.h.
References itsHid.
Referenced by casacore::HDF5File::isClosed().
const String& casacore::HDF5Object::getName () const inline
Definition at line 118 of file HDF5Object.h.
References itsName.
Referenced by casacore::HDF5Lattice< Bool >::arrayName(), and casacore::HDF5Group::HDF5Group().
static Bool casacore::HDF5Object::hasHDF5Support () static
Check if there is HDF5 support compiled in.
Referenced by casacore::canUseHDF5Image().
bool casacore::HDF5Object::isValid () const inline
Is it a valid hid?
Definition at line 103 of file HDF5Object.h.
References itsHid.
casacore::HDF5Object::operator hid_t () const inline
Convert automatically to hid_t.
Definition at line 111 of file HDF5Object.h.
References itsHid.
HDF5Object& casacore::HDF5Object::operator= (const HDF5Object & that) private
Assignment cannot be used.
void casacore::HDF5Object::setHid (hid_t hid) inline protected
Set the hid.
Definition at line 127 of file HDF5Object.h.
References itsHid.
void casacore::HDF5Object::setName (const String & name) inline
Get or set the name.
Definition at line 116 of file HDF5Object.h.
References itsName.
static void casacore::HDF5Object::throwNoHDF5 () static
If no HDF5, throw an exception that HDF5 is not supported.
Member Data Documentation
hid_t casacore::HDF5Object::itsHid private
Definition at line 136 of file HDF5Object.h.
Referenced by clearHid(), getHid(), isValid(), operator hid_t(), and setHid().
String casacore::HDF5Object::itsName private
Definition at line 137 of file HDF5Object.h.
Referenced by getName(), and setName().
The documentation for this class was generated from the following file:
casa/HDF5/HDF5Object.h