casacore: casacore::MSFlagCmdColumns Class Reference
casacore::MSFlagCmdColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSFlagCmd columns.
#include <MSFlagCmdColumns.h>
Public Member Functions
MSFlagCmdColumns (MSFlagCmd &msFlagCmd)
Create a columns object that accesses the data in the specified Table.
~MSFlagCmdColumns ()
The destructor does nothing special.
ScalarColumn< Bool > & applied ()
Read-write access to required columns.
ScalarColumn< String > & command ()
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< Int > & level ()
ScalarColumn< String > & reason ()
ScalarColumn< Int > & severity ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
ScalarColumn< String > & type ()
const ROScalarColumn< Bool > & applied () const
Read-only access to required columns.
const ROScalarColumn< String > & command () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & interval () const
const ROScalarColumn< Int > & level () const
const ROScalarColumn< String > & reason () const
const ROScalarColumn< Int > & severity () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< String > & type () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the FLAG_CMD column.
Public Member Functions inherited from casacore::ROMSFlagCmdColumns
ROMSFlagCmdColumns (const MSFlagCmd &msFlagCmd)
Create a columns object that accesses the data in the specified Table.
~ROMSFlagCmdColumns ()
The destructor does nothing special.
const ROScalarColumn< Bool > & applied () const
Access to required columns.
const ROScalarColumn< String > & command () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & interval () const
const ROScalarColumn< Int > & level () const
const ROScalarColumn< String > & reason () const
const ROScalarColumn< Int > & severity () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< String > & type () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSFlagCmdColumns ()
void attach (MSFlagCmd &msFlagCmd)
Protected Member Functions inherited from casacore::ROMSFlagCmdColumns
ROMSFlagCmdColumns ()
void attach (const MSFlagCmd &msFlagCmd)
Private Member Functions
MSFlagCmdColumns (const MSFlagCmdColumns &)
MSFlagCmdColumns & operator= (const MSFlagCmdColumns &)
Private Attributes
ScalarColumn< Bool > applied_p
ScalarColumn< String > command_p
ScalarColumn< Double > interval_p
ScalarColumn< Int > level_p
ScalarColumn< String > reason_p
ScalarColumn< Int > severity_p
ScalarColumn< Double > time_p
ScalarColumn< String > type_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarQuantColumn< Double > intervalQuant_p
ScalarQuantColumn< Double > timeQuant_p
Detailed Description
A class to provide easy read-write access to MSFlagCmd columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSFlagCmd
ScalarColumn
Etymology
MSFlagCmdColumns stands for MeasurementSet FlagCmd Table columns.
Synopsis
This class provides access to the columns in the MSFlagCmd Table, it does the declaration of all the ScalarColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 167 of file MSFlagCmdColumns.h.
Constructor & Destructor Documentation
MSFlagCmdColumns() [1/3]
casacore::MSFlagCmdColumns::MSFlagCmdColumns (MSFlagCmd & msFlagCmd)
Create a columns object that accesses the data in the specified Table.
~MSFlagCmdColumns()
casacore::MSFlagCmdColumns::~MSFlagCmdColumns ()
The destructor does nothing special.
MSFlagCmdColumns() [2/3]
casacore::MSFlagCmdColumns::MSFlagCmdColumns () protected
MSFlagCmdColumns() [3/3]
casacore::MSFlagCmdColumns::MSFlagCmdColumns (const MSFlagCmdColumns &) private
Member Function Documentation
applied() [1/2]
ScalarColumn<Bool>& casacore::MSFlagCmdColumns::applied () inline
Read-write access to required columns.
Definition at line 178 of file MSFlagCmdColumns.h.
References applied_p.
applied() [2/2]
const ROScalarColumn<Bool>& casacore::MSFlagCmdColumns::applied () const inline
Read-only access to required columns.
Definition at line 193 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::applied().
attach()
void casacore::MSFlagCmdColumns::attach (MSFlagCmd & msFlagCmd) protected
command() [1/2]
ScalarColumn<String>& casacore::MSFlagCmdColumns::command () inline
Definition at line 179 of file MSFlagCmdColumns.h.
References command_p.
command() [2/2]
const ROScalarColumn<String>& casacore::MSFlagCmdColumns::command () const inline
Definition at line 195 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::command().
interval() [1/2]
ScalarColumn<Double>& casacore::MSFlagCmdColumns::interval () inline
Definition at line 180 of file MSFlagCmdColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSFlagCmdColumns::interval () const inline
Definition at line 199 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFlagCmdColumns::intervalQuant () inline
Definition at line 181 of file MSFlagCmdColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFlagCmdColumns::intervalQuant () const inline
Definition at line 197 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::intervalQuant().
level() [1/2]
ScalarColumn<Int>& casacore::MSFlagCmdColumns::level () inline
Definition at line 182 of file MSFlagCmdColumns.h.
References level_p.
level() [2/2]
const ROScalarColumn<Int>& casacore::MSFlagCmdColumns::level () const inline
Definition at line 201 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::level().
operator=()
MSFlagCmdColumns& casacore::MSFlagCmdColumns::operator= (const MSFlagCmdColumns &) private
reason() [1/2]
ScalarColumn<String>& casacore::MSFlagCmdColumns::reason () inline
Definition at line 183 of file MSFlagCmdColumns.h.
References reason_p.
reason() [2/2]
const ROScalarColumn<String>& casacore::MSFlagCmdColumns::reason () const inline
Definition at line 203 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::reason().
setEpochRef()
void casacore::MSFlagCmdColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the FLAG_CMD column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
severity() [1/2]
ScalarColumn<Int>& casacore::MSFlagCmdColumns::severity () inline
Definition at line 184 of file MSFlagCmdColumns.h.
References severity_p.
severity() [2/2]
const ROScalarColumn<Int>& casacore::MSFlagCmdColumns::severity () const inline
Definition at line 205 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::severity().
time() [1/2]
ScalarColumn<Double>& casacore::MSFlagCmdColumns::time () inline
Definition at line 185 of file MSFlagCmdColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSFlagCmdColumns::time () const inline
Definition at line 207 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSFlagCmdColumns::timeMeas () inline
Definition at line 187 of file MSFlagCmdColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSFlagCmdColumns::timeMeas () const inline
Definition at line 211 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFlagCmdColumns::timeQuant () inline
Definition at line 186 of file MSFlagCmdColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFlagCmdColumns::timeQuant () const inline
Definition at line 209 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::timeQuant().
type() [1/2]
ScalarColumn<String>& casacore::MSFlagCmdColumns::type () inline
Definition at line 188 of file MSFlagCmdColumns.h.
References type_p.
type() [2/2]
const ROScalarColumn<String>& casacore::MSFlagCmdColumns::type () const inline
Definition at line 213 of file MSFlagCmdColumns.h.
References casacore::ROMSFlagCmdColumns::type().
Member Data Documentation
applied_p
ScalarColumn<Bool> casacore::MSFlagCmdColumns::applied_p private
Definition at line 243 of file MSFlagCmdColumns.h.
Referenced by applied().
command_p
ScalarColumn<String> casacore::MSFlagCmdColumns::command_p private
Definition at line 244 of file MSFlagCmdColumns.h.
Referenced by command().
interval_p
ScalarColumn<Double> casacore::MSFlagCmdColumns::interval_p private
Definition at line 245 of file MSFlagCmdColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSFlagCmdColumns::intervalQuant_p private
Definition at line 256 of file MSFlagCmdColumns.h.
Referenced by intervalQuant().
level_p
ScalarColumn<Int> casacore::MSFlagCmdColumns::level_p private
Definition at line 246 of file MSFlagCmdColumns.h.
Referenced by level().
reason_p
ScalarColumn<String> casacore::MSFlagCmdColumns::reason_p private
Definition at line 247 of file MSFlagCmdColumns.h.
Referenced by reason().
severity_p
ScalarColumn<Int> casacore::MSFlagCmdColumns::severity_p private
Definition at line 248 of file MSFlagCmdColumns.h.
Referenced by severity().
time_p
ScalarColumn<Double> casacore::MSFlagCmdColumns::time_p private
Definition at line 249 of file MSFlagCmdColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSFlagCmdColumns::timeMeas_p private
Definition at line 253 of file MSFlagCmdColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSFlagCmdColumns::timeQuant_p private
Definition at line 257 of file MSFlagCmdColumns.h.
Referenced by timeQuant().
type_p
ScalarColumn<String> casacore::MSFlagCmdColumns::type_p private
Definition at line 250 of file MSFlagCmdColumns.h.
Referenced by type().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSFlagCmdColumns.h