casacore: casacore::Array< T > Class Template Reference
casacore::Array< T > Class Template Reference
Arrays_module
template <class T, class U> class vector;
#include <Array.h>
Classes
class BaseIteratorSTL
See the function begin() and end() for a detailed description of the STL iterator capability.
class ConstIteratorSTL
class IteratorSTL
Public Member Functions
Array ()
Result has dimensionality of zero, and nelements is zero.
Array (const IPosition &shape)
Create an array of the given shape, i.e.
Array (const IPosition &shape, const T &initialValue)
Create an array of the given shape and initialize it with the initial value.
Array (const Array< T > &other)
After construction, this and other reference the same storage.
Array (const IPosition &shape, T *storage, StorageInitPolicy policy=COPY)
Create an Array of a given shape from a pointer.
Array (const IPosition &shape, const T *storage)
Create an Array of a given shape from a pointer.
virtual ~Array ()
Frees up storage only if this array was the last reference to it.
virtual CountedPtr< ArrayBase > makeArray () const
Make an empty array of the same template type.
virtual void assign (const Array< T > &other)
Assign the other array to this array.
virtual void assignBase (const ArrayBase &other, Bool checkType=True)
Assign the source array to this array.
void set (const T &value)
Set every element of the array to "value." Also could use the assignment operator which assigns an array from a scalar.
void apply (T(*function)(T))
Apply the function to every element of the array.
void apply (T(*function)(const T &))
This version takes a function which takes a const T reference and returns a T.
void apply (const Functional< T, T > &function)
This version applies a functional.
virtual void reference (const Array< T > &other)
After invocation, this array and other reference the same storage.
virtual Array< T > & operator= (const Array< T > &other)
Copy the values in other to this.
Array< T > & operator= (const T &value)
Set every element of this array to "value".
Array< T > & operator= (const MaskedArray< T > &marray)
Copy to this those values in marray whose corresponding elements in marray's mask are True.
Array< T > copy () const
This makes a copy of the array and returns it.
void copyMatchingPart (const Array< T > &from)
This function copies the matching part of from array to this array.
void unique ()
This ensures that this array does not reference any other storage.
template<class U >
void tovector (vector< T, U > &out) const
Create an STL vector from an Array.
vector< T > tovector () const
Array< T > reform (const IPosition &shape) const
It is occasionally useful to have an array which access the same storage appear to have a different shape.
Array< T > nonDegenerate (uInt startingAxis=0, Bool throwIfError=True) const
These member functions remove degenerate (ie.
Array< T > nonDegenerate (const IPosition &ignoreAxes) const
void nonDegenerate (const Array< T > &other, uInt startingAxis=0, Bool throwIfError=True)
void nonDegenerate (const Array< T > &other, const IPosition &ignoreAxes)
void removeDegenerate (uInt startingAxis=0, Bool throwIfError=True)
Remove degenerate axes from this Array object.
void removeDegenerate (const IPosition &ignoreAxes)
const Array< T > addDegenerate (uInt numAxes) const
This member function returns an Array reference with the specified number of extra axes, all of length one, appended to the end of the Array.
Array< T > addDegenerate (uInt numAxes)
virtual void resize ()
Make this array a different shape.
virtual void resize (const IPosition &newShape, Bool copyValues=False)
Resize the array and optionally copy the values.
T & operator() (const IPosition &)
Access a single element of the array.
const T & operator() (const IPosition &) const
Array< T > operator() (const IPosition &start, const IPosition &end)
Get a reference to an array section extending from start to end (inclusive).
const Array< T > operator() (const IPosition &start, const IPosition &end) const
Array< T > operator() (const IPosition &start, const IPosition &end, const IPosition &inc)
Along the ith axis, every inc[i]'th element is chosen.
const Array< T > operator() (const IPosition &start, const IPosition &end, const IPosition &inc) const
Array< T > operator() (const Slicer &)
Get a reference to an array section using a Slicer.
const Array< T > operator() (const Slicer &) const
virtual CountedPtr< ArrayBase > getSection (const Slicer &) const
Get a reference to a section of an array.
Array< T > operator[] (size_t i) const
Get the subset given by the i-th value of the last axis.
const MaskedArray< T > operator() (const LogicalArray &mask) const
The array is masked by the input LogicalArray.
MaskedArray< T > operator() (const LogicalArray &mask)
const MaskedArray< T > operator() (const MaskedLogicalArray &mask) const
The array is masked by the input MaskedLogicalArray.
MaskedArray< T > operator() (const MaskedLogicalArray &mask)
uInt nrefs () const
The number of references the underlying storage has assigned to it.
virtual Bool ok () const
Check to see if the Array is consistent.
Bool conform (const Array< T > &other) const
Are the shapes identical?
Bool conform (const MaskedArray< T > &other) const
T * data ()
Get a pointer to the beginning of the array.
const T * data () const
T * getStorage (Bool &deleteIt)
Generally use of this should be shunned, except to use a FORTRAN routine or something similar.
const T * getStorage (Bool &deleteIt) const
virtual void * getVStorage (Bool &deleteIt)
The following functions behave the same as the corresponding getStorage functions in the derived templated Array class.
virtual const void * getVStorage (Bool &deleteIt) const
void putStorage (T *&storage, Bool deleteAndCopy)
putStorage() is normally called after a call to getStorage() (cf).
virtual void putVStorage (void *&storage, Bool deleteAndCopy)
void freeStorage (const T *&storage, Bool deleteIt) const
If deleteIt is set, delete "storage".
void freeVStorage (const void *&storage, Bool deleteIt) const
virtual void takeStorage (const IPosition &shape, T *storage, StorageInitPolicy policy=COPY)
Replace the data values with those in the pointer storage.
virtual void takeStorage (const IPosition &shape, const T *storage)
Since the pointer is const, a copy is always taken.
virtual CountedPtr
< ArrayPositionIterator > makeIterator (uInt byDim) const
Create an ArrayIterator object of the correct type.
Public Member Functions inherited from casacore::ArrayBase
ArrayBase ()
ArrayBase (const IPosition &shape)
Create an array of the given shape, i.e.
ArrayBase (const ArrayBase &other)
Copy constructor.
ArrayBase & operator= (const ArrayBase &)
Assignment.
virtual ~ArrayBase ()
Destructor.
uInt ndim () const
The dimensionality of this array.
size_t nelements () const
How many elements does this array have? Product of all axis lengths.
size_t size () const
Bool empty () const
Is the array empty (i.e.
Bool contiguousStorage () const
Are the array data contiguous? If they are not contiguous, getStorage (see below) needs to make a copy.
const IPosition & shape () const
The length of each axis.
IPosition endPosition () const
A convenience function: endPosition(i) = shape(i) - 1; i.e.
const IPosition & steps () const
Return steps to be made if stepping one element in a dimension.
void validateConformance (const ArrayBase &) const
Various helper functions.
void validateIndex (const IPosition &) const
void validateIndex (uInt index) const
void validateIndex (uInt index1, uInt index2) const
void validateIndex (uInt index1, uInt index2, uInt index3) const
Friends
class ArrayIterator< T >
Used to iterate through Arrays.
class Matrix< T >
Needed to be a friend for Matrix<T>::reference()
typedef T value_type
Define the STL-style iterator functions (only forward iterator).
typedef IteratorSTL iterator
typedef ConstIteratorSTL const_iterator
typedef T * contiter
typedef const T * const_contiter
CountedPtr< Block< T > > data_p
Reference counted block that contains the storage.
T * begin_p
This pointer is adjusted to point to the first element of the array.
T * end_p
The end for an STL-style iteration.
iterator begin ()
Get the begin iterator object for any array.
const_iterator begin () const
iterator end ()
const_iterator end () const
contiter cbegin ()
Get the begin iterator object for a contiguous array.
const_contiter cbegin () const
contiter cend ()
const_contiter cend () const
virtual void doNonDegenerate (const Array< T > &other, const IPosition &ignoreAxes)
Remove the degenerate axes from the Array object.
void makeSteps ()
Fill the steps and the end for a derived class.
void setEndIter ()
Set the end iterator.
Additional Inherited Members
Static Public Member Functions inherited from casacore::ArrayBase
static uInt arrayVersion ()
Array version for major change (used by ArrayIO).
Protected Member Functions inherited from casacore::ArrayBase
void baseCopy (const ArrayBase &that)
Bool isStorageContiguous () const
Determine if the storage of a subset is contiguous.
void checkVectorShape ()
Check if the shape of a vector is correct.
void checkMatrixShape ()
Check if the shape of a matrix is correct.
void checkCubeShape ()
Check if the shape of a cube is correct.
void baseReform (ArrayBase &tmp, const IPosition &shape) const
Reform the array to a shape with the same nr of elements.
void baseNonDegenerate (const ArrayBase &other, const IPosition &ignoreAxes)
Remove the degenerate axes from the Array object.
void baseAddDegenerate (ArrayBase &, uInt numAxes)
These member functions return an Array reference with the specified number of extra axes, all of length one, appended to the end of the Array.
size_t makeSubset (ArrayBase &out, const IPosition &b, const IPosition &e, const IPosition &i)
Make a subset of an array.
Bool conform2 (const ArrayBase &other) const
Are the shapes identical?
void baseMakeSteps ()
Make the indexing step sizes.
void throwNdimVector ()
Throw expection if vector dimensionality is incorrect.
Bool copyVectorHelper (const ArrayBase &other)
Helper function for templated Vector class.
Protected Attributes inherited from casacore::ArrayBase
size_t nels_p
Number of elements in the array.
uInt ndimen_p
Dimensionality of the array.
Bool contiguous_p
Are the data contiguous?
IPosition length_p
Used to hold the shape, increment into the underlying storage and originalLength of the array.
IPosition inc_p
IPosition originalLength_p
IPosition steps_p
Used to hold the step to next element in each dimension.
Detailed Description
template<class T>
class casacore::Array< T >
template <class T, class U> class vector;
A templated N-D Array class with zero origin Array<T> is a templated, N-dimensional, Array class. The origin is zero, but by default indices are zero-based. This Array class is the base class for specialized Vector<T>, Matrix<T>, and Cube<T> classes.
Indexing into the array, and positions in general, are given with IPosition (essentially a vector of integers) objects. That is, an N-dimensional array requires a length-N IPosition to define a position within the array. Unlike C, indexing is done with (), not []. Also, the storage order is the same as in FORTRAN, i.e. memory varies most rapidly with the first index.
// axisLengths = [1,2,3,4,5]
IPosition axisLengths(5, 1, 2, 3, 4, 5);
Array<Int> ai(axisLengths);         // ai is a 5 dimensional array of
// integers; indices are 0-based
// => ai.nelements() == 120
Array<Int> ai2(axisLengths);        // The first element is at index 0
IPosition zero(5); zero = 0;        // [0,0,0,0,0]
//..\.
Indexing into an N-dimensional array is relatively expensive. Normally you will index into a Vector, Matrix, or Cube. These may be obtained from an N-dimensional array by creating a reference, or by using an ArrayIterator. The "shape" of the array is an IPosition which gives the length of each axis.
An Array may be standalone, or it may refer to another array, or to part of another array (by refer we mean that if you change a pixel in the current array, a pixel in the referred to array also changes, i.e. they share underlying storage).
Warning: One way one array can reference another is through the copy constructor; While this might be what you want, you should probably use the reference() member function to make it explicit; The copy constructor is used when arguments are passed by value; normally functions should not pass Arrays by value, rather they should pass a reference or a const reference; On the positive side, returning an array from a function is efficient since no copying need be done;
Aside from the explicit reference() member function, a user will most commonly encounter an array which references another array when he takes an array slice (or section). A slice is a sub-region of an array (which might also have a stride: every nth row, every mth column, ...).
IPosition lengths(3,10,20,30);
Array<Int> ai(lengths);         // A 10x20x30 cube
Cube<Int> ci;
//..\.
ci.reference(ai1);              // ci and ai now reference the same
// storage
ci(0,0,0) = 123;                // Can use Cube indexing
ci.xyPlane(2) = 0;              //     and other member functions
IPosition zero(3,0,0,0);
assert(ai(zero) == 123);        // True because ai, ci are references
//..\.
Array<Int> subArray;
IPosition blc(3,0,0,0), trc(3,5,5,5);
subArray.reference(ai(blc, trc));
subArray = 10;                  // All of subArray, which is the
// subcube from 0,0,0 to 5,5,5 in
// ai, has the value 10.
While the last example has an array slice referenced explicitly by another array variable, normally the user will often only use the slice as a temporary in an expresion, for example:
Array<Complex> array;
IPosition blc, trc, offset;
//..\.
// Copy from one region of the array into another
array(blc, trc) = array(blc+offset, trc+offset);
The Array classes are intended to operate on relatively large amounts of data. While they haven't been extensively tuned yet, they are relatively efficient in terms of speed. Presently they are not space efficient – the overhead is about 15 words. While this will be improved (probably to about 1/2 that), these array classes are not appropriate for very large numbers of very small arrays. The Block<T> class may be what you want in this circumstance.
Element by element mathematical and logical operations are available for arrays (defined in aips/ArrayMath.h and aips/ArrayLogical.h). Because arithmetic and logical functions are split out, it is possible to create an Array<T> (and hence Vector<T> etc) for any type T that has a default constructor, assignment operator, and copy constructor. In particular, Array<String> works.
If compiled with the preprocessor symbol AIPS_DEBUG symbol, array consistency ("invariants") will be checked in most member functions, and indexing will be range-checked. This should not be defined for production runs.
Tip: Most of the data members and functions which are "protected" should likely become "private";
To Do
Integrate into the Lattice hierarchy
Factor out the common functions (shape etc) into a type-independent base class.
Definition at line 167 of file Array.h.
Member Typedef Documentation
template<class T> typedef const T* casacore::Array< T >::const_contiter
Definition at line 730 of file Array.h.
template<class T> typedef ConstIteratorSTL casacore::Array< T >::const_iterator
Definition at line 728 of file Array.h.
template<class T> typedef T* casacore::Array< T >::contiter
Definition at line 729 of file Array.h.
template<class T> typedef IteratorSTL casacore::Array< T >::iterator
Definition at line 727 of file Array.h.
template<class T> typedef T casacore::Array< T >::value_type
Define the STL-style iterator functions (only forward iterator).
It makes it possible to iterate through all data elements of an array and to use it common STL functions. The end() function is relatively expensive, so it should not be used inside a for statement. It is much better to call it beforehand as shown in the example below. Furthermore it is very important to use ++iter, because iter++ is 4 times slower.
Array<Int> arr(shape);
Array<Int>::iterator iterend(arr.end());
for (Array<Int>::iterator iter=arr.begin(); iter!=iterend; ++iter) {
*iter += 1;
}
The Array class supports random access, so in principle a random iterator could be implemented, but its performance would not be great, especially for non-contiguous arrays.
Some other STL like functions exist for performance reasons. If the array is contiguous, it is possible to use the cbegin and cend functions which are about 10% faster. STL-style typedefs.
Definition at line 726 of file Array.h.
Constructor & Destructor Documentation
template<class T> casacore::Array< T >::Array ()
Result has dimensionality of zero, and nelements is zero.
template<class T> casacore::Array< T >::Array (const IPosition & shape) explicit
Create an array of the given shape, i.e.
after construction array.ndim() == shape.nelements() and array.shape() == shape. The origin of the Array is zero.
template<class T> casacore::Array< T >::Array (const IPosition & shape, const T & initialValue)
Create an array of the given shape and initialize it with the initial value.
template<class T> casacore::Array< T >::Array (const Array< T > & other)
After construction, this and other reference the same storage.
template<class T> casacore::Array< T >::Array (const IPosition & shape, T * storage, StorageInitPolicy policy = COPY)
Create an Array of a given shape from a pointer.
template<class T> casacore::Array< T >::Array (const IPosition & shape, const T * storage)
Create an Array of a given shape from a pointer.
Because the pointer is const, a copy is always made.
template<class T> virtual casacore::Array< T >::~Array () virtual
Frees up storage only if this array was the last reference to it.
Member Function Documentation
template<class T> const Array<T> casacore::Array< T >::addDegenerate (uInt numAxes) const
This member function returns an Array reference with the specified number of extra axes, all of length one, appended to the end of the Array.
Note that the reform function can also be used to add extra axes.
template<class T> Array<T> casacore::Array< T >::addDegenerate (uInt numAxes)
template<class T> void casacore::Array< T >::apply (T(*)(T) function)
Apply the function to every element of the array.
This modifies the array in place.
This version takes a function which takes a T and returns a T.
template<class T> void casacore::Array< T >::apply (T(*)(const T &) function)
This version takes a function which takes a const T reference and returns a T.
template<class T> void casacore::Array< T >::apply (const Functional< T, T > & function)
This version applies a functional.
template<class T> virtual void casacore::Array< T >::assign (const Array< T > & other) virtual
Assign the other array to this array.
If the shapes mismatch, this array is resized.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> virtual void casacore::Array< T >::assignBase (const ArrayBase & source, Bool checkType = True) virtual
Assign the source array to this array.
If checkType==True, it is checked if the underlying template types match. Otherwise, it is only checked in debug mode (for performance).
The default implementation in ArrayBase throws an exception.
Reimplemented from casacore::ArrayBase.
template<class T> iterator casacore::Array< T >::begin () inline
Get the begin iterator object for any array.
Definition at line 734 of file Array.h.
Referenced by casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayContTransform(), casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayTransformInPlace(), casacore::python::to_list< casacore::Array< casacore::String > >::makeobject(), and casacore::python::to_list< casacore::Vector< casacore::String > >::makeobject().
template<class T> const_iterator casacore::Array< T >::begin () const inline
Definition at line 736 of file Array.h.
template<class T> contiter casacore::Array< T >::cbegin () inline
Get the begin iterator object for a contiguous array.
Definition at line 746 of file Array.h.
Referenced by casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayContTransform(), and casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayTransformInPlace().
template<class T> const_contiter casacore::Array< T >::cbegin () const inline
Definition at line 748 of file Array.h.
template<class T> contiter casacore::Array< T >::cend () inline
Definition at line 750 of file Array.h.
Referenced by casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayContTransform(), and casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayTransformInPlace().
template<class T> const_contiter casacore::Array< T >::cend () const inline
Definition at line 752 of file Array.h.
template<class T> Bool casacore::Array< T >::conform (const Array< T > & other) const inline
Are the shapes identical?
Definition at line 485 of file Array.h.
template<class T> Bool casacore::Array< T >::conform (const MaskedArray< T > & other) const
template<class T> Array<T> casacore::Array< T >::copy () const
This makes a copy of the array and returns it.
This can be useful for, e.g. making working copies of function arguments that you can write into.
void someFunction(const Array<Int> &arg)
{
Array<Int> tmp(arg.copy());
// ..\.
}
Note that since the copy constructor makes a reference, if we just created used to copy constructor, modifying "tmp" would also modify "arg". Clearly another alternative would simply be:
void someFunction(const Array<Int> &arg)
{
Array<Int> tmp;
tmp = arg;
// ..\.
}
which likely would be simpler to understand. (Should copy() be deprecated and removed?)
template<class T> void casacore::Array< T >::copyMatchingPart (const Array< T > & from)
This function copies the matching part of from array to this array.
The matching part is the part with the minimum size for each axis. E.g. if this array has shape [4,5,6] and from array has shape [7,3], the matching part has shape [4,3].
Note it is used by the resize function if copyValues==True.
template<class T> T* casacore::Array< T >::data () inline
Get a pointer to the beginning of the array.
Note that the array may not be contiguous.
Definition at line 493 of file Array.h.
Referenced by casacore::ArrayLogical_global_functions_Array_logical_operations::allSame(), casacore::LSQaips::getErrors(), casacore::HDF5Record::readArr(), casacore::LSQaips::solve(), and casacore::HDF5Record::writeArr().
template<class T> const T* casacore::Array< T >::data () const inline
Definition at line 495 of file Array.h.
template<class T> virtual void casacore::Array< T >::doNonDegenerate (const Array< T > & other, const IPosition & ignoreAxes) protected virtual
Remove the degenerate axes from the Array object.
This is the implementation of the nonDegenerate functions. It has a different name to be able to make it virtual without having the "hide virtual function" message when compiling derived classes.
Reimplemented in casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, and casacore::Vector< ArgType >.
Referenced by casacore::Array< ArgType >::nonDegenerate().
template<class T> iterator casacore::Array< T >::end () inline
Definition at line 738 of file Array.h.
Referenced by casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayContTransform(), casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayTransformInPlace(), casacore::python::to_list< casacore::Array< casacore::String > >::makeobject(), and casacore::python::to_list< casacore::Vector< casacore::String > >::makeobject().
template<class T> const_iterator casacore::Array< T >::end () const inline
Definition at line 740 of file Array.h.
template<class T> void casacore::Array< T >::freeStorage (const T *& storage, Bool deleteIt) const
If deleteIt is set, delete "storage".
Normally freeStorage calls will follow calls to getStorage. The reason the pointer is "const" is because only const pointers are released from const arrays. The "storage" pointer is set to zero.
template<class T> void casacore::Array< T >::freeVStorage (const void *& storage, Bool deleteIt) const virtual
Reimplemented from casacore::ArrayBase.
template<class T> virtual CountedPtr<ArrayBase> casacore::Array< T >::getSection (const Slicer &) const virtual
Get a reference to a section of an array.
This is the same as operator(), but can be used in a type-agnostic way.
Reimplemented from casacore::ArrayBase.
template<class T> T* casacore::Array< T >::getStorage (Bool & deleteIt)
Generally use of this should be shunned, except to use a FORTRAN routine or something similar.
Because you can't know the state of the underlying data layout (in particular, if there are increments) sometimes the pointer returned will be to a copy, but often this won't be necessary. A boolean is returned which tells you if this is a copy (and hence the storage must be deleted). Note that if you don't do anything unusual, getStorage followed by freeStorage or putStorage will do the deletion for you (if required). e.g.:
Array<Int> a(shape); ..\.
Bool deleteIt; Int *storage = a.getStorage(deleteIt);
foo(storage, a.nelements()); a.puStorage(storage, deleteIt);
// or a.freeStorage(storage, deleteIt) if a is const.
NB: However, if you only use getStorage, you will have to delete the pointer yourself using freeStorage().
It would probably be useful to have corresponding "copyin" "copyout" functions that used a user supplied buffer. Note that deleteIt is set in this function.
Referenced by casacore::Array< ArgType >::getStorage().
template<class T> const T* casacore::Array< T >::getStorage (Bool & deleteIt) const inline
The cast is OK because the return pointer will be cast to const
Definition at line 521 of file Array.h.
template<class T> virtual void* casacore::Array< T >::getVStorage (Bool & deleteIt) virtual
The following functions behave the same as the corresponding getStorage functions in the derived templated Array class.
They handle a pointer to a contiguous block of array data. If the array is not contiguous, a copy is used to make it contiguous.
Reimplemented from casacore::ArrayBase.
template<class T> virtual const void* casacore::Array< T >::getVStorage (Bool & deleteIt) const virtual
Reimplemented from casacore::ArrayBase.
template<class T> virtual CountedPtr<ArrayBase> casacore::Array< T >::makeArray () const virtual
Make an empty array of the same template type.
Reimplemented from casacore::ArrayBase.
template<class T> virtual CountedPtr<ArrayPositionIterator> casacore::Array< T >::makeIterator (uInt byDim) const virtual
Create an ArrayIterator object of the correct type.
Reimplemented from casacore::ArrayBase.
template<class T> void casacore::Array< T >::makeSteps () inline protected
Fill the steps and the end for a derived class.
Definition at line 782 of file Array.h.
template<class T> Array<T> casacore::Array< T >::nonDegenerate (uInt startingAxis = 0, Bool throwIfError = True) const
These member functions remove degenerate (ie.
length==1) axes from Arrays. Only axes greater than startingAxis are considered (normally one wants to remove trailing axes). The first two of these functions return an Array reference with axes removed. The latter two functions let this Array object reference the 'other' array with degenerated axes removed.
Unless throwIfError is False, an exception will be thrown if startingAxis exceeds the array's dimensionality.
The functions with argument ignoreAxes do not consider the axes given in that argument. In this way it can be achieved that degenerate axes are kept.
Caution: When the two functions returning void are invoked on a derived object (e;g; Matrix), an exception is thrown if removing the degenerate axes from other does not result in a correct number of axes;
template<class T> Array<T> casacore::Array< T >::nonDegenerate (const IPosition & ignoreAxes) const
template<class T> void casacore::Array< T >::nonDegenerate (const Array< T > & other, uInt startingAxis = 0, Bool throwIfError = True)
template<class T> void casacore::Array< T >::nonDegenerate (const Array< T > & other, const IPosition & ignoreAxes) inline
Definition at line 370 of file Array.h.
template<class T> uInt casacore::Array< T >::nrefs () const
The number of references the underlying storage has assigned to it.
It is 1 unless there are outstanding references to the storage (e.g., through a slice). Normally you have no need to do this since the arrays handle all of the references for you.
template<class T> virtual Bool casacore::Array< T >::ok () const virtual
Check to see if the Array is consistent.
This is about the same thing as checking for invariants. If AIPS_DEBUG is defined, this is invoked after construction and on entry to most member functions.
Reimplemented from casacore::ArrayBase.
Reimplemented in casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, and casacore::Vector< ArgType >.
template<class T> T& casacore::Array< T >::operator() (const IPosition &)
Access a single element of the array.
This is relatively expensive. Extensive indexing should be done through one of the Array specializations (Vector, Matrix, Cube). If AIPS_DEBUG is defined, index checking will be performed.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> const T& casacore::Array< T >::operator() (const IPosition &) const
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> Array<T> casacore::Array< T >::operator() (const IPosition & start, const IPosition & end)
Get a reference to an array section extending from start to end (inclusive).
Reimplemented in casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> const Array<T> casacore::Array< T >::operator() (const IPosition & start, const IPosition & end) const
Reimplemented in casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> Array<T> casacore::Array< T >::operator() (const IPosition & start, const IPosition & end, const IPosition & inc)
Along the ith axis, every inc[i]'th element is chosen.
Reimplemented in casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> const Array<T> casacore::Array< T >::operator() (const IPosition & start, const IPosition & end, const IPosition & inc) const
Reimplemented in casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> Array<T> casacore::Array< T >::operator() (const Slicer &)
Get a reference to an array section using a Slicer.
Reimplemented in casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> const Array<T> casacore::Array< T >::operator() (const Slicer &) const
Reimplemented in casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> const MaskedArray<T> casacore::Array< T >::operator() (const LogicalArray< T > & mask) const
The array is masked by the input LogicalArray.
This mask must conform to the array.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, and casacore::Matrix< Complex >.
template<class T> MaskedArray<T> casacore::Array< T >::operator() (const LogicalArray< T > & mask)
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, and casacore::Matrix< Complex >.
template<class T> const MaskedArray<T> casacore::Array< T >::operator() (const MaskedLogicalArray< T > & mask) const
The array is masked by the input MaskedLogicalArray.
The mask is effectively the AND of the internal LogicalArray and the internal mask of the MaskedLogicalArray. The MaskedLogicalArray must conform to the array.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, and casacore::Matrix< Complex >.
template<class T> MaskedArray<T> casacore::Array< T >::operator() (const MaskedLogicalArray< T > & mask)
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, and casacore::Matrix< Complex >.
template<class T> virtual Array<T>& casacore::Array< T >::operator= (const Array< T > & other) virtual
Copy the values in other to this.
If the array on the left hand side has no elements, then it is resized to be the same size as as the array on the right hand side. Otherwise, the arrays must conform (same shapes).
IPosition shape(2,10,10);     // some shape
Array<Double> ad(shape);
//..\.
Array<Double> ad2;            // N.B. ad2.nelements() == 0
ad2 = ad;                     // ad2 resizes, then elements
//     are copied.
shape = 20;
Array<Double> ad3(shape);
ad3 = ad;                     // Error: arrays do not conform
Note that the assign function can be used to assign a non-conforming array.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> Array<T>& casacore::Array< T >::operator= (const T & value)
Set every element of this array to "value".
In other words, a scalar behaves as if it were a constant conformant array.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> Array<T>& casacore::Array< T >::operator= (const MaskedArray< T > & marray)
Copy to this those values in marray whose corresponding elements in marray's mask are True.
Thrown Exceptions
ArrayConformanceError
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> Array<T> casacore::Array< T >::operator[] (size_t i) const
Get the subset given by the i-th value of the last axis.
So for a cube it returns the i-th xy plane. For a Matrix it returns the i-th row. The returned array references the original array data; its dimensionality is one less. For a 1-dim array it still returns a 1-dim array.
Note: This function should not be used in tight loops as it is (much) slower than iterating using begin() and end(), ArrayIter, or ArrayAccessor;
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, and casacore::Vector< ArgType >.
template<class T> void casacore::Array< T >::putStorage (T *& storage, Bool deleteAndCopy)
putStorage() is normally called after a call to getStorage() (cf).
The "storage" pointer is set to zero.
template<class T> virtual void casacore::Array< T >::putVStorage (void *& storage, Bool deleteAndCopy) virtual
Reimplemented from casacore::ArrayBase.
template<class T> virtual void casacore::Array< T >::reference (const Array< T > & other) virtual
After invocation, this array and other reference the same storage.
That is, modifying an element through one will show up in the other. The arrays appear to be identical; they have the same shape.
Please note that this function makes it possible to reference a const Array, thus effectively it makes a const Array non-const. Although this may seem undesirable at first sight, it is necessary to be able to make references to temporary Array objects, in particular to Array slices. Otherwise one first needs to use the copy constructor.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
Referenced by casacore::ValueHolder::getValue(), and casacore::RecordInterface::toArray().
template<class T> Array<T> casacore::Array< T >::reform (const IPosition & shape) const
It is occasionally useful to have an array which access the same storage appear to have a different shape.
For example, turning an N-dimensional array into a Vector.
When the array data are contiguous, the array can be reshaped to any form as long as the number of elements stays the same. When not contiguous, it is only possible to remove or add axes with length 1.
IPosition squareShape(2,5,5);
Array<Float> square(squareShape);
IPosition lineShape(1,25);
Vector<Float> line(square.reform(lineShape));
// "square"'s storage may now be accessed through Vector "line"
template<class T> void casacore::Array< T >::removeDegenerate (uInt startingAxis = 0, Bool throwIfError = True)
Remove degenerate axes from this Array object.
Note it does not make sense to use these functions on a derived object like Matrix, because it is not possible to remove axes from them.
template<class T> void casacore::Array< T >::removeDegenerate (const IPosition & ignoreAxes)
template<class T> virtual void casacore::Array< T >::resize () virtual
Make this array a different shape.
If copyValues==True the old values are copied over to the new array. Copying is done on a per axis basis, thus a subsection with the minimum of the old and new shape is copied.
Resize without argument is equal to resize(IPosition()).
It is important to note that if multiple Array objects reference the same data storage, this Array object still references the same data storage as the other Array objects if the shape does not change. Otherwise this Array object references newly allocated storage, while the other Array objects still reference the existing data storage.
If you want to be sure that the data storage of this Array object is not referenced by other Array objects, the function unique should be called first.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> virtual void casacore::Array< T >::resize (const IPosition & newShape, Bool copyValues = False) virtual
Resize the array and optionally copy the values.
The default implementation in ArrayBase throws an exception.
Reimplemented from casacore::ArrayBase.
Reimplemented in casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, casacore::Vector< ArgType >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, and casacore::Cube< Double >.
template<class T> void casacore::Array< T >::set (const T & value)
Set every element of the array to "value." Also could use the assignment operator which assigns an array from a scalar.
template<class T> void casacore::Array< T >::setEndIter () inline protected
Set the end iterator.
Definition at line 786 of file Array.h.
Referenced by casacore::Array< ArgType >::makeSteps().
template<class T> virtual void casacore::Array< T >::takeStorage (const IPosition & shape, T * storage, StorageInitPolicy policy = COPY) virtual
Replace the data values with those in the pointer storage.
The results are undefined is storage does not point at nelements() or more data elements. After takeStorage() is called, unique() is True.
Reimplemented in casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, and casacore::Vector< ArgType >.
template<class T> virtual void casacore::Array< T >::takeStorage (const IPosition & shape, const T * storage) virtual
Since the pointer is const, a copy is always taken.
Reimplemented in casacore::Cube< T >, casacore::Cube< RigidVector< Double, 2 > >, casacore::Cube< Double >, casacore::Matrix< T >, casacore::Matrix< GaussianBeam >, casacore::Matrix< Float >, casacore::Matrix< Double >, casacore::Matrix< Int >, casacore::Matrix< FType >, casacore::Matrix< Bool >, casacore::Matrix< SquareMatrix< Complex, 2 > >, casacore::Matrix< Complex >, casacore::Vector< T >, casacore::Vector< MeasComet * >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base > >, casacore::Vector< Quantum< Double > >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base > >, casacore::Vector< double >, casacore::Vector< Float >, casacore::Vector< typename FunctionTraits< T >::BaseType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< Double >::BaseType >::base >, casacore::Vector< typename FunctionTraits< Double >::DiffType >, casacore::Vector< Unit >, casacore::Vector< Double >, casacore::Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base >, casacore::Vector< Vector< typename LSQTraits< typename FunctionTraits< T >::BaseType >::base > >, casacore::Vector< Vector< Int > >, casacore::Vector< MPosition >, casacore::Vector< typename FunctionTraits< DComplex >::ArgType >, casacore::Vector< typename FunctionTraits< Double >::ArgType >, casacore::Vector< MDirection >, casacore::Vector< AutoDiff< T > >, casacore::Vector< MFrequency >, casacore::Vector< typename FunctionTraits< Double >::BaseType >, casacore::Vector< Quantity >, casacore::Vector< String >, casacore::Vector< Range >, casacore::Vector< Int >, casacore::Vector< Int64 >, casacore::Vector< AutoDiffA< T > >, casacore::Vector< Type >, casacore::Vector< Vector< Range > >, casacore::Vector< RORecordFieldPtr< Double > >, casacore::Vector< FType >, casacore::Vector< Bool >, casacore::Vector< SquareMatrix< Complex, 2 > >, casacore::Vector< typename FunctionTraits< T >::DiffType >, casacore::Vector< AutoDiff< Double > >, casacore::Vector< MEpoch >, casacore::Vector< typename FunctionTraits< T >::ArgType >, casacore::Vector< typename LSQTraits< typename FunctionTraits< DComplex >::BaseType >::base >, casacore::Vector< typename FunctionTraits< DComplex >::BaseType >, casacore::Vector< uInt >, casacore::Vector< Domain >, casacore::Vector< typename FunctionTraits< DComplex >::DiffType >, and casacore::Vector< ArgType >.
template<class T> template<class U > void casacore::Array< T >::tovector (vector< T, U > & out) const
Create an STL vector from an Array.
The created vector is a linear representation of the Array memory. See Vector for details of the operation and its reverse (i.e. creating a Vector from a vector), and for details of definition and instantiation.
template<class T> vector<T> casacore::Array< T >::tovector () const
template<class T> void casacore::Array< T >::unique ()
This ensures that this array does not reference any other storage.
Tip: When a section is taken of an array with non-unity strides, storage can be wasted if the array, which originally contained all the data, goes away; unique() also reclaims storage; This is an optimization users don't normally need to understand;
IPosition shape(;;;), blc(;;;), trc(;;;), inc(;;;);
Array<Float> af(shape);
inc = 2; // or anything > 1
Array<Float> aSection;reference(af(blc, trc, inc));
af;reference(anotherArray);
// aSection now references storage that has a stride
// in it, but nothing else is; Storage is wasted;
aSection;unique();
Friends And Related Function Documentation
template<class T> friend class ArrayIterator< T > friend
Used to iterate through Arrays.
Derived classes VectorIterator and MatrixIterator are probably more useful.
Definition at line 556 of file Array.h.
template<class T> friend class Matrix< T > friend
Needed to be a friend for Matrix<T>::reference()
Definition at line 562 of file Array.h.
Member Data Documentation
template<class T> T* casacore::Array< T >::begin_p protected
This pointer is adjusted to point to the first element of the array.
It is not necessarily the same thing as data->storage() since this array might be a section, e.g. have a blc which shifts us forward into the block.
Definition at line 775 of file Array.h.
Referenced by casacore::Cube< Double >::at(), casacore::Array< ArgType >::cbegin(), casacore::Array< ArgType >::data(), casacore::Cube< Double >::operator()(), casacore::Matrix< Complex >::operator()(), casacore::Vector< ArgType >::operator()(), casacore::Vector< ArgType >::operator[](), and casacore::Array< ArgType >::setEndIter().
template<class T> CountedPtr<Block<T> > casacore::Array< T >::data_p protected
Reference counted block that contains the storage.
Definition at line 769 of file Array.h.
template<class T> T* casacore::Array< T >::end_p protected
The end for an STL-style iteration.
Definition at line 778 of file Array.h.
Referenced by casacore::Array< ArgType >::cend(), casacore::Array< ArgType >::end(), and casacore::Array< ArgType >::setEndIter().
The documentation for this class was generated from the following file:
casa/Arrays/Array.h