casacore: casacore::TaQLResult Class Reference
casacore::TaQLResult Class Reference
tables package (libcasa_tables) » TaQL_module » TaQL_module_internal_classes
Class to hold the result of a TaQL command.
#include <TaQLResult.h>
Public Member Functions
TaQLResult (const Table &=Table())
Construct from a Table.
TaQLResult (const TableExprNode &)
Construct from a TableExprNode.
Bool isTable () const
Is the result a Table?
Table table () const
Return the result as a Table.
operator Table () const
Make it possible to convert automatically to a Table.
TableExprNode node () const
Return the result as a TableExprNode.
Private Attributes
Table itsTable
TableExprNode itsNode
Detailed Description
Class to hold the result of a TaQL command.
Intended use:
Internal
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Synopsis
The result of a TaQL command can be a Table or a TableExprNode. This class holds the actual result.
Motivation
It is possible to give a TaQL command resulting in a TableExprNode to make it possible to make expressions of columns.
Definition at line 67 of file TaQLResult.h.
Constructor & Destructor Documentation
TaQLResult() [1/2]
casacore::TaQLResult::TaQLResult (const Table & = Table())
Construct from a Table.
TaQLResult() [2/2]
casacore::TaQLResult::TaQLResult (const TableExprNode &) explicit
Construct from a TableExprNode.
Member Function Documentation
isTable()
Bool casacore::TaQLResult::isTable () const inline
Is the result a Table?
Definition at line 77 of file TaQLResult.h.
References casacore::TableExprNode::isNull(), and itsNode.
node()
TableExprNode casacore::TaQLResult::node () const
Return the result as a TableExprNode.
It throws an exception if it is not a TableExprNode.
operator Table()
casacore::TaQLResult::operator Table () const inline
Make it possible to convert automatically to a Table.
Definition at line 86 of file TaQLResult.h.
References table().
table()
Table casacore::TaQLResult::table () const
Return the result as a Table.
It throws an exception if it is not a Table.
Referenced by operator Table().
Member Data Documentation
itsNode
TableExprNode casacore::TaQLResult::itsNode private
Definition at line 95 of file TaQLResult.h.
Referenced by isTable().
itsTable
Table casacore::TaQLResult::itsTable private
Definition at line 94 of file TaQLResult.h.
The documentation for this class was generated from the following file:
tables/TaQL/TaQLResult.h