casacore: casacore::arrays_internal::Storage< T, Alloc > Class Template Reference
casacore::arrays_internal::Storage< T, Alloc > Class Template Reference
This class emplements a static (but run-time) sized array.
#include <Storage.h>
Classes
struct conjunction
struct conjunction< B1 >
struct conjunction< B1, Bn...>
struct disjunction
Used by template code above These are already in C++17, but currently only using C++11...
struct disjunction< B1 >
struct disjunction< B1, Bn...>
Public Member Functions
Storage (const Alloc &allocator)
Construct an empty Storage.
Storage (std::size_t n, const Alloc &allocator)
Construct Storage with a given size.
Storage (std::size_t n, const T &val, const Alloc &allocator)
Construct Storage with a given size.
template<typename InputIterator >
Storage (InputIterator startIter, InputIterator endIter, const Alloc &allocator)
Construct Storage from a range.
~Storage () noexcept
Destructs the elements and deallocates the data.
size_t size () const
Size of the data, zero if empty.
const Alloc & get_allocator () const
Returns the allocator associated with this Storage.
bool is_shared () const
Whether this Storage owns its data.
Storage (const Storage< T, Alloc > &)=delete
Storage (Storage< T, Alloc > &&)=delete
Storage & operator= (const Storage &)=delete
Storage & operator= (Storage &&)=delete
T * data ()
Return a pointer to the storage data.
const T * data () const
Static Public Member Functions
static std::unique_ptr
< Storage< T, Alloc > > MakeFromMove (T *startIter, T *endIter, const Alloc &allocator)
Construct Storage from a range by moving.
static std::unique_ptr
< Storage< T, Alloc > > MakeFromSharedData (T *existingData, size_t n, const Alloc &allocator)
Construct a Storage from existing data.
static std::unique_ptr
< Storage< T, Alloc > > MakeUninitialized (size_t n, const Alloc &allocator)
Construct a Storage with uninitialized data.
Private Member Functions
Storage (T *startIter, T *endIter, const Alloc &allocator, std::false_type, std::true_type)
Moving range constructor implementation.
template<typename InputIterator >
Storage (InputIterator startIter, InputIterator endIter, const Alloc &allocator, std::false_type)
Copying range constructor implementation for non-integral types.
template<typename Integral >
Storage (Integral n, Integral val, const Alloc &allocator, std::true_type)
Copying range constructor implementation for integral types.
T * construct (size_t n)
These methods allocate the storage and construct the elements.
T * construct (size_t n, const T &val)
template<typename InputIterator >
T * construct_range (InputIterator startIter, InputIterator endIter)
T * construct_move (T *startIter, T *endIter)
Private Attributes
T * _data
T * _end
bool _isShared
Detailed Description
template<typename T, typename Alloc>
class casacore::arrays_internal::Storage< T, Alloc >
This class emplements a static (but run-time) sized array.
It is used in the Array class, and is necessary because std::vector specializes for bool. It holds the same functionality as a normal array, and enables allocation through different allocators similar to std::vector.
Definition at line 16 of file Storage.h.
Constructor & Destructor Documentation
template<typename T , typename Alloc > casacore::arrays_internal::Storage< T, Alloc >::Storage (const Alloc & allocator) inline
Construct an empty Storage.
Definition at line 20 of file Storage.h.
Referenced by casacore::arrays_internal::Storage< T, Alloc >::MakeFromMove().
template<typename T , typename Alloc > casacore::arrays_internal::Storage< T, Alloc >::Storage (std::size_t n, const Alloc & allocator) inline
Construct Storage with a given size.
The elements will be default constructed
Definition at line 29 of file Storage.h.
template<typename T , typename Alloc > casacore::arrays_internal::Storage< T, Alloc >::Storage (std::size_t n, const T & val, const Alloc & allocator) inline
Construct Storage with a given size.
The elements will be copy constructed from the given value
Definition at line 38 of file Storage.h.
template<typename T , typename Alloc > template<typename InputIterator > casacore::arrays_internal::Storage< T, Alloc >::Storage (InputIterator startIter, InputIterator endIter, const Alloc & allocator) inline
Construct Storage from a range.
The elements will be copy constructed from the given values. Note that this constructor can be chosen over of Storage(std::size_t, const T&, const Alloc) when T=size_t. Therefore, this constructor forwards to the appropriate constructor based on whether T is an integral.
Definition at line 52 of file Storage.h.
template<typename T , typename Alloc > casacore::arrays_internal::Storage< T, Alloc >::~Storage () inline noexcept
Destructs the elements and deallocates the data.
Definition at line 97 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::_data, casacore::arrays_internal::Storage< T, Alloc >::_isShared, and casacore::arrays_internal::Storage< T, Alloc >::size().
template<typename T , typename Alloc > casacore::arrays_internal::Storage< T, Alloc >::Storage (const Storage< T, Alloc > &) delete
template<typename T , typename Alloc > casacore::arrays_internal::Storage< T, Alloc >::Storage (Storage< T, Alloc > &&) delete
template<typename T , typename Alloc > casacore::arrays_internal::Storage< T, Alloc >::Storage (T * startIter, T * endIter, const Alloc & allocator, std::false_type , std::true_type) inline private
Moving range constructor implementation.
Parameter integral is only a place-holder.
Definition at line 130 of file Storage.h.
template<typename T , typename Alloc > template<typename InputIterator > casacore::arrays_internal::Storage< T, Alloc >::Storage (InputIterator startIter, InputIterator endIter, const Alloc & allocator, std::false_type) inline private
Copying range constructor implementation for non-integral types.
Definition at line 139 of file Storage.h.
template<typename T , typename Alloc > template<typename Integral > casacore::arrays_internal::Storage< T, Alloc >::Storage (Integral n, Integral val, const Alloc & allocator, std::true_type) inline private
Copying range constructor implementation for integral types.
Definition at line 148 of file Storage.h.
Member Function Documentation
template<typename T , typename Alloc > T* casacore::arrays_internal::Storage< T, Alloc >::construct (size_t n) inline private
These methods allocate the storage and construct the elements.
When any element constructor throws, the already constructed elements are destructed in reverse and the allocated storage is deallocated.
Definition at line 160 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::data().
template<typename T , typename Alloc > T* casacore::arrays_internal::Storage< T, Alloc >::construct (size_t n, const T & val) inline private
Definition at line 184 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::data().
template<typename T , typename Alloc > T* casacore::arrays_internal::Storage< T, Alloc >::construct_move (T * startIter, T * endIter) inline private
Definition at line 235 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::data().
template<typename T , typename Alloc > template<typename InputIterator > T* casacore::arrays_internal::Storage< T, Alloc >::construct_range (InputIterator startIter, InputIterator endIter) inline private
Definition at line 209 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::data().
template<typename T , typename Alloc > T* casacore::arrays_internal::Storage< T, Alloc >::data () inline
Return a pointer to the storage data.
Definition at line 109 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::_data.
Referenced by casacore::arrays_internal::Storage< T, Alloc >::construct(), casacore::arrays_internal::Storage< T, Alloc >::construct_move(), and casacore::arrays_internal::Storage< T, Alloc >::construct_range().
template<typename T , typename Alloc > const T* casacore::arrays_internal::Storage< T, Alloc >::data () const inline
Definition at line 110 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::_data.
template<typename T , typename Alloc > const Alloc& casacore::arrays_internal::Storage< T, Alloc >::get_allocator () const inline
Returns the allocator associated with this Storage.
Definition at line 117 of file Storage.h.
template<typename T , typename Alloc > bool casacore::arrays_internal::Storage< T, Alloc >::is_shared () const inline
Whether this Storage owns its data.
Returns true when this Storage was constructed with MakeFromSharedData().
Definition at line 121 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::_isShared.
template<typename T , typename Alloc > static std::unique_ptr<Storage<T, Alloc> > casacore::arrays_internal::Storage< T, Alloc >::MakeFromMove (T * startIter, T * endIter, const Alloc & allocator) inline static
Construct Storage from a range by moving.
The elements will be move constructed from the given values.
Definition at line 65 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::Storage().
template<typename T , typename Alloc > static std::unique_ptr<Storage<T, Alloc> > casacore::arrays_internal::Storage< T, Alloc >::MakeFromSharedData (T * existingData, size_t n, const Alloc & allocator) inline static
Construct a Storage from existing data.
The given pointer will not be owned by this class.
Definition at line 72 of file Storage.h.
template<typename T , typename Alloc > static std::unique_ptr<Storage<T, Alloc> > casacore::arrays_internal::Storage< T, Alloc >::MakeUninitialized (size_t n, const Alloc & allocator) inline static
Construct a Storage with uninitialized data.
This will skip the constructor of the elements. This is only allowed for trivial types.
Definition at line 84 of file Storage.h.
References casacore::value().
template<typename T , typename Alloc > Storage& casacore::arrays_internal::Storage< T, Alloc >::operator= (const Storage< T, Alloc > &) delete
template<typename T , typename Alloc > Storage& casacore::arrays_internal::Storage< T, Alloc >::operator= (Storage< T, Alloc > &&) delete
template<typename T , typename Alloc > size_t casacore::arrays_internal::Storage< T, Alloc >::size () const inline
Size of the data, zero if empty.
Definition at line 114 of file Storage.h.
References casacore::arrays_internal::Storage< T, Alloc >::_data, and casacore::arrays_internal::Storage< T, Alloc >::_end.
Referenced by casacore::arrays_internal::Storage< T, Alloc >::~Storage().
Member Data Documentation
template<typename T , typename Alloc > T* casacore::arrays_internal::Storage< T, Alloc >::_data private
Definition at line 277 of file Storage.h.
Referenced by casacore::arrays_internal::Storage< T, Alloc >::data(), casacore::arrays_internal::Storage< T, Alloc >::size(), and casacore::arrays_internal::Storage< T, Alloc >::~Storage().
template<typename T , typename Alloc > T* casacore::arrays_internal::Storage< T, Alloc >::_end private
Definition at line 278 of file Storage.h.
Referenced by casacore::arrays_internal::Storage< T, Alloc >::size().
template<typename T , typename Alloc > bool casacore::arrays_internal::Storage< T, Alloc >::_isShared private
Definition at line 279 of file Storage.h.
Referenced by casacore::arrays_internal::Storage< T, Alloc >::is_shared(), and casacore::arrays_internal::Storage< T, Alloc >::~Storage().
The documentation for this class was generated from the following file:
casa/Arrays/Storage.h