casacore: casacore::TableParseSelect Class Reference
casacore::TableParseSelect Class Reference
TaQL_module_internal_classes
Select-class for flex/bison scanner/parser for TableParse.
#include <TableParse.h>
Public Types
enum CommandType {
PSELECT,
PUPDATE,
PINSERT,
PDELETE,
PCOUNT,
PCALC,
PCRETAB
}
enum GroupAggrType {
GROUPBY,
AGGR_FUNCS,
ONLY_COUNTALL
}
Public Member Functions
TableParseSelect (CommandType type)
Construct.
~TableParseSelect ()
Destructor.
CommandType commandType () const
Return the command type.
TableExprNode getNode () const
Return the expression node.
void execute (Bool showTimings, Bool setInGiving, Bool mustSelect, uInt maxRow, Bool doTracing=False)
Execute the select command (select/sort/projection/groupby/having/giving).
Table doFromQuery (Bool showTimings)
Execute a query in a from clause resulting in a Table.
TableExprNode doSubQuery (Bool showTimings)
Execute a subquery and create an appropriate node for the result.
TableExprNode doExists (Bool noexists, Bool showTimings)
Test if a subquery has sufficient elements.
void show (ostream &os) const
Show the expression tree.
void handleWhere (const TableExprNode &)
Keep the selection expression.
void handleGroupby (const vector< TableExprNode > &, Bool rollup)
Keep the groupby expressions.
void handleHaving (const TableExprNode &)
Keep the having expression.
void handleCalcComm (const TableExprNode &)
Keep the expression of a calculate command.
void handleCreTab (const String &tableName, const Record &dmInfo)
Keep the create table command.
void handleColSpec (const String &columnName, const String &dataType, const Record &spec, Bool isCOrder=False)
Keep the column specification in a create table command.
void addUpdate (TableParseUpdate *upd)
Add an update object.
void handleUpdate ()
Keep the update expressions.
void handleInsert ()
Make ready for the insert expression.
void handleInsert (TableParseSelect *sel)
void handleCount ()
Make ready for a COUNT command.
void handleSort (const std::vector< TableParseSort > &sortList, Bool noDuplicates, Sort::Order defaultSortOrder)
Keep the sort expressions.
void handleLimit (const TableExprNodeSetElem &expr)
Evaluate and keep limit/offset/stride given as start:end:incr.
void handleLimit (const TableExprNode &expr)
Evaluate and keep the limit value.
void handleOffset (const TableExprNode &expr)
Evaluate and keep the offset value.
void addTable (Int tabnr, const String &name, const Table &table, const String &shorthand, const vector< const Table * > tempTables, const vector< TableParseSelect * > &stack)
Add a table nr, name, or object to the container.
void replaceTable (const Table &table)
Replace the first table (used by CALC command).
TableExprNode handleKeyCol (const String &name, Bool tryProj)
Find the keyword or column name and create a TableExprNode from it.
TableExprNode handleFunc (const String &name, const TableExprNodeSet &arguments, const TaQLStyle &)
Handle a function.
void handleColumn (Int type, const String &name, const TableExprNode &expr, const String &newName, const String &newDtype)
Add a column to the list of column names.
void handleColumnFinish (Bool distinct)
Finish the addition of columns to the list of column names.
void handleGiving (const String &name, Int type)
Handle the name and type given in a GIVING clause.
void handleGiving (const TableExprNodeSet &)
Handle the set given in a GIVING clause.
const Block< String > & getColumnNames () const
Get the projected column names.
const Table & getTable () const
Get the resulting table.
Static Public Member Functions
static TableExprNode handleSlice (const TableExprNode &array, const TableExprNodeSet &indices, const TaQLStyle &)
Handle a slice operator.
static TableExprNode makeFuncNode (const String &name, const TableExprNodeSet &arguments, const Vector< int > &ignoreFuncs, const Table &table, const TaQLStyle &)
Make a function object node for the given function name and arguments.
static void checkAggrFuncs (const TableExprNode &node)
An exception is thrown if the node uses an aggregate function.
Private Member Functions
Int testGroupAggr (vector< TableExprNodeRep * > &aggr) const
Test if groupby or aggregate functions are given.
vector< TableExprNodeRep * > getAggrNodes () const
Get the aggregate functions used in SELECT and HAVING.
void doUpdate (Bool showTimings, const Table &origTable, Table &updTable, const Vector< uInt > &rownrs, const CountedPtr< TableExprGroupResult > &groups=CountedPtr< TableExprGroupResult >())
Do the update step.
Table doInsert (Bool showTimings, Table &table)
Do the insert step and return a selection containing the new rows.
void doDelete (Bool showTimings, Table &table)
Do the delete step.
Table doCount (Bool showTimings, const Table &)
Do the count step returning a memory table containing the unique column values and the counts of the column values.
Table doProject (Bool showTimings, const Table &, const CountedPtr< TableExprGroupResult > &groups=CountedPtr< TableExprGroupResult >())
Do the projection step returning a table containing the projection.
Table doProjectExpr (Bool useSel, const CountedPtr< TableExprGroupResult > &groups)
Do the projection containing column expressions.
void makeProjectExprTable ()
Make the (empty) table for the epxression in the SELECT clause.
void makeProjectExprSel ()
Fill projectExprSelColumn_p telling the columns to be projected at the first stage.
Table adjustApplySelNodes (const Table &)
Set the selected rows for the column objects in applySelNodes_p.
CountedPtr< TableExprGroupResult > doGroupby (bool showTimings, vector< TableExprNodeRep * > aggrNodes, Int groupAggrUsed)
Do the groupby/aggregate step and return its result.
void doHaving (Bool showTimings, const CountedPtr< TableExprGroupResult > &groups)
Do the HAVING step.
CountedPtr< TableExprGroupResult > doOnlyCountAll (TableExprNodeRep *aggrNode)
Do a groupby/aggregate step that only does a 'select count(*)'.
CountedPtr< TableExprGroupResult > doGroupByAggr (const vector< TableExprNodeRep * > &aggrNodes)
Do a full groupby/aggregate step.
void doSort (Bool showTimings)
Do the sort step.
void doLimOff (Bool showTimings)
Do the limit/offset step.
Table doLimOff (Bool showTimings, const Table &table)
Table doDistinct (Bool showTimings, const Table &table)
Do the 'select distinct' step.
Table doFinish (Bool showTimings, Table &table)
Finish the table (rename, copy, and/or flush).
template<typename TCOL , typename TNODE >
void updateValue2 (uInt row, const TableExprId &rowid, Bool isScalarCol, const TableExprNode &node, TableColumn &col, const Slicer *slicerPtr, IPosition &blc, IPosition &trc, IPosition &inc)
Update the values in the columns (helpers of doUpdate).
template<typename T >
void updateValue1 (uInt row, const TableExprId &rowid, Bool isScalarCol, const TableExprNode &node, TableColumn &col, const Slicer *slicerPtr, IPosition &blc, IPosition &trc, IPosition &inc)
DataType makeDataType (DataType dtype, const String &dtstr, const String &colName)
Make a data type from the string.
Sort::Order getOrder (const TableParseSort &key) const
Get the order for this key.
TableExprNode getColSet ()
Make an array from the contents of a column in a subquery.
TableExprNode makeSubSet () const
Make a set from the results of the subquery.
Int64 evalIntScaExpr (const TableExprNode &expr) const
Evaluate an int scalar expression.
Bool splitName (String &shorthand, String &columnName, Vector< String > &fieldNames, const String &name, Bool checkError) const
Split a name into its parts (shorthand, column and field names).
Table findTable (const String &shorthand) const
Find a table for the given shorthand.
void handleWildColumn (Int stringType, const String &name)
Handle the selection of a wildcarded column name.
void addColumnDesc (TableDesc &td, DataType dtype, const String &colName, Int options, Int ndim, const IPosition &shape, const String &dmType, const String &dmGroup, const String &comment, const String &unitName)
Add the description of a column to the table description.
Block< String > getStoredColumns (const Table &tab) const
Find the names of all stored columns in a table.
template<typename T >
vector< CountedPtr
< TableExprGroupFuncSet > > doGroupByAggrSingleKey (const vector< TableExprNodeRep * > &aggrNodes)
Create the set of aggregate functions and groupby keys in case a single groupby key is given.
vector< CountedPtr
< TableExprGroupFuncSet > > doGroupByAggrMultipleKeys (const vector< TableExprNodeRep * > &aggrNodes)
Create the set of aggregate functions and groupby keys in case multiple keys are given.
Static Private Member Functions
static
TableExprFuncNode::FunctionType findFunc (const String &name, uInt narguments, const Vector< Int > &ignoreFuncs)
Find the function code belonging to a function name.
static Table tableKey (const String &fullName, const String &shorthand, const String &columnName, const Vector< String > &fieldNames, const vector< TableParseSelect * > &stack)
Try to find the keyword representing a table in one of the tables in any select block (from inner to outer).
static Table findTableKey (const Table &table, const String &columnName, const Vector< String > &keyNames)
Try to find the keyword representing a table in the given table.
Private Attributes
CommandType commandType_p
TableDesc tableDesc_p
vector< TableParse > fromTables_p
Block< String > columnNames_p
Block< TableExprNode > columnExpr_p
Block< String > columnOldNames_p
Block< String > columnDtypes_p
uInt nrSelExprUsed_p
Bool distinct_p
String resultName_p
Int resultType_p
TableExprNodeSet * resultSet_p
TableExprNode node_p
vector< TableExprNode > groupbyNodes_p
Bool groupbyRollup_p
TableExprNode havingNode_p
Int64 limit_p
Int64 endrow_p
Int64 offset_p
Int64 stride_p
std::vector< TableParseUpdate * > update_p
TableParseSelect * insSel_p
std::vector< TableParseSort > sort_p
Bool noDupl_p
Sort::Order order_p
vector< TableExprNode > applySelNodes_p
Table table_p
Table firstColTable_p
String firstColName_p
Table projectExprTable_p
Block< uInt > projectExprSubset_p
Block< Bool > projectExprSelColumn_p
Vector< uInt > rownrs_p
Detailed Description
Select-class for flex/bison scanner/parser for TableParse.
Intended use:
Internal
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Prerequisite
TableParse
TableGram.l and .y (flex and bison grammar)
Synopsis
This class is needed for the the actions in the flex scanner and bison parser. This stores the information by constructing TableParse objects as needed and storing them in a vector.
Motivation
It is necessary to be able to give a table select command in ASCII. This can be used in a CLI or in the table browser to get a subset of a table or to sort a table.
Definition at line 346 of file TableParse.h.
Member Enumeration Documentation
enum casacore::TableParseSelect::CommandType
Enumerator:
PSELECT
PUPDATE
PINSERT
PDELETE
PCOUNT
PCALC
PCRETAB
Definition at line 349 of file TableParse.h.
enum casacore::TableParseSelect::GroupAggrType
Enumerator:
GROUPBY
AGGR_FUNCS
ONLY_COUNTALL
Definition at line 359 of file TableParse.h.
Constructor & Destructor Documentation
casacore::TableParseSelect::TableParseSelect (CommandType type)
Construct.
casacore::TableParseSelect::~TableParseSelect ()
Destructor.
Member Function Documentation
void casacore::TableParseSelect::addColumnDesc (TableDesc & td, DataType dtype, const String & colName, Int options, Int ndim, const IPosition & shape, const String & dmType, const String & dmGroup, const String & comment, const String & unitName) private
Add the description of a column to the table description.
ndim < 0 means a scalar column.
void casacore::TableParseSelect::addTable (Int tabnr, const String & name, const Table & table, const String & shorthand, const vector< const Table * > tempTables, const vector< TableParseSelect * > & stack)
Add a table nr, name, or object to the container.
void casacore::TableParseSelect::addUpdate (TableParseUpdate * upd) inline
Add an update object.
Definition at line 833 of file TableParse.h.
References update_p.
Table casacore::TableParseSelect::adjustApplySelNodes (const Table &) private
Set the selected rows for the column objects in applySelNodes_p.
These nodes refer the original table. They requires different row numbers than the selected groups and projected columns. rownrs_p is changed to use row 0..n. It returns the Table containing the subset of rows in the input Table.
static void casacore::TableParseSelect::checkAggrFuncs (const TableExprNode & node) static
An exception is thrown if the node uses an aggregate function.
CommandType casacore::TableParseSelect::commandType () const inline
Return the command type.
Definition at line 372 of file TableParse.h.
References commandType_p.
Table casacore::TableParseSelect::doCount (Bool showTimings, const Table &) private
Do the count step returning a memory table containing the unique column values and the counts of the column values.
void casacore::TableParseSelect::doDelete (Bool showTimings, Table & table) private
Do the delete step.
Table casacore::TableParseSelect::doDistinct (Bool showTimings, const Table & table) private
Do the 'select distinct' step.
TableExprNode casacore::TableParseSelect::doExists (Bool noexists, Bool showTimings)
Test if a subquery has sufficient elements.
It uses default LIMIT=1, but that can be overidden in the subquery. The flag tells if NOT EXISTS or EXISTS was given.
Table casacore::TableParseSelect::doFinish (Bool showTimings, Table & table) private
Finish the table (rename, copy, and/or flush).
Table casacore::TableParseSelect::doFromQuery (Bool showTimings)
Execute a query in a from clause resulting in a Table.
CountedPtr<TableExprGroupResult> casacore::TableParseSelect::doGroupby (bool showTimings, vector< TableExprNodeRep * > aggrNodes, Int groupAggrUsed) private
Do the groupby/aggregate step and return its result.
CountedPtr<TableExprGroupResult> casacore::TableParseSelect::doGroupByAggr (const vector< TableExprNodeRep * > & aggrNodes) private
Do a full groupby/aggregate step.
vector<CountedPtr<TableExprGroupFuncSet> > casacore::TableParseSelect::doGroupByAggrMultipleKeys (const vector< TableExprNodeRep * > & aggrNodes) private
Create the set of aggregate functions and groupby keys in case multiple keys are given.
template<typename T > vector<CountedPtr<TableExprGroupFuncSet> > casacore::TableParseSelect::doGroupByAggrSingleKey (const vector< TableExprNodeRep * > & aggrNodes) inline private
Create the set of aggregate functions and groupby keys in case a single groupby key is given.
This offers much faster map access then doGroupByAggrMultiple.
We have to group the data according to the (possibly empty) groupby. We step through the table in the normal order which may not be the groupby order. A map<key,int> is used to keep track of the results where the int is the index in a vector of a set of aggregate function objects.
Loop through all rows. For each row generate the key to get the right entry.
Definition at line 682 of file TableParse.h.
References groupbyNodes_p, casacore::max(), rownrs_p, casacore::TableExprId::setRownr(), and casacore::ArrayBase::size().
void casacore::TableParseSelect::doHaving (Bool showTimings, const CountedPtr< TableExprGroupResult > & groups) private
Do the HAVING step.
Table casacore::TableParseSelect::doInsert (Bool showTimings, Table & table) private
Do the insert step and return a selection containing the new rows.
void casacore::TableParseSelect::doLimOff (Bool showTimings) private
Do the limit/offset step.
Table casacore::TableParseSelect::doLimOff (Bool showTimings, const Table & table) private
CountedPtr<TableExprGroupResult> casacore::TableParseSelect::doOnlyCountAll (TableExprNodeRep * aggrNode) private
Do a groupby/aggregate step that only does a 'select count(*)'.
Table casacore::TableParseSelect::doProject (Bool showTimings, const Table & , const CountedPtr< TableExprGroupResult > & groups = CountedPtr< TableExprGroupResult >()) private
Do the projection step returning a table containing the projection.
Table casacore::TableParseSelect::doProjectExpr (Bool useSel, const CountedPtr< TableExprGroupResult > & groups) private
Do the projection containing column expressions.
Use the selected or unselected columns depending on useSel.
void casacore::TableParseSelect::doSort (Bool showTimings) private
Do the sort step.
TableExprNode casacore::TableParseSelect::doSubQuery (Bool showTimings)
Execute a subquery and create an appropriate node for the result.
void casacore::TableParseSelect::doUpdate (Bool showTimings, const Table & origTable, Table & updTable, const Vector< uInt > & rownrs, const CountedPtr< TableExprGroupResult > & groups = CountedPtr< TableExprGroupResult >()) private
Do the update step.
Rows 0,1,2,.. in UpdTable are updated from the expression result for the rows in the given rownrs vector.
Int64 casacore::TableParseSelect::evalIntScaExpr (const TableExprNode & expr) const private
Evaluate an int scalar expression.
void casacore::TableParseSelect::execute (Bool showTimings, Bool setInGiving, Bool mustSelect, uInt maxRow, Bool doTracing = False)
Execute the select command (select/sort/projection/groupby/having/giving).
The setInGiving flag tells if a set in the GIVING part is allowed. The mustSelect flag tells if a SELECT command must do something. Usually that is required, but not for a SELECT in an INSERT command. Optionally the maximum nr of rows to be selected can be given. It will be used as the default value for the LIMIT clause. 0 = no maximum.
static TableExprFuncNode::FunctionType casacore::TableParseSelect::findFunc (const String & name, uInt narguments, const Vector< Int > & ignoreFuncs) static private
Find the function code belonging to a function name.
Functions to be ignored can be given (as function type values). If the function name is unknown, NRFUNC is returned.
Table casacore::TableParseSelect::findTable (const String & shorthand) const private
Find a table for the given shorthand.
If no shorthand is given, the first table is returned (if there). If not found, a null Table object is returned.
static Table casacore::TableParseSelect::findTableKey (const Table & table, const String & columnName, const Vector< String > & keyNames) static private
Try to find the keyword representing a table in the given table.
If the columnName is empty, the keyword is a table keyword. If not found, a null Table object is returned.
vector<TableExprNodeRep*> casacore::TableParseSelect::getAggrNodes () const private
Get the aggregate functions used in SELECT and HAVING.
TableExprNode casacore::TableParseSelect::getColSet () private
Make an array from the contents of a column in a subquery.
const Block< String > & casacore::TableParseSelect::getColumnNames () const inline
Get the projected column names.
Definition at line 827 of file TableParse.h.
References columnNames_p.
TableExprNode casacore::TableParseSelect::getNode () const inline
Return the expression node.
Definition at line 376 of file TableParse.h.
References node_p.
Sort::Order casacore::TableParseSelect::getOrder (const TableParseSort & key) const inline private
Get the order for this key.
Use the default order_p if not explicitly given with the key.
Definition at line 836 of file TableParse.h.
References casacore::TableParseSort::order(), order_p, and casacore::TableParseSort::orderGiven().
Block<String> casacore::TableParseSelect::getStoredColumns (const Table & tab) const private
Find the names of all stored columns in a table.
const Table & casacore::TableParseSelect::getTable () const inline
Get the resulting table.
Definition at line 830 of file TableParse.h.
References table_p.
void casacore::TableParseSelect::handleCalcComm (const TableExprNode &)
Keep the expression of a calculate command.
void casacore::TableParseSelect::handleColSpec (const String & columnName, const String & dataType, const Record & spec, Bool isCOrder = False)
Keep the column specification in a create table command.
void casacore::TableParseSelect::handleColumn (Int type, const String & name, const TableExprNode & expr, const String & newName, const String & newDtype)
Add a column to the list of column names.
void casacore::TableParseSelect::handleColumnFinish (Bool distinct)
Finish the addition of columns to the list of column names.
void casacore::TableParseSelect::handleCount ()
Make ready for a COUNT command.
It checks if all column expressions are scalar.
void casacore::TableParseSelect::handleCreTab (const String & tableName, const Record & dmInfo)
Keep the create table command.
TableExprNode casacore::TableParseSelect::handleFunc (const String & name, const TableExprNodeSet & arguments, const TaQLStyle &)
Handle a function.
void casacore::TableParseSelect::handleGiving (const String & name, Int type)
Handle the name and type given in a GIVING clause.
void casacore::TableParseSelect::handleGiving (const TableExprNodeSet &)
Handle the set given in a GIVING clause.
void casacore::TableParseSelect::handleGroupby (const vector< TableExprNode > & , Bool rollup)
Keep the groupby expressions.
It checks if they are all scalar expressions.
void casacore::TableParseSelect::handleHaving (const TableExprNode &)
Keep the having expression.
void casacore::TableParseSelect::handleInsert ()
Make ready for the insert expression.
The first one uses values (added via addUpdate), the second one a subquery.
void casacore::TableParseSelect::handleInsert (TableParseSelect * sel)
TableExprNode casacore::TableParseSelect::handleKeyCol (const String & name, Bool tryProj)
Find the keyword or column name and create a TableExprNode from it.
If tryProj=True it is first tried if the column is a coluymn in the projected table (i.e., result from the SELECT part).
void casacore::TableParseSelect::handleLimit (const TableExprNodeSetElem & expr)
Evaluate and keep limit/offset/stride given as start:end:incr.
void casacore::TableParseSelect::handleLimit (const TableExprNode & expr)
Evaluate and keep the limit value.
void casacore::TableParseSelect::handleOffset (const TableExprNode & expr)
Evaluate and keep the offset value.
static TableExprNode casacore::TableParseSelect::handleSlice (const TableExprNode & array, const TableExprNodeSet & indices, const TaQLStyle &) static
Handle a slice operator.
void casacore::TableParseSelect::handleSort (const std::vector< TableParseSort > & sortList, Bool noDuplicates, Sort::Order defaultSortOrder)
Keep the sort expressions.
void casacore::TableParseSelect::handleUpdate ()
Keep the update expressions.
void casacore::TableParseSelect::handleWhere (const TableExprNode &)
Keep the selection expression.
void casacore::TableParseSelect::handleWildColumn (Int stringType, const String & name) private
Handle the selection of a wildcarded column name.
DataType casacore::TableParseSelect::makeDataType (DataType dtype, const String & dtstr, const String & colName) private
Make a data type from the string.
It checks if it is compatible with the given (expression) data type.
static TableExprNode casacore::TableParseSelect::makeFuncNode (const String & name, const TableExprNodeSet & arguments, const Vector< int > & ignoreFuncs, const Table & table, const TaQLStyle &) static
Make a function object node for the given function name and arguments.
The ignoreFuncs vector contains invalid function codes.
void casacore::TableParseSelect::makeProjectExprSel () private
Fill projectExprSelColumn_p telling the columns to be projected at the first stage.
void casacore::TableParseSelect::makeProjectExprTable () private
Make the (empty) table for the epxression in the SELECT clause.
TableExprNode casacore::TableParseSelect::makeSubSet () const private
Make a set from the results of the subquery.
void casacore::TableParseSelect::replaceTable (const Table & table)
Replace the first table (used by CALC command).
void casacore::TableParseSelect::show (ostream & os) const
Show the expression tree.
Bool casacore::TableParseSelect::splitName (String & shorthand, String & columnName, Vector< String > & fieldNames, const String & name, Bool checkError) const private
Split a name into its parts (shorthand, column and field names).
True is returned when the name contained a keyword part. In that case fieldNames contains the keyword name and the possible subfields. The possible shorthand and the column name are filled in if it is a column keyword. If the name represents a column, fieldNames contains the subfields of the column (for the case where the column contains records). If the name is invalid, an exception is thrown if checkError=True. Otherwise the name is treated as a normal name without keyword.
static Table casacore::TableParseSelect::tableKey (const String & fullName, const String & shorthand, const String & columnName, const Vector< String > & fieldNames, const vector< TableParseSelect * > & stack) static private
Try to find the keyword representing a table in one of the tables in any select block (from inner to outer).
If not found, an exception is thrown.
Int casacore::TableParseSelect::testGroupAggr (vector< TableExprNodeRep * > & aggr) const private
Test if groupby or aggregate functions are given.
bit 0: on = groupby is given
bit 1: on = aggregate functions are given
bit 2: on = only select count(*) aggregate function is given
template<typename T > void casacore::TableParseSelect::updateValue1 (uInt row, const TableExprId & rowid, Bool isScalarCol, const TableExprNode & node, TableColumn & col, const Slicer * slicerPtr, IPosition & blc, IPosition & trc, IPosition & inc) private
template<typename TCOL , typename TNODE > void casacore::TableParseSelect::updateValue2 (uInt row, const TableExprId & rowid, Bool isScalarCol, const TableExprNode & node, TableColumn & col, const Slicer * slicerPtr, IPosition & blc, IPosition & trc, IPosition & inc) private
Update the values in the columns (helpers of doUpdate).
Member Data Documentation
vector<TableExprNode> casacore::TableParseSelect::applySelNodes_p private
Definition at line 775 of file TableParse.h.
Block<String> casacore::TableParseSelect::columnDtypes_p private
Definition at line 736 of file TableParse.h.
Block<TableExprNode> casacore::TableParseSelect::columnExpr_p private
Definition at line 732 of file TableParse.h.
Block<String> casacore::TableParseSelect::columnNames_p private
Definition at line 730 of file TableParse.h.
Referenced by getColumnNames().
Block<String> casacore::TableParseSelect::columnOldNames_p private
Definition at line 734 of file TableParse.h.
CommandType casacore::TableParseSelect::commandType_p private
Definition at line 722 of file TableParse.h.
Referenced by commandType().
Bool casacore::TableParseSelect::distinct_p private
Definition at line 740 of file TableParse.h.
Int64 casacore::TableParseSelect::endrow_p private
Definition at line 757 of file TableParse.h.
String casacore::TableParseSelect::firstColName_p private
Definition at line 781 of file TableParse.h.
Table casacore::TableParseSelect::firstColTable_p private
Definition at line 780 of file TableParse.h.
vector<TableParse> casacore::TableParseSelect::fromTables_p private
Definition at line 728 of file TableParse.h.
vector<TableExprNode> casacore::TableParseSelect::groupbyNodes_p private
Definition at line 749 of file TableParse.h.
Referenced by doGroupByAggrSingleKey().
Bool casacore::TableParseSelect::groupbyRollup_p private
Definition at line 750 of file TableParse.h.
TableExprNode casacore::TableParseSelect::havingNode_p private
Definition at line 752 of file TableParse.h.
TableParseSelect* casacore::TableParseSelect::insSel_p private
Definition at line 765 of file TableParse.h.
Int64 casacore::TableParseSelect::limit_p private
Definition at line 754 of file TableParse.h.
TableExprNode casacore::TableParseSelect::node_p private
Definition at line 747 of file TableParse.h.
Referenced by getNode().
Bool casacore::TableParseSelect::noDupl_p private
Definition at line 769 of file TableParse.h.
uInt casacore::TableParseSelect::nrSelExprUsed_p private
Definition at line 738 of file TableParse.h.
Int64 casacore::TableParseSelect::offset_p private
Definition at line 759 of file TableParse.h.
Sort::Order casacore::TableParseSelect::order_p private
Definition at line 771 of file TableParse.h.
Referenced by getOrder().
Block<Bool> casacore::TableParseSelect::projectExprSelColumn_p private
Definition at line 786 of file TableParse.h.
Block<uInt> casacore::TableParseSelect::projectExprSubset_p private
Definition at line 785 of file TableParse.h.
Table casacore::TableParseSelect::projectExprTable_p private
Definition at line 783 of file TableParse.h.
String casacore::TableParseSelect::resultName_p private
Definition at line 742 of file TableParse.h.
TableExprNodeSet* casacore::TableParseSelect::resultSet_p private
Definition at line 745 of file TableParse.h.
Int casacore::TableParseSelect::resultType_p private
Definition at line 743 of file TableParse.h.
Vector<uInt> casacore::TableParseSelect::rownrs_p private
Definition at line 788 of file TableParse.h.
Referenced by doGroupByAggrSingleKey().
std::vector<TableParseSort> casacore::TableParseSelect::sort_p private
Definition at line 767 of file TableParse.h.
Int64 casacore::TableParseSelect::stride_p private
Definition at line 761 of file TableParse.h.
Table casacore::TableParseSelect::table_p private
Definition at line 777 of file TableParse.h.
Referenced by getTable().
TableDesc casacore::TableParseSelect::tableDesc_p private
Definition at line 724 of file TableParse.h.
std::vector<TableParseUpdate*> casacore::TableParseSelect::update_p private
Definition at line 763 of file TableParse.h.
Referenced by addUpdate().
The documentation for this class was generated from the following file:
tables/TaQL/TableParse.h