casacore: casacore::Lattice< T > Class Template Reference
casacore::Lattice< T > Class Template Reference abstract
lattices package (libcasa_lattices) » Lattices_module
A templated, abstract base class for array-like objects.
#include <Functional.h>
Public Member Functions
virtual ~Lattice ()
a virtual destructor is needed so that it will use the actual destructor in the derived class
virtual Lattice< T > * clone () const =0
Make a copy of the derived object (reference semantics).
virtual DataType dataType () const
Get the data type of the lattice.
T operator() (const IPosition &where) const
Return the value of the single element located at the argument IPosition.
virtual T getAt (const IPosition &where) const
virtual void putAt (const T &value, const IPosition &where)
Put the value of a single element.
Bool get (COWPtr< Array< T > > &buffer, Bool removeDegenerateAxes=False) const
Functions which extract an Array of values from a Lattice.
Bool getSlice (COWPtr< Array< T > > &buffer, const Slicer &section, Bool removeDegenerateAxes=False) const
Bool getSlice (COWPtr< Array< T > > &buffer, const IPosition &start, const IPosition &shape, Bool removeDegenerateAxes=False) const
Bool getSlice (COWPtr< Array< T > > &buffer, const IPosition &start, const IPosition &shape, const IPosition &stride, Bool removeDegenerateAxes=False) const
Bool get (Array< T > &buffer, Bool removeDegenerateAxes=False)
Bool getSlice (Array< T > &buffer, const Slicer &section, Bool removeDegenerateAxes=False)
Bool getSlice (Array< T > &buffer, const IPosition &start, const IPosition &shape, Bool removeDegenerateAxes=False)
Bool getSlice (Array< T > &buffer, const IPosition &start, const IPosition &shape, const IPosition &stride, Bool removeDegenerateAxes=False)
Array< T > get (Bool removeDegenerateAxes=False) const
Array< T > getSlice (const Slicer &section, Bool removeDegenerateAxes=False) const
Array< T > getSlice (const IPosition &start, const IPosition &shape, Bool removeDegenerateAxes=False) const
Array< T > getSlice (const IPosition &start, const IPosition &shape, const IPosition &stride, Bool removeDegenerateAxes=False) const
void putSlice (const Array< T > &sourceBuffer, const IPosition &where, const IPosition &stride)
A function which places an Array of values within this instance of the Lattice at the location specified by the IPosition "where", incrementing by "stride".
void putSlice (const Array< T > &sourceBuffer, const IPosition &where)
void put (const Array< T > &sourceBuffer)
virtual void set (const T &value)
Set all elements in the Lattice to the given value.
virtual void apply (T(*function)(T))
Replace every element, x, of the Lattice with the result of f(x).
virtual void apply (T(*function)(const T &))
virtual void apply (const Functional< T, T > &function)
void operator+= (const Lattice< T > &other)
Add, subtract, multiple, or divide by another Lattice.
void operator-= (const Lattice< T > &other)
void operator *= (const Lattice< T > &other)
void operator/= (const Lattice< T > &other)
virtual void copyData (const Lattice< T > &from)
Copy the data from the given lattice to this one.
virtual void copyDataTo (Lattice< T > &to) const
Copy the data from this lattice to the given lattice.
virtual uInt advisedMaxPixels () const
This function returns the advised maximum number of pixels to include in the cursor of an iterator.
virtual LatticeIterInterface< T > * makeIter (const LatticeNavigator &navigator, Bool useRef) const
These functions are used by the LatticeIterator class to generate an iterator of the correct type for a specified Lattice.
virtual Bool doGetSlice (Array< T > &buffer, const Slicer &section)=0
The functions (in the derived classes) doing the actual work.
virtual void doPutSlice (const Array< T > &buffer, const IPosition &where, const IPosition &stride)=0
Public Member Functions inherited from casacore::LatticeBase
virtual ~LatticeBase ()
A virtual destructor is needed so that it will use the actual destructor in the derived class.
virtual String imageType () const
Get the image type (returns name of derived class).
virtual Bool isPersistent () const
Is the lattice persistent and can it be loaded by other processes as well? That is the case for a PagedArray or PagedImage and for an ImageExpr which does not use transient lattices or regions.
virtual Bool isPaged () const
Is the lattice paged to disk?
The default implementation returns False.
virtual Bool canReferenceArray () const
Can the lattice data be referenced as an array section? That is the case for an ArrayLattice or a Temp/SubLattice using it.
virtual Bool isWritable () const
Is the lattice writable?
The default implementation returns True.
virtual void save (const String &fileName) const
Save the image in an AipsIO file with the given name.
virtual Bool lock (FileLocker::LockType, uInt nattempts)
It is strongly recommended to use class LatticeLocker to handle lattice locking.
virtual void unlock ()
virtual Bool hasLock (FileLocker::LockType) const
virtual void resync ()
Resynchronize the Lattice object with the lattice file.
virtual void flush ()
Flush the data (but do not unlock).
virtual void tempClose ()
Temporarily close the lattice.
virtual void reopen ()
Explicitly reopen the temporarily closed lattice.
virtual String name (Bool stripPath=False) const
Return the name of the current Lattice object.
virtual IPosition shape () const =0
Return the shape of the Lattice including all degenerate axes (ie.
virtual uInt ndim () const
Return the number of axes in this Lattice.
virtual size_t nelements () const
Return the total number of elements in this Lattice.
size_t size () const
Bool conform (const LatticeBase &other) const
Return a value of "True" if this instance of Lattice and 'other' have the same shape, otherwise returns a value of "False".
virtual LELCoordinates lelCoordinates () const
Return the coordinates of the lattice.
IPosition niceCursorShape (uInt maxPixels) const
Returns a recommended cursor shape for iterating through all the pixels in the Lattice.
IPosition niceCursorShape () const
virtual Bool ok () const
Check class internals - used for debugging.
virtual IPosition doNiceCursorShape (uInt maxPixels) const
The function (in the derived classes) doing the actual work.
virtual uInt maximumCacheSize () const
Maximum cache size - not necessarily all used.
virtual void setMaximumCacheSize (uInt howManyPixels)
Set the maximum (allowed) cache size as indicated.
virtual void setCacheSizeInTiles (uInt howManyTiles)
Set the actual cache size for this Array to be big enough for the indicated number of tiles.
virtual void setCacheSizeFromPath (const IPosition &sliceShape, const IPosition &windowStart, const IPosition &windowLength, const IPosition &axisPath)
Set the cache size as to "fit" the indicated path.
virtual void clearCache ()
Clears and frees up the caches, but the maximum allowed cache size is unchanged from when setCacheSize was called.
virtual void showCacheStatistics (ostream &os) const
Report on cache success.
Protected Member Functions
Lattice ()
Define default constructor to satisfy compiler.
virtual void handleMath (const Lattice< T > &from, int oper)
Handle the Math operators (+=, -=, *=, /=).
virtual void handleMathTo (Lattice< T > &to, int oper) const
Lattice (const Lattice< T > &)
Copy constructor and assignment can only be used by derived classes.
Lattice< T > & operator= (const Lattice< T > &)
template<>
void handleMathTo (Lattice< Bool > &, int) const
Protected Member Functions inherited from casacore::LatticeBase
LatticeBase ()
Define default constructor to be used by derived classes.
LatticeBase (const LatticeBase &)
Copy constructor and assignment can only be used by derived classes.
LatticeBase & operator= (const LatticeBase &)
void throwBoolMath () const
Throw an exception for arithmetic on a Bool Lattice.
Detailed Description
template<class T>
class casacore::Lattice< T >
A templated, abstract base class for array-like objects.
Intended use:
Public interface
Review Status
Reviewed By:
Peter Barnes
Date Reviewed:
1999/10/30
Test programs:
tArrayLattice
Demo programs:
dLattice
Prerequisite
IPosition
Array
LatticeBase
Abstract Base class Inheritance - try "Advanced C++" by James O. Coplien, Ch. 5.
Etymology
Lattice: "A regular, periodic configuration of points, particles, or objects, throughout an area of a space..." (American Heritage Directory) This definition matches our own: an n-dimensional arrangement of items, on regular orthogonal axes.
Synopsis
This pure abstract base class defines the operations which may be performed on any concrete class derived from it. It has only a few non-pure virtual member functions. The fundamental contribution of this class, therefore, is that it defines the operations derived classes must provide:
how to extract a "slice" (or sub-array, or subsection) from a Lattice.
how to copy a slice in.
how to get and put a single element
how to apply a function to all elements
various shape related functions.
The base class LatticeBase contains several functions not dependent on the template parameter.
Tip: Lattices always have a zero origin;
Example
Because Lattice is an abstract base class, an actual instance of this class cannot be constructed. However the interface it defines can be used inside a function. This is always recommended as it allows functions which have Lattices as arguments to work for any derived class.
I will give a few examples here and then refer the reader to the ArrayLattice class (a memory resident Lattice) and the PagedArray class (a disk based Lattice) which contain further examples with concrete classes (rather than an abstract one). All the examples shown below are used in the dLattice.cc demo program.
Example 1:
This example calculates the mean of the Lattice. Because Lattices can be too large to fit into physical memory it is not good enough to simply use getSlice to read all the elements into an Array. Instead the Lattice is accessed in chunks which can fit into memory (the size is determined by the advisedMaxPixels and niceCursorShape functions). The LatticeIterator::cursor() function then returns each of these chunks as an Array and the standard Array based functions are used to calculate the mean on each of these chunks. Functions like this one are the recommended way to access Lattices as the LatticeIterator will correctly setup any required caches.
Complex latMean(const Lattice<Complex>& lat) {
const uInt cursorSize = lat.advisedMaxPixels();
const IPosition cursorShape = lat.niceCursorShape(cursorSize);
const IPosition latticeShape = lat.shape();
Complex currentSum = 0.0f;
size_t nPixels = 0u;
RO_LatticeIterator<Complex> iter(lat,
LatticeStepper(latticeShape, cursorShape));
for (iter.reset(); !iter.atEnd(); iter++){
currentSum += sum(iter.cursor());
nPixels += iter.cursor().nelements();
}
return currentSum/nPixels;
}
Example 2:
Sometimes it will be neccesary to access slices of a Lattice in a nearly random way. Often this can be done using the subSection commands in the LatticeStepper class. But it is also possible to use the getSlice and putSlice functions. The following example does a two-dimensional Real to Complex Fourier transform. This example is restricted to four-dimensional Arrays (unlike the previous example) and does not set up any caches (caching is currently only used with PagedArrays). So only use getSlice and putSlice when things cannot be done using LatticeIterators.
void FFT2DReal2Complex(Lattice<Complex>& result,
const Lattice<Float>& input){
AlwaysAssert(input.ndim() == 4, AipsError);
const IPosition shape = input.shape();
const uInt nx = shape(0);
AlwaysAssert (nx > 1, AipsError);
const uInt ny = shape(1);
AlwaysAssert (ny > 1, AipsError);
const uInt npol = shape(2);
const uInt nchan = shape(3);
const IPosition resultShape = result.shape();
AlwaysAssert(resultShape.nelements() == 4, AipsError);
AlwaysAssert(resultShape(3) == nchan, AipsError);
AlwaysAssert(resultShape(2) == npol, AipsError);
AlwaysAssert(resultShape(1) == ny, AipsError);
AlwaysAssert(resultShape(0) == nx/2 + 1, AipsError);
const IPosition inputSliceShape(4,nx,ny,1,1);
const IPosition resultSliceShape(4,nx/2+1,ny,1,1);
COWPtr<Array<Float> >
inputArrPtr(new Array<Float>(inputSliceShape.nonDegenerate()));
Array<Complex> resultArray(resultSliceShape.nonDegenerate());
FFTServer<Float, Complex> FFT2D(inputSliceShape.nonDegenerate());
IPosition start(4,0);
Bool isARef;
for (uInt c = 0; c < nchan; c++){
for (uInt p = 0; p < npol; p++){
isARef = input.getSlice(inputArrPtr,
Slicer(start,inputSliceShape), True);
FFT2D.fft(resultArray, *inputArrPtr);
result.putSlice(resultArray, start);
start(2) += 1;
}
start(2) = 0;
start(3) += 1;
}
}
Note that the LatticeFFT class offers a nice way to do lattice based FFTs.
Example 3:
Occasionally you may want to access a few elements of a Lattice without all the difficulty involved in setting up Iterators or calling getSlice and putSlice. This is demonstrated in the example below. Setting a single element can be done with the putAt function, while getting a single element can be done with the parenthesis operator. Using these functions to access many elements of a Lattice is not recommended as this is the slowest access method.
In this example an ideal point spread function will be inserted into an empty Lattice. As with the previous examples all the action occurs inside a function because Lattice is an interface (abstract) class.
void makePsf(Lattice<Float>& psf) {
const IPosition centrePos = psf.shape()/2;
psf.set(0.0f);       // this sets all the elements to zero
// As it uses a LatticeIterator it is efficient
psf.putAt (1, centrePos);  // This sets just the centre element to one
AlwaysAssert(near(psf(centrePos), 1.0f, 1E-6), AipsError);
AlwaysAssert(near(psf(centrePos*0), 0.0f, 1E-6), AipsError);
}
Motivation
Creating an abstract base class which provides a common interface between memory and disk based arrays has a number of advantages.
It allows functions common to all arrays to be written independent of the way the data is stored. This is illustrated in the three examples above.
It reduces the learning curve for new users who only have to become familiar with one interface (ie. Lattice) rather than distinct interfaces for different array types.
To Do
Make PagedArray cache functions virtual in this base class.
Definition at line 37 of file Functional.h.
Constructor & Destructor Documentation
~Lattice()
template<class T> virtual casacore::Lattice< T >::~Lattice () virtual
a virtual destructor is needed so that it will use the actual destructor in the derived class
Lattice() [1/2]
template<class T> casacore::Lattice< T >::Lattice () inline protected
Define default constructor to satisfy compiler.
Definition at line 407 of file Lattice.h.
Lattice() [2/2]
template<class T> casacore::Lattice< T >::Lattice (const Lattice< T > &) inline protected
Copy constructor and assignment can only be used by derived classes.
Definition at line 419 of file Lattice.h.
Member Function Documentation
advisedMaxPixels()
template<class T> virtual uInt casacore::Lattice< T >::advisedMaxPixels () const virtual
This function returns the advised maximum number of pixels to include in the cursor of an iterator.
The default implementation returns a number that is a power of two and includes enough pixels to consume between 4 and 8 MBytes of memory.
Implements casacore::LatticeBase.
Reimplemented in casacore::PagedArray< T >, casacore::PagedArray< Bool >, casacore::PagedImage< T >, casacore::HDF5Image< T >, casacore::HDF5Lattice< T >, casacore::HDF5Lattice< Bool >, casacore::TempImage< T >, casacore::SubLattice< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::ArrayLattice< T >, casacore::ArrayLattice< Bool >, casacore::MIRIADImage, casacore::FITSImage, casacore::SubImage< T >, casacore::CurvedImage2D< T >, casacore::FITSQualityImage, casacore::ExtendLattice< T >, casacore::CurvedLattice2D< T >, casacore::LatticeRegion, casacore::RebinLattice< T >, casacore::RebinImage< T >, casacore::ExtendImage< T >, casacore::LCMask, casacore::LCPagedMask, and casacore::LCHDF5Mask.
apply() [1/3]
template<class T> virtual void casacore::Lattice< T >::apply (T(*)(T) function) virtual
Replace every element, x, of the Lattice with the result of f(x).
You must pass in the address of the function – so the function must be declared and defined in the scope of your program. All versions of apply require a function that accepts a single argument of type T (the Lattice template type) and return a result of the same type. The first apply expects a function with an argument passed by value; the second expects the argument to be passed by const reference; the third requires an instance of the class Functional<T,T>. The first form ought to run faster for the built-in types, which may be an issue for large Lattices stored in memory, where disk access is not an issue.
Reimplemented in casacore::PagedImage< T >, casacore::TempImage< T >, casacore::HDF5Image< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::LatticeRegion, casacore::LCRegion, and casacore::LCRegionSingle.
apply() [2/3]
template<class T> virtual void casacore::Lattice< T >::apply (T(*)(const T &) function) virtual
Reimplemented in casacore::PagedImage< T >, casacore::TempImage< T >, casacore::HDF5Image< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::LatticeRegion, casacore::LCRegion, and casacore::LCRegionSingle.
apply() [3/3]
template<class T> virtual void casacore::Lattice< T >::apply (const Functional< T, T > & function) virtual
Reimplemented in casacore::PagedImage< T >, casacore::TempImage< T >, casacore::HDF5Image< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::LatticeRegion, casacore::LCRegion, and casacore::LCRegionSingle.
clone()
template<class T> virtual Lattice<T>* casacore::Lattice< T >::clone () const pure virtual
Make a copy of the derived object (reference semantics).
Implements casacore::LatticeBase.
Implemented in casacore::PagedArray< T >, casacore::PagedArray< Bool >, casacore::MaskedLattice< T >, casacore::ArrayLattice< T >, casacore::ArrayLattice< Bool >, casacore::HDF5Lattice< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::HDF5Lattice< Bool >, casacore::FITSMask, casacore::FITSQualityMask, casacore::LCRegion, and casacore::LatticeRegion.
copyData()
template<class T> virtual void casacore::Lattice< T >::copyData (const Lattice< T > & from) virtual
Copy the data from the given lattice to this one.
The default implementation uses function copyDataTo.
Reimplemented in casacore::LatticeRegion, casacore::LCRegion, and casacore::LCRegionSingle.
copyDataTo()
template<class T> virtual void casacore::Lattice< T >::copyDataTo (Lattice< T > & to) const virtual
Copy the data from this lattice to the given lattice.
The default implementation only copies data (thus no mask, etc.).
Reimplemented in casacore::LatticeExpr< T >.
dataType()
template<class T> virtual DataType casacore::Lattice< T >::dataType () const virtual
Get the data type of the lattice.
Implements casacore::LatticeBase.
Reimplemented in casacore::MIRIADImage, casacore::FITSImage, and casacore::FITSQualityImage.
doGetSlice()
template<class T> virtual Bool casacore::Lattice< T >::doGetSlice (Array< T > & buffer, const Slicer & section) pure virtual
The functions (in the derived classes) doing the actual work.
These functions are public, so they can be used internally in the various Lattice classes, which is especially useful for doGetSlice.
However, doGetSlice does not call Slicer::inferShapeFromSource to fill in possible unspecified section values. Therefore one should normally use one of the get(Slice) functions. doGetSlice should be used with care and only when performance is an issue.
Implemented in casacore::PagedArray< T >, casacore::PagedArray< Bool >, casacore::TempImage< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::SubLattice< T >, casacore::PagedImage< T >, casacore::ImageConcat< T >, casacore::HDF5Lattice< T >, casacore::HDF5Lattice< Bool >, casacore::LatticeConcat< T >, casacore::SubImage< T >, casacore::ArrayLattice< T >, casacore::ArrayLattice< Bool >, casacore::LatticeRegion, casacore::LatticeExpr< T >, casacore::CurvedImage2D< T >, casacore::ExtendLattice< T >, casacore::ImageExpr< T >, casacore::CurvedLattice2D< T >, casacore::HDF5Image< T >, casacore::RebinImage< T >, casacore::RebinLattice< T >, casacore::ExtendImage< T >, casacore::LCRegionMulti, casacore::FITSMask, casacore::FITSQualityMask, and casacore::LCRegionSingle.
doPutSlice()
template<class T> virtual void casacore::Lattice< T >::doPutSlice (const Array< T > & buffer, const IPosition & where, const IPosition & stride) pure virtual
Implemented in casacore::PagedArray< T >, casacore::PagedArray< Bool >, casacore::TempImage< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::SubLattice< T >, casacore::ImageConcat< T >, casacore::PagedImage< T >, casacore::LatticeConcat< T >, casacore::HDF5Lattice< T >, casacore::HDF5Lattice< Bool >, casacore::SubImage< T >, casacore::ArrayLattice< T >, casacore::ArrayLattice< Bool >, casacore::LatticeRegion, casacore::LatticeExpr< T >, casacore::CurvedImage2D< T >, casacore::LCRegion, casacore::ExtendLattice< T >, casacore::ImageExpr< T >, casacore::CurvedLattice2D< T >, casacore::HDF5Image< T >, casacore::RebinImage< T >, casacore::RebinLattice< T >, casacore::ExtendImage< T >, casacore::FITSMask, casacore::FITSQualityMask, and casacore::LCRegionSingle.
Referenced by casacore::Lattice< Complex >::putSlice().
get() [1/3]
template<class T> Bool casacore::Lattice< T >::get (COWPtr< Array< T > > & buffer, Bool removeDegenerateAxes = False) const
Functions which extract an Array of values from a Lattice.
All the IPosition arguments must have the same number of axes as the underlying Lattice, otherwise, an exception is thrown.
The parameters are:
buffer: a COWPtr<Array<T>> or an Array<T>. See example 2 above for an example.
start: The starting position (or Bottom Left Corner), within the Lattice, of the data to be extracted.
shape: The shape of the data to be extracted. This is not a position within the Lattice but the actual shape the buffer will have after this function is called. This argument added to the "start" argument should be the "Top Right Corner".
stride: The increment for each axis. A stride of one will return every data element, a stride of two will return every other element. The IPosition elements may be different for each respective axis. Thus, a stride of IPosition(3,1,2,3) says: fill the buffer with every element whose position has a first index between start(0) and start(0)+shape(0), a second index which is every other element between start(1) and (start(1)+shape(1))*2, and a third index of every third element between start(2) and (start(2)+shape(2))*3.
section: Another way of specifying the start, shape and stride
removeDegenerateAxes: a Bool which dictates whether to remove "empty" axis created in buffer. (e.g. extracting an n-dimensional from an (n+1)-dimensional will fill 'buffer' with an array that has a degenerate axis (i.e. one axis will have a length = 1.) Setting removeDegenerateAxes = True will return a buffer with a shape that doesn't reflect these superfluous axes.)
The derived implementations of these functions return 'True' if "buffer" is a reference to Lattice data and 'False' if it
is a copy.
get() [2/3]
template<class T> Bool casacore::Lattice< T >::get (Array< T > & buffer, Bool removeDegenerateAxes = False)
get() [3/3]
template<class T> Array<T> casacore::Lattice< T >::get (Bool removeDegenerateAxes = False) const
getAt()
template<class T> virtual T casacore::Lattice< T >::getAt (const IPosition & where) const virtual
Reimplemented in casacore::PagedArray< T >, casacore::PagedArray< Bool >, casacore::PagedImage< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::SubLattice< T >, casacore::HDF5Image< T >, casacore::TempImage< T >, casacore::HDF5Lattice< T >, casacore::HDF5Lattice< Bool >, casacore::SubImage< T >, casacore::ArrayLattice< T >, and casacore::ArrayLattice< Bool >.
getSlice() [1/9]
template<class T> Bool casacore::Lattice< T >::getSlice (COWPtr< Array< T > > & buffer, const Slicer & section, Bool removeDegenerateAxes = False) const
getSlice() [2/9]
template<class T> Bool casacore::Lattice< T >::getSlice (COWPtr< Array< T > > & buffer, const IPosition & start, const IPosition & shape, Bool removeDegenerateAxes = False) const
getSlice() [3/9]
template<class T> Bool casacore::Lattice< T >::getSlice (COWPtr< Array< T > > & buffer, const IPosition & start, const IPosition & shape, const IPosition & stride, Bool removeDegenerateAxes = False) const
getSlice() [4/9]
template<class T> Bool casacore::Lattice< T >::getSlice (Array< T > & buffer, const Slicer & section, Bool removeDegenerateAxes = False)
getSlice() [5/9]
template<class T> Bool casacore::Lattice< T >::getSlice (Array< T > & buffer, const IPosition & start, const IPosition & shape, Bool removeDegenerateAxes = False)
getSlice() [6/9]
template<class T> Bool casacore::Lattice< T >::getSlice (Array< T > & buffer, const IPosition & start, const IPosition & shape, const IPosition & stride, Bool removeDegenerateAxes = False)
getSlice() [7/9]
template<class T> Array<T> casacore::Lattice< T >::getSlice (const Slicer & section, Bool removeDegenerateAxes = False) const
getSlice() [8/9]
template<class T> Array<T> casacore::Lattice< T >::getSlice (const IPosition & start, const IPosition & shape, Bool removeDegenerateAxes = False) const
getSlice() [9/9]
template<class T> Array<T> casacore::Lattice< T >::getSlice (const IPosition & start, const IPosition & shape, const IPosition & stride, Bool removeDegenerateAxes = False) const
handleMath()
template<class T> virtual void casacore::Lattice< T >::handleMath (const Lattice< T > & from, int oper) protected virtual
Handle the Math operators (+=, -=, *=, /=).
They work similarly to copyData(To). However, they are not defined for Bool types, thus specialized below.
Referenced by casacore::Lattice< Complex >::operator *=(), casacore::Lattice< Complex >::operator+=(), casacore::Lattice< Complex >::operator-=(), and casacore::Lattice< Complex >::operator/=().
handleMathTo() [1/2]
template<class T> virtual void casacore::Lattice< T >::handleMathTo (Lattice< T > & to, int oper) const protected virtual
Reimplemented in casacore::LatticeExpr< T >.
handleMathTo() [2/2]
template<> void casacore::Lattice< Bool >::handleMathTo (Lattice< Bool > & , int) const inline protected
Definition at line 428 of file Lattice.h.
makeIter()
template<class T> virtual LatticeIterInterface<T>* casacore::Lattice< T >::makeIter (const LatticeNavigator & navigator, Bool useRef) const virtual
These functions are used by the LatticeIterator class to generate an iterator of the correct type for a specified Lattice.
Not recommended for general use.
The default implementation creates a LatticeIterInterface object.
Reimplemented in casacore::PagedArray< T >, casacore::PagedArray< Bool >, casacore::PagedImage< T >, casacore::ImageConcat< T >, casacore::HDF5Image< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::SubLattice< T >, casacore::TempImage< T >, casacore::SubImage< T >, casacore::HDF5Lattice< T >, casacore::HDF5Lattice< Bool >, casacore::CurvedImage2D< T >, casacore::ImageExpr< T >, casacore::ImageExpr< Bool >, casacore::RebinImage< T >, casacore::ExtendImage< T >, casacore::LatticeRegion, casacore::LCRegionSingle, casacore::LCMask, casacore::LCPagedMask, and casacore::LCHDF5Mask.
operator *=()
template<class T> void casacore::Lattice< T >::operator *= (const Lattice< T > & other) inline
Definition at line 365 of file Lattice.h.
operator()()
template<class T> T casacore::Lattice< T >::operator() (const IPosition & where) const
Return the value of the single element located at the argument IPosition.
The default implementation uses getSlice.
operator+=()
template<class T> void casacore::Lattice< T >::operator+= (const Lattice< T > & other) inline
Add, subtract, multiple, or divide by another Lattice.
The other Lattice can be a scalar (e.g. the result of LatticeExpr). Possible masks are not taken into account.
Definition at line 361 of file Lattice.h.
operator-=()
template<class T> void casacore::Lattice< T >::operator-= (const Lattice< T > & other) inline
Definition at line 363 of file Lattice.h.
operator/=()
template<class T> void casacore::Lattice< T >::operator/= (const Lattice< T > & other) inline
Definition at line 367 of file Lattice.h.
operator=()
template<class T> Lattice<T>& casacore::Lattice< T >::operator= (const Lattice< T > &) inline protected
Definition at line 421 of file Lattice.h.
put()
template<class T> void casacore::Lattice< T >::put (const Array< T > & sourceBuffer)
putAt()
template<class T> virtual void casacore::Lattice< T >::putAt (const T & value, const IPosition & where) virtual
Put the value of a single element.
The default implementation uses putSlice.
Reimplemented in casacore::PagedArray< T >, casacore::PagedArray< Bool >, casacore::PagedImage< T >, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::SubLattice< T >, casacore::HDF5Image< T >, casacore::TempImage< T >, casacore::HDF5Lattice< T >, casacore::HDF5Lattice< Bool >, casacore::LatticeRegion, casacore::SubImage< T >, casacore::ArrayLattice< T >, casacore::ArrayLattice< Bool >, casacore::LCRegion, and casacore::LCRegionSingle.
putSlice() [1/2]
template<class T> void casacore::Lattice< T >::putSlice (const Array< T > & sourceBuffer, const IPosition & where, const IPosition & stride) inline
A function which places an Array of values within this instance of the Lattice at the location specified by the IPosition "where", incrementing by "stride".
All of the IPosition arguments must be of the same dimensionality as the Lattice. The sourceBuffer array may (and probably will) have less axes than the Lattice. The stride defaults to one if not specified.
Definition at line 329 of file Lattice.h.
putSlice() [2/2]
template<class T> void casacore::Lattice< T >::putSlice (const Array< T > & sourceBuffer, const IPosition & where)
set()
template<class T> virtual void casacore::Lattice< T >::set (const T & value) virtual
Set all elements in the Lattice to the given value.
Reimplemented in casacore::TempImage< T >, casacore::LatticeRegion, casacore::TempLattice< T >, casacore::TempLattice< Float >, casacore::TempLattice< typename casacore::NumericTraits< T >::ConjugateType >, casacore::TempLattice< Complex >, casacore::ArrayLattice< T >, casacore::ArrayLattice< Bool >, casacore::LCRegion, and casacore::LCRegionSingle.
The documentation for this class was generated from the following files:
casa/BasicMath/Functional.h
lattices/Lattices/Lattice.h