casacore: casacore::ROMSProcessorColumns Class Reference
casacore::ROMSProcessorColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSProcessor columns.
#include <MSProcessorColumns.h>
Public Member Functions
ROMSProcessorColumns (const MSProcessor &msProcessor)
Create a columns object that accesses the data in the specified Table.
~ROMSProcessorColumns ()
The destructor does nothing special.
const ROScalarColumn< Bool > & flagRow () const
Access to required columns.
const ROScalarColumn< Int > & modeId () const
const ROScalarColumn< String > & type () const
const ROScalarColumn< Int > & typeId () const
const ROScalarColumn< String > & subType () const
const ROScalarColumn< Int > & passId () const
Read-only access to optional columns.
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSProcessorColumns ()
void attach (const MSProcessor &msProcessor)
Private Member Functions
ROMSProcessorColumns (const ROMSProcessorColumns &)
ROMSProcessorColumns & operator= (const ROMSProcessorColumns &)
void attachOptionalCols (const MSProcessor &msField)
Private Attributes
ROScalarColumn< Bool > flagRow_p
ROScalarColumn< Int > modeId_p
ROScalarColumn< String > type_p
ROScalarColumn< Int > typeId_p
ROScalarColumn< String > subType_p
ROScalarColumn< Int > passId_p
Detailed Description
A class to provide easy read-only access to MSProcessor columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSProcessor
ArrayColumn
ScalarColumn
Etymology
ROMSProcessorColumns stands for Read-Only MeasurementSet Processor Table columns.
Synopsis
This class provides read-only access to the columns in the MSProcessor Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 72 of file MSProcessorColumns.h.
Constructor & Destructor Documentation
ROMSProcessorColumns() [1/3]
casacore::ROMSProcessorColumns::ROMSProcessorColumns (const MSProcessor & msProcessor)
Create a columns object that accesses the data in the specified Table.
~ROMSProcessorColumns()
casacore::ROMSProcessorColumns::~ROMSProcessorColumns ()
The destructor does nothing special.
ROMSProcessorColumns() [2/3]
casacore::ROMSProcessorColumns::ROMSProcessorColumns () protected
ROMSProcessorColumns() [3/3]
casacore::ROMSProcessorColumns::ROMSProcessorColumns (const ROMSProcessorColumns &) private
Member Function Documentation
attach()
void casacore::ROMSProcessorColumns::attach (const MSProcessor & msProcessor) protected
attachOptionalCols()
void casacore::ROMSProcessorColumns::attachOptionalCols (const MSProcessor & msField) private
flagRow()
const ROScalarColumn<Bool>& casacore::ROMSProcessorColumns::flagRow () const inline
Access to required columns.
Definition at line 83 of file MSProcessorColumns.h.
References flagRow_p.
Referenced by casacore::MSProcessorColumns::flagRow().
modeId()
const ROScalarColumn<Int>& casacore::ROMSProcessorColumns::modeId () const inline
Definition at line 84 of file MSProcessorColumns.h.
References modeId_p.
Referenced by casacore::MSProcessorColumns::modeId().
nrow()
uInt casacore::ROMSProcessorColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 96 of file MSProcessorColumns.h.
References flagRow_p.
operator=()
ROMSProcessorColumns& casacore::ROMSProcessorColumns::operator= (const ROMSProcessorColumns &) private
passId()
const ROScalarColumn<Int>& casacore::ROMSProcessorColumns::passId () const inline
Read-only access to optional columns.
Definition at line 92 of file MSProcessorColumns.h.
References passId_p.
Referenced by casacore::MSProcessorColumns::passId().
subType()
const ROScalarColumn<String>& casacore::ROMSProcessorColumns::subType () const inline
Definition at line 87 of file MSProcessorColumns.h.
References subType_p.
Referenced by casacore::MSProcessorColumns::subType().
type()
const ROScalarColumn<String>& casacore::ROMSProcessorColumns::type () const inline
Definition at line 85 of file MSProcessorColumns.h.
References type_p.
Referenced by casacore::MSProcessorColumns::type().
typeId()
const ROScalarColumn<Int>& casacore::ROMSProcessorColumns::typeId () const inline
Definition at line 86 of file MSProcessorColumns.h.
References typeId_p.
Referenced by casacore::MSProcessorColumns::typeId().
Member Data Documentation
flagRow_p
ROScalarColumn<Bool> casacore::ROMSProcessorColumns::flagRow_p private
Definition at line 116 of file MSProcessorColumns.h.
Referenced by flagRow(), and nrow().
modeId_p
ROScalarColumn<Int> casacore::ROMSProcessorColumns::modeId_p private
Definition at line 117 of file MSProcessorColumns.h.
Referenced by modeId().
passId_p
ROScalarColumn<Int> casacore::ROMSProcessorColumns::passId_p private
Definition at line 122 of file MSProcessorColumns.h.
Referenced by passId().
subType_p
ROScalarColumn<String> casacore::ROMSProcessorColumns::subType_p private
Definition at line 120 of file MSProcessorColumns.h.
Referenced by subType().
type_p
ROScalarColumn<String> casacore::ROMSProcessorColumns::type_p private
Definition at line 118 of file MSProcessorColumns.h.
Referenced by type().
typeId_p
ROScalarColumn<Int> casacore::ROMSProcessorColumns::typeId_p private
Definition at line 119 of file MSProcessorColumns.h.
Referenced by typeId().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSProcessorColumns.h