casacore: casacore::ROMSObservationColumns Class Reference
casacore::ROMSObservationColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSObservation columns.
#include <MSObsColumns.h>
Public Member Functions
ROMSObservationColumns (const MSObservation &msObservation)
Create a columns object that accesses the data in the specified Table.
~ROMSObservationColumns ()
The destructor does nothing special.
const ROScalarColumn< Bool > & flagRow () const
Access to required columns.
const ROArrayColumn< String > & log () const
const ROScalarColumn< String > & observer () const
const ROScalarColumn< String > & project () const
const ROScalarColumn< Double > & releaseDate () const
const ROScalarQuantColumn< Double > & releaseDateQuant () const
const ROScalarMeasColumn< MEpoch > & releaseDateMeas () const
const ROArrayColumn< String > & schedule () const
const ROScalarColumn< String > & scheduleType () const
const ROScalarColumn< String > & telescopeName () const
const ROArrayColumn< Double > & timeRange () const
const ROArrayQuantColumn< Double > & timeRangeQuant () const
const ROArrayMeasColumn< MEpoch > & timeRangeMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSObservationColumns ()
void attach (const MSObservation &msObservation)
Private Member Functions
ROMSObservationColumns (const ROMSObservationColumns &)
ROMSObservationColumns & operator= (const ROMSObservationColumns &)
Private Attributes
ROScalarColumn< Bool > flagRow_p
ROArrayColumn< String > log_p
ROScalarColumn< String > observer_p
ROScalarColumn< String > project_p
ROScalarColumn< Double > releaseDate_p
ROArrayColumn< String > schedule_p
ROScalarColumn< String > scheduleType_p
ROScalarColumn< String > telescopeName_p
ROArrayColumn< Double > timeRange_p
ROScalarMeasColumn< MEpoch > releaseDateMeas_p
ROArrayMeasColumn< MEpoch > timeRangeMeas_p
ROScalarQuantColumn< Double > releaseDateQuant_p
ROArrayQuantColumn< Double > timeRangeQuant_p
Detailed Description
A class to provide easy read-only access to MSObservation columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSObservation
ArrayColumn
ScalarColumn
Etymology
ROMSObservationColumns stands for Read-Only MeasurementSet Observation Table columns.
Synopsis
This class provides read-only access to the columns in the MSObservation Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 80 of file MSObsColumns.h.
Constructor & Destructor Documentation
ROMSObservationColumns() [1/3]
casacore::ROMSObservationColumns::ROMSObservationColumns (const MSObservation & msObservation)
Create a columns object that accesses the data in the specified Table.
~ROMSObservationColumns()
casacore::ROMSObservationColumns::~ROMSObservationColumns ()
The destructor does nothing special.
ROMSObservationColumns() [2/3]
casacore::ROMSObservationColumns::ROMSObservationColumns () protected
ROMSObservationColumns() [3/3]
casacore::ROMSObservationColumns::ROMSObservationColumns (const ROMSObservationColumns &) private
Member Function Documentation
attach()
void casacore::ROMSObservationColumns::attach (const MSObservation & msObservation) protected
flagRow()
const ROScalarColumn<Bool>& casacore::ROMSObservationColumns::flagRow () const inline
Access to required columns.
Definition at line 91 of file MSObsColumns.h.
References flagRow_p.
Referenced by casacore::MSObservationColumns::flagRow().
log()
const ROArrayColumn<String>& casacore::ROMSObservationColumns::log () const inline
Definition at line 92 of file MSObsColumns.h.
References log_p.
Referenced by casacore::MSObservationColumns::log().
nrow()
uInt casacore::ROMSObservationColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 111 of file MSObsColumns.h.
References flagRow_p.
observer()
const ROScalarColumn<String>& casacore::ROMSObservationColumns::observer () const inline
Definition at line 93 of file MSObsColumns.h.
References observer_p.
Referenced by casacore::MSObservationColumns::observer().
operator=()
ROMSObservationColumns& casacore::ROMSObservationColumns::operator= (const ROMSObservationColumns &) private
project()
const ROScalarColumn<String>& casacore::ROMSObservationColumns::project () const inline
Definition at line 94 of file MSObsColumns.h.
References project_p.
Referenced by casacore::MSObservationColumns::project().
releaseDate()
const ROScalarColumn<Double>& casacore::ROMSObservationColumns::releaseDate () const inline
Definition at line 95 of file MSObsColumns.h.
References releaseDate_p.
Referenced by casacore::MSObservationColumns::releaseDate().
releaseDateMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSObservationColumns::releaseDateMeas () const inline
Definition at line 98 of file MSObsColumns.h.
References releaseDateMeas_p.
Referenced by casacore::MSObservationColumns::releaseDateMeas().
releaseDateQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSObservationColumns::releaseDateQuant () const inline
Definition at line 96 of file MSObsColumns.h.
References releaseDateQuant_p.
Referenced by casacore::MSObservationColumns::releaseDateQuant().
schedule()
const ROArrayColumn<String>& casacore::ROMSObservationColumns::schedule () const inline
Definition at line 100 of file MSObsColumns.h.
References schedule_p.
Referenced by casacore::MSObservationColumns::schedule().
scheduleType()
const ROScalarColumn<String>& casacore::ROMSObservationColumns::scheduleType () const inline
Definition at line 101 of file MSObsColumns.h.
References scheduleType_p.
Referenced by casacore::MSObservationColumns::scheduleType().
telescopeName()
const ROScalarColumn<String>& casacore::ROMSObservationColumns::telescopeName () const inline
Definition at line 102 of file MSObsColumns.h.
References telescopeName_p.
Referenced by casacore::MSObservationColumns::telescopeName().
timeRange()
const ROArrayColumn<Double>& casacore::ROMSObservationColumns::timeRange () const inline
Definition at line 103 of file MSObsColumns.h.
References timeRange_p.
Referenced by casacore::MSObservationColumns::timeRange().
timeRangeMeas()
const ROArrayMeasColumn<MEpoch>& casacore::ROMSObservationColumns::timeRangeMeas () const inline
Definition at line 106 of file MSObsColumns.h.
References timeRangeMeas_p.
Referenced by casacore::MSObservationColumns::timeRangeMeas().
timeRangeQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSObservationColumns::timeRangeQuant () const inline
Definition at line 104 of file MSObsColumns.h.
References timeRangeQuant_p.
Referenced by casacore::MSObservationColumns::timeRangeQuant().
Member Data Documentation
flagRow_p
ROScalarColumn<Bool> casacore::ROMSObservationColumns::flagRow_p private
Definition at line 128 of file MSObsColumns.h.
Referenced by flagRow(), and nrow().
log_p
ROArrayColumn<String> casacore::ROMSObservationColumns::log_p private
Definition at line 129 of file MSObsColumns.h.
Referenced by log().
observer_p
ROScalarColumn<String> casacore::ROMSObservationColumns::observer_p private
Definition at line 130 of file MSObsColumns.h.
Referenced by observer().
project_p
ROScalarColumn<String> casacore::ROMSObservationColumns::project_p private
Definition at line 131 of file MSObsColumns.h.
Referenced by project().
releaseDate_p
ROScalarColumn<Double> casacore::ROMSObservationColumns::releaseDate_p private
Definition at line 132 of file MSObsColumns.h.
Referenced by releaseDate().
releaseDateMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSObservationColumns::releaseDateMeas_p private
Definition at line 139 of file MSObsColumns.h.
Referenced by releaseDateMeas().
releaseDateQuant_p
ROScalarQuantColumn<Double> casacore::ROMSObservationColumns::releaseDateQuant_p private
Definition at line 143 of file MSObsColumns.h.
Referenced by releaseDateQuant().
schedule_p
ROArrayColumn<String> casacore::ROMSObservationColumns::schedule_p private
Definition at line 133 of file MSObsColumns.h.
Referenced by schedule().
scheduleType_p
ROScalarColumn<String> casacore::ROMSObservationColumns::scheduleType_p private
Definition at line 134 of file MSObsColumns.h.
Referenced by scheduleType().
telescopeName_p
ROScalarColumn<String> casacore::ROMSObservationColumns::telescopeName_p private
Definition at line 135 of file MSObsColumns.h.
Referenced by telescopeName().
timeRange_p
ROArrayColumn<Double> casacore::ROMSObservationColumns::timeRange_p private
Definition at line 136 of file MSObsColumns.h.
Referenced by timeRange().
timeRangeMeas_p
ROArrayMeasColumn<MEpoch> casacore::ROMSObservationColumns::timeRangeMeas_p private
Definition at line 140 of file MSObsColumns.h.
Referenced by timeRangeMeas().
timeRangeQuant_p
ROArrayQuantColumn<Double> casacore::ROMSObservationColumns::timeRangeQuant_p private
Definition at line 144 of file MSObsColumns.h.
Referenced by timeRangeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSObsColumns.h