casacore: casacore::HDF5HidAttribute Class Reference
casacore::HDF5HidAttribute Class Reference
casa package (libcasa_casa) » HDF5_module » HDF5_module_internal_classes
A class representing an HDF5 attribute hid.
#include <HDF5HidMeta.h>
Public Member Functions
HDF5HidAttribute ()
Default constructor sets hid to invalid.
HDF5HidAttribute (hid_t hid)
Construct from given hid.
~HDF5HidAttribute ()
The destructor closes the hid.
void close ()
Close the hid if valid.
void operator= (hid_t hid)
Put hid in it.
hid_t getHid () const
Get the hid.
operator hid_t () const
Convert automatically to hid_t.
Private Member Functions
HDF5HidAttribute (const HDF5HidAttribute &that)
Copy constructor cannot be used.
HDF5HidAttribute & operator= (const HDF5HidAttribute &that)
Assignment cannot be used.
Private Attributes
hid_t itsHid
Detailed Description
A class representing an HDF5 attribute hid.
Intended use:
Internal
Review Status
Test programs:
tHDF5Dataset
Synopsis
This class wraps an HDF5 attribute hid (hdf5 id). It offers two benefits:
The most important is resource management. In case of an exception, the hid will automatically be closed by the destructor.
A hid is a kind of pointer and should not be copied. These classes forbid making a copy, but make it possible to use them in a shared pointer context.
Definition at line 199 of file HDF5HidMeta.h.
Constructor & Destructor Documentation
HDF5HidAttribute() [1/3]
casacore::HDF5HidAttribute::HDF5HidAttribute () inline
Default constructor sets hid to invalid.
Definition at line 203 of file HDF5HidMeta.h.
HDF5HidAttribute() [2/3]
casacore::HDF5HidAttribute::HDF5HidAttribute (hid_t hid) inline
Construct from given hid.
Definition at line 206 of file HDF5HidMeta.h.
~HDF5HidAttribute()
casacore::HDF5HidAttribute::~HDF5HidAttribute () inline
The destructor closes the hid.
Definition at line 209 of file HDF5HidMeta.h.
References close().
HDF5HidAttribute() [3/3]
casacore::HDF5HidAttribute::HDF5HidAttribute (const HDF5HidAttribute & that) private
Copy constructor cannot be used.
Member Function Documentation
close()
void casacore::HDF5HidAttribute::close ()
Close the hid if valid.
Referenced by operator=(), and ~HDF5HidAttribute().
getHid()
hid_t casacore::HDF5HidAttribute::getHid () const inline
Get the hid.
Definition at line 217 of file HDF5HidMeta.h.
References itsHid.
operator hid_t()
casacore::HDF5HidAttribute::operator hid_t () const inline
Convert automatically to hid_t.
Definition at line 220 of file HDF5HidMeta.h.
References itsHid.
operator=() [1/2]
void casacore::HDF5HidAttribute::operator= (hid_t hid) inline
Put hid in it.
If it already contains a hid, it will be closed.
Definition at line 214 of file HDF5HidMeta.h.
References close(), and itsHid.
operator=() [2/2]
HDF5HidAttribute& casacore::HDF5HidAttribute::operator= (const HDF5HidAttribute & that) private
Assignment cannot be used.
Member Data Documentation
itsHid
hid_t casacore::HDF5HidAttribute::itsHid private
Definition at line 228 of file HDF5HidMeta.h.
Referenced by getHid(), operator hid_t(), and operator=().
The documentation for this class was generated from the following file:
casa/HDF5/HDF5HidMeta.h