casacore: casacore::ROMSFreqOffsetColumns Class Reference
casacore::ROMSFreqOffsetColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSFreqOffset columns.
#include <MSFreqOffColumns.h>
Public Member Functions
ROMSFreqOffsetColumns (const MSFreqOffset &msFreqOffset)
Create a columns object that accesses the data in the specified Table.
~ROMSFreqOffsetColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSFreqOffset table is optional)
const ROScalarColumn< Int > & antenna1 () const
Access to columns.
const ROScalarColumn< Int > & antenna2 () const
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & offset () const
const ROScalarQuantColumn< Double > & offsetQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSFreqOffsetColumns ()
void attach (const MSFreqOffset &msFreqOffset)
Private Member Functions
ROMSFreqOffsetColumns (const ROMSFreqOffsetColumns &)
ROMSFreqOffsetColumns & operator= (const ROMSFreqOffsetColumns &)
Private Attributes
Bool isNull_p
ROScalarColumn< Int > antenna1_p
ROScalarColumn< Int > antenna2_p
ROScalarColumn< Int > feedId_p
ROScalarColumn< Double > interval_p
ROScalarColumn< Double > offset_p
ROScalarColumn< Int > spectralWindowId_p
ROScalarColumn< Double > time_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarQuantColumn< Double > intervalQuant_p
ROScalarQuantColumn< Double > offsetQuant_p
ROScalarQuantColumn< Double > timeQuant_p
Detailed Description
A class to provide easy read-only access to MSFreqOffset columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSFreqOffset
ArrayColumn
ScalarColumn
Etymology
ROMSFreqOffsetColumns stands for Read-Only MeasurementSet FreqOffset Table columns.
Synopsis
This class provides read-only access to the columns in the MSFreqOffset Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 77 of file MSFreqOffColumns.h.
Constructor & Destructor Documentation
ROMSFreqOffsetColumns() [1/3]
casacore::ROMSFreqOffsetColumns::ROMSFreqOffsetColumns (const MSFreqOffset & msFreqOffset)
Create a columns object that accesses the data in the specified Table.
~ROMSFreqOffsetColumns()
casacore::ROMSFreqOffsetColumns::~ROMSFreqOffsetColumns ()
The destructor does nothing special.
ROMSFreqOffsetColumns() [2/3]
casacore::ROMSFreqOffsetColumns::ROMSFreqOffsetColumns () protected
ROMSFreqOffsetColumns() [3/3]
casacore::ROMSFreqOffsetColumns::ROMSFreqOffsetColumns (const ROMSFreqOffsetColumns &) private
Member Function Documentation
antenna1()
const ROScalarColumn<Int>& casacore::ROMSFreqOffsetColumns::antenna1 () const inline
Access to columns.
Definition at line 91 of file MSFreqOffColumns.h.
References antenna1_p.
Referenced by casacore::MSFreqOffsetColumns::antenna1().
antenna2()
const ROScalarColumn<Int>& casacore::ROMSFreqOffsetColumns::antenna2 () const inline
Definition at line 92 of file MSFreqOffColumns.h.
References antenna2_p.
Referenced by casacore::MSFreqOffsetColumns::antenna2().
attach()
void casacore::ROMSFreqOffsetColumns::attach (const MSFreqOffset & msFreqOffset) protected
feedId()
const ROScalarColumn<Int>& casacore::ROMSFreqOffsetColumns::feedId () const inline
Definition at line 93 of file MSFreqOffColumns.h.
References feedId_p.
Referenced by casacore::MSFreqOffsetColumns::feedId().
interval()
const ROScalarColumn<Double>& casacore::ROMSFreqOffsetColumns::interval () const inline
Definition at line 94 of file MSFreqOffColumns.h.
References interval_p.
Referenced by casacore::MSFreqOffsetColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFreqOffsetColumns::intervalQuant () const inline
Definition at line 95 of file MSFreqOffColumns.h.
References intervalQuant_p.
Referenced by casacore::MSFreqOffsetColumns::intervalQuant().
isNull()
Bool casacore::ROMSFreqOffsetColumns::isNull () const inline
Is this object defined? (MSFreqOffset table is optional)
Definition at line 87 of file MSFreqOffColumns.h.
References isNull_p.
Referenced by nrow().
nrow()
uInt casacore::ROMSFreqOffsetColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Returns zero if the object is null.
Definition at line 109 of file MSFreqOffColumns.h.
References antenna1_p, and isNull().
offset()
const ROScalarColumn<Double>& casacore::ROMSFreqOffsetColumns::offset () const inline
Definition at line 97 of file MSFreqOffColumns.h.
References offset_p.
Referenced by casacore::MSFreqOffsetColumns::offset().
offsetQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFreqOffsetColumns::offsetQuant () const inline
Definition at line 98 of file MSFreqOffColumns.h.
References offsetQuant_p.
Referenced by casacore::MSFreqOffsetColumns::offsetQuant().
operator=()
ROMSFreqOffsetColumns& casacore::ROMSFreqOffsetColumns::operator= (const ROMSFreqOffsetColumns &) private
spectralWindowId()
const ROScalarColumn<Int>& casacore::ROMSFreqOffsetColumns::spectralWindowId () const inline
Definition at line 100 of file MSFreqOffColumns.h.
References spectralWindowId_p.
Referenced by casacore::MSFreqOffsetColumns::spectralWindowId().
time()
const ROScalarColumn<Double>& casacore::ROMSFreqOffsetColumns::time () const inline
Definition at line 102 of file MSFreqOffColumns.h.
References time_p.
Referenced by casacore::MSFreqOffsetColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSFreqOffsetColumns::timeMeas () const inline
Definition at line 104 of file MSFreqOffColumns.h.
References timeMeas_p.
Referenced by casacore::MSFreqOffsetColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFreqOffsetColumns::timeQuant () const inline
Definition at line 103 of file MSFreqOffColumns.h.
References timeQuant_p.
Referenced by casacore::MSFreqOffsetColumns::timeQuant().
Member Data Documentation
antenna1_p
ROScalarColumn<Int> casacore::ROMSFreqOffsetColumns::antenna1_p private
Definition at line 129 of file MSFreqOffColumns.h.
Referenced by antenna1(), and nrow().
antenna2_p
ROScalarColumn<Int> casacore::ROMSFreqOffsetColumns::antenna2_p private
Definition at line 130 of file MSFreqOffColumns.h.
Referenced by antenna2().
feedId_p
ROScalarColumn<Int> casacore::ROMSFreqOffsetColumns::feedId_p private
Definition at line 131 of file MSFreqOffColumns.h.
Referenced by feedId().
interval_p
ROScalarColumn<Double> casacore::ROMSFreqOffsetColumns::interval_p private
Definition at line 132 of file MSFreqOffColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFreqOffsetColumns::intervalQuant_p private
Definition at line 141 of file MSFreqOffColumns.h.
Referenced by intervalQuant().
isNull_p
Bool casacore::ROMSFreqOffsetColumns::isNull_p private
Definition at line 126 of file MSFreqOffColumns.h.
Referenced by isNull().
offset_p
ROScalarColumn<Double> casacore::ROMSFreqOffsetColumns::offset_p private
Definition at line 133 of file MSFreqOffColumns.h.
Referenced by offset().
offsetQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFreqOffsetColumns::offsetQuant_p private
Definition at line 142 of file MSFreqOffColumns.h.
Referenced by offsetQuant().
spectralWindowId_p
ROScalarColumn<Int> casacore::ROMSFreqOffsetColumns::spectralWindowId_p private
Definition at line 134 of file MSFreqOffColumns.h.
Referenced by spectralWindowId().
time_p
ROScalarColumn<Double> casacore::ROMSFreqOffsetColumns::time_p private
Definition at line 135 of file MSFreqOffColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSFreqOffsetColumns::timeMeas_p private
Definition at line 138 of file MSFreqOffColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFreqOffsetColumns::timeQuant_p private
Definition at line 143 of file MSFreqOffColumns.h.
Referenced by timeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSFreqOffColumns.h