casacore: casacore::FitsField< FitsBit > Class Template Reference
casacore::FitsField< FitsBit > Class Template Reference
fits package (libcasa_fits) » FITS_module
helper class
#include <hdu.h>
Public Member Functions
FitsField (int n=1)
~FitsField ()
FitsField< FitsBit > & operator() ()
FitsField< FitsBit > & operator() (unsigned i)
FitsField< FitsBit > & operator= (unsigned i)
int fitsfieldsize () const
int localfieldsize () const
operator int ()
void * data ()
void show (std::ostream &)
Public Member Functions inherited from casacore::FitsBase
FitsBase (const FITS::ValueType &t, int n)
virtual ~FitsBase ()
unsigned int nelements () const
virtual int dims () const
virtual int dim (int n) const
virtual int * vdim ()
FITS::ValueType fieldtype () const
FitsBase & operator= (FitsBase &)
Protected Member Functions
void setaddr (void **addr)
Protected Attributes
FitsBit ** field
unsigned char mask
int byte_offset
Protected Attributes inherited from casacore::FitsBase
int no_elements
FITS::ValueType data_type
Additional Inherited Members
Static Public Member Functions inherited from casacore::FitsBase
static FitsBase * make (const FITS::ValueType &, int=1)
static FitsBase * make (const FITS::ValueType &, int, int *)
static FitsBase * make (FitsBase &)
Detailed Description
template<>
class casacore::FitsField< FitsBit >
helper class
Template Type Argument Requirements
typedef FitsField<FitsLogical> LogicalFitsField;
typedef FitsField<FitsBit> BitFitsField;
typedef FitsField<char> CharFitsField;
typedef FitsField<unsigned char> ByteFitsField;
typedef FitsField<short> ShortFitsField;
typedef FitsField<FitsLong> LongFitsField;
typedef FitsField<float> FloatFitsField;
typedef FitsField<double> DoubleFitsField;
typedef FitsField<Complex> ComplexFitsField;
typedef FitsField<IComplex> IComplexFitsField;
typedef FitsField<DComplex> DComplexFitsField;
typedef FitsField<FitsVADesc> VADescFitsField;
Caution:
Bit fields require special treatment
Definition at line 925 of file hdu.h.
Constructor & Destructor Documentation
FitsField()
casacore::FitsField< FitsBit >::FitsField (int n = 1)
~FitsField()
casacore::FitsField< FitsBit >::~FitsField ()
Member Function Documentation
data()
void* casacore::FitsField< FitsBit >::data () virtual
Implements casacore::FitsBase.
fitsfieldsize()
int casacore::FitsField< FitsBit >::fitsfieldsize () const virtual
Implements casacore::FitsBase.
localfieldsize()
int casacore::FitsField< FitsBit >::localfieldsize () const virtual
Implements casacore::FitsBase.
operator int()
casacore::FitsField< FitsBit >::operator int () inline
Definition at line 944 of file hdu.h.
References casacore::FitsField< TYPE >::field, and casacore::mask().
operator()() [1/2]
FitsField<FitsBit>& casacore::FitsField< FitsBit >::operator() () inline
Definition at line 930 of file hdu.h.
References casacore::mask().
operator()() [2/2]
FitsField<FitsBit>& casacore::FitsField< FitsBit >::operator() (unsigned i) inline
Definition at line 933 of file hdu.h.
References casacore::mask().
operator=()
FitsField<FitsBit>& casacore::FitsField< FitsBit >::operator= (unsigned i) inline
Definition at line 936 of file hdu.h.
References casacore::FitsField< TYPE >::field, and casacore::mask().
setaddr()
void casacore::FitsField< FitsBit >::setaddr (void ** addr) protected virtual
Implements casacore::FitsBase.
show()
void casacore::FitsField< FitsBit >::show (std::ostream &) virtual
Implements casacore::FitsBase.
Member Data Documentation
byte_offset
int casacore::FitsField< FitsBit >::byte_offset protected
Definition at line 953 of file hdu.h.
field
FitsBit** casacore::FitsField< FitsBit >::field protected
Definition at line 951 of file hdu.h.
mask
unsigned char casacore::FitsField< FitsBit >::mask protected
Definition at line 952 of file hdu.h.
The documentation for this class was generated from the following file:
fits/FITS/hdu.h