casacore: casacore::MSWeatherColumns Class Reference
casacore::MSWeatherColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSWeather columns.
#include <MSWeatherColumns.h>
Public Member Functions
MSWeatherColumns (MSWeather &msWeather)
Create a columns object that accesses the data in the specified Table.
~MSWeatherColumns ()
The destructor does nothing special.
ScalarColumn< Int > & antennaId ()
Read-write access to required columns.
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
ScalarColumn< Float > & dewPoint ()
Read-write access to optional columns.
ScalarQuantColumn< Float > & dewPointQuant ()
ScalarColumn< Bool > & dewPointFlag ()
ScalarColumn< Float > & H2O ()
ScalarQuantColumn< Float > & H2OQuant ()
ScalarColumn< Bool > & H2OFlag ()
ScalarColumn< Float > & ionosElectron ()
ScalarQuantColumn< Float > & ionosElectronQuant ()
ScalarColumn< Bool > & ionosElectronFlag ()
ScalarColumn< Float > & pressure ()
ScalarQuantColumn< Float > & pressureQuant ()
ScalarColumn< Bool > & pressureFlag ()
ScalarColumn< Float > & relHumidity ()
ScalarColumn< Bool > & relHumidityFlag ()
ScalarColumn< Float > & temperature ()
ScalarQuantColumn< Float > & temperatureQuant ()
ScalarColumn< Bool > & temperatureFlag ()
ScalarColumn< Float > & windDirection ()
ScalarQuantColumn< Float > & windDirectionQuant ()
ScalarColumn< Bool > & windDirectionFlag ()
ScalarColumn< Float > & windSpeed ()
ScalarQuantColumn< Float > & windSpeedQuant ()
ScalarColumn< Bool > & windSpeedFlag ()
const ROScalarColumn< Int > & antennaId () const
Read-only access to required columns.
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Float > & dewPoint () const
Read-only access to optional columns.
const ROScalarQuantColumn< Float > & dewPointQuant () const
const ROScalarColumn< Bool > & dewPointFlag () const
const ROScalarColumn< Float > & H2O () const
const ROScalarColumn< Bool > & H2OFlag () const
const ROScalarQuantColumn< Float > & H2OQuant () const
const ROScalarColumn< Float > & ionosElectron () const
const ROScalarQuantColumn< Float > & ionosElectronQuant () const
const ROScalarColumn< Bool > & ionosElectronFlag () const
const ROScalarColumn< Float > & pressure () const
const ROScalarQuantColumn< Float > & pressureQuant () const
const ROScalarColumn< Bool > & pressureFlag () const
const ROScalarColumn< Float > & relHumidity () const
const ROScalarColumn< Bool > & relHumidityFlag () const
const ROScalarColumn< Float > & temperature () const
const ROScalarQuantColumn< Float > & temperatureQuant () const
const ROScalarColumn< Bool > & temperatureFlag () const
const ROScalarColumn< Float > & windDirection () const
const ROScalarQuantColumn< Float > & windDirectionQuant () const
const ROScalarColumn< Bool > & windDirectionFlag () const
const ROScalarColumn< Float > & windSpeed () const
const ROScalarQuantColumn< Float > & windSpeedQuant () const
const ROScalarColumn< Bool > & windSpeedFlag () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME column.
Public Member Functions inherited from casacore::ROMSWeatherColumns
ROMSWeatherColumns (const MSWeather &msWeather)
Create a columns object that accesses the data in the specified Table.
~ROMSWeatherColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSWeather table is optional)
const ROScalarColumn< Int > & antennaId () const
Access to columns.
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Float > & dewPoint () const
Access to optional columns.
const ROScalarQuantColumn< Float > & dewPointQuant () const
const ROScalarColumn< Bool > & dewPointFlag () const
const ROScalarColumn< Float > & H2O () const
const ROScalarColumn< Bool > & H2OFlag () const
const ROScalarQuantColumn< Float > & H2OQuant () const
const ROScalarColumn< Float > & ionosElectron () const
const ROScalarQuantColumn< Float > & ionosElectronQuant () const
const ROScalarColumn< Bool > & ionosElectronFlag () const
const ROScalarColumn< Float > & pressure () const
const ROScalarQuantColumn< Float > & pressureQuant () const
const ROScalarColumn< Bool > & pressureFlag () const
const ROScalarColumn< Float > & relHumidity () const
const ROScalarColumn< Bool > & relHumidityFlag () const
const ROScalarColumn< Float > & temperature () const
const ROScalarQuantColumn< Float > & temperatureQuant () const
const ROScalarColumn< Bool > & temperatureFlag () const
const ROScalarColumn< Float > & windDirection () const
const ROScalarQuantColumn< Float > & windDirectionQuant () const
const ROScalarColumn< Bool > & windDirectionFlag () const
const ROScalarColumn< Float > & windSpeed () const
const ROScalarQuantColumn< Float > & windSpeedQuant () const
const ROScalarColumn< Bool > & windSpeedFlag () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSWeatherColumns ()
void attach (MSWeather &msWeather)
Protected Member Functions inherited from casacore::ROMSWeatherColumns
ROMSWeatherColumns ()
void attach (const MSWeather &msWeather)
Private Member Functions
MSWeatherColumns (const MSWeatherColumns &)
MSWeatherColumns & operator= (const MSWeatherColumns &)
void attachOptionalCols (MSWeather &msWeather)
Private Attributes
ScalarColumn< Int > antennaId_p
ScalarColumn< Double > interval_p
ScalarColumn< Double > time_p
ScalarColumn< Float > dewPoint_p
ScalarColumn< Bool > dewPointFlag_p
ScalarColumn< Float > H2O_p
ScalarColumn< Bool > H2OFlag_p
ScalarColumn< Float > ionosElectron_p
ScalarColumn< Bool > ionosElectronFlag_p
ScalarColumn< Float > pressure_p
ScalarColumn< Bool > pressureFlag_p
ScalarColumn< Float > relHumidity_p
ScalarColumn< Bool > relHumidityFlag_p
ScalarColumn< Float > temperature_p
ScalarColumn< Bool > temperatureFlag_p
ScalarColumn< Float > windDirection_p
ScalarColumn< Bool > windDirectionFlag_p
ScalarColumn< Float > windSpeed_p
ScalarColumn< Bool > windSpeedFlag_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarQuantColumn< Double > intervalQuant_p
ScalarQuantColumn< Double > timeQuant_p
ScalarQuantColumn< Float > dewPointQuant_p
ScalarQuantColumn< Float > H2OQuant_p
ScalarQuantColumn< Float > ionosElectronQuant_p
ScalarQuantColumn< Float > pressureQuant_p
ScalarQuantColumn< Float > temperatureQuant_p
ScalarQuantColumn< Float > windDirectionQuant_p
ScalarQuantColumn< Float > windSpeedQuant_p
Detailed Description
A class to provide easy read-write access to MSWeather columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSWeather
ArrayColumn
ScalarColumn
Etymology
MSWeatherColumns stands for MeasurementSet Weather Table columns.
Synopsis
This class provides access to the columns in the MSWeather Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 231 of file MSWeatherColumns.h.
Constructor & Destructor Documentation
MSWeatherColumns() [1/3]
casacore::MSWeatherColumns::MSWeatherColumns (MSWeather & msWeather)
Create a columns object that accesses the data in the specified Table.
~MSWeatherColumns()
casacore::MSWeatherColumns::~MSWeatherColumns ()
The destructor does nothing special.
MSWeatherColumns() [2/3]
casacore::MSWeatherColumns::MSWeatherColumns () protected
MSWeatherColumns() [3/3]
casacore::MSWeatherColumns::MSWeatherColumns (const MSWeatherColumns &) private
Member Function Documentation
antennaId() [1/2]
ScalarColumn<Int>& casacore::MSWeatherColumns::antennaId () inline
Read-write access to required columns.
Definition at line 242 of file MSWeatherColumns.h.
References antennaId_p.
antennaId() [2/2]
const ROScalarColumn<Int>& casacore::MSWeatherColumns::antennaId () const inline
Read-only access to required columns.
Definition at line 279 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::antennaId().
attach()
void casacore::MSWeatherColumns::attach (MSWeather & msWeather) protected
attachOptionalCols()
void casacore::MSWeatherColumns::attachOptionalCols (MSWeather & msWeather) private
dewPoint() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::dewPoint () inline
Read-write access to optional columns.
Definition at line 252 of file MSWeatherColumns.h.
References dewPoint_p.
dewPoint() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::dewPoint () const inline
Read-only access to optional columns.
Definition at line 295 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::dewPoint().
dewPointFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::dewPointFlag () inline
Definition at line 254 of file MSWeatherColumns.h.
References dewPointFlag_p.
dewPointFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::dewPointFlag () const inline
Definition at line 299 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::dewPointFlag().
dewPointQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSWeatherColumns::dewPointQuant () inline
Definition at line 253 of file MSWeatherColumns.h.
References dewPointQuant_p.
dewPointQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSWeatherColumns::dewPointQuant () const inline
Definition at line 297 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::dewPointQuant().
H2O() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::H2O () inline
Definition at line 255 of file MSWeatherColumns.h.
References H2O_p.
H2O() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::H2O () const inline
Definition at line 301 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::H2O().
H2OFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::H2OFlag () inline
Definition at line 257 of file MSWeatherColumns.h.
References H2OFlag_p.
H2OFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::H2OFlag () const inline
Definition at line 303 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::H2OFlag().
H2OQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSWeatherColumns::H2OQuant () inline
Definition at line 256 of file MSWeatherColumns.h.
References H2OQuant_p.
H2OQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSWeatherColumns::H2OQuant () const inline
Definition at line 305 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::H2OQuant().
interval() [1/2]
ScalarColumn<Double>& casacore::MSWeatherColumns::interval () inline
Definition at line 243 of file MSWeatherColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSWeatherColumns::interval () const inline
Definition at line 281 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSWeatherColumns::intervalQuant () inline
Definition at line 244 of file MSWeatherColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSWeatherColumns::intervalQuant () const inline
Definition at line 283 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::intervalQuant().
ionosElectron() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::ionosElectron () inline
Definition at line 258 of file MSWeatherColumns.h.
References ionosElectron_p.
ionosElectron() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::ionosElectron () const inline
Definition at line 307 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::ionosElectron().
ionosElectronFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::ionosElectronFlag () inline
Definition at line 260 of file MSWeatherColumns.h.
References ionosElectronFlag_p.
ionosElectronFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::ionosElectronFlag () const inline
Definition at line 311 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::ionosElectronFlag().
ionosElectronQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSWeatherColumns::ionosElectronQuant () inline
Definition at line 259 of file MSWeatherColumns.h.
References ionosElectronQuant_p.
ionosElectronQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSWeatherColumns::ionosElectronQuant () const inline
Definition at line 309 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::ionosElectronQuant().
operator=()
MSWeatherColumns& casacore::MSWeatherColumns::operator= (const MSWeatherColumns &) private
pressure() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::pressure () inline
Definition at line 261 of file MSWeatherColumns.h.
References pressure_p.
pressure() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::pressure () const inline
Definition at line 313 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::pressure().
pressureFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::pressureFlag () inline
Definition at line 263 of file MSWeatherColumns.h.
References pressureFlag_p.
pressureFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::pressureFlag () const inline
Definition at line 317 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::pressureFlag().
pressureQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSWeatherColumns::pressureQuant () inline
Definition at line 262 of file MSWeatherColumns.h.
References pressureQuant_p.
pressureQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSWeatherColumns::pressureQuant () const inline
Definition at line 315 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::pressureQuant().
relHumidity() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::relHumidity () inline
Definition at line 264 of file MSWeatherColumns.h.
References relHumidity_p.
relHumidity() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::relHumidity () const inline
Definition at line 319 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::relHumidity().
relHumidityFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::relHumidityFlag () inline
Definition at line 265 of file MSWeatherColumns.h.
References relHumidityFlag_p.
relHumidityFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::relHumidityFlag () const inline
Definition at line 321 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::relHumidityFlag().
setEpochRef()
void casacore::MSWeatherColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
temperature() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::temperature () inline
Definition at line 266 of file MSWeatherColumns.h.
References temperature_p.
temperature() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::temperature () const inline
Definition at line 323 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::temperature().
temperatureFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::temperatureFlag () inline
Definition at line 268 of file MSWeatherColumns.h.
References temperatureFlag_p.
temperatureFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::temperatureFlag () const inline
Definition at line 327 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::temperatureFlag().
temperatureQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSWeatherColumns::temperatureQuant () inline
Definition at line 267 of file MSWeatherColumns.h.
References temperatureQuant_p.
temperatureQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSWeatherColumns::temperatureQuant () const inline
Definition at line 325 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::temperatureQuant().
time() [1/2]
ScalarColumn<Double>& casacore::MSWeatherColumns::time () inline
Definition at line 245 of file MSWeatherColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSWeatherColumns::time () const inline
Definition at line 285 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSWeatherColumns::timeMeas () inline
Definition at line 247 of file MSWeatherColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSWeatherColumns::timeMeas () const inline
Definition at line 289 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSWeatherColumns::timeQuant () inline
Definition at line 246 of file MSWeatherColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSWeatherColumns::timeQuant () const inline
Definition at line 287 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::timeQuant().
windDirection() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::windDirection () inline
Definition at line 269 of file MSWeatherColumns.h.
References windDirection_p.
windDirection() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::windDirection () const inline
Definition at line 329 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::windDirection().
windDirectionFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::windDirectionFlag () inline
Definition at line 271 of file MSWeatherColumns.h.
References windDirectionFlag_p.
windDirectionFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::windDirectionFlag () const inline
Definition at line 333 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::windDirectionFlag().
windDirectionQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSWeatherColumns::windDirectionQuant () inline
Definition at line 270 of file MSWeatherColumns.h.
References windDirectionQuant_p.
windDirectionQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSWeatherColumns::windDirectionQuant () const inline
Definition at line 331 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::windDirectionQuant().
windSpeed() [1/2]
ScalarColumn<Float>& casacore::MSWeatherColumns::windSpeed () inline
Definition at line 272 of file MSWeatherColumns.h.
References windSpeed_p.
windSpeed() [2/2]
const ROScalarColumn<Float>& casacore::MSWeatherColumns::windSpeed () const inline
Definition at line 335 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::windSpeed().
windSpeedFlag() [1/2]
ScalarColumn<Bool>& casacore::MSWeatherColumns::windSpeedFlag () inline
Definition at line 274 of file MSWeatherColumns.h.
References windSpeedFlag_p.
windSpeedFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSWeatherColumns::windSpeedFlag () const inline
Definition at line 339 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::windSpeedFlag().
windSpeedQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSWeatherColumns::windSpeedQuant () inline
Definition at line 273 of file MSWeatherColumns.h.
References windSpeedQuant_p.
windSpeedQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSWeatherColumns::windSpeedQuant () const inline
Definition at line 337 of file MSWeatherColumns.h.
References casacore::ROMSWeatherColumns::windSpeedQuant().
Member Data Documentation
antennaId_p
ScalarColumn<Int> casacore::MSWeatherColumns::antennaId_p private
Definition at line 372 of file MSWeatherColumns.h.
Referenced by antennaId().
dewPoint_p
ScalarColumn<Float> casacore::MSWeatherColumns::dewPoint_p private
Definition at line 376 of file MSWeatherColumns.h.
Referenced by dewPoint().
dewPointFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::dewPointFlag_p private
Definition at line 377 of file MSWeatherColumns.h.
Referenced by dewPointFlag().
dewPointQuant_p
ScalarQuantColumn<Float> casacore::MSWeatherColumns::dewPointQuant_p private
Definition at line 400 of file MSWeatherColumns.h.
Referenced by dewPointQuant().
H2O_p
ScalarColumn<Float> casacore::MSWeatherColumns::H2O_p private
Definition at line 378 of file MSWeatherColumns.h.
Referenced by H2O().
H2OFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::H2OFlag_p private
Definition at line 379 of file MSWeatherColumns.h.
Referenced by H2OFlag().
H2OQuant_p
ScalarQuantColumn<Float> casacore::MSWeatherColumns::H2OQuant_p private
Definition at line 401 of file MSWeatherColumns.h.
Referenced by H2OQuant().
interval_p
ScalarColumn<Double> casacore::MSWeatherColumns::interval_p private
Definition at line 373 of file MSWeatherColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSWeatherColumns::intervalQuant_p private
Definition at line 397 of file MSWeatherColumns.h.
Referenced by intervalQuant().
ionosElectron_p
ScalarColumn<Float> casacore::MSWeatherColumns::ionosElectron_p private
Definition at line 380 of file MSWeatherColumns.h.
Referenced by ionosElectron().
ionosElectronFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::ionosElectronFlag_p private
Definition at line 381 of file MSWeatherColumns.h.
Referenced by ionosElectronFlag().
ionosElectronQuant_p
ScalarQuantColumn<Float> casacore::MSWeatherColumns::ionosElectronQuant_p private
Definition at line 402 of file MSWeatherColumns.h.
Referenced by ionosElectronQuant().
pressure_p
ScalarColumn<Float> casacore::MSWeatherColumns::pressure_p private
Definition at line 382 of file MSWeatherColumns.h.
Referenced by pressure().
pressureFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::pressureFlag_p private
Definition at line 383 of file MSWeatherColumns.h.
Referenced by pressureFlag().
pressureQuant_p
ScalarQuantColumn<Float> casacore::MSWeatherColumns::pressureQuant_p private
Definition at line 403 of file MSWeatherColumns.h.
Referenced by pressureQuant().
relHumidity_p
ScalarColumn<Float> casacore::MSWeatherColumns::relHumidity_p private
Definition at line 384 of file MSWeatherColumns.h.
Referenced by relHumidity().
relHumidityFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::relHumidityFlag_p private
Definition at line 385 of file MSWeatherColumns.h.
Referenced by relHumidityFlag().
temperature_p
ScalarColumn<Float> casacore::MSWeatherColumns::temperature_p private
Definition at line 386 of file MSWeatherColumns.h.
Referenced by temperature().
temperatureFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::temperatureFlag_p private
Definition at line 387 of file MSWeatherColumns.h.
Referenced by temperatureFlag().
temperatureQuant_p
ScalarQuantColumn<Float> casacore::MSWeatherColumns::temperatureQuant_p private
Definition at line 404 of file MSWeatherColumns.h.
Referenced by temperatureQuant().
time_p
ScalarColumn<Double> casacore::MSWeatherColumns::time_p private
Definition at line 374 of file MSWeatherColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSWeatherColumns::timeMeas_p private
Definition at line 394 of file MSWeatherColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSWeatherColumns::timeQuant_p private
Definition at line 398 of file MSWeatherColumns.h.
Referenced by timeQuant().
windDirection_p
ScalarColumn<Float> casacore::MSWeatherColumns::windDirection_p private
Definition at line 388 of file MSWeatherColumns.h.
Referenced by windDirection().
windDirectionFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::windDirectionFlag_p private
Definition at line 389 of file MSWeatherColumns.h.
Referenced by windDirectionFlag().
windDirectionQuant_p
ScalarQuantColumn<Float> casacore::MSWeatherColumns::windDirectionQuant_p private
Definition at line 405 of file MSWeatherColumns.h.
Referenced by windDirectionQuant().
windSpeed_p
ScalarColumn<Float> casacore::MSWeatherColumns::windSpeed_p private
Definition at line 390 of file MSWeatherColumns.h.
Referenced by windSpeed().
windSpeedFlag_p
ScalarColumn<Bool> casacore::MSWeatherColumns::windSpeedFlag_p private
Definition at line 391 of file MSWeatherColumns.h.
Referenced by windSpeedFlag().
windSpeedQuant_p
ScalarQuantColumn<Float> casacore::MSWeatherColumns::windSpeedQuant_p private
Definition at line 406 of file MSWeatherColumns.h.
Referenced by windSpeedQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSWeatherColumns.h