casacore: casacore::QC Class Reference
casacore::QC Class Reference
Quanta_module
Physical constants (i.e. dimensioned values)
#include <QC.h>
Static Public Member Functions
static const Quantum< Double > & c ()
vel of light
static const Quantum< Double > & G ()
Gravitational constant.
static const Quantum< Double > & h ()
Planck.
static const Quantum< Double > & HI ()
HI line.
static Quantum< Double > & R ()
Gas constant.
static const Quantum< Double > & NA ()
Avogadro.
static const Quantum< Double > & e ()
electron charge
static const Quantum< Double > & mp ()
proton mass
static const Quantum< Double > & mp_me ()
mp/me
static const Quantum< Double > & mu0 ()
permeability vacuum
static const Quantum< Double > & epsilon0 ()
permittivity vacuum
static const Quantum< Double > & k ()
Boltzmann.
static const Quantum< Double > & F ()
Faraday.
static const Quantum< Double > & me ()
mass electron
static const Quantum< Double > & re ()
radius electron
static const Quantum< Double > & a0 ()
Bohr's radius.
static const Quantum< Double > & R0 ()
Solar radius.
static const Quantum< Double > & k2 ()
IAU Gaussian grav.
static const Quantum< Double > & qTurn ()
quarter turn = 90 degrees = pi/2 radians
static const Quantum< Double > & hTurn ()
half turn = 180 degrees = pi radians
static const Quantum< Double > & fTurn ()
full turn = 360 degrees = 2pi radians
Friends
class QC_init
Detailed Description
Physical constants (i.e. dimensioned values)
Intended use:
Public interface
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Test programs:
tQuantum
Prerequisite
Quantum
Etymology
A QC is based on the Quantum and C (constants) class
Synopsis
QC:name will produce a Quantity (Quantum<Double>) value consisting of a value and a unit. See the Quantum class for possibilities of manipulating quanta. tQuantum will give a list of the currently available constants
Example
To obtain the velocity of light in pc/a, use:
#include <casacore/casa/Quanta.h>
Double vel_pcpy = (C::c).convert("pc/a").getValue();
The following constants are defined as public data members of class QC.
Caution: The following public data member documentation is currently extracted by hand, and thus could be out of date if this documentation was not updated when the class was modified;
// vel of light
Quantum<Double> c();
// Gravitational constant
Quantum<Double> G();
// Planck
Quantum<Double> h();
// HI line
Quantum<Double> HI();
// Gas constant
Quantum<Double> R();
// Avogadro
Quantum<Double> NA();
// electron charge
Quantum<Double> e();
// proton mass
Quantum<Double> mp();
// mp/me
Quantum<Double> mp_me();
// permeability vacuum
Quantum<Double> mu0();
// permittivity vacuum
Quantum<Double> epsilon0();
// Boltzmann
Quantum<Double> k();
// Faraday
Quantum<Double> F();
// mass electron
Quantum<Double> me();
// radius electron
Quantum<Double> re();
// Bohr's radius
Quantum<Double> a0();
// Solar radius
Quantum<Double> R0();
// IAU Gaussian grav. const **2
Quantum<Double> k2();
// quarter turn = 90 degrees = pi/2 radians
Quantum<Double> qTurn();
// half turn = 180 degrees = pi radians
Quantum<Double> hTurn();
// full turn = 360 degrees = 2pi radians
Quantum<Double> fTurn();
Motivation
Physical constants should be known with their proper dimensions
Definition at line 162 of file QC.h.
Member Function Documentation
static const Quantum<Double>& casacore::QC::a0 () inline static
Bohr's radius.
Definition at line 260 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::c () inline static
vel of light
Definition at line 170 of file QC.h.
References casacore::C::c.
static const Quantum<Double>& casacore::QC::e () inline static
electron charge
Definition at line 206 of file QC.h.
Referenced by a0(), epsilon0(), F(), G(), h(), k(), me(), mp(), mu0(), NA(), R0(), and re().
static const Quantum<Double>& casacore::QC::epsilon0 () inline static
permittivity vacuum
Definition at line 230 of file QC.h.
References casacore::C::c, e(), and casacore::C::pi.
static const Quantum<Double>& casacore::QC::F () inline static
Faraday.
Definition at line 242 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::fTurn () inline static
full turn = 360 degrees = 2pi radians
Definition at line 292 of file QC.h.
static const Quantum<Double>& casacore::QC::G () inline static
Gravitational constant.
Definition at line 176 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::h () inline static
Planck.
Definition at line 182 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::HI () inline static
HI line.
Definition at line 188 of file QC.h.
static const Quantum<Double>& casacore::QC::hTurn () inline static
half turn = 180 degrees = pi radians
Definition at line 286 of file QC.h.
static const Quantum<Double>& casacore::QC::k () inline static
Boltzmann.
Definition at line 236 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::k2 () inline static
IAU Gaussian grav.
const **2
Definition at line 273 of file QC.h.
References casacore::IAU_k.
static const Quantum<Double>& casacore::QC::me () inline static
mass electron
Definition at line 248 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::mp () inline static
proton mass
Definition at line 212 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::mp_me () inline static
mp/me
Definition at line 218 of file QC.h.
static const Quantum<Double>& casacore::QC::mu0 () inline static
permeability vacuum
Definition at line 224 of file QC.h.
References e(), and casacore::C::pi.
static const Quantum<Double>& casacore::QC::NA () inline static
Avogadro.
Definition at line 200 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::qTurn () inline static
quarter turn = 90 degrees = pi/2 radians
Definition at line 280 of file QC.h.
static Quantum<Double>& casacore::QC::R () inline static
Gas constant.
Definition at line 194 of file QC.h.
static const Quantum<Double>& casacore::QC::R0 () inline static
Solar radius.
Definition at line 266 of file QC.h.
References e().
static const Quantum<Double>& casacore::QC::re () inline static
radius electron
Definition at line 254 of file QC.h.
References e().
Friends And Related Function Documentation
friend class QC_init friend
Definition at line 163 of file QC.h.
The documentation for this class was generated from the following file:
casa/Quanta/QC.h