casacore: casacore::PtrBlock< T > Class Template Reference
casacore::PtrBlock< T > Class Template Reference
Containers_module
A drop-in replacement for Block<T*>.
#include <Block.h>
Public Member Functions
PtrBlock ()
PtrBlock (size_t n)
PtrBlock (size_t n, T val)
PtrBlock (size_t n, T *&storagePointer, Bool takeOverStorage=True)
PtrBlock (const PtrBlock< T > &other)
PtrBlock< T > & operator= (const PtrBlock< T > &other)
~PtrBlock ()
void resize (size_t n, Bool forceSmaller, Bool copyElements)
void resize (size_t n)
void resize (size_t n, Bool forceSmaller)
void remove (size_t whichOne, Bool forceSmaller)
void remove (size_t whichOne)
void replaceStorage (size_t n, T *&storagePointer, Bool takeOverStorage=True)
T & operator[] (size_t index)
const T & operator[] (size_t index) const
void set (const T &val)
PtrBlock< T > & operator= (const T &val)
T * storage ()
const T * storage () const
size_t nelements () const
size_t size () const
Bool empty () const
Private Attributes
Block< void * > block_p
Detailed Description
template<class T>
class casacore::PtrBlock< T >
A drop-in replacement for Block<T*>.
Intended use:
Public interface
Prerequisite
Block
Synopsis
PtrBlock<T*> has exactly the same interface as Block<T*> and should be used in preference to the latter. It's purpose is solely to reduce the number of template instantiations.
To Do
Partial template specialization is another implementation choice that will be possible eventually.
It might be useful to have functions that know the templte parameter is a pointer, e.g. that delete all the non-null pointers.
Definition at line 461 of file Block.h.
Constructor & Destructor Documentation
template<class T> casacore::PtrBlock< T >::PtrBlock () inline
Definition at line 463 of file Block.h.
template<class T> casacore::PtrBlock< T >::PtrBlock (size_t n) inline explicit
Definition at line 464 of file Block.h.
template<class T> casacore::PtrBlock< T >::PtrBlock (size_t n, T val) inline
Definition at line 465 of file Block.h.
template<class T> casacore::PtrBlock< T >::PtrBlock (size_t n, T *& storagePointer, Bool takeOverStorage = True) inline
Definition at line 466 of file Block.h.
template<class T> casacore::PtrBlock< T >::PtrBlock (const PtrBlock< T > & other) inline
Definition at line 468 of file Block.h.
template<class T> casacore::PtrBlock< T >::~PtrBlock () inline
Definition at line 471 of file Block.h.
Member Function Documentation
template<class T> Bool casacore::PtrBlock< T >::empty () const inline
Definition at line 490 of file Block.h.
template<class T> size_t casacore::PtrBlock< T >::nelements () const inline
Definition at line 488 of file Block.h.
Referenced by casacore::HashMap< key, val >::allocBuckets(), casacore::CombiParam< AutoDiff< T > >::CombiParam(), casacore::CompoundParam< AutoDiff< Double > >::CompoundParam(), casacore::GenericL2Fit< DComplex >::getConstraint(), casacore::SSMBase::getNrIndices(), casacore::GenericL2Fit< DComplex >::NConstraints(), casacore::TableExprNodeSet::nelements(), casacore::CompoundParam< AutoDiff< Double > >::nFunctions(), casacore::TiledStMan::nhypercubes(), casacore::LatticeConcat< T >::nlattices(), and casacore::GenericL2Fit< DComplex >::setConstraint().
template<class T> PtrBlock<T>& casacore::PtrBlock< T >::operator= (const PtrBlock< T > & other) inline
Definition at line 469 of file Block.h.
template<class T> PtrBlock<T>& casacore::PtrBlock< T >::operator= (const T & val) inline
Definition at line 485 of file Block.h.
template<class T> T& casacore::PtrBlock< T >::operator[] (size_t index) inline
Definition at line 482 of file Block.h.
template<class T> const T& casacore::PtrBlock< T >::operator[] (size_t index) const inline
Definition at line 483 of file Block.h.
template<class T> void casacore::PtrBlock< T >::remove (size_t whichOne, Bool forceSmaller) inline
Definition at line 476 of file Block.h.
template<class T> void casacore::PtrBlock< T >::remove (size_t whichOne) inline
Definition at line 478 of file Block.h.
template<class T> void casacore::PtrBlock< T >::replaceStorage (size_t n, T *& storagePointer, Bool takeOverStorage = True) inline
Definition at line 479 of file Block.h.
template<class T> void casacore::PtrBlock< T >::resize (size_t n, Bool forceSmaller, Bool copyElements) inline
Definition at line 472 of file Block.h.
template<class T> void casacore::PtrBlock< T >::resize (size_t n) inline
Definition at line 474 of file Block.h.
template<class T> void casacore::PtrBlock< T >::resize (size_t n, Bool forceSmaller) inline
Definition at line 475 of file Block.h.
template<class T> void casacore::PtrBlock< T >::set (const T & val) inline
Definition at line 484 of file Block.h.
template<class T> size_t casacore::PtrBlock< T >::size () const inline
Definition at line 489 of file Block.h.
template<class T> T* casacore::PtrBlock< T >::storage () inline
Definition at line 486 of file Block.h.
template<class T> const T* casacore::PtrBlock< T >::storage () const inline
Definition at line 487 of file Block.h.
Member Data Documentation
template<class T> Block<void*> casacore::PtrBlock< T >::block_p private
Definition at line 492 of file Block.h.
Referenced by casacore::PtrBlock< SSMIndex * >::empty(), casacore::PtrBlock< SSMIndex * >::nelements(), casacore::PtrBlock< SSMIndex * >::operator=(), casacore::PtrBlock< SSMIndex * >::operator[](), casacore::PtrBlock< SSMIndex * >::remove(), casacore::PtrBlock< SSMIndex * >::replaceStorage(), casacore::PtrBlock< SSMIndex * >::resize(), casacore::PtrBlock< SSMIndex * >::set(), casacore::PtrBlock< SSMIndex * >::size(), and casacore::PtrBlock< SSMIndex * >::storage().
The documentation for this class was generated from the following file:
casa/Containers/Block.h