casacore: casacore::LCRegion Class Reference
casacore::LCRegion Class Reference abstract
lattices package (libcasa_lattices) » LRegions_module
Abstract base class to define a region of interest in lattice coordinates.
#include <LCRegion.h>
Public Member Functions
LCRegion ()
LCRegion (const IPosition &latticeShape)
Construct with the lattice shape only.
LCRegion (const LCRegion &other)
Copy constructor (copy semantics).
virtual ~LCRegion ()
virtual Bool operator== (const LCRegion &other) const
Equality.
Bool operator!= (const LCRegion &other) const
Non-equality.
virtual Lattice< Bool > * clone () const
Make a copy of the derived object.
virtual LCRegion * cloneRegion () const =0
virtual void handleDelete ()
Handle deletion of the region by deleting possible tables.
virtual void handleRename (const String &newName, Bool overwrite)
Handle renaming the region by renaming possible tables.
virtual String type () const =0
Region type.
const String & comment () const
Get or set the comment.
void setComment (const String &comment)
virtual Bool hasMask () const =0
Does the region have a mask?
LCRegion * translate (const IPosition &translateVector) const
Construct another LCRegion (for e.g.
LCRegion * translate (const IPosition &translateVector, const IPosition &newLatticeShape) const
LCRegion * translate (const Vector< Float > &translateVector) const
LCRegion * translate (const Vector< Float > &translateVector, const IPosition &newLatticeShape) const
const IPosition & latticeShape () const
Give the full lattice shape.
const Slicer & boundingBox () const
Give the bounding box.
Slicer expand (const Slicer &slicer) const
Expand a slicer or position in the region to the full lattice.
IPosition expand (const IPosition &index) const
virtual TableRecord toRecord (const String &tableName) const =0
Convert the (derived) object to a record.
virtual uInt ndim () const
Return the dimensionality of the region.
virtual IPosition shape () const
Return the shape of the region (i.e.
virtual Bool isWritable () const
Usually the lattice (i.e.
virtual void doPutSlice (const Array< Bool > &sourceBuffer, const IPosition &where, const IPosition &stride)
Regions can usually not be put; i.e.
virtual void set (const Bool &value)
Set all elements in the Lattice to the given value.
virtual void apply (Bool(*function)(Bool))
Replace every element, x, of the Lattice with the result of f(x).
virtual void apply (Bool(*function)(const Bool &))
virtual void apply (const Functional< Bool, Bool > &function)
virtual void putAt (const Bool &value, const IPosition &where)
Put the value of a single element.
virtual void copyData (const Lattice< Bool > &from)
Copy the data from the given lattice to this one.
Public Member Functions inherited from casacore::Lattice< Bool >
virtual ~Lattice ()
a virtual destructor is needed so that it will use the actual destructor in the derived class
virtual DataType dataType () const
Get the data type of the lattice.
Bool operator() (const IPosition &where) const
Return the value of the single element located at the argument IPosition.
virtual Bool getAt (const IPosition &where) const
Bool get (COWPtr< Array< Bool > > &buffer, Bool removeDegenerateAxes=False) const
Functions which extract an Array of values from a Lattice.
Bool get (Array< Bool > &buffer, Bool removeDegenerateAxes=False)
Array< Bool > get (Bool removeDegenerateAxes=False) const
Bool getSlice (COWPtr< Array< Bool > > &buffer, const Slicer &section, Bool removeDegenerateAxes=False) const
Bool getSlice (COWPtr< Array< Bool > > &buffer, const IPosition &start, const IPosition &shape, Bool removeDegenerateAxes=False) const
Bool getSlice (COWPtr< Array< Bool > > &buffer, const IPosition &start, const IPosition &shape, const IPosition &stride, Bool removeDegenerateAxes=False) const
Bool getSlice (Array< Bool > &buffer, const Slicer &section, Bool removeDegenerateAxes=False)
Bool getSlice (Array< Bool > &buffer, const IPosition &start, const IPosition &shape, Bool removeDegenerateAxes=False)
Bool getSlice (Array< Bool > &buffer, const IPosition &start, const IPosition &shape, const IPosition &stride, Bool removeDegenerateAxes=False)
Array< Bool > getSlice (const Slicer &section, Bool removeDegenerateAxes=False) const
Array< Bool > getSlice (const IPosition &start, const IPosition &shape, Bool removeDegenerateAxes=False) const
Array< Bool > getSlice (const IPosition &start, const IPosition &shape, const IPosition &stride, Bool removeDegenerateAxes=False) const
void putSlice (const Array< Bool > &sourceBuffer, const IPosition &where, const IPosition &stride)
A function which places an Array of values within this instance of the Lattice at the location specified by the IPosition "where", incrementing by "stride".
void putSlice (const Array< Bool > &sourceBuffer, const IPosition &where)
void put (const Array< Bool > &sourceBuffer)
void operator+= (const Lattice< Bool > &other)
Add, subtract, multiple, or divide by another Lattice.
void operator-= (const Lattice< Bool > &other)
void operator *= (const Lattice< Bool > &other)
void operator/= (const Lattice< Bool > &other)
virtual void copyDataTo (Lattice< Bool > &to) const
Copy the data from this lattice to the given lattice.
virtual uInt advisedMaxPixels () const
This function returns the advised maximum number of pixels to include in the cursor of an iterator.
virtual LatticeIterInterface< Bool > * makeIter (const LatticeNavigator &navigator, Bool useRef) const
These functions are used by the LatticeIterator class to generate an iterator of the correct type for a specified Lattice.
virtual Bool doGetSlice (Array< Bool > &buffer, const Slicer &section)=0
The functions (in the derived classes) doing the actual work.
Public Member Functions inherited from casacore::LatticeBase
virtual ~LatticeBase ()
A virtual destructor is needed so that it will use the actual destructor in the derived class.
virtual String imageType () const
Get the image type (returns name of derived class).
virtual Bool isPersistent () const
Is the lattice persistent and can it be loaded by other processes as well? That is the case for a PagedArray or PagedImage and for an ImageExpr which does not use transient lattices or regions.
virtual Bool isPaged () const
Is the lattice paged to disk?
The default implementation returns False.
virtual Bool canReferenceArray () const
Can the lattice data be referenced as an array section? That is the case for an ArrayLattice or a Temp/SubLattice using it.
virtual void save (const String &fileName) const
Save the image in an AipsIO file with the given name.
virtual Bool lock (FileLocker::LockType, uInt nattempts)
It is strongly recommended to use class LatticeLocker to handle lattice locking.
virtual void unlock ()
virtual Bool hasLock (FileLocker::LockType) const
virtual void resync ()
Resynchronize the Lattice object with the lattice file.
virtual void flush ()
Flush the data (but do not unlock).
virtual void tempClose ()
Temporarily close the lattice.
virtual void reopen ()
Explicitly reopen the temporarily closed lattice.
virtual String name (Bool stripPath=False) const
Return the name of the current Lattice object.
virtual size_t nelements () const
Return the total number of elements in this Lattice.
size_t size () const
Bool conform (const LatticeBase &other) const
Return a value of "True" if this instance of Lattice and 'other' have the same shape, otherwise returns a value of "False".
virtual LELCoordinates lelCoordinates () const
Return the coordinates of the lattice.
IPosition niceCursorShape (uInt maxPixels) const
Returns a recommended cursor shape for iterating through all the pixels in the Lattice.
IPosition niceCursorShape () const
virtual Bool ok () const
Check class internals - used for debugging.
virtual IPosition doNiceCursorShape (uInt maxPixels) const
The function (in the derived classes) doing the actual work.
virtual uInt maximumCacheSize () const
Maximum cache size - not necessarily all used.
virtual void setMaximumCacheSize (uInt howManyPixels)
Set the maximum (allowed) cache size as indicated.
virtual void setCacheSizeInTiles (uInt howManyTiles)
Set the actual cache size for this Array to be big enough for the indicated number of tiles.
virtual void setCacheSizeFromPath (const IPosition &sliceShape, const IPosition &windowStart, const IPosition &windowLength, const IPosition &axisPath)
Set the cache size as to "fit" the indicated path.
virtual void clearCache ()
Clears and frees up the caches, but the maximum allowed cache size is unchanged from when setCacheSize was called.
virtual void showCacheStatistics (ostream &os) const
Report on cache success.
Static Public Member Functions
static LCRegion * fromRecord (const TableRecord &, const String &tableName)
Convert correct object from a record.
Protected Member Functions
LCRegion & operator= (const LCRegion &other)
Assignment (copy semantics) is only useful for derived classes.
void setBoundingBox (const Slicer &boundingBox)
Sometimes it is inconvenient for a derived class to set the bounding box in the constructor.
void setShapeAndBoundingBox (const IPosition &latticeShape, const Slicer &boundingBox)
virtual LCRegion * doTranslate (const Vector< Float > &translateVector, const IPosition &newLatticeShape) const =0
Do the actual translate in a derived class.
void defineRecordFields (RecordInterface &record, const String &className) const
Define the type and class name in the record.
Protected Member Functions inherited from casacore::Lattice< Bool >
Lattice ()
Define default constructor to satisfy compiler.
Lattice (const Lattice< Bool > &)
Copy constructor and assignment can only be used by derived classes.
virtual void handleMath (const Lattice< Bool > &from, int oper)
Handle the Math operators (+=, -=, *=, /=).
virtual void handleMathTo (Lattice< Bool > &to, int oper) const
void handleMathTo (Lattice< Bool > &, int) const
Lattice< Bool > & operator= (const Lattice< Bool > &)
Protected Member Functions inherited from casacore::LatticeBase
LatticeBase ()
Define default constructor to be used by derived classes.
LatticeBase (const LatticeBase &)
Copy constructor and assignment can only be used by derived classes.
LatticeBase & operator= (const LatticeBase &)
void throwBoolMath () const
Throw an exception for arithmetic on a Bool Lattice.
Private Attributes
IPosition itsShape
Slicer itsBoundingBox
String itsComment
Detailed Description
Abstract base class to define a region of interest in lattice coordinates.
Intended use:
Public interface
Prerequisite
Slicer
Synopsis
The LCRegion class is the abstract base class for various types of LCRegion's (e.g. LCEllipsoid, LCBox). It contains the minimal bounding box of the region and, if needed, a mask with the same shape as the bounding box. A mask element is true if the element is inside the box.
Each LCRegion object must be able to convert itself to and from a record. In that way they can be made persistent (in for example a Table).
The LCRegion can be used in several Lattices and Images classes and functions to limit the area to operate on.
Example
Motivation
The Slicer class is too limited as a region, because it can only describe a rectangular region. Specialized classes are needed to describe arbitrary regions. They need a base class to combine them.
Definition at line 87 of file LCRegion.h.
Constructor & Destructor Documentation
LCRegion() [1/3]
casacore::LCRegion::LCRegion ()
LCRegion() [2/3]
casacore::LCRegion::LCRegion (const IPosition & latticeShape)
Construct with the lattice shape only.
LCRegion() [3/3]
casacore::LCRegion::LCRegion (const LCRegion & other)
Copy constructor (copy semantics).
~LCRegion()
virtual casacore::LCRegion::~LCRegion () virtual
Member Function Documentation
apply() [1/3]
virtual void casacore::LCRegion::apply (Bool(*)(Bool) function) virtual
Replace every element, x, of the Lattice with the result of f(x).
You must pass in the address of the function – so the function must be declared and defined in the scope of your program. All versions of apply require a function that accepts a single argument of type T (the Lattice template type) and return a result of the same type. The first apply expects a function with an argument passed by value; the second expects the argument to be passed by const reference; the third requires an instance of the class Functional<T,T>. The first form ought to run faster for the built-in types, which may be an issue for large Lattices stored in memory, where disk access is not an issue.
Reimplemented from casacore::Lattice< Bool >.
Reimplemented in casacore::LCRegionSingle.
apply() [2/3]
virtual void casacore::LCRegion::apply (Bool(*)(const Bool &) function) virtual
Reimplemented from casacore::Lattice< Bool >.
Reimplemented in casacore::LCRegionSingle.
apply() [3/3]
virtual void casacore::LCRegion::apply (const Functional< Bool, Bool > & function) virtual
Reimplemented from casacore::Lattice< Bool >.
Reimplemented in casacore::LCRegionSingle.
boundingBox()
const Slicer & casacore::LCRegion::boundingBox () const inline
Give the bounding box.
Definition at line 227 of file LCRegion.h.
References itsBoundingBox.
clone()
virtual Lattice<Bool>* casacore::LCRegion::clone () const virtual
Make a copy of the derived object.
Implements casacore::Lattice< Bool >.
cloneRegion()
virtual LCRegion* casacore::LCRegion::cloneRegion () const pure virtual
Implemented in casacore::LCPolygon, casacore::LCEllipsoid, casacore::LCConcatenation, casacore::LCLELMask, casacore::LCMask, casacore::LCUnion, casacore::LCExtension, casacore::LCStretch, casacore::LCBox, casacore::LCIntersection, casacore::LCDifference, casacore::LCComplement, casacore::LCPagedMask, casacore::LCHDF5Mask, and casacore::LCPixelSet.
comment()
const String & casacore::LCRegion::comment () const inline
Get or set the comment.
Definition at line 244 of file LCRegion.h.
References itsComment.
Referenced by setComment().
copyData()
virtual void casacore::LCRegion::copyData (const Lattice< Bool > & from) virtual
Copy the data from the given lattice to this one.
The default implementation uses function copyDataTo.
Reimplemented from casacore::Lattice< Bool >.
Reimplemented in casacore::LCRegionSingle.
defineRecordFields()
void casacore::LCRegion::defineRecordFields (RecordInterface & record, const String & className) const protected
Define the type and class name in the record.
doPutSlice()
virtual void casacore::LCRegion::doPutSlice (const Array< Bool > & sourceBuffer, const IPosition & where, const IPosition & stride) virtual
Regions can usually not be put; i.e.
no putSlice, etc. can be done on their masks. Hence LCRegion throws by default an exception for the following functions.
Implements casacore::Lattice< Bool >.
Reimplemented in casacore::LCRegionSingle.
doTranslate()
virtual LCRegion* casacore::LCRegion::doTranslate (const Vector< Float > & translateVector, const IPosition & newLatticeShape) const protected pure virtual
Do the actual translate in a derived class.
Implemented in casacore::LCMask, casacore::LCPagedMask, casacore::LCPolygon, casacore::LCEllipsoid, casacore::LCConcatenation, casacore::LCLELMask, casacore::LCBox, casacore::LCExtension, casacore::LCStretch, casacore::LCUnion, casacore::LCHDF5Mask, casacore::LCIntersection, casacore::LCDifference, casacore::LCComplement, and casacore::LCPixelSet.
expand() [1/2]
Slicer casacore::LCRegion::expand (const Slicer & slicer) const
Expand a slicer or position in the region to the full lattice.
This converts the positions in the region to positions in the entire lattice.
expand() [2/2]
IPosition casacore::LCRegion::expand (const IPosition & index) const
fromRecord()
static LCRegion* casacore::LCRegion::fromRecord (const TableRecord & , const String & tableName) static
Convert correct object from a record.
handleDelete()
virtual void casacore::LCRegion::handleDelete () virtual
Handle deletion of the region by deleting possible tables.
The default implementation does nothing.
Reimplemented in casacore::LCPagedMask.
handleRename()
virtual void casacore::LCRegion::handleRename (const String & newName, Bool overwrite) virtual
Handle renaming the region by renaming possible tables.
The default implementation does nothing.
Reimplemented in casacore::LCPagedMask.
hasMask()
virtual Bool casacore::LCRegion::hasMask () const pure virtual
Does the region have a mask?
Implemented in casacore::LCRegionMulti, and casacore::LCRegionSingle.
isWritable()
virtual Bool casacore::LCRegion::isWritable () const virtual
Usually the lattice (i.e.
the region mask) is not writable.
Reimplemented from casacore::LatticeBase.
Reimplemented in casacore::LCMask, casacore::LCPagedMask, and casacore::LCHDF5Mask.
latticeShape()
const IPosition & casacore::LCRegion::latticeShape () const inline
Give the full lattice shape.
Definition at line 231 of file LCRegion.h.
References itsShape.
ndim()
virtual uInt casacore::LCRegion::ndim () const virtual
Return the dimensionality of the region.
Reimplemented from casacore::LatticeBase.
operator!=()
Bool casacore::LCRegion::operator!= (const LCRegion & other) const inline
Non-equality.
Watch out ! You must not, in the derived class structure, invoke LCRegion::operator!= If you do, you will be stuck in a time warp, as this will just fetch the operator== of the concrete class and you start all over again.
Be careful, do not use this anywhere in the derived class structure. You must use, e.g., if (! LCRegion::operator== (...)) rather than if (LCRegion::operator!= (...)) as the latter will invoke an infinite loop. It is ok to use when applying to a concrete class object.
You must use always use !LCRegionoperator==. It is ok in application code using the concrete class to say if (x != y) where x and y are, say, LCBoxes.
Definition at line 253 of file LCRegion.h.
operator=()
LCRegion& casacore::LCRegion::operator= (const LCRegion & other) protected
Assignment (copy semantics) is only useful for derived classes.
operator==()
virtual Bool casacore::LCRegion::operator== (const LCRegion & other) const virtual
Equality.
Reimplemented in casacore::LCPolygon, casacore::LCEllipsoid, casacore::LCConcatenation, casacore::LCRegionMulti, casacore::LCLELMask, casacore::LCMask, casacore::LCUnion, casacore::LCExtension, casacore::LCStretch, casacore::LCBox, casacore::LCIntersection, casacore::LCRegionFixed, casacore::LCDifference, casacore::LCComplement, casacore::LCPagedMask, casacore::LCHDF5Mask, and casacore::LCPixelSet.
putAt()
virtual void casacore::LCRegion::putAt (const Bool & value, const IPosition & where) virtual
Put the value of a single element.
The default implementation uses putSlice.
Reimplemented from casacore::Lattice< Bool >.
Reimplemented in casacore::LCRegionSingle.
set()
virtual void casacore::LCRegion::set (const Bool & value) virtual
Set all elements in the Lattice to the given value.
Reimplemented from casacore::Lattice< Bool >.
Reimplemented in casacore::LCRegionSingle.
setBoundingBox()
void casacore::LCRegion::setBoundingBox (const Slicer & boundingBox) protected
Sometimes it is inconvenient for a derived class to set the bounding box in the constructor.
So it can be set explicitly. It fills in the possibly undefined Slicer values. It may even be needed to set the lattice shape.
setComment()
void casacore::LCRegion::setComment (const String & comment) inline
Definition at line 248 of file LCRegion.h.
References comment(), and itsComment.
setShapeAndBoundingBox()
void casacore::LCRegion::setShapeAndBoundingBox (const IPosition & latticeShape, const Slicer & boundingBox) protected
shape()
virtual IPosition casacore::LCRegion::shape () const virtual
Return the shape of the region (i.e.
of its bounding box).
Implements casacore::LatticeBase.
toRecord()
virtual TableRecord casacore::LCRegion::toRecord (const String & tableName) const pure virtual
Convert the (derived) object to a record.
The record can be used to make the object persistent. The tableName argument can be used by derived classes (e.g. LCPagedMask) to put very large objects.
Implemented in casacore::LCMask, casacore::LCPagedMask, casacore::LCPolygon, casacore::LCEllipsoid, casacore::LCConcatenation, casacore::LCLELMask, casacore::LCExtension, casacore::LCStretch, casacore::LCUnion, casacore::LCBox, casacore::LCIntersection, casacore::LCHDF5Mask, casacore::LCDifference, casacore::LCComplement, and casacore::LCPixelSet.
translate() [1/4]
LCRegion * casacore::LCRegion::translate (const IPosition & translateVector) const inline
Construct another LCRegion (for e.g.
another lattice) by moving this one. It recalculates the bounding box and mask. A positive translation value indicates "to right".
Definition at line 235 of file LCRegion.h.
References itsShape.
Referenced by translate().
translate() [2/4]
LCRegion* casacore::LCRegion::translate (const IPosition & translateVector, const IPosition & newLatticeShape) const
translate() [3/4]
LCRegion * casacore::LCRegion::translate (const Vector< Float > & translateVector) const inline
Definition at line 239 of file LCRegion.h.
References itsShape, and translate().
translate() [4/4]
LCRegion* casacore::LCRegion::translate (const Vector< Float > & translateVector, const IPosition & newLatticeShape) const
type()
virtual String casacore::LCRegion::type () const pure virtual
Region type.
Returns className() of derived class.
Implemented in casacore::LCMask, casacore::LCPagedMask, casacore::LCPolygon, casacore::LCEllipsoid, casacore::LCConcatenation, casacore::LCLELMask, casacore::LCExtension, casacore::LCStretch, casacore::LCUnion, casacore::LCBox, casacore::LCIntersection, casacore::LCHDF5Mask, casacore::LCDifference, casacore::LCComplement, and casacore::LCPixelSet.
Member Data Documentation
itsBoundingBox
Slicer casacore::LCRegion::itsBoundingBox private
Definition at line 222 of file LCRegion.h.
Referenced by boundingBox().
itsComment
String casacore::LCRegion::itsComment private
Definition at line 223 of file LCRegion.h.
Referenced by comment(), and setComment().
itsShape
IPosition casacore::LCRegion::itsShape private
Definition at line 221 of file LCRegion.h.
Referenced by latticeShape(), and translate().
The documentation for this class was generated from the following file:
lattices/LRegions/LCRegion.h