casacore: casacore::ConstFitsKeywordList Class Reference
casacore::ConstFitsKeywordList Class Reference
fits package (libcasa_fits) » FITS_module
list of read-only FITS keywords
#include <fits.h>
Public Member Functions
ConstFitsKeywordList (FitsKeywordList &x)
const FitsKeyword * operator() (int n)
const FitsKeyword * operator() (const FITS::ReservedName &x)
const FitsKeyword * next (const FITS::ReservedName &x)
const FitsKeyword * operator() (const FITS::ReservedName &x, int n)
const FitsKeyword * next (const FITS::ReservedName &x, int n)
const FitsKeyword * operator() (const char *x)
const FitsKeyword * next (const char *x)
Bool isempty () const
void first ()
void last ()
const FitsKeyword * next ()
const FitsKeyword * prev ()
const FitsKeyword * curr ()
Private Attributes
FitsKeywordList & kw
Detailed Description
list of read-only FITS keywords
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Definition at line 955 of file fits.h.
Constructor & Destructor Documentation
ConstFitsKeywordList()
casacore::ConstFitsKeywordList::ConstFitsKeywordList (FitsKeywordList & x) inline
Definition at line 957 of file fits.h.
Member Function Documentation
curr()
const FitsKeyword* casacore::ConstFitsKeywordList::curr () inline
Definition at line 976 of file fits.h.
References casacore::FitsKeywordList::curr(), and kw.
first()
void casacore::ConstFitsKeywordList::first () inline
Definition at line 972 of file fits.h.
References casacore::FitsKeywordList::first(), and kw.
isempty()
Bool casacore::ConstFitsKeywordList::isempty () const inline
Definition at line 971 of file fits.h.
References casacore::FitsKeywordList::isempty(), and kw.
last()
void casacore::ConstFitsKeywordList::last () inline
Definition at line 973 of file fits.h.
References kw, and casacore::FitsKeywordList::last().
next() [1/4]
const FitsKeyword* casacore::ConstFitsKeywordList::next (const FITS::ReservedName & x) inline
Definition at line 962 of file fits.h.
References kw, and casacore::FitsKeywordList::next().
next() [2/4]
const FitsKeyword* casacore::ConstFitsKeywordList::next (const FITS::ReservedName & x, int n) inline
Definition at line 966 of file fits.h.
References kw, and casacore::FitsKeywordList::next().
next() [3/4]
const FitsKeyword* casacore::ConstFitsKeywordList::next (const char * x) inline
Definition at line 969 of file fits.h.
References kw, and casacore::FitsKeywordList::next().
next() [4/4]
const FitsKeyword* casacore::ConstFitsKeywordList::next () inline
Definition at line 974 of file fits.h.
References kw, and casacore::FitsKeywordList::next().
operator()() [1/4]
const FitsKeyword* casacore::ConstFitsKeywordList::operator() (int n) inline
Definition at line 959 of file fits.h.
References kw.
operator()() [2/4]
const FitsKeyword* casacore::ConstFitsKeywordList::operator() (const FITS::ReservedName & x) inline
Definition at line 960 of file fits.h.
References kw.
operator()() [3/4]
const FitsKeyword* casacore::ConstFitsKeywordList::operator() (const FITS::ReservedName & x, int n) inline
Definition at line 964 of file fits.h.
References kw.
operator()() [4/4]
const FitsKeyword* casacore::ConstFitsKeywordList::operator() (const char * x) inline
Definition at line 968 of file fits.h.
References kw.
prev()
const FitsKeyword* casacore::ConstFitsKeywordList::prev () inline
Definition at line 975 of file fits.h.
References kw, and casacore::FitsKeywordList::prev().
Member Data Documentation
kw
FitsKeywordList& casacore::ConstFitsKeywordList::kw private
Definition at line 979 of file fits.h.
Referenced by curr(), first(), isempty(), last(), next(), operator()(), and prev().
The documentation for this class was generated from the following file:
fits/FITS/fits.h