casacore: casacore::MSDopplerColumns Class Reference
casacore::MSDopplerColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSDoppler columns.
#include <MSDopplerColumns.h>
Public Member Functions
MSDopplerColumns (MSDoppler &msDoppler)
Create a columns object that accesses the data in the specified Table.
~MSDopplerColumns ()
The destructor does nothing special.
ScalarColumn< Int > & dopplerId ()
Read-write access to required columns.
ScalarColumn< Int > & sourceId ()
ScalarColumn< Int > & transitionId ()
ScalarColumn< Double > & velDef ()
ScalarQuantColumn< Double > & velDefQuant ()
ScalarMeasColumn< MDoppler > & velDefMeas ()
const ROScalarColumn< Int > & dopplerId () const
Read-only access to required columns.
const ROScalarColumn< Int > & sourceId () const
const ROScalarColumn< Int > & transitionId () const
const ROScalarColumn< Double > & velDef () const
const ROScalarQuantColumn< Double > & velDefQuant () const
const ROScalarMeasColumn< MDoppler > & velDefMeas () const
void setVelDefRef (MDoppler::Types ref)
set the DOPPLER type for the VELDEF column.
Public Member Functions inherited from casacore::ROMSDopplerColumns
ROMSDopplerColumns (const MSDoppler &msDoppler)
Create a columns object that accesses the data in the specified Table.
~ROMSDopplerColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSDoppler table is optional)
const ROScalarColumn< Int > & dopplerId () const
Access to columns.
const ROScalarColumn< Int > & sourceId () const
const ROScalarColumn< Int > & transitionId () const
const ROScalarColumn< Double > & velDef () const
const ROScalarQuantColumn< Double > & velDefQuant () const
const ROScalarMeasColumn< MDoppler > & velDefMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSDopplerColumns ()
void attach (MSDoppler &msDoppler)
Protected Member Functions inherited from casacore::ROMSDopplerColumns
ROMSDopplerColumns ()
void attach (const MSDoppler &msDoppler)
Private Member Functions
MSDopplerColumns (const MSDopplerColumns &)
MSDopplerColumns & operator= (const MSDopplerColumns &)
Private Attributes
ScalarColumn< Int > dopplerId_p
ScalarColumn< Int > sourceId_p
ScalarColumn< Int > transitionId_p
ScalarColumn< Double > velDef_p
ScalarMeasColumn< MDoppler > velDefMeas_p
ScalarQuantColumn< Double > velDefQuant_p
Detailed Description
A class to provide easy read-write access to MSDoppler columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSDoppler
ScalarColumn
Etymology
MSDopplerColumns stands for MeasurementSet Doppler Table columns.
Synopsis
This class provides access to the columns in the MSDoppler Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 164 of file MSDopplerColumns.h.
Constructor & Destructor Documentation
MSDopplerColumns() [1/3]
casacore::MSDopplerColumns::MSDopplerColumns (MSDoppler & msDoppler)
Create a columns object that accesses the data in the specified Table.
~MSDopplerColumns()
casacore::MSDopplerColumns::~MSDopplerColumns ()
The destructor does nothing special.
MSDopplerColumns() [2/3]
casacore::MSDopplerColumns::MSDopplerColumns () protected
MSDopplerColumns() [3/3]
casacore::MSDopplerColumns::MSDopplerColumns (const MSDopplerColumns &) private
Member Function Documentation
attach()
void casacore::MSDopplerColumns::attach (MSDoppler & msDoppler) protected
dopplerId() [1/2]
ScalarColumn<Int>& casacore::MSDopplerColumns::dopplerId () inline
Read-write access to required columns.
Definition at line 175 of file MSDopplerColumns.h.
References dopplerId_p.
dopplerId() [2/2]
const ROScalarColumn<Int>& casacore::MSDopplerColumns::dopplerId () const inline
Read-only access to required columns.
Definition at line 185 of file MSDopplerColumns.h.
References casacore::ROMSDopplerColumns::dopplerId().
operator=()
MSDopplerColumns& casacore::MSDopplerColumns::operator= (const MSDopplerColumns &) private
setVelDefRef()
void casacore::MSDopplerColumns::setVelDefRef (MDoppler::Types ref)
set the DOPPLER type for the VELDEF column.
sourceId() [1/2]
ScalarColumn<Int>& casacore::MSDopplerColumns::sourceId () inline
Definition at line 176 of file MSDopplerColumns.h.
References sourceId_p.
sourceId() [2/2]
const ROScalarColumn<Int>& casacore::MSDopplerColumns::sourceId () const inline
Definition at line 187 of file MSDopplerColumns.h.
References casacore::ROMSDopplerColumns::sourceId().
transitionId() [1/2]
ScalarColumn<Int>& casacore::MSDopplerColumns::transitionId () inline
Definition at line 177 of file MSDopplerColumns.h.
References transitionId_p.
transitionId() [2/2]
const ROScalarColumn<Int>& casacore::MSDopplerColumns::transitionId () const inline
Definition at line 189 of file MSDopplerColumns.h.
References casacore::ROMSDopplerColumns::transitionId().
velDef() [1/2]
ScalarColumn<Double>& casacore::MSDopplerColumns::velDef () inline
Definition at line 178 of file MSDopplerColumns.h.
References velDef_p.
velDef() [2/2]
const ROScalarColumn<Double>& casacore::MSDopplerColumns::velDef () const inline
Definition at line 191 of file MSDopplerColumns.h.
References casacore::ROMSDopplerColumns::velDef().
velDefMeas() [1/2]
ScalarMeasColumn<MDoppler>& casacore::MSDopplerColumns::velDefMeas () inline
Definition at line 180 of file MSDopplerColumns.h.
References velDefMeas_p.
velDefMeas() [2/2]
const ROScalarMeasColumn<MDoppler>& casacore::MSDopplerColumns::velDefMeas () const inline
Definition at line 195 of file MSDopplerColumns.h.
References casacore::ROMSDopplerColumns::velDefMeas().
velDefQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSDopplerColumns::velDefQuant () inline
Definition at line 179 of file MSDopplerColumns.h.
References velDefQuant_p.
velDefQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSDopplerColumns::velDefQuant () const inline
Definition at line 193 of file MSDopplerColumns.h.
References casacore::ROMSDopplerColumns::velDefQuant().
Member Data Documentation
dopplerId_p
ScalarColumn<Int> casacore::MSDopplerColumns::dopplerId_p private
Definition at line 217 of file MSDopplerColumns.h.
Referenced by dopplerId().
sourceId_p
ScalarColumn<Int> casacore::MSDopplerColumns::sourceId_p private
Definition at line 218 of file MSDopplerColumns.h.
Referenced by sourceId().
transitionId_p
ScalarColumn<Int> casacore::MSDopplerColumns::transitionId_p private
Definition at line 219 of file MSDopplerColumns.h.
Referenced by transitionId().
velDef_p
ScalarColumn<Double> casacore::MSDopplerColumns::velDef_p private
Definition at line 220 of file MSDopplerColumns.h.
Referenced by velDef().
velDefMeas_p
ScalarMeasColumn<MDoppler> casacore::MSDopplerColumns::velDefMeas_p private
Definition at line 223 of file MSDopplerColumns.h.
Referenced by velDefMeas().
velDefQuant_p
ScalarQuantColumn<Double> casacore::MSDopplerColumns::velDefQuant_p private
Definition at line 226 of file MSDopplerColumns.h.
Referenced by velDefQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSDopplerColumns.h