casacore: casacore::ROMSPolarizationColumns Class Reference
casacore::ROMSPolarizationColumns Class Reference
MeasurementSets_module
A class to provide easy read-only access to MSPolarization columns.
#include <MSPolColumns.h>
Public Member Functions
ROMSPolarizationColumns (const MSPolarization &msPolarization)
Create a columns object that accesses the data in the specified Table.
~ROMSPolarizationColumns ()
The destructor does nothing special.
const ROArrayColumn< Int > & corrProduct () const
Access to required columns.
const ROArrayColumn< Int > & corrType () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Int > & numCorr () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int match (const Vector< Stokes::StokesTypes > &polType, Int tryRow=-1)
returns the last row that contains the an entry in the CORR_TYPE column that matches, in length and value, the supplied corrType Vector.
Protected Member Functions
ROMSPolarizationColumns ()
void attach (const MSPolarization &msPolarization)
Private Member Functions
Bool matchCorrType (uInt row, const Vector< Int > &polType) const
Bool matchCorrProduct (uInt row, const Matrix< Int > &polProduct) const
ROMSPolarizationColumns (const ROMSPolarizationColumns &)
ROMSPolarizationColumns & operator= (const ROMSPolarizationColumns &)
Private Attributes
ROArrayColumn< Int > corrProduct_p
ROArrayColumn< Int > corrType_p
ROScalarColumn< Bool > flagRow_p
ROScalarColumn< Int > numCorr_p
Detailed Description
A class to provide easy read-only access to MSPolarization columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSPolarization
ArrayColumn
ScalarColumn
Etymology
ROMSPolarizationColumns stands for Read-Only MeasurementSet Polarization Table columns.
Synopsis
This class provides read-only access to the columns in the MSPolarization Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 75 of file MSPolColumns.h.
Constructor & Destructor Documentation
casacore::ROMSPolarizationColumns::ROMSPolarizationColumns (const MSPolarization & msPolarization)
Create a columns object that accesses the data in the specified Table.
casacore::ROMSPolarizationColumns::~ROMSPolarizationColumns ()
The destructor does nothing special.
casacore::ROMSPolarizationColumns::ROMSPolarizationColumns () protected
casacore::ROMSPolarizationColumns::ROMSPolarizationColumns (const ROMSPolarizationColumns &) private
Member Function Documentation
void casacore::ROMSPolarizationColumns::attach (const MSPolarization & msPolarization) protected
const ROArrayColumn<Int>& casacore::ROMSPolarizationColumns::corrProduct () const inline
Access to required columns.
Definition at line 86 of file MSPolColumns.h.
References corrProduct_p.
Referenced by casacore::MSPolarizationColumns::corrProduct().
const ROArrayColumn<Int>& casacore::ROMSPolarizationColumns::corrType () const inline
Definition at line 87 of file MSPolColumns.h.
References corrType_p.
Referenced by casacore::MSPolarizationColumns::corrType().
const ROScalarColumn<Bool>& casacore::ROMSPolarizationColumns::flagRow () const inline
Definition at line 88 of file MSPolColumns.h.
References flagRow_p.
Referenced by casacore::MSPolarizationColumns::flagRow().
Int casacore::ROMSPolarizationColumns::match (const Vector< Stokes::StokesTypes > & polType, Int tryRow = -1)
returns the last row that contains the an entry in the CORR_TYPE column that matches, in length and value, the supplied corrType Vector.
Returns -1 if no match could be found. Flagged rows can never match. If tryRow is non-negative, then that row is tested to see if it matches before any others are tested. Setting tryRow to a positive value greater than the table length will throw an exception (AipsError), when compiled in debug mode.
Bool casacore::ROMSPolarizationColumns::matchCorrProduct (uInt row, const Matrix< Int > & polProduct) const private
Bool casacore::ROMSPolarizationColumns::matchCorrType (uInt row, const Vector< Int > & polType) const private
uInt casacore::ROMSPolarizationColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 93 of file MSPolColumns.h.
References corrProduct_p.
const ROScalarColumn<Int>& casacore::ROMSPolarizationColumns::numCorr () const inline
Definition at line 89 of file MSPolColumns.h.
References numCorr_p.
Referenced by casacore::MSPolarizationColumns::numCorr().
ROMSPolarizationColumns& casacore::ROMSPolarizationColumns::operator= (const ROMSPolarizationColumns &) private
Member Data Documentation
ROArrayColumn<Int> casacore::ROMSPolarizationColumns::corrProduct_p private
Definition at line 124 of file MSPolColumns.h.
Referenced by corrProduct(), and nrow().
ROArrayColumn<Int> casacore::ROMSPolarizationColumns::corrType_p private
Definition at line 125 of file MSPolColumns.h.
Referenced by corrType().
ROScalarColumn<Bool> casacore::ROMSPolarizationColumns::flagRow_p private
Definition at line 126 of file MSPolColumns.h.
Referenced by flagRow().
ROScalarColumn<Int> casacore::ROMSPolarizationColumns::numCorr_p private
Definition at line 127 of file MSPolColumns.h.
Referenced by numCorr().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSPolColumns.h