casacore: casacore::TableColumn Class Reference
casacore::TableColumn Class Reference
tables package (libcasa_tables) » Tables_module
Read/write access to a table column.
#include <TableColumn.h>
Public Member Functions
TableColumn ()
The default constructor creates a null object, i.e.
TableColumn (const Table &, const String &columnName)
Construct the object for a column in the table using its name.
TableColumn (const Table &, uInt columnIndex)
Construct the object for a column in the table using its index.
TableColumn (const TableColumn &)
Copy constructor (reference semantics).
virtual ~TableColumn ()
TableColumn & operator= (const TableColumn &)
Assignment has reference semantics.
virtual TableColumn * clone () const
Clone the object.
void reference (const TableColumn &)
Change the reference to another column.
void attach (const Table &table, const String &columnName)
Attach a column to the object.
void attach (const Table &table, uInt columnIndex)
Bool isNull () const
Test if the object is null, i.e.
void throwIfNull () const
Throw an exception if the object is null, i.e.
Bool isWritable () const
Test if the column can be written to, thus if the column and the underlying table can be written to.
Bool isWritableAtAll () const
Test if the column is writable at all (virtual columns might not be).
void checkWritable () const
Check if the column is writable and throw an exception if not.
const TableRecord & keywordSet () const
Get readonly access to the column keyword set.
TableRecord & rwKeywordSet ()
Get read/write access to the column keyword set.
const ColumnDesc & columnDesc () const
Get const access to the column description.
Table table () const
Get the Table object this column belongs to.
uInt nrow () const
Get the number of rows in the column.
Bool canChangeShape () const
Can the shape of an already existing non-FixedShape array be changed? This depends on the storage manager.
uInt ndimColumn () const
Get the global #dimensions of an array (ie.
IPosition shapeColumn () const
Get the global shape of an array (ie.
Bool isDefined (uInt rownr) const
Test if the given cell contains a defined value.
Bool hasContent (uInt rownr=0) const
Does the column has content in the given row (default is the first row)? It has if it is defined and does not contain an empty array.
uInt ndim (uInt rownr) const
Get the #dimensions of an array in a particular cell.
IPosition shape (uInt rownr) const
Get the shape of an array in a particular cell.
IPosition tileShape (uInt rownr) const
Get the tile shape of an array in a particular cell.
void getScalar (uInt rownr, Bool &value) const
Get the value of a scalar in the given row.
void getScalar (uInt rownr, uChar &value) const
void getScalar (uInt rownr, Short &value) const
void getScalar (uInt rownr, uShort &value) const
void getScalar (uInt rownr, Int &value) const
void getScalar (uInt rownr, uInt &value) const
void getScalar (uInt rownr, Int64 &value) const
void getScalar (uInt rownr, float &value) const
void getScalar (uInt rownr, double &value) const
void getScalar (uInt rownr, Complex &value) const
void getScalar (uInt rownr, DComplex &value) const
void getScalar (uInt rownr, String &value) const
Bool asBool (uInt rownr) const
Get the value from the row and convert it to the required type.
uChar asuChar (uInt rownr) const
Short asShort (uInt rownr) const
uShort asuShort (uInt rownr) const
Int asInt (uInt rownr) const
uInt asuInt (uInt rownr) const
Int64 asInt64 (uInt rownr) const
float asfloat (uInt rownr) const
double asdouble (uInt rownr) const
Complex asComplex (uInt rownr) const
DComplex asDComplex (uInt rownr) const
String asString (uInt rownr) const
void getScalarValue (uInt rownr, Bool *value, const String &) const
Get the value of a scalar in the given row.
void getScalarValue (uInt rownr, uChar *value, const String &) const
void getScalarValue (uInt rownr, Short *value, const String &) const
void getScalarValue (uInt rownr, uShort *value, const String &) const
void getScalarValue (uInt rownr, Int *value, const String &) const
void getScalarValue (uInt rownr, uInt *value, const String &) const
void getScalarValue (uInt rownr, Int64 *value, const String &) const
void getScalarValue (uInt rownr, float *value, const String &) const
void getScalarValue (uInt rownr, double *value, const String &) const
void getScalarValue (uInt rownr, Complex *value, const String &) const
void getScalarValue (uInt rownr, DComplex *value, const String &) const
void getScalarValue (uInt rownr, String *value, const String &) const
void getScalarValue (uInt rownr, void *value, const String &dataTypeId) const
void put (uInt rownr, const TableColumn &that, Bool preserveTileShape=False)
Copy the value of a cell of that column to a cell of this column.
virtual void put (uInt thisRownr, const TableColumn &that, uInt thatRownr, Bool preserveTileShape=False)
Use possibly different row numbers for that (i.e.
void putColumn (const TableColumn &that)
Copy the values of that column to this column.
void putScalar (uInt rownr, const Bool &value)
Put the value of a scalar in the given row.
void putScalar (uInt rownr, const uChar &value)
void putScalar (uInt rownr, const Short &value)
void putScalar (uInt rownr, const uShort &value)
void putScalar (uInt rownr, const Int &value)
void putScalar (uInt rownr, const uInt &value)
void putScalar (uInt rownr, const Int64 &value)
void putScalar (uInt rownr, const float &value)
void putScalar (uInt rownr, const double &value)
void putScalar (uInt rownr, const Complex &value)
void putScalar (uInt rownr, const DComplex &value)
void putScalar (uInt rownr, const String &value)
void putScalar (uInt rownr, const Char *value)
void checkRowNumber (uInt rownr) const
Check if the row number is valid.
void setMaximumCacheSize (uInt nbytes) const
Set the maximum cache size (in bytes) to be used by a storage manager.
Protected Member Functions
BaseColumn * baseColPtr () const
Get the baseColPtr_p of this TableColumn object.
BaseColumn * baseColPtr (const TableColumn &that) const
Get the baseColPtr_p of another TableColumn object.
Protected Attributes
BaseTable * baseTabPtr_p
BaseColumn * baseColPtr_p
const ColumnCache * colCachePtr_p
Bool canChangeShape_p
Bool isColWritable_p
Private Member Functions
void throwNotWritable () const
Throw the exception that the column is not writable.
Friends
class ForwardColumn
Detailed Description
Read/write access to a table column.
Intended use:
Public interface
Review Status
Reviewed By:
dschieb
Date Reviewed:
1994/08/10
Test programs:
none
Prerequisite
Table
ColumnDesc
Synopsis
The class TableColumn gives read and write access to a column in a table. In particular access to the column description (for name, data type, etc.) and to the column keyword set can be obtained. Another important function is isDefined, which tests if a cell (i.e. table row) in a column contains a value.
The classes ScalarColumn<T> and ArrayColumn<T> have to be used to get/put the data in the column cells. However, TableColumn has get functions for the basic data types (Bool, uChar, Short, uSort, Int, uInt, float, double, Complex, DComplex and String). Opposite to the get functions in ScalarColumn<T>, the TableColumn get functions support data type promotion.
A default constructor is defined to allow construction of an array of TableColumn objects. However, this constructs an object not referencing a column. Functions like get, etc. will fail (i.e. result in a segmentation fault) when used on such objects. The functions isNull and throwIfNull can be used to test on this. The functions attach and reference can fill in the object.
Example
See module Tables.
Definition at line 98 of file TableColumn.h.
Constructor & Destructor Documentation
TableColumn() [1/4]
casacore::TableColumn::TableColumn ()
The default constructor creates a null object, i.e.
it does not reference a table column. The sole purpose of this constructor is to allow construction of an array of TableColumn objects. The functions reference and attach can be used to make a null object reference a column. Note that get functions, etc. will cause a segmentation fault when operating on a null object. It was felt it was too expensive to test on null over and over again. The user should use the isNull or throwIfNull function in case of doubt.
TableColumn() [2/4]
casacore::TableColumn::TableColumn (const Table & , const String & columnName)
Construct the object for a column in the table using its name.
TableColumn() [3/4]
casacore::TableColumn::TableColumn (const Table & , uInt columnIndex)
Construct the object for a column in the table using its index.
This allows to loop through all columns in a table as:
for (uInt=0; i<tab.ncolumn(); i++) {
TableColumn tabcol(tab,i);
}
TableColumn() [4/4]
casacore::TableColumn::TableColumn (const TableColumn &)
Copy constructor (reference semantics).
~TableColumn()
virtual casacore::TableColumn::~TableColumn () virtual
Member Function Documentation
asBool()
Bool casacore::TableColumn::asBool (uInt rownr) const
Get the value from the row and convert it to the required type.
This can only be used for scalar columns with a standard data type.
asComplex()
Complex casacore::TableColumn::asComplex (uInt rownr) const
asDComplex()
DComplex casacore::TableColumn::asDComplex (uInt rownr) const
asdouble()
double casacore::TableColumn::asdouble (uInt rownr) const
asfloat()
float casacore::TableColumn::asfloat (uInt rownr) const
asInt()
Int casacore::TableColumn::asInt (uInt rownr) const
asInt64()
Int64 casacore::TableColumn::asInt64 (uInt rownr) const
asShort()
Short casacore::TableColumn::asShort (uInt rownr) const
asString()
String casacore::TableColumn::asString (uInt rownr) const
asuChar()
uChar casacore::TableColumn::asuChar (uInt rownr) const
asuInt()
uInt casacore::TableColumn::asuInt (uInt rownr) const
asuShort()
uShort casacore::TableColumn::asuShort (uInt rownr) const
attach() [1/2]
void casacore::TableColumn::attach (const Table & table, const String & columnName) inline
Attach a column to the object.
This is in fact only a shorthand for <
reference (TableColumn (table, columnName));
Definition at line 153 of file TableColumn.h.
References reference(), and table().
attach() [2/2]
void casacore::TableColumn::attach (const Table & table, uInt columnIndex) inline
Definition at line 155 of file TableColumn.h.
References reference(), and table().
baseColPtr() [1/2]
BaseColumn* casacore::TableColumn::baseColPtr () const inline protected
Get the baseColPtr_p of this TableColumn object.
Definition at line 395 of file TableColumn.h.
References baseColPtr_p.
baseColPtr() [2/2]
BaseColumn* casacore::TableColumn::baseColPtr (const TableColumn & that) const inline protected
Get the baseColPtr_p of another TableColumn object.
This is needed for function put, because baseColPtr_p is a protected member of TableColumn. Another TableColumn has no access to that.
Definition at line 402 of file TableColumn.h.
References baseColPtr_p.
canChangeShape()
Bool casacore::TableColumn::canChangeShape () const inline
Can the shape of an already existing non-FixedShape array be changed? This depends on the storage manager.
Most storage managers can handle it, but TiledDataStMan and TiledColumnStMan can not.
Definition at line 203 of file TableColumn.h.
References canChangeShape_p.
checkRowNumber()
void casacore::TableColumn::checkRowNumber (uInt rownr) const inline
Check if the row number is valid.
It throws an exception if out of range.
Definition at line 379 of file TableColumn.h.
References baseTabPtr_p, and casacore::BaseTable::checkRowNumber().
checkWritable()
void casacore::TableColumn::checkWritable () const inline
Check if the column is writable and throw an exception if not.
Definition at line 178 of file TableColumn.h.
References isWritable(), and throwNotWritable().
Referenced by casacore::ScalarColumn< casacore::String >::put().
clone()
virtual TableColumn* casacore::TableColumn::clone () const virtual
Clone the object.
Reimplemented in casacore::ArrayColumn< T >, casacore::ArrayColumn< Float >, casacore::ArrayColumn< Double >, casacore::ArrayColumn< uChar >, casacore::ArrayColumn< Short >, casacore::ArrayColumn< StoredType >, casacore::ArrayColumn< Int >, casacore::ArrayColumn< Int64 >, casacore::ArrayColumn< DComplex >, casacore::ArrayColumn< Bool >, casacore::ArrayColumn< Complex >, casacore::ArrayColumn< uInt >, casacore::ArrayColumn< uShort >, casacore::ArrayColumn< casacore::String >, casacore::ScalarColumn< T >, casacore::ScalarColumn< casacore::TableRecord >, casacore::ScalarColumn< Float >, casacore::ScalarColumn< Double >, casacore::ScalarColumn< Int >, casacore::ScalarColumn< Bool >, casacore::ScalarColumn< VirtualType >, casacore::ScalarColumn< uInt >, and casacore::ScalarColumn< casacore::String >.
columnDesc()
const ColumnDesc& casacore::TableColumn::columnDesc () const
Get const access to the column description.
ColumnDesc functions have to be used to get the data type, etc..
getScalar() [1/12]
void casacore::TableColumn::getScalar (uInt rownr, Bool & value) const inline
Get the value of a scalar in the given row.
Data type promotion is possible. These functions only work for the standard data types.
Definition at line 242 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [2/12]
void casacore::TableColumn::getScalar (uInt rownr, uChar & value) const inline
Definition at line 244 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [3/12]
void casacore::TableColumn::getScalar (uInt rownr, Short & value) const inline
Definition at line 246 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [4/12]
void casacore::TableColumn::getScalar (uInt rownr, uShort & value) const inline
Definition at line 248 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [5/12]
void casacore::TableColumn::getScalar (uInt rownr, Int & value) const inline
Definition at line 250 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [6/12]
void casacore::TableColumn::getScalar (uInt rownr, uInt & value) const inline
Definition at line 252 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [7/12]
void casacore::TableColumn::getScalar (uInt rownr, Int64 & value) const inline
Definition at line 254 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [8/12]
void casacore::TableColumn::getScalar (uInt rownr, float & value) const inline
Definition at line 256 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [9/12]
void casacore::TableColumn::getScalar (uInt rownr, double & value) const inline
Definition at line 258 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [10/12]
void casacore::TableColumn::getScalar (uInt rownr, Complex & value) const inline
Definition at line 260 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [11/12]
void casacore::TableColumn::getScalar (uInt rownr, DComplex & value) const inline
Definition at line 262 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalar() [12/12]
void casacore::TableColumn::getScalar (uInt rownr, String & value) const inline
Definition at line 264 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [1/13]
void casacore::TableColumn::getScalarValue (uInt rownr, Bool * value, const String &) const inline
Get the value of a scalar in the given row.
These functions work for all data types. Data type promotion is possible for the standard data types. The functions are primarily meant for ScalarColumn<T>.
Definition at line 290 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [2/13]
void casacore::TableColumn::getScalarValue (uInt rownr, uChar * value, const String &) const inline
Definition at line 292 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [3/13]
void casacore::TableColumn::getScalarValue (uInt rownr, Short * value, const String &) const inline
Definition at line 294 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [4/13]
void casacore::TableColumn::getScalarValue (uInt rownr, uShort * value, const String &) const inline
Definition at line 296 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [5/13]
void casacore::TableColumn::getScalarValue (uInt rownr, Int * value, const String &) const inline
Definition at line 298 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [6/13]
void casacore::TableColumn::getScalarValue (uInt rownr, uInt * value, const String &) const inline
Definition at line 300 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [7/13]
void casacore::TableColumn::getScalarValue (uInt rownr, Int64 * value, const String &) const inline
Definition at line 302 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [8/13]
void casacore::TableColumn::getScalarValue (uInt rownr, float * value, const String &) const inline
Definition at line 304 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [9/13]
void casacore::TableColumn::getScalarValue (uInt rownr, double * value, const String &) const inline
Definition at line 306 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [10/13]
void casacore::TableColumn::getScalarValue (uInt rownr, Complex * value, const String &) const inline
Definition at line 308 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [11/13]
void casacore::TableColumn::getScalarValue (uInt rownr, DComplex * value, const String &) const inline
Definition at line 310 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [12/13]
void casacore::TableColumn::getScalarValue (uInt rownr, String * value, const String &) const inline
Definition at line 312 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
getScalarValue() [13/13]
void casacore::TableColumn::getScalarValue (uInt rownr, void * value, const String & dataTypeId) const inline
Definition at line 314 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::getScalar(), TABLECOLUMNCHECKROW, and casacore::value().
hasContent()
Bool casacore::TableColumn::hasContent (uInt rownr = 0) const
Does the column has content in the given row (default is the first row)? It has if it is defined and does not contain an empty array.
isDefined()
Bool casacore::TableColumn::isDefined (uInt rownr) const inline
Test if the given cell contains a defined value.
Definition at line 219 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::isDefined(), and TABLECOLUMNCHECKROW.
isNull()
Bool casacore::TableColumn::isNull () const inline
Test if the object is null, i.e.
does not reference a column.
Definition at line 160 of file TableColumn.h.
References baseColPtr_p, casacore::False, and casacore::True.
isWritable()
Bool casacore::TableColumn::isWritable () const inline
Test if the column can be written to, thus if the column and the underlying table can be written to.
Definition at line 169 of file TableColumn.h.
References baseTabPtr_p, isColWritable_p, and casacore::BaseTable::isWritable().
Referenced by checkWritable().
isWritableAtAll()
Bool casacore::TableColumn::isWritableAtAll () const inline
Test if the column is writable at all (virtual columns might not be).
Note that keywords can always be written, even for virtual columns.
Definition at line 174 of file TableColumn.h.
References isColWritable_p.
keywordSet()
const TableRecord& casacore::TableColumn::keywordSet () const inline
Get readonly access to the column keyword set.
Definition at line 182 of file TableColumn.h.
References baseColPtr_p, and casacore::BaseColumn::keywordSet().
ndim()
uInt casacore::TableColumn::ndim (uInt rownr) const inline
Get the #dimensions of an array in a particular cell.
Definition at line 227 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::ndim(), and TABLECOLUMNCHECKROW.
ndimColumn()
uInt casacore::TableColumn::ndimColumn () const inline
Get the global #dimensions of an array (ie.
for all cells in column). This is always set for fixed shape arrays. Otherwise, 0 will be returned.
Definition at line 209 of file TableColumn.h.
References baseColPtr_p, and casacore::BaseColumn::ndimColumn().
nrow()
uInt casacore::TableColumn::nrow () const inline
Get the number of rows in the column.
Definition at line 197 of file TableColumn.h.
References baseColPtr_p, and casacore::BaseColumn::nrow().
operator=()
TableColumn& casacore::TableColumn::operator= (const TableColumn &)
Assignment has reference semantics.
It copies the object, not the data of that column to this column. Function putColumn can be used to copy the data of a column.
It does the same as the reference function.
put() [1/2]
void casacore::TableColumn::put (uInt rownr, const TableColumn & that, Bool preserveTileShape = False) inline
Copy the value of a cell of that column to a cell of this column.
This function only works for the standard data types. Data type promotion will be done if needed. An exception is thrown if this column is not writable or if the data cannot be converted.
Use the same row numbers for both cells.
Definition at line 327 of file TableColumn.h.
put() [2/2]
virtual void casacore::TableColumn::put (uInt thisRownr, const TableColumn & that, uInt thatRownr, Bool preserveTileShape = False) virtual
Use possibly different row numbers for that (i.e.
input) and and this (i.e. output) cell.
Reimplemented in casacore::ArrayColumn< T >, casacore::ArrayColumn< Float >, casacore::ArrayColumn< Double >, casacore::ArrayColumn< uChar >, casacore::ArrayColumn< Short >, casacore::ArrayColumn< StoredType >, casacore::ArrayColumn< Int >, casacore::ArrayColumn< Int64 >, casacore::ArrayColumn< DComplex >, casacore::ArrayColumn< Bool >, casacore::ArrayColumn< Complex >, casacore::ArrayColumn< uInt >, casacore::ArrayColumn< uShort >, casacore::ArrayColumn< casacore::String >, casacore::ScalarColumn< T >, casacore::ScalarColumn< casacore::TableRecord >, casacore::ScalarColumn< Float >, casacore::ScalarColumn< Double >, casacore::ScalarColumn< Int >, casacore::ScalarColumn< Bool >, casacore::ScalarColumn< VirtualType >, casacore::ScalarColumn< uInt >, and casacore::ScalarColumn< casacore::String >.
putColumn()
void casacore::TableColumn::putColumn (const TableColumn & that)
Copy the values of that column to this column.
The numbers of rows in both columns must be equal. Data type promotion is possible. An exception is thrown if the data cannot be converted. This function is useful to copy one column to another without knowing their data types. In fact, this function is an assignment operator with copy semantics.
putScalar() [1/13]
void casacore::TableColumn::putScalar (uInt rownr, const Bool & value) inline
Put the value of a scalar in the given row.
Data type promotion is possible. These functions only work for the standard data types.
Definition at line 349 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
Referenced by putScalar().
putScalar() [2/13]
void casacore::TableColumn::putScalar (uInt rownr, const uChar & value) inline
Definition at line 351 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [3/13]
void casacore::TableColumn::putScalar (uInt rownr, const Short & value) inline
Definition at line 353 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [4/13]
void casacore::TableColumn::putScalar (uInt rownr, const uShort & value) inline
Definition at line 355 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [5/13]
void casacore::TableColumn::putScalar (uInt rownr, const Int & value) inline
Definition at line 357 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [6/13]
void casacore::TableColumn::putScalar (uInt rownr, const uInt & value) inline
Definition at line 359 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [7/13]
void casacore::TableColumn::putScalar (uInt rownr, const Int64 & value) inline
Definition at line 361 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [8/13]
void casacore::TableColumn::putScalar (uInt rownr, const float & value) inline
Definition at line 363 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [9/13]
void casacore::TableColumn::putScalar (uInt rownr, const double & value) inline
Definition at line 365 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [10/13]
void casacore::TableColumn::putScalar (uInt rownr, const Complex & value) inline
Definition at line 367 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [11/13]
void casacore::TableColumn::putScalar (uInt rownr, const DComplex & value) inline
Definition at line 369 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [12/13]
void casacore::TableColumn::putScalar (uInt rownr, const String & value) inline
Definition at line 371 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::putScalar(), TABLECOLUMNCHECKROW, and casacore::value().
putScalar() [13/13]
void casacore::TableColumn::putScalar (uInt rownr, const Char * value) inline
Definition at line 373 of file TableColumn.h.
References putScalar(), and casacore::value().
reference()
void casacore::TableColumn::reference (const TableColumn &)
Change the reference to another column.
This is in fact an assignment operator with reference semantics. It removes the reference to the current column and creates a reference to the column referenced in the other object. It will handle null objects correctly.
Referenced by attach().
rwKeywordSet()
TableRecord& casacore::TableColumn::rwKeywordSet ()
Get read/write access to the column keyword set.
An exception is thrown if the table is not writable.
setMaximumCacheSize()
void casacore::TableColumn::setMaximumCacheSize (uInt nbytes) const inline
Set the maximum cache size (in bytes) to be used by a storage manager.
Definition at line 383 of file TableColumn.h.
References baseColPtr_p, and casacore::BaseColumn::setMaximumCacheSize().
shape()
IPosition casacore::TableColumn::shape (uInt rownr) const inline
Get the shape of an array in a particular cell.
Definition at line 231 of file TableColumn.h.
References baseColPtr_p, casacore::BaseColumn::shape(), and TABLECOLUMNCHECKROW.
shapeColumn()
IPosition casacore::TableColumn::shapeColumn () const inline
Get the global shape of an array (ie.
for all cells in the column). This is always set for fixed shape arrays. Otherwise, a 0-dim shape will be returned.
Definition at line 215 of file TableColumn.h.
References baseColPtr_p, and casacore::BaseColumn::shapeColumn().
table()
Table casacore::TableColumn::table () const
Get the Table object this column belongs to.
Referenced by casacore::ScalarColumn< casacore::String >::attach(), attach(), and casacore::ArrayColumn< casacore::String >::attach().
throwIfNull()
void casacore::TableColumn::throwIfNull () const
Throw an exception if the object is null, i.e.
if function isNull() is True.
throwNotWritable()
void casacore::TableColumn::throwNotWritable () const private
Throw the exception that the column is not writable.
Referenced by checkWritable().
tileShape()
IPosition casacore::TableColumn::tileShape (uInt rownr) const inline
Get the tile shape of an array in a particular cell.
Definition at line 235 of file TableColumn.h.
References baseColPtr_p, TABLECOLUMNCHECKROW, and casacore::BaseColumn::tileShape().
Friends And Related Function Documentation
ForwardColumn
friend class ForwardColumn friend
Definition at line 100 of file TableColumn.h.
Member Data Documentation
baseColPtr_p
BaseColumn* casacore::TableColumn::baseColPtr_p protected
Definition at line 388 of file TableColumn.h.
Referenced by baseColPtr(), casacore::ArrayColumn< casacore::String >::baseGet(), casacore::ArrayColumn< casacore::String >::basePut(), casacore::ScalarColumn< casacore::String >::get(), getScalar(), getScalarValue(), isDefined(), isNull(), keywordSet(), casacore::ArrayColumn< casacore::String >::ndim(), ndim(), ndimColumn(), nrow(), casacore::ScalarColumn< casacore::String >::put(), putScalar(), setMaximumCacheSize(), casacore::ArrayColumn< casacore::String >::shape(), shape(), shapeColumn(), and tileShape().
baseTabPtr_p
BaseTable* casacore::TableColumn::baseTabPtr_p protected
Definition at line 387 of file TableColumn.h.
Referenced by checkRowNumber(), and isWritable().
canChangeShape_p
Bool casacore::TableColumn::canChangeShape_p protected
Definition at line 390 of file TableColumn.h.
Referenced by canChangeShape().
colCachePtr_p
const ColumnCache* casacore::TableColumn::colCachePtr_p protected
Definition at line 389 of file TableColumn.h.
Referenced by casacore::ScalarColumn< casacore::String >::get().
isColWritable_p
Bool casacore::TableColumn::isColWritable_p protected
Definition at line 391 of file TableColumn.h.
Referenced by isWritable(), and isWritableAtAll().
The documentation for this class was generated from the following file:
tables/Tables/TableColumn.h