casacore: casacore::ROMSFlagCmdColumns Class Reference
casacore::ROMSFlagCmdColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSFlagCmd columns.
#include <MSFlagCmdColumns.h>
Public Member Functions
ROMSFlagCmdColumns (const MSFlagCmd &msFlagCmd)
Create a columns object that accesses the data in the specified Table.
~ROMSFlagCmdColumns ()
The destructor does nothing special.
const ROScalarColumn< Bool > & applied () const
Access to required columns.
const ROScalarColumn< String > & command () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & interval () const
const ROScalarColumn< Int > & level () const
const ROScalarColumn< String > & reason () const
const ROScalarColumn< Int > & severity () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< String > & type () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSFlagCmdColumns ()
void attach (const MSFlagCmd &msFlagCmd)
Private Member Functions
ROMSFlagCmdColumns (const ROMSFlagCmdColumns &)
ROMSFlagCmdColumns & operator= (const ROMSFlagCmdColumns &)
Private Attributes
ROScalarColumn< Bool > applied_p
ROScalarColumn< String > command_p
ROScalarColumn< Double > interval_p
ROScalarColumn< Int > level_p
ROScalarColumn< String > reason_p
ROScalarColumn< Int > severity_p
ROScalarColumn< Double > time_p
ROScalarColumn< String > type_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarQuantColumn< Double > intervalQuant_p
ROScalarQuantColumn< Double > timeQuant_p
Detailed Description
A class to provide easy read-only access to MSFlagCmd columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSFlagCmd
ScalarColumn
Etymology
ROMSFlagCmdColumns stands for Read-Only MeasurementSet FlagCmd Table columns.
Synopsis
This class provides read-only access to the columns in the MSFlagCmd Table. It does the declaration of all the ScalarColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 75 of file MSFlagCmdColumns.h.
Constructor & Destructor Documentation
ROMSFlagCmdColumns() [1/3]
casacore::ROMSFlagCmdColumns::ROMSFlagCmdColumns (const MSFlagCmd & msFlagCmd)
Create a columns object that accesses the data in the specified Table.
~ROMSFlagCmdColumns()
casacore::ROMSFlagCmdColumns::~ROMSFlagCmdColumns ()
The destructor does nothing special.
ROMSFlagCmdColumns() [2/3]
casacore::ROMSFlagCmdColumns::ROMSFlagCmdColumns () protected
ROMSFlagCmdColumns() [3/3]
casacore::ROMSFlagCmdColumns::ROMSFlagCmdColumns (const ROMSFlagCmdColumns &) private
Member Function Documentation
applied()
const ROScalarColumn<Bool>& casacore::ROMSFlagCmdColumns::applied () const inline
Access to required columns.
Definition at line 86 of file MSFlagCmdColumns.h.
References applied_p.
Referenced by casacore::MSFlagCmdColumns::applied().
attach()
void casacore::ROMSFlagCmdColumns::attach (const MSFlagCmd & msFlagCmd) protected
command()
const ROScalarColumn<String>& casacore::ROMSFlagCmdColumns::command () const inline
Definition at line 87 of file MSFlagCmdColumns.h.
References command_p.
Referenced by casacore::MSFlagCmdColumns::command().
interval()
const ROScalarColumn<Double>& casacore::ROMSFlagCmdColumns::interval () const inline
Definition at line 90 of file MSFlagCmdColumns.h.
References interval_p.
Referenced by casacore::MSFlagCmdColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFlagCmdColumns::intervalQuant () const inline
Definition at line 88 of file MSFlagCmdColumns.h.
References intervalQuant_p.
Referenced by casacore::MSFlagCmdColumns::intervalQuant().
level()
const ROScalarColumn<Int>& casacore::ROMSFlagCmdColumns::level () const inline
Definition at line 91 of file MSFlagCmdColumns.h.
References level_p.
Referenced by casacore::MSFlagCmdColumns::level().
nrow()
uInt casacore::ROMSFlagCmdColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 101 of file MSFlagCmdColumns.h.
References applied_p.
operator=()
ROMSFlagCmdColumns& casacore::ROMSFlagCmdColumns::operator= (const ROMSFlagCmdColumns &) private
reason()
const ROScalarColumn<String>& casacore::ROMSFlagCmdColumns::reason () const inline
Definition at line 92 of file MSFlagCmdColumns.h.
References reason_p.
Referenced by casacore::MSFlagCmdColumns::reason().
severity()
const ROScalarColumn<Int>& casacore::ROMSFlagCmdColumns::severity () const inline
Definition at line 93 of file MSFlagCmdColumns.h.
References severity_p.
Referenced by casacore::MSFlagCmdColumns::severity().
time()
const ROScalarColumn<Double>& casacore::ROMSFlagCmdColumns::time () const inline
Definition at line 94 of file MSFlagCmdColumns.h.
References time_p.
Referenced by casacore::MSFlagCmdColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSFlagCmdColumns::timeMeas () const inline
Definition at line 96 of file MSFlagCmdColumns.h.
References timeMeas_p.
Referenced by casacore::MSFlagCmdColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFlagCmdColumns::timeQuant () const inline
Definition at line 95 of file MSFlagCmdColumns.h.
References timeQuant_p.
Referenced by casacore::MSFlagCmdColumns::timeQuant().
type()
const ROScalarColumn<String>& casacore::ROMSFlagCmdColumns::type () const inline
Definition at line 97 of file MSFlagCmdColumns.h.
References type_p.
Referenced by casacore::MSFlagCmdColumns::type().
Member Data Documentation
applied_p
ROScalarColumn<Bool> casacore::ROMSFlagCmdColumns::applied_p private
Definition at line 118 of file MSFlagCmdColumns.h.
Referenced by applied(), and nrow().
command_p
ROScalarColumn<String> casacore::ROMSFlagCmdColumns::command_p private
Definition at line 119 of file MSFlagCmdColumns.h.
Referenced by command().
interval_p
ROScalarColumn<Double> casacore::ROMSFlagCmdColumns::interval_p private
Definition at line 120 of file MSFlagCmdColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFlagCmdColumns::intervalQuant_p private
Definition at line 131 of file MSFlagCmdColumns.h.
Referenced by intervalQuant().
level_p
ROScalarColumn<Int> casacore::ROMSFlagCmdColumns::level_p private
Definition at line 121 of file MSFlagCmdColumns.h.
Referenced by level().
reason_p
ROScalarColumn<String> casacore::ROMSFlagCmdColumns::reason_p private
Definition at line 122 of file MSFlagCmdColumns.h.
Referenced by reason().
severity_p
ROScalarColumn<Int> casacore::ROMSFlagCmdColumns::severity_p private
Definition at line 123 of file MSFlagCmdColumns.h.
Referenced by severity().
time_p
ROScalarColumn<Double> casacore::ROMSFlagCmdColumns::time_p private
Definition at line 124 of file MSFlagCmdColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSFlagCmdColumns::timeMeas_p private
Definition at line 128 of file MSFlagCmdColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFlagCmdColumns::timeQuant_p private
Definition at line 132 of file MSFlagCmdColumns.h.
Referenced by timeQuant().
type_p
ROScalarColumn<String> casacore::ROMSFlagCmdColumns::type_p private
Definition at line 125 of file MSFlagCmdColumns.h.
Referenced by type().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSFlagCmdColumns.h