casacore: casacore::MSFeedColumns Class Reference
casacore::MSFeedColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSFeed columns.
#include <MSFeedColumns.h>
Public Member Functions
MSFeedColumns (MSFeed &msFeed)
Create a columns object that accesses the data in the specified Table.
~MSFeedColumns ()
The desctructor does nothing special.
ScalarColumn< Int > & antennaId ()
Read-write access to required columns.
ScalarColumn< Int > & beamId ()
ArrayColumn< Double > & beamOffset ()
ArrayQuantColumn< Double > & beamOffsetQuant ()
ArrayMeasColumn< MDirection > & beamOffsetMeas ()
ScalarColumn< Int > & feedId ()
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< Int > & numReceptors ()
ArrayColumn< Complex > & polResponse ()
ArrayColumn< String > & polarizationType ()
ArrayColumn< Double > & position ()
ArrayQuantColumn< Double > & positionQuant ()
ScalarMeasColumn< MPosition > & positionMeas ()
ArrayColumn< Double > & receptorAngle ()
ArrayQuantColumn< Double > & receptorAngleQuant ()
ScalarColumn< Int > & spectralWindowId ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
ScalarColumn< Double > & focusLength ()
Read-write access to optional columns.
ScalarQuantColumn< Double > & focusLengthQuant ()
ScalarColumn< Int > & phasedFeedId ()
const ROScalarColumn< Int > & antennaId () const
Read-only access to required columns.
const ROScalarColumn< Int > & beamId () const
const ROArrayColumn< Double > & beamOffset () const
const ROArrayQuantColumn< Double > & beamOffsetQuant () const
const ROArrayMeasColumn< MDirection > & beamOffsetMeas () const
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & numReceptors () const
const ROArrayColumn< Complex > & polResponse () const
const ROArrayColumn< String > & polarizationType () const
const ROArrayColumn< Double > & position () const
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROArrayColumn< Double > & receptorAngle () const
const ROArrayQuantColumn< Double > & receptorAngleQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & focusLength () const
Read-only access to optional columns.
const ROScalarQuantColumn< Double > & focusLengthQuant () const
const ROScalarColumn< Int > & phasedFeedId () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME column.
void setDirectionRef (MDirection::Types ref)
set the direction type for the BEAM_OFFSET column.
void setPositionRef (MPosition::Types ref)
set the position type for the POSITION column.
Public Member Functions inherited from casacore::ROMSFeedColumns
ROMSFeedColumns (const MSFeed &msFeed)
Create a columns object that accesses the data in the specified Table.
~ROMSFeedColumns ()
The destructor does nothing special.
const ROScalarColumn< Int > & antennaId () const
Access to required columns.
const ROScalarColumn< Int > & beamId () const
const ROArrayColumn< Double > & beamOffset () const
const ROArrayQuantColumn< Double > & beamOffsetQuant () const
const ROArrayMeasColumn< MDirection > & beamOffsetMeas () const
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & numReceptors () const
const ROArrayColumn< Complex > & polResponse () const
const ROArrayColumn< String > & polarizationType () const
const ROArrayColumn< Double > & position () const
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROArrayColumn< Double > & receptorAngle () const
const ROArrayQuantColumn< Double > & receptorAngleQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & focusLength () const
Access to optional columns.
const ROScalarQuantColumn< Double > & focusLengthQuant () const
const ROScalarColumn< Int > & phasedFeedId () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int matchFeed (Quantum< Double > &newTimeQ, Quantum< Double > &newIntervalQ, const Int &antId, const Int &fId, const Int &spwId, const Quantum< Double > &timeQ, const Quantum< Double > &intervalQ, const Int &numRec, const Array< Quantum< Double > > &beamOffsetQ, const Array< String > &polType, const Array< Complex > &polResp, const Array< Quantum< Double > > &positionQ, const Array< Quantum< Double > > &receptorAngleQ, const Vector< uInt > &ignoreRows, const Quantum< Double > &focusLengthQ=Quantum< Double >())
Returns the last row that contains a feed with the specified values.
Protected Member Functions
MSFeedColumns ()
void attach (MSFeed &msFeed)
Protected Member Functions inherited from casacore::ROMSFeedColumns
ROMSFeedColumns ()
void attach (const MSFeed &msFeed)
Private Member Functions
MSFeedColumns (const MSFeedColumns &)
MSFeedColumns & operator= (const MSFeedColumns &)
void attachOptionalCols (MSFeed &msFeed)
Private Attributes
ScalarColumn< Int > antennaId_p
ScalarColumn< Int > beamId_p
ArrayColumn< Double > beamOffset_p
ScalarColumn< Int > feedId_p
ScalarColumn< Double > interval_p
ScalarColumn< Int > numReceptors_p
ArrayColumn< Complex > polResponse_p
ArrayColumn< String > polarizationType_p
ArrayColumn< Double > position_p
ArrayColumn< Double > receptorAngle_p
ScalarColumn< Int > spectralWindowId_p
ScalarColumn< Double > time_p
ScalarColumn< Double > focusLength_p
ScalarColumn< Int > phasedFeedId_p
ArrayMeasColumn< MDirection > beamOffsetMeas_p
ScalarMeasColumn< MPosition > positionMeas_p
ScalarMeasColumn< MEpoch > timeMeas_p
ArrayQuantColumn< Double > beamOffsetQuant_p
ScalarQuantColumn< Double > intervalQuant_p
ArrayQuantColumn< Double > positionQuant_p
ArrayQuantColumn< Double > receptorAngleQuant_p
ScalarQuantColumn< Double > timeQuant_p
ScalarQuantColumn< Double > focusLengthQuant_p
Detailed Description
A class to provide easy read-write access to MSFeed columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSFeed
ArrayColumn
ScalarColumn
Etymology
MSFeedColumns stands for MeasurementSet Feed Table columns.
Synopsis
This class provides access to the columns in the MSFeed Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 245 of file MSFeedColumns.h.
Constructor & Destructor Documentation
MSFeedColumns() [1/3]
casacore::MSFeedColumns::MSFeedColumns (MSFeed & msFeed)
Create a columns object that accesses the data in the specified Table.
~MSFeedColumns()
casacore::MSFeedColumns::~MSFeedColumns ()
The desctructor does nothing special.
MSFeedColumns() [2/3]
casacore::MSFeedColumns::MSFeedColumns () protected
MSFeedColumns() [3/3]
casacore::MSFeedColumns::MSFeedColumns (const MSFeedColumns &) private
Member Function Documentation
antennaId() [1/2]
ScalarColumn<Int>& casacore::MSFeedColumns::antennaId () inline
Read-write access to required columns.
Definition at line 256 of file MSFeedColumns.h.
References antennaId_p.
antennaId() [2/2]
const ROScalarColumn<Int>& casacore::MSFeedColumns::antennaId () const inline
Read-only access to required columns.
Definition at line 290 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::antennaId().
attach()
void casacore::MSFeedColumns::attach (MSFeed & msFeed) protected
attachOptionalCols()
void casacore::MSFeedColumns::attachOptionalCols (MSFeed & msFeed) private
beamId() [1/2]
ScalarColumn<Int>& casacore::MSFeedColumns::beamId () inline
Definition at line 257 of file MSFeedColumns.h.
References beamId_p.
beamId() [2/2]
const ROScalarColumn<Int>& casacore::MSFeedColumns::beamId () const inline
Definition at line 292 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::beamId().
beamOffset() [1/2]
ArrayColumn<Double>& casacore::MSFeedColumns::beamOffset () inline
Definition at line 258 of file MSFeedColumns.h.
References beamOffset_p.
beamOffset() [2/2]
const ROArrayColumn<Double>& casacore::MSFeedColumns::beamOffset () const inline
Definition at line 294 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::beamOffset().
beamOffsetMeas() [1/2]
ArrayMeasColumn<MDirection>& casacore::MSFeedColumns::beamOffsetMeas () inline
Definition at line 260 of file MSFeedColumns.h.
References beamOffsetMeas_p.
beamOffsetMeas() [2/2]
const ROArrayMeasColumn<MDirection>& casacore::MSFeedColumns::beamOffsetMeas () const inline
Definition at line 298 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::beamOffsetMeas().
beamOffsetQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSFeedColumns::beamOffsetQuant () inline
Definition at line 259 of file MSFeedColumns.h.
References beamOffsetQuant_p.
beamOffsetQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSFeedColumns::beamOffsetQuant () const inline
Definition at line 296 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::beamOffsetQuant().
feedId() [1/2]
ScalarColumn<Int>& casacore::MSFeedColumns::feedId () inline
Definition at line 262 of file MSFeedColumns.h.
References feedId_p.
feedId() [2/2]
const ROScalarColumn<Int>& casacore::MSFeedColumns::feedId () const inline
Definition at line 300 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::feedId().
focusLength() [1/2]
ScalarColumn<Double>& casacore::MSFeedColumns::focusLength () inline
Read-write access to optional columns.
Definition at line 283 of file MSFeedColumns.h.
References focusLength_p.
focusLength() [2/2]
const ROScalarColumn<Double>& casacore::MSFeedColumns::focusLength () const inline
Read-only access to optional columns.
Definition at line 334 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::focusLength().
focusLengthQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFeedColumns::focusLengthQuant () inline
Definition at line 284 of file MSFeedColumns.h.
References focusLengthQuant_p.
focusLengthQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFeedColumns::focusLengthQuant () const inline
Definition at line 336 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::focusLengthQuant().
interval() [1/2]
ScalarColumn<Double>& casacore::MSFeedColumns::interval () inline
Definition at line 263 of file MSFeedColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSFeedColumns::interval () const inline
Definition at line 302 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFeedColumns::intervalQuant () inline
Definition at line 264 of file MSFeedColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFeedColumns::intervalQuant () const inline
Definition at line 304 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::intervalQuant().
numReceptors() [1/2]
ScalarColumn<Int>& casacore::MSFeedColumns::numReceptors () inline
Definition at line 265 of file MSFeedColumns.h.
References numReceptors_p.
numReceptors() [2/2]
const ROScalarColumn<Int>& casacore::MSFeedColumns::numReceptors () const inline
Definition at line 306 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::numReceptors().
operator=()
MSFeedColumns& casacore::MSFeedColumns::operator= (const MSFeedColumns &) private
phasedFeedId() [1/2]
ScalarColumn<Int>& casacore::MSFeedColumns::phasedFeedId () inline
Definition at line 285 of file MSFeedColumns.h.
References phasedFeedId_p.
phasedFeedId() [2/2]
const ROScalarColumn<Int>& casacore::MSFeedColumns::phasedFeedId () const inline
Definition at line 338 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::phasedFeedId().
polarizationType() [1/2]
ArrayColumn<String>& casacore::MSFeedColumns::polarizationType () inline
Definition at line 267 of file MSFeedColumns.h.
References polarizationType_p.
polarizationType() [2/2]
const ROArrayColumn<String>& casacore::MSFeedColumns::polarizationType () const inline
Definition at line 310 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::polarizationType().
polResponse() [1/2]
ArrayColumn<Complex>& casacore::MSFeedColumns::polResponse () inline
Definition at line 266 of file MSFeedColumns.h.
References polResponse_p.
polResponse() [2/2]
const ROArrayColumn<Complex>& casacore::MSFeedColumns::polResponse () const inline
Definition at line 308 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::polResponse().
position() [1/2]
ArrayColumn<Double>& casacore::MSFeedColumns::position () inline
Definition at line 268 of file MSFeedColumns.h.
References position_p.
position() [2/2]
const ROArrayColumn<Double>& casacore::MSFeedColumns::position () const inline
Definition at line 312 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::position().
positionMeas() [1/2]
ScalarMeasColumn<MPosition>& casacore::MSFeedColumns::positionMeas () inline
Definition at line 270 of file MSFeedColumns.h.
References positionMeas_p.
positionMeas() [2/2]
const ROScalarMeasColumn<MPosition>& casacore::MSFeedColumns::positionMeas () const inline
Definition at line 316 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::positionMeas().
positionQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSFeedColumns::positionQuant () inline
Definition at line 269 of file MSFeedColumns.h.
References positionQuant_p.
positionQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSFeedColumns::positionQuant () const inline
Definition at line 314 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::positionQuant().
receptorAngle() [1/2]
ArrayColumn<Double>& casacore::MSFeedColumns::receptorAngle () inline
Definition at line 272 of file MSFeedColumns.h.
References receptorAngle_p.
receptorAngle() [2/2]
const ROArrayColumn<Double>& casacore::MSFeedColumns::receptorAngle () const inline
Definition at line 318 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::receptorAngle().
receptorAngleQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSFeedColumns::receptorAngleQuant () inline
Definition at line 273 of file MSFeedColumns.h.
References receptorAngleQuant_p.
receptorAngleQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSFeedColumns::receptorAngleQuant () const inline
Definition at line 320 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::receptorAngleQuant().
setDirectionRef()
void casacore::MSFeedColumns::setDirectionRef (MDirection::Types ref)
set the direction type for the BEAM_OFFSET column.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
setEpochRef()
void casacore::MSFeedColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
setPositionRef()
void casacore::MSFeedColumns::setPositionRef (MPosition::Types ref)
set the position type for the POSITION column.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
spectralWindowId() [1/2]
ScalarColumn<Int>& casacore::MSFeedColumns::spectralWindowId () inline
Definition at line 275 of file MSFeedColumns.h.
References spectralWindowId_p.
spectralWindowId() [2/2]
const ROScalarColumn<Int>& casacore::MSFeedColumns::spectralWindowId () const inline
Definition at line 322 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::spectralWindowId().
time() [1/2]
ScalarColumn<Double>& casacore::MSFeedColumns::time () inline
Definition at line 276 of file MSFeedColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSFeedColumns::time () const inline
Definition at line 324 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSFeedColumns::timeMeas () inline
Definition at line 278 of file MSFeedColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSFeedColumns::timeMeas () const inline
Definition at line 328 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFeedColumns::timeQuant () inline
Definition at line 277 of file MSFeedColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFeedColumns::timeQuant () const inline
Definition at line 326 of file MSFeedColumns.h.
References casacore::ROMSFeedColumns::timeQuant().
Member Data Documentation
antennaId_p
ScalarColumn<Int> casacore::MSFeedColumns::antennaId_p private
Definition at line 381 of file MSFeedColumns.h.
Referenced by antennaId().
beamId_p
ScalarColumn<Int> casacore::MSFeedColumns::beamId_p private
Definition at line 382 of file MSFeedColumns.h.
Referenced by beamId().
beamOffset_p
ArrayColumn<Double> casacore::MSFeedColumns::beamOffset_p private
Definition at line 383 of file MSFeedColumns.h.
Referenced by beamOffset().
beamOffsetMeas_p
ArrayMeasColumn<MDirection> casacore::MSFeedColumns::beamOffsetMeas_p private
Definition at line 398 of file MSFeedColumns.h.
Referenced by beamOffsetMeas().
beamOffsetQuant_p
ArrayQuantColumn<Double> casacore::MSFeedColumns::beamOffsetQuant_p private
Definition at line 403 of file MSFeedColumns.h.
Referenced by beamOffsetQuant().
feedId_p
ScalarColumn<Int> casacore::MSFeedColumns::feedId_p private
Definition at line 384 of file MSFeedColumns.h.
Referenced by feedId().
focusLength_p
ScalarColumn<Double> casacore::MSFeedColumns::focusLength_p private
Definition at line 394 of file MSFeedColumns.h.
Referenced by focusLength().
focusLengthQuant_p
ScalarQuantColumn<Double> casacore::MSFeedColumns::focusLengthQuant_p private
Definition at line 409 of file MSFeedColumns.h.
Referenced by focusLengthQuant().
interval_p
ScalarColumn<Double> casacore::MSFeedColumns::interval_p private
Definition at line 385 of file MSFeedColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSFeedColumns::intervalQuant_p private
Definition at line 404 of file MSFeedColumns.h.
Referenced by intervalQuant().
numReceptors_p
ScalarColumn<Int> casacore::MSFeedColumns::numReceptors_p private
Definition at line 386 of file MSFeedColumns.h.
Referenced by numReceptors().
phasedFeedId_p
ScalarColumn<Int> casacore::MSFeedColumns::phasedFeedId_p private
Definition at line 395 of file MSFeedColumns.h.
Referenced by phasedFeedId().
polarizationType_p
ArrayColumn<String> casacore::MSFeedColumns::polarizationType_p private
Definition at line 388 of file MSFeedColumns.h.
Referenced by polarizationType().
polResponse_p
ArrayColumn<Complex> casacore::MSFeedColumns::polResponse_p private
Definition at line 387 of file MSFeedColumns.h.
Referenced by polResponse().
position_p
ArrayColumn<Double> casacore::MSFeedColumns::position_p private
Definition at line 389 of file MSFeedColumns.h.
Referenced by position().
positionMeas_p
ScalarMeasColumn<MPosition> casacore::MSFeedColumns::positionMeas_p private
Definition at line 399 of file MSFeedColumns.h.
Referenced by positionMeas().
positionQuant_p
ArrayQuantColumn<Double> casacore::MSFeedColumns::positionQuant_p private
Definition at line 405 of file MSFeedColumns.h.
Referenced by positionQuant().
receptorAngle_p
ArrayColumn<Double> casacore::MSFeedColumns::receptorAngle_p private
Definition at line 390 of file MSFeedColumns.h.
Referenced by receptorAngle().
receptorAngleQuant_p
ArrayQuantColumn<Double> casacore::MSFeedColumns::receptorAngleQuant_p private
Definition at line 406 of file MSFeedColumns.h.
Referenced by receptorAngleQuant().
spectralWindowId_p
ScalarColumn<Int> casacore::MSFeedColumns::spectralWindowId_p private
Definition at line 391 of file MSFeedColumns.h.
Referenced by spectralWindowId().
time_p
ScalarColumn<Double> casacore::MSFeedColumns::time_p private
Definition at line 392 of file MSFeedColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSFeedColumns::timeMeas_p private
Definition at line 400 of file MSFeedColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSFeedColumns::timeQuant_p private
Definition at line 407 of file MSFeedColumns.h.
Referenced by timeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSFeedColumns.h