casacore: casacore::ReadOnlyMatrixIterator< T > Class Template Reference
casacore::ReadOnlyMatrixIterator< T > Class Template Reference
Arrays_module
Iterate a Matrix cursor through a R/O Array.
#include <MatrixIter.h>
Public Member Functions
ReadOnlyMatrixIterator (const Array< T > &a)
ReadOnlyMatrixIterator (const Array< T > &a, size_t cursorAxis1, size_t cursorAxis2)
void next ()
void reset ()
void origin ()
const Array< T > & array ()
const Matrix< T > & matrix ()
bool atStart () const
bool pastEnd () const
const IPosition & pos () const
IPosition endPos () const
size_t ndim () const
Private Member Functions
ReadOnlyMatrixIterator (const ReadOnlyMatrixIterator< T > &)=delete
Not implemented.
ReadOnlyMatrixIterator< T > & operator= (const ReadOnlyMatrixIterator< T > &)=delete
Not implemented.
Private Attributes
MatrixIterator< T > mi
Detailed Description
template<class T>
class casacore::ReadOnlyMatrixIterator< T >
Iterate a Matrix cursor through a R/O Array.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
ReadOnlyMatrixIterator behaves exactly like MatrixIterator (cf.) only it should be used on const Arrays.
Tip: Note that the R/O MatrixIterator is not derived from R/O ArrayIterator;
Definition at line 101 of file MatrixIter.h.
Constructor & Destructor Documentation
template<class T > casacore::ReadOnlyMatrixIterator< T >::ReadOnlyMatrixIterator (const Array< T > & a) inline
Definition at line 105 of file MatrixIter.h.
template<class T > casacore::ReadOnlyMatrixIterator< T >::ReadOnlyMatrixIterator (const Array< T > & a, size_t cursorAxis1, size_t cursorAxis2) inline
Definition at line 108 of file MatrixIter.h.
template<class T > casacore::ReadOnlyMatrixIterator< T >::ReadOnlyMatrixIterator (const ReadOnlyMatrixIterator< T > &) private delete
Not implemented.
Member Function Documentation
template<class T > const Array<T>& casacore::ReadOnlyMatrixIterator< T >::array () inline
Definition at line 116 of file MatrixIter.h.
References casacore::ArrayIterator< T, Alloc >::array(), and casacore::ReadOnlyMatrixIterator< T >::mi.
template<class T > bool casacore::ReadOnlyMatrixIterator< T >::atStart () const inline
Definition at line 119 of file MatrixIter.h.
References casacore::ArrayPositionIterator::atStart(), and casacore::ReadOnlyMatrixIterator< T >::mi.
template<class T > IPosition casacore::ReadOnlyMatrixIterator< T >::endPos () const inline
Definition at line 122 of file MatrixIter.h.
References casacore::ArrayPositionIterator::endPos(), and casacore::ReadOnlyMatrixIterator< T >::mi.
template<class T > const Matrix<T>& casacore::ReadOnlyMatrixIterator< T >::matrix () inline
Definition at line 117 of file MatrixIter.h.
References casacore::MatrixIterator< T, Alloc >::matrix(), and casacore::ReadOnlyMatrixIterator< T >::mi.
template<class T > size_t casacore::ReadOnlyMatrixIterator< T >::ndim () const inline
Definition at line 123 of file MatrixIter.h.
References casacore::ReadOnlyMatrixIterator< T >::mi, and casacore::ArrayPositionIterator::ndim().
template<class T > void casacore::ReadOnlyMatrixIterator< T >::next () inline
Definition at line 112 of file MatrixIter.h.
References casacore::ReadOnlyMatrixIterator< T >::mi, and casacore::ArrayIterator< T, Alloc >::next().
template<class T > ReadOnlyMatrixIterator<T>& casacore::ReadOnlyMatrixIterator< T >::operator= (const ReadOnlyMatrixIterator< T > &) private delete
Not implemented.
template<class T > void casacore::ReadOnlyMatrixIterator< T >::origin () inline
Definition at line 114 of file MatrixIter.h.
References casacore::ReadOnlyMatrixIterator< T >::mi, and casacore::ArrayPositionIterator::origin().
template<class T > bool casacore::ReadOnlyMatrixIterator< T >::pastEnd () const inline
Definition at line 120 of file MatrixIter.h.
References casacore::ReadOnlyMatrixIterator< T >::mi, and casacore::ArrayPositionIterator::pastEnd().
template<class T > const IPosition& casacore::ReadOnlyMatrixIterator< T >::pos () const inline
Definition at line 121 of file MatrixIter.h.
References casacore::ReadOnlyMatrixIterator< T >::mi, and casacore::ArrayPositionIterator::pos().
template<class T > void casacore::ReadOnlyMatrixIterator< T >::reset () inline
Definition at line 113 of file MatrixIter.h.
References casacore::ReadOnlyMatrixIterator< T >::mi, and casacore::ArrayPositionIterator::origin().
Member Data Documentation
template<class T > MatrixIterator<T> casacore::ReadOnlyMatrixIterator< T >::mi private
Definition at line 131 of file MatrixIter.h.
Referenced by casacore::ReadOnlyMatrixIterator< T >::array(), casacore::ReadOnlyMatrixIterator< T >::atStart(), casacore::ReadOnlyMatrixIterator< T >::endPos(), casacore::ReadOnlyMatrixIterator< T >::matrix(), casacore::ReadOnlyMatrixIterator< T >::ndim(), casacore::ReadOnlyMatrixIterator< T >::next(), casacore::ReadOnlyMatrixIterator< T >::origin(), casacore::ReadOnlyMatrixIterator< T >::pastEnd(), casacore::ReadOnlyMatrixIterator< T >::pos(), and casacore::ReadOnlyMatrixIterator< T >::reset().
The documentation for this class was generated from the following file:
casa/Arrays/MatrixIter.h