casacore: casacore::ROMSWeatherColumns Class Reference
casacore::ROMSWeatherColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSWeather columns.
#include <MSWeatherColumns.h>
Public Member Functions
ROMSWeatherColumns (const MSWeather &msWeather)
Create a columns object that accesses the data in the specified Table.
~ROMSWeatherColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSWeather table is optional)
const ROScalarColumn< Int > & antennaId () const
Access to columns.
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Float > & dewPoint () const
Access to optional columns.
const ROScalarQuantColumn< Float > & dewPointQuant () const
const ROScalarColumn< Bool > & dewPointFlag () const
const ROScalarColumn< Float > & H2O () const
const ROScalarColumn< Bool > & H2OFlag () const
const ROScalarQuantColumn< Float > & H2OQuant () const
const ROScalarColumn< Float > & ionosElectron () const
const ROScalarQuantColumn< Float > & ionosElectronQuant () const
const ROScalarColumn< Bool > & ionosElectronFlag () const
const ROScalarColumn< Float > & pressure () const
const ROScalarQuantColumn< Float > & pressureQuant () const
const ROScalarColumn< Bool > & pressureFlag () const
const ROScalarColumn< Float > & relHumidity () const
const ROScalarColumn< Bool > & relHumidityFlag () const
const ROScalarColumn< Float > & temperature () const
const ROScalarQuantColumn< Float > & temperatureQuant () const
const ROScalarColumn< Bool > & temperatureFlag () const
const ROScalarColumn< Float > & windDirection () const
const ROScalarQuantColumn< Float > & windDirectionQuant () const
const ROScalarColumn< Bool > & windDirectionFlag () const
const ROScalarColumn< Float > & windSpeed () const
const ROScalarQuantColumn< Float > & windSpeedQuant () const
const ROScalarColumn< Bool > & windSpeedFlag () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSWeatherColumns ()
void attach (const MSWeather &msWeather)
Private Member Functions
ROMSWeatherColumns (const ROMSWeatherColumns &)
ROMSWeatherColumns & operator= (const ROMSWeatherColumns &)
void attachOptionalCols (const MSWeather &msWeather)
Private Attributes
Bool isNull_p
ROScalarColumn< Int > antennaId_p
ROScalarColumn< Double > interval_p
ROScalarColumn< Double > time_p
ROScalarColumn< Float > dewPoint_p
ROScalarColumn< Bool > dewPointFlag_p
ROScalarColumn< Float > H2O_p
ROScalarColumn< Bool > H2OFlag_p
ROScalarColumn< Float > ionosElectron_p
ROScalarColumn< Bool > ionosElectronFlag_p
ROScalarColumn< Float > pressure_p
ROScalarColumn< Bool > pressureFlag_p
ROScalarColumn< Float > relHumidity_p
ROScalarColumn< Bool > relHumidityFlag_p
ROScalarColumn< Float > temperature_p
ROScalarColumn< Bool > temperatureFlag_p
ROScalarColumn< Float > windDirection_p
ROScalarColumn< Bool > windDirectionFlag_p
ROScalarColumn< Float > windSpeed_p
ROScalarColumn< Bool > windSpeedFlag_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarQuantColumn< Double > intervalQuant_p
ROScalarQuantColumn< Double > timeQuant_p
ROScalarQuantColumn< Float > dewPointQuant_p
ROScalarQuantColumn< Float > H2OQuant_p
ROScalarQuantColumn< Float > ionosElectronQuant_p
ROScalarQuantColumn< Float > pressureQuant_p
ROScalarQuantColumn< Float > temperatureQuant_p
ROScalarQuantColumn< Float > windDirectionQuant_p
ROScalarQuantColumn< Float > windSpeedQuant_p
Detailed Description
A class to provide easy read-only access to MSWeather columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSWeather
ArrayColumn
ScalarColumn
Etymology
ROMSWeatherColumns stands for Read-Only MeasurementSet Weather Table columns.
Synopsis
This class provides read-only access to the columns in the MSWeather Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 76 of file MSWeatherColumns.h.
Constructor & Destructor Documentation
ROMSWeatherColumns() [1/3]
casacore::ROMSWeatherColumns::ROMSWeatherColumns (const MSWeather & msWeather)
Create a columns object that accesses the data in the specified Table.
~ROMSWeatherColumns()
casacore::ROMSWeatherColumns::~ROMSWeatherColumns ()
The destructor does nothing special.
ROMSWeatherColumns() [2/3]
casacore::ROMSWeatherColumns::ROMSWeatherColumns () protected
ROMSWeatherColumns() [3/3]
casacore::ROMSWeatherColumns::ROMSWeatherColumns (const ROMSWeatherColumns &) private
Member Function Documentation
antennaId()
const ROScalarColumn<Int>& casacore::ROMSWeatherColumns::antennaId () const inline
Access to columns.
Definition at line 90 of file MSWeatherColumns.h.
References antennaId_p.
Referenced by casacore::MSWeatherColumns::antennaId().
attach()
void casacore::ROMSWeatherColumns::attach (const MSWeather & msWeather) protected
attachOptionalCols()
void casacore::ROMSWeatherColumns::attachOptionalCols (const MSWeather & msWeather) private
dewPoint()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::dewPoint () const inline
Access to optional columns.
Definition at line 101 of file MSWeatherColumns.h.
References dewPoint_p.
Referenced by casacore::MSWeatherColumns::dewPoint().
dewPointFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::dewPointFlag () const inline
Definition at line 104 of file MSWeatherColumns.h.
References dewPointFlag_p.
Referenced by casacore::MSWeatherColumns::dewPointFlag().
dewPointQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSWeatherColumns::dewPointQuant () const inline
Definition at line 102 of file MSWeatherColumns.h.
References dewPointQuant_p.
Referenced by casacore::MSWeatherColumns::dewPointQuant().
H2O()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::H2O () const inline
Definition at line 105 of file MSWeatherColumns.h.
References H2O_p.
Referenced by casacore::MSWeatherColumns::H2O().
H2OFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::H2OFlag () const inline
Definition at line 106 of file MSWeatherColumns.h.
References H2OFlag_p.
Referenced by casacore::MSWeatherColumns::H2OFlag().
H2OQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSWeatherColumns::H2OQuant () const inline
Definition at line 107 of file MSWeatherColumns.h.
References H2OQuant_p.
Referenced by casacore::MSWeatherColumns::H2OQuant().
interval()
const ROScalarColumn<Double>& casacore::ROMSWeatherColumns::interval () const inline
Definition at line 91 of file MSWeatherColumns.h.
References interval_p.
Referenced by casacore::MSWeatherColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSWeatherColumns::intervalQuant () const inline
Definition at line 92 of file MSWeatherColumns.h.
References intervalQuant_p.
Referenced by casacore::MSWeatherColumns::intervalQuant().
ionosElectron()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::ionosElectron () const inline
Definition at line 108 of file MSWeatherColumns.h.
References ionosElectron_p.
Referenced by casacore::MSWeatherColumns::ionosElectron().
ionosElectronFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::ionosElectronFlag () const inline
Definition at line 111 of file MSWeatherColumns.h.
References ionosElectronFlag_p.
Referenced by casacore::MSWeatherColumns::ionosElectronFlag().
ionosElectronQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSWeatherColumns::ionosElectronQuant () const inline
Definition at line 109 of file MSWeatherColumns.h.
References ionosElectronQuant_p.
Referenced by casacore::MSWeatherColumns::ionosElectronQuant().
isNull()
Bool casacore::ROMSWeatherColumns::isNull () const inline
Is this object defined? (MSWeather table is optional)
Definition at line 86 of file MSWeatherColumns.h.
References isNull_p.
Referenced by nrow().
nrow()
uInt casacore::ROMSWeatherColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Returns zero if the object is null.
Definition at line 138 of file MSWeatherColumns.h.
References antennaId_p, and isNull().
operator=()
ROMSWeatherColumns& casacore::ROMSWeatherColumns::operator= (const ROMSWeatherColumns &) private
pressure()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::pressure () const inline
Definition at line 113 of file MSWeatherColumns.h.
References pressure_p.
Referenced by casacore::MSWeatherColumns::pressure().
pressureFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::pressureFlag () const inline
Definition at line 116 of file MSWeatherColumns.h.
References pressureFlag_p.
Referenced by casacore::MSWeatherColumns::pressureFlag().
pressureQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSWeatherColumns::pressureQuant () const inline
Definition at line 114 of file MSWeatherColumns.h.
References pressureQuant_p.
Referenced by casacore::MSWeatherColumns::pressureQuant().
relHumidity()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::relHumidity () const inline
Definition at line 117 of file MSWeatherColumns.h.
References relHumidity_p.
Referenced by casacore::MSWeatherColumns::relHumidity().
relHumidityFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::relHumidityFlag () const inline
Definition at line 118 of file MSWeatherColumns.h.
References relHumidityFlag_p.
Referenced by casacore::MSWeatherColumns::relHumidityFlag().
temperature()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::temperature () const inline
Definition at line 120 of file MSWeatherColumns.h.
References temperature_p.
Referenced by casacore::MSWeatherColumns::temperature().
temperatureFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::temperatureFlag () const inline
Definition at line 123 of file MSWeatherColumns.h.
References temperatureFlag_p.
Referenced by casacore::MSWeatherColumns::temperatureFlag().
temperatureQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSWeatherColumns::temperatureQuant () const inline
Definition at line 121 of file MSWeatherColumns.h.
References temperatureQuant_p.
Referenced by casacore::MSWeatherColumns::temperatureQuant().
time()
const ROScalarColumn<Double>& casacore::ROMSWeatherColumns::time () const inline
Definition at line 94 of file MSWeatherColumns.h.
References time_p.
Referenced by casacore::MSWeatherColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSWeatherColumns::timeMeas () const inline
Definition at line 96 of file MSWeatherColumns.h.
References timeMeas_p.
Referenced by casacore::MSWeatherColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSWeatherColumns::timeQuant () const inline
Definition at line 95 of file MSWeatherColumns.h.
References timeQuant_p.
Referenced by casacore::MSWeatherColumns::timeQuant().
windDirection()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::windDirection () const inline
Definition at line 125 of file MSWeatherColumns.h.
References windDirection_p.
Referenced by casacore::MSWeatherColumns::windDirection().
windDirectionFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::windDirectionFlag () const inline
Definition at line 128 of file MSWeatherColumns.h.
References windDirectionFlag_p.
Referenced by casacore::MSWeatherColumns::windDirectionFlag().
windDirectionQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSWeatherColumns::windDirectionQuant () const inline
Definition at line 126 of file MSWeatherColumns.h.
References windDirectionQuant_p.
Referenced by casacore::MSWeatherColumns::windDirectionQuant().
windSpeed()
const ROScalarColumn<Float>& casacore::ROMSWeatherColumns::windSpeed () const inline
Definition at line 130 of file MSWeatherColumns.h.
References windSpeed_p.
Referenced by casacore::MSWeatherColumns::windSpeed().
windSpeedFlag()
const ROScalarColumn<Bool>& casacore::ROMSWeatherColumns::windSpeedFlag () const inline
Definition at line 133 of file MSWeatherColumns.h.
References windSpeedFlag_p.
Referenced by casacore::MSWeatherColumns::windSpeedFlag().
windSpeedQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSWeatherColumns::windSpeedQuant () const inline
Definition at line 131 of file MSWeatherColumns.h.
References windSpeedQuant_p.
Referenced by casacore::MSWeatherColumns::windSpeedQuant().
Member Data Documentation
antennaId_p
ROScalarColumn<Int> casacore::ROMSWeatherColumns::antennaId_p private
Definition at line 161 of file MSWeatherColumns.h.
Referenced by antennaId(), and nrow().
dewPoint_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::dewPoint_p private
Definition at line 165 of file MSWeatherColumns.h.
Referenced by dewPoint().
dewPointFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::dewPointFlag_p private
Definition at line 166 of file MSWeatherColumns.h.
Referenced by dewPointFlag().
dewPointQuant_p
ROScalarQuantColumn<Float> casacore::ROMSWeatherColumns::dewPointQuant_p private
Definition at line 189 of file MSWeatherColumns.h.
Referenced by dewPointQuant().
H2O_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::H2O_p private
Definition at line 167 of file MSWeatherColumns.h.
Referenced by H2O().
H2OFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::H2OFlag_p private
Definition at line 168 of file MSWeatherColumns.h.
Referenced by H2OFlag().
H2OQuant_p
ROScalarQuantColumn<Float> casacore::ROMSWeatherColumns::H2OQuant_p private
Definition at line 190 of file MSWeatherColumns.h.
Referenced by H2OQuant().
interval_p
ROScalarColumn<Double> casacore::ROMSWeatherColumns::interval_p private
Definition at line 162 of file MSWeatherColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSWeatherColumns::intervalQuant_p private
Definition at line 186 of file MSWeatherColumns.h.
Referenced by intervalQuant().
ionosElectron_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::ionosElectron_p private
Definition at line 169 of file MSWeatherColumns.h.
Referenced by ionosElectron().
ionosElectronFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::ionosElectronFlag_p private
Definition at line 170 of file MSWeatherColumns.h.
Referenced by ionosElectronFlag().
ionosElectronQuant_p
ROScalarQuantColumn<Float> casacore::ROMSWeatherColumns::ionosElectronQuant_p private
Definition at line 191 of file MSWeatherColumns.h.
Referenced by ionosElectronQuant().
isNull_p
Bool casacore::ROMSWeatherColumns::isNull_p private
Definition at line 158 of file MSWeatherColumns.h.
Referenced by isNull().
pressure_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::pressure_p private
Definition at line 171 of file MSWeatherColumns.h.
Referenced by pressure().
pressureFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::pressureFlag_p private
Definition at line 172 of file MSWeatherColumns.h.
Referenced by pressureFlag().
pressureQuant_p
ROScalarQuantColumn<Float> casacore::ROMSWeatherColumns::pressureQuant_p private
Definition at line 192 of file MSWeatherColumns.h.
Referenced by pressureQuant().
relHumidity_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::relHumidity_p private
Definition at line 173 of file MSWeatherColumns.h.
Referenced by relHumidity().
relHumidityFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::relHumidityFlag_p private
Definition at line 174 of file MSWeatherColumns.h.
Referenced by relHumidityFlag().
temperature_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::temperature_p private
Definition at line 175 of file MSWeatherColumns.h.
Referenced by temperature().
temperatureFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::temperatureFlag_p private
Definition at line 176 of file MSWeatherColumns.h.
Referenced by temperatureFlag().
temperatureQuant_p
ROScalarQuantColumn<Float> casacore::ROMSWeatherColumns::temperatureQuant_p private
Definition at line 193 of file MSWeatherColumns.h.
Referenced by temperatureQuant().
time_p
ROScalarColumn<Double> casacore::ROMSWeatherColumns::time_p private
Definition at line 163 of file MSWeatherColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSWeatherColumns::timeMeas_p private
Definition at line 183 of file MSWeatherColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSWeatherColumns::timeQuant_p private
Definition at line 187 of file MSWeatherColumns.h.
Referenced by timeQuant().
windDirection_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::windDirection_p private
Definition at line 177 of file MSWeatherColumns.h.
Referenced by windDirection().
windDirectionFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::windDirectionFlag_p private
Definition at line 178 of file MSWeatherColumns.h.
Referenced by windDirectionFlag().
windDirectionQuant_p
ROScalarQuantColumn<Float> casacore::ROMSWeatherColumns::windDirectionQuant_p private
Definition at line 194 of file MSWeatherColumns.h.
Referenced by windDirectionQuant().
windSpeed_p
ROScalarColumn<Float> casacore::ROMSWeatherColumns::windSpeed_p private
Definition at line 179 of file MSWeatherColumns.h.
Referenced by windSpeed().
windSpeedFlag_p
ROScalarColumn<Bool> casacore::ROMSWeatherColumns::windSpeedFlag_p private
Definition at line 180 of file MSWeatherColumns.h.
Referenced by windSpeedFlag().
windSpeedQuant_p
ROScalarQuantColumn<Float> casacore::ROMSWeatherColumns::windSpeedQuant_p private
Definition at line 195 of file MSWeatherColumns.h.
Referenced by windSpeedQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSWeatherColumns.h