casacore: casacore::TableExprNodeIndex Class Reference
casacore::TableExprNodeIndex Class Reference
TaQL_module_internal_classes
The index of an array element in a table select expression.
#include <ExprNodeArray.h>
Public Member Functions
TableExprNodeIndex (const TableExprNodeSet &indices, const TaQLStyle &=TaQLStyle(0))
Constructor.
virtual ~TableExprNodeIndex ()
Destructor.
void fillIndex (const TableExprNodeSet &indices)
Link all the operands and check datatype.
void checkIndexValues (const TableExprNodeRep *arrayNode)
Check if the index values match the dimensionality and shape of fixed-shaped array.
const Slicer & getConstantSlicer () const
Get the Slicer value for a constant index.
const Slicer & getSlicer (const TableExprId &id)
Get the Slicer value for the slice.
Bool isSingle () const
Does it index a single element?
Public Member Functions inherited from casacore::TableExprNodeMulti
TableExprNodeMulti (NodeDataType, ValueType, OperType, const TableExprNodeRep &source)
Constructor.
virtual ~TableExprNodeMulti ()
Destructor.
virtual void show (ostream &, uInt indent) const
Show the expression tree.
virtual void getAggrNodes (vector< TableExprNodeRep * > &aggr)
Get the nodes representing an aggregate function.
virtual void getColumnNodes (vector< TableExprNodeRep * > &cols)
Get the nodes representing a table column.
const PtrBlock
< TableExprNodeRep * > & getChildren () const
Get the child nodes.
Public Member Functions inherited from casacore::TableExprNodeRep
TableExprNodeRep (NodeDataType, ValueType, OperType, ArgType, ExprType, Int ndim, const IPosition &shape, const Table &table)
Construct a node.
TableExprNodeRep (NodeDataType, ValueType, OperType, const Table &)
This constructor is called from the derived TableExprNodeRep.
TableExprNodeRep (const TableExprNodeRep &)
Copy constructor.
virtual ~TableExprNodeRep ()
The destructor deletes all the underlying TableExprNode objects.
TableExprNodeRep * link ()
Link to this object, i.e.
virtual void disableApplySelection ()
Do not apply the selection.
virtual void applySelection (const Vector< uInt > &rownrs)
Re-create the column object for a selection of rows.
virtual Double getUnitFactor () const
Get the unit conversion factor.
virtual CountedPtr
< TableExprGroupFuncBase > makeGroupAggrFunc ()
Create the correct immediate aggregate function object.
virtual Bool isLazyAggregate () const
Is the aggregate function a lazy or an immediate one? The default implementation returns True (because all UDF aggregate functions have to be lazy).
virtual Bool getBool (const TableExprId &id)
Get a scalar value for this node in the given row.
virtual Int64 getInt (const TableExprId &id)
virtual Double getDouble (const TableExprId &id)
virtual DComplex getDComplex (const TableExprId &id)
virtual String getString (const TableExprId &id)
virtual TaqlRegex getRegex (const TableExprId &id)
virtual MVTime getDate (const TableExprId &id)
virtual Array< Bool > getArrayBool (const TableExprId &id)
Get an array value for this node in the given row.
virtual Array< Int64 > getArrayInt (const TableExprId &id)
virtual Array< Double > getArrayDouble (const TableExprId &id)
virtual Array< DComplex > getArrayDComplex (const TableExprId &id)
virtual Array< String > getArrayString (const TableExprId &id)
virtual Array< MVTime > getArrayDate (const TableExprId &id)
void get (const TableExprId &id, Bool &value)
General get functions for template purposes.
void get (const TableExprId &id, Int64 &value)
void get (const TableExprId &id, Double &value)
void get (const TableExprId &id, DComplex &value)
void get (const TableExprId &id, MVTime &value)
void get (const TableExprId &id, String &value)
void get (const TableExprId &id, Array< Bool > &value)
void get (const TableExprId &id, Array< Int64 > &value)
void get (const TableExprId &id, Array< Double > &value)
void get (const TableExprId &id, Array< DComplex > &value)
void get (const TableExprId &id, Array< MVTime > &value)
void get (const TableExprId &id, Array< String > &value)
Array< Bool > getBoolAS (const TableExprId &id)
Get a value as an array, even it it is a scalar.
Array< Int64 > getIntAS (const TableExprId &id)
Array< Double > getDoubleAS (const TableExprId &id)
Array< DComplex > getDComplexAS (const TableExprId &id)
Array< String > getStringAS (const TableExprId &id)
Array< MVTime > getDateAS (const TableExprId &id)
virtual Bool hasBool (const TableExprId &id, Bool value)
Does a value occur in an array or set? The default implementation tests if it is in an array.
virtual Bool hasInt (const TableExprId &id, Int64 value)
virtual Bool hasDouble (const TableExprId &id, Double value)
virtual Bool hasDComplex (const TableExprId &id, const DComplex &value)
virtual Bool hasString (const TableExprId &id, const String &value)
virtual Bool hasDate (const TableExprId &id, const MVTime &value)
virtual Array< Bool > hasArrayBool (const TableExprId &id, const Array< Bool > &value)
virtual Array< Bool > hasArrayInt (const TableExprId &id, const Array< Int64 > &value)
virtual Array< Bool > hasArrayDouble (const TableExprId &id, const Array< Double > &value)
virtual Array< Bool > hasArrayDComplex (const TableExprId &id, const Array< DComplex > &value)
virtual Array< Bool > hasArrayString (const TableExprId &id, const Array< String > &value)
virtual Array< Bool > hasArrayDate (const TableExprId &id, const Array< MVTime > &value)
uInt nrow () const
Get the number of rows in the table associated with this expression.
virtual Bool getColumnDataType (DataType &) const
Get the data type of the column.
virtual Array< Bool > getColumnBool (const Vector< uInt > &rownrs)
Get the value of the expression evaluated for the entire column.
virtual Array< uChar > getColumnuChar (const Vector< uInt > &rownrs)
virtual Array< Short > getColumnShort (const Vector< uInt > &rownrs)
virtual Array< uShort > getColumnuShort (const Vector< uInt > &rownrs)
virtual Array< Int > getColumnInt (const Vector< uInt > &rownrs)
virtual Array< uInt > getColumnuInt (const Vector< uInt > &rownrs)
virtual Array< Float > getColumnFloat (const Vector< uInt > &rownrs)
virtual Array< Double > getColumnDouble (const Vector< uInt > &rownrs)
virtual Array< Complex > getColumnComplex (const Vector< uInt > &rownrs)
virtual Array< DComplex > getColumnDComplex (const Vector< uInt > &rownrs)
virtual Array< String > getColumnString (const Vector< uInt > &rownrs)
virtual void ranges (Block< TableExprRange > &)
Convert the tree to a number of range vectors which at least select the same things.
NodeDataType dataType () const
Get the data type of the derived TableExprNode object.
ValueType valueType () const
Get the value type.
void setValueType (ValueType vtype)
Set the value type.
OperType operType () const
Get the operator type.
ExprType exprType () const
Get the expression type.
Bool isConstant () const
Is the expression a constant?
const Unit & unit () const
Get the unit.
void setUnit (const Unit &unit)
Set the unit.
Int ndim () const
Get the fixed dimensionality (same for all rows).
const IPosition & shape () const
Get the fixed shape (same for all rows).
const IPosition & shape (const TableExprId &id)
Get the shape for the given row.
virtual Bool isDefined (const TableExprId &id)
Is the value in the given row defined? The default implementation returns True.
Table & table ()
Get table.
const Table & table () const
virtual void adaptSetUnits (const Unit &)
Let a set node convert itself to the given unit.
Protected Member Functions
void convertConstIndex ()
Precalculate the constant indices and store them.
void fillSlicer (const TableExprId &id)
Fill the slicer for this row.
IPosition getNodeShape (const TableExprNodeRep *arrayNode) const
Get the shape of the node involved.
Protected Attributes
Int origin_p
Int endMinus_p
Bool isCOrder_p
IPosition start_p
IPosition end_p
IPosition incr_p
Slicer slicer_p
Block< Bool > varIndex_p
Bool isSingle_p
Protected Attributes inherited from casacore::TableExprNodeMulti
PtrBlock< TableExprNodeRep * > operands_p
Protected Attributes inherited from casacore::TableExprNodeRep
uInt count_p
Table table_p
NodeDataType dtype_p
ValueType vtype_p
OperType optype_p
ArgType argtype_p
ExprType exprtype_p
Int ndim_p
IPosition shape_p
Unit unit_p
Additional Inherited Members
Public Types inherited from casacore::TableExprNodeRep
enum NodeDataType {
NTBool,
NTInt,
NTDouble,
NTComplex,
NTString,
NTRegex,
NTDate,
NTReal,
NTDouCom,
NTNumeric,
NTAny
}
Define the data types of a node.
enum ValueType {
VTScalar,
VTArray,
VTRecord,
VTSetElem,
VTSet,
VTIndex
}
Define the value types.
enum OperType {
OtPlus,
OtMinus,
OtTimes,
OtDivide,
OtModulo,
OtBitAnd,
OtBitOr,
OtBitXor,
OtBitNegate,
OtEQ,
OtGE,
OtGT,
OtNE,
OtIN,
OtAND,
OtOR,
OtNOT,
OtMIN,
OtColumn,
OtField,
OtLiteral,
OtFunc,
OtSlice,
OtUndef,
OtRownr,
OtRandom
}
Define the operator types.
enum ArgType {
NoArr,
ArrArr,
ArrSca,
ScaArr
}
Define the value types of the 2 arguments when arrays are involved.
enum ExprType {
Constant,
Variable
}
Define (sub-)expression type.
Static Public Member Functions inherited from casacore::TableExprNodeMulti
static uInt checkNumOfArg (uInt low, uInt high, const PtrBlock< TableExprNodeRep * > &nodes)
Check number of arguments low <= number_of_args <= high It throws an exception if wrong number of arguments.
static NodeDataType checkDT (Block< Int > &dtypeOper, NodeDataType dtIn, NodeDataType dtOut, const PtrBlock< TableExprNodeRep * > &nodes)
Check datatype of nodes and return output type.
Static Protected Member Functions inherited from casacore::TableExprNodeRep
static TableExprNodeRep * getRep (TableExprNode &)
Get pointer to REPresentation object.
static void checkTablePtr (Table &table, const TableExprNodeRep *node)
static void fillExprType (ExprType &, const TableExprNodeRep *node)
static TableExprNodeRep * convertNode (TableExprNodeRep *thisNode, Bool convertConstType)
When the node is constant, it is evaluated and replaced by the appropriate TableExprNodeConst object.
Detailed Description
The index of an array element in a table select expression.
Intended use:
Internal
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Prerequisite
TableExprNodeMulti
Etymology
TableExprNodeIndex is used to store an index. All the operands must be Int.
Synopsis
TableExprNodeIndex is a derivation of TableExprNodeMulti expression tree that represents an index.
Motivation
All operands of TableExprNodeIndex must be Int, therefore it is a derivation of TableExprNodeMulti.
To Do
to be filled in
Definition at line 709 of file ExprNodeArray.h.
Constructor & Destructor Documentation
casacore::TableExprNodeIndex::TableExprNodeIndex (const TableExprNodeSet & indices, const TaQLStyle & = TaQLStyle(0)) explicit
Constructor.
virtual casacore::TableExprNodeIndex::~TableExprNodeIndex () virtual
Destructor.
Member Function Documentation
void casacore::TableExprNodeIndex::checkIndexValues (const TableExprNodeRep * arrayNode)
Check if the index values match the dimensionality and shape of fixed-shaped array.
void casacore::TableExprNodeIndex::convertConstIndex () protected
Precalculate the constant indices and store them.
void casacore::TableExprNodeIndex::fillIndex (const TableExprNodeSet & indices)
Link all the operands and check datatype.
Calculate the IPosition values for the const operands.
void casacore::TableExprNodeIndex::fillSlicer (const TableExprId & id) protected
Fill the slicer for this row.
Referenced by getSlicer().
const Slicer & casacore::TableExprNodeIndex::getConstantSlicer () const inline
Get the Slicer value for a constant index.
Definition at line 842 of file ExprNodeArray.h.
References slicer_p.
IPosition casacore::TableExprNodeIndex::getNodeShape (const TableExprNodeRep * arrayNode) const protected
Get the shape of the node involved.
Reverse axes if needed.
const Slicer & casacore::TableExprNodeIndex::getSlicer (const TableExprId & id) inline
Get the Slicer value for the slice.
Definition at line 846 of file ExprNodeArray.h.
References fillSlicer(), casacore::TableExprNodeRep::isConstant(), and slicer_p.
Bool casacore::TableExprNodeIndex::isSingle () const inline
Does it index a single element?
Definition at line 838 of file ExprNodeArray.h.
References isSingle_p.
Member Data Documentation
IPosition casacore::TableExprNodeIndex::end_p protected
Definition at line 741 of file ExprNodeArray.h.
Int casacore::TableExprNodeIndex::endMinus_p protected
Definition at line 738 of file ExprNodeArray.h.
IPosition casacore::TableExprNodeIndex::incr_p protected
Definition at line 742 of file ExprNodeArray.h.
Bool casacore::TableExprNodeIndex::isCOrder_p protected
Definition at line 739 of file ExprNodeArray.h.
Bool casacore::TableExprNodeIndex::isSingle_p protected
Definition at line 745 of file ExprNodeArray.h.
Referenced by isSingle().
Int casacore::TableExprNodeIndex::origin_p protected
Definition at line 737 of file ExprNodeArray.h.
Slicer casacore::TableExprNodeIndex::slicer_p protected
Definition at line 743 of file ExprNodeArray.h.
Referenced by getConstantSlicer(), and getSlicer().
IPosition casacore::TableExprNodeIndex::start_p protected
Definition at line 740 of file ExprNodeArray.h.
Block<Bool> casacore::TableExprNodeIndex::varIndex_p protected
Definition at line 744 of file ExprNodeArray.h.
The documentation for this class was generated from the following file:
tables/TaQL/ExprNodeArray.h