casacore: casacore::ROMSSysCalColumns Class Reference
casacore::ROMSSysCalColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSSysCal columns.
#include <MSSysCalColumns.h>
Public Member Functions
ROMSSysCalColumns (const MSSysCal &msSysCal)
Create a columns object that accesses the data in the specified Table.
~ROMSSysCalColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSSysCal table is optional)
const ROScalarColumn< Int > & antennaId () const
Access to columns.
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Float > & phaseDiff () const
Access to optional columns.
const ROScalarQuantColumn< Float > & phaseDiffQuant () const
const ROScalarColumn< Bool > & phaseDiffFlag () const
const ROArrayColumn< Float > & tant () const
const ROArrayQuantColumn< Float > & tantQuant () const
const ROScalarColumn< Bool > & tantFlag () const
const ROArrayColumn< Float > & tantSpectrum () const
const ROArrayQuantColumn< Float > & tantSpectrumQuant () const
const ROArrayColumn< Float > & tantTsys () const
const ROScalarColumn< Bool > & tantTsysFlag () const
const ROArrayColumn< Float > & tantTsysSpectrum () const
const ROArrayColumn< Float > & tcal () const
const ROArrayQuantColumn< Float > & tcalQuant () const
const ROScalarColumn< Bool > & tcalFlag () const
const ROArrayColumn< Float > & tcalSpectrum () const
const ROArrayQuantColumn< Float > & tcalSpectrumQuant () const
const ROArrayColumn< Float > & trx () const
const ROArrayQuantColumn< Float > & trxQuant () const
const ROScalarColumn< Bool > & trxFlag () const
const ROArrayColumn< Float > & trxSpectrum () const
const ROArrayQuantColumn< Float > & trxSpectrumQuant () const
const ROArrayColumn< Float > & tsky () const
const ROArrayQuantColumn< Float > & tskyQuant () const
const ROScalarColumn< Bool > & tskyFlag () const
const ROArrayColumn< Float > & tskySpectrum () const
const ROArrayQuantColumn< Float > & tskySpectrumQuant () const
const ROArrayColumn< Float > & tsys () const
const ROArrayQuantColumn< Float > & tsysQuant () const
const ROScalarColumn< Bool > & tsysFlag () const
const ROArrayColumn< Float > & tsysSpectrum () const
const ROArrayQuantColumn< Float > & tsysSpectrumQuant () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSSysCalColumns ()
void attach (const MSSysCal &msSysCal)
Private Member Functions
ROMSSysCalColumns (const ROMSSysCalColumns &)
ROMSSysCalColumns & operator= (const ROMSSysCalColumns &)
void attachOptionalCols (const MSSysCal &msSysCal)
Private Attributes
Bool isNull_p
ROScalarColumn< Int > antennaId_p
ROScalarColumn< Int > feedId_p
ROScalarColumn< Double > interval_p
ROScalarColumn< Int > spectralWindowId_p
ROScalarColumn< Double > time_p
ROScalarColumn< Float > phaseDiff_p
ROScalarColumn< Bool > phaseDiffFlag_p
ROArrayColumn< Float > tant_p
ROScalarColumn< Bool > tantFlag_p
ROArrayColumn< Float > tantSpectrum_p
ROArrayColumn< Float > tantTsys_p
ROScalarColumn< Bool > tantTsysFlag_p
ROArrayColumn< Float > tantTsysSpectrum_p
ROArrayColumn< Float > tcal_p
ROScalarColumn< Bool > tcalFlag_p
ROArrayColumn< Float > tcalSpectrum_p
ROArrayColumn< Float > trx_p
ROScalarColumn< Bool > trxFlag_p
ROArrayColumn< Float > trxSpectrum_p
ROArrayColumn< Float > tsky_p
ROScalarColumn< Bool > tskyFlag_p
ROArrayColumn< Float > tskySpectrum_p
ROArrayColumn< Float > tsys_p
ROScalarColumn< Bool > tsysFlag_p
ROArrayColumn< Float > tsysSpectrum_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarQuantColumn< Double > intervalQuant_p
ROScalarQuantColumn< Double > timeQuant_p
ROScalarQuantColumn< Float > phaseDiffQuant_p
ROArrayQuantColumn< Float > tantQuant_p
ROArrayQuantColumn< Float > tantSpectrumQuant_p
ROArrayQuantColumn< Float > tcalQuant_p
ROArrayQuantColumn< Float > tcalSpectrumQuant_p
ROArrayQuantColumn< Float > trxQuant_p
ROArrayQuantColumn< Float > trxSpectrumQuant_p
ROArrayQuantColumn< Float > tskyQuant_p
ROArrayQuantColumn< Float > tskySpectrumQuant_p
ROArrayQuantColumn< Float > tsysQuant_p
ROArrayQuantColumn< Float > tsysSpectrumQuant_p
Detailed Description
A class to provide easy read-only access to MSSysCal columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSSysCal
ArrayColumn
ScalarColumn
Etymology
ROMSSysCalColumns stands for Read-Only MeasurementSet SysCal Table columns.
Synopsis
This class provides read-only access to the columns in the MSSysCal Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 78 of file MSSysCalColumns.h.
Constructor & Destructor Documentation
ROMSSysCalColumns() [1/3]
casacore::ROMSSysCalColumns::ROMSSysCalColumns (const MSSysCal & msSysCal)
Create a columns object that accesses the data in the specified Table.
~ROMSSysCalColumns()
casacore::ROMSSysCalColumns::~ROMSSysCalColumns ()
The destructor does nothing special.
ROMSSysCalColumns() [2/3]
casacore::ROMSSysCalColumns::ROMSSysCalColumns () protected
ROMSSysCalColumns() [3/3]
casacore::ROMSSysCalColumns::ROMSSysCalColumns (const ROMSSysCalColumns &) private
Member Function Documentation
antennaId()
const ROScalarColumn<Int>& casacore::ROMSSysCalColumns::antennaId () const inline
Access to columns.
Definition at line 92 of file MSSysCalColumns.h.
References antennaId_p.
Referenced by casacore::MSSysCalColumns::antennaId().
attach()
void casacore::ROMSSysCalColumns::attach (const MSSysCal & msSysCal) protected
attachOptionalCols()
void casacore::ROMSSysCalColumns::attachOptionalCols (const MSSysCal & msSysCal) private
feedId()
const ROScalarColumn<Int>& casacore::ROMSSysCalColumns::feedId () const inline
Definition at line 93 of file MSSysCalColumns.h.
References feedId_p.
Referenced by casacore::MSSysCalColumns::feedId().
interval()
const ROScalarColumn<Double>& casacore::ROMSSysCalColumns::interval () const inline
Definition at line 94 of file MSSysCalColumns.h.
References interval_p.
Referenced by casacore::MSSysCalColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSSysCalColumns::intervalQuant () const inline
Definition at line 95 of file MSSysCalColumns.h.
References intervalQuant_p.
Referenced by casacore::MSSysCalColumns::intervalQuant().
isNull()
Bool casacore::ROMSSysCalColumns::isNull () const inline
Is this object defined? (MSSysCal table is optional)
Definition at line 88 of file MSSysCalColumns.h.
References isNull_p.
Referenced by nrow().
nrow()
uInt casacore::ROMSSysCalColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Returns zero if the object is null.
Definition at line 148 of file MSSysCalColumns.h.
References antennaId_p, and isNull().
operator=()
ROMSSysCalColumns& casacore::ROMSSysCalColumns::operator= (const ROMSSysCalColumns &) private
phaseDiff()
const ROScalarColumn<Float>& casacore::ROMSSysCalColumns::phaseDiff () const inline
Access to optional columns.
Definition at line 106 of file MSSysCalColumns.h.
References phaseDiff_p.
Referenced by casacore::MSSysCalColumns::phaseDiff().
phaseDiffFlag()
const ROScalarColumn<Bool>& casacore::ROMSSysCalColumns::phaseDiffFlag () const inline
Definition at line 109 of file MSSysCalColumns.h.
References phaseDiffFlag_p.
Referenced by casacore::MSSysCalColumns::phaseDiffFlag().
phaseDiffQuant()
const ROScalarQuantColumn<Float>& casacore::ROMSSysCalColumns::phaseDiffQuant () const inline
Definition at line 107 of file MSSysCalColumns.h.
References phaseDiffQuant_p.
Referenced by casacore::MSSysCalColumns::phaseDiffQuant().
spectralWindowId()
const ROScalarColumn<Int>& casacore::ROMSSysCalColumns::spectralWindowId () const inline
Definition at line 97 of file MSSysCalColumns.h.
References spectralWindowId_p.
Referenced by casacore::MSSysCalColumns::spectralWindowId().
tant()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tant () const inline
Definition at line 110 of file MSSysCalColumns.h.
References tant_p.
Referenced by casacore::MSSysCalColumns::tant().
tantFlag()
const ROScalarColumn<Bool>& casacore::ROMSSysCalColumns::tantFlag () const inline
Definition at line 112 of file MSSysCalColumns.h.
References tantFlag_p.
Referenced by casacore::MSSysCalColumns::tantFlag().
tantQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tantQuant () const inline
Definition at line 111 of file MSSysCalColumns.h.
References tantQuant_p.
Referenced by casacore::MSSysCalColumns::tantQuant().
tantSpectrum()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tantSpectrum () const inline
Definition at line 113 of file MSSysCalColumns.h.
References tantSpectrum_p.
Referenced by casacore::MSSysCalColumns::tantSpectrum().
tantSpectrumQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tantSpectrumQuant () const inline
Definition at line 114 of file MSSysCalColumns.h.
References tantSpectrumQuant_p.
Referenced by casacore::MSSysCalColumns::tantSpectrumQuant().
tantTsys()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tantTsys () const inline
Definition at line 116 of file MSSysCalColumns.h.
References tantTsys_p.
Referenced by casacore::MSSysCalColumns::tantTsys().
tantTsysFlag()
const ROScalarColumn<Bool>& casacore::ROMSSysCalColumns::tantTsysFlag () const inline
Definition at line 117 of file MSSysCalColumns.h.
References tantTsysFlag_p.
Referenced by casacore::MSSysCalColumns::tantTsysFlag().
tantTsysSpectrum()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tantTsysSpectrum () const inline
Definition at line 118 of file MSSysCalColumns.h.
References tantTsysSpectrum_p.
Referenced by casacore::MSSysCalColumns::tantTsysSpectrum().
tcal()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tcal () const inline
Definition at line 120 of file MSSysCalColumns.h.
References tcal_p.
Referenced by casacore::MSSysCalColumns::tcal().
tcalFlag()
const ROScalarColumn<Bool>& casacore::ROMSSysCalColumns::tcalFlag () const inline
Definition at line 122 of file MSSysCalColumns.h.
References tcalFlag_p.
Referenced by casacore::MSSysCalColumns::tcalFlag().
tcalQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tcalQuant () const inline
Definition at line 121 of file MSSysCalColumns.h.
References tcalQuant_p.
Referenced by casacore::MSSysCalColumns::tcalQuant().
tcalSpectrum()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tcalSpectrum () const inline
Definition at line 123 of file MSSysCalColumns.h.
References tcalSpectrum_p.
Referenced by casacore::MSSysCalColumns::tcalSpectrum().
tcalSpectrumQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tcalSpectrumQuant () const inline
Definition at line 124 of file MSSysCalColumns.h.
References tcalSpectrumQuant_p.
Referenced by casacore::MSSysCalColumns::tcalSpectrumQuant().
time()
const ROScalarColumn<Double>& casacore::ROMSSysCalColumns::time () const inline
Definition at line 99 of file MSSysCalColumns.h.
References time_p.
Referenced by casacore::MSSysCalColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSSysCalColumns::timeMeas () const inline
Definition at line 101 of file MSSysCalColumns.h.
References timeMeas_p.
Referenced by casacore::MSSysCalColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSSysCalColumns::timeQuant () const inline
Definition at line 100 of file MSSysCalColumns.h.
References timeQuant_p.
Referenced by casacore::MSSysCalColumns::timeQuant().
trx()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::trx () const inline
Definition at line 126 of file MSSysCalColumns.h.
References trx_p.
Referenced by casacore::MSSysCalColumns::trx().
trxFlag()
const ROScalarColumn<Bool>& casacore::ROMSSysCalColumns::trxFlag () const inline
Definition at line 128 of file MSSysCalColumns.h.
References trxFlag_p.
Referenced by casacore::MSSysCalColumns::trxFlag().
trxQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::trxQuant () const inline
Definition at line 127 of file MSSysCalColumns.h.
References trxQuant_p.
Referenced by casacore::MSSysCalColumns::trxQuant().
trxSpectrum()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::trxSpectrum () const inline
Definition at line 129 of file MSSysCalColumns.h.
References trxSpectrum_p.
Referenced by casacore::MSSysCalColumns::trxSpectrum().
trxSpectrumQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::trxSpectrumQuant () const inline
Definition at line 130 of file MSSysCalColumns.h.
References trxSpectrumQuant_p.
Referenced by casacore::MSSysCalColumns::trxSpectrumQuant().
tsky()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tsky () const inline
Definition at line 132 of file MSSysCalColumns.h.
References tsky_p.
Referenced by casacore::MSSysCalColumns::tsky().
tskyFlag()
const ROScalarColumn<Bool>& casacore::ROMSSysCalColumns::tskyFlag () const inline
Definition at line 134 of file MSSysCalColumns.h.
References tskyFlag_p.
Referenced by casacore::MSSysCalColumns::tskyFlag().
tskyQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tskyQuant () const inline
Definition at line 133 of file MSSysCalColumns.h.
References tskyQuant_p.
Referenced by casacore::MSSysCalColumns::tskyQuant().
tskySpectrum()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tskySpectrum () const inline
Definition at line 135 of file MSSysCalColumns.h.
References tskySpectrum_p.
Referenced by casacore::MSSysCalColumns::tskySpectrum().
tskySpectrumQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tskySpectrumQuant () const inline
Definition at line 136 of file MSSysCalColumns.h.
References tskySpectrumQuant_p.
Referenced by casacore::MSSysCalColumns::tskySpectrumQuant().
tsys()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tsys () const inline
Definition at line 138 of file MSSysCalColumns.h.
References tsys_p.
Referenced by casacore::MSSysCalColumns::tsys().
tsysFlag()
const ROScalarColumn<Bool>& casacore::ROMSSysCalColumns::tsysFlag () const inline
Definition at line 140 of file MSSysCalColumns.h.
References tsysFlag_p.
Referenced by casacore::MSSysCalColumns::tsysFlag().
tsysQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tsysQuant () const inline
Definition at line 139 of file MSSysCalColumns.h.
References tsysQuant_p.
Referenced by casacore::MSSysCalColumns::tsysQuant().
tsysSpectrum()
const ROArrayColumn<Float>& casacore::ROMSSysCalColumns::tsysSpectrum () const inline
Definition at line 141 of file MSSysCalColumns.h.
References tsysSpectrum_p.
Referenced by casacore::MSSysCalColumns::tsysSpectrum().
tsysSpectrumQuant()
const ROArrayQuantColumn<Float>& casacore::ROMSSysCalColumns::tsysSpectrumQuant () const inline
Definition at line 142 of file MSSysCalColumns.h.
References tsysSpectrumQuant_p.
Referenced by casacore::MSSysCalColumns::tsysSpectrumQuant().
Member Data Documentation
antennaId_p
ROScalarColumn<Int> casacore::ROMSSysCalColumns::antennaId_p private
Definition at line 171 of file MSSysCalColumns.h.
Referenced by antennaId(), and nrow().
feedId_p
ROScalarColumn<Int> casacore::ROMSSysCalColumns::feedId_p private
Definition at line 172 of file MSSysCalColumns.h.
Referenced by feedId().
interval_p
ROScalarColumn<Double> casacore::ROMSSysCalColumns::interval_p private
Definition at line 173 of file MSSysCalColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSSysCalColumns::intervalQuant_p private
Definition at line 202 of file MSSysCalColumns.h.
Referenced by intervalQuant().
isNull_p
Bool casacore::ROMSSysCalColumns::isNull_p private
Definition at line 168 of file MSSysCalColumns.h.
Referenced by isNull().
phaseDiff_p
ROScalarColumn<Float> casacore::ROMSSysCalColumns::phaseDiff_p private
Definition at line 177 of file MSSysCalColumns.h.
Referenced by phaseDiff().
phaseDiffFlag_p
ROScalarColumn<Bool> casacore::ROMSSysCalColumns::phaseDiffFlag_p private
Definition at line 178 of file MSSysCalColumns.h.
Referenced by phaseDiffFlag().
phaseDiffQuant_p
ROScalarQuantColumn<Float> casacore::ROMSSysCalColumns::phaseDiffQuant_p private
Definition at line 205 of file MSSysCalColumns.h.
Referenced by phaseDiffQuant().
spectralWindowId_p
ROScalarColumn<Int> casacore::ROMSSysCalColumns::spectralWindowId_p private
Definition at line 174 of file MSSysCalColumns.h.
Referenced by spectralWindowId().
tant_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tant_p private
Definition at line 179 of file MSSysCalColumns.h.
Referenced by tant().
tantFlag_p
ROScalarColumn<Bool> casacore::ROMSSysCalColumns::tantFlag_p private
Definition at line 180 of file MSSysCalColumns.h.
Referenced by tantFlag().
tantQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tantQuant_p private
Definition at line 206 of file MSSysCalColumns.h.
Referenced by tantQuant().
tantSpectrum_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tantSpectrum_p private
Definition at line 181 of file MSSysCalColumns.h.
Referenced by tantSpectrum().
tantSpectrumQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tantSpectrumQuant_p private
Definition at line 207 of file MSSysCalColumns.h.
Referenced by tantSpectrumQuant().
tantTsys_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tantTsys_p private
Definition at line 182 of file MSSysCalColumns.h.
Referenced by tantTsys().
tantTsysFlag_p
ROScalarColumn<Bool> casacore::ROMSSysCalColumns::tantTsysFlag_p private
Definition at line 183 of file MSSysCalColumns.h.
Referenced by tantTsysFlag().
tantTsysSpectrum_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tantTsysSpectrum_p private
Definition at line 184 of file MSSysCalColumns.h.
Referenced by tantTsysSpectrum().
tcal_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tcal_p private
Definition at line 185 of file MSSysCalColumns.h.
Referenced by tcal().
tcalFlag_p
ROScalarColumn<Bool> casacore::ROMSSysCalColumns::tcalFlag_p private
Definition at line 186 of file MSSysCalColumns.h.
Referenced by tcalFlag().
tcalQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tcalQuant_p private
Definition at line 208 of file MSSysCalColumns.h.
Referenced by tcalQuant().
tcalSpectrum_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tcalSpectrum_p private
Definition at line 187 of file MSSysCalColumns.h.
Referenced by tcalSpectrum().
tcalSpectrumQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tcalSpectrumQuant_p private
Definition at line 209 of file MSSysCalColumns.h.
Referenced by tcalSpectrumQuant().
time_p
ROScalarColumn<Double> casacore::ROMSSysCalColumns::time_p private
Definition at line 175 of file MSSysCalColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSSysCalColumns::timeMeas_p private
Definition at line 199 of file MSSysCalColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSSysCalColumns::timeQuant_p private
Definition at line 203 of file MSSysCalColumns.h.
Referenced by timeQuant().
trx_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::trx_p private
Definition at line 188 of file MSSysCalColumns.h.
Referenced by trx().
trxFlag_p
ROScalarColumn<Bool> casacore::ROMSSysCalColumns::trxFlag_p private
Definition at line 189 of file MSSysCalColumns.h.
Referenced by trxFlag().
trxQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::trxQuant_p private
Definition at line 210 of file MSSysCalColumns.h.
Referenced by trxQuant().
trxSpectrum_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::trxSpectrum_p private
Definition at line 190 of file MSSysCalColumns.h.
Referenced by trxSpectrum().
trxSpectrumQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::trxSpectrumQuant_p private
Definition at line 211 of file MSSysCalColumns.h.
Referenced by trxSpectrumQuant().
tsky_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tsky_p private
Definition at line 191 of file MSSysCalColumns.h.
Referenced by tsky().
tskyFlag_p
ROScalarColumn<Bool> casacore::ROMSSysCalColumns::tskyFlag_p private
Definition at line 192 of file MSSysCalColumns.h.
Referenced by tskyFlag().
tskyQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tskyQuant_p private
Definition at line 212 of file MSSysCalColumns.h.
Referenced by tskyQuant().
tskySpectrum_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tskySpectrum_p private
Definition at line 193 of file MSSysCalColumns.h.
Referenced by tskySpectrum().
tskySpectrumQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tskySpectrumQuant_p private
Definition at line 213 of file MSSysCalColumns.h.
Referenced by tskySpectrumQuant().
tsys_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tsys_p private
Definition at line 194 of file MSSysCalColumns.h.
Referenced by tsys().
tsysFlag_p
ROScalarColumn<Bool> casacore::ROMSSysCalColumns::tsysFlag_p private
Definition at line 195 of file MSSysCalColumns.h.
Referenced by tsysFlag().
tsysQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tsysQuant_p private
Definition at line 214 of file MSSysCalColumns.h.
Referenced by tsysQuant().
tsysSpectrum_p
ROArrayColumn<Float> casacore::ROMSSysCalColumns::tsysSpectrum_p private
Definition at line 196 of file MSSysCalColumns.h.
Referenced by tsysSpectrum().
tsysSpectrumQuant_p
ROArrayQuantColumn<Float> casacore::ROMSSysCalColumns::tsysSpectrumQuant_p private
Definition at line 215 of file MSSysCalColumns.h.
Referenced by tsysSpectrumQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSSysCalColumns.h