casacore: casacore::HDF5HidDataSpace Class Reference
casacore::HDF5HidDataSpace Class Reference
casa package (libcasa_casa) » HDF5_module » HDF5_module_internal_classes
A class representing an HDF5 dataspace hid.
#include <HDF5HidMeta.h>
Public Member Functions
HDF5HidDataSpace ()
Default constructor sets hid to invalid.
HDF5HidDataSpace (hid_t hid)
Construct from given hid.
~HDF5HidDataSpace ()
The destructor closes the hid.
void close ()
Close the hid if valid.
void operator= (hid_t hid)
Put hid in it.
hid_t getHid () const
Get the hid.
operator hid_t () const
Convert automatically to hid_t.
Private Member Functions
HDF5HidDataSpace (const HDF5HidDataSpace &that)
Copy constructor cannot be used.
HDF5HidDataSpace & operator= (const HDF5HidDataSpace &that)
Assignment cannot be used.
Private Attributes
hid_t itsHid
Detailed Description
A class representing an HDF5 dataspace hid.
Intended use:
Internal
Review Status
Test programs:
tHDF5Dataset
Synopsis
This class wraps an HDF5 dataspace hid (hdf5 id). It offers two benefits:
The most important is resource management. In case of an exception, the hid will automatically be closed by the destructor.
A hid is a kind of pointer and should not be copied. These classes forbid making a copy, but make it possible to use them in a shared pointer context.
Definition at line 150 of file HDF5HidMeta.h.
Constructor & Destructor Documentation
HDF5HidDataSpace() [1/3]
casacore::HDF5HidDataSpace::HDF5HidDataSpace () inline
Default constructor sets hid to invalid.
Definition at line 154 of file HDF5HidMeta.h.
HDF5HidDataSpace() [2/3]
casacore::HDF5HidDataSpace::HDF5HidDataSpace (hid_t hid) inline
Construct from given hid.
Definition at line 157 of file HDF5HidMeta.h.
~HDF5HidDataSpace()
casacore::HDF5HidDataSpace::~HDF5HidDataSpace () inline
The destructor closes the hid.
Definition at line 160 of file HDF5HidMeta.h.
References close().
HDF5HidDataSpace() [3/3]
casacore::HDF5HidDataSpace::HDF5HidDataSpace (const HDF5HidDataSpace & that) private
Copy constructor cannot be used.
Member Function Documentation
close()
void casacore::HDF5HidDataSpace::close ()
Close the hid if valid.
Referenced by operator=(), and ~HDF5HidDataSpace().
getHid()
hid_t casacore::HDF5HidDataSpace::getHid () const inline
Get the hid.
Definition at line 168 of file HDF5HidMeta.h.
References itsHid.
operator hid_t()
casacore::HDF5HidDataSpace::operator hid_t () const inline
Convert automatically to hid_t.
Definition at line 171 of file HDF5HidMeta.h.
References itsHid.
operator=() [1/2]
void casacore::HDF5HidDataSpace::operator= (hid_t hid) inline
Put hid in it.
If it already contains a hid, it will be closed.
Definition at line 165 of file HDF5HidMeta.h.
References close(), and itsHid.
operator=() [2/2]
HDF5HidDataSpace& casacore::HDF5HidDataSpace::operator= (const HDF5HidDataSpace & that) private
Assignment cannot be used.
Member Data Documentation
itsHid
hid_t casacore::HDF5HidDataSpace::itsHid private
Definition at line 179 of file HDF5HidMeta.h.
Referenced by getHid(), operator hid_t(), and operator=().
The documentation for this class was generated from the following file:
casa/HDF5/HDF5HidMeta.h