casacore: casacore::ROMSFeedColumns Class Reference
casacore::ROMSFeedColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSFeed columns.
#include <MSFeedColumns.h>
Public Member Functions
ROMSFeedColumns (const MSFeed &msFeed)
Create a columns object that accesses the data in the specified Table.
~ROMSFeedColumns ()
The destructor does nothing special.
const ROScalarColumn< Int > & antennaId () const
Access to required columns.
const ROScalarColumn< Int > & beamId () const
const ROArrayColumn< Double > & beamOffset () const
const ROArrayQuantColumn< Double > & beamOffsetQuant () const
const ROArrayMeasColumn< MDirection > & beamOffsetMeas () const
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & numReceptors () const
const ROArrayColumn< Complex > & polResponse () const
const ROArrayColumn< String > & polarizationType () const
const ROArrayColumn< Double > & position () const
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROArrayColumn< Double > & receptorAngle () const
const ROArrayQuantColumn< Double > & receptorAngleQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & focusLength () const
Access to optional columns.
const ROScalarQuantColumn< Double > & focusLengthQuant () const
const ROScalarColumn< Int > & phasedFeedId () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int matchFeed (Quantum< Double > &newTimeQ, Quantum< Double > &newIntervalQ, const Int &antId, const Int &fId, const Int &spwId, const Quantum< Double > &timeQ, const Quantum< Double > &intervalQ, const Int &numRec, const Array< Quantum< Double > > &beamOffsetQ, const Array< String > &polType, const Array< Complex > &polResp, const Array< Quantum< Double > > &positionQ, const Array< Quantum< Double > > &receptorAngleQ, const Vector< uInt > &ignoreRows, const Quantum< Double > &focusLengthQ=Quantum< Double >())
Returns the last row that contains a feed with the specified values.
Protected Member Functions
ROMSFeedColumns ()
void attach (const MSFeed &msFeed)
Private Member Functions
ROMSFeedColumns (const ROMSFeedColumns &)
ROMSFeedColumns & operator= (const ROMSFeedColumns &)
void attachOptionalCols (const MSFeed &msFeed)
Private Attributes
ROScalarColumn< Int > antennaId_p
ROScalarColumn< Int > beamId_p
ROArrayColumn< Double > beamOffset_p
ROScalarColumn< Int > feedId_p
ROScalarColumn< Double > interval_p
ROScalarColumn< Int > numReceptors_p
ROArrayColumn< Complex > polResponse_p
ROArrayColumn< String > polarizationType_p
ROArrayColumn< Double > position_p
ROArrayColumn< Double > receptorAngle_p
ROScalarColumn< Int > spectralWindowId_p
ROScalarColumn< Double > time_p
ROScalarColumn< Double > focusLength_p
ROScalarColumn< Int > phasedFeedId_p
ROArrayMeasColumn< MDirection > beamOffsetMeas_p
Access to Measure columns.
ROScalarMeasColumn< MPosition > positionMeas_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROArrayQuantColumn< Double > beamOffsetQuant_p
Access to Quantum columns.
ROScalarQuantColumn< Double > intervalQuant_p
ROArrayQuantColumn< Double > positionQuant_p
ROArrayQuantColumn< Double > receptorAngleQuant_p
ROScalarQuantColumn< Double > timeQuant_p
ROScalarQuantColumn< Double > focusLengthQuant_p
Detailed Description
A class to provide easy read-only access to MSFeed columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSFeed
ArrayColumn
ScalarColumn
Etymology
ROMSFeedColumns stands for Read-Only MeasurementSet Feed Table columns.
Synopsis
This class provides read-only access to the columns in the MSFeed Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 84 of file MSFeedColumns.h.
Constructor & Destructor Documentation
ROMSFeedColumns() [1/3]
casacore::ROMSFeedColumns::ROMSFeedColumns (const MSFeed & msFeed)
Create a columns object that accesses the data in the specified Table.
~ROMSFeedColumns()
casacore::ROMSFeedColumns::~ROMSFeedColumns ()
The destructor does nothing special.
ROMSFeedColumns() [2/3]
casacore::ROMSFeedColumns::ROMSFeedColumns () protected
ROMSFeedColumns() [3/3]
casacore::ROMSFeedColumns::ROMSFeedColumns (const ROMSFeedColumns &) private
Member Function Documentation
antennaId()
const ROScalarColumn<Int>& casacore::ROMSFeedColumns::antennaId () const inline
Access to required columns.
Definition at line 95 of file MSFeedColumns.h.
References antennaId_p.
Referenced by casacore::MSFeedColumns::antennaId().
attach()
void casacore::ROMSFeedColumns::attach (const MSFeed & msFeed) protected
attachOptionalCols()
void casacore::ROMSFeedColumns::attachOptionalCols (const MSFeed & msFeed) private
beamId()
const ROScalarColumn<Int>& casacore::ROMSFeedColumns::beamId () const inline
Definition at line 96 of file MSFeedColumns.h.
References beamId_p.
Referenced by casacore::MSFeedColumns::beamId().
beamOffset()
const ROArrayColumn<Double>& casacore::ROMSFeedColumns::beamOffset () const inline
Definition at line 97 of file MSFeedColumns.h.
References beamOffset_p.
Referenced by casacore::MSFeedColumns::beamOffset().
beamOffsetMeas()
const ROArrayMeasColumn<MDirection>& casacore::ROMSFeedColumns::beamOffsetMeas () const inline
Definition at line 100 of file MSFeedColumns.h.
References beamOffsetMeas_p.
Referenced by casacore::MSFeedColumns::beamOffsetMeas().
beamOffsetQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSFeedColumns::beamOffsetQuant () const inline
Definition at line 98 of file MSFeedColumns.h.
References beamOffsetQuant_p.
Referenced by casacore::MSFeedColumns::beamOffsetQuant().
feedId()
const ROScalarColumn<Int>& casacore::ROMSFeedColumns::feedId () const inline
Definition at line 102 of file MSFeedColumns.h.
References feedId_p.
Referenced by casacore::MSFeedColumns::feedId().
focusLength()
const ROScalarColumn<Double>& casacore::ROMSFeedColumns::focusLength () const inline
Access to optional columns.
Definition at line 128 of file MSFeedColumns.h.
References focusLength_p.
Referenced by casacore::MSFeedColumns::focusLength().
focusLengthQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFeedColumns::focusLengthQuant () const inline
Definition at line 129 of file MSFeedColumns.h.
References focusLengthQuant_p.
Referenced by casacore::MSFeedColumns::focusLengthQuant().
interval()
const ROScalarColumn<Double>& casacore::ROMSFeedColumns::interval () const inline
Definition at line 103 of file MSFeedColumns.h.
References interval_p.
Referenced by casacore::MSFeedColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFeedColumns::intervalQuant () const inline
Definition at line 104 of file MSFeedColumns.h.
References intervalQuant_p.
Referenced by casacore::MSFeedColumns::intervalQuant().
matchFeed()
Int casacore::ROMSFeedColumns::matchFeed (Quantum< Double > & newTimeQ, Quantum< Double > & newIntervalQ, const Int & antId, const Int & fId, const Int & spwId, const Quantum< Double > & timeQ, const Quantum< Double > & intervalQ, const Int & numRec, const Array< Quantum< Double > > & beamOffsetQ, const Array< String > & polType, const Array< Complex > & polResp, const Array< Quantum< Double > > & positionQ, const Array< Quantum< Double > > & receptorAngleQ, const Vector< uInt > & ignoreRows, const Quantum< Double > & focusLengthQ = Quantum< Double >())
Returns the last row that contains a feed with the specified values.
If no matching row can be found, but a match is possible if the validity time interval is widened, return that row and the suggestion for the new time information. If no change to time is necessary, newTimeQ and newIntervalQ are zero. Returns -1 if no match could be found. Ignore the Feed table rows contained in vector ignoreRows. focusLengthQ is only compared if this optional column is present and if the value of focusLengthQ is not dimensionless.
nrow()
uInt casacore::ROMSFeedColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 135 of file MSFeedColumns.h.
References antennaId_p.
numReceptors()
const ROScalarColumn<Int>& casacore::ROMSFeedColumns::numReceptors () const inline
Definition at line 106 of file MSFeedColumns.h.
References numReceptors_p.
Referenced by casacore::MSFeedColumns::numReceptors().
operator=()
ROMSFeedColumns& casacore::ROMSFeedColumns::operator= (const ROMSFeedColumns &) private
phasedFeedId()
const ROScalarColumn<Int>& casacore::ROMSFeedColumns::phasedFeedId () const inline
Definition at line 131 of file MSFeedColumns.h.
References phasedFeedId_p.
Referenced by casacore::MSFeedColumns::phasedFeedId().
polarizationType()
const ROArrayColumn<String>& casacore::ROMSFeedColumns::polarizationType () const inline
Definition at line 108 of file MSFeedColumns.h.
References polarizationType_p.
Referenced by casacore::MSFeedColumns::polarizationType().
polResponse()
const ROArrayColumn<Complex>& casacore::ROMSFeedColumns::polResponse () const inline
Definition at line 107 of file MSFeedColumns.h.
References polResponse_p.
Referenced by casacore::MSFeedColumns::polResponse().
position()
const ROArrayColumn<Double>& casacore::ROMSFeedColumns::position () const inline
Definition at line 110 of file MSFeedColumns.h.
References position_p.
Referenced by casacore::MSFeedColumns::position().
positionMeas()
const ROScalarMeasColumn<MPosition>& casacore::ROMSFeedColumns::positionMeas () const inline
Definition at line 113 of file MSFeedColumns.h.
References positionMeas_p.
Referenced by casacore::MSFeedColumns::positionMeas().
positionQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSFeedColumns::positionQuant () const inline
Definition at line 111 of file MSFeedColumns.h.
References positionQuant_p.
Referenced by casacore::MSFeedColumns::positionQuant().
receptorAngle()
const ROArrayColumn<Double>& casacore::ROMSFeedColumns::receptorAngle () const inline
Definition at line 115 of file MSFeedColumns.h.
References receptorAngle_p.
Referenced by casacore::MSFeedColumns::receptorAngle().
receptorAngleQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSFeedColumns::receptorAngleQuant () const inline
Definition at line 116 of file MSFeedColumns.h.
References receptorAngleQuant_p.
Referenced by casacore::MSFeedColumns::receptorAngleQuant().
spectralWindowId()
const ROScalarColumn<Int>& casacore::ROMSFeedColumns::spectralWindowId () const inline
Definition at line 118 of file MSFeedColumns.h.
References spectralWindowId_p.
Referenced by casacore::MSFeedColumns::spectralWindowId().
time()
const ROScalarColumn<Double>& casacore::ROMSFeedColumns::time () const inline
Definition at line 120 of file MSFeedColumns.h.
References time_p.
Referenced by casacore::MSFeedColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSFeedColumns::timeMeas () const inline
Definition at line 123 of file MSFeedColumns.h.
References timeMeas_p.
Referenced by casacore::MSFeedColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSFeedColumns::timeQuant () const inline
Definition at line 121 of file MSFeedColumns.h.
References timeQuant_p.
Referenced by casacore::MSFeedColumns::timeQuant().
Member Data Documentation
antennaId_p
ROScalarColumn<Int> casacore::ROMSFeedColumns::antennaId_p private
Definition at line 181 of file MSFeedColumns.h.
Referenced by antennaId(), and nrow().
beamId_p
ROScalarColumn<Int> casacore::ROMSFeedColumns::beamId_p private
Definition at line 182 of file MSFeedColumns.h.
Referenced by beamId().
beamOffset_p
ROArrayColumn<Double> casacore::ROMSFeedColumns::beamOffset_p private
Definition at line 183 of file MSFeedColumns.h.
Referenced by beamOffset().
beamOffsetMeas_p
ROArrayMeasColumn<MDirection> casacore::ROMSFeedColumns::beamOffsetMeas_p private
Access to Measure columns.
Definition at line 198 of file MSFeedColumns.h.
Referenced by beamOffsetMeas().
beamOffsetQuant_p
ROArrayQuantColumn<Double> casacore::ROMSFeedColumns::beamOffsetQuant_p private
Access to Quantum columns.
Definition at line 203 of file MSFeedColumns.h.
Referenced by beamOffsetQuant().
feedId_p
ROScalarColumn<Int> casacore::ROMSFeedColumns::feedId_p private
Definition at line 184 of file MSFeedColumns.h.
Referenced by feedId().
focusLength_p
ROScalarColumn<Double> casacore::ROMSFeedColumns::focusLength_p private
Definition at line 194 of file MSFeedColumns.h.
Referenced by focusLength().
focusLengthQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFeedColumns::focusLengthQuant_p private
Definition at line 209 of file MSFeedColumns.h.
Referenced by focusLengthQuant().
interval_p
ROScalarColumn<Double> casacore::ROMSFeedColumns::interval_p private
Definition at line 185 of file MSFeedColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFeedColumns::intervalQuant_p private
Definition at line 204 of file MSFeedColumns.h.
Referenced by intervalQuant().
numReceptors_p
ROScalarColumn<Int> casacore::ROMSFeedColumns::numReceptors_p private
Definition at line 186 of file MSFeedColumns.h.
Referenced by numReceptors().
phasedFeedId_p
ROScalarColumn<Int> casacore::ROMSFeedColumns::phasedFeedId_p private
Definition at line 195 of file MSFeedColumns.h.
Referenced by phasedFeedId().
polarizationType_p
ROArrayColumn<String> casacore::ROMSFeedColumns::polarizationType_p private
Definition at line 188 of file MSFeedColumns.h.
Referenced by polarizationType().
polResponse_p
ROArrayColumn<Complex> casacore::ROMSFeedColumns::polResponse_p private
Definition at line 187 of file MSFeedColumns.h.
Referenced by polResponse().
position_p
ROArrayColumn<Double> casacore::ROMSFeedColumns::position_p private
Definition at line 189 of file MSFeedColumns.h.
Referenced by position().
positionMeas_p
ROScalarMeasColumn<MPosition> casacore::ROMSFeedColumns::positionMeas_p private
Definition at line 199 of file MSFeedColumns.h.
Referenced by positionMeas().
positionQuant_p
ROArrayQuantColumn<Double> casacore::ROMSFeedColumns::positionQuant_p private
Definition at line 205 of file MSFeedColumns.h.
Referenced by positionQuant().
receptorAngle_p
ROArrayColumn<Double> casacore::ROMSFeedColumns::receptorAngle_p private
Definition at line 190 of file MSFeedColumns.h.
Referenced by receptorAngle().
receptorAngleQuant_p
ROArrayQuantColumn<Double> casacore::ROMSFeedColumns::receptorAngleQuant_p private
Definition at line 206 of file MSFeedColumns.h.
Referenced by receptorAngleQuant().
spectralWindowId_p
ROScalarColumn<Int> casacore::ROMSFeedColumns::spectralWindowId_p private
Definition at line 191 of file MSFeedColumns.h.
Referenced by spectralWindowId().
time_p
ROScalarColumn<Double> casacore::ROMSFeedColumns::time_p private
Definition at line 192 of file MSFeedColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSFeedColumns::timeMeas_p private
Definition at line 200 of file MSFeedColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSFeedColumns::timeQuant_p private
Definition at line 207 of file MSFeedColumns.h.
Referenced by timeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSFeedColumns.h