casacore: casacore::MSDataDescColumns Class Reference
casacore::MSDataDescColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSDataDescription columns.
#include <MSDataDescColumns.h>
Public Member Functions
MSDataDescColumns (MSDataDescription &msDataDesc)
Create a columns object that accesses the data in the specified Table.
~MSDataDescColumns ()
The destructor does nothing special.
ScalarColumn< Bool > & flagRow ()
Read-write access to required columns.
ScalarColumn< Int > & polarizationId ()
ScalarColumn< Int > & spectralWindowId ()
ScalarColumn< Int > & lagId ()
read-write access to optional columns
const ROScalarColumn< Bool > & flagRow () const
Read-only access to required columns.
const ROScalarColumn< Int > & polarizationId () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Int > & lagId () const
Read-only access to optional columns.
Public Member Functions inherited from casacore::ROMSDataDescColumns
ROMSDataDescColumns (const MSDataDescription &msDataDesc)
Create a columns object that accesses the data in the specified Table.
~ROMSDataDescColumns ()
The destructor does nothing special.
const ROScalarColumn< Bool > & flagRow () const
Access to required columns.
const ROScalarColumn< Int > & polarizationId () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Int > & lagId () const
Access to optional columns.
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int match (uInt spwId, uInt polId, Int tryRow=-1)
returns the last row that contains the specified entries in the SPECTRAL_WINDOW_ID & POLARIZATION_ID columns.
Protected Member Functions
MSDataDescColumns ()
void attach (MSDataDescription &msDataDesc)
Protected Member Functions inherited from casacore::ROMSDataDescColumns
ROMSDataDescColumns ()
void attach (const MSDataDescription &msDataDesc)
Private Member Functions
MSDataDescColumns (const MSDataDescColumns &)
MSDataDescColumns & operator= (const MSDataDescColumns &)
void attachOptionalCols (MSDataDescription &msDataDesc)
Private Attributes
ScalarColumn< Bool > flagRow_p
ScalarColumn< Int > polarizationId_p
ScalarColumn< Int > spectralWindowId_p
ScalarColumn< Int > lagId_p
Detailed Description
A class to provide easy read-write access to MSDataDescription columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSDataDesc
ScalarColumn
Etymology
MSDataDescColumns stands for MeasurementSet DataDescription Table columns.
Synopsis
This class provides access to the columns in the MSDataDesc Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Warning: The Table that is used to construct this class must not be destroyed (or go out of scope) before this class does; Otherwise the scalar and array columns use by this class will be left dangling;
Motivation
See MSColumns for the motivation.
Definition at line 168 of file MSDataDescColumns.h.
Constructor & Destructor Documentation
MSDataDescColumns() [1/3]
casacore::MSDataDescColumns::MSDataDescColumns (MSDataDescription & msDataDesc)
Create a columns object that accesses the data in the specified Table.
~MSDataDescColumns()
casacore::MSDataDescColumns::~MSDataDescColumns ()
The destructor does nothing special.
MSDataDescColumns() [2/3]
casacore::MSDataDescColumns::MSDataDescColumns () protected
MSDataDescColumns() [3/3]
casacore::MSDataDescColumns::MSDataDescColumns (const MSDataDescColumns &) private
Member Function Documentation
attach()
void casacore::MSDataDescColumns::attach (MSDataDescription & msDataDesc) protected
attachOptionalCols()
void casacore::MSDataDescColumns::attachOptionalCols (MSDataDescription & msDataDesc) private
flagRow() [1/2]
ScalarColumn<Bool>& casacore::MSDataDescColumns::flagRow () inline
Read-write access to required columns.
Definition at line 179 of file MSDataDescColumns.h.
References flagRow_p.
flagRow() [2/2]
const ROScalarColumn<Bool>& casacore::MSDataDescColumns::flagRow () const inline
Read-only access to required columns.
Definition at line 191 of file MSDataDescColumns.h.
References casacore::ROMSDataDescColumns::flagRow().
lagId() [1/2]
ScalarColumn<Int>& casacore::MSDataDescColumns::lagId () inline
read-write access to optional columns
Definition at line 186 of file MSDataDescColumns.h.
References lagId_p.
lagId() [2/2]
const ROScalarColumn<Int>& casacore::MSDataDescColumns::lagId () const inline
Read-only access to optional columns.
Definition at line 201 of file MSDataDescColumns.h.
References casacore::ROMSDataDescColumns::lagId().
operator=()
MSDataDescColumns& casacore::MSDataDescColumns::operator= (const MSDataDescColumns &) private
polarizationId() [1/2]
ScalarColumn<Int>& casacore::MSDataDescColumns::polarizationId () inline
Definition at line 180 of file MSDataDescColumns.h.
References polarizationId_p.
polarizationId() [2/2]
const ROScalarColumn<Int>& casacore::MSDataDescColumns::polarizationId () const inline
Definition at line 193 of file MSDataDescColumns.h.
References casacore::ROMSDataDescColumns::polarizationId().
spectralWindowId() [1/2]
ScalarColumn<Int>& casacore::MSDataDescColumns::spectralWindowId () inline
Definition at line 181 of file MSDataDescColumns.h.
References spectralWindowId_p.
spectralWindowId() [2/2]
const ROScalarColumn<Int>& casacore::MSDataDescColumns::spectralWindowId () const inline
Definition at line 195 of file MSDataDescColumns.h.
References casacore::ROMSDataDescColumns::spectralWindowId().
Member Data Documentation
flagRow_p
ScalarColumn<Bool> casacore::MSDataDescColumns::flagRow_p private
Definition at line 223 of file MSDataDescColumns.h.
Referenced by flagRow().
lagId_p
ScalarColumn<Int> casacore::MSDataDescColumns::lagId_p private
Definition at line 227 of file MSDataDescColumns.h.
Referenced by lagId().
polarizationId_p
ScalarColumn<Int> casacore::MSDataDescColumns::polarizationId_p private
Definition at line 224 of file MSDataDescColumns.h.
Referenced by polarizationId().
spectralWindowId_p
ScalarColumn<Int> casacore::MSDataDescColumns::spectralWindowId_p private
Definition at line 225 of file MSDataDescColumns.h.
Referenced by spectralWindowId().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSDataDescColumns.h