casacore: casacore::ROMSHistoryColumns Class Reference
casacore::ROMSHistoryColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSHistory columns.
#include <MSHistoryColumns.h>
Public Member Functions
ROMSHistoryColumns (const MSHistory &msHistory)
Create a columns object that accesses the data in the specified Table.
~ROMSHistoryColumns ()
The destructor does nothing special.
const ROScalarColumn< String > & application () const
Access to required columns.
const ROArrayColumn< String > & appParams () const
const ROArrayColumn< String > & cliCommand () const
const ROScalarColumn< String > & message () const
const ROScalarColumn< Int > & objectId () const
const ROScalarColumn< Int > & observationId () const
const ROScalarColumn< String > & origin () const
const ROScalarColumn< String > & priority () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSHistoryColumns ()
void attach (const MSHistory &msHistory)
Private Member Functions
ROMSHistoryColumns (const ROMSHistoryColumns &)
ROMSHistoryColumns & operator= (const ROMSHistoryColumns &)
Private Attributes
ROScalarColumn< String > application_p
ROArrayColumn< String > appParams_p
ROArrayColumn< String > cliCommand_p
ROScalarColumn< String > message_p
ROScalarColumn< Int > objectId_p
ROScalarColumn< Int > observationId_p
ROScalarColumn< String > origin_p
ROScalarColumn< String > priority_p
ROScalarColumn< Double > time_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarQuantColumn< Double > timeQuant_p
Detailed Description
A class to provide easy read-only access to MSHistory columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSHistory
ArrayColumn
ScalarColumn
Etymology
ROMSHistoryColumns stands for Read-Only MeasurementSet History Table columns.
Synopsis
This class provides read-only access to the columns in the MSHistory Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 76 of file MSHistoryColumns.h.
Constructor & Destructor Documentation
ROMSHistoryColumns() [1/3]
casacore::ROMSHistoryColumns::ROMSHistoryColumns (const MSHistory & msHistory)
Create a columns object that accesses the data in the specified Table.
~ROMSHistoryColumns()
casacore::ROMSHistoryColumns::~ROMSHistoryColumns ()
The destructor does nothing special.
ROMSHistoryColumns() [2/3]
casacore::ROMSHistoryColumns::ROMSHistoryColumns () protected
ROMSHistoryColumns() [3/3]
casacore::ROMSHistoryColumns::ROMSHistoryColumns (const ROMSHistoryColumns &) private
Member Function Documentation
application()
const ROScalarColumn<String>& casacore::ROMSHistoryColumns::application () const inline
Access to required columns.
Definition at line 87 of file MSHistoryColumns.h.
References application_p.
Referenced by casacore::MSHistoryColumns::application().
appParams()
const ROArrayColumn<String>& casacore::ROMSHistoryColumns::appParams () const inline
Definition at line 88 of file MSHistoryColumns.h.
References appParams_p.
Referenced by casacore::MSHistoryColumns::appParams().
attach()
void casacore::ROMSHistoryColumns::attach (const MSHistory & msHistory) protected
cliCommand()
const ROArrayColumn<String>& casacore::ROMSHistoryColumns::cliCommand () const inline
Definition at line 89 of file MSHistoryColumns.h.
References cliCommand_p.
Referenced by casacore::MSHistoryColumns::cliCommand().
message()
const ROScalarColumn<String>& casacore::ROMSHistoryColumns::message () const inline
Definition at line 90 of file MSHistoryColumns.h.
References message_p.
Referenced by casacore::MSHistoryColumns::message().
nrow()
uInt casacore::ROMSHistoryColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 101 of file MSHistoryColumns.h.
References application_p.
objectId()
const ROScalarColumn<Int>& casacore::ROMSHistoryColumns::objectId () const inline
Definition at line 91 of file MSHistoryColumns.h.
References objectId_p.
Referenced by casacore::MSHistoryColumns::objectId().
observationId()
const ROScalarColumn<Int>& casacore::ROMSHistoryColumns::observationId () const inline
Definition at line 92 of file MSHistoryColumns.h.
References observationId_p.
Referenced by casacore::MSHistoryColumns::observationId().
operator=()
ROMSHistoryColumns& casacore::ROMSHistoryColumns::operator= (const ROMSHistoryColumns &) private
origin()
const ROScalarColumn<String>& casacore::ROMSHistoryColumns::origin () const inline
Definition at line 93 of file MSHistoryColumns.h.
References origin_p.
Referenced by casacore::MSHistoryColumns::origin().
priority()
const ROScalarColumn<String>& casacore::ROMSHistoryColumns::priority () const inline
Definition at line 94 of file MSHistoryColumns.h.
References priority_p.
Referenced by casacore::MSHistoryColumns::priority().
time()
const ROScalarColumn<Double>& casacore::ROMSHistoryColumns::time () const inline
Definition at line 95 of file MSHistoryColumns.h.
References time_p.
Referenced by casacore::MSHistoryColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSHistoryColumns::timeMeas () const inline
Definition at line 97 of file MSHistoryColumns.h.
References timeMeas_p.
Referenced by casacore::MSHistoryColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSHistoryColumns::timeQuant () const inline
Definition at line 96 of file MSHistoryColumns.h.
References timeQuant_p.
Referenced by casacore::MSHistoryColumns::timeQuant().
Member Data Documentation
application_p
ROScalarColumn<String> casacore::ROMSHistoryColumns::application_p private
Definition at line 118 of file MSHistoryColumns.h.
Referenced by application(), and nrow().
appParams_p
ROArrayColumn<String> casacore::ROMSHistoryColumns::appParams_p private
Definition at line 119 of file MSHistoryColumns.h.
Referenced by appParams().
cliCommand_p
ROArrayColumn<String> casacore::ROMSHistoryColumns::cliCommand_p private
Definition at line 120 of file MSHistoryColumns.h.
Referenced by cliCommand().
message_p
ROScalarColumn<String> casacore::ROMSHistoryColumns::message_p private
Definition at line 121 of file MSHistoryColumns.h.
Referenced by message().
objectId_p
ROScalarColumn<Int> casacore::ROMSHistoryColumns::objectId_p private
Definition at line 122 of file MSHistoryColumns.h.
Referenced by objectId().
observationId_p
ROScalarColumn<Int> casacore::ROMSHistoryColumns::observationId_p private
Definition at line 123 of file MSHistoryColumns.h.
Referenced by observationId().
origin_p
ROScalarColumn<String> casacore::ROMSHistoryColumns::origin_p private
Definition at line 124 of file MSHistoryColumns.h.
Referenced by origin().
priority_p
ROScalarColumn<String> casacore::ROMSHistoryColumns::priority_p private
Definition at line 125 of file MSHistoryColumns.h.
Referenced by priority().
time_p
ROScalarColumn<Double> casacore::ROMSHistoryColumns::time_p private
Definition at line 126 of file MSHistoryColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSHistoryColumns::timeMeas_p private
Definition at line 129 of file MSHistoryColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSHistoryColumns::timeQuant_p private
Definition at line 132 of file MSHistoryColumns.h.
Referenced by timeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSHistoryColumns.h