casacore: casacore::BaseColumn Class Reference
casacore::BaseColumn Class Reference abstract
tables package (libcasa_tables) » Tables_module » Tables_module_internal_classes
Abstract base class for a table column.
#include <BaseColumn.h>
Public Member Functions
BaseColumn (const BaseColumnDesc *)
Construct it using the given column description.
virtual ~BaseColumn ()
virtual Bool isWritable () const =0
Test if the column is writable.
virtual Bool isStored () const =0
Test if the column is stored (otherwise it is virtual).
virtual TableRecord & rwKeywordSet ()=0
Get access to the column keyword set.
virtual TableRecord & keywordSet ()=0
const ColumnDesc & columnDesc () const
Get const access to the column description.
virtual uInt nrow () const =0
Get nr of rows in the column.
virtual Bool isDefined (uInt rownr) const =0
Test if the given cell contains a defined value.
virtual void setShape (uInt rownr, const IPosition &shape)
Set the shape of the array in the given row.
virtual void setShape (uInt rownr, const IPosition &shape, const IPosition &tileShape)
Set the shape and tile shape of the array in the given row.
virtual uInt ndimColumn () const
Get the global #dimensions of an array (ie.
virtual IPosition shapeColumn () const
Get the global shape of an array (ie.
virtual uInt ndim (uInt rownr) const
Get the #dimensions of an array in a particular cell.
virtual IPosition shape (uInt rownr) const
Get the shape of an array in a particular cell.
virtual IPosition tileShape (uInt rownr) const
Get the tile shape of an array in a particular cell.
virtual Bool canChangeShape () const
Ask the data manager if the shape of an existing array can be changed.
virtual Bool canAccessScalarColumn (Bool &reask) const
Ask if the data manager can handle a scalar column.
virtual Bool canAccessArrayColumn (Bool &reask) const
Ask if the data manager can handle an array column.
virtual Bool canAccessScalarColumnCells (Bool &reask) const
Ask if the data manager can handle a collection of cells in a scalar column.
virtual Bool canAccessArrayColumnCells (Bool &reask) const
Ask if the data manager can handle a collection of cells in an array column.
virtual Bool canAccessSlice (Bool &reask) const
Ask if the data manager can handle a cell slice.
virtual Bool canAccessColumnSlice (Bool &reask) const
Ask if the data manager can handle a column slice.
virtual void initialize (uInt startRownr, uInt endRownr)=0
Initialize the rows from startRow till endRow (inclusive) with the default value defined in the column description.
virtual void get (uInt rownr, void *dataPtr) const =0
Get the value from a particular cell.
virtual void getSlice (uInt rownr, const Slicer &, void *dataPtr) const
Get a slice of an N-dimensional array in a particular cell.
virtual void getScalarColumn (void *dataPtr) const
Get the vector of all scalar values in a column.
virtual void getArrayColumn (void *dataPtr) const
Get the array of all array values in a column.
virtual void getColumnSlice (const Slicer &, void *dataPtr) const
Get subsections from all arrays in the column.
virtual void getScalarColumnCells (const RefRows &rownrs, void *dataPtr) const
Get the vector of some scalar values in a column.
virtual void getArrayColumnCells (const RefRows &rownrs, void *dataPtr) const
Get the array of some array values in a column.
virtual void getColumnSliceCells (const RefRows &rownrs, const Slicer &, void *dataPtr) const
Get subsections from some arrays in the column.
virtual void put (uInt rownr, const void *dataPtr)=0
Put the value in a particular cell.
virtual void putSlice (uInt rownr, const Slicer &, const void *dataPtr)
Put a slice of an N-dimensional array in a particular cell.
virtual void putScalarColumn (const void *dataPtr)
Put the vector of all scalar values in the column.
virtual void putArrayColumn (const void *dataPtr)
Put the array of all array values in the column.
virtual void putColumnSlice (const Slicer &, const void *dataPtr)
Put into subsections of all table arrays in the column.
virtual void putScalarColumnCells (const RefRows &rownrs, const void *dataPtr)
Get the vector of some scalar values in a column.
virtual void putArrayColumnCells (const RefRows &rownrs, const void *dataPtr)
Get the array of some array values in a column.
virtual void putColumnSliceCells (const RefRows &rownrs, const Slicer &, const void *dataPtr)
Put subsections of some arrays in the column.
void getScalar (uInt rownr, Bool &value) const
Get the value from the row and convert it to the required type.
void getScalar (uInt rownr, uChar &value) const
void getScalar (uInt rownr, Short &value) const
void getScalar (uInt rownr, uShort &value) const
void getScalar (uInt rownr, Int &value) const
void getScalar (uInt rownr, uInt &value) const
void getScalar (uInt rownr, Int64 &value) const
void getScalar (uInt rownr, float &value) const
void getScalar (uInt rownr, double &value) const
void getScalar (uInt rownr, Complex &value) const
void getScalar (uInt rownr, DComplex &value) const
void getScalar (uInt rownr, String &value) const
void getScalar (uInt rownr, TableRecord &value) const
void getScalar (uInt rownr, void *value, const String &dataTypeId) const
Get a scalar for the other data types.
void putScalar (uInt rownr, const Bool &value)
Put the value into the row and convert it from the given type.
void putScalar (uInt rownr, const uChar &value)
void putScalar (uInt rownr, const Short &value)
void putScalar (uInt rownr, const uShort &value)
void putScalar (uInt rownr, const Int &value)
void putScalar (uInt rownr, const uInt &value)
void putScalar (uInt rownr, const Int64 &value)
void putScalar (uInt rownr, const float &value)
void putScalar (uInt rownr, const double &value)
void putScalar (uInt rownr, const Complex &value)
void putScalar (uInt rownr, const DComplex &value)
void putScalar (uInt rownr, const String &value)
void putScalar (uInt rownr, const Char *value)
void putScalar (uInt rownr, const TableRecord &value)
virtual ColumnCache & columnCache ()=0
Get a pointer to the underlying column cache.
virtual void setMaximumCacheSize (uInt nbytes)=0
Set the maximum cache size (in bytes) to be used by a storage manager.
virtual void makeSortKey (Sort &, CountedPtr< BaseCompare > &cmpObj, Int order, const void *&dataSave)
Add this column and its data to the Sort object.
virtual void makeRefSortKey (Sort &, CountedPtr< BaseCompare > &cmpObj, Int order, const Vector< uInt > &rownrs, const void *&dataSave)
Do it only for the given row numbers.
virtual void freeSortKey (const void *&dataSave)
Free storage on the heap allocated by makeSortkey().
virtual void allocIterBuf (void *&lastVal, void *&curVal, CountedPtr< BaseCompare > &cmpObj)
Allocate value buffers for the table iterator.
virtual void freeIterBuf (void *&lastVal, void *&curVal)
Free the value buffers allocated by allocIterBuf.
Protected Member Functions
void throwGetScalar () const
Throw exceptions for invalid scalar get or put.
void throwPutScalar () const
void throwGetType (const String &type) const
void throwPutType (const String &type) const
Protected Attributes
const BaseColumnDesc * colDescPtr_p
Private Attributes
ColumnDesc colDesc_p
Detailed Description
Abstract base class for a table column.
Intended use:
Internal
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Prerequisite
ColumnDesc
Table
Etymology
This is the (abstract) base class to access a column in a table.
Synopsis
This class is the base class for the derived column classes. It is a private class in the sense that the user cannot get access to it. All user access to a column is done via the classes TableColumn, ScalarColumn and ArrayColumn. They call the corresponding functions in this class and its derived classes.
Motivation
This class serves a the base for the more specialized column classes like FilledScalarColumn and RefColumn. It defines many virtual functions, which are implemented in the derived classes. Some of these functions are purely virtual, some have a default implementation throwing an "invalid operation" exception. In that way those latter functions only have to be implemented in the classes which handle those cases.
Tip: The class RefColumn is in fact implemented in terms of this class; Almost every function in RefColumn calls the corresponding function in BaseColumn with the correct row number;
Definition at line 98 of file BaseColumn.h.
Constructor & Destructor Documentation
BaseColumn()
casacore::BaseColumn::BaseColumn (const BaseColumnDesc *)
Construct it using the given column description.
~BaseColumn()
virtual casacore::BaseColumn::~BaseColumn () virtual
Member Function Documentation
allocIterBuf()
virtual void casacore::BaseColumn::allocIterBuf (void *& lastVal, void *& curVal, CountedPtr< BaseCompare > & cmpObj) virtual
Allocate value buffers for the table iterator.
Also get a comparison object if undefined. The function freeIterBuf must be called to free the buffers.
Reimplemented in casacore::RefColumn, casacore::ConcatColumn, casacore::ScalarColumnData< T >, and casacore::ScalarRecordColumnData.
canAccessArrayColumn()
virtual Bool casacore::BaseColumn::canAccessArrayColumn (Bool & reask) const virtual
Ask if the data manager can handle an array column.
Default is never.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::ArrayColumnData< T >.
canAccessArrayColumnCells()
virtual Bool casacore::BaseColumn::canAccessArrayColumnCells (Bool & reask) const virtual
Ask if the data manager can handle a collection of cells in an array column.
Default is never.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::ArrayColumnData< T >.
canAccessColumnSlice()
virtual Bool casacore::BaseColumn::canAccessColumnSlice (Bool & reask) const virtual
Ask if the data manager can handle a column slice.
Default is never.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::ArrayColumnData< T >.
canAccessScalarColumn()
virtual Bool casacore::BaseColumn::canAccessScalarColumn (Bool & reask) const virtual
Ask if the data manager can handle a scalar column.
Default is never.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, casacore::ScalarRecordColumnData, and casacore::ScalarColumnData< T >.
canAccessScalarColumnCells()
virtual Bool casacore::BaseColumn::canAccessScalarColumnCells (Bool & reask) const virtual
Ask if the data manager can handle a collection of cells in a scalar column.
Default is never.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, casacore::ScalarRecordColumnData, and casacore::ScalarColumnData< T >.
canAccessSlice()
virtual Bool casacore::BaseColumn::canAccessSlice (Bool & reask) const virtual
Ask if the data manager can handle a cell slice.
Default is never.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::ArrayColumnData< T >.
canChangeShape()
virtual Bool casacore::BaseColumn::canChangeShape () const virtual
Ask the data manager if the shape of an existing array can be changed.
Default is no.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::ArrayColumnData< T >.
columnCache()
virtual ColumnCache& casacore::BaseColumn::columnCache () pure virtual
Get a pointer to the underlying column cache.
Implemented in casacore::RefColumn, casacore::ConcatColumn, and casacore::PlainColumn.
columnDesc()
const ColumnDesc& casacore::BaseColumn::columnDesc () const
Get const access to the column description.
freeIterBuf()
virtual void casacore::BaseColumn::freeIterBuf (void *& lastVal, void *& curVal) virtual
Free the value buffers allocated by allocIterBuf.
Reimplemented in casacore::RefColumn, casacore::ConcatColumn, casacore::ScalarColumnData< T >, and casacore::ScalarRecordColumnData.
freeSortKey()
virtual void casacore::BaseColumn::freeSortKey (const void *& dataSave) virtual
Free storage on the heap allocated by makeSortkey().
The pointer will be set to zero.
Reimplemented in casacore::RefColumn, casacore::ScalarRecordColumnData, casacore::ScalarColumnData< T >, and casacore::ConcatScalarColumn< T >.
get()
virtual void casacore::BaseColumn::get (uInt rownr, void * dataPtr) const pure virtual
Get the value from a particular cell.
This can be a scalar or an array.
Implemented in casacore::ConcatColumn, casacore::RefColumn, casacore::ArrayColumnData< T >, casacore::ScalarRecordColumnData, and casacore::ScalarColumnData< T >.
Referenced by casacore::ArrayColumn< casacore::String >::baseGet(), and casacore::ScalarColumn< casacore::String >::get().
getArrayColumn()
virtual void casacore::BaseColumn::getArrayColumn (void * dataPtr) const virtual
Get the array of all array values in a column.
If the column contains n-dim arrays, the resulting array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::ConcatColumn, casacore::ArrayColumnData< T >, and casacore::RefColumn.
getArrayColumnCells()
virtual void casacore::BaseColumn::getArrayColumnCells (const RefRows & rownrs, void * dataPtr) const virtual
Get the array of some array values in a column.
If the column contains n-dim arrays, the resulting array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::ArrayColumnData< T >.
getColumnSlice()
virtual void casacore::BaseColumn::getColumnSlice (const Slicer & , void * dataPtr) const virtual
Get subsections from all arrays in the column.
If the column contains n-dim arrays, the resulting array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, and casacore::RefColumn.
getColumnSliceCells()
virtual void casacore::BaseColumn::getColumnSliceCells (const RefRows & rownrs, const Slicer & , void * dataPtr) const virtual
Get subsections from some arrays in the column.
If the column contains n-dim arrays, the resulting array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::ConcatColumn, casacore::ArrayColumnData< T >, and casacore::RefColumn.
getScalar() [1/14]
void casacore::BaseColumn::getScalar (uInt rownr, Bool & value) const
Get the value from the row and convert it to the required type.
This can only be used for scalar columns with a standard data type. Note that an unsigned integer cannot be converted to a signed integer with the same length. So only Int64 can handle all integer values.
Referenced by casacore::TableColumn::getScalar(), and casacore::TableColumn::getScalarValue().
getScalar() [2/14]
void casacore::BaseColumn::getScalar (uInt rownr, uChar & value) const
getScalar() [3/14]
void casacore::BaseColumn::getScalar (uInt rownr, Short & value) const
getScalar() [4/14]
void casacore::BaseColumn::getScalar (uInt rownr, uShort & value) const
getScalar() [5/14]
void casacore::BaseColumn::getScalar (uInt rownr, Int & value) const
getScalar() [6/14]
void casacore::BaseColumn::getScalar (uInt rownr, uInt & value) const
getScalar() [7/14]
void casacore::BaseColumn::getScalar (uInt rownr, Int64 & value) const
getScalar() [8/14]
void casacore::BaseColumn::getScalar (uInt rownr, float & value) const
getScalar() [9/14]
void casacore::BaseColumn::getScalar (uInt rownr, double & value) const
getScalar() [10/14]
void casacore::BaseColumn::getScalar (uInt rownr, Complex & value) const
getScalar() [11/14]
void casacore::BaseColumn::getScalar (uInt rownr, DComplex & value) const
getScalar() [12/14]
void casacore::BaseColumn::getScalar (uInt rownr, String & value) const
getScalar() [13/14]
void casacore::BaseColumn::getScalar (uInt rownr, TableRecord & value) const
getScalar() [14/14]
void casacore::BaseColumn::getScalar (uInt rownr, void * value, const String & dataTypeId) const
Get a scalar for the other data types.
The given data type id must match the data type id of this column.
getScalarColumn()
virtual void casacore::BaseColumn::getScalarColumn (void * dataPtr) const virtual
Get the vector of all scalar values in a column.
Reimplemented in casacore::RefColumn, casacore::ScalarRecordColumnData, casacore::ScalarColumnData< T >, and casacore::ConcatScalarColumn< T >.
getScalarColumnCells()
virtual void casacore::BaseColumn::getScalarColumnCells (const RefRows & rownrs, void * dataPtr) const virtual
Get the vector of some scalar values in a column.
Reimplemented in casacore::RefColumn, casacore::ScalarRecordColumnData, casacore::ScalarColumnData< T >, and casacore::ConcatScalarColumn< T >.
getSlice()
virtual void casacore::BaseColumn::getSlice (uInt rownr, const Slicer & , void * dataPtr) const virtual
Get a slice of an N-dimensional array in a particular cell.
Reimplemented in casacore::ConcatColumn, casacore::ArrayColumnData< T >, and casacore::RefColumn.
initialize()
virtual void casacore::BaseColumn::initialize (uInt startRownr, uInt endRownr) pure virtual
Initialize the rows from startRow till endRow (inclusive) with the default value defined in the column description.
Implemented in casacore::ConcatColumn, casacore::RefColumn, casacore::ArrayColumnData< T >, casacore::ScalarRecordColumnData, and casacore::ScalarColumnData< T >.
isDefined()
virtual Bool casacore::BaseColumn::isDefined (uInt rownr) const pure virtual
Test if the given cell contains a defined value.
Implemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, casacore::RefColumn, casacore::ScalarRecordColumnData, and casacore::ScalarColumnData< T >.
Referenced by casacore::TableColumn::isDefined().
isStored()
virtual Bool casacore::BaseColumn::isStored () const pure virtual
Test if the column is stored (otherwise it is virtual).
Implemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::PlainColumn.
isWritable()
virtual Bool casacore::BaseColumn::isWritable () const pure virtual
Test if the column is writable.
Implemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::PlainColumn.
keywordSet()
virtual TableRecord& casacore::BaseColumn::keywordSet () pure virtual
Implemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::PlainColumn.
Referenced by casacore::TableColumn::keywordSet().
makeRefSortKey()
virtual void casacore::BaseColumn::makeRefSortKey (Sort & , CountedPtr< BaseCompare > & cmpObj, Int order, const Vector< uInt > & rownrs, const void *& dataSave) virtual
Do it only for the given row numbers.
Reimplemented in casacore::ScalarColumnData< T >, casacore::ScalarRecordColumnData, and casacore::ConcatScalarColumn< T >.
makeSortKey()
virtual void casacore::BaseColumn::makeSortKey (Sort & , CountedPtr< BaseCompare > & cmpObj, Int order, const void *& dataSave) virtual
Add this column and its data to the Sort object.
It may allocate some storage on the heap, which will be saved in the argument dataSave. The function freeSortKey must be called to free this storage.
Reimplemented in casacore::RefColumn, casacore::ScalarColumnData< T >, casacore::ScalarRecordColumnData, and casacore::ConcatScalarColumn< T >.
ndim()
virtual uInt casacore::BaseColumn::ndim (uInt rownr) const virtual
Get the #dimensions of an array in a particular cell.
Reimplemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, and casacore::RefColumn.
Referenced by casacore::ArrayColumn< casacore::String >::ndim(), and casacore::TableColumn::ndim().
ndimColumn()
virtual uInt casacore::BaseColumn::ndimColumn () const virtual
Get the global #dimensions of an array (ie.
for all rows).
Reimplemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, and casacore::RefColumn.
Referenced by casacore::TableColumn::ndimColumn().
nrow()
virtual uInt casacore::BaseColumn::nrow () const pure virtual
Get nr of rows in the column.
Implemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::PlainColumn.
Referenced by casacore::TableColumn::nrow().
put()
virtual void casacore::BaseColumn::put (uInt rownr, const void * dataPtr) pure virtual
Put the value in a particular cell.
This can be a scalar or an array.
Implemented in casacore::ArrayColumnData< T >, casacore::RefColumn, casacore::ConcatColumn, casacore::ScalarRecordColumnData, and casacore::ScalarColumnData< T >.
Referenced by casacore::ArrayColumn< casacore::String >::basePut(), and casacore::ScalarColumn< casacore::String >::put().
putArrayColumn()
virtual void casacore::BaseColumn::putArrayColumn (const void * dataPtr) virtual
Put the array of all array values in the column.
If the column contains n-dim arrays, the source array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::ArrayColumnData< T >, casacore::RefColumn, and casacore::ConcatColumn.
putArrayColumnCells()
virtual void casacore::BaseColumn::putArrayColumnCells (const RefRows & rownrs, const void * dataPtr) virtual
Get the array of some array values in a column.
If the column contains n-dim arrays, the resulting array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::RefColumn, casacore::ArrayColumnData< T >, and casacore::ConcatColumn.
putColumnSlice()
virtual void casacore::BaseColumn::putColumnSlice (const Slicer & , const void * dataPtr) virtual
Put into subsections of all table arrays in the column.
If the column contains n-dim arrays, the source array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::ArrayColumnData< T >, casacore::RefColumn, and casacore::ConcatColumn.
putColumnSliceCells()
virtual void casacore::BaseColumn::putColumnSliceCells (const RefRows & rownrs, const Slicer & , const void * dataPtr) virtual
Put subsections of some arrays in the column.
If the column contains n-dim arrays, the source array is (n+1)-dim. The arrays in the column have to have the same shape in all cells.
Reimplemented in casacore::ArrayColumnData< T >, casacore::RefColumn, and casacore::ConcatColumn.
putScalar() [1/14]
void casacore::BaseColumn::putScalar (uInt rownr, const Bool & value)
Put the value into the row and convert it from the given type.
This can only be used for scalar columns with a standard data type.
Referenced by putScalar(), and casacore::TableColumn::putScalar().
putScalar() [2/14]
void casacore::BaseColumn::putScalar (uInt rownr, const uChar & value)
putScalar() [3/14]
void casacore::BaseColumn::putScalar (uInt rownr, const Short & value)
putScalar() [4/14]
void casacore::BaseColumn::putScalar (uInt rownr, const uShort & value)
putScalar() [5/14]
void casacore::BaseColumn::putScalar (uInt rownr, const Int & value)
putScalar() [6/14]
void casacore::BaseColumn::putScalar (uInt rownr, const uInt & value)
putScalar() [7/14]
void casacore::BaseColumn::putScalar (uInt rownr, const Int64 & value)
putScalar() [8/14]
void casacore::BaseColumn::putScalar (uInt rownr, const float & value)
putScalar() [9/14]
void casacore::BaseColumn::putScalar (uInt rownr, const double & value)
putScalar() [10/14]
void casacore::BaseColumn::putScalar (uInt rownr, const Complex & value)
putScalar() [11/14]
void casacore::BaseColumn::putScalar (uInt rownr, const DComplex & value)
putScalar() [12/14]
void casacore::BaseColumn::putScalar (uInt rownr, const String & value)
putScalar() [13/14]
void casacore::BaseColumn::putScalar (uInt rownr, const Char * value) inline
Definition at line 293 of file BaseColumn.h.
References putScalar(), and casacore::value().
putScalar() [14/14]
void casacore::BaseColumn::putScalar (uInt rownr, const TableRecord & value)
putScalarColumn()
virtual void casacore::BaseColumn::putScalarColumn (const void * dataPtr) virtual
Put the vector of all scalar values in the column.
Reimplemented in casacore::RefColumn, casacore::ScalarRecordColumnData, casacore::ScalarColumnData< T >, and casacore::ConcatScalarColumn< T >.
putScalarColumnCells()
virtual void casacore::BaseColumn::putScalarColumnCells (const RefRows & rownrs, const void * dataPtr) virtual
Get the vector of some scalar values in a column.
Reimplemented in casacore::RefColumn, casacore::ScalarRecordColumnData, casacore::ScalarColumnData< T >, and casacore::ConcatScalarColumn< T >.
putSlice()
virtual void casacore::BaseColumn::putSlice (uInt rownr, const Slicer & , const void * dataPtr) virtual
Put a slice of an N-dimensional array in a particular cell.
Reimplemented in casacore::ArrayColumnData< T >, casacore::RefColumn, and casacore::ConcatColumn.
rwKeywordSet()
virtual TableRecord& casacore::BaseColumn::rwKeywordSet () pure virtual
Get access to the column keyword set.
Implemented in casacore::ConcatColumn, casacore::RefColumn, and casacore::PlainColumn.
setMaximumCacheSize()
virtual void casacore::BaseColumn::setMaximumCacheSize (uInt nbytes) pure virtual
Set the maximum cache size (in bytes) to be used by a storage manager.
Implemented in casacore::RefColumn, casacore::ConcatColumn, and casacore::PlainColumn.
Referenced by casacore::TableColumn::setMaximumCacheSize().
setShape() [1/2]
virtual void casacore::BaseColumn::setShape (uInt rownr, const IPosition & shape) virtual
Set the shape of the array in the given row.
Reimplemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, and casacore::RefColumn.
setShape() [2/2]
virtual void casacore::BaseColumn::setShape (uInt rownr, const IPosition & shape, const IPosition & tileShape) virtual
Set the shape and tile shape of the array in the given row.
Reimplemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, and casacore::RefColumn.
shape()
virtual IPosition casacore::BaseColumn::shape (uInt rownr) const virtual
Get the shape of an array in a particular cell.
Reimplemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, and casacore::RefColumn.
Referenced by casacore::ArrayColumn< casacore::String >::shape(), and casacore::TableColumn::shape().
shapeColumn()
virtual IPosition casacore::BaseColumn::shapeColumn () const virtual
Get the global shape of an array (ie.
for all rows).
Reimplemented in casacore::ArrayColumnData< T >, casacore::ConcatColumn, and casacore::RefColumn.
Referenced by casacore::TableColumn::shapeColumn().
throwGetScalar()
void casacore::BaseColumn::throwGetScalar () const protected
Throw exceptions for invalid scalar get or put.
throwGetType()
void casacore::BaseColumn::throwGetType (const String & type) const protected
throwPutScalar()
void casacore::BaseColumn::throwPutScalar () const protected
throwPutType()
void casacore::BaseColumn::throwPutType (const String & type) const protected
tileShape()
virtual IPosition casacore::BaseColumn::tileShape (uInt rownr) const virtual
Get the tile shape of an array in a particular cell.
Reimplemented in casacore::ArrayColumnData< T >, and casacore::ConcatColumn.
Referenced by casacore::TableColumn::tileShape().
Member Data Documentation
colDesc_p
ColumnDesc casacore::BaseColumn::colDesc_p mutable private
Definition at line 345 of file BaseColumn.h.
colDescPtr_p
const BaseColumnDesc* casacore::BaseColumn::colDescPtr_p protected
Definition at line 340 of file BaseColumn.h.
The documentation for this class was generated from the following file:
tables/Tables/BaseColumn.h