casacore: casacore::Lorentzian1DParam< T > Class Template Reference
casacore::Lorentzian1DParam< T > Class Template Reference
Functionals_module_internal_classes
Parameter handling for one dimensional Lorentzian class.
#include <Lorentzian1DParam.h>
Public Types
enum {
HEIGHT,
CENTER,
WIDTH
}
Public Types inherited from casacore::Function1D< T >
typedef const T * FunctionArg
Public Types inherited from casacore::Function< T, T >
typedef FunctionTraits< T >
::ArgType ArgType
typedef const ArgType * FunctionArg
Public Member Functions
Lorentzian1DParam ()
Constructs the one dimensional Lorentzians.
Lorentzian1DParam (const T &height)
Lorentzian1DParam (const T &height, const T &center)
Lorentzian1DParam (const T &height, const T &center, const T &width)
Lorentzian1DParam (const Lorentzian1DParam< T > &other)
Copy constructor (deep copy)
template<class W >
Lorentzian1DParam (const Lorentzian1DParam< W > &other)
Lorentzian1DParam< T > & operator= (const Lorentzian1DParam< T > &other)
Copy assignment (deep copy)
virtual ~Lorentzian1DParam ()
Destructor.
virtual const String & name () const
Give name of function.
T height () const
Get or set the peak height of the Lorentzian.
void setHeight (const T &height)
T flux () const
Get or set the analytical integrated area underneath the Lorentzian.
void setFlux (const T &flux)
T center () const
Get or set the center ordinate of the Lorentzian.
void setCenter (const T &cnter)
T width () const
Get or set the FWHM of the Lorentzian.
void setWidth (const T &width)
Public Member Functions inherited from casacore::Function1D< T >
Function1D ()
Constructors.
Function1D (const uInt n)
Function1D (const Vector< T > &in)
Function1D (const FunctionParam< T > &other)
Function1D (const Function1D< W, X > &other)
virtual ~Function1D ()
Destructor.
virtual uInt ndim () const
Returns the number of dimensions of function.
Public Member Functions inherited from casacore::Function< T, T >
Function ()
Constructors.
Function (const uInt n)
Function (const Vector< T > &in)
Function (const FunctionParam< T > &other)
Function (const Function< W, X > &other)
virtual ~Function ()
Destructor.
uInt nparameters () const
Returns the number of parameters.
virtual T eval (FunctionArg x) const =0
Evaluate the function object.
T & operator[] (const uInt n)
Manipulate the nth parameter (0-based) with no index check.
const T & operator[] (const uInt n) const
virtual T operator() () const
Evaluate this function object at xor at x, y.
virtual T operator() (const ArgType &x) const
virtual T operator() (const Vector< ArgType > &x) const
virtual T operator() (FunctionArg x) const
virtual T operator() (const ArgType &x, const ArgType &y) const
virtual T operator() (const ArgType &x, const ArgType &y, const ArgType &z) const
Bool & mask (const uInt n)
Manipulate the mask associated with the nth parameter (e.g.
const Bool & mask (const uInt n) const
const FunctionParam< T > & parameters () const
Return the parameter interface.
FunctionParam< T > & parameters ()
const Vector< ArgType > & argp () const
Get arg_p and parset_p.
Bool parsetp () const
void lockParam ()
Compiler cannot always find the correct 'const' version of parameter access.
void unlockParam ()
virtual void setMode (const RecordInterface &mode)
get/set the function mode.
virtual void getMode (RecordInterface &mode) const
virtual Bool hasMode () const
return True if the implementing function supports a mode.
ostream & print (ostream &os) const
Print the function (i.e.
virtual Function< T, T > * clone () const =0
Return a copy of this object from the heap.
virtual Function< typename
FunctionTraits< T >::DiffType > * cloneAD () const
virtual Function< typename
FunctionTraits< T >::BaseType > * cloneNonAD () const
Public Member Functions inherited from casacore::Functional< FunctionTraits< T >::ArgType, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const FunctionTraits< T >::ArgType &x) const =0
Map a Domain x into a Range y value.
Public Member Functions inherited from casacore::Functional< Vector< FunctionTraits< T >::ArgType >, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const Vector< FunctionTraits< T >::ArgType > &x) const =0
Map a Domain x into a Range y value.
Protected Attributes
T fwhm2int
Constant to scale halfwidth at 1/e to FWHM.
Protected Attributes inherited from casacore::Function< T, T >
FunctionParam< T > param_p
The parameters and masks.
Vector< ArgType > arg_p
Aid for non-contiguous argument storage.
Bool parset_p
Indicate parameter written.
Bool locked_p
Indicate that parameters are expected to be locked from changing.
Detailed Description
template<class T>
class casacore::Lorentzian1DParam< T >
Parameter handling for one dimensional Lorentzian class.
Intended use:
Internal
Review Status
Reviewed By:
tcornwel
Date Reviewed:
1996/02/22
Test programs:
tLorentzian1D
Prerequisite
FunctionParam class
Function1D class
Etymology
A 1-dimensional Lorentzian's parameters.
Synopsis
A Lorentzian1D is described by a height, center, and width. The parameters (height, center and width) may be changed at run time.
The width of the Lorentzian (for the constructors or the setWidth function) is always specified in terms of the full width at half maximum (FWHM). It is always positive and attempts to set a non-positive width will throw an assertion when in debug mode.
The peak height of the Lorentzian can be specified at construction time or by using the setHeight function. Alternatively the setFlux function can be used to implicitly set the peak height by specifying the integrated area under the Lorentzian. The height (or flux) can be positive, negative or zero, as this class makes no assumptions on what quantity the height represents.
Tip: Changing the width of the Lorentzian will not affect its peak height but will change its flux; So you should always set the width before setting the flux;
The parameter interface (see FunctionParam class), is used to provide an interface to the Fitting classes.
There are 3 parameters that are used to describe the Lorentzian:
The height of the Lorentzian. This is identical to the value returned using the height() member function.
The center of the Lorentzian in the x direction. This is identical to the value returned using the center() member function.
The width (FWHM) of the Lorentzian. To aid convergence of the non-linear fitting routines this parameter is allowed to be negative. This does not affect the shape of the Lorentzian as the square of the width is used when evaluating the function.
An enumeration for the HEIGHT, WIDTH and CENTER parameter index is provided, enabling the setting and reading of parameters with the [] operator. The mask() methods can be used to check and set the parameter masks.
This class is in general used implicitly by the Lorentzian1D class only.
Example
Lorentzian1D<Double> gf(5.0, 25.0, 7);
gf(25);            // = 5.0
gf.setHeight(1.0);
gf[WIDTH](2.0);
gf[CENTER](0.0);
gf(1);             // = 0.5*height = 0.5
Template Type Argument Requirements (T)
T should have standard numerical operators and exp() function. Current implementation only tested for real types (and their AutoDiffs).
Thrown Exceptions
Assertion in debug mode if attempt is made to set a negative width
AipsError if incorrect parameter number specified.
To Do
Lorentzians that know about their DFT's could be required eventually.
Definition at line 128 of file Lorentzian1DParam.h.
Member Enumeration Documentation
template<class T> anonymous enum
Enumerator
HEIGHT
CENTER
WIDTH
Definition at line 131 of file Lorentzian1DParam.h.
Constructor & Destructor Documentation
template<class T> casacore::Lorentzian1DParam< T >::Lorentzian1DParam ()
Constructs the one dimensional Lorentzians.
Defaults: height=1, center=0, width(FWHM)=1.
Warning: Could not use default arguments that worked both with gcc and IRIX and all templates
template<class T> casacore::Lorentzian1DParam< T >::Lorentzian1DParam (const T & height) explicit
template<class T> casacore::Lorentzian1DParam< T >::Lorentzian1DParam (const T & height, const T & center)
template<class T> casacore::Lorentzian1DParam< T >::Lorentzian1DParam (const T & height, const T & center, const T & width)
template<class T> casacore::Lorentzian1DParam< T >::Lorentzian1DParam (const Lorentzian1DParam< T > & other)
Copy constructor (deep copy)
template<class T> template<class W > casacore::Lorentzian1DParam< T >::Lorentzian1DParam (const Lorentzian1DParam< W > & other) inline
Definition at line 149 of file Lorentzian1DParam.h.
template<class T> virtual casacore::Lorentzian1DParam< T >::~Lorentzian1DParam () virtual
Destructor.
Member Function Documentation
template<class T> T casacore::Lorentzian1DParam< T >::center () const inline
Get or set the center ordinate of the Lorentzian.
Definition at line 181 of file Lorentzian1DParam.h.
template<class T> T casacore::Lorentzian1DParam< T >::flux () const
Get or set the analytical integrated area underneath the Lorentzian.
Use these functions as an alternative to the height functions.
template<class T> T casacore::Lorentzian1DParam< T >::height () const inline
Get or set the peak height of the Lorentzian.
Definition at line 168 of file Lorentzian1DParam.h.
Referenced by casacore::Lorentzian1DParam< AutoDiff< T > >::setHeight().
template<class T> virtual const String& casacore::Lorentzian1DParam< T >::name () const inline virtual
Give name of function.
Reimplemented from casacore::Function< T, T >.
Definition at line 163 of file Lorentzian1DParam.h.
template<class T> Lorentzian1DParam<T>& casacore::Lorentzian1DParam< T >::operator= (const Lorentzian1DParam< T > & other)
Copy assignment (deep copy)
Referenced by casacore::Lorentzian1D< T >::operator=().
template<class T> void casacore::Lorentzian1DParam< T >::setCenter (const T & cnter) inline
Definition at line 182 of file Lorentzian1DParam.h.
template<class T> void casacore::Lorentzian1DParam< T >::setFlux (const T & flux)
template<class T> void casacore::Lorentzian1DParam< T >::setHeight (const T & height) inline
Definition at line 169 of file Lorentzian1DParam.h.
template<class T> void casacore::Lorentzian1DParam< T >::setWidth (const T & width) inline
Definition at line 188 of file Lorentzian1DParam.h.
template<class T> T casacore::Lorentzian1DParam< T >::width () const inline
Get or set the FWHM of the Lorentzian.
Definition at line 187 of file Lorentzian1DParam.h.
Referenced by casacore::Lorentzian1DParam< AutoDiff< T > >::setWidth().
Member Data Documentation
template<class T> T casacore::Lorentzian1DParam< T >::fwhm2int protected
Constant to scale halfwidth at 1/e to FWHM.
Definition at line 188 of file Lorentzian1DParam.h.
The documentation for this class was generated from the following file:
scimath/Functionals/Lorentzian1DParam.h