casacore: casacore::LogHolderIter Class Reference
casacore::LogHolderIter Class Reference
tables package (libcasa_tables) » LogTables_module » LogTables_module_internal_classes
Class doing the actual iteration through an LoggerHolder.
#include <LoggerHolder.h>
Public Member Functions
LogHolderIter (const LoggerHolder *)
Construct the iterator on the given LoggerHolderRep.
~LogHolderIter ()
Bool next ()
Increment to next message.
const LogHolderIterEntry & getEntry () const
Get the entry.
const LoggerHolder & logger () const
Private Member Functions
LogHolderIter (const LogHolderIter &)
Copy constructor is not needed, thus forbidden.
LogHolderIter & operator= (const LogHolderIter &)
Assignment is not needed, thus forbidden.
Private Attributes
const LoggerHolder * itsLogger
Bool itsTempClosed
LogHolderIter * itsParentIter
uInt itsCounter
LogHolderIterEntry itsEntry
Detailed Description
Class doing the actual iteration through an LoggerHolder.
Intended use:
Internal
Review Status
Test programs:
tLoggerHolder
Prerequisite
LoggerHolder
Synopsis
This class makes it possible to use the iterator in the STL-style. It is used by LoggerHolderIterator which is the class as seen by the user. LogHolderIter makes it easier to make the first entry available on construction of an LoggerHolderIterator.
Definition at line 427 of file LoggerHolder.h.
Constructor & Destructor Documentation
LogHolderIter() [1/2]
casacore::LogHolderIter::LogHolderIter (const LoggerHolder *)
Construct the iterator on the given LoggerHolderRep.
~LogHolderIter()
casacore::LogHolderIter::~LogHolderIter ()
LogHolderIter() [2/2]
casacore::LogHolderIter::LogHolderIter (const LogHolderIter &) private
Copy constructor is not needed, thus forbidden.
Member Function Documentation
getEntry()
const LogHolderIterEntry& casacore::LogHolderIter::getEntry () const inline
Get the entry.
Definition at line 440 of file LoggerHolder.h.
References itsEntry.
Referenced by casacore::LoggerHolderIterator::operator *(), and casacore::LoggerHolderIterator::operator->().
logger()
const LoggerHolder& casacore::LogHolderIter::logger () const inline
Definition at line 443 of file LoggerHolder.h.
References itsLogger.
Referenced by casacore::LoggerHolderIterator::logger().
next()
Bool casacore::LogHolderIter::next ()
Increment to next message.
Returns False if at the end.
Referenced by casacore::LoggerHolderIterator::next().
operator=()
LogHolderIter& casacore::LogHolderIter::operator= (const LogHolderIter &) private
Assignment is not needed, thus forbidden.
Member Data Documentation
itsCounter
uInt casacore::LogHolderIter::itsCounter private
Definition at line 457 of file LoggerHolder.h.
itsEntry
LogHolderIterEntry casacore::LogHolderIter::itsEntry private
Definition at line 458 of file LoggerHolder.h.
Referenced by getEntry().
itsLogger
const LoggerHolder* casacore::LogHolderIter::itsLogger private
Definition at line 454 of file LoggerHolder.h.
Referenced by logger().
itsParentIter
LogHolderIter* casacore::LogHolderIter::itsParentIter private
Definition at line 456 of file LoggerHolder.h.
itsTempClosed
Bool casacore::LogHolderIter::itsTempClosed private
Definition at line 455 of file LoggerHolder.h.
The documentation for this class was generated from the following file:
tables/LogTables/LoggerHolder.h