casacore: casacore::MSAntennaColumns Class Reference
casacore::MSAntennaColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSAntenna columns.
#include <MSAntennaColumns.h>
Public Member Functions
MSAntennaColumns (MSAntenna &msAntenna)
Create a columns object that accesses the data in the specified Table.
~MSAntennaColumns ()
The destructor does nothing special.
ScalarColumn< Double > & dishDiameter ()
Read-write access to required columns.
ScalarQuantColumn< Double > & dishDiameterQuant ()
ScalarColumn< Bool > & flagRow ()
ScalarColumn< String > & mount ()
ScalarColumn< String > & name ()
ArrayColumn< Double > & offset ()
ArrayQuantColumn< Double > & offsetQuant ()
ScalarMeasColumn< MPosition > & offsetMeas ()
ArrayColumn< Double > & position ()
ArrayQuantColumn< Double > & positionQuant ()
ScalarMeasColumn< MPosition > & positionMeas ()
ScalarColumn< String > & station ()
ScalarColumn< String > & type ()
ArrayColumn< Double > & meanOrbit ()
Read-write access to optional columns.
ScalarColumn< Int > & orbitId ()
ScalarColumn< Int > & phasedArrayId ()
const ROScalarColumn< Double > & dishDiameter () const
Read-only access to required columns.
const ROScalarQuantColumn< Double > & dishDiameterQuant () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< String > & mount () const
const ROScalarColumn< String > & name () const
const ROArrayColumn< Double > & offset () const
const ROArrayQuantColumn< Double > & offsetQuant () const
const ROScalarMeasColumn< MPosition > & offsetMeas () const
const ROArrayColumn< Double > & position () const
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROScalarColumn< String > & station () const
const ROScalarColumn< String > & type () const
const ROArrayColumn< Double > & meanOrbit () const
Read-only access to optional columns.
const ROScalarColumn< Int > & orbitId () const
const ROScalarColumn< Int > & phasedArrayId () const
void setPositionRef (MPosition::Types ref)
set the position type for the POSITION column.
void setOffsetRef (MPosition::Types ref)
set the position type for the OFFSET column.
Public Member Functions inherited from casacore::ROMSAntennaColumns
ROMSAntennaColumns (const MSAntenna &msAntenna)
Create a columns object that accesses the data in the specified Table.
~ROMSAntennaColumns ()
The destructor does nothing special.
const ROScalarColumn< Double > & dishDiameter () const
Access to columns.
const ROScalarQuantColumn< Double > & dishDiameterQuant () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< String > & mount () const
const ROScalarColumn< String > & name () const
const ROArrayColumn< Double > & offset () const
const ROArrayQuantColumn< Double > & offsetQuant () const
const ROScalarMeasColumn< MPosition > & offsetMeas () const
const ROArrayColumn< Double > & position () const
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROScalarColumn< String > & station () const
const ROScalarColumn< String > & type () const
const ROArrayColumn< Double > & meanOrbit () const
Access to optional columns.
const ROScalarColumn< Int > & orbitId () const
const ROScalarColumn< Int > & phasedArrayId () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int matchAntenna (const MPosition &antennaPos, const Quantum< Double > &tolerance, Int tryRow=-1)
returns the last row that contains an antenna at the specified position, to within the specified tolerance.
Int matchAntenna (const String &antName, const MPosition &antennaPos, const Quantum< Double > &tolerance, Int tryRow=-1)
Same as the previous function except that the antenna name must also match.
Int matchAntennaAndStation (const String &antName, const String &stationName, const MPosition &antennaPos, const Quantum< Double > &tolerance, Int tryRow=-1)
Same as the previous function except that the station name must also match.
Protected Member Functions
MSAntennaColumns ()
void attach (MSAntenna &msAntenna)
Protected Member Functions inherited from casacore::ROMSAntennaColumns
ROMSAntennaColumns ()
void attach (const MSAntenna &msAntenna)
Private Member Functions
MSAntennaColumns (const MSAntennaColumns &)
MSAntennaColumns & operator= (const MSAntennaColumns &)
void attachOptionalCols (MSAntenna &msAntenna)
Private Attributes
ScalarColumn< Double > dishDiameter_p
ScalarColumn< Bool > flagRow_p
ScalarColumn< String > mount_p
ScalarColumn< String > name_p
ArrayColumn< Double > offset_p
ArrayColumn< Double > position_p
ScalarColumn< String > station_p
ScalarColumn< String > type_p
ArrayColumn< Double > meanOrbit_p
ScalarColumn< Int > orbitId_p
ScalarColumn< Int > phasedArrayId_p
ScalarMeasColumn< MPosition > offsetMeas_p
ScalarMeasColumn< MPosition > positionMeas_p
ScalarQuantColumn< Double > dishDiameterQuant_p
ArrayQuantColumn< Double > offsetQuant_p
ArrayQuantColumn< Double > positionQuant_p
Detailed Description
A class to provide easy read-write access to MSAntenna columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSAntenna
ArrayColumn
ScalarColumn
Etymology
MSAntennaColumns stands for MeasurementSet Antenna Table columns.
Synopsis
This class provides access to the columns in the MSAntenna Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 227 of file MSAntennaColumns.h.
Constructor & Destructor Documentation
MSAntennaColumns() [1/3]
casacore::MSAntennaColumns::MSAntennaColumns (MSAntenna & msAntenna)
Create a columns object that accesses the data in the specified Table.
~MSAntennaColumns()
casacore::MSAntennaColumns::~MSAntennaColumns ()
The destructor does nothing special.
MSAntennaColumns() [2/3]
casacore::MSAntennaColumns::MSAntennaColumns () protected
MSAntennaColumns() [3/3]
casacore::MSAntennaColumns::MSAntennaColumns (const MSAntennaColumns &) private
Member Function Documentation
attach()
void casacore::MSAntennaColumns::attach (MSAntenna & msAntenna) protected
attachOptionalCols()
void casacore::MSAntennaColumns::attachOptionalCols (MSAntenna & msAntenna) private
dishDiameter() [1/2]
ScalarColumn<Double>& casacore::MSAntennaColumns::dishDiameter () inline
Read-write access to required columns.
Definition at line 239 of file MSAntennaColumns.h.
References dishDiameter_p.
dishDiameter() [2/2]
const ROScalarColumn<Double>& casacore::MSAntennaColumns::dishDiameter () const inline
Read-only access to required columns.
Definition at line 263 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::dishDiameter().
dishDiameterQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSAntennaColumns::dishDiameterQuant () inline
Definition at line 240 of file MSAntennaColumns.h.
References dishDiameterQuant_p.
dishDiameterQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSAntennaColumns::dishDiameterQuant () const inline
Definition at line 265 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::dishDiameterQuant().
flagRow() [1/2]
ScalarColumn<Bool>& casacore::MSAntennaColumns::flagRow () inline
Definition at line 241 of file MSAntennaColumns.h.
References flagRow_p.
flagRow() [2/2]
const ROScalarColumn<Bool>& casacore::MSAntennaColumns::flagRow () const inline
Definition at line 267 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::flagRow().
meanOrbit() [1/2]
ArrayColumn<Double>& casacore::MSAntennaColumns::meanOrbit () inline
Read-write access to optional columns.
Definition at line 256 of file MSAntennaColumns.h.
References meanOrbit_p.
meanOrbit() [2/2]
const ROArrayColumn<Double>& casacore::MSAntennaColumns::meanOrbit () const inline
Read-only access to optional columns.
Definition at line 293 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::meanOrbit().
mount() [1/2]
ScalarColumn<String>& casacore::MSAntennaColumns::mount () inline
Definition at line 242 of file MSAntennaColumns.h.
References mount_p.
mount() [2/2]
const ROScalarColumn<String>& casacore::MSAntennaColumns::mount () const inline
Definition at line 269 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::mount().
name() [1/2]
ScalarColumn<String>& casacore::MSAntennaColumns::name () inline
Definition at line 243 of file MSAntennaColumns.h.
References name_p.
name() [2/2]
const ROScalarColumn<String>& casacore::MSAntennaColumns::name () const inline
Definition at line 271 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::name().
offset() [1/2]
ArrayColumn<Double>& casacore::MSAntennaColumns::offset () inline
Definition at line 244 of file MSAntennaColumns.h.
References offset_p.
offset() [2/2]
const ROArrayColumn<Double>& casacore::MSAntennaColumns::offset () const inline
Definition at line 273 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::offset().
offsetMeas() [1/2]
ScalarMeasColumn<MPosition>& casacore::MSAntennaColumns::offsetMeas () inline
Definition at line 246 of file MSAntennaColumns.h.
References offsetMeas_p.
offsetMeas() [2/2]
const ROScalarMeasColumn<MPosition>& casacore::MSAntennaColumns::offsetMeas () const inline
Definition at line 277 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::offsetMeas().
offsetQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSAntennaColumns::offsetQuant () inline
Definition at line 245 of file MSAntennaColumns.h.
References offsetQuant_p.
offsetQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSAntennaColumns::offsetQuant () const inline
Definition at line 275 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::offsetQuant().
operator=()
MSAntennaColumns& casacore::MSAntennaColumns::operator= (const MSAntennaColumns &) private
orbitId() [1/2]
ScalarColumn<Int>& casacore::MSAntennaColumns::orbitId () inline
Definition at line 257 of file MSAntennaColumns.h.
References orbitId_p.
orbitId() [2/2]
const ROScalarColumn<Int>& casacore::MSAntennaColumns::orbitId () const inline
Definition at line 295 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::orbitId().
phasedArrayId() [1/2]
ScalarColumn<Int>& casacore::MSAntennaColumns::phasedArrayId () inline
Definition at line 258 of file MSAntennaColumns.h.
References phasedArrayId_p.
phasedArrayId() [2/2]
const ROScalarColumn<Int>& casacore::MSAntennaColumns::phasedArrayId () const inline
Definition at line 297 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::phasedArrayId().
position() [1/2]
ArrayColumn<Double>& casacore::MSAntennaColumns::position () inline
Definition at line 247 of file MSAntennaColumns.h.
References position_p.
position() [2/2]
const ROArrayColumn<Double>& casacore::MSAntennaColumns::position () const inline
Definition at line 279 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::position().
positionMeas() [1/2]
ScalarMeasColumn<MPosition>& casacore::MSAntennaColumns::positionMeas () inline
Definition at line 249 of file MSAntennaColumns.h.
References positionMeas_p.
positionMeas() [2/2]
const ROScalarMeasColumn<MPosition>& casacore::MSAntennaColumns::positionMeas () const inline
Definition at line 283 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::positionMeas().
positionQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSAntennaColumns::positionQuant () inline
Definition at line 248 of file MSAntennaColumns.h.
References positionQuant_p.
positionQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSAntennaColumns::positionQuant () const inline
Definition at line 281 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::positionQuant().
setOffsetRef()
void casacore::MSAntennaColumns::setOffsetRef (MPosition::Types ref)
set the position type for the OFFSET column.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
setPositionRef()
void casacore::MSAntennaColumns::setPositionRef (MPosition::Types ref)
set the position type for the POSITION column.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
station() [1/2]
ScalarColumn<String>& casacore::MSAntennaColumns::station () inline
Definition at line 250 of file MSAntennaColumns.h.
References station_p.
station() [2/2]
const ROScalarColumn<String>& casacore::MSAntennaColumns::station () const inline
Definition at line 285 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::station().
type() [1/2]
ScalarColumn<String>& casacore::MSAntennaColumns::type () inline
Definition at line 251 of file MSAntennaColumns.h.
References type_p.
type() [2/2]
const ROScalarColumn<String>& casacore::MSAntennaColumns::type () const inline
Definition at line 287 of file MSAntennaColumns.h.
References casacore::ROMSAntennaColumns::type().
Member Data Documentation
dishDiameter_p
ScalarColumn<Double> casacore::MSAntennaColumns::dishDiameter_p private
Definition at line 329 of file MSAntennaColumns.h.
Referenced by dishDiameter().
dishDiameterQuant_p
ScalarQuantColumn<Double> casacore::MSAntennaColumns::dishDiameterQuant_p private
Definition at line 347 of file MSAntennaColumns.h.
Referenced by dishDiameterQuant().
flagRow_p
ScalarColumn<Bool> casacore::MSAntennaColumns::flagRow_p private
Definition at line 330 of file MSAntennaColumns.h.
Referenced by flagRow().
meanOrbit_p
ArrayColumn<Double> casacore::MSAntennaColumns::meanOrbit_p private
Definition at line 338 of file MSAntennaColumns.h.
Referenced by meanOrbit().
mount_p
ScalarColumn<String> casacore::MSAntennaColumns::mount_p private
Definition at line 331 of file MSAntennaColumns.h.
Referenced by mount().
name_p
ScalarColumn<String> casacore::MSAntennaColumns::name_p private
Definition at line 332 of file MSAntennaColumns.h.
Referenced by name().
offset_p
ArrayColumn<Double> casacore::MSAntennaColumns::offset_p private
Definition at line 333 of file MSAntennaColumns.h.
Referenced by offset().
offsetMeas_p
ScalarMeasColumn<MPosition> casacore::MSAntennaColumns::offsetMeas_p private
Definition at line 343 of file MSAntennaColumns.h.
Referenced by offsetMeas().
offsetQuant_p
ArrayQuantColumn<Double> casacore::MSAntennaColumns::offsetQuant_p private
Definition at line 348 of file MSAntennaColumns.h.
Referenced by offsetQuant().
orbitId_p
ScalarColumn<Int> casacore::MSAntennaColumns::orbitId_p private
Definition at line 339 of file MSAntennaColumns.h.
Referenced by orbitId().
phasedArrayId_p
ScalarColumn<Int> casacore::MSAntennaColumns::phasedArrayId_p private
Definition at line 340 of file MSAntennaColumns.h.
Referenced by phasedArrayId().
position_p
ArrayColumn<Double> casacore::MSAntennaColumns::position_p private
Definition at line 334 of file MSAntennaColumns.h.
Referenced by position().
positionMeas_p
ScalarMeasColumn<MPosition> casacore::MSAntennaColumns::positionMeas_p private
Definition at line 344 of file MSAntennaColumns.h.
Referenced by positionMeas().
positionQuant_p
ArrayQuantColumn<Double> casacore::MSAntennaColumns::positionQuant_p private
Definition at line 349 of file MSAntennaColumns.h.
Referenced by positionQuant().
station_p
ScalarColumn<String> casacore::MSAntennaColumns::station_p private
Definition at line 335 of file MSAntennaColumns.h.
Referenced by station().
type_p
ScalarColumn<String> casacore::MSAntennaColumns::type_p private
Definition at line 336 of file MSAntennaColumns.h.
Referenced by type().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSAntennaColumns.h