casacore: casacore::MSMainColInterface Class Reference
casacore::MSMainColInterface Class Reference
#include <MSSelectableMainColumn.h>
Public Member Functions
MSMainColInterface ()
MSMainColInterface (const Table &msAsTable)
virtual ~MSMainColInterface ()
virtual void init (const Table &msAsTable)
virtual const ROArrayColumn
< Bool > & flag ()
virtual Bool flagRow (const Int &i)
virtual Bool flagRow(const Int& i) {return allTrue(msCols_p->flag()(i));}
virtual const
ROScalarQuantColumn< Double > & exposureQuant ()
virtual const
ROScalarQuantColumn< Double > & timeQuant ()
virtual const MeasurementSet * asMS ()
Public Member Functions inherited from casacore::MSSelectableMainColumn
MSSelectableMainColumn (const Table &msLikeTable)
MSSelectableMainColumn ()
virtual ~MSSelectableMainColumn ()
const Table * table ()
Private Attributes
MeasurementSet ms_p
ROMSMainColumns * msCols_p
Additional Inherited Members
Protected Attributes inherited from casacore::MSSelectableMainColumn
const Table * table_p
Detailed Description
Definition at line 65 of file MSSelectableMainColumn.h.
Constructor & Destructor Documentation
casacore::MSMainColInterface::MSMainColInterface () inline
Definition at line 68 of file MSSelectableMainColumn.h.
casacore::MSMainColInterface::MSMainColInterface (const Table & msAsTable) inline
Definition at line 69 of file MSSelectableMainColumn.h.
References init().
virtual casacore::MSMainColInterface::~MSMainColInterface () inline virtual
Definition at line 72 of file MSSelectableMainColumn.h.
References msCols_p.
Member Function Documentation
virtual const MeasurementSet* casacore::MSMainColInterface::asMS () inline virtual
Implements casacore::MSSelectableMainColumn.
Definition at line 83 of file MSSelectableMainColumn.h.
References casacore::MSSelectableMainColumn::table().
virtual const ROScalarQuantColumn<Double>& casacore::MSMainColInterface::exposureQuant () inline virtual
Implements casacore::MSSelectableMainColumn.
Definition at line 80 of file MSSelectableMainColumn.h.
References casacore::ROMSMainColumns::exposureQuant(), and msCols_p.
virtual const ROArrayColumn<Bool>& casacore::MSMainColInterface::flag () inline virtual
Implements casacore::MSSelectableMainColumn.
Definition at line 76 of file MSSelectableMainColumn.h.
References casacore::ROMSMainColumns::flag(), and msCols_p.
virtual Bool casacore::MSMainColInterface::flagRow (const Int & i) inline virtual
virtual Bool flagRow(const Int& i) {return allTrue(msCols_p->flag()(i));}
Implements casacore::MSSelectableMainColumn.
Definition at line 79 of file MSSelectableMainColumn.h.
References casacore::ROMSMainColumns::flagRow(), and msCols_p.
virtual void casacore::MSMainColInterface::init (const Table & msAsTable) inline virtual
Reimplemented from casacore::MSSelectableMainColumn.
Definition at line 74 of file MSSelectableMainColumn.h.
References casacore::MSSelectableMainColumn::init(), ms_p, and msCols_p.
Referenced by MSMainColInterface().
virtual const ROScalarQuantColumn<Double>& casacore::MSMainColInterface::timeQuant () inline virtual
Implements casacore::MSSelectableMainColumn.
Definition at line 81 of file MSSelectableMainColumn.h.
References msCols_p, and casacore::ROMSMainColumns::timeQuant().
Member Data Documentation
MeasurementSet casacore::MSMainColInterface::ms_p private
Definition at line 85 of file MSSelectableMainColumn.h.
Referenced by init().
ROMSMainColumns* casacore::MSMainColInterface::msCols_p private
Definition at line 86 of file MSSelectableMainColumn.h.
Referenced by exposureQuant(), flag(), flagRow(), init(), timeQuant(), and ~MSMainColInterface().
The documentation for this class was generated from the following file:
ms/MSSel/MSSelectableMainColumn.h