casacore: casacore::HDF5HidDataType Class Reference
casacore::HDF5HidDataType Class Reference
casa package (libcasa_casa) » HDF5_module » HDF5_module_internal_classes
A class representing an HDF5 datatype hid.
#include <HDF5HidMeta.h>
Public Member Functions
HDF5HidDataType ()
Default constructor sets hid to invalid.
HDF5HidDataType (hid_t hid)
Construct from given hid.
HDF5HidDataType (const HDF5HidDataType &that)
Copy constructor makes a deep copy.
~HDF5HidDataType ()
The destructor closes the hid.
HDF5HidDataType & operator= (const HDF5HidDataType &that)
Assignment makes a deep copy.
void close ()
Close the hid if valid.
void operator= (hid_t hid)
Put hid in it.
hid_t getHid () const
Get the hid.
operator hid_t () const
Convert automatically to hid_t.
Private Attributes
hid_t itsHid
Detailed Description
A class representing an HDF5 datatype hid.
Intended use:
Internal
Review Status
Test programs:
tHDF5Dataset
Synopsis
This class wraps an HDF5 datatype hid (hdf5 id). It offers two benefits:
The most important is resource management. In case of an exception, the hid will automatically be closed by the destructor.
A hid is a kind of pointer and should not be copied. These classes forbid making a copy, but make it possible to use them in a shared pointer context.
Definition at line 102 of file HDF5HidMeta.h.
Constructor & Destructor Documentation
HDF5HidDataType() [1/3]
casacore::HDF5HidDataType::HDF5HidDataType () inline
Default constructor sets hid to invalid.
Definition at line 106 of file HDF5HidMeta.h.
HDF5HidDataType() [2/3]
casacore::HDF5HidDataType::HDF5HidDataType (hid_t hid) inline
Construct from given hid.
Definition at line 109 of file HDF5HidMeta.h.
HDF5HidDataType() [3/3]
casacore::HDF5HidDataType::HDF5HidDataType (const HDF5HidDataType & that)
Copy constructor makes a deep copy.
~HDF5HidDataType()
casacore::HDF5HidDataType::~HDF5HidDataType () inline
The destructor closes the hid.
Definition at line 114 of file HDF5HidMeta.h.
References close().
Member Function Documentation
close()
void casacore::HDF5HidDataType::close ()
Close the hid if valid.
Referenced by operator=(), and ~HDF5HidDataType().
getHid()
hid_t casacore::HDF5HidDataType::getHid () const inline
Get the hid.
Definition at line 124 of file HDF5HidMeta.h.
References itsHid.
operator hid_t()
casacore::HDF5HidDataType::operator hid_t () const inline
Convert automatically to hid_t.
Definition at line 127 of file HDF5HidMeta.h.
References itsHid.
operator=() [1/2]
HDF5HidDataType& casacore::HDF5HidDataType::operator= (const HDF5HidDataType & that)
Assignment makes a deep copy.
operator=() [2/2]
void casacore::HDF5HidDataType::operator= (hid_t hid) inline
Put hid in it.
If it already contains a hid, it will be closed.
Definition at line 121 of file HDF5HidMeta.h.
References close(), and itsHid.
Member Data Documentation
itsHid
hid_t casacore::HDF5HidDataType::itsHid private
Definition at line 130 of file HDF5HidMeta.h.
Referenced by getHid(), operator hid_t(), and operator=().
The documentation for this class was generated from the following file:
casa/HDF5/HDF5HidMeta.h