casacore: casacore::TableAttr Class Reference
casacore::TableAttr Class Reference
tables package (libcasa_tables) » Tables_module » Tables_module_internal_classes
Some attributes of a table.
#include <TableAttr.h>
Public Member Functions
TableAttr ()
Default constructor results in empty name.
TableAttr (const Table &table)
Construct the attributes from the table.
TableAttr (const String &name, Bool openWritable=False)
Construct with given values.
TableAttr (const String &name, Bool openWritable, const TableLock &)
TableAttr (const TableAttr &that)
Copy constructor (copy semantics).
TableAttr & operator= (const TableAttr &that)
Assignment (copy semantics).
TableAttr & operator= (const Table &table)
~TableAttr ()
void set (const Table &table)
Set the object to for another table.
void setRW ()
Set the keyword to read/write access.
void setName (const String &name)
const String & name () const
Get info.
Bool openWritable () const
const TableLock & lockOptions () const
Private Attributes
String name_p
Bool openWritable_p
TableLock lockOptions_p
Detailed Description
Some attributes of a table.
Intended use:
Internal
Review Status
Reviewed By:
Mark Wieringa
Date Reviewed:
1996/04/15
Test programs:
tTableRecord
Prerequisite
TableRecord
Table
Synopsis
This class holds some attributes of a table. These attributes are name, readable/writable, and lock options.
The primary use of the class is to be able to pass the various attributes of the parent table to its subtables (e.g. in classes like TableRecord and TableKeyword).
Motivation
This class makes it possible to have more attributes without having to alter the classes using subtables.
Definition at line 77 of file TableAttr.h.
Constructor & Destructor Documentation
TableAttr() [1/5]
casacore::TableAttr::TableAttr ()
Default constructor results in empty name.
TableAttr() [2/5]
casacore::TableAttr::TableAttr (const Table & table) explicit
Construct the attributes from the table.
TableAttr() [3/5]
casacore::TableAttr::TableAttr (const String & name, Bool openWritable = False) explicit
Construct with given values.
TableAttr() [4/5]
casacore::TableAttr::TableAttr (const String & name, Bool openWritable, const TableLock &)
TableAttr() [5/5]
casacore::TableAttr::TableAttr (const TableAttr & that)
Copy constructor (copy semantics).
~TableAttr()
casacore::TableAttr::~TableAttr ()
Member Function Documentation
lockOptions()
const TableLock& casacore::TableAttr::lockOptions () const inline
Definition at line 119 of file TableAttr.h.
References lockOptions_p.
name()
const String& casacore::TableAttr::name () const inline
Get info.
Definition at line 115 of file TableAttr.h.
References name_p.
Referenced by setName(), and casacore::TableKeyword::tableName().
openWritable()
Bool casacore::TableAttr::openWritable () const inline
Definition at line 117 of file TableAttr.h.
References openWritable_p.
operator=() [1/2]
TableAttr& casacore::TableAttr::operator= (const TableAttr & that)
Assignment (copy semantics).
operator=() [2/2]
TableAttr& casacore::TableAttr::operator= (const Table & table)
set()
void casacore::TableAttr::set (const Table & table)
Set the object to for another table.
setName()
void casacore::TableAttr::setName (const String & name) inline
Definition at line 110 of file TableAttr.h.
References name(), and name_p.
setRW()
void casacore::TableAttr::setRW () inline
Set the keyword to read/write access.
Definition at line 107 of file TableAttr.h.
References openWritable_p, and casacore::True.
Member Data Documentation
lockOptions_p
TableLock casacore::TableAttr::lockOptions_p private
Definition at line 126 of file TableAttr.h.
Referenced by lockOptions().
name_p
String casacore::TableAttr::name_p private
Definition at line 124 of file TableAttr.h.
Referenced by name(), and setName().
openWritable_p
Bool casacore::TableAttr::openWritable_p private
Definition at line 125 of file TableAttr.h.
Referenced by openWritable(), and setRW().
The documentation for this class was generated from the following file:
tables/Tables/TableAttr.h