casacore: casacore::MSHistoryColumns Class Reference
casacore::MSHistoryColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSHistory columns.
#include <MSHistoryColumns.h>
Public Member Functions
MSHistoryColumns (MSHistory &msHistory)
Create a columns object that accesses the data in the specified Table.
~MSHistoryColumns ()
The destructor does nothing special.
ScalarColumn< String > & application ()
Read-write access to required columns.
ArrayColumn< String > & appParams ()
ArrayColumn< String > & cliCommand ()
ScalarColumn< String > & message ()
ScalarColumn< Int > & objectId ()
ScalarColumn< Int > & observationId ()
ScalarColumn< String > & origin ()
ScalarColumn< String > & priority ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
const ROScalarColumn< String > & application () const
Read-only access to required columns.
const ROArrayColumn< String > & appParams () const
const ROArrayColumn< String > & cliCommand () const
const ROScalarColumn< String > & message () const
const ROScalarColumn< Int > & objectId () const
const ROScalarColumn< Int > & observationId () const
const ROScalarColumn< String > & origin () const
const ROScalarColumn< String > & priority () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME column.
Public Member Functions inherited from casacore::ROMSHistoryColumns
ROMSHistoryColumns (const MSHistory &msHistory)
Create a columns object that accesses the data in the specified Table.
~ROMSHistoryColumns ()
The destructor does nothing special.
const ROScalarColumn< String > & application () const
Access to required columns.
const ROArrayColumn< String > & appParams () const
const ROArrayColumn< String > & cliCommand () const
const ROScalarColumn< String > & message () const
const ROScalarColumn< Int > & objectId () const
const ROScalarColumn< Int > & observationId () const
const ROScalarColumn< String > & origin () const
const ROScalarColumn< String > & priority () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSHistoryColumns ()
void attach (MSHistory &msHistory)
Protected Member Functions inherited from casacore::ROMSHistoryColumns
ROMSHistoryColumns ()
void attach (const MSHistory &msHistory)
Private Member Functions
MSHistoryColumns (const MSHistoryColumns &)
MSHistoryColumns & operator= (const MSHistoryColumns &)
Private Attributes
ScalarColumn< String > application_p
ArrayColumn< String > appParams_p
ArrayColumn< String > cliCommand_p
ScalarColumn< String > message_p
ScalarColumn< Int > objectId_p
ScalarColumn< Int > observationId_p
ScalarColumn< String > origin_p
ScalarColumn< String > priority_p
ScalarColumn< Double > time_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarQuantColumn< Double > timeQuant_p
Detailed Description
A class to provide easy read-write access to MSHistory columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSHistory
ArrayColumn
ScalarColumn
Etymology
MSHistoryColumns stands for MeasurementSet History Table columns.
Synopsis
This class provides access to the columns in the MSHistory Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Note by GvD 28-Jan-2010: According to note 229 the OBJECTID column should contain Strings. It is, however, defined as Int. It has to be left as such, otherwise older MeasurementSets cannot be read anymore.
Motivation
See MSColumns for the motivation.
Definition at line 173 of file MSHistoryColumns.h.
Constructor & Destructor Documentation
MSHistoryColumns() [1/3]
casacore::MSHistoryColumns::MSHistoryColumns (MSHistory & msHistory)
Create a columns object that accesses the data in the specified Table.
~MSHistoryColumns()
casacore::MSHistoryColumns::~MSHistoryColumns ()
The destructor does nothing special.
MSHistoryColumns() [2/3]
casacore::MSHistoryColumns::MSHistoryColumns () protected
MSHistoryColumns() [3/3]
casacore::MSHistoryColumns::MSHistoryColumns (const MSHistoryColumns &) private
Member Function Documentation
application() [1/2]
ScalarColumn<String>& casacore::MSHistoryColumns::application () inline
Read-write access to required columns.
Definition at line 184 of file MSHistoryColumns.h.
References application_p.
application() [2/2]
const ROScalarColumn<String>& casacore::MSHistoryColumns::application () const inline
Read-only access to required columns.
Definition at line 199 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::application().
appParams() [1/2]
ArrayColumn<String>& casacore::MSHistoryColumns::appParams () inline
Definition at line 185 of file MSHistoryColumns.h.
References appParams_p.
appParams() [2/2]
const ROArrayColumn<String>& casacore::MSHistoryColumns::appParams () const inline
Definition at line 201 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::appParams().
attach()
void casacore::MSHistoryColumns::attach (MSHistory & msHistory) protected
cliCommand() [1/2]
ArrayColumn<String>& casacore::MSHistoryColumns::cliCommand () inline
Definition at line 186 of file MSHistoryColumns.h.
References cliCommand_p.
cliCommand() [2/2]
const ROArrayColumn<String>& casacore::MSHistoryColumns::cliCommand () const inline
Definition at line 203 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::cliCommand().
message() [1/2]
ScalarColumn<String>& casacore::MSHistoryColumns::message () inline
Definition at line 187 of file MSHistoryColumns.h.
References message_p.
message() [2/2]
const ROScalarColumn<String>& casacore::MSHistoryColumns::message () const inline
Definition at line 205 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::message().
objectId() [1/2]
ScalarColumn<Int>& casacore::MSHistoryColumns::objectId () inline
Definition at line 188 of file MSHistoryColumns.h.
References objectId_p.
objectId() [2/2]
const ROScalarColumn<Int>& casacore::MSHistoryColumns::objectId () const inline
Definition at line 207 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::objectId().
observationId() [1/2]
ScalarColumn<Int>& casacore::MSHistoryColumns::observationId () inline
Definition at line 189 of file MSHistoryColumns.h.
References observationId_p.
observationId() [2/2]
const ROScalarColumn<Int>& casacore::MSHistoryColumns::observationId () const inline
Definition at line 209 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::observationId().
operator=()
MSHistoryColumns& casacore::MSHistoryColumns::operator= (const MSHistoryColumns &) private
origin() [1/2]
ScalarColumn<String>& casacore::MSHistoryColumns::origin () inline
Definition at line 190 of file MSHistoryColumns.h.
References origin_p.
origin() [2/2]
const ROScalarColumn<String>& casacore::MSHistoryColumns::origin () const inline
Definition at line 211 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::origin().
priority() [1/2]
ScalarColumn<String>& casacore::MSHistoryColumns::priority () inline
Definition at line 191 of file MSHistoryColumns.h.
References priority_p.
priority() [2/2]
const ROScalarColumn<String>& casacore::MSHistoryColumns::priority () const inline
Definition at line 213 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::priority().
setEpochRef()
void casacore::MSHistoryColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
time() [1/2]
ScalarColumn<Double>& casacore::MSHistoryColumns::time () inline
Definition at line 192 of file MSHistoryColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSHistoryColumns::time () const inline
Definition at line 215 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSHistoryColumns::timeMeas () inline
Definition at line 194 of file MSHistoryColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSHistoryColumns::timeMeas () const inline
Definition at line 219 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSHistoryColumns::timeQuant () inline
Definition at line 193 of file MSHistoryColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSHistoryColumns::timeQuant () const inline
Definition at line 217 of file MSHistoryColumns.h.
References casacore::ROMSHistoryColumns::timeQuant().
Member Data Documentation
application_p
ScalarColumn<String> casacore::MSHistoryColumns::application_p private
Definition at line 249 of file MSHistoryColumns.h.
Referenced by application().
appParams_p
ArrayColumn<String> casacore::MSHistoryColumns::appParams_p private
Definition at line 250 of file MSHistoryColumns.h.
Referenced by appParams().
cliCommand_p
ArrayColumn<String> casacore::MSHistoryColumns::cliCommand_p private
Definition at line 251 of file MSHistoryColumns.h.
Referenced by cliCommand().
message_p
ScalarColumn<String> casacore::MSHistoryColumns::message_p private
Definition at line 252 of file MSHistoryColumns.h.
Referenced by message().
objectId_p
ScalarColumn<Int> casacore::MSHistoryColumns::objectId_p private
Definition at line 253 of file MSHistoryColumns.h.
Referenced by objectId().
observationId_p
ScalarColumn<Int> casacore::MSHistoryColumns::observationId_p private
Definition at line 254 of file MSHistoryColumns.h.
Referenced by observationId().
origin_p
ScalarColumn<String> casacore::MSHistoryColumns::origin_p private
Definition at line 255 of file MSHistoryColumns.h.
Referenced by origin().
priority_p
ScalarColumn<String> casacore::MSHistoryColumns::priority_p private
Definition at line 256 of file MSHistoryColumns.h.
Referenced by priority().
time_p
ScalarColumn<Double> casacore::MSHistoryColumns::time_p private
Definition at line 257 of file MSHistoryColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSHistoryColumns::timeMeas_p private
Definition at line 260 of file MSHistoryColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSHistoryColumns::timeQuant_p private
Definition at line 263 of file MSHistoryColumns.h.
Referenced by timeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSHistoryColumns.h