casacore: casacore::MSObservationColumns Class Reference
casacore::MSObservationColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSObservation columns.
#include <MSObsColumns.h>
Public Member Functions
MSObservationColumns (MSObservation &msObservation)
Create a columns object that accesses the data in the specified Table.
~MSObservationColumns ()
The desctructor does nothing special.
ScalarColumn< Bool > & flagRow ()
Read-write access to required columns.
ArrayColumn< String > & log ()
ScalarColumn< String > & observer ()
ScalarColumn< String > & project ()
ScalarColumn< Double > & releaseDate ()
ScalarQuantColumn< Double > & releaseDateQuant ()
ScalarMeasColumn< MEpoch > & releaseDateMeas ()
ArrayColumn< String > & schedule ()
ScalarColumn< String > & scheduleType ()
ScalarColumn< String > & telescopeName ()
ArrayColumn< Double > & timeRange ()
ArrayQuantColumn< Double > & timeRangeQuant ()
ArrayMeasColumn< MEpoch > & timeRangeMeas ()
const ROScalarColumn< Bool > & flagRow () const
Read-only access to required columns.
const ROArrayColumn< String > & log () const
const ROScalarColumn< String > & observer () const
const ROScalarColumn< String > & project () const
const ROScalarColumn< Double > & releaseDate () const
const ROScalarQuantColumn< Double > & releaseDateQuant () const
const ROScalarMeasColumn< MEpoch > & releaseDateMeas () const
const ROArrayColumn< String > & schedule () const
const ROScalarColumn< String > & scheduleType () const
const ROScalarColumn< String > & telescopeName () const
const ROArrayColumn< Double > & timeRange () const
const ROArrayQuantColumn< Double > & timeRangeQuant () const
const ROArrayMeasColumn< MEpoch > & timeRangeMeas () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME_RANGE & RELEASE_DATE columns.
Public Member Functions inherited from casacore::ROMSObservationColumns
ROMSObservationColumns (const MSObservation &msObservation)
Create a columns object that accesses the data in the specified Table.
~ROMSObservationColumns ()
The destructor does nothing special.
const ROScalarColumn< Bool > & flagRow () const
Access to required columns.
const ROArrayColumn< String > & log () const
const ROScalarColumn< String > & observer () const
const ROScalarColumn< String > & project () const
const ROScalarColumn< Double > & releaseDate () const
const ROScalarQuantColumn< Double > & releaseDateQuant () const
const ROScalarMeasColumn< MEpoch > & releaseDateMeas () const
const ROArrayColumn< String > & schedule () const
const ROScalarColumn< String > & scheduleType () const
const ROScalarColumn< String > & telescopeName () const
const ROArrayColumn< Double > & timeRange () const
const ROArrayQuantColumn< Double > & timeRangeQuant () const
const ROArrayMeasColumn< MEpoch > & timeRangeMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSObservationColumns ()
void attach (MSObservation &msObservation)
Protected Member Functions inherited from casacore::ROMSObservationColumns
ROMSObservationColumns ()
void attach (const MSObservation &msObservation)
Private Member Functions
MSObservationColumns (const MSObservationColumns &)
MSObservationColumns & operator= (const MSObservationColumns &)
Private Attributes
ScalarColumn< Bool > flagRow_p
ArrayColumn< String > log_p
ScalarColumn< String > observer_p
ScalarColumn< String > project_p
ScalarColumn< Double > releaseDate_p
ArrayColumn< String > schedule_p
ScalarColumn< String > scheduleType_p
ScalarColumn< String > telescopeName_p
ArrayColumn< Double > timeRange_p
ScalarMeasColumn< MEpoch > releaseDateMeas_p
ArrayMeasColumn< MEpoch > timeRangeMeas_p
ScalarQuantColumn< Double > releaseDateQuant_p
ArrayQuantColumn< Double > timeRangeQuant_p
Detailed Description
A class to provide easy read-write access to MSObservation columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSObservation
ArrayColumn
ScalarColumn
Etymology
MSObservationColumns stands for MeasurementSet Observation Table columns.
Synopsis
This class provides access to the columns in the MSObservation Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 181 of file MSObsColumns.h.
Constructor & Destructor Documentation
MSObservationColumns() [1/3]
casacore::MSObservationColumns::MSObservationColumns (MSObservation & msObservation)
Create a columns object that accesses the data in the specified Table.
~MSObservationColumns()
casacore::MSObservationColumns::~MSObservationColumns ()
The desctructor does nothing special.
MSObservationColumns() [2/3]
casacore::MSObservationColumns::MSObservationColumns () protected
MSObservationColumns() [3/3]
casacore::MSObservationColumns::MSObservationColumns (const MSObservationColumns &) private
Member Function Documentation
attach()
void casacore::MSObservationColumns::attach (MSObservation & msObservation) protected
flagRow() [1/2]
ScalarColumn<Bool>& casacore::MSObservationColumns::flagRow () inline
Read-write access to required columns.
Definition at line 192 of file MSObsColumns.h.
References flagRow_p.
flagRow() [2/2]
const ROScalarColumn<Bool>& casacore::MSObservationColumns::flagRow () const inline
Read-only access to required columns.
Definition at line 209 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::flagRow().
log() [1/2]
ArrayColumn<String>& casacore::MSObservationColumns::log () inline
Definition at line 193 of file MSObsColumns.h.
References log_p.
log() [2/2]
const ROArrayColumn<String>& casacore::MSObservationColumns::log () const inline
Definition at line 211 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::log().
observer() [1/2]
ScalarColumn<String>& casacore::MSObservationColumns::observer () inline
Definition at line 194 of file MSObsColumns.h.
References observer_p.
observer() [2/2]
const ROScalarColumn<String>& casacore::MSObservationColumns::observer () const inline
Definition at line 213 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::observer().
operator=()
MSObservationColumns& casacore::MSObservationColumns::operator= (const MSObservationColumns &) private
project() [1/2]
ScalarColumn<String>& casacore::MSObservationColumns::project () inline
Definition at line 195 of file MSObsColumns.h.
References project_p.
project() [2/2]
const ROScalarColumn<String>& casacore::MSObservationColumns::project () const inline
Definition at line 215 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::project().
releaseDate() [1/2]
ScalarColumn<Double>& casacore::MSObservationColumns::releaseDate () inline
Definition at line 196 of file MSObsColumns.h.
References releaseDate_p.
releaseDate() [2/2]
const ROScalarColumn<Double>& casacore::MSObservationColumns::releaseDate () const inline
Definition at line 217 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::releaseDate().
releaseDateMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSObservationColumns::releaseDateMeas () inline
Definition at line 198 of file MSObsColumns.h.
References releaseDateMeas_p.
releaseDateMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSObservationColumns::releaseDateMeas () const inline
Definition at line 221 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::releaseDateMeas().
releaseDateQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSObservationColumns::releaseDateQuant () inline
Definition at line 197 of file MSObsColumns.h.
References releaseDateQuant_p.
releaseDateQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSObservationColumns::releaseDateQuant () const inline
Definition at line 219 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::releaseDateQuant().
schedule() [1/2]
ArrayColumn<String>& casacore::MSObservationColumns::schedule () inline
Definition at line 199 of file MSObsColumns.h.
References schedule_p.
schedule() [2/2]
const ROArrayColumn<String>& casacore::MSObservationColumns::schedule () const inline
Definition at line 223 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::schedule().
scheduleType() [1/2]
ScalarColumn<String>& casacore::MSObservationColumns::scheduleType () inline
Definition at line 200 of file MSObsColumns.h.
References scheduleType_p.
scheduleType() [2/2]
const ROScalarColumn<String>& casacore::MSObservationColumns::scheduleType () const inline
Definition at line 225 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::scheduleType().
setEpochRef()
void casacore::MSObservationColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME_RANGE & RELEASE_DATE columns.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
telescopeName() [1/2]
ScalarColumn<String>& casacore::MSObservationColumns::telescopeName () inline
Definition at line 201 of file MSObsColumns.h.
References telescopeName_p.
telescopeName() [2/2]
const ROScalarColumn<String>& casacore::MSObservationColumns::telescopeName () const inline
Definition at line 227 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::telescopeName().
timeRange() [1/2]
ArrayColumn<Double>& casacore::MSObservationColumns::timeRange () inline
Definition at line 202 of file MSObsColumns.h.
References timeRange_p.
timeRange() [2/2]
const ROArrayColumn<Double>& casacore::MSObservationColumns::timeRange () const inline
Definition at line 229 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::timeRange().
timeRangeMeas() [1/2]
ArrayMeasColumn<MEpoch>& casacore::MSObservationColumns::timeRangeMeas () inline
Definition at line 204 of file MSObsColumns.h.
References timeRangeMeas_p.
timeRangeMeas() [2/2]
const ROArrayMeasColumn<MEpoch>& casacore::MSObservationColumns::timeRangeMeas () const inline
Definition at line 233 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::timeRangeMeas().
timeRangeQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSObservationColumns::timeRangeQuant () inline
Definition at line 203 of file MSObsColumns.h.
References timeRangeQuant_p.
timeRangeQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSObservationColumns::timeRangeQuant () const inline
Definition at line 231 of file MSObsColumns.h.
References casacore::ROMSObservationColumns::timeRangeQuant().
Member Data Documentation
flagRow_p
ScalarColumn<Bool> casacore::MSObservationColumns::flagRow_p private
Definition at line 263 of file MSObsColumns.h.
Referenced by flagRow().
log_p
ArrayColumn<String> casacore::MSObservationColumns::log_p private
Definition at line 264 of file MSObsColumns.h.
Referenced by log().
observer_p
ScalarColumn<String> casacore::MSObservationColumns::observer_p private
Definition at line 265 of file MSObsColumns.h.
Referenced by observer().
project_p
ScalarColumn<String> casacore::MSObservationColumns::project_p private
Definition at line 266 of file MSObsColumns.h.
Referenced by project().
releaseDate_p
ScalarColumn<Double> casacore::MSObservationColumns::releaseDate_p private
Definition at line 267 of file MSObsColumns.h.
Referenced by releaseDate().
releaseDateMeas_p
ScalarMeasColumn<MEpoch> casacore::MSObservationColumns::releaseDateMeas_p private
Definition at line 274 of file MSObsColumns.h.
Referenced by releaseDateMeas().
releaseDateQuant_p
ScalarQuantColumn<Double> casacore::MSObservationColumns::releaseDateQuant_p private
Definition at line 278 of file MSObsColumns.h.
Referenced by releaseDateQuant().
schedule_p
ArrayColumn<String> casacore::MSObservationColumns::schedule_p private
Definition at line 268 of file MSObsColumns.h.
Referenced by schedule().
scheduleType_p
ScalarColumn<String> casacore::MSObservationColumns::scheduleType_p private
Definition at line 269 of file MSObsColumns.h.
Referenced by scheduleType().
telescopeName_p
ScalarColumn<String> casacore::MSObservationColumns::telescopeName_p private
Definition at line 270 of file MSObsColumns.h.
Referenced by telescopeName().
timeRange_p
ArrayColumn<Double> casacore::MSObservationColumns::timeRange_p private
Definition at line 271 of file MSObsColumns.h.
Referenced by timeRange().
timeRangeMeas_p
ArrayMeasColumn<MEpoch> casacore::MSObservationColumns::timeRangeMeas_p private
Definition at line 275 of file MSObsColumns.h.
Referenced by timeRangeMeas().
timeRangeQuant_p
ArrayQuantColumn<Double> casacore::MSObservationColumns::timeRangeQuant_p private
Definition at line 279 of file MSObsColumns.h.
Referenced by timeRangeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSObsColumns.h