casacore: casacore::MSMainColumns Class Reference
casacore::MSMainColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class for easy read-write access to MeasurementSet main table columns.
#include <MSMainColumns.h>
Public Member Functions
MSMainColumns (MeasurementSet &ms)
Create a columns object that accesses the data in the specified Table.
~MSMainColumns ()
The desctructor does nothing special.
ScalarColumn< Int > & antenna1 ()
Read-write access to required columns.
ScalarColumn< Int > & antenna2 ()
ScalarColumn< Int > & arrayId ()
ScalarColumn< Int > & dataDescId ()
ScalarColumn< Double > & exposure ()
ScalarQuantColumn< Double > & exposureQuant ()
ScalarColumn< Int > & feed1 ()
ScalarColumn< Int > & feed2 ()
ScalarColumn< Int > & fieldId ()
ArrayColumn< Bool > & flag ()
ArrayColumn< Bool > & flagCategory ()
ScalarColumn< Bool > & flagRow ()
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< Int > & observationId ()
ScalarColumn< Int > & processorId ()
ScalarColumn< Int > & scanNumber ()
ArrayColumn< Float > & sigma ()
ScalarColumn< Int > & stateId ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
ScalarColumn< Double > & timeCentroid ()
ScalarQuantColumn< Double > & timeCentroidQuant ()
ScalarMeasColumn< MEpoch > & timeCentroidMeas ()
ArrayColumn< Double > & uvw ()
ArrayQuantColumn< Double > & uvwQuant ()
ScalarMeasColumn< Muvw > & uvwMeas ()
ArrayColumn< Float > & weight ()
ScalarColumn< Int > & antenna3 ()
Read-write access to optional columns.
ScalarColumn< Bool > & baselineRef ()
ArrayColumn< Complex > & correctedData ()
ArrayColumn< Complex > & data ()
ScalarColumn< Int > & feed3 ()
ArrayColumn< Float > & floatData ()
ArrayColumn< Float > & imagingWeight ()
ArrayColumn< Complex > & lagData ()
ArrayColumn< Complex > & modelData ()
ScalarColumn< Int > & phaseId ()
ScalarColumn< Int > & pulsarBin ()
ScalarColumn< Int > & pulsarGateId ()
ArrayColumn< Float > & sigmaSpectrum ()
ScalarColumn< Double > & timeExtraPrec ()
ScalarQuantColumn< Double > & timeExtraPrecQuant ()
ArrayColumn< Double > & uvw2 ()
ScalarMeasColumn< Muvw > & uvw2Meas ()
ArrayQuantColumn< Double > & uvw2Quant ()
ArrayColumn< Complex > & videoPoint ()
ArrayColumn< Float > & weightSpectrum ()
ArrayColumn< Float > & weightSpectrumCorrected ()
const ROScalarColumn< Int > & antenna1 () const
Read-only access to required columns.
const ROScalarColumn< Int > & antenna2 () const
const ROScalarColumn< Int > & arrayId () const
const ROScalarColumn< Int > & dataDescId () const
const ROScalarColumn< Double > & exposure () const
const ROScalarQuantColumn< Double > & exposureQuant () const
const ROScalarColumn< Int > & feed1 () const
const ROScalarColumn< Int > & feed2 () const
const ROScalarColumn< Int > & fieldId () const
const ROArrayColumn< Bool > & flag () const
const ROArrayColumn< Bool > & flagCategory () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & observationId () const
const ROScalarColumn< Int > & processorId () const
const ROScalarColumn< Int > & scanNumber () const
const ROArrayColumn< Float > & sigma () const
const ROScalarColumn< Int > & stateId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & timeCentroid () const
const ROScalarQuantColumn< Double > & timeCentroidQuant () const
const ROScalarMeasColumn< MEpoch > & timeCentroidMeas () const
const ROArrayColumn< Double > & uvw () const
const ROArrayQuantColumn< Double > & uvwQuant () const
const ROScalarMeasColumn< Muvw > & uvwMeas () const
const ROArrayColumn< Float > & weight () const
const ROScalarColumn< Int > & antenna3 () const
Read-only access to optional columns.
const ROScalarColumn< Bool > & baselineRef () const
const ROArrayColumn< Complex > & correctedData () const
const ROArrayColumn< Complex > & data () const
const ROScalarColumn< Int > & feed3 () const
const ROArrayColumn< Float > & floatData () const
const ROArrayColumn< Float > & imagingWeight () const
const ROArrayColumn< Complex > & lagData () const
const ROArrayColumn< Complex > & modelData () const
const ROScalarColumn< Int > & phaseId () const
const ROScalarColumn< Int > & pulsarBin () const
const ROScalarColumn< Int > & pulsarGateId () const
const ROArrayColumn< Float > & sigmaSpectrum () const
const ROScalarColumn< Double > & timeExtraPrec () const
const ROScalarQuantColumn< Double > & timeExtraPrecQuant () const
const ROArrayColumn< Double > & uvw2 () const
const ROScalarMeasColumn< Muvw > & uvw2Meas () const
const ROArrayQuantColumn< Double > & uvw2Quant () const
const ROArrayColumn< Complex > & videoPoint () const
const ROArrayColumn< Float > & weightSpectrum () const
const ROArrayColumn< Float > & weightSpectrumCorrected () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME and TIME_CENTROID columns.
void setUVWRef (Muvw::Types ref)
set the UVW reference type for the UVW and UVW2 (if defined) columns.
void setFlagCategories (const Vector< String > &categories)
Set the flag category labels to the supplied values (in the CATEGORY keyword of the FLAG_CATEGORY column).
Public Member Functions inherited from casacore::ROMSMainColumns
ROMSMainColumns (const MeasurementSet &ms)
Create a columns object that accesses the data in the specified Table.
~ROMSMainColumns ()
The desctructor does nothing special.
const ROScalarColumn< Int > & antenna1 () const
Access to required columns.
const ROScalarColumn< Int > & antenna2 () const
const ROScalarColumn< Int > & arrayId () const
const ROScalarColumn< Int > & dataDescId () const
const ROScalarColumn< Double > & exposure () const
const ROScalarQuantColumn< Double > & exposureQuant () const
const ROScalarColumn< Int > & feed1 () const
const ROScalarColumn< Int > & feed2 () const
const ROScalarColumn< Int > & fieldId () const
const ROArrayColumn< Bool > & flag () const
const ROArrayColumn< Bool > & flagCategory () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & observationId () const
const ROScalarColumn< Int > & processorId () const
const ROScalarColumn< Int > & scanNumber () const
const ROArrayColumn< Float > & sigma () const
const ROScalarColumn< Int > & stateId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & timeCentroid () const
const ROScalarQuantColumn< Double > & timeCentroidQuant () const
const ROScalarMeasColumn< MEpoch > & timeCentroidMeas () const
const ROArrayColumn< Double > & uvw () const
const ROArrayQuantColumn< Double > & uvwQuant () const
const ROScalarMeasColumn< Muvw > & uvwMeas () const
const ROArrayColumn< Float > & weight () const
const ROScalarColumn< Int > & antenna3 () const
Access to optional columns.
const ROScalarColumn< Bool > & baselineRef () const
const ROArrayColumn< Complex > & correctedData () const
const ROArrayColumn< Complex > & data () const
const ROScalarColumn< Int > & feed3 () const
const ROArrayColumn< Float > & floatData () const
const ROArrayColumn< Float > & imagingWeight () const
const ROArrayColumn< Complex > & lagData () const
const ROArrayColumn< Complex > & modelData () const
const ROScalarColumn< Int > & phaseId () const
const ROScalarColumn< Int > & pulsarBin () const
const ROScalarColumn< Int > & pulsarGateId () const
const ROArrayColumn< Float > & sigmaSpectrum () const
const ROScalarColumn< Double > & timeExtraPrec () const
const ROScalarQuantColumn< Double > & timeExtraPrecQuant () const
const ROArrayColumn< Double > & uvw2 () const
const ROScalarMeasColumn< Muvw > & uvw2Meas () const
const ROArrayQuantColumn< Double > & uvw2Quant () const
const ROArrayColumn< Complex > & videoPoint () const
const ROArrayColumn< Float > & weightSpectrum () const
const ROArrayColumn< Float > & weightSpectrumCorrected () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Vector< String > flagCategories () const
Returns the category labels for the FLAG_CATEGORY column.
Protected Member Functions
MSMainColumns ()
void attach (MeasurementSet &ms)
Protected Member Functions inherited from casacore::ROMSMainColumns
ROMSMainColumns ()
void attach (const MeasurementSet &ms)
Private Member Functions
MSMainColumns (const MSMainColumns &)
MSMainColumns & operator= (const MSMainColumns &)
void attachOptionalCols (MeasurementSet &ms)
Private Attributes
ScalarColumn< Int > antenna1_p
ScalarColumn< Int > antenna2_p
ScalarColumn< Int > arrayId_p
ScalarColumn< Int > dataDescId_p
ScalarColumn< Double > exposure_p
ScalarColumn< Int > feed1_p
ScalarColumn< Int > feed2_p
ScalarColumn< Int > fieldId_p
ArrayColumn< Bool > flag_p
ArrayColumn< Bool > flagCategory_p
ScalarColumn< Bool > flagRow_p
ScalarColumn< Double > interval_p
ScalarColumn< Int > observationId_p
ScalarColumn< Int > processorId_p
ScalarColumn< Int > scanNumber_p
ArrayColumn< Float > sigma_p
ScalarColumn< Int > stateId_p
ScalarColumn< Double > time_p
ScalarColumn< Double > timeCentroid_p
ArrayColumn< Double > uvw_p
ArrayColumn< Float > weight_p
ScalarColumn< Int > antenna3_p
ScalarColumn< Bool > baselineRef_p
ArrayColumn< Complex > data_p
ScalarColumn< Int > feed3_p
ArrayColumn< Float > floatData_p
ArrayColumn< Complex > lagData_p
ScalarColumn< Int > phaseId_p
ScalarColumn< Int > pulsarBin_p
ScalarColumn< Int > pulsarGateId_p
ArrayColumn< Float > sigmaSpectrum_p
ScalarColumn< Double > timeExtraPrec_p
ArrayColumn< Double > uvw2_p
ArrayColumn< Complex > videoPoint_p
ArrayColumn< Float > weightSpectrum_p
ArrayColumn< Float > weightSpectrumCorrected_p
ArrayColumn< Complex > correctedData_p
ArrayColumn< Float > imagingWeight_p
ArrayColumn< Complex > modelData_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarMeasColumn< MEpoch > timeCentroidMeas_p
ScalarMeasColumn< Muvw > uvwMeas_p
ScalarMeasColumn< Muvw > uvw2Meas_p
ScalarQuantColumn< Double > exposureQuant_p
ScalarQuantColumn< Double > intervalQuant_p
ScalarQuantColumn< Double > timeQuant_p
ScalarQuantColumn< Double > timeCentroidQuant_p
ArrayQuantColumn< Double > uvwQuant_p
ScalarQuantColumn< Double > timeExtraPrecQuant_p
ArrayQuantColumn< Double > uvw2Quant_p
Detailed Description
A class for easy read-write access to MeasurementSet main table columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MeasurementSet
ArrayColumn
ScalarColumn
Etymology
MSMainColumns stands for MeasurementSet main Table columns.
Synopsis
This class provides access to the columns in the MeasurementSet. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations.
Warning: The Table that is used to construct this class must not be destroyed (or go out of scope) before this class does; Otherwise the scalar and array columns use by this class will be left dangling;
Example
// use as follows
MeasurementSet ms("myMS",Table::Update);
MSColumns msc(ms);
// show data from row 5
cout << msc.data()(5);
// change name of antenna on row 3 in antenna table
msc.antenna().name().put(3,"NewAnt-3");
Motivation
Having to type long lists of Scalar and Array column declarations gets very tedious. This class attempts to relieve some of that tedium, while at the same time concentrating all the declarations in one place, making Type errors in the column declaration (only caught at run-time) less probable. Type errors in the use of the columns is caught at compile time.
To Do
We might decide to merge this class with the MeasurementSet
Definition at line 322 of file MSMainColumns.h.
Constructor & Destructor Documentation
MSMainColumns() [1/3]
casacore::MSMainColumns::MSMainColumns (MeasurementSet & ms)
Create a columns object that accesses the data in the specified Table.
~MSMainColumns()
casacore::MSMainColumns::~MSMainColumns ()
The desctructor does nothing special.
MSMainColumns() [2/3]
casacore::MSMainColumns::MSMainColumns () protected
MSMainColumns() [3/3]
casacore::MSMainColumns::MSMainColumns (const MSMainColumns &) private
Member Function Documentation
antenna1() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::antenna1 () inline
Read-write access to required columns.
Definition at line 334 of file MSMainColumns.h.
References antenna1_p.
antenna1() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::antenna1 () const inline
Read-only access to required columns.
Definition at line 403 of file MSMainColumns.h.
References casacore::ROMSMainColumns::antenna1().
antenna2() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::antenna2 () inline
Definition at line 335 of file MSMainColumns.h.
References antenna2_p.
antenna2() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::antenna2 () const inline
Definition at line 405 of file MSMainColumns.h.
References casacore::ROMSMainColumns::antenna2().
antenna3() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::antenna3 () inline
Read-write access to optional columns.
Definition at line 375 of file MSMainColumns.h.
References antenna3_p.
antenna3() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::antenna3 () const inline
Read-only access to optional columns.
Definition at line 465 of file MSMainColumns.h.
References casacore::ROMSMainColumns::antenna3().
arrayId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::arrayId () inline
Definition at line 336 of file MSMainColumns.h.
References arrayId_p.
arrayId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::arrayId () const inline
Definition at line 407 of file MSMainColumns.h.
References casacore::ROMSMainColumns::arrayId().
attach()
void casacore::MSMainColumns::attach (MeasurementSet & ms) protected
attachOptionalCols()
void casacore::MSMainColumns::attachOptionalCols (MeasurementSet & ms) private
baselineRef() [1/2]
ScalarColumn<Bool>& casacore::MSMainColumns::baselineRef () inline
Definition at line 376 of file MSMainColumns.h.
References baselineRef_p.
baselineRef() [2/2]
const ROScalarColumn<Bool>& casacore::MSMainColumns::baselineRef () const inline
Definition at line 467 of file MSMainColumns.h.
References casacore::ROMSMainColumns::baselineRef().
correctedData() [1/2]
ArrayColumn<Complex>& casacore::MSMainColumns::correctedData () inline
Definition at line 377 of file MSMainColumns.h.
References correctedData_p.
correctedData() [2/2]
const ROArrayColumn<Complex>& casacore::MSMainColumns::correctedData () const inline
Definition at line 469 of file MSMainColumns.h.
References casacore::ROMSMainColumns::correctedData().
data() [1/2]
ArrayColumn<Complex>& casacore::MSMainColumns::data () inline
Definition at line 378 of file MSMainColumns.h.
References data_p.
data() [2/2]
const ROArrayColumn<Complex>& casacore::MSMainColumns::data () const inline
Definition at line 471 of file MSMainColumns.h.
References casacore::ROMSMainColumns::data().
dataDescId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::dataDescId () inline
Definition at line 337 of file MSMainColumns.h.
References dataDescId_p.
dataDescId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::dataDescId () const inline
Definition at line 409 of file MSMainColumns.h.
References casacore::ROMSMainColumns::dataDescId().
exposure() [1/2]
ScalarColumn<Double>& casacore::MSMainColumns::exposure () inline
Definition at line 338 of file MSMainColumns.h.
References exposure_p.
exposure() [2/2]
const ROScalarColumn<Double>& casacore::MSMainColumns::exposure () const inline
Definition at line 411 of file MSMainColumns.h.
References casacore::ROMSMainColumns::exposure().
exposureQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSMainColumns::exposureQuant () inline
Definition at line 339 of file MSMainColumns.h.
References exposureQuant_p.
exposureQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSMainColumns::exposureQuant () const inline
Definition at line 413 of file MSMainColumns.h.
References casacore::ROMSMainColumns::exposureQuant().
feed1() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::feed1 () inline
Definition at line 341 of file MSMainColumns.h.
References feed1_p.
feed1() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::feed1 () const inline
Definition at line 415 of file MSMainColumns.h.
References casacore::ROMSMainColumns::feed1().
feed2() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::feed2 () inline
Definition at line 342 of file MSMainColumns.h.
References feed2_p.
feed2() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::feed2 () const inline
Definition at line 417 of file MSMainColumns.h.
References casacore::ROMSMainColumns::feed2().
feed3() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::feed3 () inline
Definition at line 379 of file MSMainColumns.h.
References feed3_p.
feed3() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::feed3 () const inline
Definition at line 473 of file MSMainColumns.h.
References casacore::ROMSMainColumns::feed3().
fieldId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::fieldId () inline
Definition at line 343 of file MSMainColumns.h.
References fieldId_p.
fieldId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::fieldId () const inline
Definition at line 419 of file MSMainColumns.h.
References casacore::ROMSMainColumns::fieldId().
flag() [1/2]
ArrayColumn<Bool>& casacore::MSMainColumns::flag () inline
Definition at line 344 of file MSMainColumns.h.
References flag_p.
flag() [2/2]
const ROArrayColumn<Bool>& casacore::MSMainColumns::flag () const inline
Definition at line 421 of file MSMainColumns.h.
References casacore::ROMSMainColumns::flag().
flagCategory() [1/2]
ArrayColumn<Bool>& casacore::MSMainColumns::flagCategory () inline
Definition at line 345 of file MSMainColumns.h.
References flagCategory_p.
flagCategory() [2/2]
const ROArrayColumn<Bool>& casacore::MSMainColumns::flagCategory () const inline
Definition at line 423 of file MSMainColumns.h.
References casacore::ROMSMainColumns::flagCategory().
flagRow() [1/2]
ScalarColumn<Bool>& casacore::MSMainColumns::flagRow () inline
Definition at line 346 of file MSMainColumns.h.
References flagRow_p.
flagRow() [2/2]
const ROScalarColumn<Bool>& casacore::MSMainColumns::flagRow () const inline
Definition at line 425 of file MSMainColumns.h.
References casacore::ROMSMainColumns::flagRow().
floatData() [1/2]
ArrayColumn<Float>& casacore::MSMainColumns::floatData () inline
Definition at line 380 of file MSMainColumns.h.
References floatData_p.
floatData() [2/2]
const ROArrayColumn<Float>& casacore::MSMainColumns::floatData () const inline
Definition at line 475 of file MSMainColumns.h.
References casacore::ROMSMainColumns::floatData().
imagingWeight() [1/2]
ArrayColumn<Float>& casacore::MSMainColumns::imagingWeight () inline
Definition at line 381 of file MSMainColumns.h.
References imagingWeight_p.
imagingWeight() [2/2]
const ROArrayColumn<Float>& casacore::MSMainColumns::imagingWeight () const inline
Definition at line 477 of file MSMainColumns.h.
References casacore::ROMSMainColumns::imagingWeight().
interval() [1/2]
ScalarColumn<Double>& casacore::MSMainColumns::interval () inline
Definition at line 347 of file MSMainColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSMainColumns::interval () const inline
Definition at line 427 of file MSMainColumns.h.
References casacore::ROMSMainColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSMainColumns::intervalQuant () inline
Definition at line 348 of file MSMainColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSMainColumns::intervalQuant () const inline
Definition at line 429 of file MSMainColumns.h.
References casacore::ROMSMainColumns::intervalQuant().
lagData() [1/2]
ArrayColumn<Complex>& casacore::MSMainColumns::lagData () inline
Definition at line 382 of file MSMainColumns.h.
References lagData_p.
lagData() [2/2]
const ROArrayColumn<Complex>& casacore::MSMainColumns::lagData () const inline
Definition at line 479 of file MSMainColumns.h.
References casacore::ROMSMainColumns::lagData().
modelData() [1/2]
ArrayColumn<Complex>& casacore::MSMainColumns::modelData () inline
Definition at line 383 of file MSMainColumns.h.
References modelData_p.
modelData() [2/2]
const ROArrayColumn<Complex>& casacore::MSMainColumns::modelData () const inline
Definition at line 481 of file MSMainColumns.h.
References casacore::ROMSMainColumns::modelData().
observationId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::observationId () inline
Definition at line 350 of file MSMainColumns.h.
References observationId_p.
observationId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::observationId () const inline
Definition at line 431 of file MSMainColumns.h.
References casacore::ROMSMainColumns::observationId().
operator=()
MSMainColumns& casacore::MSMainColumns::operator= (const MSMainColumns &) private
phaseId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::phaseId () inline
Definition at line 384 of file MSMainColumns.h.
References phaseId_p.
phaseId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::phaseId () const inline
Definition at line 483 of file MSMainColumns.h.
References casacore::ROMSMainColumns::phaseId().
processorId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::processorId () inline
Definition at line 351 of file MSMainColumns.h.
References processorId_p.
processorId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::processorId () const inline
Definition at line 433 of file MSMainColumns.h.
References casacore::ROMSMainColumns::processorId().
pulsarBin() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::pulsarBin () inline
Definition at line 385 of file MSMainColumns.h.
References pulsarBin_p.
pulsarBin() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::pulsarBin () const inline
Definition at line 485 of file MSMainColumns.h.
References casacore::ROMSMainColumns::pulsarBin().
pulsarGateId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::pulsarGateId () inline
Definition at line 386 of file MSMainColumns.h.
References pulsarGateId_p.
pulsarGateId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::pulsarGateId () const inline
Definition at line 487 of file MSMainColumns.h.
References casacore::ROMSMainColumns::pulsarGateId().
scanNumber() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::scanNumber () inline
Definition at line 352 of file MSMainColumns.h.
References scanNumber_p.
scanNumber() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::scanNumber () const inline
Definition at line 435 of file MSMainColumns.h.
References casacore::ROMSMainColumns::scanNumber().
setEpochRef()
void casacore::MSMainColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME and TIME_CENTROID columns.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
setFlagCategories()
void casacore::MSMainColumns::setFlagCategories (const Vector< String > & categories)
Set the flag category labels to the supplied values (in the CATEGORY keyword of the FLAG_CATEGORY column).
Throws an exception, when compiled in Debug mode, if the length of the supplied Vector is not the same as the length of the third dimension of the FLAG_CATEGORY column.
setUVWRef()
void casacore::MSMainColumns::setUVWRef (Muvw::Types ref)
set the UVW reference type for the UVW and UVW2 (if defined) columns.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
sigma() [1/2]
ArrayColumn<Float>& casacore::MSMainColumns::sigma () inline
Definition at line 353 of file MSMainColumns.h.
References sigma_p.
sigma() [2/2]
const ROArrayColumn<Float>& casacore::MSMainColumns::sigma () const inline
Definition at line 437 of file MSMainColumns.h.
References casacore::ROMSMainColumns::sigma().
sigmaSpectrum() [1/2]
ArrayColumn<Float>& casacore::MSMainColumns::sigmaSpectrum () inline
Definition at line 387 of file MSMainColumns.h.
References sigmaSpectrum_p.
sigmaSpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSMainColumns::sigmaSpectrum () const inline
Definition at line 489 of file MSMainColumns.h.
References casacore::ROMSMainColumns::sigmaSpectrum().
stateId() [1/2]
ScalarColumn<Int>& casacore::MSMainColumns::stateId () inline
Definition at line 354 of file MSMainColumns.h.
References stateId_p.
stateId() [2/2]
const ROScalarColumn<Int>& casacore::MSMainColumns::stateId () const inline
Definition at line 439 of file MSMainColumns.h.
References casacore::ROMSMainColumns::stateId().
time() [1/2]
ScalarColumn<Double>& casacore::MSMainColumns::time () inline
Definition at line 355 of file MSMainColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSMainColumns::time () const inline
Definition at line 441 of file MSMainColumns.h.
References casacore::ROMSMainColumns::time().
timeCentroid() [1/2]
ScalarColumn<Double>& casacore::MSMainColumns::timeCentroid () inline
Definition at line 360 of file MSMainColumns.h.
References timeCentroid_p.
timeCentroid() [2/2]
const ROScalarColumn<Double>& casacore::MSMainColumns::timeCentroid () const inline
Definition at line 447 of file MSMainColumns.h.
References casacore::ROMSMainColumns::timeCentroid().
timeCentroidMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSMainColumns::timeCentroidMeas () inline
Definition at line 363 of file MSMainColumns.h.
References timeCentroidMeas_p.
timeCentroidMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSMainColumns::timeCentroidMeas () const inline
Definition at line 451 of file MSMainColumns.h.
References casacore::ROMSMainColumns::timeCentroidMeas().
timeCentroidQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSMainColumns::timeCentroidQuant () inline
Definition at line 361 of file MSMainColumns.h.
References timeCentroidQuant_p.
timeCentroidQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSMainColumns::timeCentroidQuant () const inline
Definition at line 449 of file MSMainColumns.h.
References casacore::ROMSMainColumns::timeCentroidQuant().
timeExtraPrec() [1/2]
ScalarColumn<Double>& casacore::MSMainColumns::timeExtraPrec () inline
Definition at line 388 of file MSMainColumns.h.
References timeExtraPrec_p.
timeExtraPrec() [2/2]
const ROScalarColumn<Double>& casacore::MSMainColumns::timeExtraPrec () const inline
Definition at line 491 of file MSMainColumns.h.
References casacore::ROMSMainColumns::timeExtraPrec().
timeExtraPrecQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSMainColumns::timeExtraPrecQuant () inline
Definition at line 389 of file MSMainColumns.h.
References timeExtraPrecQuant_p.
timeExtraPrecQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSMainColumns::timeExtraPrecQuant () const inline
Definition at line 493 of file MSMainColumns.h.
References casacore::ROMSMainColumns::timeExtraPrecQuant().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSMainColumns::timeMeas () inline
Definition at line 358 of file MSMainColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSMainColumns::timeMeas () const inline
Definition at line 445 of file MSMainColumns.h.
References casacore::ROMSMainColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSMainColumns::timeQuant () inline
Definition at line 356 of file MSMainColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSMainColumns::timeQuant () const inline
Definition at line 443 of file MSMainColumns.h.
References casacore::ROMSMainColumns::timeQuant().
uvw() [1/2]
ArrayColumn<Double>& casacore::MSMainColumns::uvw () inline
Definition at line 365 of file MSMainColumns.h.
References uvw_p.
uvw() [2/2]
const ROArrayColumn<Double>& casacore::MSMainColumns::uvw () const inline
Definition at line 453 of file MSMainColumns.h.
References casacore::ROMSMainColumns::uvw().
uvw2() [1/2]
ArrayColumn<Double>& casacore::MSMainColumns::uvw2 () inline
Definition at line 391 of file MSMainColumns.h.
References uvw2_p.
uvw2() [2/2]
const ROArrayColumn<Double>& casacore::MSMainColumns::uvw2 () const inline
Definition at line 495 of file MSMainColumns.h.
References casacore::ROMSMainColumns::uvw2().
uvw2Meas() [1/2]
ScalarMeasColumn<Muvw>& casacore::MSMainColumns::uvw2Meas () inline
Definition at line 392 of file MSMainColumns.h.
References uvw2Meas_p.
uvw2Meas() [2/2]
const ROScalarMeasColumn<Muvw>& casacore::MSMainColumns::uvw2Meas () const inline
Definition at line 497 of file MSMainColumns.h.
References casacore::ROMSMainColumns::uvw2Meas().
uvw2Quant() [1/2]
ArrayQuantColumn<Double>& casacore::MSMainColumns::uvw2Quant () inline
Definition at line 394 of file MSMainColumns.h.
References uvw2Quant_p.
uvw2Quant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSMainColumns::uvw2Quant () const inline
Definition at line 499 of file MSMainColumns.h.
References casacore::ROMSMainColumns::uvw2Quant().
uvwMeas() [1/2]
ScalarMeasColumn<Muvw>& casacore::MSMainColumns::uvwMeas () inline
Definition at line 368 of file MSMainColumns.h.
References uvwMeas_p.
uvwMeas() [2/2]
const ROScalarMeasColumn<Muvw>& casacore::MSMainColumns::uvwMeas () const inline
Definition at line 457 of file MSMainColumns.h.
References casacore::ROMSMainColumns::uvwMeas().
uvwQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSMainColumns::uvwQuant () inline
Definition at line 366 of file MSMainColumns.h.
References uvwQuant_p.
uvwQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSMainColumns::uvwQuant () const inline
Definition at line 455 of file MSMainColumns.h.
References casacore::ROMSMainColumns::uvwQuant().
videoPoint() [1/2]
ArrayColumn<Complex>& casacore::MSMainColumns::videoPoint () inline
Definition at line 396 of file MSMainColumns.h.
References videoPoint_p.
videoPoint() [2/2]
const ROArrayColumn<Complex>& casacore::MSMainColumns::videoPoint () const inline
Definition at line 501 of file MSMainColumns.h.
References casacore::ROMSMainColumns::videoPoint().
weight() [1/2]
ArrayColumn<Float>& casacore::MSMainColumns::weight () inline
Definition at line 370 of file MSMainColumns.h.
References weight_p.
weight() [2/2]
const ROArrayColumn<Float>& casacore::MSMainColumns::weight () const inline
Definition at line 459 of file MSMainColumns.h.
References casacore::ROMSMainColumns::weight().
weightSpectrum() [1/2]
ArrayColumn<Float>& casacore::MSMainColumns::weightSpectrum () inline
Definition at line 397 of file MSMainColumns.h.
References weightSpectrum_p.
weightSpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSMainColumns::weightSpectrum () const inline
Definition at line 503 of file MSMainColumns.h.
References casacore::ROMSMainColumns::weightSpectrum().
weightSpectrumCorrected() [1/2]
ArrayColumn<Float>& casacore::MSMainColumns::weightSpectrumCorrected () inline
Definition at line 398 of file MSMainColumns.h.
References weightSpectrumCorrected_p.
weightSpectrumCorrected() [2/2]
const ROArrayColumn<Float>& casacore::MSMainColumns::weightSpectrumCorrected () const inline
Definition at line 505 of file MSMainColumns.h.
References casacore::ROMSMainColumns::weightSpectrumCorrected().
Member Data Documentation
antenna1_p
ScalarColumn<Int> casacore::MSMainColumns::antenna1_p private
Definition at line 549 of file MSMainColumns.h.
Referenced by antenna1().
antenna2_p
ScalarColumn<Int> casacore::MSMainColumns::antenna2_p private
Definition at line 550 of file MSMainColumns.h.
Referenced by antenna2().
antenna3_p
ScalarColumn<Int> casacore::MSMainColumns::antenna3_p private
Definition at line 571 of file MSMainColumns.h.
Referenced by antenna3().
arrayId_p
ScalarColumn<Int> casacore::MSMainColumns::arrayId_p private
Definition at line 551 of file MSMainColumns.h.
Referenced by arrayId().
baselineRef_p
ScalarColumn<Bool> casacore::MSMainColumns::baselineRef_p private
Definition at line 572 of file MSMainColumns.h.
Referenced by baselineRef().
correctedData_p
ArrayColumn<Complex> casacore::MSMainColumns::correctedData_p private
Definition at line 588 of file MSMainColumns.h.
Referenced by correctedData().
data_p
ArrayColumn<Complex> casacore::MSMainColumns::data_p private
Definition at line 573 of file MSMainColumns.h.
Referenced by data().
dataDescId_p
ScalarColumn<Int> casacore::MSMainColumns::dataDescId_p private
Definition at line 552 of file MSMainColumns.h.
Referenced by dataDescId().
exposure_p
ScalarColumn<Double> casacore::MSMainColumns::exposure_p private
Definition at line 553 of file MSMainColumns.h.
Referenced by exposure().
exposureQuant_p
ScalarQuantColumn<Double> casacore::MSMainColumns::exposureQuant_p private
Definition at line 600 of file MSMainColumns.h.
Referenced by exposureQuant().
feed1_p
ScalarColumn<Int> casacore::MSMainColumns::feed1_p private
Definition at line 554 of file MSMainColumns.h.
Referenced by feed1().
feed2_p
ScalarColumn<Int> casacore::MSMainColumns::feed2_p private
Definition at line 555 of file MSMainColumns.h.
Referenced by feed2().
feed3_p
ScalarColumn<Int> casacore::MSMainColumns::feed3_p private
Definition at line 574 of file MSMainColumns.h.
Referenced by feed3().
fieldId_p
ScalarColumn<Int> casacore::MSMainColumns::fieldId_p private
Definition at line 556 of file MSMainColumns.h.
Referenced by fieldId().
flag_p
ArrayColumn<Bool> casacore::MSMainColumns::flag_p private
Definition at line 557 of file MSMainColumns.h.
Referenced by flag().
flagCategory_p
ArrayColumn<Bool> casacore::MSMainColumns::flagCategory_p private
Definition at line 558 of file MSMainColumns.h.
Referenced by flagCategory().
flagRow_p
ScalarColumn<Bool> casacore::MSMainColumns::flagRow_p private
Definition at line 559 of file MSMainColumns.h.
Referenced by flagRow().
floatData_p
ArrayColumn<Float> casacore::MSMainColumns::floatData_p private
Definition at line 575 of file MSMainColumns.h.
Referenced by floatData().
imagingWeight_p
ArrayColumn<Float> casacore::MSMainColumns::imagingWeight_p private
Definition at line 589 of file MSMainColumns.h.
Referenced by imagingWeight().
interval_p
ScalarColumn<Double> casacore::MSMainColumns::interval_p private
Definition at line 560 of file MSMainColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSMainColumns::intervalQuant_p private
Definition at line 601 of file MSMainColumns.h.
Referenced by intervalQuant().
lagData_p
ArrayColumn<Complex> casacore::MSMainColumns::lagData_p private
Definition at line 576 of file MSMainColumns.h.
Referenced by lagData().
modelData_p
ArrayColumn<Complex> casacore::MSMainColumns::modelData_p private
Definition at line 590 of file MSMainColumns.h.
Referenced by modelData().
observationId_p
ScalarColumn<Int> casacore::MSMainColumns::observationId_p private
Definition at line 561 of file MSMainColumns.h.
Referenced by observationId().
phaseId_p
ScalarColumn<Int> casacore::MSMainColumns::phaseId_p private
Definition at line 577 of file MSMainColumns.h.
Referenced by phaseId().
processorId_p
ScalarColumn<Int> casacore::MSMainColumns::processorId_p private
Definition at line 562 of file MSMainColumns.h.
Referenced by processorId().
pulsarBin_p
ScalarColumn<Int> casacore::MSMainColumns::pulsarBin_p private
Definition at line 578 of file MSMainColumns.h.
Referenced by pulsarBin().
pulsarGateId_p
ScalarColumn<Int> casacore::MSMainColumns::pulsarGateId_p private
Definition at line 579 of file MSMainColumns.h.
Referenced by pulsarGateId().
scanNumber_p
ScalarColumn<Int> casacore::MSMainColumns::scanNumber_p private
Definition at line 563 of file MSMainColumns.h.
Referenced by scanNumber().
sigma_p
ArrayColumn<Float> casacore::MSMainColumns::sigma_p private
Definition at line 564 of file MSMainColumns.h.
Referenced by sigma().
sigmaSpectrum_p
ArrayColumn<Float> casacore::MSMainColumns::sigmaSpectrum_p private
Definition at line 580 of file MSMainColumns.h.
Referenced by sigmaSpectrum().
stateId_p
ScalarColumn<Int> casacore::MSMainColumns::stateId_p private
Definition at line 565 of file MSMainColumns.h.
Referenced by stateId().
time_p
ScalarColumn<Double> casacore::MSMainColumns::time_p private
Definition at line 566 of file MSMainColumns.h.
Referenced by time().
timeCentroid_p
ScalarColumn<Double> casacore::MSMainColumns::timeCentroid_p private
Definition at line 567 of file MSMainColumns.h.
Referenced by timeCentroid().
timeCentroidMeas_p
ScalarMeasColumn<MEpoch> casacore::MSMainColumns::timeCentroidMeas_p private
Definition at line 594 of file MSMainColumns.h.
Referenced by timeCentroidMeas().
timeCentroidQuant_p
ScalarQuantColumn<Double> casacore::MSMainColumns::timeCentroidQuant_p private
Definition at line 603 of file MSMainColumns.h.
Referenced by timeCentroidQuant().
timeExtraPrec_p
ScalarColumn<Double> casacore::MSMainColumns::timeExtraPrec_p private
Definition at line 581 of file MSMainColumns.h.
Referenced by timeExtraPrec().
timeExtraPrecQuant_p
ScalarQuantColumn<Double> casacore::MSMainColumns::timeExtraPrecQuant_p private
Definition at line 606 of file MSMainColumns.h.
Referenced by timeExtraPrecQuant().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSMainColumns::timeMeas_p private
Definition at line 593 of file MSMainColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSMainColumns::timeQuant_p private
Definition at line 602 of file MSMainColumns.h.
Referenced by timeQuant().
uvw2_p
ArrayColumn<Double> casacore::MSMainColumns::uvw2_p private
Definition at line 582 of file MSMainColumns.h.
Referenced by uvw2().
uvw2Meas_p
ScalarMeasColumn<Muvw> casacore::MSMainColumns::uvw2Meas_p private
Definition at line 597 of file MSMainColumns.h.
Referenced by uvw2Meas().
uvw2Quant_p
ArrayQuantColumn<Double> casacore::MSMainColumns::uvw2Quant_p private
Definition at line 607 of file MSMainColumns.h.
Referenced by uvw2Quant().
uvw_p
ArrayColumn<Double> casacore::MSMainColumns::uvw_p private
Definition at line 568 of file MSMainColumns.h.
Referenced by uvw().
uvwMeas_p
ScalarMeasColumn<Muvw> casacore::MSMainColumns::uvwMeas_p private
Definition at line 595 of file MSMainColumns.h.
Referenced by uvwMeas().
uvwQuant_p
ArrayQuantColumn<Double> casacore::MSMainColumns::uvwQuant_p private
Definition at line 604 of file MSMainColumns.h.
Referenced by uvwQuant().
videoPoint_p
ArrayColumn<Complex> casacore::MSMainColumns::videoPoint_p private
Definition at line 583 of file MSMainColumns.h.
Referenced by videoPoint().
weight_p
ArrayColumn<Float> casacore::MSMainColumns::weight_p private
Definition at line 569 of file MSMainColumns.h.
Referenced by weight().
weightSpectrum_p
ArrayColumn<Float> casacore::MSMainColumns::weightSpectrum_p private
Definition at line 584 of file MSMainColumns.h.
Referenced by weightSpectrum().
weightSpectrumCorrected_p
ArrayColumn<Float> casacore::MSMainColumns::weightSpectrumCorrected_p private
Definition at line 585 of file MSMainColumns.h.
Referenced by weightSpectrumCorrected().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSMainColumns.h