casacore: casacore::ROMSPointingColumns Class Reference
casacore::ROMSPointingColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSPointing columns.
#include <MSPointingColumns.h>
Public Member Functions
ROMSPointingColumns (const MSPointing &msPointing)
Create a columns object that accesses the data in the specified Table.
~ROMSPointingColumns ()
The destructor does nothing special.
const ROScalarColumn< Int > & antennaId () const
Access to required columns.
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & numPoly () const
const ROScalarColumn< Double > & timeOrigin () const
const ROScalarQuantColumn< Double > & timeOriginQuant () const
const ROScalarMeasColumn< MEpoch > & timeOriginMeas () const
const ROArrayColumn< Double > & direction () const
const ROArrayMeasColumn< MDirection > & directionMeasCol () const
const ROArrayColumn< Double > & target () const
const ROArrayMeasColumn< MDirection > & targetMeasCol () const
const ROScalarColumn< Bool > & tracking () const
const ROArrayColumn< Double > & pointingOffset () const
Access to optional columns.
const ROArrayMeasColumn< MDirection > & pointingOffsetMeasCol () const
const ROArrayColumn< Double > & sourceOffset () const
const ROArrayMeasColumn< MDirection > & sourceOffsetMeasCol () const
const ROArrayColumn< Double > & encoder () const
const ROScalarMeasColumn< MDirection > & encoderMeas () const
const ROScalarColumn< Int > & pointingModelId () const
const ROScalarColumn< Bool > & onSource () const
const ROScalarColumn< Bool > & overTheTop () const
MDirection directionMeas (Int row, Double time=0) const
Access to interpolated directions, the default time of zero will return the 0th order element of the polynomial.
MDirection targetMeas (Int row, Double time=0) const
MDirection pointingOffsetMeas (Int row, Double time=0) const
MDirection sourceOffsetMeas (Int row, Double time=0) const
Int pointingIndex (Int antenna, Double time, Int guessRow=0) const
return the first matching row index for this time and antenna, returns -1 if no match was found For long tables you may give a guess row...the last return is usually a good one.
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSPointingColumns ()
void attach (const MSPointing &msPointing)
Private Member Functions
ROMSPointingColumns (const ROMSPointingColumns &)
ROMSPointingColumns & operator= (const ROMSPointingColumns &)
void attachOptionalCols (const MSPointing &msPointing)
Private Attributes
ROScalarColumn< Int > antennaId_p
ROArrayColumn< Double > direction_p
ROScalarColumn< Double > interval_p
ROScalarColumn< String > name_p
ROScalarColumn< Int > numPoly_p
ROArrayColumn< Double > target_p
ROScalarColumn< Double > time_p
ROScalarColumn< Double > timeOrigin_p
ROScalarColumn< Bool > tracking_p
ROArrayColumn< Double > encoder_p
ROScalarColumn< Bool > onSource_p
ROScalarColumn< Int > pointingModelId_p
ROArrayColumn< Double > pointingOffset_p
ROArrayColumn< Double > sourceOffset_p
ROScalarColumn< Bool > overTheTop_p
ROArrayMeasColumn< MDirection > directionMeas_p
ROArrayMeasColumn< MDirection > targetMeas_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarMeasColumn< MEpoch > timeOriginMeas_p
ROScalarMeasColumn< MDirection > encoderMeas_p
ROArrayMeasColumn< MDirection > pointingOffsetMeas_p
ROArrayMeasColumn< MDirection > sourceOffsetMeas_p
ROScalarQuantColumn< Double > intervalQuant_p
ROScalarQuantColumn< Double > timeQuant_p
ROScalarQuantColumn< Double > timeOriginQuant_p
Detailed Description
A class to provide easy read-only access to MSPointing columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSPointing
ArrayColumn
ScalarColumn
Etymology
ROMSPointingColumns stands for Read-Only MeasurementSet Pointing Table columns.
Synopsis
This class provides read-only access to the columns in the MSPointing Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 79 of file MSPointingColumns.h.
Constructor & Destructor Documentation
ROMSPointingColumns() [1/3]
casacore::ROMSPointingColumns::ROMSPointingColumns (const MSPointing & msPointing)
Create a columns object that accesses the data in the specified Table.
~ROMSPointingColumns()
casacore::ROMSPointingColumns::~ROMSPointingColumns ()
The destructor does nothing special.
ROMSPointingColumns() [2/3]
casacore::ROMSPointingColumns::ROMSPointingColumns () protected
ROMSPointingColumns() [3/3]
casacore::ROMSPointingColumns::ROMSPointingColumns (const ROMSPointingColumns &) private
Member Function Documentation
antennaId()
const ROScalarColumn<Int>& casacore::ROMSPointingColumns::antennaId () const inline
Access to required columns.
Definition at line 90 of file MSPointingColumns.h.
References antennaId_p.
Referenced by casacore::MSPointingColumns::antennaId().
attach()
void casacore::ROMSPointingColumns::attach (const MSPointing & msPointing) protected
attachOptionalCols()
void casacore::ROMSPointingColumns::attachOptionalCols (const MSPointing & msPointing) private
direction()
const ROArrayColumn<Double>& casacore::ROMSPointingColumns::direction () const inline
Definition at line 104 of file MSPointingColumns.h.
References direction_p.
Referenced by casacore::MSPointingColumns::direction().
directionMeas()
MDirection casacore::ROMSPointingColumns::directionMeas (Int row, Double time = 0) const
Access to interpolated directions, the default time of zero will return the 0th order element of the polynomial.
directionMeasCol()
const ROArrayMeasColumn<MDirection>& casacore::ROMSPointingColumns::directionMeasCol () const inline
Definition at line 105 of file MSPointingColumns.h.
References directionMeas_p.
Referenced by casacore::MSPointingColumns::directionMeasCol().
encoder()
const ROArrayColumn<Double>& casacore::ROMSPointingColumns::encoder () const inline
Definition at line 122 of file MSPointingColumns.h.
References encoder_p.
Referenced by casacore::MSPointingColumns::encoder().
encoderMeas()
const ROScalarMeasColumn<MDirection>& casacore::ROMSPointingColumns::encoderMeas () const inline
Definition at line 123 of file MSPointingColumns.h.
References encoderMeas_p.
Referenced by casacore::MSPointingColumns::encoderMeas().
interval()
const ROScalarColumn<Double>& casacore::ROMSPointingColumns::interval () const inline
Definition at line 94 of file MSPointingColumns.h.
References interval_p.
Referenced by casacore::MSPointingColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSPointingColumns::intervalQuant () const inline
Definition at line 95 of file MSPointingColumns.h.
References intervalQuant_p.
Referenced by casacore::MSPointingColumns::intervalQuant().
name()
const ROScalarColumn<String>& casacore::ROMSPointingColumns::name () const inline
Definition at line 97 of file MSPointingColumns.h.
References name_p.
Referenced by casacore::MSPointingColumns::name().
nrow()
uInt casacore::ROMSPointingColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 147 of file MSPointingColumns.h.
References antennaId_p.
numPoly()
const ROScalarColumn<Int>& casacore::ROMSPointingColumns::numPoly () const inline
Definition at line 98 of file MSPointingColumns.h.
References numPoly_p.
Referenced by casacore::MSPointingColumns::numPoly().
onSource()
const ROScalarColumn<Bool>& casacore::ROMSPointingColumns::onSource () const inline
Definition at line 127 of file MSPointingColumns.h.
References onSource_p.
Referenced by casacore::MSPointingColumns::onSource().
operator=()
ROMSPointingColumns& casacore::ROMSPointingColumns::operator= (const ROMSPointingColumns &) private
overTheTop()
const ROScalarColumn<Bool>& casacore::ROMSPointingColumns::overTheTop () const inline
Definition at line 128 of file MSPointingColumns.h.
References overTheTop_p.
Referenced by casacore::MSPointingColumns::overTheTop().
pointingIndex()
Int casacore::ROMSPointingColumns::pointingIndex (Int antenna, Double time, Int guessRow = 0) const
return the first matching row index for this time and antenna, returns -1 if no match was found For long tables you may give a guess row...the last return is usually a good one.
pointingModelId()
const ROScalarColumn<Int>& casacore::ROMSPointingColumns::pointingModelId () const inline
Definition at line 125 of file MSPointingColumns.h.
References pointingModelId_p.
Referenced by casacore::MSPointingColumns::pointingModelId().
pointingOffset()
const ROArrayColumn<Double>& casacore::ROMSPointingColumns::pointingOffset () const inline
Access to optional columns.
Definition at line 115 of file MSPointingColumns.h.
References pointingOffset_p.
Referenced by casacore::MSPointingColumns::pointingOffset().
pointingOffsetMeas()
MDirection casacore::ROMSPointingColumns::pointingOffsetMeas (Int row, Double time = 0) const
pointingOffsetMeasCol()
const ROArrayMeasColumn<MDirection>& casacore::ROMSPointingColumns::pointingOffsetMeasCol () const inline
Definition at line 117 of file MSPointingColumns.h.
References pointingOffsetMeas_p.
Referenced by casacore::MSPointingColumns::pointingOffsetMeasCol().
sourceOffset()
const ROArrayColumn<Double>& casacore::ROMSPointingColumns::sourceOffset () const inline
Definition at line 119 of file MSPointingColumns.h.
References sourceOffset_p.
Referenced by casacore::MSPointingColumns::sourceOffset().
sourceOffsetMeas()
MDirection casacore::ROMSPointingColumns::sourceOffsetMeas (Int row, Double time = 0) const
sourceOffsetMeasCol()
const ROArrayMeasColumn<MDirection>& casacore::ROMSPointingColumns::sourceOffsetMeasCol () const inline
Definition at line 120 of file MSPointingColumns.h.
References sourceOffsetMeas_p.
Referenced by casacore::MSPointingColumns::sourceOffsetMeasCol().
target()
const ROArrayColumn<Double>& casacore::ROMSPointingColumns::target () const inline
Definition at line 107 of file MSPointingColumns.h.
References target_p.
Referenced by casacore::MSPointingColumns::target().
targetMeas()
MDirection casacore::ROMSPointingColumns::targetMeas (Int row, Double time = 0) const
targetMeasCol()
const ROArrayMeasColumn<MDirection>& casacore::ROMSPointingColumns::targetMeasCol () const inline
Definition at line 108 of file MSPointingColumns.h.
References targetMeas_p.
Referenced by casacore::MSPointingColumns::targetMeasCol().
time()
const ROScalarColumn<Double>& casacore::ROMSPointingColumns::time () const inline
Definition at line 91 of file MSPointingColumns.h.
References time_p.
Referenced by casacore::MSPointingColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSPointingColumns::timeMeas () const inline
Definition at line 93 of file MSPointingColumns.h.
References timeMeas_p.
Referenced by casacore::MSPointingColumns::timeMeas().
timeOrigin()
const ROScalarColumn<Double>& casacore::ROMSPointingColumns::timeOrigin () const inline
Definition at line 99 of file MSPointingColumns.h.
References timeOrigin_p.
Referenced by casacore::MSPointingColumns::timeOrigin().
timeOriginMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSPointingColumns::timeOriginMeas () const inline
Definition at line 102 of file MSPointingColumns.h.
References timeOriginMeas_p.
Referenced by casacore::MSPointingColumns::timeOriginMeas().
timeOriginQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSPointingColumns::timeOriginQuant () const inline
Definition at line 100 of file MSPointingColumns.h.
References timeOriginQuant_p.
Referenced by casacore::MSPointingColumns::timeOriginQuant().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSPointingColumns::timeQuant () const inline
Definition at line 92 of file MSPointingColumns.h.
References timeQuant_p.
Referenced by casacore::MSPointingColumns::timeQuant().
tracking()
const ROScalarColumn<Bool>& casacore::ROMSPointingColumns::tracking () const inline
Definition at line 110 of file MSPointingColumns.h.
References tracking_p.
Referenced by casacore::MSPointingColumns::tracking().
Member Data Documentation
antennaId_p
ROScalarColumn<Int> casacore::ROMSPointingColumns::antennaId_p private
Definition at line 167 of file MSPointingColumns.h.
Referenced by antennaId(), and nrow().
direction_p
ROArrayColumn<Double> casacore::ROMSPointingColumns::direction_p private
Definition at line 168 of file MSPointingColumns.h.
Referenced by direction().
directionMeas_p
ROArrayMeasColumn<MDirection> casacore::ROMSPointingColumns::directionMeas_p private
Definition at line 185 of file MSPointingColumns.h.
Referenced by directionMeasCol().
encoder_p
ROArrayColumn<Double> casacore::ROMSPointingColumns::encoder_p private
Definition at line 177 of file MSPointingColumns.h.
Referenced by encoder().
encoderMeas_p
ROScalarMeasColumn<MDirection> casacore::ROMSPointingColumns::encoderMeas_p private
Definition at line 190 of file MSPointingColumns.h.
Referenced by encoderMeas().
interval_p
ROScalarColumn<Double> casacore::ROMSPointingColumns::interval_p private
Definition at line 169 of file MSPointingColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSPointingColumns::intervalQuant_p private
Definition at line 195 of file MSPointingColumns.h.
Referenced by intervalQuant().
name_p
ROScalarColumn<String> casacore::ROMSPointingColumns::name_p private
Definition at line 170 of file MSPointingColumns.h.
Referenced by name().
numPoly_p
ROScalarColumn<Int> casacore::ROMSPointingColumns::numPoly_p private
Definition at line 171 of file MSPointingColumns.h.
Referenced by numPoly().
onSource_p
ROScalarColumn<Bool> casacore::ROMSPointingColumns::onSource_p private
Definition at line 178 of file MSPointingColumns.h.
Referenced by onSource().
overTheTop_p
ROScalarColumn<Bool> casacore::ROMSPointingColumns::overTheTop_p private
Definition at line 182 of file MSPointingColumns.h.
Referenced by overTheTop().
pointingModelId_p
ROScalarColumn<Int> casacore::ROMSPointingColumns::pointingModelId_p private
Definition at line 179 of file MSPointingColumns.h.
Referenced by pointingModelId().
pointingOffset_p
ROArrayColumn<Double> casacore::ROMSPointingColumns::pointingOffset_p private
Definition at line 180 of file MSPointingColumns.h.
Referenced by pointingOffset().
pointingOffsetMeas_p
ROArrayMeasColumn<MDirection> casacore::ROMSPointingColumns::pointingOffsetMeas_p private
Definition at line 191 of file MSPointingColumns.h.
Referenced by pointingOffsetMeasCol().
sourceOffset_p
ROArrayColumn<Double> casacore::ROMSPointingColumns::sourceOffset_p private
Definition at line 181 of file MSPointingColumns.h.
Referenced by sourceOffset().
sourceOffsetMeas_p
ROArrayMeasColumn<MDirection> casacore::ROMSPointingColumns::sourceOffsetMeas_p private
Definition at line 192 of file MSPointingColumns.h.
Referenced by sourceOffsetMeasCol().
target_p
ROArrayColumn<Double> casacore::ROMSPointingColumns::target_p private
Definition at line 172 of file MSPointingColumns.h.
Referenced by target().
targetMeas_p
ROArrayMeasColumn<MDirection> casacore::ROMSPointingColumns::targetMeas_p private
Definition at line 186 of file MSPointingColumns.h.
Referenced by targetMeasCol().
time_p
ROScalarColumn<Double> casacore::ROMSPointingColumns::time_p private
Definition at line 173 of file MSPointingColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSPointingColumns::timeMeas_p private
Definition at line 187 of file MSPointingColumns.h.
Referenced by timeMeas().
timeOrigin_p
ROScalarColumn<Double> casacore::ROMSPointingColumns::timeOrigin_p private
Definition at line 174 of file MSPointingColumns.h.
Referenced by timeOrigin().
timeOriginMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSPointingColumns::timeOriginMeas_p private
Definition at line 188 of file MSPointingColumns.h.
Referenced by timeOriginMeas().
timeOriginQuant_p
ROScalarQuantColumn<Double> casacore::ROMSPointingColumns::timeOriginQuant_p private
Definition at line 197 of file MSPointingColumns.h.
Referenced by timeOriginQuant().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSPointingColumns::timeQuant_p private
Definition at line 196 of file MSPointingColumns.h.
Referenced by timeQuant().
tracking_p
ROScalarColumn<Bool> casacore::ROMSPointingColumns::tracking_p private
Definition at line 175 of file MSPointingColumns.h.
Referenced by tracking().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSPointingColumns.h