casacore: casacore::FitsBase Class Reference
casacore::FitsBase Class Reference abstract
fits package (libcasa_fits) » FITS_module
helper class
#include <hdu.h>
Public Member Functions
FitsBase (const FITS::ValueType &t, int n)
virtual ~FitsBase ()
unsigned int nelements () const
virtual int fitsfieldsize () const =0
virtual int localfieldsize () const =0
virtual void * data ()=0
virtual int dims () const
virtual int dim (int n) const
virtual int * vdim ()
FITS::ValueType fieldtype () const
FitsBase & operator= (FitsBase &)
virtual void show (std::ostream &)=0
Static Public Member Functions
static FitsBase * make (const FITS::ValueType &, int=1)
static FitsBase * make (const FITS::ValueType &, int, int *)
static FitsBase * make (FitsBase &)
Protected Member Functions
virtual void setaddr (void **)=0
Protected Attributes
int no_elements
FITS::ValueType data_type
Friends
class BinaryTableExtension
class AsciiTableExtension
Detailed Description
helper class
Definition at line 840 of file hdu.h.
Constructor & Destructor Documentation
FitsBase()
casacore::FitsBase::FitsBase (const FITS::ValueType & t, int n) inline
Definition at line 844 of file hdu.h.
~FitsBase()
virtual casacore::FitsBase::~FitsBase () virtual
Member Function Documentation
data()
virtual void* casacore::FitsBase::data () pure virtual
Implemented in casacore::FitsField< FitsBit >, casacore::FitsField< TYPE >, casacore::FitsField< char >, and casacore::FitsField< fitsType >.
dim()
virtual int casacore::FitsBase::dim (int n) const virtual
Reimplemented in casacore::FitsArray< FitsBit >, and casacore::FitsArray< TYPE >.
dims()
virtual int casacore::FitsBase::dims () const virtual
Reimplemented in casacore::FitsArray< FitsBit >, and casacore::FitsArray< TYPE >.
fieldtype()
FITS::ValueType casacore::FitsBase::fieldtype () const inline
Definition at line 855 of file hdu.h.
References data_type.
fitsfieldsize()
virtual int casacore::FitsBase::fitsfieldsize () const pure virtual
Implemented in casacore::FitsField< FitsBit >, casacore::FitsField< TYPE >, casacore::FitsField< char >, and casacore::FitsField< fitsType >.
localfieldsize()
virtual int casacore::FitsBase::localfieldsize () const pure virtual
Implemented in casacore::FitsField< FitsBit >, casacore::FitsField< TYPE >, casacore::FitsField< char >, and casacore::FitsField< fitsType >.
make() [1/3]
static FitsBase* casacore::FitsBase::make (const FITS::ValueType & , int = 1) static
make() [2/3]
static FitsBase* casacore::FitsBase::make (const FITS::ValueType & , int , int *) static
make() [3/3]
static FitsBase* casacore::FitsBase::make (FitsBase &) static
nelements()
unsigned int casacore::FitsBase::nelements () const inline
Definition at line 848 of file hdu.h.
References no_elements.
Referenced by casacore::StringFITSFieldCopier::copyToFITS(), casacore::ArrayFITSFieldCopier< recordType, fitsType >::copyToFITS(), and casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::copyToFITS().
operator=()
FitsBase& casacore::FitsBase::operator= (FitsBase &)
setaddr()
virtual void casacore::FitsBase::setaddr (void **) protected pure virtual
Implemented in casacore::FitsField< FitsBit >, casacore::FitsField< TYPE >, casacore::FitsField< char >, and casacore::FitsField< fitsType >.
show()
virtual void casacore::FitsBase::show (std::ostream &) pure virtual
Implemented in casacore::FitsField< FitsBit >, casacore::FitsField< TYPE >, casacore::FitsField< char >, and casacore::FitsField< fitsType >.
Referenced by casacore::operator<<().
vdim()
virtual int* casacore::FitsBase::vdim () virtual
Reimplemented in casacore::FitsArray< FitsBit >, and casacore::FitsArray< TYPE >.
Friends And Related Function Documentation
AsciiTableExtension
friend class AsciiTableExtension friend
Definition at line 842 of file hdu.h.
BinaryTableExtension
friend class BinaryTableExtension friend
Definition at line 841 of file hdu.h.
Member Data Documentation
data_type
FITS::ValueType casacore::FitsBase::data_type protected
Definition at line 866 of file hdu.h.
Referenced by fieldtype().
no_elements
int casacore::FitsBase::no_elements protected
Definition at line 865 of file hdu.h.
Referenced by nelements().
The documentation for this class was generated from the following file:
fits/FITS/hdu.h