casacore: casacore::MSPolarizationColumns Class Reference
casacore::MSPolarizationColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSPolarization columns.
#include <MSPolColumns.h>
Public Member Functions
MSPolarizationColumns (MSPolarization &msPolarization)
Create a columns object that accesses the data in the specified Table.
~MSPolarizationColumns ()
The destructor does nothing special.
ArrayColumn< Int > & corrProduct ()
Read-write access to required columns.
ArrayColumn< Int > & corrType ()
ScalarColumn< Bool > & flagRow ()
ScalarColumn< Int > & numCorr ()
const ROArrayColumn< Int > & corrProduct () const
Read-only access to required columns.
const ROArrayColumn< Int > & corrType () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Int > & numCorr () const
Public Member Functions inherited from casacore::ROMSPolarizationColumns
ROMSPolarizationColumns (const MSPolarization &msPolarization)
Create a columns object that accesses the data in the specified Table.
~ROMSPolarizationColumns ()
The destructor does nothing special.
const ROArrayColumn< Int > & corrProduct () const
Access to required columns.
const ROArrayColumn< Int > & corrType () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< Int > & numCorr () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int match (const Vector< Stokes::StokesTypes > &polType, Int tryRow=-1)
returns the last row that contains the an entry in the CORR_TYPE column that matches, in length and value, the supplied corrType Vector.
Protected Member Functions
MSPolarizationColumns ()
void attach (MSPolarization &msPolarization)
Protected Member Functions inherited from casacore::ROMSPolarizationColumns
ROMSPolarizationColumns ()
void attach (const MSPolarization &msPolarization)
Private Member Functions
MSPolarizationColumns (const MSPolarizationColumns &)
MSPolarizationColumns & operator= (const MSPolarizationColumns &)
Private Attributes
ArrayColumn< Int > corrProduct_p
ArrayColumn< Int > corrType_p
ScalarColumn< Bool > flagRow_p
ScalarColumn< Int > numCorr_p
Detailed Description
A class to provide easy read-write access to MSPolarization columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSPolarization
ArrayColumn
ScalarColumn
Etymology
MSPolarizationColumns stands for MeasurementSet Polarization Table columns.
Synopsis
This class provides access to the columns in the MSPolarization Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 163 of file MSPolColumns.h.
Constructor & Destructor Documentation
MSPolarizationColumns() [1/3]
casacore::MSPolarizationColumns::MSPolarizationColumns (MSPolarization & msPolarization)
Create a columns object that accesses the data in the specified Table.
~MSPolarizationColumns()
casacore::MSPolarizationColumns::~MSPolarizationColumns ()
The destructor does nothing special.
MSPolarizationColumns() [2/3]
casacore::MSPolarizationColumns::MSPolarizationColumns () protected
MSPolarizationColumns() [3/3]
casacore::MSPolarizationColumns::MSPolarizationColumns (const MSPolarizationColumns &) private
Member Function Documentation
attach()
void casacore::MSPolarizationColumns::attach (MSPolarization & msPolarization) protected
corrProduct() [1/2]
ArrayColumn<Int>& casacore::MSPolarizationColumns::corrProduct () inline
Read-write access to required columns.
Definition at line 174 of file MSPolColumns.h.
References corrProduct_p.
corrProduct() [2/2]
const ROArrayColumn<Int>& casacore::MSPolarizationColumns::corrProduct () const inline
Read-only access to required columns.
Definition at line 182 of file MSPolColumns.h.
References casacore::ROMSPolarizationColumns::corrProduct().
corrType() [1/2]
ArrayColumn<Int>& casacore::MSPolarizationColumns::corrType () inline
Definition at line 175 of file MSPolColumns.h.
References corrType_p.
corrType() [2/2]
const ROArrayColumn<Int>& casacore::MSPolarizationColumns::corrType () const inline
Definition at line 184 of file MSPolColumns.h.
References casacore::ROMSPolarizationColumns::corrType().
flagRow() [1/2]
ScalarColumn<Bool>& casacore::MSPolarizationColumns::flagRow () inline
Definition at line 176 of file MSPolColumns.h.
References flagRow_p.
flagRow() [2/2]
const ROScalarColumn<Bool>& casacore::MSPolarizationColumns::flagRow () const inline
Definition at line 186 of file MSPolColumns.h.
References casacore::ROMSPolarizationColumns::flagRow().
numCorr() [1/2]
ScalarColumn<Int>& casacore::MSPolarizationColumns::numCorr () inline
Definition at line 177 of file MSPolColumns.h.
References numCorr_p.
numCorr() [2/2]
const ROScalarColumn<Int>& casacore::MSPolarizationColumns::numCorr () const inline
Definition at line 188 of file MSPolColumns.h.
References casacore::ROMSPolarizationColumns::numCorr().
operator=()
MSPolarizationColumns& casacore::MSPolarizationColumns::operator= (const MSPolarizationColumns &) private
Member Data Documentation
corrProduct_p
ArrayColumn<Int> casacore::MSPolarizationColumns::corrProduct_p private
Definition at line 207 of file MSPolColumns.h.
Referenced by corrProduct().
corrType_p
ArrayColumn<Int> casacore::MSPolarizationColumns::corrType_p private
Definition at line 208 of file MSPolColumns.h.
Referenced by corrType().
flagRow_p
ScalarColumn<Bool> casacore::MSPolarizationColumns::flagRow_p private
Definition at line 209 of file MSPolColumns.h.
Referenced by flagRow().
numCorr_p
ScalarColumn<Int> casacore::MSPolarizationColumns::numCorr_p private
Definition at line 210 of file MSPolColumns.h.
Referenced by numCorr().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSPolColumns.h