casacore: casacore::MSProcessorColumns Class Reference
casacore::MSProcessorColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSProcessor columns.
#include <MSProcessorColumns.h>
Public Member Functions
MSProcessorColumns (MSProcessor &msProcessor)
Create a columns object that accesses the data in the specified Table.
~MSProcessorColumns ()
The destructor does nothing special.
ScalarColumn< Bool > & flagRow ()
Read-write access to required columns.
ScalarColumn< Int > & modeId ()
ScalarColumn< String > & type ()
ScalarColumn< Int > & typeId ()
ScalarColumn< String > & subType ()
ScalarColumn< Int > & passId ()
Read-write access to optional columns.
const ROScalarColumn< Bool > & flagRow () const
Read-only access to required columns.
const ROScalarColumn< Int > & modeId () const
const ROScalarColumn< String > & type () const
const ROScalarColumn< Int > & typeId () const
const ROScalarColumn< String > & subType () const
const ROScalarColumn< Int > & passId () const
Read-only access to optional columns.
Public Member Functions inherited from casacore::ROMSProcessorColumns
ROMSProcessorColumns (const MSProcessor &msProcessor)
Create a columns object that accesses the data in the specified Table.
~ROMSProcessorColumns ()
The destructor does nothing special.
const ROScalarColumn< Bool > & flagRow () const
Access to required columns.
const ROScalarColumn< Int > & modeId () const
const ROScalarColumn< String > & type () const
const ROScalarColumn< Int > & typeId () const
const ROScalarColumn< String > & subType () const
const ROScalarColumn< Int > & passId () const
Read-only access to optional columns.
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSProcessorColumns ()
void attach (MSProcessor &msProcessor)
Protected Member Functions inherited from casacore::ROMSProcessorColumns
ROMSProcessorColumns ()
void attach (const MSProcessor &msProcessor)
Private Member Functions
MSProcessorColumns (const MSProcessorColumns &)
MSProcessorColumns & operator= (const MSProcessorColumns &)
void attachOptionalCols (MSProcessor &msProcessor)
Private Attributes
ScalarColumn< Bool > flagRow_p
ScalarColumn< Int > modeId_p
ScalarColumn< String > type_p
ScalarColumn< Int > typeId_p
ScalarColumn< String > subType_p
ScalarColumn< Int > passId_p
Detailed Description
A class to provide easy read-write access to MSProcessor columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSProcessor
ScalarColumn
Etymology
MSProcessorColumns stands for MeasurementSet Processor Table columns.
Synopsis
This class provides access to the columns in the MSProcessor Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 157 of file MSProcessorColumns.h.
Constructor & Destructor Documentation
MSProcessorColumns() [1/3]
casacore::MSProcessorColumns::MSProcessorColumns (MSProcessor & msProcessor)
Create a columns object that accesses the data in the specified Table.
~MSProcessorColumns()
casacore::MSProcessorColumns::~MSProcessorColumns ()
The destructor does nothing special.
MSProcessorColumns() [2/3]
casacore::MSProcessorColumns::MSProcessorColumns () protected
MSProcessorColumns() [3/3]
casacore::MSProcessorColumns::MSProcessorColumns (const MSProcessorColumns &) private
Member Function Documentation
attach()
void casacore::MSProcessorColumns::attach (MSProcessor & msProcessor) protected
attachOptionalCols()
void casacore::MSProcessorColumns::attachOptionalCols (MSProcessor & msProcessor) private
flagRow() [1/2]
ScalarColumn<Bool>& casacore::MSProcessorColumns::flagRow () inline
Read-write access to required columns.
Definition at line 168 of file MSProcessorColumns.h.
References flagRow_p.
flagRow() [2/2]
const ROScalarColumn<Bool>& casacore::MSProcessorColumns::flagRow () const inline
Read-only access to required columns.
Definition at line 182 of file MSProcessorColumns.h.
References casacore::ROMSProcessorColumns::flagRow().
modeId() [1/2]
ScalarColumn<Int>& casacore::MSProcessorColumns::modeId () inline
Definition at line 169 of file MSProcessorColumns.h.
References modeId_p.
modeId() [2/2]
const ROScalarColumn<Int>& casacore::MSProcessorColumns::modeId () const inline
Definition at line 184 of file MSProcessorColumns.h.
References casacore::ROMSProcessorColumns::modeId().
operator=()
MSProcessorColumns& casacore::MSProcessorColumns::operator= (const MSProcessorColumns &) private
passId() [1/2]
ScalarColumn<Int>& casacore::MSProcessorColumns::passId () inline
Read-write access to optional columns.
Definition at line 177 of file MSProcessorColumns.h.
References passId_p.
passId() [2/2]
const ROScalarColumn<Int>& casacore::MSProcessorColumns::passId () const inline
Read-only access to optional columns.
Definition at line 196 of file MSProcessorColumns.h.
References casacore::ROMSProcessorColumns::passId().
subType() [1/2]
ScalarColumn<String>& casacore::MSProcessorColumns::subType () inline
Definition at line 172 of file MSProcessorColumns.h.
References subType_p.
subType() [2/2]
const ROScalarColumn<String>& casacore::MSProcessorColumns::subType () const inline
Definition at line 190 of file MSProcessorColumns.h.
References casacore::ROMSProcessorColumns::subType().
type() [1/2]
ScalarColumn<String>& casacore::MSProcessorColumns::type () inline
Definition at line 170 of file MSProcessorColumns.h.
References type_p.
type() [2/2]
const ROScalarColumn<String>& casacore::MSProcessorColumns::type () const inline
Definition at line 186 of file MSProcessorColumns.h.
References casacore::ROMSProcessorColumns::type().
typeId() [1/2]
ScalarColumn<Int>& casacore::MSProcessorColumns::typeId () inline
Definition at line 171 of file MSProcessorColumns.h.
References typeId_p.
typeId() [2/2]
const ROScalarColumn<Int>& casacore::MSProcessorColumns::typeId () const inline
Definition at line 188 of file MSProcessorColumns.h.
References casacore::ROMSProcessorColumns::typeId().
Member Data Documentation
flagRow_p
ScalarColumn<Bool> casacore::MSProcessorColumns::flagRow_p private
Definition at line 218 of file MSProcessorColumns.h.
Referenced by flagRow().
modeId_p
ScalarColumn<Int> casacore::MSProcessorColumns::modeId_p private
Definition at line 219 of file MSProcessorColumns.h.
Referenced by modeId().
passId_p
ScalarColumn<Int> casacore::MSProcessorColumns::passId_p private
Definition at line 224 of file MSProcessorColumns.h.
Referenced by passId().
subType_p
ScalarColumn<String> casacore::MSProcessorColumns::subType_p private
Definition at line 222 of file MSProcessorColumns.h.
Referenced by subType().
type_p
ScalarColumn<String> casacore::MSProcessorColumns::type_p private
Definition at line 220 of file MSProcessorColumns.h.
Referenced by type().
typeId_p
ScalarColumn<Int> casacore::MSProcessorColumns::typeId_p private
Definition at line 221 of file MSProcessorColumns.h.
Referenced by typeId().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSProcessorColumns.h