casacore: casacore::MSInterface Class Reference
casacore::MSInterface Class Reference
MSSel_module
MSInterface: A specialization of MSSelectableTable for accessing MS.
#include <MSSelectableTable.h>
Public Member Functions
MSInterface ()
MSInterface (const Table &table)
virtual ~MSInterface ()
virtual const MSAntenna & antenna ()
virtual const MSField & field ()
virtual const MSSpectralWindow & spectralWindow ()
virtual const MSDataDescription & dataDescription ()
virtual const MSObservation & observation ()
virtual String columnName (MSMainEnums::PredefinedColumns nameEnum)
virtual Bool isMS ()
virtual MSSDataType dataType ()
virtual const MeasurementSet * asMS ()
virtual MSSelectableMainColumn * mainColumns ()
Public Member Functions inherited from casacore::MSSelectableTable
MSSelectableTable ()
MSSelectableTable (const Table &table)
virtual ~MSSelectableTable ()
virtual void setTable (const Table &table)
const Table * table ()
TableExprNode col (const String &colName)
Private Attributes
MSMainColInterface * msMainCols_p
Additional Inherited Members
Public Types inherited from casacore::MSSelectableTable
enum MSSDataType {
BASELINE_BASED,
PURE_ANTENNA_BASED,
REF_ANTENNA_BASED
}
Protected Attributes inherited from casacore::MSSelectableTable
const Table * table_p
Detailed Description
MSInterface: A specialization of MSSelectableTable for accessing MS.
Intended use:
Public interface
Etymology
From "ms" and "interface".
Synopsis
A class that can be passed around as MSSelectableTable, with most of the methods overloaded to work with the underlaying MS.
Example
//
// Fill in the expression in the various strings that are passed for
// parsing to the MSSelection object later.
//
String fieldStr,timeStr,spwStr,baselineStr,
uvdistStr,taqlStr,scanStr,arrayStr, polnStr,stateObsModeStr,
observationStr;
baselineStr="1&2";
timeStr="*+0:10:0";
fieldStr="CygA*";
//
// Instantiate the MS and the MSInterface objects.
//
MS ms(MSName),selectedMS(ms);
MSInterface msInterface(ms);
//
// Setup the MSSelection thingi
//
MSSelection msSelection;
msSelection.reset(msInterface,MSSelection::PARSE_NOW,
timeStr,baselineStr,fieldStr,spwStr,
uvdistStr,taqlStr,polnStr,scanStr,arrayStr,
stateObsModeStr,observationStr);
if (msSelection.getSelectedMS(selectedMS))
cerr << "Got the selected MS!" << endl;
else
cerr << "The set of expressions resulted into null-selection";
Motivation
To generalize the implementation of the MSSelection parsers.
Definition at line 198 of file MSSelectableTable.h.
Constructor & Destructor Documentation
casacore::MSInterface::MSInterface () inline
Definition at line 201 of file MSSelectableTable.h.
casacore::MSInterface::MSInterface (const Table & table)
virtual casacore::MSInterface::~MSInterface () inline virtual
Definition at line 203 of file MSSelectableTable.h.
References msMainCols_p.
Member Function Documentation
virtual const MSAntenna& casacore::MSInterface::antenna () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 204 of file MSSelectableTable.h.
References casacore::MeasurementSet::antenna(), and asMS().
virtual const MeasurementSet* casacore::MSInterface::asMS () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 213 of file MSSelectableTable.h.
References casacore::MSSelectableTable::table().
Referenced by antenna(), dataDescription(), field(), observation(), and spectralWindow().
virtual String casacore::MSInterface::columnName (MSMainEnums::PredefinedColumns nameEnum) inline virtual
Implements casacore::MSSelectableTable.
Definition at line 209 of file MSSelectableTable.h.
virtual const MSDataDescription& casacore::MSInterface::dataDescription () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 207 of file MSSelectableTable.h.
References asMS(), and casacore::MeasurementSet::dataDescription().
virtual MSSDataType casacore::MSInterface::dataType () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 211 of file MSSelectableTable.h.
References casacore::MSSelectableTable::BASELINE_BASED.
virtual const MSField& casacore::MSInterface::field () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 205 of file MSSelectableTable.h.
References asMS(), and casacore::MeasurementSet::field().
virtual Bool casacore::MSInterface::isMS () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 210 of file MSSelectableTable.h.
References casacore::True.
virtual MSSelectableMainColumn* casacore::MSInterface::mainColumns () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 214 of file MSSelectableTable.h.
References msMainCols_p, and casacore::MSSelectableTable::table_p.
virtual const MSObservation& casacore::MSInterface::observation () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 208 of file MSSelectableTable.h.
References asMS(), and casacore::MeasurementSet::observation().
virtual const MSSpectralWindow& casacore::MSInterface::spectralWindow () inline virtual
Implements casacore::MSSelectableTable.
Definition at line 206 of file MSSelectableTable.h.
References asMS(), and casacore::MeasurementSet::spectralWindow().
Member Data Documentation
MSMainColInterface* casacore::MSInterface::msMainCols_p private
Definition at line 217 of file MSSelectableTable.h.
Referenced by mainColumns(), and ~MSInterface().
The documentation for this class was generated from the following file:
ms/MSSel/MSSelectableTable.h