casacore: casacore::Array< T, Alloc >::IteratorSTL Class Reference
casacore::Array< T, Alloc >::IteratorSTL Class Reference
#include <Array.h>
Public Types
typedef T value_type
typedef value_type * pointer
typedef value_type & reference
typedef std::size_t size_type
typedef ptrdiff_t difference_type
typedef std::forward_iterator_tag iterator_category
Public Member Functions
IteratorSTL (Array< T, Alloc > &arr)
Create the begin iterator object for an Array.
IteratorSTL (const T *end=0)
Create the end iterator object for an Array.
const IteratorSTL & operator++ ()
IteratorSTL operator++ (int)
T & operator* ()
T * operator-> ()
Public Member Functions inherited from casacore::Array< T, Alloc >::BaseIteratorSTL
BaseIteratorSTL (const Array< T, Alloc > &)
Create the begin const_iterator object for an Array.
BaseIteratorSTL (const T *end=0)
Create the end const_iterator object for an Array.
void nextElem ()
void nextLine ()
bool operator== (const BaseIteratorSTL &other) const
bool operator!= (const BaseIteratorSTL &other) const
T * getPos ()
Additional Inherited Members
Protected Member Functions inherited from casacore::Array< T, Alloc >::BaseIteratorSTL
void increment ()
Increment iterator for a non-contiguous array.
Protected Attributes inherited from casacore::Array< T, Alloc >::BaseIteratorSTL
const T * itsPos
const T * itsLineEnd
size_t itsLineIncr
size_t itsLineAxis
IPosition itsCurPos
IPosition itsLastPos
const Array< T, Alloc > * itsArray
bool itsContig
Detailed Description
template<typename T, typename Alloc>
class casacore::Array< T, Alloc >::IteratorSTL
Definition at line 732 of file Array.h.
Member Typedef Documentation
template<typename T, typename Alloc> typedef ptrdiff_t casacore::Array< T, Alloc >::IteratorSTL::difference_type
Definition at line 741 of file Array.h.
template<typename T, typename Alloc> typedef std::forward_iterator_tag casacore::Array< T, Alloc >::IteratorSTL::iterator_category
Definition at line 742 of file Array.h.
template<typename T, typename Alloc> typedef value_type* casacore::Array< T, Alloc >::IteratorSTL::pointer
Definition at line 738 of file Array.h.
template<typename T, typename Alloc> typedef value_type& casacore::Array< T, Alloc >::IteratorSTL::reference
Definition at line 739 of file Array.h.
template<typename T, typename Alloc> typedef std::size_t casacore::Array< T, Alloc >::IteratorSTL::size_type
Definition at line 740 of file Array.h.
template<typename T, typename Alloc> typedef T casacore::Array< T, Alloc >::IteratorSTL::value_type
Definition at line 737 of file Array.h.
Constructor & Destructor Documentation
template<typename T, typename Alloc> casacore::Array< T, Alloc >::IteratorSTL::IteratorSTL (Array< T, Alloc > & arr) inline explicit
Create the begin iterator object for an Array.
Definition at line 745 of file Array.h.
template<typename T, typename Alloc> casacore::Array< T, Alloc >::IteratorSTL::IteratorSTL (const T * end = 0) inline explicit
Create the end iterator object for an Array.
It also acts as the default constructor.
Definition at line 749 of file Array.h.
Member Function Documentation
template<typename T, typename Alloc> T& casacore::Array< T, Alloc >::IteratorSTL::operator* () inline
Definition at line 764 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::getPos().
template<typename T, typename Alloc> const IteratorSTL& casacore::Array< T, Alloc >::IteratorSTL::operator++ () inline
Definition at line 752 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem().
template<typename T, typename Alloc> IteratorSTL casacore::Array< T, Alloc >::IteratorSTL::operator++ (int) inline
Definition at line 757 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem().
template<typename T, typename Alloc> T* casacore::Array< T, Alloc >::IteratorSTL::operator-> () inline
Definition at line 766 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::getPos().
The documentation for this class was generated from the following file:
casa/Arrays/Array.h