casacore: casacore::MSSysCalColumns Class Reference
casacore::MSSysCalColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSSysCal columns.
#include <MSSysCalColumns.h>
Public Member Functions
MSSysCalColumns (MSSysCal &msSysCal)
Create a columns object that accesses the data in the specified Table.
~MSSysCalColumns ()
The destructor does nothing special.
ScalarColumn< Int > & antennaId ()
Read-write access to required columns.
ScalarColumn< Int > & feedId ()
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< Int > & spectralWindowId ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
ScalarColumn< Float > & phaseDiff ()
Read-write access to optional columns.
ScalarQuantColumn< Float > & phaseDiffQuant ()
ScalarColumn< Bool > & phaseDiffFlag ()
ArrayColumn< Float > & tant ()
ArrayQuantColumn< Float > & tantQuant ()
ScalarColumn< Bool > & tantFlag ()
ArrayColumn< Float > & tantSpectrum ()
ArrayQuantColumn< Float > & tantSpectrumQuant ()
ArrayColumn< Float > & tantTsys ()
ScalarColumn< Bool > & tantTsysFlag ()
ArrayColumn< Float > & tantTsysSpectrum ()
ArrayColumn< Float > & tcal ()
ArrayQuantColumn< Float > & tcalQuant ()
ScalarColumn< Bool > & tcalFlag ()
ArrayColumn< Float > & tcalSpectrum ()
ArrayQuantColumn< Float > & tcalSpectrumQuant ()
ArrayColumn< Float > & trx ()
ArrayQuantColumn< Float > & trxQuant ()
ScalarColumn< Bool > & trxFlag ()
ArrayColumn< Float > & trxSpectrum ()
ArrayQuantColumn< Float > & trxSpectrumQuant ()
ArrayColumn< Float > & tsky ()
ArrayQuantColumn< Float > & tskyQuant ()
ScalarColumn< Bool > & tskyFlag ()
ArrayColumn< Float > & tskySpectrum ()
ArrayQuantColumn< Float > & tskySpectrumQuant ()
ArrayColumn< Float > & tsys ()
ArrayQuantColumn< Float > & tsysQuant ()
ScalarColumn< Bool > & tsysFlag ()
ArrayColumn< Float > & tsysSpectrum ()
ArrayQuantColumn< Float > & tsysSpectrumQuant ()
const ROScalarColumn< Int > & antennaId () const
Read-only access to required columns.
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Float > & phaseDiff () const
Read-only access to optional columns.
const ROScalarQuantColumn< Float > & phaseDiffQuant () const
const ROScalarColumn< Bool > & phaseDiffFlag () const
const ROArrayColumn< Float > & tant () const
const ROArrayQuantColumn< Float > & tantQuant () const
const ROScalarColumn< Bool > & tantFlag () const
const ROArrayColumn< Float > & tantSpectrum () const
const ROArrayQuantColumn< Float > & tantSpectrumQuant () const
const ROArrayColumn< Float > & tantTsys () const
const ROScalarColumn< Bool > & tantTsysFlag () const
const ROArrayColumn< Float > & tantTsysSpectrum () const
const ROArrayColumn< Float > & tcal () const
const ROArrayQuantColumn< Float > & tcalQuant () const
const ROScalarColumn< Bool > & tcalFlag () const
const ROArrayColumn< Float > & tcalSpectrum () const
const ROArrayQuantColumn< Float > & tcalSpectrumQuant () const
const ROArrayColumn< Float > & trx () const
const ROArrayQuantColumn< Float > & trxQuant () const
const ROScalarColumn< Bool > & trxFlag () const
const ROArrayColumn< Float > & trxSpectrum () const
const ROArrayQuantColumn< Float > & trxSpectrumQuant () const
const ROArrayColumn< Float > & tsky () const
const ROArrayQuantColumn< Float > & tskyQuant () const
const ROScalarColumn< Bool > & tskyFlag () const
const ROArrayColumn< Float > & tskySpectrum () const
const ROArrayQuantColumn< Float > & tskySpectrumQuant () const
const ROArrayColumn< Float > & tsys () const
const ROArrayQuantColumn< Float > & tsysQuant () const
const ROScalarColumn< Bool > & tsysFlag () const
const ROArrayColumn< Float > & tsysSpectrum () const
const ROArrayQuantColumn< Float > & tsysSpectrumQuant () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME column.
Public Member Functions inherited from casacore::ROMSSysCalColumns
ROMSSysCalColumns (const MSSysCal &msSysCal)
Create a columns object that accesses the data in the specified Table.
~ROMSSysCalColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSSysCal table is optional)
const ROScalarColumn< Int > & antennaId () const
Access to columns.
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Float > & phaseDiff () const
Access to optional columns.
const ROScalarQuantColumn< Float > & phaseDiffQuant () const
const ROScalarColumn< Bool > & phaseDiffFlag () const
const ROArrayColumn< Float > & tant () const
const ROArrayQuantColumn< Float > & tantQuant () const
const ROScalarColumn< Bool > & tantFlag () const
const ROArrayColumn< Float > & tantSpectrum () const
const ROArrayQuantColumn< Float > & tantSpectrumQuant () const
const ROArrayColumn< Float > & tantTsys () const
const ROScalarColumn< Bool > & tantTsysFlag () const
const ROArrayColumn< Float > & tantTsysSpectrum () const
const ROArrayColumn< Float > & tcal () const
const ROArrayQuantColumn< Float > & tcalQuant () const
const ROScalarColumn< Bool > & tcalFlag () const
const ROArrayColumn< Float > & tcalSpectrum () const
const ROArrayQuantColumn< Float > & tcalSpectrumQuant () const
const ROArrayColumn< Float > & trx () const
const ROArrayQuantColumn< Float > & trxQuant () const
const ROScalarColumn< Bool > & trxFlag () const
const ROArrayColumn< Float > & trxSpectrum () const
const ROArrayQuantColumn< Float > & trxSpectrumQuant () const
const ROArrayColumn< Float > & tsky () const
const ROArrayQuantColumn< Float > & tskyQuant () const
const ROScalarColumn< Bool > & tskyFlag () const
const ROArrayColumn< Float > & tskySpectrum () const
const ROArrayQuantColumn< Float > & tskySpectrumQuant () const
const ROArrayColumn< Float > & tsys () const
const ROArrayQuantColumn< Float > & tsysQuant () const
const ROScalarColumn< Bool > & tsysFlag () const
const ROArrayColumn< Float > & tsysSpectrum () const
const ROArrayQuantColumn< Float > & tsysSpectrumQuant () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSSysCalColumns ()
void attach (MSSysCal &msSysCal)
Protected Member Functions inherited from casacore::ROMSSysCalColumns
ROMSSysCalColumns ()
void attach (const MSSysCal &msSysCal)
Private Member Functions
MSSysCalColumns (const MSSysCalColumns &)
MSSysCalColumns & operator= (const MSSysCalColumns &)
void attachOptionalCols (MSSysCal &msSysCal)
Private Attributes
ScalarColumn< Int > antennaId_p
ScalarColumn< Int > feedId_p
ScalarColumn< Double > interval_p
ScalarColumn< Int > spectralWindowId_p
ScalarColumn< Double > time_p
ScalarColumn< Float > phaseDiff_p
ScalarColumn< Bool > phaseDiffFlag_p
ArrayColumn< Float > tant_p
ScalarColumn< Bool > tantFlag_p
ArrayColumn< Float > tantSpectrum_p
ArrayColumn< Float > tantTsys_p
ScalarColumn< Bool > tantTsysFlag_p
ArrayColumn< Float > tantTsysSpectrum_p
ArrayColumn< Float > tcal_p
ScalarColumn< Bool > tcalFlag_p
ArrayColumn< Float > tcalSpectrum_p
ArrayColumn< Float > trx_p
ScalarColumn< Bool > trxFlag_p
ArrayColumn< Float > trxSpectrum_p
ArrayColumn< Float > tsky_p
ScalarColumn< Bool > tskyFlag_p
ArrayColumn< Float > tskySpectrum_p
ArrayColumn< Float > tsys_p
ScalarColumn< Bool > tsysFlag_p
ArrayColumn< Float > tsysSpectrum_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarQuantColumn< Double > intervalQuant_p
ScalarQuantColumn< Double > timeQuant_p
ScalarQuantColumn< Float > phaseDiffQuant_p
ArrayQuantColumn< Float > tantQuant_p
ArrayQuantColumn< Float > tantSpectrumQuant_p
ArrayQuantColumn< Float > tcalQuant_p
ArrayQuantColumn< Float > tcalSpectrumQuant_p
ArrayQuantColumn< Float > trxQuant_p
ArrayQuantColumn< Float > trxSpectrumQuant_p
ArrayQuantColumn< Float > tskyQuant_p
ArrayQuantColumn< Float > tskySpectrumQuant_p
ArrayQuantColumn< Float > tsysQuant_p
ArrayQuantColumn< Float > tsysSpectrumQuant_p
Detailed Description
A class to provide easy read-write access to MSSysCal columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSSysCal
ArrayColumn
ScalarColumn
Etymology
MSSysCalColumns stands for MeasurementSet SysCal Table columns.
Synopsis
This class provides access to the columns in the MSSysCal Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 251 of file MSSysCalColumns.h.
Constructor & Destructor Documentation
MSSysCalColumns() [1/3]
casacore::MSSysCalColumns::MSSysCalColumns (MSSysCal & msSysCal)
Create a columns object that accesses the data in the specified Table.
~MSSysCalColumns()
casacore::MSSysCalColumns::~MSSysCalColumns ()
The destructor does nothing special.
MSSysCalColumns() [2/3]
casacore::MSSysCalColumns::MSSysCalColumns () protected
MSSysCalColumns() [3/3]
casacore::MSSysCalColumns::MSSysCalColumns (const MSSysCalColumns &) private
Member Function Documentation
antennaId() [1/2]
ScalarColumn<Int>& casacore::MSSysCalColumns::antennaId () inline
Read-write access to required columns.
Definition at line 262 of file MSSysCalColumns.h.
References antennaId_p.
antennaId() [2/2]
const ROScalarColumn<Int>& casacore::MSSysCalColumns::antennaId () const inline
Read-only access to required columns.
Definition at line 309 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::antennaId().
attach()
void casacore::MSSysCalColumns::attach (MSSysCal & msSysCal) protected
attachOptionalCols()
void casacore::MSSysCalColumns::attachOptionalCols (MSSysCal & msSysCal) private
feedId() [1/2]
ScalarColumn<Int>& casacore::MSSysCalColumns::feedId () inline
Definition at line 263 of file MSSysCalColumns.h.
References feedId_p.
feedId() [2/2]
const ROScalarColumn<Int>& casacore::MSSysCalColumns::feedId () const inline
Definition at line 311 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::feedId().
interval() [1/2]
ScalarColumn<Double>& casacore::MSSysCalColumns::interval () inline
Definition at line 264 of file MSSysCalColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSSysCalColumns::interval () const inline
Definition at line 313 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSSysCalColumns::intervalQuant () inline
Definition at line 265 of file MSSysCalColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSSysCalColumns::intervalQuant () const inline
Definition at line 315 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::intervalQuant().
operator=()
MSSysCalColumns& casacore::MSSysCalColumns::operator= (const MSSysCalColumns &) private
phaseDiff() [1/2]
ScalarColumn<Float>& casacore::MSSysCalColumns::phaseDiff () inline
Read-write access to optional columns.
Definition at line 274 of file MSSysCalColumns.h.
References phaseDiff_p.
phaseDiff() [2/2]
const ROScalarColumn<Float>& casacore::MSSysCalColumns::phaseDiff () const inline
Read-only access to optional columns.
Definition at line 329 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::phaseDiff().
phaseDiffFlag() [1/2]
ScalarColumn<Bool>& casacore::MSSysCalColumns::phaseDiffFlag () inline
Definition at line 276 of file MSSysCalColumns.h.
References phaseDiffFlag_p.
phaseDiffFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSSysCalColumns::phaseDiffFlag () const inline
Definition at line 333 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::phaseDiffFlag().
phaseDiffQuant() [1/2]
ScalarQuantColumn<Float>& casacore::MSSysCalColumns::phaseDiffQuant () inline
Definition at line 275 of file MSSysCalColumns.h.
References phaseDiffQuant_p.
phaseDiffQuant() [2/2]
const ROScalarQuantColumn<Float>& casacore::MSSysCalColumns::phaseDiffQuant () const inline
Definition at line 331 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::phaseDiffQuant().
setEpochRef()
void casacore::MSSysCalColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
spectralWindowId() [1/2]
ScalarColumn<Int>& casacore::MSSysCalColumns::spectralWindowId () inline
Definition at line 266 of file MSSysCalColumns.h.
References spectralWindowId_p.
spectralWindowId() [2/2]
const ROScalarColumn<Int>& casacore::MSSysCalColumns::spectralWindowId () const inline
Definition at line 317 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::spectralWindowId().
tant() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tant () inline
Definition at line 277 of file MSSysCalColumns.h.
References tant_p.
tant() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tant () const inline
Definition at line 335 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tant().
tantFlag() [1/2]
ScalarColumn<Bool>& casacore::MSSysCalColumns::tantFlag () inline
Definition at line 279 of file MSSysCalColumns.h.
References tantFlag_p.
tantFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSSysCalColumns::tantFlag () const inline
Definition at line 339 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tantFlag().
tantQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tantQuant () inline
Definition at line 278 of file MSSysCalColumns.h.
References tantQuant_p.
tantQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tantQuant () const inline
Definition at line 337 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tantQuant().
tantSpectrum() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tantSpectrum () inline
Definition at line 280 of file MSSysCalColumns.h.
References tantSpectrum_p.
tantSpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tantSpectrum () const inline
Definition at line 341 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tantSpectrum().
tantSpectrumQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tantSpectrumQuant () inline
Definition at line 281 of file MSSysCalColumns.h.
References tantSpectrumQuant_p.
tantSpectrumQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tantSpectrumQuant () const inline
Definition at line 343 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tantSpectrumQuant().
tantTsys() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tantTsys () inline
Definition at line 282 of file MSSysCalColumns.h.
References tantTsys_p.
tantTsys() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tantTsys () const inline
Definition at line 345 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tantTsys().
tantTsysFlag() [1/2]
ScalarColumn<Bool>& casacore::MSSysCalColumns::tantTsysFlag () inline
Definition at line 283 of file MSSysCalColumns.h.
References tantTsysFlag_p.
tantTsysFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSSysCalColumns::tantTsysFlag () const inline
Definition at line 347 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tantTsysFlag().
tantTsysSpectrum() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tantTsysSpectrum () inline
Definition at line 284 of file MSSysCalColumns.h.
References tantTsysSpectrum_p.
tantTsysSpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tantTsysSpectrum () const inline
Definition at line 349 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tantTsysSpectrum().
tcal() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tcal () inline
Definition at line 285 of file MSSysCalColumns.h.
References tcal_p.
tcal() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tcal () const inline
Definition at line 351 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tcal().
tcalFlag() [1/2]
ScalarColumn<Bool>& casacore::MSSysCalColumns::tcalFlag () inline
Definition at line 287 of file MSSysCalColumns.h.
References tcalFlag_p.
tcalFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSSysCalColumns::tcalFlag () const inline
Definition at line 355 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tcalFlag().
tcalQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tcalQuant () inline
Definition at line 286 of file MSSysCalColumns.h.
References tcalQuant_p.
tcalQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tcalQuant () const inline
Definition at line 353 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tcalQuant().
tcalSpectrum() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tcalSpectrum () inline
Definition at line 288 of file MSSysCalColumns.h.
References tcalSpectrum_p.
tcalSpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tcalSpectrum () const inline
Definition at line 357 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tcalSpectrum().
tcalSpectrumQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tcalSpectrumQuant () inline
Definition at line 289 of file MSSysCalColumns.h.
References tcalSpectrumQuant_p.
tcalSpectrumQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tcalSpectrumQuant () const inline
Definition at line 359 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tcalSpectrumQuant().
time() [1/2]
ScalarColumn<Double>& casacore::MSSysCalColumns::time () inline
Definition at line 267 of file MSSysCalColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSSysCalColumns::time () const inline
Definition at line 319 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSSysCalColumns::timeMeas () inline
Definition at line 269 of file MSSysCalColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSSysCalColumns::timeMeas () const inline
Definition at line 323 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSSysCalColumns::timeQuant () inline
Definition at line 268 of file MSSysCalColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSSysCalColumns::timeQuant () const inline
Definition at line 321 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::timeQuant().
trx() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::trx () inline
Definition at line 290 of file MSSysCalColumns.h.
References trx_p.
trx() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::trx () const inline
Definition at line 361 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::trx().
trxFlag() [1/2]
ScalarColumn<Bool>& casacore::MSSysCalColumns::trxFlag () inline
Definition at line 292 of file MSSysCalColumns.h.
References trxFlag_p.
trxFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSSysCalColumns::trxFlag () const inline
Definition at line 364 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::trxFlag().
trxQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::trxQuant () inline
Definition at line 291 of file MSSysCalColumns.h.
References trxQuant_p.
trxQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::trxQuant () const inline
Definition at line 362 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::trxQuant().
trxSpectrum() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::trxSpectrum () inline
Definition at line 293 of file MSSysCalColumns.h.
References trxSpectrum_p.
trxSpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::trxSpectrum () const inline
Definition at line 366 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::trxSpectrum().
trxSpectrumQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::trxSpectrumQuant () inline
Definition at line 294 of file MSSysCalColumns.h.
References trxSpectrumQuant_p.
trxSpectrumQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::trxSpectrumQuant () const inline
Definition at line 368 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::trxSpectrumQuant().
tsky() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tsky () inline
Definition at line 295 of file MSSysCalColumns.h.
References tsky_p.
tsky() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tsky () const inline
Definition at line 370 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tsky().
tskyFlag() [1/2]
ScalarColumn<Bool>& casacore::MSSysCalColumns::tskyFlag () inline
Definition at line 297 of file MSSysCalColumns.h.
References tskyFlag_p.
tskyFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSSysCalColumns::tskyFlag () const inline
Definition at line 374 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tskyFlag().
tskyQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tskyQuant () inline
Definition at line 296 of file MSSysCalColumns.h.
References tskyQuant_p.
tskyQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tskyQuant () const inline
Definition at line 372 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tskyQuant().
tskySpectrum() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tskySpectrum () inline
Definition at line 298 of file MSSysCalColumns.h.
References tskySpectrum_p.
tskySpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tskySpectrum () const inline
Definition at line 376 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tskySpectrum().
tskySpectrumQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tskySpectrumQuant () inline
Definition at line 299 of file MSSysCalColumns.h.
References tskySpectrumQuant_p.
tskySpectrumQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tskySpectrumQuant () const inline
Definition at line 378 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tskySpectrumQuant().
tsys() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tsys () inline
Definition at line 300 of file MSSysCalColumns.h.
References tsys_p.
tsys() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tsys () const inline
Definition at line 380 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tsys().
tsysFlag() [1/2]
ScalarColumn<Bool>& casacore::MSSysCalColumns::tsysFlag () inline
Definition at line 302 of file MSSysCalColumns.h.
References tsysFlag_p.
tsysFlag() [2/2]
const ROScalarColumn<Bool>& casacore::MSSysCalColumns::tsysFlag () const inline
Definition at line 384 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tsysFlag().
tsysQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tsysQuant () inline
Definition at line 301 of file MSSysCalColumns.h.
References tsysQuant_p.
tsysQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tsysQuant () const inline
Definition at line 382 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tsysQuant().
tsysSpectrum() [1/2]
ArrayColumn<Float>& casacore::MSSysCalColumns::tsysSpectrum () inline
Definition at line 303 of file MSSysCalColumns.h.
References tsysSpectrum_p.
tsysSpectrum() [2/2]
const ROArrayColumn<Float>& casacore::MSSysCalColumns::tsysSpectrum () const inline
Definition at line 386 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tsysSpectrum().
tsysSpectrumQuant() [1/2]
ArrayQuantColumn<Float>& casacore::MSSysCalColumns::tsysSpectrumQuant () inline
Definition at line 304 of file MSSysCalColumns.h.
References tsysSpectrumQuant_p.
tsysSpectrumQuant() [2/2]
const ROArrayQuantColumn<Float>& casacore::MSSysCalColumns::tsysSpectrumQuant () const inline
Definition at line 388 of file MSSysCalColumns.h.
References casacore::ROMSSysCalColumns::tsysSpectrumQuant().
Member Data Documentation
antennaId_p
ScalarColumn<Int> casacore::MSSysCalColumns::antennaId_p private
Definition at line 421 of file MSSysCalColumns.h.
Referenced by antennaId().
feedId_p
ScalarColumn<Int> casacore::MSSysCalColumns::feedId_p private
Definition at line 422 of file MSSysCalColumns.h.
Referenced by feedId().
interval_p
ScalarColumn<Double> casacore::MSSysCalColumns::interval_p private
Definition at line 423 of file MSSysCalColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSSysCalColumns::intervalQuant_p private
Definition at line 452 of file MSSysCalColumns.h.
Referenced by intervalQuant().
phaseDiff_p
ScalarColumn<Float> casacore::MSSysCalColumns::phaseDiff_p private
Definition at line 427 of file MSSysCalColumns.h.
Referenced by phaseDiff().
phaseDiffFlag_p
ScalarColumn<Bool> casacore::MSSysCalColumns::phaseDiffFlag_p private
Definition at line 428 of file MSSysCalColumns.h.
Referenced by phaseDiffFlag().
phaseDiffQuant_p
ScalarQuantColumn<Float> casacore::MSSysCalColumns::phaseDiffQuant_p private
Definition at line 455 of file MSSysCalColumns.h.
Referenced by phaseDiffQuant().
spectralWindowId_p
ScalarColumn<Int> casacore::MSSysCalColumns::spectralWindowId_p private
Definition at line 424 of file MSSysCalColumns.h.
Referenced by spectralWindowId().
tant_p
ArrayColumn<Float> casacore::MSSysCalColumns::tant_p private
Definition at line 429 of file MSSysCalColumns.h.
Referenced by tant().
tantFlag_p
ScalarColumn<Bool> casacore::MSSysCalColumns::tantFlag_p private
Definition at line 430 of file MSSysCalColumns.h.
Referenced by tantFlag().
tantQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tantQuant_p private
Definition at line 456 of file MSSysCalColumns.h.
Referenced by tantQuant().
tantSpectrum_p
ArrayColumn<Float> casacore::MSSysCalColumns::tantSpectrum_p private
Definition at line 431 of file MSSysCalColumns.h.
Referenced by tantSpectrum().
tantSpectrumQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tantSpectrumQuant_p private
Definition at line 457 of file MSSysCalColumns.h.
Referenced by tantSpectrumQuant().
tantTsys_p
ArrayColumn<Float> casacore::MSSysCalColumns::tantTsys_p private
Definition at line 432 of file MSSysCalColumns.h.
Referenced by tantTsys().
tantTsysFlag_p
ScalarColumn<Bool> casacore::MSSysCalColumns::tantTsysFlag_p private
Definition at line 433 of file MSSysCalColumns.h.
Referenced by tantTsysFlag().
tantTsysSpectrum_p
ArrayColumn<Float> casacore::MSSysCalColumns::tantTsysSpectrum_p private
Definition at line 434 of file MSSysCalColumns.h.
Referenced by tantTsysSpectrum().
tcal_p
ArrayColumn<Float> casacore::MSSysCalColumns::tcal_p private
Definition at line 435 of file MSSysCalColumns.h.
Referenced by tcal().
tcalFlag_p
ScalarColumn<Bool> casacore::MSSysCalColumns::tcalFlag_p private
Definition at line 436 of file MSSysCalColumns.h.
Referenced by tcalFlag().
tcalQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tcalQuant_p private
Definition at line 458 of file MSSysCalColumns.h.
Referenced by tcalQuant().
tcalSpectrum_p
ArrayColumn<Float> casacore::MSSysCalColumns::tcalSpectrum_p private
Definition at line 437 of file MSSysCalColumns.h.
Referenced by tcalSpectrum().
tcalSpectrumQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tcalSpectrumQuant_p private
Definition at line 459 of file MSSysCalColumns.h.
Referenced by tcalSpectrumQuant().
time_p
ScalarColumn<Double> casacore::MSSysCalColumns::time_p private
Definition at line 425 of file MSSysCalColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSSysCalColumns::timeMeas_p private
Definition at line 449 of file MSSysCalColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSSysCalColumns::timeQuant_p private
Definition at line 453 of file MSSysCalColumns.h.
Referenced by timeQuant().
trx_p
ArrayColumn<Float> casacore::MSSysCalColumns::trx_p private
Definition at line 438 of file MSSysCalColumns.h.
Referenced by trx().
trxFlag_p
ScalarColumn<Bool> casacore::MSSysCalColumns::trxFlag_p private
Definition at line 439 of file MSSysCalColumns.h.
Referenced by trxFlag().
trxQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::trxQuant_p private
Definition at line 460 of file MSSysCalColumns.h.
Referenced by trxQuant().
trxSpectrum_p
ArrayColumn<Float> casacore::MSSysCalColumns::trxSpectrum_p private
Definition at line 440 of file MSSysCalColumns.h.
Referenced by trxSpectrum().
trxSpectrumQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::trxSpectrumQuant_p private
Definition at line 461 of file MSSysCalColumns.h.
Referenced by trxSpectrumQuant().
tsky_p
ArrayColumn<Float> casacore::MSSysCalColumns::tsky_p private
Definition at line 441 of file MSSysCalColumns.h.
Referenced by tsky().
tskyFlag_p
ScalarColumn<Bool> casacore::MSSysCalColumns::tskyFlag_p private
Definition at line 442 of file MSSysCalColumns.h.
Referenced by tskyFlag().
tskyQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tskyQuant_p private
Definition at line 462 of file MSSysCalColumns.h.
Referenced by tskyQuant().
tskySpectrum_p
ArrayColumn<Float> casacore::MSSysCalColumns::tskySpectrum_p private
Definition at line 443 of file MSSysCalColumns.h.
Referenced by tskySpectrum().
tskySpectrumQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tskySpectrumQuant_p private
Definition at line 463 of file MSSysCalColumns.h.
Referenced by tskySpectrumQuant().
tsys_p
ArrayColumn<Float> casacore::MSSysCalColumns::tsys_p private
Definition at line 444 of file MSSysCalColumns.h.
Referenced by tsys().
tsysFlag_p
ScalarColumn<Bool> casacore::MSSysCalColumns::tsysFlag_p private
Definition at line 445 of file MSSysCalColumns.h.
Referenced by tsysFlag().
tsysQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tsysQuant_p private
Definition at line 464 of file MSSysCalColumns.h.
Referenced by tsysQuant().
tsysSpectrum_p
ArrayColumn<Float> casacore::MSSysCalColumns::tsysSpectrum_p private
Definition at line 446 of file MSSysCalColumns.h.
Referenced by tsysSpectrum().
tsysSpectrumQuant_p
ArrayQuantColumn<Float> casacore::MSSysCalColumns::tsysSpectrumQuant_p private
Definition at line 465 of file MSSysCalColumns.h.
Referenced by tsysSpectrumQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSSysCalColumns.h