casacore: casacore::ValueHolderRep Class Reference
casacore::ValueHolderRep Class Reference
Containers_module_internal_classes
A holder for a value of any basic type.
#include <ValueHolderRep.h>
Public Member Functions
ValueHolderRep (Bool value)
Create the object for the given value.
ValueHolderRep (uChar value)
ValueHolderRep (Short value)
ValueHolderRep (uShort value)
ValueHolderRep (Int value)
ValueHolderRep (uInt value)
ValueHolderRep (Int64 value)
ValueHolderRep (Float value)
ValueHolderRep (Double value)
ValueHolderRep (const Complex &value)
ValueHolderRep (const DComplex &value)
ValueHolderRep (const Char *value)
ValueHolderRep (const String &value)
ValueHolderRep (const Array< Bool > &value)
ValueHolderRep (const Array< uChar > &value)
ValueHolderRep (const Array< Short > &value)
ValueHolderRep (const Array< uShort > &value)
ValueHolderRep (const Array< Int > &value)
ValueHolderRep (const Array< uInt > &value)
ValueHolderRep (const Array< Int64 > &value)
ValueHolderRep (const Array< Float > &value)
ValueHolderRep (const Array< Double > &value)
ValueHolderRep (const Array< Complex > &value)
ValueHolderRep (const Array< DComplex > &value)
ValueHolderRep (const Array< String > &value)
ValueHolderRep (const Record &value)
ValueHolderRep (uInt ndim, Bool dummy)
Create an empty N-dim array.
~ValueHolderRep ()
Destructor.
DataType dataType () const
Get the data type (as defined in DataType.h).
Bool asBool () const
Get the value.
uChar asuChar () const
Short asShort () const
uShort asuShort () const
Int asInt () const
uInt asuInt () const
Int64 asInt64 () const
Float asFloat () const
Double asDouble () const
Complex asComplex () const
DComplex asDComplex () const
const String & asString () const
const Array< Bool > asArrayBool () const
const Array< uChar > asArrayuChar () const
const Array< Short > asArrayShort () const
const Array< uShort > asArrayuShort () const
const Array< Int > asArrayInt () const
const Array< uInt > asArrayuInt () const
const Array< Int64 > asArrayInt64 () const
const Array< Float > asArrayFloat () const
const Array< Double > asArrayDouble () const
const Array< Complex > asArrayComplex () const
const Array< DComplex > asArrayDComplex () const
const Array< String > asArrayString () const
const Record & asRecord () const
void toRecord (Record &, const RecordFieldId &) const
Put the value as a field in a record.
std::ostream & write (std::ostream &os) const
Write the ValueHolderRep to an output stream.
bool operator< (const ValueHolderRep &right) const
Compare two ValueHolder objects.
Static Public Member Functions
static ValueHolderRep * fromRecord (const Record &rec, const RecordFieldId &)
Construct the object from the value in a record.
Private Member Functions
ValueHolderRep (const ValueHolderRep &)
Forbid copy ctor and assignment.
ValueHolderRep & operator= (const ValueHolderRep &)
Private Attributes
uInt itsNdim
DataType itsType
union {
Bool itsBool
Int64 itsInt64
Float itsFloat
Double itsDouble
void * itsPtr
};
Detailed Description
A holder for a value of any basic type.
@anchor ValueHolderRep_summary
Intended use:
Internal
Review Status
Test programs:
tValueHolder
Synopsis
Class ValueHolderRep is the letter class for the envelope class ValueHolder. See that class for more information.
Motivation
Copying ValueHolders should be as cheap as possible, so a counted referenced letter class is used.
Definition at line 65 of file ValueHolderRep.h.
Constructor & Destructor Documentation
casacore::ValueHolderRep::ValueHolderRep (Bool value) explicit
Create the object for the given value.
casacore::ValueHolderRep::ValueHolderRep (uChar value) explicit
casacore::ValueHolderRep::ValueHolderRep (Short value) explicit
casacore::ValueHolderRep::ValueHolderRep (uShort value) explicit
casacore::ValueHolderRep::ValueHolderRep (Int value) explicit
casacore::ValueHolderRep::ValueHolderRep (uInt value) explicit
casacore::ValueHolderRep::ValueHolderRep (Int64 value) explicit
casacore::ValueHolderRep::ValueHolderRep (Float value) explicit
casacore::ValueHolderRep::ValueHolderRep (Double value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Complex & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const DComplex & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Char * value) explicit
casacore::ValueHolderRep::ValueHolderRep (const String & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< Bool > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< uChar > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< Short > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< uShort > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< Int > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< uInt > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< Int64 > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< Float > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< Double > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< Complex > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< DComplex > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Array< String > & value) explicit
casacore::ValueHolderRep::ValueHolderRep (const Record & value) explicit
casacore::ValueHolderRep::ValueHolderRep (uInt ndim, Bool dummy)
Create an empty N-dim array.
casacore::ValueHolderRep::~ValueHolderRep ()
Destructor.
casacore::ValueHolderRep::ValueHolderRep (const ValueHolderRep &) private
Forbid copy ctor and assignment.
Member Function Documentation
const Array<Bool> casacore::ValueHolderRep::asArrayBool () const
Referenced by casacore::ValueHolder::asArrayBool().
const Array<Complex> casacore::ValueHolderRep::asArrayComplex () const
Referenced by casacore::ValueHolder::asArrayComplex().
const Array<DComplex> casacore::ValueHolderRep::asArrayDComplex () const
Referenced by casacore::ValueHolder::asArrayDComplex().
const Array<Double> casacore::ValueHolderRep::asArrayDouble () const
Referenced by casacore::ValueHolder::asArrayDouble().
const Array<Float> casacore::ValueHolderRep::asArrayFloat () const
Referenced by casacore::ValueHolder::asArrayFloat().
const Array<Int> casacore::ValueHolderRep::asArrayInt () const
Referenced by casacore::ValueHolder::asArrayInt().
const Array<Int64> casacore::ValueHolderRep::asArrayInt64 () const
Referenced by casacore::ValueHolder::asArrayInt64().
const Array<Short> casacore::ValueHolderRep::asArrayShort () const
Referenced by casacore::ValueHolder::asArrayShort().
const Array<String> casacore::ValueHolderRep::asArrayString () const
Referenced by casacore::ValueHolder::asArrayString().
const Array<uChar> casacore::ValueHolderRep::asArrayuChar () const
Referenced by casacore::ValueHolder::asArrayuChar().
const Array<uInt> casacore::ValueHolderRep::asArrayuInt () const
Referenced by casacore::ValueHolder::asArrayuInt().
const Array<uShort> casacore::ValueHolderRep::asArrayuShort () const
Referenced by casacore::ValueHolder::asArrayuShort().
Bool casacore::ValueHolderRep::asBool () const
Get the value.
If possible, it converts the data as needed.
Referenced by casacore::ValueHolder::asBool().
Complex casacore::ValueHolderRep::asComplex () const
Referenced by casacore::ValueHolder::asComplex().
DComplex casacore::ValueHolderRep::asDComplex () const
Referenced by casacore::ValueHolder::asDComplex().
Double casacore::ValueHolderRep::asDouble () const
Referenced by casacore::ValueHolder::asDouble().
Float casacore::ValueHolderRep::asFloat () const
Referenced by casacore::ValueHolder::asFloat().
Int casacore::ValueHolderRep::asInt () const
Referenced by casacore::ValueHolder::asInt().
Int64 casacore::ValueHolderRep::asInt64 () const
Referenced by casacore::ValueHolder::asInt64().
const Record& casacore::ValueHolderRep::asRecord () const
Referenced by casacore::ValueHolder::asRecord().
Short casacore::ValueHolderRep::asShort () const
Referenced by casacore::ValueHolder::asShort().
const String& casacore::ValueHolderRep::asString () const
Referenced by casacore::ValueHolder::asString().
uChar casacore::ValueHolderRep::asuChar () const
Referenced by casacore::ValueHolder::asuChar().
uInt casacore::ValueHolderRep::asuInt () const
Referenced by casacore::ValueHolder::asuInt().
uShort casacore::ValueHolderRep::asuShort () const
Referenced by casacore::ValueHolder::asuShort().
DataType casacore::ValueHolderRep::dataType () const inline
Get the data type (as defined in DataType.h).
Definition at line 178 of file ValueHolderRep.h.
References itsType.
Referenced by casacore::ValueHolder::dataType().
static ValueHolderRep* casacore::ValueHolderRep::fromRecord (const Record & rec, const RecordFieldId &) static
Construct the object from the value in a record.
Referenced by casacore::ValueHolder::fromRecord().
bool casacore::ValueHolderRep::operator< (const ValueHolderRep & right) const
Compare two ValueHolder objects.
They must have the same data type.
ValueHolderRep& casacore::ValueHolderRep::operator= (const ValueHolderRep &) private
void casacore::ValueHolderRep::toRecord (Record & , const RecordFieldId &) const
Put the value as a field in a record.
Referenced by casacore::ValueHolder::toRecord().
std::ostream& casacore::ValueHolderRep::write (std::ostream & os) const
Write the ValueHolderRep to an output stream.
Arrays are written as normal arrays using ArrayIO.h.
Member Data Documentation
union { ... }
Bool casacore::ValueHolderRep::itsBool
Definition at line 169 of file ValueHolderRep.h.
Double casacore::ValueHolderRep::itsDouble
Definition at line 172 of file ValueHolderRep.h.
Float casacore::ValueHolderRep::itsFloat
Definition at line 171 of file ValueHolderRep.h.
Int64 casacore::ValueHolderRep::itsInt64
Definition at line 170 of file ValueHolderRep.h.
uInt casacore::ValueHolderRep::itsNdim private
Definition at line 166 of file ValueHolderRep.h.
void* casacore::ValueHolderRep::itsPtr
Definition at line 173 of file ValueHolderRep.h.
DataType casacore::ValueHolderRep::itsType private
Definition at line 167 of file ValueHolderRep.h.
Referenced by dataType().
The documentation for this class was generated from the following file:
casa/Containers/ValueHolderRep.h