casacore: casacore::DataManInfo Class Reference
casacore::DataManInfo Class Reference
DataMan_module
Class with static functions to manipulate a datamanager record.
#include <DataManInfo.h>
Static Public Member Functions
static void removeHypercolumns (TableDesc &tabDesc)
Remove hypercolumn definitions from the table description.
static void adjustTSM (TableDesc &tabDesc, Record &dminfo)
Replace TiledDataStMan by TiledShapeStMan in the DataManagerInfo record.
static Record adjustStMan (const Record &dminfo, const String &dmType, Bool replaceMSM=True)
Replace non-writable storage managers by the given storage manager (usually StandardStMan or IncrementalStMan).
static void setTiledStMan (Record &dminfo, const Vector< String > &columns, const String &dmType, const String &dmName, const IPosition &defaultTileShape)
Set the data managers of the given column(s) to the given tiled storage manager (normally TiledShapeStMan or TiledColumnStMan).
static Vector< String > removeDminfoColumns (Record &dminfo, const Vector< String > &columns, const String &keepType=String())
Remove the columns from the dminfo record and return a vector with the names of the columns actually removed.
static void adjustDesc (TableDesc &tabDesc, const Record &dminfo)
Adjust the data manager types and groups and the hypercolumn definitions to the actual data manager info.
static void showDataManStats (const Table &, ostream &)
Show the Table IO statistics.
Detailed Description
Class with static functions to manipulate a datamanager record.
Intended use:
Public interface
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Test programs:
tTableCopy
Prerequisite
Table
Synopsis
DataManInfo is a class to manipulate a datamanager info record and table descriptions. Often an existing table description and datamanager info record is used to construct a new table, but it might be necessary to change it somewhat.
Remove hypercolumn definitions from a table description. They are not needed anymore and can be a burden.
Replace non-writable storage managers (like LofarStMan) by a writable one.
Replace the deprecated TiledDataStMan by TiledShapeStMan.
Such things might be necessary in a number
Definition at line 78 of file DataManInfo.h.
Member Function Documentation
static void casacore::DataManInfo::adjustDesc (TableDesc & tabDesc, const Record & dminfo) static
Adjust the data manager types and groups and the hypercolumn definitions to the actual data manager info.
Referenced by casacore::TableCopy::adjustDesc().
static Record casacore::DataManInfo::adjustStMan (const Record & dminfo, const String & dmType, Bool replaceMSM = True) static
Replace non-writable storage managers by the given storage manager (usually StandardStMan or IncrementalStMan).
It is possible to specify the new data manager type to use. This is needed for special storage managers like LofarStMan. If replaceMSM is set, MemoryStMan is also replaced.
Referenced by casacore::TableCopy::adjustStMan().
static void casacore::DataManInfo::adjustTSM (TableDesc & tabDesc, Record & dminfo) static
Replace TiledDataStMan by TiledShapeStMan in the DataManagerInfo record.
Since TiledShapeStMan does not support ID columns, they are adjusted as well in tabDesc and dminfo.
Referenced by casacore::TableCopy::adjustTSM().
static Vector<String> casacore::DataManInfo::removeDminfoColumns (Record & dminfo, const Vector< String > & columns, const String & keepType = String()) static
Remove the columns from the dminfo record and return a vector with the names of the columns actually removed.
The columns having a data manager matching keepType are not removed. Matching means that the beginning of the data manager name have to match, so "Tiled" matches all tiled storagemanagers.
Referenced by casacore::TableCopy::removeDminfoColumns().
static void casacore::DataManInfo::removeHypercolumns (TableDesc & tabDesc) static
Remove hypercolumn definitions from the table description.
static void casacore::DataManInfo::setTiledStMan (Record & dminfo, const Vector< String > & columns, const String & dmType, const String & dmName, const IPosition & defaultTileShape) static
Set the data managers of the given column(s) to the given tiled storage manager (normally TiledShapeStMan or TiledColumnStMan).
The columns are combined in a single storage manager, so the function has to be called multiple times if, say, one per column is needed. The columns already having a tiled storage manager are not changed.
Referenced by casacore::TableCopy::setTiledStMan().
static void casacore::DataManInfo::showDataManStats (const Table & , ostream &) static
Show the Table IO statistics.
The documentation for this class was generated from the following file:
tables/DataMan/DataManInfo.h