casacore: casacore::MSFreqOffsetColumns Class Reference
casacore::MSFreqOffsetColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSFreqOffset columns.
#include <MSFreqOffColumns.h>
Public Member Functions
MSFreqOffsetColumns (MSFreqOffset &msFreqOffset)
Create a columns object that accesses the data in the specified Table.
~MSFreqOffsetColumns ()
The destructor does nothing special.
ScalarColumn< Int > & antenna1 ()
Read-write access to required columns.
ScalarColumn< Int > & antenna2 ()
ScalarColumn< Int > & feedId ()
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< Double > & offset ()
ScalarQuantColumn< Double > & offsetQuant ()
ScalarColumn< Int > & spectralWindowId ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
const ROScalarColumn< Int > & antenna1 () const
Read-only access to required columns.
const ROScalarColumn< Int > & antenna2 () const
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & offset () const
const ROScalarQuantColumn< Double > & offsetQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME column.
Public Member Functions inherited from casacore::ROMSFreqOffsetColumns
ROMSFreqOffsetColumns (const MSFreqOffset &msFreqOffset)
Create a columns object that accesses the data in the specified Table.
~ROMSFreqOffsetColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSFreqOffset table is optional)
const ROScalarColumn< Int > & antenna1 () const
Access to columns.
const ROScalarColumn< Int > & antenna2 () const
const ROScalarColumn< Int > & feedId () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< Double > & offset () const
const ROScalarQuantColumn< Double > & offsetQuant () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSFreqOffsetColumns ()
void attach (MSFreqOffset &msFreqOffset)
Protected Member Functions inherited from casacore::ROMSFreqOffsetColumns
ROMSFreqOffsetColumns ()
void attach (const MSFreqOffset &msFreqOffset)
Private Member Functions
MSFreqOffsetColumns (const MSFreqOffsetColumns &)
MSFreqOffsetColumns & operator= (const MSFreqOffsetColumns &)
Private Attributes
ScalarColumn< Int > antenna1_p
ScalarColumn< Int > antenna2_p
ScalarColumn< Int > feedId_p
ScalarColumn< Double > interval_p
ScalarColumn< Double > offset_p
ScalarColumn< Int > spectralWindowId_p
ScalarColumn< Double > time_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarQuantColumn< Double > intervalQuant_p
ScalarQuantColumn< Double > offsetQuant_p
ScalarQuantColumn< Double > timeQuant_p
Detailed Description
A class to provide easy read-write access to MSFreqOffset columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSFreqOffset
ScalarColumn
Etymology
MSFreqOffsetColumns stands for MeasurementSet FreqOffset Table columns.
Synopsis
This class provides access to the columns in the MSFreqOffset Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 179 of file MSFreqOffColumns.h.
Constructor & Destructor Documentation
MSFreqOffsetColumns() [1/3]
casacore::MSFreqOffsetColumns::MSFreqOffsetColumns (MSFreqOffset & msFreqOffset)
Create a columns object that accesses the data in the specified Table.
~MSFreqOffsetColumns()
casacore::MSFreqOffsetColumns::~MSFreqOffsetColumns ()
The destructor does nothing special.
MSFreqOffsetColumns() [2/3]
casacore::MSFreqOffsetColumns::MSFreqOffsetColumns () protected
MSFreqOffsetColumns() [3/3]
casacore::MSFreqOffsetColumns::MSFreqOffsetColumns (const MSFreqOffsetColumns &) private
Member Function Documentation
antenna1() [1/2]
ScalarColumn<Int>& casacore::MSFreqOffsetColumns::antenna1 () inline
Read-write access to required columns.
Definition at line 190 of file MSFreqOffColumns.h.
References antenna1_p.
antenna1() [2/2]
const ROScalarColumn<Int>& casacore::MSFreqOffsetColumns::antenna1 () const inline
Read-only access to required columns.
Definition at line 205 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::antenna1().
antenna2() [1/2]
ScalarColumn<Int>& casacore::MSFreqOffsetColumns::antenna2 () inline
Definition at line 191 of file MSFreqOffColumns.h.
References antenna2_p.
antenna2() [2/2]
const ROScalarColumn<Int>& casacore::MSFreqOffsetColumns::antenna2 () const inline
Definition at line 207 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::antenna2().
attach()
void casacore::MSFreqOffsetColumns::attach (MSFreqOffset & msFreqOffset) protected
feedId() [1/2]
ScalarColumn<Int>& casacore::MSFreqOffsetColumns::feedId () inline
Definition at line 192 of file MSFreqOffColumns.h.
References feedId_p.
feedId() [2/2]
const ROScalarColumn<Int>& casacore::MSFreqOffsetColumns::feedId () const inline
Definition at line 209 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::feedId().
interval() [1/2]
ScalarColumn<Double>& casacore::MSFreqOffsetColumns::interval () inline
Definition at line 193 of file MSFreqOffColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSFreqOffsetColumns::interval () const inline
Definition at line 211 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFreqOffsetColumns::intervalQuant () inline
Definition at line 194 of file MSFreqOffColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFreqOffsetColumns::intervalQuant () const inline
Definition at line 213 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::intervalQuant().
offset() [1/2]
ScalarColumn<Double>& casacore::MSFreqOffsetColumns::offset () inline
Definition at line 195 of file MSFreqOffColumns.h.
References offset_p.
offset() [2/2]
const ROScalarColumn<Double>& casacore::MSFreqOffsetColumns::offset () const inline
Definition at line 215 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::offset().
offsetQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFreqOffsetColumns::offsetQuant () inline
Definition at line 196 of file MSFreqOffColumns.h.
References offsetQuant_p.
offsetQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFreqOffsetColumns::offsetQuant () const inline
Definition at line 217 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::offsetQuant().
operator=()
MSFreqOffsetColumns& casacore::MSFreqOffsetColumns::operator= (const MSFreqOffsetColumns &) private
setEpochRef()
void casacore::MSFreqOffsetColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
spectralWindowId() [1/2]
ScalarColumn<Int>& casacore::MSFreqOffsetColumns::spectralWindowId () inline
Definition at line 197 of file MSFreqOffColumns.h.
References spectralWindowId_p.
spectralWindowId() [2/2]
const ROScalarColumn<Int>& casacore::MSFreqOffsetColumns::spectralWindowId () const inline
Definition at line 219 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::spectralWindowId().
time() [1/2]
ScalarColumn<Double>& casacore::MSFreqOffsetColumns::time () inline
Definition at line 198 of file MSFreqOffColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSFreqOffsetColumns::time () const inline
Definition at line 221 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSFreqOffsetColumns::timeMeas () inline
Definition at line 200 of file MSFreqOffColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSFreqOffsetColumns::timeMeas () const inline
Definition at line 225 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSFreqOffsetColumns::timeQuant () inline
Definition at line 199 of file MSFreqOffColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSFreqOffsetColumns::timeQuant () const inline
Definition at line 223 of file MSFreqOffColumns.h.
References casacore::ROMSFreqOffsetColumns::timeQuant().
Member Data Documentation
antenna1_p
ScalarColumn<Int> casacore::MSFreqOffsetColumns::antenna1_p private
Definition at line 255 of file MSFreqOffColumns.h.
Referenced by antenna1().
antenna2_p
ScalarColumn<Int> casacore::MSFreqOffsetColumns::antenna2_p private
Definition at line 256 of file MSFreqOffColumns.h.
Referenced by antenna2().
feedId_p
ScalarColumn<Int> casacore::MSFreqOffsetColumns::feedId_p private
Definition at line 257 of file MSFreqOffColumns.h.
Referenced by feedId().
interval_p
ScalarColumn<Double> casacore::MSFreqOffsetColumns::interval_p private
Definition at line 258 of file MSFreqOffColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSFreqOffsetColumns::intervalQuant_p private
Definition at line 267 of file MSFreqOffColumns.h.
Referenced by intervalQuant().
offset_p
ScalarColumn<Double> casacore::MSFreqOffsetColumns::offset_p private
Definition at line 259 of file MSFreqOffColumns.h.
Referenced by offset().
offsetQuant_p
ScalarQuantColumn<Double> casacore::MSFreqOffsetColumns::offsetQuant_p private
Definition at line 268 of file MSFreqOffColumns.h.
Referenced by offsetQuant().
spectralWindowId_p
ScalarColumn<Int> casacore::MSFreqOffsetColumns::spectralWindowId_p private
Definition at line 260 of file MSFreqOffColumns.h.
Referenced by spectralWindowId().
time_p
ScalarColumn<Double> casacore::MSFreqOffsetColumns::time_p private
Definition at line 261 of file MSFreqOffColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSFreqOffsetColumns::timeMeas_p private
Definition at line 264 of file MSFreqOffColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSFreqOffsetColumns::timeQuant_p private
Definition at line 269 of file MSFreqOffColumns.h.
Referenced by timeQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSFreqOffColumns.h