casacore: casacore::TableExprGroupAggr Class Reference
casacore::TableExprGroupAggr Class Reference
TaQL_module_internal_classes
Class collecting the arrays in a group.
#include <ExprGroup.h>
Public Member Functions
TableExprGroupAggr (TableExprNodeRep *node)
virtual ~TableExprGroupAggr ()
virtual Bool isLazy () const
Does the aggregate function use lazy semantics? The default implementation returns False.
virtual void apply (const TableExprId &id)
Get the operand's value for the given row and apply it to the aggregation.
virtual MArray< Bool > getArrayBool (const vector< TableExprId > &)
virtual MArray< Int64 > getArrayInt (const vector< TableExprId > &)
virtual MArray< Double > getArrayDouble (const vector< TableExprId > &)
virtual MArray< DComplex > getArrayDComplex (const vector< TableExprId > &)
virtual MArray< MVTime > getArrayDate (const vector< TableExprId > &)
virtual MArray< String > getArrayString (const vector< TableExprId > &)
Public Member Functions inherited from casacore::TableExprGroupFuncBase
TableExprGroupFuncBase (TableExprNodeRep *node)
Construct from the TaQL aggregation node.
virtual ~TableExprGroupFuncBase ()
uInt seqnr () const
Get the function's sequence nr.
void setSeqnr (uInt seqnr)
Set the function's sequence nr.
virtual void finish ()
If needed, finish the aggregation.
virtual CountedPtr< vector
< TableExprId > > getIds () const
Get the assembled TableExprIds of a group.
virtual Bool getBool (const vector< TableExprId > &=vector< TableExprId >())
Get the aggregated value.
virtual Int64 getInt (const vector< TableExprId > &=vector< TableExprId >())
virtual Double getDouble (const vector< TableExprId > &=vector< TableExprId >())
virtual DComplex getDComplex (const vector< TableExprId > &=vector< TableExprId >())
virtual MVTime getDate (const vector< TableExprId > &=vector< TableExprId >())
virtual String getString (const vector< TableExprId > &=vector< TableExprId >())
Protected Member Functions
template<typename T >
MArray< T > getArray (const vector< TableExprId > &ids)
Additional Inherited Members
Protected Attributes inherited from casacore::TableExprGroupFuncBase
TableExprNodeRep * itsNode
TableExprNodeRep * itsOperand
uInt itsSeqnr
Detailed Description
Class collecting the arrays in a group.
Intended use:
Internal
Review Status
Test programs:
tExprGroup
Synopsis
This class collects the non-empty arrays in a group into an array with one more axis. All arrays (if not empty) must have the same shape.
Definition at line 378 of file ExprGroup.h.
Constructor & Destructor Documentation
casacore::TableExprGroupAggr::TableExprGroupAggr (TableExprNodeRep * node) explicit
virtual casacore::TableExprGroupAggr::~TableExprGroupAggr () virtual
Member Function Documentation
virtual void casacore::TableExprGroupAggr::apply (const TableExprId & id) virtual
Get the operand's value for the given row and apply it to the aggregation.
This function should not be called for lazy classes.
Implements casacore::TableExprGroupFuncBase.
template<typename T > MArray<T> casacore::TableExprGroupAggr::getArray (const vector< TableExprId > & ids) inline protected
Return scalar values as a Vector.
Array values are returned as an array with one more axis. Use the first non-null value to determine the shape and if masked.
All arrays are null.
Definition at line 393 of file ExprGroup.h.
References casacore::IPosition::append(), casacore::MArray< T >::array(), casacore::False, casacore::TableExprNodeRep::get(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), casacore::TableExprGroupFuncBase::itsOperand, casacore::MArrayBase::mask(), casacore::mask(), casacore::MArrayBase::ndim(), casacore::Array< T >::resize(), casacore::MArrayBase::shape(), casacore::IPosition::size(), casacore::True, casacore::TableExprNodeRep::valueType(), and casacore::TableExprNodeRep::VTScalar.
virtual MArray<Bool> casacore::TableExprGroupAggr::getArrayBool (const vector< TableExprId > &) virtual
Reimplemented from casacore::TableExprGroupFuncBase.
virtual MArray<MVTime> casacore::TableExprGroupAggr::getArrayDate (const vector< TableExprId > &) virtual
Reimplemented from casacore::TableExprGroupFuncBase.
virtual MArray<DComplex> casacore::TableExprGroupAggr::getArrayDComplex (const vector< TableExprId > &) virtual
Reimplemented from casacore::TableExprGroupFuncBase.
virtual MArray<Double> casacore::TableExprGroupAggr::getArrayDouble (const vector< TableExprId > &) virtual
Reimplemented from casacore::TableExprGroupFuncBase.
virtual MArray<Int64> casacore::TableExprGroupAggr::getArrayInt (const vector< TableExprId > &) virtual
Reimplemented from casacore::TableExprGroupFuncBase.
virtual MArray<String> casacore::TableExprGroupAggr::getArrayString (const vector< TableExprId > &) virtual
Reimplemented from casacore::TableExprGroupFuncBase.
virtual Bool casacore::TableExprGroupAggr::isLazy () const virtual
Does the aggregate function use lazy semantics? The default implementation returns False.
Reimplemented from casacore::TableExprGroupFuncBase.
The documentation for this class was generated from the following file:
tables/TaQL/ExprGroup.h