casacore: casacore::MSSelectableMainColumn Class Reference
casacore::MSSelectableMainColumn Class Reference abstract
#include <MSSelectableMainColumn.h>
Public Member Functions
MSSelectableMainColumn (const Table &msLikeTable)
MSSelectableMainColumn ()
virtual ~MSSelectableMainColumn ()
virtual void init (const Table &msLikeTable)
const Table * table ()
virtual const ROArrayColumn< Bool > & flag ()=0
virtual Bool flagRow (const Int &i)=0
virtual const ROScalarQuantColumn< Double > & exposureQuant ()=0
virtual const ROScalarQuantColumn< Double > & timeQuant ()=0
virtual const MeasurementSet * asMS ()=0
Protected Attributes
const Table * table_p
Detailed Description
Definition at line 46 of file MSSelectableMainColumn.h.
Constructor & Destructor Documentation
MSSelectableMainColumn() [1/2]
casacore::MSSelectableMainColumn::MSSelectableMainColumn (const Table & msLikeTable) inline
Definition at line 49 of file MSSelectableMainColumn.h.
References init().
MSSelectableMainColumn() [2/2]
casacore::MSSelectableMainColumn::MSSelectableMainColumn () inline
Definition at line 50 of file MSSelectableMainColumn.h.
References table_p.
~MSSelectableMainColumn()
virtual casacore::MSSelectableMainColumn::~MSSelectableMainColumn () inline virtual
Definition at line 51 of file MSSelectableMainColumn.h.
Member Function Documentation
asMS()
virtual const MeasurementSet* casacore::MSSelectableMainColumn::asMS () pure virtual
Implemented in casacore::MSMainColInterface.
exposureQuant()
virtual const ROScalarQuantColumn<Double>& casacore::MSSelectableMainColumn::exposureQuant () pure virtual
Implemented in casacore::MSMainColInterface.
flag()
virtual const ROArrayColumn<Bool>& casacore::MSSelectableMainColumn::flag () pure virtual
Implemented in casacore::MSMainColInterface.
flagRow()
virtual Bool casacore::MSSelectableMainColumn::flagRow (const Int & i) pure virtual
Implemented in casacore::MSMainColInterface.
init()
virtual void casacore::MSSelectableMainColumn::init (const Table & msLikeTable) inline virtual
Reimplemented in casacore::MSMainColInterface.
Definition at line 53 of file MSSelectableMainColumn.h.
References table_p.
Referenced by casacore::MSMainColInterface::init(), and MSSelectableMainColumn().
table()
const Table* casacore::MSSelectableMainColumn::table () inline
Definition at line 54 of file MSSelectableMainColumn.h.
References table_p.
Referenced by casacore::MSMainColInterface::asMS().
timeQuant()
virtual const ROScalarQuantColumn<Double>& casacore::MSSelectableMainColumn::timeQuant () pure virtual
Implemented in casacore::MSMainColInterface.
Member Data Documentation
table_p
const Table* casacore::MSSelectableMainColumn::table_p protected
Definition at line 62 of file MSSelectableMainColumn.h.
Referenced by init(), MSSelectableMainColumn(), and table().
The documentation for this class was generated from the following file:
ms/MSSel/MSSelectableMainColumn.h