casacore: casacore::PolynomialParam< T > Class Template Reference
casacore::PolynomialParam< T > Class Template Reference
Functionals_module
Parameter handling for one-dimensional polynomials.
#include <PolynomialParam.h>
Public Member Functions
PolynomialParam ()
Constructs a zero'th order polynomial, with a coeficcient of 0.0.
PolynomialParam (uInt order)
Makes a polynomial of the given order, with all coeficcients set to zero.
PolynomialParam (const PolynomialParam< T > &other)
Make this a copy of other (deep copy).
template<class W >
PolynomialParam (const PolynomialParam< W > &other)
PolynomialParam< T > & operator= (const PolynomialParam< T > &other)
~PolynomialParam ()
Destructor.
Bool operator== (const PolynomialParam< T > &other) const
Comparisons.
Bool operator!= (const PolynomialParam< T > &other) const
virtual const String & name () const
Give name of function.
uInt order () const
What is the order of the polynomial, i.e.
T coefficient (uInt which) const
What is the which'th coefficient of the polynomial.
const Vector< T > & coefficients () const
Return all the coefficients as a vector.
void setCoefficient (uInt which, const T value)
Set the which'th coefficient to value.
void setCoefficients (const Vector< T > &coefficients)
Set all the coefficients at once, throw away all existing coefficients.
Public Member Functions inherited from casacore::Function1D< T >
Function1D ()
Constructors.
Function1D (const uInt n)
Function1D (const Vector< T > &in)
Function1D (const FunctionParam< T > &other)
Function1D (const Function1D< W, X > &other)
virtual ~Function1D ()
Destructor.
virtual uInt ndim () const
Returns the number of dimensions of function.
Public Member Functions inherited from casacore::Function< T, T >
Function ()
Constructors.
Function (const uInt n)
Function (const Vector< T > &in)
Function (const FunctionParam< T > &other)
Function (const Function< W, X > &other)
virtual ~Function ()
Destructor.
uInt nparameters () const
Returns the number of parameters.
virtual T eval (FunctionArg x) const =0
Evaluate the function object.
T & operator[] (const uInt n)
Manipulate the nth parameter (0-based) with no index check.
const T & operator[] (const uInt n) const
virtual T operator() () const
Evaluate this function object at xor at x, y.
virtual T operator() (const ArgType &x) const
virtual T operator() (const Vector< ArgType > &x) const
virtual T operator() (FunctionArg x) const
virtual T operator() (const ArgType &x, const ArgType &y) const
virtual T operator() (const ArgType &x, const ArgType &y, const ArgType &z) const
Bool & mask (const uInt n)
Manipulate the mask associated with the nth parameter (e.g.
const Bool & mask (const uInt n) const
const FunctionParam< T > & parameters () const
Return the parameter interface.
FunctionParam< T > & parameters ()
const Vector< ArgType > & argp () const
Get arg_p and parset_p.
Bool parsetp () const
void lockParam ()
Compiler cannot always find the correct 'const' version of parameter access.
void unlockParam ()
virtual void setMode (const RecordInterface &mode)
get/set the function mode.
virtual void getMode (RecordInterface &mode) const
virtual Bool hasMode () const
return True if the implementing function supports a mode.
ostream & print (ostream &os) const
Print the function (i.e.
virtual Function< T, T > * clone () const =0
Return a copy of this object from the heap.
virtual Function< typename
FunctionTraits< T >::DiffType > * cloneAD () const
virtual Function< typename
FunctionTraits< T >::BaseType > * cloneNonAD () const
Public Member Functions inherited from casacore::Functional< FunctionTraits< T >::ArgType, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const FunctionTraits< T >::ArgType &x) const =0
Map a Domain x into a Range y value.
Public Member Functions inherited from casacore::Functional< Vector< FunctionTraits< T >::ArgType >, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const Vector< FunctionTraits< T >::ArgType > &x) const =0
Map a Domain x into a Range y value.
Additional Inherited Members
Public Types inherited from casacore::Function1D< T >
typedef const T * FunctionArg
Public Types inherited from casacore::Function< T, T >
typedef FunctionTraits< T >
::ArgType ArgType
typedef const ArgType * FunctionArg
Protected Attributes inherited from casacore::Function< T, T >
FunctionParam< T > param_p
The parameters and masks.
Vector< ArgType > arg_p
Aid for non-contiguous argument storage.
Bool parset_p
Indicate parameter written.
Bool locked_p
Indicate that parameters are expected to be locked from changing.
Detailed Description
template<class T>
class casacore::PolynomialParam< T >
Parameter handling for one-dimensional polynomials.
Review Status
Reviewed By:
tcornwel
Date Reviewed:
1996/02/22
Test programs:
tPolynomial
Prerequisite
FunctionParam class
Function1D
Etymology
A 1-dimensional Polynomial's parameters.
Synopsis
A Polynomial is described by a set of coefficients; its fundamental operation is evaluating itself at some "x". The number of coefficients is the order of the polynomial plus one.
Since the Polynomial is a Function, the derivatives can be obtained as well.
The parameter interface (see FunctionParam class), is used to provide an interface to the Fitting classes.
This class is in general used implicitly by the Polynomial class only.
Example
Polynomial<Float> pf(3);  // Third order polynomial - coeffs 0 by default
pf.setCoefficient(1, 1.0);
pf[2] = 2.0;
pf.setCoefficient(3, 3.0);  // 3x^3 + 2x^2 + x
pf(2); // == 34
Template Type Argument Requirements (T)
T should have standard numerical operators. Current implementation only tested for real types (and their AutoDiffs).
Thrown Exceptions
Assertion in debug mode if attempt is made to address incorrect coefficients
To Do
Global functions to make various ``special'' polynomials of various orders will be useful eventually.
Definition at line 98 of file PolynomialParam.h.
Constructor & Destructor Documentation
template<class T> casacore::PolynomialParam< T >::PolynomialParam ()
Constructs a zero'th order polynomial, with a coeficcient of 0.0.
template<class T> casacore::PolynomialParam< T >::PolynomialParam (uInt order) explicit
Makes a polynomial of the given order, with all coeficcients set to zero.
template<class T> casacore::PolynomialParam< T >::PolynomialParam (const PolynomialParam< T > & other)
Make this a copy of other (deep copy).
template<class T> template<class W > casacore::PolynomialParam< T >::PolynomialParam (const PolynomialParam< W > & other) inline
Definition at line 112 of file PolynomialParam.h.
template<class T> casacore::PolynomialParam< T >::~PolynomialParam ()
Destructor.
Member Function Documentation
template<class T> T casacore::PolynomialParam< T >::coefficient (uInt which) const inline
What is the which'th coefficient of the polynomial.
For an nth degree polynomial, which varies between zero and n.
Definition at line 140 of file PolynomialParam.h.
template<class T> const Vector<T>& casacore::PolynomialParam< T >::coefficients () const
Return all the coefficients as a vector.
template<class T> virtual const String& casacore::PolynomialParam< T >::name () const inline virtual
Give name of function.
Reimplemented from casacore::Function< T, T >.
Definition at line 132 of file PolynomialParam.h.
template<class T> Bool casacore::PolynomialParam< T >::operator!= (const PolynomialParam< T > & other) const inline
Definition at line 126 of file PolynomialParam.h.
template<class T> PolynomialParam<T>& casacore::PolynomialParam< T >::operator= (const PolynomialParam< T > & other)
Referenced by casacore::Polynomial< Double >::operator=().
template<class T> Bool casacore::PolynomialParam< T >::operator== (const PolynomialParam< T > & other) const inline
Comparisons.
Polynomials are equal if they are the same order
Definition at line 124 of file PolynomialParam.h.
template<class T> uInt casacore::PolynomialParam< T >::order () const inline
What is the order of the polynomial, i.e.
maximum exponent of "x".
Definition at line 136 of file PolynomialParam.h.
Referenced by casacore::PolynomialParam< AutoDiff< T > >::coefficient(), and casacore::PolynomialParam< AutoDiff< T > >::setCoefficient().
template<class T> void casacore::PolynomialParam< T >::setCoefficient (uInt which, const T value) inline
Set the which'th coefficient to value.
Definition at line 147 of file PolynomialParam.h.
template<class T> void casacore::PolynomialParam< T >::setCoefficients (const Vector< T > & coefficients)
Set all the coefficients at once, throw away all existing coefficients.
The documentation for this class was generated from the following file:
scimath/Functionals/PolynomialParam.h