casacore: casacore::CombiParam< T > Class Template Reference
casacore::CombiParam< T > Class Template Reference
Functionals_module_internal_classes
Parameters for a linear combination of function objects.
#include <CombiParam.h>
Public Member Functions
CombiParam ()
The default constructor – no functions, no parameters, nothing, the function operator returns a 0.
CombiParam (const CombiParam< T > &other)
Make this object a (deep) copy of other.
CombiParam (const CombiParam< T > &other, Bool)
template<class W >
CombiParam (const CombiParam< W > &other)
template<class W >
CombiParam (const CombiParam< W > &other, Bool)
CombiParam< T > & operator= (const CombiParam< T > &other)
Make this object a (deep) copy of other.
virtual ~CombiParam ()
Destructor.
virtual const String & name () const
Give name of function.
uInt addFunction (const Function< T > &newFunction)
Add a function.
uInt nFunctions () const
Return the total number of functions.
const Function< T > & function (uInt which) const
Return a reference to a specific Function in the combination.
const Function< T > & function (uInt which)
virtual uInt ndim () const
Returns the dimension of functions in the linear combination.
Public Member Functions inherited from casacore::Function< T >
Function ()
Constructors.
Function (const uInt n)
Function (const Vector< T > &in)
Function (const FunctionParam< T > &other)
Function (const Function< W, X > &other)
Function (const Function< T, T > &other)
virtual ~Function ()
Destructor.
uInt nparameters () const
Returns the number of parameters.
virtual T eval (FunctionArg x) const =0
Evaluate the function object.
T & operator[] (const uInt n)
Manipulate the nth parameter (0-based) with no index check.
const T & operator[] (const uInt n) const
virtual T operator() () const
Evaluate this function object at xor at x, y.
virtual T operator() (const ArgType &x) const
virtual T operator() (const Vector< ArgType > &x) const
virtual T operator() (FunctionArg x) const
virtual T operator() (const ArgType &x, const ArgType &y) const
virtual T operator() (const ArgType &x, const ArgType &y, const ArgType &z) const
Bool & mask (const uInt n)
Manipulate the mask associated with the nth parameter (e.g.
const Bool & mask (const uInt n) const
const FunctionParam< T > & parameters () const
Return the parameter interface.
FunctionParam< T > & parameters ()
const Vector< ArgType > & argp () const
Get arg_p and parset_p.
Bool parsetp () const
void lockParam ()
Compiler cannot always find the correct 'const' version of parameter access.
void unlockParam ()
virtual void setMode (const RecordInterface &mode)
get/set the function mode.
virtual void getMode (RecordInterface &mode) const
virtual Bool hasMode () const
return True if the implementing function supports a mode.
ostream & print (ostream &os) const
Print the function (i.e.
virtual Function< T, T > * clone () const =0
Return a copy of this object from the heap.
virtual Function< typename
FunctionTraits< T >::DiffType > * cloneAD () const
virtual Function< typename
FunctionTraits< T >::BaseType > * cloneNonAD () const
Public Member Functions inherited from casacore::Functional< FunctionTraits< T >::ArgType, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const FunctionTraits< T >::ArgType &x) const =0
Map a Domain x into a Range y value.
Public Member Functions inherited from casacore::Functional< Vector< FunctionTraits< T >::ArgType >, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const Vector< FunctionTraits< T >::ArgType > &x) const =0
Map a Domain x into a Range y value.
Protected Attributes
uInt ndim_p
Number of dimensions of underlying functions.
PtrBlock< Function< T > * > functionPtr_p
Pointer to each added function.
Protected Attributes inherited from casacore::Function< T >
FunctionParam< T > param_p
The parameters and masks.
Vector< ArgType > arg_p
Aid for non-contiguous argument storage.
Bool parset_p
Indicate parameter written.
Bool locked_p
Indicate that parameters are expected to be locked from changing.
Additional Inherited Members
Public Types inherited from casacore::Function< T >
typedef FunctionTraits< T >
::ArgType ArgType
typedef const ArgType * FunctionArg
Detailed Description
template<class T>
class casacore::CombiParam< T >
Parameters for a linear combination of function objects.
 @anchor CombiParam_summary
Intended use:
Internal
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Test programs:
tCombiFunction
Prerequisite
CombiFunction class
Synopsis
Given N function objects, the class describes a linear combination of the form:
f(x) = a(0)*f(0)(x) + a(1)*f(1)(x) + ... + a(N-1)*f(N-1)(x)
where a = {a(n)} are parameters. If the combi function is used in a functional fitting process (see LinearFit) these parameters canm be solved for. In all aspects they behave as FunctionParam values.
Member functions are added with the addFunction() method.
Example
In the following example a second order polynomial is built from 3 separate polynomials.
Polynomial<Double> constant(0);
Polynomial<Double> linear(1);
Polynomial<Double> square(2);
constant.setCoefficient(0, 1.0);   // 1
linear.setCoefficient(1, 1.0);     // x
square[2] = 1.0;     // x^2
CombiParam<Double> combination;
// form function, e0 + e1*x + e2*x^2
combination.addFunction(constant);
combination.addFunction(linear);
combination.addFunction(square);
Template Type Argument Requirements (T)
T should have standard numerical operators and exp() function. Current implementation only tested for real types.
To obtain derivatives, the derivatives should be defined.
Thrown Exceptions
AipsError if dimensions of functions added different
Motivation
This class was created to allow specialization of the evaluation in a simple way.
To Do
Nothing I know of
Definition at line 111 of file CombiParam.h.
Constructor & Destructor Documentation
template<class T> casacore::CombiParam< T >::CombiParam ()
The default constructor – no functions, no parameters, nothing, the function operator returns a 0.
template<class T> casacore::CombiParam< T >::CombiParam (const CombiParam< T > & other)
Make this object a (deep) copy of other.
template<class T> casacore::CombiParam< T >::CombiParam (const CombiParam< T > & other, Bool) inline
Definition at line 121 of file CombiParam.h.
template<class T> template<class W > casacore::CombiParam< T >::CombiParam (const CombiParam< W > & other) inline
Definition at line 129 of file CombiParam.h.
template<class T> template<class W > casacore::CombiParam< T >::CombiParam (const CombiParam< W > & other, Bool) inline
Definition at line 137 of file CombiParam.h.
template<class T> virtual casacore::CombiParam< T >::~CombiParam () virtual
Destructor.
Member Function Documentation
template<class T> uInt casacore::CombiParam< T >::addFunction (const Function< T > & newFunction)
Add a function.
All functions must have the same ndim() as the first one. Returns the (zero relative) number (i) of the function just added. The default initial parameter value (a(i)) is initialized to 1. The parameter mask is set True.
template<class T> const Function<T>& casacore::CombiParam< T >::function (uInt which) const inline
Return a reference to a specific Function in the combination.
Definition at line 170 of file CombiParam.h.
Referenced by casacore::CombiParam< AutoDiff< T > >::CombiParam().
template<class T> const Function<T>& casacore::CombiParam< T >::function (uInt which) inline
Definition at line 173 of file CombiParam.h.
template<class T> virtual const String& casacore::CombiParam< T >::name () const inline virtual
Give name of function.
Reimplemented from casacore::Function< T >.
Definition at line 154 of file CombiParam.h.
template<class T> virtual uInt casacore::CombiParam< T >::ndim () const inline virtual
Returns the dimension of functions in the linear combination.
Implements casacore::Function< T >.
Definition at line 179 of file CombiParam.h.
template<class T> uInt casacore::CombiParam< T >::nFunctions () const inline
Return the total number of functions.
The number is equal to the number of functions that have been added.
Definition at line 166 of file CombiParam.h.
Referenced by casacore::CombiParam< AutoDiff< T > >::CombiParam(), and casacore::CombiParam< AutoDiff< T > >::function().
template<class T> CombiParam<T>& casacore::CombiParam< T >::operator= (const CombiParam< T > & other)
Make this object a (deep) copy of other.
Member Data Documentation
template<class T> PtrBlock<Function<T> *> casacore::CombiParam< T >::functionPtr_p protected
Pointer to each added function.
Definition at line 187 of file CombiParam.h.
Referenced by casacore::CombiParam< AutoDiff< T > >::CombiParam(), and casacore::CombiParam< AutoDiff< T > >::function().
template<class T> uInt casacore::CombiParam< T >::ndim_p protected
Number of dimensions of underlying functions.
Definition at line 184 of file CombiParam.h.
Referenced by casacore::CombiParam< AutoDiff< T > >::ndim().
The documentation for this class was generated from the following file:
scimath/Functionals/CombiParam.h