casacore: casacore::ROMSDopplerColumns Class Reference
casacore::ROMSDopplerColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSDoppler columns.
#include <MSDopplerColumns.h>
Public Member Functions
ROMSDopplerColumns (const MSDoppler &msDoppler)
Create a columns object that accesses the data in the specified Table.
~ROMSDopplerColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSDoppler table is optional)
const ROScalarColumn< Int > & dopplerId () const
Access to columns.
const ROScalarColumn< Int > & sourceId () const
const ROScalarColumn< Int > & transitionId () const
const ROScalarColumn< Double > & velDef () const
const ROScalarQuantColumn< Double > & velDefQuant () const
const ROScalarMeasColumn< MDoppler > & velDefMeas () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSDopplerColumns ()
void attach (const MSDoppler &msDoppler)
Private Member Functions
ROMSDopplerColumns (const ROMSDopplerColumns &)
ROMSDopplerColumns & operator= (const ROMSDopplerColumns &)
Private Attributes
Bool isNull_p
ROScalarColumn< Int > dopplerId_p
ROScalarColumn< Int > sourceId_p
ROScalarColumn< Int > transitionId_p
ROScalarColumn< Double > velDef_p
ROScalarMeasColumn< MDoppler > velDefMeas_p
ROScalarQuantColumn< Double > velDefQuant_p
Detailed Description
A class to provide easy read-only access to MSDoppler columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSDoppler
ScalarColumn
Etymology
ROMSDopplerColumns stands for Read-Only MeasurementSet Doppler Table columns.
Synopsis
This class provides read-only access to the columns in the MSDoppler Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 75 of file MSDopplerColumns.h.
Constructor & Destructor Documentation
ROMSDopplerColumns() [1/3]
casacore::ROMSDopplerColumns::ROMSDopplerColumns (const MSDoppler & msDoppler)
Create a columns object that accesses the data in the specified Table.
~ROMSDopplerColumns()
casacore::ROMSDopplerColumns::~ROMSDopplerColumns ()
The destructor does nothing special.
ROMSDopplerColumns() [2/3]
casacore::ROMSDopplerColumns::ROMSDopplerColumns () protected
ROMSDopplerColumns() [3/3]
casacore::ROMSDopplerColumns::ROMSDopplerColumns (const ROMSDopplerColumns &) private
Member Function Documentation
attach()
void casacore::ROMSDopplerColumns::attach (const MSDoppler & msDoppler) protected
dopplerId()
const ROScalarColumn<Int>& casacore::ROMSDopplerColumns::dopplerId () const inline
Access to columns.
Definition at line 89 of file MSDopplerColumns.h.
References dopplerId_p.
Referenced by casacore::MSDopplerColumns::dopplerId().
isNull()
Bool casacore::ROMSDopplerColumns::isNull () const inline
Is this object defined? (MSDoppler table is optional)
Definition at line 85 of file MSDopplerColumns.h.
References isNull_p.
Referenced by nrow().
nrow()
uInt casacore::ROMSDopplerColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Returns zero if the object is null.
Definition at line 99 of file MSDopplerColumns.h.
References dopplerId_p, and isNull().
operator=()
ROMSDopplerColumns& casacore::ROMSDopplerColumns::operator= (const ROMSDopplerColumns &) private
sourceId()
const ROScalarColumn<Int>& casacore::ROMSDopplerColumns::sourceId () const inline
Definition at line 90 of file MSDopplerColumns.h.
References sourceId_p.
Referenced by casacore::MSDopplerColumns::sourceId().
transitionId()
const ROScalarColumn<Int>& casacore::ROMSDopplerColumns::transitionId () const inline
Definition at line 91 of file MSDopplerColumns.h.
References transitionId_p.
Referenced by casacore::MSDopplerColumns::transitionId().
velDef()
const ROScalarColumn<Double>& casacore::ROMSDopplerColumns::velDef () const inline
Definition at line 92 of file MSDopplerColumns.h.
References velDef_p.
Referenced by casacore::MSDopplerColumns::velDef().
velDefMeas()
const ROScalarMeasColumn<MDoppler>& casacore::ROMSDopplerColumns::velDefMeas () const inline
Definition at line 94 of file MSDopplerColumns.h.
References velDefMeas_p.
Referenced by casacore::MSDopplerColumns::velDefMeas().
velDefQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSDopplerColumns::velDefQuant () const inline
Definition at line 93 of file MSDopplerColumns.h.
References velDefQuant_p.
Referenced by casacore::MSDopplerColumns::velDefQuant().
Member Data Documentation
dopplerId_p
ROScalarColumn<Int> casacore::ROMSDopplerColumns::dopplerId_p private
Definition at line 119 of file MSDopplerColumns.h.
Referenced by dopplerId(), and nrow().
isNull_p
Bool casacore::ROMSDopplerColumns::isNull_p private
Definition at line 116 of file MSDopplerColumns.h.
Referenced by isNull().
sourceId_p
ROScalarColumn<Int> casacore::ROMSDopplerColumns::sourceId_p private
Definition at line 120 of file MSDopplerColumns.h.
Referenced by sourceId().
transitionId_p
ROScalarColumn<Int> casacore::ROMSDopplerColumns::transitionId_p private
Definition at line 121 of file MSDopplerColumns.h.
Referenced by transitionId().
velDef_p
ROScalarColumn<Double> casacore::ROMSDopplerColumns::velDef_p private
Definition at line 122 of file MSDopplerColumns.h.
Referenced by velDef().
velDefMeas_p
ROScalarMeasColumn<MDoppler> casacore::ROMSDopplerColumns::velDefMeas_p private
Definition at line 125 of file MSDopplerColumns.h.
Referenced by velDefMeas().
velDefQuant_p
ROScalarQuantColumn<Double> casacore::ROMSDopplerColumns::velDefQuant_p private
Definition at line 128 of file MSDopplerColumns.h.
Referenced by velDefQuant().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSDopplerColumns.h