casacore: casacore::MSPointingColumns Class Reference
casacore::MSPointingColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSPointing columns.
#include <MSPointingColumns.h>
Public Member Functions
MSPointingColumns (MSPointing &msPointing)
Construct from the supplied Table.
~MSPointingColumns ()
The destructor does nothing special.
ScalarColumn< Int > & antennaId ()
Read-write access to required columns.
ScalarColumn< Double > & time ()
ScalarMeasColumn< MEpoch > & timeMeas ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< String > & name ()
ScalarColumn< Int > & numPoly ()
ScalarColumn< Double > & timeOrigin ()
ScalarQuantColumn< Double > & timeOriginQuant ()
ScalarMeasColumn< MEpoch > & timeOriginMeas ()
ArrayColumn< Double > & direction ()
ArrayMeasColumn< MDirection > & directionMeasCol ()
ArrayColumn< Double > & target ()
ArrayMeasColumn< MDirection > & targetMeasCol ()
ScalarColumn< Bool > & tracking ()
ArrayColumn< Double > & pointingOffset ()
Read-write access to optional columns.
ArrayMeasColumn< MDirection > & pointingOffsetMeasCol ()
ArrayColumn< Double > & sourceOffset ()
ArrayMeasColumn< MDirection > & sourceOffsetMeasCol ()
ArrayColumn< Double > & encoder ()
ScalarMeasColumn< MDirection > & encoderMeas ()
ScalarColumn< Int > & pointingModelId ()
ScalarColumn< Bool > & onSource ()
ScalarColumn< Bool > & overTheTop ()
const ROScalarColumn< Int > & antennaId () const
Read-only access to required columns.
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & numPoly () const
const ROScalarColumn< Double > & timeOrigin () const
const ROScalarQuantColumn< Double > & timeOriginQuant () const
const ROScalarMeasColumn< MEpoch > & timeOriginMeas () const
const ROArrayColumn< Double > & direction () const
const ROArrayMeasColumn< MDirection > & directionMeasCol () const
const ROArrayColumn< Double > & target () const
const ROArrayMeasColumn< MDirection > & targetMeasCol () const
const ROScalarColumn< Bool > & tracking () const
const ROArrayColumn< Double > & pointingOffset () const
Access to optional columns.
const ROArrayMeasColumn< MDirection > & pointingOffsetMeasCol () const
const ROArrayColumn< Double > & sourceOffset () const
const ROArrayMeasColumn< MDirection > & sourceOffsetMeasCol () const
const ROArrayColumn< Double > & encoder () const
const ROScalarMeasColumn< MDirection > & encoderMeas () const
const ROScalarColumn< Int > & pointingModelId () const
const ROScalarColumn< Bool > & onSource () const
const ROScalarColumn< Bool > & overTheTop () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch reference type for the TIME & TIME_ORIGIN column.
void setDirectionRef (MDirection::Types ref)
set the direction reference type for the DIRECTION, TARGET & and, if defined, the SOURCE_OFFSET & POINTING_OFFSET columns.
void setEncoderDirectionRef (MDirection::Types ref)
set the direction reference type for the ENCODER column (if it is defined).
Public Member Functions inherited from casacore::ROMSPointingColumns
ROMSPointingColumns (const MSPointing &msPointing)
Create a columns object that accesses the data in the specified Table.
~ROMSPointingColumns ()
The destructor does nothing special.
const ROScalarColumn< Int > & antennaId () const
Access to required columns.
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & numPoly () const
const ROScalarColumn< Double > & timeOrigin () const
const ROScalarQuantColumn< Double > & timeOriginQuant () const
const ROScalarMeasColumn< MEpoch > & timeOriginMeas () const
const ROArrayColumn< Double > & direction () const
const ROArrayMeasColumn< MDirection > & directionMeasCol () const
const ROArrayColumn< Double > & target () const
const ROArrayMeasColumn< MDirection > & targetMeasCol () const
const ROScalarColumn< Bool > & tracking () const
const ROArrayColumn< Double > & pointingOffset () const
Access to optional columns.
const ROArrayMeasColumn< MDirection > & pointingOffsetMeasCol () const
const ROArrayColumn< Double > & sourceOffset () const
const ROArrayMeasColumn< MDirection > & sourceOffsetMeasCol () const
const ROArrayColumn< Double > & encoder () const
const ROScalarMeasColumn< MDirection > & encoderMeas () const
const ROScalarColumn< Int > & pointingModelId () const
const ROScalarColumn< Bool > & onSource () const
const ROScalarColumn< Bool > & overTheTop () const
MDirection directionMeas (Int row, Double time=0) const
Access to interpolated directions, the default time of zero will return the 0th order element of the polynomial.
MDirection targetMeas (Int row, Double time=0) const
MDirection pointingOffsetMeas (Int row, Double time=0) const
MDirection sourceOffsetMeas (Int row, Double time=0) const
Int pointingIndex (Int antenna, Double time, Int guessRow=0) const
return the first matching row index for this time and antenna, returns -1 if no match was found For long tables you may give a guess row...the last return is usually a good one.
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSPointingColumns ()
void attach (MSPointing &msPointing)
Protected Member Functions inherited from casacore::ROMSPointingColumns
ROMSPointingColumns ()
void attach (const MSPointing &msPointing)
Private Member Functions
MSPointingColumns (const MSPointingColumns &)
MSPointingColumns & operator= (const MSPointingColumns &)
void attachOptionalCols (MSPointing &msPointing)
Private Attributes
ScalarColumn< Int > antennaId_p
ArrayColumn< Double > direction_p
ScalarColumn< Double > interval_p
ScalarColumn< String > name_p
ScalarColumn< Int > numPoly_p
ArrayColumn< Double > target_p
ScalarColumn< Double > time_p
ScalarColumn< Double > timeOrigin_p
ScalarColumn< Bool > tracking_p
ArrayColumn< Double > encoder_p
ScalarColumn< Bool > onSource_p
ScalarColumn< Int > pointingModelId_p
ArrayColumn< Double > pointingOffset_p
ArrayColumn< Double > sourceOffset_p
ScalarColumn< Bool > overTheTop_p
ArrayMeasColumn< MDirection > directionMeas_p
ArrayMeasColumn< MDirection > targetMeas_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarMeasColumn< MEpoch > timeOriginMeas_p
ScalarMeasColumn< MDirection > encoderMeas_p
ArrayMeasColumn< MDirection > pointingOffsetMeas_p
ArrayMeasColumn< MDirection > sourceOffsetMeas_p
ScalarQuantColumn< Double > intervalQuant_p
ScalarQuantColumn< Double > timeQuant_p
ScalarQuantColumn< Double > timeOriginQuant_p
Detailed Description
A class to provide easy read-write access to MSPointing columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSPointing
ArrayColumn
ScalarColumn
Etymology
MSPointingColumns stands for MeasurementSet Pointing Table columns.
Synopsis
This class provides access to the columns in the MSPointing Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 233 of file MSPointingColumns.h.
Constructor & Destructor Documentation
MSPointingColumns() [1/3]
casacore::MSPointingColumns::MSPointingColumns (MSPointing & msPointing)
Construct from the supplied Table.
~MSPointingColumns()
casacore::MSPointingColumns::~MSPointingColumns ()
The destructor does nothing special.
MSPointingColumns() [2/3]
casacore::MSPointingColumns::MSPointingColumns () protected
MSPointingColumns() [3/3]
casacore::MSPointingColumns::MSPointingColumns (const MSPointingColumns &) private
Member Function Documentation
antennaId() [1/2]
ScalarColumn<Int>& casacore::MSPointingColumns::antennaId () inline
Read-write access to required columns.
Note that the direction measures with a stored polynomial have Col() added to their name. They are better accessed via the functions that have the same name, without the Col suffix, that will do the interpolation for you. These functions are in the ROMSPointingColumns class.
Definition at line 249 of file MSPointingColumns.h.
References antennaId_p.
antennaId() [2/2]
const ROScalarColumn<Int>& casacore::MSPointingColumns::antennaId () const inline
Read-only access to required columns.
Definition at line 289 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::antennaId().
attach()
void casacore::MSPointingColumns::attach (MSPointing & msPointing) protected
attachOptionalCols()
void casacore::MSPointingColumns::attachOptionalCols (MSPointing & msPointing) private
direction() [1/2]
ArrayColumn<Double>& casacore::MSPointingColumns::direction () inline
Definition at line 260 of file MSPointingColumns.h.
References direction_p.
direction() [2/2]
const ROArrayColumn<Double>& casacore::MSPointingColumns::direction () const inline
Definition at line 311 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::direction().
directionMeasCol() [1/2]
ArrayMeasColumn<MDirection>& casacore::MSPointingColumns::directionMeasCol () inline
Definition at line 261 of file MSPointingColumns.h.
References directionMeas_p.
directionMeasCol() [2/2]
const ROArrayMeasColumn<MDirection>& casacore::MSPointingColumns::directionMeasCol () const inline
Definition at line 313 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::directionMeasCol().
encoder() [1/2]
ArrayColumn<Double>& casacore::MSPointingColumns::encoder () inline
Definition at line 280 of file MSPointingColumns.h.
References encoder_p.
encoder() [2/2]
const ROArrayColumn<Double>& casacore::MSPointingColumns::encoder () const inline
Definition at line 333 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::encoder().
encoderMeas() [1/2]
ScalarMeasColumn<MDirection>& casacore::MSPointingColumns::encoderMeas () inline
Definition at line 281 of file MSPointingColumns.h.
References encoderMeas_p.
encoderMeas() [2/2]
const ROScalarMeasColumn<MDirection>& casacore::MSPointingColumns::encoderMeas () const inline
Definition at line 335 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::encoderMeas().
interval() [1/2]
ScalarColumn<Double>& casacore::MSPointingColumns::interval () inline
Definition at line 253 of file MSPointingColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSPointingColumns::interval () const inline
Definition at line 297 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSPointingColumns::intervalQuant () inline
Definition at line 254 of file MSPointingColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSPointingColumns::intervalQuant () const inline
Definition at line 299 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::intervalQuant().
name() [1/2]
ScalarColumn<String>& casacore::MSPointingColumns::name () inline
Definition at line 255 of file MSPointingColumns.h.
References name_p.
name() [2/2]
const ROScalarColumn<String>& casacore::MSPointingColumns::name () const inline
Definition at line 301 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::name().
numPoly() [1/2]
ScalarColumn<Int>& casacore::MSPointingColumns::numPoly () inline
Definition at line 256 of file MSPointingColumns.h.
References numPoly_p.
numPoly() [2/2]
const ROScalarColumn<Int>& casacore::MSPointingColumns::numPoly () const inline
Definition at line 303 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::numPoly().
onSource() [1/2]
ScalarColumn<Bool>& casacore::MSPointingColumns::onSource () inline
Definition at line 283 of file MSPointingColumns.h.
References onSource_p.
onSource() [2/2]
const ROScalarColumn<Bool>& casacore::MSPointingColumns::onSource () const inline
Definition at line 339 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::onSource().
operator=()
MSPointingColumns& casacore::MSPointingColumns::operator= (const MSPointingColumns &) private
overTheTop() [1/2]
ScalarColumn<Bool>& casacore::MSPointingColumns::overTheTop () inline
Definition at line 284 of file MSPointingColumns.h.
References overTheTop_p.
overTheTop() [2/2]
const ROScalarColumn<Bool>& casacore::MSPointingColumns::overTheTop () const inline
Definition at line 341 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::overTheTop().
pointingModelId() [1/2]
ScalarColumn<Int>& casacore::MSPointingColumns::pointingModelId () inline
Definition at line 282 of file MSPointingColumns.h.
References pointingModelId_p.
pointingModelId() [2/2]
const ROScalarColumn<Int>& casacore::MSPointingColumns::pointingModelId () const inline
Definition at line 337 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::pointingModelId().
pointingOffset() [1/2]
ArrayColumn<Double>& casacore::MSPointingColumns::pointingOffset () inline
Read-write access to optional columns.
Note that the direction measures with a stored polynomial have Col() added to their name. They are better accessed via the functions that have the same name, without the Col suffix, that will do the interpolation for you. These functions are in the ROMSPointingColumns class.
Definition at line 274 of file MSPointingColumns.h.
References pointingOffset_p.
pointingOffset() [2/2]
const ROArrayColumn<Double>& casacore::MSPointingColumns::pointingOffset () const inline
Access to optional columns.
Definition at line 325 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::pointingOffset().
pointingOffsetMeasCol() [1/2]
ArrayMeasColumn<MDirection>& casacore::MSPointingColumns::pointingOffsetMeasCol () inline
Definition at line 275 of file MSPointingColumns.h.
References pointingOffsetMeas_p.
pointingOffsetMeasCol() [2/2]
const ROArrayMeasColumn<MDirection>& casacore::MSPointingColumns::pointingOffsetMeasCol () const inline
Definition at line 327 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::pointingOffsetMeasCol().
setDirectionRef()
void casacore::MSPointingColumns::setDirectionRef (MDirection::Types ref)
set the direction reference type for the DIRECTION, TARGET & and, if defined, the SOURCE_OFFSET & POINTING_OFFSET columns.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception. Note that the optional ENCODER column must be done separately as the MSv2 definition requires this column to use the frame(s) of the antenna mounts.
setEncoderDirectionRef()
void casacore::MSPointingColumns::setEncoderDirectionRef (MDirection::Types ref)
set the direction reference type for the ENCODER column (if it is defined).
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
setEpochRef()
void casacore::MSPointingColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch reference type for the TIME & TIME_ORIGIN column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
sourceOffset() [1/2]
ArrayColumn<Double>& casacore::MSPointingColumns::sourceOffset () inline
Definition at line 277 of file MSPointingColumns.h.
References sourceOffset_p.
sourceOffset() [2/2]
const ROArrayColumn<Double>& casacore::MSPointingColumns::sourceOffset () const inline
Definition at line 329 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::sourceOffset().
sourceOffsetMeasCol() [1/2]
ArrayMeasColumn<MDirection>& casacore::MSPointingColumns::sourceOffsetMeasCol () inline
Definition at line 278 of file MSPointingColumns.h.
References sourceOffsetMeas_p.
sourceOffsetMeasCol() [2/2]
const ROArrayMeasColumn<MDirection>& casacore::MSPointingColumns::sourceOffsetMeasCol () const inline
Definition at line 331 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::sourceOffsetMeasCol().
target() [1/2]
ArrayColumn<Double>& casacore::MSPointingColumns::target () inline
Definition at line 262 of file MSPointingColumns.h.
References target_p.
target() [2/2]
const ROArrayColumn<Double>& casacore::MSPointingColumns::target () const inline
Definition at line 315 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::target().
targetMeasCol() [1/2]
ArrayMeasColumn<MDirection>& casacore::MSPointingColumns::targetMeasCol () inline
Definition at line 263 of file MSPointingColumns.h.
References targetMeas_p.
targetMeasCol() [2/2]
const ROArrayMeasColumn<MDirection>& casacore::MSPointingColumns::targetMeasCol () const inline
Definition at line 317 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::targetMeasCol().
time() [1/2]
ScalarColumn<Double>& casacore::MSPointingColumns::time () inline
Definition at line 250 of file MSPointingColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSPointingColumns::time () const inline
Definition at line 291 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSPointingColumns::timeMeas () inline
Definition at line 251 of file MSPointingColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSPointingColumns::timeMeas () const inline
Definition at line 295 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::timeMeas().
timeOrigin() [1/2]
ScalarColumn<Double>& casacore::MSPointingColumns::timeOrigin () inline
Definition at line 257 of file MSPointingColumns.h.
References timeOrigin_p.
timeOrigin() [2/2]
const ROScalarColumn<Double>& casacore::MSPointingColumns::timeOrigin () const inline
Definition at line 305 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::timeOrigin().
timeOriginMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSPointingColumns::timeOriginMeas () inline
Definition at line 259 of file MSPointingColumns.h.
References timeOriginMeas_p.
timeOriginMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSPointingColumns::timeOriginMeas () const inline
Definition at line 309 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::timeOriginMeas().
timeOriginQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSPointingColumns::timeOriginQuant () inline
Definition at line 258 of file MSPointingColumns.h.
References timeOriginQuant_p.
timeOriginQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSPointingColumns::timeOriginQuant () const inline
Definition at line 307 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::timeOriginQuant().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSPointingColumns::timeQuant () inline
Definition at line 252 of file MSPointingColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSPointingColumns::timeQuant () const inline
Definition at line 293 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::timeQuant().
tracking() [1/2]
ScalarColumn<Bool>& casacore::MSPointingColumns::tracking () inline
Definition at line 264 of file MSPointingColumns.h.
References tracking_p.
tracking() [2/2]
const ROScalarColumn<Bool>& casacore::MSPointingColumns::tracking () const inline
Definition at line 319 of file MSPointingColumns.h.
References casacore::ROMSPointingColumns::tracking().
Member Data Documentation
antennaId_p
ScalarColumn<Int> casacore::MSPointingColumns::antennaId_p private
Definition at line 387 of file MSPointingColumns.h.
Referenced by antennaId().
direction_p
ArrayColumn<Double> casacore::MSPointingColumns::direction_p private
Definition at line 388 of file MSPointingColumns.h.
Referenced by direction().
directionMeas_p
ArrayMeasColumn<MDirection> casacore::MSPointingColumns::directionMeas_p private
Definition at line 405 of file MSPointingColumns.h.
Referenced by directionMeasCol().
encoder_p
ArrayColumn<Double> casacore::MSPointingColumns::encoder_p private
Definition at line 397 of file MSPointingColumns.h.
Referenced by encoder().
encoderMeas_p
ScalarMeasColumn<MDirection> casacore::MSPointingColumns::encoderMeas_p private
Definition at line 410 of file MSPointingColumns.h.
Referenced by encoderMeas().
interval_p
ScalarColumn<Double> casacore::MSPointingColumns::interval_p private
Definition at line 389 of file MSPointingColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSPointingColumns::intervalQuant_p private
Definition at line 415 of file MSPointingColumns.h.
Referenced by intervalQuant().
name_p
ScalarColumn<String> casacore::MSPointingColumns::name_p private
Definition at line 390 of file MSPointingColumns.h.
Referenced by name().
numPoly_p
ScalarColumn<Int> casacore::MSPointingColumns::numPoly_p private
Definition at line 391 of file MSPointingColumns.h.
Referenced by numPoly().
onSource_p
ScalarColumn<Bool> casacore::MSPointingColumns::onSource_p private
Definition at line 398 of file MSPointingColumns.h.
Referenced by onSource().
overTheTop_p
ScalarColumn<Bool> casacore::MSPointingColumns::overTheTop_p private
Definition at line 402 of file MSPointingColumns.h.
Referenced by overTheTop().
pointingModelId_p
ScalarColumn<Int> casacore::MSPointingColumns::pointingModelId_p private
Definition at line 399 of file MSPointingColumns.h.
Referenced by pointingModelId().
pointingOffset_p
ArrayColumn<Double> casacore::MSPointingColumns::pointingOffset_p private
Definition at line 400 of file MSPointingColumns.h.
Referenced by pointingOffset().
pointingOffsetMeas_p
ArrayMeasColumn<MDirection> casacore::MSPointingColumns::pointingOffsetMeas_p private
Definition at line 411 of file MSPointingColumns.h.
Referenced by pointingOffsetMeasCol().
sourceOffset_p
ArrayColumn<Double> casacore::MSPointingColumns::sourceOffset_p private
Definition at line 401 of file MSPointingColumns.h.
Referenced by sourceOffset().
sourceOffsetMeas_p
ArrayMeasColumn<MDirection> casacore::MSPointingColumns::sourceOffsetMeas_p private
Definition at line 412 of file MSPointingColumns.h.
Referenced by sourceOffsetMeasCol().
target_p
ArrayColumn<Double> casacore::MSPointingColumns::target_p private
Definition at line 392 of file MSPointingColumns.h.
Referenced by target().
targetMeas_p
ArrayMeasColumn<MDirection> casacore::MSPointingColumns::targetMeas_p private
Definition at line 406 of file MSPointingColumns.h.
Referenced by targetMeasCol().
time_p
ScalarColumn<Double> casacore::MSPointingColumns::time_p private
Definition at line 393 of file MSPointingColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSPointingColumns::timeMeas_p private
Definition at line 407 of file MSPointingColumns.h.
Referenced by timeMeas().
timeOrigin_p
ScalarColumn<Double> casacore::MSPointingColumns::timeOrigin_p private
Definition at line 394 of file MSPointingColumns.h.
Referenced by timeOrigin().
timeOriginMeas_p
ScalarMeasColumn<MEpoch> casacore::MSPointingColumns::timeOriginMeas_p private
Definition at line 408 of file MSPointingColumns.h.
Referenced by timeOriginMeas().
timeOriginQuant_p
ScalarQuantColumn<Double> casacore::MSPointingColumns::timeOriginQuant_p private
Definition at line 417 of file MSPointingColumns.h.
Referenced by timeOriginQuant().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSPointingColumns::timeQuant_p private
Definition at line 416 of file MSPointingColumns.h.
Referenced by timeQuant().
tracking_p
ScalarColumn<Bool> casacore::MSPointingColumns::tracking_p private
Definition at line 395 of file MSPointingColumns.h.
Referenced by tracking().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSPointingColumns.h