casacore: casacore::TableExprNodeRep Class Reference
casacore::TableExprNodeRep Class Reference
tables package (libcasa_tables) » TaQL_module » TaQL_module_internal_classes
Abstract base class for a node in a table column expression tree.
#include <ExprNodeRep.h>
Public Types
enum NodeDataType {
NTBool,
NTInt,
NTDouble,
NTComplex,
NTString,
NTRegex,
NTDate,
NTReal,
NTDouCom,
NTNumeric,
NTAny
}
Define the data types of a node.
enum ValueType {
VTScalar,
VTArray,
VTRecord,
VTSetElem,
VTSet,
VTIndex
}
Define the value types.
enum OperType {
OtPlus,
OtMinus,
OtTimes,
OtDivide,
OtModulo,
OtBitAnd,
OtBitOr,
OtBitXor,
OtBitNegate,
OtEQ,
OtGE,
OtGT,
OtNE,
OtIN,
OtAND,
OtOR,
OtNOT,
OtMIN,
OtColumn,
OtField,
OtLiteral,
OtFunc,
OtSlice,
OtUndef,
OtRownr,
OtRandom
}
Define the operator types.
enum ArgType {
NoArr,
ArrArr,
ArrSca,
ScaArr
}
Define the value types of the 2 arguments when arrays are involved.
enum ExprType {
Constant,
Variable
}
Define (sub-)expression type.
Public Member Functions
TableExprNodeRep (NodeDataType, ValueType, OperType, ArgType, ExprType, Int ndim, const IPosition &shape, const Table &table)
Construct a node.
TableExprNodeRep (NodeDataType, ValueType, OperType, const Table &)
This constructor is called from the derived TableExprNodeRep.
TableExprNodeRep (const TableExprNodeRep &)
Copy constructor.
virtual ~TableExprNodeRep ()
The destructor deletes all the underlying TableExprNode objects.
virtual void disableApplySelection ()
Do not apply the selection.
virtual void applySelection (const Vector< uInt > &rownrs)
Re-create the column object for a selection of rows.
virtual Double getUnitFactor () const
Get the unit conversion factor.
void checkAggrFuncs ()
Throw an exception if an aggregate function is used in the expression node or its children.
virtual void getAggrNodes (std::vector< TableExprNodeRep * > &aggr)
Get the nodes representing an aggregate function.
virtual void getColumnNodes (std::vector< TableExprNodeRep * > &cols)
Get the nodes representing a table column.
virtual CountedPtr< TableExprGroupFuncBase > makeGroupAggrFunc ()
Create the correct immediate aggregate function object.
virtual Bool isLazyAggregate () const
Is the aggregate function a lazy or an immediate one? The default implementation returns True (because all UDF aggregate functions have to be lazy).
virtual Bool getBool (const TableExprId &id)
Get a scalar value for this node in the given row.
virtual Int64 getInt (const TableExprId &id)
virtual Double getDouble (const TableExprId &id)
virtual DComplex getDComplex (const TableExprId &id)
virtual String getString (const TableExprId &id)
virtual TaqlRegex getRegex (const TableExprId &id)
virtual MVTime getDate (const TableExprId &id)
virtual MArray< Bool > getArrayBool (const TableExprId &id)
Get an array value for this node in the given row.
virtual MArray< Int64 > getArrayInt (const TableExprId &id)
virtual MArray< Double > getArrayDouble (const TableExprId &id)
virtual MArray< DComplex > getArrayDComplex (const TableExprId &id)
virtual MArray< String > getArrayString (const TableExprId &id)
virtual MArray< MVTime > getArrayDate (const TableExprId &id)
void get (const TableExprId &id, Bool &value)
General get functions for template purposes.
void get (const TableExprId &id, Int64 &value)
void get (const TableExprId &id, Double &value)
void get (const TableExprId &id, DComplex &value)
void get (const TableExprId &id, MVTime &value)
void get (const TableExprId &id, String &value)
void get (const TableExprId &id, MArray< Bool > &value)
void get (const TableExprId &id, MArray< Int64 > &value)
void get (const TableExprId &id, MArray< Double > &value)
void get (const TableExprId &id, MArray< DComplex > &value)
void get (const TableExprId &id, MArray< MVTime > &value)
void get (const TableExprId &id, MArray< String > &value)
MArray< Bool > getBoolAS (const TableExprId &id)
Get a value as an array, even it it is a scalar.
MArray< Int64 > getIntAS (const TableExprId &id)
MArray< Double > getDoubleAS (const TableExprId &id)
MArray< DComplex > getDComplexAS (const TableExprId &id)
MArray< String > getStringAS (const TableExprId &id)
MArray< MVTime > getDateAS (const TableExprId &id)
virtual Bool hasBool (const TableExprId &id, Bool value)
Does a value occur in an array or set? The default implementation tests if it is in an array.
virtual Bool hasInt (const TableExprId &id, Int64 value)
virtual Bool hasDouble (const TableExprId &id, Double value)
virtual Bool hasDComplex (const TableExprId &id, const DComplex &value)
virtual Bool hasString (const TableExprId &id, const String &value)
virtual Bool hasDate (const TableExprId &id, const MVTime &value)
virtual MArray< Bool > hasArrayBool (const TableExprId &id, const MArray< Bool > &value)
virtual MArray< Bool > hasArrayInt (const TableExprId &id, const MArray< Int64 > &value)
virtual MArray< Bool > hasArrayDouble (const TableExprId &id, const MArray< Double > &value)
virtual MArray< Bool > hasArrayDComplex (const TableExprId &id, const MArray< DComplex > &value)
virtual MArray< Bool > hasArrayString (const TableExprId &id, const MArray< String > &value)
virtual MArray< Bool > hasArrayDate (const TableExprId &id, const MArray< MVTime > &value)
uInt nrow () const
Get the number of rows in the table associated with this expression.
virtual Bool getColumnDataType (DataType &) const
Get the data type of the column.
virtual Array< Bool > getColumnBool (const Vector< uInt > &rownrs)
Get the value of the expression evaluated for the entire column.
virtual Array< uChar > getColumnuChar (const Vector< uInt > &rownrs)
virtual Array< Short > getColumnShort (const Vector< uInt > &rownrs)
virtual Array< uShort > getColumnuShort (const Vector< uInt > &rownrs)
virtual Array< Int > getColumnInt (const Vector< uInt > &rownrs)
virtual Array< uInt > getColumnuInt (const Vector< uInt > &rownrs)
virtual Array< Int64 > getColumnInt64 (const Vector< uInt > &rownrs)
virtual Array< Float > getColumnFloat (const Vector< uInt > &rownrs)
virtual Array< Double > getColumnDouble (const Vector< uInt > &rownrs)
virtual Array< Complex > getColumnComplex (const Vector< uInt > &rownrs)
virtual Array< DComplex > getColumnDComplex (const Vector< uInt > &rownrs)
virtual Array< String > getColumnString (const Vector< uInt > &rownrs)
virtual void ranges (Block< TableExprRange > &)
Convert the tree to a number of range vectors which at least select the same things.
NodeDataType dataType () const
Get the data type of the derived TableExprNode object.
Bool isReal () const
Is the data type real (i.e., integer or double)?
ValueType valueType () const
Get the value type.
void setValueType (ValueType vtype)
Set the value type.
OperType operType () const
Get the operator type.
ExprType exprType () const
Get the expression type.
Bool isConstant () const
Is the expression a constant?
const Unit & unit () const
Get the unit.
void setUnit (const Unit &unit)
Set the unit.
const Record & attributes () const
Get the attributes.
void setAttributes (const Record &)
Set the attributes.
Int ndim () const
Get the fixed dimensionality (same for all rows).
const IPosition & shape () const
Get the fixed shape (same for all rows).
const IPosition & shape (const TableExprId &id)
Get the shape for the given row.
virtual Bool isDefined (const TableExprId &id)
Is the value in the given row defined? The default implementation returns True.
virtual void show (ostream &, uInt indent) const
Show the expression tree.
Table & table ()
Get table.
const Table & table () const
virtual void adaptSetUnits (const Unit &)
Let a set node convert itself to the given unit.
Static Public Member Functions
static TENShPtr replaceConstNode (const TENShPtr &node)
Replace a node with a constant expression by node with its value.
static void createRange (Block< TableExprRange > &, TableExprNodeColumn *, Double start, Double end)
Create a range object from a column and an interval.
static void createRange (Block< TableExprRange > &)
Create a empty range object.
static String typeString (NodeDataType)
Convert a NodeDataType to a string.
static String typeString (ValueType)
Convert a ValueType to a string.
Protected Member Functions
virtual const IPosition & getShape (const TableExprId &id)
Get the shape for the given row.
virtual void convertConstChild ()
If one of the children is a constant, convert its data type to that of the other operand (if appropriate).
void checkTablePtr (const TENShPtr &node)
Check if this node uses the same table pointer.
void fillExprType (const TENShPtr &node)
Set expression type to Variable if node is Variable.
Static Protected Member Functions
static void checkTablePtr (Table &table, const TENShPtr &node)
static void fillExprType (ExprType &, const TENShPtr &node)
static TENShPtr convertNode (const TENShPtr &thisNode, Bool convertConstType)
If the node is constant, it is evaluated and replaced by the appropriate TableExprNodeConst object.
Protected Attributes
Table table_p
NodeDataType dtype_p
ValueType vtype_p
OperType optype_p
ArgType argtype_p
ExprType exprtype_p
Int ndim_p
IPosition shape_p
Unit unit_p
Record attributes_p
Private Member Functions
TableExprNodeRep & operator= (const TableExprNodeRep &)
A copy of a TableExprNodeRep cannot be made.
Detailed Description
Abstract base class for a node in a table column expression tree.
Intended use:
Internal
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Prerequisite
TableExprNode
Etymology
TableExprNodeRep is the (abstract) REPresentation of a node in a table expression tree.
Synopsis
TableExprNodeRep is the base class for all nodes in a table expression tree. It is used by the handle class TableExprNode.
The objects of this class are reference-counted to make it possible that the same object is reused.
Motivation
TableExprNodeRep and its derivations store a table select expression before actually evaluating it. It is also possible that the classes are used by the table expression parser defined in TableParse and TableGram.
For each operator a special derived class is implemented. Another approach could have been to store the operator as a flag and switch on that. However, that causes extra overhead and the C++ virtual function mechanism is designed for these purposes.
To Do
add selection by comparing with a set of values
Definition at line 157 of file ExprNodeRep.h.
Member Enumeration Documentation
ArgType
enum casacore::TableExprNodeRep::ArgType
Define the value types of the 2 arguments when arrays are involved.
Enumerator
NoArr
ArrArr
ArrSca
ScaArr
Definition at line 196 of file ExprNodeRep.h.
ExprType
enum casacore::TableExprNodeRep::ExprType
Define (sub-)expression type.
Enumerator
Constant
A constant subexpression which can be evaluated immediately.
Variable
A variable (i.e.
row dependent) subexpression which has to be evaluated for each table row. An expensive constant subexpression which should only be evaluated when needed (e.g. a subquery). Lazy
Definition at line 201 of file ExprNodeRep.h.
NodeDataType
enum casacore::TableExprNodeRep::NodeDataType
Define the data types of a node.
Enumerator
NTBool
NTInt
NTDouble
NTComplex
NTString
NTRegex
NTDate
NTReal
NTDouCom
NTNumeric
NTAny
Definition at line 161 of file ExprNodeRep.h.
OperType
enum casacore::TableExprNodeRep::OperType
Define the operator types.
LE and LT are handled as GE and GT with swapped operands.
Enumerator
OtPlus
OtMinus
OtTimes
OtDivide
OtModulo
OtBitAnd
OtBitOr
OtBitXor
OtBitNegate
OtEQ
OtGE
OtGT
OtNE
OtIN
OtAND
OtOR
OtNOT
OtMIN
OtColumn
OtField
OtLiteral
OtFunc
OtSlice
OtUndef
OtRownr
OtRandom
Definition at line 187 of file ExprNodeRep.h.
ValueType
enum casacore::TableExprNodeRep::ValueType
Define the value types.
Enumerator
VTScalar
VTArray
VTRecord
VTSetElem
VTSet
VTIndex
Definition at line 176 of file ExprNodeRep.h.
Constructor & Destructor Documentation
TableExprNodeRep() [1/3]
casacore::TableExprNodeRep::TableExprNodeRep (NodeDataType , ValueType , OperType , ArgType , ExprType , Int ndim, const IPosition & shape, const Table & table)
Construct a node.
TableExprNodeRep() [2/3]
casacore::TableExprNodeRep::TableExprNodeRep (NodeDataType , ValueType , OperType , const Table &)
This constructor is called from the derived TableExprNodeRep.
TableExprNodeRep() [3/3]
casacore::TableExprNodeRep::TableExprNodeRep (const TableExprNodeRep &)
Copy constructor.
~TableExprNodeRep()
virtual casacore::TableExprNodeRep::~TableExprNodeRep () virtual
The destructor deletes all the underlying TableExprNode objects.
Member Function Documentation
adaptSetUnits()
virtual void casacore::TableExprNodeRep::adaptSetUnits (const Unit &) virtual
Let a set node convert itself to the given unit.
The default implementation does nothing.
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeSetElem.
applySelection()
virtual void casacore::TableExprNodeRep::applySelection (const Vector< uInt > & rownrs) virtual
Re-create the column object for a selection of rows.
The default implementation does nothing.
Reimplemented in casacore::TableExprNodeArrayColumnString, casacore::TableExprNodeArrayColumnDComplex, casacore::TableExprNodeArrayColumnComplex, casacore::TableExprNodeArrayColumnDouble, casacore::TableExprNodeArrayColumnFloat, casacore::TableExprNodeArrayColumnInt64, casacore::TableExprNodeArrayColumnuInt, casacore::TableExprNodeArrayColumnInt, casacore::TableExprNodeRowid, casacore::TableExprNodeArrayColumnuShort, casacore::TableExprNodeArrayColumnShort, casacore::TableExprNodeArrayColumnuChar, casacore::TableExprNodeColumn, casacore::TableExprNodeArrayColumnBool, casacore::TableExprNodeArrayColumn, casacore::TableExprUDFNode, and casacore::TableExprUDFNodeArray.
Referenced by casacore::TableExprNode::applySelection().
attributes()
const Record & casacore::TableExprNodeRep::attributes () const inline
Get the attributes.
Definition at line 734 of file ExprNodeRep.h.
References attributes_p.
Referenced by casacore::TableExprNode::attributes(), and setAttributes().
checkAggrFuncs()
void casacore::TableExprNodeRep::checkAggrFuncs ()
Throw an exception if an aggregate function is used in the expression node or its children.
checkTablePtr() [1/2]
void casacore::TableExprNodeRep::checkTablePtr (const TENShPtr & node) inline protected
Check if this node uses the same table pointer.
Fill the Table object if it is still null.
Definition at line 754 of file ExprNodeRep.h.
References table_p.
checkTablePtr() [2/2]
static void casacore::TableExprNodeRep::checkTablePtr (Table & table, const TENShPtr & node) static protected
convertConstChild()
virtual void casacore::TableExprNodeRep::convertConstChild () protected virtual
If one of the children is a constant, convert its data type to that of the other operand (if appropriate).
This avoids that conversions are done for each get. The default implementation does nothing.
Reimplemented in casacore::TableExprNodeINInt.
convertNode()
static TENShPtr casacore::TableExprNodeRep::convertNode (const TENShPtr & thisNode, Bool convertConstType) static protected
If the node is constant, it is evaluated and replaced by the appropriate TableExprNodeConst object.
If not constant, it calls the virtual ConvertConstChild function which can convert a constant child if appropriate.
createRange() [1/2]
static void casacore::TableExprNodeRep::createRange (Block< TableExprRange > & , TableExprNodeColumn * , Double start, Double end) static
Create a range object from a column and an interval.
createRange() [2/2]
static void casacore::TableExprNodeRep::createRange (Block< TableExprRange > &) static
Create a empty range object.
dataType()
TableExprNodeRep::NodeDataType casacore::TableExprNodeRep::dataType () const inline
Get the data type of the derived TableExprNode object.
This is the data type of the resulting value. E.g. a compare of 2 numeric values results in a Bool, thus the data type of, say, TableExprNodeEQ<T> is always Bool. Function getInternalDT gives the internal data type, thus in the example above the data type of T.
Definition at line 704 of file ExprNodeRep.h.
References dtype_p.
disableApplySelection()
virtual void casacore::TableExprNodeRep::disableApplySelection () virtual
Do not apply the selection.
Reimplemented in casacore::TableExprNodeColumn, casacore::TableExprNodeArrayColumn, casacore::TableExprUDFNode, and casacore::TableExprUDFNodeArray.
Referenced by casacore::TableExprNode::disableApplySelection().
exprType()
TableExprNodeRep::ExprType casacore::TableExprNodeRep::exprType () const inline
Get the expression type.
Definition at line 723 of file ExprNodeRep.h.
References exprtype_p.
fillExprType() [1/2]
void casacore::TableExprNodeRep::fillExprType (const TENShPtr & node) inline protected
Set expression type to Variable if node is Variable.
Definition at line 756 of file ExprNodeRep.h.
References exprtype_p.
fillExprType() [2/2]
static void casacore::TableExprNodeRep::fillExprType (ExprType & , const TENShPtr & node) static protected
get() [1/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, Bool & value) inline
General get functions for template purposes.
Definition at line 286 of file ExprNodeRep.h.
References getBool(), and casacore::value().
Referenced by casacore::TableExprGroupAggr::getArray().
get() [2/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, Int64 & value) inline
Definition at line 288 of file ExprNodeRep.h.
References getInt(), and casacore::value().
get() [3/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, Double & value) inline
Definition at line 290 of file ExprNodeRep.h.
References getDouble(), and casacore::value().
get() [4/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, DComplex & value) inline
Definition at line 292 of file ExprNodeRep.h.
References getDComplex(), and casacore::value().
get() [5/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, MVTime & value) inline
Definition at line 294 of file ExprNodeRep.h.
References getDate(), and casacore::value().
get() [6/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, String & value) inline
Definition at line 296 of file ExprNodeRep.h.
References getString(), and casacore::value().
get() [7/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, MArray< Bool > & value) inline
Definition at line 298 of file ExprNodeRep.h.
References getArrayBool(), and casacore::value().
get() [8/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, MArray< Int64 > & value) inline
Definition at line 300 of file ExprNodeRep.h.
References getArrayInt(), and casacore::value().
get() [9/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, MArray< Double > & value) inline
Definition at line 302 of file ExprNodeRep.h.
References getArrayDouble(), and casacore::value().
get() [10/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, MArray< DComplex > & value) inline
Definition at line 304 of file ExprNodeRep.h.
References getArrayDComplex(), and casacore::value().
get() [11/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, MArray< MVTime > & value) inline
Definition at line 306 of file ExprNodeRep.h.
References getArrayDate(), and casacore::value().
get() [12/12]
void casacore::TableExprNodeRep::get (const TableExprId & id, MArray< String > & value) inline
Definition at line 308 of file ExprNodeRep.h.
References getArrayString(), and casacore::value().
getAggrNodes()
virtual void casacore::TableExprNodeRep::getAggrNodes (std::vector< TableExprNodeRep * > & aggr) virtual
Get the nodes representing an aggregate function.
Reimplemented in casacore::TableExprNodeMulti, casacore::TableExprNodeBinary, casacore::TableExprNodeSet, casacore::TableExprNodeSetElem, casacore::TableExprAggrNode, casacore::TableExprUDFNode, casacore::TableExprUDFNodeArray, casacore::TableExprFuncNodeArray, and casacore::TableExprAggrNodeArray.
getArrayBool()
virtual MArray<Bool> casacore::TableExprNodeRep::getArrayBool (const TableExprId & id) virtual
Get an array value for this node in the given row.
The appropriate functions are implemented in the derived classes and will usually invoke the get in their children and apply the operator on the resulting values.
Reimplemented in casacore::TableExprNodeArrayNOT, casacore::TableExprNodeArrayAND, casacore::TableExprNodeArrayOR, casacore::TableExprNodeArrayINDate, casacore::TableExprNodeArrayINString, casacore::TableExprNodeArrayINDComplex, casacore::TableExprNodeArrayPart, casacore::TableExprNodeArrayINDouble, casacore::TableExprNodeArrayINInt, casacore::TableExprNodeArrayGEDate, casacore::TableExprNodeArrayGEString, casacore::TableExprNodeArrayGEDComplex, casacore::TableExprNodeArrayGEDouble, casacore::TableExprNodeArrayGEInt, casacore::TableExprNodeArrayGTDate, casacore::TableExprNodeArrayGTString, casacore::TableExprNodeArrayGTDComplex, casacore::TableExprNodeArrayGTDouble, casacore::TableExprNodeArrayGTInt, casacore::TableExprNodeArrayNEDate, casacore::TableExprNodeArrayNERegex, casacore::TableExprNodeArrayNEString, casacore::TableExprNodeSet, casacore::TableExprNodeArrayNEDComplex, casacore::TableExprNodeArrayNEDouble, casacore::TableExprNodeArrayNEInt, casacore::TableExprNodeArrayNEBool, casacore::TableExprNodeArrayColumnBool, casacore::TableExprNodeArrayEQDate, casacore::TableExprNodeArrayEQRegex, casacore::TableExprNodeArrayEQString, casacore::TableExprNodeArrayEQDComplex, casacore::TableExprNodeArrayEQDouble, casacore::TableExprNodeRecordFieldArray, casacore::TableExprConeNodeArray, casacore::TableExprNodeArrayEQInt, casacore::TableExprUDFNodeArray, casacore::TableExprFuncNodeArray, casacore::TableExprAggrNodeArray, casacore::TableExprNodeArrayEQBool, and casacore::TableExprNodeArrayConstBool.
Referenced by get(), casacore::TableExprNode::get(), casacore::TableExprNodeSet::getArray(), and casacore::TableExprNode::getArrayBool().
getArrayDate()
virtual MArray<MVTime> casacore::TableExprNodeRep::getArrayDate (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeSet, casacore::TableExprNodeArrayMinusDate, casacore::TableExprNodeArrayConstDate, casacore::TableExprNodeArrayPlusDate, casacore::TableExprUDFNodeArray, casacore::TableExprFuncNodeArray, and casacore::TableExprAggrNodeArray.
Referenced by get(), casacore::TableExprNode::get(), casacore::TableExprNodeSet::getArray(), and casacore::TableExprNode::getArrayDate().
getArrayDComplex()
virtual MArray<DComplex> casacore::TableExprNodeRep::getArrayDComplex (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeArrayMIN, casacore::TableExprNodeArrayColumnDComplex, casacore::TableExprNodeArrayColumnComplex, casacore::TableExprNodeArrayDivideDComplex, casacore::TableExprNodeArrayTimesDComplex, casacore::TableExprNodeSet, casacore::TableExprNodeArrayMinusDComplex, casacore::TableExprNodeArrayConstDComplex, casacore::TableExprNodeArrayPlusDComplex, casacore::TableExprNodeArrayConstDouble, casacore::TableExprNodeRecordFieldArray, casacore::TableExprNodeArrayUnit, casacore::TableExprNodeArrayConstInt, casacore::TableExprUDFNodeArray, casacore::TableExprNodeArray, casacore::TableExprFuncNodeArray, and casacore::TableExprAggrNodeArray.
Referenced by get(), casacore::TableExprNode::get(), casacore::TableExprNodeSet::getArray(), and casacore::TableExprNode::getArrayDComplex().
getArrayDouble()
virtual MArray<Double> casacore::TableExprNodeRep::getArrayDouble (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeArrayMIN, casacore::TableExprNodeArrayModuloDouble, casacore::TableExprNodeArrayColumnDouble, casacore::TableExprNodeArrayDivideDouble, casacore::TableExprNodeArrayColumnFloat, casacore::TableExprNodeArrayTimesDouble, casacore::TableExprNodeSet, casacore::TableExprNodeArrayMinusDate, casacore::TableExprNodeArrayMinusDouble, casacore::TableExprNodeArrayConstDate, casacore::TableExprNodeArrayPlusDate, casacore::TableExprNodeArrayConstDouble, casacore::TableExprNodeArrayPlusDouble, casacore::TableExprNodeRecordFieldArray, casacore::TableExprNodeArrayUnit, casacore::TableExprNodeArrayConstInt, casacore::TableExprUDFNodeArray, casacore::TableExprFuncNodeArray, casacore::TableExprNodeArray, and casacore::TableExprAggrNodeArray.
Referenced by get(), casacore::TableExprNode::get(), casacore::TableExprNodeSet::getArray(), and casacore::TableExprNode::getArrayDouble().
getArrayInt()
virtual MArray<Int64> casacore::TableExprNodeRep::getArrayInt (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeArrayBitNegate, casacore::TableExprNodeArrayMIN, casacore::TableExprNodeArrayBitXorInt, casacore::TableExprNodeArrayBitOrInt, casacore::TableExprNodeArrayBitAndInt, casacore::TableExprNodeArrayModuloInt, casacore::TableExprNodeArrayColumnInt64, casacore::TableExprNodeArrayColumnuInt, casacore::TableExprNodeArrayTimesInt, casacore::TableExprNodeArrayColumnInt, casacore::TableExprNodeArrayColumnuShort, casacore::TableExprNodeSet, casacore::TableExprNodeArrayColumnShort, casacore::TableExprNodeArrayColumnuChar, casacore::TableExprNodeArrayMinusInt, casacore::TableExprNodeRecordFieldArray, casacore::TableExprConeNodeArray, casacore::TableExprNodeArrayConstInt, casacore::TableExprNodeArrayPlusInt, casacore::TableExprUDFNodeArray, casacore::TableExprFuncNodeArray, and casacore::TableExprAggrNodeArray.
Referenced by get(), casacore::TableExprNode::get(), casacore::TableExprNodeSet::getArray(), and casacore::TableExprNode::getArrayInt().
getArrayString()
virtual MArray<String> casacore::TableExprNodeRep::getArrayString (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeArrayColumnString, casacore::TableExprNodeSet, casacore::TableExprNodeArrayConstString, casacore::TableExprNodeArrayPlusString, casacore::TableExprNodeRecordFieldArray, casacore::TableExprUDFNodeArray, casacore::TableExprFuncNodeArray, and casacore::TableExprAggrNodeArray.
Referenced by get(), casacore::TableExprNode::get(), casacore::TableExprNodeSet::getArray(), and casacore::TableExprNode::getArrayString().
getBool()
virtual Bool casacore::TableExprNodeRep::getBool (const TableExprId & id) virtual
Get a scalar value for this node in the given row.
The appropriate functions are implemented in the derived classes and will usually invoke the get in their children and apply the operator on the resulting values.
Reimplemented in casacore::TableExprNodeNOT, casacore::TableExprNodeAND, casacore::TableExprNodeOR, casacore::TableExprNodeINDate, casacore::TableExprNodeINString, casacore::TableExprNodeINDComplex, casacore::TableExprNodeINDouble, casacore::TableExprNodeArrayPart, casacore::TableExprNodeINInt, casacore::TableExprNodeGEDate, casacore::TableExprNodeGEString, casacore::TableExprNodeGEDComplex, casacore::TableExprNodeGEDouble, casacore::TableExprNodeGEInt, casacore::TableExprNodeGTDate, casacore::TableExprNodeGTString, casacore::TableExprNodeGTDComplex, casacore::TableExprNodeGTDouble, casacore::TableExprNodeGTInt, casacore::TableExprNodeNEDate, casacore::TableExprNodeNERegex, casacore::TableExprNodeNEString, casacore::TableExprNodeNEDComplex, casacore::TableExprFuncNode, casacore::TableExprNodeNEDouble, casacore::TableExprNodeColumn, casacore::TableExprNodeNEInt, casacore::TableExprNodeNEBool, casacore::TableExprNodeEQDate, casacore::TableExprNodeEQRegex, casacore::TableExprNodeEQString, casacore::TableExprNodeEQDComplex, casacore::TableExprNodeEQDouble, casacore::TableExprAggrNode, casacore::TableExprUDFNode, casacore::TableExprNodeEQInt, casacore::TableExprNodeRecordField, casacore::TableExprConeNode, casacore::TableExprNodeConstBool, and casacore::TableExprNodeEQBool.
Referenced by get(), casacore::TableExprNode::get(), and casacore::TableExprNode::getBool().
getBoolAS()
MArray<Bool> casacore::TableExprNodeRep::getBoolAS (const TableExprId & id)
Get a value as an array, even it it is a scalar.
This is useful if one could give an argument as scalar or array.
Referenced by casacore::TableExprNode::getBoolAS().
getColumnBool()
virtual Array<Bool> casacore::TableExprNodeRep::getColumnBool (const Vector< uInt > & rownrs) virtual
Get the value of the expression evaluated for the entire column.
The data of function called should match the data type as returned by function getColumnDataType.
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnBool().
getColumnComplex()
virtual Array<Complex> casacore::TableExprNodeRep::getColumnComplex (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnComplex().
getColumnDataType()
virtual Bool casacore::TableExprNodeRep::getColumnDataType (DataType &) const virtual
Get the data type of the column.
It returns True when it could set the data type (which it can if the expression is a scalar column or a constant array column pixel). Otherwise it returns False.
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeColumn, and casacore::TableExprNodeArrayColumn.
getColumnDComplex()
virtual Array<DComplex> casacore::TableExprNodeRep::getColumnDComplex (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnDComplex().
getColumnDouble()
virtual Array<Double> casacore::TableExprNodeRep::getColumnDouble (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnDouble().
getColumnFloat()
virtual Array<Float> casacore::TableExprNodeRep::getColumnFloat (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnFloat().
getColumnInt()
virtual Array<Int> casacore::TableExprNodeRep::getColumnInt (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnInt().
getColumnInt64()
virtual Array<Int64> casacore::TableExprNodeRep::getColumnInt64 (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnInt64().
getColumnNodes()
virtual void casacore::TableExprNodeRep::getColumnNodes (std::vector< TableExprNodeRep * > & cols) virtual
Get the nodes representing a table column.
Reimplemented in casacore::TableExprNodeMulti, casacore::TableExprNodeBinary, casacore::TableExprNodeSet, casacore::TableExprNodeColumn, casacore::TableExprNodeArrayColumn, casacore::TableExprNodeSetElem, casacore::TableExprUDFNode, casacore::TableExprUDFNodeArray, and casacore::TableExprFuncNodeArray.
getColumnShort()
virtual Array<Short> casacore::TableExprNodeRep::getColumnShort (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnShort().
getColumnString()
virtual Array<String> casacore::TableExprNodeRep::getColumnString (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnString().
getColumnuChar()
virtual Array<uChar> casacore::TableExprNodeRep::getColumnuChar (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnuChar().
getColumnuInt()
virtual Array<uInt> casacore::TableExprNodeRep::getColumnuInt (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnuInt().
getColumnuShort()
virtual Array<uShort> casacore::TableExprNodeRep::getColumnuShort (const Vector< uInt > & rownrs) virtual
Reimplemented in casacore::TableExprNodeArrayPart, and casacore::TableExprNodeColumn.
Referenced by casacore::TableExprNode::getColumnuShort().
getDate()
virtual MVTime casacore::TableExprNodeRep::getDate (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeMinusDate, casacore::TableExprFuncNode, casacore::TableExprNodeConstDate, casacore::TableExprNodePlusDate, casacore::TableExprAggrNode, and casacore::TableExprUDFNode.
Referenced by get(), casacore::TableExprNode::get(), and casacore::TableExprNode::getDate().
getDateAS()
MArray<MVTime> casacore::TableExprNodeRep::getDateAS (const TableExprId & id)
Referenced by casacore::TableExprNode::getDateAS().
getDComplex()
virtual DComplex casacore::TableExprNodeRep::getDComplex (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeBitNegate, casacore::TableExprNodeArrayPart, casacore::TableExprNodeMIN, casacore::TableExprNodeBitXorInt, casacore::TableExprNodeBitOrInt, casacore::TableExprNodeBitAndInt, casacore::TableExprNodeModuloDouble, casacore::TableExprNodeModuloInt, casacore::TableExprNodeDivideDComplex, casacore::TableExprNodeDivideDouble, casacore::TableExprNodeTimesDComplex, casacore::TableExprNodeTimesDouble, casacore::TableExprNodeTimesInt, casacore::TableExprFuncNode, casacore::TableExprNodeMinusDComplex, casacore::TableExprNodeMinusDouble, casacore::TableExprNodeColumn, casacore::TableExprNodeMinusInt, casacore::TableExprNodeConstDComplex, casacore::TableExprNodePlusDComplex, casacore::TableExprNodeConstDouble, casacore::TableExprNodePlusDouble, casacore::TableExprAggrNode, casacore::TableExprNodeConstInt, casacore::TableExprUDFNode, casacore::TableExprNodePlusInt, casacore::TableExprNodeUnit, and casacore::TableExprNodeRecordField.
Referenced by get(), casacore::TableExprNode::get(), and casacore::TableExprNode::getDComplex().
getDComplexAS()
MArray<DComplex> casacore::TableExprNodeRep::getDComplexAS (const TableExprId & id)
Referenced by casacore::TableExprNode::getDComplexAS().
getDouble()
virtual Double casacore::TableExprNodeRep::getDouble (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeBitNegate, casacore::TableExprNodeArrayPart, casacore::TableExprNodeMIN, casacore::TableExprNodeBitXorInt, casacore::TableExprNodeBitOrInt, casacore::TableExprNodeBitAndInt, casacore::TableExprNodeModuloDouble, casacore::TableExprNodeModuloInt, casacore::TableExprNodeDivideDouble, casacore::TableExprNodeTimesDouble, casacore::TableExprNodeTimesInt, casacore::TableExprNodeRandom, casacore::TableExprNodeMinusDate, casacore::TableExprFuncNode, casacore::TableExprNodeMinusDouble, casacore::TableExprNodeColumn, casacore::TableExprNodeMinusInt, casacore::TableExprNodeConstDate, casacore::TableExprNodePlusDate, casacore::TableExprNodeConstDouble, casacore::TableExprNodePlusDouble, casacore::TableExprAggrNode, casacore::TableExprNodeConstInt, casacore::TableExprUDFNode, casacore::TableExprNodePlusInt, casacore::TableExprNodeUnit, and casacore::TableExprNodeRecordField.
Referenced by get(), casacore::TableExprNode::get(), and casacore::TableExprNode::getDouble().
getDoubleAS()
MArray<Double> casacore::TableExprNodeRep::getDoubleAS (const TableExprId & id)
Referenced by casacore::TableExprNode::getDoubleAS().
getInt()
virtual Int64 casacore::TableExprNodeRep::getInt (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeBitNegate, casacore::TableExprNodeArrayPart, casacore::TableExprNodeMIN, casacore::TableExprNodeBitXorInt, casacore::TableExprNodeBitOrInt, casacore::TableExprNodeBitAndInt, casacore::TableExprNodeModuloInt, casacore::TableExprNodeTimesInt, casacore::TableExprNodeRowid, casacore::TableExprNodeRownr, casacore::TableExprFuncNode, casacore::TableExprNodeColumn, casacore::TableExprNodeMinusInt, casacore::TableExprAggrNode, casacore::TableExprNodeConstInt, casacore::TableExprUDFNode, casacore::TableExprNodePlusInt, casacore::TableExprNodeRecordField, and casacore::TableExprConeNode.
Referenced by get(), casacore::TableExprNode::get(), and casacore::TableExprNode::getInt().
getIntAS()
MArray<Int64> casacore::TableExprNodeRep::getIntAS (const TableExprId & id)
Referenced by casacore::TableExprNode::getIntAS().
getRegex()
virtual TaqlRegex casacore::TableExprNodeRep::getRegex (const TableExprId & id) virtual
Reimplemented in casacore::TableExprFuncNode, casacore::TableExprNodeConstRegex, and casacore::TableExprUDFNode.
Referenced by casacore::TableExprNode::get().
getShape()
virtual const IPosition& casacore::TableExprNodeRep::getShape (const TableExprId & id) protected virtual
Get the shape for the given row.
Reimplemented in casacore::TableExprNodeArrayColumn, casacore::TableExprNodeRecordFieldArray, casacore::TableExprNodeArray, and casacore::TableExprNodeRecordField.
getString()
virtual String casacore::TableExprNodeRep::getString (const TableExprId & id) virtual
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprFuncNode, casacore::TableExprNodeColumn, casacore::TableExprNodeConstString, casacore::TableExprNodePlusString, casacore::TableExprAggrNode, casacore::TableExprUDFNode, and casacore::TableExprNodeRecordField.
Referenced by get(), casacore::TableExprNode::get(), and casacore::TableExprNode::getString().
getStringAS()
MArray<String> casacore::TableExprNodeRep::getStringAS (const TableExprId & id)
Referenced by casacore::TableExprNode::getStringAS().
getUnitFactor()
virtual Double casacore::TableExprNodeRep::getUnitFactor () const virtual
Get the unit conversion factor.
Default 1 is returned.
Reimplemented in casacore::TableExprNodeArrayUnit, and casacore::TableExprNodeUnit.
hasArrayBool()
virtual MArray<Bool> casacore::TableExprNodeRep::hasArrayBool (const TableExprId & id, const MArray< Bool > & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasArrayDate()
virtual MArray<Bool> casacore::TableExprNodeRep::hasArrayDate (const TableExprId & id, const MArray< MVTime > & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasArrayDComplex()
virtual MArray<Bool> casacore::TableExprNodeRep::hasArrayDComplex (const TableExprId & id, const MArray< DComplex > & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasArrayDouble()
virtual MArray<Bool> casacore::TableExprNodeRep::hasArrayDouble (const TableExprId & id, const MArray< Double > & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasArrayInt()
virtual MArray<Bool> casacore::TableExprNodeRep::hasArrayInt (const TableExprId & id, const MArray< Int64 > & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasArrayString()
virtual MArray<Bool> casacore::TableExprNodeRep::hasArrayString (const TableExprId & id, const MArray< String > & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasBool()
virtual Bool casacore::TableExprNodeRep::hasBool (const TableExprId & id, Bool value) virtual
Does a value occur in an array or set? The default implementation tests if it is in an array.
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasDate()
virtual Bool casacore::TableExprNodeRep::hasDate (const TableExprId & id, const MVTime & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasDComplex()
virtual Bool casacore::TableExprNodeRep::hasDComplex (const TableExprId & id, const DComplex & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasDouble()
virtual Bool casacore::TableExprNodeRep::hasDouble (const TableExprId & id, Double value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasInt()
virtual Bool casacore::TableExprNodeRep::hasInt (const TableExprId & id, Int64 value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
hasString()
virtual Bool casacore::TableExprNodeRep::hasString (const TableExprId & id, const String & value) virtual
Reimplemented in casacore::TableExprNodeSet, and casacore::TableExprNodeArray.
isConstant()
Bool casacore::TableExprNodeRep::isConstant () const inline
Is the expression a constant?
Definition at line 727 of file ExprNodeRep.h.
References Constant, and exprtype_p.
Referenced by casacore::TableExprNodeIndex::getSlicer().
isDefined()
virtual Bool casacore::TableExprNodeRep::isDefined (const TableExprId & id) virtual
Is the value in the given row defined? The default implementation returns True.
Reimplemented in casacore::TableExprNodeArrayColumn, casacore::TableExprNodeRecordFieldArray, and casacore::TableExprNodeRecordField.
isLazyAggregate()
virtual Bool casacore::TableExprNodeRep::isLazyAggregate () const virtual
Is the aggregate function a lazy or an immediate one? The default implementation returns True (because all UDF aggregate functions have to be lazy).
Reimplemented in casacore::TableExprAggrNode, and casacore::TableExprAggrNodeArray.
isReal()
Bool casacore::TableExprNodeRep::isReal () const inline
Is the data type real (i.e., integer or double)?
Definition at line 707 of file ExprNodeRep.h.
References dtype_p, NTDouble, and NTInt.
makeGroupAggrFunc()
virtual CountedPtr<TableExprGroupFuncBase> casacore::TableExprNodeRep::makeGroupAggrFunc () virtual
Create the correct immediate aggregate function object.
The default implementation throws an exception, because it should only be called for TableExprAggrNode(Array).
Reimplemented in casacore::TableExprAggrNode, casacore::TableExprUDFNode, casacore::TableExprUDFNodeArray, and casacore::TableExprAggrNodeArray.
ndim()
Int casacore::TableExprNodeRep::ndim () const inline
Get the fixed dimensionality (same for all rows).
Definition at line 741 of file ExprNodeRep.h.
References ndim_p.
nrow()
uInt casacore::TableExprNodeRep::nrow () const
Get the number of rows in the table associated with this expression.
One is returned if the expression is a constant. Zero is returned if no table is associated with it.
Referenced by casacore::TableExprNode::nrow().
operator=()
TableExprNodeRep& casacore::TableExprNodeRep::operator= (const TableExprNodeRep &) private
A copy of a TableExprNodeRep cannot be made.
operType()
TableExprNodeRep::OperType casacore::TableExprNodeRep::operType () const inline
Get the operator type.
Definition at line 719 of file ExprNodeRep.h.
References optype_p.
ranges()
virtual void casacore::TableExprNodeRep::ranges (Block< TableExprRange > &) virtual
Convert the tree to a number of range vectors which at least select the same things.
This function is very useful to convert the expression to some intervals covering the select expression. This can be used to do a rough fast selection via an index and do the the slower final selection on that much smaller subset. The function can only convert direct comparisons of columns with constants (via ==, !=, >, >=, < or <=) and their combinations using && or ||.
Reimplemented in casacore::TableExprNodeAND, casacore::TableExprNodeOR, casacore::TableExprNodeGEDouble, casacore::TableExprNodeGTDouble, and casacore::TableExprNodeEQDouble.
Referenced by casacore::TableExprNode::ranges().
replaceConstNode()
static TENShPtr casacore::TableExprNodeRep::replaceConstNode (const TENShPtr & node) static
Replace a node with a constant expression by node with its value.
setAttributes()
void casacore::TableExprNodeRep::setAttributes (const Record & attributes) inline
Set the attributes.
Definition at line 737 of file ExprNodeRep.h.
References attributes(), and attributes_p.
setUnit()
void casacore::TableExprNodeRep::setUnit (const Unit & unit)
Set the unit.
It also sets the datatype to NTDouble if it is NTInt.
setValueType()
void casacore::TableExprNodeRep::setValueType (TableExprNodeRep::ValueType vtype) inline
Set the value type.
Definition at line 715 of file ExprNodeRep.h.
References vtype_p.
shape() [1/2]
const IPosition & casacore::TableExprNodeRep::shape () const inline
Get the fixed shape (same for all rows).
Definition at line 745 of file ExprNodeRep.h.
References shape_p.
shape() [2/2]
const IPosition& casacore::TableExprNodeRep::shape (const TableExprId & id)
Get the shape for the given row.
It returns the fixed shape if defined, otherwise getShape(id).
show()
virtual void casacore::TableExprNodeRep::show (ostream & , uInt indent) const virtual
Show the expression tree.
Reimplemented in casacore::TableExprNodeArrayPart, casacore::TableExprNodeMulti, casacore::TableExprNodeBinary, casacore::TableExprNodeSet, and casacore::TableExprNodeSetElem.
Referenced by casacore::TableExprNode::show().
table() [1/2]
Table & casacore::TableExprNodeRep::table () inline
Get table.
This gets the Table object to which a TableExprNode belongs. A TableExprNode belongs to the Table to which the first column used in an expression belongs.
Definition at line 749 of file ExprNodeRep.h.
References table_p.
Referenced by casacore::TableExprNode::table().
table() [2/2]
const Table & casacore::TableExprNodeRep::table () const inline
Definition at line 751 of file ExprNodeRep.h.
References table_p.
typeString() [1/2]
static String casacore::TableExprNodeRep::typeString (NodeDataType) static
Convert a NodeDataType to a string.
typeString() [2/2]
static String casacore::TableExprNodeRep::typeString (ValueType) static
Convert a ValueType to a string.
unit()
const Unit & casacore::TableExprNodeRep::unit () const inline
Get the unit.
Definition at line 731 of file ExprNodeRep.h.
References unit_p.
Referenced by casacore::TableExprNode::unit().
valueType()
TableExprNodeRep::ValueType casacore::TableExprNodeRep::valueType () const inline
Get the value type.
Definition at line 711 of file ExprNodeRep.h.
References vtype_p.
Referenced by casacore::TableExprGroupAggr::getArray(), and casacore::TableExprNode::isScalar().
Member Data Documentation
argtype_p
ArgType casacore::TableExprNodeRep::argtype_p protected
Definition at line 475 of file ExprNodeRep.h.
attributes_p
Record casacore::TableExprNodeRep::attributes_p protected
Definition at line 481 of file ExprNodeRep.h.
Referenced by attributes(), and setAttributes().
dtype_p
NodeDataType casacore::TableExprNodeRep::dtype_p protected
Definition at line 472 of file ExprNodeRep.h.
Referenced by dataType(), and isReal().
exprtype_p
ExprType casacore::TableExprNodeRep::exprtype_p protected
Definition at line 476 of file ExprNodeRep.h.
Referenced by exprType(), fillExprType(), and isConstant().
ndim_p
Int casacore::TableExprNodeRep::ndim_p protected
Definition at line 477 of file ExprNodeRep.h.
Referenced by ndim().
optype_p
OperType casacore::TableExprNodeRep::optype_p protected
Definition at line 474 of file ExprNodeRep.h.
Referenced by operType().
shape_p
IPosition casacore::TableExprNodeRep::shape_p protected
Definition at line 479 of file ExprNodeRep.h.
Referenced by shape().
table_p
Table casacore::TableExprNodeRep::table_p protected
Definition at line 471 of file ExprNodeRep.h.
Referenced by checkTablePtr(), and table().
unit_p
Unit casacore::TableExprNodeRep::unit_p protected
Definition at line 480 of file ExprNodeRep.h.
Referenced by unit().
vtype_p
ValueType casacore::TableExprNodeRep::vtype_p protected
Definition at line 473 of file ExprNodeRep.h.
Referenced by setValueType(), and valueType().
The documentation for this class was generated from the following file:
tables/TaQL/ExprNodeRep.h