casacore: casacore::ConcatRows Class Reference
casacore::ConcatRows Class Reference
tables package (libcasa_tables) » Tables_module » Tables_module_internal_classes
Class holding the row numbers in a ConcatTable.
#include <ConcatRows.h>
Public Member Functions
ConcatRows ()
Construct an empty block.
void reserve (uInt ntable)
Reserve the block for the given nr of tables.
void add (uInt nrow)
Add a table with the given nr of rows.
uInt ntable () const
Give the nr of tables.
uInt nrow () const
Get the total nr of rows.
uInt operator[] (uInt i) const
Give the nr of rows for the i-th table.
uInt offset (uInt i) const
Give the offset for the i-th table.
void mapRownr (uInt &tableNr, uInt &tabRownr, uInt rownr) const
Map an overall row number to a table and row number.
Private Member Functions
void findRownr (uInt rownr) const
Find the row number and fill in the lastXX_p values.
Private Attributes
Block< uInt > itsRows
uInt itsNTable
uInt itsLastStRow
uInt itsLastEndRow
uInt itsLastTableNr
Detailed Description
Class holding the row numbers in a ConcatTable.
Intended use:
Internal
Review Status
Reviewed By:
UNKNOWN
Test programs:
tConcatRows
Prerequisite
Block
Synopsis
ConcatRows is used to hold the row numbers forming the concatenation of oher tables. table. It contains a vector which can hold the row numbers in 2 ways:
As a normal series of row numbers. This is used by e.g. class ConcatTable
As a series of Slices. In this case 3 subsequent entries in the vector are used to represent start, end, and increment. This is used by a function like ScalarColumn::getColumnRange.
Class ConcatRowsIter can be used to iterate through a ConcatRows object. Each step in the iteration goes to the next slice. If the ConcatRows object contains a simple series of row numbers, each slice contains only one row number. This can degrade performance, so it is possible to use shortcuts by testing if the object contains slices (using isSliced()) and getting the row number vector directly (using rowVector()).
Motivation
ConcatRows is meant to have one class representing the various ways of picking row numbers. This simplifies the interface of the table and data manager classes dealing with getting/putting the data.
Definition at line 83 of file ConcatRows.h.
Constructor & Destructor Documentation
ConcatRows()
casacore::ConcatRows::ConcatRows () inline
Construct an empty block.
Definition at line 87 of file ConcatRows.h.
Member Function Documentation
add()
void casacore::ConcatRows::add (uInt nrow)
Add a table with the given nr of rows.
findRownr()
void casacore::ConcatRows::findRownr (uInt rownr) const private
Find the row number and fill in the lastXX_p values.
Referenced by mapRownr().
mapRownr()
void casacore::ConcatRows::mapRownr (uInt & tableNr, uInt & tabRownr, uInt rownr) const inline
Map an overall row number to a table and row number.
Definition at line 118 of file ConcatRows.h.
References findRownr(), itsLastEndRow, itsLastStRow, and itsLastTableNr.
nrow()
uInt casacore::ConcatRows::nrow () const inline
Get the total nr of rows.
Definition at line 106 of file ConcatRows.h.
References itsNTable, and itsRows.
ntable()
uInt casacore::ConcatRows::ntable () const inline
Give the nr of tables.
Definition at line 102 of file ConcatRows.h.
References itsNTable.
Referenced by reserve().
offset()
uInt casacore::ConcatRows::offset (uInt i) const inline
Give the offset for the i-th table.
Definition at line 114 of file ConcatRows.h.
References itsRows.
operator[]()
uInt casacore::ConcatRows::operator[] (uInt i) const inline
Give the nr of rows for the i-th table.
Definition at line 110 of file ConcatRows.h.
References itsRows.
reserve()
void casacore::ConcatRows::reserve (uInt ntable) inline
Reserve the block for the given nr of tables.
Definition at line 95 of file ConcatRows.h.
References itsRows, ntable(), and casacore::Block< T >::resize().
Member Data Documentation
itsLastEndRow
uInt casacore::ConcatRows::itsLastEndRow mutable private
Definition at line 135 of file ConcatRows.h.
Referenced by mapRownr().
itsLastStRow
uInt casacore::ConcatRows::itsLastStRow mutable private
Definition at line 134 of file ConcatRows.h.
Referenced by mapRownr().
itsLastTableNr
uInt casacore::ConcatRows::itsLastTableNr mutable private
Definition at line 136 of file ConcatRows.h.
Referenced by mapRownr().
itsNTable
uInt casacore::ConcatRows::itsNTable private
Definition at line 133 of file ConcatRows.h.
Referenced by nrow(), and ntable().
itsRows
Block<uInt> casacore::ConcatRows::itsRows private
Definition at line 132 of file ConcatRows.h.
Referenced by nrow(), offset(), operator[](), and reserve().
The documentation for this class was generated from the following file:
tables/Tables/ConcatRows.h