casacore: casacore::ROMSAntennaColumns Class Reference
casacore::ROMSAntennaColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSAntenna columns.
#include <MSAntennaColumns.h>
Public Member Functions
ROMSAntennaColumns (const MSAntenna &msAntenna)
Create a columns object that accesses the data in the specified Table.
~ROMSAntennaColumns ()
The destructor does nothing special.
const ROScalarColumn< Double > & dishDiameter () const
Access to columns.
const ROScalarQuantColumn< Double > & dishDiameterQuant () const
const ROScalarColumn< Bool > & flagRow () const
const ROScalarColumn< String > & mount () const
const ROScalarColumn< String > & name () const
const ROArrayColumn< Double > & offset () const
const ROArrayQuantColumn< Double > & offsetQuant () const
const ROScalarMeasColumn< MPosition > & offsetMeas () const
const ROArrayColumn< Double > & position () const
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROScalarColumn< String > & station () const
const ROScalarColumn< String > & type () const
const ROArrayColumn< Double > & meanOrbit () const
Access to optional columns.
const ROScalarColumn< Int > & orbitId () const
const ROScalarColumn< Int > & phasedArrayId () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Int matchAntenna (const MPosition &antennaPos, const Quantum< Double > &tolerance, Int tryRow=-1)
returns the last row that contains an antenna at the specified position, to within the specified tolerance.
Int matchAntenna (const String &antName, const MPosition &antennaPos, const Quantum< Double > &tolerance, Int tryRow=-1)
Same as the previous function except that the antenna name must also match.
Int matchAntennaAndStation (const String &antName, const String &stationName, const MPosition &antennaPos, const Quantum< Double > &tolerance, Int tryRow=-1)
Same as the previous function except that the station name must also match.
Protected Member Functions
ROMSAntennaColumns ()
void attach (const MSAntenna &msAntenna)
Private Member Functions
ROMSAntennaColumns (const ROMSAntennaColumns &)
ROMSAntennaColumns & operator= (const ROMSAntennaColumns &)
void attachOptionalCols (const MSAntenna &msAntenna)
Bool matchName (uInt row, const String &antName) const
Bool matchStation (uInt row, const String &stationName) const
Bool matchPosition (uInt row, const Vector< Double > &antPosInM, const Double tolInM) const
Private Attributes
ROScalarColumn< Double > dishDiameter_p
ROScalarColumn< Bool > flagRow_p
ROScalarColumn< String > mount_p
ROScalarColumn< String > name_p
ROArrayColumn< Double > offset_p
ROArrayColumn< Double > position_p
ROScalarColumn< String > station_p
ROScalarColumn< String > type_p
ROArrayColumn< Double > meanOrbit_p
ROScalarColumn< Int > orbitId_p
ROScalarColumn< Int > phasedArrayId_p
ROScalarMeasColumn< MPosition > offsetMeas_p
ROScalarMeasColumn< MPosition > positionMeas_p
ROScalarQuantColumn< Double > dishDiameterQuant_p
ROArrayQuantColumn< Double > offsetQuant_p
ROArrayQuantColumn< Double > positionQuant_p
Detailed Description
A class to provide easy read-only access to MSAntenna columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSAntenna
ArrayColumn
ScalarColumn
Etymology
ROMSAntennaColumns stands for Read-Only MeasurementSet Antenna Table columns.
Synopsis
This class provides read-only access to the columns in the MSAntenna Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 78 of file MSAntennaColumns.h.
Constructor & Destructor Documentation
ROMSAntennaColumns() [1/3]
casacore::ROMSAntennaColumns::ROMSAntennaColumns (const MSAntenna & msAntenna)
Create a columns object that accesses the data in the specified Table.
~ROMSAntennaColumns()
casacore::ROMSAntennaColumns::~ROMSAntennaColumns ()
The destructor does nothing special.
ROMSAntennaColumns() [2/3]
casacore::ROMSAntennaColumns::ROMSAntennaColumns () protected
ROMSAntennaColumns() [3/3]
casacore::ROMSAntennaColumns::ROMSAntennaColumns (const ROMSAntennaColumns &) private
Member Function Documentation
attach()
void casacore::ROMSAntennaColumns::attach (const MSAntenna & msAntenna) protected
attachOptionalCols()
void casacore::ROMSAntennaColumns::attachOptionalCols (const MSAntenna & msAntenna) private
dishDiameter()
const ROScalarColumn<Double>& casacore::ROMSAntennaColumns::dishDiameter () const inline
Access to columns.
Definition at line 90 of file MSAntennaColumns.h.
References dishDiameter_p.
Referenced by casacore::MSAntennaColumns::dishDiameter().
dishDiameterQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSAntennaColumns::dishDiameterQuant () const inline
Definition at line 91 of file MSAntennaColumns.h.
References dishDiameterQuant_p.
Referenced by casacore::MSAntennaColumns::dishDiameterQuant().
flagRow()
const ROScalarColumn<Bool>& casacore::ROMSAntennaColumns::flagRow () const inline
Definition at line 93 of file MSAntennaColumns.h.
References flagRow_p.
Referenced by casacore::MSAntennaColumns::flagRow().
matchAntenna() [1/2]
Int casacore::ROMSAntennaColumns::matchAntenna (const MPosition & antennaPos, const Quantum< Double > & tolerance, Int tryRow = -1)
returns the last row that contains an antenna at the specified position, to within the specified tolerance.
The reference frame of the supplied position must be the same as the one for the POSITION columns. If not an AipsError is thrown as such an argument will never match any row of the Table. The tolerance is the maximum allowed distance between the two positions and the supplied Quantum must have dimensions of length. This is checked when compiled in debug mode and an AipsError exception is thrown if the dimensions are wrong. Returns -1 if no match could be found. Flaged rows can never match. If tryRow is non-negative, then that row is tested to see if it matches before any others are tested. Setting tryRow to a positive value greater than the table length will throw an exception (AipsError), when compiled in debug mode.
matchAntenna() [2/2]
Int casacore::ROMSAntennaColumns::matchAntenna (const String & antName, const MPosition & antennaPos, const Quantum< Double > & tolerance, Int tryRow = -1)
Same as the previous function except that the antenna name must also match.
matchAntennaAndStation()
Int casacore::ROMSAntennaColumns::matchAntennaAndStation (const String & antName, const String & stationName, const MPosition & antennaPos, const Quantum< Double > & tolerance, Int tryRow = -1)
Same as the previous function except that the station name must also match.
matchName()
Bool casacore::ROMSAntennaColumns::matchName (uInt row, const String & antName) const private
matchPosition()
Bool casacore::ROMSAntennaColumns::matchPosition (uInt row, const Vector< Double > & antPosInM, const Double tolInM) const private
matchStation()
Bool casacore::ROMSAntennaColumns::matchStation (uInt row, const String & stationName) const private
meanOrbit()
const ROArrayColumn<Double>& casacore::ROMSAntennaColumns::meanOrbit () const inline
Access to optional columns.
Definition at line 111 of file MSAntennaColumns.h.
References meanOrbit_p.
Referenced by casacore::MSAntennaColumns::meanOrbit().
mount()
const ROScalarColumn<String>& casacore::ROMSAntennaColumns::mount () const inline
Definition at line 94 of file MSAntennaColumns.h.
References mount_p.
Referenced by casacore::MSAntennaColumns::mount().
name()
const ROScalarColumn<String>& casacore::ROMSAntennaColumns::name () const inline
Definition at line 95 of file MSAntennaColumns.h.
References name_p.
Referenced by casacore::MSAntennaColumns::name().
nrow()
uInt casacore::ROMSAntennaColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Definition at line 117 of file MSAntennaColumns.h.
References dishDiameter_p.
offset()
const ROArrayColumn<Double>& casacore::ROMSAntennaColumns::offset () const inline
Definition at line 96 of file MSAntennaColumns.h.
References offset_p.
Referenced by casacore::MSAntennaColumns::offset().
offsetMeas()
const ROScalarMeasColumn<MPosition>& casacore::ROMSAntennaColumns::offsetMeas () const inline
Definition at line 98 of file MSAntennaColumns.h.
References offsetMeas_p.
Referenced by casacore::MSAntennaColumns::offsetMeas().
offsetQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSAntennaColumns::offsetQuant () const inline
Definition at line 97 of file MSAntennaColumns.h.
References offsetQuant_p.
Referenced by casacore::MSAntennaColumns::offsetQuant().
operator=()
ROMSAntennaColumns& casacore::ROMSAntennaColumns::operator= (const ROMSAntennaColumns &) private
orbitId()
const ROScalarColumn<Int>& casacore::ROMSAntennaColumns::orbitId () const inline
Definition at line 112 of file MSAntennaColumns.h.
References orbitId_p.
Referenced by casacore::MSAntennaColumns::orbitId().
phasedArrayId()
const ROScalarColumn<Int>& casacore::ROMSAntennaColumns::phasedArrayId () const inline
Definition at line 113 of file MSAntennaColumns.h.
References phasedArrayId_p.
Referenced by casacore::MSAntennaColumns::phasedArrayId().
position()
const ROArrayColumn<Double>& casacore::ROMSAntennaColumns::position () const inline
Definition at line 100 of file MSAntennaColumns.h.
References position_p.
Referenced by casacore::MSAntennaColumns::position().
positionMeas()
const ROScalarMeasColumn<MPosition>& casacore::ROMSAntennaColumns::positionMeas () const inline
Definition at line 103 of file MSAntennaColumns.h.
References positionMeas_p.
Referenced by casacore::MSAntennaColumns::positionMeas().
positionQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSAntennaColumns::positionQuant () const inline
Definition at line 101 of file MSAntennaColumns.h.
References positionQuant_p.
Referenced by casacore::MSAntennaColumns::positionQuant().
station()
const ROScalarColumn<String>& casacore::ROMSAntennaColumns::station () const inline
Definition at line 105 of file MSAntennaColumns.h.
References station_p.
Referenced by casacore::MSAntennaColumns::station().
type()
const ROScalarColumn<String>& casacore::ROMSAntennaColumns::type () const inline
Definition at line 106 of file MSAntennaColumns.h.
References type_p.
Referenced by casacore::MSAntennaColumns::type().
Member Data Documentation
dishDiameter_p
ROScalarColumn<Double> casacore::ROMSAntennaColumns::dishDiameter_p private
Definition at line 171 of file MSAntennaColumns.h.
Referenced by dishDiameter(), and nrow().
dishDiameterQuant_p
ROScalarQuantColumn<Double> casacore::ROMSAntennaColumns::dishDiameterQuant_p private
Definition at line 189 of file MSAntennaColumns.h.
Referenced by dishDiameterQuant().
flagRow_p
ROScalarColumn<Bool> casacore::ROMSAntennaColumns::flagRow_p private
Definition at line 172 of file MSAntennaColumns.h.
Referenced by flagRow().
meanOrbit_p
ROArrayColumn<Double> casacore::ROMSAntennaColumns::meanOrbit_p private
Definition at line 180 of file MSAntennaColumns.h.
Referenced by meanOrbit().
mount_p
ROScalarColumn<String> casacore::ROMSAntennaColumns::mount_p private
Definition at line 173 of file MSAntennaColumns.h.
Referenced by mount().
name_p
ROScalarColumn<String> casacore::ROMSAntennaColumns::name_p private
Definition at line 174 of file MSAntennaColumns.h.
Referenced by name().
offset_p
ROArrayColumn<Double> casacore::ROMSAntennaColumns::offset_p private
Definition at line 175 of file MSAntennaColumns.h.
Referenced by offset().
offsetMeas_p
ROScalarMeasColumn<MPosition> casacore::ROMSAntennaColumns::offsetMeas_p private
Definition at line 185 of file MSAntennaColumns.h.
Referenced by offsetMeas().
offsetQuant_p
ROArrayQuantColumn<Double> casacore::ROMSAntennaColumns::offsetQuant_p private
Definition at line 190 of file MSAntennaColumns.h.
Referenced by offsetQuant().
orbitId_p
ROScalarColumn<Int> casacore::ROMSAntennaColumns::orbitId_p private
Definition at line 181 of file MSAntennaColumns.h.
Referenced by orbitId().
phasedArrayId_p
ROScalarColumn<Int> casacore::ROMSAntennaColumns::phasedArrayId_p private
Definition at line 182 of file MSAntennaColumns.h.
Referenced by phasedArrayId().
position_p
ROArrayColumn<Double> casacore::ROMSAntennaColumns::position_p private
Definition at line 176 of file MSAntennaColumns.h.
Referenced by position().
positionMeas_p
ROScalarMeasColumn<MPosition> casacore::ROMSAntennaColumns::positionMeas_p private
Definition at line 186 of file MSAntennaColumns.h.
Referenced by positionMeas().
positionQuant_p
ROArrayQuantColumn<Double> casacore::ROMSAntennaColumns::positionQuant_p private
Definition at line 191 of file MSAntennaColumns.h.
Referenced by positionQuant().
station_p
ROScalarColumn<String> casacore::ROMSAntennaColumns::station_p private
Definition at line 177 of file MSAntennaColumns.h.
Referenced by station().
type_p
ROScalarColumn<String> casacore::ROMSAntennaColumns::type_p private
Definition at line 178 of file MSAntennaColumns.h.
Referenced by type().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSAntennaColumns.h