casacore: casacore::MSSourceColumns Class Reference
casacore::MSSourceColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-write access to MSSource columns.
#include <MSSourceColumns.h>
Public Member Functions
MSSourceColumns (MSSource &msSource)
Construct from the supplied Table.
~MSSourceColumns ()
The destructor does nothing special.
ScalarColumn< Int > & calibrationGroup ()
Read-write access to required columns.
ScalarColumn< String > & code ()
ArrayColumn< Double > & direction ()
ArrayQuantColumn< Double > & directionQuant ()
ScalarMeasColumn< MDirection > & directionMeas ()
ScalarColumn< Double > & interval ()
ScalarQuantColumn< Double > & intervalQuant ()
ScalarColumn< String > & name ()
ScalarColumn< Int > & numLines ()
ArrayColumn< Double > & properMotion ()
ArrayQuantColumn< Double > & properMotionQuant ()
ScalarColumn< Int > & sourceId ()
ScalarColumn< Int > & spectralWindowId ()
ScalarColumn< Double > & time ()
ScalarQuantColumn< Double > & timeQuant ()
ScalarMeasColumn< MEpoch > & timeMeas ()
ArrayColumn< Double > & position ()
Read-write access to optional columns.
ArrayQuantColumn< Double > & positionQuant ()
ScalarMeasColumn< MPosition > & positionMeas ()
ScalarColumn< Int > & pulsarId ()
ArrayColumn< Double > & restFrequency ()
ArrayQuantColumn< Double > & restFrequencyQuant ()
ArrayMeasColumn< MFrequency > & restFrequencyMeas ()
ScalarColumn< TableRecord > & sourceModel ()
ArrayColumn< Double > & sysvel ()
ArrayQuantColumn< Double > & sysvelQuant ()
ArrayMeasColumn< MRadialVelocity > & sysvelMeas ()
ArrayColumn< String > & transition ()
const ROScalarColumn< Int > & calibrationGroup () const
Read-only access to required columns.
const ROScalarColumn< String > & code () const
const ROArrayColumn< Double > & direction () const
const ROArrayQuantColumn< Double > & directionQuant () const
const ROScalarMeasColumn< MDirection > & directionMeas () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & numLines () const
const ROArrayColumn< Double > & properMotion () const
const ROArrayQuantColumn< Double > & properMotionQuant () const
const ROScalarColumn< Int > & sourceId () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROArrayColumn< Double > & position () const
Read-only access to optional columns.
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROScalarColumn< Int > & pulsarId () const
const ROArrayColumn< Double > & restFrequency () const
const ROArrayQuantColumn< Double > & restFrequencyQuant () const
const ROArrayMeasColumn< MFrequency > & restFrequencyMeas () const
const ROScalarColumn< TableRecord > & sourceModel () const
const ROArrayColumn< Double > & sysvel () const
const ROArrayQuantColumn< Double > & sysvelQuant () const
const ROArrayMeasColumn< MRadialVelocity > & sysvelMeas () const
const ROArrayColumn< String > & transition () const
void setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty=True)
set the epoch type for the TIME column.
void setDirectionRef (MDirection::Types ref)
set the direction type for the DIRECTION column.
void setPositionRef (MPosition::Types ref)
set the position type for the POSITION column.
void setFrequencyRef (MFrequency::Types ref)
set the frequency type for the REST_FREQUENCY column.
void setRadialVelocityRef (MRadialVelocity::Types ref)
set the radial velocity type for the SYSVEL column.
Public Member Functions inherited from casacore::ROMSSourceColumns
ROMSSourceColumns (const MSSource &msSource)
Construct from the supplied Table.
~ROMSSourceColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSSource table is optional)
const ROScalarColumn< Int > & calibrationGroup () const
Access to required columns.
const ROScalarColumn< String > & code () const
const ROArrayColumn< Double > & direction () const
const ROArrayQuantColumn< Double > & directionQuant () const
const ROScalarMeasColumn< MDirection > & directionMeas () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & numLines () const
const ROArrayColumn< Double > & properMotion () const
const ROArrayQuantColumn< Double > & properMotionQuant () const
const ROScalarColumn< Int > & sourceId () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROArrayColumn< Double > & position () const
Access to optional columns.
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROScalarColumn< Int > & pulsarId () const
const ROArrayColumn< Double > & restFrequency () const
const ROArrayQuantColumn< Double > & restFrequencyQuant () const
const ROArrayMeasColumn< MFrequency > & restFrequencyMeas () const
const ROScalarColumn< TableRecord > & sourceModel () const
const ROArrayColumn< Double > & sysvel () const
const ROArrayQuantColumn< Double > & sysvelQuant () const
const ROArrayMeasColumn< MRadialVelocity > & sysvelMeas () const
const ROArrayColumn< String > & transition () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
MSSourceColumns ()
void attach (MSSource &msSource)
Protected Member Functions inherited from casacore::ROMSSourceColumns
ROMSSourceColumns ()
void attach (const MSSource &msSource)
Private Member Functions
MSSourceColumns (const MSSourceColumns &)
MSSourceColumns & operator= (const MSSourceColumns &)
void attachOptionalCols (MSSource &msSource)
Private Attributes
ScalarColumn< Int > calibrationGroup_p
ScalarColumn< String > code_p
ArrayColumn< Double > direction_p
ScalarColumn< Double > interval_p
ScalarColumn< String > name_p
ScalarColumn< Int > numLines_p
ArrayColumn< Double > properMotion_p
ScalarColumn< Int > sourceId_p
ScalarColumn< Int > spectralWindowId_p
ScalarColumn< Double > time_p
ArrayColumn< Double > position_p
ScalarColumn< Int > pulsarId_p
ArrayColumn< Double > restFrequency_p
ScalarColumn< TableRecord > sourceModel_p
ArrayColumn< Double > sysvel_p
ArrayColumn< String > transition_p
ScalarMeasColumn< MDirection > directionMeas_p
ScalarMeasColumn< MEpoch > timeMeas_p
ScalarMeasColumn< MPosition > positionMeas_p
ArrayMeasColumn< MFrequency > restFrequencyMeas_p
ArrayMeasColumn< MRadialVelocity > sysvelMeas_p
ArrayQuantColumn< Double > directionQuant_p
ScalarQuantColumn< Double > intervalQuant_p
ArrayQuantColumn< Double > properMotionQuant_p
ScalarQuantColumn< Double > timeQuant_p
ArrayQuantColumn< Double > positionQuant_p
ArrayQuantColumn< Double > restFrequencyQuant_p
ArrayQuantColumn< Double > sysvelQuant_p
Detailed Description
A class to provide easy read-write access to MSSource columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSSource
ArrayColumn
ScalarColumn
Etymology
MSSourceColumns stands for MeasurementSet Source Table columns.
Synopsis
This class provides access to the columns in the MSSource Table, it does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See MSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 243 of file MSSourceColumns.h.
Constructor & Destructor Documentation
MSSourceColumns() [1/3]
casacore::MSSourceColumns::MSSourceColumns (MSSource & msSource)
Construct from the supplied Table.
~MSSourceColumns()
casacore::MSSourceColumns::~MSSourceColumns ()
The destructor does nothing special.
MSSourceColumns() [2/3]
casacore::MSSourceColumns::MSSourceColumns () protected
MSSourceColumns() [3/3]
casacore::MSSourceColumns::MSSourceColumns (const MSSourceColumns &) private
Member Function Documentation
attach()
void casacore::MSSourceColumns::attach (MSSource & msSource) protected
attachOptionalCols()
void casacore::MSSourceColumns::attachOptionalCols (MSSource & msSource) private
calibrationGroup() [1/2]
ScalarColumn<Int>& casacore::MSSourceColumns::calibrationGroup () inline
Read-write access to required columns.
Definition at line 254 of file MSSourceColumns.h.
References calibrationGroup_p.
calibrationGroup() [2/2]
const ROScalarColumn<Int>& casacore::MSSourceColumns::calibrationGroup () const inline
Read-only access to required columns.
Definition at line 291 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::calibrationGroup().
code() [1/2]
ScalarColumn<String>& casacore::MSSourceColumns::code () inline
Definition at line 255 of file MSSourceColumns.h.
References code_p.
code() [2/2]
const ROScalarColumn<String>& casacore::MSSourceColumns::code () const inline
Definition at line 293 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::code().
direction() [1/2]
ArrayColumn<Double>& casacore::MSSourceColumns::direction () inline
Definition at line 256 of file MSSourceColumns.h.
References direction_p.
direction() [2/2]
const ROArrayColumn<Double>& casacore::MSSourceColumns::direction () const inline
Definition at line 295 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::direction().
directionMeas() [1/2]
ScalarMeasColumn<MDirection>& casacore::MSSourceColumns::directionMeas () inline
Definition at line 258 of file MSSourceColumns.h.
References directionMeas_p.
directionMeas() [2/2]
const ROScalarMeasColumn<MDirection>& casacore::MSSourceColumns::directionMeas () const inline
Definition at line 299 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::directionMeas().
directionQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSourceColumns::directionQuant () inline
Definition at line 257 of file MSSourceColumns.h.
References directionQuant_p.
directionQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSourceColumns::directionQuant () const inline
Definition at line 297 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::directionQuant().
interval() [1/2]
ScalarColumn<Double>& casacore::MSSourceColumns::interval () inline
Definition at line 259 of file MSSourceColumns.h.
References interval_p.
interval() [2/2]
const ROScalarColumn<Double>& casacore::MSSourceColumns::interval () const inline
Definition at line 301 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::interval().
intervalQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSSourceColumns::intervalQuant () inline
Definition at line 260 of file MSSourceColumns.h.
References intervalQuant_p.
intervalQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSSourceColumns::intervalQuant () const inline
Definition at line 303 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::intervalQuant().
name() [1/2]
ScalarColumn<String>& casacore::MSSourceColumns::name () inline
Definition at line 261 of file MSSourceColumns.h.
References name_p.
name() [2/2]
const ROScalarColumn<String>& casacore::MSSourceColumns::name () const inline
Definition at line 305 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::name().
numLines() [1/2]
ScalarColumn<Int>& casacore::MSSourceColumns::numLines () inline
Definition at line 262 of file MSSourceColumns.h.
References numLines_p.
numLines() [2/2]
const ROScalarColumn<Int>& casacore::MSSourceColumns::numLines () const inline
Definition at line 307 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::numLines().
operator=()
MSSourceColumns& casacore::MSSourceColumns::operator= (const MSSourceColumns &) private
position() [1/2]
ArrayColumn<Double>& casacore::MSSourceColumns::position () inline
Read-write access to optional columns.
Definition at line 274 of file MSSourceColumns.h.
References position_p.
position() [2/2]
const ROArrayColumn<Double>& casacore::MSSourceColumns::position () const inline
Read-only access to optional columns.
Definition at line 327 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::position().
positionMeas() [1/2]
ScalarMeasColumn<MPosition>& casacore::MSSourceColumns::positionMeas () inline
Definition at line 276 of file MSSourceColumns.h.
References positionMeas_p.
positionMeas() [2/2]
const ROScalarMeasColumn<MPosition>& casacore::MSSourceColumns::positionMeas () const inline
Definition at line 331 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::positionMeas().
positionQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSourceColumns::positionQuant () inline
Definition at line 275 of file MSSourceColumns.h.
References positionQuant_p.
positionQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSourceColumns::positionQuant () const inline
Definition at line 329 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::positionQuant().
properMotion() [1/2]
ArrayColumn<Double>& casacore::MSSourceColumns::properMotion () inline
Definition at line 263 of file MSSourceColumns.h.
References properMotion_p.
properMotion() [2/2]
const ROArrayColumn<Double>& casacore::MSSourceColumns::properMotion () const inline
Definition at line 309 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::properMotion().
properMotionQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSourceColumns::properMotionQuant () inline
Definition at line 264 of file MSSourceColumns.h.
References properMotionQuant_p.
properMotionQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSourceColumns::properMotionQuant () const inline
Definition at line 311 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::properMotionQuant().
pulsarId() [1/2]
ScalarColumn<Int>& casacore::MSSourceColumns::pulsarId () inline
Definition at line 277 of file MSSourceColumns.h.
References pulsarId_p.
pulsarId() [2/2]
const ROScalarColumn<Int>& casacore::MSSourceColumns::pulsarId () const inline
Definition at line 333 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::pulsarId().
restFrequency() [1/2]
ArrayColumn<Double>& casacore::MSSourceColumns::restFrequency () inline
Definition at line 278 of file MSSourceColumns.h.
References restFrequency_p.
restFrequency() [2/2]
const ROArrayColumn<Double>& casacore::MSSourceColumns::restFrequency () const inline
Definition at line 335 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::restFrequency().
restFrequencyMeas() [1/2]
ArrayMeasColumn<MFrequency>& casacore::MSSourceColumns::restFrequencyMeas () inline
Definition at line 280 of file MSSourceColumns.h.
References restFrequencyMeas_p.
restFrequencyMeas() [2/2]
const ROArrayMeasColumn<MFrequency>& casacore::MSSourceColumns::restFrequencyMeas () const inline
Definition at line 339 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::restFrequencyMeas().
restFrequencyQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSourceColumns::restFrequencyQuant () inline
Definition at line 279 of file MSSourceColumns.h.
References restFrequencyQuant_p.
restFrequencyQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSourceColumns::restFrequencyQuant () const inline
Definition at line 337 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::restFrequencyQuant().
setDirectionRef()
void casacore::MSSourceColumns::setDirectionRef (MDirection::Types ref)
set the direction type for the DIRECTION column.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
setEpochRef()
void casacore::MSSourceColumns::setEpochRef (MEpoch::Types ref, Bool tableMustBeEmpty = True)
set the epoch type for the TIME column.
Tip: In principle this function can only be used if the table is empty, otherwise already written values may thereafter have an incorrect reference, offset, or unit; However, it is possible that part of the table gets written before these values are known; In that case the reference, offset, or units can be set by using a False tableMustBeEmpty argument;
setFrequencyRef()
void casacore::MSSourceColumns::setFrequencyRef (MFrequency::Types ref)
set the frequency type for the REST_FREQUENCY column.
Does nothing if this column is not defined. This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
setPositionRef()
void casacore::MSSourceColumns::setPositionRef (MPosition::Types ref)
set the position type for the POSITION column.
This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
setRadialVelocityRef()
void casacore::MSSourceColumns::setRadialVelocityRef (MRadialVelocity::Types ref)
set the radial velocity type for the SYSVEL column.
Does nothing if this column is not defined. This can only be done when the table has no rows. Trying to do so at other times will throw an exception.
sourceId() [1/2]
ScalarColumn<Int>& casacore::MSSourceColumns::sourceId () inline
Definition at line 265 of file MSSourceColumns.h.
References sourceId_p.
sourceId() [2/2]
const ROScalarColumn<Int>& casacore::MSSourceColumns::sourceId () const inline
Definition at line 313 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::sourceId().
sourceModel() [1/2]
ScalarColumn<TableRecord>& casacore::MSSourceColumns::sourceModel () inline
Definition at line 282 of file MSSourceColumns.h.
References sourceModel_p.
sourceModel() [2/2]
const ROScalarColumn<TableRecord>& casacore::MSSourceColumns::sourceModel () const inline
Definition at line 341 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::sourceModel().
spectralWindowId() [1/2]
ScalarColumn<Int>& casacore::MSSourceColumns::spectralWindowId () inline
Definition at line 266 of file MSSourceColumns.h.
References spectralWindowId_p.
spectralWindowId() [2/2]
const ROScalarColumn<Int>& casacore::MSSourceColumns::spectralWindowId () const inline
Definition at line 315 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::spectralWindowId().
sysvel() [1/2]
ArrayColumn<Double>& casacore::MSSourceColumns::sysvel () inline
Definition at line 283 of file MSSourceColumns.h.
References sysvel_p.
sysvel() [2/2]
const ROArrayColumn<Double>& casacore::MSSourceColumns::sysvel () const inline
Definition at line 343 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::sysvel().
sysvelMeas() [1/2]
ArrayMeasColumn<MRadialVelocity>& casacore::MSSourceColumns::sysvelMeas () inline
Definition at line 285 of file MSSourceColumns.h.
References sysvelMeas_p.
sysvelMeas() [2/2]
const ROArrayMeasColumn<MRadialVelocity>& casacore::MSSourceColumns::sysvelMeas () const inline
Definition at line 347 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::sysvelMeas().
sysvelQuant() [1/2]
ArrayQuantColumn<Double>& casacore::MSSourceColumns::sysvelQuant () inline
Definition at line 284 of file MSSourceColumns.h.
References sysvelQuant_p.
sysvelQuant() [2/2]
const ROArrayQuantColumn<Double>& casacore::MSSourceColumns::sysvelQuant () const inline
Definition at line 345 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::sysvelQuant().
time() [1/2]
ScalarColumn<Double>& casacore::MSSourceColumns::time () inline
Definition at line 267 of file MSSourceColumns.h.
References time_p.
time() [2/2]
const ROScalarColumn<Double>& casacore::MSSourceColumns::time () const inline
Definition at line 317 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::time().
timeMeas() [1/2]
ScalarMeasColumn<MEpoch>& casacore::MSSourceColumns::timeMeas () inline
Definition at line 269 of file MSSourceColumns.h.
References timeMeas_p.
timeMeas() [2/2]
const ROScalarMeasColumn<MEpoch>& casacore::MSSourceColumns::timeMeas () const inline
Definition at line 321 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::timeMeas().
timeQuant() [1/2]
ScalarQuantColumn<Double>& casacore::MSSourceColumns::timeQuant () inline
Definition at line 268 of file MSSourceColumns.h.
References timeQuant_p.
timeQuant() [2/2]
const ROScalarQuantColumn<Double>& casacore::MSSourceColumns::timeQuant () const inline
Definition at line 319 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::timeQuant().
transition() [1/2]
ArrayColumn<String>& casacore::MSSourceColumns::transition () inline
Definition at line 286 of file MSSourceColumns.h.
References transition_p.
transition() [2/2]
const ROArrayColumn<String>& casacore::MSSourceColumns::transition () const inline
Definition at line 349 of file MSSourceColumns.h.
References casacore::ROMSSourceColumns::transition().
Member Data Documentation
calibrationGroup_p
ScalarColumn<Int> casacore::MSSourceColumns::calibrationGroup_p private
Definition at line 402 of file MSSourceColumns.h.
Referenced by calibrationGroup().
code_p
ScalarColumn<String> casacore::MSSourceColumns::code_p private
Definition at line 403 of file MSSourceColumns.h.
Referenced by code().
direction_p
ArrayColumn<Double> casacore::MSSourceColumns::direction_p private
Definition at line 404 of file MSSourceColumns.h.
Referenced by direction().
directionMeas_p
ScalarMeasColumn<MDirection> casacore::MSSourceColumns::directionMeas_p private
Definition at line 421 of file MSSourceColumns.h.
Referenced by directionMeas().
directionQuant_p
ArrayQuantColumn<Double> casacore::MSSourceColumns::directionQuant_p private
Definition at line 429 of file MSSourceColumns.h.
Referenced by directionQuant().
interval_p
ScalarColumn<Double> casacore::MSSourceColumns::interval_p private
Definition at line 405 of file MSSourceColumns.h.
Referenced by interval().
intervalQuant_p
ScalarQuantColumn<Double> casacore::MSSourceColumns::intervalQuant_p private
Definition at line 430 of file MSSourceColumns.h.
Referenced by intervalQuant().
name_p
ScalarColumn<String> casacore::MSSourceColumns::name_p private
Definition at line 406 of file MSSourceColumns.h.
Referenced by name().
numLines_p
ScalarColumn<Int> casacore::MSSourceColumns::numLines_p private
Definition at line 407 of file MSSourceColumns.h.
Referenced by numLines().
position_p
ArrayColumn<Double> casacore::MSSourceColumns::position_p private
Definition at line 413 of file MSSourceColumns.h.
Referenced by position().
positionMeas_p
ScalarMeasColumn<MPosition> casacore::MSSourceColumns::positionMeas_p private
Definition at line 424 of file MSSourceColumns.h.
Referenced by positionMeas().
positionQuant_p
ArrayQuantColumn<Double> casacore::MSSourceColumns::positionQuant_p private
Definition at line 434 of file MSSourceColumns.h.
Referenced by positionQuant().
properMotion_p
ArrayColumn<Double> casacore::MSSourceColumns::properMotion_p private
Definition at line 408 of file MSSourceColumns.h.
Referenced by properMotion().
properMotionQuant_p
ArrayQuantColumn<Double> casacore::MSSourceColumns::properMotionQuant_p private
Definition at line 431 of file MSSourceColumns.h.
Referenced by properMotionQuant().
pulsarId_p
ScalarColumn<Int> casacore::MSSourceColumns::pulsarId_p private
Definition at line 414 of file MSSourceColumns.h.
Referenced by pulsarId().
restFrequency_p
ArrayColumn<Double> casacore::MSSourceColumns::restFrequency_p private
Definition at line 415 of file MSSourceColumns.h.
Referenced by restFrequency().
restFrequencyMeas_p
ArrayMeasColumn<MFrequency> casacore::MSSourceColumns::restFrequencyMeas_p private
Definition at line 425 of file MSSourceColumns.h.
Referenced by restFrequencyMeas().
restFrequencyQuant_p
ArrayQuantColumn<Double> casacore::MSSourceColumns::restFrequencyQuant_p private
Definition at line 435 of file MSSourceColumns.h.
Referenced by restFrequencyQuant().
sourceId_p
ScalarColumn<Int> casacore::MSSourceColumns::sourceId_p private
Definition at line 409 of file MSSourceColumns.h.
Referenced by sourceId().
sourceModel_p
ScalarColumn<TableRecord> casacore::MSSourceColumns::sourceModel_p private
Definition at line 416 of file MSSourceColumns.h.
Referenced by sourceModel().
spectralWindowId_p
ScalarColumn<Int> casacore::MSSourceColumns::spectralWindowId_p private
Definition at line 410 of file MSSourceColumns.h.
Referenced by spectralWindowId().
sysvel_p
ArrayColumn<Double> casacore::MSSourceColumns::sysvel_p private
Definition at line 417 of file MSSourceColumns.h.
Referenced by sysvel().
sysvelMeas_p
ArrayMeasColumn<MRadialVelocity> casacore::MSSourceColumns::sysvelMeas_p private
Definition at line 426 of file MSSourceColumns.h.
Referenced by sysvelMeas().
sysvelQuant_p
ArrayQuantColumn<Double> casacore::MSSourceColumns::sysvelQuant_p private
Definition at line 436 of file MSSourceColumns.h.
Referenced by sysvelQuant().
time_p
ScalarColumn<Double> casacore::MSSourceColumns::time_p private
Definition at line 411 of file MSSourceColumns.h.
Referenced by time().
timeMeas_p
ScalarMeasColumn<MEpoch> casacore::MSSourceColumns::timeMeas_p private
Definition at line 422 of file MSSourceColumns.h.
Referenced by timeMeas().
timeQuant_p
ScalarQuantColumn<Double> casacore::MSSourceColumns::timeQuant_p private
Definition at line 432 of file MSSourceColumns.h.
Referenced by timeQuant().
transition_p
ArrayColumn<String> casacore::MSSourceColumns::transition_p private
Definition at line 418 of file MSSourceColumns.h.
Referenced by transition().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSSourceColumns.h