casacore: casacore::TaQLNodeResultRep Class Reference
casacore::TaQLNodeResultRep Class Reference
tables package (libcasa_tables) » TaQL_module » TaQL_module_internal_classes
Abstract base class to hold the result of a visit to the node tree.
#include <TaQLNodeResult.h>
Public Member Functions
TaQLNodeResultRep ()
Default constructor clears the reference count.
virtual ~TaQLNodeResultRep ()
Destructor.
Static Public Member Functions
static TaQLNodeResultRep * link (TaQLNodeResultRep *rep)
Increment the reference count.
static void unlink (TaQLNodeResultRep *rep)
Decrement the reference count.
Private Member Functions
TaQLNodeResultRep (const TaQLNodeResultRep &)
Letter objects cannot be copied.
TaQLNodeResultRep & operator= (const TaQLNodeResultRep &)
Private Attributes
int itsCount
Detailed Description
Abstract base class to hold the result of a visit to the node tree.
Intended use:
Internal
Review Status
Test programs:
tTableGram
Prerequisite
TaQLNodeVisitor
Note 199 describing TaQL
Synopsis
TaQLNodeResultRep is the abstract base class for classes holding values filled by visitors to the raw TaQL parse tree. Visitors are classes derived from TaQLNodeVisitor which traverse the parse tree. TaQLNodeResultRep is the counted referenced letter class in the envelope class TaQLNodeResult.
Definition at line 62 of file TaQLNodeResult.h.
Constructor & Destructor Documentation
TaQLNodeResultRep() [1/2]
casacore::TaQLNodeResultRep::TaQLNodeResultRep () inline
Default constructor clears the reference count.
The count is updated by functions link and unlink.
Definition at line 67 of file TaQLNodeResult.h.
~TaQLNodeResultRep()
virtual casacore::TaQLNodeResultRep::~TaQLNodeResultRep () virtual
Destructor.
TaQLNodeResultRep() [2/2]
casacore::TaQLNodeResultRep::TaQLNodeResultRep (const TaQLNodeResultRep &) private
Letter objects cannot be copied.
Member Function Documentation
link()
static TaQLNodeResultRep* casacore::TaQLNodeResultRep::link (TaQLNodeResultRep * rep) inline static
Increment the reference count.
Definition at line 74 of file TaQLNodeResult.h.
References itsCount.
Referenced by casacore::TaQLNodeResult::operator=(), and casacore::TaQLNodeResult::TaQLNodeResult().
operator=()
TaQLNodeResultRep& casacore::TaQLNodeResultRep::operator= (const TaQLNodeResultRep &) private
unlink()
static void casacore::TaQLNodeResultRep::unlink (TaQLNodeResultRep * rep) inline static
Decrement the reference count.
Delete the letter if no more references.
Definition at line 82 of file TaQLNodeResult.h.
References itsCount.
Referenced by casacore::TaQLNodeResult::operator=(), and casacore::TaQLNodeResult::~TaQLNodeResult().
Member Data Documentation
itsCount
int casacore::TaQLNodeResultRep::itsCount private
Definition at line 94 of file TaQLNodeResult.h.
Referenced by link(), and unlink().
The documentation for this class was generated from the following file:
tables/TaQL/TaQLNodeResult.h