casacore: casacore::PoissonParam< T > Class Template Reference
casacore::PoissonParam< T > Class Template Reference
scimath package (libcasa_scimath) » Functionals_module » Functionals_module_internal_classes
A one dimensional Poisson function.
#include <PoissonParam.h>
Public Types
enum {
LAMBDA,
HEIGHT
}
Parameter numbers.
Public Types inherited from casacore::Function< T >
typedef FunctionTraits< T >::ArgType ArgType
typedef const ArgType * FunctionArg
Public Member Functions
PoissonParam ()
Constructs the Poisson, Defaults: lambda=1.
PoissonParam (const T &lambda)
PoissonParam (const T &lambda, const T &height)
PoissonParam (const PoissonParam< T > &other)
Copy constructor (deep copy)
template<class W >
PoissonParam (const PoissonParam< W > &other)
PoissonParam< T > & operator= (const PoissonParam< T > &other)
Copy assignment (deep copy)
virtual ~PoissonParam ()
Destructor.
virtual uInt ndim () const
Returns the number of dimensions of function.
virtual const String & name () const
Give name of function.
T lambda () const
Get or set lambda.
void setLambda (const T &lambda)
T height () const
void setHeight (const T &height)
Public Member Functions inherited from casacore::Function< T >
Function ()
Constructors.
Function (const uInt n)
Function (const Vector< T > &in)
Function (const FunctionParam< T > &other)
Function (const Function< W, X > &other)
Function (const Function< T, T > &other)
virtual ~Function ()
Destructor.
uInt nparameters () const
Returns the number of parameters.
virtual T eval (FunctionArg x) const=0
Evaluate the function object.
T & operator[] (const uInt n)
Manipulate the nth parameter (0-based) with no index check.
const T & operator[] (const uInt n) const
virtual T operator() () const
Evaluate this function object at xor at x, y.
virtual T operator() (const ArgType &x) const
virtual T operator() (const Vector< ArgType > &x) const
virtual T operator() (FunctionArg x) const
virtual T operator() (const ArgType &x, const ArgType &y) const
virtual T operator() (const ArgType &x, const ArgType &y, const ArgType &z) const
Bool & mask (const uInt n)
Manipulate the mask associated with the nth parameter (e.g.
const Bool & mask (const uInt n) const
const FunctionParam< T > & parameters () const
Return the parameter interface.
FunctionParam< T > & parameters ()
const Vector< ArgType > & argp () const
Get arg_p and parset_p.
Bool parsetp () const
void lockParam ()
Compiler cannot always find the correct 'const' version of parameter access.
void unlockParam ()
virtual void setMode (const RecordInterface &mode)
get/set the function mode.
virtual void getMode (RecordInterface &mode) const
virtual Bool hasMode () const
return True if the implementing function supports a mode.
ostream & print (ostream &os) const
Print the function (i.e.
virtual Function< T, T > * clone () const=0
Return a copy of this object from the heap.
virtual Function< typename FunctionTraits< T >::DiffType > * cloneAD () const
virtual Function< typename FunctionTraits< T >::BaseType > * cloneNonAD () const
Public Member Functions inherited from casacore::Functional< FunctionTraits< T >::ArgType, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const FunctionTraits< T >::ArgType &x) const=0
Map a Domain x into a Range y value.
Public Member Functions inherited from casacore::Functional< Vector< FunctionTraits< T >::ArgType >, T >
virtual ~Functional ()
Destructor.
virtual T operator() (const Vector< FunctionTraits< T >::ArgType > &x) const=0
Map a Domain x into a Range y value.
Additional Inherited Members
Protected Attributes inherited from casacore::Function< T >
FunctionParam< T > param_p
The parameters and masks.
Vector< ArgType > arg_p
Aid for non-contiguous argument storage.
Bool parset_p
Indicate parameter written.
Bool locked_p
Indicate that parameters are expected to be locked from changing.
Detailed Description
template<class T>
class casacore::PoissonParam< T >
A one dimensional Poisson function.
Intended use:
Internal
Review Status
Test programs:
tFunctionHolder
Prerequisite
FunctionParam class
Function class
Etymology
A 1-dimensional Poisson.
Synopsis
A Poisson is described by lambda The value is:
height          (|x-center| == 0.0)
0               (|x-center| != 0.0)
The parameters are enumerated by LAMDA. They have default values of 1.
Example
PoissonFunction<Double> sf(5.0);
sf(25);            // = 5.0
Template Type Argument Requirements (T)
T should have standard numerical operators
Thrown Exceptions
AipsError if incorrect parameter number specified.
Definition at line 83 of file PoissonParam.h.
Member Enumeration Documentation
anonymous enum
template<class T> anonymous enum
Parameter numbers.
Enumerator
LAMBDA
HEIGHT
Definition at line 88 of file PoissonParam.h.
Constructor & Destructor Documentation
PoissonParam() [1/5]
template<class T> casacore::PoissonParam< T >::PoissonParam ()
Constructs the Poisson, Defaults: lambda=1.
Warning: Could not use default arguments that worked both with gcc and IRIX
PoissonParam() [2/5]
template<class T> casacore::PoissonParam< T >::PoissonParam (const T & lambda) explicit
PoissonParam() [3/5]
template<class T> casacore::PoissonParam< T >::PoissonParam (const T & lambda, const T & height)
PoissonParam() [4/5]
template<class T> casacore::PoissonParam< T >::PoissonParam (const PoissonParam< T > & other)
Copy constructor (deep copy)
PoissonParam() [5/5]
template<class T> template<class W > casacore::PoissonParam< T >::PoissonParam (const PoissonParam< W > & other) inline
Definition at line 105 of file PoissonParam.h.
~PoissonParam()
template<class T> virtual casacore::PoissonParam< T >::~PoissonParam () virtual
Destructor.
Member Function Documentation
height()
template<class T> T casacore::PoissonParam< T >::height () const inline
Definition at line 133 of file PoissonParam.h.
Referenced by casacore::PoissonParam< AutoDiff< T > >::setHeight().
lambda()
template<class T> T casacore::PoissonParam< T >::lambda () const inline
Get or set lambda.
Definition at line 126 of file PoissonParam.h.
Referenced by casacore::PoissonParam< AutoDiff< T > >::setLambda().
name()
template<class T> virtual const String& casacore::PoissonParam< T >::name () const inline virtual
Give name of function.
Reimplemented from casacore::Function< T >.
Definition at line 119 of file PoissonParam.h.
ndim()
template<class T> virtual uInt casacore::PoissonParam< T >::ndim () const inline virtual
Returns the number of dimensions of function.
Implements casacore::Function< T >.
Definition at line 115 of file PoissonParam.h.
operator=()
template<class T> PoissonParam<T>& casacore::PoissonParam< T >::operator= (const PoissonParam< T > & other)
Copy assignment (deep copy)
Referenced by casacore::PoissonFunction< T >::operator=().
setHeight()
template<class T> void casacore::PoissonParam< T >::setHeight (const T & height) inline
Definition at line 136 of file PoissonParam.h.
setLambda()
template<class T> void casacore::PoissonParam< T >::setLambda (const T & lambda) inline
Definition at line 129 of file PoissonParam.h.
The documentation for this class was generated from the following file:
scimath/Functionals/PoissonParam.h