casacore: casacore::ROMSSourceColumns Class Reference
casacore::ROMSSourceColumns Class Reference
ms package (libcasa_ms) » MeasurementSets_module
A class to provide easy read-only access to MSSource columns.
#include <MSSourceColumns.h>
Public Member Functions
ROMSSourceColumns (const MSSource &msSource)
Construct from the supplied Table.
~ROMSSourceColumns ()
The destructor does nothing special.
Bool isNull () const
Is this object defined? (MSSource table is optional)
const ROScalarColumn< Int > & calibrationGroup () const
Access to required columns.
const ROScalarColumn< String > & code () const
const ROArrayColumn< Double > & direction () const
const ROArrayQuantColumn< Double > & directionQuant () const
const ROScalarMeasColumn< MDirection > & directionMeas () const
const ROScalarColumn< Double > & interval () const
const ROScalarQuantColumn< Double > & intervalQuant () const
const ROScalarColumn< String > & name () const
const ROScalarColumn< Int > & numLines () const
const ROArrayColumn< Double > & properMotion () const
const ROArrayQuantColumn< Double > & properMotionQuant () const
const ROScalarColumn< Int > & sourceId () const
const ROScalarColumn< Int > & spectralWindowId () const
const ROScalarColumn< Double > & time () const
const ROScalarQuantColumn< Double > & timeQuant () const
const ROScalarMeasColumn< MEpoch > & timeMeas () const
const ROArrayColumn< Double > & position () const
Access to optional columns.
const ROArrayQuantColumn< Double > & positionQuant () const
const ROScalarMeasColumn< MPosition > & positionMeas () const
const ROScalarColumn< Int > & pulsarId () const
const ROArrayColumn< Double > & restFrequency () const
const ROArrayQuantColumn< Double > & restFrequencyQuant () const
const ROArrayMeasColumn< MFrequency > & restFrequencyMeas () const
const ROScalarColumn< TableRecord > & sourceModel () const
const ROArrayColumn< Double > & sysvel () const
const ROArrayQuantColumn< Double > & sysvelQuant () const
const ROArrayMeasColumn< MRadialVelocity > & sysvelMeas () const
const ROArrayColumn< String > & transition () const
uInt nrow () const
Convenience function that returns the number of rows in any of the columns.
Protected Member Functions
ROMSSourceColumns ()
void attach (const MSSource &msSource)
Private Member Functions
ROMSSourceColumns (const ROMSSourceColumns &)
ROMSSourceColumns & operator= (const ROMSSourceColumns &)
void attachOptionalCols (const MSSource &msSource)
Private Attributes
Bool isNull_p
ROScalarColumn< Int > calibrationGroup_p
ROScalarColumn< String > code_p
ROArrayColumn< Double > direction_p
ROScalarColumn< Double > interval_p
ROScalarColumn< String > name_p
ROScalarColumn< Int > numLines_p
ROArrayColumn< Double > properMotion_p
ROScalarColumn< Int > sourceId_p
ROScalarColumn< Int > spectralWindowId_p
ROScalarColumn< Double > time_p
ROArrayColumn< Double > position_p
ROScalarColumn< Int > pulsarId_p
ROArrayColumn< Double > restFrequency_p
ROScalarColumn< TableRecord > sourceModel_p
ROArrayColumn< Double > sysvel_p
ROArrayColumn< String > transition_p
ROScalarMeasColumn< MDirection > directionMeas_p
ROScalarMeasColumn< MEpoch > timeMeas_p
ROScalarMeasColumn< MPosition > positionMeas_p
ROArrayMeasColumn< MFrequency > restFrequencyMeas_p
ROArrayMeasColumn< MRadialVelocity > sysvelMeas_p
ROArrayQuantColumn< Double > directionQuant_p
ROScalarQuantColumn< Double > intervalQuant_p
ROArrayQuantColumn< Double > properMotionQuant_p
ROScalarQuantColumn< Double > timeQuant_p
ROArrayQuantColumn< Double > positionQuant_p
ROArrayQuantColumn< Double > restFrequencyQuant_p
ROArrayQuantColumn< Double > sysvelQuant_p
Detailed Description
A class to provide easy read-only access to MSSource columns.
Intended use:
Public interface
Review Status
Reviewed By:
Bob Garwood
Date Reviewed:
1997/02/01
Prerequisite
MSSource
ArrayColumn
ScalarColumn
Etymology
ROMSSourceColumns stands for Read-Only MeasurementSet Source Table columns.
Synopsis
This class provides read-only access to the columns in the MSSource Table. It does the declaration of all the Scalar and ArrayColumns with the correct types, so the application programmer doesn't have to worry about getting those right. There is an access function for every predefined column. Access to non-predefined columns will still have to be done with explicit declarations. See ROMSColumns for an example.
Motivation
See MSColumns for the motivation.
Definition at line 88 of file MSSourceColumns.h.
Constructor & Destructor Documentation
ROMSSourceColumns() [1/3]
casacore::ROMSSourceColumns::ROMSSourceColumns (const MSSource & msSource)
Construct from the supplied Table.
~ROMSSourceColumns()
casacore::ROMSSourceColumns::~ROMSSourceColumns ()
The destructor does nothing special.
ROMSSourceColumns() [2/3]
casacore::ROMSSourceColumns::ROMSSourceColumns () protected
ROMSSourceColumns() [3/3]
casacore::ROMSSourceColumns::ROMSSourceColumns (const ROMSSourceColumns &) private
Member Function Documentation
attach()
void casacore::ROMSSourceColumns::attach (const MSSource & msSource) protected
attachOptionalCols()
void casacore::ROMSSourceColumns::attachOptionalCols (const MSSource & msSource) private
calibrationGroup()
const ROScalarColumn<Int>& casacore::ROMSSourceColumns::calibrationGroup () const inline
Access to required columns.
Definition at line 102 of file MSSourceColumns.h.
References calibrationGroup_p.
Referenced by casacore::MSSourceColumns::calibrationGroup().
code()
const ROScalarColumn<String>& casacore::ROMSSourceColumns::code () const inline
Definition at line 104 of file MSSourceColumns.h.
References code_p.
Referenced by casacore::MSSourceColumns::code().
direction()
const ROArrayColumn<Double>& casacore::ROMSSourceColumns::direction () const inline
Definition at line 105 of file MSSourceColumns.h.
References direction_p.
Referenced by casacore::MSSourceColumns::direction().
directionMeas()
const ROScalarMeasColumn<MDirection>& casacore::ROMSSourceColumns::directionMeas () const inline
Definition at line 108 of file MSSourceColumns.h.
References directionMeas_p.
Referenced by casacore::MSSourceColumns::directionMeas().
directionQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSourceColumns::directionQuant () const inline
Definition at line 106 of file MSSourceColumns.h.
References directionQuant_p.
Referenced by casacore::MSSourceColumns::directionQuant().
interval()
const ROScalarColumn<Double>& casacore::ROMSSourceColumns::interval () const inline
Definition at line 110 of file MSSourceColumns.h.
References interval_p.
Referenced by casacore::MSSourceColumns::interval().
intervalQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSSourceColumns::intervalQuant () const inline
Definition at line 111 of file MSSourceColumns.h.
References intervalQuant_p.
Referenced by casacore::MSSourceColumns::intervalQuant().
isNull()
Bool casacore::ROMSSourceColumns::isNull () const inline
Is this object defined? (MSSource table is optional)
Definition at line 98 of file MSSourceColumns.h.
References isNull_p.
Referenced by nrow().
name()
const ROScalarColumn<String>& casacore::ROMSSourceColumns::name () const inline
Definition at line 113 of file MSSourceColumns.h.
References name_p.
Referenced by casacore::MSSourceColumns::name().
nrow()
uInt casacore::ROMSSourceColumns::nrow () const inline
Convenience function that returns the number of rows in any of the columns.
Returns zero if the object is null.
Definition at line 150 of file MSSourceColumns.h.
References calibrationGroup_p, and isNull().
numLines()
const ROScalarColumn<Int>& casacore::ROMSSourceColumns::numLines () const inline
Definition at line 114 of file MSSourceColumns.h.
References numLines_p.
Referenced by casacore::MSSourceColumns::numLines().
operator=()
ROMSSourceColumns& casacore::ROMSSourceColumns::operator= (const ROMSSourceColumns &) private
position()
const ROArrayColumn<Double>& casacore::ROMSSourceColumns::position () const inline
Access to optional columns.
Definition at line 128 of file MSSourceColumns.h.
References position_p.
Referenced by casacore::MSSourceColumns::position().
positionMeas()
const ROScalarMeasColumn<MPosition>& casacore::ROMSSourceColumns::positionMeas () const inline
Definition at line 131 of file MSSourceColumns.h.
References positionMeas_p.
Referenced by casacore::MSSourceColumns::positionMeas().
positionQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSourceColumns::positionQuant () const inline
Definition at line 129 of file MSSourceColumns.h.
References positionQuant_p.
Referenced by casacore::MSSourceColumns::positionQuant().
properMotion()
const ROArrayColumn<Double>& casacore::ROMSSourceColumns::properMotion () const inline
Definition at line 115 of file MSSourceColumns.h.
References properMotion_p.
Referenced by casacore::MSSourceColumns::properMotion().
properMotionQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSourceColumns::properMotionQuant () const inline
Definition at line 116 of file MSSourceColumns.h.
References properMotionQuant_p.
Referenced by casacore::MSSourceColumns::properMotionQuant().
pulsarId()
const ROScalarColumn<Int>& casacore::ROMSSourceColumns::pulsarId () const inline
Definition at line 133 of file MSSourceColumns.h.
References pulsarId_p.
Referenced by casacore::MSSourceColumns::pulsarId().
restFrequency()
const ROArrayColumn<Double>& casacore::ROMSSourceColumns::restFrequency () const inline
Definition at line 134 of file MSSourceColumns.h.
References restFrequency_p.
Referenced by casacore::MSSourceColumns::restFrequency().
restFrequencyMeas()
const ROArrayMeasColumn<MFrequency>& casacore::ROMSSourceColumns::restFrequencyMeas () const inline
Definition at line 137 of file MSSourceColumns.h.
References restFrequencyMeas_p.
Referenced by casacore::MSSourceColumns::restFrequencyMeas().
restFrequencyQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSourceColumns::restFrequencyQuant () const inline
Definition at line 135 of file MSSourceColumns.h.
References restFrequencyQuant_p.
Referenced by casacore::MSSourceColumns::restFrequencyQuant().
sourceId()
const ROScalarColumn<Int>& casacore::ROMSSourceColumns::sourceId () const inline
Definition at line 118 of file MSSourceColumns.h.
References sourceId_p.
Referenced by casacore::MSSourceColumns::sourceId().
sourceModel()
const ROScalarColumn<TableRecord>& casacore::ROMSSourceColumns::sourceModel () const inline
Definition at line 139 of file MSSourceColumns.h.
References sourceModel_p.
Referenced by casacore::MSSourceColumns::sourceModel().
spectralWindowId()
const ROScalarColumn<Int>& casacore::ROMSSourceColumns::spectralWindowId () const inline
Definition at line 119 of file MSSourceColumns.h.
References spectralWindowId_p.
Referenced by casacore::MSSourceColumns::spectralWindowId().
sysvel()
const ROArrayColumn<Double>& casacore::ROMSSourceColumns::sysvel () const inline
Definition at line 141 of file MSSourceColumns.h.
References sysvel_p.
Referenced by casacore::MSSourceColumns::sysvel().
sysvelMeas()
const ROArrayMeasColumn<MRadialVelocity>& casacore::ROMSSourceColumns::sysvelMeas () const inline
Definition at line 143 of file MSSourceColumns.h.
References sysvelMeas_p.
Referenced by casacore::MSSourceColumns::sysvelMeas().
sysvelQuant()
const ROArrayQuantColumn<Double>& casacore::ROMSSourceColumns::sysvelQuant () const inline
Definition at line 142 of file MSSourceColumns.h.
References sysvelQuant_p.
Referenced by casacore::MSSourceColumns::sysvelQuant().
time()
const ROScalarColumn<Double>& casacore::ROMSSourceColumns::time () const inline
Definition at line 121 of file MSSourceColumns.h.
References time_p.
Referenced by casacore::MSSourceColumns::time().
timeMeas()
const ROScalarMeasColumn<MEpoch>& casacore::ROMSSourceColumns::timeMeas () const inline
Definition at line 123 of file MSSourceColumns.h.
References timeMeas_p.
Referenced by casacore::MSSourceColumns::timeMeas().
timeQuant()
const ROScalarQuantColumn<Double>& casacore::ROMSSourceColumns::timeQuant () const inline
Definition at line 122 of file MSSourceColumns.h.
References timeQuant_p.
Referenced by casacore::MSSourceColumns::timeQuant().
transition()
const ROArrayColumn<String>& casacore::ROMSSourceColumns::transition () const inline
Definition at line 145 of file MSSourceColumns.h.
References transition_p.
Referenced by casacore::MSSourceColumns::transition().
Member Data Documentation
calibrationGroup_p
ROScalarColumn<Int> casacore::ROMSSourceColumns::calibrationGroup_p private
Definition at line 173 of file MSSourceColumns.h.
Referenced by calibrationGroup(), and nrow().
code_p
ROScalarColumn<String> casacore::ROMSSourceColumns::code_p private
Definition at line 174 of file MSSourceColumns.h.
Referenced by code().
direction_p
ROArrayColumn<Double> casacore::ROMSSourceColumns::direction_p private
Definition at line 175 of file MSSourceColumns.h.
Referenced by direction().
directionMeas_p
ROScalarMeasColumn<MDirection> casacore::ROMSSourceColumns::directionMeas_p private
Definition at line 192 of file MSSourceColumns.h.
Referenced by directionMeas().
directionQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSourceColumns::directionQuant_p private
Definition at line 200 of file MSSourceColumns.h.
Referenced by directionQuant().
interval_p
ROScalarColumn<Double> casacore::ROMSSourceColumns::interval_p private
Definition at line 176 of file MSSourceColumns.h.
Referenced by interval().
intervalQuant_p
ROScalarQuantColumn<Double> casacore::ROMSSourceColumns::intervalQuant_p private
Definition at line 201 of file MSSourceColumns.h.
Referenced by intervalQuant().
isNull_p
Bool casacore::ROMSSourceColumns::isNull_p private
Definition at line 170 of file MSSourceColumns.h.
Referenced by isNull().
name_p
ROScalarColumn<String> casacore::ROMSSourceColumns::name_p private
Definition at line 177 of file MSSourceColumns.h.
Referenced by name().
numLines_p
ROScalarColumn<Int> casacore::ROMSSourceColumns::numLines_p private
Definition at line 178 of file MSSourceColumns.h.
Referenced by numLines().
position_p
ROArrayColumn<Double> casacore::ROMSSourceColumns::position_p private
Definition at line 184 of file MSSourceColumns.h.
Referenced by position().
positionMeas_p
ROScalarMeasColumn<MPosition> casacore::ROMSSourceColumns::positionMeas_p private
Definition at line 195 of file MSSourceColumns.h.
Referenced by positionMeas().
positionQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSourceColumns::positionQuant_p private
Definition at line 205 of file MSSourceColumns.h.
Referenced by positionQuant().
properMotion_p
ROArrayColumn<Double> casacore::ROMSSourceColumns::properMotion_p private
Definition at line 179 of file MSSourceColumns.h.
Referenced by properMotion().
properMotionQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSourceColumns::properMotionQuant_p private
Definition at line 202 of file MSSourceColumns.h.
Referenced by properMotionQuant().
pulsarId_p
ROScalarColumn<Int> casacore::ROMSSourceColumns::pulsarId_p private
Definition at line 185 of file MSSourceColumns.h.
Referenced by pulsarId().
restFrequency_p
ROArrayColumn<Double> casacore::ROMSSourceColumns::restFrequency_p private
Definition at line 186 of file MSSourceColumns.h.
Referenced by restFrequency().
restFrequencyMeas_p
ROArrayMeasColumn<MFrequency> casacore::ROMSSourceColumns::restFrequencyMeas_p private
Definition at line 196 of file MSSourceColumns.h.
Referenced by restFrequencyMeas().
restFrequencyQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSourceColumns::restFrequencyQuant_p private
Definition at line 206 of file MSSourceColumns.h.
Referenced by restFrequencyQuant().
sourceId_p
ROScalarColumn<Int> casacore::ROMSSourceColumns::sourceId_p private
Definition at line 180 of file MSSourceColumns.h.
Referenced by sourceId().
sourceModel_p
ROScalarColumn<TableRecord> casacore::ROMSSourceColumns::sourceModel_p private
Definition at line 187 of file MSSourceColumns.h.
Referenced by sourceModel().
spectralWindowId_p
ROScalarColumn<Int> casacore::ROMSSourceColumns::spectralWindowId_p private
Definition at line 181 of file MSSourceColumns.h.
Referenced by spectralWindowId().
sysvel_p
ROArrayColumn<Double> casacore::ROMSSourceColumns::sysvel_p private
Definition at line 188 of file MSSourceColumns.h.
Referenced by sysvel().
sysvelMeas_p
ROArrayMeasColumn<MRadialVelocity> casacore::ROMSSourceColumns::sysvelMeas_p private
Definition at line 197 of file MSSourceColumns.h.
Referenced by sysvelMeas().
sysvelQuant_p
ROArrayQuantColumn<Double> casacore::ROMSSourceColumns::sysvelQuant_p private
Definition at line 207 of file MSSourceColumns.h.
Referenced by sysvelQuant().
time_p
ROScalarColumn<Double> casacore::ROMSSourceColumns::time_p private
Definition at line 182 of file MSSourceColumns.h.
Referenced by time().
timeMeas_p
ROScalarMeasColumn<MEpoch> casacore::ROMSSourceColumns::timeMeas_p private
Definition at line 193 of file MSSourceColumns.h.
Referenced by timeMeas().
timeQuant_p
ROScalarQuantColumn<Double> casacore::ROMSSourceColumns::timeQuant_p private
Definition at line 203 of file MSSourceColumns.h.
Referenced by timeQuant().
transition_p
ROArrayColumn<String> casacore::ROMSSourceColumns::transition_p private
Definition at line 189 of file MSSourceColumns.h.
Referenced by transition().
The documentation for this class was generated from the following file:
ms/MeasurementSets/MSSourceColumns.h