casacore: casacore::MSSelectableTable Class Reference
casacore::MSSelectableTable Class Reference abstract
ms package (libcasa_ms) » MSSel_module
MSSelectableTable: An interface class used by MSSelection module to access the sub-tables and main-table columns of MS-like tables.
#include <MSSelectableTable.h>
Public Types
enum MSSDataType {
BASELINE_BASED,
PURE_ANTENNA_BASED,
REF_ANTENNA_BASED
}
Public Member Functions
MSSelectableTable ()
MSSelectableTable (const Table &table)
virtual ~MSSelectableTable ()
virtual void setTable (const Table &table)
const Table * table ()
TableExprNode col (const String &colName)
virtual Bool isMS ()=0
virtual MSSDataType dataType ()=0
virtual const MSAntenna & antenna ()=0
virtual const MSField & field ()=0
virtual const MSSpectralWindow & spectralWindow ()=0
virtual const MSDataDescription & dataDescription ()=0
virtual const MSObservation & observation ()=0
virtual String columnName (MSMainEnums::PredefinedColumns nameEnum)=0
virtual const MeasurementSet * asMS ()=0
virtual MSSelectableMainColumn * mainColumns ()=0
Protected Attributes
const Table * table_p
Detailed Description
MSSelectableTable: An interface class used by MSSelection module to access the sub-tables and main-table columns of MS-like tables.
Intended use:
Public interface
Etymology
From "msselection" and "table".
Synopsis
This is a pure virtual base-class to provide a table-type agnostic interface to the MSSelection module to access sub-tables and main-table columns of MS-like tables.
Example
Motivation
To allow use of the MSSelection module for selection on any table that follows the general structure of the MS database. Via this class, minor differences in the database layout can be hidden from the MSSelection module. This also keeps MeasurementSet module from depending on other MS-like database implemention which may use the MSSelection module. Such usage will need to implement a specialization of MSSelectableTable and use it to instantiate the MSSelection object.
Definition at line 96 of file MSSelectableTable.h.
Member Enumeration Documentation
MSSDataType
enum casacore::MSSelectableTable::MSSDataType
Enumerator
BASELINE_BASED
PURE_ANTENNA_BASED
REF_ANTENNA_BASED
Definition at line 99 of file MSSelectableTable.h.
Constructor & Destructor Documentation
MSSelectableTable() [1/2]
casacore::MSSelectableTable::MSSelectableTable () inline
Definition at line 101 of file MSSelectableTable.h.
MSSelectableTable() [2/2]
casacore::MSSelectableTable::MSSelectableTable (const Table & table) inline
Definition at line 102 of file MSSelectableTable.h.
References table(), and table_p.
~MSSelectableTable()
virtual casacore::MSSelectableTable::~MSSelectableTable () inline virtual
Definition at line 103 of file MSSelectableTable.h.
Member Function Documentation
antenna()
virtual const MSAntenna& casacore::MSSelectableTable::antenna () pure virtual
Implemented in casacore::MSInterface.
asMS()
virtual const MeasurementSet* casacore::MSSelectableTable::asMS () pure virtual
Implemented in casacore::MSInterface.
col()
TableExprNode casacore::MSSelectableTable::col (const String & colName) inline
Definition at line 107 of file MSSelectableTable.h.
References casacore::Table::col(), and table().
columnName()
virtual String casacore::MSSelectableTable::columnName (MSMainEnums::PredefinedColumns nameEnum) pure virtual
Implemented in casacore::MSInterface.
dataDescription()
virtual const MSDataDescription& casacore::MSSelectableTable::dataDescription () pure virtual
Implemented in casacore::MSInterface.
dataType()
virtual MSSDataType casacore::MSSelectableTable::dataType () pure virtual
Implemented in casacore::MSInterface.
field()
virtual const MSField& casacore::MSSelectableTable::field () pure virtual
Implemented in casacore::MSInterface.
isMS()
virtual Bool casacore::MSSelectableTable::isMS () pure virtual
Implemented in casacore::MSInterface.
mainColumns()
virtual MSSelectableMainColumn* casacore::MSSelectableTable::mainColumns () pure virtual
Implemented in casacore::MSInterface.
observation()
virtual const MSObservation& casacore::MSSelectableTable::observation () pure virtual
Implemented in casacore::MSInterface.
setTable()
virtual void casacore::MSSelectableTable::setTable (const Table & table) inline virtual
Definition at line 105 of file MSSelectableTable.h.
References table(), and table_p.
spectralWindow()
virtual const MSSpectralWindow& casacore::MSSelectableTable::spectralWindow () pure virtual
Implemented in casacore::MSInterface.
table()
const Table* casacore::MSSelectableTable::table () inline
Definition at line 106 of file MSSelectableTable.h.
References table_p.
Referenced by casacore::MSInterface::asMS(), col(), MSSelectableTable(), and setTable().
Member Data Documentation
table_p
const Table* casacore::MSSelectableTable::table_p protected
Definition at line 123 of file MSSelectableTable.h.
Referenced by casacore::MSInterface::mainColumns(), MSSelectableTable(), setTable(), and table().
The documentation for this class was generated from the following file:
ms/MSSel/MSSelectableTable.h