casacore: casacore::CanonicalConversion Class Reference
casacore::CanonicalConversion Class Reference
OS_module
LDOUBLE is 8 bytes on SUN, but 16 bytes canonical.
#include <CanonicalConversion.h>
Static Public Member Functions
static size_t toLocal (char &to, const void *from)
Convert one value from canonical format to local format.
static size_t toLocal (unsigned char &to, const void *from)
static size_t toLocal (short &to, const void *from)
static size_t toLocal (unsigned short &to, const void *from)
static size_t toLocal (int &to, const void *from)
static size_t toLocal (unsigned int &to, const void *from)
static size_t toLocal (Int64 &to, const void *from)
static size_t toLocal (uInt64 &to, const void *from)
static size_t toLocal (float &to, const void *from)
static size_t toLocal (double &to, const void *from)
static size_t fromLocal (void *to, const char &from)
Convert one value from local format to canonical format.
static size_t fromLocal (void *to, const unsigned char &from)
static size_t fromLocal (void *to, const short &from)
static size_t fromLocal (void *to, const unsigned short &from)
static size_t fromLocal (void *to, const int &from)
static size_t fromLocal (void *to, const unsigned int &from)
static size_t fromLocal (void *to, const Int64 &from)
static size_t fromLocal (void *to, const uInt64 &from)
static size_t fromLocal (void *to, const float &from)
static size_t fromLocal (void *to, const double &from)
static size_t toLocal (char *to, const void *from, size_t nr)
Convert nr values from canonical format to local format.
static size_t toLocal (unsigned char *to, const void *from, size_t nr)
static size_t toLocal (short *to, const void *from, size_t nr)
static size_t toLocal (unsigned short *to, const void *from, size_t nr)
static size_t toLocal (int *to, const void *from, size_t nr)
static size_t toLocal (unsigned int *to, const void *from, size_t nr)
static size_t toLocal (Int64 *to, const void *from, size_t nr)
static size_t toLocal (uInt64 *to, const void *from, size_t nr)
static size_t toLocal (float *to, const void *from, size_t nr)
static size_t toLocal (double *to, const void *from, size_t nr)
static size_t fromLocal (void *to, const char *from, size_t nr)
Convert nr values from local format to canonical format.
static size_t fromLocal (void *to, const unsigned char *from, size_t nr)
static size_t fromLocal (void *to, const short *from, size_t nr)
static size_t fromLocal (void *to, const unsigned short *from, size_t nr)
static size_t fromLocal (void *to, const int *from, size_t nr)
static size_t fromLocal (void *to, const unsigned int *from, size_t nr)
static size_t fromLocal (void *to, const Int64 *from, size_t nr)
static size_t fromLocal (void *to, const uInt64 *from, size_t nr)
static size_t fromLocal (void *to, const float *from, size_t nr)
static size_t fromLocal (void *to, const double *from, size_t nr)
static size_t toLocalChar (void *to, const void *from, size_t nr)
Convert nr values from canonical format to local format.
static size_t toLocalUChar (void *to, const void *from, size_t nr)
static size_t toLocalShort (void *to, const void *from, size_t nr)
static size_t toLocalUShort (void *to, const void *from, size_t nr)
static size_t toLocalInt (void *to, const void *from, size_t nr)
static size_t toLocalUInt (void *to, const void *from, size_t nr)
static size_t toLocalInt64 (void *to, const void *from, size_t nr)
static size_t toLocalUInt64 (void *to, const void *from, size_t nr)
static size_t toLocalFloat (void *to, const void *from, size_t nr)
static size_t toLocalDouble (void *to, const void *from, size_t nr)
static size_t fromLocalChar (void *to, const void *from, size_t nr)
Convert nr values from local format to canonical format.
static size_t fromLocalUChar (void *to, const void *from, size_t nr)
static size_t fromLocalShort (void *to, const void *from, size_t nr)
static size_t fromLocalUShort (void *to, const void *from, size_t nr)
static size_t fromLocalInt (void *to, const void *from, size_t nr)
static size_t fromLocalUInt (void *to, const void *from, size_t nr)
static size_t fromLocalInt64 (void *to, const void *from, size_t nr)
static size_t fromLocalUInt64 (void *to, const void *from, size_t nr)
static size_t fromLocalFloat (void *to, const void *from, size_t nr)
static size_t fromLocalDouble (void *to, const void *from, size_t nr)
static void * byteToLocalChar (void *to, const void *from, size_t nrbytes)
Convert values from canonical format to local format.
static void * byteToLocalUChar (void *to, const void *from, size_t nrbytes)
static void * byteToLocalShort (void *to, const void *from, size_t nrbytes)
static void * byteToLocalUShort (void *to, const void *from, size_t nrbytes)
static void * byteToLocalInt (void *to, const void *from, size_t nrbytes)
static void * byteToLocalUInt (void *to, const void *from, size_t nrbytes)
static void * byteToLocalInt64 (void *to, const void *from, size_t nrbytes)
static void * byteToLocalUInt64 (void *to, const void *from, size_t nrbytes)
static void * byteToLocalFloat (void *to, const void *from, size_t nrbytes)
static void * byteToLocalDouble (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalChar (void *to, const void *from, size_t nrbytes)
Convert values from local format to canonical format.
static void * byteFromLocalUChar (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalShort (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalUShort (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalInt (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalUInt (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalInt64 (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalUInt64 (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalFloat (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalDouble (void *to, const void *from, size_t nrbytes)
static Conversion::ValueFunction * getToLocal (const char *)
Get the value conversion function for the given type.
static Conversion::ValueFunction * getToLocal (const unsigned char *)
static Conversion::ValueFunction * getToLocal (const short *)
static Conversion::ValueFunction * getToLocal (const unsigned short *)
static Conversion::ValueFunction * getToLocal (const int *)
static Conversion::ValueFunction * getToLocal (const unsigned int *)
static Conversion::ValueFunction * getToLocal (const Int64 *)
static Conversion::ValueFunction * getToLocal (const uInt64 *)
static Conversion::ValueFunction * getToLocal (const float *)
static Conversion::ValueFunction * getToLocal (const double *)
static Conversion::ValueFunction * getFromLocal (const char *)
static Conversion::ValueFunction * getFromLocal (const unsigned char *)
static Conversion::ValueFunction * getFromLocal (const short *)
static Conversion::ValueFunction * getFromLocal (const unsigned short *)
static Conversion::ValueFunction * getFromLocal (const int *)
static Conversion::ValueFunction * getFromLocal (const unsigned int *)
static Conversion::ValueFunction * getFromLocal (const Int64 *)
static Conversion::ValueFunction * getFromLocal (const uInt64 *)
static Conversion::ValueFunction * getFromLocal (const float *)
static Conversion::ValueFunction * getFromLocal (const double *)
static Conversion::ByteFunction * getByteToLocal (const char *)
Get the byte conversion function for the given type.
static Conversion::ByteFunction * getByteToLocal (const unsigned char *)
static Conversion::ByteFunction * getByteToLocal (const short *)
static Conversion::ByteFunction * getByteToLocal (const unsigned short *)
static Conversion::ByteFunction * getByteToLocal (const int *)
static Conversion::ByteFunction * getByteToLocal (const unsigned int *)
static Conversion::ByteFunction * getByteToLocal (const Int64 *)
static Conversion::ByteFunction * getByteToLocal (const uInt64 *)
static Conversion::ByteFunction * getByteToLocal (const float *)
static Conversion::ByteFunction * getByteToLocal (const double *)
static Conversion::ByteFunction * getByteFromLocal (const char *)
static Conversion::ByteFunction * getByteFromLocal (const unsigned char *)
static Conversion::ByteFunction * getByteFromLocal (const short *)
static Conversion::ByteFunction * getByteFromLocal (const unsigned short *)
static Conversion::ByteFunction * getByteFromLocal (const int *)
static Conversion::ByteFunction * getByteFromLocal (const unsigned int *)
static Conversion::ByteFunction * getByteFromLocal (const Int64 *)
static Conversion::ByteFunction * getByteFromLocal (const uInt64 *)
static Conversion::ByteFunction * getByteFromLocal (const float *)
static Conversion::ByteFunction * getByteFromLocal (const double *)
static unsigned int canonicalSize (const char *)
Return the canonical length for the various data types.
static unsigned int canonicalSize (const unsigned char *)
static unsigned int canonicalSize (const short *)
static unsigned int canonicalSize (const unsigned short *)
static unsigned int canonicalSize (const int *)
static unsigned int canonicalSize (const unsigned int *)
static unsigned int canonicalSize (const Int64 *)
static unsigned int canonicalSize (const uInt64 *)
static unsigned int canonicalSize (const float *)
static unsigned int canonicalSize (const double *)
static void reverse2 (void *to, const void *from)
Reverse 2 bytes.
static void reverse4 (void *to, const void *from)
Reverse 4 bytes.
static void reverse8 (void *to, const void *from)
Reverse 8 bytes.
static void move2 (void *to, const void *from)
Move 2 bytes.
static void move4 (void *to, const void *from)
Move 4 bytes.
static void move8 (void *to, const void *from)
Move 8 bytes.
Private Member Functions
CanonicalConversion ()
This class should not be constructed (so declare the constructor private).
Detailed Description
LDOUBLE is 8 bytes on SUN, but 16 bytes canonical.
@anchor CanonicalConversion_summary
A class with static functions to convert canonical format
Intended use:
Public interface
Review Status
Reviewed By:
Friso Olnon
Date Reviewed:
1996/11/06
Test programs:
tCanonicalConversion
Synopsis
This class consists of several static functions to convert data from local (=native) format to a canonical format. The canonical length of each data type is:
- Bool: 1 bit
- char: 1 byte
- short: 2 bytes
- int: 4 bytes
- Int64: 8 bytes
- float: 4 bytes
- double: 8 bytes
The canonical format is big-endian IEEE format, so on many machines the conversion is only a copy operation. On Alpha- or Intel-based machines, however, it involves a byte swap to convert from little endian to big endian.
The class also contains conversion functions making it possible to specify the number of bytes (in local format) instead of the number of values. These functions are included to make it possible to have the same signature as memcpy.
The current implementation of this class works on big- and little-endian machines using IEEE format. When using on other machines (e.g. VAX) the toLocal and fromLocal functions have to be changed.
Note that no functions are provided to handle Bools. Instead class Conversion provides functions to convert Bools to/from bits.
Example
void someFunction (const uInt* data, uInt nrval)
{
char* buffer = new char[nrval*CanonicalConversion::canonicalSize(data)];
CanonicalConversion::fromLocal (buffer, data, nrval);
...\.
delete [] buffer;
}
Motivation
Casacore data will often be stored in a canonical format. To read these data conversion functions are needed. However, these functions do not use any other Casacore classes, so they can easily be used in any other software system.
To Do
Support data type long double.
Definition at line 160 of file CanonicalConversion.h.
Constructor & Destructor Documentation
casacore::CanonicalConversion::CanonicalConversion () private
This class should not be constructed (so declare the constructor private).
Member Function Documentation
static void* casacore::CanonicalConversion::byteFromLocalChar (void * to, const void * from, size_t nrbytes) static
Convert values from local format to canonical format.
The from and to buffer should not overlap. The number of values involved is determined from the argument nrbytes, which gives the number of bytes in local format. The signature of this function is the same as memcpy, so that memcpy can directly be used if no conversion is needed.
static void* casacore::CanonicalConversion::byteFromLocalDouble (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalFloat (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalShort (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalUChar (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalUInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalUInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteFromLocalUShort (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalChar (void * to, const void * from, size_t nrbytes) static
Convert values from canonical format to local format.
The from and to buffer should not overlap. The number of values involved is determined from the argument nrbytes, which gives the number of bytes in local format. The signature of this function is the same as memcpy, so that memcpy can directly be used if no conversion is needed.
static void* casacore::CanonicalConversion::byteToLocalDouble (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalFloat (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalShort (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalUChar (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalUInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalUInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::CanonicalConversion::byteToLocalUShort (void * to, const void * from, size_t nrbytes) static
unsigned int casacore::CanonicalConversion::canonicalSize (const char *) inline static
Return the canonical length for the various data types.
Definition at line 948 of file CanonicalConversion.h.
References SIZE_CAN_CHAR.
unsigned int casacore::CanonicalConversion::canonicalSize (const unsigned char *) inline static
Definition at line 950 of file CanonicalConversion.h.
References SIZE_CAN_UCHAR.
unsigned int casacore::CanonicalConversion::canonicalSize (const short *) inline static
Definition at line 952 of file CanonicalConversion.h.
References SIZE_CAN_SHORT.
unsigned int casacore::CanonicalConversion::canonicalSize (const unsigned short *) inline static
Definition at line 954 of file CanonicalConversion.h.
References SIZE_CAN_USHORT.
unsigned int casacore::CanonicalConversion::canonicalSize (const int *) inline static
Definition at line 956 of file CanonicalConversion.h.
References SIZE_CAN_INT.
unsigned int casacore::CanonicalConversion::canonicalSize (const unsigned int *) inline static
Definition at line 958 of file CanonicalConversion.h.
References SIZE_CAN_UINT.
unsigned int casacore::CanonicalConversion::canonicalSize (const Int64 *) inline static
Definition at line 960 of file CanonicalConversion.h.
References SIZE_CAN_INT64.
unsigned int casacore::CanonicalConversion::canonicalSize (const uInt64 *) inline static
Definition at line 962 of file CanonicalConversion.h.
References SIZE_CAN_UINT64.
unsigned int casacore::CanonicalConversion::canonicalSize (const float *) inline static
Definition at line 964 of file CanonicalConversion.h.
References SIZE_CAN_FLOAT.
unsigned int casacore::CanonicalConversion::canonicalSize (const double *) inline static
Definition at line 966 of file CanonicalConversion.h.
References SIZE_CAN_DOUBLE.
size_t casacore::CanonicalConversion::fromLocal (void * to, const char & from) inline static
Convert one value from local format to canonical format.
The from and to buffer should not overlap.
Definition at line 620 of file CanonicalConversion.h.
References SIZE_CAN_CHAR.
size_t casacore::CanonicalConversion::fromLocal (void * to, const unsigned char & from) inline static
Definition at line 626 of file CanonicalConversion.h.
References SIZE_CAN_UCHAR.
size_t casacore::CanonicalConversion::fromLocal (void * to, const short & from) inline static
Definition at line 633 of file CanonicalConversion.h.
References move2(), reverse2(), and SIZE_CAN_SHORT.
size_t casacore::CanonicalConversion::fromLocal (void * to, const unsigned short & from) inline static
Definition at line 644 of file CanonicalConversion.h.
References move2(), reverse2(), and SIZE_CAN_USHORT.
size_t casacore::CanonicalConversion::fromLocal (void * to, const int & from) inline static
Definition at line 655 of file CanonicalConversion.h.
References move4(), reverse4(), and SIZE_CAN_INT.
size_t casacore::CanonicalConversion::fromLocal (void * to, const unsigned int & from) inline static
Definition at line 666 of file CanonicalConversion.h.
References move4(), reverse4(), and SIZE_CAN_UINT.
size_t casacore::CanonicalConversion::fromLocal (void * to, const Int64 & from) inline static
Definition at line 677 of file CanonicalConversion.h.
References move8(), reverse8(), and SIZE_CAN_INT64.
size_t casacore::CanonicalConversion::fromLocal (void * to, const uInt64 & from) inline static
Definition at line 688 of file CanonicalConversion.h.
References move8(), reverse8(), and SIZE_CAN_UINT64.
size_t casacore::CanonicalConversion::fromLocal (void * to, const float & from) inline static
Definition at line 699 of file CanonicalConversion.h.
References move4(), reverse4(), and SIZE_CAN_FLOAT.
size_t casacore::CanonicalConversion::fromLocal (void * to, const double & from) inline static
Definition at line 710 of file CanonicalConversion.h.
References move8(), reverse8(), and SIZE_CAN_FLOAT.
size_t casacore::CanonicalConversion::fromLocal (void * to, const char * from, size_t nr) inline static
Convert nr values from local format to canonical format.
The from and to buffer should not overlap.
Definition at line 783 of file CanonicalConversion.h.
References fromLocalChar().
size_t casacore::CanonicalConversion::fromLocal (void * to, const unsigned char * from, size_t nr) inline static
Definition at line 789 of file CanonicalConversion.h.
References fromLocalUChar().
size_t casacore::CanonicalConversion::fromLocal (void * to, const short * from, size_t nr) inline static
Definition at line 795 of file CanonicalConversion.h.
References fromLocalShort().
size_t casacore::CanonicalConversion::fromLocal (void * to, const unsigned short * from, size_t nr) inline static
Definition at line 801 of file CanonicalConversion.h.
References fromLocalUShort().
size_t casacore::CanonicalConversion::fromLocal (void * to, const int * from, size_t nr) inline static
Definition at line 807 of file CanonicalConversion.h.
References fromLocalInt().
size_t casacore::CanonicalConversion::fromLocal (void * to, const unsigned int * from, size_t nr) inline static
Definition at line 813 of file CanonicalConversion.h.
References fromLocalUInt().
size_t casacore::CanonicalConversion::fromLocal (void * to, const Int64 * from, size_t nr) inline static
Definition at line 819 of file CanonicalConversion.h.
References fromLocalInt64().
size_t casacore::CanonicalConversion::fromLocal (void * to, const uInt64 * from, size_t nr) inline static
Definition at line 825 of file CanonicalConversion.h.
References fromLocalUInt64().
size_t casacore::CanonicalConversion::fromLocal (void * to, const float * from, size_t nr) inline static
Definition at line 831 of file CanonicalConversion.h.
References fromLocalFloat().
size_t casacore::CanonicalConversion::fromLocal (void * to, const double * from, size_t nr) inline static
Definition at line 837 of file CanonicalConversion.h.
References fromLocalDouble().
static size_t casacore::CanonicalConversion::fromLocalChar (void * to, const void * from, size_t nr) static
Convert nr values from local format to canonical format.
The from and to buffer should not overlap.
Referenced by casacore::ModcompConversion::fromLocal(), and fromLocal().
static size_t casacore::CanonicalConversion::fromLocalDouble (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::CanonicalConversion::fromLocalFloat (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::CanonicalConversion::fromLocalInt (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::fromLocal(), and fromLocal().
static size_t casacore::CanonicalConversion::fromLocalInt64 (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::CanonicalConversion::fromLocalShort (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::fromLocal(), and fromLocal().
static size_t casacore::CanonicalConversion::fromLocalUChar (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::fromLocal(), and fromLocal().
static size_t casacore::CanonicalConversion::fromLocalUInt (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::fromLocal(), and fromLocal().
static size_t casacore::CanonicalConversion::fromLocalUInt64 (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::CanonicalConversion::fromLocalUShort (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::fromLocal(), and fromLocal().
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const char *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const unsigned char *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const short *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const unsigned short *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const int *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const unsigned int *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const Int64 *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const uInt64 *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const float *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteFromLocal (const double *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const char *) static
Get the byte conversion function for the given type.
The function memcpy is returned when a conversion is not needed.
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const unsigned char *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const short *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const unsigned short *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const int *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const unsigned int *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const Int64 *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const uInt64 *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const float *) static
static Conversion::ByteFunction* casacore::CanonicalConversion::getByteToLocal (const double *) static
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const char *) inline static
Definition at line 897 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const unsigned char *) inline static
Definition at line 902 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const short *) inline static
Definition at line 907 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const unsigned short *) inline static
Definition at line 912 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const int *) inline static
Definition at line 917 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const unsigned int *) inline static
Definition at line 922 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const Int64 *) inline static
Definition at line 927 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const uInt64 *) inline static
Definition at line 932 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const float *) inline static
Definition at line 937 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getFromLocal (const double *) inline static
Definition at line 942 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const char *) inline static
Get the value conversion function for the given type.
Definition at line 846 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const unsigned char *) inline static
Definition at line 851 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const short *) inline static
Definition at line 856 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const unsigned short *) inline static
Definition at line 861 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const int *) inline static
Definition at line 866 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const unsigned int *) inline static
Definition at line 871 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const Int64 *) inline static
Definition at line 876 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const uInt64 *) inline static
Definition at line 881 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const float *) inline static
Definition at line 886 of file CanonicalConversion.h.
Conversion::ValueFunction * casacore::CanonicalConversion::getToLocal (const double *) inline static
Definition at line 891 of file CanonicalConversion.h.
void casacore::CanonicalConversion::move2 (void * to, const void * from) inline static
Move 2 bytes.
Definition at line 468 of file CanonicalConversion.h.
Referenced by casacore::LittleEndianConversion::fromLocal(), fromLocal(), casacore::LittleEndianConversion::toLocal(), and toLocal().
void casacore::CanonicalConversion::move4 (void * to, const void * from) inline static
Move 4 bytes.
Definition at line 473 of file CanonicalConversion.h.
Referenced by casacore::LittleEndianConversion::fromLocal(), casacore::IBMConversion::fromLocal(), fromLocal(), casacore::LittleEndianConversion::toLocal(), casacore::IBMConversion::toLocal(), and toLocal().
void casacore::CanonicalConversion::move8 (void * to, const void * from) inline static
Move 8 bytes.
Definition at line 480 of file CanonicalConversion.h.
Referenced by casacore::LittleEndianConversion::fromLocal(), fromLocal(), casacore::LittleEndianConversion::toLocal(), and toLocal().
void casacore::CanonicalConversion::reverse2 (void * to, const void * from) inline static
Reverse 2 bytes.
Definition at line 444 of file CanonicalConversion.h.
Referenced by casacore::LittleEndianConversion::fromLocal(), fromLocal(), casacore::LittleEndianConversion::toLocal(), and toLocal().
void casacore::CanonicalConversion::reverse4 (void * to, const void * from) inline static
Reverse 4 bytes.
Definition at line 449 of file CanonicalConversion.h.
Referenced by casacore::LittleEndianConversion::fromLocal(), casacore::IBMConversion::fromLocal(), fromLocal(), casacore::LittleEndianConversion::toLocal(), casacore::IBMConversion::toLocal(), and toLocal().
void casacore::CanonicalConversion::reverse8 (void * to, const void * from) inline static
Reverse 8 bytes.
Definition at line 456 of file CanonicalConversion.h.
Referenced by casacore::LittleEndianConversion::fromLocal(), fromLocal(), casacore::LittleEndianConversion::toLocal(), and toLocal().
size_t casacore::CanonicalConversion::toLocal (char & to, const void * from) inline static
Convert one value from canonical format to local format.
The from and to buffer should not overlap.
Definition at line 494 of file CanonicalConversion.h.
References SIZE_CAN_CHAR.
size_t casacore::CanonicalConversion::toLocal (unsigned char & to, const void * from) inline static
Definition at line 500 of file CanonicalConversion.h.
References SIZE_CAN_UCHAR.
size_t casacore::CanonicalConversion::toLocal (short & to, const void * from) inline static
Definition at line 507 of file CanonicalConversion.h.
References move2(), reverse2(), and SIZE_CAN_SHORT.
size_t casacore::CanonicalConversion::toLocal (unsigned short & to, const void * from) inline static
Definition at line 524 of file CanonicalConversion.h.
References move2(), reverse2(), and SIZE_CAN_USHORT.
size_t casacore::CanonicalConversion::toLocal (int & to, const void * from) inline static
Definition at line 538 of file CanonicalConversion.h.
References move4(), reverse4(), and SIZE_CAN_INT.
size_t casacore::CanonicalConversion::toLocal (unsigned int & to, const void * from) inline static
Definition at line 555 of file CanonicalConversion.h.
References move4(), reverse4(), and SIZE_CAN_UINT.
size_t casacore::CanonicalConversion::toLocal (Int64 & to, const void * from) inline static
Definition at line 569 of file CanonicalConversion.h.
References move8(), reverse8(), and SIZE_CAN_INT64.
size_t casacore::CanonicalConversion::toLocal (uInt64 & to, const void * from) inline static
Definition at line 586 of file CanonicalConversion.h.
References move8(), reverse8(), and SIZE_CAN_UINT64.
size_t casacore::CanonicalConversion::toLocal (float & to, const void * from) inline static
Definition at line 599 of file CanonicalConversion.h.
References move4(), reverse4(), and SIZE_CAN_FLOAT.
size_t casacore::CanonicalConversion::toLocal (double & to, const void * from) inline static
Definition at line 609 of file CanonicalConversion.h.
References move8(), reverse8(), and SIZE_CAN_DOUBLE.
size_t casacore::CanonicalConversion::toLocal (char * to, const void * from, size_t nr) inline static
Convert nr values from canonical format to local format.
The from and to buffer should not overlap.
Definition at line 722 of file CanonicalConversion.h.
References toLocalChar().
size_t casacore::CanonicalConversion::toLocal (unsigned char * to, const void * from, size_t nr) inline static
Definition at line 728 of file CanonicalConversion.h.
References toLocalUChar().
size_t casacore::CanonicalConversion::toLocal (short * to, const void * from, size_t nr) inline static
Definition at line 734 of file CanonicalConversion.h.
References toLocalShort().
size_t casacore::CanonicalConversion::toLocal (unsigned short * to, const void * from, size_t nr) inline static
Definition at line 740 of file CanonicalConversion.h.
References toLocalUShort().
size_t casacore::CanonicalConversion::toLocal (int * to, const void * from, size_t nr) inline static
Definition at line 746 of file CanonicalConversion.h.
References toLocalInt().
size_t casacore::CanonicalConversion::toLocal (unsigned int * to, const void * from, size_t nr) inline static
Definition at line 752 of file CanonicalConversion.h.
References toLocalUInt().
size_t casacore::CanonicalConversion::toLocal (Int64 * to, const void * from, size_t nr) inline static
Definition at line 758 of file CanonicalConversion.h.
References toLocalInt64().
size_t casacore::CanonicalConversion::toLocal (uInt64 * to, const void * from, size_t nr) inline static
Definition at line 764 of file CanonicalConversion.h.
References toLocalUInt64().
size_t casacore::CanonicalConversion::toLocal (float * to, const void * from, size_t nr) inline static
Definition at line 770 of file CanonicalConversion.h.
References toLocalFloat().
size_t casacore::CanonicalConversion::toLocal (double * to, const void * from, size_t nr) inline static
Definition at line 776 of file CanonicalConversion.h.
References toLocalDouble().
static size_t casacore::CanonicalConversion::toLocalChar (void * to, const void * from, size_t nr) static
Convert nr values from canonical format to local format.
The from and to buffer should not overlap.
Referenced by casacore::ModcompConversion::toLocal(), and toLocal().
static size_t casacore::CanonicalConversion::toLocalDouble (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::CanonicalConversion::toLocalFloat (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::CanonicalConversion::toLocalInt (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::toLocal(), and toLocal().
static size_t casacore::CanonicalConversion::toLocalInt64 (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::CanonicalConversion::toLocalShort (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::toLocal(), and toLocal().
static size_t casacore::CanonicalConversion::toLocalUChar (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::toLocal(), and toLocal().
static size_t casacore::CanonicalConversion::toLocalUInt (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::toLocal(), and toLocal().
static size_t casacore::CanonicalConversion::toLocalUInt64 (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::CanonicalConversion::toLocalUShort (void * to, const void * from, size_t nr) static
Referenced by casacore::ModcompConversion::toLocal(), and toLocal().
The documentation for this class was generated from the following file:
casa/OS/CanonicalConversion.h