casacore: casacore::PrimaryGroup< TYPE > Class Template Reference
casacore::PrimaryGroup< TYPE > Class Template Reference
FITS_module
Random Group datastructure.
#include <hdu.h>
Public Member Functions
PrimaryGroup (FitsInput &, FITSErrorHandler errhandler=FITSError::defaultHandler)
PrimaryGroup (FitsKeywordList &, FITSErrorHandler errhandler=FITSError::defaultHandler)
PrimaryGroup (FITSErrorHandler errhandler=FITSError::defaultHandler)
constructor for header consisted required keywords only
~PrimaryGroup ()
Int gcount () const
Return basic parameters of a random group.
Int pcount () const
char * ptype (int n) const
double pscal (int n) const
double pzero (int n) const
Int currgroup () const
double parm (int)
TYPE & rawparm (int)
void storeparm (const TYPE *source)
void copyparm (double *target) const
void copyparm (float *target) const
void moveparm (TYPE *target) const
int read ()
read, or write the next group
int write (FitsOutput &)
int write_priGrp_hdr (FitsOutput &fout, int simple, int bitpix, int naxis, long naxes[], long pcount, long gcount)
write the required keywords for PrimaryGroup
OFF_T set_next (OFF_T)
disable these functions, since they are inherited from PrimaryArray
int read (int)
Public Member Functions inherited from casacore::PrimaryArray< TYPE >
PrimaryArray (FitsInput &, FITSErrorHandler=FITSError::defaultHandler)
constructor from a FitsInput
PrimaryArray (FitsKeywordList &, FITSErrorHandler=FITSError::defaultHandler)
constructor from a FitsKeywordList
PrimaryArray (FITSErrorHandler=FITSError::defaultHandler)
constructor does not require a FitsKeywordList.
virtual ~PrimaryArray ()
destructor
double bscale () const
General access routines for a primary array.
double bzero () const
char * bunit () const
Bool isablank () const
Int blank () const
char * ctype (int n) const
double crpix (int n) const
double crota (int n) const
double crval (int n) const
double cdelt (int n) const
double datamax () const
double datamin () const
OFF_T nelements () const
double operator() (int, int, int, int, int) const
The overloaded operator functions `()' all return physical data, i.
double operator() (int, int, int, int) const
double operator() (int, int, int) const
double operator() (int, int) const
double operator() (int) const
TYPE & data (int, int, int, int, int)
The various `data()' functions allow one to access and set the raw data itself.
TYPE & data (int, int, int, int)
TYPE & data (int, int, int)
TYPE & data (int, int)
TYPE & data (int)
int store (const TYPE *source, FITS::FitsArrayOption=FITS::NoOpt)
The `store()', `move()' and `copy()' functions allow bulk data transfer between the internal FITS array and an external data storage area.
void copy (double *target, FITS::FitsArrayOption=FITS::NoOpt) const
void copy (float *target, FITS::FitsArrayOption=FITS::NoOpt) const
void move (TYPE *target, FITS::FitsArrayOption=FITS::NoOpt) const
int store (const TYPE *source, int npixels)
Use these versions if you are reading/writing "chunk by chunk.
void copy (double *target, int npixels) const
void copy (float *target, int npixels) const
void move (TYPE *target, int npixels) const
int write_priArr_hdr (FitsOutput &fout, int simple, int bitpix, int naxis, long naxes[], int extend)
Public Member Functions inherited from casacore::HeaderDataUnit
virtual ~HeaderDataUnit ()
Int dims () const
Int dim (int n) const
OFF_T fitsdatasize () const
FITS::ValueType datatype () const
Int fitsitemsize () const
Int localitemsize () const
FITS::HDUType hdutype () const
int err () const
int skip (uInt n)
skipping one or more HDU's
int skip ()
int write_hdr (FitsOutput &)
write the current header
ConstFitsKeywordList & kwlist ()
Operations on the HDU's keyword list.
Vector< String > kwlist_str (Bool length80=False)
return the header of the chdu as a vector of String.
void firstkw ()
void lastkw ()
const FitsKeyword * nextkw ()
const FitsKeyword * prevkw ()
const FitsKeyword * currkw ()
const FitsKeyword * kw (int n)
const FitsKeyword * kw (const FITS::ReservedName &n)
const FitsKeyword * nextkw (FITS::ReservedName &n)
const FitsKeyword * kw (FITS::ReservedName &n, int i)
const FitsKeyword * nextkw (FITS::ReservedName &n, int i)
const FitsKeyword * kw (const char *n)
const FitsKeyword * nextkw (const char *n)
void mk (FITS::ReservedName k, Bool v, const char *c=0)
void mk (FITS::ReservedName k, const char *v=0, const char *c=0)
void mk (FITS::ReservedName k, Int v, const char *c=0)
void mk (FITS::ReservedName k, double v, const char *c=0)
void mk (int n, FITS::ReservedName k, Bool v, const char *c=0)
void mk (int n, FITS::ReservedName k, const char *v, const char *c=0)
void mk (int n, FITS::ReservedName k, Int v, const char *c=0)
void mk (int n, FITS::ReservedName k, double v, const char *c=0)
void mk (const char *n, Bool v, const char *c=0)
void mk (const char *n, const char *v=0, const char *c=0)
void mk (const char *n, Int v, const char *c=0)
void mk (const char *n, float v, const char *c=0)
void mk (const char *n, double v, const char *c=0)
void mk (const char *n, Int r, Int i, const char *c=0)
void mk (const char *n, float r, float i, const char *c=0)
void mk (const char *n, double r, double i, const char *c=0)
void spaces (const char *n=0, const char *c=0)
void comment (const char *n=0, const char *c=0)
void history (const char *c=0)
Bool notnull (double x) const
Bool notnull (char *s) const
Bool notnull (Int l) const
int get_hdr (FITS::HDUType, FitsKeywordList &)
int read_data (char *, Int)
int write_data (FitsOutput &, char *, Int)
OFF_T read_all_data (char *)
int write_all_data (FitsOutput &, char *)
Protected Attributes
Int pcount_x
Int gcount_x
char ** ptype_x
double * pscal_x
double * pzero_x
TYPE * group_parm
Int current_group
Protected Attributes inherited from casacore::PrimaryArray< TYPE >
double bscale_x
double bzero_x
char * bunit_x
Bool isablank_x
Int blank_x
char ** ctype_x
double * crpix_x
double * crota_x
double * crval_x
double * cdelt_x
double datamax_x
double datamin_x
OFF_T totsize
int * factor
OFF_T alloc_elems
OFF_T beg_elem
OFF_T end_elem
TYPE * array
the allocated array
Protected Attributes inherited from casacore::HeaderDataUnit
FitsKeywordList & kwlist_
ConstFitsKeywordList constkwlist_
FitsInput * fin
FITSErrorHandler errfn
HDUErrs err_status
Int no_dims
Int * dimn
OFF_T fits_data_size
uInt fits_data_size; // size in bytes of total amount of data
FITS::ValueType data_type
Int fits_item_size
Int local_item_size
FITS::HDUType hdu_type
char pad_char
double double_null
char char_null
Int Int_null
Private Member Functions
void pg_assign ()
Additional Inherited Members
Public Types inherited from casacore::PrimaryArray< TYPE >
typedef TYPE ElementType
Public Types inherited from casacore::HeaderDataUnit
enum HDUErrs {
OK,
NOMEM,
MISSKEY,
BADBITPIX,
NOAXISN,
NOPCOUNT,
NOGCOUNT,
BADPCOUNT,
BADGCOUNT,
NOGROUPS,
BADNAXIS,
BADREC,
BADTYPE,
BADRULES,
BADSIZE,
BADOPER,
BADCONV,
BADIO
}
error handling and error codes that can be returned
Static Public Member Functions inherited from casacore::HeaderDataUnit
static Bool determine_type (FitsKeywordList &, FITS::HDUType &, FITS::ValueType &, FITSErrorHandler, HDUErrs &)
Determines the HDU type and the data type Parameterss: keyword list, hdu type, data type, error handler and error status.
static Bool compute_size (FitsKeywordList &, OFF_T &, Int &, FITS::HDUType &, FITS::ValueType &, FITSErrorHandler, HDUErrs &)
Compute the total size of the data associated with an HDU.
Protected Member Functions inherited from casacore::PrimaryArray< TYPE >
PrimaryArray (FitsInput &, FITS::HDUType, FITSErrorHandler errhandler=FITSError::defaultHandler)
construct from a FitsInput with given HDU type
PrimaryArray (FitsKeywordList &, FITS::HDUType, FITSErrorHandler errhandler=FITSError::defaultHandler)
construct from a FitsKeywordList with given HDU type
PrimaryArray (FITS::HDUType, FITSErrorHandler errhandler=FITSError::defaultHandler)
construct witout FitsKeywordList for given HDU type(for ImageExtension and PrimaryGroup)
int offset (int, int) const
compute a linear offset from array indicies
int offset (int, int, int) const
int offset (int, int, int, int) const
int offset (int, int, int, int, int) const
void pa_assign ()
Protected Member Functions inherited from casacore::HeaderDataUnit
HeaderDataUnit (FitsInput &, FITS::HDUType, FITSErrorHandler errhandler=FITSError::defaultHandler)
For input – ~ should delete the keyword list: kwflag = 1.
HeaderDataUnit (FitsKeywordList &, FITS::HDUType, FITSErrorHandler errhandler=FITSError::defaultHandler, FitsInput *=0)
For output – ~ should not delete keyword list: kwflag = 0 07/21/98 AKH Clarification: HeaderDataUnit has a copy of the FitsKeywordList, and should delete it.
HeaderDataUnit (FITS::HDUType, FITSErrorHandler errhandler=FITSError::defaultHandler, FitsInput *=0)
constructor for objects that write only required keyword to fits file.
bool init_data_unit (FITS::HDUType t)
for write required keywords only to use.
void posEnd ()
void errmsg (HDUErrs, const char *)
char * assign (FITS::ReservedName)
char * assign (FITS::ReservedName, int)
double asgdbl (FITS::ReservedName, double)
double asgdbl (FITS::ReservedName, int, double)
Detailed Description
template<class TYPE>
class casacore::PrimaryGroup< TYPE >
Random Group datastructure.
Synopsis
A Random Group Structure is represented by the following:
struct GroupData {
<Type> group_parms [PCOUNT];
<Type> data_array [NAXIS2][NAXIS3]...[NAXISN];
} group_data[GCOUNT];
Template Type Argument Requirements
typedef PrimaryGroup<unsigned char> BytePrimaryGroup;
typedef PrimaryGroup<short> ShortPrimaryGroup;
typedef PrimaryGroup<FitsLong> LongPrimaryGroup;
typedef PrimaryGroup<float> FloatPrimaryGroup;
typedef PrimaryGroup<double> DoublePrimaryGroup;
Warning: Please note that the NOST has deprecated the Random Group datastructure, it has been replaced by the much more powerfull BINTABLE extension;
Definition at line 594 of file hdu.h.
Constructor & Destructor Documentation
template<class TYPE> casacore::PrimaryGroup< TYPE >::PrimaryGroup (FitsInput & , FITSErrorHandler errhandler = FITSError::defaultHandler)
template<class TYPE> casacore::PrimaryGroup< TYPE >::PrimaryGroup (FitsKeywordList & , FITSErrorHandler errhandler = FITSError::defaultHandler)
template<class TYPE> casacore::PrimaryGroup< TYPE >::PrimaryGroup (FITSErrorHandler errhandler = FITSError::defaultHandler)
constructor for header consisted required keywords only
template<class TYPE> casacore::PrimaryGroup< TYPE >::~PrimaryGroup ()
Member Function Documentation
template<class TYPE> void casacore::PrimaryGroup< TYPE >::copyparm (double * target) const
template<class TYPE> void casacore::PrimaryGroup< TYPE >::copyparm (float * target) const
template<class TYPE> Int casacore::PrimaryGroup< TYPE >::currgroup () const inline
Definition at line 614 of file hdu.h.
template<class TYPE> Int casacore::PrimaryGroup< TYPE >::gcount () const inline
Return basic parameters of a random group.
Definition at line 607 of file hdu.h.
Referenced by casacore::MSPrimaryGroupHolder::gcount().
template<class TYPE> void casacore::PrimaryGroup< TYPE >::moveparm (TYPE * target) const
template<class TYPE> double casacore::PrimaryGroup< TYPE >::parm (int)
Referenced by casacore::MSPrimaryGroupHolder::parm().
template<class TYPE> Int casacore::PrimaryGroup< TYPE >::pcount () const inline
Definition at line 608 of file hdu.h.
Referenced by casacore::MSPrimaryGroupHolder::pcount().
template<class TYPE> void casacore::PrimaryGroup< TYPE >::pg_assign () private
template<class TYPE> double casacore::PrimaryGroup< TYPE >::pscal (int n) const inline
Definition at line 610 of file hdu.h.
template<class TYPE> char* casacore::PrimaryGroup< TYPE >::ptype (int n) const inline
Definition at line 609 of file hdu.h.
Referenced by casacore::MSPrimaryGroupHolder::ptype().
template<class TYPE> double casacore::PrimaryGroup< TYPE >::pzero (int n) const inline
Definition at line 611 of file hdu.h.
template<class TYPE> TYPE& casacore::PrimaryGroup< TYPE >::rawparm (int)
template<class TYPE> int casacore::PrimaryGroup< TYPE >::read () virtual
read, or write the next group
Reimplemented from casacore::PrimaryArray< TYPE >.
Referenced by casacore::MSPrimaryGroupHolder::read().
template<class TYPE> int casacore::PrimaryGroup< TYPE >::read (int) inline virtual
Reimplemented from casacore::PrimaryArray< TYPE >.
Definition at line 639 of file hdu.h.
template<class TYPE> OFF_T casacore::PrimaryGroup< TYPE >::set_next (OFF_T) inline virtual
disable these functions, since they are inherited from PrimaryArray
Reimplemented from casacore::PrimaryArray< TYPE >.
Definition at line 638 of file hdu.h.
template<class TYPE> void casacore::PrimaryGroup< TYPE >::storeparm (const TYPE * source)
template<class TYPE> int casacore::PrimaryGroup< TYPE >::write (FitsOutput &) virtual
Reimplemented from casacore::PrimaryArray< TYPE >.
template<class TYPE> int casacore::PrimaryGroup< TYPE >::write_priGrp_hdr (FitsOutput & fout, int simple, int bitpix, int naxis, long naxes[], long pcount, long gcount)
write the required keywords for PrimaryGroup
Member Data Documentation
template<class TYPE> Int casacore::PrimaryGroup< TYPE >::current_group protected
Definition at line 649 of file hdu.h.
Referenced by casacore::PrimaryGroup< Short >::currgroup().
template<class TYPE> Int casacore::PrimaryGroup< TYPE >::gcount_x protected
Definition at line 644 of file hdu.h.
Referenced by casacore::PrimaryGroup< Short >::gcount().
template<class TYPE> TYPE* casacore::PrimaryGroup< TYPE >::group_parm protected
Definition at line 648 of file hdu.h.
template<class TYPE> Int casacore::PrimaryGroup< TYPE >::pcount_x protected
Definition at line 643 of file hdu.h.
Referenced by casacore::PrimaryGroup< Short >::pcount().
template<class TYPE> double* casacore::PrimaryGroup< TYPE >::pscal_x protected
Definition at line 646 of file hdu.h.
Referenced by casacore::PrimaryGroup< Short >::pscal().
template<class TYPE> char** casacore::PrimaryGroup< TYPE >::ptype_x protected
Definition at line 645 of file hdu.h.
Referenced by casacore::PrimaryGroup< Short >::ptype().
template<class TYPE> double* casacore::PrimaryGroup< TYPE >::pzero_x protected
Definition at line 647 of file hdu.h.
Referenced by casacore::PrimaryGroup< Short >::pzero().
The documentation for this class was generated from the following file:
fits/FITS/hdu.h