casacore: casacore::DataManager Class Reference
casacore::DataManager Class Reference abstract
DataMan_module_internal_classes
Abstract base class for a data manager.
#include <DataManager.h>
Public Member Functions
DataManager ()
Default constructor.
virtual ~DataManager ()
virtual DataManager * clone () const =0
Make a clone of the derived object.
virtual String dataManagerName () const
Return the name of the data manager.
virtual String dataManagerType () const =0
Return the type name of the data manager (in fact its class name).
void dataManagerInfo (Record &info) const
Add SEQNR and SPEC (the DataManagerSpec subrecord) to the info.
virtual Record dataManagerSpec () const
Return a record containing data manager specifications.
virtual Record getProperties () const
Get data manager properties that can be modified.
virtual void setProperties (const Record &spec)
Modify data manager properties given in record fields.
virtual Bool isStorageManager () const
Is the data manager a storage manager? The default is yes.
virtual Bool canReallocateColumns () const
Tell if the data manager wants to reallocate the data manager column objects.
virtual DataManagerColumn * reallocateColumn (DataManagerColumn *column)
Reallocate the column object if it is part of this data manager.
uInt sequenceNr () const
Get the (unique) sequence nr of this data manager.
uInt ncolumn () const
Get the nr of columns in this data manager (can be zero).
Bool asBigEndian () const
Have the data to be stored in big or little endian canonical format?
const TSMOption & tsmOption () const
Get the TSM option.
MultiFileBase * multiFile ()
Get the MultiFile pointer (can be 0).
String keywordName (const String &keyword) const
Compose a keyword name from the given keyword appended with the sequence number (e.g.
String fileName () const
Compose a unique filename from the table name and sequence number.
ByteIO::OpenOption fileOption () const
Get the AipsIO option of the underlying file.
virtual Bool isRegular () const
Is this a regular storage manager? It is regular if it allows addition of rows and writing data in them.
Table & table () const
Get the table this object is associated with.
virtual void reopenRW ()
Reopen the data manager for read/write access.
virtual Bool canAddRow () const
Does the data manager allow to add rows? (default no)
virtual Bool canRemoveRow () const
Does the data manager allow to delete rows? (default no)
virtual Bool canAddColumn () const
Does the data manager allow to add columns? (default no)
virtual Bool canRemoveColumn () const
Does the data manager allow to delete columns? (default no)
virtual Bool canRenameColumn () const
Does the data manager allow to rename columns? (default yes)
virtual void setMaximumCacheSize (uInt nMiB)
Set the maximum cache size (in bytes) to be used by a storage manager.
virtual void showCacheStatistics (std::ostream &) const
Show the data manager's IO statistics.
DataManagerColumn * createScalarColumn (const String &columnName, int dataType, const String &dataTypeId)
Create a column in the data manager on behalf of a table column.
DataManagerColumn * createDirArrColumn (const String &columnName, int dataType, const String &dataTypeId)
Create a direct array column.
DataManagerColumn * createIndArrColumn (const String &columnName, int dataType, const String &dataTypeId)
Create an indirect array column.
virtual void deleteManager ()=0
The data manager will be deleted (because all its columns are requested to be deleted).
DataManager * getClone () const
Has the object already been cloned?
void setClone (DataManager *clone) const
Set the pointer to the clone.
Static Public Member Functions
static void registerCtor (const String &type, DataManagerCtor func)
Register a mapping of a data manager type to its static construction function.
static DataManagerCtor getCtor (const String &dataManagerType)
Get the "constructor" of a data manager (thread-safe).
static Bool isRegistered (const String &dataManagerType)
Test if a data manager is registered (thread-safe).
static DataManager * unknownDataManager (const String &dataManagerType, const Record &spec)
Serve as default function for theirRegisterMap, which catches all unknown data manager types.
Static Public Attributes
static rownr_t MAXROWNR32
Define the highest row number that can be represented as signed 32-bit.
Protected Member Functions
void decrementNcolumn ()
Decrement number of columns (in case a column is deleted).
void setEndian (Bool bigEndian)
Tell the data manager if big or little endian format is needed.
void setTsmOption (const TSMOption &tsmOption)
Tell the data manager which TSM option to use.
void setMultiFile (MultiFileBase *mfile)
Tell the data manager that MultiFile can be used.
virtual Bool hasMultiFileSupport () const
Does the data manager support use of MultiFile? A derived class has to return True if it can use the MultiFile.
void throwDataTypeOther (const String &columnName, int dataType) const
Throw an exception in case data type is TpOther, because the storage managers (and maybe other data managers) do not support such columns.
Private Member Functions
DataManager (const DataManager &)
The copy constructor cannot be used for this base class.
DataManager & operator= (const DataManager &)
Assignment cannot be used for this base class.
virtual DataManagerColumn * makeScalarColumn (const String &columnName, int dataType, const String &dataTypeId)=0
Create a column in the data manager on behalf of a table column.
virtual DataManagerColumn * makeDirArrColumn (const String &columnName, int dataType, const String &dataTypeId)=0
Create a direct array column.
virtual DataManagerColumn * makeIndArrColumn (const String &columnName, int dataType, const String &dataTypeId)=0
Create an indirect array column.
void checkDataType (const DataManagerColumn *colPtr, const String &columnName, int dataType, const String &dataTypeId) const
Check if the data type of the created data manager column is correct.
virtual void addRow64 (rownr_t nrrow)
Add rows to all columns.
virtual void removeRow64 (rownr_t rownr)
Delete a row from all columns.
virtual void addColumn (DataManagerColumn *)
Add a column.
virtual void removeColumn (DataManagerColumn *)
Delete a column.
void setSeqnr (uInt nr)
Set the sequence number of this data manager.
void linkToTable (Table &tab)
Link the data manager to the Table object.
virtual Bool flush (AipsIO &ios, Bool fsync)=0
Flush and optionally fsync the data.
virtual void create64 (rownr_t nrrow)
Let the data manager initialize itself for a new table.
virtual rownr_t open64 (rownr_t nrrow, AipsIO &ios)
Let the data manager initialize itself for an existing table.
virtual rownr_t resync64 (rownr_t nrrow)
Resync the data by rereading cached data from the file.
virtual void prepare ()
Let the data manager initialize itself further.
virtual void addRow (uInt nrrow)
Backward compatibility function using uInt instead of rownr_t.
virtual void removeRow (uInt rownr)
virtual void create (uInt nrrow)
virtual void open (uInt nrrow, AipsIO &ios)
virtual uInt open1 (uInt nrrow, AipsIO &ios)
virtual void resync (uInt nrrow)
virtual uInt resync1 (uInt nrrow)
Static Private Member Functions
static std::map< String,
DataManagerCtor > initRegisterMap ()
Register the main data managers.
Private Attributes
uInt nrcol_p
uInt seqnr_p
Bool asBigEndian_p
TSMOption tsmOption_p
MultiFileBase * multiFile_p
Table * table_p
DataManager * clone_p
Static Private Attributes
static std::map< String,
DataManagerCtor > theirRegisterMap
Declare the mapping of the data manager type name to a static "makeObject" function.
static std::recursive_mutex theirMutex
Friends
class SetupNewTable
class ColumnSet
Detailed Description
Abstract base class for a data manager.
Intended use:
Internal
Review Status
Reviewed By:
Gareth Hunt
Date Reviewed:
94Nov17
Synopsis
DataManager is the abstract base class for all kind of table data managers. There are currently 2 classes of data managers:
Storage managers handling the storage of data. These classes have to be derived from DataManager. StManAipsIO is an example of a storage manager.
Virtual column engines handling the on-the-fly calculation of data, which are not stored as such. The base class for these is VirtualColumnEngine (which is derived from DataManager), from which all virtual columns engine must be derived from.
DataManager contains some common data and defines several virtual functions, which usually have to be implemented in the derived classes. It also contains some helper functions for the derived classes (like fileName().
The actual handling of a column by the data manager is defined in the abstract base class DataManagerColumn. Each data manager must have an associated class (derived from DataManagerColumn) to handle the columns.
There is a protocol defined how a data manager is created and initialized. For a new table it is:
The user creates data managers and binds them to columns. For example:
SetupNewTable newtab("name.data", Table::New);  // set up new table
StManAipsIO stman;                       // define storage manager
newtab.bindColumn ("column1", stman);    // bind column to st.man.
newtab.bindColumn ("column2", stman);    // bind column to st.man.
Table tab(newtab);                       // actually create table
When the given data manager object is used for the first time in a bind function, a copy of the object is made using the clone function. Thus in the above example column1 and column2 share the same data manager; only at the first bind the stman object is cloned. Columns not explicitly bound to a data manager get implicitly bound to the default data manager (as defined in the column description) by the Table constructor (as used in line 5).
After binding the unbound columns, the PlainTable constructor sets up the data managers. For each column it asks the data manager to construct a DataManagerColumn object (in fact, an object of a class derived from DataManagerColumn). This is done by the functions createScalarColumn, createIndArrColumn and createDirArrColumn. For each data manager the create function is called. This allows them to initialize themselves and/or to call an initialization function in their column objects. This is, for instance, used by the storage managers to create files. Thereafter the prepare function is called to allow the data managers to do further initialization possibly requiring information from other columns.
When the table gets written (by the PlainTable destructor), the flush function is called for each data manager. This allows the data manager or their column objects to write or flush their data. The table system takes care of storing the information required to reconstruct the data managers. It uses the function dataManagerType to store the (unique) type name of the data manager class.
Finally each data manager object gets deleted. Their destructors must delete their column objects (if any and if needed).
For an existing table the procedure is slightly different:
The statement
Table tab("name.data"); will create a table object for an existing table. This has the effect that the given table file will be read to reconstruct the Table object and the data managers.
The stored data manager class names are used to reconstruct the data managers. This uses the static registration map, which maps the class name to a static class constructor function (usually called makeObject). This requires that the type name and constructor for each possible data manager are registered before the table is opened. The DataManager function registerMainCtor (implemented in DataManager.cc) is called before a table is opened, so registration of data managers should, in principle, be done there.
However, for unknown data managers it is tried to load a shared library whose name is the lowercase version of the data manager without a possible template argument (e.g. bitflagsengine for data manager BitFlagsEngine<Int>). It can be preceeded by lib or libcasa_ and followed by.so or.dylib. The shared library has to have a function with a name like register_bitflagsengine that must register the data manager(s). The function must be declared as extern "C", otherwise its name gets mangled.
Each table column is bound to the correct data manager. The sequence number stored in the table file is used for that purpose.
The DataManager createXXXColumn functions are called for each table column to let the data manager construct a data manager column object.
For each data manager the open function is called to allow it and its column objects to read back the information stored in the flush function. Thereafter the prepare function is called for each data manager to allow it to initialize some variables. The reason that open and prepare are separated is that in order to initialize variables it may be required to use other columns. So it may be needed that all columns are read back before they get initialized.
Similar to a new table the flush functions gets called when the table gets written. Destruction is also the same as sketched for new tables.
Motivation
An abstract base class is needed to support data managers and virtual column engines in the table system in a transparant way.
To Do
Handle unregistered data managers in a better way. Instead of throwing an exception a subprocess could be started which represents the data manager.
Definition at line 218 of file DataManager.h.
Constructor & Destructor Documentation
casacore::DataManager::DataManager ()
Default constructor.
virtual casacore::DataManager::~DataManager () virtual
casacore::DataManager::DataManager (const DataManager &) private
The copy constructor cannot be used for this base class.
The clone function should be used instead. The private declaration of this constructor makes it unusable.
Member Function Documentation
virtual void casacore::DataManager::addColumn (DataManagerColumn *) private virtual
Add a column.
The default implementation throws a "not possible" exception.
Reimplemented in casacore::ForwardColumnEngine, dyscostman::DyscoStMan, casacore::SSMBase, casacore::ISMBase, casacore::DerivedMSCal, and casacore::MSMBase.
virtual void casacore::DataManager::addRow (uInt nrrow) private virtual
Backward compatibility function using uInt instead of rownr_t.
The default implementations throw an exception.
Reimplemented in dyscostman::DyscoStMan.
virtual void casacore::DataManager::addRow64 (rownr_t nrrow) private virtual
Add rows to all columns.
The default implementation calls the uInt version.
Reimplemented in casacore::ForwardColumnEngine, casacore::TiledDataStMan, casacore::SSMBase, casacore::BaseMappedArrayEngine< VirtualType, StoredType >, casacore::BaseMappedArrayEngine< Complex, Int >, casacore::BaseMappedArrayEngine< Float, Short >, casacore::BaseMappedArrayEngine< Bool, StoredType >, casacore::ISMBase, casacore::TiledShapeStMan, casacore::TiledCellStMan, casacore::TiledColumnStMan, casacore::MSMBase, casacore::VirtualColumnEngine, and casacore::Adios2StMan.
Bool casacore::DataManager::asBigEndian () const inline
Have the data to be stored in big or little endian canonical format?
Definition at line 287 of file DataManager.h.
References asBigEndian_p.
virtual Bool casacore::DataManager::canAddColumn () const virtual
Does the data manager allow to add columns? (default no)
Reimplemented in casacore::ForwardColumnEngine, casacore::SSMBase, casacore::ISMBase, dyscostman::DyscoStMan, casacore::DerivedMSCal, and casacore::MSMBase.
virtual Bool casacore::DataManager::canAddRow () const virtual
Does the data manager allow to add rows? (default no)
Reimplemented in casacore::ForwardColumnEngine, casacore::TiledStMan, casacore::SSMBase, casacore::ISMBase, dyscostman::DyscoStMan, casacore::VirtualColumnEngine, and casacore::MSMBase.
virtual Bool casacore::DataManager::canReallocateColumns () const virtual
Tell if the data manager wants to reallocate the data manager column objects.
This is used by the tiling storage manager. By default it returns False.
Reimplemented in casacore::TiledStMan, and casacore::MSMBase.
virtual Bool casacore::DataManager::canRemoveColumn () const virtual
Does the data manager allow to delete columns? (default no)
Reimplemented in casacore::ForwardColumnEngine, casacore::SSMBase, dyscostman::DyscoStMan, casacore::ISMBase, casacore::DerivedMSCal, and casacore::MSMBase.
virtual Bool casacore::DataManager::canRemoveRow () const virtual
Does the data manager allow to delete rows? (default no)
Reimplemented in casacore::ForwardColumnEngine, casacore::SSMBase, casacore::ISMBase, dyscostman::DyscoStMan, casacore::VirtualColumnEngine, and casacore::MSMBase.
virtual Bool casacore::DataManager::canRenameColumn () const virtual
Does the data manager allow to rename columns? (default yes)
void casacore::DataManager::checkDataType (const DataManagerColumn * colPtr, const String & columnName, int dataType, const String & dataTypeId) const private
Check if the data type of the created data manager column is correct.
virtual DataManager* casacore::DataManager::clone () const pure virtual
Make a clone of the derived object.
Implemented in casacore::RetypedArrayEngine< VirtualType, StoredType >, casacore::CompressComplexSD, casacore::ForwardColumnEngine, casacore::TiledDataStMan, casacore::ForwardColumnIndexedRowEngine, casacore::BitFlagsEngine< StoredType >, casacore::ScaledComplexData< VirtualType, StoredType >, casacore::ScaledArrayEngine< VirtualType, StoredType >, casacore::StManAipsIO, casacore::TiledShapeStMan, casacore::CompressComplex, casacore::CompressFloat, casacore::TiledCellStMan, casacore::TiledColumnStMan, casacore::SSMBase, casacore::MappedArrayEngine< VirtualType, StoredType >, dyscostman::DyscoStMan, casacore::DerivedMSCal, casacore::ISMBase, casacore::VirtualTaQLColumn, casacore::TiledFileHelper, casacore::MSMBase, and casacore::Adios2StMan.
Referenced by setClone().
virtual void casacore::DataManager::create (uInt nrrow) private virtual
Reimplemented in dyscostman::DyscoStMan.
virtual void casacore::DataManager::create64 (rownr_t nrrow) private virtual
Let the data manager initialize itself for a new table.
The default implementation calls the uInt version.
Reimplemented in casacore::RetypedArrayEngine< VirtualType, StoredType >, casacore::ForwardColumnEngine, casacore::CompressComplexSD, casacore::TiledDataStMan, casacore::ForwardColumnIndexedRowEngine, casacore::BaseMappedArrayEngine< VirtualType, StoredType >, casacore::BaseMappedArrayEngine< Complex, Int >, casacore::BaseMappedArrayEngine< Float, Short >, casacore::BaseMappedArrayEngine< Bool, StoredType >, casacore::SSMBase, casacore::TiledShapeStMan, casacore::BitFlagsEngine< StoredType >, casacore::ISMBase, casacore::StManAipsIO, casacore::TiledCellStMan, casacore::ScaledComplexData< VirtualType, StoredType >, casacore::TiledColumnStMan, casacore::ScaledArrayEngine< VirtualType, StoredType >, casacore::CompressComplex, casacore::CompressFloat, casacore::VirtualColumnEngine, casacore::VirtualTaQLColumn, casacore::MSMBase, casacore::TiledFileHelper, and casacore::Adios2StMan.
DataManagerColumn* casacore::DataManager::createDirArrColumn (const String & columnName, int dataType, const String & dataTypeId)
Create a direct array column.
DataManagerColumn* casacore::DataManager::createIndArrColumn (const String & columnName, int dataType, const String & dataTypeId)
Create an indirect array column.
DataManagerColumn* casacore::DataManager::createScalarColumn (const String & columnName, int dataType, const String & dataTypeId)
Create a column in the data manager on behalf of a table column.
It calls makeXColumn and checks the data type.
Create a scalar column. The dataTypeId argument is gives the id (i.e. name) of the data type of the column. It is only used for virtual columns of a non-standard data type to be able to check if the correctness of the column data type.
Storage managers only handle standard data types and can readily ignore this argument.
void casacore::DataManager::dataManagerInfo (Record & info) const
Add SEQNR and SPEC (the DataManagerSpec subrecord) to the info.
virtual String casacore::DataManager::dataManagerName () const virtual
Return the name of the data manager.
This is the name of this instantiation of the data manager, thus not its type name. By default it returns an empty string.
Reimplemented in casacore::RetypedArrayEngine< VirtualType, StoredType >, casacore::ForwardColumnEngine, casacore::BitFlagsEngine< StoredType >, casacore::ScaledArrayEngine< VirtualType, StoredType >, casacore::SSMBase, casacore::CompressComplex, casacore::CompressFloat, dyscostman::DyscoStMan, casacore::MappedArrayEngine< VirtualType, StoredType >, casacore::TiledStMan, casacore::ISMBase, casacore::MSMBase, and casacore::Adios2StMan.
Referenced by casacore::RODataManAccessor::dataManagerName().
virtual Record casacore::DataManager::dataManagerSpec () const virtual
Return a record containing data manager specifications.
The default implementation returns an empty record.
Reimplemented in casacore::RetypedArrayEngine< VirtualType, StoredType >, casacore::ForwardColumnEngine, casacore::ForwardColumnIndexedRowEngine, casacore::BitFlagsEngine< StoredType >, casacore::TiledShapeStMan, casacore::ScaledComplexData< VirtualType, StoredType >, casacore::ScaledArrayEngine< VirtualType, StoredType >, casacore::SSMBase, casacore::CompressComplex, casacore::CompressFloat, dyscostman::DyscoStMan, casacore::DerivedMSCal, casacore::MappedArrayEngine< VirtualType, StoredType >, casacore::TiledStMan, casacore::ISMBase, casacore::VirtualTaQLColumn, and casacore::Adios2StMan.
virtual String casacore::DataManager::dataManagerType () const pure virtual
Return the type name of the data manager (in fact its class name).
It has to be a unique name, thus if the class is templated the template parameter has to be part of the name. This is used by the open/flush mechanism to be able to reconstruct the correct data manager.
Implemented in casacore::RetypedArrayEngine< VirtualType, StoredType >, casacore::CompressComplexSD, casacore::ForwardColumnEngine, casacore::TiledDataStMan, casacore::ForwardColumnIndexedRowEngine, casacore::VACEngine< T >, casacore::VSCEngine< T >, casacore::StManAipsIO, casacore::BitFlagsEngine< StoredType >, casacore::TiledShapeStMan, casacore::ScaledComplexData< VirtualType, StoredType >, casacore::ScaledArrayEngine< VirtualType, StoredType >, casacore::TiledCellStMan, casacore::TiledColumnStMan, casacore::SSMBase, casacore::CompressComplex, casacore::CompressFloat, dyscostman::DyscoStMan, casacore::DerivedMSCal, casacore::MappedArrayEngine< VirtualType, StoredType >, casacore::VirtualTaQLColumn, casacore::ISMBase, casacore::MSMBase, casacore::TiledFileHelper, and casacore::Adios2StMan.
Referenced by casacore::RODataManAccessor::dataManagerType().
void casacore::DataManager::decrementNcolumn () inline protected
Decrement number of columns (in case a column is deleted).
Definition at line 377 of file DataManager.h.
References nrcol_p.
virtual void casacore::DataManager::deleteManager () pure virtual
The data manager will be deleted (because all its columns are requested to be deleted).
So clean up the things needed (e.g. delete files).
Implemented in dyscostman::DyscoStMan, casacore::SSMBase, casacore::TiledStMan, casacore::ISMBase, casacore::StManAipsIO, casacore::VirtualColumnEngine, casacore::MSMBase, and casacore::Adios2StMan.
String casacore::DataManager::fileName () const
Compose a unique filename from the table name and sequence number.
Referenced by casacore::Adios2StMan::impl::fileName().
ByteIO::OpenOption casacore::DataManager::fileOption () const
Get the AipsIO option of the underlying file.
virtual Bool casacore::DataManager::flush (AipsIO & ios, Bool fsync) private pure virtual
Flush and optionally fsync the data.
The AipsIO stream represents the main table file and can be used by virtual column engines to store SMALL amounts of data. It returns a True status if it had to flush (i.e. if data have changed).
Implemented in casacore::TiledDataStMan, dyscostman::DyscoStMan, casacore::SSMBase, casacore::TiledShapeStMan, casacore::ISMBase, casacore::StManAipsIO, casacore::TiledCellStMan, casacore::TiledColumnStMan, casacore::VirtualColumnEngine, casacore::MSMBase, casacore::TiledFileHelper, and casacore::Adios2StMan.
DataManager* casacore::DataManager::getClone () const inline
Has the object already been cloned?
Definition at line 526 of file DataManager.h.
References clone_p.
static DataManagerCtor casacore::DataManager::getCtor (const String & dataManagerType) static
Get the "constructor" of a data manager (thread-safe).
virtual Record casacore::DataManager::getProperties () const virtual
Get data manager properties that can be modified.
It is a subset of the data manager specification. The default implementation returns an empty record.
Reimplemented in casacore::BitFlagsEngine< StoredType >, casacore::SSMBase, casacore::TiledStMan, and casacore::ISMBase.
virtual Bool casacore::DataManager::hasMultiFileSupport () const protected virtual
Does the data manager support use of MultiFile? A derived class has to return True if it can use the MultiFile.
The default implementation returns False.
Reimplemented in casacore::SSMBase, casacore::ISMBase, and casacore::TiledStMan.
static std::map<String,DataManagerCtor> casacore::DataManager::initRegisterMap () static private
Register the main data managers.
static Bool casacore::DataManager::isRegistered (const String & dataManagerType) static
Test if a data manager is registered (thread-safe).
virtual Bool casacore::DataManager::isRegular () const virtual
Is this a regular storage manager? It is regular if it allows addition of rows and writing data in them.
The default implementation returns True.
virtual Bool casacore::DataManager::isStorageManager () const virtual
Is the data manager a storage manager? The default is yes.
Reimplemented in casacore::VirtualColumnEngine.
String casacore::DataManager::keywordName (const String & keyword) const
Compose a keyword name from the given keyword appended with the sequence number (e.g.
key_0). This makes the keyword name unique if multiple data managers are used with the same type.
void casacore::DataManager::linkToTable (Table & tab) private
Link the data manager to the Table object.
virtual DataManagerColumn* casacore::DataManager::makeDirArrColumn (const String & columnName, int dataType, const String & dataTypeId) private pure virtual
Create a direct array column.
Implemented in casacore::SSMBase, dyscostman::DyscoStMan, casacore::TiledStMan, casacore::VACEngine< T >, casacore::ISMBase, casacore::StManAipsIO, casacore::VirtualColumnEngine, casacore::MSMBase, and casacore::Adios2StMan.
virtual DataManagerColumn* casacore::DataManager::makeIndArrColumn (const String & columnName, int dataType, const String & dataTypeId) private pure virtual
Create an indirect array column.
Implemented in casacore::ForwardColumnEngine, casacore::SSMBase, dyscostman::DyscoStMan, casacore::ForwardColumnIndexedRowEngine, casacore::TiledStMan, casacore::VACEngine< T >, casacore::ISMBase, casacore::BaseMappedArrayEngine< VirtualType, StoredType >, casacore::BaseMappedArrayEngine< Complex, Int >, casacore::BaseMappedArrayEngine< Float, Short >, casacore::BaseMappedArrayEngine< Bool, StoredType >, casacore::StManAipsIO, casacore::VirtualColumnEngine, casacore::DerivedMSCal, casacore::VirtualTaQLColumn, casacore::MSMBase, and casacore::Adios2StMan.
virtual DataManagerColumn* casacore::DataManager::makeScalarColumn (const String & columnName, int dataType, const String & dataTypeId) private pure virtual
Create a column in the data manager on behalf of a table column.
Create a scalar column.
Implemented in casacore::ForwardColumnEngine, casacore::SSMBase, dyscostman::DyscoStMan, casacore::ForwardColumnIndexedRowEngine, casacore::TiledStMan, casacore::VSCEngine< T >, casacore::ISMBase, casacore::StManAipsIO, casacore::VirtualColumnEngine, casacore::DerivedMSCal, casacore::VirtualTaQLColumn, casacore::MSMBase, and casacore::Adios2StMan.
MultiFileBase* casacore::DataManager::multiFile () inline
Get the MultiFile pointer (can be 0).
Definition at line 295 of file DataManager.h.
References multiFile_p.
uInt casacore::DataManager::ncolumn () const inline
Get the nr of columns in this data manager (can be zero).
Definition at line 283 of file DataManager.h.
References nrcol_p.
Referenced by casacore::Adios2StMan::impl::ncolumn().
virtual void casacore::DataManager::open (uInt nrrow, AipsIO & ios) private virtual
Reimplemented in dyscostman::DyscoStMan.
virtual uInt casacore::DataManager::open1 (uInt nrrow, AipsIO & ios) private virtual
virtual rownr_t casacore::DataManager::open64 (rownr_t nrrow, AipsIO & ios) private virtual
Let the data manager initialize itself for an existing table.
The AipsIO stream represents the main table file and must be used by virtual column engines to retrieve the data stored in the flush function.
The data manager returns 0 or the nr of rows it thinks there are. This is particularly useful for data managers like LofarStMan whose data are written outside the table system, thus for which no rows have been added.
The default implementation calls the uInt version of open and open1.
Reimplemented in casacore::SSMBase, casacore::TiledStMan, casacore::ISMBase, casacore::StManAipsIO, casacore::VirtualColumnEngine, casacore::MSMBase, and casacore::Adios2StMan.
DataManager& casacore::DataManager::operator= (const DataManager &) private
Assignment cannot be used for this base class.
The private declaration of this operator makes it unusable.
virtual void casacore::DataManager::prepare () private virtual
Let the data manager initialize itself further.
Prepare is called after create/open has been called for all columns. In this way one can be sure that referenced columns are read back and partly initialized. The default implementation does nothing.
Reimplemented in casacore::RetypedArrayEngine< VirtualType, StoredType >, casacore::ForwardColumnEngine, dyscostman::DyscoStMan, casacore::ForwardColumnIndexedRowEngine, casacore::BaseMappedArrayEngine< VirtualType, StoredType >, casacore::BaseMappedArrayEngine< Complex, Int >, casacore::BaseMappedArrayEngine< Float, Short >, casacore::BaseMappedArrayEngine< Bool, StoredType >, casacore::BitFlagsEngine< StoredType >, casacore::ScaledComplexData< VirtualType, StoredType >, casacore::ScaledArrayEngine< VirtualType, StoredType >, casacore::CompressComplex, casacore::CompressFloat, casacore::VirtualColumnEngine, casacore::VirtualTaQLColumn, casacore::DerivedMSCal, and casacore::MSMBase.
virtual DataManagerColumn* casacore::DataManager::reallocateColumn (DataManagerColumn * column) virtual
Reallocate the column object if it is part of this data manager.
It returns a pointer to the new column object. This function is used by the tiling storage manager. By default it does nothing and returns the input pointer.
Reimplemented in casacore::TiledStMan, and casacore::MSMBase.
static void casacore::DataManager::registerCtor (const String & type, DataManagerCtor func) static
Register a mapping of a data manager type to its static construction function.
It is fully thread-safe.
virtual void casacore::DataManager::removeColumn (DataManagerColumn *) private virtual
Delete a column.
The default implementation throws a "not possible" exception.
Reimplemented in casacore::ForwardColumnEngine, dyscostman::DyscoStMan, casacore::SSMBase, casacore::ISMBase, casacore::DerivedMSCal, and casacore::MSMBase.
virtual void casacore::DataManager::removeRow (uInt rownr) private virtual
Reimplemented in dyscostman::DyscoStMan.
virtual void casacore::DataManager::removeRow64 (rownr_t rownr) private virtual
Delete a row from all columns.
The default implementation calls the uInt version.
Reimplemented in casacore::ForwardColumnEngine, casacore::SSMBase, casacore::ISMBase, casacore::MSMBase, and casacore::VirtualColumnEngine.
virtual void casacore::DataManager::reopenRW () virtual
Reopen the data manager for read/write access.
By default it is assumed that a reopen for read/write does not have to do anything.
Reimplemented in casacore::ForwardColumnEngine, dyscostman::DyscoStMan, casacore::ForwardColumnIndexedRowEngine, casacore::SSMBase, casacore::TiledStMan, casacore::ISMBase, casacore::StManAipsIO, casacore::CompressComplex, and casacore::CompressFloat.
virtual void casacore::DataManager::resync (uInt nrrow) private virtual
Reimplemented in dyscostman::DyscoStMan.
virtual uInt casacore::DataManager::resync1 (uInt nrrow) private virtual
virtual rownr_t casacore::DataManager::resync64 (rownr_t nrrow) private virtual
Resync the data by rereading cached data from the file.
This is called when a lock is acquired on the file and it appears that data in this data manager has been changed by another process.
The data manager returns 0 or the number of rows it thinks there are. This is particularly useful for data managers like LofarStMan whose data are written outside the table system, thus for which no rows have been added.
The default implementation calls the uInt version of resync and resync1.
Reimplemented in casacore::SSMBase, casacore::TiledStMan, casacore::ISMBase, casacore::StManAipsIO, casacore::VirtualColumnEngine, casacore::MSMBase, and casacore::Adios2StMan.
uInt casacore::DataManager::sequenceNr () const inline
Get the (unique) sequence nr of this data manager.
Definition at line 279 of file DataManager.h.
References seqnr_p.
Referenced by casacore::RODataManAccessor::dataManagerSeqNr().
void casacore::DataManager::setClone (DataManager * clone) const inline
Set the pointer to the clone.
Definition at line 530 of file DataManager.h.
References clone(), and clone_p.
void casacore::DataManager::setEndian (Bool bigEndian) inline protected
Tell the data manager if big or little endian format is needed.
Definition at line 381 of file DataManager.h.
References asBigEndian_p.
virtual void casacore::DataManager::setMaximumCacheSize (uInt nMiB) virtual
Set the maximum cache size (in bytes) to be used by a storage manager.
The default implementation does nothing.
Reimplemented in casacore::TiledStMan.
void casacore::DataManager::setMultiFile (MultiFileBase * mfile) protected
Tell the data manager that MultiFile can be used.
Because MultiFile cannot be used with mmapped files, it sets the TSMOption accordingly.
virtual void casacore::DataManager::setProperties (const Record & spec) virtual
Modify data manager properties given in record fields.
Only the properties as returned by getProperties are used, others are ignored. The default implementation does nothing.
Reimplemented in casacore::BitFlagsEngine< StoredType >, casacore::SSMBase, casacore::TiledStMan, and casacore::ISMBase.
void casacore::DataManager::setSeqnr (uInt nr) inline private
Set the sequence number of this data manager.
Definition at line 462 of file DataManager.h.
References seqnr_p.
void casacore::DataManager::setTsmOption (const TSMOption & tsmOption) protected
Tell the data manager which TSM option to use.
virtual void casacore::DataManager::showCacheStatistics (std::ostream &) const virtual
Show the data manager's IO statistics.
By default it does nothing.
Referenced by casacore::RODataManAccessor::showCacheStatistics().
Table& casacore::DataManager::table () const inline
Get the table this object is associated with.
Definition at line 316 of file DataManager.h.
References table_p.
void casacore::DataManager::throwDataTypeOther (const String & columnName, int dataType) const protected
Throw an exception in case data type is TpOther, because the storage managers (and maybe other data managers) do not support such columns.
const TSMOption& casacore::DataManager::tsmOption () const inline
Get the TSM option.
Definition at line 291 of file DataManager.h.
References tsmOption_p.
static DataManager* casacore::DataManager::unknownDataManager (const String & dataManagerType, const Record & spec) static
Serve as default function for theirRegisterMap, which catches all unknown data manager types.
Thrown Exceptions
TableUnknownDataManager
Friends And Related Function Documentation
friend class ColumnSet friend
Definition at line 221 of file DataManager.h.
friend class SetupNewTable friend
Definition at line 220 of file DataManager.h.
Member Data Documentation
Bool casacore::DataManager::asBigEndian_p private
Definition at line 406 of file DataManager.h.
Referenced by asBigEndian(), and setEndian().
DataManager* casacore::DataManager::clone_p mutable private
Definition at line 410 of file DataManager.h.
Referenced by getClone(), and setClone().
rownr_t casacore::DataManager::MAXROWNR32 static
Define the highest row number that can be represented as signed 32-bit.
In principle it is the maximum uInt number, but for test purposes it can be reset (to a lower number).
Definition at line 554 of file DataManager.h.
MultiFileBase* casacore::DataManager::multiFile_p private
Definition at line 408 of file DataManager.h.
Referenced by multiFile().
uInt casacore::DataManager::nrcol_p private
Definition at line 404 of file DataManager.h.
Referenced by decrementNcolumn(), and ncolumn().
uInt casacore::DataManager::seqnr_p private
Definition at line 405 of file DataManager.h.
Referenced by sequenceNr(), and setSeqnr().
Table* casacore::DataManager::table_p private
Definition at line 409 of file DataManager.h.
Referenced by table().
std::recursive_mutex casacore::DataManager::theirMutex static private
Definition at line 522 of file DataManager.h.
std::map<String,DataManagerCtor> casacore::DataManager::theirRegisterMap static private
Declare the mapping of the data manager type name to a static "makeObject" function.
Definition at line 521 of file DataManager.h.
TSMOption casacore::DataManager::tsmOption_p private
Definition at line 407 of file DataManager.h.
Referenced by tsmOption().
The documentation for this class was generated from the following file:
tables/DataMan/DataManager.h