casacore: casacore::SetupNewTable Class Reference
casacore::SetupNewTable Class Reference
tables package (libcasa_tables) » Tables_module
Create a new table - define shapes, data managers, etc.
#include <SetupNewTab.h>
Public Member Functions
SetupNewTable (const String &tableName, const String &tableDescName, Table::TableOption, const StorageOption &=StorageOption())
Create a new table using the table description with the given name.
SetupNewTable (const String &tableName, const TableDesc &, Table::TableOption, const StorageOption &=StorageOption())
Create a new table using the given table description.
SetupNewTable (const SetupNewTable &)
Copy constructor (reference semantics).
~SetupNewTable ()
SetupNewTable & operator= (const SetupNewTable &)
Assignment (reference semantics).
const String & name () const
Get the name of the table.
int option () const
Get the table create option.
const StorageOption & storageOption () const
Get the storage option.
Bool isMarkedForDelete () const
Test if the table is marked for delete.
const TableDesc & tableDesc () const
Get the table description.
void adjustHypercolumns (const std::map< String, String > &old2new, Bool keepUnknown)
Adjust the hypercolumn definitions.
void bindColumn (const String &columnName, const DataManager &dm)
Bind a column to the given data manager.
void bindColumn (const String &columnName, const String &otherColumn)
Bind a column to the given data manager of the other column.
void bindGroup (const String &columnGroup, const DataManager &dm, Bool rebind=False)
Bind a group of columns to the given data manager.
void bindAll (const DataManager &dm, Bool rebind=False)
Bind all columns to the given data manager.
void bindCreate (const Record &spec)
Create data managers and bind the columns using the specifications in the given record (which is obtained using Table::dataManagerInfo()).
void setShapeColumn (const String &columnName, const IPosition &shape)
Define the shape of fixed shaped arrays in a column.
Bool isUsed () const
Test if object is already in use.
Private Member Functions
ColumnSet * columnSetPtr ()
Get pointer to column set.
TableDesc * tableDescPtr ()
Get pointer to table description.
void setInUse ()
Set object to in use by a (Plain)Table object.
void handleUnbound ()
Make a data manager for all unbound columns.
Private Attributes
SetupNewTableRep * newTable_p
Actual object.
Friends
class PlainTable
class MemoryTable
Detailed Description
Create a new table - define shapes, data managers, etc.
Intended use:
Public interface
Review Status
Reviewed By:
bglenden
Date Reviewed:
12AUG94
Test programs:
None
Prerequisite
TableDesc and related classes like ArrayColumnDesc
DataManager
Table
Etymology
SetupNewTable is a class to setup a new table.
Synopsis
Constructing a new table is a two stage process. First a SetupNewTable object has to be created. Thereafter its columns have to be bound defining how they have to be stored or calculated. Columns have to be bound to a data manager (e.g. a storage manager or a virtual column engine).. Once the required columns are bound, the actual Table object can be created. At this stage, still unbound columns will be bound to the default data managers. The Table object can be used to write data, etc.
The construct options for SetupNewTable are defined in class Table. The possible options are:
New creates a new table file. The Table destructor will write the table into the file.
NewNoReplace as option New, but an exception will be thrown if the table file already exists.
Scratch creates a temporary table. It will be lost when the Table object gets destructed.
More information is provided in the Tables module documentation.
Example
Table makeIt(const TableDesc &td) {                            // 1
SetupNewTable maker("test.table", td, Table::New);       // 2
maker.setShapeColumn("SomeArray", IPosition(2,10,10));   // 3
maker.setShapeColumn("AnotherArray", IPosition(1,100));  // 4
StManAipsIO sm1;                                         // 5
StManKarma  sm2;                                         // 6
maker.bindAll(sm1);                                      // 7
maker.bindColumn("SomeCol", sm2);                        // 8
maker.bindColumn("AnotherCol", sm2);                     // 9
return Table(maker, 1000); // 1000 row table             // 10
}                                                              // 11
This code illustrates a simple function that creates a Table starting from a Table descriptor. I
Declare the function makeIt which, given a TableDesc, returns a table.
Create the SetupNewTable object "maker". We want the new table to be named "test.table", its rows columns and keywords come from the TableDesc "td", and this table is to be created unconditionally, that is, it will overwrite an existing table of the same name. Alternative options are given in the synopsis.
Give direct arrays declared in the table descriptor (but not necessarily given a shape) a defined shape; 10x10 for the first array, 100 long vector for the second. If all direct arrays do not have a shape, an error will occur when the table is actually constructed.
Declare two data (storage) managers. AipsIO keeps a whole column in memory, Karma does I/O to keep a subsection in memory at once. A powerful feature of Casacore tables is that different columns may be bound to different data managers, which have different properties.
Define the default data manager. AipsIO in this case. Note that this statement and statement 5 are actually not needed. When the Table constructor finds some unbound columns, it will construct the default data manager for them and bind them. A default data manager can be defined in the column description and defaults to AipsIO.
Override the default for some particular columns.
Create and return a 1000 row table. With the Karma storage manager the table size must be defined at construction since new rows can't be added or deleted. If AipsIO was the only storage manager, the size wouldn't need to be defined since rows can be added with AipsIO.
Motivation
In principle, SetupNewTab isn't necessary as what we are doing is logically just constructing a Table, so it could be done in the Table constructor. However such a process can be an involved one - binding multiple data managers and filling in the shapes of direct arrays - so separating the process makes it much clearer what is going on.
To Do
full implementation of tiling
Definition at line 346 of file SetupNewTab.h.
Constructor & Destructor Documentation
SetupNewTable() [1/3]
casacore::SetupNewTable::SetupNewTable (const String & tableName, const String & tableDescName, Table::TableOption , const StorageOption & = StorageOption())
Create a new table using the table description with the given name.
The description will be read from a file.
SetupNewTable() [2/3]
casacore::SetupNewTable::SetupNewTable (const String & tableName, const TableDesc & , Table::TableOption , const StorageOption & = StorageOption())
Create a new table using the given table description.
SetupNewTable() [3/3]
casacore::SetupNewTable::SetupNewTable (const SetupNewTable &)
Copy constructor (reference semantics).
~SetupNewTable()
casacore::SetupNewTable::~SetupNewTable ()
Member Function Documentation
adjustHypercolumns()
void casacore::SetupNewTable::adjustHypercolumns (const std::map< String, String > & old2new, Bool keepUnknown) inline
Adjust the hypercolumn definitions.
It renames and/or removes columns as necessary.
Definition at line 391 of file SetupNewTab.h.
References casacore::TableDesc::adjustHypercolumns(), newTable_p, and casacore::SetupNewTableRep::tableDescPtr().
bindAll()
void casacore::SetupNewTable::bindAll (const DataManager & dm, Bool rebind = False) inline
Bind all columns to the given data manager.
The flag rebind tells if the binding of an already bound column will be overwritten. It cannot be used anymore once the SetupNewTable object is used to construct a Table object.
Definition at line 424 of file SetupNewTab.h.
References casacore::SetupNewTableRep::bindAll(), and newTable_p.
bindColumn() [1/2]
void casacore::SetupNewTable::bindColumn (const String & columnName, const DataManager & dm) inline
Bind a column to the given data manager.
If already bound, the binding will be overwritten. It cannot be used anymore once the SetupNewTable object is used to construct a Table object.
Definition at line 399 of file SetupNewTab.h.
References casacore::SetupNewTableRep::bindColumn(), and newTable_p.
bindColumn() [2/2]
void casacore::SetupNewTable::bindColumn (const String & columnName, const String & otherColumn) inline
Bind a column to the given data manager of the other column.
If the other column is not bound, nothing will be done. If columnName is already bound, the binding will be overwritten. It cannot be used anymore once the SetupNewTableRep object is used to construct a Table object.
Definition at line 407 of file SetupNewTab.h.
References casacore::SetupNewTableRep::bindColumn(), and newTable_p.
bindCreate()
void casacore::SetupNewTable::bindCreate (const Record & spec) inline
Create data managers and bind the columns using the specifications in the given record (which is obtained using Table::dataManagerInfo()).
Definition at line 429 of file SetupNewTab.h.
References casacore::SetupNewTableRep::bindCreate(), and newTable_p.
bindGroup()
void casacore::SetupNewTable::bindGroup (const String & columnGroup, const DataManager & dm, Bool rebind = False) inline
Bind a group of columns to the given data manager.
The flag rebind tells if the binding of an already bound column will be overwritten. It cannot be used anymore once the SetupNewTable object is used to construct a Table object.
Definition at line 415 of file SetupNewTab.h.
References casacore::SetupNewTableRep::bindGroup(), and newTable_p.
columnSetPtr()
ColumnSet* casacore::SetupNewTable::columnSetPtr () inline private
Get pointer to column set.
This function is used by PlainTable.
Definition at line 455 of file SetupNewTab.h.
References casacore::SetupNewTableRep::columnSetPtr(), and newTable_p.
handleUnbound()
void casacore::SetupNewTable::handleUnbound () inline private
Make a data manager for all unbound columns.
Definition at line 469 of file SetupNewTab.h.
References casacore::SetupNewTableRep::handleUnbound(), and newTable_p.
isMarkedForDelete()
Bool casacore::SetupNewTable::isMarkedForDelete () const inline
Test if the table is marked for delete.
Definition at line 382 of file SetupNewTab.h.
References casacore::SetupNewTableRep::isMarkedForDelete(), and newTable_p.
isUsed()
Bool casacore::SetupNewTable::isUsed () const inline
Test if object is already in use.
Definition at line 446 of file SetupNewTab.h.
References casacore::SetupNewTableRep::isUsed(), and newTable_p.
name()
const String& casacore::SetupNewTable::name () const inline
Get the name of the table.
Definition at line 370 of file SetupNewTab.h.
References casacore::SetupNewTableRep::name(), and newTable_p.
operator=()
SetupNewTable& casacore::SetupNewTable::operator= (const SetupNewTable &)
Assignment (reference semantics).
option()
int casacore::SetupNewTable::option () const inline
Get the table create option.
Definition at line 374 of file SetupNewTab.h.
References newTable_p, and casacore::SetupNewTableRep::option().
setInUse()
void casacore::SetupNewTable::setInUse () inline private
Set object to in use by a (Plain)Table object.
This function is used by PlainTable.
Definition at line 465 of file SetupNewTab.h.
References newTable_p, and casacore::SetupNewTableRep::setInUse().
setShapeColumn()
void casacore::SetupNewTable::setShapeColumn (const String & columnName, const IPosition & shape) inline
Define the shape of fixed shaped arrays in a column.
The shape of those arrays has to be known before the table can be constructed. It has to be defined via this function, if it was not already defined in the column description. If only the dimensionality was defined in the column description, the shape's dimensionality must match it. Calling this function for an non-fixed shaped array results in an exception. It cannot be used anymore once the SetupNewTable object is used to construct a Table object.
Definition at line 442 of file SetupNewTab.h.
References newTable_p, casacore::SetupNewTableRep::setShapeColumn(), and casacore::shape().
storageOption()
const StorageOption& casacore::SetupNewTable::storageOption () const inline
Get the storage option.
Definition at line 378 of file SetupNewTab.h.
References newTable_p, and casacore::SetupNewTableRep::storageOption().
tableDesc()
const TableDesc& casacore::SetupNewTable::tableDesc () const inline
Get the table description.
Definition at line 386 of file SetupNewTab.h.
References newTable_p, and casacore::SetupNewTableRep::tableDesc().
tableDescPtr()
TableDesc* casacore::SetupNewTable::tableDescPtr () inline private
Get pointer to table description.
This function is used by PlainTable.
Definition at line 460 of file SetupNewTab.h.
References newTable_p, and casacore::SetupNewTableRep::tableDescPtr().
Friends And Related Function Documentation
MemoryTable
friend class MemoryTable friend
Definition at line 349 of file SetupNewTab.h.
PlainTable
friend class PlainTable friend
Definition at line 348 of file SetupNewTab.h.
Member Data Documentation
newTable_p
SetupNewTableRep* casacore::SetupNewTable::newTable_p private
Actual object.
Definition at line 451 of file SetupNewTab.h.
Referenced by adjustHypercolumns(), bindAll(), bindColumn(), bindCreate(), bindGroup(), columnSetPtr(), handleUnbound(), isMarkedForDelete(), isUsed(), name(), option(), setInUse(), setShapeColumn(), storageOption(), tableDesc(), and tableDescPtr().
The documentation for this class was generated from the following file:
tables/Tables/SetupNewTab.h