casacore: casacore::Array< T, Alloc >::BaseIteratorSTL Class Reference
casacore::Array< T, Alloc >::BaseIteratorSTL Class Reference
See the function begin() and end() for a detailed description of the STL iterator capability.
#include <Array.h>
Public Member Functions
BaseIteratorSTL (const Array< T, Alloc > &)
Create the begin const_iterator object for an Array.
BaseIteratorSTL (const T *end=0)
Create the end const_iterator object for an Array.
void nextElem ()
void nextLine ()
bool operator== (const BaseIteratorSTL &other) const
bool operator!= (const BaseIteratorSTL &other) const
T * getPos ()
Protected Member Functions
void increment ()
Increment iterator for a non-contiguous array.
Protected Attributes
const T * itsPos
const T * itsLineEnd
size_t itsLineIncr
size_t itsLineAxis
IPosition itsCurPos
IPosition itsLastPos
const Array< T, Alloc > * itsArray
bool itsContig
Friends
std::ostream & operator<< (std::ostream &os, const BaseIteratorSTL &iter)
Detailed Description
template<typename T, typename Alloc>
class casacore::Array< T, Alloc >::BaseIteratorSTL
See the function begin() and end() for a detailed description of the STL iterator capability.
Definition at line 682 of file Array.h.
Constructor & Destructor Documentation
template<typename T, typename Alloc> casacore::Array< T, Alloc >::BaseIteratorSTL::BaseIteratorSTL (const Array< T, Alloc > &) explicit
Create the begin const_iterator object for an Array.
template<typename T, typename Alloc> casacore::Array< T, Alloc >::BaseIteratorSTL::BaseIteratorSTL (const T * end = 0) inline explicit
Create the end const_iterator object for an Array.
It also acts as the default constructor.
Definition at line 689 of file Array.h.
Member Function Documentation
template<typename T, typename Alloc> T* casacore::Array< T, Alloc >::BaseIteratorSTL::getPos () inline
Definition at line 712 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::itsPos.
Referenced by casacore::Array< T, Alloc >::IteratorSTL::operator*(), and casacore::Array< T, Alloc >::IteratorSTL::operator->().
template<typename T, typename Alloc> void casacore::Array< T, Alloc >::BaseIteratorSTL::increment () protected
Increment iterator for a non-contiguous array.
Referenced by casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem(), and casacore::Array< T, Alloc >::BaseIteratorSTL::nextLine().
template<typename T, typename Alloc> void casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem () inline
Definition at line 692 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::increment(), casacore::Array< T, Alloc >::BaseIteratorSTL::itsContig, casacore::Array< T, Alloc >::BaseIteratorSTL::itsLineEnd, casacore::Array< T, Alloc >::BaseIteratorSTL::itsLineIncr, and casacore::Array< T, Alloc >::BaseIteratorSTL::itsPos.
Referenced by casacore::Array< T, Alloc >::IteratorSTL::operator++(), and casacore::Array< T, Alloc >::ConstIteratorSTL::operator++().
template<typename T, typename Alloc> void casacore::Array< T, Alloc >::BaseIteratorSTL::nextLine () inline
Definition at line 700 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::increment(), casacore::Array< T, Alloc >::BaseIteratorSTL::itsLineEnd, and casacore::Array< T, Alloc >::BaseIteratorSTL::itsPos.
template<typename T, typename Alloc> bool casacore::Array< T, Alloc >::BaseIteratorSTL::operator!= (const BaseIteratorSTL & other) const inline
Definition at line 709 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::itsPos.
template<typename T, typename Alloc> bool casacore::Array< T, Alloc >::BaseIteratorSTL::operator== (const BaseIteratorSTL & other) const inline
Definition at line 706 of file Array.h.
References casacore::Array< T, Alloc >::BaseIteratorSTL::itsPos.
Friends And Related Function Documentation
template<typename T, typename Alloc> std::ostream& operator<< (std::ostream & os, const BaseIteratorSTL & iter) friend
Definition at line 715 of file Array.h.
Member Data Documentation
template<typename T, typename Alloc> const Array<T, Alloc>* casacore::Array< T, Alloc >::BaseIteratorSTL::itsArray protected
Definition at line 728 of file Array.h.
template<typename T, typename Alloc> bool casacore::Array< T, Alloc >::BaseIteratorSTL::itsContig protected
Definition at line 729 of file Array.h.
Referenced by casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem().
template<typename T, typename Alloc> IPosition casacore::Array< T, Alloc >::BaseIteratorSTL::itsCurPos protected
Definition at line 726 of file Array.h.
template<typename T, typename Alloc> IPosition casacore::Array< T, Alloc >::BaseIteratorSTL::itsLastPos protected
Definition at line 727 of file Array.h.
template<typename T, typename Alloc> size_t casacore::Array< T, Alloc >::BaseIteratorSTL::itsLineAxis protected
Definition at line 725 of file Array.h.
template<typename T, typename Alloc> const T* casacore::Array< T, Alloc >::BaseIteratorSTL::itsLineEnd protected
Definition at line 723 of file Array.h.
Referenced by casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem(), and casacore::Array< T, Alloc >::BaseIteratorSTL::nextLine().
template<typename T, typename Alloc> size_t casacore::Array< T, Alloc >::BaseIteratorSTL::itsLineIncr protected
Definition at line 724 of file Array.h.
Referenced by casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem().
template<typename T, typename Alloc> const T* casacore::Array< T, Alloc >::BaseIteratorSTL::itsPos protected
Definition at line 722 of file Array.h.
Referenced by casacore::Array< T, Alloc >::BaseIteratorSTL::getPos(), casacore::Array< T, Alloc >::BaseIteratorSTL::nextElem(), casacore::Array< T, Alloc >::BaseIteratorSTL::nextLine(), casacore::Array< T, Alloc >::BaseIteratorSTL::operator!=(), casacore::Array< T, Alloc >::ConstIteratorSTL::operator*(), casacore::Array< T, Alloc >::ConstIteratorSTL::operator->(), casacore::Array< T, Alloc >::BaseIteratorSTL::operator==(), and casacore::Array< T, Alloc >::ConstIteratorSTL::pos().
The documentation for this class was generated from the following file:
casa/Arrays/Array.h