casacore: casacore::VariableArrayFITSFieldCopier< recordType, fitsType > Class Template Reference
casacore::VariableArrayFITSFieldCopier< recordType, fitsType > Class Template Reference
#include <FITSFieldCopier.h>
Public Member Functions
VariableArrayFITSFieldCopier (RORecordFieldPtr< Array< recordType > > *recptr, FitsField< fitsType > *fitsptr, FitsField< char > *tdirptr)
~VariableArrayFITSFieldCopier ()
virtual void copyToFITS ()
Copy the current contents of the input RORecordFieldPtr to the output FitsField.
Public Member Functions inherited from casacore::FITSFieldCopier
virtual ~FITSFieldCopier ()
destructor
Private Member Functions
VariableArrayFITSFieldCopier (const VariableArrayFITSFieldCopier< recordType, fitsType > &other)
Undefined and inaccessible.
VariableArrayFITSFieldCopier & operator= (const VariableArrayFITSFieldCopier< recordType, fitsType > &other)
Private Attributes
RORecordFieldPtr< Array
< recordType > > * rec_p
FitsField< fitsType > * fits_p
FitsField< char > * tdir_p
Detailed Description
template<class recordType, class fitsType>
class casacore::VariableArrayFITSFieldCopier< recordType, fitsType >
Definition at line 281 of file FITSFieldCopier.h.
Constructor & Destructor Documentation
template<class recordType, class fitsType> casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::VariableArrayFITSFieldCopier (RORecordFieldPtr< Array< recordType > > * recptr, FitsField< fitsType > * fitsptr, FitsField< char > * tdirptr) inline
Definition at line 285 of file FITSFieldCopier.h.
template<class recordType, class fitsType> casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::~VariableArrayFITSFieldCopier () inline
Definition at line 289 of file FITSFieldCopier.h.
References casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::fits_p, and casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::rec_p.
template<class recordType, class fitsType> casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::VariableArrayFITSFieldCopier (const VariableArrayFITSFieldCopier< recordType, fitsType > & other) private
Undefined and inaccessible.
Member Function Documentation
template<class recordType, class fitsType> virtual void casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::copyToFITS () inline virtual
Copy the current contents of the input RORecordFieldPtr to the output FitsField.
and construct the TDIM value for this array
and store it in the tdir_p FitsField
Implements casacore::FITSFieldCopier.
Definition at line 292 of file FITSFieldCopier.h.
References casacore::String::chars(), casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::fits_p, casacore::String::length(), casacore::FitsBase::nelements(), casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::tdir_p, and casacore::FITSKeywordUtil::toTDIM().
template<class recordType, class fitsType> VariableArrayFITSFieldCopier& casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::operator= (const VariableArrayFITSFieldCopier< recordType, fitsType > & other) private
Member Data Documentation
template<class recordType, class fitsType> FitsField<fitsType>* casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::fits_p private
Definition at line 323 of file FITSFieldCopier.h.
Referenced by casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::copyToFITS(), and casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::~VariableArrayFITSFieldCopier().
template<class recordType, class fitsType> RORecordFieldPtr<Array<recordType> >* casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::rec_p private
Definition at line 322 of file FITSFieldCopier.h.
Referenced by casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::~VariableArrayFITSFieldCopier().
template<class recordType, class fitsType> FitsField<char>* casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::tdir_p private
Definition at line 324 of file FITSFieldCopier.h.
Referenced by casacore::VariableArrayFITSFieldCopier< recordType, fitsType >::copyToFITS().
The documentation for this class was generated from the following file:
fits/FITS/FITSFieldCopier.h