casacore: casacore::IBMConversion Class Reference
casacore::IBMConversion Class Reference
OS_module
A class with static functions to convert IBM format.
#include <IBMConversion.h>
Static Public Member Functions
static void toLocal (char &to, const void *from)
Convert one value from IBM format to local format.
static void toLocal (unsigned char &to, const void *from)
static void toLocal (short &to, const void *from)
static void toLocal (unsigned short &to, const void *from)
static void toLocal (int &to, const void *from)
static void toLocal (unsigned int &to, const void *from)
static void toLocal (Int64 &to, const void *from)
static void toLocal (uInt64 &to, const void *from)
static void toLocal (float &to, const void *from)
static void toLocal (double &to, const void *from)
static void toLocal (char *to, const void *from, size_t nr)
Convert nr values from IBM format to local format.
static void toLocal (unsigned char *to, const void *from, size_t nr)
static void toLocal (short *to, const void *from, size_t nr)
static void toLocal (unsigned short *to, const void *from, size_t nr)
static void toLocal (int *to, const void *from, size_t nr)
static void toLocal (unsigned int *to, const void *from, size_t nr)
static void toLocal (Int64 *to, const void *from, size_t nr)
static void toLocal (uInt64 *to, const void *from, size_t nr)
static void toLocal (float *to, const void *from, size_t nr)
static void toLocal (double *to, const void *from, size_t nr)
static void fromLocal (void *to, char from)
Convert one value from local format to IBM format.
static void fromLocal (void *to, unsigned char from)
static void fromLocal (void *to, short from)
static void fromLocal (void *to, unsigned short from)
static void fromLocal (void *to, int from)
static void fromLocal (void *to, unsigned int from)
static void fromLocal (void *to, Int64 from)
static void fromLocal (void *to, uInt64 from)
static void fromLocal (void *to, float from)
static void fromLocal (void *to, double from)
static void fromLocal (void *to, const char *from, size_t nr)
Convert nr values from local format to IBM format.
static void fromLocal (void *to, const unsigned char *from, size_t nr)
static void fromLocal (void *to, const short *from, size_t nr)
static void fromLocal (void *to, const unsigned short *from, size_t nr)
static void fromLocal (void *to, const int *from, size_t nr)
static void fromLocal (void *to, const unsigned int *from, size_t nr)
static void fromLocal (void *to, const Int64 *from, size_t nr)
static void fromLocal (void *to, const uInt64 *from, size_t nr)
static void fromLocal (void *to, const float *from, size_t nr)
static void fromLocal (void *to, const double *from, size_t nr)
Private Member Functions
IBMConversion ()
This class should not be constructed
(so declare the constructor private).
Detailed Description
A class with static functions to convert IBM format.
Intended use:
Public interface
Review Status
Reviewed By:
Friso Olnon
Date Reviewed:
1996/11/06
Test programs:
tIBMConversion
Synopsis
This class contains static toLocal functions to convert data from IBM-360 format to local format and vice-versa. It also handles the conversion of the IBM EBCDIC characters to ASCII characters (for data type char).
The functions work well on big-endian as well as little-endian machines.
Motivation
Archived WSRT data can be stored in the old IBM format (EBCDIC characters and floats with base 16). Conversion functions are needed to read these data.
To Do
Support data type long double.
Definition at line 80 of file IBMConversion.h.
Constructor & Destructor Documentation
casacore::IBMConversion::IBMConversion () private
This class should not be constructed
(so declare the constructor private).
Member Function Documentation
static void casacore::IBMConversion::fromLocal (void * to, char from) static
Convert one value from local format to IBM format.
The from and to buffer should not overlap.
Note: The char version converts from ASCII to EBCDIC, while the unsigned char version is a simple copy;
Referenced by fromLocal().
void casacore::IBMConversion::fromLocal (void * to, unsigned char from) inline static
Definition at line 281 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, short from) inline static
Definition at line 286 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, unsigned short from) inline static
Definition at line 291 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, int from) inline static
Definition at line 296 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, unsigned int from) inline static
Definition at line 301 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, Int64 from) inline static
Definition at line 306 of file IBMConversion.h.
References casacore::CanonicalConversion::move4(), and casacore::CanonicalConversion::reverse4().
void casacore::IBMConversion::fromLocal (void * to, uInt64 from) inline static
Definition at line 315 of file IBMConversion.h.
References casacore::CanonicalConversion::move4(), and casacore::CanonicalConversion::reverse4().
void casacore::IBMConversion::fromLocal (void * to, float from) inline static
Definition at line 324 of file IBMConversion.h.
References fromLocal().
void casacore::IBMConversion::fromLocal (void * to, double from) inline static
Definition at line 329 of file IBMConversion.h.
References fromLocal().
static void casacore::IBMConversion::fromLocal (void * to, const char * from, size_t nr) static
Convert nr values from local format to IBM format.
The from and to buffer should not overlap.
Note: The char version converts from ASCII to EBCDIC, while the unsigned char version is a simple copy;
void casacore::IBMConversion::fromLocal (void * to, const unsigned char * from, size_t nr) inline static
Definition at line 335 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, const short * from, size_t nr) inline static
Definition at line 341 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, const unsigned short * from, size_t nr) inline static
Definition at line 347 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, const int * from, size_t nr) inline static
Definition at line 353 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
void casacore::IBMConversion::fromLocal (void * to, const unsigned int * from, size_t nr) inline static
Definition at line 359 of file IBMConversion.h.
References casacore::CanonicalConversion::fromLocal().
static void casacore::IBMConversion::fromLocal (void * to, const Int64 * from, size_t nr) static
static void casacore::IBMConversion::fromLocal (void * to, const uInt64 * from, size_t nr) static
static void casacore::IBMConversion::fromLocal (void * to, const float * from, size_t nr) static
static void casacore::IBMConversion::fromLocal (void * to, const double * from, size_t nr) static
static void casacore::IBMConversion::toLocal (char & to, const void * from) static
Convert one value from IBM format to local format.
The from and to buffer should not overlap.
Note: The char version converts from EBCDIC to ASCII, while the unsigned char version is a simple copy;
Referenced by toLocal().
void casacore::IBMConversion::toLocal (unsigned char & to, const void * from) inline static
Definition at line 187 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (short & to, const void * from) inline static
Definition at line 192 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (unsigned short & to, const void * from) inline static
Definition at line 197 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (int & to, const void * from) inline static
Definition at line 202 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (unsigned int & to, const void * from) inline static
Definition at line 207 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (Int64 & to, const void * from) inline static
Definition at line 212 of file IBMConversion.h.
References casacore::CanonicalConversion::move4(), and casacore::CanonicalConversion::reverse4().
void casacore::IBMConversion::toLocal (uInt64 & to, const void * from) inline static
Definition at line 228 of file IBMConversion.h.
References casacore::CanonicalConversion::move4(), and casacore::CanonicalConversion::reverse4().
void casacore::IBMConversion::toLocal (float & to, const void * from) inline static
Definition at line 240 of file IBMConversion.h.
References toLocal().
void casacore::IBMConversion::toLocal (double & to, const void * from) inline static
Definition at line 245 of file IBMConversion.h.
References toLocal().
static void casacore::IBMConversion::toLocal (char * to, const void * from, size_t nr) static
Convert nr values from IBM format to local format.
The from and to buffer should not overlap.
Note: The char version converts from EBCDIC to ASCII, while the unsigned char version is a simple copy;
void casacore::IBMConversion::toLocal (unsigned char * to, const void * from, size_t nr) inline static
Definition at line 250 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (short * to, const void * from, size_t nr) inline static
Definition at line 256 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (unsigned short * to, const void * from, size_t nr) inline static
Definition at line 262 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (int * to, const void * from, size_t nr) inline static
Definition at line 268 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
void casacore::IBMConversion::toLocal (unsigned int * to, const void * from, size_t nr) inline static
Definition at line 274 of file IBMConversion.h.
References casacore::CanonicalConversion::toLocal().
static void casacore::IBMConversion::toLocal (Int64 * to, const void * from, size_t nr) static
static void casacore::IBMConversion::toLocal (uInt64 * to, const void * from, size_t nr) static
static void casacore::IBMConversion::toLocal (float * to, const void * from, size_t nr) static
static void casacore::IBMConversion::toLocal (double * to, const void * from, size_t nr) static
The documentation for this class was generated from the following file:
casa/OS/IBMConversion.h