casacore: casacore::IPosition Class Reference
casacore::IPosition Class Reference
Arrays_module
A Vector of integers, for indexing into Array<T> objects.
#include <IPosition.h>
Public Member Functions
IPosition () noexcept
A zero-length IPosition.
IPosition (size_t length)
An IPosition of size "length." The values in the object are uninitialized.
IPosition (std::initializer_list< ssize_t > list)
An IPosition initialized from the given list.
IPosition (size_t length, ssize_t val)
An IPosition of size "length." All values in the object are initialized to val.
template<typename... Vals>
IPosition (size_t, ssize_t val1, ssize_t val2, Vals...vals)
An IPosition initialized from a variable number of parameters.
IPosition (const IPosition &source)
Makes a copy (copy, NOT reference, semantics) of source.
IPosition (IPosition &&source) noexcept
~IPosition ()
IPosition & operator= (const IPosition &source)
Makes this a copy of other.
IPosition & operator= (IPosition &&source)
IPosition & operator= (ssize_t value)
Copy "value" into every position of this IPosition.
IPosition (const Array< int > &other)
Convert an IPosition to and from an Array<int/int64>.
IPosition (const Array< long long > &other)
Vector< int > asVector () const
Vector< long long > asVector64 () const
IPosition (const std::vector< int > &other)
Convert an IPosition to and from an Array<int/int64>.
IPosition (const std::vector< long long > &other)
std::vector< int > asStdVector () const
std::vector< long long > asStdVector64 () const
template<typename InputIterator >
void fill (size_t size, InputIterator iter)
Resize and fill this IPosition object.
template<typename OutputIterator >
void copy (OutputIterator iter) const
Copy the contents of this IPosition object to the output iterator.
IPosition nonDegenerate (size_t startingAxis=0) const
This member functions return an IPosition which has degenerate (length==1) axes removed and the dimensionality reduced appropriately.
IPosition nonDegenerate (const IPosition &ignoreAxes) const
void resize (size_t newSize, bool copy=true)
Old values are copied on resize if copy==true.
ssize_t & operator[] (size_t index)
Index into the IPosition.
ssize_t operator[] (size_t index) const
ssize_t & operator() (size_t index)
ssize_t operator() (size_t index) const
IPosition operator() (const IPosition &axes) const
Make an IPosition by using only the specified elements of the current
IPosition.
ssize_t & last (size_t index=0)
Index into the IPosition from the end.
ssize_t last (size_t index=0) const
const ssize_t * storage () const
Get the storage.
void append (const IPosition &other)
Append this IPosition with another one (causing a resize).
void prepend (const IPosition &other)
Prepend this IPosition with another one (causing a resize).
IPosition concatenate (const IPosition &other) const
Return an IPosition as the concetanation of this and another IPosition.
void setFirst (const IPosition &other)
Set the first values of this IPosition to another IPosition.
void setLast (const IPosition &other)
Set the last values of this IPosition to another IPosition.
IPosition getFirst (size_t n) const
Construct an IPosition from the first n values of this IPosition.
IPosition getLast (size_t n) const
Construct an IPosition from the last n values of this IPosition.
IPosition removeAxes (const IPosition &axes) const
Return an IPosition where the given axes are reoved.
IPosition keepAxes (const IPosition &axes) const
Return an IPosition containing the given axes only.
size_t nelements () const
The number of elements in this IPosition.
size_t size () const
bool empty () const
Is the IPosition empty (i.e.
bool conform (const IPosition &other) const
conform returns true if nelements() == other.nelements().
void operator+= (const IPosition &other)
Element-by-element arithmetic.
void operator-= (const IPosition &other)
void operator*= (const IPosition &other)
void operator/= (const IPosition &other)
void operator+= (ssize_t val)
void operator-= (ssize_t val)
void operator*= (ssize_t val)
void operator/= (ssize_t val)
long long product () const
Returns 0 if nelements() == 0, otherwise it returns the product of its elements.
bool allOne () const
Are all elements equal to 1? Useful to check if a given stride is really a stride.
bool isEqual (const IPosition &other) const
Element-by-element comparison for equality.
bool isEqual (const IPosition &other, bool skipDegeneratedAxes) const
Element-by-element comparison for equality.
bool isEqual (const IPosition &other, size_t nrCompare) const
Element-by-element comparison for (partial) equality.
bool isSubSet (const IPosition &other) const
Is the other IPosition a subset of (or equal to) this IPosition? It is a subset if zero or more axes of this IPosition do not occur or are degenerated in the other and if the remaining axes are in the same order.
std::string toString () const
Write the IPosition into a string.
bool ok () const
Is this IPosition consistent?
Static Public Member Functions
template<typename... Vals>
static IPosition Make (Vals...vals)
Construct an IPosition that is initialized from a variable number of parameter.
static IPosition makeAxisPath (size_t nrdim)
Construct a default axis path consisting of the values 0.
static IPosition makeAxisPath (size_t nrdim, const IPosition &partialPath)
Construct a full axis path from a (partially) given axis path.
static IPosition otherAxes (size_t nrdim, const IPosition &axes)
Make a list of axes which are the axes not given in axes up to the given dimension.
Friends
class IPositionComparator
std::ostream & operator<< (std::ostream &os, const IPosition &ip)
Write an IPosition to an ostream in a simple text form.
enum { BufferLength }
typedef ssize_t value_type
Define the STL-style iterators.
typedef ssize_t * iterator
typedef const ssize_t * const_iterator
typedef value_type * pointer
typedef const value_type * const_pointer
typedef value_type & reference
typedef const value_type & const_reference
typedef size_t size_type
typedef ptrdiff_t difference_type
size_t size_p
ssize_t buffer_p [BufferLength]
ssize_t * data_p
When the iposition is length BufferSize or less data is just buffer_p, avoiding calls to new and delete.
iterator begin ()
Get the begin and end iterator object for this object.
const_iterator begin () const
iterator end ()
const_iterator end () const
void allocateBuffer ()
Allocate a buffer with length size_p.
void throwIndexError () const
Throw an index error exception.
Detailed Description
A Vector of integers, for indexing into Array<T> objects.
Intended use:
Public interface
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Etymology
IPosition is an Index Position in an n-dimensional array.
Synopsis
IPosition is "logically" a Vector<int> constrained so that its origin is zero-based, and in fact that used to be the way it was implemented. It was split out into a separate class to make the inheritance from Arrays simpler (since Arrays use IPositions). The template instantiation mechanism is complicated enough that this simplification was felt to be a good idea.
IPosition objects are normally used to index into, and define the shapes of, multi-dimensional arrays. For example, if you have a 5 dimensional array, you need an IPosition of length 5 to index into the array (or to define its shape, etc.).
Unlike Vectors, IPositions always use copy semantics.
IPosition ip1(5);                         // An IPosition of length 5
ip1(0) = 11; ip1(1) = 5;... ip1(4) = 6;  // Indices 0-based
IPosition ip2(ip1);                       // Copy constructor; a COPY
Binary operations must take place either with a conformnat (same size) IPosition or with an integer, which behaves as if it was an IPosition of the same size (i.e., length). All the usual binary arithmetic operations are available, as well as logical operations, which return Booleans. These all operate "element-by-element".
All non-inlined member functions of IPosition check invariants if the preprocessor symbol AIPS_DEBUG is defined. That is, the member functions check that ok() is true (constructors check after construction, other functions on entry to the function). If these tests fail, an AipsError exception is thrown; its message contains the line number and source file of the failure (it is thrown by the lAssert macro defined in aips/Assert.h).
Constructors and functions exist to construct an IPosition directly from a Vector or std::vector object or to convert to it. Furthermore the fill and copy can be used to fill from or copy to any STL-type iterator.
Example
IPosition blc(5), trc(5,1,2,3,4,5);
blc = 0;            // OR IPosition blc(5,0);
//..\.
if (blc > trc) {
IPosition tmp;
tmp = trc;       // Swap
trc = blc;
blc = tmp;
}
//..\.
trc += 5;           // make the box 5 larger in all dimensions
std::vector<int> vec(trc.toStdVector());
Definition at line 118 of file IPosition.h.
Member Typedef Documentation
typedef const ssize_t* casacore::IPosition::const_iterator
Definition at line 407 of file IPosition.h.
typedef const value_type* casacore::IPosition::const_pointer
Definition at line 409 of file IPosition.h.
typedef const value_type& casacore::IPosition::const_reference
Definition at line 411 of file IPosition.h.
typedef ptrdiff_t casacore::IPosition::difference_type
Definition at line 413 of file IPosition.h.
typedef ssize_t* casacore::IPosition::iterator
Definition at line 406 of file IPosition.h.
typedef value_type* casacore::IPosition::pointer
Definition at line 408 of file IPosition.h.
typedef value_type& casacore::IPosition::reference
Definition at line 410 of file IPosition.h.
typedef size_t casacore::IPosition::size_type
Definition at line 412 of file IPosition.h.
typedef ssize_t casacore::IPosition::value_type
Define the STL-style iterators.
It makes it possible to iterate through all data elements.
IPosition shp(2,0);
for (IPosition::iterator iter=shp.begin(); iter!=shp.end(); iter++) {
*iter += 1;
}
STL-style typedefs.
Definition at line 405 of file IPosition.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
BufferLength
Definition at line 435 of file IPosition.h.
Constructor & Destructor Documentation
casacore::IPosition::IPosition () inline noexcept
A zero-length IPosition.
Definition at line 558 of file IPosition.h.
Referenced by IPosition(), and makeAxisPath().
casacore::IPosition::IPosition (size_t length) explicit
An IPosition of size "length." The values in the object are uninitialized.
casacore::IPosition::IPosition (std::initializer_list< ssize_t > list)
An IPosition initialized from the given list.
casacore::IPosition::IPosition (size_t length, ssize_t val)
An IPosition of size "length." All values in the object are initialized to val.
template<typename... Vals> casacore::IPosition::IPosition (size_t , ssize_t val1, ssize_t val2, Vals... vals) inline
An IPosition initialized from a variable number of parameters.
The first parameter should specify the size, but the actual size of the resulting IPosition is determined from the number of parameters (the first argument is ignored).
This constructor should be disfavoured, because i) of the dummy parameter and ii) because it may narrow the specified parameter without a warning.
Instead, use an initializer list constructor whenever possible. If an IPosition is created inside a macro, an initializer list is not possible. In those cases, use the Make(Vals...) factory method. Both of those methods do not have the above issues. [[ deprecated("Use the initializer list constructor or Make() method") ]]
Definition at line 151 of file IPosition.h.
References IPosition(), and ~IPosition().
casacore::IPosition::IPosition (const IPosition & source)
Makes a copy (copy, NOT reference, semantics) of source.
casacore::IPosition::IPosition (IPosition && source) noexcept
casacore::IPosition::~IPosition ()
Referenced by IPosition().
casacore::IPosition::IPosition (const Array< int > & other)
Convert an IPosition to and from an Array<int/int64>.
In either case, the array must be one dimensional.
casacore::IPosition::IPosition (const Array< long long > & other)
casacore::IPosition::IPosition (const std::vector< int > & other)
Convert an IPosition to and from an Array<int/int64>.
In either case, the array must be one dimensional.
casacore::IPosition::IPosition (const std::vector< long long > & other)
Member Function Documentation
void casacore::IPosition::allocateBuffer () private
Allocate a buffer with length size_p.
bool casacore::IPosition::allOne () const
Are all elements equal to 1? Useful to check if a given stride is really a stride.
void casacore::IPosition::append (const IPosition & other)
Append this IPosition with another one (causing a resize).
Referenced by casacore::TableExprGroupAggr::getArray(), and casacore::TableProxy::record2Array().
std::vector<int> casacore::IPosition::asStdVector () const
std::vector<long long> casacore::IPosition::asStdVector64 () const
Vector<int> casacore::IPosition::asVector () const
Vector<long long> casacore::IPosition::asVector64 () const
iterator casacore::IPosition::begin () inline
Get the begin and end iterator object for this object.
Definition at line 417 of file IPosition.h.
References data_p.
const_iterator casacore::IPosition::begin () const inline
Definition at line 419 of file IPosition.h.
References data_p.
IPosition casacore::IPosition::concatenate (const IPosition & other) const
Return an IPosition as the concetanation of this and another IPosition.
Referenced by casacore::ScaledComplexData< VirtualType, StoredType >::storedShape().
bool casacore::IPosition::conform (const IPosition & other) const inline
conform returns true if nelements() == other.nelements().
Definition at line 636 of file IPosition.h.
References size_p.
Referenced by casacore::TSMShape::conform().
template<typename OutputIterator > void casacore::IPosition::copy (OutputIterator iter) const inline
Copy the contents of this IPosition object to the output iterator.
The size of the output must be sufficient.
Definition at line 230 of file IPosition.h.
References data_p, and size_p.
bool casacore::IPosition::empty () const inline
Is the IPosition empty (i.e.
no elements)?
Definition at line 576 of file IPosition.h.
References size_p.
iterator casacore::IPosition::end () inline
Definition at line 421 of file IPosition.h.
References data_p, and size_p.
const_iterator casacore::IPosition::end () const inline
Definition at line 423 of file IPosition.h.
References data_p, and size_p.
template<typename InputIterator > void casacore::IPosition::fill (size_t size, InputIterator iter) inline
Resize and fill this IPosition object.
Definition at line 219 of file IPosition.h.
References data_p, resize(), and size().
IPosition casacore::IPosition::getFirst (size_t n) const
Construct an IPosition from the first n values of this IPosition.
An exception is thrown if n is too high.
IPosition casacore::IPosition::getLast (size_t n) const
Construct an IPosition from the last n values of this IPosition.
An exception is thrown if n is too high.
bool casacore::IPosition::isEqual (const IPosition & other) const
Element-by-element comparison for equality.
It returns true if the lengths and all elements are equal.
Note that an important difference between this function and operator==() is that if the two IPositions have different lengths, this function returns false, instead of throwing an exception as operator==() does.
Referenced by casacore::checkArrayShapes(), casacore::LatticeBase::conform(), and casacore::ArrayBase::conform2().
bool casacore::IPosition::isEqual (const IPosition & other, bool skipDegeneratedAxes) const
Element-by-element comparison for equality.
It returns true if all elements are equal. When skipDegeneratedAxes is true, axes with length 1 are skipped in both operands.
bool casacore::IPosition::isEqual (const IPosition & other, size_t nrCompare) const
Element-by-element comparison for (partial) equality.
It returns true if the lengths and the first nrCompare elements are equal.
bool casacore::IPosition::isSubSet (const IPosition & other) const
Is the other IPosition a subset of (or equal to) this IPosition? It is a subset if zero or more axes of this IPosition do not occur or are degenerated in the other and if the remaining axes are in the same order.
IPosition casacore::IPosition::keepAxes (const IPosition & axes) const
Return an IPosition containing the given axes only.
ssize_t & casacore::IPosition::last (size_t index = 0) inline
Index into the IPosition from the end.
By default the last value is returned. If the preprocessor symbol AIPS_ARRAY_INDEX_CHECK is defined, it will check if the index is not out of bounds.
Definition at line 611 of file IPosition.h.
References data_p, size_p, and throwIndexError().
ssize_t casacore::IPosition::last (size_t index = 0) const inline
Definition at line 621 of file IPosition.h.
References data_p, size_p, and throwIndexError().
template<typename... Vals> static IPosition casacore::IPosition::Make (Vals... vals) inline static
Construct an IPosition that is initialized from a variable number of parameter.
The resulting size of the IPosition will equal the number of parameters specified.
In general, using the initializer list constructor should be preferred. Defining an initializer list inside macros is however not possible. In those cases, this method can be used to construct the IPosition.
Example: IPosition::Make(3, 5) creates an IPosition of size 2, with values 3 and 5. It is identical to IPosition{3, 5}. A program is ill-formed when narrowing of a parameter is required, causing a compiler warning or error.
Definition at line 172 of file IPosition.h.
IPosition casacore::IPosition::makeAxisPath (size_t nrdim) inline static
Construct a default axis path consisting of the values 0.
. nrdim-1.
Definition at line 563 of file IPosition.h.
References IPosition().
static IPosition casacore::IPosition::makeAxisPath (size_t nrdim, const IPosition & partialPath) static
Construct a full axis path from a (partially) given axis path.
It fills the path with the non-given axis. It is checked if the given axis path is valid (i.e. if the axis are < nrdim and if they are not doubly defined). E.g.: in the 4D case an axis path [0,2] is returned as [0,2,1,3].
size_t casacore::IPosition::nelements () const inline
The number of elements in this IPosition.
Since IPosition objects use zero-based indexing, the maximum available index is nelements() - 1.
Definition at line 568 of file IPosition.h.
References size_p.
Referenced by casacore::ArrayPositionIterator::dimIter(), casacore::ArrayPositionIterator::ndim(), casacore::Slicer::ndim(), operator()(), and casacore::TSMCube::setLastColSlice().
IPosition casacore::IPosition::nonDegenerate (size_t startingAxis = 0) const
This member functions return an IPosition which has degenerate (length==1) axes removed and the dimensionality reduced appropriately.
Only axes greater than startingAxis are considered (normally one wants to remove trailing axes.
The functions with argument ignoreAxes do not consider the axes given in that argument.
IPosition casacore::IPosition::nonDegenerate (const IPosition & ignoreAxes) const
bool casacore::IPosition::ok () const
Is this IPosition consistent?
ssize_t & casacore::IPosition::operator() (size_t index) inline
Definition at line 591 of file IPosition.h.
References data_p, nelements(), and throwIndexError().
ssize_t casacore::IPosition::operator() (size_t index) const inline
Definition at line 601 of file IPosition.h.
References data_p, nelements(), and throwIndexError().
IPosition casacore::IPosition::operator() (const IPosition & axes) const
Make an IPosition by using only the specified elements of the current
IPosition.
All values of axes must be less than the number of elements of the current object.
Example
IPosition ipos(4, 11, 12, 13, 14); ex1 is IPosition(3, 11, 12, 13); IPosition ex1 = ipos(IPosition(3,0,1,2); ex2 is IPosition(3, 12, 11) IPosition ex2 = ipos(IPosition(2,2,1); ex3 is IPosition(4,14,14,14,14) IPosition ex3 = ipos(IPosition(4,3,3,3,3);
void casacore::IPosition::operator*= (const IPosition & other)
void casacore::IPosition::operator*= (ssize_t val)
void casacore::IPosition::operator+= (const IPosition & other)
Element-by-element arithmetic.
void casacore::IPosition::operator+= (ssize_t val)
void casacore::IPosition::operator-= (const IPosition & other)
void casacore::IPosition::operator-= (ssize_t val)
void casacore::IPosition::operator/= (const IPosition & other)
void casacore::IPosition::operator/= (ssize_t val)
IPosition& casacore::IPosition::operator= (const IPosition & source)
Makes this a copy of other.
When the dest is not of the same size, it will resize itself to be the same length as the source.
IPosition& casacore::IPosition::operator= (IPosition && source)
IPosition& casacore::IPosition::operator= (ssize_t value)
Copy "value" into every position of this IPosition.
ssize_t & casacore::IPosition::operator[] (size_t index) inline
Index into the IPosition.
Indices are zero-based. If the preprocessor symbol AIPS_ARRAY_INDEX_CHECK is defined, operator() will check "index" to ensure it is not out of bounds. If this check fails, an AipsError will be thrown.
Definition at line 581 of file IPosition.h.
References data_p.
ssize_t casacore::IPosition::operator[] (size_t index) const inline
Definition at line 586 of file IPosition.h.
References data_p.
static IPosition casacore::IPosition::otherAxes (size_t nrdim, const IPosition & axes) static
Make a list of axes which are the axes not given in axes up to the given dimension.
void casacore::IPosition::prepend (const IPosition & other)
Prepend this IPosition with another one (causing a resize).
long long casacore::IPosition::product () const
Returns 0 if nelements() == 0, otherwise it returns the product of its elements.
Referenced by casacore::LatticeIndexer::nelements().
IPosition casacore::IPosition::removeAxes (const IPosition & axes) const
Return an IPosition where the given axes are reoved.
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialArrayMath().
void casacore::IPosition::resize (size_t newSize, bool copy = true)
Old values are copied on resize if copy==true.
If the size increases, values beyond the former size are undefined.
Referenced by fill(), casacore::TSMCube::setLastColSlice(), and casacore::TableExprNodeSet::toArray().
void casacore::IPosition::setFirst (const IPosition & other)
Set the first values of this IPosition to another IPosition.
An exception is thrown if the other IPosition is too long.
void casacore::IPosition::setLast (const IPosition & other)
Set the last values of this IPosition to another IPosition.
An exception is thrown if the other IPosition is too long.
size_t casacore::IPosition::size () const inline
Definition at line 572 of file IPosition.h.
References size_p.
Referenced by casacore::Array< T, std::allocator< T > >::checkBeforeResize(), casacore::ArrayMath_global_functions_Array_mathematical_operations::expandArray(), fill(), casacore::TableExprGroupAggr::getArray(), casacore::python::to_list< casacore::IPosition >::makeobject(), casacore::MArrayBase::ndim(), and casacore::TableExprNodeSet::toArray().
const ssize_t * casacore::IPosition::storage () const inline
Get the storage.
Definition at line 631 of file IPosition.h.
References data_p.
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::fractile(), and casacore::MArrayMath_global_functions_MArray_mathematical_operations::median().
void casacore::IPosition::throwIndexError () const private
Throw an index error exception.
Referenced by last(), and operator()().
std::string casacore::IPosition::toString () const
Write the IPosition into a string.
TODO deprecate in favour of to_string(const IPosition&)
Friends And Related Function Documentation
friend class IPositionComparator friend
Definition at line 120 of file IPosition.h.
std::ostream& operator<< (std::ostream & os, const IPosition & ip) friend
Write an IPosition to an ostream in a simple text form.
Member Data Documentation
ssize_t casacore::IPosition::buffer_p[BufferLength] private
Definition at line 437 of file IPosition.h.
ssize_t* casacore::IPosition::data_p private
When the iposition is length BufferSize or less data is just buffer_p, avoiding calls to new and delete.
Definition at line 440 of file IPosition.h.
Referenced by begin(), copy(), end(), fill(), last(), operator()(), operator[](), and storage().
size_t casacore::IPosition::size_p private
Definition at line 436 of file IPosition.h.
Referenced by conform(), copy(), empty(), end(), last(), nelements(), and size().
The documentation for this class was generated from the following file:
casa/Arrays/IPosition.h