casacore: casacore::Erlang Class Reference
casacore::Erlang Class Reference
BasicMath_module
Erlang distribution.
#include <Random.h>
Public Member Functions
Erlang (RNG *gen, Double mean=1.0, Double variance=1.0)
Construct a random number generator for an Erlang distribution.
virtual ~Erlang ()
The destructor is trivial.
virtual Double operator() ()
Returns a value from the Erlang distribution.
Double mean () const
Functions that allow you to query and change the parameters of the discrete uniform distribution.
void mean (Double x)
Double variance () const
void variance (Double x)
virtual void setParameters (const Vector< Double > &parms)
These function allow you to manipulate the parameters (mean & variance) described above through the base class.
virtual Vector< Double > parameters () const
virtual Bool checkParameters (const Vector< Double > &parms) const
Public Member Functions inherited from casacore::Random
virtual ~Random ()
A virtual destructor is needed to ensure that the destructor of derived classes gets used.
RNG * generator ()
Functions that allow you to access and change the class that generates the random bits.
void generator (RNG *p)
Private Member Functions
void setState ()
Private Attributes
Double itsMean
Double itsVariance
Int itsK
Double itsA
Additional Inherited Members
Public Types inherited from casacore::Random
enum Types {
BINOMIAL,
DISCRETEUNIFORM,
ERLANG,
GEOMETRIC,
HYPERGEOMETRIC,
NORMAL,
LOGNORMAL,
NEGATIVEEXPONENTIAL,
POISSON,
UNIFORM,
WEIBULL,
UNKNOWN,
NUMBER_TYPES
}
This enumerator lists all the predefined random number distributions.
Static Public Member Functions inherited from casacore::Random
static String asString (Random::Types type)
Convert the enumerator to a lower-case string.
static Random::Types asType (const String &str)
Convert the string to enumerator.
static Random * construct (Random::Types type, RNG *gen)
Convert the Random::Type enumerator to a specific object (derived from Random but upcast to a Random object).
static Vector< Double > defaultParameters (Random::Types type)
returns the default parameters for the specified distribution.
Protected Member Functions inherited from casacore::Random
Random (RNG *generator)
Protected Attributes inherited from casacore::Random
RNG * itsRNG
Detailed Description
Erlang distribution.
Synopsis
The Erlang class implements an Erlang distribution with mean mean and variance variance.
It is assumed that the mean is non-zero and the variance is positive an AipsError exception thrown if this is not true. The remaining members allow you to read and set the parameters.
Example
Thrown Exceptions
AipsError: if bad values for the arguments are given, as specified above.
To Do
Nothing I hope!
Definition at line 740 of file Random.h.
Constructor & Destructor Documentation
casacore::Erlang::Erlang (RNG * gen, Double mean = 1.0, Double variance = 1.0) inline
Construct a random number generator for an Erlang distribution.
The first argument is a class that produces random bits. This pointer is NOT taken over by this class and the user is responsible for deleting it. The second and third arguments define the parameters for this distribution as described in the synopsis.
Definition at line 781 of file Random.h.
References setState().
virtual casacore::Erlang::~Erlang () virtual
The destructor is trivial.
Member Function Documentation
virtual Bool casacore::Erlang::checkParameters (const Vector< Double > & parms) const virtual
Implements casacore::Random.
Double casacore::Erlang::mean () const inline
Functions that allow you to query and change the parameters of the discrete uniform distribution.
Definition at line 789 of file Random.h.
References itsMean.
void casacore::Erlang::mean (Double x) inline
Definition at line 793 of file Random.h.
References itsMean, and setState().
virtual Double casacore::Erlang::operator() () virtual
Returns a value from the Erlang distribution.
Implements casacore::Random.
virtual Vector<Double> casacore::Erlang::parameters () const virtual
Implements casacore::Random.
virtual void casacore::Erlang::setParameters (const Vector< Double > & parms) virtual
These function allow you to manipulate the parameters (mean & variance) described above through the base class.
The Vectors must always be of length two.
Implements casacore::Random.
void casacore::Erlang::setState () private
Referenced by Erlang(), mean(), and variance().
Double casacore::Erlang::variance () const inline
Definition at line 798 of file Random.h.
References itsVariance.
void casacore::Erlang::variance (Double x) inline
Definition at line 802 of file Random.h.
References itsVariance, and setState().
Member Data Documentation
Double casacore::Erlang::itsA private
Definition at line 778 of file Random.h.
Int casacore::Erlang::itsK private
Definition at line 777 of file Random.h.
Double casacore::Erlang::itsMean private
Definition at line 775 of file Random.h.
Referenced by mean().
Double casacore::Erlang::itsVariance private
Definition at line 776 of file Random.h.
Referenced by variance().
The documentation for this class was generated from the following file:
casa/BasicMath/Random.h