casacore: casacore::AipsIO Class Reference
casacore::AipsIO Class Reference
IO_module
AipsIO is the object persistency mechanism of Casacore.
#include <AipsIO.h>
Public Member Functions
AipsIO ()
No file attached yet.
AipsIO (const String &fileName, ByteIO::OpenOption=ByteIO::Old, uInt filebufSize=65536,/uInt filebufSize=1048576,*/MultiFileBase *mfile=0)
Construct and open/create a file with the given name.
AipsIO (ByteIO *)
Construct from a stream object derived from ByteIO.
AipsIO (TypeIO *)
Construct from a stream object derived from TypeIO, thus from a stream on top of ByteIOn doing the possible conversions.
~AipsIO ()
Close if not done yet.
void open (const String &fileName, ByteIO::OpenOption=ByteIO::Old, uInt filebufSize=65536, MultiFileBase *mfile=0)
Open/create file (either a regular file or a MultiFileBase virtual file).
void open (ByteIO *)
Open by connecting to the given byte stream.
void open (TypeIO *)
Open by connecting to the given typed byte stream.
void close ()
Close file opened.
ByteIO::OpenOption fileOption () const
Return the file option.
uInt putstart (const String &objectType, uInt objectVersion)
Start putting an object.
uInt putstart (const Char *objectType, uInt objectVersion)
AipsIO & operator<< (const Bool &value)
Put a single value.
AipsIO & operator<< (const Char &value)
AipsIO & operator<< (const uChar &value)
AipsIO & operator<< (const short &value)
AipsIO & operator<< (const unsigned short &value)
AipsIO & operator<< (const int &value)
AipsIO & operator<< (const unsigned int &value)
AipsIO & operator<< (const Int64 &value)
AipsIO & operator<< (const uInt64 &value)
AipsIO & operator<< (const float &value)
AipsIO & operator<< (const double &value)
AipsIO & operator<< (const Complex &value)
AipsIO & operator<< (const DComplex &value)
AipsIO & operator<< (const String &value)
AipsIO & operator<< (const Char *value)
AipsIO & put (uInt nrval, const Bool *values, Bool putNR=True)
Put an array of values with the given number of values.
AipsIO & put (uInt nrval, const Char *values, Bool putNR=True)
AipsIO & put (uInt nrval, const uChar *values, Bool putNR=True)
AipsIO & put (uInt nrval, const short *values, Bool putNR=True)
AipsIO & put (uInt nrval, const unsigned short *values, Bool putNR=True)
AipsIO & put (uInt nrval, const int *values, Bool putNR=True)
AipsIO & put (uInt nrval, const unsigned int *values, Bool putNR=True)
AipsIO & put (uInt nrval, const Int64 *values, Bool putNR=True)
AipsIO & put (uInt nrval, const uInt64 *values, Bool putNR=True)
AipsIO & put (uInt nrval, const float *values, Bool putNR=True)
AipsIO & put (uInt nrval, const double *values, Bool putNR=True)
AipsIO & put (uInt nrval, const Complex *values, Bool putNR=True)
AipsIO & put (uInt nrval, const DComplex *values, Bool putNR=True)
AipsIO & put (uInt nrval, const String *values, Bool putNR=True)
template<typename T >
AipsIO & put (const vector< T > &vec)
Put a vector as an array of values For standard types it has the same result as put with putNR=True.
AipsIO & put (const vector< Bool > &vec)
uInt putend ()
End putting an object.
Int64 getpos ()
Get and set file-offset.
Int64 setpos (Int64 offset)
const String & getNextType ()
Get the type of the next object stored.
uInt getstart (const String &objectType)
Start reading an object.
uInt getstart (const Char *objectType)
AipsIO & operator>> (Bool &value)
Get a single value.
AipsIO & operator>> (Char &value)
AipsIO & operator>> (uChar &value)
AipsIO & operator>> (short &value)
AipsIO & operator>> (unsigned short &value)
AipsIO & operator>> (int &value)
AipsIO & operator>> (unsigned int &value)
AipsIO & operator>> (Int64 &value)
AipsIO & operator>> (uInt64 &value)
AipsIO & operator>> (float &value)
AipsIO & operator>> (double &value)
AipsIO & operator>> (Complex &value)
AipsIO & operator>> (DComplex &value)
AipsIO & operator>> (String &value)
AipsIO & get (uInt nrval, Bool *values)
Read in nrval values into the user-supplied values buffer.
AipsIO & get (uInt nrval, Char *values)
AipsIO & get (uInt nrval, uChar *values)
AipsIO & get (uInt nrval, short *values)
AipsIO & get (uInt nrval, unsigned short *values)
AipsIO & get (uInt nrval, int *values)
AipsIO & get (uInt nrval, unsigned int *values)
AipsIO & get (uInt nrval, Int64 *values)
AipsIO & get (uInt nrval, uInt64 *values)
AipsIO & get (uInt nrval, float *values)
AipsIO & get (uInt nrval, double *values)
AipsIO & get (uInt nrval, Complex *values)
AipsIO & get (uInt nrval, DComplex *values)
AipsIO & get (uInt nrval, String *values)
template<typename T >
AipsIO & get (vector< T > &vec)
Get a vector as an array of values (similar to getnew).
AipsIO & get (vector< Bool > &vec)
AipsIO & getnew (uInt &nrval, Bool *&values)
Read in values as written by the function put.
AipsIO & getnew (uInt &nrval, Char *&values)
AipsIO & getnew (uInt &nrval, uChar *&values)
AipsIO & getnew (uInt &nrval, short *&values)
AipsIO & getnew (uInt &nrval, unsigned short *&values)
AipsIO & getnew (uInt &nrval, int *&values)
AipsIO & getnew (uInt &nrval, unsigned int *&values)
AipsIO & getnew (uInt &nrval, Int64 *&values)
AipsIO & getnew (uInt &nrval, uInt64 *&values)
AipsIO & getnew (uInt &nrval, float *&values)
AipsIO & getnew (uInt &nrval, double *&values)
AipsIO & getnew (uInt &nrval, Complex *&values)
AipsIO & getnew (uInt &nrval, DComplex *&values)
AipsIO & getnew (uInt &nrval, String *&values)
uInt getend ()
End reading an object.
Private Member Functions
void openInit (ByteIO::OpenOption)
Initialize everything for the open.
void testput ()
Test if put is possible (throw exception if not).
void testget ()
Test if get is possible (throw exception if not).
void testgetLength ()
Test if get did not exceed object.
void testputerr ()
Throw exception for testput.
void testgeterr ()
Throw exception for testget.
void testgeterrLength ()
Throw exception for testgetLength.
Private Attributes
Int opened_p
1 = file was opened by AipsIO 0 = file not opened -1 = file opened by user (=fd passed)
ByteIO::OpenOption fopt_p
File open option.
int swput_p
<0 = not opened for put 0 = no putstart done >0 = put is possible
int swget_p
<0 = not opened for get 0 = no getstart done >0 = get is possible
uInt level_p
Nested object level.
uInt maxlev_p
Current size of objlen and objptr.
Block< uInt > objlen_p
Object length at each level.
Block< uInt > objtln_p
Object length to be read at each level.
Block< Int64 > objptr_p
Offset of length at each level.
Bool hasCachedType_p
True = the object type has already been read.
String objectType_p
The cached object type.
ByteIO * file_p
The file object.
TypeIO * io_p
The actual IO object.
Bool seekable_p
Is the file is seekable?
Static Private Attributes
static const uInt magicval_p
magic value to check sync.
Detailed Description
AipsIO is the object persistency mechanism of Casacore.
Intended use:
Public interface
Review Status
Reviewed By:
ghunt
Date Reviewed:
95Feb21
Etymology
AipsIO is simply the conventional shorthand for "AIPS++ input/output". Note that Casacore is the successor of the old AIPS++ project.
Synopsis
AipsIO is a class designed to do I/O for objects. It reads/writes the data using a class derived from TypeIO. For instance, class CanonicalIO can be used to read/write the data in canonical format.
The TypeIO class in its turn uses a class derived from ByteIO to determine where the data has to be written.
An object is written by writing all its data members. It will be preceeded by a header containing type and version. The I/O can be done via de overloaded << and >> operators to write or read a single item (e.g., an int or an object). These operators are already defined for all built-in data types and for Complex, DComplex, String, and Bool. Since each enumeration is a specific type, it is hard to handle them. Casting to Bool (which is also an enumerated type) is a possibility, but that assumes that each enumerated type has the same size (which is probably true for all compilers). Another possibility is to store it in an int when writing. Reading can be done the opposite way, although the ARM says that an int cannot be assigned to an enumerated type.
There are also functions put, get and getnew to write or read an array of values. These functions are defined for the same data types as << and >> (so one can write, for example, an array of Strings). AipsIO.put (nr, arr) writes nr values from the given array. AipsIO.get (nr, arr) reads nr values into the given user-supplied array. AipsIO.getnew (&nr, &arr) reads the number of values written into a new array allocated on the heap. It returns the nr of values read and a pointer to the array. The data must be read back in the same order as it was written.
The functions putstart(type,version) and putend() must be called before resp. after writing all values of the object. It stores the given type and version of the object. Similarly getstart(type) and getend() must be called. getstart checks the type and returns the version. By using the version the read function of the object can convert older versions of the object (which may still reside on disk) to the latest version. The function getNextType is available to get the type of the next object stored. This can be used to check the type or to open (i.e. issue a getstart) in the correct way.
When implementing a class, one should also define the operators << and >> for the class to allow users to write or read an object in this simple way (e.g., as io >> obj; to read an object). One has to define the friend functions:
friend AipsIO& operator<< (AipsIO&, const YourClass&);
friend AipsIO& operator>> (AipsIO&, YourClass&);
since they cannot be stored in the class itself. The type of an object is usually passed as the class name.
AipsIO& operator<< (AipsIO& ios, const YourClass& object) {
ios.putstart ("YourClass", version);
ios <<....;
ios.putend ();
}
The functions getpos() and setpos(offset) can be used to get and set the offset in the file to a given point. They can be used to point to a position in the file where an object must be written or read. Obviously these functions are to be used by a storage manager and are not for public use. Someday they should be made private with a friend defined.
Example
MyClass myObject(...);                   // some object
AipsIO ios("file.name", ByteIO::New);    // create new file
ios << myObject;                         // write object
MyClass myObject2;
ios >> myObject2;                        // read it back
This example creates an object, writes it to AipsIO and reads it back into another object. The shift functions for MyClass could be defined as follows:
AipsIO& operator<< (AipsIO& ios, const MyClass& myObject)
{
ios.putstart ("MyClass", 1);    // MyClass version 1
ios <<...;                     // write all data members
ios.putend();
}
AipsIO& operator>> (AipsIO& ios, const MyClass& myObject)
{
// If needed, delete current data members first.
// Now read in the object.
uInt version = ios.getstart ("MyClass");
ios >>...;                     // read all data members
ios.getend();
}
In this example the version is not used. In more complex objects it will probably be used when data members get added or changed in future versions of a software system.
Definition at line 168 of file AipsIO.h.
Constructor & Destructor Documentation
casacore::AipsIO::AipsIO ()
No file attached yet.
casacore::AipsIO::AipsIO (const String & fileName, ByteIO::OpenOption = ByteIO::Old, uInt filebufSize = 65536, /uInt filebufSize = 1048576, */MultiFileBase * mfile = 0) explicit
Construct and open/create a file with the given name.
The actual IO is done via a CanonicalIO object on a regular file using buffered IO with a buffer of the given size.
If the MultiFileBase pointer is not null, a virtual file in the MultiFileBase will be used instead of a regular file.
casacore::AipsIO::AipsIO (ByteIO *) explicit
Construct from a stream object derived from ByteIO.
This can for instance by used to use AipsIO on a file descriptor for which a FilebufIO object has been created. The actual IO is done via a CanonicalIO object on top of it.
casacore::AipsIO::AipsIO (TypeIO *) explicit
Construct from a stream object derived from TypeIO, thus from a stream on top of ByteIOn doing the possible conversions.
casacore::AipsIO::~AipsIO ()
Close if not done yet.
Member Function Documentation
void casacore::AipsIO::close ()
Close file opened.
ByteIO::OpenOption casacore::AipsIO::fileOption () const inline
Return the file option.
Definition at line 467 of file AipsIO.h.
References fopt_p.
AipsIO& casacore::AipsIO::get (uInt nrval, Bool * values)
Read in nrval values into the user-supplied values buffer.
The buffer must be long enough.
AipsIO& casacore::AipsIO::get (uInt nrval, Char * values)
AipsIO& casacore::AipsIO::get (uInt nrval, uChar * values)
AipsIO& casacore::AipsIO::get (uInt nrval, short * values)
AipsIO& casacore::AipsIO::get (uInt nrval, unsigned short * values)
AipsIO& casacore::AipsIO::get (uInt nrval, int * values)
AipsIO& casacore::AipsIO::get (uInt nrval, unsigned int * values)
AipsIO& casacore::AipsIO::get (uInt nrval, Int64 * values)
AipsIO& casacore::AipsIO::get (uInt nrval, uInt64 * values)
AipsIO& casacore::AipsIO::get (uInt nrval, float * values)
AipsIO& casacore::AipsIO::get (uInt nrval, double * values)
AipsIO& casacore::AipsIO::get (uInt nrval, Complex * values)
AipsIO& casacore::AipsIO::get (uInt nrval, DComplex * values)
AipsIO& casacore::AipsIO::get (uInt nrval, String * values)
template<typename T > AipsIO& casacore::AipsIO::get (vector< T > & vec) inline
Get a vector as an array of values (similar to getnew).
It resizes the vector as needed.
Definition at line 359 of file AipsIO.h.
AipsIO& casacore::AipsIO::get (vector< Bool > & vec)
uInt casacore::AipsIO::getend ()
End reading an object.
It returns the object length (including possible nested objects). It checks if the entire object has been read (to keep the data stream in sync). If not, an exception is thrown.
AipsIO& casacore::AipsIO::getnew (uInt & nrval, Bool *& values)
Read in values as written by the function put.
It will read the number of values (into nrval), allocate a values buffer of that length and read the values into that buffer. A pointer to the buffer is returned into values. <warn=caution> Although the buffer is allocated by this function, the user has to delete it (using delete [] values;).
AipsIO& casacore::AipsIO::getnew (uInt & nrval, Char *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, uChar *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, short *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, unsigned short *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, int *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, unsigned int *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, Int64 *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, uInt64 *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, float *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, double *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, Complex *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, DComplex *& values)
AipsIO& casacore::AipsIO::getnew (uInt & nrval, String *& values)
const String& casacore::AipsIO::getNextType ()
Get the type of the next object stored.
This is not possible if a put is in progress.
Int64 casacore::AipsIO::getpos ()
Get and set file-offset.
uInt casacore::AipsIO::getstart (const String & objectType)
Start reading an object.
It will check if the given type matches the one stored by putstart. It returns the object version which can be used to read in older version of the object correctly.
After all values (inclusing nested objects) of the object have been read, a call to getend has to be done.
uInt casacore::AipsIO::getstart (const Char * objectType)
void casacore::AipsIO::open (const String & fileName, ByteIO::OpenOption = ByteIO::Old, uInt filebufSize = 65536, MultiFileBase * mfile = 0)
Open/create file (either a regular file or a MultiFileBase virtual file).
An exception is thrown if the object contains an already open file.
void casacore::AipsIO::open (ByteIO *)
Open by connecting to the given byte stream.
This can for instance by used to use AipsIO on a file descriptor for which a FilebufIO object has been created. The actual IO is done via a CanonicalIO object on top of it. An exception is thrown if the object contains an already open file.
void casacore::AipsIO::open (TypeIO *)
Open by connecting to the given typed byte stream.
An exception is thrown if the object contains an already open file.
void casacore::AipsIO::openInit (ByteIO::OpenOption) private
Initialize everything for the open.
It checks if there is no outstanding open file.
AipsIO& casacore::AipsIO::operator<< (const Bool & value)
Put a single value.
AipsIO& casacore::AipsIO::operator<< (const Char & value)
AipsIO& casacore::AipsIO::operator<< (const uChar & value)
AipsIO& casacore::AipsIO::operator<< (const short & value)
AipsIO& casacore::AipsIO::operator<< (const unsigned short & value)
AipsIO& casacore::AipsIO::operator<< (const int & value)
AipsIO& casacore::AipsIO::operator<< (const unsigned int & value)
AipsIO& casacore::AipsIO::operator<< (const Int64 & value)
AipsIO& casacore::AipsIO::operator<< (const uInt64 & value)
AipsIO& casacore::AipsIO::operator<< (const float & value)
AipsIO& casacore::AipsIO::operator<< (const double & value)
AipsIO& casacore::AipsIO::operator<< (const Complex & value)
AipsIO& casacore::AipsIO::operator<< (const DComplex & value)
AipsIO& casacore::AipsIO::operator<< (const String & value)
AipsIO& casacore::AipsIO::operator<< (const Char * value)
AipsIO& casacore::AipsIO::operator>> (Bool & value)
Get a single value.
AipsIO& casacore::AipsIO::operator>> (Char & value)
AipsIO& casacore::AipsIO::operator>> (uChar & value)
AipsIO& casacore::AipsIO::operator>> (short & value)
AipsIO& casacore::AipsIO::operator>> (unsigned short & value)
AipsIO& casacore::AipsIO::operator>> (int & value)
AipsIO& casacore::AipsIO::operator>> (unsigned int & value)
AipsIO& casacore::AipsIO::operator>> (Int64 & value)
AipsIO& casacore::AipsIO::operator>> (uInt64 & value)
AipsIO& casacore::AipsIO::operator>> (float & value)
AipsIO& casacore::AipsIO::operator>> (double & value)
AipsIO& casacore::AipsIO::operator>> (Complex & value)
AipsIO& casacore::AipsIO::operator>> (DComplex & value)
AipsIO& casacore::AipsIO::operator>> (String & value)
AipsIO& casacore::AipsIO::put (uInt nrval, const Bool * values, Bool putNR = True)
Put an array of values with the given number of values.
If the flag putNr is set, the number of values is put first.
AipsIO& casacore::AipsIO::put (uInt nrval, const Char * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const uChar * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const short * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const unsigned short * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const int * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const unsigned int * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const Int64 * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const uInt64 * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const float * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const double * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const Complex * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const DComplex * values, Bool putNR = True)
AipsIO& casacore::AipsIO::put (uInt nrval, const String * values, Bool putNR = True)
template<typename T > AipsIO& casacore::AipsIO::put (const vector< T > & vec) inline
Put a vector as an array of values For standard types it has the same result as put with putNR=True.
Definition at line 281 of file AipsIO.h.
AipsIO& casacore::AipsIO::put (const vector< Bool > & vec)
uInt casacore::AipsIO::putend ()
End putting an object.
It returns the object length (including possible nested objects).
uInt casacore::AipsIO::putstart (const String & objectType, uInt objectVersion)
Start putting an object.
This writes the object type and version. When reading back getstart calls have to be done in the same way. Getstart checks the type and returns the version. The user can use that to correctly read back objects with different versions.
Data in the outermost object cannot be put before a putstart is done. Data in nested objects can be put without an intermediate putstart. However, for complex objects it is recommended to do a putstart to have a better checking.
After all values (inclusing nested objects) of the object have been put, a call to putend has to be done.
uInt casacore::AipsIO::putstart (const Char * objectType, uInt objectVersion)
Int64 casacore::AipsIO::setpos (Int64 offset)
void casacore::AipsIO::testget () inline private
Test if get is possible (throw exception if not).
Definition at line 480 of file AipsIO.h.
References swget_p, and testgeterr().
void casacore::AipsIO::testgeterr () private
Throw exception for testget.
Referenced by testget().
void casacore::AipsIO::testgeterrLength () private
Throw exception for testgetLength.
Referenced by testgetLength().
void casacore::AipsIO::testgetLength () inline private
Test if get did not exceed object.
Definition at line 486 of file AipsIO.h.
References level_p, objlen_p, objtln_p, and testgeterrLength().
void casacore::AipsIO::testput () inline private
Test if put is possible (throw exception if not).
testput tests if a put can be done; ie.
if putstart has been done. It throws an exception if not. testget is similar to test if a get can be done.
Definition at line 474 of file AipsIO.h.
References swput_p, and testputerr().
void casacore::AipsIO::testputerr () private
Throw exception for testput.
Referenced by testput().
Member Data Documentation
ByteIO* casacore::AipsIO::file_p private
The file object.
Definition at line 455 of file AipsIO.h.
ByteIO::OpenOption casacore::AipsIO::fopt_p private
File open option.
Definition at line 431 of file AipsIO.h.
Referenced by fileOption().
Bool casacore::AipsIO::hasCachedType_p private
True = the object type has already been read.
Definition at line 451 of file AipsIO.h.
TypeIO* casacore::AipsIO::io_p private
The actual IO object.
Definition at line 457 of file AipsIO.h.
uInt casacore::AipsIO::level_p private
Nested object level.
Definition at line 441 of file AipsIO.h.
Referenced by testgetLength().
const uInt casacore::AipsIO::magicval_p static private
magic value to check sync.
Definition at line 461 of file AipsIO.h.
uInt casacore::AipsIO::maxlev_p private
Current size of objlen and objptr.
Definition at line 443 of file AipsIO.h.
String casacore::AipsIO::objectType_p private
The cached object type.
Definition at line 453 of file AipsIO.h.
Block<uInt> casacore::AipsIO::objlen_p private
Object length at each level.
Definition at line 445 of file AipsIO.h.
Referenced by testgetLength().
Block<Int64> casacore::AipsIO::objptr_p private
Offset of length at each level.
Definition at line 449 of file AipsIO.h.
Block<uInt> casacore::AipsIO::objtln_p private
Object length to be read at each level.
Definition at line 447 of file AipsIO.h.
Referenced by testgetLength().
Int casacore::AipsIO::opened_p private
1 = file was opened by AipsIO 0 = file not opened -1 = file opened by user (=fd passed)
Definition at line 429 of file AipsIO.h.
Bool casacore::AipsIO::seekable_p private
Is the file is seekable?
Definition at line 459 of file AipsIO.h.
int casacore::AipsIO::swget_p private
<0 = not opened for get 0 = no getstart done >0 = get is possible
Definition at line 439 of file AipsIO.h.
Referenced by testget().
int casacore::AipsIO::swput_p private
<0 = not opened for put 0 = no putstart done >0 = put is possible
Definition at line 435 of file AipsIO.h.
Referenced by testput().
The documentation for this class was generated from the following file:
casa/IO/AipsIO.h