casacore: casacore::LECanonicalConversion Class Reference
casacore::LECanonicalConversion Class Reference
OS_module
A class with static functions to convert little endian canonical format.
#include <LECanonicalConversion.h>
Static Public Member Functions
static size_t toLocal (char &to, const void *from)
Convert one value from canonical format to local format.
static size_t toLocal (unsigned char &to, const void *from)
static size_t toLocal (short &to, const void *from)
static size_t toLocal (unsigned short &to, const void *from)
static size_t toLocal (int &to, const void *from)
static size_t toLocal (unsigned int &to, const void *from)
static size_t toLocal (Int64 &to, const void *from)
static size_t toLocal (uInt64 &to, const void *from)
static size_t toLocal (float &to, const void *from)
static size_t toLocal (double &to, const void *from)
static size_t fromLocal (void *to, const char &from)
Convert one value from local format to canonical format.
static size_t fromLocal (void *to, const unsigned char &from)
static size_t fromLocal (void *to, const short &from)
static size_t fromLocal (void *to, const unsigned short &from)
static size_t fromLocal (void *to, const int &from)
static size_t fromLocal (void *to, const unsigned int &from)
static size_t fromLocal (void *to, const Int64 &from)
static size_t fromLocal (void *to, const uInt64 &from)
static size_t fromLocal (void *to, const float &from)
static size_t fromLocal (void *to, const double &from)
static size_t toLocal (char *to, const void *from, size_t nr)
Convert nr values from canonical format to local format.
static size_t toLocal (unsigned char *to, const void *from, size_t nr)
static size_t toLocal (short *to, const void *from, size_t nr)
static size_t toLocal (unsigned short *to, const void *from, size_t nr)
static size_t toLocal (int *to, const void *from, size_t nr)
static size_t toLocal (unsigned int *to, const void *from, size_t nr)
static size_t toLocal (Int64 *to, const void *from, size_t nr)
static size_t toLocal (uInt64 *to, const void *from, size_t nr)
static size_t toLocal (float *to, const void *from, size_t nr)
static size_t toLocal (double *to, const void *from, size_t nr)
static size_t fromLocal (void *to, const char *from, size_t nr)
Convert nr values from local format to canonical format.
static size_t fromLocal (void *to, const unsigned char *from, size_t nr)
static size_t fromLocal (void *to, const short *from, size_t nr)
static size_t fromLocal (void *to, const unsigned short *from, size_t nr)
static size_t fromLocal (void *to, const int *from, size_t nr)
static size_t fromLocal (void *to, const unsigned int *from, size_t nr)
static size_t fromLocal (void *to, const Int64 *from, size_t nr)
static size_t fromLocal (void *to, const uInt64 *from, size_t nr)
static size_t fromLocal (void *to, const float *from, size_t nr)
static size_t fromLocal (void *to, const double *from, size_t nr)
static size_t toLocalChar (void *to, const void *from, size_t nr)
Convert nr values from canonical format to local format.
static size_t toLocalUChar (void *to, const void *from, size_t nr)
static size_t toLocalShort (void *to, const void *from, size_t nr)
static size_t toLocalUShort (void *to, const void *from, size_t nr)
static size_t toLocalInt (void *to, const void *from, size_t nr)
static size_t toLocalUInt (void *to, const void *from, size_t nr)
static size_t toLocalInt64 (void *to, const void *from, size_t nr)
static size_t toLocalUInt64 (void *to, const void *from, size_t nr)
static size_t toLocalFloat (void *to, const void *from, size_t nr)
static size_t toLocalDouble (void *to, const void *from, size_t nr)
static size_t fromLocalChar (void *to, const void *from, size_t nr)
Convert nr values from local format to canonical format.
static size_t fromLocalUChar (void *to, const void *from, size_t nr)
static size_t fromLocalShort (void *to, const void *from, size_t nr)
static size_t fromLocalUShort (void *to, const void *from, size_t nr)
static size_t fromLocalInt (void *to, const void *from, size_t nr)
static size_t fromLocalUInt (void *to, const void *from, size_t nr)
static size_t fromLocalInt64 (void *to, const void *from, size_t nr)
static size_t fromLocalUInt64 (void *to, const void *from, size_t nr)
static size_t fromLocalFloat (void *to, const void *from, size_t nr)
static size_t fromLocalDouble (void *to, const void *from, size_t nr)
static void * byteToLocalChar (void *to, const void *from, size_t nrbytes)
Convert values from canonical format to local format.
static void * byteToLocalUChar (void *to, const void *from, size_t nrbytes)
static void * byteToLocalShort (void *to, const void *from, size_t nrbytes)
static void * byteToLocalUShort (void *to, const void *from, size_t nrbytes)
static void * byteToLocalInt (void *to, const void *from, size_t nrbytes)
static void * byteToLocalUInt (void *to, const void *from, size_t nrbytes)
static void * byteToLocalInt64 (void *to, const void *from, size_t nrbytes)
static void * byteToLocalUInt64 (void *to, const void *from, size_t nrbytes)
static void * byteToLocalFloat (void *to, const void *from, size_t nrbytes)
static void * byteToLocalDouble (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalChar (void *to, const void *from, size_t nrbytes)
Convert values from local format to canonical format.
static void * byteFromLocalUChar (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalShort (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalUShort (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalInt (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalUInt (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalInt64 (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalUInt64 (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalFloat (void *to, const void *from, size_t nrbytes)
static void * byteFromLocalDouble (void *to, const void *from, size_t nrbytes)
static Conversion::ValueFunction * getToLocal (const char *)
Get the value conversion function for the given type.
static Conversion::ValueFunction * getToLocal (const unsigned char *)
static Conversion::ValueFunction * getToLocal (const short *)
static Conversion::ValueFunction * getToLocal (const unsigned short *)
static Conversion::ValueFunction * getToLocal (const int *)
static Conversion::ValueFunction * getToLocal (const unsigned int *)
static Conversion::ValueFunction * getToLocal (const Int64 *)
static Conversion::ValueFunction * getToLocal (const uInt64 *)
static Conversion::ValueFunction * getToLocal (const float *)
static Conversion::ValueFunction * getToLocal (const double *)
static Conversion::ValueFunction * getFromLocal (const char *)
static Conversion::ValueFunction * getFromLocal (const unsigned char *)
static Conversion::ValueFunction * getFromLocal (const short *)
static Conversion::ValueFunction * getFromLocal (const unsigned short *)
static Conversion::ValueFunction * getFromLocal (const int *)
static Conversion::ValueFunction * getFromLocal (const unsigned int *)
static Conversion::ValueFunction * getFromLocal (const Int64 *)
static Conversion::ValueFunction * getFromLocal (const uInt64 *)
static Conversion::ValueFunction * getFromLocal (const float *)
static Conversion::ValueFunction * getFromLocal (const double *)
static Conversion::ByteFunction * getByteToLocal (const char *)
Get the byte conversion function for the given type.
static Conversion::ByteFunction * getByteToLocal (const unsigned char *)
static Conversion::ByteFunction * getByteToLocal (const short *)
static Conversion::ByteFunction * getByteToLocal (const unsigned short *)
static Conversion::ByteFunction * getByteToLocal (const int *)
static Conversion::ByteFunction * getByteToLocal (const unsigned int *)
static Conversion::ByteFunction * getByteToLocal (const Int64 *)
static Conversion::ByteFunction * getByteToLocal (const uInt64 *)
static Conversion::ByteFunction * getByteToLocal (const float *)
static Conversion::ByteFunction * getByteToLocal (const double *)
static Conversion::ByteFunction * getByteFromLocal (const char *)
static Conversion::ByteFunction * getByteFromLocal (const unsigned char *)
static Conversion::ByteFunction * getByteFromLocal (const short *)
static Conversion::ByteFunction * getByteFromLocal (const unsigned short *)
static Conversion::ByteFunction * getByteFromLocal (const int *)
static Conversion::ByteFunction * getByteFromLocal (const unsigned int *)
static Conversion::ByteFunction * getByteFromLocal (const Int64 *)
static Conversion::ByteFunction * getByteFromLocal (const uInt64 *)
static Conversion::ByteFunction * getByteFromLocal (const float *)
static Conversion::ByteFunction * getByteFromLocal (const double *)
static unsigned int canonicalSize (const char *)
Return the canonical length for the various data types.
static unsigned int canonicalSize (const unsigned char *)
static unsigned int canonicalSize (const short *)
static unsigned int canonicalSize (const unsigned short *)
static unsigned int canonicalSize (const int *)
static unsigned int canonicalSize (const unsigned int *)
static unsigned int canonicalSize (const Int64 *)
static unsigned int canonicalSize (const uInt64 *)
static unsigned int canonicalSize (const float *)
static unsigned int canonicalSize (const double *)
static void reverse2 (void *to, const void *from)
Reverse 2 bytes.
static void reverse4 (void *to, const void *from)
Reverse 4 bytes.
static void reverse8 (void *to, const void *from)
Reverse 8 bytes.
static void move2 (void *to, const void *from)
Move 2 bytes.
static void move4 (void *to, const void *from)
Move 4 bytes.
static void move8 (void *to, const void *from)
Move 8 bytes.
Private Member Functions
LECanonicalConversion ()
This class should not be constructed (so declare the constructor private).
Detailed Description
A class with static functions to convert little endian canonical format.
@anchor LECanonicalConversion_summary
Intended use:
Public interface
Review Status
Reviewed By:
Friso Olnon
Date Reviewed:
1996/11/06
Test programs:
tLECanonicalConversion
Synopsis
This class consists of several static functions to convert data from local (=native) format to a little endian canonical format. The canonical length of each data type is:
- Bool: 1 bit
- char: 1 byte
- short: 2 bytes
- int: 4 bytes
- Int64: 8 bytes
- float: 4 bytes
- double: 8 bytes
This canonical format is little-endian IEEE format, so on PCs the conversion is only a copy operation. On e.g. SUNs however, it involves a byte swap to convert from little endian to big endian.
The class also contains conversion functions making it possible to specify the number of bytes (in local format) instead of the number of values. These functions are included to make it possible to have the same signature as memcpy.
The current implementation of this class works on big- and little-endian machines using IEEE format. When using on other machines (e.g. VAX) the toLocal and fromLocal functions have to be changed.
Note that no functions are provided to handle Bools. Instead class Conversion provides functions to convert Bools to/from bits.
Example
void someFunction (const uInt* data, uInt nrval)
{
char* buffer = new char[nrval*LECanonicalConversion::canonicalSize(data)];
LECanonicalConversion::fromLocal (buffer, data, nrval);
...\.
delete [] buffer;
}
Motivation
Casacore data will often be stored in a canonical format. To read these data conversion functions are needed. However, these functions do not use any other Casacore classes, so they can easily be used in any other software system.
To Do
Support data type long double.
Definition at line 159 of file LECanonicalConversion.h.
Constructor & Destructor Documentation
casacore::LECanonicalConversion::LECanonicalConversion () private
This class should not be constructed (so declare the constructor private).
Member Function Documentation
static void* casacore::LECanonicalConversion::byteFromLocalChar (void * to, const void * from, size_t nrbytes) static
Convert values from local format to canonical format.
The from and to buffer should not overlap. The number of values involved is determined from the argument nrbytes, which gives the number of bytes in local format. The signature of this function is the same as memcpy, so that memcpy can directly be used if no conversion is needed.
static void* casacore::LECanonicalConversion::byteFromLocalDouble (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalFloat (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalShort (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalUChar (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalUInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalUInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteFromLocalUShort (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalChar (void * to, const void * from, size_t nrbytes) static
Convert values from canonical format to local format.
The from and to buffer should not overlap. The number of values involved is determined from the argument nrbytes, which gives the number of bytes in local format. The signature of this function is the same as memcpy, so that memcpy can directly be used if no conversion is needed.
static void* casacore::LECanonicalConversion::byteToLocalDouble (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalFloat (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalShort (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalUChar (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalUInt (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalUInt64 (void * to, const void * from, size_t nrbytes) static
static void* casacore::LECanonicalConversion::byteToLocalUShort (void * to, const void * from, size_t nrbytes) static
unsigned int casacore::LECanonicalConversion::canonicalSize (const char *) inline static
Return the canonical length for the various data types.
Definition at line 952 of file LECanonicalConversion.h.
References SIZE_LECAN_CHAR.
unsigned int casacore::LECanonicalConversion::canonicalSize (const unsigned char *) inline static
Definition at line 954 of file LECanonicalConversion.h.
References SIZE_LECAN_UCHAR.
unsigned int casacore::LECanonicalConversion::canonicalSize (const short *) inline static
Definition at line 956 of file LECanonicalConversion.h.
References SIZE_LECAN_SHORT.
unsigned int casacore::LECanonicalConversion::canonicalSize (const unsigned short *) inline static
Definition at line 958 of file LECanonicalConversion.h.
References SIZE_LECAN_USHORT.
unsigned int casacore::LECanonicalConversion::canonicalSize (const int *) inline static
Definition at line 960 of file LECanonicalConversion.h.
References SIZE_LECAN_INT.
unsigned int casacore::LECanonicalConversion::canonicalSize (const unsigned int *) inline static
Definition at line 962 of file LECanonicalConversion.h.
References SIZE_LECAN_UINT.
unsigned int casacore::LECanonicalConversion::canonicalSize (const Int64 *) inline static
Definition at line 964 of file LECanonicalConversion.h.
References SIZE_LECAN_INT64.
unsigned int casacore::LECanonicalConversion::canonicalSize (const uInt64 *) inline static
Definition at line 966 of file LECanonicalConversion.h.
References SIZE_LECAN_UINT64.
unsigned int casacore::LECanonicalConversion::canonicalSize (const float *) inline static
Definition at line 968 of file LECanonicalConversion.h.
References SIZE_LECAN_FLOAT.
unsigned int casacore::LECanonicalConversion::canonicalSize (const double *) inline static
Definition at line 970 of file LECanonicalConversion.h.
References SIZE_LECAN_DOUBLE.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const char & from) inline static
Convert one value from local format to canonical format.
The from and to buffer should not overlap.
Definition at line 624 of file LECanonicalConversion.h.
References SIZE_LECAN_CHAR.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const unsigned char & from) inline static
Definition at line 630 of file LECanonicalConversion.h.
References SIZE_LECAN_UCHAR.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const short & from) inline static
Definition at line 637 of file LECanonicalConversion.h.
References move2(), reverse2(), and SIZE_LECAN_SHORT.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const unsigned short & from) inline static
Definition at line 648 of file LECanonicalConversion.h.
References move2(), reverse2(), and SIZE_LECAN_USHORT.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const int & from) inline static
Definition at line 659 of file LECanonicalConversion.h.
References move4(), reverse4(), and SIZE_LECAN_INT.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const unsigned int & from) inline static
Definition at line 670 of file LECanonicalConversion.h.
References move4(), reverse4(), and SIZE_LECAN_UINT.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const Int64 & from) inline static
Definition at line 681 of file LECanonicalConversion.h.
References move8(), reverse8(), and SIZE_LECAN_INT64.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const uInt64 & from) inline static
Definition at line 692 of file LECanonicalConversion.h.
References move8(), reverse8(), and SIZE_LECAN_UINT64.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const float & from) inline static
Definition at line 703 of file LECanonicalConversion.h.
References move4(), reverse4(), and SIZE_LECAN_FLOAT.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const double & from) inline static
Definition at line 714 of file LECanonicalConversion.h.
References move8(), reverse8(), and SIZE_LECAN_FLOAT.
size_t casacore::LECanonicalConversion::fromLocal (void * to, const char * from, size_t nr) inline static
Convert nr values from local format to canonical format.
The from and to buffer should not overlap.
Definition at line 787 of file LECanonicalConversion.h.
References fromLocalChar().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const unsigned char * from, size_t nr) inline static
Definition at line 793 of file LECanonicalConversion.h.
References fromLocalUChar().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const short * from, size_t nr) inline static
Definition at line 799 of file LECanonicalConversion.h.
References fromLocalShort().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const unsigned short * from, size_t nr) inline static
Definition at line 805 of file LECanonicalConversion.h.
References fromLocalUShort().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const int * from, size_t nr) inline static
Definition at line 811 of file LECanonicalConversion.h.
References fromLocalInt().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const unsigned int * from, size_t nr) inline static
Definition at line 817 of file LECanonicalConversion.h.
References fromLocalUInt().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const Int64 * from, size_t nr) inline static
Definition at line 823 of file LECanonicalConversion.h.
References fromLocalInt64().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const uInt64 * from, size_t nr) inline static
Definition at line 829 of file LECanonicalConversion.h.
References fromLocalUInt64().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const float * from, size_t nr) inline static
Definition at line 835 of file LECanonicalConversion.h.
References fromLocalFloat().
size_t casacore::LECanonicalConversion::fromLocal (void * to, const double * from, size_t nr) inline static
Definition at line 841 of file LECanonicalConversion.h.
References fromLocalDouble().
static size_t casacore::LECanonicalConversion::fromLocalChar (void * to, const void * from, size_t nr) static
Convert nr values from local format to canonical format.
The from and to buffer should not overlap.
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalDouble (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalFloat (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalInt (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalInt64 (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalShort (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalUChar (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalUInt (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalUInt64 (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static size_t casacore::LECanonicalConversion::fromLocalUShort (void * to, const void * from, size_t nr) static
Referenced by fromLocal().
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const char *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const unsigned char *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const short *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const unsigned short *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const int *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const unsigned int *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const Int64 *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const uInt64 *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const float *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteFromLocal (const double *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const char *) static
Get the byte conversion function for the given type.
The function memcpy is returned when a conversion is not needed.
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const unsigned char *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const short *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const unsigned short *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const int *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const unsigned int *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const Int64 *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const uInt64 *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const float *) static
static Conversion::ByteFunction* casacore::LECanonicalConversion::getByteToLocal (const double *) static
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const char *) inline static
Definition at line 901 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const unsigned char *) inline static
Definition at line 906 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const short *) inline static
Definition at line 911 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const unsigned short *) inline static
Definition at line 916 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const int *) inline static
Definition at line 921 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const unsigned int *) inline static
Definition at line 926 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const Int64 *) inline static
Definition at line 931 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const uInt64 *) inline static
Definition at line 936 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const float *) inline static
Definition at line 941 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getFromLocal (const double *) inline static
Definition at line 946 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const char *) inline static
Get the value conversion function for the given type.
Definition at line 850 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const unsigned char *) inline static
Definition at line 855 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const short *) inline static
Definition at line 860 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const unsigned short *) inline static
Definition at line 865 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const int *) inline static
Definition at line 870 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const unsigned int *) inline static
Definition at line 875 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const Int64 *) inline static
Definition at line 880 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const uInt64 *) inline static
Definition at line 885 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const float *) inline static
Definition at line 890 of file LECanonicalConversion.h.
Conversion::ValueFunction * casacore::LECanonicalConversion::getToLocal (const double *) inline static
Definition at line 895 of file LECanonicalConversion.h.
void casacore::LECanonicalConversion::move2 (void * to, const void * from) inline static
Move 2 bytes.
Definition at line 465 of file LECanonicalConversion.h.
Referenced by fromLocal(), and toLocal().
void casacore::LECanonicalConversion::move4 (void * to, const void * from) inline static
Move 4 bytes.
Definition at line 470 of file LECanonicalConversion.h.
Referenced by fromLocal(), and toLocal().
void casacore::LECanonicalConversion::move8 (void * to, const void * from) inline static
Move 8 bytes.
Definition at line 477 of file LECanonicalConversion.h.
Referenced by fromLocal(), and toLocal().
void casacore::LECanonicalConversion::reverse2 (void * to, const void * from) inline static
Reverse 2 bytes.
Definition at line 441 of file LECanonicalConversion.h.
Referenced by fromLocal(), and toLocal().
void casacore::LECanonicalConversion::reverse4 (void * to, const void * from) inline static
Reverse 4 bytes.
Definition at line 446 of file LECanonicalConversion.h.
Referenced by fromLocal(), and toLocal().
void casacore::LECanonicalConversion::reverse8 (void * to, const void * from) inline static
Reverse 8 bytes.
Definition at line 453 of file LECanonicalConversion.h.
Referenced by fromLocal(), and toLocal().
size_t casacore::LECanonicalConversion::toLocal (char & to, const void * from) inline static
Convert one value from canonical format to local format.
The from and to buffer should not overlap.
Definition at line 491 of file LECanonicalConversion.h.
References SIZE_LECAN_CHAR.
size_t casacore::LECanonicalConversion::toLocal (unsigned char & to, const void * from) inline static
Definition at line 498 of file LECanonicalConversion.h.
References SIZE_LECAN_UCHAR.
size_t casacore::LECanonicalConversion::toLocal (short & to, const void * from) inline static
Definition at line 505 of file LECanonicalConversion.h.
References move2(), reverse2(), and SIZE_LECAN_SHORT.
size_t casacore::LECanonicalConversion::toLocal (unsigned short & to, const void * from) inline static
Definition at line 523 of file LECanonicalConversion.h.
References move2(), reverse2(), and SIZE_LECAN_USHORT.
size_t casacore::LECanonicalConversion::toLocal (int & to, const void * from) inline static
Definition at line 537 of file LECanonicalConversion.h.
References move4(), reverse4(), and SIZE_LECAN_INT.
size_t casacore::LECanonicalConversion::toLocal (unsigned int & to, const void * from) inline static
Definition at line 555 of file LECanonicalConversion.h.
References move4(), reverse4(), and SIZE_LECAN_UINT.
size_t casacore::LECanonicalConversion::toLocal (Int64 & to, const void * from) inline static
Definition at line 569 of file LECanonicalConversion.h.
References move8(), reverse8(), and SIZE_LECAN_INT64.
size_t casacore::LECanonicalConversion::toLocal (uInt64 & to, const void * from) inline static
Definition at line 587 of file LECanonicalConversion.h.
References move8(), reverse8(), and SIZE_LECAN_UINT64.
size_t casacore::LECanonicalConversion::toLocal (float & to, const void * from) inline static
Definition at line 601 of file LECanonicalConversion.h.
References move4(), reverse4(), and SIZE_LECAN_FLOAT.
size_t casacore::LECanonicalConversion::toLocal (double & to, const void * from) inline static
Definition at line 612 of file LECanonicalConversion.h.
References move8(), reverse8(), and SIZE_LECAN_DOUBLE.
size_t casacore::LECanonicalConversion::toLocal (char * to, const void * from, size_t nr) inline static
Convert nr values from canonical format to local format.
The from and to buffer should not overlap.
Definition at line 726 of file LECanonicalConversion.h.
References toLocalChar().
size_t casacore::LECanonicalConversion::toLocal (unsigned char * to, const void * from, size_t nr) inline static
Definition at line 732 of file LECanonicalConversion.h.
References toLocalUChar().
size_t casacore::LECanonicalConversion::toLocal (short * to, const void * from, size_t nr) inline static
Definition at line 738 of file LECanonicalConversion.h.
References toLocalShort().
size_t casacore::LECanonicalConversion::toLocal (unsigned short * to, const void * from, size_t nr) inline static
Definition at line 744 of file LECanonicalConversion.h.
References toLocalUShort().
size_t casacore::LECanonicalConversion::toLocal (int * to, const void * from, size_t nr) inline static
Definition at line 750 of file LECanonicalConversion.h.
References toLocalInt().
size_t casacore::LECanonicalConversion::toLocal (unsigned int * to, const void * from, size_t nr) inline static
Definition at line 756 of file LECanonicalConversion.h.
References toLocalUInt().
size_t casacore::LECanonicalConversion::toLocal (Int64 * to, const void * from, size_t nr) inline static
Definition at line 762 of file LECanonicalConversion.h.
References toLocalInt64().
size_t casacore::LECanonicalConversion::toLocal (uInt64 * to, const void * from, size_t nr) inline static
Definition at line 768 of file LECanonicalConversion.h.
References toLocalUInt64().
size_t casacore::LECanonicalConversion::toLocal (float * to, const void * from, size_t nr) inline static
Definition at line 774 of file LECanonicalConversion.h.
References toLocalFloat().
size_t casacore::LECanonicalConversion::toLocal (double * to, const void * from, size_t nr) inline static
Definition at line 780 of file LECanonicalConversion.h.
References toLocalDouble().
static size_t casacore::LECanonicalConversion::toLocalChar (void * to, const void * from, size_t nr) static
Convert nr values from canonical format to local format.
The from and to buffer should not overlap.
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalDouble (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalFloat (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalInt (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalInt64 (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalShort (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalUChar (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalUInt (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalUInt64 (void * to, const void * from, size_t nr) static
Referenced by toLocal().
static size_t casacore::LECanonicalConversion::toLocalUShort (void * to, const void * from, size_t nr) static
Referenced by toLocal().
The documentation for this class was generated from the following file:
casa/OS/LECanonicalConversion.h