casacore: Class uvector and related functions.
Class uvector and related functions.
Classes
class ao::uvector< Tp, Alloc >
A container similar to std::vector, but one that allows construction without initializing its elements.
Functions
template<class Tp , class Alloc >
bool ao::operator== (const uvector< Tp, Alloc > &lhs, const uvector< Tp, Alloc > &rhs) noexcept
Compare two uvectors for equality.
template<class Tp , class Alloc >
bool ao::operator!= (const uvector< Tp, Alloc > &lhs, const uvector< Tp, Alloc > &rhs) noexcept
Compare two uvectors for inequality.
template<class Tp , class Alloc >
bool ao::operator< (const uvector< Tp, Alloc > &lhs, const uvector< Tp, Alloc > &rhs) noexcept
Compare two uvectors for smaller than.
template<class Tp , class Alloc >
bool ao::operator<= (const uvector< Tp, Alloc > &lhs, const uvector< Tp, Alloc > &rhs) noexcept
Compare two uvectors for smaller than or equal.
template<class Tp , class Alloc >
bool ao::operator> (const uvector< Tp, Alloc > &lhs, const uvector< Tp, Alloc > &rhs) noexcept
Compare two uvectors for larger than.
template<class Tp , class Alloc >
bool ao::operator>= (const uvector< Tp, Alloc > &lhs, const uvector< Tp, Alloc > &rhs) noexcept
Compare two uvectors for larger than or equal.
template<class Tp , class Alloc >
void ao::swap (uvector< Tp, Alloc > &x, uvector< Tp, Alloc > &y)
Swap the contents of the two uvectors.
Detailed Description
Function Documentation
template<class Tp , class Alloc > bool ao::operator!= (const uvector< Tp, Alloc > & lhs, const uvector< Tp, Alloc > & rhs) inline noexcept
Compare two uvectors for inequality.
Definition at line 1162 of file uvector.h.
template<class Tp , class Alloc > bool ao::operator< (const uvector< Tp, Alloc > & lhs, const uvector< Tp, Alloc > & rhs) inline noexcept
Compare two uvectors for smaller than.
If two uvectors compare equal up to the length of one, the uvector with the smallest size is consider to be smaller.
Definition at line 1172 of file uvector.h.
References casacore::min().
template<class Tp , class Alloc > bool ao::operator<= (const uvector< Tp, Alloc > & lhs, const uvector< Tp, Alloc > & rhs) inline noexcept
Compare two uvectors for smaller than or equal.
If two uvectors compare equal up to the length of one, the uvector with the smallest size is consider to be smaller.
Definition at line 1190 of file uvector.h.
References casacore::min().
template<class Tp , class Alloc > bool ao::operator== (const uvector< Tp, Alloc > & lhs, const uvector< Tp, Alloc > & rhs) inline noexcept
Compare two uvectors for equality.
Definition at line 1155 of file uvector.h.
template<class Tp , class Alloc > bool ao::operator> (const uvector< Tp, Alloc > & lhs, const uvector< Tp, Alloc > & rhs) inline noexcept
Compare two uvectors for larger than.
If two uvectors compare equal up to the length of one, the uvector with the smallest size is consider to be smaller.
Definition at line 1208 of file uvector.h.
template<class Tp , class Alloc > bool ao::operator>= (const uvector< Tp, Alloc > & lhs, const uvector< Tp, Alloc > & rhs) inline noexcept
Compare two uvectors for larger than or equal.
If two uvectors compare equal up to the length of one, the uvector with the smallest size is consider to be smaller.
Definition at line 1218 of file uvector.h.
template<class Tp , class Alloc > void ao::swap (uvector< Tp, Alloc > & x, uvector< Tp, Alloc > & y) inline
Swap the contents of the two uvectors.
Iterators to both vectors will remain valid and will point into to the swapped container afterwards. This function will never reallocate space.
The allocator will be swapped when the propagate_on_container_swap of the respective allocator_trait is true_type. Its behaviour is undefined when the allocators do not compare equal and propagate_on_container_swap is false.
Definition at line 1234 of file uvector.h.
References ao::uvector< Tp, Alloc >::swap().