casacore: BasicSL_module
BasicSL_module
casa package (libcasa_casa)
Classes and global functions for standard library use.
Modules
BasicSL_module_internal_classes
Internal BasicSL_module classes and functions.
Classes
struct casacore::Complex_global_functions_Complex_desc
Single and double precision complex numbers.
struct Complexfwd_global_functions_Complexfwd
Forward declaration complex classes.
class casacore::Dummy_Constants_class
Mathematical and numerical constants.
class casacore::IComplex
Integer complex numbers.
struct casacore::STLIO_global_functions_Container_IO
Input/output operators for STL-like containers.
struct casacore::STLMath_global_functions_Container_Math
Math operations on STL-like containers.
class casacore::SubString
SubString help class to be used in at, before,...
class casacore::String
String: the storage and methods of handling collections of characters.
struct casacore::String_global_functions_concatenator
Global concatenation operators.
struct casacore::String_global_functions_comparitor
Global comparison operators.
struct casacore::String_global_functions_split
Splitting Global function which splits the String into string array res at separator and returns the number of elements.
struct casacore::String_global_functions_common
Some general functions Functions to find special patterns, join and replicate.
struct casacore::String_global_functions_case
Casing and related functions Case conversion and rearrangement functions.
struct casacore::String_global_functions_io
IO.
Bool casacore::Complex_global_functions_Complex_desc::isNaN (const Complex &val)
Complex NaN and Infinity.
void casacore::Complex_global_functions_Complex_desc::setNaN (Complex &val)
Bool casacore::Complex_global_functions_Complex_desc::isInf (const Complex &val)
void casacore::Complex_global_functions_Complex_desc::setInf (Complex &val)
Bool casacore::Complex_global_functions_Complex_desc::isFinite (const Complex &val)
Bool casacore::Complex_global_functions_Complex_desc::operator>= (const Complex &left, const Complex &right)
Complex comparisons.
Bool casacore::Complex_global_functions_Complex_desc::operator> (const Complex &left, const Complex &right)
Bool casacore::Complex_global_functions_Complex_desc::operator<= (const Complex &left, const Complex &right)
Bool casacore::Complex_global_functions_Complex_desc::operator< (const Complex &left, const Complex &right)
Bool casacore::Complex_global_functions_Complex_desc::isNaN (const DComplex &val)
DComplex NaN and Infinity.
void casacore::Complex_global_functions_Complex_desc::setNaN (DComplex &val)
Bool casacore::Complex_global_functions_Complex_desc::isInf (const DComplex &val)
void casacore::Complex_global_functions_Complex_desc::setInf (DComplex &val)
Bool casacore::Complex_global_functions_Complex_desc::isFinite (const DComplex &val)
Bool casacore::Complex_global_functions_Complex_desc::operator>= (const DComplex &left, const DComplex &right)
DComplex comparisons.
Bool casacore::Complex_global_functions_Complex_desc::operator> (const DComplex &left, const DComplex &right)
Bool casacore::Complex_global_functions_Complex_desc::operator<= (const DComplex &left, const DComplex &right)
Bool casacore::Complex_global_functions_Complex_desc::operator< (const DComplex &left, const DComplex &right)
Double casacore::Complex_global_functions_Complex_desc::fabs (const DComplex &val)
Additional complex mathematical functions.
Bool casacore::Complex_global_functions_Complex_desc::near (const Complex &val1, const Complex &val2, Double tol=1.0e-5)
The near functions.
Float casacore::Complex_global_functions_Complex_desc::fabs (const Complex &val)
DComplex casacore::Complex_global_functions_Complex_desc::square (const DComplex &val)
Complex casacore::Complex_global_functions_Complex_desc::square (const Complex &val)
DComplex casacore::Complex_global_functions_Complex_desc::cube (const DComplex &val)
Complex casacore::Complex_global_functions_Complex_desc::cube (const Complex &val)
DComplex casacore::Complex_global_functions_Complex_desc::operator+ (const DComplex &d, const Complex &c)
ArrayMath::pow needs this pow function.
DComplex casacore::Complex_global_functions_Complex_desc::operator+ (const Complex &c, const DComplex &d)
DComplex casacore::Complex_global_functions_Complex_desc::operator- (const DComplex &d, const Complex &c)
DComplex casacore::Complex_global_functions_Complex_desc::operator- (const Complex &c, const DComplex &d)
Complex casacore::Complex_global_functions_Complex_desc::operator * (const Complex &val, Double f)
QMath and scimath need these operators * and /.
Complex casacore::Complex_global_functions_Complex_desc::operator * (Double f, const Complex &val)
Complex casacore::Complex_global_functions_Complex_desc::operator/ (const Complex &val, Double f)
Complex casacore::Complex_global_functions_Complex_desc::operator/ (Double f, const Complex &val)
Complex casacore::Complex_global_functions_Complex_desc::operator * (const Complex &val, Int f)
These operators are useful, otherwise both Float and Double are applicable for Ints.
Complex casacore::Complex_global_functions_Complex_desc::operator * (Int f, const Complex &val)
Complex casacore::Complex_global_functions_Complex_desc::operator/ (const Complex &val, Int f)
Complex casacore::Complex_global_functions_Complex_desc::operator/ (Int f, const Complex &val)
Bool casacore::Complex_global_functions_Complex_desc::near (const DComplex &val1, const DComplex &val2, Double tol=1.0e-13)
Bool casacore::Complex_global_functions_Complex_desc::nearAbs (const Complex &val1, const Complex &val2, Double tol=1.0e-5)
Bool casacore::Complex_global_functions_Complex_desc::nearAbs (const DComplex &val1, const DComplex &val2, Double tol=1.0e-13)
Bool casacore::Complex_global_functions_Complex_desc::allNear (const Complex &val1, const Complex &val2, Double tol=1.0e-5)
Bool casacore::Complex_global_functions_Complex_desc::allNear (const DComplex &val1, const DComplex &val2, Double tol=1.0e-13)
Bool casacore::Complex_global_functions_Complex_desc::allNearAbs (const Complex &val1, const Complex &val2, Double tol=1.0e-5)
Bool casacore::Complex_global_functions_Complex_desc::allNearAbs (const DComplex &val1, const DComplex &val2, Double tol=1.0e-13)
Complex casacore::Complex_global_functions_Complex_desc::max (const Complex &x, const Complex &y)
Max and min, floor and ceil functions.
DComplex casacore::Complex_global_functions_Complex_desc::max (const DComplex &x, const DComplex &y)
Complex casacore::Complex_global_functions_Complex_desc::min (const Complex &x, const Complex &y)
DComplex casacore::Complex_global_functions_Complex_desc::min (const DComplex &x, const DComplex &y)
Complex casacore::Complex_global_functions_Complex_desc::floor (const Complex &x)
DComplex casacore::Complex_global_functions_Complex_desc::floor (const DComplex &x)
Complex casacore::Complex_global_functions_Complex_desc::ceil (const Complex &x)
DComplex casacore::Complex_global_functions_Complex_desc::ceil (const DComplex &x)
DComplex casacore::Complex_global_functions_Complex_desc::fmod (const DComplex &in, const DComplex &f)
fmod
Complex casacore::Complex_global_functions_Complex_desc::fmod (const Complex &in, const Complex &f)
DComplex casacore::Complex_global_functions_Complex_desc::atan (const DComplex &in)
Inverse trigonometry.
Complex casacore::Complex_global_functions_Complex_desc::atan (const Complex &in)
DComplex casacore::Complex_global_functions_Complex_desc::asin (const DComplex &in)
Complex casacore::Complex_global_functions_Complex_desc::asin (const Complex &in)
DComplex casacore::Complex_global_functions_Complex_desc::acos (const DComplex &in)
Complex casacore::Complex_global_functions_Complex_desc::acos (const Complex &in)
DComplex casacore::Complex_global_functions_Complex_desc::atan2 (const DComplex &in, const DComplex &t2)
Complex casacore::Complex_global_functions_Complex_desc::atan2 (const Complex &in, const Complex &t2)
DComplex casacore::Complex_global_functions_Complex_desc::erf (const DComplex &in)
Error function.
Complex casacore::Complex_global_functions_Complex_desc::erf (const Complex &in)
DComplex casacore::Complex_global_functions_Complex_desc::erfc (const DComplex &in)
Complex casacore::Complex_global_functions_Complex_desc::erfc (const Complex &in)
Detailed Description
Classes and global functions for standard library use.
See below for an overview of the classes in this module.
Synopsis
This module is a bag of related standard library classes and global functions.
The following functionality is available:
Forward declarations
Complexfwd for complex numbers.
Class Complex to offer single and double precision complex numbers.
Class IComplex for integer complex numbers.
Value Constants to offer mathematical and numerical constants.
Class RegexBase to offer abstract interface to regular expressions for String.
Class String for handling character strings.
STLMath.h has some functions doing math on std::vector objects.
STLIO.h has some functions showing a container on std::ostream or LogIO.
Tip: You may want to look at the individual header files to see whether you might not prefer to include only the header files you really need; it may be more efficient to do so;
Function Documentation
acos() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::acos (const DComplex & in)
acos() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::acos (const Complex & in)
allNear() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::allNear (const Complex & val1, const Complex & val2, Double tol = 1.0e-5) inline
Definition at line 273 of file Complex.h.
References casacore::Complex_global_functions_Complex_desc::near().
allNear() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::allNear (const DComplex & val1, const DComplex & val2, Double tol = 1.0e-13) inline
Definition at line 276 of file Complex.h.
References casacore::Complex_global_functions_Complex_desc::near().
allNearAbs() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::allNearAbs (const Complex & val1, const Complex & val2, Double tol = 1.0e-5) inline
Definition at line 279 of file Complex.h.
References casacore::Complex_global_functions_Complex_desc::nearAbs().
allNearAbs() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::allNearAbs (const DComplex & val1, const DComplex & val2, Double tol = 1.0e-13) inline
Definition at line 282 of file Complex.h.
References casacore::Complex_global_functions_Complex_desc::nearAbs().
asin() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::asin (const DComplex & in)
asin() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::asin (const Complex & in)
atan() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::atan (const DComplex & in)
Inverse trigonometry.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
atan not valid for z == -1
atan() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::atan (const Complex & in)
atan2() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::atan2 (const DComplex & in, const DComplex & t2)
atan2() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::atan2 (const Complex & in, const Complex & t2)
ceil() [1/2]
Complex casacore::Complex_global_functions_Complex_desc::ceil (const Complex & x) inline
Definition at line 305 of file Complex.h.
References casacore::ceil().
ceil() [2/2]
DComplex casacore::Complex_global_functions_Complex_desc::ceil (const DComplex & x) inline
Definition at line 307 of file Complex.h.
References casacore::ceil().
cube() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::cube (const DComplex & val) inline
Definition at line 224 of file Complex.h.
cube() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::cube (const Complex & val) inline
Definition at line 225 of file Complex.h.
erf() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::erf (const DComplex & in)
Error function.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Preliminary to get Functionals working. erf(z) will return erf(real(z)) only for now.
erf() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::erf (const Complex & in)
erfc() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::erfc (const DComplex & in)
erfc() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::erfc (const Complex & in)
fabs() [1/2]
Double casacore::Complex_global_functions_Complex_desc::fabs (const DComplex & val) inline
Additional complex mathematical functions.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Definition at line 219 of file Complex.h.
References casacore::abs().
fabs() [2/2]
Float casacore::Complex_global_functions_Complex_desc::fabs (const Complex & val) inline
Definition at line 220 of file Complex.h.
References casacore::abs().
floor() [1/2]
Complex casacore::Complex_global_functions_Complex_desc::floor (const Complex & x) inline
Definition at line 300 of file Complex.h.
References casacore::floor().
floor() [2/2]
DComplex casacore::Complex_global_functions_Complex_desc::floor (const DComplex & x) inline
Definition at line 302 of file Complex.h.
References casacore::floor().
fmod() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::fmod (const DComplex & in, const DComplex & f)
fmod
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
fmod() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::fmod (const Complex & in, const Complex & f)
isFinite() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::isFinite (const Complex & val)
isFinite() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::isFinite (const DComplex & val)
isInf() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::isInf (const Complex & val)
isInf() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::isInf (const DComplex & val)
isNaN() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::isNaN (const Complex & val)
Complex NaN and Infinity.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
isNaN() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::isNaN (const DComplex & val)
DComplex NaN and Infinity.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
max() [1/2]
Complex casacore::Complex_global_functions_Complex_desc::max (const Complex & x, const Complex & y) inline
Max and min, floor and ceil functions.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Definition at line 291 of file Complex.h.
max() [2/2]
DComplex casacore::Complex_global_functions_Complex_desc::max (const DComplex & x, const DComplex & y) inline
Definition at line 293 of file Complex.h.
min() [1/2]
Complex casacore::Complex_global_functions_Complex_desc::min (const Complex & x, const Complex & y) inline
Definition at line 295 of file Complex.h.
min() [2/2]
DComplex casacore::Complex_global_functions_Complex_desc::min (const DComplex & x, const DComplex & y) inline
Definition at line 297 of file Complex.h.
near() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::near (const Complex & val1, const Complex & val2, Double tol = 1.0e-5)
The near functions.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Referenced by casacore::Complex_global_functions_Complex_desc::allNear().
near() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::near (const DComplex & val1, const DComplex & val2, Double tol = 1.0e-13)
nearAbs() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::nearAbs (const Complex & val1, const Complex & val2, Double tol = 1.0e-5)
Referenced by casacore::Complex_global_functions_Complex_desc::allNearAbs().
nearAbs() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::nearAbs (const DComplex & val1, const DComplex & val2, Double tol = 1.0e-13)
operator *() [1/4]
Complex casacore::Complex_global_functions_Complex_desc::operator * (const Complex & val, Double f) inline
QMath and scimath need these operators * and /.
Definition at line 249 of file Complex.h.
operator *() [2/4]
Complex casacore::Complex_global_functions_Complex_desc::operator * (Double f, const Complex & val) inline
Definition at line 250 of file Complex.h.
operator *() [3/4]
Complex casacore::Complex_global_functions_Complex_desc::operator * (const Complex & val, Int f) inline
These operators are useful, otherwise both Float and Double are applicable for Ints.
Definition at line 257 of file Complex.h.
operator *() [4/4]
Complex casacore::Complex_global_functions_Complex_desc::operator * (Int f, const Complex & val) inline
Definition at line 258 of file Complex.h.
operator+() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::operator+ (const DComplex & d, const Complex & c) inline
ArrayMath::pow needs this pow function.
inline Complex pow(const Complex& val, Double p) { return std::pow(val,Float(p)); } We have to explicitly implement these for different type operands
Definition at line 231 of file Complex.h.
References casacore::C::c.
operator+() [2/2]
DComplex casacore::Complex_global_functions_Complex_desc::operator+ (const Complex & c, const DComplex & d) inline
Definition at line 235 of file Complex.h.
References casacore::C::c.
operator-() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::operator- (const DComplex & d, const Complex & c) inline
Definition at line 239 of file Complex.h.
References casacore::C::c.
operator-() [2/2]
DComplex casacore::Complex_global_functions_Complex_desc::operator- (const Complex & c, const DComplex & d) inline
Definition at line 243 of file Complex.h.
References casacore::C::c.
operator/() [1/4]
Complex casacore::Complex_global_functions_Complex_desc::operator/ (const Complex & val, Double f) inline
Definition at line 251 of file Complex.h.
operator/() [2/4]
Complex casacore::Complex_global_functions_Complex_desc::operator/ (Double f, const Complex & val) inline
Definition at line 252 of file Complex.h.
operator/() [3/4]
Complex casacore::Complex_global_functions_Complex_desc::operator/ (const Complex & val, Int f) inline
Definition at line 259 of file Complex.h.
operator/() [4/4]
Complex casacore::Complex_global_functions_Complex_desc::operator/ (Int f, const Complex & val) inline
Definition at line 260 of file Complex.h.
operator<() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::operator< (const Complex & left, const Complex & right) inline
Definition at line 182 of file Complex.h.
References casacore::False, and casacore::norm().
operator<() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::operator< (const DComplex & left, const DComplex & right) inline
Definition at line 209 of file Complex.h.
References casacore::norm().
operator<=() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::operator<= (const Complex & left, const Complex & right) inline
Definition at line 180 of file Complex.h.
References casacore::norm(), and casacore::True.
operator<=() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::operator<= (const DComplex & left, const DComplex & right) inline
Definition at line 207 of file Complex.h.
References casacore::norm().
operator>() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::operator> (const Complex & left, const Complex & right) inline
Definition at line 178 of file Complex.h.
References casacore::False, and casacore::norm().
operator>() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::operator> (const DComplex & left, const DComplex & right) inline
Definition at line 205 of file Complex.h.
References casacore::norm().
operator>=() [1/2]
Bool casacore::Complex_global_functions_Complex_desc::operator>= (const Complex & left, const Complex & right) inline
Complex comparisons.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Definition at line 176 of file Complex.h.
References casacore::norm(), and casacore::True.
operator>=() [2/2]
Bool casacore::Complex_global_functions_Complex_desc::operator>= (const DComplex & left, const DComplex & right) inline
DComplex comparisons.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Definition at line 203 of file Complex.h.
References casacore::norm().
setInf() [1/2]
void casacore::Complex_global_functions_Complex_desc::setInf (Complex & val)
setInf() [2/2]
void casacore::Complex_global_functions_Complex_desc::setInf (DComplex & val)
setNaN() [1/2]
void casacore::Complex_global_functions_Complex_desc::setNaN (Complex & val)
setNaN() [2/2]
void casacore::Complex_global_functions_Complex_desc::setNaN (DComplex & val)
square() [1/2]
DComplex casacore::Complex_global_functions_Complex_desc::square (const DComplex & val) inline
Definition at line 221 of file Complex.h.
square() [2/2]
Complex casacore::Complex_global_functions_Complex_desc::square (const Complex & val) inline
Definition at line 222 of file Complex.h.