casacore: casacore Namespace Reference
casacore Namespace Reference
Containers_module
this file contains all the compiler specific defines
Namespaces
C
casacore
python
Classes
class Matrix
A 2-D Specialization of the Array class.
class ArrayIterator
Iterate an Array cursor through another Array.
class MaskedArray
Class for masking an Array for operations on that Array.
class Functional
Map a domain object into a range object via operator().
class Array
template <class T, class U> class vector;
class ArrayBaseAccessor
Axis independent base for the ArrayAccessor classes.
class ArrayAccessor
class ArrayAccessor< T, Axis< U > >
Fast 1D accessor/iterator for nD array classes.
class ArrayAccessor_RT< T, AxisN >
Specialization for run-time axes.
class ArrayBase
Non-templated base class for templated Array class.
class ArrayError
The base class for all Array exception classes.
class ArrayIndexError
An error thrown when an index is out of range.
class ArrayConformanceError
An error thrown when two arrays do not conform.
class ArrayNDimError
Thrown when two arrays have different dimensionality.
class ArrayShapeError
An error thrown when two arrays have different shapes.
class ArrayIteratorError
An error thrown by an ArrayIterator.
class ArraySlicerError
An error thrown by an Slicer member function.
class Vector
A 1-D Specialization of the Array class.
class Cube
A 3-D Specialization of the Array class.
class Block
simple 1-D array
struct ArrayIO_global_functions_Array_IO
Input/output operators for Arrays.
struct ArrayIO_global_functions_Array_binary_IO
Global functions to read/write binary arrays from/to a file.
struct ArrayIO_global_functions_Array_Ascii_IO
Global functions for Matrix/Vector input/output using ASCII format.
class ReadOnlyArrayIterator
Iterate a const Array cursor through a const Array.
struct ArrayLogical_global_functions_Array_logical_operations
Logical operations for Arrays.
class AllFunc
Define logical Functors.
class AnyFunc
class NTrueFunc
class NFalseFunc
struct ArrayMath_global_functions_Array_mathematical_operations
Mathematical operations for Arrays.
class ArrayFunctorBase
Basic class for math on Array objects.
struct ArrayOpsDiffShapes_global_functions_OpsDiff_functions
Operations for 2 Arrays with possibly different shapes.
struct ArrayPartMath_global_functions_Array_partial_operations
Mathematical and logical operations for Array parts.
class ArrayPositionIterator
Iterate an IPosition through the shape of an Array.
struct ArrayUtil_global_functions_stringToVector
Split a String into its elements.
struct ArrayUtil_global_functions_concatenateArray
Concatenate two Arrays.
struct ArrayUtil_global_functions_partialFuncHelper
Helper function for partialX functions.
struct ArrayUtil_global_functions_reverseArray
Reverse the order of one or more axes of an array.
struct ArrayUtil_global_functions_reorderArray
Reorder the axes of an array.
struct ArrayUtil_global_functions_reorderArrayHelper
Helper function for function reorderArray.
class AxesMapping
Info about mapping array axes to another order.
class AxesSpecifier
Specification of axes to keep or remove.
class ExtendSpecifier
Specification of new and stretched lattice axes.
class IPosition
A Vector of integers, for indexing into Array<T> objects.
struct IPosition_global_functions_IPosition_Arithmetic
Arithmetic Operations for IPosition's Element by element arithmetic on IPositions.
struct IPosition_global_functions_IPosition_Logical
Logical operations for IPosition's Element by element boolean operations on IPositions.
struct IPosition_global_functions_IPosition_Indexing
Indexing functions for IPosition's Convert between IPosition and offset in an array.
struct LogiArray_global_functions_LogicalArray
Logical valued Arrays.
struct LogiArrayFwd_global_functions_LogicalArray_forwards
Forward declarations for LogicalArrays.
struct LogiCube_global_functions_LogicalCube
Logical valued Cubes.
struct LogiMatrix_global_functions_LogicalMatrix
Logical valued Matrices.
struct LogiVector_global_functions_LogicalVector
Logical valued Vectors.
struct MaskArrIO_global_functions_MaskedArray_IO
Ascii input/output operations for MaskedArrays.
struct MaskArrLogi_global_functions_MaskedArray_logical_operations
Logical operations for MaskedArrays, and between MaskedArrays and Arrays.
struct MaskArrMath_global_functions_MaskedArray_mathematical_operations
Mathematical operations for MaskedArrays (and with Arrays)
class MaskedSumFunc
class MaskedProductFunc
class MaskedMinFunc
class MaskedMaxFunc
class MaskedMeanFunc
class MaskedVarianceFunc
class MaskedStddevFunc
class MaskedAvdevFunc
class MaskedRmsFunc
class MaskedMedianFunc
class MaskedMadfmFunc
struct MaskedArray_global_functions_MaskedArray_general_global_functions
General global functions for MaskedArrays, and MaskedArrays and Arrays.
struct MaskLogiArr_global_functions_MaskedLogicalArray
Masked LogicalArrays.
struct MaskLogiArrFwd_global_functions_MaskedLogicalArray_forwards
Forward declarations for MaskedLogicalArrays.
class MatrixIterator
Iterate a Matrix cursor through another Array.
class ReadOnlyMatrixIterator
Iterate a Matrix cursor through a R/O Array.
struct MatrixMath_global_functions_Linear_Algebra
Linear algebra functions on Vectors and Matrices.
class Slice
define a (start,length,increment) along an axis
class Slicer
Specify which elements to extract from an n-dimensional array.
struct Slicer_global_functions_Slicer_IO
IO functions for Slicer's.
class VectorIterator
Iterate an Vector cursor through another Array.
class ReadOnlyVectorIterator
Iterate a Vector cursor through another Array.
class VectorSTLIterator
Casacore Vector iterator.
struct ConvertScalar_global_functions_Scalar_conversion
Templated functions to convert scalars from one type to another.
class Lattice
A templated, abstract base class for array-like objects.
struct Plus
Functor to add variables of possibly different types.
struct Minus
Functor to subtract variables of possibly different types.
struct Multiplies
Functor to multiply variables of possibly different types.
struct Divides
Functor to divide variables of possibly different types.
struct Modulo
Functor to take modulo of (integer) variables of possibly different types in the C way.
struct FloorMod
Functor to take modulo of variables of possibly different types using the floor modulo (% as used in Python).
struct BitAnd
Functor for bitwise and of (integer) values.
struct BitOr
Functor for bitwise or of (integer) values.
struct BitXor
Functor for bitwise xor of (integer) values.
struct BitNegate
Functor for bitwise negate of (integer) values.
struct IsNaN
Functor to test for NaN.
struct IsInf
Functor to test for infinity.
struct IsFinite
Functor to test for finiteness.
struct Near
Functor to test if two values are relatively near each other.
struct NearAbs
Functor to test for if two values are absolutely near each other.
struct Sin
Functor to apply sin.
struct Sinh
Functor to apply sinh.
struct Asin
Functor to apply asin.
struct Cos
Functor to apply cos.
struct Cosh
Functor to apply cosh.
struct Acos
Functor to apply acos.
struct Tan
Functor to apply tan.
struct Tanh
Functor to apply tanh.
struct Atan
Functor to apply atan.
struct Atan2
Functor to apply atan2.
struct Sqr
Functor to apply sqr (power of 2).
struct Pow3
Functor to apply a power of 3.
struct Sqrt
Functor to apply sqrt.
struct Exp
Functor to apply exp.
struct Log
Functor to apply log.
struct Log10
Functor to apply log10.
struct Abs
Functor to apply abs.
struct Floor
Functor to apply floor.
struct Ceil
Functor to apply ceil.
struct Round
Functor to apply round (e.g.
struct Sign
Functor to apply sign (result is -1, 0, or 1).
struct MakeComplex
Functor to form a complex number from the left and right value.
struct MakeComplexReal
Functor to form a complex number from the real part of the left value and the right value.
struct MakeComplexImag
Functor to form a complex number from the left value and the imaginary part of the right value.
struct MakeComplexRealImag
Functor to form a complex number from the real part of the left value and the imaginary part of the right value.
struct Conj
Functor to apply complex function conj.
struct Real
Functor to apply complex function real.
struct Imag
Functor to apply complex function imag.
struct CArg
Functor to apply complex function arg.
struct CAbs
Functor to apply complex function fabs.
struct Pow
Functor to apply pow.
struct Fmod
Functor to apply fmod.
struct Min
Functor to get minimum of two values.
struct Max
Functor to get maximum of two values.
struct SumSqr
Functor to add square of right to left.
struct SumSqrDiff
Functor to add squared diff of right and base value to left.
struct SumAbsDiff
Functor to add absolute diff of right and base value to left.
struct Downcase
Functor to downcase a std::string.
struct Upcase
Functor to upcase a std::string.
struct Capitalize
Functor to capitalize a std::string.
struct Trim
Functor to trim a std::string.
struct Math_global_functions_Math_interface_for_casacore
Casacore interface to math.h and other scalar math functions.
class Primes
Creates a reference table of prime numbers, and some functions.
class RNG
Base class for random number generators.
class ACG
Additive number generator.
class MLCG
Multiplicative linear congruential generator.
class Random
Base class for random number distributions.
class Binomial
Binomial distribution.
class DiscreteUniform
Discrete uniform distribution.
class Erlang
Erlang distribution.
class Geometric
Discrete geometric distribution.
class HyperGeometric
Hypergeometric distribution.
class Normal
Normal or Gaussian distribution.
class LogNormal
Logarithmic normal distribution.
class NegativeExpntl
Negative exponential distribution.
class Poisson
Poisson distribution.
class Uniform
Uniform distribution.
class Weibull
Weibull distribution.
struct Complex_global_functions_Complex_desc
Single and double precision complex numbers.
class Dummy_Constants_class
Mathematical and numerical constants.
class IComplex
Integer complex numbers.
class RegexBase
Abstract interface class to regular expressions for String.
struct STLMath_global_functions_Container_Math
Math operations on STL-like containers.
class SubString
SubString help class to be used in at, before, ...
class String
String: the storage and methods of handling collections of characters.
struct String_global_functions_concatenator
Global concatenation operators.
struct String_global_functions_comparitor
Global comparison operators.
struct String_global_functions_split
Splitting Global function which splits the String into string array res at separator and returns the number of elements.
struct String_global_functions_common
Some general functions Functions to find special patterns, join and replicate.
struct String_global_functions_case
Casing and related functions Case conversion and rearrangement functions.
struct String_global_functions_io
IO.
class ArrayInitPolicy
A global enum used by some Array/Block constructors.
struct std11_allocator
struct casacore_allocator
struct new_del_allocator
class Allocator_private
class AbstractAllocator
class BaseAllocator
class NewDelAllocator
An allocator behaves like operator new[]/delete[].
class AlignedAllocator
An allocator which allocates aligned memory.
class DefaultAllocator
An aligned allocator with the default alignment.
struct AllocSpec
Allocator specifier.
class BlockTrace
simple 1-D array
class Block_internal_IsFundamental
class Block_internal_IsPointer
class Block_internal_IsPointer< T * >
class PtrBlock
A drop-in replacement for Block<T*>.
struct BlockIO_global_functions_BlockIO
IO functions for Block.
class ConstHashMapIter
struct HashMap_global_functions_hashfunc
Hash functions for standard types.
struct HashMap_global_functions_defaulthashvalue
Specify the default values for HashMap keys.
class HashClass
Hash function with state.
class HashMap
Associative Array with a hash table implementation.
struct HashMapIO_global_functions_hashmapio
HashMap/HashMapIter IO functions.
class HashMapIter
Step through a non-const HashMap.
class IterError
Iteration error class.
class IterBoundaryError
Iteration Boundary error class.
class IterInitError
Iteration initialization error.
class InvalidIterError
Invalide iteration error class.
class Link
doubly linked list primitive
class ListIter
Doubly linked non-constant list iterator The List class above only provides for the list framework.
class ConstListIter
Doubly linked constant list iterator.
class List
Doubly linked list.
class ListNotice
Linked list update notice.
struct ListIO_global_functions_List_IO
Input/output operators for Lists.
class MapIterRep
Abstract base class for associative array iterators.
class ConstMapIter
Const associative array iterator.
class Map
Abstract base class for associative arrays.
class MapRep
Map representation class.
class MapIter
Associative array iterator.
struct MapIO_global_functions_Map_IO
Input/output operators for Maps.
class ObjectPool
A parameterized stack of re-usable objects.
class ObjectStack
A stack of re-usable objects.
class OrderedMap
Map with keys ordered.
class OrderedMapRep
Representation class for an Ordered Map.
class OrderedMapIterRep
OrderedMap iterator "letter".
class OrderedMapNotice
Message used for OrderedMap notification.
class OrderedPair
Ordered pair class.
struct OrdPairIO_global_functions_inoutput
These need to be left out SUN BUG
class PoolStack
A parameterized stack of re-usable objects.
class Queue
A First-In-First-Out (FIFO) data structure.
class Record
A hierarchical collection of named fields of various types.
class RecordDesc
Description of the fields in a record object.
class RecordDescRep
Representation of a RecordDesc.
class RecordFieldPtr
Access to an individual field in a record.
class RORecordFieldPtr
Read-Only access to an individual field from a Record.
class RecordFieldId
The identification of a record field.
class RecordFieldWriter
Record field writer. Base class for the copiers.
class RecordFieldCopier
Record field copier.
class UnequalShapeCopier
Unequal shape copier.
class MultiRecordFieldWriter
Multi field writer.
class RecordInterface
Abstract base class for Record classes.
class RecordNotice
Helper class to notify class Record about changes.
class RecordRep
The representation of a Record.
class SimpleOrderedMap
Simple map with keys ordered.
struct SimOrdMapIO_global_functions_inoutput
Global IO functions.
class Stack
This class, Stack<t>, defines an implementation of a stack using the doubly linked list primitive, Link<t>.
class EmptyStackError
Error class for the Stack class.
class ValueHolder
A holder for a value of any basic Casacore data type.
class ValueHolderRep
A holder for a value of any basic type.
class CasaErrorTools
class AipsError
Base class for all Casacore library errors.
class AllocError
Allocation errors.
class IndexError
Base class for all indexing errors.
class indexError
Index errors returning the bad index.
class DuplError
Duplicate key errors.
class duplError
Duplicate key errors where the bad key is returned.
class SystemCallError
Exception for an error in a system call.
class AbortError
Exception which halts execution.
class HDF5DataSet
A class representing an HDF5 data set.
class HDF5DataType
A class representing an HDF5 data type.
class HDF5Error
Base error class for HDF5 wrapper classes.
class HDF5File
A class representing an HDF5 file.
class HDF5Group
A class representing an HDF5 group.
class HDF5HidProperty
A class representing an HDF5 property hid.
class HDF5HidDataType
A class representing an HDF5 datatype hid.
class HDF5HidDataSpace
A class representing an HDF5 dataspace hid.
class HDF5HidAttribute
A class representing an HDF5 attribute hid.
class HDF5Object
An abstract base class representing an HDF5 object.
class HDF5Record
A class to write/read a record into HDF5.
class Input
Input.h: A simple command-line argument method for applications.
class Param
A simple keyword/value pair with internal help Strings.
class AipsIO
AipsIO is the object persistency mechanism of Casacore.
struct AipsIOCarray_global_functions_AipsIOCarray
Templated functions to get/put a C-style array from/into AipsIO.
class BaseSinkSource
Shared base class for ByteSink and ByteSource.
class BucketBase
Abstract base class for Bucket classes.
class BucketBuffered
Use buffered file IO for buckets in a part of a file.
struct BucketCache_global_functions_BucketCache_CallBack
Define the type of the static read and write function.
class BucketCache
Cache for buckets in a part of a file.
class BucketFile
File object for BucketCache.
class BucketMapped
Use file mapping for buckets in a part of a file.
class ByteIO
Abstract base class for IO on a byte stream.
class ByteSink
Class for write-only access to data in a given format.
class ByteSinkSource
Class for read/write access to data in a given format.
class ByteSource
Class for read-only access to data in a given format.
class CanonicalIO
Class for IO in canonical format.
class ConversionIO
Class for IO in a converted format.
class FilebufIO
Class for buffered IO on a file.
class FiledesIO
Class for unbuffered IO on a file.
class FileLocker
Class to handle file locking.
class LECanonicalIO
Class for IO in little endian canonical format.
class LockFile
Class to handle file locking and synchronization.
class MemoryIO
Class for IO to a memory buffer.
class MFFileIO
Class for IO on a virtual file in a MultiFileBase.
class MMapfdIO
Memory-mapped IO on a file.
class MMapIO
Memory-mapped IO on a file.
class MultiFile
Class to combine multiple files in a single one.
struct MultiFileInfo
Helper class for MultiFileBase containing info per internal file.
class MultiFileBase
Abstract base class to combine multiple files in a single one.
class MultiHDF5
Class to combine multiple files in a single HDF5 file.
class RawIO
Class for IO in local format.
class RegularFileIO
Class for IO on a regular file.
class StreamIO
Class for IO on connection oriented socket.
class TapeIO
Class for IO on a tape device.
class TypeIO
Abstract base class for IO of data in a type-dependent format.
class LogFilter
Filter LogMessages on message priority.
class LogFilterInterface
Abstract base class for filtering LogMessages.
class LogIO
ostream-like interface to creating log messages.
struct LogIO_global_functions_command
Functions to send commands to a LogIO object.
struct LogIO_global_functions_output
Functions to accumulate text in the output message.
class LogMessage
Informational log messages with with time, priority, and origin.
struct LogMessage_global_functions_LogMessage_ostream
Write a LogMessage to an ostream.
class LogOrigin
LogOrigin: The source code location of the originator of a LogMessage.
struct LogOrigin_global_functions_LogOrigin_ostream
Write a LogOrigin to an ostream.
struct LogOrigin_global_functions_SourceLocation
Helper struct to get the source line.
class LogSink
Distribute LogMessages to their destination(s)
class LogSinkInterface
Accepts LogMessages and posts them to some destination.
class MemoryLogSink
Save log messages in memory.
class NullLogSink
Throw away all messages.
class StreamLogSink
Send log messages to an ostream.
class CanonicalConversion
LDOUBLE is 8 bytes on SUN, but 16 bytes canonical.
class CanonicalDataConversion
A class with virtual functions to convert canonical format.
class Conversion
A class with general conversion definitions.
class DataConversion
Abstract base class with functions to convert any format.
class Directory
Get information about, and manipulate directories.
class DirectoryIterator
Traverse the contents of a directory.
class DOos
DO for accessing os-specific functions.
class DynLib
Class to handle loading of dynamic libraries.
class EnvironmentVariable
This class allows for getting enviroment variables.
class File
Class to get file information and a base for other file classes.
class HostInfo
Miscellaneous information about this host and process.
class IBMConversion
A class with static functions to convert IBM format.
class IBMDataConversion
A class with virtual functions to convert IBM format.
class LECanonicalConversion
A class with static functions to convert little endian canonical format.
class LECanonicalDataConversion
A class with virtual functions to convert little endian canonical format.
class LittleEndianConversion
A class with static functions to convert littleEndian format.
class Memory
Memory related information and utilities. use visibility=export>
class MemoryTrace
memory usage tracing mechanism
class MemoryTraceBlock
Class to write begin and end block message.
class ModcompConversion
Static functions to convert Modcomp numeric formats.
class ModcompDataConversion
A DataConversion class to convert between Modcomp format.
class Mutex
Wrapper around a pthreads mutex.
class ScopedMutexLock
Exception-safe lock/unlock of a mutex.
class MutexedInit
Thread-safe initialization of global variables.
class Path
Path name of a file.
class PrecTimer
Precision timer to measure elapsed times in a cumulative way.
class RawDataConversion
A class with virtual functions to copy without conversion.
class RegularFile
Manipulate and get information about regular files.
class SymLink
Get information about, and manipulate symbolic links.
class Time
date and time enquiry functions, with some operations.
class Timer
measure the time it takes to execute parts of a program
class VAXConversion
A class with static functions to convert VAX format.
class VAXDataConversion
A class with virtual functions to convert VAX format.
class Euler
Vector of Euler rotation angles.
class Quantum
Quantities (i.e. dimensioned values)
class MeasValue
Base class for values in a Measure.
struct MeasValue_global_functions_Output
Global functions.
class MVAngle
Class to handle angle type conversions and I/O.
struct MVAngle_global_functions_output
Global functions.
class MVBaseline
A 3D vector on Earth.
class MVDirection
Vector of three direction cosines.
class MVDoppler
Internal value for MDoppler.
class MVDouble
Class to distinguish external and Measure internal Double.
class MVEarthMagnetic
A 3D Earth magnetic field vector.
class MVEpoch
A class for high precision time.
class MVFrequency
Internal value for MFrequency.
class MVPosition
A 3D vector in space.
class MVRadialVelocity
Internal value for MRadialVelocity.
class MVTime
Class to handle date/time type conversions and I/O.
class MVuvw
A 3D vector on Earth.
class QBase
Base for Quantities (i.e. dimensioned values)
struct QBase_global_functions_Output
Global functions.
class QC
Physical constants (i.e. dimensioned values)
class QC_init
Class used to force construction of QC .
struct QC_global_functions_QC_initialization_object
Object used to force construction of QC .
struct QLogical_global_functions_Quantum_logical_operations
Logical operations for the Quantum class.
struct Quantum_global_functions_output
Global functions.
class QuantumHolder
A holder for Quantums to enable record conversions.
struct QuantumType_global_functions_QuantumType
Get an integer type for a Qunatum<T>
class QVector
Specialization for Quantum<Vector<T> >
class RotMatrix
A 3x3 rotation matrix.
class Unit
defines physical units
class UnitDim
describes a unit in basic SI unit dimensions
class UnitMap
contains all simple known physical units
class UnitName
handles physical units
class UnitVal
describes any valid unit as a factor and a dimenion of SI units
struct UnitVal_global_functions_output
Global output function.
class UnitVal_static_initializer
Static initialisation of UnitVal constants.
class AipsrcValue
Class to read values from the Aipsrc general resource files.
class AipsrcVector
Read multiple values from the Aipsrc resource files.
class Aipsrc
Class to read the casa general resource files.
class AipsrcValue_Bool< Bool >
Specialization of AipsrcValue for Bool.
class AipsrcVector_String< String >
Specialization of AipsrcVector for String.
class AipsrcVector_Bool< Bool >
Specialization of AipsrcVector for Bool.
class AppInfo
General information for applications.
class Casarc
class CasarcCleanup
class Choice
Class to ask a user a choice.
class ObjectID
ObjectID: A unique identifier for distributed and other objects.
class PGPlotter
Standard plotting object for application programmers.
class PGPlotterInterface
Abstract base class for PGPLOT style plotting.
class PGPlotterNull
Plot to a PGPLOT device "local" to this process.
class ProgressMeter
Visual indication of a tasks progress.
class AlignMemory
Referenced counted pointer for constant data.
class assert_
Utility class for Assert macros.
struct BinarySearch_global_functions_binarysearch
Binary search a sorted, linear, data structure.
class BitVector
Bit vectors of any size.
class BitVectorHelper
Helper class for BitVector.
class CASATask
Task interface.
struct Compare_global_functions_ObjCompareFunc
signature of comparison functions
class BaseCompare
abstract base class for comparing two objects
class ObjCompare
compare two objects
class CompareIntervalInt
Integer comparison class with intervals.
class CompareIntervalReal
Real comparison class with intervals.
class CompareNoCase
Case-insensitive string comparison class.
class CompositeNumber
This class generates composite numbers.
struct Copy_global_functions_throw
Copy objects from one C-style array to another.
struct Copy_global_functions_test
Test routines.
struct Copy_global_functions_copy
Copy methods.
struct CountedPtr_global_functions_dereference_error
act on dereference error
class CountedPtr
Referenced counted pointer for constant data.
class COWPtr
Copy-On-Write-Pointer class - allows control of copy based on constness.
struct re_pattern_buffer
This data structure is used to represent a compiled pattern.
struct re_registers
Data structure to store register contents data in.
struct DataType_global_functions_DataType
Data types (primarily) in the table system.
struct DefaultValue_global_functions_defval
A templated function which sets a variable to a default value.
class DynBuffer
Store data in dynamically allocated buffers.
struct Fallible_global_functions_invalid_access
throw exception on access of an invalid object This function gets called when an invalid object is accessed. It just throws an exception. Since we have inline functions, let's keep the throw out of them to keep them from moving out of line.
class Fallible
Mark a value as valid or invalid.
struct generic_global_functions_def
Generic gnu macros.
class GenSort
General in-place sort functions.
class GenSortIndirect
General indirect sort functions.
struct LinearSearch_global_functions_linearsearch
Linear search a linear data structure.
class MUString
Pointed String class to aid analysis of quantity strings.
struct MUString_global_functions_output
Global functions.
class Notice
abstract base class for notices
class NoticeSource
base class for notice originators
class NoticeTarget
abstract base class for notice receptors
class PtrHolder
Hold and delete pointers not deleted by object destructors.
class RecordTransformable
Interface class for converting to/from records.
class Regex
Regular expression class.
struct Register_global_functions_register
Primitive Run Time Type Information (RTTI)
class RegSequence
Sequence for the Register() template functions.
class Sequence
virtual templated base class for sequences
class uIntSequence
uInt sequence for general use
class SortKey
Define a Sort key.
class Sort
Sort on one or more keys, ascending and/or descending.
class SortError
Generic Sort exception.
class SortInvDT
Invalid data type used for this sort key.
class SortInvIncr
Invalid increment used for this sort key.
class SortNoData
No data array given to Sort constructor.
class SortInvOpt
Invalid sort option given to routine dosort.
class StringDistance
Class to deal with Levensthein distance of strings.
class Template
Canonicalise, format and other actions on Casacore template definitions.
class ValType
Data types and their undefined values.
struct ValTypeId_global_functions_typeid
The id-string of a value type.
class Coordinate
Interface for converting between world and pixel coordinates.
class CoordinateSystem
Interconvert pixel and world coordinates.
class CoordinateUtil
Functions for creating default CoordinateSystems.
class DirectionCoordinate
Interconvert pixel positions and directions (e.g. RA/DEC).
class FITSCoordinateUtil
class FrequencyAligner
Aligns spectra in frequency space.
class GaussianConvert
Converts Gaussian parameters between pixel and world.
class LinearCoordinate
Interconvert between pixel and a linear world coordinate.
class LinearXform
Perform a linear transform between input and output vectors.
class ObsInfo
Store miscellaneous information related to an observation.
class Projection
Geometric parameters needed for a sky projection to a plane.
class QualityCoordinate
Interconvert between pixel and Quality value.
class SpectralCoordinate
Interconvert pixel and frequency values.
class StokesCoordinate
Interconvert between pixel and Stokes value.
class Interpolate1D
Interpolate in one dimension.
class TabularCoordinate
Table lookup 1-D coordinate, with interpolation.
class HourangleColumn
Hourangle derived from TIME, etc.
class LASTColumn
Local sidereal time derived from TIME, etc.
class ParAngleColumn
Parallactic angle derived from TIME, etc.
class HaDecColumn
Hourangle/declination derived from TIME, etc.
class AzElColumn
Azimuth/elevation derived from TIME, etc.
class UVWJ2000Column
UVW J2000 derived from TIME, etc.
class DerivedMSCal
Virtual column engine to return derived MS values.
class MSCalEngine
Engine to calculate derived MS values.
class HelpMsCalUDF
class UDFMSCal
TaQL UDFs to calculate derived MS values.
class UDFMSCalErrorHandler
Error handler class for MSSel selection.
struct BasicFITS_global_functions_ReadFITS
read a FITS file from a Casacore array
struct BasicFITS_global_functions_WriteFITS
write a FITS file to a Casacore array
class BinaryTable
BinaryTable is used to translate a FITS binary table to a Casacore Table.
class BlockIO
class BlockInput
fixed-length blocked sequential input base class
class BlockOutput
fixed-length blocked sequential output base class
class ScalarColumn
Access to a scalar table column with arbitrary data type.
class ArrayColumn
Read and write access to an array table column with arbitrary data type.
class CopyRecordToTable
Copies fields from a Record to columns of a Table.
class CopyRecordToRecord
Copies fields between Records, possibly to fields with another name.
class NoConvert
FITS templated helper class.
class FitsLogical
FITS helper class.
class FitsBit
helper class for FITS Binary Tables
class FitsVADesc
Variable Length Array Descriptor.
class FITS
static functions and enumerations
class ReservedFitsKeyword
reserved FITS keyword
class ReservedFitsKeywordCollection
collection of reserved FITS keywords
class FitsNameResult
analyse the name of a header card
class FitsValueResult
analyse the value of a header card
class FitsParse
parse a header card
class FitsKeyword
FITS keyword.
class FitsKeywordList
linked list of FITS keywords
class ConstFitsKeywordList
list of read-only FITS keywords
class FitsKeyCardTranslator
translator between Keyword lists and fixed FITS cars
class FitsFPUtil
Utility functions for floating point values.
struct FITS2_global_functions_ReadFITSin
helper function for ReadFITS and WriteFITS
class FITSDateUtil
A class with static functions to help deal with FITS dates.
class FITSError
default FITS error handling function, typdef, and enumeration
class FITSFieldCopier
Virtual base class for copying RORecordFields to FitsFields.
class ScalarFITSFieldCopier
A FITSFieldCopier for copying scalar non-string RecordFields to FitsFields.
class StringFITSFieldCopier
A FITSFieldCopier for copying String RecordFields to FitsFields.
class ArrayFITSFieldCopier
A FITSFieldCopier for copying Array RecordFields to FitsFields.
class VariableArrayFITSFieldCopier
class FITSHistoryUtil
A class with static functions to help deal with FITS History cards.
class FitsIO
sequential FITS I/O
class FitsInput
fixed-length sequential blocked FITS input
class FitsOutput
fixed-length sequential blocked FITS output
class FitsDiskInput
FITS input from disk.
class FitsDiskOutput
FITS output to disk.
class FitsStdInput
FITS input from standard input.
class FitsStdOutput
FITS output to standard output.
class FitsTape9Input
FITS input from 9-track tape.
class FitsTape9Output
FITS output to 9-track tape.
class FITSKeywordUtil
A class with static functions to help deal with FITS Keywords.
class FITSMultiTable
View multiple FITS files as a single table.
class FITSReader
class FITSSpectralUtil
A class with static functions to help deal with FITS spectral axes.
class FITSTabular
Simplified interface to FITS tables with Casacore Look and Feel.
class FITSTable
Attach a FITSTabular to a binary or ASCII table.
class FITSTableWriter
Simplified interface to create and write to a FITS Binary Table.
class FITSGroupWriter
Simplified interface to create and write to FITS random groups.
class FITSTimedTable
class HeaderDataUnit
base class that defines a HDU
class PrimaryArray
templated primary array base class of given type
class ImageExtension
IMAGE extension of given type.
class PrimaryGroup
Random Group datastructure.
class PrimaryTable
Primary Table structure.
class ExtensionHeaderDataUnit
base class for generalized exentensions HDU
class FitsBase
helper class
class FitsField
helper class
Note: Note that FitsField does not allocate space for the data; Space is external to FitsField and its address is set via the setaddr function;
class FitsField< FitsBit >
helper class
class FitsArray
FITS array of given type.
class FitsArray< FitsBit >
FITS array of FitsBit type
Note: We must specify a FitsArray<FitsBit> as a specialization;
class BinaryTableExtension
BINTABLE extension.
class AsciiTableExtension
(ascii) TABLE extension
class SDFITSTable
SDFITSTable is a FITSTable which follows the Single Dish FITS Convention.
class CurvedLattice2D
A lattice crosscut based on a curve in a plane.
class CLInterpolator2D
Abstract base class for interpolator used by CurvedLattice2D.
class CurvedImage2D
An image crosscut based on a curve in a plane.
class ExtendLattice
An extension of a Lattice or MaskedLattice.
class ExtendImage
An extension of an ImageInterface object.
class FITSErrorImage
Class providing native access to FITS Error images.
class FITSImage
Class providing native access to FITS images.
class FITSImgParser
Class for handling FITS Image extensions.
class FITSExtInfo
class FitsKeywordList;
class FITSQualityImage
Class providing native access to FITS Quality Images.
class FITSQualityMask
Provides an on-the-fly mask for FITS quality images.
class HDF5Image
Read, store, and manipulate astronomical images in HDF5 format.
class ImageAttrGroup
Abstract base class for an image attributes group.
class ImageAttrGroupCasa
Attribute group for a CASA image.
class ImageAttrGroupHDF5
Attribute group for a HDF5 image.
class ImageAttrHandler
Abstract base class for an image attributes handler.
class ImageAttrHandlerCasa
Abstract base class for an image attributes handler.
class ImageAttrHandlerHDF5
Abstract base class for an image attributes handler.
class ImageBeamSet
Represents a set of restoring beams associated with an image.
class ImageSummary
Provides and lists information about the header of an image.
class MaskedLattice
A templated, abstract base class for array-like objects with masks.
class ImageConcat
Concatenates images along a specified axis.
class LatticeIterInterface
A base class for Lattice iterators.
class ImageExpr
Hold mathematical expressions involving ImageInterface objects.
struct ImageExprGram_global_functions_ImageExprGramFunctions
Global functions for flex/bison scanner/parser for ImageExprGram.
class ImageExprParse
Class to hold values from image expression parser.
class PagedImage
Read, store, and manipulate astronomical images.
class ImageInterface
A base class for astronomical images.
struct ImageFITSHeaderInfo
Struct holding information derived from the image and its header.
class ImageFITSConverter
Interconvert between Casacore Images and FITS files.
class ImageFITSConverterImpl
This class is an internal class for ImageFITSConverter.
class ImageInfo
Miscellaneous information related to an image.
struct ImageInfo_global_functions_Output
Global functions.
class ImageOpener
Definition of image types and handlers.
class ImageProxy
class LatticeIterator
A read/write lattice iterator.
class ImageRegrid
This regrids one image to match the coordinate system of another.
class ImageStatistics
Displays various statistics from an image.
class ImageUtilities
Utility functions for Image manipulation.
class LELImageCoord
The letter class for image coordinates.
class MaskSpecifier
Class to specify which mask to use in an image.
class MIRIADImage
Class providing native access to MIRIAD images.
class RebinLattice
Rebin a masked lattice.
class RebinImage
Rebin an image.
class SubLattice
A subset of a Lattice or MaskedLattice.
class SubImage
A (masked) subset of an ImageInterface object.
class TempImage
Temporary astronomical images.
class AipsIOReaderWriter
Implementation of CASA region AipsIO file reader and writer.
class ImageRegion
Class to hold a region of interest in an image.
class RegionHandler
Base class for handling regions in images.
class RegionHandlerHDF5
Class for keeping regions in an HDF5 file.
class RegionHandlerMemory
Class for keeping regions in memory.
class RegionHandlerTable
Class for keeping regions in memory.
class RegionManager
class RFError
Convenience class for a String/bool pair.
class RFReaderWriter
Superclass for readers and writers containing common definitions and operations.
class RFReader
Abstract superclass for any class that reads a format that produces Regions from a file.
class RFWriter
Abstract superclass for any class that writes Regions to a region file format.
class WCBox
Class to define a world coordinate box region of interest in an image.
class WCComplement
Make the complement of an image region.
class WCCompound
Base class for compound WCRegion objects.
class WCConcatenation
Combine multiple ImageRegion's into a new dimension.
class WCDifference
Make the difference of 2 image regions.
class WCEllipsoid
Class to define an n-dimensional ellipsoid in world coordinates.
class WCExtension
Make the extension of an image region.
class WCIntersection
Make the intersection of 2 or more image regions.
class LatticeExpr
Class to allow C++ expressions involving lattices.
class WCLELMask
Class to define a mask as a LEL expression.
class WCPolygon
Class to define a 2-D polygonal world coordinate region in an image.
class WCRegion
Base class to define world coordinate regions of interest in an image.
class WCUnion
Make the union of 2 or more image regions.
class CLIPNearest2D
Arbitrarily shaped 1-dim lattice crosscut.
class Fit2D
Fit 2-D objects to 2-D Lattices or Arrays.
class LatticeAddNoise
Add noise from specified distribution to a lattice.
class TiledCollapser
Abstract base class to collapse chunks for LatticeApply.
class LineCollapser
Abstract base class for LatticeApply function signatures.
class LatticeApply
Optimally iterate through a Lattice and apply provided function object.
class TempLattice
A Lattice that can be used for temporary storage.
class CleanEnums
Lists the different types of Convolutions that can be done.
class LatticeCleaner
A class for doing multi-dimensional cleaning.
class LatticeCleanProgress
Abstract base class to monitor progress in lattice operations.
class ConvEnums
Lists the different types of Convolutions that can be done.
class LatticeConvolver
A class for doing multi-dimensional convolution.
class LatticeFFT
Functions for Fourier transforming Lattices.
class LatticeFit
Fit every line of pixels parallel to any axis in a Lattice.
class LatticeFractile
Static functions to get median and fractiles of a lattice.
class LatticeHistograms
Displays histograms of regions from a lattice.
class HistTiledCollapser
Generate histograms, tile by tile, from a masked lattice.
class LatticeHistProgress
Provides a progress meter for the LatticeHistograms class.
class LatticeHistSpecialize
Specialized functions for LatticeHistograms.
class LatticeMathUtil
Static math functions for Lattices.
struct LatticeMathUtil_global_functions_LatticeMathUtil
Global functions on Lattices.
class LatticeProgress
Abstract base class to monitor progress in lattice operations.
class LatticeSlice1D
Extract a 1-D slice from a Lattice.
class LatticeStatistics
Compute and display various statistics from a lattice.
class LatticeStatsBase
Base class for LatticeStatistics class.
class LatticeStatsDataProvider
Data provider which allows stats framework to iterate through an unmasked lattice.
class LatticeStatsDataProviderBase
Abstract base class of data providers which allows stats framework to iterate through a lattice.
class LatticeTwoPtCorr
Compute two point auto-correlation functions from a lattice.
class LattStatsProgress
Provides a progress meter for the LatticeStatistics class.
class LattStatsSpecialize
class MaskedLatticeStatsDataProvider
Data provider which allows stats framework to iterate through a masked lattice.
class MultiTermLatticeCleaner
class StatsTiledCollapser
Generate statistics, tile by tile, from a masked lattice NOTE this version was moved from LatticeStatistics (early Dec 2014 version) and slightly modified mostly for style issues (no significant semantic differences from that version). For a large number of statistics sets that need to be computed simultaneously, this version is more efficient than using the new stats framework, because creating large numbers of eg ClassicalStatistics objects is much less efficient than the direct manipulation of pointers to primitive types that this class does.
class ArrayLattice
A memory resident Lattice.
class HDF5Lattice
A Lattice that is read from or written to an HDF5 dataset.
class HDF5LattIter
A read/write Lattice iterator for PagedArrays.
class LatticeBase
A non-templated, abstract base class for array-like objects.
class LatticeCache
a class for caching image access via tiles
class LatticeConcat
Concatenates lattices along a specified axis.
class LatticeIndexer
A helper class for stepping through Lattices.
class RO_LatticeIterator
A readonly iterator for Lattices.
class LatticeLocker
Class to hold a (user) lock on a lattice.
class LatticeNavigator
Abstract base class to steer lattice iterators.
class LatticeStepper
Traverse a Lattice by cursor shape.
class LatticeUtilities
Static functions for Lattices.
class RO_MaskedLatticeIterator
A readonly iterator for masked Lattices.
class PagedArray
A Lattice that is read from or written to disk.
class PagedArrIter
A read/write Lattice iterator for PagedArrays.
class PixelCurve1D
Arbitrary 1-dim curve in a lattice plane.
class TempLatticeImpl
The class implementing TempLattice.
class TiledLineStepper
Step a Vector cursor optimally through a tiled Lattice.
class TiledShape
Define the shape and tile shape.
class TileStepper
traverse a tiled Lattice optimally with a tile cursor
class LELArray
This LEL class holds an array with a mask.
class LatticeExprNode
Bridging class to allow C++ expressions involving lattices.
class LELArrayRef
This LEL class holds a possible referenced array with a mask.
class LELArrayBase
Base class for LELArray holding the mask.
class LELAttribute
Ancillary information for the LEL letter classes.
class LELBinary
This LEL class handles numerical binary operators.
class LELBinaryCmp
This LEL class handles relational binary numerical operators.
class LELBinaryBool
This LEL class handles logical binary operators.
class LELBinaryEnums
Each LEL binary operation is described in this enum.
class LELCondition
Class to make a mask from a condition.
class LELConvert
Class to convert a LEL node from one numerical type to another.
class LELCoordinates
Envelope class to handle Lattice Coordinates in LEL.
class LELFunction1D
This LEL class handles numerical (real and complex) 1-argument functions.
class LELFunctionReal1D
This LEL class handles numerical (real only) 1-argument functions.
class LELFunctionND
This LEL class handles functions with a variable number of arguments.
class LELFunctionFloat
This LEL class handles numerical functions whose return type is a Float.
class LELFunctionDouble
This LEL class handles numerical functions whose return type is a Double.
class LELFunctionComplex
This LEL class handles complex numerical functions.
class LELFunctionDComplex
This LEL class handles double complex numerical functions.
class LELFunctionBool
This LEL class handles logical functions.
class LELFunctionEnums
Each LEL function is described in this enum.
class LELScalar
This LEL class holds a scalar with a mask.
class LELInterface
This base class provides the interface for Lattice expressions.
class LELLattCoord
The base letter class for lattice coordinates in LEL.
class LELLattCoordBase
The base letter class for lattice coordinates in LEL.
class LELLattice
This LEL class handles access to Lattices.
class LELRegion
Class to hold a region as a LEL node.
class LELRegionAsBool
Class to convert a region to a boolean node.
class LELSpectralIndex
This LEL class handles calculation of the spectral index.
class LELUnaryConst
This LEL class handles scalar (unary) constants.
class LELUnary
This LEL class handles numerical unary operators.
class LELUnaryBool
This LEL class handles logical unary operators.
class LELUnaryEnums
Each LEL unary operation is described in this enum.
class FITSMask
Provides an on-the-fly mask for FITS images.
class LatticeRegion
An optionally strided region in a Lattice.
class LattRegionHolder
Class to hold a region of interest in an image.
class LCBox
Class to define a rectangular box of interest.
class LCComplement
Make the complement of a region.
class LCConcatenation
Combine multiple LCRegion's into a new dimension.
class LCDifference
Make the difference of 2 regions.
class LCEllipsoid
Define an N-dimensional ellipsoidal region of interest.
class LCExtension
Extend an LCRegion along straight lines to other dimensions.
class LCHDF5Mask
Class to define a rectangular mask as a region.
class LCIntersection
Make the intersection of 2 or more regions.
class LCLELMask
Class to define a mask as a LEL expression.
class LCMask
Class to define a rectangular mask as a temporary region.
class LCPagedMask
Class to define a rectangular mask as a region.
class LCPixelSet
Class to define a rectangular mask as a region.
class LCPolygon
Define a 2-dimensional region by a polygon.
class LCRegion
Abstract base class to define a region of interest in lattice coordinates.
class LCRegionFixed
Abstract base class to define a fixed region.
class LCRegionMulti
Make the intersection of 2 or more regions.
class LCRegionSingle
Abstract base class to define a single region.
class LCSlicer
Class to define a rectangular box of interest with strides.
class LCStretch
Stretch length 1 axes in an LCRegion along straight lines.
class LCUnion
Make the union of 2 or more regions.
class RegionType
Define the various region types.
class Aberration
Aberration class and calculations.
class EarthField
EarthField class model calculations.
class EarthMagneticMachine
Calculates magnetic field in a direction.
class MeasConvert
Conversion of Measures.
class ArrayMeasColumn
Read only access to table array Measure columns.
class ScalarMeasColumn
Read only access to table scalar Measure columns.
class MBaseline
A Measure: Baseline on Earth.
class MCBase
Base for specific measure conversions.
class MCBaseline
MBaseline conversion routines.
class MCDirection
MDirection conversion routines.
class MCDoppler
MDoppler conversion routines.
class MCEarthMagnetic
MEarthMagnetic conversion routines.
class MCEpoch
MEpoch conversion routines.
class MCFrame
Measure frame calculations proxy.
class MCFrequency
MFrequency conversion routines.
class MConvertBase
Conversion of Measures Base.
struct MConvertBase_global_functions_Output
Global functions.
class MCPosition
MPosition conversion routines.
class MCRadialVelocity
MRadialVelocity conversion routines.
class MCuvw
Muvw conversion routines.
class MDirection
A Measure: astronomical direction.
class MDoppler
A Measure: Doppler shift.
class MEarthMagnetic
A Measure: Magnetic field on Earth.
class MeasBase
Base class for all measures.
class MeasComet
Position for comets and other solar system bodies.
class MeasData
MeasData provides Measure computing data.
class MeasFrame
Container for Measure frame.
struct MeasFrame_global_functions_Output
Global functions.
class MeasIERS
Interface to IERS tables.
class MeasJPL
Interface to JPL DE tables.
class MeasMath
Measure conversion aid routines.
class MeasRef
Reference frame for physical measures.
class MeasTable
MeasTable provides Measure computing database data.
class MeasTableMul
MeasTableMul provides thread-safe access to time-dependent multiplier matrices.
class MeasTableMulSCBase
Base class for standard and B1950 nutation multipliers.
class MeasTableMulSC
Class calculating the standard nutation multipliers.
class MeasTableMulSC1950
Class calculating the B1950 nutation multipliers.
class MeasTableMulSC2000Base
Base class for J2000 nutation multipliers.
class MeasTableMulSC2000A
Class calculating the J2000A nutation multipliers.
class MeasTableMulSC2000B
Class calculating the J2000B nutation multipliers.
class MeasTableMulAber
Class calculating the standard aberration multipliers.
class MeasTableMulAber1950
Class calculating the B1950 aberration multipliers.
class MeasTableMulPosSunXY
Class calculating the XY solar position multipliers.
class MeasTableMulPosSunZ
Class calculating the Z solar position multipliers.
class MeasTableMulPosEarthXY
Class calculating the XY earth position multipliers.
class MeasTableMulPosEarthZ
Class calculating the Z earth position multipliers.
class Measure
Physical quantities within reference frame.
struct Measure_global_functions_Output
Global functions.
class MeasureHolder
A holder for Measures to enable record conversions.
class MeasuresProxy
class MEpoch
A Measure: instant in time.
class MFrequency
A Measure: wave characteristics.
class MPosition
A Measure: position on Earth.
class MRadialVelocity
A Measure: radial velocity.
class MRBase
Base for Reference frame for physical measures.
struct MRBase_global_functions_Output
Global functions.
class Muvw
A Measure: uvw on Earth.
class Nutation
Nutation class and calculations.
class ParAngleMachine
Converts a direction into parallactic angle.
class Precession
Precession class and calculations.
class Quality
Quality parameter definitions.
class SolarPos
Solar position class and calculations.
class Stokes
Stokes parameter definitions for interface to table data.
class UVWMachine
Converts UVW coordinates between coordinate systems.
class VelocityMachine
Converts between velocities and frequencies.
class ArrayQuantColumn
Provides read/write access to Array Quantum columns in Tables.
class ScalarQuantColumn
Provides access to Scalar Quantum Columns in Tables.
class TableMeasColumn
Read only access to table scalar Measure columns.
class TableMeasDesc
Definition of a Measure column in a Table.
class TableMeasDescBase
Definition of a Measure in a Table.
class TableMeasOffsetDesc
Definition of a Measure Offset in a Table.
class TableMeasRefDesc
Definition of a Measure Reference in a Table.
class TableMeasType
Definition of a Measure column in a Table.
class TableMeasValueDesc
Definition of a Measure Value in a Table.
class TableQuantumDesc
A class for defining Quantum columns in Tables.
class DirectionEngine
Engine for TaQL UDF Direction conversions.
class DirectionUDF
TaQL UDFs for Direction conversions.
class EpochEngine
Engine for TaQL UDF Epoch conversions.
class EpochUDF
TaQL UDFs for Epoch conversions.
class PositionEngine
Engine for TaQL UDF Position conversions.
class PositionUDF
TaQL UDFs for Position conversions.
class HelpMeasUDF
class MrsEligibility
class MeasurementSet
A Table intended to hold astronomical data (a set of Measurements).
class MSAntenna
A Table intended to hold a MeasurementSet ANTENNA table.
class ROMSAntennaColumns
A class to provide easy read-only access to MSAntenna columns.
class MSAntennaColumns
A class to provide easy read-write access to MSAntenna columns.
class MSAntennaEnums
Enums for the MeasurementSet ANTENNA table.
class ROMSColumns
A class to provide easy read-only access to MeasurementSet columns.
class MSColumns
A class to provide easy read-write access to MeasurementSet columns.
class ROMSDataDescColumns
A class to provide easy read-only access to MSDataDesc columns.
class MSDataDescColumns
A class to provide easy read-write access to MSDataDescription columns.
class MSDataDescriptionEnums
Enums for the MeasurementSet DATA_DESCRIPTION table.
class MSDataDescription
A Table intended to hold a MeasurementSet DATADESCRIPTION table.
class MSDoppler
A Table intended to hold a MeasurementSet DOPPLER table.
class ROMSDopplerColumns
A class to provide easy read-only access to MSDoppler columns.
class MSDopplerColumns
A class to provide easy read-write access to MSDoppler columns.
class MSDopplerEnums
Enums for the MeasurementSet DOPPLER table.
class MSDopplerUtil
A utility class for MS Doppler tracking information.
class MSFeed
A Table intended to hold a MeasurementSet FEED table.
class ROMSFeedColumns
A class to provide easy read-only access to MSFeed columns.
class MSFeedColumns
A class to provide easy read-write access to MSFeed columns.
class MSFeedEnums
Enums for the MeasurementSet FEED table.
class MSField
A Table intended to hold a MeasurementSet FIELD table.
class ROMSFieldColumns
A class to provide easy access to MSField columns.
class MSFieldColumns
A class to provide easy read-write access to MSField columns.
class MSFieldEnums
Enums for the MeasurementSet FIELD table.
class MSFlagCmd
A Table intended to hold a MeasurementSet FLAG_CMD table.
class ROMSFlagCmdColumns
A class to provide easy read-only access to MSFlagCmd columns.
class MSFlagCmdColumns
A class to provide easy read-write access to MSFlagCmd columns.
class MSFlagCmdEnums
Enums for the MeasurementSet FLAG_CMD table.
class ROMSFreqOffsetColumns
A class to provide easy read-only access to MSFreqOffset columns.
class MSFreqOffsetColumns
A class to provide easy read-write access to MSFreqOffset columns.
class MSFreqOffsetEnums
Enums for the MeasurementSet FREQ_OFFSET table.
class MSFreqOffset
A Table intended to hold a MeasurementSet FREQ_OFFSET table.
class MSHistory
A Table intended to hold a MeasurementSet OBSERVATIONLOG table.
class ROMSHistoryColumns
A class to provide easy read-only access to MSHistory columns.
class MSHistoryColumns
A class to provide easy read-write access to MSHistory columns.
class MSHistoryEnums
Enums for the MeasurementSet HISTORY table.
class MSHistoryHandler
A class to provide a simple interface to history writing.
class MSInterval
Small helper class to specify an 'interval' comparison.
class MSIter
An iterator class for MeasurementSets.
class ROMSMainColumns
A class for easy read-only access to MeasurementSet main table columns.
class MSMainColumns
A class for easy read-write access to MeasurementSet main table columns.
class MSMainEnums
Enums for the MeasurementSet main table.
class ROMSObservationColumns
A class to provide easy read-only access to MSObservation columns.
class MSObservationColumns
A class to provide easy read-write access to MSObservation columns.
class MSObservationEnums
Enums for the MeasurementSet OBSERVATION table.
class MSObservation
A Table intended to hold a MeasurementSet OBSERVATION table.
class MSPointing
A Table intended to hold a MeasurementSet POINTING table.
class ROMSPointingColumns
A class to provide easy read-only access to MSPointing columns.
class MSPointingColumns
A class to provide easy read-write access to MSPointing columns.
class MSPointingEnums
Enums for the MeasurementSet POINTING table.
class MSPolarization
A Table intended to hold a MeasurementSet POLARIZATION table.
class ROMSPolarizationColumns
A class to provide easy read-only access to MSPolarization columns.
class MSPolarizationColumns
A class to provide easy read-write access to MSPolarization columns.
class MSPolarizationEnums
Enums for the MeasurementSet POLARIZATION table.
class MSProcessor
A Table intended to hold a MeasurementSet PROCESSOR table.
class ROMSProcessorColumns
A class to provide easy read-only access to MSProcessor columns.
class MSProcessorColumns
A class to provide easy read-write access to MSProcessor columns.
class MSProcessorEnums
Enums for the MeasurementSet PROCESSER table.
class MSRange
MSRange determines ranges of values in a MeasurementSet.
class MSSource
A Table intended to hold a MeasurementSet SOURCE table.
class ROMSSourceColumns
A class to provide easy read-only access to MSSource columns.
class MSSourceColumns
A class to provide easy read-write access to MSSource columns.
class MSSourceEnums
Enums for the MeasurementSet SOURCE table.
class MSSpectralWindow
A Table intended to hold a MeasurementSet SPECTRAL_WINDOW table.
class ROMSSpWindowColumns
A class to provide easy read-only access to MSASpectralWindow columns.
class MSSpWindowColumns
A class to provide easy read-write access to MSSpectralWindow columns.
class MSSpectralWindowEnums
Enums for the MeasurementSet SPECTRAL_WINDOW table.
class MSState
A Table intended to hold a MeasurementSet STATE table.
class ROMSStateColumns
A class to provide easy read-only access to MSState columns.
class MSStateColumns
A class to provide easy read-write access to MSState columns.
class MSStateEnums
Enums for the MeasurementSet STATE table.
class MSSysCal
A Table intended to hold a MeasurementSet SYSCAL table.
class ROMSSysCalColumns
A class to provide easy read-only access to MSSysCal columns.
class MSSysCalColumns
A class to provide easy read-write access to MSSysCal columns.
class MSSysCalEnums
Enums for the MeasurementSet SYSCAL table.
class MSTable
A Table intended to hold astronomical data.
class MSTableImpl
An implementation class for the MeasurementSet to share code.
class MSTileLayout
An helper class for deciding on tile shapes in MeasurementSets.
class MSWeather
A Table intended to hold a MeasurementSet WEATHER table.
class ROMSWeatherColumns
A class to provide easy read-only access to MSWeather columns.
class MSWeatherColumns
A class to provide easy read-write access to MSWeather columns.
class MSWeatherEnums
Enums for the MeasurementSet WEATHER table.
class StokesConverter
StokesConverter converts any set of polarizations into any other one.
class MS1ToMS2Converter
Class to convert a MeasurementSet v1 to v2.
class MSConcat
A class with functions for concatenating MeasurementSets.
class MSDerivedValues
MSDerivedValues calculates values derived from a MS.
class MSFlagger
MSFlagger specifies selections on a MeasurementSet.
struct SubScanKey
A sub scan is a unique combination of observation ID, array ID, scan number, and field ID.
struct ScanKey
A scan is a unique combination of observation ID, array ID, and scan number Negative values are allowed to indicate all values of the particular ID are desired.
struct ArrayKey
An ArrayKey is a unique combination of observation ID and array ID Negative values are allowed to indicate all values of the particular ID are desired.
struct SourceKey
represents primary key in the SOURCE table
class MSLister
List visibility records from a Measurement Set.
class MSMetaData
Class to interrogate an MS for metadata. Interrogation happens on demand and resulting metadata are stored for use by subsequent queries if the cache has not exceeded the specified limit. Parallel processing is enabled using openmp.
class MSReader
Read from an MS, coordinating all of the subtables in the process.
class MSSummary
Provides and lists information about the header of an image.
class MSValidIds
class NewMSSimulator
Create an empty MeasurementSet from observation and telescope descriptions.
struct MSAntennaGram_global_functions_MSAntennaGramFunctions
Global functions for flex/bison scanner/parser for MSAntennaGram.
class MSAntennaIndex
Class to handle lookup or indexing into a MS ANTENNA subtable.
class MSAntennaParse
Class to hold values from antenna grammar parser.
struct MSArrayGram_global_functions_MSArrayGramFunctions
Global functions for flex/bison scanner/parser for MSArrayGram.
class MSArrayParse
Class to hold values from array grammar parser.
struct MSCorrGram_global_functions_MSCorrGramFunctions
Global functions for flex/bison scanner/parser for MSCorrGram.
class MSCorrParse
Class to hold values from UV dist grammar parser.
class MSDataDescIndex
Class to handle lookup or indexing into a MS DATA_DESC subtable.
class MSDopplerIndex
struct MSFeedGram_global_functions_MSFeedGramFunctions
Global functions for flex/bison scanner/parser for MSFeedGram.
class MSFeedIndex
class MSFeedParse
Class to hold values from feed grammar parser.
struct MSFieldGram_global_functions_MSFieldGramFunctions
Global functions for flex/bison scanner/parser for MSFieldGram.
class MSFieldIndex
Class to handle lookup or indexing into a MS FIELD subtable.
class MSFieldParse
Class to hold values from field grammar parser.
class MSFreqOffIndex
struct MSObservationGram_global_functions_MSObservationGramFunctions
Global functions for flex/bison scanner/parser for MSObservationGram.
class MSObservationParse
Class to hold values from scan grammar parser.
class MSObservationIndex
Class to handle lookup or indexing into an MS OBSERVATION subtable.
class MSParse
Class to hold values from an ms grammar parser.
class MSPointingIndex
class MSPolarizationIndex
Class to handle lookup or indexing into an MS POLARIZATION subtable.
struct MSPolnGram_global_functions_MSPolnGramFunctions
Global functions to drive the MSPolnParse class. These, for Polarization selection, need not be global functions, but are done this way to keep the interface uniform for the various selection expressions.
class MSPolnParse
Class to hold values from field grammar parser.
struct MSScanGram_global_functions_MSScanGramFunctions
Global functions for flex/bison scanner/parser for MSScanGram.
class MSScanParse
Class to hold values from scan grammar parser.
class MSSelectableMainColumn
class MSMainColInterface
class MSSelectableTable
MSSelectableTable: An interface class used by MSSelection module to access the sub-tables and main-table columns of MS-like tables.
class MSInterface
MSInterface: A specialization of MSSelectableTable for accessing MS.
class MSSelection
MSSelection: Class to represent a selection on an MS.
class MSSelectionError
class MSSelectionNullSelection
class MSSelectionNullExpr
class MSSelectionNullTEN
class MSSelectionTimeError
class MSSelectionTimeParseError
class MSSelectionAntennaError
class MSSelectionAntennaParseError
class MSSelectionFieldError
class MSSelectionFieldParseError
class MSSelectionFieldWarning
class MSSelectionUvDistError
class MSSelectionUvDistParseError
class MSSelectionSpwError
class MSSelectionSpwParseError
class MSSelectionSpwWarning
class MSSelectionScanError
class MSSelectionScanParseError
class MSSelectionScanWarning
class MSSelectionArrayError
class MSSelectionArrayParseError
class MSSelectionArrayWarning
class MSSelectionPolnError
class MSSelectionPolnParseError
class MSSelectionPolnWarning
class MSSelectionStateError
class MSSelectionStateParseError
class MSSelectionStateWarning
class MSSelectionObservationError
class MSSelectionObservationParseError
class MSSelectionObservationWarning
class MSSelectionFeedError
class MSSelectionFeedParseError
class MSSelectionErrorHandler
class MSSelectionLogError
class MSSelectionKeywords
MSSelectionKeywords specifies selection keywords for the MeasurementSet.
class MSSelector
MSSelector specifies selections on a MeasurementSet.
class MSSelUtil
Helper class for MSFlagger with templated static function.
class MSSelUtil2
class MSSourceIndex
struct MSSpwGram_global_functions_MSSpwGramFunctions
Global functions for flex/bison scanner/parser for MSSpwGram.
class MSSpwIndex
Class to handle lookup or indexing into a MS Data_Desc_ID and SpectralWindow subtables.
class MSSpWindowIndex
Class to handle lookup or indexing into a MS SPECTRAL_WINDOW subtable.
class MSSpwParse
Class to hold values from field grammar parser.
class MSSSpwErrorHandler
struct MSStateGram_global_functions_MSStateGramFunctions
Global functions for flex/bison scanner/parser for MSStateGram.
class MSStateIndex
Class to handle lookup or indexing into a MS FIELD subtable.
class MSStateParse
Class to hold values from field grammar parser.
class MSSysCalIndex
class MSTableIndex
struct TimeFields
struct MSTimeGram_global_functions_MSTimeGramFunctions
Global functions for flex/bison scanner/parser for MSTimeGram.
class MSTimeParse
Class to hold values from time grammar parser.
struct MSUvDistGram_global_functions_MSUvDistGramFunctions
Global functions for flex/bison scanner/parser for MSUvDistGram.
class MSUvDistParse
Class to hold values from UV dist grammar parser.
class MSWeatherIndex
class FITSIDItoMS1
FITSIDItoMS converts a FITS-IDI file to a CASA Measurement Set.
class MSFitsIDI
MSFitsIDI: Convert FITS-IDI data to MS format.
class MSPrimaryTableHolder
A helper class for MSFitsInput.
class MSPrimaryGroupHolder
A helper class for MSFitsInput.
class MSFitsInput
UV FITS to MeasurementSet filler.
class MSFitsOutput
Write a MeasurementSet to a random group uvfits file.
class MSFitsOutputAstron
Write a MeasurementSet to a random group uvfits file.
class SDAntennaHandler
class SDDataDescHandler
class SDFeedHandler
class SDFieldHandler
class SDFITSHandler
class SDHistoryHandler
class SDMainHandler
class SDObservationHandler
class SDPointingHandler
class SDPolarizationHandler
class SDSourceHandler
class SDSpWindowHandler
class SDSysCalHandler
class SDWeatherHandler
class FitGaussian
Multidimensional fitter class for Gaussians.
class GenericL2Fit
Generic base class for least-squares fit.
class FittingProxy
This class gives Proxy to Fitting connection.
class Function
Numerical functional interface class.
class LinearFit
Class for linear least-squares fit.
class LinearFitSVD
Linear least-squares fit using Singular Value Decomposition method.
class LSQaips
Interface for Casacore Vectors in least squares fitting.
class LSQFit
Basic class for the least squares fitting.
class LSQMatrix
Support class for the LSQ package.
class LSQReal
Typing support classes for LSQ classes.
class LSQComplex
Type of complex numeric class indicator.
class LSQNull
Non relevant class indicator.
class LSQType
Determine if pointer type.
class LSQTraits
Traits for numeric classes used.
class LSQTraits_F< Float >
LSQTraits specialization for Float.
class LSQTraits_D< Double >
LSQTraits specialization for Double.
class LSQTraits_CD< std::complex< Double > >
LSQTraits specialization for DComplex.
class LSQTraits_CF< std::complex< Float > >
LSQTraits specialization for Complex.
class NonLinearFit
Class for non-linear least-squares fit.
class NonLinearFitLM
Solve non-linear fit with Levenberg-Marquardt method.
class FunctionFactory
a class for creating Function objects from Records
class ArraySampledFunctional
Index into an array using the longest axis.
class Chebyshev
A function class that defines a Chebyshev polynomial.
class ChebyshevEnums
Define enums for Chebyshev classes.
class ChebyshevParam
Parameter handling for Chebyshev polynomial parameters.
class ChebyshevParamModeImpl
A ChebyshevParam with the get/setMode implementation.
class ChebyshevParamModeImpl_PS< AutoDiff< T > >
Partial specialization of ChebyshevParamModeImpl for AutoDiff
class ChebyshevParamModeImpl_PSA< AutoDiffA< T > >
Partial specialization of ChebyshevParamModeImpl for AutoDiff
class CombiFunction
Form a linear combination of function objects.
class CombiFunction_PS< AutoDiff< T > >
Partial specialization of CombiFunction for AutoDiff
class CombiParam
Parameters for a linear combination of function objects.
class CompiledFunction
Form a linear combination of function objects.
class CompiledParam
Parameters for a compiled string function object.
class CompoundFunction
Sum of a collection of Functions which behaves as one Function object.
class CompoundFunction_PS< AutoDiff< T > >
Partial AutoDiff specialization of CompoundFunction.
class CompoundParam
Parameters for sum of parameterized Functions.
class ConstantND
A constant function.
class ConstantND_PS< AutoDiff< T > >
Partial specialization of ConstantND for AutoDiff
class ConstantNDParam
Parameter handling for a constant function in a space of arbitrary dimensionality.
class DiracDFunction
A one dimensional Dirac delta function.
class DiracDParam
A one dimensional Dirac delta function.
class EclecticFunctionFactory
class EvenPolynomial
A one dimensional odd polynomial class.
class EvenPolynomial_PS< AutoDiff< T > >
Partial specialization of EvenPolynomial for AutoDiff
class EvenPolynomialParam
Parameter handling for even polynomials.
class FuncExprData
Data and enumerations for functional expressions.
struct FuncExprData_global_functions_output
Output function.
class FuncExpression
An expression executable as function.
struct FuncExpression_global_functions_output
Output function.
struct FuncExpression_global_functions_execute
Execute function.
struct Function_global_functions_Output
Global functions.
class Function1D
Numerical functional interface class for 1 dimension.
class FunctionalProxy
class FunctionFactoryError
class UnrecognizedFunctionError
class InvalidSerializationError
class FieldNotFoundError
class FunctionHolder
A holder for Functions to enable record conversions.
class FunctionMarshallable
a class for serializing/reconstituting Function objects to/from Records
class FunctionOrder
Container of function description details.
struct FunctionOrder_global_functions_Output
Global functions.
class FunctionParam
Container of function parameters with masking flags.
struct FunctionParam_global_functions_Output
Global functions.
class FunctionTraits
Function data types for parameters and arguments.
class FunctionTraits_P< AutoDiff< T > >
FunctionTraits specialization for AutoDiff.
class FunctionTraits_PA< AutoDiffA< T > >
FunctionTraits specialization for AutoDiffA.
class FunctionTraits_PX< AutoDiffX< T > >
FunctionTraits specialization for AutoDiffX.
class WrapperBase
Aid in constructing function objects from C++ functions.
class FunctionWrapper
Construct nD function objects from C++ functions.
class Gaussian1D
A one dimensional Gaussian class.
class Gaussian1D_PS< AutoDiff< T > >
Partial specialization of Gaussian1D for AutoDiff
class Gaussian1DParam
Parameter handling for one dimensional Gaussian class.
class Gaussian2D
A two dimensional Gaussian class.
class Gaussian2D_PS< AutoDiff< T > >
Partial specialization of Gaussian2D for AutoDiff
class Gaussian2DParam
Parameter handling for 2 dimensional Gaussian class.
class Gaussian3D
A three dimensional Gaussian class.
class Gaussian3D_PS< AutoDiff< T > >
Partial specialization of Gaussian3D for AutoDiff
class Gaussian3DParam
Parameter handling for 3 dimensional Gaussian class.
class GaussianND
A Multi-dimensional Gaussian functional.
class GaussianNDParam
A Multi-dimensional Gaussian parameter handling.
class GNoiseFunction
A one dimensional normal distribution.
class GNoiseParam
A one dimensional normal distribution.
class HyperPlane
A hyper plane function.
class HyperPlane_PS< AutoDiff< T > >
Partial specialization of HyperPlane for AutoDiff
class HyperPlaneParam
Parameter handling for a hyper plane function.
class SampledFunctional
A base class for indexing into arbitrary data types.
class KaiserBFunction
A one dimensional Kaiser-Bessel function.
class KaiserBParam
A one dimensional Kaiser-Bessel function.
class Lorentzian1D
A one dimensional Lorentzian class.
class Lorentzian1D_PS< AutoDiff< T > >
Partial specialization of Lorentzian1D for AutoDiff
class Lorentzian1DParam
Parameter handling for one dimensional Lorentzian class.
class MarshallableChebyshev
A Chebyshev function class that supports serialization.
class MarshButterworthBandpass
A Butterworth function class that supports serialization.
class OddPolynomial
A one dimensional odd polynomial class.
class OddPolynomial_PS< AutoDiff< T > >
Partial specialization of OddPolynomial for AutoDiff
class OddPolynomialParam
Parameter handling for odd polynomials.
class PoissonFunction
A one dimensional Poisson function.
class PoissonFunction_PS< AutoDiff< T > >
Partial specialization of PoissonFunction for AutoDiff
class PoissonParam
A one dimensional Poisson function.
class Polynomial
A one dimensional polynomial class.
class Polynomial_PS< AutoDiff< T > >
Partial specialization of Polynomial for AutoDiff
class PolynomialParam
Parameter handling for one-dimensional polynomials.
class PowerLogarithmicPolynomial
A one dimensional power logarithmic polynomial class of form y = c_0 * x**(c_1 + c_2*ln(x) + c_3*ln(x)**2 + ... c_n*ln(x)**(n-1))
class PowerLogarithmicPolynomial_PS< AutoDiff< T > >
Partial specialization of PowerLogarithmicPolynomial for AutoDiff
class PowerLogarithmicPolynomialParam
Parameter handling for one-dimensional power logarithmic polynomials.
class ScalarSampledFunctional
A unified interface for indexing into Vectors or Blocks.
class SerialHelper
class SimButterworthBandpass
a class for evaluating a Butterworth filter transfer function.
class SincFunction
A one dimensional sin(x)/x.
class SincParam
A one dimensional sin(x)/x.
class Sinusoid1D
A one dimensional Sinusoid class.
class Sinusoid1D_PS< AutoDiff< T > >
Partial specialization of Sinusoid1D for AutoDiff
class Sinusoid1DParam
Parameter handling for one dimensional Sinusoid class.
class SpecificFunctionFactory
class SPolynomial
A one dimensional scaled polynomial class.
class SPolynomialParam
Parameter handling for scaled 1-D polynomials.
class UnaryFunction
A one dimensional unary function.
class UnaryParam
Parameter handling for one dimensional unary function.
class WrapperData
Aid in constructing function objects from C++ functions.
class WrapperData_TT< T, T, T, True, True >
Specialization for calls with argument and parameter.
class WrapperData_VT< T, Vector< T >, T, True, True >
Specialization for calls with argument and parameter.
class WrapperData_TV< T, T, Vector< T >, True, True >
Specialization for calls with argument and parameters.
class WrapperData_VV< T, Vector< T >, Vector< T >, True, True >
Specialization for calls with argument and parameters.
class WrapperData_FT< T, T, T, False, True >
Specialization for calls with no arguments and parameter.
class WrapperData_FV< T, T, Vector< T >, False, True >
Specialization for calls with no arguments and parameters.
class WrapperData_TF< T, T, T, True, False >
Specialization for calls with argument and no parameters.
class WrapperData_VF< T, Vector< T >, T, True, False >
Specialization for calls with argument and no parameters.
class WrapperData_FF< T, T, T, False, False >
Specialization for calls with no arguments and no parameters.
class WrapperParam
Parameter handling for wrapped function objects.
class AutoDiff
Class that computes partial derivatives by automatic differentiation.
class AutoDiffA
Class that computes partial derivatives by automatic differentiation.
struct AutoDiffIO_global_functions_AutoDiff_IO_operations
Implements all IO operators and functions for AutoDiff.
struct AutoDiffMath_global_functions_AutoDiff_mathematical_operations
Implements all mathematical operators and functions for AutoDiff.
class AutoDiffRep
Representation of an automatic differential class data.
class AutoDiffX
Class that computes partial derivatives by automatic differentiation.
class ChauvenetCriterionStatistics
Class to calculate statistics using the so-called Chauvenet criterion.
class ClassicalStatistics
Class to calculate statistics in a "classical" sense, ie using accumulators with no special filtering beyond optional range filtering etc.
class Combinatorics
Combinatorics related functions.
class ConstrainedRangeStatistics
Abstract base class for statistics algorithms which are characterized by a range of good values.
class ConvolveGridder
Does convolutional gridding.
class Convolver
Forward Declarations.
class DFTError
Error class for DFTServer class.
class DFTServer
Class containing methods for doing n-D slow Fourier transforms.
class FFTPack
C++ interface to the Fortran FFTPACK library.
class FFTEnums
Lists the different types of FFT's that can be done.
class FFTServer
A class with methods for Fast Fourier Transforms.
class FFTW
C++ interface to the FFTWw library.
class FitToHalfStatistics
Class to calculate statistics using the so-called fit to half algorithm.
class FitToHalfStatisticsData
Various data for FitToHalfStatistics.
class GaussianBeam
Represents a Gaussian restoring beam associated with an image.
class Geometry
Geometry related methods.
class Gridder
A base class for gridding.
class HingesFencesStatistics
Class to calculate statistics using the so-called hinges and fences algorithm.
class HistAcc
Makes a histogram from input values.
class Interpolate2D
A two dimension interpolator for Matrices or Arrays.
class InterpolateArray1D
Interpolate in one dimension.
class MathFuncError
Error class for MathFunc class.
struct MathFunc_global_functions_spheriodal_functions
Fred Schwab function to calculate spheriodal functions.
struct MathFunc_global_functions_FUNCTYPE_enum
Enum used to identify function type for MathFunc class.
struct FuncId
Function ID, for use by MathFunc class.
class MathFunc
A class to generate values of mathematical functions.
class Unary
Unary.
class GaussianConv
Gaussian.
class KB_Conv
A Kaiser-Bessel function.
class Mod_KB_Conv
A Kaiser-Bessel function multiplied by a Gaussian.
class Sinc_Conv
Sine x / x function.
class Sph_Conv
Spheroidal function.
class ExpSincConv
Exponential times a Sinc.
struct MatrixMathLA_global_functions_Linear_Algebra
Linear algebra functions on Vectors and Matrices.
class MatrixSolver
MatrixSolver.h: the base class for solvers of linear equations AX=B.
class MedianSlider
Class to compute sliding median.
class NNGridder
A non-negative gridding class.
class NNLSMatrixSolver
NNLSMatrixSolver.h: the base class for NNLS solvers of linear equations AX=B.
class NumericTraits
Relationships between numeric data types.
class NumericTraits_F< Float >
NumericTraits specialization for Float.
class NumericTraits_D< Double >
NumericTraits specialization for Double.
class NumericTraits_C< Complex >
NumericTraits specialization for Complex.
class NumericTraits_DC< DComplex >
NumericTraits specialization for DComplex.
class NumericTraits< Float >
A specialisation for T=Float of the NumericTraits class.
class NumericTraits< Double >
A specialisation for T=Double of the NumericTraits class.
class NumericTraits< Complex >
A specialisation for T=Complex of the NumericTraits class.
class NumericTraits< DComplex >
A specialisation for T=DComplex of the NumericTraits class.
class SquareMatrix
Fast Square Matrix class with fixed (templated) size.
class RigidVector
Fast Vector classes with fixed (templated) length.
struct RigidVector_global_functions_math
Mathematical operations involving RigidVectors.
class SCSL
C++ Interface to the Sgi/Cray Scientific Library (SCSL)
class Smooth
Smooth a Vector or the rows of a 2D Array taking into account flags which are supplied in a Vector/Array of the same shape. Modify the flags as necessary to mark channels for which the smoothing could not be done because needed channels were flagged.
class SparseDiff
Class that computes partial derivatives by automatic differentiation.
class SparseDiffA
Class that computes partial derivatives by automatic differentiation.
struct SparseDiffIO_global_functions_SparseDiff_IO_operations
Implements all IO operators and functions for SparseDiff.
struct SparseDiffMath_global_functions_SparseDiff_mathematical_operations
Implements all mathematical operators and functions for SparseDiff.
class SparseDiffRep
Representation of data for the spare automatic differentiation calss.
class SparseDiffX
Class that computes partial derivatives by automatic differentiation.
struct SquareMatrix_global_functions_SqM_global_functions
Various global math and IO functions.
class StatAcc
A statistics accumulator.
class StatisticsAlgorithm
Base class of statistics algorithm class hierarchy.
class StatisticsData
class StatisticsIncrementer
Utility functions used for incrementing pointers in a data set used by the stats framework.
struct StatsData
class StatisticsUtilities
Various statistics related methods for the statistics framework.
class StatsDataProvider
Abstract base class which defines interface for providing "datasets" to the statistics framework when nontrivial means of doing so are not sufficient.
class VanVleck
A class of static functions to aid with vanVleck corrections of lag data.
class VectorKernel
Make a Vector smoothing kernel from a kernel specification.
class ZScoreCalculator
class BaseMappedArrayEngine
Templated virtual column engine for a table array of any type.
class BFEngineMask
Non-templated Helper class to handle the mask.
class BitFlagsEngine
Templated virtual column engine to map bit flags to a Bool.
class CompressComplex
Virtual column engine to scale a table Complex array.
class CompressComplexSD
Virtual column engine to scale a table Complex array for Single Dish data.
class CompressFloat
Virtual column engine to scale a table float array.
class RODataManAccessor
Base class for the Data Manager Accessor classes.
struct DataManager_global_functions_DataManagerCtor
Define the type of the static construction function.
class DataManager
Abstract base class for a data manager.
class DataManagerColumn
Abstract base class for a column in a data manager.
class DataManError
Base error class for table data manager.
class DataManInternalError
Internal table data manager error.
class DataManUnknownCtor
Table DataManager error; invalid data manager.
class DataManInvDT
Table DataManager error; invalid data type.
class DataManInvOper
Table DataManager error; invalid operation.
class DataManUnknownVirtualColumn
Table DataManager error; unknown virtual column.
class TSMError
Table DataManager error; error in TiledStMan.
class DataManInfo
Class with static functions to manipulate a datamanager record.
class ForwardColumn
Virtual column forwarding to another column.
class ForwardColumnEngine
Virtual column engine forwarding to other columns.
class ForwardColumnIndexedRow
Virtual column forwarding to another row/column.
class ForwardColumnIndexedRowEngine
Virtual column engine forwarding to other columns/rows.
class IncrementalStMan
The Incremental Storage Manager.
class ROIncrementalStManAccessor
Give access to some IncrementalStMan functions.
class ISMBase
Base class of the Incremental Storage Manager.
class ISMBucket
A bucket in the Incremental Storage Manager.
class ISMColumn
A Column in the Incremental Storage Manager.
class ISMIndColumn
A column of Incremental storage manager for indirect arrays.
class ISMIndex
The Index of the Incremental Storage Manager.
class MappedArrayEngine
Templated virtual column engine to map the data type of a table array.
class MemoryStMan
Memory-based table storage manager class.
class MSMBase
Base class for memory-based table storage manager class.
class MSMColumn
Column in the Memory table storage manager class.
class MSMDirColumn
Memory storage manager for table arrays.
class MSMIndColumn
Mmeory storage manager for variable shaped table arrays.
class RetypedArrayEngine
Virtual column engine to retype and reshape arrays.
struct RetypedArraySetGet_global_functions_RetypedArrayEngineSetGet
Helper functions for users of RetypedArrayEngine.
class ScaledArrayEngine
Templated virtual column engine to scale a table array.
class ScaledComplexData
Templated virtual column engine to scale a complex table array.
class SSMBase
Base class of the Standard Storage Manager.
class SSMColumn
A Column in the Standard Storage Manager.
class SSMDirColumn
A Direct Array Column in the Standard Storage Manager.
class SSMIndColumn
A column of Standard storage manager for indirect arrays.
class SSMIndex
The bucket index for a group of columns in the Standard Storage Manager.
class SSMIndStringColumn
An Indirect String Array Column in the Standard Storage Manager.
class SSMStringHandler
Store strings in the Standard Storage Manager.
class StandardStMan
The Standard Storage Manager.
class ROStandardStManAccessor
Give access to some StandardStMan functions.
class StManColumnArrayAipsIO
AipsIO storage manager for direct table arrays.
class StManArrayFile
Read/write array in external format for a storage manager.
class StManColumnIndArrayAipsIO
AipsIO storage manager for indirect table arrays.
class StIndArray
Read/write indirect arrays.
class StManColumnAipsIO
AipsIO table column storage manager class.
class StManAipsIO
AipsIO table storage manager class.
class StManColumn
Base table column storage manager class.
class TiledCellStMan
Tiled Cell Storage Manager.
class TiledColumnStMan
Tiled Column Storage Manager.
class TiledDataStMan
Tiled Data Storage Manager.
class TiledDataStManAccessor
Give access to some TiledDataStMan functions.
class TiledFileAccess
Tiled access to an array in a file.
class TiledFileHelper
Helper class for tiled access to an array in a file.
class TiledShapeStMan
Tiled Data Storage Manager using the shape as id.
class TiledStMan
Base class for Tiled Storage Manager classes.
class ROTiledStManAccessor
Give access to some TiledStMan functions.
class TSMColumn
A column in the Tiled Storage Manager.
class TSMCoordColumn
A coordinate column in Tiled Storage Manager.
class TSMCube
Tiled hypercube in a table.
class TSMCubeBuff
Tiled hypercube in a table.
class TSMCubeMMap
Tiled hypercube in a table.
class TSMDataColumn
A data column in Tiled Storage Manager.
class TSMFile
File object for Tiled Storage Manager.
class TSMIdColumn
An id column in Tiled Storage Manager.
class TSMOption
Options for the Tiled Storage Manager Access.
class TSMShape
Expanded IPosition for shapes.
class VirtualArrayColumn
Templated base class for virtual array column.
class VirtualColumnEngine
Abstract base class for virtual column handling.
class VirtualScalarColumn
Templated base class for virtual scalar column.
struct VirtScaCol_global_functions_getVirtualScalarColumn
Global functions to get or put data of a virtual column.
class VirtualTaQLColumn
Virtual scalar column using TaQL.
class VSCEngine
Base virtual column for a scalar column with any type.
class LogFilterExpr
Class to deal with a TaQL expression to filter messages.
class LogFilterTaql
Filter LogMessages using a TaQL expression.
class LoggerHolder
Class holding a hierarchy of loggers.
class LoggerHolderRep
Representation of the class holding a hierarchy of loggers.
class LogHolderIterEntry
Class representing an entry in a LoggerHolder.
class LogHolderIter
Class doing the actual iteration through an LoggerHolder.
class LoggerHolderIterator
Class to iterate through an LoggerHolder.
class NewFile
Do checks for a new (non-existent) file.
class TableLogSink
Save log messages in a Casacore Table.
class BaseSlicesFunctor
Abstract baseclass for slices functors.
class ColumnSlicer
class GetCellSlices
Functor to get irregular array slices from a cell.
class GetColumnSlices
Functor to get irregular array slices from a column.
class PutCellSlices
Functor to put irregular array slices into a cell.
class PutColumnSlices
Functor to get irregular array slices from a column.
class ArrayColumnDesc
Templated class for description of table array columns.
class ArrayColumnData
Access to a table column containing arrays.
class BaseColumnDesc
An abstract base class for table column descriptions.
class BaseColumn
Abstract base class for a table column.
class BaseTableIterator
Base class for table iterator.
class BaseTable
Abstract base class for tables.
class ColumnDescSet
Set of table column descriptions.
class ColumnCache
A caching object for a table column.
class ColumnDesc
Envelope class for the description of a table column.
class ColumnSet
Class to manage a set of table columns.
class ColumnsIndex
Index to one or more columns in a table.
class ColumnsIndexArray
Index to an array column in a table.
class ConcatColumn
A column in a concatenated table.
class ConcatRows
Class holding the row numbers in a ConcatTable.
class ConcatRowsIter
Class to iterate through a ConcatRows object.
class ConcatScalarColumn
A typed column in a concatenated table.
class ConcatTable
Class to view a concatenation of tables as a single table.
class ExternalLockSync
Class to hold table lock data.
class MemoryTable
Class for a table held in memory.
class NullTable
Class indicating a null Table object.
class PlainColumn
Base class for a column in a plain table.
class PlainTable
Class defining a plain regular table.
struct ReadAsciiTable_global_functions_readAsciiTable
Filling a table from an Ascii file.
class ReadAsciiTable
Helper class for readAsciiTable.
class RefColumn
A column in a reference table.
class RefRows
Class holding the row numbers in a RefTable.
class RefRowsSliceIter
Class to iterate through a RefRows object.
class RefTable
Class for a table as a view of another table.
class RowCopier
RowCopier copies all or part of a row from one table to another.
class ScalarColumnDesc
Templated class to define columns of scalars in tables.
class ScalarColumnData
Access to a table column containing scalars.
class ScalarRecordColumnData
Access to a table column containing scalar records.
class ScalarRecordColumnDesc
Class to define columns of scalar records in tables.
class SetupNewTableRep
Representation for handle class SetupNewTable.
class SetupNewTable
Create a new table - define shapes, data managers, etc.
class StorageOption
Options defining how table files are organized.
class SubTableDesc
Description of columns containing tables.
class Table
Main interface class to a read/write table.
class TableAttr
Some attributes of a table.
class TableCache
Cache of open tables.
class TableColumn
Read/write access to a table column.
class TableCopy
Class with static functions for copying a table.
class TableDesc
Define the structure of a Casacore table.
class TableError
Base error class for storage manager.
class TableInternalError
Internal table error.
class TableDuplFile
Table error; table (description) already exists.
class TableNoFile
Table error; table (description) not found.
class TableDescNoName
Table error; no name given to table description.
class TableInvOpt
Table error; invalid table (description) option.
class TableNoDir
Table error; path is not a directory.
class TableNoDatFile
Table error; table.dat file not found.
class TableInvType
Table error; table type mismatch.
class TableInvColumnDesc
Table error; invalid column description.
class TableInvHyperDesc
Table error; invalid hypercolumn description.
class TableUnknownDesc
Table error; unknown column description.
class TableInvDT
Table error; invalid data type.
class TableInvOper
Table error; invalid operation.
class TableArrayConformanceError
Table error; non-conformant array.
class TableConformanceError
Table error; table length conformance error.
class TableInvSort
Table error; invalid sort.
class TableInvLogic
Table error; invalid logical operation.
class TableInvExpr
Table error; invalid select expression.
class TableVectorNonConform
Table error; non-conformant table vectors.
class TableParseError
Table error; invalid table command.
class TableGramError
Table grammar error; invalid table command.
class TableIndexProxy
Proxy for table index access.
class TableInfo
Table type, subtype and further info.
class TableIterator
Iterate through a Table.
class TableIterProxy
Proxy for table iterator access.
class TableKeyword
Keyword value representing a table.
class TableLock
Class to hold table lock options.
class TableLockData
Class to hold table lock data.
class TableLocker
Class to hold a (user) lock on a table.
class TableProxy
High-level interface to tables.
class TableRecord
A hierarchical collection of named fields of various types.
class TableRecordRep
The representation of a TableRecord.
class ROTableRow
Readonly access to a table row.
class TableRow
Read/write access to a table row.
class TableRowProxy
Proxy for table row access.
class TableSyncData
Class to hold table synchronization data.
class TableTrace
Class with static functions for tracing column IO.
class TableVectorHelper
class TableVector
Templated readonly table column vectors.
class TabPath
Search path for table files.
struct TabVecLogic_global_functions_vectorComparison
Comparison between two table vectors.
struct TabVecLogic_global_functions_scalarComparison
Comparison between a table vector and a scalar.
struct TabVecMath_global_functions_basicMath
Basic math for table vectors.
struct TabVecMath_global_functions_basicTransMath
Transcendental math for table vectors.
struct TabVecMath_global_functions_advTransMath
Further transcendental math for table vectors.
struct TabVecMath_global_functions_miscellaneous
Miscellaneous table vector operations.
struct TabVecMath_global_functions_vectorMath
Vector operations on a table vector.
struct TVec_global_functions_enum
Enumeration of possible table vectors.
class TabVecRep
Templated base class for table vectors.
struct TVecLogic_global_functions_vectorComparison
Comparison between two table vectors.
struct TVecLogic_global_functions_scalarComparison
Comparison between a table vector and a scalar.
struct TVecMath_global_functions_basicMath
Basic math for table vectors.
struct TVecMath_global_functions_basicTransMath
Transcendental math for table vectors.
struct TVecMath_global_functions_advTransMath
Further transcendental math for table vectors.
struct TVecMath_global_functions_miscellaneous
Miscellaneous table vector operations.
struct TVecMath_global_functions_vectorMath
Vector operations on a table vector.
class TabVecScaCol
Templated table scalar column vectors.
class TabVecTemp
Templated table vectors held in memory as a temporary.
class TableExprAggrNode
TaQL node representing a scalar aggregate function.
class TableExprAggrNodeArray
TaQL node representing an array aggregate function.
class TableExprConeNode
Class representing a cone search in table select expression.
class TableExprConeNodeArray
class TableExprNodeConstBool
Constant Bool in table select expression tree.
class TableExprNodeConstInt
Constant Int64 in table select expression tree.
class TableExprNodeConstDouble
Constant Double in table select expression tree.
class TableExprNodeConstDComplex
Constant DComplex in table select expression tree.
class TableExprNodeConstString
Constant String in table select expression tree.
class TableExprNodeConstRegex
Constant Regex or StringDistance in table select expression tree.
class TableExprNodeConstDate
Constant Date in table select expression tree.
class TableExprNodeColumn
Scalar column in table select expression tree.
class TableExprNodeRownr
Rownumber in table select expression tree.
class TableExprNodeRowid
Rowid in table select expression tree.
class TableExprNodeRandom
Random number in table select expression tree.
class TableExprNodeArrayConstBool
Bool Array constant in table select expression tree.
class TableExprNodeArrayConstInt
Int Array constant in table select expression tree.
class TableExprNodeArrayConstDouble
Double Array constant in table select expression tree.
class TableExprNodeArrayConstDComplex
DComplex Array constant in table select expression tree.
class TableExprNodeArrayConstString
String Array constant in table select expression tree.
class TableExprNodeArrayConstDate
Date Array constant in table select expression tree.
class TableExprFuncNode
Class representing a function in table select expression.
class TableExprFuncNodeArray
Class representing an array function in table select expression.
class TableExprGroupKey
Class representing a key in the groupby clause.
class TableExprGroupKeySet
Class representing all keys in the groupby clause.
class TableExprGroupResult
Class holding the results of groupby and aggregation.
class TableExprGroupFuncBase
Abstract base class for classes calculating an aggregated group result.
class TableExprGroupNull
Class derived from TableExprGroupFuncBase representing a no function.
class TableExprGroupFirst
Class derived from TableExprGroupFuncBase for the first value in a group.
class TableExprGroupLast
Class derived from TableExprGroupFuncBase for the first value in a group.
class TableExprGroupExprId
Class derived from TableExprGroupFuncBase collecting the ids in a group.
class TableExprGroupRowid
Class collecting the rowids of entries in a group.
class TableExprGroupAggr
Class collecting the arrays in a group.
class TableExprGroupFuncBool
Abstract base class for aggregate functions giving a bool scalar.
class TableExprGroupFuncInt
Abstract base class for aggregate functions giving an integer scalar.
class TableExprGroupFuncDouble
Abstract base class for aggregate functions giving a double scalar.
class TableExprGroupFuncDComplex
Abstract base class for aggregate functions giving a dcomplex scalar.
class TableExprGroupFuncDate
Abstract base class for aggregate functions giving a date/time scalar.
class TableExprGroupFuncString
Abstract base class for aggregate functions giving a string scalar.
class TableExprGroupFuncArrayBool
Abstract base class for aggregate functions giving a bool array.
class TableExprGroupFuncArrayInt
Abstract base class for aggregate functions giving an integer array.
class TableExprGroupFuncArrayDouble
Abstract base class for aggregate functions giving a double array.
class TableExprGroupFuncArrayDComplex
Abstract base class for aggregate functions giving a dcomplex array.
class TableExprGroupFuncArrayDate
Abstract base class for aggregate functions giving a date/time array.
class TableExprGroupFuncArrayString
Abstract base class for aggregate functions giving a string array.
class TableExprGroupFuncSet
Class containing the results of aggregated values in a group.
class TableExprGroupCountAll
Aggregate class counting number of rows in a group.
class TableExprGroupCount
Aggregate class counting number of rows in a group containing a value.
class TableExprGroupAny
Aggregate class counting if any value in a group is true.
class TableExprGroupAll
Aggregate class counting if all values in a group are true.
class TableExprGroupNTrue
Aggregate class counting the number of true values in a group.
class TableExprGroupNFalse
Aggregate class counting the number of false values in a group.
class TableExprGroupMinInt
Aggregate class determining the minimum integer value in a group.
class TableExprGroupMaxInt
Aggregate class determining the maximum integer value in a group.
class TableExprGroupSumInt
Aggregate class determining the sum of integer values in a group.
class TableExprGroupProductInt
Aggregate class determining the product of integer values in a group.
class TableExprGroupSumSqrInt
Aggregate class determining the sum of squares of integer values in a group.
class TableExprGroupMinDouble
Aggregate class determining the minimum double value in a group.
class TableExprGroupMaxDouble
Aggregate class determining the maximum double value in a group.
class TableExprGroupSumDouble
Aggregate class determining the sum of double values in a group.
class TableExprGroupProductDouble
Aggregate class determining the product of double values in a group.
class TableExprGroupSumSqrDouble
Aggregate class determining the sum of squares of double values in a group.
class TableExprGroupMeanDouble
Aggregate class determining the mean of values in a group.
class TableExprGroupVarianceDouble
Aggregate class determining the variance of values in a group.
class TableExprGroupStdDevDouble
Aggregate class determining the standard deviation of values in a group.
class TableExprGroupRmsDouble
Aggregate class determining the RMS of values in a group.
class TableExprGroupFractileDouble
Aggregate class determining the fractile of values in a group.
class TableExprGroupSumDComplex
Aggregate class determining the sum of complex values in a group.
class TableExprGroupProductDComplex
Aggregate class determining the product of complex values in a group.
class TableExprGroupSumSqrDComplex
Aggregate class determining the sum of squares of complex values in a group.
class TableExprGroupMeanDComplex
Aggregate class determining the mean of complex values in a group.
class TableExprGroupArrayAny
Aggregate class counting if any array value in a group is true.
class TableExprGroupArrayAll
Aggregate class counting if all array values in a group are true.
class TableExprGroupArrayNTrue
Aggregate class counting the number of true array values in a group.
class TableExprGroupArrayNFalse
Aggregate class counting the number of false array values in a group.
class TableExprGroupMinArrayInt
Aggregate class determining the minimum integer array value in a group.
class TableExprGroupMaxArrayInt
Aggregate class determining the maximum integer array value in a group.
class TableExprGroupSumArrayInt
Aggregate class determining the sum of integer array values in a group.
class TableExprGroupProductArrayInt
Aggregate class determining the product of integer array values in a group.
class TableExprGroupSumSqrArrayInt
Aggregate class determining the sum of squares of integer array values in a group.
class TableExprGroupMinArrayDouble
Aggregate class determining the minimum double array value in a group.
class TableExprGroupMaxArrayDouble
Aggregate class determining the maximum double array value in a group.
class TableExprGroupSumArrayDouble
Aggregate class determining the sum of double array values in a group.
class TableExprGroupProductArrayDouble
Aggregate class determining the product of double array values in a group.
class TableExprGroupSumSqrArrayDouble
Aggregate class determining the sum of squares of double array values in a group.
class TableExprGroupMeanArrayDouble
Aggregate class determining the mean of array values in a group.
class TableExprGroupVarianceArrayDouble
Aggregate class determining the variance of array values in a group.
class TableExprGroupStdDevArrayDouble
Aggregate class determining the standard devation of array values in a group.
class TableExprGroupRmsArrayDouble
Aggregate class determining the RMS of array values in a group.
class TableExprGroupFractileArrayDouble
Aggregate class determining the fractile of array values in a group.
class TableExprGroupSumArrayDComplex
Aggregate class determining the sum of complex array values in a group.
class TableExprGroupProductArrayDComplex
Aggregate class determining the product of complex array values in a group.
class TableExprGroupSumSqrArrayDComplex
Aggregate class determining the sum of squares of complex array values in a group.
class TableExprGroupMeanArrayDComplex
Aggregate class determining the mean of complex array values in a group.
class TableExprGroupArrayAnys
Aggregate class counting per array index in a group if any is true.
class TableExprGroupArrayAlls
Aggregate class counting per array index in a group if all are true.
class TableExprGroupArrayNTrues
Aggregate class counting per array index in a group the nr of true values.
class TableExprGroupArrayNFalses
Aggregate class counting per array index in a group the nr of false values.
class TableExprGroupMinsArrayInt
Aggregate class determining per array index in a group the minimum value.
class TableExprGroupMaxsArrayInt
Aggregate class determining per array index in a group the maximum value.
class TableExprGroupSumsArrayInt
Aggregate class determining per array index in a group the sum of values.
class TableExprGroupProductsArrayInt
Aggregate class determining per array index in a group the product of values.
class TableExprGroupSumSqrsArrayInt
Aggregate class determining per array index in a group the sum of value squares in a group.
class TableExprGroupMinsArrayDouble
Aggregate class determining the minimum double array value in a group.
class TableExprGroupMaxsArrayDouble
Aggregate class determining the maximum double array value in a group.
class TableExprGroupSumsArrayDouble
Aggregate class determining the sum of double array values in a group.
class TableExprGroupProductsArrayDouble
Aggregate class determining the product of double array values in a group.
class TableExprGroupSumSqrsArrayDouble
Aggregate class determining the sum of squares of double array values in a group.
class TableExprGroupMeansArrayDouble
Aggregate class determining the mean of array values in a group.
class TableExprGroupVariancesArrayDouble
Aggregate class determining the variance of array values in a group.
class TableExprGroupStdDevsArrayDouble
Aggregate class determining the standard devation of array values in a group.
class TableExprGroupRmssArrayDouble
Aggregate class determining the RMS of array values in a group.
class TableExprGroupSumsArrayDComplex
Aggregate class determining the sum of complex array values in a group.
class TableExprGroupProductsArrayDComplex
Aggregate class determining the product of complex array values in a group.
class TableExprGroupSumSqrsArrayDComplex
Aggregate class determining the sum of squares of complex array values in a group.
class TableExprGroupMeansArrayDComplex
Aggregate class determining the mean of complex array values in a group.
class TableExprGroupHistBase
Base aggregate class determining the histogram of values in a group.
class TableExprGroupHistScalar
Aggregate class determining the histogram of scalar values in a group.
class TableExprGroupHistInt
Aggregate class determining the histogram of integer array values in a group.
class TableExprGroupHistDouble
Aggregate class determining the histogram of double array values in a group.
class TableExprNodeEQBool
Bool comparison == in table select expression tree.
class TableExprNodeEQInt
Int comparison == in table select expression tree.
class TableExprNodeEQDouble
Double comparison == in table select expression tree.
class TableExprNodeEQDComplex
DComplex comparison == in table select expression tree.
class TableExprNodeEQString
String comparison == in table select expression tree.
class TableExprNodeEQRegex
Regex comparison == in table select expression tree.
class TableExprNodeEQDate
Date comparison == in table select expression tree.
class TableExprNodeNEBool
Bool comparison != in table select expression tree.
class TableExprNodeNEInt
Int comparison != in table select expression tree.
class TableExprNodeNEDouble
Double comparison != in table select expression tree.
class TableExprNodeNEDComplex
DComplex comparison != in table select expression tree.
class TableExprNodeNEString
String comparison != in table select expression tree.
class TableExprNodeNERegex
Regex comparison != in table select expression tree.
class TableExprNodeNEDate
Date comparison != in table select expression tree.
class TableExprNodeGTInt
Int comparison > in table select expression tree.
class TableExprNodeGTDouble
Double comparison > in table select expression tree.
class TableExprNodeGTDComplex
DComplex comparison > in table select expression tree.
class TableExprNodeGTString
String comparison > in table select expression tree.
class TableExprNodeGTDate
Date comparison > in table select expression tree.
class TableExprNodeGEInt
Int comparison >= in table select expression tree.
class TableExprNodeGEDouble
Double comparison >= in table select expression tree.
class TableExprNodeGEDComplex
DComplex comparison >= in table select expression tree.
class TableExprNodeGEString
String comparison >= in table select expression tree.
class TableExprNodeGEDate
Date comparison >= in table select expression tree.
class TableExprNodeINInt
Int comparison IN in table select expression tree.
class TableExprNodeINDouble
Double comparison IN in table select expression tree.
class TableExprNodeINDComplex
DComplex comparison IN in table select expression tree.
class TableExprNodeINString
String comparison IN in table select expression tree.
class TableExprNodeINDate
Date comparison IN in table select expression tree.
class TableExprNodeOR
Logical or in table select expression tree.
class TableExprNodeAND
Logical and in table select expression tree.
class TableExprNodeNOT
Logical not in table select expression tree.
class TableExprNodeArrayEQBool
Bool Array comparison == in table select expression tree.
class TableExprNodeArrayEQInt
Int Array comparison == in table select expression tree.
class TableExprNodeArrayEQDouble
Double Array comparison == in table select expression tree.
class TableExprNodeArrayEQDComplex
DComplex Array comparison == in table select expression tree.
class TableExprNodeArrayEQString
String Array comparison == in table select expression tree.
class TableExprNodeArrayEQRegex
Regex Array comparison == in table select expression tree.
class TableExprNodeArrayEQDate
Date Array comparison == in table select expression tree.
class TableExprNodeArrayNEBool
Bool Array comparison != in table select expression tree.
class TableExprNodeArrayNEInt
Int Array comparison != in table select expression tree.
class TableExprNodeArrayNEDouble
Double Array comparison != in table select expression tree.
class TableExprNodeArrayNEDComplex
DComplex Array comparison != in table select expression tree.
class TableExprNodeArrayNEString
String Array comparison != in table select expression tree.
class TableExprNodeArrayNERegex
Regex Array comparison != in table select expression tree.
class TableExprNodeArrayNEDate
Date Array comparison != in table select expression tree.
class TableExprNodeArrayGTInt
Int Array comparison > in table select expression tree.
class TableExprNodeArrayGTDouble
Double Array comparison > in table select expression tree.
class TableExprNodeArrayGTDComplex
DComplex Array comparison > in table select expression tree.
class TableExprNodeArrayGTString
String Array comparison > in table select expression tree.
class TableExprNodeArrayGTDate
Date Array comparison > in table select expression tree.
class TableExprNodeArrayGEInt
Int Array comparison >= in table select expression tree.
class TableExprNodeArrayGEDouble
Double Array comparison >= in table select expression tree.
class TableExprNodeArrayGEDComplex
DComplex Array comparison >= in table select expression tree.
class TableExprNodeArrayGEString
String Array comparison >= in table select expression tree.
class TableExprNodeArrayGEDate
Date Array comparison >= in table select expression tree.
class TableExprNodeArrayINInt
Int Array comparison IN in table select expression tree.
class TableExprNodeArrayINDouble
Double Array comparison IN in table select expression tree.
class TableExprNodeArrayINDComplex
DComplex Array comparison IN in table select expression tree.
class TableExprNodeArrayINString
String Array comparison IN in table select expression tree.
class TableExprNodeArrayINDate
Date Array comparison IN in table select expression tree.
class TableExprNodeArrayOR
Logical or in table select expression tree.
class TableExprNodeArrayAND
Logical and in table select expression tree.
class TableExprNodeArrayNOT
Logical not in table select expression tree.
class TableExprNodePlus
Addition in table select expression tree.
class TableExprNodePlusInt
Int addition in table select expression tree.
class TableExprNodePlusDouble
Double addition in table select expression tree.
class TableExprNodePlusDComplex
DComplex addition in table select expression tree.
class TableExprNodePlusString
String addition in table select expression tree.
class TableExprNodePlusDate
Date addition in table select expression tree.
class TableExprNodeMinus
Subtraction in table select expression tree.
class TableExprNodeMinusInt
Int subtraction in table select expression tree.
class TableExprNodeMinusDouble
Double subtraction in table select expression tree.
class TableExprNodeMinusDComplex
DComplex subtraction in table select expression tree.
class TableExprNodeMinusDate
Date subtraction in table select expression tree.
class TableExprNodeTimes
Multiplication in table select expression tree.
class TableExprNodeTimesInt
Int multiplication in table select expression tree.
class TableExprNodeTimesDouble
Double multiplication in table select expression tree.
class TableExprNodeTimesDComplex
DComplex multiplication in table select expression tree.
class TableExprNodeDivide
Division in table select expression tree.
class TableExprNodeDivideDouble
Double division in table select expression tree.
class TableExprNodeDivideDComplex
DComplex division in table select expression tree.
class TableExprNodeModulo
Modulo in table select expression tree.
class TableExprNodeModuloInt
Int modulo in table select expression tree.
class TableExprNodeModuloDouble
Double modulo in table select expression tree.
class TableExprNodeBitAndInt
Bitwise and in table select expression tree.
class TableExprNodeBitOrInt
Bitwise or in table select expression tree.
class TableExprNodeBitXorInt
Bitwise xor in table select expression tree.
class TableExprNodeMIN
Unary minus in table select expression tree.
class TableExprNodeBitNegate
Bitwise negate in table select expression tree.
class TableExprNodeArrayPlus
Array addition in table select expression tree.
class TableExprNodeArrayPlusInt
Int Array addition in table select expression tree.
class TableExprNodeArrayPlusDouble
Double Array addition in table select expression tree.
class TableExprNodeArrayPlusDComplex
DComplex Array addition in table select expression tree.
class TableExprNodeArrayPlusString
String Array addition in table select expression tree.
class TableExprNodeArrayPlusDate
Date Array addition in table select expression tree.
class TableExprNodeArrayMinus
Array addition in table select expression tree.
class TableExprNodeArrayMinusInt
Int Array subtraction in table select expression tree.
class TableExprNodeArrayMinusDouble
Double Array subtraction in table select expression tree.
class TableExprNodeArrayMinusDComplex
DComplex Array subtraction in table select expression tree.
class TableExprNodeArrayMinusDate
Date Array subtraction in table select expression tree.
class TableExprNodeArrayTimes
Array addition in table select expression tree.
class TableExprNodeArrayTimesInt
Int Array multiplication in table select expression tree.
class TableExprNodeArrayTimesDouble
Double Array multiplication in table select expression tree.
class TableExprNodeArrayTimesDComplex
DComplex Array multiplication in table select expression tree.
class TableExprNodeArrayDivide
Array addition in table select expression tree.
class TableExprNodeArrayDivideDouble
Double Array division in table select expression tree.
class TableExprNodeArrayDivideDComplex
DComplex Array division in table select expression tree.
class TableExprNodeArrayModulo
Array addition in table select expression tree.
class TableExprNodeArrayModuloInt
Int Array modulo in table select expression tree.
class TableExprNodeArrayModuloDouble
Double Array modulo in table select expression tree.
class TableExprNodeArrayBitAndInt
Int Array bitwise and in table select expression tree.
class TableExprNodeArrayBitOrInt
Int Array bitwise or in table select expression tree.
class TableExprNodeArrayBitXorInt
Int Array bitwise xor in table select expression tree.
class TableExprNodeArrayMIN
Unary minus in table select expression tree.
class TableExprNodeArrayBitNegate
Bitwise negate in table select expression tree.
class MArray
Class to handle an Array with an optional mask.
class TableExprNode
Handle class for a table column expression tree.
class TableExprNodeArray
Base class for arrays in table select expression.
class TableExprNodeArrayColumn
Base class for Array column in table select expression.
class TableExprNodeArrayColumnBool
Bool array column in table select expression.
class TableExprNodeArrayColumnuChar
uChar array column in table select expression
class TableExprNodeArrayColumnShort
Short array column in table select expression.
class TableExprNodeArrayColumnuShort
uShort array column in table select expression
class TableExprNodeArrayColumnInt
Int array column in table select expression.
class TableExprNodeArrayColumnuInt
uInt array column in table select expression
class TableExprNodeArrayColumnFloat
Float array column in table select expression.
class TableExprNodeArrayColumnDouble
Double array column in table select expression.
class TableExprNodeArrayColumnComplex
Complex array column in table select expression.
class TableExprNodeArrayColumnDComplex
DComplex array column in table select expression.
class TableExprNodeArrayColumnString
String array column in table select expression.
class TableExprNodeIndex
The index of an array element in a table select expression.
class TableExprNodeArrayPart
Array column part in table select expression.
class TableExprNodeRecordField
Scalar field in record select expression tree.
class TableExprNodeRecordFieldArray
Array field in record select expression tree.
class TaqlRegex
Class to handle a Regex or StringDistance.
class TableExprNodeRep
Abstract base class for a node in a table column expression tree.
class TableExprNodeBinary
Abstract base class for a node having 0, 1, or 2 child nodes.
class TableExprNodeMulti
Abstract base class for a node having multiple child nodes.
class TableExprNodeSetElem
Class to hold the table expression nodes for an element in a set.
class TableExprNodeSet
Class to hold multiple table expression nodes.
class TableExprRange
Select range of a column in an select expression.
class TableExprUDFNode
Class representing a scalar UDF in select expression.
class TableExprUDFNodeArray
Class representing an array UDF in select expression.
class TableExprNodeUnit
Unit for scalar values in a table select expression tree.
class TableExprNodeArrayUnit
Unit for array values in a table select expression tree.
class MArrayBase
Base class for an array with an optional mask.
struct MArrayLogical_global_functions_MArray_logical_operations
Logical operations for MArray objects.
struct MArrayMath_global_functions_MArray_mathematical_operations
Mathematical operations for MArray objects.
struct MArrayMathBase_global_functions_Array_basic_functions
Basic functions and classes for math on MArray objects.
struct MArrayUtil_global_functions_reorderMArray
Reorder the axes of the data in an MArray object.
struct RecordExpr_global_functions_RecordExpr
Global functions to make a expression node for a record field.
struct RecordGram_global_functions_RecordGramFunctions
Global functions for flex/bison scanner/parser for RecordGram.
class RecordGramVal
Helper class for values in RecordGram.
class RecordGram
Select-class for flex/bison scanner/parser for RecordGram.
class TableExprData
Abstract base class for data object in a TaQL expression.
class TableExprId
The identification of a TaQL selection subject.
class TableExprIdAggr
The Table Expression Selection id used with aggregation.
struct TableGram_global_functions_TableGramFunctions
Global functions for flex/bison scanner/parser for TableGram.
class TableParse
Class to hold values from table grammar parser.
class TableParseSort
Helper class for sort keys in TableParse.
class TableParseUpdate
Helper class for updates in TableParse.
class TableParseSelect
Select-class for flex/bison scanner/parser for TableParse.
class TaQLNode
Envelope class for a node in the raw TaQL parse tree.
class TaQLConstNode
Envelope class for a node containing a constant value.
class TaQLRegexNode
Envelope class for a node containing a constant regex value.
class TaQLMultiNode
Envelope class for a node containing a list of nodes.
class TaQLQueryNode
Envelope class for a node containing a selection command.
class TaQLConstNodeRep
Raw TaQL parse tree node defining a constant value.
class TaQLRegexNodeRep
Raw TaQL parse tree node defining a constant regex value.
class TaQLUnaryNodeRep
Raw TaQL parse tree node defining a unary operator.
class TaQLBinaryNodeRep
Raw TaQL parse tree node defining a binary operator.
class TaQLMultiNodeRep
Raw TaQL parse tree node defining a list of nodes.
class TaQLFuncNodeRep
Raw TaQL parse tree node defining a function.
class TaQLRangeNodeRep
Raw TaQL parse tree node defining a range.
class TaQLIndexNodeRep
Raw TaQL parse tree node defining an index in a array.
class TaQLJoinNodeRep
Raw TaQL parse tree node defining a join operation.
class TaQLKeyColNodeRep
Raw TaQL parse tree node defining a keyword or column name.
class TaQLTableNodeRep
Raw TaQL parse tree node defining a table.
class TaQLColNodeRep
Raw TaQL parse tree node defining a select column expression.
class TaQLColumnsNodeRep
Raw TaQL parse tree node defining a select column list.
class TaQLGroupNodeRep
Raw TaQL parse tree node defining a groupby list.
class TaQLSortKeyNodeRep
Raw TaQL parse tree node defining a sort key.
class TaQLSortNodeRep
Raw TaQL parse tree node defining a sort list.
class TaQLLimitOffNodeRep
Raw TaQL parse tree node defining a limit/offset expression.
class TaQLGivingNodeRep
Raw TaQL parse tree node defining a giving expression list.
class TaQLUpdExprNodeRep
Raw TaQL parse tree node defining a column update expression.
class TaQLQueryNodeRep
Raw TaQL parse tree node defining a selection command.
class TaQLSelectNodeRep
Raw TaQL parse tree node defining a select command.
class TaQLCountNodeRep
Raw TaQL parse tree node defining a count command.
class TaQLUpdateNodeRep
Raw TaQL parse tree node defining an update command.
class TaQLInsertNodeRep
Raw TaQL parse tree node defining an insert command.
class TaQLDeleteNodeRep
Raw TaQL parse tree node defining a delete command.
class TaQLCalcNodeRep
Raw TaQL parse tree node defining a calc command.
class TaQLCreTabNodeRep
Raw TaQL parse tree node defining a create table command.
class TaQLColSpecNodeRep
Raw TaQL parse tree node defining a create column specification.
class TaQLRecFldNodeRep
Raw TaQL parse tree node defining a record field.
class TaQLUnitNodeRep
Raw TaQL parse tree node defining a unit.
class TaQLAltTabNodeRep
Raw TaQL parse tree node defining an alter table command.
class TaQLAddColNodeRep
Raw TaQL parse tree node defining an alter table add column command.
class TaQLRenDropNodeRep
Raw TaQL parse tree node defining an alter table rename or drop command.
class TaQLSetKeyNodeRep
Raw TaQL parse tree node defining an alter table set keyword command.
class TaQLAddRowNodeRep
Raw TaQL parse tree node defining an alter table add rows command.
class TaQLConcTabNodeRep
Raw TaQL parse tree node defining an alter table command.
class TaQLShowNodeRep
Raw TaQL parse tree node defining a show command.
class TaQLNodeHandler
Class to handle the nodes in the raw TaQL parse tree.
class TaQLNodeHRValue
Class containing the result value of the handling of a TaQLNode.
class TaQLNodeRep
Representation of a node in the raw TaQL parse tree.
class TaQLNodeResultRep
Abstract base class to hold the result of a visit to the node tree.
class TaQLNodeResult
Envelope class to hold the result of a visit to the node tree.
class TaQLNodeVisitor
Class to visit the nodes in the raw TaQL parse tree.
class TaQLResult
Class to hold the result of a TaQL command.
class TaQLShow
Class to show various TaQL-related info.
class TaQLStyle
Class with static members defining the TaQL style.
class UDFBase
Abstract base class for a user-defined TaQL function.
Typedefs
typedef bool Bool
Define the standard types used by Casacore.
typedef char Char
typedef unsigned char uChar
typedef short Short
typedef unsigned short uShort
typedef int Int
typedef unsigned int uInt
typedef long Long
typedef unsigned long uLong
typedef float Float
typedef double Double
typedef long double lDouble
typedef long long Int64
Define the extra non-standard types used by Casacore (like proposed uSize, Size)
typedef unsigned long long uInt64
typedef int FitsLong
typedef Link< int > Link_int
typedef FilebufIO LargeFilebufIO
typedef FiledesIO LargeFiledesIO
typedef RegularFileIO LargeRegularFileIO
typedef Quantum< Double > Quantity
typedef QVector< Double > QVD
typedef AipsrcValue< Double > AipsrcDouble
typedef AipsrcValue< Int > AipsrcInt
typedef AipsrcValue< Bool > AipsrcBool
typedef Aipsrc AipsrcString
typedef AipsrcVector< Double > AipsrcVDouble
typedef AipsrcVector< Int > AipsrcVInt
typedef AipsrcVector< Bool > AipsrcVBool
typedef AipsrcVector< String > AipsrcVString
typedef void(* FITSErrorHandler)(const char *errMessage, FITSError::ErrorLevel severity)
Define a typedef for the handler function signature for convenience.
typedef PrimaryArray< unsigned
char > BytePrimaryArray
typedef PrimaryArray< short > ShortPrimaryArray
typedef PrimaryArray< FitsLong > LongPrimaryArray
typedef PrimaryArray< float > FloatPrimaryArray
typedef PrimaryArray< double > DoublePrimaryArray
typedef ImageExtension
< unsigned char > ByteImageExtension
typedef ImageExtension< short > ShortImageExtension
typedef ImageExtension< FitsLong > LongImageExtension
typedef ImageExtension< float > FloatImageExtension
typedef ImageExtension< double > DoubleImageExtension
typedef PrimaryGroup< unsigned
char > BytePrimaryGroup
typedef PrimaryGroup< short > ShortPrimaryGroup
typedef PrimaryGroup< FitsLong > LongPrimaryGroup
typedef PrimaryGroup< float > FloatPrimaryGroup
typedef PrimaryGroup< double > DoublePrimaryGroup
typedef PrimaryTable< unsigned
char > BytePrimaryTable
typedef PrimaryTable< short > ShortPrimaryTable
typedef PrimaryTable< FitsLong > LongPrimaryTable
typedef PrimaryTable< float > FloatPrimaryTable
typedef PrimaryTable< double > DoublePrimaryTable
typedef FitsField< FitsLogical > LogicalFitsField
typedef FitsField< FitsBit > BitFitsField
typedef FitsField< char > CharFitsField
typedef FitsField< unsigned char > ByteFitsField
typedef FitsField< short > ShortFitsField
typedef FitsField< FitsLong > LongFitsField
typedef FitsField< float > FloatFitsField
typedef FitsField< double > DoubleFitsField
typedef FitsField< Complex > ComplexFitsField
typedef FitsField< IComplex > IComplexFitsField
typedef FitsField< DComplex > DComplexFitsField
typedef FitsField< FitsVADesc > VADescFitsField
typedef FitsArray< FitsLogical > LogicalFitsArray
typedef FitsArray< FitsBit > BitFitsArray
typedef FitsArray< char > CharFitsArray
typedef FitsArray< unsigned char > ByteFitsArray
typedef FitsArray< short > ShortFitsArray
typedef FitsArray< FitsLong > LongFitsArray
typedef FitsArray< float > FloatFitsArray
typedef FitsArray< double > DoubleFitsArray
typedef FitsArray< Complex > ComplexFitsArray
typedef FitsArray< IComplex > IComplexFitsArray
typedef FitsArray< DComplex > DComplexFitsArray
typedef FitsArray< FitsVADesc > VADescFitsArray
typedef MeasurementSet MS
MeasurementSet is too cumbersome for a number of common uses, so we give a typedef here.
typedef MSSelectionKeywords MSS
Define a shorthand notation for this class, so enums can be specified easily.
typedef struct casacore::TimeFields TimeFields
typedef Convolver< Float > FloatConvolver
Typedefs.
typedef Convolver< Double > DoubleConvolver
typedef Float FType
typedef std::pair< Int64, Int64 > LocationType
typedef TableColumn ROTableColumn
Define ROTableColumn for backward compatibility.
Enumerations
enum StorageInitPolicy {
COPY,
TAKE_OVER,
SHARE
}
A global enum used by some Array constructors.
enum { ConstListIterVersion }
enum outside class because of compiler errors on HPUX
Functions
void fillBoxedShape (const IPosition &shape, const IPosition &boxShape, IPosition &fullBoxShape, IPosition &resultShape)
Helper functions for boxed and sliding functions.
Bool fillSlidingShape (const IPosition &shape, const IPosition &halfBoxSize, IPosition &boxEnd, IPosition &resultShape)
Determine the box end and shape of result for a sliding operation.
template<typename T , typename FuncType >
MaskedArray< T > boxedArrayMath (const MaskedArray< T > &array, const IPosition &boxSize, const FuncType &funcObj)
Apply the given ArrayMath reduction function objects to each box in the array.
template<typename T , typename FuncType >
Array< T > slidingArrayMath (const MaskedArray< T > &array, const IPosition &halfBoxSize, const FuncType &funcObj, Bool fillEdge=True)
Apply for each element in the array the given ArrayMath reduction function object to the box around that element.
template<typename InputIterator1 , typename InputIterator2 , typename BinaryOperator >
void transformInPlace (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, BinaryOperator op)
Define a function to do a binary transform in place.
template<typename InputIterator1 , typename UnaryOperator >
void transformInPlace (InputIterator1 first1, InputIterator1 last1, UnaryOperator op)
Define a function to do a unary transform in place.
template<typename InputIterator , typename MaskIterator , typename Accum , typename BinaryOperator >
Accum accumulateTrue (InputIterator first, InputIterator last, MaskIterator mask, Accum acc, BinaryOperator op=std::plus< Accum >())
Define a function (similar to std::accumulate) to do accumulation of elements for which the corresponding mask value is true.
template<typename InputIterator , typename MaskIterator , typename Accum , typename BinaryOperator >
Accum accumulateFalse (InputIterator first, InputIterator last, MaskIterator mask, Accum acc, BinaryOperator op=std::plus< Accum >())
Define a function (similar to std::accumulate) to do accumulation of elements for which the corresponding mask value is false.
template<typename InputIterator1 , typename InputIterator2 , typename CompareOperator >
bool compareAll (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, CompareOperator op)
Define a function to compare all elements of two sequences.
template<typename InputIterator1 , typename T , typename CompareOperator >
bool compareAllLeft (InputIterator1 first1, InputIterator1 last1, T left, CompareOperator op)
For use with a constant left value.
template<typename InputIterator1 , typename T , typename CompareOperator >
bool compareAllRight (InputIterator1 first1, InputIterator1 last1, T right, CompareOperator op)
For use with a constant right value.
template<typename InputIterator1 , typename InputIterator2 , typename CompareOperator >
bool compareAny (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, CompareOperator op)
Define a function to compare all elements of two sequences.
template<typename InputIterator1 , typename T , typename CompareOperator >
bool compareAnyLeft (InputIterator1 first1, InputIterator1 last1, T left, CompareOperator op)
For use with a constant left value.
template<typename InputIterator1 , typename T , typename CompareOperator >
bool compareAnyRight (InputIterator1 first1, InputIterator1 last1, T right, CompareOperator op)
For use with a constant right value.
template<typename C1 , typename C2 , typename CompareOperator >
bool compareAll (const C1 &l, const C2 &r, CompareOperator op)
Arbitrary compare operation on two STL-style containers.
template<typename C1 , typename C2 , typename U >
bool allNear (const C1 &l, const C2 &r, U tolerance)
Test if all elements of the containers are relatively near each other.
template<typename C1 , typename C2 , typename U >
bool allNearAbs (const C1 &l, const C2 &r, U tolerance)
Test if all elements of the containers are absolutely near each other.
ostream & operator<< (ostream &os, const IComplex &)
Show on ostream.
ostream & operator<< (ostream &s, const String &x)
template<typename T >
bool operator== (const std11_allocator< T > &, const std11_allocator< T > &)
template<typename T >
bool operator!= (const std11_allocator< T > &, const std11_allocator< T > &)
template<typename T , size_t ALIGNMENT>
bool operator== (const casacore_allocator< T, ALIGNMENT > &, const casacore_allocator< T, ALIGNMENT > &)
template<typename T , size_t ALIGNMENT>
bool operator!= (const casacore_allocator< T, ALIGNMENT > &, const casacore_allocator< T, ALIGNMENT > &)
template<typename T >
bool operator== (const new_del_allocator< T > &, const new_del_allocator< T > &)
template<typename T >
bool operator!= (const new_del_allocator< T > &, const new_del_allocator< T > &)
CASA_TMP_939727 (void)
CASA_TMP_939727 (bool)
CASA_TMP_939727 (wchar_t)
CASA_TMP_939727 (signed char)
CASA_TMP_939727 (unsigned char)
CASA_TMP_939727 (float)
CASA_TMP_939727 (double)
CASA_TMP_939727 (long double)
CASA_TMP_939727_int (int)
CASA_TMP_939727_int (long int)
CASA_TMP_939727_int (long long int)
void putBlock (AipsIO &, const Block< void * > &, Int)
void getBlock (AipsIO &, Block< void * > &)
void showBlock (AipsIO &, const Block< void * > &, Int)
void throw_invalid_hashmapiter_error ()
void throw_hashmapiter_init_error ()
void throw_list_end_error ()
The function which throws an exception for advancing the internal cursor past the end of a list.
void throw_list_init_error ()
void throw_list_start_error ()
void throw_list_swapright_same_error ()
void throw_mapiter_init_error ()
void throw_map_init_error ()
void throw_invalid_mapiter_error ()
void throw_map_constop_error ()
AipsIO & operator<< (AipsIO &os, const Record &rec)
AipsIO & operator>> (AipsIO &os, Record &rec)
ostream & operator<< (ostream &os, const RecordDesc &desc)
AipsIO & operator<< (AipsIO &os, const RecordDesc &desc)
AipsIO & operator>> (AipsIO &os, RecordDesc &desc)
void defineRecordFieldPtr (RecordInterface *parent, Int fieldNumber, DataType type, const void *value)
void defineRecordFieldPtr (RecordInterface *parent, Int fieldNumber, DataType, const TableRecord *value)
void * attachRecordFieldPtr (RecordInterface *parent, Int fieldNumber, DataType type, const void *)
This function attaches a RecordFieldPtr object.
void * attachRecordFieldPtr (RecordInterface *parent, Int fieldNumber, DataType, const Table *)
Specialization for a Table field (which cannot be used).
void * attachRecordFieldPtr (RecordInterface *parent, Int fieldNumber, DataType, const Record *)
Specialization for a Record field.
void * attachRecordFieldPtr (RecordInterface *parent, Int fieldNumber, DataType, const TableRecord *)
Specialization for a TableRecord field.
void throw_empty_Stack_error (const char *msg=0)
void throwInvHDF5 ()
Define 2 functions to check that hid_t and hsize_t are mapped correctly.
void check_hid_t (int)
template<typename T >
void check_hid_t (T)
void check_hsize_t (unsigned long long)
template<typename T >
void check_hsize_t (T)
void operator<< (ostream &, const MultiFileInfo &)
void operator<< (AipsIO &, const MultiFileInfo &)
void operator>> (AipsIO &, MultiFileInfo &)
Float pow (Float f1, Float f2)
MVBaseline operator* (const RotMatrix &left, const MVBaseline &right)
Rotate a Baseline vector with rotation matrix and other multiplications.
MVBaseline operator* (const MVBaseline &left, const RotMatrix &right)
MVBaseline operator* (Double left, const MVBaseline &right)
MVBaseline operator* (const MVBaseline &left, Double right)
Double operator* (const Vector< Double > &left, const MVBaseline &right)
Double operator* (const MVBaseline &left, const Vector< Double > &right)
Double operator* (const MVPosition &left, const MVBaseline &right)
Double operator* (const MVBaseline &left, const MVPosition &right)
MVDirection operator* (const RotMatrix &left, const MVDirection &right)
Rotate a position vector.
MVDirection operator* (const MVDirection &left, const RotMatrix &right)
MVEarthMagnetic operator* (const RotMatrix &left, const MVEarthMagnetic &right)
Rotate a EarthMagnetic vector with rotation matrix and other multiplications.
MVEarthMagnetic operator* (const MVEarthMagnetic &left, const RotMatrix &right)
MVEarthMagnetic operator* (Double left, const MVEarthMagnetic &right)
MVEarthMagnetic operator* (const MVEarthMagnetic &left, Double right)
Double operator* (const Vector< Double > &left, const MVEarthMagnetic &right)
Double operator* (const MVEarthMagnetic &left, const Vector< Double > &right)
Double operator* (const MVPosition &left, const MVEarthMagnetic &right)
Double operator* (const MVEarthMagnetic &left, const MVPosition &right)
MVPosition operator* (const RotMatrix &left, const MVPosition &right)
Rotate a position vector with rotation matrix and other multiplications.
MVPosition operator* (const MVPosition &left, const RotMatrix &right)
MVPosition operator* (Double left, const MVPosition &right)
MVPosition operator* (const MVPosition &left, Double right)
Double operator* (const Vector< Double > &left, const MVPosition &right)
Double operator* (const MVPosition &left, const Vector< Double > &right)
ostream & operator<< (ostream &os, const MVTime &meas)
Global functions.
ostream & operator>> (ostream &is, MVTime &meas)
ostream & operator<< (ostream &os, const MVTime::Format &form)
Set a temporary format (thread-unsafe).
Bool operator== (const MVTime &lh, const MVTime &rh)
is equal operator, uses operator Double which returns days
MVuvw operator* (const RotMatrix &left, const MVuvw &right)
Rotate a uvw vector with rotation matrix and other multiplications.
MVuvw operator* (const MVuvw &left, const RotMatrix &right)
MVuvw operator* (Double left, const MVuvw &right)
MVuvw operator* (const MVuvw &left, Double right)
Double operator* (const Vector< Double > &left, const MVuvw &right)
Double operator* (const MVuvw &left, const Vector< Double > &right)
Double operator* (const MVPosition &left, const MVuvw &right)
Double operator* (const MVuvw &left, const MVPosition &right)
ostream & operator<< (ostream &os, const UnitDim &du)
Output.
uInt hashFunc (const ObjectID &)
ostream & operator<< (ostream &os, const ObjectID &id)
Bool countedPtrShared ()
A shared_ptr is used as implementation.
template<typename T , typename U >
CountedPtr< T > static_pointer_cast (const CountedPtr< U > &that)
Cast the CountedPtr from one pointer type to another.
template<typename T , typename U >
CountedPtr< T > const_pointer_cast (const CountedPtr< U > &that)
template<typename T , typename U >
CountedPtr< T > dynamic_pointer_cast (const CountedPtr< U > &that)
const char * a2_re_compile_pattern ()
void a2_re_compile_fastmap ()
int a2_re_search ()
int a2_re_search_2 ()
int a2_re_match ()
int a2_re_match_2 ()
const char * re_comp ()
int re_exec ()
uInt precisionForValueErrorPairs (const Vector< Double > &pair1, const Vector< Double > &pair2)
Various precision-related functions.
T * operator-> () const
Make it possible to use -> on the pointer object.
Bool isCArray () const
See if the pointer points to a C-array.
PtrHolder (const PtrHolder< T > &other)
PtrHolder< T > & operator= (const PtrHolder< T > &other)
void delete_pointer_if_necessary ()
const std::string getVersion ()
Get the casacore version.
const std::string getVersionCASA ()
Get the version of casacore on CASA's vendor branch Note: CASA's private version of casacore has a lifecycle which is not necessarily identical to versions of casacore elsewhere.
ostream & operator<< (ostream &os, const SpectralCoordinate &spcoord)
void addRecordDesc (TableDesc &tableDescription, const RecordDesc &recordDescription, const String &prefix)
This function probably doesn't belong here, but I'm not yet sure where it does belong.
ostream & operator<< (ostream &, const FITS::ValueType &)
ostream & operator<< (ostream &, const FitsKeyword &)
ostream & operator<< (ostream &o, FitsKeywordList &)
std::ostream & operator<< (std::ostream &o, HeaderDataUnit &h)
std::ostream & operator<< (std::ostream &o, FitsBase &x)
Bool canUseHDF5Image ()
Tell if HDF5 images can be used.
DataType hdf5imagePixelType (const String &fileName)
Determine the pixel type in the HDF5Image contained in fileName.
Bool isHDF5Image (const String &fileName)
Check if this HDF5 file is an HDF5 image.
ostream & operator<< (ostream &os, const ImageBeamSet &beamSet)
DataType imagePixelType (const String &fileName)
Determine the pixel type in the PagedImage contained in fileName.
MrsEligibility operator- (const MrsEligibility &a, MrsEligibility::SubtableId subtableId)
Creates a new MrsEligibilitySet by adding or removing the specified subtable or the specified set of subtables.
MrsEligibility operator+ (const MrsEligibility &a, MrsEligibility::SubtableId subtableId)
MrsEligibility operator- (const MrsEligibility &a, const MrsEligibility &b)
MrsEligibility operator+ (const MrsEligibility &a, const MrsEligibility &b)
template<class T >
Bool areEQ (const ROScalarColumn< T > &col, uInt row_i, uInt row_j)
template<class T >
Bool areEQ (const ROArrayColumn< T > &col, uInt row_i, uInt row_j)
Bool operator< (const SubScanKey &lhs, const SubScanKey &rhs)
define operator<() so it can be used as a key in std::map
String toString (const SubScanKey &subScanKey)
std::ostream & operator<< (std::ostream &os, const SubScanKey &scanKey)
ScanKey scanKey (const SubScanKey &subScanKey)
create a ScanKey from a SubScanKey, just omits the SubScanKey's fieldID
String toString (const ScanKey &scanKey)
Bool operator< (const ScanKey &lhs, const ScanKey &rhs)
define operator<() so it can be used as a key in std::map
Bool operator== (const ScanKey &lhs, const ScanKey &rhs)
std::set< Int > scanNumbers (const std::set< ScanKey > &scanKeys)
extract all the unique scan numbers from the specified scans
std::ostream & operator<< (std::ostream &os, const ScanKey &scanKey)
Bool operator< (const ArrayKey &lhs, const ArrayKey &rhs)
define operator<() so it can be used as a key in std::map
Bool operator== (const ArrayKey &lhs, const ArrayKey &rhs)
Bool operator!= (const ArrayKey &lhs, const ArrayKey &rhs)
std::set< ScanKey > scanKeys (const std::set< Int > &scans, const ArrayKey &arrayKey)
construct scan keys given a set of scan numbers and an ArrayKey
Bool operator< (const SourceKey &lhs, const SourceKey &rhs)
define operator<() so it can be used as a key in std::map
std::set< ArrayKey > uniqueArrayKeys (const std::set< ScanKey > &scanKeys)
get a set of unique ArrayKeys from a set of ScanKeys
std::set< ScanKey > filter (const std::set< ScanKey > scans, const ArrayKey &arrayKey)
given a set of scan keys, return the subset that matches the given array key
String constructMessage (const Int pos, const String &command)
Vector< Int > set_intersection (const Vector< Int > &v1, const Vector< Int > &v2)
Vector< Int > set_union (const Vector< Int > &v1, const Vector< Int > &v2)
Bool mssSetData (const MeasurementSet &ms, MeasurementSet &selectedMS, const String &outMSName="", const String &timeExpr="", const String &antennaExpr="", const String &fieldExpr="", const String &spwExpr="", const String &uvDistExpr="", const String &taQLExpr="", const String &polnExpr="", const String &scanExpr="", const String &arrayExpr="", const String &stateExpr="", const String &obsExpr="", MSSelection *mss=NULL)
Collective selection returning a selected MS.
Bool mssSetData2 (const MeasurementSet &ms, MeasurementSet &selectedMS, const String &outMSName="", const String &timeExpr="", const String &antennaExpr="", const String &fieldExpr="", const String &spwExpr="", const String &uvDistExpr="", const String &taQLExpr="", const String &polnExpr="", const String &scanExpr="", const String &arrayExpr="", const String &stateExpr="", const String &obsExpr="", const String &feedExpr="", MSSelection *mss=NULL)
Added feedExpr.
Bool mssSetData (const MeasurementSet &ms, MeasurementSet &selectedMS, Vector< Vector< Slice > > &chanSlices, Vector< Vector< Slice > > &corrSlices, const String &outMSName="", const String &timeExpr="", const String &antennaExpr="", const String &fieldExpr="", const String &spwExpr="", const String &uvDistExpr="", const String &taQLExpr="", const String &polnExpr="", const String &scanExpr="", const String &arrayExpr="", const String &stateExpr="", const String &obsExpr="", const Int defaultChanStep=1, MSSelection *mss=NULL)
Collective selection also returning in-row (corr/chan) slices.
Bool mssSetData2 (const MeasurementSet &ms, MeasurementSet &selectedMS, Vector< Vector< Slice > > &chanSlices, Vector< Vector< Slice > > &corrSlices, const String &outMSName="", const String &timeExpr="", const String &antennaExpr="", const String &fieldExpr="", const String &spwExpr="", const String &uvDistExpr="", const String &taQLExpr="", const String &polnExpr="", const String &scanExpr="", const String &arrayExpr="", const String &stateExpr="", const String &obsExpr="", const String &feedExpr="", const Int defaultChanStep=1, MSSelection *mss=NULL)
Added feedExpr.
Bool getSelectedTable (Table &selectedTab, const Table &baseTab, TableExprNode &fullTEN, const String &outName)
Record mssSelectedIndices (MSSelection &mss, const MeasurementSet *ms)
String stripWhite (const String &str, Bool onlyends=True)
int tokenize (const String &str, const String &sep, Vector< String > &tokens, Bool upCase=False)
Vector< String > & split (const String &s, char delim, Vector< String > &elems)
template<class T , class U >
ostream & operator<< (ostream &os, const Function< T, U > &fun)
template<class T >
ostream & operator<< (ostream &os, const FunctionOrder< T > &par)
template<class T >
ostream & operator<< (ostream &os, const FunctionParam< T > &par)
template<class V >
void getArrayVal (V &val, int type, const Record &gr, const String &name, uInt index=0)
template<class V >
void getArray (Array< V > &val, int type, const Record &gr, const String &name)
AccumType _getStatistic (StatisticsData::STATS stat)
StatsData< AccumType > _getStatistics ()
Bool _isInRange (const AccumType &datum) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, Int64 nr, uInt dataStride) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude) const
virtual void _minMax (CountedPtr< AccumType > &mymin, CountedPtr< AccumType > &mymax, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride) const
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride) const
populate an unsorted array with valid data.
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude) const
ranges
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride) const
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude) const
mask and ranges
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride) const
weights
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude) const
weights and ranges
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride) const
weights and mask
void _populateArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude) const
weights, mask, ranges
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
no weights, no mask, no ranges
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
ranges
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
mask and ranges
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
weights
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
weights and ranges
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
weights and mask
virtual void _populateArrays (vector< vector< AccumType > > &arys, uInt64 &currentCount, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > &includeLimits, uInt64 maxCount) const
weights, mask, ranges
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride, uInt maxElements) const
no weights, no mask, no ranges
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude, uInt maxElements) const
ranges
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, uInt maxElements) const
mask
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude, uInt maxElements) const
mask and ranges
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, uInt maxElements) const
weights
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude, uInt maxElements) const
weights and ranges
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, uInt maxElements) const
weights and mask
Bool _populateTestArray (vector< AccumType > &ary, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude, uInt maxElements) const
weights, mask, ranges
void _setRange (CountedPtr< std::pair< AccumType, AccumType > > r)
virtual void _setRange ()=0
derived classes need to implement how to set their respective range
void _unweightedStats (StatsData< AccumType > &stats, uInt64 &ngood, LocationType &location, const DataIterator &dataBegin, Int64 nr, uInt dataStride)
no weights, no mask, no ranges
void _unweightedStats (StatsData< AccumType > &stats, uInt64 &ngood, LocationType &location, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude)
no weights, no mask
void _unweightedStats (StatsData< AccumType > &stats, uInt64 &ngood, LocationType &location, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride)
void _unweightedStats (StatsData< AccumType > &stats, uInt64 &ngood, LocationType &location, const DataIterator &dataBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude)
void _weightedStats (StatsData< AccumType > &stats, LocationType &location, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride)
has weights, but no mask, no ranges
void _weightedStats (StatsData< AccumType > &stats, LocationType &location, const DataIterator &dataBegin, const WeightsIterator &weightsBegin, Int64 nr, uInt dataStride, const DataRanges &ranges, Bool isInclude)
void _weightedStats (StatsData< AccumType > &stats, LocationType &location, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride)
void _weightedStats (StatsData< AccumType > &stats, LocationType &location, const DataIterator &dataBegin, const WeightsIterator &weightBegin, Int64 nr, uInt dataStride, const MaskIterator &maskBegin, uInt maskStride, const DataRanges &ranges, Bool isInclude)
ostream & operator<< (ostream &os, const GaussianBeam &beam)
LogIO & operator<< (LogIO &os, const GaussianBeam &beam)
Bool near (const GaussianBeam &left, const GaussianBeam &other, const Double relWidthTol, const Quantity &absPaTol)
template<class T >
void CholeskyDecomp (Matrix< T > &A, Vector< T > &diag)
template<class T >
void CholeskySolve (Matrix< T > &A, Vector< T > &diag, Vector< T > &b, Vector< T > &x)
void sgetrf (const int *m, const int *n, float *a, const int *lda, int *ipiv, int *info)
void dgetrf (const int *m, const int *n, double *a, const int *lda, int *ipiv, int *info)
void cgetrf (const int *m, const int *n, Complex *a, const int *lda, int *ipiv, int *info)
void zgetrf (const int *m, const int *n, DComplex *a, const int *lda, int *ipiv, int *info)
void sgetri (const int *m, float *a, const int *lda, const int *ipiv, float *work, const int *lwork, int *info)
void dgetri (const int *m, double *a, const int *lda, const int *ipiv, double *work, const int *lwork, int *info)
void cgetri (const int *m, Complex *a, const int *lda, const int *ipiv, Complex *work, const int *lwork, int *info)
void zgetri (const int *m, DComplex *a, const int *lda, const int *ipiv, DComplex *work, const int *lwork, int *info)
void sposv (const char *uplo, const int *n, const int *nrhs, float *a, const int *lda, float *b, const int *ldb, int *info)
void dposv (const char *uplo, const int *n, const int *nrhs, double *a, const int *lda, double *b, const int *ldb, int *info)
void cposv (const char *uplo, const int *n, const int *nrhs, Complex *a, const int *lda, Complex *b, const int *ldb, int *info)
void zposv (const char *uplo, const int *n, const int *nrhs, DComplex *a, const int *lda, DComplex *b, const int *ldb, int *info)
void spotri (const char *uplo, const int *n, float *a, const int *lda, int *info)
void dpotri (const char *uplo, const int *n, double *a, const int *lda, int *info)
void cpotri (const char *uplo, const int *n, Complex *a, const int *lda, int *info)
void zpotri (const char *uplo, const int *n, DComplex *a, const int *lda, int *info)
void getrf (const int *m, const int *n, float *a, const int *lda, int *ipiv, int *info)
void getrf (const int *m, const int *n, double *a, const int *lda, int *ipiv, int *info)
void getrf (const int *m, const int *n, Complex *a, const int *lda, int *ipiv, int *info)
void getrf (const int *m, const int *n, DComplex *a, const int *lda, int *ipiv, int *info)
void getri (const int *m, float *a, const int *lda, const int *ipiv, float *work, const int *lwork, int *info)
void getri (const int *m, double *a, const int *lda, const int *ipiv, double *work, const int *lwork, int *info)
void getri (const int *m, Complex *a, const int *lda, const int *ipiv, Complex *work, const int *lwork, int *info)
void getri (const int *m, DComplex *a, const int *lda, const int *ipiv, DComplex *work, const int *lwork, int *info)
void posv (const char *uplo, const int *n, const int *nrhs, float *a, const int *lda, float *b, const int *ldb, int *info)
void posv (const char *uplo, const int *n, const int *nrhs, double *a, const int *lda, double *b, const int *ldb, int *info)
void posv (const char *uplo, const int *n, const int *nrhs, Complex *a, const int *lda, Complex *b, const int *ldb, int *info)
void posv (const char *uplo, const int *n, const int *nrhs, DComplex *a, const int *lda, DComplex *b, const int *ldb, int *info)
void potri (const char *uplo, const int *n, float *a, const int *lda, int *info)
void potri (const char *uplo, const int *n, double *a, const int *lda, int *info)
void potri (const char *uplo, const int *n, Complex *a, const int *lda, int *info)
void potri (const char *uplo, const int *n, DComplex *a, const int *lda, int *info)
template<class AccumType >
StatsData< AccumType > initializeStatsData ()
template<class AccumType >
StatsData< AccumType > copy (const StatsData< AccumType > &stats)
template<class AccumType >
Record toRecord (const StatsData< AccumType > &stats)
template<class T >
ostream & operator<< (ostream &os, const typename StatisticsUtilities< T >::BinDesc &desc)
void setColumnCache (uInt tableNr, const ColumnCache &) const
Set the column cache to the cache of the given table.
template<class T >
Bool anyLE (const TableVector< T > &l, const TableVector< T > &r)
Element by element comparisons between the "l" and "r" table vectors.
template<class T >
Bool anyLT (const TableVector< T > &l, const TableVector< T > &r)
template<class T >
Bool anyGE (const TableVector< T > &l, const TableVector< T > &r)
template<class T >
Bool anyGT (const TableVector< T > &l, const TableVector< T > &r)
template<class T >
Bool anyEQ (const TableVector< T > &l, const TableVector< T > &r)
template<class T >
Bool anyNE (const TableVector< T > &l, const TableVector< T > &r)
template<class T >
Bool anyLE (const TableVector< T > &tv, const T &val)
Element by element comparisons between a table vector and a scalar, which behaves as if it were a conformant vector filled with the value "val." The result is true if the comparison is true for some element of the vector.
template<class T >
Bool anyLE (const T &val, const TableVector< T > &tv)
template<class T >
Bool anyLT (const TableVector< T > &tv, const T &val)
template<class T >
Bool anyLT (const T &val, const TableVector< T > &tv)
template<class T >
Bool anyGE (const TableVector< T > &tv, const T &val)
template<class T >
Bool anyGE (const T &val, const TableVector< T > &tv)
template<class T >
Bool anyGT (const TableVector< T > &tv, const T &val)
template<class T >
Bool anyGT (const T &val, const TableVector< T > &tv)
template<class T >
Bool anyEQ (const TableVector< T > &tv, const T &val)
template<class T >
Bool anyEQ (const T &val, const TableVector< T > &tv)
template<class T >
Bool anyNE (const TableVector< T > &tv, const T &val)
template<class T >
Bool anyNE (const T &val, const TableVector< T > &tv)
template<class T >
TableVector< T > pow (const TableVector< T > &tv, const double &exp)
template<class T >
T sum (const TableVector< T > &tv)
template<class T >
T product (const TableVector< T > &tv)
template<class T >
void minMax (T &min, T &max, const TableVector< T > &tv)
template<class T >
T min (const TableVector< T > &tv)
template<class T >
T max (const TableVector< T > &tv)
template<class T >
void indgen (TableVector< T > &tv, Int start, Int inc)
template<class T >
void indgen (TableVector< T > &tv, Int start)
template<class T >
void indgen (TableVector< T > &tv)
template<class T >
T innerProduct (const TableVector< T > &l, const TableVector< T > &r)
template<class T >
T norm (const TableVector< T > &tv)
template<class T >
TableVector< T > crossProduct (const TableVector< T > &l, const TableVector< T > &r)
size_t ArrayVolume (uInt Ndim, const Int *Shape)
General global functions for Arrays.
size_t ArrayIndexOffset (uInt Ndim, const ssize_t *Shape, const ssize_t *Origin, const ssize_t *Inc, const IPosition &Index)
What is the linear index into an "Ndim" dimensional array of the given "Shape", "Origin", and "Increment" for a given IPosition Index.
size_t ArrayIndexOffset (uInt Ndim, const ssize_t *Shape, const ssize_t *Inc, const IPosition &Index)
void throwArrayShapes (const IPosition &shape1, const IPosition &shape2, const char *name)
Function to check the shapes.
void checkArrayShapes (const ArrayBase &left, const ArrayBase &right, const char *name)
template<class T >
uInt genSort (T *data, uInt nr, Sort::Order order=Sort::Ascending, int options=0)
Global in-place sort functions The following global functions are easier to use than the static GenSort member functions.
template<class T >
uInt genSort (Array< T > &data, Sort::Order order=Sort::Ascending, int options=0)
template<class T >
uInt genSort (Block< T > &data, Sort::Order order=Sort::Ascending, int options=0)
template<class T >
uInt genSort (Block< T > &data, uInt nr, Sort::Order order=Sort::Ascending, int options=0)
template<class T >
uInt genSort (Vector< uInt > &indexVector, const T *data, uInt nr, Sort::Order order=Sort::Ascending, int options=0)
Global indirect sort functions The following global functions easier to use than the static GenSortIndirect member functions.
template<class T >
uInt genSort (Vector< uInt > &indexVector, const Array< T > &data, Sort::Order order=Sort::Ascending, int options=0)
template<class T >
uInt genSort (Vector< uInt > &indexVector, const Block< T > &data, Sort::Order order=Sort::Ascending, int options=0)
template<class T >
uInt genSort (Vector< uInt > &indexVector, const Block< T > &data, uInt nr, Sort::Order order=Sort::Ascending, int options=0)
ostream & operator<< (ostream &os, const ObsInfo &info)
Global functions.
LatticeExprNode operator+ (const LatticeExprNode &expr)
Global functions operating on a LatticeExprNode.
LatticeExprNode operator- (const LatticeExprNode &expr)
LatticeExprNode operator! (const LatticeExprNode &expr)
LatticeExprNode operator+ (const LatticeExprNode &left, const LatticeExprNode &right)
Numerical binary operators.
LatticeExprNode operator- (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator* (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator/ (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator% (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator^ (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator== (const LatticeExprNode &left, const LatticeExprNode &right)
Relational binary operators.
LatticeExprNode operator> (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator>= (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator< (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator<= (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator!= (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode operator&& (const LatticeExprNode &left, const LatticeExprNode &right)
Logical binary operators.
LatticeExprNode operator|| (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode sin (const LatticeExprNode &expr)
Numerical 1-argument functions.
LatticeExprNode sinh (const LatticeExprNode &expr)
LatticeExprNode asin (const LatticeExprNode &expr)
LatticeExprNode cos (const LatticeExprNode &expr)
LatticeExprNode cosh (const LatticeExprNode &expr)
LatticeExprNode acos (const LatticeExprNode &expr)
LatticeExprNode tan (const LatticeExprNode &expr)
LatticeExprNode tanh (const LatticeExprNode &expr)
LatticeExprNode atan (const LatticeExprNode &expr)
LatticeExprNode exp (const LatticeExprNode &expr)
LatticeExprNode log (const LatticeExprNode &expr)
LatticeExprNode log10 (const LatticeExprNode &expr)
LatticeExprNode sqrt (const LatticeExprNode &expr)
LatticeExprNode sign (const LatticeExprNode &expr)
LatticeExprNode round (const LatticeExprNode &expr)
LatticeExprNode ceil (const LatticeExprNode &expr)
LatticeExprNode floor (const LatticeExprNode &expr)
LatticeExprNode conj (const LatticeExprNode &expr)
LatticeExprNode atan2 (const LatticeExprNode &left, const LatticeExprNode &right)
Numerical 2-argument functions.
LatticeExprNode pow (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode fmod (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode min (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode max (const LatticeExprNode &left, const LatticeExprNode &right)
LatticeExprNode formComplex (const LatticeExprNode &left, const LatticeExprNode &right)
Form a complex number from two real numbers.
LatticeExprNode abs (const LatticeExprNode &expr)
Numerical 1-argument functions which result in a real number regardless of input expression type.
LatticeExprNode arg (const LatticeExprNode &expr)
LatticeExprNode real (const LatticeExprNode &expr)
LatticeExprNode imag (const LatticeExprNode &expr)
LatticeExprNode min (const LatticeExprNode &expr)
1-argument functions operating on a numeric expression resulting in a scalar
LatticeExprNode max (const LatticeExprNode &expr)
LatticeExprNode sum (const LatticeExprNode &expr)
LatticeExprNode median (const LatticeExprNode &expr)
LatticeExprNode mean (const LatticeExprNode &expr)
LatticeExprNode variance (const LatticeExprNode &expr)
LatticeExprNode stddev (const LatticeExprNode &expr)
LatticeExprNode avdev (const LatticeExprNode &expr)
LatticeExprNode fractile (const LatticeExprNode &expr, const LatticeExprNode &fraction)
Determine the value of the element at the part fraction from the beginning of the given lattice.
LatticeExprNode fractileRange (const LatticeExprNode &expr, const LatticeExprNode &fraction1, const LatticeExprNode &fraction2)
Determine the value range of the elements at the part fraction1 and fraction2 from the beginning of the given lattice.
LatticeExprNode fractileRange (const LatticeExprNode &expr, const LatticeExprNode &fraction)
LatticeExprNode nelements (const LatticeExprNode &expr)
1-argument function to get the number of elements in a lattice.
LatticeExprNode ndim (const LatticeExprNode &expr)
1-argument function to get the dimensionality of a lattice.
LatticeExprNode length (const LatticeExprNode &expr, const LatticeExprNode &axis)
2-argument function to get the length of an axis.
LatticeExprNode indexin (const LatticeExprNode &axis, const LatticeExprNode &indexFlags)
2-argument function telling per pixel if its index on the given axis is contained in the 2nd argument.
LatticeExprNode rebin (const LatticeExprNode &expr, const LatticeExprNode &bin)
2-argument function rebinning Lattice by given factors.
LatticeExprNode isNaN (const LatticeExprNode &expr)
Test if a value is a NaN.
LatticeExprNode any (const LatticeExprNode &expr)
Functions operating on a logical expression resulting in a scalar; Functions "any" (are any pixels "True") and "all" (are all pixels "True") result in a Bool; functions "ntrue" and "nfalse" result in a Double.
LatticeExprNode all (const LatticeExprNode &expr)
LatticeExprNode ntrue (const LatticeExprNode &expr)
LatticeExprNode nfalse (const LatticeExprNode &expr)
LatticeExprNode mask (const LatticeExprNode &expr)
This function returns the mask of the given expression.
LatticeExprNode value (const LatticeExprNode &expr)
This function returns the value of the expression without a mask.
LatticeExprNode amp (const LatticeExprNode &left, const LatticeExprNode &right)
This function finds sqrt(left^2+right^2).
LatticeExprNode pa (const LatticeExprNode &left, const LatticeExprNode &right)
This function finds 180/pi*atan2(left,right)/2.
LatticeExprNode spectralindex (const LatticeExprNode &left, const LatticeExprNode &right)
This function finds the spectral index alpha = log(s1/s2) / log(f1/f2).
LatticeExprNode iif (const LatticeExprNode &condition, const LatticeExprNode &arg1, const LatticeExprNode &arg2)
Function resembling the ternary ?: construct in C++.
LatticeExprNode replace (const LatticeExprNode &arg1, const LatticeExprNode &arg2)
This function replaces every masked-off element in the first argument with the corresponding element from the second argument.
LatticeExprNode toFloat (const LatticeExprNode &expr)
Functions to convert to the given data type.
LatticeExprNode toDouble (const LatticeExprNode &expr)
LatticeExprNode toComplex (const LatticeExprNode &expr)
LatticeExprNode toDComplex (const LatticeExprNode &expr)
LatticeExprNode toBool (const LatticeExprNode &expr)
LatticeExprNode convertType (const LatticeExprNode &expr, const Float *)
LatticeExprNode convertType (const LatticeExprNode &expr, const Double *)
LatticeExprNode convertType (const LatticeExprNode &expr, const Complex *)
LatticeExprNode convertType (const LatticeExprNode &expr, const DComplex *)
LatticeExprNode convertType (const LatticeExprNode &expr, const Bool *)
TableExprNode operator+ (const TableExprNode &left, const TableExprNode &right)
Define all global functions operating on a TableExprNode.
TableExprNode operator- (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator* (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator/ (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator% (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator& (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator| (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator^ (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator== (const TableExprNode &left, const TableExprNode &right)
Comparison operators.
TableExprNode operator!= (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator>= (const TableExprNode &left, const TableExprNode &right)
Not defined for Bool.
TableExprNode operator> (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator<= (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator< (const TableExprNode &left, const TableExprNode &right)
TableExprNode operator&& (const TableExprNode &left, const TableExprNode &right)
Logical operators to combine boolean TableExprNode's.
TableExprNode operator|| (const TableExprNode &left, const TableExprNode &right)
TableExprNode near (const TableExprNode &left, const TableExprNode &right)
Functions to return whether a value is "relatively" near another.
TableExprNode near (const TableExprNode &left, const TableExprNode &right, const TableExprNode &tolerance)
TableExprNode nearAbs (const TableExprNode &left, const TableExprNode &right)
TableExprNode nearAbs (const TableExprNode &left, const TableExprNode &right, const TableExprNode &tolerance)
TableExprNode angdist (const TableExprNode &pos1, const TableExprNode &pos2)
Angular distance between positions.
TableExprNode angdistx (const TableExprNode &pos1, const TableExprNode &pos2)
Angular distance as above, but only pair-wise enties are used if both arguments are arrays.
TableExprNode cones (const TableExprNode &sourcePos, const TableExprNode &cones)
Cone search; test if the position of a source is inside a cone.
TableExprNode anyCone (const TableExprNode &sourcePos, const TableExprNode &cones)
The result is always a Bool scalar telling if any cone contains the source.
TableExprNode findCone (const TableExprNode &sourcePos, const TableExprNode &cones)
The sourcePos can contain multiple sources.
TableExprNode cones (const TableExprNode &sourcePos, const TableExprNode &conePos, const TableExprNode &radii)
Cone search as above.
TableExprNode anyCone (const TableExprNode &sourcePos, const TableExprNode &conePos, const TableExprNode &radii)
TableExprNode findCone (const TableExprNode &sourcePos, const TableExprNode &conePos, const TableExprNode &radii)
TableExprNode sin (const TableExprNode &node)
Transcendental functions that can be applied to essentially all numeric nodes containing scalars or arrays.
TableExprNode sinh (const TableExprNode &node)
TableExprNode cos (const TableExprNode &node)
TableExprNode cosh (const TableExprNode &node)
TableExprNode exp (const TableExprNode &node)
TableExprNode log (const TableExprNode &node)
TableExprNode log10 (const TableExprNode &node)
TableExprNode pow (const TableExprNode &x, const TableExprNode &exp)
TableExprNode square (const TableExprNode &node)
TableExprNode cube (const TableExprNode &node)
TableExprNode sqrt (const TableExprNode &node)
TableExprNode norm (const TableExprNode &node)
TableExprNode asin (const TableExprNode &node)
Transcendental functions applied to to nodes containing scalars or arrays with double values.
TableExprNode acos (const TableExprNode &node)
TableExprNode atan (const TableExprNode &node)
TableExprNode atan2 (const TableExprNode &y, const TableExprNode &x)
TableExprNode tan (const TableExprNode &node)
TableExprNode tanh (const TableExprNode &node)
TableExprNode sign (const TableExprNode &node)
TableExprNode round (const TableExprNode &node)
TableExprNode ceil (const TableExprNode &node)
TableExprNode abs (const TableExprNode &node)
TableExprNode floor (const TableExprNode &node)
TableExprNode fmod (const TableExprNode &x, const TableExprNode &y)
TableExprNode strlength (const TableExprNode &node)
String functions on scalars or arrays.
TableExprNode upcase (const TableExprNode &node)
TableExprNode downcase (const TableExprNode &node)
TableExprNode capitalize (const TableExprNode &node)
TableExprNode trim (const TableExprNode &node)
TableExprNode ltrim (const TableExprNode &node)
TableExprNode rtrim (const TableExprNode &node)
TableExprNode substr (const TableExprNode &str, const TableExprNode &pos)
TableExprNode substr (const TableExprNode &str, const TableExprNode &pos, const TableExprNode &npos)
TableExprNode replace (const TableExprNode &str, const TableExprNode &patt)
TableExprNode replace (const TableExprNode &str, const TableExprNode &patt, const TableExprNode &repl)
TableExprNode regex (const TableExprNode &node)
Functions for regular expression matching and pattern matching.
TableExprNode pattern (const TableExprNode &node)
TableExprNode sqlpattern (const TableExprNode &node)
TableExprNode datetime (const TableExprNode &node)
Functions for date-values.
TableExprNode mjdtodate (const TableExprNode &node)
TableExprNode mjd (const TableExprNode &node)
TableExprNode date (const TableExprNode &node)
TableExprNode year (const TableExprNode &node)
TableExprNode month (const TableExprNode &node)
TableExprNode day (const TableExprNode &node)
TableExprNode cmonth (const TableExprNode &node)
TableExprNode weekday (const TableExprNode &node)
TableExprNode cdow (const TableExprNode &node)
TableExprNode ctodt (const TableExprNode &node)
TableExprNode cdate (const TableExprNode &node)
TableExprNode ctime (const TableExprNode &node)
TableExprNode week (const TableExprNode &node)
TableExprNode time (const TableExprNode &node)
TableExprNode hms (const TableExprNode &node)
Functions for angle-values.
TableExprNode dms (const TableExprNode &node)
TableExprNode hdms (const TableExprNode &node)
TableExprNode toString (const TableExprNode &node)
Function to convert any value to a string.
TableExprNode toString (const TableExprNode &node, const TableExprNode &format)
TableExprNode isNaN (const TableExprNode &node)
Function to test if a scalar or array is NaN (not-a-number).
TableExprNode isFinite (const TableExprNode &node)
Function to test if a scalar or array is finite.
TableExprNode min (const TableExprNode &a, const TableExprNode &b)
Minimum or maximum of 2 nodes.
TableExprNode max (const TableExprNode &a, const TableExprNode &b)
TableExprNode conj (const TableExprNode &node)
The complex conjugate of a complex node.
TableExprNode real (const TableExprNode &node)
The real part of a complex node.
TableExprNode imag (const TableExprNode &node)
The imaginary part of a complex node.
TableExprNode integer (const TableExprNode &node)
Convert double, bool, or string to int (using floor).
TableExprNode boolean (const TableExprNode &node)
Convert numeric or string value to bool (0, no, false, - means false)
TableExprNode amplitude (const TableExprNode &node)
The amplitude (i.e.
TableExprNode phase (const TableExprNode &node)
The phase (i.e.
TableExprNode arg (const TableExprNode &node)
The arg (i.e.
TableExprNode formComplex (const TableExprNode &real, const TableExprNode &imag)
Form a complex number from two Doubles.
TableExprNode formComplex (const TableExprNode &node)
Form a complex number from a string.
TableExprNode sum (const TableExprNode &array)
Functions operating on a Double or Complex scalar or array resulting in a scalar with the same data type.
TableExprNode product (const TableExprNode &array)
TableExprNode sumSquare (const TableExprNode &array)
TableExprNode min (const TableExprNode &array)
Functions operating on a Double scalar or array resulting in a Double scalar.
TableExprNode max (const TableExprNode &array)
TableExprNode mean (const TableExprNode &array)
TableExprNode variance (const TableExprNode &array)
TableExprNode stddev (const TableExprNode &array)
TableExprNode avdev (const TableExprNode &array)
TableExprNode rms (const TableExprNode &array)
TableExprNode median (const TableExprNode &array)
TableExprNode fractile (const TableExprNode &array, const TableExprNode &fraction)
TableExprNode any (const TableExprNode &array)
TableExprNode all (const TableExprNode &array)
TableExprNode ntrue (const TableExprNode &array)
TableExprNode nfalse (const TableExprNode &array)
TableExprNode sums (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
The partial version of the functions above.
TableExprNode products (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode sumSquares (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode mins (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode maxs (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode means (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode variances (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode stddevs (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode avdevs (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode rmss (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode medians (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode fractiles (const TableExprNode &array, const TableExprNode &fraction, const TableExprNodeSet &collapseAxes)
TableExprNode anys (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode alls (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode ntrues (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode nfalses (const TableExprNode &array, const TableExprNodeSet &collapseAxes)
TableExprNode runningMin (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
Functions operating for each element on a box around that element.
TableExprNode runningMax (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningMean (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningVariance (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningStddev (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningAvdev (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningRms (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningMedian (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningAny (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode runningAll (const TableExprNode &array, const TableExprNodeSet &halfBoxWidth)
TableExprNode array (const TableExprNode &values, const TableExprNodeSet &shape)
Create an array of the given shape and fill it with the values.
TableExprNode marray (const TableExprNode &array, const TableExprNode &mask)
Form a masked array.
TableExprNode arrayData (const TableExprNode &array)
Get the data array of a masked array.
TableExprNode arrayFlatten (const TableExprNode &array)
Flatten a masked array (get unmasked elements).
TableExprNode arrayMask (const TableExprNode &array)
Get the mask of a masked array.
TableExprNode diagonal (const TableExprNode &array)
Get the diagonal of a (masked) array; If the array is not a Matrix, it will take the diagonals of the subarrays given by the two axes in the axes argument.
TableExprNode diagonal (const TableExprNode &array, const TableExprNode &firstAxis)
TableExprNode diagonal (const TableExprNode &array, const TableExprNode &firstAxis, const TableExprNode &diag)
TableExprNode transpose (const TableExprNode &array)
Transpose all axes of a (masked) array.
TableExprNode transpose (const TableExprNode &array, const TableExprNode &axes)
Transpose a (masked) array by making the given axes the first axes.
TableExprNode isdefined (const TableExprNode &array)
Function operating on a field resulting in a bool scalar.
TableExprNode nelements (const TableExprNode &array)
Functions operating on any scalar or array resulting in a Double scalar.
TableExprNode ndim (const TableExprNode &array)
TableExprNode shape (const TableExprNode &array)
Function operating on any scalar or array resulting in a Double array containing the shape.
TableExprNode iif (const TableExprNode &condition, const TableExprNode &arg1, const TableExprNode &arg2)
Function resembling the ternary ?: construct in C++.
TableExprNode isInf (const TableExprNode &node)
TableExprNode boxedMin (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedMax (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedMean (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedVariance (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedStddev (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedAvdev (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedRms (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedMedian (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedAny (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode boxedAll (const TableExprNode &node, const TableExprNodeSet &halfBoxWidth)
TableExprNode transpose (const TableExprNode &array, const TableExprNodeSet &axes)
TaQLResult tableCommand (const String &command)
TaQLResult tableCommand (const String &command, const Table &tempTable)
TaQLResult tableCommand (const String &command, const std::vector< const Table * > &tempTables)
TaQLResult tableCommand (const String &command, Vector< String > &columnNames)
TaQLResult tableCommand (const String &command, Vector< String > &columnNames, String &commandType)
TaQLResult tableCommand (const String &command, const std::vector< const Table * > &tempTables, Vector< String > &columnNames)
TaQLResult tableCommand (const String &command, const std::vector< const Table * > &tempTables, Vector< String > &columnNames, String &commandType)
Variables
Bool aips_debug_on
If AIPS_DEBUG is not defined, then the symbol expands to (0) which in an if should be removed by the dead code eliminator of any optimizer; thus using this in your code should have no performance penalty in the normal case.
const Bool True
const Bool False
const Double IAU_k
const uInt N_FITS
Number of FITS units recognised (change the FITSstring and FITSunit lists in the UnitMap.cc when changing this number.
static const String EmptyString
Warning: SUN compiler does not accept non-simple default arguments
static class
casacore::UnitVal_static_initializer unitval_static_initializer
static class
casacore::CasarcCleanup local_cleanup_object
const uInt WORDSIZE
The size of a unsigned Integer (assumes 8-bit char)
int obscure_syntax
T * ptr_p
Bool isCarray_p
const Regex RXwhite
some built in regular expressions
const Regex RXint
const Regex RXdouble
const Regex RXalpha
const Regex RXlowercase
const Regex RXuppercase
const Regex RXalphanum
const Regex RXidentifier
const Int PQ_LEN
Length of P and Q arrays, half length of CL/SL arrays in IGRF model.
const Double DER_INTV
Interval (m) for derivatives in IGRF model.
CountedPtr< std::pair
< AccumType, AccumType > > _range
Bool _doMedAbsDevMed
ConcatTable * refTabPtr_p
Block< BaseColumn * > refColPtr_p
ColumnCache colCache_p
TableRecord keywordSet_p
Detailed Description
this file contains all the compiler specific defines
include python first to avoid _POSIX_C_SOURCE redefined warnings
include first to avoid _POSIX_C_SOURCE redefined warnings
-*- C++ -*-
Step through a const HashMap.
On some systems the following is needed to get the finite function.
template <class T, class U> class vector;
Don't forget a .tcc file is included at the end!
Intended use:
Public interface
Review Status
Date Reviewed:
yyyy/mm/dd
Synopsis
This class is an iterator, and it used to step through const HashMap s. This is useful when one wishes to find each of the user defined mappings in a particular map.
Example
#include <casacore/casa/Containers/HashMap.h>
#include <casacore/casa/BasicSL/String.h>
#include <casacore/casa/iostream.h>
main() {
HashMap<String,Int> hash;
hash.define("one",1);
hash.define("two",2);
hash.define("three",3);
hash.define("four",4);
hash.define("five",5);
hash.define("six",6);
ConstHashMapIter<String,Int> iter(hash);
for (iter.toStart(); ! iter.atEnd(); iter++)
cout << iter.getVal() << ": " << iter.getKey() << endl;
}
Motivation
Sometimes one needs to step through the defined elements of an associative array. The user should be told when iterator does not modify the underlying data structure. The standard C++ const is not sufficient because while the internal state of the iterator changes, the underlying data structure is not modified. For this reason, both const and non-const versions of the iterator are useful.
Define classes and functions to convert the basic data types and containers to and from Python.
Typedef Documentation
typedef AipsrcValue<Bool> casacore::AipsrcBool
Definition at line 47 of file Aipsrc.h.
typedef AipsrcValue<Double> casacore::AipsrcDouble
Definition at line 42 of file Aipsrc.h.
typedef AipsrcValue<Int> casacore::AipsrcInt
Definition at line 46 of file Aipsrc.h.
typedef Aipsrc casacore::AipsrcString
Definition at line 48 of file Aipsrc.h.
typedef AipsrcVector<Bool> casacore::AipsrcVBool
Definition at line 51 of file Aipsrc.h.
typedef AipsrcVector<Double> casacore::AipsrcVDouble
Definition at line 49 of file Aipsrc.h.
typedef AipsrcVector<Int> casacore::AipsrcVInt
Definition at line 50 of file Aipsrc.h.
typedef AipsrcVector<String> casacore::AipsrcVString
Definition at line 52 of file Aipsrc.h.
typedef FitsArray<FitsBit> casacore::BitFitsArray
Definition at line 1021 of file hdu.h.
typedef FitsField<FitsBit> casacore::BitFitsField
Definition at line 958 of file hdu.h.
typedef bool casacore::Bool
Define the standard types used by Casacore.
Definition at line 42 of file aipstype.h.
typedef FitsArray<unsigned char> casacore::ByteFitsArray
Definition at line 1023 of file hdu.h.
typedef FitsField<unsigned char> casacore::ByteFitsField
Definition at line 960 of file hdu.h.
typedef ImageExtension<unsigned char> casacore::ByteImageExtension
Definition at line 564 of file hdu.h.
typedef PrimaryArray<unsigned char> casacore::BytePrimaryArray
Definition at line 498 of file hdu.h.
typedef PrimaryGroup<unsigned char> casacore::BytePrimaryGroup
Definition at line 690 of file hdu.h.
typedef PrimaryTable<unsigned char> casacore::BytePrimaryTable
Definition at line 789 of file hdu.h.
typedef char casacore::Char
Definition at line 46 of file aipstype.h.
typedef FitsArray<char> casacore::CharFitsArray
Definition at line 1022 of file hdu.h.
typedef FitsField<char> casacore::CharFitsField
Definition at line 959 of file hdu.h.
typedef FitsArray<Complex> casacore::ComplexFitsArray
Definition at line 1028 of file hdu.h.
typedef FitsField<Complex> casacore::ComplexFitsField
Definition at line 965 of file hdu.h.
typedef FitsArray<DComplex> casacore::DComplexFitsArray
Definition at line 1030 of file hdu.h.
typedef FitsField<DComplex> casacore::DComplexFitsField
Definition at line 967 of file hdu.h.
typedef double casacore::Double
Definition at line 55 of file aipstype.h.
typedef Convolver<Double> casacore::DoubleConvolver
Definition at line 46 of file Convolver.h.
typedef FitsArray<double> casacore::DoubleFitsArray
Definition at line 1027 of file hdu.h.
typedef FitsField<double> casacore::DoubleFitsField
Definition at line 964 of file hdu.h.
typedef ImageExtension<double> casacore::DoubleImageExtension
Definition at line 568 of file hdu.h.
typedef PrimaryArray<double> casacore::DoublePrimaryArray
Definition at line 502 of file hdu.h.
typedef PrimaryGroup<double> casacore::DoublePrimaryGroup
Definition at line 694 of file hdu.h.
typedef PrimaryTable<double> casacore::DoublePrimaryTable
Definition at line 793 of file hdu.h.
typedef Int casacore::FitsLong
Definition at line 43 of file aipsxtype.h.
typedef float casacore::Float
Definition at line 54 of file aipstype.h.
typedef Convolver<Float> casacore::FloatConvolver
Typedefs.
Definition at line 42 of file Convolver.h.
typedef FitsArray<float> casacore::FloatFitsArray
Definition at line 1026 of file hdu.h.
typedef FitsField<float> casacore::FloatFitsField
Definition at line 963 of file hdu.h.
typedef ImageExtension<float> casacore::FloatImageExtension
Definition at line 567 of file hdu.h.
typedef PrimaryArray<float> casacore::FloatPrimaryArray
Definition at line 501 of file hdu.h.
typedef PrimaryGroup<float> casacore::FloatPrimaryGroup
Definition at line 693 of file hdu.h.
typedef PrimaryTable<float> casacore::FloatPrimaryTable
Definition at line 792 of file hdu.h.
typedef Float casacore::FType
Definition at line 43 of file MatrixSolver.h.
typedef FitsArray<IComplex> casacore::IComplexFitsArray
Definition at line 1029 of file hdu.h.
typedef FitsField<IComplex> casacore::IComplexFitsField
Definition at line 966 of file hdu.h.
typedef int casacore::Int
Definition at line 50 of file aipstype.h.
typedef long long casacore::Int64
Define the extra non-standard types used by Casacore (like proposed uSize, Size)
A guaranteed 64-bit long integer (for a.o. large file systems). An implementation must support the + and - operators.
Definition at line 38 of file aipsxtype.h.
typedef FilebufIO casacore::LargeFilebufIO
Definition at line 11 of file LargeFilebufIO.h.
typedef FiledesIO casacore::LargeFiledesIO
Definition at line 11 of file LargeFiledesIO.h.
typedef RegularFileIO casacore::LargeRegularFileIO
Definition at line 11 of file LargeRegularFileIO.h.
typedef long double casacore::lDouble
Definition at line 56 of file aipstype.h.
typedef Link<int> casacore::Link_int
Definition at line 202 of file Link.h.
typedef std::pair<Int64, Int64> casacore::LocationType
Definition at line 44 of file StatisticsTypes.h.
typedef FitsArray<FitsLogical> casacore::LogicalFitsArray
Definition at line 1020 of file hdu.h.
typedef FitsField<FitsLogical> casacore::LogicalFitsField
Definition at line 957 of file hdu.h.
typedef long casacore::Long
Definition at line 52 of file aipstype.h.
typedef FitsArray<FitsLong> casacore::LongFitsArray
Definition at line 1025 of file hdu.h.
typedef FitsField<FitsLong> casacore::LongFitsField
Definition at line 962 of file hdu.h.
typedef ImageExtension<FitsLong> casacore::LongImageExtension
Definition at line 566 of file hdu.h.
typedef PrimaryArray<FitsLong> casacore::LongPrimaryArray
Definition at line 500 of file hdu.h.
typedef PrimaryGroup<FitsLong> casacore::LongPrimaryGroup
Definition at line 692 of file hdu.h.
typedef PrimaryTable<FitsLong> casacore::LongPrimaryTable
Definition at line 791 of file hdu.h.
typedef MeasurementSet casacore::MS
MeasurementSet is too cumbersome for a number of common uses, so we give a typedef here.
Definition at line 110 of file MeasurementSet.h.
typedef MSSelectionKeywords casacore::MSS
Define a shorthand notation for this class, so enums can be specified easily.
Definition at line 40 of file MSSelectionKeywords.h.
typedef Quantum<Double> casacore::Quantity
Definition at line 38 of file Quantum.h.
typedef QVector<Double> casacore::QVD
Definition at line 37 of file QVector.h.
typedef TableColumn casacore::ROTableColumn
Define ROTableColumn for backward compatibility.
Definition at line 407 of file TableColumn.h.
typedef short casacore::Short
Definition at line 48 of file aipstype.h.
typedef FitsArray<short> casacore::ShortFitsArray
Definition at line 1024 of file hdu.h.
typedef FitsField<short> casacore::ShortFitsField
Definition at line 961 of file hdu.h.
typedef ImageExtension<short> casacore::ShortImageExtension
Definition at line 565 of file hdu.h.
typedef PrimaryArray<short> casacore::ShortPrimaryArray
Definition at line 499 of file hdu.h.
typedef PrimaryGroup<short> casacore::ShortPrimaryGroup
Definition at line 691 of file hdu.h.
typedef PrimaryTable<short> casacore::ShortPrimaryTable
Definition at line 790 of file hdu.h.
typedef struct casacore::TimeFields casacore::TimeFields
typedef unsigned char casacore::uChar
Definition at line 47 of file aipstype.h.
typedef unsigned int casacore::uInt
Definition at line 51 of file aipstype.h.
typedef unsigned long long casacore::uInt64
Definition at line 39 of file aipsxtype.h.
typedef unsigned long casacore::uLong
Definition at line 53 of file aipstype.h.
typedef unsigned short casacore::uShort
Definition at line 49 of file aipstype.h.
typedef FitsArray<FitsVADesc> casacore::VADescFitsArray
Definition at line 1031 of file hdu.h.
typedef FitsField<FitsVADesc> casacore::VADescFitsField
Definition at line 968 of file hdu.h.
Enumeration Type Documentation
anonymous enum
enum outside class because of compiler errors on HPUX
Enumerator
ConstListIterVersion
Definition at line 750 of file List.h.
Function Documentation
AccumType casacore::_getStatistic (StatisticsData::STATS stat)
StatsData<AccumType> casacore::_getStatistics ()
Bool casacore::_isInRange (const AccumType & datum) const inline
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, Int64 nr, uInt dataStride) const virtual
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude) const virtual
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride) const virtual
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude) const virtual
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride) const virtual
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude) const virtual
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude) const virtual
virtual void casacore::_minMax (CountedPtr< AccumType > & mymin, CountedPtr< AccumType > & mymax, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride) const virtual
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride) const
populate an unsorted array with valid data.
If includeLimits is defined, then restrict values that are entered in the array to those limits (inclusive of the minimum, exclusive of the maximum). maxCount and currentCount are used only if includeLimits is defined. In this case, the method will return when currentCount == maxCount, thus avoiding scanning remaining data unnecessarily.
no weights, no mask, no ranges
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude) const
ranges
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride) const
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude) const
mask and ranges
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride) const
weights
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude) const
weights and ranges
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride) const
weights and mask
void casacore::_populateArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude) const
weights, mask, ranges
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
no weights, no mask, no ranges
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
ranges
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
mask and ranges
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
weights
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
weights and ranges
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
weights and mask
virtual void casacore::_populateArrays (vector< vector< AccumType > > & arys, uInt64 & currentCount, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude, const vector< std::pair< AccumType, AccumType > > & includeLimits, uInt64 maxCount) const virtual
weights, mask, ranges
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride, uInt maxElements) const
no weights, no mask, no ranges
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude, uInt maxElements) const
ranges
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, uInt maxElements) const
mask
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude, uInt maxElements) const
mask and ranges
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, uInt maxElements) const
weights
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude, uInt maxElements) const
weights and ranges
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, uInt maxElements) const
weights and mask
Bool casacore::_populateTestArray (vector< AccumType > & ary, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude, uInt maxElements) const
weights, mask, ranges
void casacore::_setRange (CountedPtr< std::pair< AccumType, AccumType > > r) inline
Definition at line 508 of file ConstrainedRangeStatistics.h.
References _range.
virtual void casacore::_setRange () pure virtual
derived classes need to implement how to set their respective range
void casacore::_unweightedStats (StatsData< AccumType > & stats, uInt64 & ngood, LocationType & location, const DataIterator & dataBegin, Int64 nr, uInt dataStride)
no weights, no mask, no ranges
void casacore::_unweightedStats (StatsData< AccumType > & stats, uInt64 & ngood, LocationType & location, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude)
no weights, no mask
void casacore::_unweightedStats (StatsData< AccumType > & stats, uInt64 & ngood, LocationType & location, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride)
void casacore::_unweightedStats (StatsData< AccumType > & stats, uInt64 & ngood, LocationType & location, const DataIterator & dataBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude)
void casacore::_weightedStats (StatsData< AccumType > & stats, LocationType & location, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride)
has weights, but no mask, no ranges
void casacore::_weightedStats (StatsData< AccumType > & stats, LocationType & location, const DataIterator & dataBegin, const WeightsIterator & weightsBegin, Int64 nr, uInt dataStride, const DataRanges & ranges, Bool isInclude)
void casacore::_weightedStats (StatsData< AccumType > & stats, LocationType & location, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride)
void casacore::_weightedStats (StatsData< AccumType > & stats, LocationType & location, const DataIterator & dataBegin, const WeightsIterator & weightBegin, Int64 nr, uInt dataStride, const MaskIterator & maskBegin, uInt maskStride, const DataRanges & ranges, Bool isInclude)
void casacore::a2_re_compile_fastmap ()
const char* casacore::a2_re_compile_pattern ()
int casacore::a2_re_match ()
int casacore::a2_re_match_2 ()
int casacore::a2_re_search ()
int casacore::a2_re_search_2 ()
LatticeExprNode casacore::abs (const LatticeExprNode & expr)
Numerical 1-argument functions which result in a real number regardless of input expression type.
Referenced by casacore::Complex_global_functions_Complex_desc::fabs(), casacore::Abs< T, RES >::operator()(), casacore::SumAbsDiff< T, Accum >::operator()(), and casacore::FrequencyAligner< T >::setTolerance().
TableExprNode casacore::abs (const TableExprNode & node) inline
Definition at line 1556 of file ExprNode.h.
References casacore::TableExprFuncNode::absFUNC, and casacore::TableExprNode::newFunctionNode().
template<typename InputIterator , typename MaskIterator , typename Accum , typename BinaryOperator > Accum casacore::accumulateFalse (InputIterator first, InputIterator last, MaskIterator mask, Accum acc, BinaryOperator op = std::plus<Accum>()) inline
Define a function (similar to std::accumulate) to do accumulation of elements for which the corresponding mask value is false.
The default accumulation is addition.
Definition at line 82 of file Functors.h.
References mask().
template<typename InputIterator , typename MaskIterator , typename Accum , typename BinaryOperator > Accum casacore::accumulateTrue (InputIterator first, InputIterator last, MaskIterator mask, Accum acc, BinaryOperator op = std::plus<Accum>()) inline
Define a function (similar to std::accumulate) to do accumulation of elements for which the corresponding mask value is true.
The default accumulation is addition.
Definition at line 68 of file Functors.h.
References mask().
LatticeExprNode casacore::acos (const LatticeExprNode & expr)
Referenced by casacore::TableExprFuncNode::angdist(), and casacore::Acos< T, RES >::operator()().
TableExprNode casacore::acos (const TableExprNode & node) inline
Definition at line 1528 of file ExprNode.h.
References casacore::TableExprFuncNode::acosFUNC, and casacore::TableExprNode::newFunctionNode().
void casacore::addRecordDesc (TableDesc & tableDescription, const RecordDesc & recordDescription, const String & prefix)
This function probably doesn't belong here, but I'm not yet sure where it does belong.
This function adds all the fields in recordDescription to tableDescription, prefixed by "prefix". If prefix is empty, nothing is prepended otherwise the string prefix + "_" is prepended to each RecordFieldPtr name in constructing the TableDesc
LatticeExprNode casacore::all (const LatticeExprNode & expr)
TableExprNode casacore::all (const TableExprNode & array) inline
Definition at line 1864 of file ExprNode.h.
References casacore::TableExprFuncNode::allFUNC, and casacore::TableExprNode::newFunctionNode().
template<typename C1 , typename C2 , typename U > bool casacore::allNear (const C1 & l, const C2 & r, U tolerance)
Test if all elements of the containers are relatively near each other.
Definition at line 49 of file StdLogical.h.
References compareAll().
template<typename C1 , typename C2 , typename U > bool casacore::allNearAbs (const C1 & l, const C2 & r, U tolerance)
Test if all elements of the containers are absolutely near each other.
Definition at line 54 of file StdLogical.h.
References compareAll().
TableExprNode casacore::alls (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1955 of file ExprNode.h.
References casacore::TableExprFuncNode::allsFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::amp (const LatticeExprNode & left, const LatticeExprNode & right)
This function finds sqrt(left^2+right^2).
This could be used to find the (biased) polarized intensity if left and right are images of Stokes Q and U.
TableExprNode casacore::amplitude (const TableExprNode & node) inline
The amplitude (i.e.
sqrt(re*re + im*im)) of a complex node. This is a synonym for function abs. Defined for scalars and arrays.
Definition at line 1604 of file ExprNode.h.
References casacore::TableExprFuncNode::absFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::angdist (const TableExprNode & pos1, const TableExprNode & pos2) inline
Angular distance between positions.
Both arguments have to be arrays. If both arrays contain 2 values (ra and dec), the result is a scalar. Otherwise the arrays have to contain a multiple of 2 values and the result is a 2-dim array giving the distance of each position in the first array to each position in the second array.
Definition at line 1427 of file ExprNode.h.
References casacore::TableExprFuncNode::angdistFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::angdistx (const TableExprNode & pos1, const TableExprNode & pos2) inline
Angular distance as above, but only pair-wise enties are used if both arguments are arrays.
Definition at line 1433 of file ExprNode.h.
References casacore::TableExprFuncNode::angdistxFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::any (const LatticeExprNode & expr)
Functions operating on a logical expression resulting in a scalar; Functions "any" (are any pixels "True") and "all" (are all pixels "True") result in a Bool; functions "ntrue" and "nfalse" result in a Double.
TableExprNode casacore::any (const TableExprNode & array) inline
Definition at line 1860 of file ExprNode.h.
References casacore::TableExprFuncNode::anyFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::anyCone (const TableExprNode & sourcePos, const TableExprNode & cones) inline
The result is always a Bool scalar telling if any cone contains the source.
Definition at line 1445 of file ExprNode.h.
References casacore::TableExprFuncNode::anyconeFUNC, and casacore::TableExprNode::newConeNode().
TableExprNode casacore::anyCone (const TableExprNode & sourcePos, const TableExprNode & conePos, const TableExprNode & radii) inline
Definition at line 1464 of file ExprNode.h.
References casacore::TableExprFuncNode::anycone3FUNC, and casacore::TableExprNode::newConeNode().
template<class T > Bool casacore::anyEQ (const TableVector< T > & l, const TableVector< T > & r) inline
Definition at line 168 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyEQ (const TableVector< T > & tv, const T & val) inline
Definition at line 226 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyEQ (const T & val, const TableVector< T > & tv) inline
Definition at line 231 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyGE (const TableVector< T > & l, const TableVector< T > & r) inline
Definition at line 158 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyGE (const TableVector< T > & tv, const T & val) inline
Definition at line 206 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyGE (const T & val, const TableVector< T > & tv) inline
Definition at line 211 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyGT (const TableVector< T > & l, const TableVector< T > & r) inline
Definition at line 163 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyGT (const TableVector< T > & tv, const T & val) inline
Definition at line 216 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyGT (const T & val, const TableVector< T > & tv) inline
Definition at line 221 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyLE (const TableVector< T > & l, const TableVector< T > & r) inline
Element by element comparisons between the "l" and "r" table vectors.
The result is true if the comparison is true for some element of the vectors. At some point operators will be available that return masks where the comparison is true. The vectors must conform or an exception is thrown.
Definition at line 148 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyLE (const TableVector< T > & tv, const T & val) inline
Element by element comparisons between a table vector and a scalar, which behaves as if it were a conformant vector filled with the value "val." The result is true if the comparison is true for some element of the vector.
At some point operators will be available that return masks where the comparison is true.
Definition at line 186 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyLE (const T & val, const TableVector< T > & tv) inline
Definition at line 191 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyLT (const TableVector< T > & l, const TableVector< T > & r) inline
Definition at line 153 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyLT (const TableVector< T > & tv, const T & val) inline
Definition at line 196 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyLT (const T & val, const TableVector< T > & tv) inline
Definition at line 201 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyNE (const TableVector< T > & l, const TableVector< T > & r) inline
Definition at line 173 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyNE (const TableVector< T > & tv, const T & val) inline
Definition at line 236 of file TabVecLogic.h.
References False, and True.
template<class T > Bool casacore::anyNE (const T & val, const TableVector< T > & tv) inline
Definition at line 241 of file TabVecLogic.h.
References False, and True.
TableExprNode casacore::anys (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1949 of file ExprNode.h.
References casacore::TableExprFuncNode::anysFUNC, and casacore::TableExprNode::newFunctionNode().
template<class T > Bool casacore::areEQ (const ROScalarColumn< T > & col, uInt row_i, uInt row_j)
Definition at line 173 of file MSConcat.h.
template<class T > Bool casacore::areEQ (const ROArrayColumn< T > & col, uInt row_i, uInt row_j)
Definition at line 182 of file MSConcat.h.
References False, casacore::ArrayBase::nelements(), and True.
LatticeExprNode casacore::arg (const LatticeExprNode & expr)
Referenced by casacore::CArg< T, RES >::operator()().
TableExprNode casacore::arg (const TableExprNode & node) inline
The arg (i.e.
atan2(im, re)) of a complex node. Defined for scalars and arrays.
Definition at line 1608 of file ExprNode.h.
References casacore::TableExprFuncNode::argFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::array (const TableExprNode & values, const TableExprNodeSet & shape) inline
Create an array of the given shape and fill it with the values.
The values array is rewound as needed.
Definition at line 2093 of file ExprNode.h.
References casacore::TableExprFuncNode::arrayFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::arrayData (const TableExprNode & array) inline
Get the data array of a masked array.
Definition at line 2105 of file ExprNode.h.
References casacore::TableExprFuncNode::arrdataFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::arrayFlatten (const TableExprNode & array) inline
Flatten a masked array (get unmasked elements).
Definition at line 2115 of file ExprNode.h.
References casacore::TableExprFuncNode::arrflatFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::arrayMask (const TableExprNode & array) inline
Get the mask of a masked array.
If the array has no mask, it return an array with all False values.
Definition at line 2110 of file ExprNode.h.
References casacore::TableExprFuncNode::arrmaskFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::asin (const LatticeExprNode & expr)
Referenced by casacore::Asin< T, RES >::operator()().
TableExprNode casacore::asin (const TableExprNode & node) inline
Transcendental functions applied to to nodes containing scalars or arrays with double values.
They are invalid for Complex nodes.
Definition at line 1532 of file ExprNode.h.
References casacore::TableExprFuncNode::asinFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::atan (const LatticeExprNode & expr)
Referenced by casacore::Atan< T, RES >::operator()().
TableExprNode casacore::atan (const TableExprNode & node) inline
Definition at line 1536 of file ExprNode.h.
References casacore::TableExprFuncNode::atanFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::atan2 (const LatticeExprNode & left, const LatticeExprNode & right)
Numerical 2-argument functions.
Referenced by casacore::Atan2< L, R, RES >::operator()().
TableExprNode casacore::atan2 (const TableExprNode & y, const TableExprNode & x) inline
Definition at line 1540 of file ExprNode.h.
References casacore::TableExprFuncNode::atan2FUNC, and casacore::TableExprNode::newFunctionNode().
void* casacore::attachRecordFieldPtr (RecordInterface * parent, Int fieldNumber, DataType type, const void *) inline
This function attaches a RecordFieldPtr object.
It is checked if the field type is correct.
Definition at line 282 of file RecordField.h.
References casacore::RecordInterface::get_pointer().
void* casacore::attachRecordFieldPtr (RecordInterface * parent, Int fieldNumber, DataType , const Table *) inline
Specialization for a Table field (which cannot be used).
Definition at line 288 of file RecordField.h.
References casacore::RecordInterface::get_pointer().
void* casacore::attachRecordFieldPtr (RecordInterface * parent, Int fieldNumber, DataType , const Record *) inline
Specialization for a Record field.
Definition at line 294 of file RecordField.h.
References casacore::RecordInterface::get_pointer().
void* casacore::attachRecordFieldPtr (RecordInterface * parent, Int fieldNumber, DataType , const TableRecord *) inline
Specialization for a TableRecord field.
Definition at line 300 of file RecordField.h.
References casacore::RecordInterface::get_pointer().
LatticeExprNode casacore::avdev (const LatticeExprNode & expr)
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::AvdevFunc< T >::operator()(), and casacore::MaskedAvdevFunc< T >::operator()().
TableExprNode casacore::avdev (const TableExprNode & array) inline
Definition at line 1839 of file ExprNode.h.
References casacore::TableExprFuncNode::arravdevFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::avdevs (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1924 of file ExprNode.h.
References casacore::TableExprFuncNode::arravdevsFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boolean (const TableExprNode & node) inline
Convert numeric or string value to bool (0, no, false, - means false)
Definition at line 1596 of file ExprNode.h.
References casacore::TableExprFuncNode::boolFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedAll (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2087 of file ExprNode.h.
References casacore::TableExprFuncNode::boxallFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedAny (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2081 of file ExprNode.h.
References casacore::TableExprFuncNode::boxanyFUNC, and casacore::TableExprNode::newFunctionNode().
template<typename T , typename FuncType > MaskedArray<T> casacore::boxedArrayMath (const MaskedArray< T > & array, const IPosition & boxSize, const FuncType & funcObj)
Apply the given ArrayMath reduction function objects to each box in the array.
Example
Downsample an array by taking the mean of every [25,25] elements.
Array<Float> downArr = boxedArrayMath(in, IPosition(2,25,25),
MaskedMeanFunc<Float>());
The dimensionality of the array can be larger than the box; in that case the missing axes of the box are assumed to have length 1. A box axis length <= 0 means the full array axis.
Referenced by casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedAlls(), casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedAnys(), casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedNFalse(), and casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedNTrue().
TableExprNode casacore::boxedAvdev (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2063 of file ExprNode.h.
References casacore::TableExprFuncNode::boxavdevFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedMax (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2039 of file ExprNode.h.
References casacore::TableExprFuncNode::boxmaxFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedMean (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2045 of file ExprNode.h.
References casacore::TableExprFuncNode::boxmeanFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedMedian (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2075 of file ExprNode.h.
References casacore::TableExprFuncNode::boxmedianFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedMin (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2033 of file ExprNode.h.
References casacore::TableExprFuncNode::boxminFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedRms (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2069 of file ExprNode.h.
References casacore::TableExprFuncNode::boxrmsFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedStddev (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2057 of file ExprNode.h.
References casacore::TableExprFuncNode::boxstddevFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::boxedVariance (const TableExprNode & node, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2051 of file ExprNode.h.
References casacore::TableExprFuncNode::boxvarianceFUNC, and casacore::TableExprNode::newFunctionNode().
Bool casacore::canUseHDF5Image () inline
Tell if HDF5 images can be used.
Definition at line 324 of file HDF5Image.h.
References casacore::HDF5Object::hasHDF5Support().
TableExprNode casacore::capitalize (const TableExprNode & node) inline
Definition at line 1642 of file ExprNode.h.
References casacore::TableExprFuncNode::capitalizeFUNC, and casacore::TableExprNode::newFunctionNode().
Referenced by casacore::Capitalize::operator()().
casacore::CASA_TMP_939727 (void)
casacore::CASA_TMP_939727 (bool)
casacore::CASA_TMP_939727 (wchar_t)
casacore::CASA_TMP_939727 (signed char)
casacore::CASA_TMP_939727 (unsigned char)
casacore::CASA_TMP_939727 (float)
casacore::CASA_TMP_939727 (double)
casacore::CASA_TMP_939727 (long double)
casacore::CASA_TMP_939727_int (int)
casacore::CASA_TMP_939727_int (long int)
casacore::CASA_TMP_939727_int (long long int)
TableExprNode casacore::cdate (const TableExprNode & node) inline
Definition at line 1709 of file ExprNode.h.
References casacore::TableExprFuncNode::cdateFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::cdow (const TableExprNode & node) inline
Definition at line 1701 of file ExprNode.h.
References casacore::TableExprFuncNode::cdowFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::ceil (const LatticeExprNode & expr)
Referenced by casacore::Complex_global_functions_Complex_desc::ceil(), casacore::Ceil< T, RES >::operator()(), and casacore::Round< T, RES >::operator()().
TableExprNode casacore::ceil (const TableExprNode & node) inline
Definition at line 1552 of file ExprNode.h.
References casacore::TableExprFuncNode::ceilFUNC, and casacore::TableExprNode::newFunctionNode().
void casacore::cgetrf (const int * m, const int * n, Complex * a, const int * lda, int * ipiv, int * info)
Referenced by getrf().
void casacore::cgetri (const int * m, Complex * a, const int * lda, const int * ipiv, Complex * work, const int * lwork, int * info)
Referenced by getri().
void casacore::check_hid_t (int) inline
Definition at line 53 of file HDF5Object.h.
Referenced by casacore::HDF5Object::HDF5Object().
template<typename T > void casacore::check_hid_t (T) inline
Definition at line 54 of file HDF5Object.h.
References throwInvHDF5().
void casacore::check_hsize_t (unsigned long long) inline
Definition at line 55 of file HDF5Object.h.
Referenced by casacore::HDF5Object::HDF5Object().
template<typename T > void casacore::check_hsize_t (T) inline
Definition at line 56 of file HDF5Object.h.
References throwInvHDF5().
template<class T > void casacore::CholeskyDecomp (Matrix< T > & A, Vector< T > & diag)
template<class T > void casacore::CholeskySolve (Matrix< T > & A, Vector< T > & diag, Vector< T > & b, Vector< T > & x)
TableExprNode casacore::cmonth (const TableExprNode & node) inline
Definition at line 1691 of file ExprNode.h.
References casacore::TableExprFuncNode::cmonthFUNC, and casacore::TableExprNode::newFunctionNode().
template<typename C1 , typename C2 , typename CompareOperator > bool casacore::compareAll (const C1 & l, const C2 & r, CompareOperator op)
Arbitrary compare operation on two STL-style containers.
It returns True if containers have equal size and all elements compare True.
Definition at line 41 of file StdLogical.h.
References compareAll().
template<typename InputIterator1 , typename InputIterator2 , typename CompareOperator > bool casacore::compareAll (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, CompareOperator op) inline
Define a function to compare all elements of two sequences.
It returns true if all elements compare true. An example compare operator is std::equal_to.
Definition at line 97 of file Functors.h.
Referenced by allNear(), allNearAbs(), and compareAll().
template<typename InputIterator1 , typename T , typename CompareOperator > bool casacore::compareAllLeft (InputIterator1 first1, InputIterator1 last1, T left, CompareOperator op) inline
For use with a constant left value.
This avoids use of bind1st or bind2nd which can fail for gcc-4.3. (see ArrayMath.h).
Definition at line 109 of file Functors.h.
template<typename InputIterator1 , typename T , typename CompareOperator > bool casacore::compareAllRight (InputIterator1 first1, InputIterator1 last1, T right, CompareOperator op) inline
For use with a constant right value.
This avoids use of bind1st or bind2nd which can fail for gcc-4.3. (see ArrayMath.h).
Definition at line 121 of file Functors.h.
template<typename InputIterator1 , typename InputIterator2 , typename CompareOperator > bool casacore::compareAny (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, CompareOperator op) inline
Define a function to compare all elements of two sequences.
It returns true if any element compares true. An example compare operator is std::equal_to.
Definition at line 136 of file Functors.h.
template<typename InputIterator1 , typename T , typename CompareOperator > bool casacore::compareAnyLeft (InputIterator1 first1, InputIterator1 last1, T left, CompareOperator op) inline
For use with a constant left value.
This avoids use of bind1st or bind2nd which can fail for gcc-4.3. (see ArrayMath.h).
Definition at line 148 of file Functors.h.
template<typename InputIterator1 , typename T , typename CompareOperator > bool casacore::compareAnyRight (InputIterator1 first1, InputIterator1 last1, T right, CompareOperator op) inline
For use with a constant right value.
This avoids use of bind1st or bind2nd which can fail for gcc-4.3. (see ArrayMath.h).
Definition at line 160 of file Functors.h.
TableExprNode casacore::cones (const TableExprNode & sourcePos, const TableExprNode & cones) inline
Cone search; test if the position of a source is inside a cone.
Argument sourcePos must be a double array containing two values (ra and dec of source) in radians.
Argument cones must be a double array specifying the position of the cone centers and radii in radians. So the array must contain three values (ra,dec,radius) or a multiple of it.
The result is a bool array telling for each cone if it contains the source. If there is only one cone, the result is a scalar.
Definition at line 1439 of file ExprNode.h.
References casacore::TableExprFuncNode::conesFUNC, and casacore::TableExprNode::newConeNode().
TableExprNode casacore::cones (const TableExprNode & sourcePos, const TableExprNode & conePos, const TableExprNode & radii) inline
Cone search as above.
However, the cone positions and radii are specified separately and (virtually) a larger array containing every combination of position/radius is formed.
Definition at line 1457 of file ExprNode.h.
References casacore::TableExprFuncNode::cones3FUNC, and casacore::TableExprNode::newConeNode().
LatticeExprNode casacore::conj (const LatticeExprNode & expr)
Referenced by casacore::Conj< T, RES >::operator()().
TableExprNode casacore::conj (const TableExprNode & node) inline
The complex conjugate of a complex node.
Defined for scalars and arrays.
Definition at line 1600 of file ExprNode.h.
References casacore::TableExprFuncNode::conjFUNC, and casacore::TableExprNode::newFunctionNode().
template<typename T , typename U > CountedPtr<T> casacore::const_pointer_cast (const CountedPtr< U > & that)
Definition at line 268 of file CountedPtr.h.
String casacore::constructMessage (const Int pos, const String & command)
Referenced by casacore::MSSelectionLogError::handleError().
LatticeExprNode casacore::convertType (const LatticeExprNode & expr, const Float *) inline
Definition at line 849 of file LatticeExprNode.h.
References toFloat().
LatticeExprNode casacore::convertType (const LatticeExprNode & expr, const Double *) inline
Definition at line 851 of file LatticeExprNode.h.
References toDouble().
LatticeExprNode casacore::convertType (const LatticeExprNode & expr, const Complex *) inline
Definition at line 853 of file LatticeExprNode.h.
References toComplex().
LatticeExprNode casacore::convertType (const LatticeExprNode & expr, const DComplex *) inline
Definition at line 855 of file LatticeExprNode.h.
References toDComplex().
LatticeExprNode casacore::convertType (const LatticeExprNode & expr, const Bool *) inline
Definition at line 857 of file LatticeExprNode.h.
References toBool().
template<class AccumType > StatsData<AccumType> casacore::copy (const StatsData< AccumType > & stats)
Referenced by casacore::String::copy(), casacore::Copy_global_functions_copy::objcopy(), and casacore::Copy_global_functions_copy::objmove().
LatticeExprNode casacore::cos (const LatticeExprNode & expr)
Referenced by casacore::TableExprFuncNode::angdist(), and casacore::Cos< T, RES >::operator()().
TableExprNode casacore::cos (const TableExprNode & node) inline
Definition at line 1478 of file ExprNode.h.
References casacore::TableExprFuncNode::cosFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::cosh (const LatticeExprNode & expr)
Referenced by casacore::Cosh< T, RES >::operator()().
TableExprNode casacore::cosh (const TableExprNode & node) inline
Definition at line 1482 of file ExprNode.h.
References casacore::TableExprFuncNode::coshFUNC, and casacore::TableExprNode::newFunctionNode().
Bool casacore::countedPtrShared () inline
A shared_ptr is used as implementation.
Definition at line 260 of file CountedPtr.h.
References True.
void casacore::cposv (const char * uplo, const int * n, const int * nrhs, Complex * a, const int * lda, Complex * b, const int * ldb, int * info)
Referenced by posv().
void casacore::cpotri (const char * uplo, const int * n, Complex * a, const int * lda, int * info)
Referenced by potri().
template<class T > TableVector<T> casacore::crossProduct (const TableVector< T > & l, const TableVector< T > & r) inline
Definition at line 417 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
TableExprNode casacore::ctime (const TableExprNode & node) inline
Definition at line 1713 of file ExprNode.h.
References casacore::TableExprFuncNode::ctimeFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::ctodt (const TableExprNode & node) inline
Definition at line 1705 of file ExprNode.h.
References casacore::TableExprFuncNode::ctodFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::cube (const TableExprNode & node) inline
Definition at line 1515 of file ExprNode.h.
References casacore::TableExprFuncNode::cubeFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::date (const TableExprNode & node) inline
Definition at line 1675 of file ExprNode.h.
References casacore::TableExprFuncNode::dateFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::datetime (const TableExprNode & node) inline
Functions for date-values.
Defined for scalars and arrays.
Definition at line 1661 of file ExprNode.h.
References casacore::TableExprFuncNode::datetimeFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::day (const TableExprNode & node) inline
Definition at line 1687 of file ExprNode.h.
References casacore::TableExprFuncNode::dayFUNC, and casacore::TableExprNode::newFunctionNode().
void casacore::defineRecordFieldPtr (RecordInterface * parent, Int fieldNumber, DataType type, const void * value) inline
Definition at line 269 of file RecordField.h.
References casacore::RecordInterface::defineDataField().
void casacore::defineRecordFieldPtr (RecordInterface * parent, Int fieldNumber, DataType , const TableRecord * value) inline
Definition at line 274 of file RecordField.h.
References casacore::RecordInterface::defineDataField().
void casacore::delete_pointer_if_necessary () private
void casacore::dgetrf (const int * m, const int * n, double * a, const int * lda, int * ipiv, int * info)
Referenced by getrf().
void casacore::dgetri (const int * m, double * a, const int * lda, const int * ipiv, double * work, const int * lwork, int * info)
Referenced by getri().
TableExprNode casacore::diagonal (const TableExprNode & array) inline
Get the diagonal of a (masked) array; If the array is not a Matrix, it will take the diagonals of the subarrays given by the two axes in the axes argument.
Those axes have to have the same length (thus each subarray is a Matrix). If no axes are given, they default to the first two axes.
The diag argument tells which diagonal to take. 0 is the main diagonal, >0 is above main diagonal, <0 is below.
Definition at line 2133 of file ExprNode.h.
References casacore::TableExprFuncNode::diagonalFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::diagonal (const TableExprNode & array, const TableExprNode & firstAxis)
TableExprNode casacore::diagonal (const TableExprNode & array, const TableExprNode & firstAxis, const TableExprNode & diag)
TableExprNode casacore::dms (const TableExprNode & node) inline
Definition at line 1721 of file ExprNode.h.
References casacore::TableExprFuncNode::dmsFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::downcase (const TableExprNode & node) inline
Definition at line 1637 of file ExprNode.h.
References casacore::TableExprFuncNode::downcaseFUNC, and casacore::TableExprNode::newFunctionNode().
Referenced by casacore::CoordinateSystem::_downcase(), and casacore::Downcase::operator()().
void casacore::dposv (const char * uplo, const int * n, const int * nrhs, double * a, const int * lda, double * b, const int * ldb, int * info)
Referenced by posv().
void casacore::dpotri (const char * uplo, const int * n, double * a, const int * lda, int * info)
Referenced by potri().
template<typename T , typename U > CountedPtr<T> casacore::dynamic_pointer_cast (const CountedPtr< U > & that)
Definition at line 271 of file CountedPtr.h.
LatticeExprNode casacore::exp (const LatticeExprNode & expr)
Referenced by casacore::Exp< T, RES >::operator()(), and pow().
TableExprNode casacore::exp (const TableExprNode & node) inline
Definition at line 1486 of file ExprNode.h.
References casacore::TableExprFuncNode::expFUNC, and casacore::TableExprNode::newFunctionNode().
void casacore::fillBoxedShape (const IPosition & shape, const IPosition & boxShape, IPosition & fullBoxShape, IPosition & resultShape)
Helper functions for boxed and sliding functions.
Determine full box shape and shape of result for a boxed operation.
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath().
Bool casacore::fillSlidingShape (const IPosition & shape, const IPosition & halfBoxSize, IPosition & boxEnd, IPosition & resultShape)
Determine the box end and shape of result for a sliding operation.
It returns False if the result is empty.
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath().
std::set<ScanKey> casacore::filter (const std::set< ScanKey > scans, const ArrayKey & arrayKey)
given a set of scan keys, return the subset that matches the given array key
TableExprNode casacore::findCone (const TableExprNode & sourcePos, const TableExprNode & cones) inline
The sourcePos can contain multiple sources.
The result is a double array giving the index of the first cone containing the corresponding source. If there is one source, the result is a double scalar.
Definition at line 1451 of file ExprNode.h.
References casacore::TableExprFuncNode::findconeFUNC, and casacore::TableExprNode::newConeNode().
TableExprNode casacore::findCone (const TableExprNode & sourcePos, const TableExprNode & conePos, const TableExprNode & radii) inline
Definition at line 1471 of file ExprNode.h.
References casacore::TableExprFuncNode::findcone3FUNC, and casacore::TableExprNode::newConeNode().
LatticeExprNode casacore::floor (const LatticeExprNode & expr)
Referenced by casacore::Complex_global_functions_Complex_desc::floor(), casacore::Gridder< Domain, Range >::nint(), casacore::Floor< T, RES >::operator()(), and casacore::Round< T, RES >::operator()().
TableExprNode casacore::floor (const TableExprNode & node) inline
Definition at line 1560 of file ExprNode.h.
References casacore::TableExprFuncNode::floorFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::fmod (const LatticeExprNode & left, const LatticeExprNode & right)
Referenced by casacore::Math_global_functions_Math_interface_for_casacore::floormod(), operator%(), and casacore::Fmod< L, R, RES >::operator()().
TableExprNode casacore::fmod (const TableExprNode & x, const TableExprNode & y) inline
Definition at line 1564 of file ExprNode.h.
References casacore::TableExprFuncNode::fmodFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::formComplex (const LatticeExprNode & left, const LatticeExprNode & right)
Form a complex number from two real numbers.
TableExprNode casacore::formComplex (const TableExprNode & real, const TableExprNode & imag) inline
Form a complex number from two Doubles.
One or both arguments can be scalar or array.
Definition at line 1616 of file ExprNode.h.
References casacore::TableExprFuncNode::complexFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::formComplex (const TableExprNode & node) inline
Form a complex number from a string.
Defined for scalars and arrays.
Definition at line 1622 of file ExprNode.h.
References casacore::TableExprFuncNode::complexFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::fractile (const LatticeExprNode & expr, const LatticeExprNode & fraction)
Determine the value of the element at the part fraction from the beginning of the given lattice.
Thus fraction=0.5 is equal to the median.
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::FractileFunc< T >::operator()().
TableExprNode casacore::fractile (const TableExprNode & array, const TableExprNode & fraction) inline
Definition at line 1854 of file ExprNode.h.
References casacore::TableExprFuncNode::arrfractileFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::fractileRange (const LatticeExprNode & expr, const LatticeExprNode & fraction1, const LatticeExprNode & fraction2)
Determine the value range of the elements at the part fraction1 and fraction2 from the beginning of the given lattice.
Both fractions must be >=0 and <=1 and fraction1 must be <= fraction2. By default fraction2 is equal to 1-fraction1. Thus fraction=0.25 gives the quartile range of the lattice.
LatticeExprNode casacore::fractileRange (const LatticeExprNode & expr, const LatticeExprNode & fraction)
TableExprNode casacore::fractiles (const TableExprNode & array, const TableExprNode & fraction, const TableExprNodeSet & collapseAxes) inline
Definition at line 1942 of file ExprNode.h.
References casacore::TableExprFuncNode::arrfractilesFUNC, and casacore::TableExprNode::newFunctionNode().
template<class V > void casacore::getArray (Array< V > & val, int type, const Record & gr, const String & name)
template<class V > void casacore::getArrayVal (V & val, int type, const Record & gr, const String & name, uInt index = 0)
void casacore::getBlock (AipsIO & , Block< void * > &) inline
Definition at line 136 of file BlockIO.h.
void casacore::getrf (const int * m, const int * n, float * a, const int * lda, int * ipiv, int * info) inline
Definition at line 167 of file MatrixMathLA.h.
References sgetrf().
void casacore::getrf (const int * m, const int * n, double * a, const int * lda, int * ipiv, int * info) inline
Definition at line 170 of file MatrixMathLA.h.
References dgetrf().
void casacore::getrf (const int * m, const int * n, Complex * a, const int * lda, int * ipiv, int * info) inline
Definition at line 173 of file MatrixMathLA.h.
References cgetrf().
void casacore::getrf (const int * m, const int * n, DComplex * a, const int * lda, int * ipiv, int * info) inline
Definition at line 176 of file MatrixMathLA.h.
References zgetrf().
void casacore::getri (const int * m, float * a, const int * lda, const int * ipiv, float * work, const int * lwork, int * info) inline
Definition at line 179 of file MatrixMathLA.h.
References sgetri().
void casacore::getri (const int * m, double * a, const int * lda, const int * ipiv, double * work, const int * lwork, int * info) inline
Definition at line 182 of file MatrixMathLA.h.
References dgetri().
void casacore::getri (const int * m, Complex * a, const int * lda, const int * ipiv, Complex * work, const int * lwork, int * info) inline
Definition at line 185 of file MatrixMathLA.h.
References cgetri().
void casacore::getri (const int * m, DComplex * a, const int * lda, const int * ipiv, DComplex * work, const int * lwork, int * info) inline
Definition at line 188 of file MatrixMathLA.h.
References zgetri().
Bool casacore::getSelectedTable (Table & selectedTab, const Table & baseTab, TableExprNode & fullTEN, const String & outName)
const std::string casacore::getVersion ()
Get the casacore version.
const std::string casacore::getVersionCASA ()
Get the version of casacore on CASA's vendor branch Note: CASA's private version of casacore has a lifecycle which is not necessarily identical to versions of casacore elsewhere.
This function returns the version of casacore on CASA's vendor branch.
uInt casacore::hashFunc (const ObjectID &)
DataType casacore::hdf5imagePixelType (const String & fileName)
Determine the pixel type in the HDF5Image contained in fileName.
If the file doesn't appear to be HDF5 or cannot be opened, TpOther is returned. <group name="pixeltype")
TableExprNode casacore::hdms (const TableExprNode & node) inline
Definition at line 1725 of file ExprNode.h.
References casacore::TableExprFuncNode::hdmsFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::hms (const TableExprNode & node) inline
Functions for angle-values.
Defined for scalars and arrays. dhms converts pairs of values to hms and dms and only works for arrays.
Definition at line 1717 of file ExprNode.h.
References casacore::TableExprFuncNode::hmsFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::iif (const LatticeExprNode & condition, const LatticeExprNode & arg1, const LatticeExprNode & arg2)
Function resembling the ternary ?: construct in C++.
The argument "condition" has to be a Bool scalar or lattice. If an element in "condition" is True, the corresponding element from "arg1" is taken, otherwise it is taken from "arg2".
TableExprNode casacore::iif (const TableExprNode & condition, const TableExprNode & arg1, const TableExprNode & arg2) inline
Function resembling the ternary ?: construct in C++.
The argument "condition" has to be a Bool value. If an element in "condition" is True, the corresponding element from "arg1" is taken, otherwise it is taken from "arg2". The arguments can be scalars or array or any combination.
Definition at line 2155 of file ExprNode.h.
References casacore::TableExprFuncNode::iifFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::imag (const LatticeExprNode & expr)
Referenced by casacore::MakeComplexImag< L, R, RES >::operator()(), casacore::MakeComplexRealImag< L, R, RES >::operator()(), and casacore::Imag< T, RES >::operator()().
TableExprNode casacore::imag (const TableExprNode & node) inline
The imaginary part of a complex node.
Defined for scalars and arrays.
Definition at line 1588 of file ExprNode.h.
References casacore::TableExprFuncNode::imagFUNC, and casacore::TableExprNode::newFunctionNode().
DataType casacore::imagePixelType (const String & fileName)
Determine the pixel type in the PagedImage contained in fileName.
If the file doesn't appear to be a Table or cannot be opened, TpOther is returned. <group name="pixeltype")
LatticeExprNode casacore::indexin (const LatticeExprNode & axis, const LatticeExprNode & indexFlags)
2-argument function telling per pixel if its index on the given axis is contained in the 2nd argument.
The 2nd argument should be a boolean vector where True means that the index is contained. For indices >= vector_length, the 2nd argument defaults to False. Results in a Bool array.
Caution: Axes start counting at 0; If the axis is a number < 0 or >= ndim, an exception is thrown;
template<class T > void casacore::indgen (TableVector< T > & tv, Int start, Int inc) inline
Definition at line 400 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
template<class T > void casacore::indgen (TableVector< T > & tv, Int start) inline
Definition at line 403 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
template<class T > void casacore::indgen (TableVector< T > & tv) inline
Definition at line 406 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
template<class AccumType > StatsData<AccumType> casacore::initializeStatsData ()
template<class T > T casacore::innerProduct (const TableVector< T > & l, const TableVector< T > & r) inline
Definition at line 411 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
TableExprNode casacore::integer (const TableExprNode & node) inline
Convert double, bool, or string to int (using floor).
Definition at line 1592 of file ExprNode.h.
References casacore::TableExprFuncNode::intFUNC, and casacore::TableExprNode::newFunctionNode().
Bool casacore::isCArray () const
See if the pointer points to a C-array.
Definition at line 133 of file PtrHolder.h.
References isCarray_p.
TableExprNode casacore::isdefined (const TableExprNode & array) inline
Function operating on a field resulting in a bool scalar.
It can be used to test if a column has an array in the current row. It can also be used to test if a record contains a field.
Definition at line 2139 of file ExprNode.h.
References casacore::TableExprFuncNode::isdefFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::isFinite (const TableExprNode & node) inline
Function to test if a scalar or array is finite.
It results in a Bool scalar or array.
Definition at line 1794 of file ExprNode.h.
References casacore::TableExprFuncNode::isfiniteFUNC, and casacore::TableExprNode::newFunctionNode().
Referenced by casacore::IsFinite< T >::operator()().
Bool casacore::isHDF5Image (const String & fileName)
Check if this HDF5 file is an HDF5 image.
TableExprNode casacore::isInf (const TableExprNode & node) inline
Definition at line 1790 of file ExprNode.h.
References casacore::TableExprFuncNode::isinfFUNC, and casacore::TableExprNode::newFunctionNode().
Referenced by casacore::IsInf< T >::operator()().
LatticeExprNode casacore::isNaN (const LatticeExprNode & expr)
Test if a value is a NaN.
Referenced by casacore::IsNaN< T >::operator()().
TableExprNode casacore::isNaN (const TableExprNode & node) inline
Function to test if a scalar or array is NaN (not-a-number).
It results in a Bool scalar or array.
Definition at line 1786 of file ExprNode.h.
References casacore::TableExprFuncNode::isnanFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::length (const LatticeExprNode & expr, const LatticeExprNode & axis)
2-argument function to get the length of an axis.
Results in a scalar Float. The 2nd expression (giving the axis number) has to be a real scalar.
Caution: Axes start counting at 0; If the axis is a number < 0, an exception is thrown; If the axis is a number exceeding the dimensionality, 1 is returned;
Referenced by casacore::StringFITSFieldCopier::copyToFITS(), casacore::String::index(), casacore::String::length(), and casacore::ColumnSlicer::validateParameters().
LatticeExprNode casacore::log (const LatticeExprNode & expr)
Referenced by casacore::Log< T, RES >::operator()().
TableExprNode casacore::log (const TableExprNode & node) inline
Definition at line 1490 of file ExprNode.h.
References casacore::TableExprFuncNode::logFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::log10 (const LatticeExprNode & expr)
Referenced by casacore::Log10< T, RES >::operator()().
TableExprNode casacore::log10 (const TableExprNode & node) inline
Definition at line 1494 of file ExprNode.h.
References casacore::TableExprFuncNode::log10FUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::ltrim (const TableExprNode & node) inline
Definition at line 1752 of file ExprNode.h.
References casacore::TableExprFuncNode::ltrimFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::marray (const TableExprNode & array, const TableExprNode & mask) inline
Form a masked array.
Definition at line 2099 of file ExprNode.h.
References casacore::TableExprFuncNode::marrayFUNC, and casacore::TableExprNode::newFunctionNode().
Referenced by casacore::Cube< casacore::RigidVector< Double, 2 > >::operator=(), casacore::Matrix< Complex >::operator=(), and casacore::Vector< ArgType >::operator=().
LatticeExprNode casacore::mask (const LatticeExprNode & expr)
This function returns the mask of the given expression.
If it has no mask, the result is an array with all True values.
Referenced by accumulateFalse(), accumulateTrue(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath(), casacore::MArray< T >::flatten(), casacore::TableExprGroupAggr::getArray(), casacore::FitsField< FitsBit >::operator int(), casacore::FitsField< FitsBit >::operator()(), casacore::FitsField< FitsBit >::operator=(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialArrayMath(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath(), and casacore::TableExprNodeSet::toArray().
LatticeExprNode casacore::max (const LatticeExprNode & left, const LatticeExprNode & right)
Referenced by casacore::TableParseSelect::doGroupByAggrSingleKey(), casacore::ArrayPartMath_global_functions_Array_partial_operations::MaxFunc< T >::operator()(), and casacore::MaskedMaxFunc< T >::operator()().
LatticeExprNode casacore::max (const LatticeExprNode & expr)
TableExprNode casacore::max (const TableExprNode & a, const TableExprNode & b) inline
Definition at line 1580 of file ExprNode.h.
References casacore::TableExprFuncNode::maxFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::max (const TableExprNode & array) inline
Definition at line 1804 of file ExprNode.h.
References casacore::TableExprFuncNode::arrmaxFUNC, and casacore::TableExprNode::newFunctionNode().
template<class T > T casacore::max (const TableVector< T > & tv) inline
Definition at line 396 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
TableExprNode casacore::maxs (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1900 of file ExprNode.h.
References casacore::TableExprFuncNode::arrmaxsFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::mean (const LatticeExprNode & expr)
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::MeanFunc< T >::operator()(), and casacore::MaskedMeanFunc< T >::operator()().
TableExprNode casacore::mean (const TableExprNode & array) inline
Definition at line 1824 of file ExprNode.h.
References casacore::TableExprFuncNode::arrmeanFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::means (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1906 of file ExprNode.h.
References casacore::TableExprFuncNode::arrmeansFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::median (const LatticeExprNode & expr)
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::MedianFunc< T >::operator()(), and casacore::MaskedMedianFunc< T >::operator()().
TableExprNode casacore::median (const TableExprNode & array) inline
Definition at line 1849 of file ExprNode.h.
References casacore::TableExprFuncNode::arrmedianFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::medians (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1936 of file ExprNode.h.
References casacore::TableExprFuncNode::arrmediansFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::min (const LatticeExprNode & left, const LatticeExprNode & right)
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::MinFunc< T >::operator()(), casacore::MaskedMinFunc< T >::operator()(), casacore::Block< casacore::String >::resize(), and casacore::Block< casacore::String >::set_capacity().
LatticeExprNode casacore::min (const LatticeExprNode & expr)
1-argument functions operating on a numeric expression resulting in a scalar
TableExprNode casacore::min (const TableExprNode & a, const TableExprNode & b) inline
Minimum or maximum of 2 nodes.
Makes sense for numeric and String values. For Complex values the norm is compared. One or both arguments can be scalar or array.
Definition at line 1576 of file ExprNode.h.
References casacore::TableExprFuncNode::minFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::min (const TableExprNode & array) inline
Functions operating on a Double scalar or array resulting in a Double scalar.
Definition at line 1799 of file ExprNode.h.
References casacore::TableExprFuncNode::arrminFUNC, and casacore::TableExprNode::newFunctionNode().
template<class T > T casacore::min (const TableVector< T > & tv) inline
Definition at line 393 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
template<class T > void casacore::minMax (T & min, T & max, const TableVector< T > & tv) inline
Definition at line 390 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
TableExprNode casacore::mins (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1894 of file ExprNode.h.
References casacore::TableExprFuncNode::arrminsFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::mjd (const TableExprNode & node) inline
Definition at line 1671 of file ExprNode.h.
References casacore::TableExprFuncNode::mjdFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::mjdtodate (const TableExprNode & node) inline
Definition at line 1666 of file ExprNode.h.
References casacore::TableExprFuncNode::mjdtodateFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::month (const TableExprNode & node) inline
Definition at line 1683 of file ExprNode.h.
References casacore::TableExprFuncNode::monthFUNC, and casacore::TableExprNode::newFunctionNode().
Record casacore::mssSelectedIndices (MSSelection & mss, const MeasurementSet * ms)
Bool casacore::mssSetData (const MeasurementSet & ms, MeasurementSet & selectedMS, const String & outMSName = "", const String & timeExpr = "", const String & antennaExpr = "", const String & fieldExpr = "", const String & spwExpr = "", const String & uvDistExpr = "", const String & taQLExpr = "", const String & polnExpr = "", const String & scanExpr = "", const String & arrayExpr = "", const String & stateExpr = "", const String & obsExpr = "", MSSelection * mss = NULL)
Collective selection returning a selected MS.
Bool casacore::mssSetData (const MeasurementSet & ms, MeasurementSet & selectedMS, Vector< Vector< Slice > > & chanSlices, Vector< Vector< Slice > > & corrSlices, const String & outMSName = "", const String & timeExpr = "", const String & antennaExpr = "", const String & fieldExpr = "", const String & spwExpr = "", const String & uvDistExpr = "", const String & taQLExpr = "", const String & polnExpr = "", const String & scanExpr = "", const String & arrayExpr = "", const String & stateExpr = "", const String & obsExpr = "", const Int defaultChanStep = 1, MSSelection * mss = NULL)
Collective selection also returning in-row (corr/chan) slices.
Bool casacore::mssSetData2 (const MeasurementSet & ms, MeasurementSet & selectedMS, const String & outMSName = "", const String & timeExpr = "", const String & antennaExpr = "", const String & fieldExpr = "", const String & spwExpr = "", const String & uvDistExpr = "", const String & taQLExpr = "", const String & polnExpr = "", const String & scanExpr = "", const String & arrayExpr = "", const String & stateExpr = "", const String & obsExpr = "", const String & feedExpr = "", MSSelection * mss = NULL)
Added feedExpr.
Bool casacore::mssSetData2 (const MeasurementSet & ms, MeasurementSet & selectedMS, Vector< Vector< Slice > > & chanSlices, Vector< Vector< Slice > > & corrSlices, const String & outMSName = "", const String & timeExpr = "", const String & antennaExpr = "", const String & fieldExpr = "", const String & spwExpr = "", const String & uvDistExpr = "", const String & taQLExpr = "", const String & polnExpr = "", const String & scanExpr = "", const String & arrayExpr = "", const String & stateExpr = "", const String & obsExpr = "", const String & feedExpr = "", const Int defaultChanStep = 1, MSSelection * mss = NULL)
Added feedExpr.
LatticeExprNode casacore::ndim (const LatticeExprNode & expr)
1-argument function to get the dimensionality of a lattice.
0 is returned if it is a scalar. Results in a scalar Float.
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath(), and casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath().
TableExprNode casacore::ndim (const TableExprNode & array) inline
Definition at line 2147 of file ExprNode.h.
References casacore::TableExprFuncNode::ndimFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::near (const TableExprNode & left, const TableExprNode & right)
Functions to return whether a value is "relatively" near another.
Returns tol > abs(val2 - val1)/max(abs(val1),(val2)). If tol <= 0, returns val1 == val2. If either val is 0.0, takes care of area around the minimum number that can be represented.
The nearAbs functions return whether a value is "absolutely" near another. Returns tol > abs(val2 - val1). Default tolerance is 1.0e-13. They operate on scalars and arrays.
Definition at line 1401 of file ExprNode.h.
References casacore::TableExprFuncNode::near2FUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::near (const TableExprNode & left, const TableExprNode & right, const TableExprNode & tolerance) inline
Definition at line 1407 of file ExprNode.h.
References casacore::TableExprFuncNode::near3FUNC, and casacore::TableExprNode::newFunctionNode().
Bool casacore::near (const GaussianBeam & left, const GaussianBeam & other, const Double relWidthTol, const Quantity & absPaTol)
Referenced by casacore::Near< L, R >::operator()().
TableExprNode casacore::nearAbs (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1414 of file ExprNode.h.
References casacore::TableExprFuncNode::nearabs2FUNC, and casacore::TableExprNode::newFunctionNode().
Referenced by casacore::NearAbs< L, R >::operator()().
TableExprNode casacore::nearAbs (const TableExprNode & left, const TableExprNode & right, const TableExprNode & tolerance) inline
Definition at line 1420 of file ExprNode.h.
References casacore::TableExprFuncNode::nearabs3FUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::nelements (const LatticeExprNode & expr)
1-argument function to get the number of elements in a lattice.
If the lattice is masked, only the True elements are counted. Results in a scalar Double.
Referenced by casacore::TabVecRep< T >::conform().
TableExprNode casacore::nelements (const TableExprNode & array) inline
Functions operating on any scalar or array resulting in a Double scalar.
A scalar has 1 element and dimensionality 0.
Definition at line 2143 of file ExprNode.h.
References casacore::TableExprFuncNode::nelemFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::nfalse (const LatticeExprNode & expr)
Referenced by casacore::NFalseFunc< T >::operator()().
TableExprNode casacore::nfalse (const TableExprNode & array) inline
Definition at line 1872 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::nfalseFUNC.
TableExprNode casacore::nfalses (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1967 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::nfalsesFUNC.
TableExprNode casacore::norm (const TableExprNode & node) inline
Definition at line 1524 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::normFUNC.
template<class T > T casacore::norm (const TableVector< T > & tv) inline
Definition at line 414 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
Referenced by casacore::Complex_global_functions_Complex_desc::operator<(), casacore::Complex_global_functions_Complex_desc::operator<=(), casacore::Complex_global_functions_Complex_desc::operator>(), and casacore::Complex_global_functions_Complex_desc::operator>=().
LatticeExprNode casacore::ntrue (const LatticeExprNode & expr)
Referenced by casacore::NTrueFunc< T >::operator()().
TableExprNode casacore::ntrue (const TableExprNode & array) inline
Definition at line 1868 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::ntrueFUNC.
TableExprNode casacore::ntrues (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1961 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::ntruesFUNC.
LatticeExprNode casacore::operator! (const LatticeExprNode & expr)
LatticeExprNode casacore::operator!= (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator!= (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1365 of file ExprNode.h.
References casacore::TableExprNode::newNE(), and casacore::TableExprNode::node_p.
Bool casacore::operator!= (const ArrayKey & lhs, const ArrayKey & rhs) inline
Definition at line 101 of file MSKeys.h.
template<typename T > bool casacore::operator!= (const std11_allocator< T > & , const std11_allocator< T > &) inline
Definition at line 105 of file Allocator.h.
template<typename T , size_t ALIGNMENT> bool casacore::operator!= (const casacore_allocator< T, ALIGNMENT > & , const casacore_allocator< T, ALIGNMENT > &) inline
Definition at line 173 of file Allocator.h.
template<typename T > bool casacore::operator!= (const new_del_allocator< T > & , const new_del_allocator< T > &) inline
Definition at line 250 of file Allocator.h.
LatticeExprNode casacore::operator% (const LatticeExprNode & left, const LatticeExprNode & right) inline
Definition at line 842 of file LatticeExprNode.h.
References fmod().
TableExprNode casacore::operator% (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1340 of file ExprNode.h.
References casacore::TableExprNode::newModulo(), and casacore::TableExprNode::node_p.
TableExprNode casacore::operator& (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1345 of file ExprNode.h.
References casacore::TableExprNode::newBitAnd(), and casacore::TableExprNode::node_p.
LatticeExprNode casacore::operator&& (const LatticeExprNode & left, const LatticeExprNode & right)
Logical binary operators.
TableExprNode casacore::operator&& (const TableExprNode & left, const TableExprNode & right)
Logical operators to combine boolean TableExprNode's.
A null TableExprNode object is ignored, so it is possible to build up a full expression gradually.
LatticeExprNode casacore::operator* (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator* (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1330 of file ExprNode.h.
References casacore::TableExprNode::newTimes(), and casacore::TableExprNode::node_p.
MVEarthMagnetic casacore::operator* (const RotMatrix & left, const MVEarthMagnetic & right)
Rotate a EarthMagnetic vector with rotation matrix and other multiplications.
MVEarthMagnetic casacore::operator* (const MVEarthMagnetic & left, const RotMatrix & right)
MVEarthMagnetic casacore::operator* (Double left, const MVEarthMagnetic & right)
MVEarthMagnetic casacore::operator* (const MVEarthMagnetic & left, Double right)
Double casacore::operator* (const Vector< Double > & left, const MVEarthMagnetic & right)
MVDirection casacore::operator* (const RotMatrix & left, const MVDirection & right)
Rotate a position vector.
Double casacore::operator* (const MVEarthMagnetic & left, const Vector< Double > & right)
MVBaseline casacore::operator* (const RotMatrix & left, const MVBaseline & right)
Rotate a Baseline vector with rotation matrix and other multiplications.
MVDirection casacore::operator* (const MVDirection & left, const RotMatrix & right)
Double casacore::operator* (const MVPosition & left, const MVEarthMagnetic & right)
MVBaseline casacore::operator* (const MVBaseline & left, const RotMatrix & right)
Double casacore::operator* (const MVEarthMagnetic & left, const MVPosition & right)
MVBaseline casacore::operator* (Double left, const MVBaseline & right)
MVBaseline casacore::operator* (const MVBaseline & left, Double right)
MVuvw casacore::operator* (const RotMatrix & left, const MVuvw & right)
Rotate a uvw vector with rotation matrix and other multiplications.
Double casacore::operator* (const Vector< Double > & left, const MVBaseline & right)
MVuvw casacore::operator* (const MVuvw & left, const RotMatrix & right)
MVuvw casacore::operator* (Double left, const MVuvw & right)
Double casacore::operator* (const MVBaseline & left, const Vector< Double > & right)
MVuvw casacore::operator* (const MVuvw & left, Double right)
Double casacore::operator* (const MVPosition & left, const MVBaseline & right)
Double casacore::operator* (const MVBaseline & left, const MVPosition & right)
Double casacore::operator* (const Vector< Double > & left, const MVuvw & right)
Double casacore::operator* (const MVuvw & left, const Vector< Double > & right)
Double casacore::operator* (const MVPosition & left, const MVuvw & right)
Double casacore::operator* (const MVuvw & left, const MVPosition & right)
MVPosition casacore::operator* (const RotMatrix & left, const MVPosition & right)
Rotate a position vector with rotation matrix and other multiplications.
MVPosition casacore::operator* (const MVPosition & left, const RotMatrix & right)
MVPosition casacore::operator* (Double left, const MVPosition & right)
MVPosition casacore::operator* (const MVPosition & left, Double right)
Double casacore::operator* (const Vector< Double > & left, const MVPosition & right)
Double casacore::operator* (const MVPosition & left, const Vector< Double > & right)
LatticeExprNode casacore::operator+ (const LatticeExprNode & expr)
Global functions operating on a LatticeExprNode.
All global functions need to be declared as friends.
Unary functions.
LatticeExprNode casacore::operator+ (const LatticeExprNode & left, const LatticeExprNode & right)
Numerical binary operators.
TableExprNode casacore::operator+ (const TableExprNode & left, const TableExprNode & right) inline
Define all global functions operating on a TableExprNode.
Define all global functions as friends.
Arithmetic operators for numeric TableExprNode's.
is also defined for strings (means concatenation).
Definition at line 1320 of file ExprNode.h.
References casacore::TableExprNode::newPlus(), and casacore::TableExprNode::node_p.
MrsEligibility casacore::operator+ (const MrsEligibility & a, MrsEligibility::SubtableId subtableId)
MrsEligibility casacore::operator+ (const MrsEligibility & a, const MrsEligibility & b)
LatticeExprNode casacore::operator- (const LatticeExprNode & expr)
LatticeExprNode casacore::operator- (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator- (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1325 of file ExprNode.h.
References casacore::TableExprNode::newMinus(), and casacore::TableExprNode::node_p.
MrsEligibility casacore::operator- (const MrsEligibility & a, MrsEligibility::SubtableId subtableId)
Creates a new MrsEligibilitySet by adding or removing the specified subtable or the specified set of subtables.
MrsEligibility casacore::operator- (const MrsEligibility & a, const MrsEligibility & b)
T* casacore::operator-> () const
Make it possible to use -> on the pointer object.
Definition at line 129 of file PtrHolder.h.
References ptr_p.
LatticeExprNode casacore::operator/ (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator/ (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1335 of file ExprNode.h.
References casacore::TableExprNode::newDivide(), and casacore::TableExprNode::node_p.
Bool casacore::operator< (const SubScanKey & lhs, const SubScanKey & rhs)
define operator<() so it can be used as a key in std::map
Bool casacore::operator< (const ScanKey & lhs, const ScanKey & rhs)
define operator<() so it can be used as a key in std::map
LatticeExprNode casacore::operator< (const LatticeExprNode & left, const LatticeExprNode & right)
Bool casacore::operator< (const ArrayKey & lhs, const ArrayKey & rhs)
define operator<() so it can be used as a key in std::map
TableExprNode casacore::operator< (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1385 of file ExprNode.h.
References casacore::TableExprNode::newGT(), and casacore::TableExprNode::node_p.
Bool casacore::operator< (const SourceKey & lhs, const SourceKey & rhs)
define operator<() so it can be used as a key in std::map
std::ostream& casacore::operator<< (std::ostream & os, const SubScanKey & scanKey)
void casacore::operator<< (ostream & , const MultiFileInfo &)
void casacore::operator<< (AipsIO & , const MultiFileInfo &)
ostream& casacore::operator<< (ostream & os, const IComplex &)
Show on ostream.
std::ostream& casacore::operator<< (std::ostream & os, const ScanKey & scanKey)
ostream& casacore::operator<< (ostream & os, const ObjectID & id)
ostream& casacore::operator<< (ostream & os, const GaussianBeam & beam)
LogIO& casacore::operator<< (LogIO & os, const GaussianBeam & beam)
template<class T > ostream& casacore::operator<< (ostream & os, const FunctionOrder< T > & par) inline
Definition at line 162 of file FunctionOrder.h.
ostream& casacore::operator<< (ostream & os, const UnitDim & du)
Output.
Output the SI dimensions (e.g.
'km/s/g' as 'm kg-1 s-1')
template<class T > ostream& casacore::operator<< (ostream & os, const FunctionParam< T > & par) inline
Definition at line 209 of file FunctionParam.h.
std::ostream& casacore::operator<< (std::ostream & o, HeaderDataUnit & h) inline
Definition at line 223 of file hdu.h.
References casacore::HeaderDataUnit::kwlist_.
template<class T > ostream& casacore::operator<< (ostream & os, const typename StatisticsUtilities< T >::BinDesc & desc)
Definition at line 233 of file StatisticsUtilities.h.
ostream& casacore::operator<< (ostream & os, const ImageBeamSet & beamSet)
ostream& casacore::operator<< (ostream & , const FITS::ValueType &)
template<class T , class U > ostream& casacore::operator<< (ostream & os, const Function< T, U > & fun) inline
Definition at line 359 of file Function.h.
ostream& casacore::operator<< (ostream & os, const MVTime & meas)
Global functions.
Output a date/time.
Output
ostream& casacore::operator<< (ostream & os, const MVTime::Format & form)
Set a temporary format (thread-unsafe).
Set a temporary format.
AipsIO& casacore::operator<< (AipsIO & os, const Record & rec) inline
Definition at line 455 of file Record.h.
References casacore::Record::putRecord().
ostream& casacore::operator<< (ostream & os, const RecordDesc & desc) inline
Definition at line 502 of file RecordDesc.h.
References casacore::RecordDesc::put().
AipsIO& casacore::operator<< (AipsIO & os, const RecordDesc & desc) inline
Definition at line 506 of file RecordDesc.h.
References casacore::RecordDesc::put().
ostream& casacore::operator<< (ostream & , const FitsKeyword &)
ostream& casacore::operator<< (ostream & os, const SpectralCoordinate & spcoord)
std::ostream& casacore::operator<< (std::ostream & o, FitsBase & x) inline
Definition at line 870 of file hdu.h.
References casacore::FitsBase::show().
ostream& casacore::operator<< (ostream & o, FitsKeywordList &)
ostream& casacore::operator<< (ostream & s, const String & x) inline
Definition at line 1031 of file String.h.
References casacore::String::c_str().
LatticeExprNode casacore::operator<= (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator<= (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1380 of file ExprNode.h.
References casacore::TableExprNode::newGE(), and casacore::TableExprNode::node_p.
PtrHolder<T>& casacore::operator= (const PtrHolder< T > & other) private
Referenced by casacore::VectorSTLIterator< T >::operator=(), and casacore::String::operator=().
Bool casacore::operator== (const ScanKey & lhs, const ScanKey & rhs)
LatticeExprNode casacore::operator== (const LatticeExprNode & left, const LatticeExprNode & right)
Relational binary operators.
TableExprNode casacore::operator== (const TableExprNode & left, const TableExprNode & right) inline
Comparison operators.
Definition at line 1360 of file ExprNode.h.
References casacore::TableExprNode::newEQ(), and casacore::TableExprNode::node_p.
Bool casacore::operator== (const ArrayKey & lhs, const ArrayKey & rhs) inline
Definition at line 97 of file MSKeys.h.
References casacore::ArrayKey::arrayID, and casacore::ArrayKey::obsID.
template<typename T > bool casacore::operator== (const std11_allocator< T > & , const std11_allocator< T > &) inline
Definition at line 99 of file Allocator.h.
template<typename T , size_t ALIGNMENT> bool casacore::operator== (const casacore_allocator< T, ALIGNMENT > & , const casacore_allocator< T, ALIGNMENT > &) inline
Definition at line 167 of file Allocator.h.
template<typename T > bool casacore::operator== (const new_del_allocator< T > & , const new_del_allocator< T > &) inline
Definition at line 244 of file Allocator.h.
Bool casacore::operator== (const MVTime & lh, const MVTime & rh) inline
is equal operator, uses operator Double which returns days
Definition at line 456 of file MVTime.h.
LatticeExprNode casacore::operator> (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator> (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1370 of file ExprNode.h.
References casacore::TableExprNode::newGT(), and casacore::TableExprNode::node_p.
LatticeExprNode casacore::operator>= (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator>= (const TableExprNode & left, const TableExprNode & right) inline
Not defined for Bool.
Definition at line 1375 of file ExprNode.h.
References casacore::TableExprNode::newGE(), and casacore::TableExprNode::node_p.
void casacore::operator>> (AipsIO & , MultiFileInfo &)
ostream& casacore::operator>> (ostream & is, MVTime & meas)
AipsIO& casacore::operator>> (AipsIO & os, Record & rec) inline
Definition at line 465 of file Record.h.
References casacore::Record::getRecord().
AipsIO& casacore::operator>> (AipsIO & os, RecordDesc & desc) inline
Definition at line 510 of file RecordDesc.h.
References casacore::RecordDesc::get().
LatticeExprNode casacore::operator^ (const LatticeExprNode & left, const LatticeExprNode & right) inline
Definition at line 845 of file LatticeExprNode.h.
References pow().
TableExprNode casacore::operator^ (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1355 of file ExprNode.h.
References casacore::TableExprNode::newBitXor(), and casacore::TableExprNode::node_p.
TableExprNode casacore::operator| (const TableExprNode & left, const TableExprNode & right) inline
Definition at line 1350 of file ExprNode.h.
References casacore::TableExprNode::newBitOr(), and casacore::TableExprNode::node_p.
LatticeExprNode casacore::operator|| (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::operator|| (const TableExprNode & left, const TableExprNode & right)
LatticeExprNode casacore::pa (const LatticeExprNode & left, const LatticeExprNode & right)
This function finds 180/pi*atan2(left,right)/2.
This could be used to find the position of linear polarization if left and right are images of Stokes U and Q, respectively.
Referenced by casacore::SquareMatrix< T, n >::operator=().
TableExprNode casacore::pattern (const TableExprNode & node) inline
Definition at line 1651 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::patternFUNC.
TableExprNode casacore::phase (const TableExprNode & node) inline
The phase (i.e.
atan2(im, re)) of a complex node. This is a synonym for function arg. Defined for scalars and arrays.
Definition at line 1612 of file ExprNode.h.
References casacore::TableExprFuncNode::argFUNC, and casacore::TableExprNode::newFunctionNode().
void casacore::posv (const char * uplo, const int * n, const int * nrhs, float * a, const int * lda, float * b, const int * ldb, int * info) inline
Definition at line 192 of file MatrixMathLA.h.
References sposv().
void casacore::posv (const char * uplo, const int * n, const int * nrhs, double * a, const int * lda, double * b, const int * ldb, int * info) inline
Definition at line 195 of file MatrixMathLA.h.
References dposv().
void casacore::posv (const char * uplo, const int * n, const int * nrhs, Complex * a, const int * lda, Complex * b, const int * ldb, int * info) inline
Definition at line 198 of file MatrixMathLA.h.
References cposv().
void casacore::posv (const char * uplo, const int * n, const int * nrhs, DComplex * a, const int * lda, DComplex * b, const int * ldb, int * info) inline
Definition at line 201 of file MatrixMathLA.h.
References zposv().
void casacore::potri (const char * uplo, const int * n, float * a, const int * lda, int * info) inline
Definition at line 205 of file MatrixMathLA.h.
References spotri().
void casacore::potri (const char * uplo, const int * n, double * a, const int * lda, int * info) inline
Definition at line 208 of file MatrixMathLA.h.
References dpotri().
void casacore::potri (const char * uplo, const int * n, Complex * a, const int * lda, int * info) inline
Definition at line 211 of file MatrixMathLA.h.
References cpotri().
void casacore::potri (const char * uplo, const int * n, DComplex * a, const int * lda, int * info) inline
Definition at line 214 of file MatrixMathLA.h.
References zpotri().
Float casacore::pow (Float f1, Float f2) inline
Definition at line 90 of file math.h.
Referenced by casacore::Pow< T, E, RES >::operator()(), operator^(), casacore::Math_global_functions_Math_interface_for_casacore::pow(), casacore::Complex_global_functions_Complex_desc::pow(), casacore::FITS::tenD(), and casacore::FITS::tenF().
LatticeExprNode casacore::pow (const LatticeExprNode & left, const LatticeExprNode & right)
TableExprNode casacore::pow (const TableExprNode & x, const TableExprNode & exp) inline
Definition at line 1498 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::powFUNC.
template<class T > TableVector<T> casacore::pow (const TableVector< T > & tv, const double & exp) inline
Definition at line 377 of file TabVecMath.h.
References exp().
TableExprNode casacore::product (const TableExprNode & array) inline
Definition at line 1814 of file ExprNode.h.
References casacore::TableExprFuncNode::arrproductFUNC, and casacore::TableExprNode::newFunctionNode().
template<class T > T casacore::product (const TableVector< T > & tv) inline
Definition at line 385 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::ProductFunc< T >::operator()(), and casacore::MaskedProductFunc< T >::operator()().
TableExprNode casacore::products (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1882 of file ExprNode.h.
References casacore::TableExprFuncNode::arrproductsFUNC, and casacore::TableExprNode::newFunctionNode().
casacore::PtrHolder (const PtrHolder< T > & other) private
void casacore::putBlock (AipsIO & , const Block< void * > & , Int) inline
Definition at line 134 of file BlockIO.h.
const char* casacore::re_comp ()
int casacore::re_exec ()
LatticeExprNode casacore::real (const LatticeExprNode & expr)
Referenced by casacore::MakeComplexReal< L, R, RES >::operator()(), casacore::MakeComplexRealImag< L, R, RES >::operator()(), and casacore::Real< T, RES >::operator()().
TableExprNode casacore::real (const TableExprNode & node) inline
The real part of a complex node.
Defined for scalars and arrays.
Definition at line 1584 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::realFUNC.
LatticeExprNode casacore::rebin (const LatticeExprNode & expr, const LatticeExprNode & bin)
2-argument function rebinning Lattice by given factors.
The 2nd argument should be a vector (preferably Float - really Int but Int not well supported in LEL yet). Results in a T array.
TableExprNode casacore::regex (const TableExprNode & node) inline
Functions for regular expression matching and pattern matching.
Defined for scalars and arrays.
pattern is for a file name like pattern.
sqlpattern is for an SQL like pattern.
Definition at line 1647 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::regexFUNC.
TableExprNode casacore::replace (const TableExprNode & str, const TableExprNode & patt) inline
Definition at line 1773 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::replaceFUNC.
TableExprNode casacore::replace (const TableExprNode & str, const TableExprNode & patt, const TableExprNode & repl) inline
Definition at line 1779 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::replaceFUNC.
LatticeExprNode casacore::replace (const LatticeExprNode & arg1, const LatticeExprNode & arg2)
This function replaces every masked-off element in the first argument with the corresponding element from the second argument.
The first argument has to be a lattice (expression), the second can be a scalar or lattice. The mask of the first argument is not changed. If the first argument does not have a mask, this function does nothing.
Referenced by casacore::String::replace().
TableExprNode casacore::rms (const TableExprNode & array) inline
Definition at line 1844 of file ExprNode.h.
References casacore::TableExprFuncNode::arrrmsFUNC, and casacore::TableExprNode::newFunctionNode().
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::RmsFunc< T >::operator()(), and casacore::MaskedRmsFunc< T >::operator()().
TableExprNode casacore::rmss (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1930 of file ExprNode.h.
References casacore::TableExprFuncNode::arrrmssFUNC, and casacore::TableExprNode::newFunctionNode().
LatticeExprNode casacore::round (const LatticeExprNode & expr)
TableExprNode casacore::round (const TableExprNode & node) inline
Definition at line 1548 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::roundFUNC.
TableExprNode casacore::rtrim (const TableExprNode & node) inline
Definition at line 1756 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::rtrimFUNC.
TableExprNode casacore::runningAll (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2027 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runallFUNC.
TableExprNode casacore::runningAny (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2021 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runanyFUNC.
TableExprNode casacore::runningAvdev (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2003 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runavdevFUNC.
TableExprNode casacore::runningMax (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 1979 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runmaxFUNC.
TableExprNode casacore::runningMean (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 1985 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runmeanFUNC.
TableExprNode casacore::runningMedian (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2015 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runmedianFUNC.
TableExprNode casacore::runningMin (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Functions operating for each element on a box around that element.
The elements at the edges (where no full box can be made) are set to 0.
Definition at line 1973 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runminFUNC.
TableExprNode casacore::runningRms (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 2009 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runrmsFUNC.
TableExprNode casacore::runningStddev (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 1997 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runstddevFUNC.
TableExprNode casacore::runningVariance (const TableExprNode & array, const TableExprNodeSet & halfBoxWidth) inline
Definition at line 1991 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::runvarianceFUNC.
ScanKey casacore::scanKey (const SubScanKey & subScanKey) inline
create a ScanKey from a SubScanKey, just omits the SubScanKey's fieldID
Definition at line 66 of file MSKeys.h.
References casacore::SubScanKey::arrayID, casacore::ScanKey::arrayID, casacore::SubScanKey::obsID, casacore::ScanKey::obsID, casacore::SubScanKey::scan, and casacore::ScanKey::scan.
std::set<ScanKey> casacore::scanKeys (const std::set< Int > & scans, const ArrayKey & arrayKey)
construct scan keys given a set of scan numbers and an ArrayKey
std::set<Int> casacore::scanNumbers (const std::set< ScanKey > & scanKeys)
extract all the unique scan numbers from the specified scans
Vector<Int> casacore::set_intersection (const Vector< Int > & v1, const Vector< Int > & v2)
Vector<Int> casacore::set_union (const Vector< Int > & v1, const Vector< Int > & v2)
void casacore::setColumnCache (uInt tableNr, const ColumnCache &) const protected
Set the column cache to the cache of the given table.
The row numbers will be adjusted as needed.
void casacore::sgetrf (const int * m, const int * n, float * a, const int * lda, int * ipiv, int * info)
Referenced by getrf().
void casacore::sgetri (const int * m, float * a, const int * lda, const int * ipiv, float * work, const int * lwork, int * info)
Referenced by getri().
TableExprNode casacore::shape (const TableExprNode & array) inline
Function operating on any scalar or array resulting in a Double array containing the shape.
A scalar has shape [1].
Definition at line 2151 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::shapeFUNC.
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialArrayMath(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath(), ArrayCopy< T >::toArray(), ArrayCopy< Complex >::toArray(), and ArrayCopy< DComplex >::toArray().
void casacore::showBlock (AipsIO & , const Block< void * > & , Int) inline
Definition at line 138 of file BlockIO.h.
LatticeExprNode casacore::sign (const LatticeExprNode & expr)
TableExprNode casacore::sign (const TableExprNode & node) inline
Definition at line 1544 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::signFUNC.
LatticeExprNode casacore::sin (const LatticeExprNode & expr)
Numerical 1-argument functions.
Referenced by casacore::TableExprFuncNode::angdist(), and casacore::Sin< T, RES >::operator()().
TableExprNode casacore::sin (const TableExprNode & node) inline
Transcendental functions that can be applied to essentially all numeric nodes containing scalars or arrays.
Definition at line 1502 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::sinFUNC.
LatticeExprNode casacore::sinh (const LatticeExprNode & expr)
Referenced by casacore::Sinh< T, RES >::operator()().
TableExprNode casacore::sinh (const TableExprNode & node) inline
Definition at line 1506 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::sinhFUNC.
template<typename T , typename FuncType > Array<T> casacore::slidingArrayMath (const MaskedArray< T > & array, const IPosition & halfBoxSize, const FuncType & funcObj, Bool fillEdge = True)
Apply for each element in the array the given ArrayMath reduction function object to the box around that element.
The full box is 2*halfBoxSize + 1. It can be used for arrays and boxes of any dimensionality; missing halfBoxSize values are set to 1.
Example
Determine for each element in the array the median of a box with size [51,51] around that element:
Array<Float> medians = slidingArrayMath(in, IPosition(2,25,25),
MaskedMedianFunc<Float>());
This is a potentially expensive operation. On a high-end PC it took appr. 27 seconds to get the medians for an array of [1000,1000] using a halfBoxSize of [50,50].
The fillEdge argument determines how the edge is filled where no full boxes can be made. True means it is set to zero; False means that the edge is removed, thus the output array is smaller than the input array.
Note: This brute-force method of determining the medians outperforms all kinds of smart implementations; For a vector it is about as fast as class MedianSlider , for a 2D array it is much, much faster;
Referenced by casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingAlls(), casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingAnys(), casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingNFalse(), and casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingNTrue().
LatticeExprNode casacore::spectralindex (const LatticeExprNode & left, const LatticeExprNode & right)
This function finds the spectral index alpha = log(s1/s2) / log(f1/f2).
Vector<String>& casacore::split (const String & s, char delim, Vector< String > & elems)
void casacore::sposv (const char * uplo, const int * n, const int * nrhs, float * a, const int * lda, float * b, const int * ldb, int * info)
Referenced by posv().
void casacore::spotri (const char * uplo, const int * n, float * a, const int * lda, int * info)
Referenced by potri().
TableExprNode casacore::sqlpattern (const TableExprNode & node) inline
Definition at line 1656 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::sqlpatternFUNC.
LatticeExprNode casacore::sqrt (const LatticeExprNode & expr)
Referenced by casacore::LatticeStatistics< T >::_rms(), casacore::Sqrt< T, RES >::operator()(), casacore::ArrayPartMath_global_functions_Array_partial_operations::partialStddevs(), casacore::VanVleck::predictN3(), casacore::VanVleck::threshN3(), and casacore::ZScoreCalculator::zscoreToNpts().
TableExprNode casacore::sqrt (const TableExprNode & node) inline
Definition at line 1520 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::sqrtFUNC.
TableExprNode casacore::square (const TableExprNode & node) inline
Definition at line 1510 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::squareFUNC.
template<typename T , typename U > CountedPtr<T> casacore::static_pointer_cast (const CountedPtr< U > & that)
Cast the CountedPtr from one pointer type to another.
Definition at line 265 of file CountedPtr.h.
LatticeExprNode casacore::stddev (const LatticeExprNode & expr)
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::StddevFunc< T >::operator()(), and casacore::MaskedStddevFunc< T >::operator()().
TableExprNode casacore::stddev (const TableExprNode & array) inline
Definition at line 1834 of file ExprNode.h.
References casacore::TableExprFuncNode::arrstddevFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::stddevs (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1918 of file ExprNode.h.
References casacore::TableExprFuncNode::arrstddevsFUNC, and casacore::TableExprNode::newFunctionNode().
String casacore::stripWhite (const String & str, Bool onlyends = True)
TableExprNode casacore::strlength (const TableExprNode & node) inline
String functions on scalars or arrays.
Definition at line 1627 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::strlengthFUNC.
TableExprNode casacore::substr (const TableExprNode & str, const TableExprNode & pos) inline
Definition at line 1760 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::substrFUNC.
TableExprNode casacore::substr (const TableExprNode & str, const TableExprNode & pos, const TableExprNode & npos) inline
Definition at line 1766 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::substrFUNC.
LatticeExprNode casacore::sum (const LatticeExprNode & expr)
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::SumFunc< T >::operator()(), and casacore::MaskedSumFunc< T >::operator()().
TableExprNode casacore::sum (const TableExprNode & array) inline
Functions operating on a Double or Complex scalar or array resulting in a scalar with the same data type.
Definition at line 1809 of file ExprNode.h.
References casacore::TableExprFuncNode::arrsumFUNC, and casacore::TableExprNode::newFunctionNode().
template<class T > T casacore::sum (const TableVector< T > & tv) inline
Definition at line 382 of file TabVecMath.h.
References casacore::TableVector< T >::tabVec().
TableExprNode casacore::sums (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
The partial version of the functions above.
They are applied to the array subsets defined by the axes in the set using the partialXXX functions in ArrayMath. The axes must be 0-relative.
Definition at line 1876 of file ExprNode.h.
References casacore::TableExprFuncNode::arrsumsFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::sumSquare (const TableExprNode & array) inline
Definition at line 1819 of file ExprNode.h.
References casacore::TableExprFuncNode::arrsumsqrFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::sumSquares (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1888 of file ExprNode.h.
References casacore::TableExprFuncNode::arrsumsqrsFUNC, and casacore::TableExprNode::newFunctionNode().
TaQLResult casacore::tableCommand (const String & command)
Synopsis
Parse and execute the given command. It will open (and close) all tables needed. It returns the resulting table. The command type (select or update) and the selected or updated column names can be returned. Zero or more temporary tables can be used in the command using the $nnn syntax.
TaQLResult casacore::tableCommand (const String & command, const Table & tempTable)
TaQLResult casacore::tableCommand (const String & command, const std::vector< const Table * > & tempTables)
TaQLResult casacore::tableCommand (const String & command, Vector< String > & columnNames)
TaQLResult casacore::tableCommand (const String & command, Vector< String > & columnNames, String & commandType)
TaQLResult casacore::tableCommand (const String & command, const std::vector< const Table * > & tempTables, Vector< String > & columnNames)
TaQLResult casacore::tableCommand (const String & command, const std::vector< const Table * > & tempTables, Vector< String > & columnNames, String & commandType)
LatticeExprNode casacore::tan (const LatticeExprNode & expr)
Referenced by casacore::Tan< T, RES >::operator()().
TableExprNode casacore::tan (const TableExprNode & node) inline
Definition at line 1568 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::tanFUNC.
LatticeExprNode casacore::tanh (const LatticeExprNode & expr)
Referenced by casacore::Tanh< T, RES >::operator()().
TableExprNode casacore::tanh (const TableExprNode & node) inline
Definition at line 1572 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::tanhFUNC.
void casacore::throw_empty_Stack_error (const char * msg = 0)
Referenced by casacore::Stack< elem >::pop(), casacore::Stack< elem >::popVal(), and casacore::Stack< elem >::top().
void casacore::throw_hashmapiter_init_error ()
Referenced by casacore::HashMapIter< key, val >::operator=().
void casacore::throw_invalid_hashmapiter_error ()
Referenced by casacore::HashMapIter< key, val >::clear(), casacore::ConstHashMapIter< key, val >::container(), casacore::HashMapIter< key, val >::container(), casacore::ConstHashMapIter< key, val >::defaultVal(), casacore::HashMapIter< key, val >::defaultVal(), casacore::HashMapIter< key, val >::define(), casacore::ConstHashMapIter< key, val >::isDefined(), casacore::ConstHashMapIter< key, val >::ndefined(), casacore::ConstHashMapIter< key, val >::operator()(), casacore::HashMapIter< key, val >::operator()(), and casacore::HashMapIter< key, val >::remove().
void casacore::throw_invalid_mapiter_error ()
Referenced by casacore::MapIter< key, value >::clear(), casacore::MapIter< key, value >::defaultVal(), casacore::MapIter< key, value >::define(), casacore::MapIter< key, value >::isDefined(), casacore::MapIter< key, value >::operator()(), and casacore::MapIter< key, value >::remove().
void casacore::throw_list_end_error ()
The function which throws an exception for advancing the internal cursor past the end of a list.
Referenced by casacore::ConstListIter< casacore::OrderedPair< key, val > >::getRight(), casacore::ListIter< casacore::OrderedPair< key, val > >::getRight(), and casacore::ConstListIter< casacore::OrderedPair< key, val > >::operator++().
void casacore::throw_list_init_error ()
void casacore::throw_list_start_error ()
Referenced by casacore::ConstListIter< casacore::OrderedPair< key, val > >::operator--().
void casacore::throw_list_swapright_same_error ()
void casacore::throw_map_constop_error ()
void casacore::throw_map_init_error ()
void casacore::throw_mapiter_init_error ()
Referenced by casacore::MapIter< key, value >::operator=().
void casacore::throwInvHDF5 ()
Define 2 functions to check that hid_t and hsize_t are mapped correctly.
They are called by the constructor, so the compiler will scream if incorrect.
Referenced by check_hid_t(), and check_hsize_t().
TableExprNode casacore::time (const TableExprNode & node) inline
Definition at line 1744 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::timeFUNC.
Referenced by casacore::PrecTimer::start(), and casacore::PrecTimer::stop().
LatticeExprNode casacore::toBool (const LatticeExprNode & expr)
Referenced by convertType().
LatticeExprNode casacore::toComplex (const LatticeExprNode & expr)
Referenced by convertType().
LatticeExprNode casacore::toDComplex (const LatticeExprNode & expr)
Referenced by convertType().
LatticeExprNode casacore::toDouble (const LatticeExprNode & expr)
Referenced by convertType().
LatticeExprNode casacore::toFloat (const LatticeExprNode & expr)
Functions to convert to the given data type.
These are mostly meaningful for down-conversions (e.g. double to float), since up-conversions are automatically done to get matching data types when needed. Note that some conversions are not supported, such as Complex to Double or Float.
The conversion to Bool is useful to convert a region to a boolean lattice, which is only possible if the region is given in world coordinates. Otherwise an exception is thrown.
Referenced by convertType().
int casacore::tokenize (const String & str, const String & sep, Vector< String > & tokens, Bool upCase = False)
template<class AccumType > Record casacore::toRecord (const StatsData< AccumType > & stats)
String casacore::toString (const SubScanKey & subScanKey)
Referenced by casacore::ColumnSlicer::validateParameters().
String casacore::toString (const ScanKey & scanKey)
TableExprNode casacore::toString (const TableExprNode & node) inline
Function to convert any value to a string.
See TaQL note 199 for possible format values.
Definition at line 1729 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::stringFUNC.
TableExprNode casacore::toString (const TableExprNode & node, const TableExprNode & format) inline
Definition at line 1734 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::stringFUNC.
template<typename InputIterator1 , typename InputIterator2 , typename BinaryOperator > void casacore::transformInPlace (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, BinaryOperator op) inline
Define a function to do a binary transform in place.
It is functionally equivalent to std::transform where the first and result iterator are the same, but it is faster for non-trivial iterators.
Definition at line 44 of file Functors.h.
Referenced by casacore::ArrayMath_global_functions_Array_mathematical_operations::arrayTransformInPlace().
template<typename InputIterator1 , typename UnaryOperator > void casacore::transformInPlace (InputIterator1 first1, InputIterator1 last1, UnaryOperator op) inline
Define a function to do a unary transform in place.
It is functionally equivalent to std::transform where the first and result iterator are the same, but it is faster for non-trivial iterators.
Definition at line 56 of file Functors.h.
TableExprNode casacore::transpose (const TableExprNode & array) inline
Transpose all axes of a (masked) array.
Needs an empty axes argument.
Needs an empty axes argument.
Definition at line 2120 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::transposeFUNC.
TableExprNode casacore::transpose (const TableExprNode & array, const TableExprNode & axes)
Transpose a (masked) array by making the given axes the first axes.
TableExprNode casacore::transpose (const TableExprNode & array, const TableExprNodeSet & axes) inline
Definition at line 2127 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::transposeFUNC.
TableExprNode casacore::trim (const TableExprNode & node) inline
Definition at line 1748 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::trimFUNC.
Referenced by casacore::Trim::operator()().
std::set<ArrayKey> casacore::uniqueArrayKeys (const std::set< ScanKey > & scanKeys)
get a set of unique ArrayKeys from a set of ScanKeys
TableExprNode casacore::upcase (const TableExprNode & node) inline
Definition at line 1632 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::upcaseFUNC.
Referenced by casacore::Upcase::operator()().
LatticeExprNode casacore::value (const LatticeExprNode & expr)
This function returns the value of the expression without a mask.
Referenced by casacore::MArrayLogical_global_functions_MArray_logical_operations::allEQ(), casacore::MArrayLogical_global_functions_MArray_logical_operations::anyEQ(), casacore::python::casa_string_from_python_str::construct(), casacore::new_del_allocator< T >::construct(), casacore::String::fromString(), casacore::ScalarColumn< casacore::String >::get(), casacore::ValType::get(), casacore::TableExprNodeRep::get(), casacore::ScalarColumn< casacore::String >::operator()(), casacore::ValType::put(), casacore::HDF5Record::readArr(), casacore::HDF5Record::readSca(), casacore::Block< casacore::String >::replaceStorage(), casacore::PowerLogarithmicPolynomialParam< AutoDiff< T > >::setCoefficient(), casacore::EvenPolynomialParam< AutoDiff< T > >::setCoefficient(), casacore::OddPolynomialParam< AutoDiff< T > >::setCoefficient(), casacore::PolynomialParam< AutoDiff< T > >::setCoefficient(), casacore::SPolynomialParam< T >::setCoefficient(), casacore::String::toString(), casacore::HDF5Record::writeArr(), and casacore::HDF5Record::writeSca().
LatticeExprNode casacore::variance (const LatticeExprNode & expr)
Referenced by casacore::ArrayPartMath_global_functions_Array_partial_operations::VarianceFunc< T >::operator()(), and casacore::MaskedVarianceFunc< T >::operator()().
TableExprNode casacore::variance (const TableExprNode & array) inline
Definition at line 1829 of file ExprNode.h.
References casacore::TableExprFuncNode::arrvarianceFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::variances (const TableExprNode & array, const TableExprNodeSet & collapseAxes) inline
Definition at line 1912 of file ExprNode.h.
References casacore::TableExprFuncNode::arrvariancesFUNC, and casacore::TableExprNode::newFunctionNode().
TableExprNode casacore::week (const TableExprNode & node) inline
Definition at line 1740 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::weekFUNC.
TableExprNode casacore::weekday (const TableExprNode & node) inline
Definition at line 1696 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::weekdayFUNC.
TableExprNode casacore::year (const TableExprNode & node) inline
Definition at line 1679 of file ExprNode.h.
References casacore::TableExprNode::newFunctionNode(), and casacore::TableExprFuncNode::yearFUNC.
void casacore::zgetrf (const int * m, const int * n, DComplex * a, const int * lda, int * ipiv, int * info)
Referenced by getrf().
void casacore::zgetri (const int * m, DComplex * a, const int * lda, const int * ipiv, DComplex * work, const int * lwork, int * info)
Referenced by getri().
void casacore::zposv (const char * uplo, const int * n, const int * nrhs, DComplex * a, const int * lda, DComplex * b, const int * ldb, int * info)
Referenced by posv().
void casacore::zpotri (const char * uplo, const int * n, DComplex * a, const int * lda, int * info)
Referenced by potri().
Variable Documentation
Bool casacore::_doMedAbsDevMed
Definition at line 645 of file ConstrainedRangeStatistics.h.
CountedPtr<std::pair<AccumType, AccumType> > casacore::_range
Definition at line 644 of file ConstrainedRangeStatistics.h.
Referenced by _setRange().
Bool casacore::aips_debug_on
If AIPS_DEBUG is not defined, then the symbol expands to (0) which in an if should be removed by the dead code eliminator of any optimizer; thus using this in your code should have no performance penalty in the normal case.
If compiled with AIPS_DEBUG, then aips_debug is (defined to) a global boolean variable (so it can be turned on and off in a debugger) which is initialized to True.
ColumnCache casacore::colCache_p mutable
Definition at line 290 of file ConcatColumn.h.
const Double casacore::DER_INTV
Interval (m) for derivatives in IGRF model.
Definition at line 45 of file EarthField.h.
const String casacore::EmptyString static
Warning: SUN compiler does not accept non-simple default arguments
Definition at line 47 of file UnitName.h.
const Bool casacore::False
Definition at line 44 of file aipstype.h.
Referenced by casacore::LatticeStatistics< T >::_canDoFlux(), casacore::MArrayLogical_global_functions_MArray_logical_operations::allEQ(), anyEQ(), casacore::MArrayLogical_global_functions_MArray_logical_operations::anyEQ(), anyGE(), anyGT(), anyLE(), anyLT(), anyNE(), areEQ(), casacore::ConcatTable::asTable(), casacore::ConstListIter< casacore::OrderedPair< key, val > >::atEnd(), casacore::ConstListIter< casacore::OrderedPair< key, val > >::atStart(), casacore::HostInfo::bigEndian(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedFractiles(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedMedians(), casacore::MArrayMathBase_global_functions_Array_basic_functions::compareAllLeftMasked(), casacore::MArrayMathBase_global_functions_Array_basic_functions::compareAllMasked(), casacore::MArrayMathBase_global_functions_Array_basic_functions::compareAllRightMasked(), casacore::MArrayMathBase_global_functions_Array_basic_functions::compareAnyLeftMasked(), casacore::MArrayMathBase_global_functions_Array_basic_functions::compareAnyMasked(), casacore::MArrayMathBase_global_functions_Array_basic_functions::compareAnyRightMasked(), casacore::TabVecRep< T >::conform(), casacore::Input::debug(), casacore::UDFBase::disableApplySelection(), casacore::Stack< elem >::empty(), casacore::HashMap< key, val >::empty(), casacore::MArray< casacore::String >::fill(), casacore::FITSExtInfo::FITSExtInfo(), casacore::String::fromString(), casacore::TableExprGroupAggr::getArray(), casacore::FITSImgParser::has_qualityimg(), casacore::FITSTabular::hasChanged(), casacore::Fit2D::includeIt(), casacore::NoticeTarget::invalidate(), casacore::FITS::isa_digit(), casacore::FITS::isa_letter(), casacore::FITS::isa_text(), casacore::NoticeTarget::isAttached(), casacore::FitsLogical::isdefined(), casacore::FitsKeywordList::isempty(), casacore::FitsKeyword::isindexed(), casacore::TableColumn::isNull(), casacore::TableVector< T >::isNull(), casacore::TableIterator::isNull(), casacore::TableMeasRefDesc::isOffsetArray(), casacore::TableMeasRefDesc::isOffsetVariable(), casacore::FitsKeyword::isreserved(), casacore::COWPtr< T >::isUnique(), casacore::SetupNewTableRep::isUsed(), casacore::ConstHashMapIter< key, val >::isValid(), casacore::ArrayMath_global_functions_Array_mathematical_operations::madfm(), makeArray(), casacore::MArray< casacore::String >::MArray(), casacore::ArrayMath_global_functions_Array_mathematical_operations::median(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::median(), casacore::HeaderDataUnit::notnull(), casacore::FitsLogical::operator Bool(), casacore::CountedPtr< casacore::Block< Float > >::operator!=(), casacore::Complex_global_functions_Complex_desc::operator<(), casacore::Block< casacore::String >::operator=(), casacore::Complex_global_functions_Complex_desc::operator>(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialArrayMath(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialFractiles(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialMedians(), casacore::TableIterator::pastEnd(), casacore::Block< casacore::String >::permitChangingAllocator(), casacore::python::numpy::PycArrayCheck(), casacore::AutoDiff< T >::release(), casacore::FITSTabular::reopen(), casacore::FITSTimedTable::resetChangedFlag(), casacore::FITSMultiTable::resetChangedFlag(), casacore::Block< casacore::String >::resize(), casacore::ImageInterface< Complex >::roAttrHandler(), casacore::GenericL2Fit< DComplex >::setConstraint(), casacore::COWPtr< T >::setReadOnly(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingFractiles(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingMedians(), casacore::RegionHandlerTable::table(), casacore::TableParse::test(), casacore::TableExprNodeSet::toArray(), casacore::Function< T, T >::unlockParam(), casacore::MSTable< MSPointingEnums::PredefinedColumns, MSPointingEnums::PredefinedKeywords >::validate(), and casacore::MultiFileBase::writeDirty().
const Double casacore::IAU_k
Definition at line 51 of file UnitMap.h.
Bool casacore::isCarray_p
Definition at line 149 of file PtrHolder.h.
Referenced by isCArray().
TableRecord casacore::keywordSet_p
Definition at line 291 of file ConcatColumn.h.
class casacore::CasarcCleanup casacore::local_cleanup_object static
const uInt casacore::N_FITS
Number of FITS units recognised (change the FITSstring and FITSunit lists in the UnitMap.cc when changing this number.
Definition at line 54 of file UnitMap.h.
int casacore::obscure_syntax
const Int casacore::PQ_LEN
Length of P and Q arrays, half length of CL/SL arrays in IGRF model.
Definition at line 43 of file EarthField.h.
T* casacore::ptr_p
Definition at line 147 of file PtrHolder.h.
Referenced by casacore::ArrayAccessor< T, Axis< U > >::index(), casacore::ArrayAccessor_RT< T, AxisN >::index(), casacore::ArrayAccessor< T, Axis< U > >::initStep(), casacore::ArrayAccessor_RT< T, AxisN >::initStep(), casacore::ArrayAccessor< T, Axis< U > >::next(), casacore::ArrayAccessor_RT< T, AxisN >::next(), casacore::PtrHolder< T >::operator T *(), casacore::ArrayAccessor< T, Axis< U > >::operator!=(), casacore::ArrayAccessor_RT< T, AxisN >::operator!=(), operator->(), casacore::ArrayAccessor< T, Axis< U > >::operator==(), casacore::ArrayAccessor_RT< T, AxisN >::operator==(), casacore::ArrayAccessor< T, Axis< U > >::prev(), casacore::ArrayAccessor_RT< T, AxisN >::prev(), casacore::PtrHolder< casacore::Function< T > >::ptr(), casacore::ArrayAccessor< T, Axis< U > >::reset(), and casacore::ArrayAccessor_RT< T, AxisN >::reset().
Block<BaseColumn*> casacore::refColPtr_p
Definition at line 289 of file ConcatColumn.h.
ConcatTable* casacore::refTabPtr_p
Definition at line 288 of file ConcatColumn.h.
const Regex casacore::RXalpha
const Regex casacore::RXalphanum
const Regex casacore::RXdouble
const Regex casacore::RXidentifier
const Regex casacore::RXint
const Regex casacore::RXlowercase
const Regex casacore::RXuppercase
const Regex casacore::RXwhite
some built in regular expressions
const Bool casacore::True
Definition at line 43 of file aipstype.h.
Referenced by casacore::MedianSlider::add(), casacore::MArrayLogical_global_functions_MArray_logical_operations::allTrue(), casacore::ArrayLogical_global_functions_Array_logical_operations::allTrue(), anyEQ(), anyGE(), anyGT(), anyLE(), anyLT(), anyNE(), casacore::MArrayLogical_global_functions_MArray_logical_operations::anyTrue(), casacore::ArrayLogical_global_functions_Array_logical_operations::anyTrue(), areEQ(), casacore::ConstListIter< casacore::OrderedPair< key, val > >::atEnd(), casacore::ConstListIter< casacore::OrderedPair< key, val > >::atStart(), casacore::HostInfo::bigEndian(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath(), casacore::StatsTiledCollapser< T, U >::canHandleNullMask(), canImport(), casacore::LockFile::canLock(), casacore::MSFlagger::clearDataBuffer(), casacore::CombiFunction< T >::cloneNonAD(), casacore::CompoundFunction< casacore::AutoDiff< Double > >::cloneNonAD(), casacore::CombiFunction_PS< AutoDiff< T > >::cloneNonAD(), casacore::CompoundFunction_PS< AutoDiff< T > >::cloneNonAD(), casacore::TabVecRep< T >::conform(), countedPtrShared(), casacore::Input::debug(), casacore::BaseTable::doNotWrite(), casacore::Stack< elem >::empty(), casacore::HashMap< key, val >::empty(), casacore::FitsLogical::FitsLogical(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::fractile(), casacore::String::fromString(), casacore::TableExprGroupAggr::getArray(), casacore::ConcatRowsIter::getChunk(), casacore::PagedArray< T >::getRWArray(), casacore::BucketMapped::getrwBucket(), casacore::FITSImgParser::has_qualityimg(), casacore::TableLockData::hasLock(), casacore::LockFile::hasLock(), casacore::Fit2D::includeIt(), casacore::FITS::isa_digit(), casacore::FITS::isa_letter(), casacore::FITS::isa_text(), casacore::NoticeTarget::isAttached(), casacore::FitsLogical::isdefined(), casacore::FitsKeywordList::isempty(), casacore::FitsKeyword::isindexed(), casacore::MSInterface::isMS(), casacore::TableColumn::isNull(), casacore::TableVector< T >::isNull(), casacore::TableIterator::isNull(), casacore::Table::isNull(), casacore::Time::ISODate(), casacore::FitsKeyword::isreserved(), casacore::COWPtr< T >::isUnique(), casacore::SetupNewTableRep::isUsed(), casacore::ConstHashMapIter< key, val >::isValid(), casacore::TempLatticeImpl< T >::isWritable(), casacore::Function< T, T >::lockParam(), casacore::ArrayMath_global_functions_Array_mathematical_operations::madfmInPlace(), casacore::Table::markForDelete(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::median(), casacore::ArrayMath_global_functions_Array_mathematical_operations::medianInPlace(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::medianInPlace(), casacore::HeaderDataUnit::notnull(), casacore::FitsLogical::operator Bool(), casacore::CountedPtr< casacore::Block< Float > >::operator!=(), casacore::Complex_global_functions_Complex_desc::operator<=(), casacore::FitsLogical::operator=(), casacore::Block< casacore::String >::operator=(), casacore::Complex_global_functions_Complex_desc::operator>=(), casacore::Function< T, T >::parameters(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialArrayMath(), casacore::TableIterator::pastEnd(), casacore::Block< casacore::String >::prohibitChangingAllocator(), casacore::StManArrayFile::put(), casacore::AutoDiff< T >::ref(), casacore::Block< casacore::String >::remove(), casacore::LatticeHistograms< T >::resetError(), casacore::LatticeStatistics< T >::resetError(), casacore::Block< casacore::String >::resize(), casacore::RegionHandlerTable::rwTable(), casacore::TaQLQueryNodeRep::setBrackets(), casacore::TiledFileAccess::setCacheSize(), casacore::MSAntennaParse::setComplexity(), casacore::TiledStMan::setDataChanged(), casacore::DataManagerColumn::setFixedShapeColumn(), casacore::TaQLQueryNodeRep::setFromExecute(), casacore::StManAipsIO::setHasPut(), casacore::TaQLMultiNodeRep::setIsSetOrArray(), casacore::TaQLConstNodeRep::setIsTableName(), casacore::TaQLQueryNodeRep::setNoExecute(), casacore::COWPtr< T >::setReadOnly(), casacore::TableAttr::setRW(), casacore::FiledesIO::setWritable(), casacore::BucketBase::setWritten(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath(), casacore::LatticeCleaner< T >::stopAtLargeScaleNegative(), casacore::TableParse::test(), casacore::TableExprNodeSet::toArray(), and casacore::Table::unmarkForDelete().
const uInt casacore::WORDSIZE
The size of a unsigned Integer (assumes 8-bit char)
Definition at line 43 of file BitVector.h.
Referenced by casacore::BitVector::clearBit(), and casacore::BitVector::setBit().