casacore: casacore::MArrayLogical_global_functions_MArray_logical_operations Struct Reference
casacore::MArrayLogical_global_functions_MArray_logical_operations Struct Reference
tables package (libcasa_tables) » TaQL_module
Logical operations for MArray objects.
#include <MArrayLogical.h>
Classes
class MAllFunc
class MAnyFunc
class MNFalseFunc
class MNTrueFunc
Define functors to perform a reduction function on an MArray object.
Public Member Functions
template<typename T >
MArray< Bool > operator== (const MArray< T > &left, const MArray< T > &right)
Define comparison functions between 2 MArray objects and between MArray object and scalar.
template<typename T >
MArray< Bool > operator<= (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator< (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator>= (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator> (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator!= (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator|| (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator && (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator== (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator<= (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator< (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator>= (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator> (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator!= (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator|| (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator && (const MArray< T > &left, const T &right)
template<typename T >
MArray< Bool > operator== (const T &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator<= (const T &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator< (const T &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator>= (const T &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator> (const T &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator!= (const T &left, const MArray< T > &right)
template<typename T >
MArray< Bool > operator|| (const T &left, const MArray< T > &right)
The logical OR of 2 MArray objects (normally Bool type)
template<typename T >
MArray< Bool > operator && (const T &left, const MArray< T > &right)
The logical AND of 2 MArray objects (normally Bool type).
template<typename T >
MArray< Bool > operator! (const MArray< T > &a)
The logical NOT of an MArray object (normally Bool type).
template<typename T >
MArray< Bool > near (const MArray< T > &left, const MArray< T > &right, Double tol)
Compare with a given relative or absolute tolerance.
template<typename T >
MArray< Bool > nearAbs (const MArray< T > &left, const MArray< T > &right, Double tol)
template<typename T >
MArray< Bool > near (const MArray< T > &left, const T &right, Double tol)
template<typename T >
MArray< Bool > nearAbs (const MArray< T > &left, const T &right, Double tol)
template<typename T >
MArray< Bool > near (const T &left, const MArray< T > &right, Double tol)
template<typename T >
MArray< Bool > nearAbs (const T &left, const MArray< T > &right, Double tol)
template<typename T >
MArray< Bool > isNaN (const MArray< T > &arr)
Test which elements are NaN.
template<typename T >
MArray< Bool > isInf (const MArray< T > &arr)
Test which elements are infinite.
template<typename T >
MArray< Bool > isFinite (const MArray< T > &arr)
Test which elements have a finite value.
template<typename T >
Bool allEQ (const MArray< T > &left, const MArray< T > &right)
Are all unmasked elements equal? The result is True if there are no unmasked elements.
template<typename T >
Bool allEQ (const MArray< T > &array, const T &value)
template<typename T >
Bool allEQ (const T &value, const MArray< T > &array)
template<typename T >
Bool anyEQ (const MArray< T > &left, const MArray< T > &right)
Is any unmasked element equal? The result is False if there are no unmasked elements.
template<typename T >
Bool anyEQ (const MArray< T > &array, const T &value)
template<typename T >
Bool anyEQ (const T &value, const MArray< T > &array)
Bool allTrue (const MArray< Bool > &array)
Are all unmasked elements true?
Bool anyTrue (const MArray< Bool > &array)
Is any unmasked element true?
template<typename T >
size_t ntrue (const MArray< T > &a)
Count the number of unmasked elements that are True.
template<typename T >
size_t nfalse (const MArray< T > &a)
Count the number of unmasked elements that are False.
template<typename T >
MArray< uInt > partialNTrue (const MArray< T > &a, const IPosition &collapseAxes)
Get partial ntrues.
template<typename T >
MArray< uInt > partialNFalse (const MArray< T > &a, const IPosition &collapseAxes)
Get partial nfalses.
template<typename T >
MArray< Bool > partialAlls (const MArray< T > &a, const IPosition &collapseAxes)
Get partial all.
template<typename T >
MArray< Bool > partialAnys (const MArray< T > &a, const IPosition &collapseAxes)
Get partial any.
template<typename T >
MArray< uInt > slidingNTrue (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
Get sliding ntrues.
template<typename T >
MArray< uInt > slidingNFalse (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
Get sliding nfalses.
template<typename T >
MArray< Bool > slidingAlls (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
Get sliding all.
template<typename T >
MArray< Bool > slidingAnys (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
Get sliding any.
template<typename T >
MArray< uInt > boxedNTrue (const MArray< T > &a, const IPosition &boxSize)
Get boxed ntrues.
template<typename T >
MArray< uInt > boxedNFalse (const MArray< T > &a, const IPosition &boxSize)
Get boxed nfalses.
template<typename T >
MArray< Bool > boxedAlls (const MArray< T > &a, const IPosition &boxSize)
Get boxed all.
template<typename T >
MArray< Bool > boxedAnys (const MArray< T > &a, const IPosition &boxSize)
Get boxed any.
Detailed Description
Logical operations for MArray objects.
Review Status
Reviewed By:
UNKNOWN
Test programs:
tMArrayMath
Prerequisite
MArray
Synopsis
These functions perform element by element logical operations on optionally masked arrays and/or scalars. If two arrays are used, the arrays must conform, except for allEQ which returns False if the arrays do not conform.
The functions in this file can be divided in 3 groups:
Full array operations like ==, near, etc. They are defined for array-array and array-scalar operations. Arrays shapes have to be conformant. They operate on all elements (also the masked ones). The result is an MArray with the same shape as the input array(s). It will have a mask if one of the operands has a mask. If both operands have a mask, the resulting mask is the OR of both masks.
Full reduction functions like ntrue, all, allEQ, etc. They operate on the unmasked elements only. If there are no unmasked elements, the results is 0 or True.
Reduction functions working on unmasked elements in parts of the input array. The result is an MArray that has a mask if the input array has a mask. An output element is masked off if its input part has no unmasked elements. The functors defined at the beginning of this file are used to operate on each part. There are 3 flavours:
partialXXX reduces one or more axes. E.g. one can count the number of True elements for particular array axes. The result is an array with a lower dimensionality. They can be seen as a special versions of the boxedXXX functions.
slidingXXX operates in a sliding window over the array. So the result is an array with the same shape as the input, although the output array is smaller if the edge is not filled.
boxedXXX divides the input array in boxes with the given size and operates on each box. The result is an array with the same dimensionality, but with a smaller size. If the box size does not fit integrally, the edge box is smaller.
Definition at line 92 of file MArrayLogical.h.
Member Function Documentation
allEQ() [1/3]
template<typename T > Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::allEQ (const MArray< T > & left, const MArray< T > & right) inline
Are all unmasked elements equal? The result is True if there are no unmasked elements.
Definition at line 302 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::False, casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and casacore::MArrayBase::mask().
Referenced by allEQ(), and allTrue().
allEQ() [2/3]
template<typename T > Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::allEQ (const MArray< T > & array, const T & value) inline
Definition at line 323 of file MArrayLogical.h.
References allEQ(), casacore::array(), casacore::False, casacore::TableExprNode::isNull(), and casacore::value().
allEQ() [3/3]
template<typename T > Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::allEQ (const T & value, const MArray< T > & array) inline
Definition at line 331 of file MArrayLogical.h.
References allEQ(), casacore::array(), and casacore::value().
allTrue()
Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::allTrue (const MArray< Bool > & array) inline
Are all unmasked elements true?
Definition at line 373 of file MArrayLogical.h.
References allEQ(), casacore::array(), and casacore::True.
Referenced by casacore::MArrayLogical_global_functions_MArray_logical_operations::MAllFunc< T >::operator()().
anyEQ() [1/3]
template<typename T > Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::anyEQ (const MArray< T > & left, const MArray< T > & right) inline
Is any unmasked element equal? The result is False if there are no unmasked elements.
Definition at line 339 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::False, casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and casacore::MArrayBase::mask().
Referenced by anyEQ(), and anyTrue().
anyEQ() [2/3]
template<typename T > Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::anyEQ (const MArray< T > & array, const T & value) inline
Definition at line 360 of file MArrayLogical.h.
References anyEQ(), casacore::array(), casacore::False, casacore::TableExprNode::isNull(), and casacore::value().
anyEQ() [3/3]
template<typename T > Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::anyEQ (const T & value, const MArray< T > & array) inline
Definition at line 368 of file MArrayLogical.h.
References anyEQ(), casacore::array(), and casacore::value().
anyTrue()
Bool casacore::MArrayLogical_global_functions_MArray_logical_operations::anyTrue (const MArray< Bool > & array) inline
Is any unmasked element true?
Definition at line 377 of file MArrayLogical.h.
References anyEQ(), casacore::array(), and casacore::True.
Referenced by casacore::MArrayLogical_global_functions_MArray_logical_operations::MAnyFunc< T >::operator()().
boxedAlls()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedAlls (const MArray< T > & a, const IPosition & boxSize) inline
Get boxed all.
Definition at line 571 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedAnys()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedAnys (const MArray< T > & a, const IPosition & boxSize) inline
Get boxed any.
Definition at line 587 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedNFalse()
template<typename T > MArray<uInt> casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedNFalse (const MArray< T > & a, const IPosition & boxSize) inline
Get boxed nfalses.
Definition at line 555 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedNTrue()
template<typename T > MArray<uInt> casacore::MArrayLogical_global_functions_MArray_logical_operations::boxedNTrue (const MArray< T > & a, const IPosition & boxSize) inline
Get boxed ntrues.
Definition at line 539 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
isFinite()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::isFinite (const MArray< T > & arr) inline
Test which elements have a finite value.
Definition at line 294 of file MArrayLogical.h.
References casacore::MArray< T >::array().
isInf()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::isInf (const MArray< T > & arr) inline
Test which elements are infinite.
Definition at line 289 of file MArrayLogical.h.
References casacore::MArray< T >::array().
isNaN()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::isNaN (const MArray< T > & arr) inline
Test which elements are NaN.
Definition at line 284 of file MArrayLogical.h.
References casacore::MArray< T >::array().
near() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::near (const MArray< T > & left, const MArray< T > & right, Double tol) inline
Compare with a given relative or absolute tolerance.
Definition at line 247 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
Referenced by near().
near() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::near (const MArray< T > & left, const T & right, Double tol) inline
Definition at line 261 of file MArrayLogical.h.
References casacore::MArray< T >::array(), and near().
near() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::near (const T & left, const MArray< T > & right, Double tol) inline
Definition at line 271 of file MArrayLogical.h.
References casacore::MArray< T >::array(), and near().
nearAbs() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::nearAbs (const MArray< T > & left, const MArray< T > & right, Double tol) inline
Definition at line 254 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
Referenced by nearAbs().
nearAbs() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::nearAbs (const MArray< T > & left, const T & right, Double tol) inline
Definition at line 266 of file MArrayLogical.h.
References casacore::MArray< T >::array(), and nearAbs().
nearAbs() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::nearAbs (const T & left, const MArray< T > & right, Double tol) inline
Definition at line 276 of file MArrayLogical.h.
References casacore::MArray< T >::array(), and nearAbs().
nfalse()
template<typename T > size_t casacore::MArrayLogical_global_functions_MArray_logical_operations::nfalse (const MArray< T > & a) inline
Count the number of unmasked elements that are False.
Definition at line 396 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::mask().
Referenced by casacore::MArrayLogical_global_functions_MArray_logical_operations::MNFalseFunc< T, RES >::operator()().
ntrue()
template<typename T > size_t casacore::MArrayLogical_global_functions_MArray_logical_operations::ntrue (const MArray< T > & a) inline
Count the number of unmasked elements that are True.
Definition at line 382 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::mask().
Referenced by casacore::MArrayLogical_global_functions_MArray_logical_operations::MNTrueFunc< T, RES >::operator()().
operator &&() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator && (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 166 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator &&() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator && (const MArray< T > & left, const T & right) inline
Definition at line 200 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator &&() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator && (const T & left, const MArray< T > & right) inline
The logical AND of 2 MArray objects (normally Bool type).
Definition at line 235 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator!()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator! (const MArray< T > & a) inline
The logical NOT of an MArray object (normally Bool type).
Definition at line 240 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator!=() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator!= (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 154 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator!=() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator!= (const MArray< T > & left, const T & right) inline
Definition at line 192 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator!=() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator!= (const T & left, const MArray< T > & right) inline
Definition at line 224 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator<() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator< (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 136 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator<() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator< (const MArray< T > & left, const T & right) inline
Definition at line 180 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator<() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator< (const T & left, const MArray< T > & right) inline
Definition at line 212 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator<=() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator<= (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 130 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator<=() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator<= (const MArray< T > & left, const T & right) inline
Definition at line 176 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator<=() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator<= (const T & left, const MArray< T > & right) inline
Definition at line 208 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator==() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator== (const MArray< T > & left, const MArray< T > & right) inline
Define comparison functions between 2 MArray objects and between MArray object and scalar.
Definition at line 124 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator==() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator== (const MArray< T > & left, const T & right) inline
Definition at line 172 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator==() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator== (const T & left, const MArray< T > & right) inline
Definition at line 204 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator>() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator> (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 148 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator>() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator> (const MArray< T > & left, const T & right) inline
Definition at line 188 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator>() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator> (const T & left, const MArray< T > & right) inline
Definition at line 220 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator>=() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator>= (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 142 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator>=() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator>= (const MArray< T > & left, const T & right) inline
Definition at line 184 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator>=() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator>= (const T & left, const MArray< T > & right) inline
Definition at line 216 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator||() [1/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator|| (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 160 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator||() [2/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator|| (const MArray< T > & left, const T & right) inline
Definition at line 196 of file MArrayLogical.h.
References casacore::MArray< T >::array().
operator||() [3/3]
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::operator|| (const T & left, const MArray< T > & right) inline
The logical OR of 2 MArray objects (normally Bool type)
Definition at line 230 of file MArrayLogical.h.
References casacore::MArray< T >::array().
partialAlls()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::partialAlls (const MArray< T > & a, const IPosition & collapseAxes) inline
Get partial all.
Definition at line 439 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
partialAnys()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::partialAnys (const MArray< T > & a, const IPosition & collapseAxes) inline
Get partial any.
Definition at line 455 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
partialNFalse()
template<typename T > MArray<uInt> casacore::MArrayLogical_global_functions_MArray_logical_operations::partialNFalse (const MArray< T > & a, const IPosition & collapseAxes) inline
Get partial nfalses.
Definition at line 425 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
partialNTrue()
template<typename T > MArray<uInt> casacore::MArrayLogical_global_functions_MArray_logical_operations::partialNTrue (const MArray< T > & a, const IPosition & collapseAxes) inline
Get partial ntrues.
Definition at line 411 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
slidingAlls()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingAlls (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Get sliding all.
Definition at line 506 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and casacore::slidingArrayMath().
slidingAnys()
template<typename T > MArray<Bool> casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingAnys (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Get sliding any.
Definition at line 522 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and casacore::slidingArrayMath().
slidingNFalse()
template<typename T > MArray<uInt> casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingNFalse (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Get sliding nfalses.
Definition at line 489 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and casacore::slidingArrayMath().
slidingNTrue()
template<typename T > MArray<uInt> casacore::MArrayLogical_global_functions_MArray_logical_operations::slidingNTrue (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Get sliding ntrues.
Definition at line 472 of file MArrayLogical.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and casacore::slidingArrayMath().
The documentation for this struct was generated from the following file:
tables/TaQL/MArrayLogical.h