casacore: casacore::python::casa_array_to_python< T > Struct Template Reference
casacore::python::casa_array_to_python< T > Struct Template Reference
Convert Array to Python.
#include <PycArray.h>
Static Public Member Functions
static boost::python::object makeobject (Array< T > const &arr)
static PyObject * convert (Array< T > const &c)
Detailed Description
template<typename T>
struct casacore::python::casa_array_to_python< T >
Convert Array to Python.
Definition at line 95 of file PycArray.h.
Member Function Documentation
convert()
template<typename T > static PyObject* casacore::python::casa_array_to_python< T >::convert (Array< T > const & c) inline static
Definition at line 99 of file PycArray.h.
References casacore::C::c, and casacore::python::casa_array_to_python< T >::makeobject().
makeobject()
template<typename T > static boost::python::object casacore::python::casa_array_to_python< T >::makeobject (Array< T > const & arr) inline static
Definition at line 97 of file PycArray.h.
References casacore::python::makePyArrayObject().
Referenced by casacore::python::casa_array_to_python< T >::convert().
The documentation for this struct was generated from the following file:
python/Converters/PycArray.h