casacore: casacore::python::casa_record_from_python Struct Reference
casacore::python::casa_record_from_python Struct Reference
#include <PycRecord.h>
Public Member Functions
casa_record_from_python ()
Static Public Member Functions
static void * convertible (PyObject *obj_ptr)
Check if it is a type we can convert.
static void construct (PyObject *obj_ptr, boost::python::converter::rvalue_from_python_stage1_data *data)
Constructs a Record from a Python object.
static Record makeRecord (PyObject *obj_ptr)
Detailed Description
Definition at line 62 of file PycRecord.h.
Constructor & Destructor Documentation
casa_record_from_python()
casacore::python::casa_record_from_python::casa_record_from_python () inline
Definition at line 64 of file PycRecord.h.
References construct(), and convertible().
Member Function Documentation
construct()
static void casacore::python::casa_record_from_python::construct (PyObject * obj_ptr, boost::python::converter::rvalue_from_python_stage1_data * data) static
Constructs a Record from a Python object.
Referenced by casa_record_from_python().
convertible()
static void* casacore::python::casa_record_from_python::convertible (PyObject * obj_ptr) static
Check if it is a type we can convert.
Referenced by casa_record_from_python().
makeRecord()
static Record casacore::python::casa_record_from_python::makeRecord (PyObject * obj_ptr) static
The documentation for this struct was generated from the following file:
python/Converters/PycRecord.h