casacore: casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations Struct Reference
casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations Struct Reference
Arrays_module
Mathematical operations for MaskedArrays (and with Arrays)
#include <MaskArrMath.h>
Public Member Functions
template<class T >
const MaskedArray< T > & operator+= (const MaskedArray< T > &left, const Array< T > &other)
Element by element arithmetic modifying left in-place.
template<class T >
const MaskedArray< T > & operator-= (const MaskedArray< T > &left, const Array< T > &other)
template<class T >
const MaskedArray< T > & operator*= (const MaskedArray< T > &left, const Array< T > &other)
template<class T >
const MaskedArray< T > & operator/= (const MaskedArray< T > &left, const Array< T > &other)
template<class T >
Array< T > & operator+= (Array< T > &left, const MaskedArray< T > &other)
template<class T >
Array< T > & operator-= (Array< T > &left, const MaskedArray< T > &other)
template<class T >
Array< T > & operator*= (Array< T > &left, const MaskedArray< T > &other)
template<class T >
Array< T > & operator/= (Array< T > &left, const MaskedArray< T > &other)
template<class T >
const MaskedArray< T > & operator+= (const MaskedArray< T > &left, const MaskedArray< T > &other)
template<class T >
const MaskedArray< T > & operator-= (const MaskedArray< T > &left, const MaskedArray< T > &other)
template<class T >
const MaskedArray< T > & operator*= (const MaskedArray< T > &left, const MaskedArray< T > &other)
template<class T >
const MaskedArray< T > & operator/= (const MaskedArray< T > &left, const MaskedArray< T > &other)
template<class T , class S >
const MaskedArray< T > & operator/= (const MaskedArray< T > &left, const MaskedArray< S > &other)
template<class T >
const MaskedArray< T > & operator+= (const MaskedArray< T > &left, const T &other)
Element by element arithmetic modifying left in-place.
template<class T >
const MaskedArray< T > & operator-= (const MaskedArray< T > &left, const T &other)
template<class T >
const MaskedArray< T > & operator*= (const MaskedArray< T > &left, const T &other)
template<class T >
const MaskedArray< T > & operator/= (const MaskedArray< T > &left, const T &other)
template<class T >
MaskedArray< T > operator+ (const MaskedArray< T > &a)
Unary arithmetic operation.
template<class T >
MaskedArray< T > operator- (const MaskedArray< T > &a)
template<class T >
MaskedArray< T > operator+ (const MaskedArray< T > &left, const Array< T > &right)
Element by element arithmetic on MaskedArrays, returns a MaskedArray.
template<class T >
MaskedArray< T > operator- (const MaskedArray< T > &left, const Array< T > &right)
template<class T >
MaskedArray< T > operator* (const MaskedArray< T > &left, const Array< T > &right)
template<class T >
MaskedArray< T > operator/ (const MaskedArray< T > &left, const Array< T > &right)
template<class T >
MaskedArray< T > operator+ (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator- (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator* (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator/ (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator+ (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator- (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator* (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator/ (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator+ (const MaskedArray< T > &left, const T &right)
Element by element arithmetic between a MaskedArray and a scalar, returning a MaskedArray.
template<class T >
MaskedArray< T > operator- (const MaskedArray< T > &left, const T &right)
template<class T >
MaskedArray< T > operator* (const MaskedArray< T > &left, const T &right)
template<class T >
MaskedArray< T > operator/ (const MaskedArray< T > &left, const T &right)
MaskedArray< Complex > operator* (const MaskedArray< Complex > &left, const Float &right)
template<class T >
MaskedArray< T > operator+ (const T &left, const MaskedArray< T > &right)
Element by element arithmetic between a scalar and a MaskedArray, returning a MaskedArray.
template<class T >
MaskedArray< T > operator- (const T &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator* (const T &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > operator/ (const T &left, const MaskedArray< T > &right)
MaskedArray< Complex > operator* (const Float &left, const MaskedArray< Complex > &right)
template<class T >
MaskedArray< T > sin (const MaskedArray< T > &left)
Transcendental function applied to the array on an element-by-element basis.
template<class T >
MaskedArray< T > cos (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > tan (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > asin (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > acos (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > atan (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > sinh (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > cosh (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > tanh (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > exp (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > log (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > log10 (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > sqrt (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > abs (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > fabs (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > ceil (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > floor (const MaskedArray< T > &left)
template<class T >
MaskedArray< T > atan2 (const MaskedArray< T > &left, const Array< T > &right)
Transcendental functions requiring two arguments applied on an element-by-element
basis.
template<class T >
MaskedArray< T > fmod (const MaskedArray< T > &left, const Array< T > &right)
template<class T >
MaskedArray< T > atan2 (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > fmod (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > atan2 (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > fmod (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > atan2 (const MaskedArray< T > &left, const T &right)
template<class T >
MaskedArray< T > fmod (const MaskedArray< T > &left, const T &right)
template<class T >
MaskedArray< T > atan2 (const T &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > fmod (const T &left, const MaskedArray< T > &right)
template<class T , class U >
MaskedArray< T > pow (const MaskedArray< T > &left, const Array< U > &right)
template<class T , class U >
MaskedArray< T > pow (const Array< T > &left, const MaskedArray< U > &right)
template<class T , class U >
MaskedArray< T > pow (const MaskedArray< T > &left, const MaskedArray< U > &right)
template<class T >
MaskedArray< T > pow (const MaskedArray< T > &left, const Double &right)
template<class T >
MaskedArray< T > real (const MaskedArray< std::complex< T >> &carray)
Extracts the real part of a complex array into an array of floats.
template<class T >
MaskedArray< T > imag (const MaskedArray< std::complex< T >> &carray)
Extracts the imaginary part of a complex array into an array of floats.
template<class T >
void minMax (T &minVal, T &maxVal, IPosition &minPos, IPosition &maxPos, const MaskedArray< T > &marray)
Find the minimum and maximum values of a MaskedArray.
template<class T >
void minMax (T &minVal, T &maxVal, const MaskedArray< T > &marray)
template<class T >
T min (const MaskedArray< T > &left)
The "min" and "max" functions require that the type "T" have comparison operators.
template<class T >
MaskedArray< T > min (const MaskedArray< T > &left, const Array< T > &right)
Return an array that contains the minimum of "left" and "right" at each position.
template<class T >
MaskedArray< T > min (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > min (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > min (const T &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > min (const MaskedArray< T > &left, const T &right)
template<class T >
void min (const MaskedArray< T > &result, const Array< T > &left, const Array< T > &right)
"result" contains the minimum of "left" and "right" at each position.
template<class T >
T max (const MaskedArray< T > &left)
The maximum element of the array.
template<class T >
MaskedArray< T > max (const MaskedArray< T > &left, const Array< T > &right)
Return an array that contains the maximum of "left" and "right" at each position.
template<class T >
MaskedArray< T > max (const Array< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > max (const MaskedArray< T > &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > max (const T &left, const MaskedArray< T > &right)
template<class T >
MaskedArray< T > max (const MaskedArray< T > &left, const T &right)
template<class T >
void max (const MaskedArray< T > &result, const Array< T > &left, const Array< T > &right)
"result" contains the maximum of "left" and "right" at each position.
template<class T >
void indgen (MaskedArray< T > &a, T start, T inc)
Fills all elements of "array" where the mask is True with a sequence starting with "start" and incrementing by "inc" for each element where the mask is True.
template<class T >
void indgen (MaskedArray< T > &a)
Fills all elements of "array" where the mask is True with a sequence starting with 0 and incremented by one for each element where the mask is True.
template<class T >
void indgen (MaskedArray< T > &a, T start)
Fills all elements of "array" where the mask is True with a sequence starting with "start" and incremented by one for each element where the mask is True.
template<class T >
T sum (const MaskedArray< T > &a)
template<class T >
T sumsquares (const MaskedArray< T > &a)
Sum of the squares of every element of the MaskedArray where the Mask is True.
template<class T >
T product (const MaskedArray< T > &a)
Product of every element of the MaskedArray where the Mask is True.
template<class T >
T mean (const MaskedArray< T > &a)
The mean of "a" is the sum of all elements of "a" divided by the number of elements of "a".
template<class T >
T variance (const MaskedArray< T > &a)
The variance of "a" is the sum of (a(i) - mean(a))**2/(a.nelements() - ddof).
template<class T >
T pvariance (const MaskedArray< T > &a, uInt ddof=0)
template<class T >
T variance (const MaskedArray< T > &a, T mean)
Rather than using a computed mean, use the supplied value.
template<class T >
T pvariance (const MaskedArray< T > &a, T mean, uInt ddof=0)
template<class T >
T stddev (const MaskedArray< T > &a)
The standard deviation of "a" is the square root of its variance.
template<class T >
T pstddev (const MaskedArray< T > &a, uInt ddof=0)
template<class T >
T stddev (const MaskedArray< T > &a, T mean)
template<class T >
T pstddev (const MaskedArray< T > &a, T mean, uInt ddof=0)
template<class T >
T avdev (const MaskedArray< T > &a)
The average deviation of "a" is the sum of abs(a(i) - mean(a))/N.
template<class T >
T avdev (const MaskedArray< T > &a, T mean)
The average deviation of "a" is the sum of abs(a(i) - mean(a))/N.
template<class T >
T rms (const MaskedArray< T > &a)
The root-mean-square of "a" is the sqrt of sum(a*a)/N.
template<class T >
T median (const MaskedArray< T > &a, Bool sorted=False)
The median of "a" is a(n/2).
template<class T >
T median (const MaskedArray< T > &a, Bool sorted, Bool takeEvenMean)
template<class T >
T madfm (const MaskedArray< T > &a, Bool sorted=False)
The median absolute deviation from the median.
template<class T >
T madfm (const MaskedArray< T > &a, Bool sorted, Bool takeEvenMean)
template<class T >
MaskedArray< T > square (const MaskedArray< T > &val)
Returns a MaskedArray where every element is squared.
template<class T >
MaskedArray< T > cube (const MaskedArray< T > &val)
Returns a MaskedArray where every element is cubed.
Detailed Description
Mathematical operations for MaskedArrays (and with Arrays)
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Test programs:
tMaskArrMath0 tMaskArrMath1 tMaskArrMath2 tMaskArrExcp
Prerequisite
Array
MaskedArray
Etymology
MaskArrMath is short for MaskedArrayMath, which is too long by the old AIPS++ file naming conventions. This file contains global functions which perform element by element mathematical operations on masked arrays.
Synopsis
These functions perform element by element mathematical operations on masked arrays. With two arrays, they must both conform, and the result is done element by element, for those locations where the mask of the MaskedArray is True. For two MaskedArrays, the "and" of the masks is used.
Example
 Vector<Int> a(10);
 Vector<Int> b(10);
 Vector<Int> c(10);
...
 c = a(a>0) + b(b>0);
This example sets those elements of c where ((a>0) && (b>0)) to (a+b). Elements of c where !((a>0) && (b>0)) are unchanged. The result of this operation is a MaskedArray. The assignment from this MaskedArray to the Vector c only assigns those elements where the mask is True.
Example
 Vector<Double> a(10);
 Vector<Double> b(10);
 Vector<Double> c(10);
...
 c = atan2 (a, b(b>0);
This example sets those elements of c where (b>0) to atan2 (a,b). Elements of c where !(b>0) are unchanged. The result of this operation is a MaskedArray. The assignment from this MaskedArray to the Vector c only assigns those elements where the mask is True.
Example
 Vector<Int> a(10);
 Int result;
...
 result = sum (a(a>0));
This example sums a, for those elements of a which are greater than 0.
Motivation
One wants to be able to mask arrays and perform mathematical operations on those masked arrays. Since the masked arrays are only defined where the masks are True, the result must be a MaskedArray, or a simple number.
Definition at line 116 of file MaskArrMath.h.
Member Function Documentation
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::abs (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::acos (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::asin (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::atan (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::atan2 (const MaskedArray< T > & left, const Array< T > & right)
Transcendental functions requiring two arguments applied on an element-by-element
basis.
Although a template function, this may not make sense for all numeric types.
Thrown Exceptions
ArrayConformanceError
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::atan2 (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::atan2 (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::atan2 (const MaskedArray< T > & left, const T & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::atan2 (const T & left, const MaskedArray< T > & right)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::avdev (const MaskedArray< T > & a)
The average deviation of "a" is the sum of abs(a(i) - mean(a))/N.
(N.B. N, not N-1 in the denominator).
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::avdev (const MaskedArray< T > & a, T mean)
The average deviation of "a" is the sum of abs(a(i) - mean(a))/N.
(N.B. N, not N-1 in the denominator). Rather than using a computed mean, use the supplied value.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::ceil (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::cos (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::cosh (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::cube (const MaskedArray< T > & val)
Returns a MaskedArray where every element is cubed.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::exp (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::fabs (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::floor (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::fmod (const MaskedArray< T > & left, const Array< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::fmod (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::fmod (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::fmod (const MaskedArray< T > & left, const T & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::fmod (const T & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::imag (const MaskedArray< std::complex< T >> & carray) inline
Extracts the imaginary part of a complex array into an array of floats.
Definition at line 258 of file MaskArrMath.h.
References casacore::imag().
template<class T > void casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::indgen (MaskedArray< T > & a, T start, T inc)
Fills all elements of "array" where the mask is True with a sequence starting with "start" and incrementing by "inc" for each element where the mask is True.
The first axis varies most rapidly.
template<class T > void casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::indgen (MaskedArray< T > & a)
Fills all elements of "array" where the mask is True with a sequence starting with 0 and incremented by one for each element where the mask is True.
The first axis varies most rapidly.
template<class T > void casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::indgen (MaskedArray< T > & a, T start)
Fills all elements of "array" where the mask is True with a sequence starting with "start" and incremented by one for each element where the mask is True.
The first axis varies most rapidly.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::log (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::log10 (const MaskedArray< T > & left)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::madfm (const MaskedArray< T > & a, Bool sorted = False) inline
The median absolute deviation from the median.
Interface is as for the median functions
Definition at line 440 of file MaskArrMath.h.
References casacore::MaskedArray< T >::nelements().
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::madfm (const MaskedArray< T > & a, Bool sorted, Bool takeEvenMean)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::max (const MaskedArray< T > & left)
The maximum element of the array.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::max (const MaskedArray< T > & left, const Array< T > & right)
Return an array that contains the maximum of "left" and "right" at each position.
"left" and "right" must be conformant.
Thrown Exceptions
ArrayError
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::max (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::max (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::max (const T & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::max (const MaskedArray< T > & left, const T & right)
template<class T > void casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::max (const MaskedArray< T > & result, const Array< T > & left, const Array< T > & right)
"result" contains the maximum of "left" and "right" at each position.
"result", "left", and "right" must be conformant.
Thrown Exceptions
ArrayConformanceError
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::mean (const MaskedArray< T > & a)
The mean of "a" is the sum of all elements of "a" divided by the number of elements of "a".
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::median (const MaskedArray< T > & a, Bool sorted = False) inline
The median of "a" is a(n/2).
When a has an even number of elements and the switch takeEvenMean is set, the median is 0.5*(a(n/2) + a((n+1)/2)). According to Numerical Recipes (2nd edition) it makes little sense to take the mean when the array is large enough (> 100 elements). Therefore the default for takeEvenMean is False when the array has > 100 elements, otherwise it is True.
If "sorted"==True we assume the data is already sorted and we compute the median directly. Otherwise the function GenSort::kthLargest is used to find the median (kthLargest is about 6 times faster than a full quicksort).
Definition at line 431 of file MaskArrMath.h.
References casacore::median(), and casacore::MaskedArray< T >::nelements().
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::median (const MaskedArray< T > & a, Bool sorted, Bool takeEvenMean)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::min (const MaskedArray< T > & left)
The "min" and "max" functions require that the type "T" have comparison operators.
The minimum element of the array.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::min (const MaskedArray< T > & left, const Array< T > & right)
Return an array that contains the minimum of "left" and "right" at each position.
"left" and "right" must be conformant.
Thrown Exceptions
ArrayError
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::min (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::min (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::min (const T & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::min (const MaskedArray< T > & left, const T & right)
template<class T > void casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::min (const MaskedArray< T > & result, const Array< T > & left, const Array< T > & right)
"result" contains the minimum of "left" and "right" at each position.
"result", "left", and "right" must be conformant.
Thrown Exceptions
ArrayConformanceError
template<class T > void casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::minMax (T & minVal, T & maxVal, IPosition & minPos, IPosition & maxPos, const MaskedArray< T > & marray)
Find the minimum and maximum values of a MaskedArray.
Also find the IPositions of the minimum and maximum values.
Thrown Exceptions
ArrayError
template<class T > void casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::minMax (T & minVal, T & maxVal, const MaskedArray< T > & marray)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator* (const MaskedArray< T > & left, const Array< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator* (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator* (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator* (const MaskedArray< T > & left, const T & right)
MaskedArray<Complex> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator* (const MaskedArray< Complex > & left, const Float & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator* (const T & left, const MaskedArray< T > & right)
MaskedArray<Complex> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator* (const Float & left, const MaskedArray< Complex > & right)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator*= (const MaskedArray< T > & left, const Array< T > & other)
template<class T > Array<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator*= (Array< T > & left, const MaskedArray< T > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator*= (const MaskedArray< T > & left, const MaskedArray< T > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator*= (const MaskedArray< T > & left, const T & other)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+ (const MaskedArray< T > & a)
Unary arithmetic operation.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+ (const MaskedArray< T > & left, const Array< T > & right)
Element by element arithmetic on MaskedArrays, returns a MaskedArray.
Thrown Exceptions
ArrayConformanceError
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+ (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+ (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+ (const MaskedArray< T > & left, const T & right)
Element by element arithmetic between a MaskedArray and a scalar, returning a MaskedArray.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+ (const T & left, const MaskedArray< T > & right)
Element by element arithmetic between a scalar and a MaskedArray, returning a MaskedArray.
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+= (const MaskedArray< T > & left, const Array< T > & other)
Element by element arithmetic modifying left in-place.
left and other must be conformant.
Thrown Exceptions
ArrayConformanceError
template<class T > Array<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+= (Array< T > & left, const MaskedArray< T > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+= (const MaskedArray< T > & left, const MaskedArray< T > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator+= (const MaskedArray< T > & left, const T & other)
Element by element arithmetic modifying left in-place.
The scalar "other" behaves as if it were a conformant Array to left filled with constant values.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator- (const MaskedArray< T > & a)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator- (const MaskedArray< T > & left, const Array< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator- (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator- (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator- (const MaskedArray< T > & left, const T & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator- (const T & left, const MaskedArray< T > & right)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator-= (const MaskedArray< T > & left, const Array< T > & other)
template<class T > Array<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator-= (Array< T > & left, const MaskedArray< T > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator-= (const MaskedArray< T > & left, const MaskedArray< T > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator-= (const MaskedArray< T > & left, const T & other)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/ (const MaskedArray< T > & left, const Array< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/ (const Array< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/ (const MaskedArray< T > & left, const MaskedArray< T > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/ (const MaskedArray< T > & left, const T & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/ (const T & left, const MaskedArray< T > & right)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/= (const MaskedArray< T > & left, const Array< T > & other)
template<class T > Array<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/= (Array< T > & left, const MaskedArray< T > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/= (const MaskedArray< T > & left, const MaskedArray< T > & other)
template<class T , class S > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/= (const MaskedArray< T > & left, const MaskedArray< S > & other)
template<class T > const MaskedArray<T>& casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::operator/= (const MaskedArray< T > & left, const T & other)
template<class T , class U > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pow (const MaskedArray< T > & left, const Array< U > & right)
template<class T , class U > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pow (const Array< T > & left, const MaskedArray< U > & right)
template<class T , class U > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pow (const MaskedArray< T > & left, const MaskedArray< U > & right)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pow (const MaskedArray< T > & left, const Double & right)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::product (const MaskedArray< T > & a)
Product of every element of the MaskedArray where the Mask is True.
This could of course easily overflow.
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pstddev (const MaskedArray< T > & a, uInt ddof = 0)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pstddev (const MaskedArray< T > & a, T mean, uInt ddof = 0)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pvariance (const MaskedArray< T > & a, uInt ddof = 0)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::pvariance (const MaskedArray< T > & a, T mean, uInt ddof = 0)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::real (const MaskedArray< std::complex< T >> & carray) inline
Extracts the real part of a complex array into an array of floats.
Definition at line 252 of file MaskArrMath.h.
References casacore::real().
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::rms (const MaskedArray< T > & a)
The root-mean-square of "a" is the sqrt of sum(a*a)/N.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::sin (const MaskedArray< T > & left)
Transcendental function applied to the array on an element-by-element basis.
Although a template function, this may not make sense for all numeric types.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::sinh (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::sqrt (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::square (const MaskedArray< T > & val)
Returns a MaskedArray where every element is squared.
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::stddev (const MaskedArray< T > & a)
The standard deviation of "a" is the square root of its variance.
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::stddev (const MaskedArray< T > & a, T mean)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::sum (const MaskedArray< T > & a)
Thrown Exceptions
ArrayError
Sum of every element of the MaskedArray where the Mask is True.
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::sumsquares (const MaskedArray< T > & a)
Sum of the squares of every element of the MaskedArray where the Mask is True.
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::tan (const MaskedArray< T > & left)
template<class T > MaskedArray<T> casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::tanh (const MaskedArray< T > & left)
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::variance (const MaskedArray< T > & a)
The variance of "a" is the sum of (a(i) - mean(a))**2/(a.nelements() - ddof).
Similar to numpy the argument ddof tells if the population variance (ddof=0) or the sample variance (ddof=1) is taken. The variance functions proper use ddof=1.
Note that for a complex valued T the absolute values are used; in that way the variance is equal to the sum of the variances of the real and imaginary parts. Hence the imaginary part in the return value is 0.
template<class T > T casacore::MaskArrMath_global_functions_MaskedArray_mathematical_operations::variance (const MaskedArray< T > & a, T mean)
Rather than using a computed mean, use the supplied value.
The documentation for this struct was generated from the following file:
casa/Arrays/MaskArrMath.h