casacore: casacore::Allocator_private::BulkAllocator< T2 > Struct Template Reference
casacore::Allocator_private::BulkAllocator< T2 > Struct Template Reference abstract
Public Types
typedef std::allocator< T2 >::size_type size_type
typedef std::allocator< T2 >::pointer pointer
typedef std::allocator< T2 >::const_pointer const_pointer
typedef std::allocator< T2 >::value_type value_type
Public Member Functions
virtual pointer allocate (size_type elements, const void *ptr=0)=0
virtual void deallocate (pointer ptr, size_type size)=0
virtual void construct (pointer ptr, size_type n, const_pointer src)=0
virtual void construct (pointer ptr, size_type n, value_type const &initial_value)=0
virtual void construct (pointer ptr, size_type n)=0
virtual void destroy (pointer ptr, size_type n)=0
virtual std::type_info const & allocator_typeid () const =0
virtual ~BulkAllocator ()
Detailed Description
template<typename T2>
struct casacore::Allocator_private::BulkAllocator< T2 >
Definition at line 219 of file Allocator.h.
Member Typedef Documentation
const_pointer
template<typename T2> typedef std::allocator<T2>::const_pointer casacore::Allocator_private::BulkAllocator< T2 >::const_pointer
Definition at line 222 of file Allocator.h.
pointer
template<typename T2> typedef std::allocator<T2>::pointer casacore::Allocator_private::BulkAllocator< T2 >::pointer
Definition at line 221 of file Allocator.h.
size_type
template<typename T2> typedef std::allocator<T2>::size_type casacore::Allocator_private::BulkAllocator< T2 >::size_type
Definition at line 220 of file Allocator.h.
value_type
template<typename T2> typedef std::allocator<T2>::value_type casacore::Allocator_private::BulkAllocator< T2 >::value_type
Definition at line 223 of file Allocator.h.
Constructor & Destructor Documentation
~BulkAllocator()
template<typename T2> virtual casacore::Allocator_private::BulkAllocator< T2 >::~BulkAllocator () inline virtual
Definition at line 233 of file Allocator.h.
Member Function Documentation
allocate()
template<typename T2> virtual pointer casacore::Allocator_private::BulkAllocator< T2 >::allocate (size_type elements, const void * ptr = 0) pure virtual
Referenced by casacore::Block< casacore::String >::init(), casacore::Block< casacore::String >::remove(), and casacore::Block< casacore::String >::resize().
allocator_typeid()
template<typename T2> virtual std::type_info const& casacore::Allocator_private::BulkAllocator< T2 >::allocator_typeid () const pure virtual
Implemented in casacore::Allocator_private::BulkAllocatorImpl< Allocator >.
construct() [1/3]
template<typename T2> virtual void casacore::Allocator_private::BulkAllocator< T2 >::construct (pointer ptr, size_type n, const_pointer src) pure virtual
Referenced by casacore::Block< casacore::String >::Block(), casacore::Block< casacore::String >::construct(), casacore::Block< casacore::String >::init(), casacore::Block< casacore::String >::operator=(), casacore::Block< casacore::String >::remove(), and casacore::Block< casacore::String >::resize().
construct() [2/3]
template<typename T2> virtual void casacore::Allocator_private::BulkAllocator< T2 >::construct (pointer ptr, size_type n, value_type const & initial_value) pure virtual
construct() [3/3]
template<typename T2> virtual void casacore::Allocator_private::BulkAllocator< T2 >::construct (pointer ptr, size_type n) pure virtual
deallocate()
template<typename T2> virtual void casacore::Allocator_private::BulkAllocator< T2 >::deallocate (pointer ptr, size_type size) pure virtual
Referenced by casacore::Block< casacore::String >::dealloc(), casacore::Block< casacore::String >::remove(), casacore::Block< casacore::String >::replaceStorage(), and casacore::Block< casacore::String >::resize().
destroy()
template<typename T2> virtual void casacore::Allocator_private::BulkAllocator< T2 >::destroy (pointer ptr, size_type n) pure virtual
Referenced by casacore::Block< casacore::String >::deinit(), casacore::Block< casacore::String >::destroy(), casacore::Block< casacore::String >::remove(), casacore::Block< casacore::String >::replaceStorage(), and casacore::Block< casacore::String >::resize().
The documentation for this struct was generated from the following file:
casa/Containers/Allocator.h