casacore: casacore::MArrayMath_global_functions_MArray_mathematical_operations Struct Reference
casacore::MArrayMath_global_functions_MArray_mathematical_operations Struct Reference
tables package (libcasa_tables) » TaQL_module
Mathematical operations for MArray objects.
#include <MArrayMath.h>
Classes
class MAvdevFunc
class MFractileFunc
class MMaxFunc
class MMeanFunc
class MMedianFunc
class MMinFunc
class MProductFunc
class MRmsFunc
class MStddevFunc
class MSumFunc
Define functors to perform a reduction function on an MArray object.
class MSumSqrFunc
class MVarianceFunc
Public Member Functions
template<typename T >
MArray< T > partialArrayMath (const MArray< T > &a, const IPosition &collapseAxes, const MArrayFunctorBase< T > &funcObj)
Do partial reduction of an MArray object.
template<typename T , typename RES >
void partialArrayMath (MArray< RES > &res, const MArray< T > &a, const IPosition &collapseAxes, const MArrayFunctorBase< T, RES > &funcObj)
template<typename T >
MArray< T > boxedArrayMath (const MArray< T > &a, const IPosition &boxShape, const MArrayFunctorBase< T > &funcObj)
template<typename T , typename RES >
void boxedArrayMath (MArray< RES > &res, const MArray< T > &array, const IPosition &boxShape, const MArrayFunctorBase< T, RES > &funcObj)
template<typename T >
MArray< T > slidingArrayMath (const MArray< T > &array, const IPosition &halfBoxShape, const MArrayFunctorBase< T > &funcObj, Bool fillEdge=True)
template<typename T , typename RES >
void slidingArrayMath (MArray< RES > &res, const MArray< T > &array, const IPosition &halfBoxShape, const MArrayFunctorBase< T, RES > &funcObj, Bool fillEdge=True)
template<typename T >
MArray< T > operator+ (const MArray< T > &left, const MArray< T > &right)
Add, subtract, etc.
template<typename T >
MArray< T > operator- (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > operator * (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > operator/ (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > operator% (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > operator & (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > operator| (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > operator^ (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > operator+ (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator- (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator * (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator/ (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator% (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator & (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator| (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator^ (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > operator+ (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator- (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator * (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator/ (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator% (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator & (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator| (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator^ (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > operator- (const MArray< T > &a)
Negate the elements in an array.
template<typename T >
MArray< T > operator~ (const MArray< T > &a)
Take the complement of the elements in an array.
template<typename T >
MArray< T > sin (const MArray< T > &a)
Perform mathematical function on each element in an array.
template<typename T >
MArray< T > cos (const MArray< T > &a)
template<typename T >
MArray< T > tan (const MArray< T > &a)
template<typename T >
MArray< T > sinh (const MArray< T > &a)
template<typename T >
MArray< T > cosh (const MArray< T > &a)
template<typename T >
MArray< T > tanh (const MArray< T > &a)
template<typename T >
MArray< T > asin (const MArray< T > &a)
template<typename T >
MArray< T > acos (const MArray< T > &a)
template<typename T >
MArray< T > atan (const MArray< T > &a)
template<typename T >
MArray< T > atan2 (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > atan2 (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > atan2 (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > exp (const MArray< T > &a)
template<typename T >
MArray< T > log (const MArray< T > &a)
template<typename T >
MArray< T > log10 (const MArray< T > &a)
template<typename T >
MArray< T > sqrt (const MArray< T > &a)
template<typename T >
MArray< T > square (const MArray< T > &a)
template<typename T >
MArray< T > cube (const MArray< T > &a)
template<typename T >
MArray< T > pow (const MArray< T > &a, const MArray< T > &exp)
template<typename T >
MArray< T > pow (const T &a, const MArray< T > &exp)
template<typename T >
MArray< T > pow (const MArray< T > &a, const Double &exp)
template<typename T >
MArray< T > min (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > min (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > min (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > max (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > max (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > max (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > ceil (const MArray< T > &a)
template<typename T >
MArray< T > floor (const MArray< T > &a)
template<typename T >
MArray< T > round (const MArray< T > &a)
template<typename T >
MArray< T > sign (const MArray< T > &a)
template<typename T >
MArray< T > abs (const MArray< T > &a)
template<typename T >
MArray< T > fabs (const MArray< T > &a)
template<typename T >
MArray< T > fmod (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > fmod (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > fmod (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > floormod (const MArray< T > &left, const MArray< T > &right)
template<typename T >
MArray< T > floormod (const MArray< T > &left, const T &right)
template<typename T >
MArray< T > floormod (const T &left, const MArray< T > &right)
template<typename T >
MArray< T > conj (const MArray< T > &arr)
MArray< Float > real (const MArray< Complex > &arr)
MArray< Float > imag (const MArray< Complex > &arr)
MArray< Float > amplitude (const MArray< Complex > &arr)
MArray< Float > phase (const MArray< Complex > &arr)
MArray< Double > real (const MArray< DComplex > &arr)
MArray< Double > imag (const MArray< DComplex > &arr)
MArray< Double > amplitude (const MArray< DComplex > &arr)
MArray< Double > phase (const MArray< DComplex > &arr)
template<typename T >
T sum (const MArray< T > &a)
Reduce an array to a scalar using the unmasked elements only.
template<typename T >
T sumsqr (const MArray< T > &a)
template<typename T >
T product (const MArray< T > &a)
template<typename T >
T min (const MArray< T > &a)
template<typename T >
T max (const MArray< T > &a)
template<typename T >
T mean (const MArray< T > &a)
template<typename T >
T variance (const MArray< T > &a, T mean, uInt ddof)
template<typename T >
T variance (const MArray< T > &a, uInt ddof)
template<typename T >
T stddev (const MArray< T > &a, uInt ddof)
template<typename T >
T stddev (const MArray< T > &a, T mean, uInt ddof)
template<typename T >
T avdev (const MArray< T > &a, T mean)
template<typename T >
T avdev (const MArray< T > &a)
template<typename T >
T rms (const MArray< T > &a)
template<typename T >
T median (const MArray< T > &a, Bool sorted, Bool takeEvenMean, Bool inPlace=False)
template<typename T >
T median (const MArray< T > &a)
template<typename T >
T median (const MArray< T > &a, Bool sorted)
template<typename T >
T medianInPlace (const MArray< T > &a, Bool sorted=False)
template<typename T >
T fractile (const MArray< T > &a, Float fraction, Bool sorted=False, Bool inPlace=False)
Return the fractile of an array.
template<typename T >
MArray< T > partialSums (const MArray< T > &a, const IPosition &collapseAxes)
Get partial sums, etc.
template<typename T >
MArray< T > partialSumSqrs (const MArray< T > &a, const IPosition &collapseAxes)
template<typename T >
MArray< T > partialProducts (const MArray< T > &a, const IPosition &collapseAxes)
template<typename T >
MArray< T > partialMins (const MArray< T > &a, const IPosition &collapseAxes)
template<typename T >
MArray< T > partialMaxs (const MArray< T > &a, const IPosition &collapseAxes)
template<typename T >
MArray< T > partialMeans (const MArray< T > &a, const IPosition &collapseAxes)
template<typename T >
MArray< T > partialVariances (const MArray< T > &a, const IPosition &collapseAxes, uInt ddof)
template<typename T >
MArray< T > partialStddevs (const MArray< T > &a, const IPosition &collapseAxes, uInt ddof)
template<typename T >
MArray< T > partialAvdevs (const MArray< T > &a, const IPosition &collapseAxes)
template<typename T >
MArray< T > partialRmss (const MArray< T > &a, const IPosition &collapseAxes)
template<typename T >
MArray< T > partialMedians (const MArray< T > &a, const IPosition &collapseAxes, Bool takeEvenMean=False, Bool inPlace=False)
template<typename T >
MArray< T > partialFractiles (const MArray< T > &a, const IPosition &collapseAxes, Float fraction, Bool inPlace=False)
template<typename T >
MArray< T > slidingSums (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
Get sliding sums.
template<typename T >
MArray< T > slidingSumSqrs (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
template<typename T >
MArray< T > slidingProducts (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
template<typename T >
MArray< T > slidingMins (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
template<typename T >
MArray< T > slidingMaxs (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
template<typename T >
MArray< T > slidingMeans (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
template<typename T >
MArray< T > slidingVariances (const MArray< T > &a, const IPosition &halfBoxSize, uInt ddof, Bool fillEdge=True)
template<typename T >
MArray< T > slidingStddevs (const MArray< T > &a, const IPosition &halfBoxSize, uInt ddof, Bool fillEdge=True)
template<typename T >
MArray< T > slidingAvdevs (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
template<typename T >
MArray< T > slidingRmss (const MArray< T > &a, const IPosition &halfBoxSize, Bool fillEdge=True)
template<typename T >
MArray< T > slidingMedians (const MArray< T > &a, const IPosition &halfBoxSize, Bool takeEvenMean=False, Bool inPlace=False, Bool fillEdge=True)
template<typename T >
MArray< T > slidingFractiles (const MArray< T > &a, const IPosition &halfBoxSize, Float fraction, Bool inPlace=False, Bool fillEdge=True)
template<typename T >
MArray< T > boxedSums (const MArray< T > &a, const IPosition &boxSize)
Get boxed sums.
template<typename T >
MArray< T > boxedSumSqrs (const MArray< T > &a, const IPosition &boxSize)
template<typename T >
MArray< T > boxedProducts (const MArray< T > &a, const IPosition &boxSize)
template<typename T >
MArray< T > boxedMins (const MArray< T > &a, const IPosition &boxSize)
template<typename T >
MArray< T > boxedMaxs (const MArray< T > &a, const IPosition &boxSize)
template<typename T >
MArray< T > boxedMeans (const MArray< T > &a, const IPosition &boxSize)
template<typename T >
MArray< T > boxedVariances (const MArray< T > &a, const IPosition &boxSize, uInt ddof)
template<typename T >
MArray< T > boxedStddevs (const MArray< T > &a, const IPosition &boxSize, uInt ddof)
template<typename T >
MArray< T > boxedAvdevs (const MArray< T > &a, const IPosition &boxSize)
template<typename T >
MArray< T > boxedRmss (const MArray< T > &a, const IPosition &boxSize)
template<typename T >
MArray< T > boxedMedians (const MArray< T > &a, const IPosition &boxSize, Bool takeEvenMean=False, Bool inPlace=False)
template<typename T >
MArray< T > boxedFractiles (const MArray< T > &a, const IPosition &boxSize, Float fraction, Bool inPlace=False)
Detailed Description
Mathematical operations for MArray objects.
Review Status
Reviewed By:
UNKNOWN
Test programs:
tMArrayMath
Prerequisite
MArray
Synopsis
These functions perform element by element mathematical operations on optionally masked arrays and/or scalars. If two arrays are used, the arrays must conform, except for allEQ which returns False if the arrays do not conform.
The functions in this file can be divided in 3 groups:
Full array operations like ==, near, etc. They are defined for array-array and array-scalar operations. Arrays shapes have to be conformant. They operate on all elements (also the masked ones). The result is an MArray with the same shape as the input array(s). It will have a mask if one of the operands has a mask. If both operands have a mask, the resulting mask is the OR of both masks.
Full reduction functions like ntrue, all, allEQ, etc. They operate on the unmasked elements only. If there are no unmasked elements, the results is 0 or True.
Reduction functions working on unmasked elements in parts of the input array. The result is an MArray that has a mask if the input array has a mask. An output element is masked off if its input part has no unmasked elements. The functors defined at the beginning of this file are used to operate on each part. There are 3 flavours:
partialXXX reduces one or more axes. E.g. one can count the number of True elements for particular array axes. The result is an array with a lower dimensionality. They can be seen as a special versions of the boxedXXX functions.
slidingXXX operates in a sliding window over the array. So the result is an array with the same shape as the input, although the output array is smaller if the edge is not filled.
boxedXXX divides the input array in boxes with the given size and operates on each box. The result is an array with the same dimensionality, but with a smaller size. If the box size does not fit integrally, the edge box is smaller.
Definition at line 92 of file MArrayMath.h.
Member Function Documentation
abs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::abs (const MArray< T > & a) inline
Definition at line 636 of file MArrayMath.h.
References casacore::MArray< T >::array().
acos()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::acos (const MArray< T > & a) inline
Definition at line 532 of file MArrayMath.h.
References casacore::MArray< T >::array().
amplitude() [1/2]
MArray<Float> casacore::MArrayMath_global_functions_MArray_mathematical_operations::amplitude (const MArray< Complex > & arr) inline
Definition at line 681 of file MArrayMath.h.
References casacore::MArray< T >::array().
Referenced by amplitude().
amplitude() [2/2]
MArray<Double> casacore::MArrayMath_global_functions_MArray_mathematical_operations::amplitude (const MArray< DComplex > & arr) inline
Definition at line 693 of file MArrayMath.h.
References amplitude(), and casacore::MArray< T >::array().
asin()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::asin (const MArray< T > & a) inline
Definition at line 528 of file MArrayMath.h.
References casacore::MArray< T >::array().
atan()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::atan (const MArray< T > & a) inline
Definition at line 536 of file MArrayMath.h.
References casacore::MArray< T >::array().
atan2() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::atan2 (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 540 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
Referenced by atan2().
atan2() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::atan2 (const MArray< T > & left, const T & right) inline
Definition at line 546 of file MArrayMath.h.
References casacore::MArray< T >::array(), and atan2().
atan2() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::atan2 (const T & left, const MArray< T > & right) inline
Definition at line 550 of file MArrayMath.h.
References casacore::MArray< T >::array(), and atan2().
avdev() [1/2]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::avdev (const MArray< T > & a, T mean) inline
Definition at line 811 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::mask(), mean(), casacore::MArrayBase::nvalid(), and sum().
Referenced by avdev(), and casacore::MArrayMath_global_functions_MArray_mathematical_operations::MAvdevFunc< T >::operator()().
avdev() [2/2]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::avdev (const MArray< T > & a) inline
Definition at line 825 of file MArrayMath.h.
References avdev(), and mean().
boxedArrayMath() [1/2]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath (const MArray< T > & a, const IPosition & boxShape, const MArrayFunctorBase< T > & funcObj) inline
Definition at line 247 of file MArrayMath.h.
Referenced by boxedAvdevs(), boxedFractiles(), boxedMaxs(), boxedMeans(), boxedMedians(), boxedMins(), boxedProducts(), boxedRmss(), boxedStddevs(), boxedSums(), boxedSumSqrs(), and boxedVariances().
boxedArrayMath() [2/2]
template<typename T , typename RES > void casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedArrayMath (MArray< RES > & res, const MArray< T > & array, const IPosition & boxShape, const MArrayFunctorBase< T, RES > & funcObj) inline
Loop through all data and assemble as needed.
Definition at line 256 of file MArrayMath.h.
References AlwaysAssert, casacore::MArray< T >::array(), casacore::array(), casacore::Array< T >::data(), casacore::False, casacore::fillBoxedShape(), casacore::mask(), casacore::ndim(), casacore::MArray< T >::resize(), casacore::MArrayBase::setMask(), casacore::shape(), and casacore::True.
boxedAvdevs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedAvdevs (const MArray< T > & a, const IPosition & boxSize) inline
Definition at line 1294 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedFractiles()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedFractiles (const MArray< T > & a, const IPosition & boxSize, Float fraction, Bool inPlace = False) inline
Definition at line 1332 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::False, casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedMaxs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedMaxs (const MArray< T > & a, const IPosition & boxSize) inline
Definition at line 1248 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedMeans()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedMeans (const MArray< T > & a, const IPosition & boxSize) inline
Definition at line 1259 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedMedians()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedMedians (const MArray< T > & a, const IPosition & boxSize, Bool takeEvenMean = False, Bool inPlace = False) inline
Definition at line 1316 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::False, casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedMins()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedMins (const MArray< T > & a, const IPosition & boxSize) inline
Definition at line 1237 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedProducts()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedProducts (const MArray< T > & a, const IPosition & boxSize) inline
Definition at line 1226 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedRmss()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedRmss (const MArray< T > & a, const IPosition & boxSize) inline
Definition at line 1305 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedStddevs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedStddevs (const MArray< T > & a, const IPosition & boxSize, uInt ddof) inline
Definition at line 1282 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedSums()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedSums (const MArray< T > & a, const IPosition & boxSize) inline
Get boxed sums.
Definition at line 1204 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedSumSqrs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedSumSqrs (const MArray< T > & a, const IPosition & boxSize) inline
Definition at line 1215 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
boxedVariances()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::boxedVariances (const MArray< T > & a, const IPosition & boxSize, uInt ddof) inline
Definition at line 1270 of file MArrayMath.h.
References casacore::MArray< T >::array(), boxedArrayMath(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::isNull().
ceil()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::ceil (const MArray< T > & a) inline
Definition at line 620 of file MArrayMath.h.
References casacore::MArray< T >::array().
conj()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::conj (const MArray< T > & arr) inline
Definition at line 672 of file MArrayMath.h.
References casacore::MArray< T >::array().
cos()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::cos (const MArray< T > & a) inline
Definition at line 508 of file MArrayMath.h.
References casacore::MArray< T >::array().
cosh()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::cosh (const MArray< T > & a) inline
Definition at line 520 of file MArrayMath.h.
References casacore::MArray< T >::array().
cube()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::cube (const MArray< T > & a) inline
Definition at line 574 of file MArrayMath.h.
References casacore::MArray< T >::array().
exp()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::exp (const MArray< T > & a) inline
Definition at line 554 of file MArrayMath.h.
References casacore::MArray< T >::array().
Referenced by pow().
fabs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::fabs (const MArray< T > & a) inline
Definition at line 640 of file MArrayMath.h.
References casacore::MArray< T >::array().
floor()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::floor (const MArray< T > & a) inline
Definition at line 624 of file MArrayMath.h.
References casacore::MArray< T >::array().
floormod() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::floormod (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 658 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
Referenced by floormod().
floormod() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::floormod (const MArray< T > & left, const T & right) inline
Definition at line 664 of file MArrayMath.h.
References casacore::MArray< T >::array(), and floormod().
floormod() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::floormod (const T & left, const MArray< T > & right) inline
Definition at line 668 of file MArrayMath.h.
References casacore::MArray< T >::array(), and floormod().
fmod() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::fmod (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 644 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
Referenced by fmod().
fmod() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::fmod (const MArray< T > & left, const T & right) inline
Definition at line 650 of file MArrayMath.h.
References casacore::MArray< T >::array(), and fmod().
fmod() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::fmod (const T & left, const MArray< T > & right) inline
Definition at line 654 of file MArrayMath.h.
References casacore::MArray< T >::array(), and fmod().
fractile()
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::fractile (const MArray< T > & a, Float fraction, Bool sorted = False, Bool inPlace = False) inline
Return the fractile of an array.
It returns the value at the given fraction of the array. A fraction of 0.5 is the same as the median, be it that no mean of the two middle elements is taken if the array has an even nr of elements. It uses kthLargest if the array is not sorted yet.
The normal fractile function needs at least one element, so shortcut.
Definition at line 874 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::empty(), casacore::MArray< T >::flatten(), casacore::MArrayBase::hasMask(), casacore::SHARE, casacore::MArrayBase::size(), casacore::IPosition::storage(), and casacore::True.
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::MFractileFunc< T >::operator()().
imag() [1/2]
MArray<Float> casacore::MArrayMath_global_functions_MArray_mathematical_operations::imag (const MArray< Complex > & arr) inline
Definition at line 678 of file MArrayMath.h.
References casacore::MArray< T >::array().
Referenced by imag().
imag() [2/2]
MArray<Double> casacore::MArrayMath_global_functions_MArray_mathematical_operations::imag (const MArray< DComplex > & arr) inline
Definition at line 690 of file MArrayMath.h.
References casacore::MArray< T >::array(), and imag().
log()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::log (const MArray< T > & a) inline
Definition at line 558 of file MArrayMath.h.
References casacore::MArray< T >::array().
log10()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::log10 (const MArray< T > & a) inline
Definition at line 562 of file MArrayMath.h.
References casacore::MArray< T >::array().
max() [1/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::max (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 606 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
Referenced by max(), and casacore::MArrayMath_global_functions_MArray_mathematical_operations::MMaxFunc< T >::operator()().
max() [2/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::max (const MArray< T > & left, const T & right) inline
Definition at line 612 of file MArrayMath.h.
References casacore::MArray< T >::array(), and max().
max() [3/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::max (const T & left, const MArray< T > & right) inline
Definition at line 616 of file MArrayMath.h.
References casacore::MArray< T >::array(), and max().
max() [4/4]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::max (const MArray< T > & a) inline
Definition at line 757 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::mask(), and max().
mean()
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::mean (const MArray< T > & a) inline
Definition at line 770 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::nvalid(), and sum().
Referenced by avdev(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::MMeanFunc< T >::operator()(), stddev(), and variance().
median() [1/3]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::median (const MArray< T > & a, Bool sorted, Bool takeEvenMean, Bool inPlace = False) inline
The normal median function needs at least one element, so shortcut.
Median can be taken in place.
Definition at line 845 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::empty(), casacore::MArray< T >::flatten(), casacore::MArrayBase::hasMask(), casacore::SHARE, casacore::MArrayBase::size(), casacore::IPosition::storage(), and casacore::True.
Referenced by median(), medianInPlace(), and casacore::MArrayMath_global_functions_MArray_mathematical_operations::MMedianFunc< T >::operator()().
median() [2/3]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::median (const MArray< T > & a) inline
Definition at line 859 of file MArrayMath.h.
References casacore::False, median(), and casacore::MArrayBase::size().
median() [3/3]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::median (const MArray< T > & a, Bool sorted) inline
Definition at line 862 of file MArrayMath.h.
References casacore::False, median(), and casacore::MArrayBase::nelements().
medianInPlace()
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::medianInPlace (const MArray< T > & a, Bool sorted = False) inline
Definition at line 865 of file MArrayMath.h.
References median(), casacore::MArrayBase::nelements(), and casacore::True.
min() [1/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::min (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 592 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
Referenced by min(), and casacore::MArrayMath_global_functions_MArray_mathematical_operations::MMinFunc< T >::operator()().
min() [2/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::min (const MArray< T > & left, const T & right) inline
Definition at line 598 of file MArrayMath.h.
References casacore::MArray< T >::array(), and min().
min() [3/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::min (const T & left, const MArray< T > & right) inline
Definition at line 602 of file MArrayMath.h.
References casacore::MArray< T >::array(), and min().
min() [4/4]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::min (const MArray< T > & a) inline
Definition at line 744 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::mask(), and min().
operator &() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator & (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 409 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator &() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator & (const MArray< T > & left, const T & right) inline
Definition at line 447 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator &() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator & (const T & left, const MArray< T > & right) inline
Definition at line 479 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator *() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator * (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 391 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator *() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator * (const MArray< T > & left, const T & right) inline
Definition at line 435 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator *() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator * (const T & left, const MArray< T > & right) inline
Definition at line 467 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator%() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator% (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 403 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator%() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator% (const MArray< T > & left, const T & right) inline
Definition at line 443 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator%() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator% (const T & left, const MArray< T > & right) inline
Definition at line 475 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator+() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator+ (const MArray< T > & left, const MArray< T > & right) inline
Add, subtract, etc.
2 arrays or array and scalar.
Definition at line 379 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator+() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator+ (const MArray< T > & left, const T & right) inline
Definition at line 427 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator+() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator+ (const T & left, const MArray< T > & right) inline
Definition at line 459 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator-() [1/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator- (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 385 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator-() [2/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator- (const MArray< T > & left, const T & right) inline
Definition at line 431 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator-() [3/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator- (const T & left, const MArray< T > & right) inline
Definition at line 463 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator-() [4/4]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator- (const MArray< T > & a) inline
Negate the elements in an array.
Definition at line 493 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator/() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator/ (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 397 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator/() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator/ (const MArray< T > & left, const T & right) inline
Definition at line 439 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator/() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator/ (const T & left, const MArray< T > & right) inline
Definition at line 471 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator^() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator^ (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 421 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator^() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator^ (const MArray< T > & left, const T & right) inline
Definition at line 455 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator^() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator^ (const T & left, const MArray< T > & right) inline
Definition at line 487 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator|() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator| (const MArray< T > & left, const MArray< T > & right) inline
Definition at line 415 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), and casacore::MArrayBase::isNull().
operator|() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator| (const MArray< T > & left, const T & right) inline
Definition at line 451 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator|() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator| (const T & left, const MArray< T > & right) inline
Definition at line 483 of file MArrayMath.h.
References casacore::MArray< T >::array().
operator~()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::operator~ (const MArray< T > & a) inline
Take the complement of the elements in an array.
Definition at line 498 of file MArrayMath.h.
References casacore::MArray< T >::array().
partialArrayMath() [1/2]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialArrayMath (const MArray< T > & a, const IPosition & collapseAxes, const MArrayFunctorBase< T > & funcObj) inline
Do partial reduction of an MArray object.
I.e., perform the operation on a subset of the array axes (the collapse axes).
Definition at line 184 of file MArrayMath.h.
Referenced by partialAvdevs(), partialFractiles(), partialMaxs(), partialMeans(), partialMedians(), partialMins(), partialProducts(), partialRmss(), partialStddevs(), partialSums(), partialSumSqrs(), and partialVariances().
partialArrayMath() [2/2]
template<typename T , typename RES > void casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialArrayMath (MArray< RES > & res, const MArray< T > & a, const IPosition & collapseAxes, const MArrayFunctorBase< T, RES > & funcObj) inline
This can also be done as boxedArrayMath with a removeDegenerate thereafter.
It should be possible to parallelize this loop. Determine nr of iteration steps and iterate over that as an int. Do not use Array slicing, because that is not thread-safe. Instead create ArraySTLIterator directly from Array and blc,trc, so funcObj should accept iterators instead of Array. However, ArraySTLIterator needs the sliced array, not original. Maybe keep ref of itsSteps in iterator instead of array. Hmm, tricky for median and fractile. Better to make Array copy ctor thread-safe (thus use boost shared_ptr).
IPosition shape(a.array().shape().removeAxes (collapseAxes));
Definition at line 193 of file MArrayMath.h.
References AlwaysAssert, casacore::MArray< T >::array(), casacore::Array< T >::data(), casacore::False, casacore::MArrayBase::hasMask(), casacore::MArrayBase::mask(), casacore::mask(), casacore::MArray< T >::resize(), casacore::MArrayBase::setMask(), casacore::shape(), and casacore::True.
partialAvdevs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialAvdevs (const MArray< T > & a, const IPosition & collapseAxes) inline
Definition at line 982 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialFractiles()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialFractiles (const MArray< T > & a, const IPosition & collapseAxes, Float fraction, Bool inPlace = False) inline
Definition at line 1019 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::False, casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialMaxs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialMaxs (const MArray< T > & a, const IPosition & collapseAxes) inline
Definition at line 936 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialMeans()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialMeans (const MArray< T > & a, const IPosition & collapseAxes) inline
Definition at line 947 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialMedians()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialMedians (const MArray< T > & a, const IPosition & collapseAxes, Bool takeEvenMean = False, Bool inPlace = False) inline
Definition at line 1004 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::False, casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialMins()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialMins (const MArray< T > & a, const IPosition & collapseAxes) inline
Definition at line 925 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialProducts()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialProducts (const MArray< T > & a, const IPosition & collapseAxes) inline
Definition at line 914 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialRmss()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialRmss (const MArray< T > & a, const IPosition & collapseAxes) inline
Definition at line 993 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialStddevs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialStddevs (const MArray< T > & a, const IPosition & collapseAxes, uInt ddof) inline
Definition at line 970 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialSums()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialSums (const MArray< T > & a, const IPosition & collapseAxes) inline
Get partial sums, etc.
Definition at line 891 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialSumSqrs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialSumSqrs (const MArray< T > & a, const IPosition & collapseAxes) inline
Definition at line 902 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
partialVariances()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::partialVariances (const MArray< T > & a, const IPosition & collapseAxes, uInt ddof) inline
Definition at line 958 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and partialArrayMath().
phase() [1/2]
MArray<Float> casacore::MArrayMath_global_functions_MArray_mathematical_operations::phase (const MArray< Complex > & arr) inline
Definition at line 684 of file MArrayMath.h.
References casacore::MArray< T >::array().
Referenced by phase().
phase() [2/2]
MArray<Double> casacore::MArrayMath_global_functions_MArray_mathematical_operations::phase (const MArray< DComplex > & arr) inline
Definition at line 696 of file MArrayMath.h.
References casacore::MArray< T >::array(), and phase().
pow() [1/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::pow (const MArray< T > & a, const MArray< T > & exp) inline
Definition at line 578 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::combineMask(), exp(), and casacore::MArrayBase::isNull().
Referenced by pow().
pow() [2/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::pow (const T & a, const MArray< T > & exp) inline
Definition at line 584 of file MArrayMath.h.
References exp(), and pow().
pow() [3/3]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::pow (const MArray< T > & a, const Double & exp) inline
Definition at line 588 of file MArrayMath.h.
References casacore::MArray< T >::array(), exp(), and pow().
product()
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::product (const MArray< T > & a) inline
Definition at line 731 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::mask().
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::MProductFunc< T >::operator()().
real() [1/2]
MArray<Float> casacore::MArrayMath_global_functions_MArray_mathematical_operations::real (const MArray< Complex > & arr) inline
Definition at line 675 of file MArrayMath.h.
References casacore::MArray< T >::array().
Referenced by real().
real() [2/2]
MArray<Double> casacore::MArrayMath_global_functions_MArray_mathematical_operations::real (const MArray< DComplex > & arr) inline
Definition at line 687 of file MArrayMath.h.
References casacore::MArray< T >::array(), and real().
rms()
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::rms (const MArray< T > & a) inline
Definition at line 831 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::mask(), casacore::MArrayBase::nvalid(), sqrt(), and sum().
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::MRmsFunc< T >::operator()().
round()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::round (const MArray< T > & a) inline
Definition at line 628 of file MArrayMath.h.
References casacore::MArray< T >::array().
sign()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::sign (const MArray< T > & a) inline
Definition at line 632 of file MArrayMath.h.
References casacore::MArray< T >::array().
sin()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::sin (const MArray< T > & a) inline
Perform mathematical function on each element in an array.
Definition at line 504 of file MArrayMath.h.
References casacore::MArray< T >::array().
sinh()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::sinh (const MArray< T > & a) inline
Definition at line 516 of file MArrayMath.h.
References casacore::MArray< T >::array().
slidingArrayMath() [1/2]
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath (const MArray< T > & array, const IPosition & halfBoxShape, const MArrayFunctorBase< T > & funcObj, Bool fillEdge = True) inline
Definition at line 303 of file MArrayMath.h.
References casacore::array().
Referenced by slidingAvdevs(), slidingFractiles(), slidingMaxs(), slidingMeans(), slidingMedians(), slidingMins(), slidingProducts(), slidingRmss(), slidingStddevs(), slidingSums(), slidingSumSqrs(), and slidingVariances().
slidingArrayMath() [2/2]
template<typename T , typename RES > void casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingArrayMath (MArray< RES > & res, const MArray< T > & array, const IPosition & halfBoxShape, const MArrayFunctorBase< T, RES > & funcObj, Bool fillEdge = True) inline
Loop through all data and assemble as needed.
Definition at line 313 of file MArrayMath.h.
References AlwaysAssert, casacore::MArray< T >::array(), casacore::array(), casacore::False, casacore::fillSlidingShape(), casacore::MArrayBase::mask(), casacore::mask(), casacore::ndim(), casacore::MArray< T >::resize(), casacore::MArrayBase::setMask(), casacore::shape(), and casacore::True.
slidingAvdevs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingAvdevs (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Definition at line 1138 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingFractiles()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingFractiles (const MArray< T > & a, const IPosition & halfBoxSize, Float fraction, Bool inPlace = False, Bool fillEdge = True) inline
Definition at line 1181 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::False, casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingMaxs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingMaxs (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Definition at line 1086 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingMeans()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingMeans (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Definition at line 1098 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingMedians()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingMedians (const MArray< T > & a, const IPosition & halfBoxSize, Bool takeEvenMean = False, Bool inPlace = False, Bool fillEdge = True) inline
Definition at line 1162 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::False, casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingMins()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingMins (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Definition at line 1074 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingProducts()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingProducts (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Definition at line 1062 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingRmss()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingRmss (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Definition at line 1150 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingStddevs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingStddevs (const MArray< T > & a, const IPosition & halfBoxSize, uInt ddof, Bool fillEdge = True) inline
Definition at line 1124 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingSums()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingSums (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Get sliding sums.
Definition at line 1038 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingSumSqrs()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingSumSqrs (const MArray< T > & a, const IPosition & halfBoxSize, Bool fillEdge = True) inline
Definition at line 1050 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
slidingVariances()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::slidingVariances (const MArray< T > & a, const IPosition & halfBoxSize, uInt ddof, Bool fillEdge = True) inline
Definition at line 1110 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::isNull(), and slidingArrayMath().
sqrt()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::sqrt (const MArray< T > & a) inline
Definition at line 566 of file MArrayMath.h.
References casacore::MArray< T >::array().
Referenced by rms(), and stddev().
square()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::square (const MArray< T > & a) inline
Definition at line 570 of file MArrayMath.h.
References casacore::MArray< T >::array().
stddev() [1/2]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::stddev (const MArray< T > & a, uInt ddof) inline
Definition at line 799 of file MArrayMath.h.
References sqrt(), and variance().
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::MStddevFunc< T >::operator()().
stddev() [2/2]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::stddev (const MArray< T > & a, T mean, uInt ddof) inline
Definition at line 805 of file MArrayMath.h.
References mean(), sqrt(), and variance().
sum()
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::sum (const MArray< T > & a) inline
Reduce an array to a scalar using the unmasked elements only.
The result is 0 if there are no unmasked elements.
Definition at line 705 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::mask().
Referenced by avdev(), mean(), casacore::MArrayMath_global_functions_MArray_mathematical_operations::MSumFunc< T >::operator()(), rms(), and variance().
sumsqr()
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::sumsqr (const MArray< T > & a) inline
Definition at line 718 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), and casacore::MArrayBase::mask().
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::MSumSqrFunc< T >::operator()().
tan()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::tan (const MArray< T > & a) inline
Definition at line 512 of file MArrayMath.h.
References casacore::MArray< T >::array().
tanh()
template<typename T > MArray<T> casacore::MArrayMath_global_functions_MArray_mathematical_operations::tanh (const MArray< T > & a) inline
Definition at line 524 of file MArrayMath.h.
References casacore::MArray< T >::array().
variance() [1/2]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::variance (const MArray< T > & a, T mean, uInt ddof) inline
Definition at line 779 of file MArrayMath.h.
References casacore::MArray< T >::array(), casacore::Array< T >::begin(), casacore::Array< T >::cbegin(), casacore::ArrayBase::contiguousStorage(), casacore::MArrayBase::hasMask(), casacore::MArrayBase::mask(), mean(), casacore::MArrayBase::nvalid(), and sum().
Referenced by casacore::MArrayMath_global_functions_MArray_mathematical_operations::MVarianceFunc< T >::operator()(), stddev(), and variance().
variance() [2/2]
template<typename T > T casacore::MArrayMath_global_functions_MArray_mathematical_operations::variance (const MArray< T > & a, uInt ddof) inline
Definition at line 793 of file MArrayMath.h.
References mean(), and variance().
The documentation for this struct was generated from the following file:
tables/TaQL/MArrayMath.h