casacore: casacore::VirtScaCol_global_functions_getVirtualScalarColumn Struct Reference
casacore::VirtScaCol_global_functions_getVirtualScalarColumn Struct Reference
tables package (libcasa_tables) » DataMan_module
Global functions to get or put data of a virtual column.
#include <VirtScaCol.h>
Public Member Functions
template<class T >
void getVirtualScalarColumn (VirtualScalarColumn< T > *col, uInt rownr, T *dataPtr)
void getVirtualScalarColumn (DataManagerColumn *col, uInt, void *)
template<class T >
void putVirtualScalarColumn (VirtualScalarColumn< T > *col, uInt rownr, const T *dataPtr)
void putVirtualScalarColumn (DataManagerColumn *col, uInt, const void *)
Detailed Description
Global functions to get or put data of a virtual column.
Synopsis
Definition at line 259 of file VirtScaCol.h.
Member Function Documentation
getVirtualScalarColumn() [1/2]
template<class T > void casacore::VirtScaCol_global_functions_getVirtualScalarColumn::getVirtualScalarColumn (VirtualScalarColumn< T > * col, uInt rownr, T * dataPtr) inline
Definition at line 261 of file VirtScaCol.h.
References casacore::VirtualScalarColumn< T >::get().
getVirtualScalarColumn() [2/2]
void casacore::VirtScaCol_global_functions_getVirtualScalarColumn::getVirtualScalarColumn (DataManagerColumn * col, uInt , void *) inline
Definition at line 264 of file VirtScaCol.h.
References casacore::DataManagerColumn::throwGet().
putVirtualScalarColumn() [1/2]
template<class T > void casacore::VirtScaCol_global_functions_getVirtualScalarColumn::putVirtualScalarColumn (VirtualScalarColumn< T > * col, uInt rownr, const T * dataPtr) inline
Definition at line 268 of file VirtScaCol.h.
References casacore::VirtualScalarColumn< T >::put().
putVirtualScalarColumn() [2/2]
void casacore::VirtScaCol_global_functions_getVirtualScalarColumn::putVirtualScalarColumn (DataManagerColumn * col, uInt , const void *) inline
Definition at line 271 of file VirtScaCol.h.
References casacore::DataManagerColumn::throwPut().
The documentation for this struct was generated from the following file:
tables/DataMan/VirtScaCol.h