casacore: casacore::new_del_allocator< T > Struct Template Reference
casacore::new_del_allocator< T > Struct Template Reference
#include <Allocator.h>
Classes
struct rebind
Public Types
typedef std11_allocator< T > Super
typedef Super::size_type size_type
typedef Super::difference_type difference_type
typedef Super::pointer pointer
typedef Super::const_pointer const_pointer
typedef Super::reference reference
typedef Super::const_reference const_reference
typedef Super::value_type value_type
Public Member Functions
new_del_allocator () noexcept
new_del_allocator (const new_del_allocator &other) noexcept
template<typename TOther >
new_del_allocator (const new_del_allocator< TOther > &) noexcept
~new_del_allocator () noexcept
pointer allocate (size_type elements, const void *=0)
void deallocate (pointer ptr, size_type)
template<typename U , typename... Args>
void construct (U *, Args &&...)
template<typename U >
void construct (U *ptr, U &&value)
template<typename U >
void construct (U *ptr, U &value)
template<typename U >
void construct (U *ptr, U const &value)
template<typename U >
void destroy (U *)
Detailed Description
template<typename T>
struct casacore::new_del_allocator< T >
Definition at line 140 of file Allocator.h.
Member Typedef Documentation
const_pointer
template<typename T > typedef Super::const_pointer casacore::new_del_allocator< T >::const_pointer
Definition at line 145 of file Allocator.h.
const_reference
template<typename T > typedef Super::const_reference casacore::new_del_allocator< T >::const_reference
Definition at line 147 of file Allocator.h.
difference_type
template<typename T > typedef Super::difference_type casacore::new_del_allocator< T >::difference_type
Definition at line 143 of file Allocator.h.
pointer
template<typename T > typedef Super::pointer casacore::new_del_allocator< T >::pointer
Definition at line 144 of file Allocator.h.
reference
template<typename T > typedef Super::reference casacore::new_del_allocator< T >::reference
Definition at line 146 of file Allocator.h.
size_type
template<typename T > typedef Super::size_type casacore::new_del_allocator< T >::size_type
Definition at line 142 of file Allocator.h.
Super
template<typename T > typedef std11_allocator<T> casacore::new_del_allocator< T >::Super
Definition at line 141 of file Allocator.h.
value_type
template<typename T > typedef Super::value_type casacore::new_del_allocator< T >::value_type
Definition at line 148 of file Allocator.h.
Constructor & Destructor Documentation
new_del_allocator() [1/3]
template<typename T > casacore::new_del_allocator< T >::new_del_allocator () inline noexcept
Definition at line 154 of file Allocator.h.
new_del_allocator() [2/3]
template<typename T > casacore::new_del_allocator< T >::new_del_allocator (const new_del_allocator< T > & other) inline noexcept
Definition at line 157 of file Allocator.h.
new_del_allocator() [3/3]
template<typename T > template<typename TOther > casacore::new_del_allocator< T >::new_del_allocator (const new_del_allocator< TOther > &) inline noexcept
Definition at line 162 of file Allocator.h.
~new_del_allocator()
template<typename T > casacore::new_del_allocator< T >::~new_del_allocator () inline noexcept
Definition at line 165 of file Allocator.h.
Member Function Documentation
allocate()
template<typename T > pointer casacore::new_del_allocator< T >::allocate (size_type elements, const void * = 0) inline
Definition at line 168 of file Allocator.h.
construct() [1/4]
template<typename T > template<typename U , typename... Args> void casacore::new_del_allocator< T >::construct (U * , Args && ...) inline
Definition at line 179 of file Allocator.h.
construct() [2/4]
template<typename T > template<typename U > void casacore::new_del_allocator< T >::construct (U * ptr, U && value) inline
Definition at line 181 of file Allocator.h.
References casacore::value().
construct() [3/4]
template<typename T > template<typename U > void casacore::new_del_allocator< T >::construct (U * ptr, U & value) inline
Definition at line 185 of file Allocator.h.
References casacore::value().
construct() [4/4]
template<typename T > template<typename U > void casacore::new_del_allocator< T >::construct (U * ptr, U const & value) inline
Definition at line 189 of file Allocator.h.
References casacore::value().
deallocate()
template<typename T > void casacore::new_del_allocator< T >::deallocate (pointer ptr, size_type) inline
Definition at line 175 of file Allocator.h.
destroy()
template<typename T > template<typename U > void casacore::new_del_allocator< T >::destroy (U *) inline
Definition at line 194 of file Allocator.h.
The documentation for this struct was generated from the following file:
casa/Containers/Allocator.h