casacore: ArrayCopy< Complex > Struct Template Reference
ArrayCopy< Complex > Struct Template Reference
#include <PycArrayComH.h>
Static Public Member Functions
static void toPy (void *to, const Complex *from, size_t nr)
static void fromPy (Complex *to, const void *from, size_t nr)
static Array< Complex > toArray (const IPosition &shape, void *data, bool copy)
Detailed Description
template<>
struct ArrayCopy< Complex >
Definition at line 56 of file PycArrayComH.h.
Member Function Documentation
fromPy()
void ArrayCopy< Complex >::fromPy (Complex * to, const void * from, size_t nr) static
Definition at line 197 of file PycArrayComCC.h.
toArray()
Array< Complex > ArrayCopy< Complex >::toArray (const IPosition & shape, void * data, bool copy) static
Definition at line 204 of file PycArrayComCC.h.
References casacore::copy(), ArrayCopy< T >::fromPy(), casacore::shape(), and casacore::SHARE.
toPy()
void ArrayCopy< Complex >::toPy (void * to, const Complex * from, size_t nr) static
Definition at line 190 of file PycArrayComCC.h.
The documentation for this struct was generated from the following files:
python/Converters/PycArrayComH.h
python/Converters/PycArrayComCC.h