casacore: casacore::BlockIO_global_functions_BlockIO Struct Reference
casacore::BlockIO_global_functions_BlockIO Struct Reference
Containers_module
IO functions for Block.
#include <BlockIO.h>
Public Member Functions
template<class T >
void putBlock (AipsIO &, const Block< T > &, Int nr)
These functions allow the user to read and write Blocks from the AipsIO stream.
template<class T >
void putBlock (AipsIO &ios, const Block< T > &blk)
template<class T >
void getBlock (AipsIO &, Block< T > &)
template<class T >
void showBlock (std::ostream &, const Block< T > &, Int nr)
These functions allow the user to write Blocks out to a standard ostream.
template<class T >
void showBlock (std::ostream &ios, const Block< T > &blk)
template<class T >
AipsIO & operator<< (AipsIO &ios, const Block< T > &blk)
These are the standard shift operators for writing an entire Block out to a stream.
template<class T >
AipsIO & operator>> (AipsIO &ios, Block< T > &blk)
template<class T >
std::ostream & operator<< (std::ostream &ios, const Block< T > &blk)
Detailed Description
IO functions for Block.
Review Status
Reviewed By:
UNKNOWN
Date Reviewed:
before2004/08/25
Intended use:
Public interface
Synopsis
These functions allow the user to write either an entire or a partial Block out to an ostream or to AipsIO. These functions provide simple storage and display capabilities for Block.
Definition at line 58 of file BlockIO.h.
Member Function Documentation
template<class T > void casacore::BlockIO_global_functions_BlockIO::getBlock (AipsIO & , Block< T > &)
template<class T > AipsIO& casacore::BlockIO_global_functions_BlockIO::operator<< (AipsIO & ios, const Block< T > & blk) inline
These are the standard shift operators for writing an entire Block out to a stream.
Shift operators are provided to write the block out to either AipsIO or ostream. A shift operator is also provided for reading a Block in from AipsIO.
Note: STL containers like vector and list are written in the same way as a Block, so they can be written one way and read back the other;
Definition at line 110 of file BlockIO.h.
References casacore::putBlock().
template<class T > std::ostream& casacore::BlockIO_global_functions_BlockIO::operator<< (std::ostream & ios, const Block< T > & blk) inline
Definition at line 122 of file BlockIO.h.
References casacore::showBlock().
template<class T > AipsIO& casacore::BlockIO_global_functions_BlockIO::operator>> (AipsIO & ios, Block< T > & blk) inline
Definition at line 116 of file BlockIO.h.
References casacore::getBlock().
template<class T > void casacore::BlockIO_global_functions_BlockIO::putBlock (AipsIO & , const Block< T > & , Int nr)
These functions allow the user to read and write Blocks from the AipsIO stream.
putBlock writes the Block to the stream. If a number, nr, of elements is specified, only the first nr elements will be written out to AipsI0.
getBlock reads a Block in from an AipsIO stream.
template<class T > void casacore::BlockIO_global_functions_BlockIO::putBlock (AipsIO & ios, const Block< T > & blk) inline
Definition at line 80 of file BlockIO.h.
References casacore::Block< T >::nelements(), and casacore::putBlock().
template<class T > void casacore::BlockIO_global_functions_BlockIO::showBlock (std::ostream & , const Block< T > & , Int nr)
These functions allow the user to write Blocks out to a standard ostream.
The user can either write the entire Block out to the stream, or if a number of elements, nr, is specified, only the first nr elements of the Block will be written out.
template<class T > void casacore::BlockIO_global_functions_BlockIO::showBlock (std::ostream & ios, const Block< T > & blk) inline
Definition at line 96 of file BlockIO.h.
References casacore::Block< T >::nelements(), and casacore::showBlock().
The documentation for this struct was generated from the following file:
casa/Containers/BlockIO.h