casacore: ArrayCopy< DComplex > Struct Template Reference
ArrayCopy< DComplex > Struct Template Reference
#include <PycArrayComH.h>
Static Public Member Functions
static void toPy (void *to, const DComplex *from, size_t nr)
static void fromPy (DComplex *to, const void *from, size_t nr)
static Array< DComplex > toArray (const IPosition &shape, void *data, bool copy)
Detailed Description
template<>
struct ArrayCopy< DComplex >
Definition at line 64 of file PycArrayComH.h.
Member Function Documentation
fromPy()
void ArrayCopy< DComplex >::fromPy (DComplex * to, const void * from, size_t nr) static
Definition at line 225 of file PycArrayComCC.h.
toArray()
Array< DComplex > ArrayCopy< DComplex >::toArray (const IPosition & shape, void * data, bool copy) static
Definition at line 232 of file PycArrayComCC.h.
References casacore::copy(), ArrayCopy< T >::fromPy(), casacore::shape(), and casacore::SHARE.
toPy()
void ArrayCopy< DComplex >::toPy (void * to, const DComplex * from, size_t nr) static
Definition at line 218 of file PycArrayComCC.h.
The documentation for this struct was generated from the following files:
python/Converters/PycArrayComH.h
python/Converters/PycArrayComCC.h