var searchData=
[
  ['radialvelocityengine',['RadialVelocityEngine',['../classcasacore_1_1RadialVelocityEngine.html',1,'casacore']]],
  ['radialvelocityudf',['RadialVelocityUDF',['../classcasacore_1_1RadialVelocityUDF.html',1,'casacore']]],
  ['random',['Random',['../classcasacore_1_1Random.html',1,'casacore']]],
  ['rawdataconversion',['RawDataConversion',['../classcasacore_1_1RawDataConversion.html',1,'casacore']]],
  ['rawio',['RawIO',['../classcasacore_1_1RawIO.html',1,'casacore']]],
  ['re_5fpattern_5fbuffer',['re_pattern_buffer',['../structcasacore_1_1re__pattern__buffer.html',1,'casacore']]],
  ['re_5fregisters',['re_registers',['../structcasacore_1_1re__registers.html',1,'casacore']]],
  ['readasciitable',['ReadAsciiTable',['../classcasacore_1_1ReadAsciiTable.html',1,'casacore']]],
  ['readasciitable_5fglobal_5ffunctions_5freadasciitable',['ReadAsciiTable_global_functions_readAsciiTable',['../structcasacore_1_1ReadAsciiTable__global__functions__readAsciiTable.html',1,'casacore']]],
  ['readonlyarrayiterator',['ReadOnlyArrayIterator',['../classcasacore_1_1ReadOnlyArrayIterator.html',1,'casacore']]],
  ['readonlymatrixiterator',['ReadOnlyMatrixIterator',['../classcasacore_1_1ReadOnlyMatrixIterator.html',1,'casacore']]],
  ['readonlyvectoriterator',['ReadOnlyVectorIterator',['../classcasacore_1_1ReadOnlyVectorIterator.html',1,'casacore']]],
  ['real',['Real',['../structcasacore_1_1Real.html',1,'casacore::Real&lt; T, RES &gt;'],['../structcasacore_1_1LSQFit_1_1Real.html',1,'casacore::LSQFit::Real']]],
  ['rebind',['rebind',['../structcasacore_1_1casacore__allocator_1_1rebind.html',1,'casacore::casacore_allocator&lt; T, ALIGNMENT &gt;::rebind&lt; TOther &gt;'],['../structcasacore_1_1new__del__allocator_1_1rebind.html',1,'casacore::new_del_allocator&lt; T &gt;::rebind&lt; TOther &gt;']]],
  ['rebinimage',['RebinImage',['../classcasacore_1_1RebinImage.html',1,'casacore']]],
  ['rebinlattice',['RebinLattice',['../classcasacore_1_1RebinLattice.html',1,'casacore']]],
  ['record',['Record',['../classcasacore_1_1Record.html',1,'casacore']]],
  ['recorddesc',['RecordDesc',['../classcasacore_1_1RecordDesc.html',1,'casacore']]],
  ['recorddescrep',['RecordDescRep',['../classcasacore_1_1RecordDescRep.html',1,'casacore']]],
  ['recordexpr_5fglobal_5ffunctions_5frecordexpr',['RecordExpr_global_functions_RecordExpr',['../structcasacore_1_1RecordExpr__global__functions__RecordExpr.html',1,'casacore']]],
  ['recordfieldcopier',['RecordFieldCopier',['../classcasacore_1_1RecordFieldCopier.html',1,'casacore']]],
  ['recordfieldid',['RecordFieldId',['../classcasacore_1_1RecordFieldId.html',1,'casacore']]],
  ['recordfieldptr',['RecordFieldPtr',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20bool_20_3e',['RecordFieldPtr&lt; Bool &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20bool_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; Bool &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20casacore_3a_3astring_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; casacore::String &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20complex_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; Complex &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20dcomplex_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; DComplex &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20double_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; Double &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20float_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; Float &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20int_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; Int &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20recordtype_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; recordType &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20short_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; Short &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20t_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; T &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3aarray_3c_20uchar_20_3e_20_3e',['RecordFieldPtr&lt; casacore::Array&lt; uChar &gt; &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20casacore_3a_3astring_20_3e',['RecordFieldPtr&lt; casacore::String &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20complex_20_3e',['RecordFieldPtr&lt; Complex &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20dcomplex_20_3e',['RecordFieldPtr&lt; DComplex &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20double_20_3e',['RecordFieldPtr&lt; Double &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20float_20_3e',['RecordFieldPtr&lt; Float &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20int_20_3e',['RecordFieldPtr&lt; Int &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20intype_20_3e',['RecordFieldPtr&lt; inType &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20outtype_20_3e',['RecordFieldPtr&lt; outType &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20recordtype_20_3e',['RecordFieldPtr&lt; recordType &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20short_20_3e',['RecordFieldPtr&lt; Short &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldptr_3c_20uchar_20_3e',['RecordFieldPtr&lt; uChar &gt;',['../classcasacore_1_1RecordFieldPtr.html',1,'casacore']]],
  ['recordfieldwriter',['RecordFieldWriter',['../classcasacore_1_1RecordFieldWriter.html',1,'casacore']]],
  ['recordgram',['RecordGram',['../classcasacore_1_1RecordGram.html',1,'casacore']]],
  ['recordgram_5fglobal_5ffunctions_5frecordgramfunctions',['RecordGram_global_functions_RecordGramFunctions',['../structcasacore_1_1RecordGram__global__functions__RecordGramFunctions.html',1,'casacore']]],
  ['recordgramval',['RecordGramVal',['../classcasacore_1_1RecordGramVal.html',1,'casacore']]],
  ['recordinterface',['RecordInterface',['../classcasacore_1_1RecordInterface.html',1,'casacore']]],
  ['recordnotice',['RecordNotice',['../classcasacore_1_1RecordNotice.html',1,'casacore']]],
  ['recordrep',['RecordRep',['../classcasacore_1_1RecordRep.html',1,'casacore']]],
  ['recordtransformable',['RecordTransformable',['../classcasacore_1_1RecordTransformable.html',1,'casacore']]],
  ['refcolumn',['RefColumn',['../classcasacore_1_1RefColumn.html',1,'casacore']]],
  ['refrep',['RefRep',['../classcasacore_1_1MeasRef_1_1RefRep.html',1,'casacore::MeasRef']]],
  ['refrows',['RefRows',['../classcasacore_1_1RefRows.html',1,'casacore']]],
  ['refrowssliceiter',['RefRowsSliceIter',['../classcasacore_1_1RefRowsSliceIter.html',1,'casacore']]],
  ['reftable',['RefTable',['../classcasacore_1_1RefTable.html',1,'casacore']]],
  ['regex',['Regex',['../classcasacore_1_1Regex.html',1,'casacore']]],
  ['regexbase',['RegexBase',['../classcasacore_1_1RegexBase.html',1,'casacore']]],
  ['regionhandler',['RegionHandler',['../classcasacore_1_1RegionHandler.html',1,'casacore']]],
  ['regionhandlerhdf5',['RegionHandlerHDF5',['../classcasacore_1_1RegionHandlerHDF5.html',1,'casacore']]],
  ['regionhandlermemory',['RegionHandlerMemory',['../classcasacore_1_1RegionHandlerMemory.html',1,'casacore']]],
  ['regionhandlertable',['RegionHandlerTable',['../classcasacore_1_1RegionHandlerTable.html',1,'casacore']]],
  ['regionmanager',['RegionManager',['../classcasacore_1_1RegionManager.html',1,'casacore']]],
  ['regiontype',['RegionType',['../classcasacore_1_1RegionType.html',1,'casacore']]],
  ['register_5fglobal_5ffunctions_5fregister',['Register_global_functions_register',['../structcasacore_1_1Register__global__functions__register.html',1,'casacore']]],
  ['regsequence',['RegSequence',['../classcasacore_1_1RegSequence.html',1,'casacore']]],
  ['regularfile',['RegularFile',['../classcasacore_1_1RegularFile.html',1,'casacore']]],
  ['regularfileio',['RegularFileIO',['../classcasacore_1_1RegularFileIO.html',1,'casacore']]],
  ['reservedfitskeyword',['ReservedFitsKeyword',['../classcasacore_1_1ReservedFitsKeyword.html',1,'casacore']]],
  ['reservedfitskeywordcollection',['ReservedFitsKeywordCollection',['../classcasacore_1_1ReservedFitsKeywordCollection.html',1,'casacore']]],
  ['retypedarrayengine',['RetypedArrayEngine',['../classcasacore_1_1RetypedArrayEngine.html',1,'casacore']]],
  ['retypedarraysetget_5fglobal_5ffunctions_5fretypedarrayenginesetget',['RetypedArraySetGet_global_functions_RetypedArrayEngineSetGet',['../structcasacore_1_1RetypedArraySetGet__global__functions__RetypedArrayEngineSetGet.html',1,'casacore']]],
  ['rferror',['RFError',['../classcasacore_1_1RFError.html',1,'casacore']]],
  ['rfreader',['RFReader',['../classcasacore_1_1RFReader.html',1,'casacore']]],
  ['rfreaderwriter',['RFReaderWriter',['../classcasacore_1_1RFReaderWriter.html',1,'casacore']]],
  ['rfwriter',['RFWriter',['../classcasacore_1_1RFWriter.html',1,'casacore']]],
  ['rigidvector',['RigidVector',['../classcasacore_1_1RigidVector.html',1,'casacore']]],
  ['rigidvector_5fglobal_5ffunctions_5fmath',['RigidVector_global_functions_math',['../structcasacore_1_1RigidVector__global__functions__math.html',1,'casacore']]],
  ['rmsfunc',['RmsFunc',['../classcasacore_1_1ArrayPartMath__global__functions__Array__partial__operations_1_1RmsFunc.html',1,'casacore::ArrayPartMath_global_functions_Array_partial_operations']]],
  ['rng',['RNG',['../classcasacore_1_1RNG.html',1,'casacore']]],
  ['ro_5flatticeiterator',['RO_LatticeIterator',['../classcasacore_1_1RO__LatticeIterator.html',1,'casacore']]],
  ['ro_5fmaskedlatticeiterator',['RO_MaskedLatticeIterator',['../classcasacore_1_1RO__MaskedLatticeIterator.html',1,'casacore']]],
  ['rodatamanaccessor',['RODataManAccessor',['../classcasacore_1_1RODataManAccessor.html',1,'casacore']]],
  ['roincrementalstmanaccessor',['ROIncrementalStManAccessor',['../classcasacore_1_1ROIncrementalStManAccessor.html',1,'casacore']]],
  ['romsantennacolumns',['ROMSAntennaColumns',['../classcasacore_1_1ROMSAntennaColumns.html',1,'casacore']]],
  ['romscolumns',['ROMSColumns',['../classcasacore_1_1ROMSColumns.html',1,'casacore']]],
  ['romsdatadesccolumns',['ROMSDataDescColumns',['../classcasacore_1_1ROMSDataDescColumns.html',1,'casacore']]],
  ['romsdopplercolumns',['ROMSDopplerColumns',['../classcasacore_1_1ROMSDopplerColumns.html',1,'casacore']]],
  ['romsfeedcolumns',['ROMSFeedColumns',['../classcasacore_1_1ROMSFeedColumns.html',1,'casacore']]],
  ['romsfieldcolumns',['ROMSFieldColumns',['../classcasacore_1_1ROMSFieldColumns.html',1,'casacore']]],
  ['romsflagcmdcolumns',['ROMSFlagCmdColumns',['../classcasacore_1_1ROMSFlagCmdColumns.html',1,'casacore']]],
  ['romsfreqoffsetcolumns',['ROMSFreqOffsetColumns',['../classcasacore_1_1ROMSFreqOffsetColumns.html',1,'casacore']]],
  ['romshistorycolumns',['ROMSHistoryColumns',['../classcasacore_1_1ROMSHistoryColumns.html',1,'casacore']]],
  ['romsmaincolumns',['ROMSMainColumns',['../classcasacore_1_1ROMSMainColumns.html',1,'casacore']]],
  ['romsobservationcolumns',['ROMSObservationColumns',['../classcasacore_1_1ROMSObservationColumns.html',1,'casacore']]],
  ['romspointingcolumns',['ROMSPointingColumns',['../classcasacore_1_1ROMSPointingColumns.html',1,'casacore']]],
  ['romspolarizationcolumns',['ROMSPolarizationColumns',['../classcasacore_1_1ROMSPolarizationColumns.html',1,'casacore']]],
  ['romsprocessorcolumns',['ROMSProcessorColumns',['../classcasacore_1_1ROMSProcessorColumns.html',1,'casacore']]],
  ['romssourcecolumns',['ROMSSourceColumns',['../classcasacore_1_1ROMSSourceColumns.html',1,'casacore']]],
  ['romsspwindowcolumns',['ROMSSpWindowColumns',['../classcasacore_1_1ROMSSpWindowColumns.html',1,'casacore']]],
  ['romsstatecolumns',['ROMSStateColumns',['../classcasacore_1_1ROMSStateColumns.html',1,'casacore']]],
  ['romssyscalcolumns',['ROMSSysCalColumns',['../classcasacore_1_1ROMSSysCalColumns.html',1,'casacore']]],
  ['romsweathercolumns',['ROMSWeatherColumns',['../classcasacore_1_1ROMSWeatherColumns.html',1,'casacore']]],
  ['rorecordfieldptr',['RORecordFieldPtr',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20bool_20_3e',['RORecordFieldPtr&lt; Bool &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20bool_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; Bool &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20casacore_3a_3astring_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; casacore::String &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20complex_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; Complex &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20dcomplex_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; DComplex &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20double_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; Double &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20float_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; Float &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20int_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; Int &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20recordtype_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; recordType &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20short_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; Short &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20t_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; T &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3aarray_3c_20uchar_20_3e_20_3e',['RORecordFieldPtr&lt; casacore::Array&lt; uChar &gt; &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20casacore_3a_3astring_20_3e',['RORecordFieldPtr&lt; casacore::String &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20complex_20_3e',['RORecordFieldPtr&lt; Complex &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20dcomplex_20_3e',['RORecordFieldPtr&lt; DComplex &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20double_20_3e',['RORecordFieldPtr&lt; Double &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20float_20_3e',['RORecordFieldPtr&lt; Float &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20int_20_3e',['RORecordFieldPtr&lt; Int &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20intype_20_3e',['RORecordFieldPtr&lt; inType &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20recordtype_20_3e',['RORecordFieldPtr&lt; recordType &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20short_20_3e',['RORecordFieldPtr&lt; Short &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rorecordfieldptr_3c_20uchar_20_3e',['RORecordFieldPtr&lt; uChar &gt;',['../classcasacore_1_1RORecordFieldPtr.html',1,'casacore']]],
  ['rostandardstmanaccessor',['ROStandardStManAccessor',['../classcasacore_1_1ROStandardStManAccessor.html',1,'casacore']]],
  ['rotablerow',['ROTableRow',['../classcasacore_1_1ROTableRow.html',1,'casacore']]],
  ['rotiledstmanaccessor',['ROTiledStManAccessor',['../classcasacore_1_1ROTiledStManAccessor.html',1,'casacore']]],
  ['rotmatrix',['RotMatrix',['../classcasacore_1_1RotMatrix.html',1,'casacore']]],
  ['round',['Round',['../structcasacore_1_1Round.html',1,'casacore']]],
  ['rowcopier',['RowCopier',['../classcasacore_1_1RowCopier.html',1,'casacore']]]
];
