var searchData=
[
  ['sampledfunctional',['SampledFunctional',['../classcasacore_1_1SampledFunctional.html',1,'casacore']]],
  ['sampledfunctional_3c_20t_20_3e',['SampledFunctional&lt; T &gt;',['../classcasacore_1_1SampledFunctional.html',1,'casacore']]],
  ['scalarcolumn',['ScalarColumn',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20bool_20_3e',['ScalarColumn&lt; Bool &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20double_20_3e',['ScalarColumn&lt; Double &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20float_20_3e',['ScalarColumn&lt; Float &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20int_20_3e',['ScalarColumn&lt; Int &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20string_20_3e',['ScalarColumn&lt; String &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20tablerecord_20_3e',['ScalarColumn&lt; TableRecord &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20uint_20_3e',['ScalarColumn&lt; uInt &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumn_3c_20virtualtype_20_3e',['ScalarColumn&lt; VirtualType &gt;',['../classcasacore_1_1ScalarColumn.html',1,'casacore']]],
  ['scalarcolumndata',['ScalarColumnData',['../classcasacore_1_1ScalarColumnData.html',1,'casacore']]],
  ['scalarcolumndesc',['ScalarColumnDesc',['../classcasacore_1_1ScalarColumnDesc.html',1,'casacore']]],
  ['scalarfitsfieldcopier',['ScalarFITSFieldCopier',['../classcasacore_1_1ScalarFITSFieldCopier.html',1,'casacore']]],
  ['scalarmeascolumn',['ScalarMeasColumn',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarmeascolumn_3c_20mdirection_20_3e',['ScalarMeasColumn&lt; MDirection &gt;',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarmeascolumn_3c_20mdoppler_20_3e',['ScalarMeasColumn&lt; MDoppler &gt;',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarmeascolumn_3c_20mepoch_20_3e',['ScalarMeasColumn&lt; MEpoch &gt;',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarmeascolumn_3c_20mfrequency_20_3e',['ScalarMeasColumn&lt; MFrequency &gt;',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarmeascolumn_3c_20mposition_20_3e',['ScalarMeasColumn&lt; MPosition &gt;',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarmeascolumn_3c_20mradialvelocity_20_3e',['ScalarMeasColumn&lt; MRadialVelocity &gt;',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarmeascolumn_3c_20muvw_20_3e',['ScalarMeasColumn&lt; Muvw &gt;',['../classcasacore_1_1ScalarMeasColumn.html',1,'casacore']]],
  ['scalarquantcolumn',['ScalarQuantColumn',['../classcasacore_1_1ScalarQuantColumn.html',1,'casacore']]],
  ['scalarquantcolumn_3c_20double_20_3e',['ScalarQuantColumn&lt; Double &gt;',['../classcasacore_1_1ScalarQuantColumn.html',1,'casacore']]],
  ['scalarquantcolumn_3c_20float_20_3e',['ScalarQuantColumn&lt; Float &gt;',['../classcasacore_1_1ScalarQuantColumn.html',1,'casacore']]],
  ['scalarrecordcolumndata',['ScalarRecordColumnData',['../classcasacore_1_1ScalarRecordColumnData.html',1,'casacore']]],
  ['scalarrecordcolumndesc',['ScalarRecordColumnDesc',['../classcasacore_1_1ScalarRecordColumnDesc.html',1,'casacore']]],
  ['scalarsampledfunctional',['ScalarSampledFunctional',['../classcasacore_1_1ScalarSampledFunctional.html',1,'casacore']]],
  ['scaledarrayengine',['ScaledArrayEngine',['../classcasacore_1_1ScaledArrayEngine.html',1,'casacore']]],
  ['scaledcomplexdata',['ScaledComplexData',['../classcasacore_1_1ScaledComplexData.html',1,'casacore']]],
  ['scankey',['ScanKey',['../structcasacore_1_1ScanKey.html',1,'casacore']]],
  ['scopedmutexlock',['ScopedMutexLock',['../classcasacore_1_1ScopedMutexLock.html',1,'casacore']]],
  ['scsl',['SCSL',['../classcasacore_1_1SCSL.html',1,'casacore']]],
  ['sdantennahandler',['SDAntennaHandler',['../classcasacore_1_1SDAntennaHandler.html',1,'casacore']]],
  ['sddatadeschandler',['SDDataDescHandler',['../classcasacore_1_1SDDataDescHandler.html',1,'casacore']]],
  ['sdfeedhandler',['SDFeedHandler',['../classcasacore_1_1SDFeedHandler.html',1,'casacore']]],
  ['sdfieldhandler',['SDFieldHandler',['../classcasacore_1_1SDFieldHandler.html',1,'casacore']]],
  ['sdfitshandler',['SDFITSHandler',['../classcasacore_1_1SDFITSHandler.html',1,'casacore']]],
  ['sdfitstable',['SDFITSTable',['../classcasacore_1_1SDFITSTable.html',1,'casacore']]],
  ['sdhistoryhandler',['SDHistoryHandler',['../classcasacore_1_1SDHistoryHandler.html',1,'casacore']]],
  ['sdmainhandler',['SDMainHandler',['../classcasacore_1_1SDMainHandler.html',1,'casacore']]],
  ['sdobservationhandler',['SDObservationHandler',['../classcasacore_1_1SDObservationHandler.html',1,'casacore']]],
  ['sdpointinghandler',['SDPointingHandler',['../classcasacore_1_1SDPointingHandler.html',1,'casacore']]],
  ['sdpolarizationhandler',['SDPolarizationHandler',['../classcasacore_1_1SDPolarizationHandler.html',1,'casacore']]],
  ['sdsourcehandler',['SDSourceHandler',['../classcasacore_1_1SDSourceHandler.html',1,'casacore']]],
  ['sdspwindowhandler',['SDSpWindowHandler',['../classcasacore_1_1SDSpWindowHandler.html',1,'casacore']]],
  ['sdsyscalhandler',['SDSysCalHandler',['../classcasacore_1_1SDSysCalHandler.html',1,'casacore']]],
  ['sdweatherhandler',['SDWeatherHandler',['../classcasacore_1_1SDWeatherHandler.html',1,'casacore']]],
  ['separable',['Separable',['../structcasacore_1_1LSQFit_1_1Separable.html',1,'casacore::LSQFit']]],
  ['sequence',['Sequence',['../classcasacore_1_1Sequence.html',1,'casacore']]],
  ['sequence_3c_20uint_20_3e',['Sequence&lt; uInt &gt;',['../classcasacore_1_1Sequence.html',1,'casacore']]],
  ['serialhelper',['SerialHelper',['../classcasacore_1_1SerialHelper.html',1,'casacore']]],
  ['setupnewtable',['SetupNewTable',['../classcasacore_1_1SetupNewTable.html',1,'casacore']]],
  ['setupnewtablerep',['SetupNewTableRep',['../classcasacore_1_1SetupNewTableRep.html',1,'casacore']]],
  ['sign',['Sign',['../structcasacore_1_1Sign.html',1,'casacore']]],
  ['simbutterworthbandpass',['SimButterworthBandpass',['../classcasacore_1_1SimButterworthBandpass.html',1,'casacore']]],
  ['simordmapio_5fglobal_5ffunctions_5finoutput',['SimOrdMapIO_global_functions_inoutput',['../structcasacore_1_1SimOrdMapIO__global__functions__inoutput.html',1,'casacore']]],
  ['simpleorderedmap',['SimpleOrderedMap',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20imagetypes_2c_20openimagefunction_20_2a_20_3e',['SimpleOrderedMap&lt; ImageTypes, OpenImageFunction * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20int_2c_20int_20_3e',['SimpleOrderedMap&lt; Int, Int &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20int_2c_20string_20_3e',['SimpleOrderedMap&lt; Int, String &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20key_2c_20poolstack_3c_20t_2c_20key_20_3e_20_2a_20_3e',['SimpleOrderedMap&lt; Key, PoolStack&lt; T, Key &gt; * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20basecolumndesc_20_2a_28_2a_29_28const_20string_20_26_29_3e',['SimpleOrderedMap&lt; String, BaseColumnDesc *(*)(const String &amp;)&gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20columndesc_20_3e',['SimpleOrderedMap&lt; String, ColumnDesc &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20concatcolumn_20_2a_20_3e',['SimpleOrderedMap&lt; String, ConcatColumn * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20datamanagerctor_20_3e',['SimpleOrderedMap&lt; String, DataManagerCtor &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20int_20_3e',['SimpleOrderedMap&lt; String, Int &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20refcolumn_20_2a_20_3e',['SimpleOrderedMap&lt; String, RefColumn * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20string_20_3e',['SimpleOrderedMap&lt; String, String &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20string_2c_20void_20_2a_20_3e',['SimpleOrderedMap&lt; String, void * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20uint_2c_20poolstack_3c_20autodiffrep_3c_20double_20_3e_2c_20uint_20_3e_20_2a_20_3e',['SimpleOrderedMap&lt; uInt, PoolStack&lt; AutoDiffRep&lt; Double &gt;, uInt &gt; * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20uint_2c_20poolstack_3c_20autodiffrep_3c_20t_20_3e_2c_20uint_20_3e_20_2a_20_3e',['SimpleOrderedMap&lt; uInt, PoolStack&lt; AutoDiffRep&lt; T &gt;, uInt &gt; * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['simpleorderedmap_3c_20void_20_2a_2c_20void_20_2a_20_3e',['SimpleOrderedMap&lt; void *, void * &gt;',['../classcasacore_1_1SimpleOrderedMap.html',1,'casacore']]],
  ['sin',['Sin',['../structcasacore_1_1Sin.html',1,'casacore']]],
  ['sinc_5fconv',['Sinc_Conv',['../classcasacore_1_1Sinc__Conv.html',1,'casacore']]],
  ['sincfunction',['SincFunction',['../classcasacore_1_1SincFunction.html',1,'casacore']]],
  ['sincparam',['SincParam',['../classcasacore_1_1SincParam.html',1,'casacore']]],
  ['sinh',['Sinh',['../structcasacore_1_1Sinh.html',1,'casacore']]],
  ['sinusoid1d',['Sinusoid1D',['../classcasacore_1_1Sinusoid1D.html',1,'casacore']]],
  ['sinusoid1d_5fps_3c_20autodiff_3c_20t_20_3e_20_3e',['Sinusoid1D_PS&lt; AutoDiff&lt; T &gt; &gt;',['../classcasacore_1_1Sinusoid1D__PS_3_01AutoDiff_3_01T_01_4_01_4.html',1,'casacore']]],
  ['sinusoid1dparam',['Sinusoid1DParam',['../classcasacore_1_1Sinusoid1DParam.html',1,'casacore']]],
  ['sinusoid1dparam_3c_20autodiff_3c_20t_20_3e_20_3e',['Sinusoid1DParam&lt; AutoDiff&lt; T &gt; &gt;',['../classcasacore_1_1Sinusoid1DParam.html',1,'casacore']]],
  ['slice',['Slice',['../classcasacore_1_1Slice.html',1,'casacore']]],
  ['slicer',['Slicer',['../classcasacore_1_1Slicer.html',1,'casacore']]],
  ['slicer_5fglobal_5ffunctions_5fslicer_5fio',['Slicer_global_functions_Slicer_IO',['../structcasacore_1_1Slicer__global__functions__Slicer__IO.html',1,'casacore']]],
  ['smooth',['Smooth',['../classcasacore_1_1Smooth.html',1,'casacore']]],
  ['sofatest',['SofaTest',['../classcasacore_1_1SofaTest.html',1,'casacore']]],
  ['sofatest_5fglobal_5ffunctions_5fiau_5fsofa',['SofaTest_global_functions_IAU_SOFA',['../structcasacore_1_1SofaTest__global__functions__IAU__SOFA.html',1,'casacore']]],
  ['solarpos',['SolarPos',['../classcasacore_1_1SolarPos.html',1,'casacore']]],
  ['sort',['Sort',['../classcasacore_1_1Sort.html',1,'casacore']]],
  ['sorterror',['SortError',['../classcasacore_1_1SortError.html',1,'casacore']]],
  ['sortinvdt',['SortInvDT',['../classcasacore_1_1SortInvDT.html',1,'casacore']]],
  ['sortinvincr',['SortInvIncr',['../classcasacore_1_1SortInvIncr.html',1,'casacore']]],
  ['sortinvopt',['SortInvOpt',['../classcasacore_1_1SortInvOpt.html',1,'casacore']]],
  ['sortkey',['SortKey',['../classcasacore_1_1SortKey.html',1,'casacore']]],
  ['sortnodata',['SortNoData',['../classcasacore_1_1SortNoData.html',1,'casacore']]],
  ['sourcelocation',['SourceLocation',['../structcasacore_1_1LogOrigin__global__functions__SourceLocation_1_1SourceLocation.html',1,'casacore::LogOrigin_global_functions_SourceLocation']]],
  ['sparsediff',['SparseDiff',['../classcasacore_1_1SparseDiff.html',1,'casacore']]],
  ['sparsediffa',['SparseDiffA',['../classcasacore_1_1SparseDiffA.html',1,'casacore']]],
  ['sparsediffio_5fglobal_5ffunctions_5fsparsediff_5fio_5foperations',['SparseDiffIO_global_functions_SparseDiff_IO_operations',['../structcasacore_1_1SparseDiffIO__global__functions__SparseDiff__IO__operations.html',1,'casacore']]],
  ['sparsediffmath_5fglobal_5ffunctions_5fsparsediff_5fmathematical_5foperations',['SparseDiffMath_global_functions_SparseDiff_mathematical_operations',['../structcasacore_1_1SparseDiffMath__global__functions__SparseDiff__mathematical__operations.html',1,'casacore']]],
  ['sparsediffrep',['SparseDiffRep',['../classcasacore_1_1SparseDiffRep.html',1,'casacore']]],
  ['sparsediffx',['SparseDiffX',['../classcasacore_1_1SparseDiffX.html',1,'casacore']]],
  ['specificfunctionfactory',['SpecificFunctionFactory',['../classcasacore_1_1SpecificFunctionFactory.html',1,'casacore']]],
  ['spectralcoordinate',['SpectralCoordinate',['../classcasacore_1_1SpectralCoordinate.html',1,'casacore']]],
  ['sph_5fconv',['Sph_Conv',['../classcasacore_1_1Sph__Conv.html',1,'casacore']]],
  ['spolynomial',['SPolynomial',['../classcasacore_1_1SPolynomial.html',1,'casacore']]],
  ['spolynomialparam',['SPolynomialParam',['../classcasacore_1_1SPolynomialParam.html',1,'casacore']]],
  ['sptrholder',['SPtrHolder',['../classSPtrHolder.html',1,'']]],
  ['sptrholder_3c_20msmetadata_20_3e',['SPtrHolder&lt; MSMetaData &gt;',['../classSPtrHolder.html',1,'']]],
  ['sptrholder_3c_20tabularcoordinate_20_3e',['SPtrHolder&lt; TabularCoordinate &gt;',['../classSPtrHolder.html',1,'']]],
  ['spwproperties',['SpwProperties',['../structcasacore_1_1MSMetaData_1_1SpwProperties.html',1,'casacore::MSMetaData']]],
  ['sqr',['Sqr',['../structcasacore_1_1Sqr.html',1,'casacore']]],
  ['sqrt',['Sqrt',['../structcasacore_1_1Sqrt.html',1,'casacore']]],
  ['squarematrix',['SquareMatrix',['../classcasacore_1_1SquareMatrix.html',1,'casacore']]],
  ['squarematrix_3c_20complex_2c_202_20_3e',['SquareMatrix&lt; Complex, 2 &gt;',['../classcasacore_1_1SquareMatrix.html',1,'casacore']]],
  ['squarematrix_5fglobal_5ffunctions_5fsqm_5fglobal_5ffunctions',['SquareMatrix_global_functions_SqM_global_functions',['../structcasacore_1_1SquareMatrix__global__functions__SqM__global__functions.html',1,'casacore']]],
  ['ssmbase',['SSMBase',['../classcasacore_1_1SSMBase.html',1,'casacore']]],
  ['ssmcolumn',['SSMColumn',['../classcasacore_1_1SSMColumn.html',1,'casacore']]],
  ['ssmdircolumn',['SSMDirColumn',['../classcasacore_1_1SSMDirColumn.html',1,'casacore']]],
  ['ssmindcolumn',['SSMIndColumn',['../classcasacore_1_1SSMIndColumn.html',1,'casacore']]],
  ['ssmindex',['SSMIndex',['../classcasacore_1_1SSMIndex.html',1,'casacore']]],
  ['ssmindstringcolumn',['SSMIndStringColumn',['../classcasacore_1_1SSMIndStringColumn.html',1,'casacore']]],
  ['ssmstringhandler',['SSMStringHandler',['../classcasacore_1_1SSMStringHandler.html',1,'casacore']]],
  ['stack',['Stack',['../classcasacore_1_1Stack.html',1,'casacore']]],
  ['standardstman',['StandardStMan',['../classcasacore_1_1StandardStMan.html',1,'casacore']]],
  ['statacc',['StatAcc',['../classcasacore_1_1StatAcc.html',1,'casacore']]],
  ['statisticsalgorithm',['StatisticsAlgorithm',['../classcasacore_1_1StatisticsAlgorithm.html',1,'casacore']]],
  ['statisticsdata',['StatisticsData',['../classcasacore_1_1StatisticsData.html',1,'casacore']]],
  ['statisticsincrementer',['StatisticsIncrementer',['../classcasacore_1_1StatisticsIncrementer.html',1,'casacore']]],
  ['statisticsutilities',['StatisticsUtilities',['../classcasacore_1_1StatisticsUtilities.html',1,'casacore']]],
  ['statsdata',['StatsData',['../structcasacore_1_1StatsData.html',1,'casacore']]],
  ['statsdataprovider',['StatsDataProvider',['../classcasacore_1_1StatsDataProvider.html',1,'casacore']]],
  ['statsdataprovider_3c_20numerictraits_3c_20t_20_3e_3a_3aprecisiontype_2c_20const_20t_20_2a_2c_20const_20bool_20_2a_20_3e',['StatsDataProvider&lt; NumericTraits&lt; T &gt;::PrecisionType, const T *, const Bool * &gt;',['../classcasacore_1_1StatsDataProvider.html',1,'casacore']]],
  ['statstiledcollapser',['StatsTiledCollapser',['../classcasacore_1_1StatsTiledCollapser.html',1,'casacore']]],
  ['std_5fvector_5fto_5flist',['std_vector_to_list',['../structcasacore_1_1python_1_1std__vector__to__list.html',1,'casacore::python']]],
  ['stddevfunc',['StddevFunc',['../classcasacore_1_1ArrayPartMath__global__functions__Array__partial__operations_1_1StddevFunc.html',1,'casacore::ArrayPartMath_global_functions_Array_partial_operations']]],
  ['stindarray',['StIndArray',['../classcasacore_1_1StIndArray.html',1,'casacore']]],
  ['stl_5fvariable_5fcapacity_5fpolicy',['stl_variable_capacity_policy',['../structcasacore_1_1python_1_1stl__variable__capacity__policy.html',1,'casacore::python']]],
  ['stlmath_5fglobal_5ffunctions_5fcontainer_5fmath',['STLMath_global_functions_Container_Math',['../structcasacore_1_1STLMath__global__functions__Container__Math.html',1,'casacore']]],
  ['stmanaipsio',['StManAipsIO',['../classcasacore_1_1StManAipsIO.html',1,'casacore']]],
  ['stmanarrayfile',['StManArrayFile',['../classcasacore_1_1StManArrayFile.html',1,'casacore']]],
  ['stmancolumn',['StManColumn',['../classcasacore_1_1StManColumn.html',1,'casacore']]],
  ['stmancolumnaipsio',['StManColumnAipsIO',['../classcasacore_1_1StManColumnAipsIO.html',1,'casacore']]],
  ['stmancolumnarrayaipsio',['StManColumnArrayAipsIO',['../classcasacore_1_1StManColumnArrayAipsIO.html',1,'casacore']]],
  ['stmancolumnindarrayaipsio',['StManColumnIndArrayAipsIO',['../classcasacore_1_1StManColumnIndArrayAipsIO.html',1,'casacore']]],
  ['stokes',['Stokes',['../classcasacore_1_1Stokes.html',1,'casacore']]],
  ['stokesconverter',['StokesConverter',['../classcasacore_1_1StokesConverter.html',1,'casacore']]],
  ['stokescoordinate',['StokesCoordinate',['../classcasacore_1_1StokesCoordinate.html',1,'casacore']]],
  ['storageoption',['StorageOption',['../classcasacore_1_1StorageOption.html',1,'casacore']]],
  ['streamio',['StreamIO',['../classcasacore_1_1StreamIO.html',1,'casacore']]],
  ['streamlogsink',['StreamLogSink',['../classcasacore_1_1StreamLogSink.html',1,'casacore']]],
  ['string',['String',['../classcasacore_1_1String.html',1,'casacore']]],
  ['string_5fglobal_5ffunctions_5fcase',['String_global_functions_case',['../structcasacore_1_1String__global__functions__case.html',1,'casacore']]],
  ['string_5fglobal_5ffunctions_5fcommon',['String_global_functions_common',['../structcasacore_1_1String__global__functions__common.html',1,'casacore']]],
  ['string_5fglobal_5ffunctions_5fcomparitor',['String_global_functions_comparitor',['../structcasacore_1_1String__global__functions__comparitor.html',1,'casacore']]],
  ['string_5fglobal_5ffunctions_5fconcatenator',['String_global_functions_concatenator',['../structcasacore_1_1String__global__functions__concatenator.html',1,'casacore']]],
  ['string_5fglobal_5ffunctions_5fio',['String_global_functions_io',['../structcasacore_1_1String__global__functions__io.html',1,'casacore']]],
  ['string_5fglobal_5ffunctions_5fsplit',['String_global_functions_split',['../structcasacore_1_1String__global__functions__split.html',1,'casacore']]],
  ['stringdistance',['StringDistance',['../classcasacore_1_1StringDistance.html',1,'casacore']]],
  ['stringfitsfieldcopier',['StringFITSFieldCopier',['../classcasacore_1_1StringFITSFieldCopier.html',1,'casacore']]],
  ['subimage',['SubImage',['../classcasacore_1_1SubImage.html',1,'casacore']]],
  ['sublattice',['SubLattice',['../classcasacore_1_1SubLattice.html',1,'casacore']]],
  ['subscankey',['SubScanKey',['../structcasacore_1_1SubScanKey.html',1,'casacore']]],
  ['subscanproperties',['SubScanProperties',['../structcasacore_1_1MSMetaData_1_1SubScanProperties.html',1,'casacore::MSMetaData']]],
  ['substring',['SubString',['../classcasacore_1_1SubString.html',1,'casacore']]],
  ['subtabledesc',['SubTableDesc',['../classcasacore_1_1SubTableDesc.html',1,'casacore']]],
  ['sumabsdiff',['SumAbsDiff',['../structcasacore_1_1SumAbsDiff.html',1,'casacore']]],
  ['sumfunc',['SumFunc',['../classcasacore_1_1ArrayPartMath__global__functions__Array__partial__operations_1_1SumFunc.html',1,'casacore::ArrayPartMath_global_functions_Array_partial_operations']]],
  ['sumsqr',['SumSqr',['../structcasacore_1_1SumSqr.html',1,'casacore']]],
  ['sumsqrdiff',['SumSqrDiff',['../structcasacore_1_1SumSqrDiff.html',1,'casacore']]],
  ['symlink',['SymLink',['../classcasacore_1_1SymLink.html',1,'casacore']]],
  ['systemcallerror',['SystemCallError',['../classcasacore_1_1SystemCallError.html',1,'casacore']]]
];
