# Fundamentals
#-------------
AIPSROOT := $(word 1, $(AIPSPATH))


# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(AIPSROOT)/code/install/makefile.doc
