#!/bin/sh
#-----------------------------------------------------------------------------
# Script to invoke tIncrementalStMan and verify its output.
#=============================================================================

exec assay tIncrementalStMan "1000 && \
     tIncrementalStMan 2000 && \
     tIncrementalStMan 3000 && \
     tIncrementalStMan 4000 && \
     tIncrementalStMan 5000 && \
     tIncrementalStMan 0"
