#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the RecordGram class for a table
#=============================================================================

tRecordGramTable "ab"
tRecordGramTable "ac"
tRecordGramTable "ad"
tRecordGramTable "ae"
tRecordGramTable "af"
tRecordGramTable "ag"
tRecordGramTable "ab>4"
tRecordGramTable "ab+ac"
