#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the TableGram and TableParse class.  All files generated will
# be deleted on exit.
#=============================================================================

# Use table tTable_2.data_v0 as the input by creating a link to its directory.
  rm -rf tTableGram_tmp.tab*
  mkdir tTableGram_tmp.tab
  AIPSCODE=`echo $AIPSPATH | awk '{printf("%s/code",$1)}'`
  cp -r $AIPSCODE/tables/implement/Tables/test/tTable_2.data_v0/table.* tTableGram_tmp.tab
  chmod 644 tTableGram_tmp.tab/*
  cp -r tTableGram_tmp.tab tTableGram_tmp.tabc

# Whitespace around * had to be removed to avoid file name expansion by shell.


tTableGram 'select ab,ac,ad,ae,af,ag into tTableGram_tmp.data2 from tTableGram_tmp.tab sh where all(ab>2) && (ae<10 || ae>11.0) && ag!= 10 + 1i orderby ac desc,ab'

tTableGram 'select distinct ab,ac,ad,ae,af,ag from tTableGram_tmp.data2'

tTableGram 'select all ab,ac,ad,ae,af,ag from tTableGram_tmp.data2 orderby af'

tTableGram 'select ab from tTableGram_tmp.tab where ab==2^1^2 || ab==-2^-1*8/-2*3'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab where lower(af) == regex("v[01279]")'
tTableGram 'select ab,ac,af from tTableGram_tmp.tab where lower(af)!~m/v[01279]/'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab where af ~ p/?{3,5,8}/'
tTableGram 'select ab,ac,af from tTableGram_tmp.tab where af != pattern("?{3,5,8}")'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab where af == sqlpattern("_3%")'
tTableGram 'select ab,ac,af from tTableGram_tmp.tab where af like "_3%"'
tTableGram 'select ab,ac,af from tTableGram_tmp.tab where af not like "_3%"'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab%1.5==0'

tTableGram 'select ab,ac from tTableGram_tmp.tab where arr1[1,1,1]>=10 && arr2[1,1,1]<120'

tTableGram 'select * from tTableGram_tmp.tab where arr1[1,1,1]>=10 && arr2[1,1,1]<120'

tTableGram 'select ab,ac from tTableGram_tmp.tab where arr1[1,1,1+ab%1]>=192 orderby ad desc'

tTableGram 'select ab,ac from tTableGram_tmp.tab where cos(2d0m) <= sin(-2d)*sin(-ab/180*pi()) + cos(-2deg)*cos(-ab/180*pi())*cos(3d - ac/180*pi())'

tTableGram 'select ab,ac,ad,ae,af,ag from tTableGram_tmp.tab where ab+ac+ad+ae+real(ag) >= year(31-12-60) + year("31Dec60") + month(1990/5/12) + day(date(1990/1/30/12h14m33.3)) - 3910'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab where ab>5 orderby af desc, ac'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab orderby arr1[1,1,1]'

tTableGram 'select ab,ac from tTableGram_tmp.tab orderby round(2*sin(ab)),ac desc'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab < mean([3:6,ab])'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab < 4 && EXISTS (select from tTableGram_tmp.tab)'
tTableGram 'select ab,ac from tTableGram_tmp.tab where ab < 4 && EXISTS (select from tTableGram_tmp.tab LIMIT 11)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN (select ac from tTableGram_tmp.tab where ab>4)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab BETWEEN 2 AND 4'
tTableGram 'select ab,ac from tTableGram_tmp.tab where ab NOT BETWEEN 2 AND 4'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN [:=2,4=:<6,7<:]'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN (2,(3))'
tTableGram 'select ab,ac from tTableGram_tmp.tab where ab NOT IN (2,(3))'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN [select from tTableGram_tmp.tab where ab>4 giving [ac=:=ac+0.5]]'

tTableGram 'select ab from tTableGram_tmp.tab where ab IN [select from tTableGram_tmp.tab where ab>7 giving [ab-1=:=ab]]'
tTableGram 'select ab from tTableGram_tmp.tab where ab IN [select from tTableGram_tmp.tab where ab>7 giving [ab-1=:<ab]]'
tTableGram 'select ab from tTableGram_tmp.tab where ab IN [select from tTableGram_tmp.tab where ab>7 giving [ab-1<:=ab]]'
tTableGram 'select ab from tTableGram_tmp.tab where ab IN [select from tTableGram_tmp.tab where ab>7 giving [ab-1<:<ab]]'

tTableGram 'select ab,ac from tTableGram_tmp.tab where any(isnan(arr1)) || isnan(ab)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN arr1'

tTableGram 'select ab,ac from tTableGram_tmp.tab where any(arr1-array(100,shape(arr1)) > 0  &&  arr1<200)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where count(shape(arr1))==3 && count(ab)==1 && ndim(ac)==0 && isdefined(arr2)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab in ab'

tTableGram 'select ab,ac from tTableGram_tmp.tab where any(arr1 in ab)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where (ab=ab)=T'

tTableGram 'select ab,ac from tTableGram_tmp.tab where (ab=ab)=F'

tTableGram 'select ab,ac from tTableGram_tmp.tab where rownumber()==rowid()+1'

tTableGram 'select ab,ac from [select from tTableGram_tmp.tab where ab > 4] where ab < 6'

tTableGram 'select ab,ac from [select from tTableGram_tmp.tab where ab > 4] TEMPTAB, tTableGram_tmp.tab where any([ab,ac] in [select ac from TEMPTAB])'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ac in [select from tTableGram_tmp.tab where ac in 4:6:2 giving [rowid()]]'

tTableGram 'select ab from tTableGram_tmp.tab where min(maxs(arr1,[1+arr1[1,1,1]%2,3])) == 19'

tTableGram 'select ab from tTableGram_tmp.tab where min(1+maxs(arr1-1,1,3)) == 19'

tTableGram 'select ab from tTableGram_tmp.tab where sum(fractiles(arr1,0.5,[2:3])) == 21+shape(arr1)[1]*count(arr1)'

tTableGram 'select ab from tTableGram_tmp.tab where sum(ntrues(arr1%5==0,[1])) < 5'

tTableGram 'select ab from tTableGram_tmp.tab where all(anys(fmod(sums(arr1,1),5)==0,[2:4]))'

tTableGram 'select ab from $1;tTableGram_tmp.tab'

tTableGram 'calc sum([select from tTableGram_tmp.tab giving [ab+1]])'
tTableGram 'calc from $1 calc sum([select ab from $1]);tTableGram_tmp.tab'
tTableGram 'calc from tTableGram_tmp.tab calc ab'
tTableGram 'calc from $1 calc ab+1;tTableGram_tmp.tab'

echo ""

tTableGram 'update tTableGram_tmp.tab set ab=sum(arr1)+ac*2, arr1=arr1+2 where ac>3'
tTableGram 'select ab from tTableGram_tmp.tab'
tTableGram 'update tTableGram_tmp.tab set ab=sum(arr1)+ac*2, arr1=arr1+2 from tTableGram_tmp.tabc where ac>3 orderby ac limit 5'

tTableGram 'update tTableGram_tmp.tab set arr1=2, ab=sum(arr1) limit 1 offset 3'
tTableGram 'update tTableGram_tmp.tab set arr1[1,1,1]=3, arr1[2,2,2]=arr1[1,1,1], ab=sum(arr1) limit 1 offset 3'
tTableGram 'update tTableGram_tmp.tab set arr1[1,,]=4, ab=sum(arr1) limit 1 offset 3'

tTableGram 'delete from tTableGram_tmp.tab limit 3 offset 2'
tTableGram 'delete from tTableGram_tmp.tab orderby desc ab limit 1 offset 2'
tTableGram 'select ab from tTableGram_tmp.tab'

tTableGram 'delete from tTableGram_tmp.tab'
tTableGram 'select ab from tTableGram_tmp.tab'

tTableGram 'insert into tTableGram_tmp.tab select from tTableGram_tmp.tabc'
tTableGram 'select ab from tTableGram_tmp.tab'

tTableGram 'delete from tTableGram_tmp.tab where ab%2==0'
tTableGram 'select ab from tTableGram_tmp.tab'

tTableGram 'insert into tTableGram_tmp.tab (ab,ac) values (1+2,3*ab + sum([select ab from tTableGram_tmp.tab]))'
tTableGram 'select ab,ac from tTableGram_tmp.tab'
