#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the TableGram and TableParse class.  All files generated will
# be deleted on exit.
#=============================================================================

# Use table tTable_2.data_v0 as the input by creating a link to its directory.
  rm -rf tTableGram_tmp.tab
  mkdir tTableGram_tmp.tab
  AIPSCODE=`echo $AIPSPATH | awk '{printf("%s/code",$1)}'`
  cp -r $AIPSCODE/aips/implement/Tables/test/tTable_2.data_v0/table.* tTableGram_tmp.tab
  chmod 644 tTableGram_tmp.tab/*

# Whitespace around * had to be removed to avoid file name expansion by shell.


tTableGram 'select ab,ac,ad,ae,af,ag into tTableGram_tmp.data2 from tTableGram_tmp.tab sh where all(ab>2) && (ae<10 || ae>11.0) && ag!= 10 + 1i orderby ac desc,ab'

tTableGram 'select distinct ab,ac,ad,ae,af,ag from tTableGram_tmp.data2'

tTableGram 'select all ab,ac,ad,ae,af,ag from tTableGram_tmp.data2 orderby af'

tTableGram 'select ab from tTableGram_tmp.tab where ab==2^1^2 || ab==-2^-1*8/-2*3'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab where lower(af) == regex("v[01279]")'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab where af == pattern("?{3,5,8}")'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab%1.5==0'

tTableGram 'select ab,ac from tTableGram_tmp.tab where arr1[1,1,1]>=10 && arr2[1,1,1]<120'

tTableGram 'select * from tTableGram_tmp.tab where arr1[1,1,1]>=10 && arr2[1,1,1]<120'

tTableGram 'select ab,ac from tTableGram_tmp.tab where arr1[1,1,1+ab%1]>=192 orderby ad desc'

tTableGram 'select ab,ac from tTableGram_tmp.tab where cos(2d0m) <= sin(-2d)*sin(-ab/180*pi()) + cos(-2deg)*cos(-ab/180*pi())*cos(3d - ac/180*pi())'

tTableGram 'select ab,ac,ad,ae,af,ag from tTableGram_tmp.tab where ab+ac+ad+ae+real(ag) >= year(31-12-60) + year("31Dec60") + month(1990/5/12) + day(date(1990/1/30/12h14m33.3)) - 3910'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab where ab>5 orderby af desc, ac'

tTableGram 'select ab,ac,af from tTableGram_tmp.tab orderby arr1[1,1,1]'

tTableGram 'select ab,ac from tTableGram_tmp.tab orderby round(2*sin(ab)),ac desc'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab < mean([3:6,ab])'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN [select ac from tTableGram_tmp.tab where ab>4]'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN [:=2,4=:<6,7<:]'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN [select from tTableGram_tmp.tab where ab>4 giving [ac=:=ac+0.5]]'

tTableGram 'select ab,ac from tTableGram_tmp.tab where any(isnan(arr1)) || isnan(ab)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab IN arr1'

tTableGram 'select ab,ac from tTableGram_tmp.tab where any(arr1 > 100  &&  arr1<200)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where count(shape(arr1))==3 && count(ab)==1 && ndim(ac)==0 && isdefined(arr2)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ab in ab'

tTableGram 'select ab,ac from tTableGram_tmp.tab where any(arr1 in ab)'

tTableGram 'select ab,ac from tTableGram_tmp.tab where (ab=ab)=T'

tTableGram 'select ab,ac from tTableGram_tmp.tab where (ab=ab)=F'

tTableGram 'select ab,ac from tTableGram_tmp.tab where rownumber()==rowid()+1'

tTableGram 'select ab,ac from [select from tTableGram_tmp.tab where ab > 4] where ab < 6'

tTableGram 'select ab,ac from [select from tTableGram_tmp.tab where ab > 4] TEMPTAB, tTableGram_tmp.tab where any([ab,ac] in [select ac from TEMPTAB])'

tTableGram 'select ab,ac from tTableGram_tmp.tab where ac in [select from tTableGram_tmp.tab where ac in 4:6:2 giving [rowid()]]'

tTableGram 'select ab from tTableGram_tmp.tab where min(maxs(arr1,[1+arr1[1,1,1]%2,3])) == 19'

tTableGram 'select ab from tTableGram_tmp.tab where min(1+maxs(arr1-1,1,3)) == 19'

tTableGram 'select ab from tTableGram_tmp.tab where sum(fractiles(arr1,0.5,[2:3])) == 21+shape(arr1)[1]*count(arr1)'

tTableGram 'select ab from tTableGram_tmp.tab where sum(ntrues(arr1%5==0,[1])) < 5'

tTableGram 'select ab from tTableGram_tmp.tab where all(anys(fmod(sums(arr1,1),5)==0,[2:4]))'


tTableGram 'update tTableGram_tmp.tab set ab=sum(arr1)+ac*2, arr1=arr1+2 where ac>3'
tTableGram 'select ab from tTableGram_tmp.tab'
