#!/bin/sh
#-----------------------------------------------------------------------------
# depstat: Count the number of header files used by class implemetation files
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1994,1997
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: depstat [<$AIPSAUXD/package.list>]
#-----------------------------------------------------------------------------
# depstat is a sed/awk filter which counts the number of AIPS++ header files
# on which each AIPS++ implementation file depends by scanning the dependency
# list.
#
# Example:
#
#    Typically the output may be sorted as follows:
#
#    depstat aips.list | sort +1 -n -r
#
# Notes:
#    1) If no dependency file is specified on the command line, input is taken
#       from stdin.
#
# Original: 1994/03/24 by Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------

  sed -e 's/.*%=%(\([^.]*\).*/\1/' $1 | \
     awk 'file == "" { \
             file = $1 ; \
             count = 0 \
          } \
          file == $1 { \
             count++ \
          } \
          file != $1 { \
             print sprintf("%20s%8d",file,count) ; \
             file = $1 ; \
             count = 1 \
          } \
          END { \
             print sprintf("%20s%8d",file,count) \
          }'
