# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Clone()
if not myenv.GetOption('clean') and not myenv.GetOption("help"):
    conf = myenv.Configure()
    # readline
    if conf.env.get("enable_readline"):
        pkgname = "readline"
        libname = myenv.get(pkgname+"_lib")
        conf.env.AddCustomPackage(pkgname)
        if conf.CheckLib(libname, language='c',autoadd=0):
            myenv.Append(CPPFLAGS=['-DHAVE_READLINE'])
	    myenv["READLINE"] = [libname]
        else:
            myenv.Exit(1)
    conf.Finish()
rllib = myenv.get("READLINE", [])
myenv.AppendUnique(LIBS=rllib)
myenv.AppsBuilder(installer=installer)
