#!/bin/sh

path=`echo $AIPSPATH | awk '{ print $1; }'`/code

function depend
{
   if test $1 = "lib"
      then
         subdir="implement"
         echo "  Library:" >> compliance.log
      else
         subdir="apps"
         echo "  Application:" >> compliance.log
   fi

   for dep in `cat compliance.dat`
   do
      rm -rf $dep_compliance.log

      grep ^\#include\ \<$dep\/ $path/$2/$subdir/*.h \
           >> $dep_compliance.log \
           2> /dev/null
      grep ^\#include\ \<$dep\/ $path/$2/$subdir/*/*.h \
           >> $dep_compliance.log \
           2> /dev/null
      grep ^\#include\ \<$dep\/ $path/$2/$subdir/*/*.cc \
           >> $dep_compliance.log \
           2> /dev/null

      if test -s $dep_compliance.log
         then
            echo "    $1$2 => lib$dep" >> compliance.log
      fi
   done
}

function usage
{
   if test $1 
      then
         if test $1 = "all" -o $1 = "lib" -o $1 = "app"
            then
               return
         fi
   fi

   echo "usage: compliance [all|lib|app]"
   exit 1
}

function checkdir
{
   for dir in `cat compliance.dat`
   do
      if test -d $path/$dir
         then
            continue
         else
            echo "Missing $path/$dir"
            echo "The compliance script must be run from the root tree"
            exit 1
      fi
   done
}

function compliance
{
   for diff in `diff compliance.$1 compliance.log`
   do

      if test $diff = ">"
         then
            echo
            echo "A new dependency has been introduced:"
      elif test $diff = "<"
         then
            echo
            echo "An old dependency has been removed:"
      else
         printf " $diff" | sed 's/[0-9].*//'
      fi
   done

   echo
}


usage $1
checkdir

rm -rf compliance.log

for dir in `cat compliance.dat`
do
   echo "Processing $dir..."
   echo "Dependencies for $dir" >> compliance.log

   if test $1 = "all"
      then
         depend "lib" $dir
         depend "app" $dir
      else
         depend $1 $dir
   fi

   echo >> compliance.log
done

echo
echo "Reporting compliance failures..."

compliance $1

echo
echo "Complete"

