#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test tIncrementalStMan by running it in various ways.
#=============================================================================

  $casa_checktool ./tIncrementalStMan 1000
  $casa_checktool ./tIncrementalStMan 2000
  $casa_checktool ./tIncrementalStMan 3000
  $casa_checktool ./tIncrementalStMan 4000
  $casa_checktool ./tIncrementalStMan 5000
  $casa_checktool ./tIncrementalStMan 0
