#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: tTable_2.exec
#-----------------------------------------------------------------------------
# This scripts executes the program tTable_2 to test if new table
# software can still read old tables.
# The script supplies the names of all test tables found in the system.
# It is meant to be run from assay, but can also be used standalone.
#
# $Id$
#-----------------------------------------------------------------------------

# Fundamentals.
  TABLES="$testsrcdir/tTable_2.data_v*"

  $casa_checktool ./tTable_2 $TABLES
