#!/bin/sh

# Define the 'casarc' file to be used by Aipsrc.
CASARCFILES=`pwd`/tTableTrace_tmp.rc
export CASARCFILES

# Do high level tracing to a file.
# Remove the time from the log lines.
cat > tTableTrace_tmp.rc <<EOF
table.trace.filename: tTableTrace_tmp.log1
EOF
$casa_checktool ./tTableTrace
sed -e 's/^[0-9][^ ]* /time1 /' tTableTrace_tmp.log1

# This traces IO of arrays to stdout
echo
cat > tTableTrace_tmp.rc <<EOF
table.trace.filename: stdout
table.trace.operation: srw
EOF
$casa_checktool ./tTableTrace | sed -e 's/^[0-9][^ ]* /time2 /'

# This traces IO of scalars to stdout
echo
cat > tTableTrace_tmp.rc <<EOF
table.trace.filename: stdout
table.trace.operation: srw
table.trace.columntype: s
EOF
$casa_checktool ./tTableTrace | sed -e 's/^[0-9][^ ]* /time2 /'

