#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the TableGram and TaQLNode class.# be deleted on exit.
#=============================================================================

# Whitespace around * had to be removed to avoid file name expansion by shell.


$casa_checktool ./tTaQLNode 'select ab,ac,ad,ae,af,ag into tTaQLNode_tmp.data2 from tTaQLNode_tmp.tab sh where all(ab>2) && (ae<10 || ae>11.0) && ag!= 10 + 1i orderby ac desc,ab'
$casa_checktool ./tTaQLNode 'select ab,ac,ad,ae,af,ag into tTaQLNode_tmp.data2 as PLAIN_LOCAL from tTaQLNode_tmp.tab sh where all(ab>2) && (ae<10 || ae>11.0) && ag!= 10 + 1i orderby ac desc,ab'

$casa_checktool ./tTaQLNode 'select distinct ab+1 as ab1,ac,ad,ae,af,ag from tTaQLNode_tmp.data2'

$casa_checktool ./tTaQLNode 'select all ab as ab1,ac as ac1,ad,ae,af,ag from tTaQLNode_tmp.data2 orderby af'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where ab==2**1**2 || ab==-2**-1*0x0A1f/-2*3'

# $casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where ab==2^1^2 || ab==-2^-1*8/-2*3'

$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where lower(af) == regex("v[01279]")'
$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where lower(af)!~m/v[01279]/'

$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where af ~ p/?{3,5,8}/'
$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where af != pattern("?{3,5,8}")'

$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where af == sqlpattern("_3%")'
$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where af like "_3%"'
$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where af not like "_3%"'

$casa_checktool ./tTaQLNode 'select from tTaQLNode_tmp.tab where af ~ d/abc/'
$casa_checktool ./tTaQLNode 'select from tTaQLNode_tmp.tab where af ~ d#abc#ib3'
$casa_checktool ./tTaQLNode 'select from tTaQLNode_tmp.tab where af ~ d/abc/03bi'
$casa_checktool ./tTaQLNode 'select from tTaQLNode_tmp.tab where af ~ d%abc%04'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab%1.5==0'

$casa_checktool ./tTaQLNode 'select ab,(ac)mm from tTaQLNode_tmp.tab where ab%1.5==0 "m/s"'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where arr1[1,1,1]>=10 && arr2[1,1,1]<120'

$casa_checktool ./tTaQLNode 'select * from tTaQLNode_tmp.tab where arr1[1,1,1]>=10 && arr2[1,1,1]<120'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where arr1[1,1,1+ab%1]>=192 orderby ad desc'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where cos(0.01rad) <= sin(-0.02rad)*sin(-ab/180*pi()) + cos(-0.5rad)*cos(-ab/180*pi())*cos(0.02rad - ac/180*pi())'

$casa_checktool ./tTaQLNode 'select ab,ac,ad,ae,af,ag from tTaQLNode_tmp.tab where ab+ac+ad+ae+real(ag) >= year(31-12-60) + year("31Dec60") + month(1990/5/12) + day(date(1990/1/30/12h14m33.3)) - 3910'

$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab where ab>5 orderby af desc, ac'

$casa_checktool ./tTaQLNode 'select ab,ac,af from tTaQLNode_tmp.tab orderby arr1[1,1,1]'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab orderby round(2*sin(ab)),ac desc'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab < mean([3:6,ab])'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab < 4 && EXISTS (select from tTaQLNode_tmp.tab)'
$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab < 4 && EXISTS (select from tTaQLNode_tmp.tab LIMIT 11)'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab IN (select ac from tTaQLNode_tmp.tab where ab>4)'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab BETWEEN 2 AND 4'
$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab NOT BETWEEN 2 AND 4'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab IN [:=2,4=:<6,7<:]'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab IN (2,(3))'
$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab NOT IN (2,(3))'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab IN [select from tTaQLNode_tmp.tab where ab>4 giving [ac=:=ac+0.5]]'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where ab IN [select from tTaQLNode_tmp.tab where ab>7 giving [ab-1=:=ab]]'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where ab IN [select from tTaQLNode_tmp.tab where ab>7 giving [ab-1=:<ab]]'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where ab IN [select from tTaQLNode_tmp.tab where ab>7 giving [ab-1<:=ab]]'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where ab IN [select from tTaQLNode_tmp.tab where ab>7 giving [ab-1<:<ab]]'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where any(isnan(arr1)) || isnan(ab)'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab IN arr1'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where any(arr1-array(100,shape(arr1)) > 0  &&  arr1<200)'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where count(shape(arr1))==3 && count(ab)==1 && ndim(ac)==0 && isdefined(arr2)'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ab in ab'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where any(arr1 in ab)'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where (ab=ab)=T'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where (ab=ab)=F'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where rownumber()==rowid()+1'

$casa_checktool ./tTaQLNode 'select ab,ac from [select from tTaQLNode_tmp.tab where ab > 4] where ab < 6'

$casa_checktool ./tTaQLNode 'select ab,ac from [select from tTaQLNode_tmp.tab where ab > 4] TEMPTAB, tTaQLNode_tmp.tab where any([ab,ac] in [select ac from TEMPTAB])'

$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab where ac in [select from tTaQLNode_tmp.tab where ac in 4:6:2 giving [rowid()]]'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where min(maxs(arr1,[1+arr1[1,1,1]%2,3])) == 19'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where min(1+maxs(arr1-1,1,3)) == 19'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where sum(fractiles(arr1,0.5,[2:3])) == 21+shape(arr1)[1]*count(arr1)'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where sum(ntrues(arr1%5==0,[1])) < 5'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where all(anys(fmod(sums(arr1,1),5)==0,[2:4]))'

$casa_checktool ./tTaQLNode 'select ab from $1'

$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where [ab,ab] incone [2 rad,2rad,1rad]'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where anycone([ab,ab],[2rad,2rad],1rad)'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where cones([ab,ab],[4rad,4rad,1rad])'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where any(cones([ab,ab],array([2rad,2rad,4rad,4rad],[2,2]),1rad))'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab where [ab,ab] incone [2rad,2rad,1rad,4rad,4rad,1rad]'

$casa_checktool ./tTaQLNode 'select *, !~p/ab*/i, *, !~m%b%, !~ m%c%i, abc, ~p/AB*/ from tTaQLNode_tmp.tab'

$casa_checktool ./tTaQLNode 'count TIME from tTaQLNode_tmp.tab'
$casa_checktool ./tTaQLNode 'count ANTENNA+1,ANTENNA2+3 from tTaQLNode_tmp.tab where ab'

$casa_checktool ./tTaQLNode 'calc from tTaQLNode_tmp.tab calc findcone([ab,ab],array([2rad,2rad,4rad,4rad],[2,2]),[1rad,2rad])'
$casa_checktool ./tTaQLNode 'calc from tTaQLNode_tmp.tab  calc findcone([ab,ab],[select from tTaQLNode_tmp.tab giving [ab,ab]],[1rad,2rad])'
echo ""

$casa_checktool ./tTaQLNode 'calc sum([select from tTaQLNode_tmp.tab giving [ab+1]])'
$casa_checktool ./tTaQLNode 'calc sum([select from tTaQLNode_tmp.tab giving [ab,ac,ab:ac]])'
$casa_checktool ./tTaQLNode 'calc from $1 calc sum([select ab from $1])'
$casa_checktool ./tTaQLNode 'calc from tTaQLNode_tmp.tab calc ab'
$casa_checktool ./tTaQLNode 'calc from tTaQLNode_tmp.tab calc arr1[2,1,1]'
$casa_checktool ./tTaQLNode 'calc from tTaQLNode_tmp.tab calc arr1[1+ab%2,1,1]'
$casa_checktool ./tTaQLNode 'calc from $1 calc ab+1'

echo ""

$casa_checktool ./tTaQLNode 'update tTaQLNode_tmp.tab set ab=sum(arr1)+ac*2, arr1=arr1+2 where ac>3'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab'
$casa_checktool ./tTaQLNode 'update tTaQLNode_tmp.tab set ab=sum(arr1)+ac*2, arr1=arr1+2 from tTaQLNode_tmp.tabc where ac>3 orderby ac limit 5'

$casa_checktool ./tTaQLNode 'update tTaQLNode_tmp.tab set arr1=2, ab=sum(arr1) limit 1 offset 3'
$casa_checktool ./tTaQLNode 'update tTaQLNode_tmp.tab set arr1[1,1,1]=3, arr1[2,2,2]=arr1[1,1,1], ab=sum(arr1) limit 1 offset 3'
$casa_checktool ./tTaQLNode 'update tTaQLNode_tmp.tab set arr1[1,,]=4, ab=sum(arr1) limit 1 offset 3'

$casa_checktool ./tTaQLNode 'delete from tTaQLNode_tmp.tab limit 3 offset 2'
$casa_checktool ./tTaQLNode 'delete from tTaQLNode_tmp.tab orderby desc ab limit 1 offset 2'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab'

$casa_checktool ./tTaQLNode 'delete from tTaQLNode_tmp.tab'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab'

$casa_checktool ./tTaQLNode 'insert into tTaQLNode_tmp.tab select from tTaQLNode_tmp.tabc'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab'

$casa_checktool ./tTaQLNode 'delete from tTaQLNode_tmp.tab where ab%2==0'
$casa_checktool ./tTaQLNode 'select ab from tTaQLNode_tmp.tab'

$casa_checktool ./tTaQLNode 'insert into tTaQLNode_tmp.tab (ab,ac) values (1+2,3*ab + sum([select ab from tTaQLNode_tmp.tab]))'
$casa_checktool ./tTaQLNode 'select ab,ac from tTaQLNode_tmp.tab'

$casa_checktool ./tTaQLNode 'count ab,ac+1 from tTaQLnode_tmp.tab'
$casa_checktool ./tTaQLNode 'count min(ab),ac+1 from tTaQLnode_tmp.tab where ac>1'

$casa_checktool ./tTaQLNode 'create table tTaQLNode_tmp.tab col1 i4, col2 r4 ndim=1, c3 r8 [ndim=2, shape=[3,4]] dminfo [name="ISM1",type="IncrementalStMan"], [name="SSM1",type="StandardStMan", bucketsize=1000]'
