#! /bin/sh
#-----------------------------------------------------------------------------
# Script to execute the tDirectory program via assay.
# It defines a few files, etc. to make the program work in any environment.
# Execution:
#      tDirectory.run      execute using assay (normal procedure)
#      tDirectory.run 0    only define the subdirectory, etc. (for debugging)
#      tDirectory.run 1    execute as such (to test)
#      tDirectory.run 1 1  execute without exceptions (to test leakage)
#=============================================================================

/bin/rm -rf tDirectory_tmp
mkdir tDirectory_tmp

mkdir tDirectory_tmp/linkDir
mkdir tDirectory_tmp/test1
mkdir tDirectory_tmp/test2
mkdir tDirectory_tmp/test5
ls > tDirectory_tmp/testFile
ln -s testFile tDirectory_tmp/testLink
ls > tDirectory_tmp/test1/testFile2
ln -s testFile2 tDirectory_tmp/test1/testLink2
ls > tDirectory_tmp/test1/isFile1
ls > tDirectory_tmp/test1/isFile2
mkdir tDirectory_tmp/test1/isDir1
ls > tDirectory_tmp/test1/isDir1/is1
ls > tDirectory_tmp/test1/isDir1/is2
ls > tDirectory_tmp/test1/isDir1/is3
mkdir tDirectory_tmp/test1/isDir2
ls > tDirectory_tmp/test2/isFile1
ls > tDirectory_tmp/test5/isFile

if [ $# != 0 ]
then
    if [ $1 != 0 ]
    then
        $casa_checktool ./tDirectory $2
    fi
else
    $casa_checktool ./tDirectory
fi
