#!/bin/sh

if [ ${#AIPSPATH} = 0 ]
then 
   echo "UNTESTED: tBinTable (AIPSPATH not defined)"
   exit 3
fi

DATAFILE=`echo $AIPSPATH | awk '{print $1}'`/data/demo/dishdemo/dishdemo1.fits

if [ -f $DATAFILE ]
then
  # make sure things are cleaned up
  rm -rf tBinTable_tmp.table.0
  $casa_checktool ./tBinTable inputFile=$DATAFILE baseName=tBinTable_tmp
else
  echo "UNTESTED: tBinTable, could not find the test data" $DATAFILE
  exit 3
fi
