#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test tGenSort in various ways.
#=============================================================================

  $casa_checktool ./tGenSort 2500 1
  $casa_checktool ./tGenSort 2500 2
  $casa_checktool ./tGenSort 2500 4
  $casa_checktool ./tGenSort 2500 9
  $casa_checktool ./tGenSort 2500 10
  $casa_checktool ./tGenSort 2500 12
  $casa_checktool ./tGenSort 2500 1 desc
  $casa_checktool ./tGenSort 2500 2 desc
  $casa_checktool ./tGenSort 2500 4 desc
  $casa_checktool ./tGenSort 2500 9 desc
  $casa_checktool ./tGenSort 2500 10 desc
  $casa_checktool ./tGenSort 2500 12 desc
