#!/bin/sh
#-------------------------------------------------------------------
# Script to test the StringDistance class.
#======================================================

$casa_checktool ./tStringDistance abcd abcd 0 0 0
$casa_checktool ./tStringDistance abcd abcd 1 1 1
$casa_checktool ./tStringDistance AbCd aBcD 0 0 0
$casa_checktool ./tStringDistance AbCd aBcD 0 0 1
$casa_checktool ./tStringDistance AbCd abcd 0 0 1
$casa_checktool ./tStringDistance ACbd abcd 0 0 0
$casa_checktool ./tStringDistance ACbd abcd 0 0 1
$casa_checktool ./tStringDistance ACbd abcd 1 0 1
$casa_checktool ./tStringDistance ACbd 'ab cd' 1 0 1
$casa_checktool ./tStringDistance ACbd 'ab cd' 1 1 1
$casa_checktool ./tStringDistance ab ba 1 1 1
