#! /bin/sh
#-----------------------------------------------------------------------------
# Script to execute the tFile program via assay.
# It defines a few files, etc. to make the program work in any environment.
# Execution:
#      tFile.run        execute using assay (normal procedure)
#      tFile.run 0      only define the subdirectory, etc. (for debugging)
#      tFile.run 1      execute as such (to test)
#      tFile.run 1 1    execute without exceptions (to test leakage)
#=============================================================================

/bin/rm -rf tFile_tmp
mkdir tFile_tmp

ls > tFile_tmp/isFile
mkdir tFile_tmp/isDir
ln -s $HOME tFile_tmp/isLink
mkdir tFile_tmp/isDir2
ln -s isFile tFile_tmp/isLink2

if [ $# != 0 ]
then
    if [ $1 != 0 ]
    then
        ./tFile $2
    fi
else
    ./tFile
fi
