#!/bin/sh
#-----------------------------------------------------------------------------
# ae: Extricate an AIPS++ source file from a half-completed checkin/out.
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1995,1996
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: ae file
#-----------------------------------------------------------------------------
# ae extricates a source file in the current directory from a half-completed
# RCS checkin/out.  Such problems sometimes arise when the checkin/out is
# interrupted part way through leaving behind an RCS semaphore file.
#
# 'ae' invokes $MSTRETCD/ae_master, where $AIPSMSTR is expected to be NFS
# mounted from the AIPS++ master host (aips2.nrao.edu).  It waits if
# necessary until the semaphore file is at least 15 minutes old before
# deleting it in case a slow RCS transaction is in progress.
#
# Options:
#   none
#
# Status returns:
#    0:  success
#    1:  initialization error
#    2:  semaphore file not found
#    3:  failed to delete semaphore file
#
# Notes:
#    1) The utility which generates updates for the AIPS++ code distribution
#       system ('exhale') routinely searches for and deletes all semaphore
#       files which are more than a day old.  'ae' allows particular semaphore
#       files to be deleted on a much shorter timescale.
#
# Original: 1995/02/23 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Fundamentals.
  if [ "$AIPSPATH" = "" ]
  then
     echo "ae: AIPSPATH is not defined, abort!" 1>&2
     exit 1
  fi

  AIPSROOT=`echo $AIPSPATH | awk '{ print $1 }'`

# Define AIPS++ directory names.
  AIPSMSTR=$AIPSROOT/master
  MSTRETCD=$AIPSMSTR/etc

# Check the number of arguments.
  if [ "$#" != 1 ]
  then
     exec 1>&2
     echo "Usage: ae <file>"
     exit 1
  fi

# Invoke ae_master.
  $MSTRETCD/ae_master $1


  exit $?
