#!/bin/sh
#-----------------------------------------------------------------------------
# am_master: Change the descriptive text in a master AIPS++ RCS version file
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1995,1996
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: am_master <RCSfile>
#-----------------------------------------------------------------------------
# Change the descriptive text in an master AIPS++ RCS version file.  The RCS
# version file must be specified as a fully qualified pathname with or without
# RCS (,v) suffix.  The descriptive text will be obtained from stdin.
#
# This script should reside in $AIPSMSTR on the AIPS++ master machine
# (aips2.nrao.edu) and be setuid to the owner of the AIPS++ master RCS version
# files (aips2adm).
#
# 'am_master' should not be accessed directly, but via the 'am' script in the
# $AIPSARCH/bin area which executes this.
#
# Status returns:
#    0:  success
#    1:  initialization error
#    2:  modifications are disabled or restricted
#    3:  modification failed
#
# Original: 1995/03/17 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Fundamentals.
  if [ "$AIPSPATH" = "" ]
  then
     echo "am_master: AIPSPATH is not defined, abort!" 1>&2
     exit 1
  fi

  AIPSROOT=`echo $AIPSPATH | awk '{ print $1 }'`

# Define AIPS++ directory names.
  AIPSMSTR=$AIPSROOT/master
  MSTRETCD=$AIPSMSTR/etc

# Are modifications (checkins) disabled?
  if [ -f "$MSTRETCD/ai_disable" ]
  then
     if [ -s "$MSTRETCD/ai_disable" ]
     then
        cat $MSTRETCD/ai_disable
        echo ""
     fi

     echo "am: Modifications are currently disabled, try again later." 1>&2
     exit 2
  fi

# Do the RCS modification.
  RCSINIT="" rcs -t $1
  if [ "$?" != 0 ]
  then
     echo "am_master: Modification failed, abort!" 1>&2
     exit 3
  fi


  exit 0
