#!/bin/sh
#-----------------------------------------------------------------------------
# ao_master: Check out AIPS++ sources from the master
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1992,1993,1994,1996
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: ao_master [co options] file RCSfile
#-----------------------------------------------------------------------------
# Extract an AIPS++ source file from the master RCS repository.
#
# This script should reside in $AIPSMSTR on the AIPS++ master machine
# (aips2.nrao.edu) and be setuid to the owner of the AIPS++ master RCS version
# files (aips2adm).
#
# 'ao_master' should not be accessed directly, but via the 'ao' script in the
# $AIPSARCH/bin area which executes this.
#
# Status returns:
#    0:  success
#    1:  initialization error
#    2:  checkouts are disabled
#    3:  checkout failed
#
# Original: 1992/04/29 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Fundamentals.
  if [ ! "$AIPSPATH" ]
  then
     echo "ao_master: AIPSPATH is not defined, abort!"
     exit 1
  fi

  AIPSROOT=`echo $AIPSPATH | awk '{ print $1 }'`

# Define AIPS++ directory names.
  AIPSMSTR=$AIPSROOT/master
  MSTRETCD=$AIPSMSTR/etc

# Are checkouts disabled?
  if [ -f "$MSTRETCD/ao_disable" ]
  then
     if [ -s "$MSTRETCD/ao_disable" ]
     then
        cat $MSTRETCD/ao_disable
        echo ""
     fi

     echo "ao: Checkouts are currently disabled, try again later."
     exit 2
  fi

# Do the RCS check out.
  RCSINIT="" co -T $*
  if [ "$?" != 0 ]
  then
     echo "ao_master: Check out failed, abort!"
     exit 3
  fi

  exit 0
