#!/bin/sh
#-----------------------------------------------------------------------------
# ax_master: Delete or rename AIPS++ sources
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1992-1998,Wednes1998
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: ax_master [-master | -slave | -system | -archive] [-s] [-c]
#-----------------------------------------------------------------------------
# ax_master deletes or renames files and directories in the AIPS++ master,
# slave, system, or archive areas.  The action list it contains is maintained
# by 'ax' and 'amv' and should not be modified by hand.
#
# ax_master is applied
#
#    1) to the master by 'ax' or 'amv' to delete or rename master RCS version
#       files or directories,
#
#    2) to the slave  by 'inhale' immediately after each update file has been
#       installed,
#
#    3) to the system by 'sneeze' before the system is remade.  An AIPS++
#       minor version number is passed to 'sneeze' by 'inhale' so that all
#       deletions applicable to a multi-increment update can be applied,
#
#    4) to the archive by 'exhale' in the process of updating the archive in
#       preparation for a new base release.
#
# Options:
#   -master  Rescind or rename files or directories in the master RCS
#            repositories only.
#
#   -slave   Delete or rename files or directories in the slave RCS
#            repositories and plain-text code directories.
#
#   -system  Apply deletions to the slave system.  Renaming is not done -
#            the file or directory to be renamed is simply deleted since a
#            system rebuild will reconstruct whatever is necessary.
#
#   -archive Rescind or rename files or directories in the archive RCS
#            repositories only.
#
#   -c       Cumulative mode, apply all deletions or renames for this major
#            version:
#
#               master)  Fatal error.
#                slave)  Apply all actions starting from minor version 000 of
#                        the current major version.
#               system)  Apply all actions starting from minor version 000 of
#                        the current major version.  All static object
#                        libraries are also deleted.
#              archive)  Apply all actions starting from minor version 000 of
#                        the current major version.  This is done whether "-c"
#                        is specified or not.
#
#            The current version number is that stored in:
#
#               master)  $AIPSMSTR/VERSION
#                slave)  $AIPSLAVE/VERSION
#               system)  $AIPSARCH/VERSION
#              archive)  $AIPSARKV/VERSION
#
#   -s       Silent mode - don't interrogate the user.
#
# Notes:
#    1) The version number in the action list corresponds to that stored in
#       the $AIPSMSTR/VERSION file at the time the entry in this file is made.
#
#    2) Deletions or renames in the master are handled by a special action
#       list deposited in $MSTRETCD by 'ax' or 'amv'.  This list is deleted
#       after use so that the same action won't be applied twice by mistake.
#       If, on the other hand, master deletions or renames were done from
#       ax_master's own list then a file deleted and then recreated in the
#       same version would again be deleted by any subsequent invokation of
#       ax_master in the same version.
#
#    3) Files and directories are not actually deleted from the master or
#       archive but instead "rescinded" by renaming them as "dot" files which
#       makes them invisible to 'exhale'.  They are also given a prefix
#       identifying the version at the time of their "deletion".
#
#    4) See the prologue comments to 'ax' for a description of usage.
#
# Status returns:
#    0:  success
#    1:  initialization error, no action
#
# Original: 1992/05/13 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Fundamentals.
  if [ "$AIPSPATH" = "" ]
  then
     echo "ax_master: AIPSPATH is not defined, abort!" 1>&2
     exit 1
  fi

# Parse options.
  MODE=slave
  SILENT=
  VERSMIN=

  while [ "$#" -gt 0 ]
  do
     case $1 in
     -master)
        MODE=master
        ;;
     -slave)
        MODE=slave
        ;;
     -system)
        MODE=system
        ;;
     -archive)
        MODE=archive
        ;;
     -c)
        VERSMIN="-1"
        ;;
     -s)
        SILENT=1
        ;;
     *)
        echo "Usage: ax_master [-master | -slave | -system] [-c] [-s]" 1>&2
        exit 1
        ;;
     esac

     [ "$2" = "" ] && break

     shift
  done

  if [ "$MODE" = master -a "$VERSMIN" != "" ]
  then
     echo "ax_master: Cumulative mode may not be specified for the master," \
          "abort!" 1>&2
     exit 1
  fi

  if [ "$SILENT" = "" ]
  then
     echo ""
     echo "ax_master is used by the AIPS++ code management system to delete"
     echo "or rename AIPS++ files or directories, including RCS version"
     echo "files, library members and executables.  It is provided so that"
     echo "AIPS++ slave installations can keep track of the master."
     echo ""
     echo "ax_master contains an action list which is maintained by 'ax' (for"
     echo "deletions) and 'amv' (for renaming).  These are the commands"
     echo "for general use, normally ax_master should not be invoked by hand."
     echo ""
     echo "        ax_master IS NOT INTENDED FOR CASUAL USE!"
     echo ""
     echo -n "Continue (y/n) [n]: "
     read ANSWER
     [ "$ANSWER" = y ] || exit 1
  fi


# Define major AIPS++ directories.
  AIPSROOT=`echo $AIPSPATH | awk '{ print $1 }'`
  ARCH=`echo $AIPSPATH | awk '{ print $2 }'`
  AIPSARCH="$AIPSROOT/$ARCH"
  AIPSCODE="$AIPSROOT/code"
  ARCHTMPD="$AIPSARCH/tmp"

# Get account information.
  if [ "$MODE" != archive ]
  then
     AIPS2MGR=`getrc -i account.manager 2> /dev/null`
     MGRGROUP=`echo $AIPS2MGR | sed -e 's/.*\.//'`
     ADMGROUP=aips2adm
  else
     ADMGROUP=aips2adm
  fi


# Interrupt processing.
  trap 'rm -f $AXDELIST $TMPFILES' 0
  trap 'exec 1>&2 ; \
        echo "" ; \
        echo "Cleaning up..." ; \
        exit 1' 1 2 3 15

  case $MODE in
  master)
#    Actions on the master.
     AIPSMSTR="$AIPSROOT/master"
     MSTRETCD="$AIPSMSTR/etc"

#    Get the master's version number.
     if [ ! -f "$AIPSMSTR/VERSION" ]
     then
        echo "ax_master: Couldn't find $AIPSMSTR/VERSION, abort!" 1>&2
        exit 1
     fi

     MSTRVERS=`cat $AIPSMSTR/VERSION | awk '{ print $1 }'`
     MSTRMAJ=`echo $MSTRVERS | awk -F. '{ print $1 }'`
     MSTRMIN=`echo $MSTRVERS | awk -F. '{ print $2 }'`
     MAJMIN=$MSTRMAJ.$MSTRMIN

     if [ ! -f "$MSTRETCD/ax_list" ]
     then
        echo "ax_master: $MSTRETCD/ax_list not found, abort!" 1>&2
        exit 1
     fi

     AXDELIST=$MSTRETCD/ax_master.$$
     grep "^$MSTRMAJ $MSTRMIN" $MSTRETCD/ax_list > $AXDELIST
     exec 3<$AXDELIST

     while read VMAJ VMIN OPCODE ACTION ARG1 ARG2 ARG3 0<&3
     do
#       Strip off trailing "/".
        ARG1=`echo $ARG1 | sed -e 's#//*$##'`
        ARG2=`echo $ARG2 | sed -e 's#//*$##'`

        case $ACTION in
        rm)
           if [ "$ARG2" != "" ]
           then
              echo "ax_master: Invalid deletion command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        mv)
           if [ "$ARG2" = "" -o "$ARG3" != "" ]
           then
              echo "ax_master: Invalid rename command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        *)
           echo "ax_master: Invalid action -"
           echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
           continue
           ;;
        esac

        case $OPCODE in
        src)
           case $ACTION in
           rm)
#             Deletion in the master consists of concealing the file.
              ARG2=`echo $ARG1 | sed -e 's#\([^/]*\)$#.'$MAJMIN'_\1#'`
              if [ -d "$AIPSMSTR/$ARG1" ]
              then
#                Break extant locks.
                 LOCKED=`rlog -L -R $AIPSMSTR/$ARG1/*,v`
                 [ "$LOCKED" != "" ] && rcs -M -u $LOCKED

                 if mv -f $AIPSMSTR/$ARG1 $AIPSMSTR/$ARG2
                 then
                    echo "Rescinded master directory $AIPSMSTR/$ARG1"
                 fi
              elif [ -f "$AIPSMSTR/$ARG1,v" ]
              then
#                Break extant locks.
                 if [ "`rlog -L -R $AIPSMSTR/$ARG1,v`" != "" ]
                 then
                    rcs -M -u $AIPSMSTR/$ARG1,v
                 fi

                 if mv -f $AIPSMSTR/$ARG1,v $AIPSMSTR/$ARG2,v
                 then
                    echo "Rescinded master file $AIPSMSTR/$ARG1,v"
                 fi
              fi
              ;;
           mv)
#             Rename the master directory or file.
              if [ -d "$AIPSMSTR/$ARG1" ]
              then
#                Check that the directory doesn't already exist.
                 if [ -d "$AIPSMSTR/$ARG2" ]
                 then
                    echo "Directory $AIPSMSTR/$ARG2 already exists, abort!" 1>&2
                    continue
                 fi

#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSMSTR/$ARG2

                 if mv -f $AIPSMSTR/$ARG1 $AIPSMSTR/$ARG2
                 then
                    echo "Renamed master directory"
                    echo "   from $AIPSMSTR/$ARG1"
                    echo "     to $AIPSMSTR/$ARG2"
                 fi
              elif [ -f "$AIPSMSTR/$ARG1,v" ]
              then
#                Check that the file doesn't already exist.
                 if [ -f "$AIPSMSTR/$ARG2,v" ]
                 then
                    echo "File $AIPSMSTR/$ARG2,v already exists, abort!" 1>&2
                    continue
                 fi

#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSMSTR/$ARG2

                 if mv -f $AIPSMSTR/$ARG1,v $AIPSMSTR/$ARG2,v
                 then
                    echo "Renamed master RCS version file"
                    echo "   from $AIPSMSTR/$ARG1,v"
                    echo "     to $AIPSMSTR/$ARG2,v"
                 fi
              fi
              ;;
           esac
           ;;

        sys)
#          No master system.
           continue
           ;;

        top)
#          Apply actions only to master files or directories.
           case $ARG1 in
           master/*)
#             Explicit specification of a master file (e.g. in ../master/etc).
              ;;
           rcs/*)
#             Signals an action on the master as well as the slave.
              ARG1=`echo $ARG1 | sed -e 's#^rcs/#master/#'`
              ARG2=`echo $ARG2 | sed -e 's#^rcs/#master/#'`
              ;;
           *)
              continue
              ;;
           esac

           case $ACTION in
           rm)
#             Deletion in the master consists of concealing the file.
              ARG2=`echo $ARG1 | sed -e 's#\([^/]*\)$#.'$MAJMIN'_\1#'`
              if [ -d "$AIPSROOT/$ARG1" ]
              then
#                Break extant locks.
                 LOCKED=`rlog -L -R $AIPSROOT/$ARG1/*,v`
                 [ "$LOCKED" != "" ] && rcs -M -u $LOCKED

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "Rescinded master directory $AIPSROOT/$ARG1"
                 fi
              elif [ -f "$AIPSROOT/$ARG1" ]
              then
#                Break extant locks.
                 if [ "`rlog -L -R $AIPSROOT/$ARG1`" != "" ]
                 then
                    rcs -M -u $AIPSROOT/$ARG1
                 fi

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "Rescinded master file $AIPSROOT/$ARG1"
                 fi
              fi
              ;;
           mv)
#             Rename the master directory or file.
              if [ -d "$AIPSROOT/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSROOT/$ARG2

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "Renamed master directory"
                    echo "   from $AIPSROOT/$ARG1"
                    echo "     to $AIPSROOT/$ARG2"
                 fi
              elif [ -f "$AIPSROOT/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSROOT/$ARG2

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "Renamed master RCS version file"
                    echo "   from $AIPSROOT/$ARG1"
                    echo "     to $AIPSROOT/$ARG2"
                 fi
              fi
              ;;
           esac
           ;;

        *)
           echo "ax_master: Unknown opcode, $OPCODE"
           ;;
        esac
     done

     rm -f $MSTRETCD/ax_list
     ;;

  slave)
#    Actions on the slave.
     AIPSLAVE="$AIPSROOT/slave"

#    Get the current version number.
     if [ ! -f "$AIPSLAVE/VERSION" ]
     then
        echo "ax_master: Couldn't find $AIPSLAVE/VERSION, abort!" 1>&2
        exit 1
     fi

     SLAVERS=`cat $AIPSLAVE/VERSION | awk '{ print $1 }'`
     SLAVMAJ=`echo $SLAVERS | awk -F. '{ print $1 }'`
     SLAVMIN=`echo $SLAVERS | awk -F. '{ print $2 }'`
     [ "$VERSMIN" = "" ] || SLAVMIN="$VERSMIN"

#    List all actions for this major version.
     AXDELIST=$ARCHTMPD/ax_master.$$
     grep "^$SLAVMAJ " $0 > $AXDELIST
     exec 3<$AXDELIST

     while read VMAJ VMIN OPCODE ACTION ARG1 ARG2 ARG3 0<&3
     do
#       Test the minor version.
        [ "$VMIN" -lt "$SLAVMIN" ] && continue

        case $ACTION in
        rm)
           if [ "$ARG2" != "" ]
           then
              echo "ax_master: Invalid deletion command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        mv)
           if [ "$ARG2" = "" -o "$ARG3" != "" ]
           then
              echo "ax_master: Invalid rename command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        *)
           echo "ax_master: Invalid action -"
           echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
           continue
           ;;
        esac

        case $OPCODE in
        src)
           case $ACTION in
           rm)
#             Check the slave RCS repository.
              if [ -d "$AIPSLAVE/$ARG1" ]
              then
                 if rm -rf $AIPSLAVE/$ARG1
                 then
                    echo "Deleted directory $AIPSLAVE/$ARG1"
                 fi
              elif [ -f "$AIPSLAVE/$ARG1,v" ]
              then
                 if rm -f $AIPSLAVE/$ARG1,v
                 then
                    echo "Deleted file $AIPSLAVE/$ARG1,v"
                 fi
              fi

#             Check the code area.
              if [ -d "$AIPSCODE/$ARG1" ]
              then
                 if rm -rf $AIPSCODE/$ARG1
                 then
                    echo "Deleted directory $AIPSCODE/$ARG1"
                 fi
              elif [ -f "$AIPSCODE/$ARG1" ]
              then
                 if rm -f $AIPSCODE/$ARG1
                 then
                    echo "Deleted file $AIPSCODE/$ARG1"
                 fi
              fi
              ;;
           mv)
#             Check the slave RCS repository.
              if [ -d "$AIPSLAVE/$ARG1" ]
              then
#                Delete the directory if it already exists.
                 [ -d "$AIPSLAVE/$ARG2" ] && rm -rf $AIPSLAVE/$ARG2

#                Create the target directory if necessary.
                 amkdir -g $MGRGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSLAVE/$ARG2

                 if mv -f $AIPSLAVE/$ARG1 $AIPSLAVE/$ARG2
                 then
                    echo "Renamed slave directory"
                    echo "   from $AIPSLAVE/$ARG1"
                    echo "     to $AIPSLAVE/$ARG2"
                 fi
              elif [ -f "$AIPSLAVE/$ARG1,v" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $MGRGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSLAVE/$ARG2

                 if mv -f $AIPSLAVE/$ARG1,v $AIPSLAVE/$ARG2,v
                 then
                    echo "Renamed slave RCS version file"
                    echo "   from $AIPSLAVE/$ARG1,v"
                    echo "     to $AIPSLAVE/$ARG2,v"
                 fi
              fi

#             Check the code area.
              if [ -d "$AIPSCODE/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $MGRGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSCODE/$ARG2

                 if mv -f $AIPSCODE/$ARG1 $AIPSCODE/$ARG2
                 then
                    echo "Renamed code directory"
                    echo "   from $AIPSCODE/$ARG1"
                    echo "     to $AIPSCODE/$ARG2"

                    echo "Delete misdirected RCS symlinks:"
                    find $AIPSCODE/$ARG2 -name RCS -type l -print \
                       -exec rm -f {} \;
                 fi
              elif [ -f "$AIPSCODE/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $MGRGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSCODE/$ARG2

                 if mv -f $AIPSCODE/$ARG1 $AIPSCODE/$ARG2
                 then
                    echo "Renamed code file"
                    echo "   from $AIPSCODE/$ARG1"
                    echo "     to $AIPSCODE/$ARG2"
                 fi
              fi
              ;;
           esac
           ;;

        sys)
#          No slave system.
           continue
           ;;

        top)
           case $ACTION in
           rm)
#             Check for directory deletion.
              if [ -d "$AIPSROOT/$ARG1" ]
              then
                 if rm -rf $AIPSROOT/$ARG1
                 then
                    echo "Deleted directory $AIPSROOT/$ARG1"
                 fi
              elif [ -f "$AIPSROOT/$ARG1" ]
              then
                 if rm -f $AIPSROOT/$ARG1
                 then
                    echo "Deleted file $AIPSROOT/$ARG1"
                 fi
              fi
              ;;
           mv)
#             Check for directory renaming.
              if [ -d "$AIPSROOT/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $MGRGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSROOT/$ARG2

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "Renamed directory"
                    echo "   from $AIPSROOT/$ARG1"
                    echo "     to $AIPSROOT/$ARG2"
                 fi
              elif [ -f "$AIPSROOT/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $MGRGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSROOT/$ARG2

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "Renamed file"
                    echo "   from $AIPSROOT/$ARG1"
                    echo "     to $AIPSROOT/$ARG2"
                 fi
              fi
              ;;
           esac
           ;;

        *)
           echo "ax_master: Unknown opcode, $OPCODE"
           ;;
        esac
     done
     ;;

  system)
#    Get the code's current version number.
     if [ ! -f "$AIPSCODE/VERSION" ]
     then
        echo "ax_master: Couldn't find $AIPSCODE/VERSION, abort!" 1>&2
        exit 1
     else
        CODEVERS=`cat $AIPSCODE/VERSION | awk '{ print $1 }'`
        CODEMAJ=`echo $CODEVERS | awk -F. '{ print $1 }'`
     fi

#    Get the system's current version number.
     if [ -f "$AIPSARCH/VERSION" ]
     then
        SYSVERS=`cat $AIPSARCH/VERSION | awk '{ print $1 }'`
        SYSMAJ=`echo $SYSVERS | awk -F. '{ print $1 }'`
        SYSMIN=`echo $SYSVERS | awk -F. '{ print $2 }'`

        if [ "$SYSMAJ" != "$CODEMAJ" ]
        then
           SYSMAJ="$CODEMAJ"
           SYSMIN="-1"
        else
           [ "$VERSMIN" = "" ] || SYSMIN="$VERSMIN"
        fi
     else
        SYSMAJ="$CODEMAJ"
        SYSMIN="-1"
     fi

     if [ "$SYSMIN" -lt 0 ]
     then
#       Delete all static object libraries.
        PACKAGES="`(cd $AIPSCODE ; ls -d */implement | \
           sed -e 's#/implement##')`"
        for PACKAGE in $PACKAGES
        do
           if [ -f "$AIPSARCH/lib/lib${PACKAGE}.a" ]
           then
              rm -f "$AIPSARCH/lib/lib${PACKAGE}.a"
              rm -f "$AIPSARCH/lib/lib${PACKAGE}-*.a"
              echo "Deleted $AIPSARCH/lib/lib${PACKAGE}.a"
           fi

           if [ -f "$AIPSARCH/lib/lib${PACKAGE}_c.a" ]
           then
              rm -f "$AIPSARCH/lib/lib${PACKAGE}_c.a"
              rm -f "$AIPSARCH/lib/lib${PACKAGE}-*_c.a"
              echo "Deleted $AIPSARCH/lib/lib${PACKAGE}_c.a"
           fi

           if [ -f "$AIPSARCH/lib/lib${PACKAGE}_f.a" ]
           then
              rm -f "$AIPSARCH/lib/lib${PACKAGE}_f.a"
              rm -f "$AIPSARCH/lib/lib${PACKAGE}-*_f.a"
              echo "Deleted $AIPSARCH/lib/lib${PACKAGE}_f.a"
           fi

           if [ -f "$AIPSARCH/libdbg/lib${PACKAGE}.a" ]
           then
              rm -f "$AIPSARCH/libdbg/lib${PACKAGE}.a"
              rm -f "$AIPSARCH/libdbg/lib${PACKAGE}-*.a"
              echo "Deleted $AIPSARCH/libdbg/lib${PACKAGE}.a"
           fi

           if [ -f "$AIPSARCH/libdbg/lib${PACKAGE}_c.a" ]
           then
              rm -f "$AIPSARCH/libdbg/lib${PACKAGE}_c.a"
              rm -f "$AIPSARCH/libdbg/lib${PACKAGE}-*_c.a"
              echo "Deleted $AIPSARCH/libdbg/lib${PACKAGE}_c.a"
           fi

           if [ -f "$AIPSARCH/libdbg/lib${PACKAGE}_f.a" ]
           then
              rm -f "$AIPSARCH/libdbg/lib${PACKAGE}_f.a"
              rm -f "$AIPSARCH/libdbg/lib${PACKAGE}-*_f.a"
              echo "Deleted $AIPSARCH/libdbg/lib${PACKAGE}_f.a"
           fi
        done
     fi

#    List all actions for this major version.
     AXDELIST=$ARCHTMPD/ax_master.$$
     grep "^$SYSMAJ " $0 > $AXDELIST
     exec 3<$AXDELIST

     LIBMBRS=""

     while read VMAJ VMIN OPCODE ACTION ARG1 ARG2 ARG3 0<&3
     do
#       Test the minor version.
        [ "$VMIN" -lt "$SYSMIN" ] && continue

        case $ACTION in
        rm)
           if [ "$ARG2" != "" ]
           then
              echo "ax_master: Invalid deletion command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        mv)
           if [ "$ARG2" = "" -o "$ARG3" != "" ]
           then
              echo "ax_master: Invalid rename command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        *)
           echo "ax_master: Invalid action -"
           echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
           continue
           ;;
        esac

        case $OPCODE in
        src)
#          Is it a library member?
           case $ARG1 in
           */implement/*/test/* | */fortran/*/test/*)
#             Ignore test code.
              ;;
           */implement/*.cc | */fortran/*.f)
              case $ARG1 in
              */implement/*)
                 PACKAGE=`echo $ARG1 | sed -e 's#/implement/.*##'`
                 MEMBER=`echo $ARG1 | sed -e 's#.*/##' -e 's#\.cc#.o#'`
                 ;;
              */fortran/*)
                 PACKAGE=`echo $ARG1 | sed -e 's#/fortran/.*#_f#'`
                 MEMBER=`echo $ARG1 | sed -e 's#.*/##' -e 's#\.f#.o#'`
                 ;;
              esac

              LIBR=lib${PACKAGE}.a

              if [ -f "$AIPSARCH/lib/$LIBR" -o  -f "$AIPSARCH/libdbg/$LIBR" ]
              then
                 LIBMBRS="$LIBMBRS $LIBR($MEMBER)"
              fi
              ;;

           */implement/*.h)
#             Delete extracted documentation.
              if [ -f "$AIPSROOT/docs/${ARG1}tml" ]
              then
                 if rm -f $AIPSROOT/docs/${ARG1}tml
                 then
                    echo "Deleted file $AIPSROOT/docs/${ARG1}tml"
                 fi
              fi
              ;;

           */implement/*.gif)
#             Delete gifs associated with extracted documentation.
              if [ -f "$AIPSROOT/docs/$ARG1" ]
              then
                 if rm -f $AIPSROOT/docs/$ARG1
                 then
                    echo "Deleted file $AIPSROOT/docs/$ARG1"
                 fi
              fi
              ;;

           *)
#             Check for directory deletion or renaming.
              if [ -d "$AIPSROOT/docs/$ARG1" ]
              then
                 if rm -rf $AIPSROOT/docs/$ARG1
                 then
                    echo "Deleted directory $AIPSROOT/docs/$ARG1"
                 fi
              fi

#             The object libraries should also be updated for directory
#             deletion / renaming but there's no easy way to do that.
              ;;

           esac
           ;;

        sys)
#          Must consider library members.
           case $ARG1 in
           *\(*\))
              LIBR=`echo $ARG1 | sed -e '{s#(.*##;s#.*/##;}'`
              MEMBER=`echo $ARG1 | sed -e 's#.*(##' -e 's#)$##'`

              if [ -f "$AIPSARCH/lib/$LIBR" -o  -f "$AIPSARCH/libdbg/$LIBR" ]
              then
                 LIBMBRS="$LIBMBRS $LIBR($MEMBER)"
              fi
              ;;

           *)
              if [ -d "$AIPSARCH/$ARG1" ]
              then
                 if rm -rf $AIPSARCH/$ARG1
                 then
                    echo "Deleted directory $AIPSARCH/$ARG1"
                 fi
              elif [ -f "$AIPSARCH/$ARG1" ]
              then
                 if rm -f $AIPSARCH/$ARG1
                 then
                    echo "Deleted file $AIPSARCH/$ARG1"
                 fi
              fi
              ;;
           esac
           ;;

        top)
#          Only allow deletions for this host's architecture.
           case $ARG1 in
           $ARCH/*)
#             Check for directory deletion.
              if [ -d "$AIPSROOT/$ARG1" ]
              then
                 if rm -rf $AIPSROOT/$ARG1
                 then
                    echo "Deleted directory $AIPSROOT/$ARG1"
                 fi
              elif [ -f "$AIPSROOT/$ARG1" ]
              then
                 if rm -f $AIPSROOT/$ARG1
                 then
                    echo "Deleted file $AIPSROOT/$ARG1"
                 fi
              fi
              ;;

           *)
              continue
              ;;
           esac
           ;;

        *)
           echo "ax_master: Unknown opcode, $OPCODE"
           ;;
        esac
     done

#    Any libraries to update?
     if [ "$LIBMBRS" != "" ]
     then
#       Load makedefs variables into the environment.
        eval `gmake -f $AIPSARCH/makedefs VARS="AR ARFLAGS" eval_vars`
        ARDFLAGS="`echo $ARFLAGS | sed -e 's/r/d/'`"

#       Sort LIBMBRS removing duplicate entries.
        LIBMBRS=`for LIBMBR in $LIBMBRS
             do
                echo $LIBMBR
             done | sort -u`

#       Get the list of libraries.
        LIBS=`echo "$LIBMBRS" | sed -e 's/(.*)//' | sort -u`

#       Process each library in turn.
        for LIBR in $LIBS
        do
#          Find all members to be deleted from this library.
           MEMBERS=`echo "$LIBMBRS" | sed -n -e /$LIBR'/s/.*(\(.*\))/\1/p'`

#          Account for OS-dependent archive member name truncation.
           for MEMBER in $MEMBERS
           do
              TMPFILES="$ARCHTMPD/$MEMBER $ARCHTMPD/libax.$$"
              echo dummy > $ARCHTMPD/$MEMBER
              $AR r $ARCHTMPD/libax.$$ $ARCHTMPD/$MEMBER 2> /dev/null
              rm -f $ARCHTMPD/$MEMBER
           done
           MEMBERS=`$AR t $ARCHTMPD/libax.$$`
           rm -f $ARCHTMPD/libax.$$

           UPDATE=""

           if [ -f "$AIPSARCH/lib/$LIBR" ]
           then
              echo "Members to be deleted from $AIPSARCH/lib/$LIBR:"
              echo "$MEMBERS"
              $AR $ARDFLAGS $AIPSARCH/lib/$LIBR $MEMBERS && UPDATE=1
           fi

           if [ -f "$AIPSARCH/libdbg/$LIBR" ]
           then
              echo "Members to be deleted from $AIPSARCH/libdbg/$LIBR:"
              echo "$MEMBERS"
              $AR $ARDFLAGS $AIPSARCH/libdbg/$LIBR $MEMBERS && UPDATE=1
           fi

#          Update the library.
           if [ "$UPDATE" != "" ]
           then
              PACKAGE=`echo $LIBR | sed -e 's/lib\(.*\)\.a/\1/'`
              updatelib -f $PACKAGE
           fi
        done
     fi
     ;;

  archive)
#    Actions on the archive.
     AIPSARKV="$AIPSROOT/archive"

#    Get the archive's version number.
     if [ ! -f "$AIPSARKV/VERSION" ]
     then
        echo "ax_master: Couldn't find $AIPSARKV/VERSION, abort!" 1>&2
        exit 1
     fi

     ARKVVERS=`cat $AIPSARKV/VERSION | awk '{ print $1 }'`
     ARKVMAJ=`echo $ARKVVERS | awk -F. '{ print $1 }'`

     AXDELIST=/tmp/ax_master.$$
     grep "^$ARKVMAJ " $0 > $AXDELIST
     exec 3<$AXDELIST

     while read VMAJ VMIN OPCODE ACTION ARG1 ARG2 ARG3 0<&3
     do
#       Strip off trailing "/".
        ARG1=`echo $ARG1 | sed -e 's#//*$##'`
        ARG2=`echo $ARG2 | sed -e 's#//*$##'`

        case $ACTION in
        rm)
           if [ "$ARG2" != "" ]
           then
              echo "ax_master: Invalid deletion command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        mv)
           if [ "$ARG2" = "" -o "$ARG3" != "" ]
           then
              echo "ax_master: Invalid rename command -"
              echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
              continue
           fi
           ;;
        *)
           echo "ax_master: Invalid action -"
           echo "           $VMAJ $VMIN $OPCODE $ACTION $ARG1 $ARG2 $ARG3"
           continue
           ;;
        esac

        MAJMIN="$VMAJ.$VMIN"

        case $OPCODE in
        src)
           case $ACTION in
           rm)
#             Deletion in the archive consists of concealing the file.
              ARG2=`echo $ARG1 | sed -e 's#\([^/]*\)$#.'$MAJMIN'_\1#'`
              if [ -d "$AIPSARKV/$ARG1" ]
              then
                 if mv -f $AIPSARKV/$ARG1 $AIPSARKV/$ARG2
                 then
                    echo "$MAJMIN: Rescinded directory $AIPSARKV/$ARG1"
                 fi
              elif [ -f "$AIPSARKV/$ARG1,v" ]
              then
                 if mv -f $AIPSARKV/$ARG1,v $AIPSARKV/$ARG2,v
                 then
                    echo "$MAJMIN: Rescinded file $AIPSARKV/$ARG1,v"
                 fi
              fi
              ;;
           mv)
#             Rename the archive directory or file.
              if [ -d "$AIPSARKV/$ARG1" ]
              then
#                Check that the directory doesn't already exist.
                 if [ -d "$AIPSARKV/$ARG2" ]
                 then
                    echo "Directory $AIPSARKV/$ARG2 already exists, abort!" 1>&2
                    continue
                 fi

#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSARKV/$ARG2

                 if mv -f $AIPSARKV/$ARG1 $AIPSARKV/$ARG2
                 then
                    echo "$MAJMIN: Renamed archive directory"
                    echo "   from $AIPSARKV/$ARG1"
                    echo "     to $AIPSARKV/$ARG2"
                 fi
              elif [ -f "$AIPSARKV/$ARG1,v" ]
              then
#                Check that the file doesn't already exist.
                 if [ -f "$AIPSARKV/$ARG2,v" ]
                 then
                    echo "File $AIPSARKV/$ARG2,v already exists, abort!" 1>&2
                    continue
                 fi

#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSARKV/$ARG2

                 if mv -f $AIPSARKV/$ARG1,v $AIPSARKV/$ARG2,v
                 then
                    echo "$MAJMIN: Renamed archive RCS version file"
                    echo "   from $AIPSARKV/$ARG1,v"
                    echo "     to $AIPSARKV/$ARG2,v"
                 fi
              fi
              ;;
           esac
           ;;

        sys)
#          No archive system.
           continue
           ;;

        top)
#          Apply actions only to master files or directories.
           case $ARG1 in
           master/*)
#             Explicit specification of a master file (e.g. in ../master/etc).
              ARG1=`echo $ARG1 | sed -e 's#^master/#archive/#'`
              ;;
           rcs/*)
#             Signals an action on the master as well as the slave.
              ARG1=`echo $ARG1 | sed -e 's#^rcs/#archive/#'`
              ARG2=`echo $ARG2 | sed -e 's#^rcs/#archive/#'`
              ;;
           *)
              continue
              ;;
           esac

           case $ACTION in
           rm)
#             Deletion in the archive consists of concealing the file.
              ARG2=`echo $ARG1 | sed -e 's#\([^/]*\)$#.'$MAJMIN'_\1#'`
              if [ -d "$AIPSROOT/$ARG1" ]
              then
                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "$MAJMIN: Rescinded directory $AIPSROOT/$ARG1"
                 fi
              elif [ -f "$AIPSROOT/$ARG1" ]
              then
                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "$MAJMIN: Rescinded file $AIPSROOT/$ARG1"
                 fi
              fi
              ;;
           mv)
#             Rename the archive directory or file.
              if [ -d "$AIPSROOT/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSROOT/$ARG2

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "$MAJMIN: Renamed archive directory"
                    echo "   from $AIPSROOT/$ARG1"
                    echo "     to $AIPSROOT/$ARG2"
                 fi
              elif [ -f "$AIPSROOT/$ARG1" ]
              then
#                Create the target directory if necessary.
                 amkdir -g $ADMGROUP -p ug=rwx,o=rx,g+s -s -v $AIPSROOT/$ARG2

                 if mv -f $AIPSROOT/$ARG1 $AIPSROOT/$ARG2
                 then
                    echo "$MAJMIN: Renamed archive RCS version file"
                    echo "   from $AIPSROOT/$ARG1"
                    echo "     to $AIPSROOT/$ARG2"
                 fi
              fi
              ;;
           esac
           ;;

        *)
           echo "ax_master: Unknown opcode, $OPCODE"
           ;;
        esac
     done
     ;;
  esac


# Delete the action lists.
  rm -f $AXDELIST

  exit 0

#-----------------------------------------------------------------------------
# Data section:
# The action list is maintained by ax, do not change it by hand.
#-----------------------------------------------------------------------------
10 005 src rm doc/html/navpages/learnmore/ahrecipe.tex
10 008 src rm aips/implement/Measures/UnitExpress.h
10 010 src mv trial/implement/Lattices/LatticeConvolver.h trial/implement/Lattices/Lattice2Convolver.h
10 010 src mv trial/implement/Lattices/Lattice2Convolver.h trial/implement/Lattices/LatticeConvolver.h
10 010 src mv aips/implement/Quantum aips/implement/Quanta
10 010 src mv aips/implement/Measures/QBase.h aips/implement/Quanta/QBase.h
10 010 src mv aips/implement/Measures/QC.cc aips/implement/Quanta/QC.cc
10 010 src mv aips/implement/Measures/QC.h aips/implement/Quanta/QC.h
10 010 src mv aips/implement/Measures/QLogical.cc aips/implement/Quanta/QLogical.cc
10 010 src mv aips/implement/Measures/QLogical.h aips/implement/Quanta/QLogical.h
10 010 src mv aips/implement/Measures/QLogical2.cc aips/implement/Quanta/QLogical2.cc
10 010 src mv aips/implement/Measures/QMath.cc aips/implement/Quanta/QMath.cc
10 010 src mv aips/implement/Measures/QMath.h aips/implement/Quanta/QMath.h
10 010 src mv aips/implement/Measures/QMath2.cc aips/implement/Quanta/QMath2.cc
10 010 src mv aips/implement/Measures/Quantum.cc aips/implement/Quanta/Quantum.cc
10 010 src mv aips/implement/Measures/Quantum.h aips/implement/Quanta/Quantum.h
10 010 src mv aips/implement/Measures/Quantum2.cc aips/implement/Quanta/Quantum2.cc
10 010 src mv aips/implement/Measures/QuantumHolder.cc aips/implement/Quanta/QuantumHolder.cc
10 010 src mv aips/implement/Measures/QuantumHolder.h aips/implement/Quanta/QuantumHolder.h
10 010 src mv aips/implement/Measures/QuantumHolder2.cc aips/implement/Quanta/QuantumHolder2.cc
10 010 src mv aips/implement/Measures/Unit.cc aips/implement/Quanta/Unit.cc
10 010 src mv aips/implement/Measures/Unit.h aips/implement/Quanta/Unit.h
10 010 src mv aips/implement/Measures/UnitDim.cc aips/implement/Quanta/UnitDim.cc
10 010 src mv aips/implement/Measures/UnitDim.h aips/implement/Quanta/UnitDim.h
10 010 src mv aips/implement/Measures/UnitMap.cc aips/implement/Quanta/UnitMap.cc
10 010 src mv aips/implement/Measures/UnitMap.h aips/implement/Quanta/UnitMap.h
10 010 src mv aips/implement/Measures/UnitName.cc aips/implement/Quanta/UnitName.cc
10 010 src mv aips/implement/Measures/UnitName.h aips/implement/Quanta/UnitName.h
10 010 src mv aips/implement/Measures/UnitVal.cc aips/implement/Quanta/UnitVal.cc
10 010 src mv aips/implement/Measures/UnitVal.h aips/implement/Quanta/UnitVal.h
10 010 src mv aips/implement/Measures/MUString.cc aips/implement/Quanta/MUString.cc
10 010 src mv aips/implement/Measures/MUString.h aips/implement/Quanta/MUString.h
10 010 src mv aips/implement/Measures/MVAngle.cc aips/implement/Quanta/MVAngle.cc
10 010 src mv aips/implement/Measures/MVAngle.h aips/implement/Quanta/MVAngle.h
10 010 src mv aips/implement/Measures/MVTime.cc aips/implement/Quanta/MVTime.cc
10 010 src mv aips/implement/Measures/MVTime.h aips/implement/Quanta/MVTime.h
10 010 src mv aips/implement/Measures/Euler.cc aips/implement/Quanta/Euler.cc
10 010 src mv aips/implement/Measures/Euler.h aips/implement/Quanta/Euler.h
10 010 src mv aips/implement/Measures/RotMatrix.cc aips/implement/Quanta/RotMatrix.cc
10 010 src mv aips/implement/Measures/RotMatrix.h aips/implement/Quanta/RotMatrix.h
10 010 src mv aips/implement/Measures/test/dMUString.cc aips/implement/Quanta/test/dMUString.cc
10 010 src mv aips/implement/Measures/test/tQuantum.cc aips/implement/Quanta/test/tQuantum.cc
10 010 src mv aips/implement/Measures/test/tQuantum.out aips/implement/Quanta/test/tQuantum.out
10 010 src mv aips/implement/Measures/test/tQuantumHolder.cc aips/implement/Quanta/test/tQuantumHolder.cc
10 010 src mv aips/implement/Measures/test/tQuantumHolder.out aips/implement/Quanta/test/tQuantumHolder.out
10 010 src mv aips/implement/Measures/test/tUnit.cc aips/implement/Quanta/test/tUnit.cc
10 010 src mv aips/implement/Measures/test/tUnit.out aips/implement/Quanta/test/tUnit.out
10 010 src mv aips/implement/Measures/QBase.cc aips/implement/Quanta/QBase.cc
10 012 src rm atnf/implement/pks/HVCBandPass_median.cc
10 012 src rm atnf/implement/pks/HVCBandPass_median.h
10 014 src mv trial/implement/Measures/Muvw.cc aips/implement/Measures/Muvw.cc
10 014 src mv trial/implement/Measures/MVuvw.cc aips/implement/Measures/MVuvw.cc
10 014 src mv trial/implement/Measures/MVuvw.h aips/implement/Measures/MVuvw.h
10 014 src mv trial/implement/Measures/MCuvw.h aips/implement/Measures/MCuvw.h
10 014 src mv trial/implement/Measures/MCuvw.cc aips/implement/Measures/MCuvw.cc
10 014 src mv trial/implement/Measures/test/tMuvw.cc aips/implement/Measures/test/tMuvw.cc
10 014 src mv trial/implement/Measures/test/tMuvw.out aips/implement/Measures/test/tMuvw.out
10 014 src mv trial/implement/Measures/Muvw.h aips/implement/Measures/Muvw.h
10 014 src mv trial/implement/Measures/MBaseline.cc aips/implement/Measures/MBaseline.cc
10 014 src mv trial/implement/Measures/MBaseline.h aips/implement/Measures/MBaseline.h
10 014 src mv trial/implement/Measures/MVBaseline.h aips/implement/Measures/MVBaseline.h
10 014 src mv trial/implement/Measures/MVBaseline.cc aips/implement/Measures/MVBaseline.cc
10 014 src mv trial/implement/Measures/MCBaseline.cc aips/implement/Measures/MCBaseline.cc
10 014 src mv trial/implement/Measures/MCBaseline.h aips/implement/Measures/MCBaseline.h
10 014 src mv trial/implement/Measures/test/tMBaseline.cc aips/implement/Measures/test/tMBaseline.cc
10 014 src mv trial/implement/Measures/test/tMBaseline.out aips/implement/Measures/test/tMBaseline.out
10 014 src rm aips/implement/Measures/test/tMeasure.cc-old
10 019 src mv trial/apps/datalinetool/datagroup.g trial/implement/Datalinetool/datagroup.g
10 019 src mv trial/implement/Measures/MEarthMagnetic.cc aips/implement/Measures/MEarthMagnetic.cc
10 019 src mv trial/implement/Measures/MEarthMagnetic.h aips/implement/Measures/MEarthMagnetic.h
10 019 src mv trial/implement/Measures/MCEarthMagnetic.h aips/implement/Measures/MCEarthMagnetic.h
10 019 src mv trial/implement/Measures/MCEarthMagnetic.cc aips/implement/Measures/MCEarthMagnetic.cc
10 019 src mv trial/implement/Measures/MVEarthMagnetic.cc aips/implement/Measures/MVEarthMagnetic.cc
10 019 src mv trial/implement/Measures/MVEarthMagnetic.h aips/implement/Measures/MVEarthMagnetic.h
10 019 src mv trial/implement/Measures/EarthField.h aips/implement/Measures/EarthField.h
10 019 src mv trial/implement/Measures/EarthField.cc aips/implement/Measures/EarthField.cc
10 019 src mv trial/implement/Measures/EarthMagneticMachine.cc aips/implement/Measures/EarthMagneticMachine.cc
10 019 src mv trial/implement/Measures/EarthMagneticMachine.h aips/implement/Measures/EarthMagneticMachine.h
10 019 src mv trial/implement/Measures/test/tEarthMagneticMachine.cc aips/implement/Measures/test/tEarthMagneticMachine.cc
10 019 src mv trial/implement/Measures/test/tMEarthMagnetic.cc aips/implement/Measures/test/tMEarthMagnetic.cc
10 019 src mv trial/implement/Measures/test/tEarthField.cc aips/implement/Measures/test/tEarthField.cc
10 019 src mv trial/implement/Measures/test/tEarthMagneticMachine.out aips/implement/Measures/test/tEarthMagneticMachine.out
10 019 src mv trial/implement/Measures/test/tMEarthMagnetic.out aips/implement/Measures/test/tMEarthMagnetic.out
10 019 src mv trial/implement/Measures/test/tEarthField.out aips/implement/Measures/test/tEarthField.out
10 020 src mv trial/apps/datalinetool/dataline.g trial/implement/Datalinetool/dataline.g
10 020 src mv trial/apps/datalinetool/datalinetool.help trial/implement/Datalinetool/datalinetool.help
10 020 src mv trial/apps/datalinetool/dgplot.g trial/implement/Datalinetool/dgplot.g
10 020 src mv trial/apps/datalinetool/dlt_col.g trial/implement/Datalinetool/dlt_col.g
10 020 src mv trial/apps/datalinetool/dlt_style.g trial/implement/Datalinetool/dlt_style.g
10 020 src mv trial/apps/datalinetool/dlt_zoom.g trial/implement/Datalinetool/dlt_zoom.g
10 020 src mv trial/apps/datalinetool/dltplot.g trial/implement/Datalinetool/dltplot.g
10 020 src mv trial/apps/datalinetool/makefile trial/implement/Datalinetool/makefile
10 020 src mv trial/apps/datalinetool/textgroup.g trial/implement/Datalinetool/textgroup.g
10 020 src mv trial/apps/datalinetool/tgplot.g trial/implement/Datalinetool/tgplot.g
10 030 src rm trial/apps/gmisc/gmisc.cc
10 030 sys rm bin/gmisc
10 030 sys rm bindbg/gmisc
10 032 src mv trial/implement/Guiutils/barchart.help aips/implement/Guiutils/barchart.help
10 037 src rm install/ibmrs
10 047 src rm atnf/apps/pks
10 052 src rm nrao/apps/dish/dish_tracewin.g
10 052 src rm nrao/apps/dish/dish_dialogbox.g
10 058 src rm nrao/apps/dish/dishavg.g
10 060 src mv aips/implement/Measures/MVBaseline.cc aips/implement/Quanta/MVBaseline.cc
10 060 src mv aips/implement/Measures/MVBaseline.h aips/implement/Quanta/MVBaseline.h
10 060 src mv aips/implement/Measures/MVDirection.cc aips/implement/Quanta/MVDirection.cc
10 060 src mv aips/implement/Measures/MVDirection.h aips/implement/Quanta/MVDirection.h
10 060 src mv aips/implement/Measures/MVDoppler.cc aips/implement/Quanta/MVDoppler.cc
10 060 src mv aips/implement/Measures/MVDoppler.h aips/implement/Quanta/MVDoppler.h
10 060 src mv aips/implement/Measures/MVDouble.cc aips/implement/Quanta/MVDouble.cc
10 060 src mv aips/implement/Measures/MVDouble.h aips/implement/Quanta/MVDouble.h
10 060 src mv aips/implement/Measures/MVEarthMagnetic.cc aips/implement/Quanta/MVEarthMagnetic.cc
10 060 src mv aips/implement/Measures/MVEarthMagnetic.h aips/implement/Quanta/MVEarthMagnetic.h
10 060 src mv aips/implement/Measures/MVEpoch.cc aips/implement/Quanta/MVEpoch.cc
10 060 src mv aips/implement/Measures/MVEpoch.h aips/implement/Quanta/MVEpoch.h
10 060 src mv aips/implement/Measures/MVFrequency.cc aips/implement/Quanta/MVFrequency.cc
10 060 src mv aips/implement/Measures/MVFrequency.h aips/implement/Quanta/MVFrequency.h
10 060 src mv aips/implement/Measures/MVPosition.cc aips/implement/Quanta/MVPosition.cc
10 060 src mv aips/implement/Measures/MVPosition.h aips/implement/Quanta/MVPosition.h
10 060 src mv aips/implement/Measures/MVRadialVelocity.cc aips/implement/Quanta/MVRadialVelocity.cc
10 060 src mv aips/implement/Measures/MVRadialVelocity.h aips/implement/Quanta/MVRadialVelocity.h
10 060 src mv aips/implement/Measures/MVuvw.cc aips/implement/Quanta/MVuvw.cc
10 060 src mv aips/implement/Measures/MVuvw.h aips/implement/Quanta/MVuvw.h
10 061 src mv aips/implement/Measures/MeasValue.cc aips/implement/Quanta/MeasValue.cc
10 061 src mv aips/implement/Measures/MeasValue.h aips/implement/Quanta/MeasValue.h
10 062 src rm doc/newsletters/aug98/aug98news.dir
10 066 src mv trial/apps/gmisc/gmisc.g trial/implement/Utilities/gmisc.g
10 072 src rm trial/apps/gmisc/makefile
10 072 src rm trial/apps/gmisc
10 075 src rm trial/apps/sky/skyImpl.h
10 075 src rm trial/apps/sky/skyImpl.cc
10 077 src rm trial/implement/Tasking/QuantumParameterAccessor.h
10 077 src rm trial/implement/Tasking/QuantumParameterAccessor.cc
10 077 src rm trial/implement/Tasking/MeasureParameterAccessor.h
10 077 src rm trial/implement/Tasking/MeasureParameterAccessor.cc
10 087 src rm trial/apps/sky/sky.cc
10 087 src rm trial/apps/sky/sky.g
10 087 src rm trial/apps/sky/sky.help
10 087 src rm trial/apps/sky/skyFactory.h
10 087 src rm trial/apps/sky/skyFactory.cc
10 087 src rm trial/apps/sky/sky_meta.g
10 087 src rm trial/apps/sky/sky_standard.gp
10 087 src rm trial/apps/sky/templates
10 087 src rm trial/apps/simulator
10 088 src rm aips/implement/Measures/MeasureMath.h
10 089 src rm trial/implement/MeasurementEquations/CompositeSkyEquation.h
10 089 src rm trial/implement/MeasurementEquations/DOsky.h
10 089 src rm trial/implement/MeasurementEquations/DOsky.cc
10 093 src mv trial/implement/Measures/VelocityMachine.h aips/implement/Measures/VelocityMachine.h
10 093 src mv trial/implement/Measures/VelocityMachine.cc aips/implement/Measures/VelocityMachine.cc
10 093 src mv trial/implement/Measures/test/tVelocityMachine.cc aips/implement/Measures/test/tVelocityMachine.cc
10 093 src mv trial/implement/Measures/test/tVelocityMachine.out aips/implement/Measures/test/tVelocityMachine.out
10 095 src rm trial/apps/sky
10 095 src rm trial/apps/sky/makefile
10 095 src rm aips/implement/Mathematics/DComplex.h
10 098 src rm trial/implement/Tasking/objectgui.g
10 098 src rm atnf/apps/livedata/livedatafileserver.g
10 098 src rm atnf/apps/livedata/livedatagui.g
10 098 src rm atnf/apps/livedata/livedata.glishrc
10 098 sys rm libexec/livedatafileserver.g
10 098 sys rm libexec/livedatagui.g
10 098 sys rm bin/livedata.glishrc
10 100 src rm trial/implement/Coordinates/test/templates
10 100 src rm nfra/apps/j2convert/templates
10 101 src rm trial/apps/numerics/numerics_meta.g
10 101 src mv trial/apps/numerics/fftserver.help trial/implement/Mathematics/fftserver.help
10 101 src mv trial/apps/numerics/fftserver.g trial/implement/Mathematics/fftserver.g
10 101 src mv trial/apps/numerics/polyfitter.g trial/implement/Mathematics/polyfitter.g
10 101 src mv trial/apps/numerics/polyfitter.help trial/implement/Mathematics/polyfitter.help
10 101 src mv trial/apps/numerics/interpolate1d.help trial/implement/Mathematics/interpolate1d.help
10 101 src mv trial/apps/numerics/randomnumbers.help trial/implement/Mathematics/randomnumbers.help
10 101 src mv trial/apps/numerics/randomnumbers.g trial/implement/Mathematics/randomnumbers.g
10 101 src mv trial/apps/numerics/sinusoidfitter.g trial/implement/Mathematics/sinusoidfitter.g
10 101 src mv trial/apps/numerics/sinusoidfitter.help trial/implement/Mathematics/sinusoidfitter.help
10 101 src mv trial/apps/numerics/sinusoidfitter_meta.g trial/implement/Mathematics/sinusoidfitter_meta.g
10 101 src mv trial/apps/numerics/interpolate1d_meta.g trial/implement/Mathematics/interpolate1d_meta.g
10 101 src mv trial/apps/numerics/polyfitter_meta.g trial/implement/Mathematics/polyfitter_meta.g
10 101 src mv trial/apps/numerics/randomnumbers_meta.g trial/implement/Mathematics/randomnumbers_meta.g
10 101 src mv trial/apps/numerics/fftserver_meta.g trial/implement/Mathematics/fftserver_meta.g
10 102 src rm trial/apps/imager/templates
10 102 src rm trial/apps/cal
10 104 src rm nrao/apps/gbtutils/gbt.g
10 104 src rm trial/scripts/gbt.g
10 105 src rm doc/html/gettingstarted/gettingstarted.tex
10 105 src rm doc/html/gettingstarted/gsedition2.aux
10 105 src rm doc/html/gettingstarted/gsedition2.dvi
10 105 src rm doc/html/gettingstarted/gsedition2.log
10 105 src rm doc/html/gettingstarted/gsedition2.ps
10 105 src rm doc/html/gettingstarted/gsedition2.tex~
10 105 src rm doc/html/gettingstarted/gsedition2.toc
10 105 src mv doc/html/gettingstarted/gsedition2.tex doc/html/gettingstarted/gsedtion2.latex
10 105 src mv doc/html/gettingstarted/gsedtion2.latex doc/html/gettingstarted/gsedition2.latex
10 105 src rm doc/html/gettingstarted/gettingstarted.tex
11 008 src mv trial/apps/numerics/fftserver.cc trial/implement/Mathematics/fftserver.cc
11 008 src mv trial/apps/numerics/fftserver.h trial/implement/Mathematics/fftserver.h
11 008 src mv trial/apps/numerics/sinusoidfitter.h trial/implement/Mathematics/sinusoidfitter.h
11 008 src mv trial/apps/numerics/sinusoidfitter.cc trial/implement/Mathematics/sinusoidfitter.cc
11 008 src mv trial/apps/numerics/randomnumbers.cc trial/implement/Mathematics/randomnumbers.cc
11 008 src mv trial/apps/numerics/randomnumbers.h trial/implement/Mathematics/randomnumbers.h
11 008 src mv trial/apps/numerics/polyfitter.cc trial/implement/Mathematics/polyfitter.cc
11 008 src mv trial/apps/numerics/polyfitter.h trial/implement/Mathematics/polyfitter.h
11 008 src mv trial/apps/numerics/interpolate1d.h trial/implement/Mathematics/interpolate1d.h
11 008 src mv trial/apps/numerics/interpolate1d.cc trial/implement/Mathematics/interpolate1d.cc
11 008 src rm trial/apps/numerics/fftserver.help
11 008 src mv trial/implement/Mathematics/fftserver.cc trial/implement/Mathematics/DOfftserver.cc
11 008 src mv trial/implement/Mathematics/fftserver.h trial/implement/Mathematics/DOfftserver.h
11 008 src mv trial/implement/Mathematics/interpolate1d.h trial/implement/Mathematics/DOinterpolate1d.h
11 008 src mv trial/implement/Mathematics/interpolate1d.cc trial/implement/Mathematics/DOinterpolate1d.cc
11 008 src mv trial/implement/Mathematics/polyfitter.h trial/implement/Mathematics/DOpolyfitter.h
11 008 src mv trial/implement/Mathematics/polyfitter.cc trial/implement/Mathematics/DOpolyfitter.cc
11 008 src mv trial/implement/Mathematics/randomnumbers.cc trial/implement/Mathematics/DOrandomnumbers.cc
11 008 src mv trial/implement/Mathematics/randomnumbers.h trial/implement/Mathematics/DOrandomnumbers.h
11 008 src mv trial/implement/Mathematics/sinusoidfitter.h trial/implement/Mathematics/DOsinusoidfitter.h
11 008 src mv trial/implement/Mathematics/sinusoidfitter.cc trial/implement/Mathematics/DOsinusoidfitter.cc
11 012 src mv trial/apps/HDS trial/apps/hds
11 015 src rm trial/implement/Lattices/test/dPagedArrIter.cc
11 022 src mv doc/xreference doc/reference
11 026 sys rm libexec/numerics_meta.g
11 027 src mv atnf/apps/pksbandpass/pksbandpass.g atnf/apps/livedata/pksbandpass.g
11 027 src mv atnf/apps/pksmonitor/pksmonitor.g atnf/apps/livedata/pksmonitor.g
11 027 src mv atnf/apps/pksmscalstats/pksmscalstats.g atnf/apps/livedata/pksmscalstats.g
11 027 src mv atnf/apps/pksmbfits/pksmbfits.g atnf/apps/livedata/pksreader.g
11 027 src mv atnf/apps/pksmeasurementset/pksmeasurementset.g atnf/apps/livedata/pkswriter.g
11 027 sys rm libexec/pksmbfits.g
11 027 sys rm libexec/pksmeasurementset.g
11 028 src mv trial/apps/psky trial/apps/pimager
11 034 src mv trial/implement/Guiutils/progress.g aips/implement/Guiutils/progress.g
11 034 src mv trial/implement/Guiutils/progress.help aips/implement/Guiutils/progress.help
11 038 src mv drao hia
11 039 src mv trial/apps/ms/UVFitsFiller.cc trial/implement/MeasurementSet/MSFitsInput.cc
11 039 src mv trial/apps/ms/UVFitsFiller.h trial/implement/MeasurementSet/MSFitsInput.h
11 039 src mv trial/apps/ms/UVFitsWriter.h trial/implement/MeasurementSet/MSFitsOutput.h
11 039 src mv trial/apps/ms/UVFitsWriter.cc trial/implement/MeasurementSet/MSFitsOutput.cc
11 039 src mv trial/apps/ms/msImpl.cc trial/implement/MeasurementSet/DOms.cc
11 039 src mv trial/apps/ms/msImpl.h trial/implement/MeasurementSet/DOms.h
11 047 src rm aips/implement/Containers/test/tDlist.exec
11 047 src rm aips/implement/Containers/test/tList.exec
11 047 src rm aips/implement/Containers/test/tListMap.exec
11 047 src rm aips/implement/Containers/test/tListMap2.exec
11 047 src rm aips/implement/Containers/test/tOrdMap.exec
11 047 src rm aips/implement/Containers/test/tOrdMap2.exec
11 047 src rm aips/implement/Containers/test/tSimOrdMap.exec
11 048 src rm aips/implement/RTTI/test/tRegister.exec
11 051 src mv aips/implement/Arrays/test/tArrayIO2.exec aips/implement/Arrays/test/tArrayIO2.run
11 051 src rm aips/implement/Arrays/test/tArrayIO2.out_mat
11 051 src rm aips/implement/Arrays/test/tArrayIO2.out_vec
11 051 src mv aips/implement/Exceptions/test/tException.exec aips/implement/Exceptions/test/tException.run
11 051 src mv aips/implement/Exceptions/test/tExcpA.exec aips/implement/Exceptions/test/tExcpA.run
11 051 src mv aips/implement/Exceptions/test/tExcpB.exec aips/implement/Exceptions/test/tExcpB.run
11 051 src mv aips/implement/Mathematics/test/tComplex.exec aips/implement/Mathematics/test/tComplex.run
11 051 src mv aips/implement/Mathematics/test/tConvVector.exec aips/implement/Mathematics/test/tConvVector.in
11 051 src mv aips/implement/Mathematics/test/tGridTool.exec aips/implement/Mathematics/test/tGridTool.in
11 052 src rm admin/personnel/diary
11 059 src mv aips/implement/Tables/test/tTableGram.exec aips/implement/Tables/test/tTableGram.run
11 064 src mv doc/newsletters/oct98 doc/newsletters/nov98
11 071 src mv doc/html/navpages/recipes doc/recipes
11 074 src rm trial/apps/deconvolver/templates
11 074 src rm trial/implement/MeasurementEquations/DOpimager.h
11 074 src rm trial/implement/MeasurementEquations/DOpimager.cc
11 074 src rm trial/apps/pimager
11 075 src rm trial/apps/ms/templates
11 075 src mv trial/apps/image/image.g trial/implement/Images/image.g
11 075 src mv trial/apps/image/image.help trial/implement/Images/image.help
11 075 src mv trial/apps/image/image_meta.g trial/implement/Images/image_meta.g
11 075 src mv trial/apps/image/image_standard.gp trial/implement/Images/image_standard.gp
11 075 src mv doc/html/gettingstarted doc/user/gettingstarted
11 075 src rm doc/html/navpages/images/communicate10.gif
11 075 src rm doc/html/navpages/images/aipslabels5_7.gif
11 075 src rm doc/html/navpages/images/aipsnewest.gif
11 075 src rm doc/html/navpages/images/communicate10.gif
11 075 src rm doc/html/navpages/images/communicatebar.gif
11 075 src rm doc/html/navpages/images/csiro.gif
11 075 src rm doc/html/navpages/images/csiro1.gif
11 075 src rm doc/html/navpages/images/emailreflectors.gif
11 075 src rm doc/html/navpages/images/gettingstarted.gif
11 075 src rm doc/html/navpages/images/gettingstartedbaroff.gif
11 075 src rm doc/html/navpages/images/gettingstartedbaron.gif
11 076 src rm doc/html/navpages/images/aipslabels5_1.gif
11 076 src rm doc/html/navpages/images/aipsref.gif
11 076 src rm doc/html/navpages/images/aipsview.gif
11 076 src rm doc/html/navpages/images/glishusers.gif
11 076 src rm doc/html/navpages/images/glossary.gif
11 076 src rm doc/html/navpages/images/howto.gif
11 076 src rm doc/html/navpages/images/introbar.gif
11 076 src rm doc/html/navpages/images/introbaroff.gif
11 076 src rm doc/html/navpages/images/introbaron.gif
11 076 src rm doc/html/navpages/images/labels53.gif
11 076 src rm doc/html/navpages/images/learn10.gif
11 076 src rm doc/html/navpages/images/learnbar.gif
11 076 src rm doc/html/navpages/images/logmessages1.gif
11 076 src rm doc/html/navpages/images/logmessages1.ps
11 076 src rm doc/html/navpages/images/memos.gif
11 076 src rm doc/html/navpages/images/mirrorsites.gif
11 076 src rm doc/html/navpages/images/modulereference.gif
11 076 src rm doc/html/navpages/images/newsletters.gif
11 076 src rm doc/html/navpages/images/newtba.gif
11 076 src rm doc/html/navpages/images/newtba.ps
11 076 src rm doc/html/navpages/images/objectlist.gif
11 076 src rm doc/html/navpages/images/packageaips.gif
11 076 src rm doc/html/navpages/images/personnel.gif
11 076 src rm doc/html/navpages/images/pgplotter.gif
11 076 src rm doc/html/navpages/images/pgplotter.ps
11 076 src rm doc/html/navpages/images/program10.gif
11 076 src rm doc/html/navpages/images/programbar.gif
11 076 src rm doc/html/navpages/images/programmers.gif
11 076 src rm doc/html/navpages/images/quarterlyreports.gif
11 076 src rm doc/html/navpages/images/recipes.gif
11 076 src rm doc/html/navpages/images/recipesbaroff.gif
11 076 src rm doc/html/navpages/images/recipesbaron.gif
11 076 src rm doc/html/navpages/images/redhomebaroff.gif
11 076 src rm doc/html/navpages/images/redhomebaron.gif
11 076 src rm doc/html/navpages/images/redhomebaroff.gif
11 076 src rm doc/html/navpages/images/ref10.gif
11 076 src rm doc/html/navpages/images/refbar.gif
11 076 src rm doc/html/navpages/images/reportabug.gif
11 076 src rm doc/html/navpages/images/search.gif
11 076 src rm doc/html/navpages/images/sourcecode.gif
11 076 src rm doc/html/navpages/images/startedwithglish.gif
11 076 src rm doc/html/navpages/images/startglishbaroff.gif
11 076 src rm doc/html/navpages/images/startglishbaron.gif
11 076 src rm doc/html/navpages/images/starting10.gif
11 076 src rm doc/html/navpages/images/system.gif
11 076 src rm doc/html/navpages/images/tablebrowser.gif
11 076 src rm doc/html/navpages/images/tablebrowser.ps
11 076 src rm doc/html/navpages/images/trackabug.gif
11 076 src rm doc/html/navpages/images/trial.gif
11 076 src rm doc/html/navpages/images/buttons/aips56on.gif
11 076 src rm doc/html/navpages/images/buttons/aipson.gif
11 076 src rm doc/html/navpages/images/buttons/aipsviewoff.gif
11 076 src rm doc/html/navpages/images/buttons/aipsviewon.gif
11 076 src rm doc/html/navpages/images/buttons/communicate10off.gif
11 076 src rm doc/html/navpages/images/buttons/communicate10on.gif
11 076 src rm doc/html/navpages/images/buttons/emailreflectorsoff.gif
11 076 src rm doc/html/navpages/images/buttons/emailreflectorson.gif
11 076 src rm doc/html/navpages/images/buttons/gettingstartedoff.gif
11 076 src rm doc/html/navpages/images/buttons/gettingstartedon.gif
11 076 src rm doc/html/navpages/images/buttons/glishusersoff.gif
11 076 src rm doc/html/navpages/images/buttons/glishuserson.gif
11 076 src rm doc/html/navpages/images/buttons/glossaryoff.gif
11 076 src rm doc/html/navpages/images/buttons/glossaryon.gif
11 076 src rm doc/html/navpages/images/buttons/home10off.gif
11 076 src rm doc/html/navpages/images/buttons/home10on.gif
11 076 src rm doc/html/navpages/images/buttons/howtooff.gif
11 076 src rm doc/html/navpages/images/buttons/newsletterson.gif
11 076 src rm doc/html/navpages/images/buttons/packageaipsoff.gif
11 076 src rm doc/html/navpages/images/buttons/packageaipson.gif
11 076 src rm doc/html/navpages/images/buttons/personneloff.gif
11 076 src rm doc/html/navpages/images/buttons/personnelon.gif
11 076 src rm doc/html/navpages/images/buttons/program10off.gif
11 076 src rm doc/html/navpages/images/buttons/program10on.gif
11 076 src rm doc/html/navpages/images/buttons/programmersoff.gif
11 076 src rm doc/html/navpages/images/buttons/programmerson.gif
11 076 src rm doc/html/navpages/images/buttons/quarterlyreportsoff.gif
11 076 src rm doc/html/navpages/images/buttons/quarterlyreportson.gif
11 076 src rm doc/html/navpages/images/buttons/recipeson.gif
11 076 src rm doc/html/navpages/images/buttons/recipesoff.gif
11 076 src rm doc/html/navpages/images/buttons/ref10on.gif
11 076 src rm doc/html/navpages/images/buttons/ref10off.gif
11 076 src rm doc/html/navpages/images/buttons/reportabugoff.gif
11 076 src rm doc/html/navpages/images/buttons/reportabugon.gif
11 076 src rm doc/html/navpages/images/buttons/search10off.gif
11 076 src rm doc/html/navpages/images/buttons/search10on.gif
11 076 src rm doc/html/navpages/images/buttons/howtoon.gif
11 076 src rm doc/html/navpages/images/buttons/introduction.gif
11 076 src rm doc/html/navpages/images/buttons/introductionoff.gif
11 076 src rm doc/html/navpages/images/buttons/introductionon.gif
11 076 src rm doc/html/navpages/images/buttons/learn10off.gif
11 076 src rm doc/html/navpages/images/buttons/learn10on.gif
11 076 src rm doc/html/navpages/images/buttons/makefile
11 076 src rm doc/html/navpages/images/buttons/memosoff.gif
11 076 src rm doc/html/navpages/images/buttons/memoson.gif
11 076 src rm doc/html/navpages/images/buttons/mirrorsitesoff.gif
11 076 src rm doc/html/navpages/images/buttons/mirrorsiteson.gif
11 076 src rm doc/html/navpages/images/buttons/modulereferenceoff.gif
11 076 src rm doc/html/navpages/images/buttons/modulereferenceon.gif
11 076 src rm doc/html/navpages/images/buttons/newslettersoff.gif
11 076 src rm doc/html/navpages/images/buttons/search10off.gif
11 076 src rm doc/html/navpages/images/buttons/reportabugon.gif
11 076 src rm doc/html/navpages/images/buttons/reportabugoff.gif
11 076 src rm doc/html/navpages/images/buttons/ref10on.gif
11 076 src rm doc/html/navpages/images/buttons/ref10off.gif
11 076 src rm doc/html/navpages/images/buttons/recipeson.gif
11 076 src rm doc/html/navpages/images/buttons/recipesoff.gif
11 076 src rm doc/html/navpages/images/buttons/quarterlyreportson.gif
11 076 src rm doc/html/navpages/images/buttons/gettingstartedoff.gif
11 076 src rm doc/html/navpages/images/buttons/gettingstartedon.gif
11 076 src rm doc/html/navpages/images/buttons/glishusersoff.gif
11 076 src rm doc/html/navpages/images/buttons/glishuserson.gif
11 076 src rm doc/html/navpages/images/buttons/glossaryoff.gif
11 076 src rm doc/html/navpages/images/buttons/glossaryon.gif
11 076 src rm doc/html/navpages/images/buttons/home10off.gif
11 076 src rm doc/html/navpages/images/buttons/home10on.gif
11 076 src rm doc/html/navpages/images/buttons/howtooff.gif
11 076 src rm doc/html/navpages/images/buttons/howtoon.gif
11 076 src rm doc/html/navpages/images/buttons/introduction.gif
11 076 src rm doc/html/navpages/images/buttons/introductionoff.gif
11 076 src rm doc/html/navpages/images/buttons/introductionon.gif
11 076 src rm doc/html/navpages/images/buttons/learn10off.gif
11 076 src rm doc/html/navpages/images/buttons/learn10on.gif
11 076 src rm doc/html/navpages/images/buttons/makefile
11 076 src rm doc/html/navpages/images/buttons/memosoff.gif
11 076 src rm doc/html/navpages/images/buttons/memoson.gif
11 076 src rm doc/html/navpages/images/buttons/mirrorsitesoff.gif
11 076 src rm doc/html/navpages/images/buttons/mirrorsiteson.gif
11 076 src rm doc/html/navpages/images/buttons/modulereferenceoff.gif
11 076 src rm doc/html/navpages/images/buttons/modulereferenceon.gif
11 076 src rm doc/html/navpages/images/buttons/newslettersoff.gif
11 076 src rm doc/html/navpages/images/buttons/trialon.gif
11 076 src rm doc/html/navpages/images/buttons/trialoff.gif
11 076 src rm doc/html/navpages/images/buttons/trackabugon.gif
11 076 src rm doc/html/navpages/images/buttons/trackabugoff.gif
11 076 src rm doc/html/navpages/images/buttons/systemon.gif
11 076 src rm doc/html/navpages/images/buttons/systemoff.gif
11 076 src rm doc/html/navpages/images/buttons/starting10on.gif
11 076 src rm doc/html/navpages/images/buttons/starting10off.gif
11 076 src rm doc/html/navpages/images/buttons/startedwithglishon.gif
11 076 src rm doc/html/navpages/images/buttons/startedwithglishoff.gif
11 076 src rm doc/html/navpages/images/buttons/startedwithglishon.gif
11 076 src rm doc/html/navpages/images/buttons/sourcecodeon.gif
11 076 src rm doc/html/navpages/images/buttons/sourcecodeoff.gif
11 076 src rm doc/html/navpages/images/buttons/searchon.gif
11 076 src rm doc/html/navpages/images/buttons/searchoff.gif
11 076 src rm doc/html/navpages/images/buttons/search10on.gif
11 076 src rm doc/html/navpages/images/buttons/search10off.gif
11 076 src rm doc/html/navpages/images/buttons/reportabugon.gif
11 076 src rm doc/html/navpages/images/buttons/reportabugoff.gif
11 076 src rm doc/html/navpages/images/buttons/ref10on.gif
11 076 src rm doc/html/navpages/images/buttons/ref10off.gif
11 076 src rm doc/html/navpages/images/buttons/recipeson.gif
11 076 src rm doc/html/navpages/images/buttons/recipesoff.gif
11 076 src rm doc/html/navpages/images/navigation/aipsviewbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/aipsviewbaron.gif
11 076 src rm doc/html/navpages/images/navigation/bluehomebaroff.gif
11 076 src rm doc/html/navpages/images/navigation/bluehomebaron.gif
11 076 src rm doc/html/navpages/images/navigation/commoff2.gif
11 076 src rm doc/html/navpages/images/navigation/common2.gif
11 076 src rm doc/html/navpages/images/navigation/emailbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/emailbaron.gif
11 076 src rm doc/html/navpages/images/navigation/gettingstartedbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/gettingstartedbaron.gif
11 076 src rm doc/html/navpages/images/navigation/glishusersbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/glishusersbaron.gif
11 076 src rm doc/html/navpages/images/navigation/glossarybaroff.gif
11 076 src rm doc/html/navpages/images/navigation/glossarybaron.gif
11 076 src rm doc/html/navpages/images/navigation/greenhomebaroff.gif
11 076 src rm doc/html/navpages/images/navigation/greenhomebaron.gif
11 076 src rm doc/html/navpages/images/navigation/homeoff2.gif
11 076 src rm doc/html/navpages/images/navigation/homeon2.gif
11 076 src rm doc/html/navpages/images/navigation/howtobaroff.gif
11 076 src rm doc/html/navpages/images/navigation/howtobaron.gif
11 076 src rm doc/html/navpages/images/navigation/introbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/introbaron.gif
11 076 src rm doc/html/navpages/images/navigation/learnoff2.gif
11 076 src rm doc/html/navpages/images/navigation/learnon2.gif
11 076 src rm doc/html/navpages/images/navigation/memosbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/memosbaron.gif
11 076 src rm doc/html/navpages/images/navigation/mirrorbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/mirrorbaron.gif
11 076 src rm doc/html/navpages/images/navigation/modulereferencebaroff.gif
11 076 src rm doc/html/navpages/images/navigation/modulereferencebaron.gif
11 076 src rm doc/html/navpages/images/navigation/newslettersbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/newslettersbaron.gif
11 076 src rm doc/html/navpages/images/navigation/orangehomebaroff.gif
11 076 src rm doc/html/navpages/images/navigation/orangehomebaron.gif
11 076 src rm doc/html/navpages/images/navigation/packageaipsbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/packageaipsbaron.gif
11 076 src rm doc/html/navpages/images/navigation/personnelbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/personnelbaron.gif
11 076 src rm doc/html/navpages/images/navigation/programmersbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/programmersbaron.gif
11 076 src rm doc/html/navpages/images/navigation/programoff2.gif
11 076 src rm doc/html/navpages/images/navigation/programon2.gif
11 076 src rm doc/html/navpages/images/navigation/purplehomebaroff.gif
11 076 src rm doc/html/navpages/images/navigation/purplehomebaron.gif
11 076 src rm doc/html/navpages/images/navigation/quarterlyreportsbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/quarterlyreportsbaron.gif
11 076 src rm doc/html/navpages/images/navigation/recipesbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/recipesbaron.gif
11 076 src rm doc/html/navpages/images/navigation/refoff2.gif
11 076 src rm doc/html/navpages/images/navigation/refon2.gif
11 076 src rm doc/html/navpages/images/navigation/reportabugbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/reportabugbaron.gif
11 076 src rm doc/html/navpages/images/navigation/searchoff2.gif
11 076 src rm doc/html/navpages/images/navigation/searchon2.gif
11 076 src rm doc/html/navpages/images/navigation/sourcecodebaroff.gif
11 076 src rm doc/html/navpages/images/navigation/sourcecodebaron.gif
11 076 src rm doc/html/navpages/images/navigation/startglishbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/startglishbaron.gif
11 076 src rm doc/html/navpages/images/navigation/startoff2.gif
11 076 src rm doc/html/navpages/images/navigation/starton2.gif
11 076 src rm doc/html/navpages/images/navigation/systemmanualbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/systemmanualbaron.gif
11 076 src rm doc/html/navpages/images/navigation/trackabugbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/trackabugbaron.gif
11 076 src rm doc/html/navpages/images/navigation/trialbaroff.gif
11 076 src rm doc/html/navpages/images/navigation/trialbaron.gif
11 076 src rm doc/html/navpages/images/navigation
11 076 src rm doc/html/navpages/images/buttons
11 076 src rm doc/html/navpages/images2/aipart.gif
11 076 src rm doc/html/navpages/images2/aipart1.gif
11 076 src rm doc/html/navpages/images2/aipart2.gif
11 076 src rm doc/html/navpages/images2/aipart3.gif
11 076 src rm doc/html/navpages/images2/aipart4.gif
11 076 src rm doc/html/navpages/images2/aipslogo.gif
11 076 src rm doc/html/navpages/images2/aipslogo03.gif
11 076 src rm doc/html/navpages/images2/aipslogo4.gif
11 076 src rm doc/html/navpages/images2/backdrop.gif
11 076 src rm doc/html/navpages/images2/backdrop02.gif
11 076 src rm doc/html/navpages/images2/comm.gif
11 076 src rm doc/html/navpages/images2/aipslogo03.gif
11 076 src rm doc/html/navpages/images2/comm02.gif
11 076 src rm doc/html/navpages/images2/email.gif
11 076 src rm doc/html/navpages/images2/get.gif
11 076 src rm doc/html/navpages/images2/getting.gif
11 076 src rm doc/html/navpages/images2/glish.gif
11 076 src rm doc/html/navpages/images2/glossary.gif
11 076 src rm doc/html/navpages/images2/glossry.gif
11 076 src rm doc/html/navpages/images2/home02.gif
11 076 src rm doc/html/navpages/images2/howto.gif
11 076 src rm doc/html/navpages/images2/intro.gif
11 076 src rm doc/html/navpages/images2/introbig.gif
11 076 src rm doc/html/navpages/images2/learn.gif
11 076 src rm doc/html/navpages/images2/learn02.gif
11 076 src rm doc/html/navpages/images2/learn03.gif
11 076 src rm doc/html/navpages/images2/learn04.gif
11 076 src rm doc/html/navpages/images2/learnmore.gif
11 076 src rm doc/html/navpages/images2/memos.gif
11 076 src rm doc/html/navpages/images2/mirror.gif
11 076 src rm doc/html/navpages/images2/module.gif
11 076 src rm doc/html/navpages/images2/newaips03.gif
11 076 src rm doc/html/navpages/images2/newaips03a.gif
11 076 src rm doc/html/navpages/images2/newaips2.gif
11 076 src rm doc/html/navpages/images2/newletters.gif
11 076 src rm doc/html/navpages/images2/newsletters.gif
11 076 src rm doc/html/navpages/images2/nrao.gif
11 076 src rm doc/html/navpages/images2/nrao01.gif
11 076 src rm doc/html/navpages/images2/nrao02.gif
11 076 src rm doc/html/navpages/images2/package.gif
11 076 src rm doc/html/navpages/images2/personnel.gif
11 076 src rm doc/html/navpages/images2/program.gif
11 076 src rm doc/html/navpages/images2/program02.gif
11 076 src rm doc/html/navpages/images2/programmer.gif
11 076 src rm doc/html/navpages/images2/quarter.gif
11 076 src rm doc/html/navpages/images2/rbug.gif
11 076 src rm doc/html/navpages/images2/recipes.gif
11 076 src rm doc/html/navpages/images2/recipesbig.gif
11 076 src rm doc/html/navpages/images2/ref.gif
11 076 src rm doc/html/navpages/images2/ref02.gif
11 076 src rm doc/html/navpages/images2/search.gif
11 076 src rm doc/html/navpages/images2/source.gif
11 076 src rm doc/html/navpages/images2/start.gif
11 076 src rm doc/html/navpages/images2/starting.gif
11 076 src rm doc/html/navpages/images2/starting1.gif
11 076 src rm doc/html/navpages/images2/starting2.gif
11 076 src rm doc/html/navpages/images2/startingbig.gif
11 076 src rm doc/html/navpages/images2/system1.gif
11 076 src rm doc/html/navpages/images2/tbug.gif
11 076 src rm doc/html/navpages/images2/tri.gif
11 076 src rm doc/html/navpages/images2/tri2.gif
11 076 src rm doc/html/navpages/images2/view.gif
11 076 src rm doc/html/navpages/images2/
11 076 src rm doc/html/navpages/images3/aipsnav6.gif
11 076 src rm doc/html/navpages/images3/aipsnav6b.gif
11 076 src rm doc/html/navpages/easy/problems.html
11 076 src rm doc/html/navpages/easy/starting.html
11 076 src rm doc/html/navpages/easy/tools.html
11 076 src rm doc/html/navpages/easy/toolsa.html
11 076 src rm doc/html/navpages/easy/
11 076 src rm doc/html/navpages/newsletter/personnel.html
11 076 src rm doc/html/navpages/newsletter/projects.html
11 076 src rm doc/html/navpages/newsletter/stories.html
11 076 src rm doc/html/navpages/newsletter/
11 076 src rm doc/html/navpages/programmer/HowTo/code.html
11 076 src rm doc/html/navpages/programmer/HowTo/contents.html
11 076 src rm doc/html/navpages/programmer/HowTo/footnode.html
11 076 src rm doc/html/navpages/programmer/HowTo/general.html
11 076 src rm doc/html/navpages/programmer/HowTo/glish.html
11 076 src rm doc/html/navpages/programmer/HowTo/gnotes.html
11 076 src rm doc/html/navpages/programmer/HowTo/help.html
11 076 src rm doc/html/navpages/programmer/HowTo/howtos.html
11 076 src rm doc/html/navpages/programmer/HowTo/images.pl
11 076 src rm doc/html/navpages/programmer/HowTo/index.html
11 076 src rm doc/html/navpages/programmer/HowTo/internals.pl
11 076 src rm doc/html/navpages/programmer/HowTo/labels.pl
11 076 src rm doc/html/navpages/programmer/HowTo/look.html
11 076 src rm doc/html/navpages/programmer/HowTo/node1.html
11 076 src rm doc/html/navpages/programmer/HowTo/node2.html
11 076 src rm doc/html/navpages/programmer/HowTo/node3.html
11 076 src rm doc/html/navpages/programmer/HowTo/node4.html
11 076 src rm doc/html/navpages/programmer/HowTo/node5.html
11 076 src rm doc/html/navpages/programmer/HowTo/node6.html
11 076 src rm doc/html/navpages/programmer/HowTo/node7.html
11 076 src rm doc/html/navpages/programmer/HowTo/node8.html
11 076 src rm doc/html/navpages/programmer/HowTo/node9.html
11 076 src rm doc/html/navpages/programmer/HowTo/notes.html
11 076 src rm doc/html/navpages/programmer/HowTo/start.html
11 076 src rm doc/html/navpages/programmer/HowTo/writing.html
11 076 src rm doc/html/navpages/programmer/HowTo/
11 085 src rm /doc/html/navpages/images/aips10.gif
11 085 src rm doc/html/navpages/images/aipslogo2.gif
11 085 src rm doc/html/navpages/images/atnf.gif
11 085 src rm doc/html/navpages/images/bima3.gif
11 085 src rm doc/html/navpages/images/nfra.gif
11 085 src rm doc/html/navpages/images/aips10.gif
11 085 src rm doc/html/navpages/images/aipslogo1.gif
11 085 src rm doc/html/navpages/images/aipslogo2.gif
11 085 src rm doc/html/navpages/images/atnf.gif
11 085 src rm doc/html/navpages/images/backdrop02.gif
11 085 src rm doc/html/navpages/images/bima.gif
11 085 src rm doc/html/navpages/images/bima3.gif
11 085 src rm doc/html/navpages/images/nfra.gif
11 085 src rm doc/html/navpages/images/nfra70.gif
11 085 src rm doc/html/navpages/images/nrao.gif
11 085 src rm doc/html/navpages/images/nrao54.gif
11 085 src rm doc/html/navpages/programmer/programmer.html
11 085 src rm doc/html/navpages/firstpage.html
11 085 src rm nrao/apps/otfgridder/GLSProjector.h
11 085 src rm nrao/apps/otfgridder/OTFInputs.cc
11 085 src rm nrao/apps/otfgridder/OTFInputs.h
11 085 src rm nrao/apps/otfgridder/PosSwitchedColumns.cc
11 085 src rm nrao/apps/otfgridder/PosSwitchedColumns.h
11 085 src rm nrao/apps/otfgridder/PosSwitchedCorrector.h
11 085 src rm nrao/apps/otfgridder/PosSwitchedCorrector.cc
11 085 src rm nrao/apps/otfgridder/otfgridder.cc
11 085 src rm nrao/apps/otfgridder/templates
11 085 src rm nrao/apps/otfgridder/makefile
11 085 sys rm bin/otfgridder
11 085 src rm nrao/apps/gOTF/gOTF.ad
11 085 src rm nrao/apps/gOTF/gOTF.cc
11 085 src rm nrao/apps/gOTF/tgOTF.g
11 085 src rm nrao/apps/gOTF/makefile
11 085 sys rm bin/gOTF
11 085 sys rm libexec/tgOTF.g
11 085 src rm nrao/apps/sddfiller/gsdd-helper.g
11 085 src rm nrao/apps/sddfiller/makefile
11 085 src rm nrao/apps/sddfiller/sddfiller.cc
11 085 src rm nrao/apps/sddfiller/sddfiller.notes
11 085 sys rm bin/sddfiller
11 085 sys rm libexec/gsdd-helper.g
11 085 src rm nrao/implement/MeasurementSets/OldMeasurementSet.h
11 085 src rm nrao/implement/MeasurementSets/OldMeasurementSet.cc
11 085 src rm nrao/implement/MeasurementSets/test/tOldMeasurementSet.cc
11 085 src rm nrao/implement/MeasurementSets/test/templates
11 086 src rm nrao/implement/SDD/SDD12mStMan.h
11 086 src rm nrao/implement/SDD/SDD12mStMan.cc
11 086 src rm nrao/implement/SDD/SDDStMan.h
11 086 src rm nrao/implement/SDD/SDDStMan.cc
11 086 src mv trial/implement/Tasking/Index.h aips/implement/Tasking/Index.h
11 086 src mv trial/implement/Tasking/Index.cc aips/implement/Tasking/Index.cc
11 086 src mv trial/implement/Tasking/test/tIndex.cc aips/implement/Tasking/test/tIndex.cc
11 086 src rm doc/html/navpages/learnmore/learnmore.html
11 086 src rm doc/html/navpages/aips2search.html
11 086 src rm doc/html/navpages/betasearch.html
11 086 src rm doc/html/navpages/comm.html
11 086 src rm doc/html/navpages/commonproblems.html
11 086 src rm doc/html/navpages/gettingstarted1.html
11 086 src rm doc/html/navpages/startaips.html
11 086 src rm doc/html/navpages/terminology.html
11 086 src rm doc/html/navpages/feedback.html
11 086 src rm doc/html/navpages/firstpagetest.html
11 086 src rm doc/html/navpages/frontpage01.html
11 086 src rm doc/html/navpages/frontpage02.html
11 086 src rm doc/html/navpages/email.html
11 086 src rm doc/html/navpages/inprep.html
11 086 src rm doc/html/navpages/intro.html
11 086 src rm doc/html/navpages/intronavbar.html
11 086 src rm doc/html/navpages/mirror.html
11 086 src rm doc/html/navpages/navb.html
11 086 src rm doc/html/navpages/navigationbar6.html
11 086 src rm doc/html/navpages/reportabug.html
11 086 src rm doc/html/navpages/startingaips2.html
11 086 src rm doc/html/navpages/testpage1.html
11 086 src rm doc/html/navpages/testpageb.html
11 086 src rm doc/html/navpages/trackabug.html
11 086 src rm doc/html/navpages/tutor.html
11 086 src rm doc/html/navpages/communicate/comm.html
11 086 src rm doc/html/navpages/communicate/commnavbar.html
11 086 src rm doc/html/navpages/ref/refnavbar.html
11 086 src rm doc/html/navpages/programmer/programmersnavbar.html
11 088 src rm trial/apps/dog
11 088 sys rm libexec/dog.g
11 088 src rm doc/html/navpages/learnmore/banner01.gif
11 088 src rm doc/html/navpages/learnmore/banner01a.gif
11 088 src rm doc/html/navpages/learnmore/aipstop3.gif
11 088 src rm doc/html/navpages/learnmore/learnmorenavbar.html
11 088 src rm doc/html/navpages/learnmore/themast.gif
11 088 src rm doc/html/navpages/learnmore/quarterlyreport.html
11 088 src rm doc/html/navpages/ref/aipsview/advanced.html
11 088 src rm doc/html/navpages/ref/aipsview/aipsview.html
11 088 src rm doc/html/navpages/ref/aipsview/animation.html
11 088 src rm doc/html/navpages/ref/aipsview/appendices.html
11 088 src rm doc/html/navpages/ref/aipsview/avLogo.gif
11 088 src rm doc/html/navpages/ref/aipsview/colormap.html
11 088 src rm doc/html/navpages/ref/aipsview/configuration.html
11 088 src rm doc/html/navpages/ref/aipsview/contents.html
11 088 src rm doc/html/navpages/ref/aipsview/custom.html
11 088 src rm doc/html/navpages/ref/aipsview/description.html
11 088 src rm doc/html/navpages/ref/aipsview/display.html
11 088 src rm doc/html/navpages/ref/aipsview/figures.html
11 088 src rm doc/html/navpages/ref/aipsview/function.html
11 088 src rm doc/html/navpages/ref/aipsview/glish.html
11 088 src rm doc/html/navpages/ref/aipsview/img1.gif
11 088 src rm doc/html/navpages/ref/aipsview/img10.gif
11 088 src rm doc/html/navpages/ref/aipsview/img11.gif
11 088 src rm doc/html/navpages/ref/aipsview/img12.gif
11 088 src rm doc/html/navpages/ref/aipsview/img13.gif
11 088 src rm doc/html/navpages/ref/aipsview/img14.gif
11 088 src rm doc/html/navpages/ref/aipsview/img15.gif
11 088 src rm doc/html/navpages/ref/aipsview/img16.gif
11 088 src rm doc/html/navpages/ref/aipsview/img17.gif
11 088 src rm doc/html/navpages/ref/aipsview/img18.gif
11 088 src rm doc/html/navpages/ref/aipsview/img19.gif
11 088 src rm doc/html/navpages/ref/aipsview/img2.gif
11 088 src rm doc/html/navpages/ref/aipsview/img20.gif
11 088 src rm doc/html/navpages/ref/aipsview/img21.gif
11 088 src rm doc/html/navpages/ref/aipsview/img22.gif
11 088 src rm doc/html/navpages/ref/aipsview/img23.gif
11 088 src rm doc/html/navpages/ref/aipsview/img24.gif
11 088 src rm doc/html/navpages/ref/aipsview/img25.gif
11 088 src rm doc/html/navpages/ref/aipsview/img26.gif
11 088 src rm doc/html/navpages/ref/aipsview/img27.gif
11 088 src rm doc/html/navpages/ref/aipsview/img28.gif
11 088 src rm doc/html/navpages/ref/aipsview/img29.gif
11 088 src rm doc/html/navpages/ref/aipsview/img3.gif
11 088 src rm doc/html/navpages/ref/aipsview/img30.gif
11 088 src rm doc/html/navpages/ref/aipsview/img31.gif
11 088 src rm doc/html/navpages/ref/aipsview/img4.gif
11 088 src rm doc/html/navpages/ref/aipsview/img5.gif
11 088 src rm doc/html/navpages/ref/aipsview/img6.gif
11 088 src rm doc/html/navpages/ref/aipsview/img7.gif
11 088 src rm doc/html/navpages/ref/aipsview/img8.gif
11 088 src rm doc/html/navpages/ref/aipsview/img9.gif
11 088 src rm doc/html/navpages/ref/aipsview/index.html
11 088 src rm doc/html/navpages/ref/aipsview/infoarea.html
11 088 src rm doc/html/navpages/ref/aipsview/interface.html
11 088 src rm doc/html/navpages/ref/aipsview/intro.html
11 088 src rm doc/html/navpages/ref/aipsview/memory.html
11 088 src rm doc/html/navpages/ref/aipsview/node1.html
11 088 src rm doc/html/navpages/ref/aipsview/node2.html
11 088 src rm doc/html/navpages/ref/aipsview/node3.html
11 088 src rm doc/html/navpages/ref/aipsview/node4.html
11 088 src rm doc/html/navpages/ref/aipsview/node5.html
11 088 src rm doc/html/navpages/ref/aipsview/node6.html
11 088 src rm doc/html/navpages/ref/aipsview/node7.html
11 088 src rm doc/html/navpages/ref/aipsview/node8.html
11 088 src rm doc/html/navpages/ref/aipsview/node9.html
11 088 src rm doc/html/navpages/ref/aipsview/node10.html
11 088 src rm doc/html/navpages/ref/aipsview/node11.html
11 088 src rm doc/html/navpages/ref/aipsview/node12.html
11 088 src rm doc/html/navpages/ref/aipsview/node13.html
11 088 src rm doc/html/navpages/ref/aipsview/node14.html
11 088 src rm doc/html/navpages/ref/aipsview/node15.html
11 088 src rm doc/html/navpages/ref/aipsview/node16.html
11 088 src rm doc/html/navpages/ref/aipsview/node17.html
11 088 src rm doc/html/navpages/ref/aipsview/node18.html
11 088 src rm doc/html/navpages/ref/aipsview/node19.html
11 088 src rm doc/html/navpages/ref/aipsview/node20.html
11 088 src rm doc/html/navpages/ref/aipsview/node21.html
11 088 src rm doc/html/navpages/ref/aipsview/node22.html
11 088 src rm doc/html/navpages/ref/aipsview/node23.html
11 088 src rm doc/html/navpages/ref/aipsview/overlay.html
11 088 src rm doc/html/navpages/ref/aipsview/panel.html
11 088 src rm doc/html/navpages/ref/aipsview/starting.html
11 088 src rm doc/html/navpages/ref/aipsview/synch.html
11 088 src rm doc/html/navpages/ref/aipsview/using.html
11 088 src rm doc/html/navpages/ref/aipsview/window.html
11 088 src rm doc/html/navpages/ref/glossary/b.html
11 088 src rm doc/html/navpages/ref/glossary/a.html
11 088 src rm doc/html/navpages/ref/glossary/alpha.gif
11 088 src rm doc/html/navpages/ref/glossary/ant_ifg.gif
11 088 src rm doc/html/navpages/ref/glossary/aperture.gif
11 088 src rm doc/html/navpages/ref/glossary/approx.gif
11 088 src rm doc/html/navpages/ref/glossary/azimbase.gif
11 088 src rm doc/html/navpages/ref/glossary/b.html
11 088 src rm doc/html/navpages/ref/glossary/bbandimg.gif
11 088 src rm doc/html/navpages/ref/glossary/beta.gif
11 088 src rm doc/html/navpages/ref/glossary/beta2.gif
11 088 src rm doc/html/navpages/ref/glossary/c.html
11 088 src rm doc/html/navpages/ref/glossary/capdelta.gif
11 088 src rm doc/html/navpages/ref/glossary/ceqpim2.gif
11 088 src rm doc/html/navpages/ref/glossary/chat.gif
11 088 src rm doc/html/navpages/ref/glossary/chi.gif
11 088 src rm doc/html/navpages/ref/glossary/chisq.gif
11 088 src rm doc/html/navpages/ref/glossary/closamp.gif
11 088 src rm doc/html/navpages/ref/glossary/closphas.gif
11 088 src rm doc/html/navpages/ref/glossary/conratio.gif
11 088 src rm doc/html/navpages/ref/glossary/conveqns.gif
11 088 src rm doc/html/navpages/ref/glossary/convsumm.gif
11 088 src rm doc/html/navpages/ref/glossary/convthrm.gif
11 088 src rm doc/html/navpages/ref/glossary/cplanen.gif
11 088 src rm doc/html/navpages/ref/glossary/croscorr.gif
11 088 src rm doc/html/navpages/ref/glossary/d.html
11 088 src rm doc/html/navpages/ref/glossary/defexpty.gif
11 088 src rm doc/html/navpages/ref/glossary/delta.gif
11 088 src rm doc/html/navpages/ref/glossary/dirft.gif
11 088 src rm doc/html/navpages/ref/glossary/discsamp.gif
11 088 src rm doc/html/navpages/ref/glossary/disft.gif
11 088 src rm doc/html/navpages/ref/glossary/e.html
11 088 src rm doc/html/navpages/ref/glossary/entropy.gif
11 088 src rm doc/html/navpages/ref/glossary/entropyc.gif
11 088 src rm doc/html/navpages/ref/glossary/entropyd.gif
11 088 src rm doc/html/navpages/ref/glossary/epsilon.gif
11 088 src rm doc/html/navpages/ref/glossary/errort.gif
11 088 src rm doc/html/navpages/ref/glossary/eta.gif
11 088 src rm doc/html/navpages/ref/glossary/e.html
11 088 src rm doc/html/navpages/ref/glossary/euclnorm.gif
11 088 src rm doc/html/navpages/ref/glossary/exists.gif
11 088 src rm doc/html/navpages/ref/glossary/f.html
11 088 src rm doc/html/navpages/ref/glossary/fcoeffnt.gif
11 088 src rm doc/html/navpages/ref/glossary/fhat.gif
11 088 src rm doc/html/navpages/ref/glossary/fintnorm.gif
11 088 src rm doc/html/navpages/ref/glossary/fseries.gif
11 088 src rm doc/html/navpages/ref/glossary/fsumnorm.gif
11 088 src rm doc/html/navpages/ref/glossary/ft_t_2_x.gif
11 088 src rm doc/html/navpages/ref/glossary/ftilde.gif
11 088 src rm doc/html/navpages/ref/glossary/g.html
11 088 src rm doc/html/navpages/ref/glossary/gain_kt.gif
11 088 src rm doc/html/navpages/ref/glossary/gain_tf.gif
11 088 src rm doc/html/navpages/ref/glossary/gaineq.gif
11 088 src rm doc/html/navpages/ref/glossary/gaineq.gif
11 088 src rm doc/html/navpages/ref/glossary/gaineqt.gif
11 088 src rm doc/html/navpages/ref/glossary/gamma.gif
11 088 src rm doc/html/navpages/ref/glossary/gaussinc.gif
11 088 src rm doc/html/navpages/ref/glossary/geq.gif
11 088 src rm doc/html/navpages/ref/glossary/globalfr.gif
11 088 src rm doc/html/navpages/ref/glossary/glossary.html
11 088 src rm doc/html/navpages/ref/glossary/glossind.html
11 088 src rm doc/html/navpages/ref/glossary/gresgen.gif
11 088 src rm doc/html/navpages/ref/glossary/gresphas.gif
11 088 src rm doc/html/navpages/ref/glossary/gresslow.gif
11 088 src rm doc/html/navpages/ref/glossary/h.html
11 088 src rm doc/html/navpages/ref/glossary/hanningw.gif
11 088 src rm doc/html/navpages/ref/glossary/i.html
11 088 src rm doc/html/navpages/ref/glossary/ident.gif
11 088 src rm doc/html/navpages/ref/glossary/imagerec.gif
11 088 src rm doc/html/navpages/ref/glossary/invdisft.gif
11 088 src rm doc/html/navpages/ref/glossary/j.html
11 088 src rm doc/html/navpages/ref/glossary/jansky.gif
11 088 src rm doc/html/navpages/ref/glossary/k.html
11 088 src rm doc/html/navpages/ref/glossary/l.html
11 088 src rm doc/html/navpages/ref/glossary/l_2the_p.gif
11 088 src rm doc/html/navpages/ref/glossary/lambda.gif
11 088 src rm doc/html/navpages/ref/glossary/leq.gif
11 088 src rm doc/html/navpages/ref/glossary/m.html
11 088 src rm doc/html/navpages/ref/glossary/mdelta_u.gif
11 088 src rm doc/html/navpages/ref/glossary/mdeltau.gif
11 088 src rm doc/html/navpages/ref/glossary/memsum.gif
11 088 src rm doc/html/navpages/ref/glossary/n.html
11 088 src rm doc/html/navpages/ref/glossary/nseries.gif
11 088 src rm doc/html/navpages/ref/glossary/nu.gif
11 088 src rm doc/html/navpages/ref/glossary/nu1ton.gif
11 088 src rm doc/html/navpages/ref/glossary/o.html
11 088 src rm doc/html/navpages/ref/glossary/obsvbyv.gif
11 088 src rm doc/html/navpages/ref/glossary/p.html
11 088 src rm doc/html/navpages/ref/glossary/parrangl.gif
11 088 src rm doc/html/navpages/ref/glossary/phi.gif
11 088 src rm doc/html/navpages/ref/glossary/pi.gif
11 088 src rm doc/html/navpages/ref/glossary/prolsphd.gif
11 088 src rm doc/html/navpages/ref/glossary/pseudocm.gif
11 088 src rm doc/html/navpages/ref/glossary/psi.gif
11 088 src rm doc/html/navpages/ref/glossary/psi_alpn.gif
11 088 src rm doc/html/navpages/ref/glossary/psik.gif
11 088 src rm doc/html/navpages/ref/glossary/psiktf.gif
11 088 src rm doc/html/navpages/ref/glossary/q.html
11 088 src rm doc/html/navpages/ref/glossary/r.html
11 088 src rm doc/html/navpages/ref/glossary/regminim.gif
11 088 src rm doc/html/navpages/ref/glossary/regresid.gif
11 088 src rm doc/html/navpages/ref/glossary/resdela.gif
11 088 src rm doc/html/navpages/ref/glossary/resdelay.gif
11 088 src rm doc/html/navpages/ref/glossary/rho_ij.gif
11 088 src rm doc/html/navpages/ref/glossary/s.html
11 088 src rm doc/html/navpages/ref/glossary/sautoc.gif
11 088 src rm doc/html/navpages/ref/glossary/scgaineq.gif
11 088 src rm doc/html/navpages/ref/glossary/shannons.gif
11 088 src rm doc/html/navpages/ref/glossary/sigma.gif
11 088 src rm doc/html/navpages/ref/glossary/sigmavs.gif
11 088 src rm doc/html/navpages/ref/glossary/spherfnd.gif
11 088 src rm doc/html/navpages/ref/glossary/spherfni.gif
11 088 src rm doc/html/navpages/ref/glossary/sphfconc.gif
11 088 src rm doc/html/navpages/ref/glossary/sphfnzer.gif
11 088 src rm doc/html/navpages/ref/glossary/sqrt.gif
11 088 src rm doc/html/navpages/ref/glossary/stokes22.gif
11 088 src rm doc/html/navpages/ref/glossary/stokesxy.gif
11 088 src rm doc/html/navpages/ref/glossary/stokiquv.gif
11 088 src rm doc/html/navpages/ref/glossary/t.html
11 088 src rm doc/html/navpages/ref/glossary/tau.gif
11 088 src rm doc/html/navpages/ref/glossary/tau_ij.gif
11 088 src rm doc/html/navpages/ref/glossary/tauk.gif
11 088 src rm doc/html/navpages/ref/glossary/tcrossc.gif
11 088 src rm doc/html/navpages/ref/glossary/theta.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny-1.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_0.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_1.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_2.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_3.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_3.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_e.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_g.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_i.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_j.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_k.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_n.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_un.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_x.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_y.gif
11 088 src rm doc/html/navpages/ref/glossary/tiny_z.gif
11 088 src rm doc/html/navpages/ref/glossary/twopi.gif
11 088 src rm doc/html/navpages/ref/glossary/u.html
11 088 src rm doc/html/navpages/ref/glossary/ugamma.gif
11 088 src rm doc/html/navpages/ref/glossary/uvcover.gif
11 088 src rm doc/html/navpages/ref/glossary/uvmeas.gif
11 088 src rm doc/html/navpages/ref/glossary/uvsample.gif
11 088 src rm doc/html/navpages/ref/glossary/uvwcoord.gif
11 088 src rm doc/html/navpages/ref/glossary/v.html
11 088 src rm doc/html/navpages/ref/glossary/v_ij.gif
11 088 src rm doc/html/navpages/ref/glossary/v_ijtild.gif
11 088 src rm doc/html/navpages/ref/glossary/vanvleck.gif
11 088 src rm doc/html/navpages/ref/glossary/visgains.gif
11 088 src rm doc/html/navpages/ref/glossary/visibset.gif
11 088 src rm doc/html/navpages/ref/glossary/visymm.gif
