#!/bin/sh
#-----------------------------------------------------------------------------
# rai: Remotely check in AIPS++ sources
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1996,1999,2000,2001
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: rai [ai options]
#-----------------------------------------------------------------------------
# rai is an ssh-based front-end to 'ai'.  It allows remote checkin of AIPS++
# sources by invoking 'ai' on the AIPS++ master machine.  This contrasts to
# the local method where 'ai' is invoked on a machine on which the
# AIPS++ master directory is NFS mounted.
#
# In order to use rao an AIPS++ programmer must have an account on the AIPS++
# master host (aips2.nrao.edu) and it must be set up for 'ssh' access from the
# host on which rao is run.  The programmer must also have an up-to-date
# AIPS++ workspace on the master host rooted at $HOME/aips++.
#
# The files checked in are transferred to the master as a tar file.
#
# Options:
#    Refer to the options for 'ai'.
#
# Status returns:
#    0:  success (returned from ai_master)
#    1:  initialization error, no check out
#    2:  checkout failure
#
# Notes:
#    1) Where the remote account name differs from the local account name an
#       environment variable may be used to translate between them:
#
#          AUID="<remotename>"
#
#    2) If you specify a key in your .ssh/authorized_keys files you will not
#       be prompted for a password
#
#    3) If the -au switch is used, see rau for limitations
#
# Original: 1996/08/06 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Check number of arguments.
  if [ $# = 0 ]
  then
     echo "Usage: rai (arguments for ai)"
     exit 1
  fi

# Get the work directory.
  PGMRDIR=`pwd | sed -e 's#.*/code/#code/#' -e 's#.*/code$#code#'`
# Make sure we've got something sensible.
  case "$PGMRDIR" in
  /*)
     echo "rai: Invalid work directory - `pwd`"
     exit 1
     ;;
  esac
  PGMRDIR=aips++/$PGMRDIR

# Get file names.
  REMOTETAR=a.tmp.tar
  LOCALTAR=b.tmp.tar
  ARGS=
  AU=
  OPER="chmod a-w"
  SAVE_RESULTS=
  FILES=
  DIRS=
  for i
  do
     case $i in
     -au)
        AU=1
        ;;
     *)
        ARGS="$ARGS $i"
        ;;
     esac

     case $i in
     -l)
        OPER="rm -f"
        SAVE_RESULTS="tar cf $REMOTETAR"
        continue
        ;;
     -u)
        OPER="rm -f"
        SAVE_RESULTS="tar cf $REMOTETAR"
        continue
        ;;
     -*)
        continue
        ;;
     esac
 
#    Allow wildcard checkout via an RCS symbolic link.
     i=`echo $i | sed -e 's#^RCS/##' -e 's#,v$##'`
 
     case $i in
        */*)
           continue
           ;;
 
        *)
           if [ -f "$i" ]
           then
              FILES="$FILES $i"
           elif [ -d "$i" ]
           then
              DIRS="$DIRS $i"
           fi
           ;;
     esac
  done

# Transmit files to the master host.
  REMOTE_USER=""
  if [ "$AUID" ] ; then
     REMOTE_USER="-l $AUID"
  fi
  ARSH="ssh aips2.nrao.edu $REMOTE_USER"

# Entire command is now collected and handled
# as one ssh to avoid loosing stdin.
  COMMAND=
  if [ "$FILES" != "" ]
  then
     rm -f $LOCALTAR && tar cf $LOCALTAR $FILES
     scp -qpC $LOCALTAR $AUID@aips2.nrao.edu:$PGMRDIR/$REMOTETAR
     rm -f $LOCALTAR
     if [ "$COMMAND" ]
     then
        COMMAND="$COMMAND &&"
     else
        COMMAND="cd $PGMRDIR &&"
     fi
     COMMAND="$COMMAND tar pvxf $REMOTETAR > /dev/null && rm -f $REMOTETAR"
  fi

# Transmit directories to the master host.
  if [ "$DIRS" != "" ]
  then
     if [ "$COMMAND" ]
     then
        COMMAND="$COMMAND &&"
     else
        COMMAND="cd $PGMRDIR &&"
     fi
     COMMAND="$COMMAND mkdir $DIRS"
  fi

# Invoke 'ai' on the master host.
  if [ "$COMMAND" ]
  then
     COMMAND="$COMMAND &&"
  else
     COMMAND="cd $PGMRDIR &&"
  fi
  COMMAND="$COMMAND ai -I $ARGS"
  if [ "$SAVE_RESULTS" ]
  then
     COMMAND="$COMMAND && $SAVE_RESULTS $FILES"
  fi
  COMMAND="$COMMAND && rm -f $FILES"
  $ARSH /aips++/weekly/.rshexec sh -c \'\""$COMMAND"\"\' && [ "X$FILES" != "X" ] && $OPER $FILES

# Retrieve results if they were saved
  if [ "$SAVE_RESULTS" ]
  then
     scp -qpC $AUID@aips2.nrao.edu:$PGMRDIR/$REMOTETAR $LOCALTAR && tar pvxf $LOCALTAR > /dev/null
     $ARSH /aips++/weekly/.rshexec sh -c \'\""cd $PGMRDIR && rm -f $REMOTETAR"\"\'
     rm -f $LOCALTAR
  fi

# Update the local installation?
  [ "$AU" ] && rau $FILES $DIRS

  exit 0
