#!/usr/local/bin/tcsh
#-----------------------------------------------------------------------------
# UPsed script
#-----------------------------------------------------------------------------
# Copyright (C) 2000
# Associated Universities, Inc. Washington DC, USA.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 675 Massachusetts Ave, Cambridge, MA 02139, USA.
#
# Correspondence concerning AIPS++ should be addressed as follows:
#        Internet email: aips2-request@nrao.edu.
#        Postal address: AIPS++ Project Office
#                        National Radio Astronomy Observatory
#                        520 Edgemont Road
#                        Charlottesville, VA 22903-2475 USA
#
# $Id$
#
set script = "UPsed"
set usage = 'Usage: UPsed [-f] <typ> <filename in> [<filename out>]'
#
# UPsed script (must have x allowed)
# Change a file according to a sed rule
#
# sed pattern will be in <typ>.sed file created by
#     sourcing <typ>.info if necessary
# file out will default to file in
# the <typ> can have directory information
#
# See UPinfo for details
#
#
# Get general info
#
if ($# < 1) then
    echo "$usage"
    exit (1)
endif

if ("$1" == "-f") then
    shift
    set arg = ($*)
else
   if (! $?AIPSPATH) then
      echo "No AIPSPATH environment set, initialize aips++ first"
      exit 1
   endif
   set x = "`which UPfind`"
   if (-x "$x") then
     set uppath = $x:h
   else
     set x = ( $AIPSPATH )
     set uppath = $x[1]/$x[2]/bin
   endif
   unset x
   if ("$uppath" == ".") then
     set uppath = `pwd`
   endif
   if (! -r $uppath/UPinfo) then
     echo "Cannot find the UPinfo source script in $uppath"
     echo "Check your aips++ installation"
   endif
   source $uppath/UPinfo
   if (! $ok) exit 1
endif
#
# Get specific data
#
if ($#arg < 2) then
    echo "$usage"
    exit (1)
endif

set tp = $arg[1]
set fin = $arg[2]
if ($#arg < 3) then
    set fout = $fin
else
    set fout = $arg[3]
endif

set tmp = $$
if (! -e $tp.sed) then
    echo "Cannot access $tp.sed"
    exit 1
endif

sed -f $tp.sed $fin >! $tmp.tmp

mv -f $tmp.tmp $fout

unset tmp

exit 0

##






