#!/usr/local/bin/tcsh
#-----------------------------------------------------------------------------
# UPtmpl script
#-----------------------------------------------------------------------------
# Copyright (C) 1999,2000
# Associated Universities, Inc. Washington DC, USA.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 675 Massachusetts Ave, Cambridge, MA 02139, USA.
#
# Correspondence concerning AIPS++ should be addressed as follows:
#        Internet email: aips2-request@nrao.edu.
#        Postal address: AIPS++ Project Office
#                        National Radio Astronomy Observatory
#                        520 Edgemont Road
#                        Charlottesville, VA 22903-2475 USA
#
# $Id$
#
set script = "UPtmpl"
set usage = 'Usage: UPtmpl [-c] [-r] [-d] [-n] <typ>'
#
# UPtmpl script (must have x allowed)
# Get all files in the tmplinst directories. 
# The file list will be in <typ>.tmpinst
#
# See UPinfo for details
#
# Get general info
#
if (! $?AIPSPATH) then
   echo "No AIPSPATH environment set, initialize aips++ first"
   exit 1
endif
set x = "`which UPfind`"
if (-x "$x") then
   set uppath = $x:h
else
   set x = ( $AIPSPATH )
   set uppath = $x[1]/$x[2]/bin
endif
   unset x
   if ("$uppath" == ".") then
   set uppath = `pwd`
endif
if (! -r $uppath/UPinfo) then
   echo "Cannot find the UPinfo source script in $uppath"
   echo "Check your aips++ installation"
endif
source $uppath/UPinfo
if (! $ok) exit 1
#
# Get specific data
#
if ($nox) exit 0 
#
# Get data
#
cd $dir/code
echo "Getting template file list..."
find . -name '*_????.cc' -print | \
     grep tmplinst \
     >! $ldir/${tp}.tmpinst
cd $ldir

set a = ( `wc ${tp}.tmpinst` )
echo $a[1] files found in ${tp}.tmpinst
unset a

exit 0
