import os

# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Clone()

apps =  myenv.SConscript(["%s/SConscript" % "apps"],
                         duplicate=0, exports=["buildenv", "installer"])

myenv["ASSAYAUX"] = myenv.SGlob("*/test/*.fits")
myenv["ASSAYAUX"] += myenv.SGlob("*/test/*.im")
myenv.CasaBuilder(installer=installer)
