import os, glob
import SCons.Defaults

# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Copy()
# get all the sourcefiles recursively
ffs = myenv.SGlob("*.f", recursive=False )
# need this to go to the root dir, as SConsript asumes to be in the
# build dir
rootdir=myenv.Dir("#").abspath
libname= "casa_" + myenv["PACKAGE"] + "_f"

slib =  myenv.StaticLibrary(target = libname, source = [ffs])
installer.AddLibrary(slib)
myenv.Alias(os.path.basename(os.path.normpath(str(slib[0]))), slib)
myenv.Alias("static", slib)
myenv.Default(slib)

dlib =  myenv.SharedLibrary(target = libname, source = [ffs])
installer.AddLibrary(dlib)
myenv.Alias(os.path.basename(os.path.normpath(str(dlib[0]))), dlib)
myenv.Alias("shared", dlib)
