#!/bin/sh
#-----------------------------------------------------------------------------
# ai_master: Check sources into the AIPS++ master repository
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1992-1996
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: ai_master [ci options] file RCSfile
#        ai_master directory
#-----------------------------------------------------------------------------
# Insert an AIPS++ source file into the master RCS repository with the correct
# file ownership.
#
# This script should reside in $AIPSMSTR on the AIPS++ master machine
# (aips2.nrao.edu) and be setuid to the owner of the AIPS++ master RCS version
# files (aips2adm).
#
# 'ai_master' should not be accessed directly, but via the 'ai' script in the
# $AIPSARCH/bin area which executes this.
#
# Status returns:
#    0:  success
#    1:  initialization error
#    2:  checkins are disabled or restricted
#    3:  checkin failed
#    4:  directory creation failed
#
# Original: 1992/04/28 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Fundamentals.
  if [ "$AIPSPATH" = "" ]
  then
     echo "ai_master: AIPSPATH is not defined, abort!" 1>&2
     exit 1
  fi

  AIPSROOT=`echo $AIPSPATH | awk '{ print $1 }'`

# Define AIPS++ directory names.
  AIPSMSTR=$AIPSROOT/master
  MSTRETCD=$AIPSMSTR/etc

# Are checkins disabled?
  if [ -f "$MSTRETCD/ai_disable" ]
  then
     if [ -s "$MSTRETCD/ai_disable" ]
     then
        cat $MSTRETCD/ai_disable
        echo ""
     fi

     echo "ai: Checkins are currently disabled, try again later." 1>&2
     exit 2
  fi

  if [ "$#" -gt 1 ]
  then
#    Create any new files if necessary.
     NEWFILE=
     for i
     do
        case $i in
        *,v)
           if [ ! -f "$i" ]
           then
#             Look for an access control list.
              MSTRDIR=`echo $i | sed -e 's#/[^/]*$##'`
              if [ -f "$MSTRDIR/.acl" ]
              then
                 MSTRSUBD=`echo $MSTRDIR | sed -e "s#^$AIPSMSTR/##"`
                 [ "$MSTRSUBD" = "" ] && MSTRSUBD="."
                 LOGNAME=${LOGNAME-$USER}
                 grep $LOGNAME $MSTRDIR/.acl > /dev/null 2>&1
                 if [ "$?" != 0 ]
                 then
                    echo "ai: File creation in $MSTRSUBD" \
                         "denied to $LOGNAME." 1>&2
                    exit 2
                 else
                    echo "ai: File creation in $MSTRSUBD" \
                         "permitted to $LOGNAME."
                 fi
              fi

              if [ ! -f "$MSTRDIR/.oc" ]
	      then
#                Validate the file name.
                 case $i in
                 *.cc,v | *.[hly],v)
                    AV=`av $i`
                    if [ "$AV" != "" ]
                    then
                       case $i in
                       $AIPSMSTR/$AV.cc,v | $AIPSMSTR/$AV.[hly],v)
                          AV=""
                          ;;
                       *)
                          exec 1>&2
                          echo "ai: The first 15 characters of filename match"
                          echo "    $AV"
                          exit 2
                          ;;
                       esac
                    else
#                      Create an addendum to the av cache.
                       trap 'echo "ai: Cleaning up..." ; \
                             rm -f $MSTRETCD/av_cache-$$.gz ; \
                             exit 3' 1 2 3 15
                       echo $i | \
                          sed -e "{s#^$AIPSMSTR/##;s#\..*,v##;}" | \
                          gzip > $MSTRETCD/av_cache-$$.gz
                       chmod 644 $MSTRETCD/av_cache-$$.gz
                    fi
                    ;;
                 esac
              fi

#             Create an empty RCS version file.
              RCSINIT="" rcs -I -i $i
              NEWFILE="$i"
           fi
           ;;
        esac
     done

#    Do the RCS check in.
     if [ "$1" != nofile ]
     then
        RCSINIT="" ci $*
        if [ "$?" != 0 ]
        then
           echo "ai_master: Checkin failed, abort!" 1>&2
           exit 3
        fi
     fi

#    Ensure that newly created files are world readable.
     [ "$NEWFILE" != "" ] && chmod ugo+r $NEWFILE

  else
#    Directory creation; look for an access control list.
     ACL=""
     MSTRDIR=`echo $1 | sed -e 's#/[^/]*$##'`
     if [ -f "$MSTRDIR/.acl" ]
     then
        MSTRSUBD=`echo $MSTRDIR | sed -e "s#^$AIPSMSTR/##"`
        [ "$MSTRSUBD" = "" ] && MSTRSUBD="."
        LOGNAME=${LOGNAME-$USER}
        grep $LOGNAME $MSTRDIR/.acl > /dev/null 2>&1
        if [ "$?" != 0 ]
        then
           echo "ai: Directory creation in $MSTRSUBD" \
                "denied to $LOGNAME." 1>&2
           exit 4
        else
           echo "ai: Directory creation in $MSTRSUBD" \
                "permitted to $LOGNAME."
        fi
        ACL=1
     fi

#    Barge ahead and try to create it.
     mkdir $1
     if [ "$?" != 0 ]
     then
        echo "ai_master: Directory creation failed, abort!" 1>&2
        exit 4
     fi

     chmod ug=rwx,g+s,o=rx $1

#    Propagate the access control list.
     [ "$ACL" != "" ] && ln -s ../.acl $1

#    Propagate .oc files too.
     [ -f "$MSTRDIR/.oc" ] && touch $1/.oc
  fi


  exit 0
