#!/bin/sh
#-----------------------------------------------------------------------------
# cvsmv: Move files or directories of files within the CVS repository
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1996,1999,2001
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: cvsmv [-nag] <source> <destination>
#-----------------------------------------------------------------------------
# cvsmv more a file or a directory full of files (though it is non-recursive),
# within the master CVS repository. The change history is preserved with BOTH
# the new copy and the deleted original. However, all tags are stripped from
# the new copy. This is done so that (1) history is preserved, (2) old states
# of the system can be retrieved using old tags, and (3) new tags do not
# affect the deleted files.
#
# Status returns:
#    0:  initialization succeeded
#    1:  initialization error
#
# Original: 1996/08/16 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Fundamentals.
#  if [ ! "$AIPSPATH" ]
#  then
#     echo "cvsmv: AIPSPATH is not defined, abort!" 1>&2
#     exit 1
#  fi

#  AIPSROOT=`echo $AIPSPATH | awk '{print $1}'`
#  AIPSCODE=$AIPSROOT/code

  
  SOURCE=
  DESTINATION=
  NEWAGENT=
# Check number of arguments.
  if [ $# -eq 2 ]
  then
     SOURCE=$1
     DESTINATION=$2
  elif [ $# -eq 3 ]
  then
     if [ $1 = "-nag" ]
     then
	NEWAGENT=YES
     else
	 echo "Usage: cvsmv [-nag] <source> <destination>" 1>&2
     fi
     SOURCE=$2
     DESTINATION=$3
  else
     echo "Usage: cvsmv [-nag] <source> <destination>" 1>&2
     exit 1
  fi

# Make sure we've got something sensible.
#  if [ ! -d "$AIPSCODE/$SOURCE" -a ! -f "$AIPSCODE/$SOURCE" ]
#  then
#      echo "cvsmv: source ($SOURCE) doesn't exist beneath code directory" 1>&2
#      exit 1
#  fi

  STARTED_AGENT=
  if [ -n "$NEWAGENT" -o -z "$SSH_AUTH_SOCK" ]; then
    eval `ssh-agent -s` > /dev/null
    trap 'ssh-agent -k > /dev/null 2>&1' 0 1 2 3 15
    STARTED_AGENT='YES'
    ssh-add
  else
    SSHID=`cat $HOME/.ssh/identity.pub | sed 's/.* \([^ ][^ ]*\)$/\1/'`
    if ! ssh-add -l | grep $SSHID > /dev/null 2>&1; then
        ssh-add
    fi
  fi

  REMOTE_USER="-l cvsmgr"

  ssh -q -C cvs.cv.nrao.edu $REMOTE_USER cvs MOVE $SOURCE $DESTINATION

  exit 0
