#!/bin/sh
#-----------------------------------------------------------------------------
# rao: Remotely check out AIPS++ sources
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1996-1997,1999,2000,2001
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: rao [ao options]
#-----------------------------------------------------------------------------
# rao is an ssh-based front-end to 'ao'.  It allows remote checkout of AIPS++
# sources by invoking 'ao' on the AIPS++ master machine.  This is provided as
# an alternative to invoking 'ao' directly on a machine on which the
# AIPS++ master directory is NFS mounted.
#
# In order to use rao an AIPS++ programmer must have an account on the AIPS++
# master host (aips2.nrao.edu) and it must be set up for 'ssh' access from the
# host on which rao is run.  The programmer must also have an up-to-date
# AIPS++ workspace on the master host rooted at $HOME/aips++.
#
# The files checked out are transferred from the master as a tar file.
#
# Options:
#    Refer to the options for 'ao'.
#
# Status returns:
#    0:  success (returned from ao_master)
#    1:  initialization error, no check out
#
# Notes:
#    1) Where the remote account name differs from the local account name an
#       environment variable may be used to translate between them:
#
#          AUID="<remotename>"
#    2) If you specify a key in your .ssh/authorized_keys files you will not
#       be prompted for a password
#
#
# Original: 1996/08/06 by Mark Calabretta, ATNF
# $Id$
#=============================================================================
# Check number of arguments.
  if [ $# = 0 ]
  then
     echo "Usage: rao (arguments for ao)"
     exit 1
  fi

# Get the work directory.
  PGMRDIR=`pwd | sed -e 's#.*/code/#code/#' -e 's#.*/code$#code#'`

# Make sure we've got something sensible.
  case "$PGMRDIR" in
  /*)
     echo "rao: Invalid work directory - `pwd`"
     exit 1
     ;;
  esac
  PGMRDIR=aips++/$PGMRDIR

# Get file names.
  FILES=""
  for i
  do
     case $i in
     -*)
        continue
        ;;
     esac
 
#    Allow wildcard checkout via an RCS symbolic link.
     i=`echo $i | sed -e 's#^RCS/##' -e 's#,v$##'`
 
     case $i in
        */*)
           continue
           ;;
 
        *)
	   if [ -f "$i" ]
	   then
	      if [ -w "$i" ]
	      then
		 printf "rao: Warning, $i is writable, continue (y/n) [n]: "
		 read ANSWER
		 affirm -o -s "$ANSWER" || exit 1
	      else
		 echo "rao: Removing unwritable copy of $i"
		 rm -f "$i"
	      fi
	   fi

           FILES="$FILES $i"
           ;;
     esac
  done

# The business end.
  REMOTE_USER=""
  if [ "$AUID" ]; then
     REMOTE_USER="-l $AUID"
  fi
  ARSH="ssh aips2.nrao.edu $REMOTE_USER"
  REMOTETAR=a.tmp.tar
  LOCALTAR=b.tmp.tar
  COMMAND="cd $PGMRDIR && rm -f $REMOTETAR && ao -I $* && tar cf $REMOTETAR $FILES && rm -f $FILES"
  $ARSH /aips++/weekly/.rshexec sh -c \'\""$COMMAND"\"\'
  rm -f $LOCALTAR
  if  $ARSH /aips++/weekly/.rshexec test -e $PGMRDIR/$REMOTETAR ; then
     scp -qpC  $AUID@aips2.nrao.edu:$PGMRDIR/$REMOTETAR $LOCALTAR
     tar xpvf $LOCALTAR > /dev/null 
     COMMAND="cd $PGMRDIR && rm -f $REMOTETAR"
     $ARSH /aips++/weekly/.rshexec sh -c \'\""$COMMAND"\"\'
     rm -f $LOCALTAR
  fi

  exit 0
