#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: runtests
#-----------------------------------------------------------------------------
# runtests runs the AIPS++ test programs and mails the results to the AIPS++
# email exploders.
#
# Options:
#   none
#
# Status returns:
#    0:  success
#    1:  initialization error
#
# Original: 1997/01/29 by Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------
# Fundamentals.
  if [ "$AIPSPATH" = "" ] ; then
     echo "runtests: AIPSPATH is undefined, abort!" 1>&2
     exit 1
  fi
 
  AIPSROOT=`echo $AIPSPATH | awk '{ print $1 }'`
  AIPSARCH=`echo $AIPSPATH | awk '{printf("%s/%s",$1,$2)}'`
  BINTESTD=$AIPSARCH/bintest
 
# Get the current version number.
  VERSION=`avers | awk '{printf("%.6s",$1)}'`

# Do it.
  {  exec 2>&1

     echo ""
     echo "runtests: $AIPSPATH"
     echo ""
     echo "runtests: Validating $VERSION."
 
#    Initiate the test suite, preserving the log.
     cd $AIPSROOT
     gmake -C code TESTOPT=opt NODEP=1 runtests > $BINTESTD/runtests.log 2>&1
 
     cd $BINTESTD
     FAILED=`grep 'FAIL (' runtests.report | wc -l`
     FAILED=`echo $FAILED`
     echo ""
     echo "runtests: Version $VERSION finished with $FAILED failures."
     echo ""
     echo "runtests: runtests summary and complete log are appended."
     echo ""
     cat $BINTESTD/runtests.report
     echo ""
     cat $BINTESTD/runtests.log
     echo $PATH

     # Create a total summary.
     rm -f $BINTESTD/runtests.summary
     echo "Summary of runtests for $AIPSPATH ($VERSION)" > $BINTESTD/runtests.summary
     echo "--------------------------------------" >> $BINTESTD/runtests.summary
     echo "" >> $BINTESTD/runtests.summary
     testsum.sh $AIPSARCH $BINTESTD/runtests.report 2>&1 | fgrep -A15 'Test results for ' | fgrep -B15 '*****' >> $BINTESTD/runtests.summary
     echo "" >> $BINTESTD/runtests.summary

     # Create a summary for each package (which must have an implement dir).
     # Do it only if the package occurs in the runtests output.
     for PKG in `ls $AIPSROOT/code`
     do
       PKGNM=`basename $PKG`
       if [ -d $AIPSROOT/code/$PKGNM/implement ]; then
         grep "${PKGNM}-" $BINTESTD/runtests.report > /dev/null 2>&1
         if [ $? = 0 ]; then
           echo "" >> $BINTESTD/runtests.summary
           testsum.sh $AIPSARCH $BINTESTD/runtests.report $PKGNM > $BINTESTD/runtests_$PKGNM.summary 2>&1
           # Append the number of failed, etc. to the total summary.
           fgrep -A15 'Test results for ' $BINTESTD/runtests_$PKGNM.summary | fgrep -B15 '+****' | fgrep -v '+****' >> $BINTESTD/runtests.summary
           # Append the failures.
	   fgrep -A10000000 '+****' $BINTESTD/runtests_$PKGNM.summary | fgrep -v '+****' | fgrep -B10000000 'Tests that passed' | fgrep -v 'Tests that passed' | egrep -B10000000 '[^ ]+' >> $BINTESTD/runtests.summary
	   echo "******************************************************************************" >> $BINTESTD/runtests.summary
         fi
       fi
     done
  } > $BINTESTD/runtests.rptNlog

  exit 0
