#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the tHashMap functions.  All files generated will be deleted
# on exit.
#=============================================================================
# Define exit and interrupt handler.
  trap 'rm -rf tHashMap_* words ; \
        trap 0 ; \
        exit $STATUS' 0 1 2 3 4 15

  if test ! -f ./words; then
     if test -f ./words.gz && gunzip -c ./words.gz > words; then :
     else
        echo "FAIL (output not verified): tHashMap"
        STATUS=4
        exit
     fi
  fi
        
  if test ! -f ./words; then
     echo "FAIL (output not verified): tHashMap"
     STATUS=4
     exit
  fi

  if tHashMap | egrep -v '^size:' > tHashMap_out; then
     if diff tHashMap_out tHashMap.out; then
        echo "PASS (output verified): tHashMap"
        STATUS=0
        exit
     else
        echo "FAIL (output not verified): tHashMap"
        STATUS=2
        exit
     fi
  else
     echo "FAIL (execution failure): tHashMap"
     STATUS=1
     exit
  fi
