#!/bin/sh
#-----------------------------------------------------------------------------
# assay: Invoke an AIPS++ test program and verify its output
#-----------------------------------------------------------------------------
#
#   Copyright (C) 1995,1996,1998,1999,2001,2003
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#-----------------------------------------------------------------------------
# Usage: assay <testexe and arguments>
#-----------------------------------------------------------------------------
# assay invokes an AIPS++ test program.  If the test program has an associated
# .run file then it simply invokes it.  Otherwise assay invokes the test
# executable directly, and, if there is a corresponding .out file, compares
# its output with that.
#
# If there is a .in file associated with the test program then assay will
# redirect stdin from it.
#
# assay recognizes Glish test scripts via their .g suffix and invokes glish
# on them.
# Similarly Python test scripts are recognized via their .py suffix.
#
# Options:
#   none
#
# Status returns:
#    0:  success
#    1:  test execution failed
#    2:  test output disagreement
#    3:  untested (usually returned from a .run)
#  130:  interrupt
#
# Notes:
#    1) It is assumed that the test executable exists in the current PATH.
#       If an environment variable called ASSAYBIN exists then ".:$ASSAYBIN"
#       is added to the start of PATH.  The AIPS++ system bintest directory is
#       always appended to PATH.
#       If an environment variable ASSAYPY exists, it is added to PYTHONPATH.
#
# Original: 1995/11/01 by Mark Calabretta, ATNF
# $Id: assay,v 19.11 2006/10/17 03:41:50 gvandiep Exp $
#=============================================================================
# Also set PYTHONPATH.
  if [ "$PYTHONPATH" = "" ]
  then
     PYTHONPATH=.
  else
     PYTHONPATH=".:$PYTHONPATH"
  fi
  CLEANUP=

# Define exit and interrupt handler.
  trap 'rm -rf $CLEANUP core ${1}_tmp* ; \
        trap - 0 ; \
        exit $STATUS' 0 1 2 3 15

# Check if command is a glish or python script.
  COMMAND="$@"
  SCRIPTUSED=0
  set $@

# If there is a .run file then use it.
# Note that in this way the run file is used if there is a .run and .py file.
# Still the .py file is copied and removed as needed, so the .run file
# can use the .py file.
  if [ -f "$1.run" ]
  then
     COMMAND="sh $1.run"
     SCRIPTUSED=1
  fi

# If there is a .in file then use it as input.
  if [ -f "$1.in" ]
  then
     COMMAND="$COMMAND < $1.in"
  fi

  # If running on a Cray cluster, we have to use qsub and yod.
  # If found, the result is a path, thus starts with a slash.
  QSUBP=`which qsub 2>&1 | sed -e 's%^[^/].*%%'`
  YODP=`which yod 2>&1 | sed -e 's%^[^/].*%%'`
  if [ "$QSUBP" = ""  -o  "$YODP" = "" ]
  then
    # No Cray.
    eval "$COMMAND" > ${1}_tmp.out
    STATUS=$?
    if [ $STATUS != 0 ]
    then
      if [ $STATUS = 3 ]
      then
        echo "UNTESTED: $*"
      else
        echo "FAIL (execution failure): $*"
      fi
      exit
    fi
  else
    # .run files are not supported yet on the Cray.
    if [ -f "$1.run" ]
    then
      echo "UNTESTED (no .run support): $*"
      exit 3
    fi
    # Create a batch job which will use a single processor.
    # Copy the AIPSPATH definition.
    # Because the job does not wait, we do that by using a wait file.
    # Note that yod does wait.
    rm -f $1_tmp.wait
    cat > $1_tmp.qsub <<EOF
#PBS -l size=1
#PBS -N $1_tmp_job
#PBS -j oe
#PBS -v AIPSPATH
cd \$PBS_O_WORKDIR
yod -sz 1 ./$1 > $1_tmp.out
touch $1_tmp.wait
EOF
    # Submit the job and wait for it to be finished.
    # Do not wait longer than 10 minutes.
    qsub $1_tmp.qsub
    NRTIMES=0
    while [ ! -f $1_tmp.wait ]
    do
      if test $NRTIMES -gt 600
      then
        # Keep job file.
        mv $1_tmp_job  $1_job
        echo "FAIL (execution killed): $*"
        exit 1
      fi
      sleep 1
      NRTIMES=`expr $NRTIMES + 1`
    done
  fi

  if [ -f $1.out ]
  then
     CAT="$1.out"
  else
     echo "PASS (execution succeeded): $*"
     STATUS=0
     exit
  fi

# Strip out demarked text.
  sed -e '/^>>>/,/^<<</d' ${1}_tmp.out > ${1}_tmp.out2
  mv -f ${1}_tmp.out2 ${1}_tmp.out

# Compare with the expected output.
  cat "$CAT" | sed -e '/^>>>/,/^<<</d' > ${1}_tmpo.out
  if diff ${1}_tmp.out ${1}_tmpo.out
  then
     echo "PASS (output verified): $*"
     STATUS=0
     exit
  fi
  # Not fully equal, check if equal except for numbers.
  # Replace for this purpose all numbers by x.
  sed -e 's/[+-]\?\(\(\([0-9]\+\)\|\([0-9]*\.\?[0-9]*\)\)\(e[+-]\?[0-9]\+\)\?\)/x/g' ${1}_tmp.out > ${1}_tmp.out2
  sed -e 's/[+-]\?\(\(\([0-9]\+\)\|\([0-9]*\.\?[0-9]*\)\)\(e[+-]\?[0-9]\+\)\?\)/x/g' ${1}_tmpo.out > ${1}_tmpo.out2
  diff ${1}_tmp.out2 ${1}_tmpo.out2 > /dev/null 2>&1
  if [ $? != 0 ]
  then
     echo "FAIL (output not verified): $1"
     STATUS=2
     exit
  fi
  if floatcheck.sh ${1}_tmp.out ${1}_tmpo.out 1e-5
  then
     echo "PASS (floating point discrepancies <= 1e-5): $1"
     STATUS=0
     exit
  fi
  echo "FAIL (floating point discrepancies > 1e-5): $1"
  STATUS=2
  exit
