#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the RecordGram class for a table
#=============================================================================

$casa_checktool ./tRecordGramTable "ab"
$casa_checktool ./tRecordGramTable "ac"
$casa_checktool ./tRecordGramTable "ad"
$casa_checktool ./tRecordGramTable "ae"
$casa_checktool ./tRecordGramTable "af"
$casa_checktool ./tRecordGramTable "ag"
$casa_checktool ./tRecordGramTable "ab>4"
$casa_checktool ./tRecordGramTable "ab+ac"
$casa_checktool ./tRecordGramTable "arr1[1,1,1]+1"
$casa_checktool ./tRecordGramTable "max(arr1)"
$casa_checktool ./tRecordGramTable "arr1"
