import os

# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Copy()

# gather c files
cs = myenv.SGlob("*.c")

slib =  myenv.StaticLibrary(target = "casa_"+myenv["PACKAGE"], source = cs)
myenv.Alias(os.path.basename(os.path.normpath(str(slib[0]))), slib)
myenv.Alias("static", slib)
myenv.Default(slib)
installer.AddLibrary(slib)

dlib =  myenv.SharedLibrary(target = "casa_"+myenv["PACKAGE"], source = cs)
myenv.Alias(os.path.basename(os.path.normpath(str(dlib[0]))), dlib)
myenv.Alias("shared", dlib)
installer.AddLibrary(dlib)
