#!/bin/sh

if [ ${#AIPSPATH} = 0 ]
then 
   echo "UNTESTED: tVisibilityIterator (AIPSPATH not defined)"
   exit 3
fi

DATADIR=`echo $AIPSPATH | awk '{print $1}'`/data/demo/

if [ ! -d $DATADIR/autoflag/WSRT-test.MS2 ]; then
   echo "UNTESTED: tVisibilityIterator, could not find the test data" $DATADIR/autoflag/WSRT-test.MS2 
   exit 3;
fi
rm -rf tVisibilityIterator.MS
# MS might get changed, so copy it first.
cp -r $DATADIR/autoflag/WSRT-test.MS2 tVisibilityIterator_tmp.MS 
./tVisibilityIterator tVisibilityIterator_tmp.MS
