#! /bin/sh
#-----------------------------------------------------------------------------
# Script to execute the tRegularFile program via assay.
# It defines a few files, etc. to make the program work in any environment.
# Execution:
#     tRegularFile.exec      execute using assay (normal procedure)
#     tRegularFile.exec 0    only define the subdirectory, etc. (for debugging)
#     tRegularFile.exec 1    execute as such (to test)
#     tRegularFile.exec 1 1  execute without exceptions (to test leakage)
#=============================================================================

/bin/rm -rf tRegularFile_tmp
mkdir tRegularFile_tmp

mkdir tRegularFile_tmp/moveto
ls > tRegularFile_tmp/isFile
ls tRegularFile_tmp > tRegularFile_tmp/isFile1
ln -s isFile1 tRegularFile_tmp/isLink
ln -s isLink tRegularFile_tmp/isLink1
ln -s $HOME tRegularFile_tmp/isLink2

# Wait a second to be sure new times will be greater.
sleep 1        

if [ $# != 0 ]
then
    if [ $1 != 0 ]
    then
        tRegularFile $2
    fi
else
    exec assay tRegularFile
fi
