#!/bin/sh
#-----------------------------------------------------------------------------
# Script to invoke tGenSort and verify its output.
#=============================================================================

exec assay tGenSort "2500 1 && \
     tGenSort 2500 2 && \
     tGenSort 2500 4 && \
     tGenSort 2500 9 && \
     tGenSort 2500 10 && \
     tGenSort 2500 12 && \
     tGenSort 2500 1 desc && \
     tGenSort 2500 2 desc && \
     tGenSort 2500 4 desc && \
     tGenSort 2500 9 desc && \
     tGenSort 2500 10 desc && \
     tGenSort 2500 12 desc"
