name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dist:
          - ubuntu1804_clang
          - ubuntu1804_gcc
          - ubuntu2004_clang
          - ubuntu2004_gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build container
        run: docker build . -t ${{ matrix.dist }} -f .github/workflows/${{ matrix.dist }}.docker
