import os, glob

# import root environment
Import( ["buildenv", "installer"])
myenv = buildenv.Clone()

apps =  myenv.SConscript(["%s/SConscript" % "apps"],
                         duplicate=0, exports=["buildenv", "installer"])

myenv.CasaBuilder(installer=installer)

